### ISSUE TITLE
Compile task fails with latest xsbt

### ISSUE THREAD

**Issue by aolshevskiy** [sbt/sbt#10]
Here is the console output:
    % xsbt
    Getting net.java.dev.jna jna 3.2.3 ...
    :: retrieving :: org.scala-tools.sbt#boot-app
        confs: [default]
        1 artifacts copied, 0 already retrieved (838kB/16ms)
    Getting Scala 2.8.1 ...
    :: retrieving :: org.scala-tools.sbt#boot-scala
    confs: [default]
    4 artifacts copied, 0 already retrieved (15296kB/38ms)
    Getting org.scala-tools.sbt sbt_2.8.1 0.9.3-SNAPSHOT ...
    :: retrieving :: org.scala-tools.sbt#boot-app
        confs: [default]
    33 artifacts copied, 0 already retrieved (5526kB/98ms)
    [info] Set current project to default (in build file:/home/siasia/projects/test/)
    > compile
    [info] Updating...
    [info] Done updating.
    [error] Incomplete task(s):
    [error](file:/home/siasia/projects/test/)default/compile:  java.lang.NoSuchMethodError: sbt.CompileOptions.<init>(Lscala/collection/Seq;Lscala/collection/Seq;)V
    [error] Run 'last <task>' for the full log(s).
    [error] Total time: 1 s, completed 04.04.2011 19:38:31
    >

Looks like it's related to you latest commit of Java, Scala compile order support.

**Comment by harrah** [comment]
Should be fixed now.
