### ISSUE TITLE
Document the current ways to sequence tasks

### ISSUE THREAD

**Issue by mighdoll** [sbt/sbt#1000]
The nifty new macro syntax makes it easy to write a task that triggers subtasks.  It's tempting to write code like this:

```
runRemote := {
   val stopped = stop.value
   val deployed = deploy.value
   val started = start.value
   val launched = launch.value
}
```

and expect that the subtasks would run in sequential order.  (Unfortunately, the tasks might
run in sequential order sometimes, which will surely confuse the unwary.)

The documentation should clarify that tasks will generally run concurrently, possibly as [tasks are introduced in the docs](http://www.scala-sbt.org/0.13.0/docs/Getting-Started/Custom-Settings.html) and certainly as [tasks are discussed in detail](http://www.scala-sbt.org/0.13.0/docs/Detailed-Topics/Tasks.html).

On the detail page, I'd suggest explaining one or more ways to control task sequencing.
I think there are a few..
- use the output of one task as the input to another
- arrange a string of dependsOn calls between the subtasks
- arrange a chain of taskDyn calls
- execute them within a Command via runTask

Task sequencing seems to come up around integration tests, so I'd suggest using that as an example.

Eugene also [brought this up](https://groups.google.com/forum/#!topic/simple-build-tool/1c7unObqjJ8).

**Comment by eed3si9n** [comment]
http://www.scala-sbt.org/0.13/docs/Howto-Sequencing.html

**Comment by gavares** [comment]
@eed3si9n Thanks for adding these pages. In the last section "How to sequence using commands",
the example you've provided doesn't seem to compile for me. The compiler claims that `::` is not defined on String.

I tried adding `:: Nil` to the end of the sequence thinking that you were building a List but this sort of expression has no effect. The List is generated but the net-effect of the Command is a no-op.

Am I misunderstanding something?
