### ISSUE TITLE
New TrapExit implementation in 0.13.1 prints UncaughtExceptionHandler message

### ISSUE THREAD

**Issue by SethTisue** [sbt/sbt#1017]
in the part of my build where I actually use TrapExit, 0.13.1-RC5 (and RC3 and RC2) now prints `Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "run-main-0"`

nbd, the extra output isn't causing any trouble, but reporting anyway. I can isolate/minimize if desired

**Comment by harrah** [comment]
Yes, a minimized test case would be appreciated.  A naive test case doesn't show the problem, so presumably it is something involving how the threads are created.  Thanks.

**Comment by SethTisue** [comment]
build.sbt:

``` scala
val depend = taskKey[Unit]("")

depend := {
  TrapExit(
    classycle.dependency.DependencyChecker.main(Array()),
    streams.value.log)
}
```

project/plugins.sbt:

``` scala
libraryDependencies +=
  "classycle" % "classycle" % "1.4.1" from
    "http://ccl.northwestern.edu/devel/classycle-1.4.1.jar"
```

gives:

``` text
> depend
Usage: java -cp classycle.jar classycle.DependencyChecker -dependencies=<description>|@<description file> [-renderer=<fully qualified class name of a ResultRenderer>] [-mergeInnerClasses] [-includingClasses=<pattern1>,<pattern2>,...] [-excludingClasses=<pattern1>,<pattern2>,...] [-reflectionPattern=<pattern1>,<pattern2>,...] <class files, zip/jar/war/ear files, or folders>

Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "run-main-0"
[success] Total time: 0 s, completed Dec 2, 2013 7:08:50 PM
```

but this still involves invoking 3rd-party code (Classycle). let me look at the Classycle code and see what they're doing, but it's probably not much, since we're not getting past their "Usage: " message

**Comment by SethTisue** [comment]
All that Classycle is doing is this, from http://sourceforge.net/p/classycle/code/HEAD/tree/trunk/Classycle/src/classycle/dependency/DependencyChecker.java#l94 :

``` java
public static void main(String[] args)
  {
    DependencyCheckerCommandLine commandLine 
        = new DependencyCheckerCommandLine(args);
    if (!commandLine.isValid()) {
      System.out.println("Usage: java -cp classycle.jar "
                         + "classycle.DependencyChecker "
                         + commandLine.getUsage());
      System.exit(1);
    }
```

is this isolated/minimized enough, or should I keep going...? (what's your naive test case look like?)

**Comment by harrah** [comment]
That would be enough if it showed the problem for me.  It does not, but perhaps it is os-specific so I will check on the mac later.

**Comment by SethTisue** [comment]
I'm on Mac OS X 10.9.

**Comment by mslinn** [comment]
I have a program that calls sys.exit(-1) and it generates the same error message when running under sbt 0.13.1. (Linux Saucy Salamander)

**Comment by SethTisue** [comment]
let's reopen this if someone can confirm that the problem still exists in sbt 1.1.1 or newer
