### ISSUE TITLE
scala.reflect.internal.MissingRequirementError

### ISSUE THREAD

**Issue by mathieuleclaire** [sbt/sbt#1028]
Hi, 
I compile and publish locally a sbt plugin (called janet) with sbt 0.13 and scala 2.10.3. I also get a dependency on scala.reflect, version 2.10.3. This project compiles fine and everything is publish properly.

The problem occurs when I use that plugin in an other sbt project (with same sbt and scala versions). It compiles but at runtime, I get the following class missing. I read some topics about this but without clear answer on what occurs. 

scala.reflect.internal.MissingRequirementError: class org.apache.ivy.util.url.HttpClientHandler in JavaMirror with scala.tools.nsc.util.ScalaClassLoader$URLClassLoader@1d4b7e38 of type class scala.tools.nsc.util.ScalaClassLoader$URLClassLoader with classpath [...] is not found

**Comment by mathieuleclaire** [comment]
Any hint about this error ?

**Comment by harrah** [comment]
Please use StackOverflow for support: https://github.com/sbt/sbt/blob/0.13/CONTRIBUTING.md#new-issues.  The bug tracker is best used as a todo list or record of known bugs.
