### ISSUE TITLE
Problem with loading spring application context during test

### ISSUE THREAD

**Issue by kgrodzicki** [sbt/sbt#103]
Hi, 

I have an issue with loading spring application context configuration file during tests:

``` scala
def loadConf() {
  val context = new ClassPathXmlApplicationContext("context.xml", this.getClass);
}
```

will give FileNotFoundException(the test class and xml is located in the same directory)

Adding full path to configuration file solve the problem:

``` scala
val context = new ClassPathXmlApplicationContext("file:src/test/scala/myApp/context.xml");
```

Is this a bug or I am missing some sbt configuration? 

Best,
Krzysiek
@kgrodzicki

**Comment by harrah** [comment]
Please use the mailing list for questions.
