### ISSUE TITLE
SBT 0.13 expects plugin artifacts on wrong path on Maven Central

### ISSUE THREAD

**Issue by axelfontaine** [sbt/sbt#1047]
The general convention for Jar artifacts on Maven Central is

repo/groupId/artifactId/version/artifactId-version.jar

With an SBT 0.13 plugin, SBT now looks for

repo/groupId/artifactId_2.10_0.13/version/artifactId-version.jar

whereas to stay consistent and compatible with other tools, this really should be

repo/groupId/artifactId_2.10_0.13/version/artifactId_2.10_0.13-version.jar

**Comment by axelfontaine** [comment]
Any news about this?

**Comment by jsuereth** [comment]
If you'd like to examine the issue, feel free to take a look.  Most plugins are currently targeted at Ivy repositories, particularly the bintray repo:  http://repo.scala-sbt.org/sbt-plugin-releases

While we want to remain maven-friendly, there was some insidiuous (and unremembered) reason why we couldn't get the ivy extra-attribute feature working on maven repositories.   This is one of the artifacts of that.   Generally, you should still be able to use sbt plugins on maven central, which was our initial goal.

If you need any help looking into how to improve the maven-situation, please let us know.

**Comment by dwijnand** [comment]
I would say that we can only change this in a new major version of sbt (so sbt 2.x). But until we have some concrete reasons as to why we should change this, I'll close off the issue.
