### ISSUE TITLE
The sbt launcher and custom character sets

### ISSUE THREAD

**Issue by huntc** [sbt/sbt#1052]
In the course of writing a plugin I may have discovered an issue regarding the use of custom character sets and the sbt launcher.

My plugin depends on a library that requires some custom character sets. The library correctly declares the requisite service provider interfaces.

If I run main code on the library within sbt using "fork in Run" then all is well. However if I do not fork, for example in my plugin's unit tests or use my plugin on another project, then there are problems loading the custom character set.

On further investigation I discovered the following code in the JDK:

http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/java/nio/charset/Charset.java#326

Charset locates the service providers of custom character sets via the system class loader. In the case of a plugin's regular execution, and for my unit tests, I believe that the system class loader is that of the sbt-launcher.jar.

I cannot determine a work-around that permits me to use custom character sets via the service provider interface of the JDK.

**Comment by jsuereth** [comment]
Anything that requires the system classloader breaks any container from
using it, without hacky workarounds.

There are a few potential solutions, we should discuss:

1) the start script has a mechanism to include additional jars when
starting sbt.  Thesr may be shaded by our loader.
2) use the ext/ directory of the jvm.  Evil.
3) get the jvm to use the context classloader.  May take forever
4) force users to fork.

**Comment by huntc** [comment]
Thanks @jsureth. None of those options are viable for sbt plugins that have a custom char set requirement; other than lobbying for a JDK change (which won't help with JDK 6 I suspect).

I might try to get the library I'm using to avoid custom char sets in the way it is.

I suppose though that this really is a JDK issue in the end. On reflection I'll consider raising the issue there as it doesn't feel like we can work around this via sbt.

Thanks.
