### ISSUE TITLE
SBT script on Mac is deficient

### ISSUE THREAD

**Issue by mslinn** [sbt/sbt#1053]
I installed sbt on Mavericks via brew and again with port, and each time I found that the sbt script is much less capable than the sbt script installed on Linux using apt-get. For example, the -mem option is not supported by the Mac versions of the sbt script.

**Comment by jsuereth** [comment]
We don't support either brew or Port _directly_.  We provide our script in downloadable tgz/zip files that these systems can use.  You should open a ticket against the port or brew packages directly and perhaps point them here:  https://github.com/sbt/sbt-launcher-package.

**Comment by mslinn** [comment]
One possible workaround might be to copy in the sbt script from this project and modify it. What is the original source file(s) for the sbt script found on Linux?

**Comment by jsuereth** [comment]
https://github.com/sbt/sbt-launcher-package/blob/full-packaging/src/universal/bin/sbt

You can also download the tgz from here: http://repo.scala-sbt.org/scalasbt/sbt-native-packages/org/scala-sbt/sbt/0.13.1/sbt.tgz

Like I said, the brew/port issues should be opened at their respective ticket managers.

**Comment by mslinn** [comment]
http://mikeslinn.blogspot.com/2013/12/mac-sbt-missing-scripts.html
