### ISSUE TITLE
Suggested improvement for unversioned global SBT directory warning

### ISSUE THREAD

**Issue by mslinn** [sbt/sbt#1054]
If you do not create a ~/.sbt/0.13/ directory, SBT 0.13+ runs in compatibility mode, and issues this warning that suggests you should create the directory:

```
[warn] The global sbt directory is now versioned and is located at /Users/mslinn/.sbt/0.13.
```

The sentence actually says the opposite of what was intended. A better wording might be:

```
There is no versioned global SBT directory. If you want to make one, you could put it at ~/.sbt/0.13/
```

Also, I suggest that this be removed:

```
[warn]   The global sbt directory may be changed via the sbt.global.base system property.
```

Changing sbt.global.base leads to confusion and is rarely needed. SBT is complicated enough without encouraging users to stray from the straight and narrow path.

**Comment by jsuereth** [comment]
Pull request welcome.

**Comment by eed3si9n** [comment]
The relevant code for it is at https://github.com/sbt/sbt/blob/43607b0c4051a014bdcf6d5b274aa10304809eae/main/src/main/scala/sbt/BuildPaths.scala#L126-L130
