### ISSUE TITLE
Prevent loading a project with the wrong version of sbt

### ISSUE THREAD

**Issue by jrudolph** [sbt/sbt#1055]
This situation arises if someone tries to use `reload` after having changed `build.properties`. As it's probably harder/impossible to fix taking `build.properties` into account when running `reload` sbt could at least refuse to load when the sbt.version in `build.properties` doesn't match the current runtime version.

**Comment by harrah** [comment]
Note that `reboot` is the command that indicates you want to completely restart sbt and reread `build.properties`.  This throws away pretty much everything, so it shouldn't be run unless it is actually needed.  `reload` could perhaps see if `build.properties` has changed and run `reboot` if it did, but I don't know whether that is a good idea.

**Comment by jozic** [comment]
`reload` could emit a warning if `build.properties` has changed and recommend to run`reboot` explicitly

**Comment by jsuereth** [comment]
That seems most reasonable
