### ISSUE TITLE
Provide scaladoc for DefinableSetting functions

### ISSUE THREAD

**Issue by metasim** [sbt/sbt#1057]
Provide scaladoc for [DefinableSetting](http://www.scala-sbt.org/release/api/index.html#sbt.Scoped$$DefinableSetting) functions `<<=`, `?:`, `??`, `or`. Their purpose isn't evident from their spelling alone.

**Comment by jsuereth** [comment]
Pull requests more than welcome!

Also, besides `<<=` and `??`, the rest are little used.  `<<=` and `:=` are equivalent functions, but at different API levels.   Next time I'm swinging through API doc fixes, I'll make sure to hit this, unless someone else beats me to it.

**Comment by metasim** [comment]
Associated pull request is #1115.
