### ISSUE TITLE
keys defined in *.sbt cannot be rewired via set command

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#1059]
Originally reported as:
- https://twitter.com/xuwei_k/status/371176463334010881 by @xuwei-k
- http://stackoverflow.com/questions/20896393/why-set-cant-assign-value-to-custom-settingkey-i-can-show-in-sbt-shell by @SethTisue
## steps

In `build.sbt`:

``` scala
val startServer = taskKey[Unit]("start server.")

startServer := {
  println("start")
}
```

Then from shell:

```
> set startServer := ()
```
## problem

```
> set startServer := ()
<set>:1: error: not found: value startServer
startServer := ()
^
[error] Type error in expression
```
## expectation

`set` command rewires the setting for `startServer`.
## note

[0.13 changes](http://www.scala-sbt.org/0.13.0/docs/Community/ChangeSummary_0.13.0.html#sbt-format-enhancements):

> All definitions are compiled before settings, but it will probably be best practice to put definitions together. Currently, the visibility of definitions is restricted to the .sbt file it is defined in. They are not visible in `consoleProject` or the `set` command at this time, either.

**Comment by eed3si9n** [comment]
@xuwei-k reminded me that the limitation has been mentioned in 0.13.0 changes. Is this too hard to fix?

**Comment by harrah** [comment]
I don't remember exactly the issues, but it is probably not too hard to put the enclosing modules on the classpath and import them.  It might be the class loading that is hard- I think each `.sbt` gets its own class loader.  You can write a class loader that will load from multiple parents (sbt has a dual loader), but it does complicate things.  If you are interested in addressing this, I can give more pointers or answer any questions you come up with.

**Comment by jsuereth** [comment]
yeah, I'd love to see this fixed sometime.  It currently limits the utility of `build.sbt`

**Comment by xuwei-k** [comment]
#1456

**Comment by everson** [comment]
I am also having this issue when using a Build.scala if the SettingKey is defined in another object and then imported into the build.

**Comment by jsuereth** [comment]
you need to fully qualify the key in that case, the way you would in Scala.

**Comment by everson** [comment]
Thanks!
