### ISSUE TITLE
clean should not delete target directories and only remove contents

### ISSUE THREAD

**Issue by cosm1c** [sbt/sbt#106]
Low priority enhancement to change the clean task so that it does not delete the target directories but only their contents (including subdirectories therein).

Deleting and recreating the target directory has some unfortunate side effects:
- causes IDEs to lose any settings against that directory (eg: setting the directory to "Derived" in Eclipse IDE)
- doesn't work correctly with symbolic links (I symlink my target directories to a separate location that is not periodically backed up)

**Comment by Blaisorblade** [comment]
Subdirectories of the target directory should still be removed - see #387.

**Comment by hsn10** [comment]
there is another problem that sometimes build fails on windows if it can not remove target directory because other process has it open

**Comment by fommil** [comment]
:+1: this means we have to add lots of crazy workarounds to ensime. sorry, should have subscribed far sooner.

**Comment by fommil** [comment]
I think the presentation compiler might not like directories being deleted beneath it... seeing some weird behaviour.

**Comment by fommil** [comment]
shouldn't this be a simple fix? @eed3si9n if you can point me at the part of the code that actually does the `.delete()` on the `File` I'll even send you that PR you've always wanted :-P

**Comment by eed3si9n** [comment]
@fommil If we're not careful the fix could introduce a really bad perf issue on your favorite filesystem.

**Comment by fommil** [comment]
@eed3si9n just deleting the files (never deleting directories) should be sufficient, or have you seen something different?

I can imagine that **moving** the top level directory on windows would give a big performance boost... but Java 6 doesn't support that operation.

**Comment by fommil** [comment]
(but then, see #2293 for thoughts on Windows performance...)

**Comment by fommil** [comment]
hmm, I may be wrong http://docs.oracle.com/javase/6/docs/api/java/io/File.html#renameTo(java.io.File)

From an ENSIME perspective, we'd just like it if the `target/scala-2.11/classes` directory was never shifted out. So if subfolders of _that_ could be moved away, that would be ideal. It's got to do with the way the Apache VFS folders handle root directories that they are watching.

**Comment by dwijnand** [comment]
@fommil see #2136

**Comment by eed3si9n** [comment]
Looks like this has been fixed. I can symlink target and it survives clean.
