### ISSUE TITLE
assertion failed: When `nameHashing` is disabled `names` relation should be empty: $names

### ISSUE THREAD

**Issue by OlegYch** [sbt/sbt#1071]
using 0.13.2-M1 with incOptions := incOptions.value.withNameHashing(true)
i get the error on incremental compilation
last doesn't show  stacktrace for some reason

**Comment by gkossakowski** [comment]
What about `last compile`?

Also, I assume you did run `clean` after turning on name hashing, right?

**Comment by OlegYch** [comment]
same for 'last compile' and 'last tehproject/compile:compile' , yes i did clean all projects
the tehproject contains one single source file (which was not modified in any way) and doesn't depend on any other subprojects btw

**Comment by gkossakowski** [comment]
It's really strange. Can you share this project or reproduce it in a sample project so I can have a look into it?

**Comment by OlegYch** [comment]
i'll try to minimize it but it was too weird and spurious, so can't promise anything

**Comment by gkossakowski** [comment]
Thanks a lot! Is your project a Play project or just a plain sbt project?

Also, it's really strange if this problem is not deterministic. The whole incremental compiler is deterministic.

**Comment by gkossakowski** [comment]
Hi @OlegYch! Did you have a chance to minimize a sample reproducing this problem?

**Comment by OlegYch** [comment]
sorry, i haven't managed to minimize it yet
will try again over the weekend
that's not a play project btw

**Comment by OlegYch** [comment]
dunno, really
when i start minimizing it goes away and doesn't come back even if you do clean
but it randomly comes back later
even when i do clean checkout and compile it reappears
i'm not using macros or anything like that..

**Comment by gkossakowski** [comment]
Actually, I finally reproduced it deterministically. The way to reproduce is very simple. Create a project with just one source file:

``` scala
// Foo.scala
class Foo
```

then:
1. Enable `nameHashing`
2. Run `compile`
3. Restart sbt (this is important)
4. Run `compile` again

It will crash with the error from this ticket. You could observe that (non-deterministically) without restarting sbt if GC happened to clean hacky Analysis cache we have. See #1081 for details.
