### ISSUE TITLE
Release milestone sbt-launch.jar

### ISSUE THREAD

**Issue by hanxue** [sbt/sbt#1075]
Can you please release sbt-launch.jar for major miletones? At the moment, there are only daily releases at http://repo.typesafe.com/typesafe/ivy-snapshots/org.scala-sbt/sbt-launch/0.13.2-20140112-062314/

The github releases contain the whole source directory. Would be nice to have milestone specific sbt-launch.jar instead of building it on our own. Thank you.

**Comment by jsuereth** [comment]
It's already there: http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.2-M1/

Milestones go in the releases directory as they will not change.
