### ISSUE TITLE
Do not use `macro` as identifier in sbt code base

### ISSUE THREAD

**Issue by gkossakowski** [sbt/sbt#1077]
Use of `macro` as an identifier has been deprecated in Scala 2.10 and will be prohibited in Scala 2.11.

We should inspect sbt code base and get rid of uses of `macro` as an identifier. For example, we'll need to update:
- `sbt/src/sbt-test/source-dependencies/macro`
- `sbt/src/sbt-test/source-dependencies/macro-name-hashing`

scripted tests. Nonetheless, the whole code base should be grepped.

**Comment by jsuereth** [comment]
Has this been fixed?  Just curious.

**Comment by gkossakowski** [comment]
Nope. I didn't touch it and I don't plan to do it this week. I'll unassign from myself to enable work stealing.

**Comment by dwijnand** [comment]
Given the 1.0.x branch is successfully building on Scala 2.11, whatever changes _needed_ to be done, must've been done.
