### ISSUE TITLE
exportJars = true thwarts incremental recompilation

### ISSUE THREAD

**Issue by retronym** [sbt/sbt#108]
I was trying out this setting to test out some code that displays the version from the JAR manifest within my app.

I noticed that a full recompilation is triggered in any module that depends on an exported JAR.

```
> last analytics-finance-basics/compile
[debug] 
[debug] Initial source changes: 
[debug]     removed:Set()
[debug]     added: Set()
[debug]     modified: Set()
[debug] Removed products: Set()
[debug] Modified external sources: Set()
[debug] Modified binary dependencies: Set(E:\code\analytics\analytics-math\target\scala-2.9.0.1\analytics-math_2.9.0-1-0.3-SNAPSHOT.jar)
[debug] Initial directly invalidated sources: Set()
```

Perhaps the dependency analysis needs a special case to handle this; analysing the .class files rather than the exported JAR.

This isn't a big priority for me, as I normally don't use this setting.

**Comment by harrah** [comment]
This was a good one, thanks!

A piece was missing for mapping an external source dependency back to its Analysis.  Basically, there were functions:

```
(dependencyClassName: String) => (binaryFile: File)

(binaryFile: File) => (sourceFile: File)

(sourceFile: File) => (analysis: Analysis)
```

but binaryFile was assumed to be a class file (since it is a one-to-many mapping from jar file to Scala/Java source files).  So, I added the direct function:

```
(dependencyClassName: String) => (sourceFile: File)
```

and it should be fixed with that.

**Comment by retronym** [comment]
Heh, turns out I _do_ need this, otherwise the xsbt-web-plugin splats all the classes into `WEB-INF/classes`, which messes up my app that has resources with the same name in multiple modules. So thanks for the fast fix!
