### ISSUE TITLE
sbtopts overrides not honored in expected way

### ISSUE THREAD

**Issue by nairbv** [sbt/sbt#1080]
I installed sbt 13.1 using the .deb file.  In the file /usr/bin/sbt (`which sbt`) there's a line:

declare -r sbt_opts_file=".sbtopts"

Which looks like it should be:

declare -r sbt_opts_file="${HOME}/.sbtopts"

If I put a .sbtopts file in my home directory, the options I specify aren't honored.  If I make the above change, they are.

**Comment by jsuereth** [comment]
This was original meant for project-local overrides of `/etc/sbtopts`.  Can you please reopen this ticket against:

https://github.com/sbt/sbt-launcher-package

I'd like to do some further discussion of possibilities.  I think reading options from multiple files may be a nice addition, and we should read from the home directory too.
