### ISSUE TITLE
share external compiler with IntelliJ / ENSIME / maker

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#1083]
IntelliJ can use an external Nailgun and it would be incredibly useful if either SBT could use IntelliJ's instance or SBT exposed a server that IntelliJ could use.

This would dramatically reduce compile times on larger projects.

**Comment by jsuereth** [comment]
Sbt 1.0 will include a server feature.  We have an experimental version that's almost feature complete now.  Once we've prototyped through the issue, you'll see a full proposla on sbt-dev.  For now, you can see the preliminary ideas:  https://github.com/sbt/sbt/wiki/Client-server-split

**Comment by fommil** [comment]
@jsuereth fyi, we're also interested in this at Ensime, which uses the presentation compiler.

**Comment by jsuereth** [comment]
@fommil awesome.   The goal of sbt-server is to let ANY IDE-like environment benefit from the sbt engine and automation configuration, so we'd love to have you onboard.  Ping me via email and I'll rope you in when the alpha releases start happening (soon).

**Comment by jsuereth** [comment]
And for this watching publicly, there's a 0.13.6-MSERVER-3 release of sbt with the most latest hooks for the sbt-server, while thesbt-server still resides in a separate R&D branch (while we stabilize it)

**Comment by fommil** [comment]
@jsuereth I'm `sam.halliday@gmail.com`

**Comment by fommil** [comment]
ENSIME no longer does the compile, so no need to share. It would be good if we could plug in to the presentation compiler while you're doing a compile but I think that's more of an issue for scalac
