### ISSUE TITLE
Incremental compilation broken for managed sources

### ISSUE THREAD

**Issue by OlegYch** [sbt/sbt#1085]
I have a play 2.2.1 project with sbt 0.13.1 on windows
Every time i compile, managed sources appear to be invalidated. 
This is caused by  
val removedProducts = previous.allProducts.filter( p => !equivS.equiv( previous.product(p), current.product(p) ) ).toSet
in sbt.inc.Incremental#changedInitial
every product produced from managed sources has wrong timestamp
Note that products from unmanaged sources are ok
I've tried debugging this, but it appears to be some kind of background file synchronization issue. 
Timestamps are ok after sbt.inc.Incremental#compile finishes, but when the compiling thread finishes the task something touches the files once again.

**Comment by OlegYch** [comment]
works fine with sbt 0.13.0, broken with 0.13.2-M1

**Comment by gkossakowski** [comment]
It's a bug in Play, see: playframework/playframework#2237.

AFAIK, there's no problem on sbt-side so I'm closing this issue.

**Comment by OlegYch** [comment]
i see, any idea why it works with 0.13.0 ?

**Comment by gkossakowski** [comment]
Yup, in the comment of playframework/playframework#2237 there's reference to #965. The relevant part is:

> The other way to solve this problem is to record time stamps of class files in Analysis object. This way, incremental compiler can detect that class files and Analysis object got out of sync and recover from that by recompiling corresponding sources.

So we fixed one bug in sbt and exposed another bug in Play.

**Comment by OlegYch** [comment]
thanks!
