### ISSUE TITLE
remove "resolving" bottleneck

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#1087]
This is to raise awareness of http://stackoverflow.com/questions/21123819

We are using [maker](https://github.com/cage433/maker) to build a very large scala project. It takes about 3 minutes to compile an 18 layer project (about 30 - 40 modules).

I was interested in comparing the performance with a more recent SBT and I created a quick and dirty build file for sbt 0.12.4. Despite SBT using parallel compilation, it took **10 minutes** to compile the same project from clean (not counting ivy download time).

The console output seemed to be preoccupied with resolving the dependencies, which were all in my ivy cache. I stumbled upon http://stackoverflow.com/questions/17190755 and it provides a hack that at least speeds up the second build to 3.5 minutes. However, this hack does not work on 0.13.x.
1. What is the equivalent hack in 0.13?
2. Is there anything else can be done to speed up an `sbt` compile?
3. Can this crazy bottleneck please be addressed going forward?

Although not the project, assume for all intents and purposes that my build script looks something like [build.scala](https://github.com/fommil/akka-patterns/blob/master/server/project/build.scala) (this file was the template that I used and added the hack around line 54).

**Comment by dansanduleac** [comment]
In 0.13, the cacheDirectory setting has moved to `InlineIvyConfiguration.resolutionCacheDir`. Therefore, if you want to avoid cleaning that directory, you could try:

``` scala
cleanKeepFiles ++= (ivyConfiguration.value match {
  case i: InlineIvyConfiguration => i.resolutionCacheDir case _ => None }).toList
```

not sure where it comes from if you use an `ExternalIvyConfiguration` - i.e. an external ivysettings.xml (then I reckon it's not controlled/maintained by sbt anymore).

_Edit_: this doesn't work because `cleanKeepFiles` is a setting, and `ivyConfiguration` is a task... I'd argue that it would make sense to convert `cleanKeepFiles` to a `TaskKey`.

_Edit 2:_ That shouldn't be too hard to work around. Because `clean := doClean(cleanFiles.value, cleanKeepFiles.value)`, you can just override that: 

``` scala
clean := Defaults.doClean(cleanFiles.value, cleanKeepFiles.value ++ 
  (ivyConfiguration.value match {
    case i: InlineIvyConfiguration => i.resolutionCacheDir 
    case _ => None 
  }).toList)
```

**Comment by jsuereth** [comment]
Migrating this bug as an 'enhancement' request.  We'd actually just like to remove the Ivy bottleneck.  Resolution actually serializes, thanks to requiring explicit file locks on the process.   @dansanduleac 's response is great.   That said, we're not really happy with Ivy, besides its conceptual model.

**Comment by erikkaplun** [comment]
@dansanduleac: the workaround doesn't seem to be working for me; I'm getting:

```
[error] (root/*:clean) java.lang.IllegalArgumentException: requirement failed: Source file '/Users/erik/myproj/target/resolution-cache/reports/ivy-report.css' does not exist.
```

What I did was put this in my `build.sbt`:

```
cleanKeepFiles ++= Seq("resolution-cache", "streams").map(target.value / _)

clean := Defaults.doClean(cleanFiles.value, cleanKeepFiles.value ++ 
  (ivyConfiguration.value match {
    case i: InlineIvyConfiguration => i.resolutionCacheDir 
    case _ => None 
  }).toList)
```

Without the first line, there was no error, but `clean` still wiped out the resolution-cache.
