### ISSUE TITLE
A website

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#109]
The whole readme file and wiki thing I don't think does justice to how awesome sbt 0.10 (or 0.7) is.

There has to be someone who can whip out a cool site focused on using sbt, not hacking on sbt.

**Comment by harrah** [comment]
Yes, I talked to n8han about using pamflet to produce static versions of the wiki, including things like table of contents and an index.  It would be best to have the Home page be the landing page instead of the readme/standard github page.  Beyond that, I'll hold out for "someone" to further improve the site.

**Comment by n8han** [comment]
I opened a number of [Pamflet issues](https://github.com/n8han/pamflet/issues) and tagged them "sbt". Feel free to open and tag any issues that are required to support sbt documentation.

I think eed3si9n makes a good point about user documentation being different from sbt hacking documentation. What I _really_ want to encourage with Pamflet is more people putting forkable book-like things on the web, so potentially you could have an sbt website based off the wiki and covering all things, but at the same time e. could publish his own "absolute beginners guide to sbt" at a different URL. Sort of like he has [already done](http://eed3si9n.com/sbt-010-guide), but using Pamflet!

**Comment by harrah** [comment]
The goal of the current documentation is certainly to be reference documentation first.  A linear pamflet is of course welcome.

**Comment by eed3si9n** [comment]
A beginner's guide would be a great content, but I am more concerned about general landing page something along the lines of
- http://jenkins-ci.org/
- http://akka.io/
- http://squeryl.org/
- http://buildr.apache.org/

or http://www.nescala.org/ @softprops designed.

For starters, sbt needs a logo sticker that says "converted to 0.10". All these details send the message.

**Comment by softprops** [comment]
Here's my 2¢. 

One thing I think the scala community is lacking is a respectable web presence as viewed from those just coming into the language. Sbt is definitely the first stop on the road to learning scala for most people so I care a lot about the impression something like this would have. I won't name names but I've seen some pretty hideous sites come from decent projects and libraries. Sbt has a really strong and growing community (based on the increasing volume of questions coming in from the email list alone) so it deserves a nice face on the web.

Below is a list of project sites that I think work well as `landing` pages for projects
- [vows](http://vowsjs.org/)
- [brubeck](http://brubeck.io/)
- [riakjs](http://riakjs.org/)
- [coffee script](http://jashkenas.github.com/coffee-script/)
- [express](http://expressjs.com/)

The second thing I think is important is making it very easy for someone coming into sbt with a specific problem to find an answer quickly. I think the wiki does an okay job there with a break down by topic but it could be a lot better. (The best answers are on the email list :))

I think if the pamflet style documentation could be embedded some how that would be great. One use case, which I think is becoming more common, is someone new to a project wanting to get a good overview with examples and with time to sit down and really read up on a project. We used to do this with these things called "books" for that but we all know by the time something tech related goes to press these days the content is already months out of date. Formats like [dive into..](http://diveintohtml5.org/) are really becoming strong alternatives. I think pamflet really fits this perfectly. The wiki structure and navigation is really awkward for this kind of browsing. Something like [Dispatch's](http://dispatch.databinder.net/Dispatch.html) docs really works well.

I'd love to help out on this.

**Comment by harrah** [comment]
Please have at it guys.  Let me know if you need something from me.

**Comment by relgames** [comment]
I agree. I've already spent around 2 hours to understand basics, and I still don't know how to create a sample project.
In sbt 0.7 is was possible just to run it and sbt was asking "create new project?"
Now what I see is a lot of pages with a tons of configuration options. And I can't find where to change scala version from default 2.8.0 to 2.9.0...

In maven you can just run mvn archetype:generate and you will get a sample project.

**Comment by softprops** [comment]
Hi @relgames  I just recently had a lot of time open up so I'm going to start actively working on this. Feel free to chip in yr ideas.

**Comment by bmc** [comment]
@softprops, et al, I just spent the requisite several days to get my head into SBT 0.10. I even managed to write a couple of plugins. I had a couple side conversations with Josh Suereth on SBT usability issues. Documentation would certainly go a long way toward solving these issues. Let me know if I can help.

BTW, [GitHub Pages](http://pages.github.com/) would be an awesome way to create the landing page for SBT. All my GH projects (the ones that have landing pages) are within the domain _software.clapper.org_, which is handled via GH Pages. Even without a separate SBT domain, having _harrah.github.com/sbt_ be the landing page would be nice.

FWIW, we did the entire [Scalathon](http://scalathon.org/) website with GH Pages.

**Comment by paulbutcher** [comment]
FWIW, I knocked this up a few days ago:

http://www.paulbutcher.com/2011/09/scala-2-9-1-sbt-0-10-and-scalatest-step-by-step/

I would be very happy to have it stolen to form part of an SBT landing page...

**Comment by eed3si9n** [comment]
Yea, I hate for this one to sit around on Issues too long. Let's get this ball rolling @softprops.

**Comment by eed3si9n** [comment]
About 11 hours ago, @jsuereth wrote [an sbt plugin that creates a home page](https://github.com/jsuereth/xsbt-ghpages-plugin).

**Comment by jsuereth** [comment]
Note:  I just took Mark's existing ghpages work and expanded it to allow entire site creation.   This still needs some reviewing and a few iterations :)

**Comment by softprops** [comment]
hey guys. I've been caught up in a few projects. I do have most of the splash page done. but its on my home machine now. Ill post back here tonight to get some reviews

**Comment by softprops** [comment]
still a wip but if you were interested in seeing where it was going, check out https://github.com/softprops/www-sbt. Im going to put focus on this and play with joshes new plugin tomorrow. feedback is welcome

**Comment by harrah** [comment]
@paulbutcher Nice writeup (again).  @softprops I like it.  Keep it up.

**Comment by harrah** [comment]
www.scala-sbt.org still needs work, but that will be ongoing.  Further website bugs should get filed at github.com/sbt/sbt.github.com.
