### ISSUE TITLE
Tests are not found with 0.13.1 sbt *nix shell script

### ISSUE THREAD

**Issue by sander24** [sbt/sbt#1096]
On ubuntu linux, the shell script does not execute Play 2.1.x application's unit tests -- it just says there are 0 tests found, even though there actually is plenty of tests. Don't know the root cause. Project itself is definitely okay. "sbt clean" or "sbt compile" work just fine, and so does the interactive console when i execute just "sbt". If i replace the script that ships with 0.13.1 with the old wrapper script then "sbt test" starts to work again and finds/compiles the tests with no problem (that's also why I'm sure the cause is in SBT wrapper script and not my own project setup).

(the script from your site that i use to replace sbt shell script : 

```
#!/bin/sh
SBT_OPTS="-Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M"
java $SBT_OPTS -jar `dirname $0`/sbt-launch.jar "$@"
```

As mentioned, for me myself this is now resolved, but just dropping you a note as maybe you want to improve the shell script : ) Thanks!

**Comment by cunei** [comment]
I cannot reproduce, at least with Play 2.2.1 and Play 2.1.5. I tried the stock 0.13.1 sbt launcher and script, and sbt.version in build.properties set to 0.13.0 or 0.13.1 for 2.2.1 and 0.12.2/0.12.4 for 2.1.5.
Could you kindly package a reproducible test case?

**Comment by sander24** [comment]
damn.. i can't reproduce it any more as well. i swear it was there. it must be related with something else in the environment then, like the version of java or scala or something. we're using play 2.1.5, sbt 0.12.3. if i can ever reproduce this, i'll update and re-open. thanks!
