### ISSUE TITLE
tab completion in 0.9 ignores one of the characters I typed

### ISSUE THREAD

**Issue by SethTisue** [sbt/sbt#11]
in the following transcript, note that I type Problem9 and press the tab key, yet the completions
I am offered aren't restricted to those where "9" is the first character after "Problem"

you can grab a copy of the project from http://www.sendspace.com/file/ymz38c

<pre>
  ~/sethtisue/eul> xsbt
[info] Set current project to default (in build file:/Users/tisue/sethtisue/eul/)
> compile
[success] Total time: 1 s, completed Apr 18, 2011 3:36:33 PM
> test-only net.tisue.euler.Problem9
Display all 131 possibilities? (y or n) 
--                           net.tisue.euler.Problem1     net.tisue.euler.Problem10
net.tisue.euler.Problem100   net.tisue.euler.Problem101   net.tisue.euler.Problem102
net.tisue.euler.Problem104   net.tisue.euler.Problem107   net.tisue.euler.Problem108
net.tisue.euler.Problem11    net.tisue.euler.Problem110   net.tisue.euler.Problem112
net.tisue.euler.Problem113   net.tisue.euler.Problem114   net.tisue.euler.Problem115
net.tisue.euler.Problem116   net.tisue.euler.Problem117   net.tisue.euler.Problem118
net.tisue.euler.Problem119   net.tisue.euler.Problem12    net.tisue.euler.Problem120
net.tisue.euler.Problem121   net.tisue.euler.Problem123   net.tisue.euler.Problem124
net.tisue.euler.Problem125   net.tisue.euler.Problem13    net.tisue.euler.Problem14
net.tisue.euler.Problem145   net.tisue.euler.Problem15    net.tisue.euler.Problem16
net.tisue.euler.Problem17    net.tisue.euler.Problem173   net.tisue.euler.Problem179
net.tisue.euler.Problem18    net.tisue.euler.Problem187   net.tisue.euler.Problem188
net.tisue.euler.Problem19    net.tisue.euler.Problem191   net.tisue.euler.Problem2
net.tisue.euler.Problem20    net.tisue.euler.Problem203   net.tisue.euler.Problem204
net.tisue.euler.Problem205   net.tisue.euler.Problem206   net.tisue.euler.Problem21
net.tisue.euler.Problem22    net.tisue.euler.Problem23    net.tisue.euler.Problem24
net.tisue.euler.Problem25    net.tisue.euler.Problem26    net.tisue.euler.Problem27
net.tisue.euler.Problem28    net.tisue.euler.Problem29    net.tisue.euler.Problem3
net.tisue.euler.Problem30    net.tisue.euler.Problem31    net.tisue.euler.Problem32
net.tisue.euler.Problem33    net.tisue.euler.Problem34    net.tisue.euler.Problem35
net.tisue.euler.Problem36    net.tisue.euler.Problem37    net.tisue.euler.Problem38
net.tisue.euler.Problem39    net.tisue.euler.Problem4     net.tisue.euler.Problem40
net.tisue.euler.Problem41    net.tisue.euler.Problem42    net.tisue.euler.Problem43
net.tisue.euler.Problem44    net.tisue.euler.Problem45    net.tisue.euler.Problem46
net.tisue.euler.Problem47    net.tisue.euler.Problem48    net.tisue.euler.Problem49
net.tisue.euler.Problem4f    net.tisue.euler.Problem5     net.tisue.euler.Problem50
net.tisue.euler.Problem50i   net.tisue.euler.Problem51    net.tisue.euler.Problem52
net.tisue.euler.Problem53    net.tisue.euler.Problem54    net.tisue.euler.Problem55
net.tisue.euler.Problem56    net.tisue.euler.Problem57    net.tisue.euler.Problem58
net.tisue.euler.Problem59    net.tisue.euler.Problem6     net.tisue.euler.Problem60
net.tisue.euler.Problem61    net.tisue.euler.Problem62    net.tisue.euler.Problem63
net.tisue.euler.Problem64    net.tisue.euler.Problem65    net.tisue.euler.Problem66
net.tisue.euler.Problem67    net.tisue.euler.Problem68    net.tisue.euler.Problem69
net.tisue.euler.Problem7     net.tisue.euler.Problem70    net.tisue.euler.Problem71
net.tisue.euler.Problem72    net.tisue.euler.Problem73    net.tisue.euler.Problem74
net.tisue.euler.Problem75    net.tisue.euler.Problem76    net.tisue.euler.Problem77
net.tisue.euler.Problem78    net.tisue.euler.Problem79    net.tisue.euler.Problem8
net.tisue.euler.Problem80    net.tisue.euler.Problem81    net.tisue.euler.Problem82
net.tisue.euler.Problem83    net.tisue.euler.Problem84    net.tisue.euler.Problem85
net.tisue.euler.Problem86    net.tisue.euler.Problem87    net.tisue.euler.Problem88
net.tisue.euler.Problem89    net.tisue.euler.Problem90    net.tisue.euler.Problem91
net.tisue.euler.Problem92    net.tisue.euler.Problem93    net.tisue.euler.Problem94
net.tisue.euler.Problem95    net.tisue.euler.Problem96    net.tisue.euler.Problem97
net.tisue.euler.Problem98    net.tisue.euler.Problem99
</pre>

**Comment by harrah** [comment]
It looks like improper token boundaries and whitespace placement: whitespace is trimmed before displaying alternatives, otherwise you would see that the "invalid" alternatives are preceded by a space.  Writing out the whole line, the suggestion for "...Problem66" is really "test-only net.tisue.euler.Problem9 net.tisue.euler.Problem66", if that makes sense.  Anyway, should be easy to fix.

**Comment by harrah** [comment]
fixed in 6abab8e4b3232630b4f
