### ISSUE TITLE
Transitive dependency issue: test scope dependency is treated as compile if intermediate module has compile dependency on it

### ISSUE THREAD

**Issue by AlainODea** [sbt/sbt#1109]
If I have moduleX depends on moduleY depends on moduleZ and moduleX also depends on moduleZ as a test-scoped dependency, SBT allows me to compile code in moduleX that directly uses code in moduleZ.

**Root build.sbt**:

``` scala
name := "multimodule-sbt-dependencies"

version := "0.1"

organization := "com.alainodea"

scalaVersion := "2.10.2"

lazy val allScopes = "compile;test;test->test"

lazy val moduleX = project.in(file("moduleX")).dependsOn(moduleY % allScopes, moduleZ % "test")

lazy val moduleY = project.in(file("moduleY")).dependsOn(moduleZ % allScopes)

lazy val moduleZ = project.in(file("moduleZ"))
```

**moduleX build.sbt**:

``` scala
name := "moduleX"

version := "0.1"

organization := "com.alainodea"

scalaVersion := "2.10.2"
```

**moduleY build.sbt**:

``` scala
name := "moduleY"

version := "0.1"

organization := "com.alainodea"

scalaVersion := "2.10.2"
```

**moduleZ build.sbt**:

``` scala
name := "moduleZ"

version := "0.1"

organization := "com.alainodea"

scalaVersion := "2.10.2"
```

**ModuleXClass.scala in moduleX/src/main/scala**:

``` scala
class ModuleXClass {
  val compileDependencyOnZIsInvalid = new ModuleZClass
}
```

**ModuleZClass.scala in moduleZ/src/main/scala**:

``` scala
class ModuleZClass
```

In this example my understanding is that **ModuleXClass** should not compile with the reference to **ModuleZClass** in place.

My [multimodule-sbt-dependencies](https://github.com/AlainODea-scala/multimodule-sbt-dependencies) repository provides this example for easy consumption.

**Comment by jsuereth** [comment]
You're pulling in all of moduleZ transitively via ModuleY.

**Comment by jsuereth** [comment]
In any case, let me know if I'm wrong in that assumption and I'll reopen this.   I very much appreciate the minimized test case!  If you need me to clarify any more what's happening here I can, or perhaps you can clarify what you're trying to do so I can understand.

I'm closing for now in lieu of more info.

**Comment by AlainODea** [comment]
@jsuereth it's by design then.  Good to know.  I have a bug to file with JetBrains :)  Thank you for reviewing the issue.

**Comment by AlainODea** [comment]
@jsuereth I'm trying to prevent **moduleX** from using the source of **moduleZ** except in tests.  How do I do that?

Here's my question on StackOverflow if that is a better medium for this:
http://stackoverflow.com/q/21716720/154527
