### ISSUE TITLE
Publish as Maven style includes SBT plugins in POM

### ISSUE THREAD

**Issue by rgladwell** [sbt/sbt#1118]
Publishing with the Maven style includes SBT plugins as dependencies in the generated POM.

Steps to reproduce:

Modify you `~/.sbt/0.13/plugins.sbt` to add the following lines:

```
resolvers += Resolver.url("Typesafe repository", new java.net.URL("http://typesafe.artifactoryonline.com/typesafe/ivy-releases/"))(Resolver.defaultIvyPatterns)

addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "2.4.0")
```

Then execute the following

```
$ git clone git@github.com:alphagov/dropwizard-scala.git
$ cd dropwizard-scala
$ sbt
> set publishMavenStyle := true
> set publishTo := Some(Resolver.file("your local repo", new java.io.File("/tmp")))
> publish
```

The POM file generated at `/tmp/uk/gov/gds/dropwizard-scala_2.10/1.0.0-SNAPSHOT/dropwizard-scala_2.10-1.0.0-SNAPSHOT.pom` contains the following dependency:

```
        <dependency>
            <groupId>com.typesafe.sbteclipse</groupId>
            <artifactId>sbteclipse-plugin</artifactId>
            <version>2.4.0</version>
        </dependency>
```

It should not contain this dependency

**Comment by jsuereth** [comment]
You want to put your global plugins under:

`~/.sbt/0.13/plugins/plugins.sbt`

THe file you're using is one that can modify all local project settings, so it's not actualyl adding the plugin.  It's adding the plugin as a dependency to all your projects.
