### ISSUE TITLE
sbt 0.13.2 macro engine regression [21/02/2014]

### ISSUE THREAD

**Issue by dansanduleac** [sbt/sbt#1131]
I seem to have found a bug in sbt 0.13.2. If, inside the initialisation of a task, I take a `SettingKey`, `.apply` it and then get all the values of the resulting thing with `.all`, ultimately getting the `.value`, it crashes the compiler. 
If I remove the `.apply`, it works. If I don't assign this expression to a `val`, it also works.

All three examples, however, work as expected on sbt 0.13.1.

``` scala
val inNonRootProjects = inAggregates(LocalRootProject)
val t = taskKey[Seq[String]]("aaa")

// Crashes
t := {
  val abc = projectID(_.name).all(ScopeFilter(inNonRootProjects)).value
  abc
}

// Works if I remove the .apply
t := {
  val abc = projectID.all(ScopeFilter(inNonRootProjects)).value
  abc map (_.name)
}

// Works if I don't assign to a val
t := projectID(_.name).all(ScopeFilter(inNonRootProjects)).value
```

crashes the compiler like this:

```
[error]      while compiling: C:\cygwin64\tmp\a\build.sbt
[error]         during phase: global=explicitouter, atPhase=erasure
[error]      library version: version 2.10.3
[error]     compiler version: version 2.10.3
...

[error]
[error]   last tree to typer: This(anonymous class $anonfun)
[error]               symbol: anonymous class $anonfun (flags: final <synthetic>)
[error]    symbol definition: final class $anonfun extends AbstractFunction1[sbt.ModuleID,String] with Serializable
[error]                  tpe: $58d9edf2ae4a5ebbd30d.$anonfun.$anonfun.type
[error]        symbol owners: anonymous class $anonfun -> value abc -> method apply -> anonymous class $anonfun -> method $sbtdef -> object $58d9edf2ae4a5ebbd30d -> package <empty>
[error]       context owners: value $outer -> anonymous class $anonfun -> value abc -> method apply -> anonymous class $anonfun -> method $sbtdef -> object $58d9edf2ae4a5ebbd30d -> package <empty>
[error]
[error] == Enclosing template or block ==
[error]
[error] DefDef( // val $outer(): $58d9edf2ae4a5ebbd30d.$anonfun.type
[error]   <method> <synthetic> <stable> <expandedname>
[error]   "$58d9edf2ae4a5ebbd30d$$anonfun$$anonfun$$$outer"
[error]   []
[error]   List(Nil)
[error]   <tpt> // tree.tpe=Any
[error]   $anonfun.this."$outer " // private[this] val $outer: $58d9edf2ae4a5ebbd30d.$anonfun.type, tree.tpe=$58d9edf2ae4a5ebbd30d.$anonfun.type
[error] )
[error]
[error] == Expanded type of tree ==
[error]
[error] ThisType(anonymous class $anonfun)
[error]
[error] no-symbol does not have an owner
[error] Use 'last' for the full log.
```

**Comment by jsuereth** [comment]
@retronym I may need help with this one, whenever you find yourself with spare time.

**Comment by dansanduleac** [comment]
Quick response! I'm looking into this as well, but it's likely that @retronym will find a fix sooner :)

**Comment by retronym** [comment]
I'm a bit tied up right now. Could you ping me in a week or so to help out?

**Comment by jsuereth** [comment]
@retronym no problems.  Whenever you have time.  I'll ping you.

**Comment by jaceklaskowski** [comment]
@dansanduleac you sure there should be `projectId` not `projectID` (it doesn't solve the issue, tough)?

**Comment by dansanduleac** [comment]
@jaceklaskowski Oops, you're right. Amended. (and no, it doesn't solve the issue :) )

**Comment by cunei** [comment]
I tried to reproduce this ticket, but the example you supplied worked ok for me:

```
$ cat t1131.sbt 
val inNonRootProjects = inAggregates(LocalRootProject)
val t = taskKey[Seq[String]]("aaa")

// Crashes
t := {
  val abc = projectID(_.name).all(ScopeFilter(inNonRootProjects)).value
  abc
}
$ sbt
[...]
> about
[info] This is sbt 0.13.1
[info] The current project is {file:/home/cunei/activities/triaging/sbt/1131/test/}test 0.1-SNAPSHOT
[info] The current project is built against Scala 2.10.3
[info] 
[info] sbt, sbt plugins, and build definitions are using Scala 2.10.3
> show t
[info] List(test)
[success] Total time: 0 s, completed Feb 25, 2014 12:15:51 AM
>
```

Can you please package a project that exhibits the problem? (I wonder whether Cygwin may have a role)

**Comment by cunei** [comment]
I double checked, and it also worked for me using (an old version of) Cygwin.

**Comment by dansanduleac** [comment]
I'm sorry, it seems the issue is only with the latest sbt `0.13.2`.
I've been calling `sbt -sbt-version=0.13.1` but for some reason sbt's start script does not parse that correctly and just ignores it, I should have replaced the `=` with a space. And I am on Cygwin.

**Comment by cunei** [comment]
Yes, the syntax is either "sbt -sbt-version 0.13.1" or "sbt -Dsbt.version=0.13.1". I can reproduce the bug in sbt 0.13.2-20140225-062312, I'll try to locate the commit that introduced the regression. Thanks!

**Comment by cunei** [comment]
The regression occurred between 0.13.1-20131121-062303 (good) and 0.13.1-20131125-062250 (fails). The snapshots in the middle unfortunately are broken, but the offending commit should be in that range.

**Comment by dansanduleac** [comment]
Looks like this is the same as #1150.

**Comment by dansanduleac** [comment]
#1166 fixed this as well. Thanks!

**Comment by retronym** [comment]
Thanks for letting us know!
