### ISSUE TITLE
unexpected dummy task parse error with InputKey in inConfig vs global scope

### ISSUE THREAD

**Issue by softprops** [sbt/sbt#114]
I tried to sum this much ask I could in a [gist](https://gist.github.com/1096374). 

[This file](https://gist.github.com/1096374#file_usage.session.log) is the example sbt session in question.

The basic idea is that if you define a function binding for an InputKey within a config and then define an alias to that keys binding in the global scope so users won't have to type the config name `:`, you'll get an unexpected parse error when _not_ using the namespace in sbt's prompt (global scope)

```
Parsed result dummy task not found in ...
```

thrown [here](https://github.com/harrah/xsbt/blob/0.10/main/Aggregation.scala#L152-153)

I am guessing the dummy task is provided by the `inputTask` method and is missing some scope registration.

I originally thought this had to do with the custom parser combinators but I am also about to reproduce this with the default parser.

**Comment by harrah** [comment]
This is sufficient for me to work with.  It is likely the default parser will work ok.
