### ISSUE TITLE
ansi escape sequence stripping is broken

### ISSUE THREAD

**Issue by jroper** [sbt/sbt#1143]
The ansi escape sequence stripping (`ConsoleLogger.removeEscapeSequences`) is broken, especially when stripping escapes for colouring.  An example colour escape sequence is `<ESC>[33m`, only the `<ESC>[` is being stripped, leaving the `33m` behind.

According to wikipedia:

> Escape sequences start with the character ESC (ASCII decimal 27/hex 0x1B/octal 033). For two character sequences, the second character is in the range ASCII 64 to 95 (@ to _). However, most of the sequences are more than two characters, and start with the characters ESC and [ (left bracket). This sequence is called CSI for Control Sequence Introducer (or Control Sequence Initiator). The final character of these sequences is in the range ASCII 64 to 126 (@ to ~).

The problem with the current logic is that it's missing the middle bit about the second character either being ASCII 64 to 95 or 96 (`[`), and just looks for the final character in range 64 to 126, so for > 2 character escapes, it will never strip the CSI.

**Comment by jsuereth** [comment]
@jroper did you have a fix for this?

**Comment by jroper** [comment]
Not really, for my purposes, I just stripped the colour codes:

https://github.com/sbt/sbt-mocha/blob/master/src/sbt-test/sbt-mocha-plugin/test/project/TestBuild.scala

**Comment by jsuereth** [comment]
Just a note:  JANSI (which we use) has the means to strip color codes already.
