### ISSUE TITLE
Documentation for AutoPlugins

### ISSUE THREAD

**Issue by jsuereth** [sbt/sbt#1149]
Documentation in sbt needs to be updated for AutoPlugin feature.  Existing Plugin docs should be deprecated.

**Comment by jsuereth** [comment]
This was mostly done in the auto-plugins pull request.  Debating closing this for RC1.  Anyone have any thoughts?

@retronym @havocp you guys saw the docs so far, what do you think?

**Comment by jsuereth** [comment]
cc @eed3si9n When you feel this is done we should close it.  I think we're pretty close.

**Comment by jaceklaskowski** [comment]
Is there a landing page for the feature? Do we want to have a single page for this or keep it spread across different ones as it seems so now?
- http://www.scala-sbt.org/0.13/tutorial/Using-Plugins.html
- http://www.scala-sbt.org/0.13/docs/Plugins.html

**Comment by jsuereth** [comment]
Yeah, the "docs" one is hte landing page, the tutorial is a walkthrough of sbt features for newcomers, so both need to exist for different reasons.

**Comment by jsuereth** [comment]
Also, I feel this is sufficiently fixed now.
