### ISSUE TITLE
export classpath no longer exports

### ISSUE THREAD

**Issue by paulp** [sbt/sbt#1155]
In 0.13.1, given this build.sbt

```
scalaVersion := "2.11.0-RC1"

libraryDependencies += "org.scala-lang" % "scala-reflect" % scalaVersion.value
```

Running sbt 'export fullClasspath' gives this:

```
/Users/paulp/scratch/2014-03-07_scala_1/target/scala-2.11.0-RC1/classes:/Users/paulp/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.0-RC1.jar:/Users/paulp/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.0-RC1.jar
```

In 0.13.2-M1 and -M2, it just exits silently.

**Comment by jsuereth** [comment]
This appears to be related to the addition of the `all` task.   Somewhere along the chain our "show values" settings.  Specifically, this line looks suspicious: https://github.com/sbt/sbt/blob/0.13/main/src/main/scala/sbt/Aggregation.scala#L157

I'm still investigating, this is just a note so I don't forget.

**Comment by jsuereth** [comment]
Hmm, was barking up the wrong tree. This commit is interesting: ca7e78d03d.

**Comment by jsuereth** [comment]
It looks like we have more than one "export" stream per task run.  That commit ensures the one we read from is closed before written to, although there is another file which DOES have the correct value in it.  Going to figure out how to wire up to the correct export stream, then we should be good to go.

**Comment by jsuereth** [comment]
Ok, the issue appears to be we're exporting things with the 'streams' key (associated with the fullClaspsath task), but we're reading from the 'fullClasspath' key, so the resulting stream is empty.

```
[SUCKY DEBUG] Exporting: Stream(ScopedKey(Scope(Select(ProjectRef(file:/home/jsuereth/projects/sbt/test-ivy-issues/,test-ivy-issues)),Select(ConfigKey(compile)),Select(fullClasspath),Global),streams), export, @/home/jsuereth/projects/sbt/test-ivy-issues/target/streams/compile/fullClasspath/$global/streams/export)
[SUCKY DEBUG] Reading  : Stream(ScopedKey(Scope(Select(ProjectRef(file:/home/jsuereth/projects/sbt/test-ivy-issues/,test-ivy-issues)),Select(ConfigKey(compile)),Select(fullClasspath),Global),fullClasspath), export, @/home/jsuereth/projects/sbt/test-ivy-issues/target/streams/compile/fullClasspath/$global/fullClasspath/export)
```

Lining up the keys in that way shows exactly the issue.

**Comment by jsuereth** [comment]
Found it.  Will be fixed in the RC1.

**Comment by paulp** [comment]
Great, thanks.

**Comment by paulp** [comment]
Oh yeah - I saw there was a test which issued some command involving export classpath, and it has apparently not been failing. That might merit investigation in case it's not testing what it was written to test.

**Comment by jsuereth** [comment]
Yeah, it was never testing what made it to System.out from the sbt process.   We actually don't have hooks for those tests, so unfortunately the only way to test `export` right now is to reimplement its logic in a test, which is mostly a useless exercise in CPU.

I'll be working the test suite slowly over the coming months for greater stability + a few more features so we can check things like "export".  Ironically, the move to sbt-server makes checking System.out easy and a lot else harder.
