### ISSUE TITLE
sbt console explodes in 2.11.0-RC1 when given a compiler plugin

### ISSUE THREAD

**Issue by dlwh** [sbt/sbt#1159]
Thought it was a scalac issue, seems to be an SBT issue.

https://issues.scala-lang.org/browse/SI-8370

build.sbt:

```
scalaVersion := "2.11.0-RC1"

addCompilerPlugin("org.scalamacros" % "paradise" % "2.0.0-SNAPSHOT" cross CrossVersion.full)

resolvers ++= Seq(
    Resolver.mavenLocal,
    Resolver.sonatypeRepo("snapshots"),
    Resolver.sonatypeRepo("releases"),
    Resolver.typesafeRepo("releases")
    )
```

sbt console-quick will explode. Running Scala directly doesn't seem to explode.

According to Eugene, not specific to macro-paradise.

**Comment by dlwh** [comment]
(checked against 0.13.1 and 0.13.2-M1)

**Comment by jsuereth** [comment]
Thanks for the report.  Will investigate after 0.13.2-RC1 is out (as it's not a regression).

**Comment by xeno-by** [comment]
Don't think that it's sbt who's at fault. See my comments to the aforementioned Scala issue.

**Comment by dlwh** [comment]
But I got scala console to run directly?

**Comment by dlwh** [comment]
either way, you're better equipped to figure it out than I am :-)

This command works fine for me:

```
java -cp
/Users/dlwh/.ivy2/cache/jline/jline/jars/jline-2.11.jar:/Users/dlwh//.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.0-RC1.jar:/Users/dlwh//.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.11.0-RC1.jar:/Users/dlwh//.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.0-RC1.jar
scala.tools.nsc.MainGenericRunner -usejavacp
-Xplugin:/Users/dlwh/.ivy2/cache/org.scalamacros/paradise_2.11.0-RC1/jars/paradise_2.11.0-RC1-2.0.0-SNAPSHOT.jar
```

**Comment by xeno-by** [comment]
I guess scalac's bug is only exposed through sbt's classloader magic.

**Comment by jsuereth** [comment]
Appears to no longer be an issue with Scala 2.11.0 and macro paradise 2.0.1
