### ISSUE TITLE
sub project src path

### ISSUE THREAD

**Issue by krux02** [sbt/sbt#116]
the source path in subproject does not work as expected.

Directory layout

```
root
+-project
| +-project.scala
+-sub
  +-build.sbt
  +-src
    +-main.scala
```

project.scala

```
import sbt._
object SimplexBuild extends Build{
  lazy val sub = Project("sub",file("sub"))
}
```

build.sbt

```
name := "sub"
scalaVersion := "2.9.0-1"
scalaSource in Compile := file("src")
```

main.scala

```
scala
object main extends App{
  println("Hello world!")
}
```

staring sbt in the subproject does work, but stating sbt in the root project and select the subproject does not compile anything

**Comment by harrah** [comment]
Please use the mailing list for questions.

**Comment by krux02** [comment]
sorry that i don't use the mailing list. But I still see this as a bug or usability issue. Even if a small change in code would correct this problem, it does not feel natural that a configuration in sub projects and configurations on top level projects need to be handled differently.

For me its only one of many usability issue that sbt has at the moment. But for me it seems you definity don't want to have any feedback about usability.
