### ISSUE TITLE
Improve error message when trying to compile sbt plugins against different scala binary versions than sbt supports.

### ISSUE THREAD

**Issue by sksamuel** [sbt/sbt#1175]
I am using this build.sbt file and I get the good old `class Universe does not have a member Quasiquote` error when building for 2.11. If I remove the sbtPlugin := true line then it all works fine. I've stripped the actual plugin class down to nothing but an empty class file and the error still persists. 

``` scala
name := "sbt-scoverage"

organization := "com.sksamuel.scoverage"

version := "0.96.0"

scalaVersion := "2.10.3"

crossScalaVersions := Seq("2.10.3", "2.11.0-RC1")

scalacOptions := Seq("-unchecked", "-deprecation", "-feature", "-encoding", "utf8")

sbtPlugin := true

publishTo := Some(Resolver.url("sbt-plugin-releases",
  new URL("http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/"))(Resolver.ivyStylePatterns))

publishMavenStyle := false

publishArtifact in Test := false

licenses +=("Apache-2.0", url("http://www.apache.org/licenses/LICENSE-2.0.html"))
```

``` scala
class ScoverageSbtPlugin
```

**Comment by jsuereth** [comment]
You can't build sbt plugins against Scala versions which are not compatible with the `sbt` version you're building.  That means no Scala 2.11 until sbt 1.0, Sorry.

Going to leave this open as an enhancement to improve that error message :)

**Comment by sksamuel** [comment]
Is 1.0 planned for release at same time as 2.11 ?

**Comment by jsuereth** [comment]
No.  End of this year.  I believe @xeno-by has some compatibility things for 2.11 vs. 2.10 macros that might let you get what you need....

**Comment by sksamuel** [comment]
Maybe I'm confused. I have a plugin for sbt that I'd like to use with 2.11.
Sbt obviously compiles 2.11 as I've done that. Does my plugin just need to
stay as 2.10 and its all good ?

**Comment by jsuereth** [comment]
Yes.  At runtime, sbt is using Scala 2.10.x.  If you're creating an sbt plugin, you have to stick with 2.10.x binary compatible libraries. 

Sbt can compile any project, but any project that relies on a 2.10.x artifact is stuck on 2.10.x.  This mean sbt plugin (for sbt 0.13) need to use 2.10.x.

**Comment by xeno-by** [comment]
The compat trick decribed in http://docs.scala-lang.org/overviews/macros/changelog211.html#how_to_make_your_210x_macros_work_in_2110 is solely about source compatibility, not binary compatibility.

**Comment by sksamuel** [comment]
Ok I see. The plugin doesn't need anything from 2.11 just needs to work
with projects that want to use 2.11. So I think there's actually nothing I
need to do.

**Comment by jsuereth** [comment]
Yep, you should be good.
