### ISSUE TITLE
run command should display detected main classes in package order

### ISSUE THREAD

**Issue by jpsacha** [sbt/sbt#1180]
When you issue `run` command from `sbt` prompt and you have more than one main class, you will get a numbered list to select class to run. That list s not ordered in any meaningful way. With large number of main classes is quite difficult to find one you need. They should be listed in alphabetical order by package.

**Comment by cunei** [comment]
Thanks for the report! Note that the selection of the main method can be easily customized by using the settings `mainClass`, `discoveredMainClasses`, and `selectMainClass` (which depends on the first two). The default definition is:

```
selectMainClass := mainClass.value orElse selectRunMain(discoveredMainClasses.value)
```

where `selectRunMain()` is an internal method, but you can redefine it as needed.
 --
As an sbt enhancement, this can be implemented by adding a sort to the `multiple` Seq[] within `selectRunMain()`, in the file `run/src/main/scala/sbt/SelectMainClass.scala`:

```
for( (className, index) <- multiple.zipWithIndex )
```

We'll consider this change for inclusion in the next release, thanks!

**Comment by deanwampler** [comment]
Is this actually merged into sbt? If so, which version.

@cunei what is the actual command you would add to sbt to override. As written, `selectMainClass := mainClass.value orElse selectRunMain(discoveredMainClasses.value)` doesn't compile. How could this be modified in a build file to do sorting?

**Comment by jsuereth** [comment]
I'm not sure this was ever implemented.  

However the default value is here:
https://github.com/sbt/sbt/blob/0.13/main/src/main/scala/sbt/Defaults.scala#L271

I think you want:

```
selectMainClass in Compile := (mainClass in Compile).value orElse Defaults.askForMainClass((discoveredMainClasses in Compile).value)
```

**Comment by deanwampler** [comment]
I fixed a type (`orElseDefaults` -> `orElse Defaults`) and updated to 0.13.7, but it doesn't appear to work when I enter `run`:

```
Multiple main classes detected, select one to run:

 [1] Crawl5a
 [2] hadoop.HJoins7
 [3] Matrix4
 [4] Joins7
 [5] hadoop.HNGrams6
 [6] NGrams6
 ...
```

and so forth for my tutorial. Does it only sort package names? I use the default package because otherwise the names are cut off in the Activator UI.

**Comment by eed3si9n** [comment]
Closing via #1695. Test sbt 0.13.8-RC1 and see if this fixes it.
