### ISSUE TITLE
errors found in build.sbt are reported with no position (java.lang.ArrayIndexOutOfBoundsException: -1)

### ISSUE THREAD

**Issue by paulp** [sbt/sbt#1181]
This build.sbt:

```
lazy val bob = scala.Console println
```

Will crash sbt with no indication whatsoever what happened, where or why. (My real one is more than one line.) The expression is valid scala.

```
[info] Loading project definition from /Users/paulp/scratch/2014-03-12_sbt_1/project
java.lang.ArrayIndexOutOfBoundsException: -1
    at scala.reflect.internal.util.OffsetPosition.column(Position.scala:249)
    at scala.reflect.internal.util.Position$.formatMessage(Position.scala:33)
    at scala.tools.nsc.reporters.ConsoleReporter.printMessage(ConsoleReporter.scala:49)
    at scala.tools.nsc.reporters.ConsoleReporter.print(ConsoleReporter.scala:52)
    at scala.tools.nsc.reporters.ConsoleReporter.display(ConsoleReporter.scala:78)
    at scala.tools.nsc.reporters.AbstractReporter.info0(AbstractReporter.scala:49)
    at scala.tools.nsc.reporters.Reporter$$anonfun$error$1.apply$mcV$sp(Reporter.scala:70)
    at scala.tools.nsc.reporters.Reporter$$anonfun$error$1.apply(Reporter.scala:70)
    at scala.tools.nsc.reporters.Reporter$$anonfun$error$1.apply(Reporter.scala:70)
```

The "full log", or at least it is so implied:

```
[error] java.lang.ArrayIndexOutOfBoundsException: -1
[error] Use 'last' for the full log.
[debug] > load-failed
[debug] > last
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

If the implied empty param list is given, it compiles.

```
lazy val bob = scala.Console println ()
```

**Comment by jsuereth** [comment]
Go Go Macro fun!

Thanks for the report.

**Comment by som-snytt** [comment]
If sbt supplied parens, the message would read:

```
Project loading failed: (r)etry, (q)uit, (l)ast, (i)gnore or ()?
```

**Comment by jsuereth** [comment]
@som-snytt Sounds like a good April 1 feature request.

**Comment by cunei** [comment]
I tried to reproduce, but did not get the same error. Are there any other files involved? My session is:

```
cunei@rover:~/activities/triaging/sbt$ mkdir 1181
cunei@rover:~/activities/triaging/sbt$ cd 1181
cunei@rover:~/activities/triaging/sbt/1181$ echo 'lazy val bob = scala.Console println' >build.sbt
cunei@rover:~/activities/triaging/sbt/1181$ sbt -Dsbt.version="0.13.3-20140312-062331"
Loading /home/cunei/activities/sbt-initialtests/13-1/sbt/bin/sbt-launch-lib.bash
[warn] The global sbt directory is now versioned and is located at /home/cunei/.sbt/0.13.3-20140312-062331.
[warn]   You are seeing this warning because there is global configuration in /home/cunei/.sbt but not in /home/cunei/.sbt/0.13.3-20140312-062331.
[warn]   The global sbt directory may be changed via the sbt.global.base system property.
[info] Set current project to root-1181 (in build file:/home/cunei/activities/triaging/sbt/1181/)
> about
[info] This is sbt 0.13.3-20140312-062331
[info] The current project is {file:/home/cunei/activities/triaging/sbt/1181/}root-1181 0.1-SNAPSHOT
[info] The current project is built against Scala 2.10.3
[info] Available Plugins: sbt.plugins.IvyModule, sbt.plugins.JvmModule, sbt.plugins.GlobalModule
[info] sbt, sbt plugins, and build definitions are using Scala 2.10.3
>
```

Using the lazy val does what is expected (prints a blank line). The result was the same with 0.13.2-M3 and 0.13.1.

**Comment by paulp** [comment]
Sorry, I blew the minimization.

```
// Build.scala
import sbt._

object Build {
  class ProjectOps(val p: Project) { def configured(deps: ModuleID*): Project = p }
  implicit def projectOps(p: Project): ProjectOps = new ProjectOps(p)
}
```

And

```
// build.sbt
import Build._

lazy val bob = project configured

// just for the contrast
lazy val tom = project configured ()
```

Crashes with both those versions.

**Comment by paulp** [comment]
Oh I see what happened. THIS is enough to reproduce it:

```
lazy val bob = Console println
```

At the last minute I added the "scala." to Console so as to make it valid code (as by default that's sbt's Console) but the crash actually depends on the conversion which doesn't take place with scala.Console.println.

**Comment by paulp** [comment]
Or even more plausibly, this alone is enough:

```
lazy val proj = project settings
```

**Comment by cunei** [comment]
Thanks, this was working ok in 0.13.0. The regression occurred between 0.13.1-20130925-062608 (working) and 0.13.1-20130926-062536 (broken).

**Comment by SethTisue** [comment]
Here's a build.sbt that results in a similar ArrayIndexOutOfBoundsException in OffsetPosition:

``` scala
test ++
```

yup, that's it. (I'm on 0.13.2)

**Comment by paulp** [comment]
Your implied crash repro golf challenge does not go unnoticed. 4 chars.

```
run+
```

**Comment by som-snytt** [comment]
You guys are trying too hard.  `1+` suffices.

**Comment by Discipe** [comment]
Just ran into this. All what scalac wanted to do is print me a warning!
But cruel 'source-&lt;no file&gt;' results in 'out of bound' exception. IMHO that bug priority needs a boost, because it may crash compiler on valid sbt files. ;(

**Comment by paulp** [comment]
Yes, it's extremely user-unfriendly that positions are so aggressively crashy. scalac has always been this way, and used to be even more so. NoSymbol.owner is NoSymbol these days rather than stack trace, so there may be hope.

**Comment by jaceklaskowski** [comment]
Just hit this today with the latest `sbt 0.13.6-SNAPSHOT` built from the sources  while learning sbt and its operators with the following `build.sbt`:

```
lazy val abc = taskKey[Unit]("abc task")

abc <<= abc ?
```

When I've changed to `abc.?` the `build.sbt` parses (however sbt correctly throws `type mismatch` error).

**Comment by LeftenantZero** [comment]
Just ran across this error after I accidentally added an "s" after one of 17 dependencies in a 50+ line build.sbt while tabbing through files in my IDE.  (So dependency became:, "org.scalaz" %% "scalaz-core" % "7.1.0"s)

It's not too hard to figure out error is caused by some kind of error in project configuration and back our recent changes to troubleshoot or something like that, but this message seems insanely/aggressively un-userfriendly.  If the stack trace could even just include the line that triggered the exception somewhere, it would be far more helpful.
