### ISSUE TITLE
Be silent when there are no tests to run

### ISSUE THREAD

**Issue by japgolly** [sbt/sbt#1185]
In a multi-module project, when I run `test` in the root which aggregates everything else, I want to be able to hide all the noise about modules without tests.

This is the kind of noise I want to opt-out of.

```
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for blah-server-schema/test:test
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for blah-server-logic/test:test
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for blah-api/test:test
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for blah-server-impl/test:test
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for blah-server/test:test
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for blah/test:test
```

I think a normal scoped setting would be enough. Does that sound good? Should I start writing a patch?

**Comment by jsuereth** [comment]
Yeah, feel to write a patch.  Would love to have this for 0.13.5.  we're planning another milestone of it shortly, and an RC in a few weeks.

**Comment by huntc** [comment]
I have some code that presently uses Tests.showResults e.g.:

``` scala
Tests.showResults(streams.value.log, Tests.Output(result, events, Nil), "No mocha tests found")
```

... I suspect others may have been using `Tests.showResults` so it might be useful to show an example here of how the above can be directly represented by `TestResultLogger`.

@japgolly Can you do that?

**Comment by huntc** [comment]
Actually, I did it. Somewhere declare the logger:

``` scala
  val testResultLogger = TestResultLogger.Default.copy(printNoTests = TestResultLogger.const(_ info "No mocha tests found"))
```

and then use it:

``` scala
testResultLogger.run(streams.value.log, Tests.Output(result, events, Nil), "")
```

**Comment by japgolly** [comment]
Cool, my work here is done :grinning:

**Comment by jmuth** [comment]
Hi,

Using version 0.13.11 still can't achieve to silent useless information. How can I do it ?
