### ISSUE TITLE
Add configuration to fail a task execution if triggered task fails

### ISSUE THREAD

**Issue by savulchik** [sbt/sbt#1187]
Having the following build definition file and `sbt 0.13.1`:

``` sbt
name := "foobar"

val foo = taskKey[Unit]("foo")
val bar = taskKey[Unit]("bar")

foo := { println("foo") }

bar := { println("bar"); throw new Exception("bar exception") }

bar <<= bar triggeredBy foo
```

When I execute the `foo` task the exception thrown by the triggered `bar` task isn't reported:

``` shell
$ sbt foo
Loading /opt/local/sbt/bin/sbt-launch-lib.bash
[info] Loading global plugins from /home/s.savulchik/.sbt/0.13/plugins
[info] Loading project definition from /home/s.savulchik/projects/foobar/project
[info] Set current project to foobar (in build file:/home/s.savulchik/projects/foobar/)
foo
bar
[success] Total time: 0 s, completed Mar 12, 2014 6:34:52 PM
```

Instead when I directly execute the `bar` task the exception in reported as expected:

``` shell
$ sbt bar            
Loading /opt/local/sbt/bin/sbt-launch-lib.bash
[info] Loading global plugins from /home/s.savulchik/.sbt/0.13/plugins
[info] Loading project definition from /home/s.savulchik/projects/foobar/project
[info] Updating {file:/home/s.savulchik/projects/foobar/project/}foobar-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to foobar (in build file:/home/s.savulchik/projects/foobar/)
bar
java.lang.Exception: bar exception
    at $df74d6ea1c7cfacc5a14$$anonfun$$sbtdef$1.apply(/home/s.savulchik/projects/foobar/build.sbt:8)
    at $df74d6ea1c7cfacc5a14$$anonfun$$sbtdef$1.apply(/home/s.savulchik/projects/foobar/build.sbt:8)
    at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:45)
    at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:45)
    at sbt.std.Transform$$anon$4.work(System.scala:64)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:244)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
[error] (*:bar) java.lang.Exception: bar exception
[error] Total time: 0 s, completed Mar 12, 2014 6:33:45 PM
```

Previously the question regarding this issue was asked at [StackOverflow](http://stackoverflow.com/questions/22350336/why-does-the-exception-thrown-in-triggered-task-isnt-reported-during-build).

**Comment by k4sbasia** [comment]
any chance that this can be related to - https://github.com/sbt/sbt-release/issues/55

**Comment by jsuereth** [comment]
Hmm, this may be by design.   probably up for discussion on how this should behave (cc @eed3si9n )

**Comment by eed3si9n** [comment]
You take your significant other out to a dinner. You've called in ahead of time to bring out a birthday cake triggered by the end of dinner. The dinner ends, but the birthday cake had thrown a ClassNotFoundException. The restaurant does not inform you. Because you know? By design. It was after all a secret cake. After looking around nervously for a few minutes, you pay the check and laugh about the cake on the way back to shell. In the scale of 1 to 10, how success was your dinner?

**Comment by jsuereth** [comment]
The situation is more like this:
- You take your significant other out to a dinner  (sbt> task)
- Your friends secretly arrange for a mariachi band to come play after your dinner is completed, but
  the band has an accident on the way to the dinner, so they don't make it.  (triggeredBy execution failure)

Was your dinner a success?   Do you even care if the band didn't make it?   Do you care that your friends wasted their money on the band?

**Comment by savulchik** [comment]
@jsuereth Initially the behavior was discovered when troubleshooting the build relying on [xsbt-filter](https://github.com/sdb/xsbt-filter) plugin that performs resources filtering `triggeredBy` copyResources task.

See https://github.com/sdb/xsbt-filter/blob/master/src/FilterPlugin.scala:

```
lazy val filterResourcesTask = filterResources <<= filter(copyResources, filterResources) triggeredBy copyResources
```

So I <b>expected</b> that one of my friends would arrange for a mariachi band to come play right <b>before</b> my dinner is completed (the build artifact is produced).

**Comment by jsuereth** [comment]
That's actually super dangerous behavior. "triggeredby" makes no guarantees on dependenceis for downstream tasks. It's likely that the thingmaking the jar will be reading the resource directory at the same time (in parallel) with filtering.

Not a good thing...

**Comment by savulchik** [comment]
@jsuereth indeed, sometimes I observe the described race condition when I get the jar with unfiltered resources. I should report the problem to @sdb .

**Comment by jsuereth** [comment]
@savulchik Please do.   In sbt, one of the core tenets is "All dependencies must be explicit".   If @sdb needs hooks for his plugin to work properly with the default settings, we can add those as needed.

**Comment by savulchik** [comment]
@jsuereth should I close this issue?

**Comment by jsuereth** [comment]
Actually, I think I'll turn this into a configuration feature request.

**Comment by jsuereth** [comment]
Unless of course you don't need it, in which case, please just close.

**Comment by jaytaylor** [comment]
I would very much like this configuration functionality to be available.

**Comment by wchen9911** [comment]
Stumped on this today. It would be good to have this clarified somewhere for "triggeredby".

@eed3si9n, great analogy. :+1:

**Comment by cuzfrog** [comment]
This config is useful. When, sometimes, you cannot change the task call, and have to hook some others to it.
