### ISSUE TITLE
sbt-0.13.2-M3 AutoImport of settings

### ISSUE THREAD

**Issue by huntc** [sbt/sbt#1188]
It appears that extending AutoPlugin doesn't automatically bring in AutoImport and thus settings have to be imported explicitly.

**Comment by eed3si9n** [comment]
Plugins not bringing all the names in I think is a good thing.

### current best practice guide

But we should standardize on the treatment of keys, but The current [Plugins Best Practices](http://www.scala-sbt.org/release/docs/Extending/Plugins-Best-Practices.html) says:

> ## Avoid namespace clashes
> 
> Sometimes, you need a new key, because there is no existing sbt key. In this case, use a plugin-specific prefix, both in the (string) key name used in the sbt namespace and in the Scala val. There are two acceptable ways to accomplish this goal.
> 
> ### Just use a val prefix
> 
> ``` scala
> package sbtobfuscate
> object Plugin extends sbt.Plugin {
>   val obfuscateStylesheet = settingKey[File]("Obfuscate stylesheet")
> }
> ```
> 
> ...
> 
> ### Use a nested object
> 
> ``` scala
> package sbtobfuscate
> object Plugin extends sbt.Plugin {
>   object ObfuscateKeys {
>     val stylesheet = SettingKey[File]("obfuscateStylesheet")
>   }
> }
> ```

### second object

I generally tend to use nested object as namespace like [`AssemblyKeys`](https://github.com/sbt/sbt-assembly/blob/9190eda522918444bca0af13d6dcbe877eb75753/src/main/scala/sbtassembly/Plugin.scala#L14).
In this case, we would need two objects one `AutoPlugin` and the other:

``` scala
package sbtassembly

object Import extends sbt.AutoImport {
  object AssemblyKeys {
    ...
  }
}

object Plugin extends sbt.AutoPlugin {
  import Import.AssemblyKeys._
  ...
}
```

### def autoImport: Any

I thought @jroper's `def autoImport: Any` idea wouldn't look good when you need to explicitly import it in `build.scala`, but `Import` is no better. (Note: You do need `val` or `lazy val` at the end or else you get "stable identifier required, but Foo.autoImport found"):

``` scala
trait AutoPlugin {
  val autoImport: Any
}
```

``` scala
package sbtassembly

object Import {
  type X = Int
  object AssemblyKeys {
    lazy val jarName  = "jarName" // TaskKey[String]("assembly-jar-name")
  }
}
object Plugin extends sbt.AutoPlugin {
  val autoImport = Import
}
```

This works in the REPL:

``` scala
scala> import Plugin.autoImport._
import Plugin.autoImport._

scala> import AssemblyKeys._
import AssemblyKeys._

scala> jarName
res0: String = jarName
```

The drawback compared to `AutoImport` mixin is that now you can't inherit from a plugin, but I don't know if anyone does that.

**Comment by huntc** [comment]
Why not just:

``` scala
object Plugin extends sbt.AutoPlugin {
  object AssemblyKeys extends sbt.AutoImport {
    ...
  }

  import AssemblyKeys._
  ...
}
```

The above is also compatible with our existing guidelines and plugin usage. It is also just a small migration for most plugins.

**Comment by eed3si9n** [comment]
@huntc To avoid namespace clashes. The purpose of wrapping in `AssemblyKeys` was to avoid prefix "assembly" in front of all keys in the Scala variable name. If `AssemblyKeys` automatically imports `jarName` the protection is gone.

**Comment by huntc** [comment]
Ah yes of course. So back to this:

``` scala
object Plugin extends sbt.AutoPlugin with sbt.AutoImport {
  object AssemblyKeys {
    ...
  }

  import AssemblyKeys._
  ...
}
```

...which is the equivalent of today. If people want finer grained control then they can use your `object Import` approach.

**Comment by huntc** [comment]
I'm concerned here about backward compatibility

**Comment by eed3si9n** [comment]
To maintain the perfect BC for both `build.sbt` and `build.sbt` mixing in `sbt.AutoImport` into `sbtassembly.Plugin` would essentially achieve the old behavior. And no changes needed to 0.13.2 code.

However, we should come up with a recommended handling of keys with 0.13.2, and "mix `sbt.AutoImport` in" I don't think is the best practice since it undoes what it achieved, which is not spew out all the guts.

If we have time to implement it, I kind of like `val autoImport` approach since we can get rid of `AutoImport` trait altogether. Otherwise, the best practice recommendation should be "second object" approach. This will preserve `build.sbt` compat.

**Comment by huntc** [comment]
I quite like having the key declarations as part of the plugin as it associates things nicely. Perhaps that is just a habit I've also got into, but I'm thinking that it would be nice to preserve as a convention going forward.

Would it be possible to have something like this:

``` scala
object Plugin extends sbt.AutoPlugin {
  object AssemblyKeys {
    ...
  }

  val autoImport = AssemblyKeys :: Nil

  import AssemblyKeys._
  ...
}
```

where autoImport accepts a sequence of things to import, and then instead of the statement implying `import AssemblyKeys._`, it is instead `import AssemblyKeys`.

What'd think?

**Comment by eed3si9n** [comment]
That could be tricky, since now I need to know the full path of all the references you list in there, including something like `1 :: Nil`. With `import Plugin.autoImport._` the name is always stable.

**Comment by huntc** [comment]
OK, then I guess what you suggest i.e.:

``` scala
package sbtassembly

object Import {
  type X = Int
  object AssemblyKeys {
    lazy val jarName  = "jarName" // TaskKey[String]("assembly-jar-name")
  }
}
object Plugin extends sbt.AutoPlugin {
  val autoImport = Import
}
```

...at least the things to import are still declared in the same file as the plugin itself.

Just one potentially crazy idea:

``` scala
package object sbtassembly {
  type X = Int
  object AssemblyKeys {
    lazy val jarName  = "jarName" // TaskKey[String]("assembly-jar-name")
  }

  object Plugin extends sbt.AutoPlugin {
    ...
  }
}
```

Thus anything declared for the package object would be imported by importing `sbtassembly._` right?
