### ISSUE TITLE
Support micro-libraries via source dependencies

### ISSUE THREAD

**Issue by Blaisorblade** [sbt/sbt#1193]
Git source dependencies could be a great feature for small-cost deployment of small libraries. But this requires quite some work, first of all in fixing bugs like #1120 or #895. Since @jsuereth there asks about use cases, I decided to write about what I imagined.

Imagine that you have essentially a gist, but you imagine people using it _without_ copy-pasting it. Now imagine you could just add **one** line to your build.sbt to depend on that gist using source dependencies. That would be awesome, wouldn't it? I can think of lots of small independent utilities which I'd like to reuse this way. And for half of them, the gist GUI would be perfect because users should not see a README, just some (commented) code.

Last time I tried that, I ended up with https://github.com/Blaisorblade/scrap-expr-boilerplate, which in turn contains further small utilities like [this](https://github.com/Blaisorblade/scrap-expr-boilerplate/blob/780a82482e05fa5af4606ef9b5119aff5ff9b86c/src/traversal/Extractor.scala). There's just too much overhead per-module to make this really seamless (OK, part of that is due to using Eclipse).

I imagine some of this overhead could be reduced via an appropriate SBT plugin, but part of this requires support in SBT itself.

There's one small problems with Github Gists, but I'd be OK with regular projects if needed.
One problem with gists is that they don't support directories, which means one can't store project/build.properties in there, so if you need anything in build.sbt you need to hope SBT doesn't evolve too much for your gist to keep working.

Another problem is that source dependencies cannot be treated as subprojects, AFAIK, but they are separate libraries. So even if your code keeps working on Scala 2.11, your gist doesn't, unless you setup cross-building with some plugin (which in turn requires).

Finally, the standard directory layout is not very helpful here, especially if I decide to have tests without a subdirectory but mark them by file name (again, for a gist).
But again, that can be changed via plugins.

If somebody else likes the idea, I think I could actually get started working on it soon-ish.

**Comment by jsuereth** [comment]
I feel like this, maybe, should be some kind of plugin where you can point at gists and locally cache them / wire into the build with `sourceGenerators`.

I'm not positive the source-level URI-dependency is the right feature given the things you mention.  We also may be taking source-dependencies a different direction (i.e. "Dependency" could be binary or source, where you can dynamically flip between the two depending on what you're doing).

I'm going to leave this open for a bit as we think through direction, but I feel what you want _probably_ means you want the micro-library compiled + delivered with the current project and treated as an external-to-the-project dependency (which is what source dependencies are right now).

**Comment by jsuereth** [comment]
I'm curious to see what you come up with, btw, so feel free to take a shot.

Also, for sbt, you may want to check out build loaders...

**Comment by Blaisorblade** [comment]
Thanks for the encouragement! I fear I got stuck trying to get a good set of requirements for this, so I didn't even get started. (That's my general problem, my PhD sucks enough resources out of me).

Thanks for the link to build loaders, they seem extremely powerful.

> I feel like this, maybe, should be some kind of plugin where you can point at gists and locally cache them / wire into the build with sourceGenerators.

I guess that might be good to get started, yes :-D.

**Comment by Blaisorblade** [comment]
> I feel like this, maybe, should be some kind of plugin where you can point at gists and locally cache them / wire into the build with sourceGenerators.

A correction: I wanted to support having macros in the library, so the library should be built as a separate project. But [custom builders](http://www.scala-sbt.org/release/docs/Extending/Build-Loaders.html#custom-builder) seem to allow creating new projects, so what I'd like seems technically possible.

**Comment by dwijnand** [comment]
I wonder how well @viktorklang's [Gistard](https://gist.github.com/viktorklang/a09aad920c1a4072cfe6) fixes your use case.

**Comment by viktorklang** [comment]
@dwijnand It's quite possible that Gistard fixes ALL use cases.

**Comment by Blaisorblade** [comment]
@dwijnand, @viktorklang: thanks for the pointer! That's very close to the idea I had. I'll look more/have to use this in anger to give more feedback, but for now I think it's best to close this issue.

**Comment by dwijnand** [comment]
Cool, I will too. Too often I'm copying extend-your-library classes for Any, Future, Collection.. I didn't realised Gistard might be what I've been searching for too.
