### ISSUE TITLE
ThisProject resolves to incorrect scope

### ISSUE THREAD

**Issue by dansanduleac** [sbt/sbt#1194]
## steps

**build.sbt**

``` scala
val proj2 = project

name := "proj1"
```

**proj2/build.sbt**

``` scala
name in ThisProject := "boo"
```

```
[info] Loading global plugins from C:\Users\dsandul\.sbt\0.13\plugins
[info] Loading project definition from C:\cygwin64\tmp\test\project
[info] Set current project to boo (in build file:/C:/cygwin64/tmp/test/)
> name
[info] proj2/*:name
[info]  proj2
[info] test/*:name
[info]  boo
```
## problem

The root project's name is set to "boo." In other words, when I use `ThisProject` as a scope for settings in a subproject, the settings get set on the root project instead.
## expectation

The root project's name remain as "proj1", and proj2's name is set to "boo."

**Comment by eed3si9n** [comment]
I reproduced it using 0.13.0 and 0.13.1, so it's not a regression.

```
boo> name
[info] proj2/*:name
[info]  proj2
[info] sbt-1194/*:name
[info]  boo
```

We might have to wait for 0.13.3 to get this fixed.

**Comment by dansanduleac** [comment]
Ow :(
