### ISSUE TITLE
How does sbt check the source file modification?

### ISSUE THREAD

**Issue by chenweiyj** [sbt/sbt#1199]
I just wonder how does sbt check whether a source file is modified when does the compilation. By checking the modification timestamp on the file system or any diff tool? I cannot find anything generated by sbt to record the last state of a file. Thanks.

**Comment by eed3si9n** [comment]
Hi @chenweiyj GitHub issues are used mostly to track bugs and tasks. Please open a question on StackOverflow for general questions. You might also want to check out zinc, which is responsible for incremental compilation.
- http://www.scala-sbt.org/release/docs/faq#how-do-i-get-help
- https://github.com/typesafehub/zinc
