### ISSUE TITLE
shell should display all evicted libraries on start up

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#1200]
This is inspired by [In SBT 0.13, does scalaVersion still control the version of scala used for compile, run and test?](http://stackoverflow.com/questions/22551430/), [sbt-lock](https://github.com/tkawachi/sbt-lock), and nescala talks around efforts in the field to control the deps pulled in by Ivy.
## problems

Currently the build user is at the mercy of conflict management by Ivy. So when it evicts Scala library or any other libraries, our usual response is.

![THIS IS IVY](https://user-images.githubusercontent.com/184683/27014552-103ae22c-4ec9-11e7-8839-ba2dfbe876e2.jpg)

(THIS IS IVY)

## what we could do

We have the knowledge of when eviction happens, so why not add a task to display the list of evicted libraries including scala-library.jar on the shell, and call it at starts ups and/or the on completion of `update`.

**Comment by jsuereth** [comment]
Interesting tidbits:
1.  If you use an "unmanaged" scalaInstance (from directory), we override the version Ivy grabs with it.
2. If you're using the same version of scala as the sbt-launcher is currently using, we override the jars from Ivy cache with the ones loaded by sbt.
3. If none of those are try, we just grab whatever Ivy found.

I can definitely get the error message in, but 1 + 2 throw some wrenches in place.

**Comment by jsuereth** [comment]
In the land of unintended side effects, a lot of Ivy details are getting leaked:

```
[info] Updating {file:/home/jsuereth/projects/sbt/diagnose/evicted/project/}evicted-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[warn] Some dependencies were evicted: 
[warn]  * org.scala-lang:scala-library:2.10.3
[warn]  * org.scala-lang:scala-library:2.10.1
[warn]  * org.scala-lang:scala-library:2.9.2
[warn]  * org.scala-lang:scala-library:2.8.2
[warn]  * org.scala-lang:scala-library:2.10.2
[warn]  * org.scala-lang:scala-library:2.9.3
[info] Set current project to foo (in build file:/home/jsuereth/projects/sbt/diagnose/evicted/)
> 
```

I think this will need to involve some sort of filtering API for which configurations to warn on, and possibly which modules we care about...

**Comment by jsuereth** [comment]
Ok, a first cut, eliciting comments: https://github.com/sbt/sbt/commit/453f90588d526f176adbd6865dfc376c36f6b005

**Comment by eed3si9n** [comment]
This is a nice start. Maybe we print the first 20 lines and say:

```
type "evicted" to get the full report.
```

It would be nice to know which version won, and what was the parent node of the dep.

```
[warn] Some dependencies were evicted: 
[warn]  * org.foo:something_core:0.10.0 (parent: org.bar.json) -> 0.11.0
```

Also an option to ignore third number change if the major version is zero, and ignore second number if the major version is non-zero might be useful.

**Comment by jsuereth** [comment]
we don't actually have enough info to know the parent at this point (it's erased)

**Comment by jsuereth** [comment]
Ok, so for 0.13.5, I think we implement this user story:

https://github.com/sbt/sbt/wiki/User-Stories%3A-Conflict-Warning#user-story-warn-if-scalaversion-is-no-longer-effective
