### ISSUE TITLE
provide some means of forcing scala-library version to scalaVersion

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#1201]
Similar to #1200, this is inspired by [In SBT 0.13, does scalaVersion still control the version of scala used for compile, run and test?](http://stackoverflow.com/questions/22551430/).
## problem

sbt 0.13.0 treats scala-library as a normal library, which means it's at the mercy of Ivy eviction policy. For example:

``` scala
scalaVersion := "2.10.2"

libraryDependencies += "com.typesafe.akka" %% "akka-actor" % "2.3.0"
```

In the linked StackOverflow question, `scalaVersion` was evicted and `fullClasspath` went to Scala 2.10.3 because Akka 2.3.0 depends on it. It might be desirable in some cases, but it's quite surprising.
## what we should do
#1200 addresses the notification part, but for Scala libraries in particular, we should provide a way of configuring whether to `force()` `scalaVersion` and perhaps default it to respect `scalaVersion` at all times. Something that adds:

``` scala
dependencyOverrides += "org.scala-lang" % "scala-library" % scalaVersion.value
```

**Comment by jpringle** [comment]
In many cases the "other" scala libraries tag along (e.g. specs2 expresses dependencies on scala-reflect, scala-library and scala-compiler).  Presumably bad things would happen if the versions of these libraries diverged, so a simple mechanism to force all to the value specified by scalaVersion would be welcomed.

**Comment by jsuereth** [comment]
I think if #1200 exists you should do the following:
1. Warn if the scalaVersion is overridden by dependencies.
2. List the code to FORCE the scala version in the warning.
3. Provide a simplified hook you can display in 2 if necessary.
