### ISSUE TITLE
Provide a mechanisms to log all tasks as they are run with a simple setting enablement.

### ISSUE THREAD

**Issue by sander24** [sbt/sbt#1209]
There are a bunch of things that play all together and produce a total effect of SBT builds being VERY hard to debug for a beginner (and probably also for intermediate) user. If you want your tool to gain more popularity, this certainly needs to be addressed.

One of the obvious things that would be easy but important to improve is how SBT prints what it is actually doing.

1) My personal opinion is that executed tasks should be printed to everybody, not just the few that type in the "--debug" key. But this is debatable, of course. I would suggest rather to provide an option to _hide_ them ("--quiet"?), rather than hiding them by default. I don't know a single other build engine that wouldn't by default at least give hints about what it is actually doing. For example, this is output of a full build of my project:

```
$ sbt clean package
Loading /media/linux-data/apps/sbt/bin/sbt-launch-lib.bash
[info] Loading project definition from /media/linux-data/dev/workspace-indigo/jr-license-server/project
[info] Set current project to license-server (in build file:/media/linux-data/dev/workspace-indigo/jr-license-server/)
[success] Total time: 0 s, completed Mar 25, 2014 1:35:23 PM

[warn] warning: [options] bootstrap class path not set in conjunction with -source 1.6
[warn] 1 warning
[success] Total time: 54 s, completed Mar 25, 2014 1:36:16 PM
```

This really looks like a "very quiet" mode, not the default mode. A developer normally wants to see what was executed, at least on a very high level.

2) The more serious problem is that, in the sbt-release context, I can't seem to be able to see _at all_ which tasks actually execute, even with "--debug". I'm talking about the case where tasks are wrapped into ReleaseSteps.

```
$ sbt --debug release
Loading /media/linux-data/apps/sbt/bin/sbt-launch-lib.bash
[debug] > boot
[debug] > reload
[debug] > sbtStashOnFailure
[debug] > onFailure load-failed
[debug] > loadp
[info] Loading project definition from /media/linux-data/dev/workspace-indigo/jr-license-server/project
[debug] Running task... Cancelable: false, check cycles: false
[info] Set current project to license-server (in build file:/media/linux-data/dev/workspace-indigo/jr-license-server/)
[debug] > sbtPopOnFailure
[debug] > resumeFromFailure
[debug] > iflast shell
[debug] > release
[debug] Running task... Cancelable: false, check cycles: false
 === Starting custom ReleaseStep ===
[debug] Running task... Cancelable: false, check cycles: false
[debug] Running task... Cancelable: false, check cycles: false
...
(omitted)
```

I can see a lot of internal tasks getting executed that don't really interest me, but I have absolutely _no_ way to see which tasks my own ReleaseSteps execute. (The corresponding ReleaseStep definition is this:

```
  val myReleaseStep : ReleaseStep = { st : State =>
    System.out.println(" === Starting custom ReleaseStep ===");
    Project.extract(st).runTask(sbt.Keys.clean, st)
    Project.extract(st).runTask(BuildSettings.customdist, st)
    st
  }
```

What one certainly would want here is to see instead of this ..

`[debug] Running task... Cancelable: false, check cycles: false`

.. this ..

`[debug] Running task 'clean' ... Cancelable: false, check cycles: false`

Thank you!
Sander.

**Comment by jsuereth** [comment]
The `runTask` methods are actually quite low-level APIs that don't log commands.  

If you want the ability to log which command is running, you should, instead, be logging commands.

``` scala
commands += Command.simple("release") { state: State =>
  "clean" :: "customdist" :: state
}
```

This _would_ log the command.  

I think perhaps what you want is one of two things:
1.  The sbt-release plugin to include some kind of logging/debugging of which release steps are running (including names for these)
2. Some mechanism to log tasks as they are running.

Note:  There's a hidden api (https://github.com/sbt/sbt/blob/0.13/main/src/main/scala/sbt/Keys.scala#L347-L348) that may become "public" in sbt 1.0 which would let you log every task as it is run.  We use it when doing profiling/performance work.

I recommend opening up an enhancement request for logging named release-steps in the sbt-release plugin.   I'll leave this open (but renamed) as a means to log all tasks being executed via some flag, if we can.

**Comment by sander24** [comment]
Thanks! I created a case under sbt-release as you suggested.

**Comment by alexbezhan** [comment]
Is there any temp workaround how to enable logging all the tasks executed ?

**Comment by jsuereth** [comment]
-Dsbt.task.timings=true will give you more than you wanted to know. This _should_ work with the release plugin, as it attacks the task engine itself, but no guarantees.

**Comment by alexbezhan** [comment]
Thanks, it helped.

**Comment by matanox** [comment]
@jsuereth I second the overall motivation, as described in the original post here, beyond the specific particulars of wrangling sbt-release. 

> The runTask methods are actually quite low-level APIs that don't log commands.

So this may make sense to change.

Maybe, if what -Dsbt.task.timings does could also be applied after sbt is already running, this _might_ be a replacement. Otherwise it is crucial for debugging or even following builds, that the logs say what task is being started in which project (and probably also configuration) scope.

**Comment by matanox** [comment]
The lack of this capability also means it is difficult to track the build's progress from outside of sbt or develop an alternative build UI (imagine a graphical display of dependencies, where one can see each step starting, finishing, and more).

**Comment by fommil** [comment]
:+1:

**Comment by fommil** [comment]
`-Dsbt.task.timings=true` is no good for automated testing because the information is all just written to stdout.

I've got a breadcrumb hack for asserting on this sort of thing, but it must be enabled per task, e.g.

https://github.com/fommil/sbt-big-project/blob/master/src/main/scala/BigProjectTestSupport.scala#L16

and, of course, the biggest problem is that this gives no information about **what** called a task, so its useless for tracking down overzealous tasks.

**Comment by fommil** [comment]
``` diff
diff --git a/main/src/main/scala/sbt/TaskTimings.scala b/main/src/main/scala/sbt/TaskTimings.scala
index 75be9d2..453795d 100644
--- a/main/src/main/scala/sbt/TaskTimings.scala
+++ b/main/src/main/scala/sbt/TaskTimings.scala
@@ -7,18 +7,26 @@ private[sbt] final class TaskTimings extends ExecuteProgress[Task] {
   private[this] val calledBy = new ConcurrentHashMap[Task[_], Task[_]]
   private[this] val anonOwners = new ConcurrentHashMap[Task[_], Task[_]]
   private[this] val timings = new ConcurrentHashMap[Task[_], Long]
+  private[this] val aggregate = new ConcurrentHashMap[Task[_], Long]
   private[this] var start = 0L

   type S = Unit

   def initial = { start = System.nanoTime }
   def registered(state: Unit, task: Task[_], allDeps: Iterable[Task[_]], pendingDeps: Iterable[Task[_]]) = {
+    // Dynamic dependencies are not listed here, nor is registered called for them
+    println(s"REGISTERING ${mappedName(task)} with deps ${allDeps.map(mappedName)}") // pendingDeps doesn't say much
     pendingDeps foreach { t => if (transformNode(t).isEmpty) anonOwners.put(t, task) }
+    aggregate.put(task, System.nanoTime)
   }
   def ready(state: Unit, task: Task[_]) = ()
-  def workStarting(task: Task[_]) = timings.put(task, System.nanoTime)
+  def workStarting(task: Task[_]) = {
+    println(s"STARTING ${mappedName(task)}")
+    timings.put(task, System.nanoTime)
+  }
   def workFinished[T](task: Task[T], result: Either[Task[T], Result[T]]) = {
     timings.put(task, System.nanoTime - timings.get(task))
+    aggregate.put(task, System.nanoTime - aggregate.get(task))
     result.left.foreach { t => calledBy.put(t, task) }
   }
   def completed[T](state: Unit, task: Task[T], result: Result[T]) = ()
@@ -28,11 +36,21 @@ private[sbt] final class TaskTimings extends ExecuteProgress[Task] {
       println("Total time: " + (total * 1e-6) + " ms")
       import collection.JavaConversions._
       def sumTimes(in: Seq[(Task[_], Long)]) = in.map(_._2).sum
-      val timingsByName = timings.toSeq.groupBy { case (t, time) => mappedName(t) } mapValues (sumTimes)
-      for ((taskName, time) <- timingsByName.toSeq.sortBy(_._2).reverse)
-        println("  " + taskName + ": " + (time * 1e-6) + " ms")
+
+      def printTimings(t: ConcurrentHashMap[Task[_], Long]): Unit = {
+        val timingsByName = t.toSeq.groupBy { case (t, time) => mappedName(t) } mapValues (sumTimes)
+        for ((taskName, time) <- timingsByName.toSeq.sortBy(_._2).reverse)
+          println("  " + taskName + ": " + (time * 1e-6) + " ms")
+      }
+      println("Task times:")
+      printTimings(timings)
+
+      println("Graph times:")
+      printTimings(aggregate)
     }
   private[this] def inferredName(t: Task[_]): Option[String] = nameDelegate(t) map mappedName
   private[this] def nameDelegate(t: Task[_]): Option[Task[_]] = Option(anonOwners.get(t)) orElse Option(calledBy.get(t))
-  private[this] def mappedName(t: Task[_]): String = definedName(t) orElse inferredName(t) getOrElse anonymousName(t)
+  private[this] def mappedName(t: Task[_]): String = {
+    definedName(t) orElse inferredName(t) getOrElse anonymousName(t)
+  }.replaceAll(raw"\{[^{}]+\}", "") // removes the baseDirectory
 }
```

**Comment by fommil** [comment]
I'd still like to know how to know when a `Task` dynamically invokes another `Task` (and print out the names of both). Printing out this information is very hard to interpret, because the dependency chain is lost. What I **really** want is to have an immutable copy of the entire dependency graph after all the computations have been done.

BTW, to try to reduce concurrency, I use

```
concurrentRestrictions in Global := Seq(Tags.limitAll(1))
```

**Comment by fommil** [comment]
I've updated the diff to include what I'm calling "graph times". These have the potentially to be totally random or very useful. I used these timings to find the big tasks that were pulling in lots of other tasks, and were therefore potential candidates for converting to dynamic tasks with a cache.

**Comment by matanox** [comment]
I humbly think if we can't go through such a process with relative ease, it kind of negates the notion of scalability around scala (as in ― project scalability). So I believe this aught to be pinned down inside sbt.

**Comment by fommil** [comment]
if there was a way to detect when a Task depends on another Task (especially dynamically) and hook it in with these numbers, we could just generate the graph and persist it (e.g. JSON). Then there would be no need to ever hack the sbt build again for this sort of thing.

**Comment by jrudolph** [comment]
I published a first version of my [sbt-optimizer plugin](https://github.com/jrudolph/sbt-optimizer) which is very similar to `sbt.task.timings` but provides a nice timeline visualization of task runs.

**Comment by fommil** [comment]
Given that this seems to be possible from a plugin, I propose closing this ticket. I'll port over my code above the plugin after understanding exactly which magical incantation Johannes has used!

**Comment by eed3si9n** [comment]
This is now fixed with super shell - https://github.com/sbt/sbt/pull/4396
