### ISSUE TITLE
Nashorn script engine not found when running under sbt

### ISSUE THREAD

**Issue by ghost** [sbt/sbt#1214]
Hi,
I have previously created an issue at Play project but it seems to be more sbt related.
The issue is the following.
I have just upgraded to Java 8 and I want to use Nashorn. Simply put, I have two projects, one scala lib and a play project to have a GUI. 

I haven't seen the issue straight away because the scala lib uses maven but when I try to load nashorn after running play with sbt -> run, the engine is not found and if I try to do it manually (new NashornScriptEngineFactory) I get a ClassDefNotFound. 

I have created a very simple test from the basics scala project. 

The code I have added is the following

```
"Nashorn" should "be available" in {
    import javax.script._
    val manager = new ScriptEngineManager()
    val engine = manager.getEngineByName("nashorn")
    engine should not be null
  }
```

For play, when I create a distribution and run it from outside sbt everything works and nashorn is found.

**Comment by jsuereth** [comment]
Does this work if you fork your tests?  `fork in Test := true` ?

**Comment by ghost** [comment]
wow nice one!
Yes it does work. could you explain please? How can I make it so it will work for my play project as well ?

**Comment by jsuereth** [comment]
Looks like some kind of classloader issue.   Do you know how `manager.getEngineByName("nashorn")` is looking for its classes?  You may need to give it `this.getClass.getClassLoader` so it's using the right reflection.

This is because sbt is loading your play application in a classloader directly with the build.  Allows it to communicate back/forth with play directly, rather than over some process hook.

**Comment by ghost** [comment]
It seems to work for the simple scala test.
But it doesn't seem to work for Play. 
I looked at the code and this is the classloader it uses: 

```
ClassLoader ctxtLoader = Thread.currentThread().getContextClassLoader();
```

this.getClass.getClassLoader does not seem to work for my case in Play.

**Comment by ghost** [comment]
What I don't understand is why the Build classloader does not have the classes for nashorn loaded.

**Comment by jsuereth** [comment]
I don't either.  ANd context classloader may be null. I'm not sure if that's correctly set.  When using play with sbt launchers, I tend to manually set that sucker, e.g:

https://github.com/typesafehub/activator/blob/master/ui/app/activator/UIMain.scala#L110

**Comment by ghost** [comment]
but then I don't know which classloader should I use? Which classloader do you use usually ?

**Comment by jsuereth** [comment]
In that case the one that has play on it....

**Comment by ghost** [comment]
So this is why you use the NettyServer one is that it? Let me try and I let you know. Thank you very much !

**Comment by ghost** [comment]
Ok so the issue is resolved if I pass "null" as a parameter. If someone could explain this to me it would be very nice! Also I will let this open as it is still an issue in my opinion.

**Comment by jsuereth** [comment]
I think "null" means you either use the boot classpath or the system classpath (the one you pass to the `java` executable).

This kind of wonkyness is actually common in classloader land. Lots of assumption about usage that differ across every project.   I think perhaps you may want to follow this up with the nashorn folks about how they WANT you to use them inside a classloader.

**Comment by ghost** [comment]
if you pass the classloader as null, it uses another method to load the factories

```
if (loader != null) {
                sl = ServiceLoader.load(ScriptEngineFactory.class, loader);
            } else {
                sl = ServiceLoader.loadInstalled(ScriptEngineFactory.class);
            }
```

But I still have issues as it cannot find another class now. I have this classloading thing ...

**Comment by eed3si9n** [comment]
This looks to be resolved, so I'm closing this.

**Comment by som-snytt** [comment]
This came up on StackOverflow.  It makes me nostalgic for the old days of debugging ant class loaders.  Someday I'll use sbt and scalatest enough to be more helpful.

http://stackoverflow.com/a/23575337/1296806

**Comment by montaro** [comment]
I had the same problem with SBT project, and this worked for me

```
val engineManager: ScriptEngineManager = new ScriptEngineManager(null)
//Or
val engineManager: ScriptEngineManager = new ScriptEngineManager(getClass.getClassLoader)
```

**Comment by MaggieLeber** [comment]
We're seeing this same probelm with Activiti inside Play under `sbt`, but only on OSX. Linux and Windows are OK. I think it's classpath related too...connected somehow with where `Nashorn.jar` is packaged in JDK 8

**Comment by SethTisue** [comment]
@MaggieLeber this might help https://github.com/playframework/playframework/pull/3420

**Comment by MaggieLeber** [comment]
@SethTisue Thanks, that does look potentially helpful; interesting that we only seem to hit it on OSX. 

Now if I could only get https://issues.scala-lang.org/browse/SI-8422 fixed maybe I could get my Activiti users off of JavaScript altogether and writing their `<scriptTask>`s in Scala. Pushing them onto Groovy makes me sad.  

Scala 2.11 is supposed to support JSR-223, but it's broken.

**Comment by SethTisue** [comment]
re JSR 223, let's discuss further at https://issues.scala-lang.org/browse/SI-8422
