### ISSUE TITLE
docs: code samples are hard to read

### ISSUE THREAD

**Issue by numerodix** [sbt/sbt#1216]
Whenever I view pages on http://www.scala-sbt.org/ I find myself zooming in because the font in the code samples is both small and so light it contrasts poorly against the background. The same goes for "code formatted" inline strings (as opposed to blockquotes).

**Comment by eed3si9n** [comment]
+1 on improving the contrast.
What do you think about white background + GitHub-like formatting like I'm doing with my pamflet docs? - http://eed3si9n.com/tetrix-in-scala/akka.html

**Comment by numerodix** [comment]
Your page is nice and readable and I think this would be a big improvement
over the current style.

2014-03-26 17:23 GMT+01:00 eugene yokota notifications@github.com:

**Comment by eed3si9n** [comment]
The new site is up with improved code highlighting. See http://www.scala-sbt.org/0.13/docs/Artifacts.html for example.
