### ISSUE TITLE
Plugins with autoImport require an explicit import themselves

### ISSUE THREAD

**Issue by huntc** [sbt/sbt#1217]
When using the new autoImport feature, the encapsulating plugin doesn't get imported also. For example:

``` scala
object Import {

  object WebKeys {
...


object SbtWeb extends AutoPlugin {

  val autoImport = Import
```

The `WebKeys` become available for importing, but the `SbtWeb` plugin itself still requires an explicit import.

**Comment by jsuereth** [comment]
Not sure you saw, but @eed3si9n caught this when he was writing the docs for 0.13.5.   Should be fixed before final.

**Comment by huntc** [comment]
Thanks. Yep, just capturing here to ensure that it doesn't get lost. :-)

**Comment by huntc** [comment]
Awesome. Thanks! Do you have a nightly or build release available?

**Comment by eed3si9n** [comment]
We should cut M2 soon.

**Comment by huntc** [comment]
Great. However I thought you'd be using sbt-git to publish to bintray by now. ;-)

**Comment by jsuereth** [comment]
Not yet :).  Can't wait to migrate at some point.

Nightlies fire around 11pm EDT IIRC.
