### ISSUE TITLE
Reducing PermGen usage in sbt

### ISSUE THREAD

**Issue by cunei** [sbt/sbt#1223]
I tracked down a PermGen leak in sbt, which can easily be worked around (although other PermGen leaks may exist).

The full story is below, but in short object finalizers are not called frequently enough by the VM (in jdk 6 and 7), causing classloaders to survive long past their time.

The solution is adding after the parts of runTask that create a new classloader, in order to launch Scala or other utilities, the sequence:

```
{ System.gc(); java.lang.System.runFinalization(); System.gc() }
```

That must be done from an enclosing stack frame that no longer contains any reference, direct or indirect, to the generated classloader (note that escape analysis was not generally on by default in jdk 6).

The complete, albeit condensed explanation, is:
- Each time sbt invokes the Scala compiler, by creating a new classloader, the classloader is not released.
- the classloader is kept in the heap by means of a chain of links involving weak references. In particular, when the garbage collector runs and frees the referent from a weak reference, the referred instance may still being tracked if some finalization is still pending.
- if finalization is not run promptly, the classloader cannot be freed, and its permgen cannot be released.
- file descriptors, like FileInputStream or JarFile, are all finalizable, and sbt uses a lot of them.
- the jdk 6 and 7 are quite lazy when running finalizers. If there is still heap space, they will not rush to complete finalization in order to free memory. The VMs will not notice that PermGen is slowly running out.
- as a net result, I saw cases in which there are more than 47'000 file descriptors lying idle in the system, indirectly keeping classloaders from being reclaimed, and leading some code to crash despite being given 1GB of PermGen.
- adding an explicit invocation to runFinalization(), following the exact sequence described above, will solve the problem. The first gc() causes the referent of the WeakReferences to be released, and tracks the newly freed finalizable objects. The runFinalization() call forces the jvm to deal with those instances immediately. Finally, the second gc() will deallocate them. Once the file descriptors are freed, the weak references are also freed, the classloader is freed, and therefore its PermGen space is in the end also freed.

More in general,  when using together weak references, multiple classloaders, and files (even if you close them), manual invocations to runFinalization() will be needed, or you will get leaks that may show up as "Too many files" or "PermGen Error". 

Java 8 replaces the PermGen with a "Meta" space, but it is still subject to leaks. However, it calls finalizers more promptly, which avoids this issue. Java 6 and Java 7 are both affected.

**Comment by eed3si9n** [comment]
This explains why sbt has been PermGen hungry. Nice detective work!

**Comment by ijuma** [comment]
If Java 8 doesn't suffer from the issue, it would be nice to only trigger the GCs and finalizers if Java < 8.

**Comment by cunei** [comment]
Java 8 seems to be a little more eager to finalize, but there is still no guarantee the finalizer thread will process all the instances on time: calling runFinalization() explicitly will make it certain.

**Comment by ijuma** [comment]
One thing to remember is that two full GCs can be quite costly for decently-sized heaps. Some measurement should probably be done.

**Comment by jsuereth** [comment]
True.  I think running it when a command is "done" may be ok though, as this is usually when the human is going to do something else, so it shouldn't be significantly noticable to observers....

**Comment by ijuma** [comment]
Perhaps. Please don't forget about continuous execution though.

**Comment by jsuereth** [comment]
@ijuma don't you think it's more important in continuous execution to ensure you don't leak permgen?

**Comment by ijuma** [comment]
@jsuereth given that I have never run out of PermGen when using SBT for years (with typical settings of -XX:MaxPermSize=192m), certainly not for me. Now, making continuous compilation even  slower than it is already, that would be very painful for me.

**Comment by jsuereth** [comment]
yeah, i don't want to make it slower for you, BUT I'm still amazed you never ran out of permgen....

**Comment by jsuereth** [comment]
@ijuma A second idea I have:  We could just run the gc/finalizers on project reload, because there we _know_ we have to dump a few classloaders.

~ foo would be unaffected....

**Comment by ijuma** [comment]
We run tests in a forked JVM, that probably helps. Doing it on project reload is more conservative indeed. In any case, if this is affecting many people, I am not opposed to the proposed solution since there's a way to disable it and it's not enabled by default in Java 8 (which is what we are using now).

**Comment by fommil** [comment]
referencing back to https://issues.scala-lang.org/browse/SI-9632

**Comment by fommil** [comment]
I'm still seeing this problem on windows 7 (Java 7), even with the suggested hacks above.

A reference to one of my `exportJars` still exists, and inspecting a heap dump shows that a JarFile reference is being held in an object that is pending finalization.

Even manually calling

```
 eval System.runFinalization()
```

doesn't force the finalizers to run.

**Comment by fommil** [comment]
could it be that the finalizers are in a different classpath? Just before we discard an old classpath, can we run its finalizers?

**Comment by fommil** [comment]
Those of a sensitive disposition should close their eyes...

``` java
public abstract class Reference<T> {
...
    private static Reference pending = null;
...
```

we could get that by reflection and then go through and run the finalizers ourselves if they are `JarFile`.

**Comment by fommil** [comment]
reporting in... this always seems to return `null` for `pending`, so I can never get the list of objects. This is a magical part of the JVM and it doesn't necessarily play by the rules.

``` scala
        import java.lang.ref.{Reference, FinalReference}
        import java.util.jar.JarFile
        val pendingField = classOf[Reference[_]].getDeclaredField("pending")
        pendingField.setAccessible(true)
        val referentField = classOf[Reference[_]].getDeclaredField("referent")
        referentField.setAccessible(true)
        val nextField = classOf[Reference[_]].getDeclaredField("next")
        nextField.setAccessible(true)
        val finalizeMethod = classOf[Object].getDeclaredMethod("finalize")
        finalizeMethod.setAccessible(true)

        var pending = pendingField.get(null).asInstanceOf[Reference[_]]
        while (pending != null) {
          // class not accessible...
          //if (pending.isInstanceOf[FinalReference[_]]) {
          if (pending.isEnqueued()) {
            val referent = referentField.get(pending)
            if (referent.isInstanceOf[JarFile]) {
              log.info(s"trying to manually finalize $referent")
              Try(finalizeMethod.invoke(referent))
            }
          }
          pending = nextField.get(pending).asInstanceOf[Reference[_]]
        }
```

**Comment by fommil** [comment]
(you can open your eyes now).

I am working around this by using java 8 to run sbt. But that, of course, conflicts with https://github.com/sbt/sbt/issues/1519 because the project needs a specific version of `javac` 7, so I've created my own launch script that has the correct `javac.exe` on `PATH` but is launched with a specific java 8 `java.exe`
