### ISSUE TITLE
Sync.apply fails on duplicate directories

### ISSUE THREAD

**Issue by samskivert** [sbt/sbt#123]
I tried adding my source directory to unmanagedResourceDirectories and it failed, complaining that both my source directory and my resource directory contained the same directories (e.g. com/foo in src/main/scala/com/foo/Bar.scala and com/foo in src/main/resources/com/foo/Bar.properties).

Since duplicate directories are to be expected, and present no problems, Sync should probably allow them.

**Comment by harrah** [comment]
fixed in https://github.com/harrah/xsbt/commit/eb31cc025a3728877a69e3e451f9f21489910df0
