### ISSUE TITLE
sbt 0.13.5-M2 can't publish to artifactory

### ISSUE THREAD

**Issue by jsuereth** [sbt/sbt#1233]
When it tries to publish, you get a "XYZ exists and overwrite=false" error.  This is because it's trying to push a checksum (md5/sha1) _after_ ivy has autogenerated it, and the logic hits  files before publishing.

cc> @huntc.

**Comment by huntc** [comment]
Thanks Josh. This is the issue I previously ask for citing a moment ago. All good.
