### ISSUE TITLE
SBT repeatedly compiles package-info.java files

### ISSUE THREAD

**Issue by samskivert** [sbt/sbt#124]
Somehow the compilation of package-info.java files does not cause SBT to believe that they are up-to-date, so it recompiles them on every invocation of compile.

**Comment by harrah** [comment]
Please provide the sbt version and steps to reproduce.  (I don't see a problem for a basic example.)

**Comment by samskivert** [comment]
Oops, I was using 0.10.0 and it seems to be fixed in 0.10.1.
