### ISSUE TITLE
Sbt hangs at loading global plugins

### ISSUE THREAD

**Issue by gkossakowski** [sbt/sbt#1251]
Sbt 0.13.5-SNAPSHOT hangs while loading global plugins. An empty project is enough to reproduce it:

```
Grzegorzs-MacBook-Pro:sbt-empty grek$ echo "sbt.version=0.13.5-SNAPSHOT" > project/build.properties
Grzegorzs-MacBook-Pro:sbt-empty grek$ sbt
[info] Loading global plugins from /Users/grek/.sbt/0.13/plugins
// hangs here
```

I attached the profiler and noticed that it hangs in `EvaluateTask.runTask` method. It recurses by accident: wrong overload is chosen. The fix is on its way.

**Comment by jsuereth** [comment]
Thanks @gkossakowski !
