### ISSUE TITLE
SLF4J Bug With Scalatra

### ISSUE THREAD

**Issue by crunchman** [sbt/sbt#1256]
On Windows-7 Terminal (cmd.exe):

> A:\Desktop\new>g8 scalatra/scalatra-sbt
> organization [com.example]:
> name [My Scalatra Web App]: MyApp
> version [0.1.0-SNAPSHOT]: 1
> servlet_name [MyScalatraServlet]: MyServlet
> package [com.example.app]:
> scala_version [2.10.3]: 2.10.4
> scalatra_version [2.2.2]: 2.2.2
> 
> Template applied in .\myapp

Changed sbt-version in build.properties to 0.13.1
On terminal again :

> A:\Desktop\new>cd myapp
> A:\Desktop\new\myapp>sbt
> [info] Loading project definition from A:\Desktop\new\myapp\project
> [info] Updating {file:/A:/Desktop/new/myapp/project/}myapp-build...
> [info] Resolving ...
>   [info] Resolving ...
> ...
> [info] Done updating.
> compile
> [info] Generating A:\Desktop\new\myapp\target\scala-2.10\resource_managed\main\rebel.xml.
> [info] Compiling Templates in Template Directory: A:\Desktop\new\myapp\src\main\webapp\WEB-INF\templates
> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> [info] Compiling 5 Scala sources to A:\Desktop\new\myapp\target\scala-2.10\classes...
> [info] 'compiler-interface' not yet compiled for Scala 2.10.4. Compiling...
> [info]   Compilation completed in 15.279 s
> [success] Total time: 35 s, completed 10.04.2014 23:12:05

The SLF4J-Error occurs on compile and run. I use sbt-assembly as a plugIn.
After assembling to a fat jar and running that fat jar, the SLF4J-Problem disappears.
Conclusively, it is a sbt bug.

**Comment by cunei** [comment]
The message is informational, and apparently not related to sbt, but to the scalatra template. There are mentions of it on many forums, including: https://gist.github.com/geeksville/6214944 where they comment: "yep - that's all good - you can ignore that warning".
If you try "container:start", then "browse", the example should work normally. If you see a message that says `java.lang.ClassNotFoundException: javax.servlet.jsp.JspPage`, you will need to update the plugin line for "scalatra-sbt" in `project/plugins.sbt` to version 0.3.5.
I am closing this ticket, as it refers to slf4j usage. Please feel free to reopen if the people supporting slf4j and scalatra find that sbt is at fault.
