### ISSUE TITLE
JLine Bug

### ISSUE THREAD

**Issue by crunchman** [sbt/sbt#1257]
Given the following project structure:

```
- new
|----project
|----src
|----|----main
|----|----|----scala
|----|----|----|----Main.scala
-build.sbt
```

where Main.scala holds:

```
object Main {
    def main(args: Array[String]) {
        val reader = new jline.console.ConsoleReader()
        var line = ""
        println("Started")
        while ({line = reader.readLine();  line != null}) {
            if (line equalsIgnoreCase "quit") {
               println("Exiting")
               return
            }
        }
    }
}
```

and build.sbt holds:

```
name := "new"

version := "1"

scalaVersion := "2.10.4"

fork in run := true

libraryDependencies += "jline" % "jline" % "latest.integration"
```

Running on a Windows-7 terminal (cmd.exe)

```
A:\Desktop\new>sbt
[info] Set current project to new (in build file:/A:/Desktop/new/)
> compile
[info] Compiling 1 Scala source to A:\Desktop\new\target\scala-2.10\classes...
[success] Total time: 4 s, completed 10.04.2014 23:26:58
> run
[info] Running Main
[info] Started
```

--------- no possibility to see what is typed into the terminal, neither any reaction if "quit" has been entered. Only possible way to stop the run is to terminate the whole sbt process. Again, after using sbt-assembly as a plugin, creating the fat jar and running it
by "java -jar ..........." it works as expected.
 Therefore it is a sbt bug.

**Comment by jsuereth** [comment]
Do you know which version of jlin is actually being used?

sbt itself uses jline 2.11, so most likely you're running into an issue where your jline is conflicting with ours.  

We have the following codez in our codebase to deal with jline conflicts between, e.g. scalac + sbt:

``` scala
jline.TerminalFactory.reset
JLine.terminal.init
```

You may need to do something similar

**Comment by jsuereth** [comment]
Also, if this is windows, you should check the JLine options passed in sbt (-Djline.terminal).  I believe windows has a lot of oddities we had to cover that may differ between our use of jline and your terminal.

**Comment by benhutchison** [comment]
I think there is a real, non-windows-specific problem here which has been missed. I am seeing much the same behavior on Mac OSX. 

To me, the root problem is that, when I fork a run process from SBT, and try to readLine input in that process, I get back null. Seems to happen with JLine ConsoleReader and stdin. Which signals a closed input stream. In turn, this makes it difficult to communicate with local webapps started in dev mode from SBT via run.

In my case, I want to do something like "> ;run;~copyResources" and signal to the forked run process to shutdown by typing something. Given that the output of the forked process goes to SBT, it might be nice to send the console input to the subprocess also. Or at least be able to opt-in to that behavior..?

**Comment by eed3si9n** [comment]
I was looking at another JLine issue recently and figured I should drop a note on this issue.

@cunei identified that there's JLine interference starting Scala 2.11.2 and up. See scala/scala#3882. Here are two workaround that worked for me.

### restoring the terminal using try-finally

``` scala
    val reader = new ConsoleReader()
    try {
      ....
    } finally {
      reader.shutdown
      reader.getTerminal.restore
    }
```

### forking

``` scala
fork in run := true
outputStrategy := Some(StdoutOutput)
connectInput in run := true
```

Note `outputStrategy` and `connectInput in run` settings need to be set.
