### ISSUE TITLE
thisProject

### ISSUE THREAD

**Issue by ahjohannessen** [sbt/sbt#1258]
I have made a sbt-plugin that is used to bootstrap various projects in our organization. The sbt-plugin contains various useful common generic settings for things such as scalac, basic test dependencies and also more specific things such as publishing and resolvers tied to our organization.

In order to use this in a fresh project I define the following:

In ./project/plugins.sbt:

``` scala
resolvers += Resolver.url("n", url("u"))(Resolver.ivyStylePatterns)

addSbtPlugin("a.b.c" %% "c-sbt" % "0.0.1")
```

In ./build.sbt:

``` scala
name := "ohhi"

version := "x.y.z"

commonSettings
```

This works perfect except for when I publish artifacts, because I wish to use a project `id` that I define. In our case it is common that `id == name`.

This is trivial to do in a build.scala, but I do not seem to be able to set the project `id` in the .sbt file. Is there some way to accomplish this?

**Comment by cunei** [comment]
If you are using sbt 0.13, project ids can be specified within an .sbt file by using the syntax described at the beginning of this page: http://www.scala-sbt.org/release/docs/Getting-Started/Multi-Project.html

I hope that can be of help with your query. I am closing this ticket, however, as this is not actually an sbt bug description or a request for enhancement. General support for sbt is best obtained via StackOverflow, where you can post general usage questions.

**Comment by ahjohannessen** [comment]
cunei, what I was after is more like:

``` scala
id := "id1"
```

and not `lazy val id1 = project`

**Comment by jsuereth** [comment]
You can do: 

``` scala
lazy val project = Project("id1", file("."))
```

Or what not.  We should probably fix it to be shared.

**Comment by eed3si9n** [comment]
I asked @ahjohannessen to create this ticket on twitter since I thought this could relate to improving ux (including auto plugins etc), we've talked about `self` reference.

**Comment by jsuereth** [comment]
@eed3si9n If you have time to chat, I have a proposal around that now (although not a self reference).

**Comment by jsuereth** [comment]
We're going to investigate something like this in relation to #1213  

I'm adding a quick proposal there.

**Comment by jsuereth** [comment]
Here's the proposal: https://github.com/sbt/sbt/issues/1213#issuecomment-40234140

I may start further comments on this case.

**Comment by dwijnand** [comment]
This ticket is very confusing (and old). Is it about "thisProject" or about project id?

I'm going to close a blind eye and assume the root issue was dealt with in #1213.
