### ISSUE TITLE
RFE: exclude(rules: Seq[ExclusionRule])

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#1259]
this method currently takes a varargs, which makes it really ugly to call when one already has a `Seq` at hand.

**Comment by indrajitr** [comment]
I am guessing you mean `excludeAll(rules: ExclusionRule*)`.
Are you finding `excludeAll(seq:_*)` inadequate?

AFAIR, @harrah opined in favor of one form to avoid too many variations.

**Comment by fommil** [comment]
yeah, that's the one... I have this:

``` scala
val bad = Seq(
    ExclusionRule(name = "log4j"),
    ExclusionRule(name = "commons-logging"),
    ExclusionRule(organization = "org.slf4j"),
    ... so many people who don't like standard APIs ...
  )
```

and that means it's messy to use.

I'm actually thinking about applying this in a map to everything implicitly... nothing good ever came out of transitive dependencies on java logging frameworks. Then I can explicitly add logback and all the SLF4J wrappers to the runtimes.

**Comment by eed3si9n** [comment]
Hi Sam. sbt project currently uses issues for confirmed bugs only. See https://github.com/sbt/sbt/blob/0.13/CONTRIBUTING.md. Please bring this up in StackOverflow or sbt-dev list.

**Comment by fommil** [comment]
ok, but that's very non-standard on github and you'll probably spend a lot of your time posting comments like this.

I suspect you'll miss a lot of feature requests doing it this way: the mailing list is in retirement and StackOverflow is very aggressively NOT a discussion forum. "I'd like to have X" style questions are simply not tolerated there.

**Comment by eed3si9n** [comment]
I'm fairly new at running sbt project, so for now I'm keeping it the way it's been set before. The old mailing list was retired but [sbt-dev](https://groups.google.com/forum/#!forum/sbt-dev) mailing list is active. I'd love to keep issues open for suggestions, and I do that for most of my personal projects (except sbt-assembly), but once the user/contributor ratio reaches certain point it quickly becomes unmanagable.

**Comment by fommil** [comment]
cool, I see. You can still hide them from view with tags or milestones: possibly even add a strategic priority to feature requests (and bump them up if more people +1 the ticket). A cull every few months - e.g. after the next release features have been decided - isn't so onerous.
