### ISSUE TITLE
plugins require explicit libraryDependencies to get jars from update

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#1260]
I was surprised that `update.value.configuration("runtime-internal")` doesn't have the plugin's dependencies (as listed in its ivy artifact) included. Is there a reason for this, or is it a bug?

In any case, I had to work around this by doing an explicit `libraryDependencies += deps` in the settings for the plugin, which adds the necessary jars to the update list.

**Comment by eed3si9n** [comment]
Hi Sam. sbt project currently uses issues for confirmed bugs only. See https://github.com/sbt/sbt/blob/0.13/CONTRIBUTING.md. Please bring this up in StackOverflow or sbt-dev list.

**Comment by fommil** [comment]
I just realised why I created this. In my project lions-share I have to list my plugin's dependencies in its source code, even though I'm depending on a module in the same project:

https://github.com/fommil/lions-share/blob/master/sbt/src/main/scala/LionPlugin.scala#L25

This makes it **really** hard to test staging versions prior to release, as well as making it hard to maintain.

**Comment by fommil** [comment]
I guess this is probably just tough luck if you want to do it, the current setup is actually fairly sensible and it only seems complex because of the nature of my project.
