### ISSUE TITLE
Non-static annotations might cause spurious recompilations

### ISSUE THREAD

**Issue by gkossakowski** [sbt/sbt#1261]
Pickler in Scala compiler strips out all non-static annotations on types. This leads to different view of the symbol depending on whether it's coming from source code or from unpickling. Experience shows, that this is almost always breaking incremental compilation.

I don't have time to investigate it further so I just lodged this ticket as a reminder in case somebody is working on API extraction in incremental compiler.

Inspired by https://issues.scala-lang.org/browse/SI-8497

**Comment by gkossakowski** [comment]
//cc @adriaanm

**Comment by jvican** [comment]
This is fixed in https://github.com/adriaanm/sbt/commit/dab9b9e19670ca2da9fffd350c5cbb181e7618a5, which is merged upstream in Zinc. Let's close it @eed3si9n.
