### ISSUE TITLE
0.13.2: Error during sbt execution: No Scala version specified or detected

### ISSUE THREAD

**Issue by cowboy129** [sbt/sbt#1264]
I launch sbt in my projects, it works well with `sbt.version=0.13.1`, but failed with 0.13.2.

```
$sbt
Error during sbt execution: No Scala version specified or detected
```

I'm in Mac OS X and use `brew install sbt` to install sbt. 

```
$sbt --version
sbt launcher version 0.13.2
```

**Comment by jsuereth** [comment]
Duplicate of #1117
