### ISSUE TITLE
sbt deleting cross-build classes directory without provocation

### ISSUE THREAD

**Issue by paulp** [sbt/sbt#1267]
## steps

```
$ cat project/build.properties
sbt.version=0.13.2
$ cat build.sbt               
name := "foo"

scalaVersion := "2.10.4"

crossScalaVersions := List("2.10.4", "2.11.0-RC4")
$ cat foo.scala 
package foo

object Foo extends App {
  println("yay")
}
```

```
% ls -1d target/*/classes
target/scala-2.10/classes
% sbt ++2.11.0-RC4 compile
[success] Total time: 2 s, completed Apr 16, 2014 7:03:22 PM
% ls -1d target/*/classes
target/scala-2.11.0-RC4/classes
% sbt +compile
[info] Setting version to 2.10.4
[success] Total time: 2 s, completed Apr 16, 2014 7:06:34 PM
[info] Setting version to 2.11.0-RC4
[success] Total time: 2 s, completed Apr 16, 2014 7:06:36 PM
[info] Setting version to 2.10.4
% ls -1d target/*/classes
target/scala-2.11.0-RC4/classes
% sbt ++2.10.4 compile
[info] Setting version to 2.10.4
[success] Total time: 2 s, completed Apr 16, 2014 7:06:57 PM
% ls -1d target/*/classes
target/scala-2.10/classes
%
```
## problem

sbt deletes unused target/*/classes directory on cross building.
## expectation

sbt does not delete target/*/classes directory from prior cross building.

**Comment by jsuereth** [comment]
I'm not exactly sure why it's deleting the classes directory at all. I don't see any `clean` calls in there.

**Comment by paulp** [comment]
Well yeah, that's kind of my point.

**Comment by paulp** [comment]
I meant "the classes directory it isn't currently building" to identify what it is deleting, not to suggest that there is some classes directory it should be deleting.

**Comment by jsuereth** [comment]
I have a  guess:

The incremental compiler remembering too much (i.e. it doesn't realize you're in a different scala world, so it says "Oh, these are stale I can delete them).

build.sbt is the only thing in your project besides some random .scala file?  Should be easy to set up a test for this then.

**Comment by eed3si9n** [comment]
I reproduced it in my env too. It happens with sbt 0.13.2, but not with 0.13.1. I haven't checked the code yet, but this could be an intentional behavior due to caching around tasks and/or incremental compiler.

**Comment by paulp** [comment]
> I reproduced it in my env too. It happens with sbt 0.13.2, but not with 0.13.1. I haven't checked the code yet, but this could be an intentional behavior due to caching around tasks and/or incremental compiler.

I choose to disbelieve it could possibly be intentional.

**Comment by jsuereth** [comment]
You never know.  We haven't cleaned up all the `if(isPaulp) annoyAsMuchAsWeCan()` calls...

**Comment by paulp** [comment]
I know, I have a bot which emails me whenever one is removed (or, more often, added.)

**Comment by jsuereth** [comment]
:)  We'll do what we can.  Thanks for reporting and helping us out.

**Comment by jsuereth** [comment]
Ok, isolated this to the compile task itself, so it's related to incremental compiler changes (cc @gkossakowski ).  I'll try to isolate the root cause shortly, but I expect it's not appropriately invalidating Analysis anymore on Scala "major" version bump (where class files move) so the incremental compiler cleans the old files when it compiles the new ones.

**Comment by gkossakowski** [comment]
I'm guessing that Analysis might be kept around longer than it's supposed to be. @jsuereth, I'm looking forward to your findings. If you confirm it's a problem with Analysis caching I can have a look into it.

**Comment by jsuereth** [comment]
So it was a regression in analysis, but honestly the place where we were tracking cross-compilation didn't really make sense to me.   Now exposed in the build and driven off the `crossPaths` task, like other "use the scala binary version" things are.

**Comment by paulp** [comment]
The bot alerts me we retired an invocation of annoyAsMuchAsWeCan(), thanks!

**Comment by jsuereth** [comment]
@paulp Let me know if we still have issues with `+` and the cache.  Looking around the code, it's entirely probably there's another hidden cache somewhere.  We'll have to clean that area up a bit when we have a chance to break compatibility.
