### ISSUE TITLE
sbt 13.2 breaks code my code (that works well for sbt 0.13.1.)

### ISSUE THREAD

**Issue by antonkulaga** [sbt/sbt#1271]
When I try to compile my project (https://github.com/denigma/semantic-web) with sbt 0.13.2 (  it fires dozens of compile-time errors like):

[error] bad symbolic reference. A signature in package.class refers to type Scala2SesameModelImplicits
[error] in package org.denigma.semantic which is not available.
[error] It may be completely missing from the current classpath, or the version on
[error] the classpath might be incompatible with the version used when compiling package.class.
[error] bad symbolic reference. A signature in package.class refers to type Sesame2ScalaModelImplicits
[error] in package org.denigma.semantic which is not available.
[error] It may be completely missing from the current classpath, or the version on
[error] the classpath might be incompatible with the version used when compiling package.class.

I suspect it has something to do with shared unmanaged source directories that I use to share code between scala/scalajs ( common practice for most of mixed scala/scalajs projects). The project compiles and runs perfectly well by sbt 0.13.1 (at the moment it is current version; do not looks at travis results as travis is somewhat misconfigured there).

**Comment by gkossakowski** [comment]
I just tried to reproduce it by checking out current master (d9cd5970ef91a10da2c003724ac56472fcd91005) of semantic-web. I changed sbt version to 0.13.2:

``` patch
diff --git a/project/build.properties b/project/build.properties
index 37b489c..8ac605a 100644
--- a/project/build.properties
+++ b/project/build.properties
@@ -1 +1 @@
-sbt.version=0.13.1
+sbt.version=0.13.2
```

I started sbt and compiled the whole project successfully.

**Comment by antonkulaga** [comment]
Really strange :( I did activator clean-files before building the project with sbt 0.13.2 I will check it with pure sbt (because I had errors while using activator run and activator test commands)

**Comment by antonkulaga** [comment]
I have checked several times both with sbt and activator commands (with activator clean-files to make sure it is not a cache issue). It does not compile on my machine (Ubuntu 13:10, scala 2.10.4) with sbt 0.13.2 I do not know, maybe I should res-install activator/sbt or do something more radical...

**Comment by gkossakowski** [comment]
I just tried with Activator 1.1.1 and I couldn't reproduce it either. Could you provide the output of `last compile` after errors are reported?

**Comment by jsuereth** [comment]
You may want to manually delete your ~/.sbt/boot and <project>/target, <project>/project/target directories.

**Comment by OlegYch** [comment]
for the record cleanFiles doesn't do anything, it's a setting

**Comment by pemistahl** [comment]
FYI: I had the same problem when I upgraded to sbt 0.13.2 and got the same error messages. The suggestion of @jsuereth worked for me. After deleting the respective directories, sbt 0.13.2 compiled my project just fine, even with Scala 2.11.

**Comment by jsuereth** [comment]
We're actually noticing forward-compatibility reports between the sbt 0.13.1 launcher and sbt 0.13.2.   I'm still investigating, but it could be some of the changes are leading to inconsistent caches. Right now the workaround I listed above is best.   In the future, I'll try to set up some kind of "upgrade" test for new versions before issuing a final release.

**Comment by SethTisue** [comment]
hi, triage squad here. if the bug has gone unreproduced/unreproducible this long, it should probably be closed? it could be always reopened if anyone appears with a reproduction

**Comment by jsuereth** [comment]
Listening to @SethTisue
