### ISSUE TITLE
Problem with publish trying to move files for aggregates after upgrade to sbt 0.13.2

### ISSUE THREAD

**Issue by bantonsson** [sbt/sbt#1281]
We have an issue in akka (akka/akka#15018) where the publication of our nightly timestamped snapshots has started to fail after upgrading to sbt 0.13.2.

What happens is that the publish task tries to move files for the aggregates after we update the version of the projects.

This is the error:

```
impossible to move '/localhome/jenkinsakka/workspace/akka-publish-nightly/target/repository/com/typesafe/akka/akka/2.4-20140415-231907.part' to '/localhome/jenkinsakka/workspace/akka-publish-nightly/target/repository/com/typesafe/akka/akka/2.4-20140415-231907'
impossible to move '/localhome/jenkinsakka/workspace/akka-publish-nightly/target/repository/com/typesafe/akka/akka-samples/2.4-20140415-231907.part' to '/localhome/jenkinsakka/workspace/akka-publish-nightly/target/repository/com/typesafe/akka/akka-samples/2.4-20140415-231907'
impossible to move '/localhome/jenkinsakka/workspace/akka-publish-nightly/target/repository/com/typesafe/akka/akka-sample-osgi-dining-hakkers/2.4-20140415-231907.part' to '/localhome/jenkinsakka/workspace/akka-publish-nightly/target/repository/com/typesafe/akka/akka-sample-osgi-dining-hakkers/2.4-20140415-231907'
```

And this is the code that changes the versions:

``` scala
  // timestamped versions

  def stampVersion = Command.command("stamp-version") { state =>
    val extracted = Project.extract(state)
    extracted.append(List(version in ThisBuild ~= stamp), state)
  }

  def stamp(version: String): String = {
    if (version endsWith Snapshot) (version stripSuffix Snapshot) + "-" + timestamp(System.currentTimeMillis)
    else version
  }

  def timestamp(time: Long): String = {
    val format = new java.text.SimpleDateFormat("yyyyMMdd-HHmmss")
    format.format(new java.util.Date(time))
  }
```

Is there something obviously wrong with how we do this?

**Comment by 2m** [comment]
I have determined that the `publish` task starts to fail when `sbt` is upgraded from `0.13.2-M1` to `0.13.2-M2`. So the commit is [somewhere in here](https://github.com/sbt/sbt/compare/v0.13.2-M1...v0.13.2-M2).

It seems to be related with [this commit](https://github.com/sbt/sbt/commit/0199a93ffbed2a89f8ce88be1ea04333c48320ec). And the workaround was to add `isSnapshot := true` when changing version from `SNAPSHOT` to a timestamped one. So `stampVersion` method would look like this:

``` scala
  def stampVersion = Command.command("stamp-version") { state =>
    val extracted = Project.extract(state)
    extracted.append(List(version in ThisBuild ~= stamp, isSnapshot in ThisBuild := true), state)
  }
```

Can anyone comment is this a bug in sbt or the way akka timestamps project versions is wrong?

**Comment by cunei** [comment]
This is an issue in sbt; dbuild is also affected. I am looking into it as we speak, but it will be a bit tricky to isolate.

**Comment by cunei** [comment]
I minified the error condition to the following standalone `build.sbt`:

```
publishTo := Some(Resolver.file("here", file("here")))

version := "1.0-test"

publishArtifact := false
```

An `sbt publish` with this build file on sbt 0.13.2 will fail with a similar error message. I am currently debugging this issue.

**Comment by jsuereth** [comment]
@cunei Good diagnosis.  Looks like in Ivy 2.3.0-final the default for file repositories is transactional _AND_ there's a bug in the interaction.  Disabling transactions fixes it, and sbt assumes non-transactional defaults.   We can expose transactions in sbt completely, now that they're on by default, but this is looking like an issue with Ivy 2.3 or our assumption that it's non-transactional

**Comment by jsuereth** [comment]
Also, we can probably default file repositories in sbt 0.13.5 to non-transactional if needed.

**Comment by jsuereth** [comment]
Looks like a legitimate Ivy issue.  The transactional filesystem never creates the directory in which it'll be copying files. Then when it goes to move the directory, nother exists properly and the dubious `renameTo` fails.   Let me know how your investigationg goes or how I can help.

**Comment by cunei** [comment]
Apparently, Ivy fails when there are no artifacts to be published within a transaction; depending on the configuration sometimes it emits an error message saying "publish aborted: nothing was started", or it will fail to spot that the temporary directory was not created, aborting during the rename.
I just added a test, skipping publication (and the transaction) altogether if there is nothing to be published. I am running some additional tests with dbuild now, to be on the safe side; I will issue the related PR later today. /cc @gkossakowski

**Comment by gkossakowski** [comment]
Excellent! Thanks for debugging this @cunei!

**Comment by jsuereth** [comment]
@cunei Good finds!  I'm going to hold of the 0.13.5-RC1 for this fix :)
