### ISSUE TITLE
Remove resident compiler infrastructure

### ISSUE THREAD

**Issue by gkossakowski** [sbt/sbt#1287]
Inspired by: http://stackoverflow.com/questions/23278316/experimental-support-for-keeping-the-scala-compiler-resident-with-sbt-resident-l

The conclusion from our experiments with resident compilation is that the feature is very difficult to implement (due to Scala compiler being not designed for that use case). The benefit of resident compilation turned out to be much smaller than anticipated.

For those reasons, we don't plan to work on resident compilation and we should remove any references from sbt to it.

**Comment by jvican** [comment]
This can be closed since it has been ported to the Zinc repository.

**Comment by Duhemm** [comment]
This si the corresponding issue: sbt/zinc#340
