### ISSUE TITLE
$HOME/.sbt/plugins/build.sbt is not picked up on Windows

### ISSUE THREAD

**Issue by max-l** [sbt/sbt#130]
the file :

  $HOME/.sbt/plugins/build.sbt

seems to be ignored by SBT on windows.

(I'm using a Mingw32 bash sell in which I can do :

cat $HOME/.sbt/plugins/build.sbt

and see the file
)

**Comment by retronym** [comment]
What do you see from `scala -e "println(util.Properties.userHome)`?

**Comment by harrah** [comment]
Please provide steps to reproduce and the sbt version being used.  I'm going to guess this isn't a bug and it would be better discussed on the mailing list.

**Comment by max-l** [comment]
The problem I was having is that the shell that I am using has it's own $HOME, different that the one given
by java.lang.System.getProperty("user.home")... So you are right, it's not a bug...
