### ISSUE TITLE
Adding apiMappings doesn't resolve linking to external classes

### ISSUE THREAD

**Issue by taylorleese** [sbt/sbt#1301]
I'm trying to resolve a number of warnings similar to below where I can't link to external classes in scaladocs. This is with Scala 2.11.0.

```
[warn] /my/path/resource.scala:136: Could not find any member to link for "scala.util.Either".
```

This is how I am setting up my api mappings:

``` scala
apiMappings ++= {
  def findManagedDependency(organization: String, name: String): Option[File] = {
    (for {
      entry <- (fullClasspath in Compile).value
      module <- entry.get(moduleID.key) if module.organization == organization && module.name.startsWith(name)
    } yield entry.data).headOption
  }
  val links: Seq[Option[(File, URL)]] = Seq(
    findManagedDependency("org.scala-lang", "scala-library").map(d => d -> url(s"http://www.scala-lang.org/api/$scalaVsn/")),
    findManagedDependency("com.typesafe.akka", "akka-actor").map(d => d -> url(s"http://doc.akka.io/api/akka/$akkaVersion/")),
    findManagedDependency("com.typesafe", "config").map(d => d -> url("http://typesafehub.github.io/config/latest/api/"))
  )
  val x = links.collect { case Some(d) => d }.toMap
  println("links: " + x)
  x
},
```

Sample output from the println:

```
links: Map(/Users/tleese/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.0.jar -> http://www.scala-lang.org/api/2.11.0/, /Users/tleese/.ivy2/cache/com.typesafe.akka/akka-actor_2.11/jars/akka-actor_2.11-2.3.2.jar -> http://doc.akka.io/api/akka/2.3.2/, /Users/tleese/.ivy2/cache/com.typesafe/config/bundles/config-1.2.0.jar -> http://typesafehub.github.io/config/latest/api/)
```

Is this a bug or am I doing something wrong?

**Comment by taylorleese** [comment]
Side note, I've had some success with non-standard Scala libraries (e.g. Akka, typesafe config), but I seem to be having the most trouble with the standard Scala library and I'm not sure why.

**Comment by taylorleese** [comment]
Ah, it looks like this may only be a problem specific to links in package objects. Perhaps this is a Scaladoc bug?

**Comment by eed3si9n** [comment]
Hi Taylor, sbt project uses Github issues for internal todo list. For getting help about sbt, please refer to our issue reporting guideline (https://github.com/sbt/sbt/blob/0.13/CONTRIBUTING.md) and open a StackOverflow question to get help from the community. Scaladoc issues I think are tracked as part of scala issues here - https://issues.scala-lang.org/secure/Dashboard.jspa.
