### ISSUE TITLE
addSbtPlugin ordering

### ISSUE THREAD

**Issue by huntc** [sbt/sbt#1302]
We had an expectation (perhaps wrongly) that the order of `addSbtPlugin` calls was significant thus these asset pipeline plugin declarations:

``` scala
addSbtPlugin("com.typesafe.sbt" % "sbt-rjs" % "1.0.0-SNAPSHOT")

addSbtPlugin("com.typesafe.sbt" % "sbt-digest" % "1.0.0-SNAPSHOT")

addSbtPlugin("com.typesafe.sbt" % "sbt-gzip" % "1.0.0-SNAPSHOT")
```

...would result in rjs being executed, then digest and then gzip.

Each plugin adds its pipeline task. For example, with sbt-digest:

``` scala
pipelineStages <+= addChecksums
```

where `addChecksums` is the task and `pipelineStages` is defined by sbt-web as:

``` scala
val pipelineStages = SettingKey[Seq[Task[Pipeline.Stage]]]("web-pipeline-stages", "Sequence of tasks for the asset pipeline stages.")
```

Unfortunately for us, the pipeline stage tasks are added in no specific order (I suspect there's a hash based collection in place):

```
[reactive-maps] $ show web-assets:web-pipeline-stages
[info] List(Task((taskDefinitionKey: ScopedKey(Scope(Select(ProjectRef(file:/Users/huntc/Projects/typesafe/ReactiveMaps/,root)),Global,Global,Global),digestAddChecksums))), Task((taskDefinitionKey: ScopedKey(Scope(Select(ProjectRef(file:/Users/huntc/Projects/typesafe/ReactiveMaps/,root)),Global,Global,Global),gzipCompress))), Task((taskDefinitionKey: ScopedKey(Scope(Select(ProjectRef(file:/Users/huntc/Projects/typesafe/ReactiveMaps/,root)),Global,Global,Global),rjs))))
```

In the above the sequence is `digestAddChecksums`, `gzipCompress` and then `rjs`.

I'd really like the ordering of a pipeline plugin to be predictable i.e. the order of `addSbtPlugin` to be the default order of how pipeline plugins are added to `pipelineStages`. The reason I'd like to have this is for the developer experience; it is quite minimal and avoids the user having to understand what tasks a pipeline plugin has. In addition each pipeline plugin absolutely cannot know about plugins that go before it (there could be anything - it is user defined).

Thoughts? Unfortunately the way things are at present means that our sbt-web asset pipeline is stuffed. I can't release sbt-web 1.0.0-RC1 until we have a resolution. :-(

**Comment by huntc** [comment]
Thinking about it more, I could have the developers assign `pipelineStages` themselves; this may even be a better DX given that they have complete control over pipeline stage ordering, and there's no magic. This is what `build.sbt` could look like:

``` scala
pipelineStages := Seq(rjs, digest, gzip)
```

To achieve this I'd define the `rjs`, `digest` and `gzip` keys in the scope of the auto import. For example instead of:

``` scala
object Import {
  object GzipKeys {
    val gzip = TaskKey[Pipeline.Stage]("gzip", "Add gzipped files to asset pipeline.")
  }
}
```

...I'd:

``` scala
object Import {
  val gzip = TaskKey[Pipeline.Stage]("gzip", "Add gzipped files to asset pipeline.")
}
```

There is a potential for namespace clashing here, but I think that is low risk given that keys are generally declared within a *Keys object i.e. commonly used keys should be the exception... do you agree?

**Comment by jsuereth** [comment]
Hmm, let me investigate the ordering issue a bit here.   It could be the use of a Set is hosing things, however unless otherwise restricted by requirements, the order you declare should have been the one used.

That said, it may make sense to do the following:
1. Have the plugins go into the pipeline in the random order
2. Let the user override this order in their build by having direct access to each stage (as you suggest).

This way, the out of the box experience is ok, and you can _also_ completely configure things easily.  WDYT?

**Comment by huntc** [comment]
Hi Josh - I've actually now gone down the "user specifies ordering" path. I actually quite prefer this as there is less magic going on. I'm going to close the ticket, but if you could review my second comment in terms of the approach I've taken then that'd be great. Thanks!
