### ISSUE TITLE
'last <task>' should take aggregation into account

### ISSUE THREAD

**Issue by paulp** [sbt/sbt#131]
My laboriously created command line reproduction trying to compile akka with 2.9.1 rc:

```
/scala/inst/rc/bin/scalac -optimise -P:continuations:enable -verbose -cp $(cpof lib_managed) \
-d /tmp $(find akka-actor -name '*.scala' -o -name '*.java')

https://issues.scala-lang.org/browse/SI-4840
```

This crashes in the backend, spewing lots and lots of interesting icode and thoughts from the optimizer.  However sbt seems hell-bent on keeping me from seeing any of it.  Here's what I was able to get out of it, after dialing every dial I could find to the moon for "just print it out, man."

```
...
[debug]     resolve done (1719ms resolve - 61ms download)
[info] Done updating.
[warn] Potentially incompatible versions specified:
[warn]    org.scala-lang: 2.9.0-1, 2.8.1, 2.9.0, 2.8.0
[error] {file:/Users/paulp/Desktop/akka-copy/}akka-actor/compile: java.lang.reflect.InvocationTargetException
[error] Total time: 15 s, completed Jul 26, 2011 2:58:21 PM
```

Not real helpful, that.   The exception isn't even unwrapped.  Is "last" supposed to say something useful?

```
> last compile
[debug] 
[debug] Initial source changes: 
[debug]     removed:Set()
[debug]     added: Set()
[debug]     modified: Set()
[debug] Removed products: Set()
[debug] Modified external sources: Set()
[debug] Modified binary dependencies: Set()
[debug] Initial directly invalidated sources: Set()
[debug] 
[debug] Sources indirectly invalidated by:
[debug]     product: Set()
[debug]     binary dep: Set()
[debug]     external source: Set()
[debug] Initially invalidated: Set()
```

**Comment by harrah** [comment]
Probably `last akka-actor/compile`, since `last compile` from the root project is the same as `last root/compile`.

You probably wouldn't want to see the output from all N projects in Akka.  But if you do, that is now possible in the 0.10 branch.  The 'last' command now displays all logging output from all tasks for the current execution.  (Strictly, it is since the last time the 'shell' command reads a command from the > prompt.)

https://github.com/harrah/xsbt/commit/30baf741697f76d232a5513286a321e66ff70480
https://github.com/harrah/xsbt/commit/00c41ae59a6c7ef3aeb1650a6a3c8c70e683254c

**Comment by paulp** [comment]
I would want to see the output, no matter how much it is, because otherwise I CAN'T SEE THE OUTPUT.

If I can run the compile by typing "compile", then I should not have to know to type "last akka-actor/compile" in order to find out where it blew up.  It sounds like you are saying that "last" will tell me this in the future.  That's good, but it makes no sense that "last compile" wouldn't tell me what happened with "compile" if "last XXX" is supposed to be the mechanism by which I find this out.

I'm all for fighting noise, but sticking firecrackers in my ears would not be my chosen avenue.

**Comment by harrah** [comment]
I see what you're saying and it makes sense that if `compile` is aggregated, `last compile` should be too.  Note that this hypothetical improvement would still only display the output from `compile` tasks and not any `update` or other tasks that were dependencies.

For that, yes, 'last' will display absolutely everything.
