### ISSUE TITLE
SBT doesn't honor Maven's uniqueVersions

### ISSUE THREAD

**Issue by pdalpra** [sbt/sbt#1322]
## Steps
- Publish an `SNAPSHOT` artifact to a Maven repository (with `publishMavenStyle` set to `true`, obviously)
- Try to fetch this artifact as a dependency from Maven 3
- Notice the trouble you're into when trying to fetch the latest `SNAPSHOT`...
## Problems

Maven's support for "unique versions" was deprecated in Maven 2, which reached EOL in February 2014, and definitely disabled in Maven 3. 
However, SBT publishes `SNAPSHOT` artifacts as "unique versions", which causes all kinds of trouble when trying to fetch dependencies from Maven.

Of course, I know SBT isn't Maven and does not try to be Maven, which is great, I love SBT for that, among other things.
However, I think that SBT can't ignore Maven either, as it does already with the possibility to publish POMs, to publish to Maven repos, etc...
Allowing to publish "non-unique versions" is just another step ;)

I know that the [sbt-unique-version plugin](https://github.com/sbt/sbt-unique-version) allows to do that, but I honestly think this should be standard behaviour when publishing `SNAPSHOT` dependencies to a remote Maven repository (as long as it doesn't cause problems somewhere else, of course).

[The sbt-aether-deploy plugin](https://github.com/arktekk/sbt-aether-deploy) fixes that issue too, but pulling Maven in SBT to publish artifacts is a tiny bit overkill...
Plus, there is a version conflict on `httpclient` (both used by SBT and the plugin, pulled by the dependency on Aether) with SBT 0.13, causing the plugin to fail to publish artifacts (SBT isn't to blame for that, of course).

As the problem only arises when trying to fetch a dependency from a remote Maven repository (not a local repo), I suggest that : 
- Publishing to a remote repository (eg. using the `publish` task) 
- With `publishMavenStyle` to `true`

could trigger the change in the artifact name to include the timestamp.

Should you agree with this, I could provide a PR if you like.

**Comment by jsuereth** [comment]
Questions:  
1. Is this a feature of how you publish pom files, or is there an additional step in publishing that needs to happen?
2. is this reported in apache Ivy?  If not, have you asked them if they support this (It could be sbt is just out of date regarding ivy).

I'm all for making this work out of the box in sbt, just need to get some more info.  Tentatively scheduled for fix in 0.13.6.

**Comment by pdalpra** [comment]
1. It's not a feature of how pom files are published, all kinds of artifacts have to be published with `SNAPSHOT` substituted by a timestamp. 
   I guess you're thinking about my `publishMavenStyle` suggestion, as `publishMavenStyle` description states that it controls publication of either a POM or an Ivy module descriptor and I would agree it may be not the best choice after all... A `uniqueVersion` setting or something like that would be just fine too :)
2. I tried to look in Ivy's doc for some info, but I couldn't find anything. After all, Ivy already has a concept of "changing" dependencies, which SBT supports. However, it seems that this could be changed by changing the "artifact pattern" : http://stackoverflow.com/questions/8505062/publish-snapshot-artifacts-to-maven-using-ivy-whats-the-magic (look for the second code block). I haven't reported this issue to Ivy maintainers.

**Comment by pdalpra** [comment]
FYI : Looks like Gradle managed to do it, in some way or another : http://www.gradle.org/docs/current/javadoc/org/gradle/api/artifacts/maven/MavenDeployer.html (they're using Ivy 2.2.0)

I'll dig into Gradle code to find out how they did it.

**Comment by jsuereth** [comment]
gradle actually rewrote their own dependency manager (in 1.x)...

**Comment by hamnis** [comment]
Author of aether-deploy plugin here. I have never had any problem with any httpclient version with 0.13. I have used the plugin on every project the last year, and never run into any dependency problem there. This seems like a combination of plugins that has not been tested.

I would suggest giving it a go, and ping me back if I need to fix something.

Another thing: Aether plugin only depends on the metadata generator in maven, not maven itself.
