### ISSUE TITLE
eating CPU while waiting -- is this OK?

### ISSUE THREAD

**Issue by vn971** [sbt/sbt#1326]
I created a sample repository which shows the CPU eating problem:
https://github.com/vn971/sbt-0.13.5-RC2-bug
(It's almost empty: no sources and no plugins at all.)

Instruction on how to see it:
- start `sbt` in a first terminal
- start another `sbt` in a second terminal. 
- open `htop` (linux), filter by "sbt" (with F4), see that there are currently two processes with sbt.
- in the second terminal enter a task `~ test:compile`

The second terminal will now constantly eat about 60 CPU. It can be seen with `htop`: the process with the bigger pid will have ~50-70 CPU time, distributed among all the cores.

**Comment by jsuereth** [comment]
Currently, sbt uses polling, which can suck up CPU.  For me, it's only 20-30%, but i geuss oculd be different depending on your architecture.

We're planning to implement a fix, where for environmnts that support OS-level hooks, you'll see a CPU usage improvement.  See: https://github.com/playframework/playframework/issues/2620 for more info/reports.

**Comment by vn971** [comment]
Ah, so it's even a single opened SBT that can eat up CPU while `~`. That's a pity. OK, understood, thanks.

I guess I can close this issue because there's a more general one. (Or maybe open a new one with unnecessary stuff cleaned-up, if you'll want.)
