### ISSUE TITLE
Order of magnitude performance regression in watch mode

### ISSUE THREAD

**Issue by jroper** [sbt/sbt#1329]
The performance of SBT's watch mode seems to have regressed across multiple releases, with a significant regression occurring since 0.13.1.

I've used the Play code base as a benchmark, on OSX, with 4 CPU cores.

I've used `find . -path '*/src/main/*' | wc -l` from Play's `framework` directory to estimate the number of source files being watched.

I've used `~compile` as the test to run, and then monitored the `java` process CPU usage in `top`.

On SBT 0.12.4 (Play 2.2.x branch, 482 source files), `java` uses a fairly steady 20% CPU.

On SBT 0.13.1 (Not on any branch, but at the ad306013fe6b2566f328bff3f41ff325d5a269a7 commit, 521 source files), `java` uses approx 40% CPU, fluctuating between 23% and 70%.

On SBT 0.13.5-RC1 (Play master, 574 source files), I'm seeing `java` use between 150% and 250% CPU, seemingly averaging around 200%.

Either adding more files for SBT to watch increases the amount of CPU consumed exponentially, or there's been some very serious regressions.

This has been reported by other users (at least one user on Linux):

https://github.com/playframework/playframework/issues/2793

This makes me very wary of ever giving control of watching files over to SBT.

Related: #1223

**Comment by jroper** [comment]
I've captured some profiling snapshots between SBT 0.13.1 and 0.13.5-RC1, but the data from the profiling is a mess - I suspect that YourKit filters out by default many of the method calls that we're most interested in profiling.  One sampling snapshot that I got showed that SBT 0.13.5-RC1 was calling File.isHidden a lot, it wasn't being called in 0.13.1.  The tracing snapshots reveal nothing, the only methods they show taking any serious is the main call heirarchy.  If anyone knows how to better read these than me, then I'll be happy to send the data.

**Comment by retronym** [comment]
I'd suggest to use sampling mode, rather than tracing mode, as the first pass.

When you view the CPU snapshot, you can configure which methods are filtered out of the view with:

![image](https://cloud.githubusercontent.com/assets/65551/2954117/0fd6fca0-da6c-11e3-8e3c-d1a2f6ecd3b9.png)

**Comment by gaydenko** [comment]
I just want to add I haven't met the issue with 0.13.5-M2, a problem has appeared with RC1.

**Comment by retronym** [comment]
I wonder if e076bfa970e is in play here. Do you see the same issue with `sbt -Dsbt.task.forcegc=false ...`

**Comment by godenji** [comment]
@retronym forcegc=false chops down CPU usage from constant minimum 50% to around 20% with idle `~run` in Play 2.3, which is welcome, thanks!!

Also speeds up SBT incremental recompilation performance, which was painfully laggy compared to 0.13.1/2

Applying this one flag seems to resolve at least 2 bugs, nice ;-) @jroper forgive the grumbling elsewhere, just trying to preserve the excellent Play 2.2 developer experience gains.

**Comment by gaydenko** [comment]
@retronym , great, thanks! `-Dsbt.task.forcegc=false` resolves the issue at my case: idle `~run` takes 1-3% on my machine.

**Comment by retronym** [comment]
@eed3si9n @jsuereth I would suggest to throttle this option ("no more often than once per N-seconds") by default.

Integrating SBT with JDK7 `WatchService` would be an awesome contribution to SBT. We could also use that in the part of the incremental compiler that checks for updates to source and class files; we've had reports that this is a bottleneck on Windows systems with realtime virus scanning enabled.

**Comment by jsuereth** [comment]
@retronym Good points.  I'll expand it to be a more configurable strategy, perhaps.  

Also, we already have a ticket for creating a new, re-usable, watch service that can be backed on JDK7 if running on JDK7.

I'm going to leave this open as we'll have to tune the autogc fix for open files.

**Comment by jroper** [comment]
I should have checked gc, the profile shows 2 full gcs per second - totally explains it, and that also explains why CPU profiling was completely useless at determining anything useful.

**Comment by jroper** [comment]
Sorry - wrote a comment, and then deleted it, then hit the close button to close the comment box... except that's not what it does.

**Comment by jsuereth** [comment]
should be fixed in latest
