### ISSUE TITLE
Keyboard commands in console are broken with sbt 0.7.7 and Scala 2.9.1.RC1

### ISSUE THREAD

**Issue by jrudolph** [sbt/sbt#134]
At least Ctrl-C and Ctrl-D aren't working any more on Linux in `sbt console`.

I created an issue for Scala as well, see https://issues.scala-lang.org/browse/SI-4844.

**Comment by harrah** [comment]
Not an sbt bug as far as I can tell.  It appears to be covered by SI-4844 and SI-4705.
