### ISSUE TITLE
Global plugins class loader should not be parent of project classloader

### ISSUE THREAD

**Issue by jroper** [sbt/sbt#1347]
Global plugins are merged in with a build projects classpath (I mean, the sbt project build, that thing configure by `project/plugins.sbt`, not the applications build).  But in addition to this, the global plugins are loaded into their own classloader, and then this classloader is used as the parent of the build project.  This means that while it is possible for a projects build to override dependencies defined globally (eg, if a project declares a dependency in a never version of a library than is brought in by the global plugins) and ivy should work this out, because the global plugins are also in a parent classloader and classloading is parent first, such configuration has no affect.

This bites in practice when you have, for example, the sbt-idea plugin configured globally (a common use case), and it depends on commons-io 2.0.1, but then you have a plugin configured for a project (eg play) which depends on commons-io 2.4 and uses methods from commons-io 2.4 that aren't in 2.0.1.  Ivy resolves this nicely, evicting the 2.0.1 dependency from the sbt projects build, but then since the parent classloader just has the sbt-idea plugin, the commons-io 2.0.1 jar is still in that classloader, and because it's the parent the classes are loaded from there in preference to the 2.4 jar in the child classloader.

I can't see any reason why the global plugins should be in a parent classloader of the sbt project build, it seems this will only cause major problems.

I'm seeing this in 0.13.5-RC3, but we've only just added the commons-io dependency to play, so this may have existed for a long time.

**Comment by jroper** [comment]
Issue caused by this in Play: https://github.com/playframework/playframework/issues/2882

**Comment by dansanduleac** [comment]
I was just about to comment on this as well. Also see #1084 for a previous discussion on this.
To answer your question, this has existed for a long time, and it's probably about time we fix it.
I think I've identified @8cb7e23 as the main cause for this, whose scripted test verifies something that is not the behaviour we want. I think we should probably revert that change, and instead only inject the GP's loader at the point of _loading_ new builds (so that their definition compiles), but not further than that.

**Comment by jsuereth** [comment]
Yeah, I think this may take some time to clean up, but we should.  For now, unfortunately, we just want to make sure plugin versions line up as much as is feasible.  As a temporary workaround, we could invert the parent-classloader delegation for projects so the local class is pulled before the parent class is pulled, but that may lead to odd classformatexceptions.

**Comment by jsuereth** [comment]
I think @dansanduleac's patch has fixed this issue.
