### ISSUE TITLE
That's a lot of State copies

### ISSUE THREAD

**Issue by paulp** [sbt/sbt#1348]
If you look at State.scala there's an ignored expression in the StateOps constructor, floating almost invisibly unattached to the methods on either side of it.

```
s.copy(remainingCommands = s.remainingCommands.drop(1))
```

There's a compiler option which is supposed to warn you about this sort of thing.

**Comment by jsuereth** [comment]
Hmm, I wonder if this was a leftover artifact of the "style formatter".   I turned warnings on once for sbt and was then unable to separate the sheep from the goats.

In any case, thanks for the report.  Most likely that line can just be removed.  PR welcome.

**Comment by jsuereth** [comment]
I think @eed3si9n cleaned this up after the code reformatter made it apparent it wasn't included in a block.  It's no longer in the State.scala file.
