### ISSUE TITLE
[0.13.5-RC3] sbt fails to start the shell for some command line options

### ISSUE THREAD

**Issue by timohirt** [sbt/sbt#1354]
I want to define the max perm gen size as well as some other non standard JVM options. As soon as I add the options the the `sbt` call it fails to start the interactive shell.

``` bash
sbt  -XX:MaxPermSize=1024M -Dsbt.jse.engineType=Node -v
# Executing command line:
java
-Xms1024m
-Xmx1024m
-XX:MaxPermSize=256m
-XX:ReservedCodeCacheSize=128m
-Dsbt.jse.engineType=Node
-jar
/usr/share/sbt-launcher-packaging/bin/sbt-launch.jar
-XX:MaxPermSize=1024M

[info] Loading project definition from /home/timo/my_project/project
[info] Set current project to my_project (in build file:/home/timo/my_project/)
[warn] The `-` command is deprecated in favor of `onFailure` and will be removed in 0.14.0
```

**Comment by jsuereth** [comment]
Which sbt script are you using?  You'll want to use `-J` for most of them to ensure that the argument is used as a JAVA argument, not an argument to sbt.

**Comment by timohirt** [comment]
`-J` solved the problem. Thanks!

**Comment by oforero** [comment]
Hello guys,

I now get to work in some scala projects at work, I am seeing this same warning with the sbt-launcher-0.13.6, I would appreciate some pointer about how to use the -J option? for example I tried :

-J -Xms512M and -JXms512M but that results in the JVM being unable to start
