### ISSUE TITLE
plugin review: sbt-jmh

### ISSUE THREAD

**Issue by ktoso** [sbt/sbt#1355]
Hi guys,
it would be great if you could review this plugin: https://github.com/ktoso/sbt-jmh/
It's for http://openjdk.java.net/projects/code-tools/jmh/ and a bit convoluted, since JMH does a lot of stuff to prepare the benchmarks.

JMH works like this:

```
scalac: scala -> bytecode
jmh: bytecode -> java sources
javac: these java sources -> bytecode // which we can run finally
```

It's an early version - feel free to bash. For example I should be able to disable the scala compiler for the last step.

**Comment by gkossakowski** [comment]
I looked at the plugin source and I don't understand why do you need to modify anything in the `Compile` configuration. I think it would be a lot cleaner for your `sourceGenerators in Jmh` to depend on `compile in Compile` and then the rest would be straightforward, the `compile in Jmh` would pick up java sources generated by jmh and compile them. The `run in Jmh` would have the right classpath, etc.

**Comment by ktoso** [comment]
Thanks Greg - good tips. I'll try to modify it according to this suggestion over the weekend.

**Comment by ktoso** [comment]
Closing for now, I'm still working on it ofc; Thanks for the feedback!
