### ISSUE TITLE
java.lang.ClassCastException when serializing object

### ISSUE THREAD

**Issue by teamon** [sbt/sbt#136]
The code to reproduce: https://gist.github.com/1af85bff5de659b3d266

The issue is that this code works under scala repl, but within sbt console it throws an exception.

It is not only related to sbt console, if I execute jetty-run from sbt it behaves the same way.

**Comment by harrah** [comment]
This is just standard OOIS behavior in the presence of class loaders, unfortunately.  There isn't even a simple place you can say "use this class loader" and sbt can't work around it either as far as I know.  You have to have a custom OOIS subclass, although it isn't too bad.  See http://jira.codehaus.org/browse/GROOVY-1627, for example.

**Comment by harrah** [comment]
`IO.objectInputStream` implements a custom OOIS subclass as a convenience for working around the problem.
