### ISSUE TITLE
sbt classloaders should not return null from java.lang.ClassLoader#getResources

### ISSUE THREAD

**Issue by OlegYch** [sbt/sbt#1368]
this breaks general contract of the method
in particular i'm having an issue with NullLoader returning null at https://github.com/hazelcast/hazelcast/blob/db8721eab91961d61ef4957682e71ce9dc3fdcf7/hazelcast/src/main/java/com/hazelcast/util/ServiceLoader.java#L169
using sbt 0.13.5-RC5

**Comment by hcoles** [comment]
Just hit the same issue, also with hazelcast.

@OlegYch Did you find a workaround?
