### ISSUE TITLE
inconsistent update strategies

### ISSUE THREAD

**Issue by softprops** [sbt/sbt#137]
I recently received a bug report [1](https://github.com/softprops/coffeescripted-sbt/issues/1) in my plugin about a library dependency not being resolved. I am able to resolve this dependency fine "from" a url [2](https://github.com/softprops/coffeescripted-sbt/blob/master/build.sbt#L12) when I build my plugin locally. I removed the dependency from my ivy cache and tried to depend on my plugin from a scratch project

```
set resolvers += "less is" at "http://repo.lessis.me"
set libraryDependencies <+= sbtVersion(v => "me.lessis" %% "coffeescripted-sbt" % "0.1.2-%s".format(v))
update
```

I get the same dependency resolution error mentioned by this user. I did a little more detective work and found that sbt was doing different things based on whether I was building my plugin and updating or depending on my plugin and updating. I captured the relavant ivy logging in a gist [3](https://gist.github.com/1110957) to show you want I mean. It looks like when I build my plugin locally, sbt is aware that my dependency is declared as an artifact with a url and falls back on that 

```
[debug]   using url for org.jcoffeescript#jcoffeescript;1.1!jcoffeescript.jar: http://cloud.github.com/downloads/yeungda/jcoffeescript/jcoffeescript-1.1.jar
```

This is not the case when adding my plugin as a dep to a project and updating.

I'll try tracking down a more of what happens in the relavent IvyAction code [4](https://github.com/harrah/xsbt/blob/0.10/ivy/IvyActions.scala#L126-143) so to try to find discrepancies.

Let me know if anything I'm doing pops out at you.

**Comment by harrah** [comment]
From [Library-Management](https://github.com/harrah/xsbt/wiki/Library-Management/):

"The URL is only used as a fallback if the dependency cannot be found through the configured repositories. Also, the explicit URL is not included in published metadata (that is, the pom or ivy.xml)."

This is handled by Ivy.  sbt just declares the URL.

**Comment by softprops** [comment]
Is there a work around for this in plugins? I'll contact the libraries author to try and coax him into publishing it to a mvn or ivy repo.

**Comment by harrah** [comment]
Not that I know of, beyond having users add the dependency explicitly.
