### ISSUE TITLE
Tracing an exception from a test framework gives invalid suggestion

### ISSUE THREAD

**Issue by EECOLOR** [sbt/sbt#1371]
When I trace an exception from my test framework it displays the following line:

[trace] Stack trace suppressed: run last little-spec/test:test(name: org.qirx.littlespec.sbt.SbtReporterSpec, isModule: false) for the full output.

Executing `last little-spec/test:test(name: org.qirx.littlespec.sbt.SbtReporterSpec, isModule: false)` results in the following error:

```
[error] Expected key
[error] Expected '::'
[error] Expected end of input.
[error] last little-spec/test:test(name: org.qirx.littlespec.sbt.SbtReporterSpec, isModule: false)
```

It seems the `testExtra` method in `Defaults` adds the `name: org.qirx.littlespec.sbt.SbtReporterSpec, isModule: false)`.

I am not sure what command to call to get to the suppressed stack trace.

**Comment by jsuereth** [comment]
Are you using  a command or a task?  Also what version of sbt?

Finally, I think you just want to write:

```
last little-spec/test:test
```

Looks like the output is getting garbled for some reason.

**Comment by EECOLOR** [comment]
No, it's not wrong, the directory in `target/streams/test/test/` is actually called `isModule=false name=org.qirx.littlespec.sbt.SbtReporterSpec`

The `last little-spec/test:test` command shows information from another file.

It's in sbt 0.13.5 when running the `test` command (or task, I'm not sure of the difference). From my custom test framework I call a `trace` method on the logger of the `sbt.testing` interface.

**Comment by benhutchison** [comment]
I'm seeing similar, using scala.js & utest [https://github.com/lihaoyi/utest]

> js/test
> [info] Compiling 1 Scala source to /Users/ben_hutchison/swork/prickle/js/target/scala-2.11/test-classes...
> [warn] there were 2 deprecation warning(s); re-run with -deprecation for details
> [warn] one warning found
> [trace] Stack trace suppressed: run last js/test:test(name: prickle.JsPickleTest, isModule: true) for the full output.

..but then:

> last js/test:test(name: prickle.JsPickleTest, isModule: true)
> [error] Expected key
> [error] Expected '::'
> [error] Expected end of input.
> [error] last js/test:test(name: prickle.JsPickleTest, isModule: true)
> [error]                  ^

..and:

> last
> [error] Expected key
> [error] Expected '::'
> [error] Expected end of input.
> [error] last js/test:test(name: prickle.JsPickleTest, isModule: true)
> [error]                  ^

**Comment by dispalt** [comment]
Anyone figure this out?

**Comment by eed3si9n** [comment]
The error message should now display slash syntax, so I am closing this.
