### ISSUE TITLE
Incremental compiler loses warnings

### ISSUE THREAD

**Issue by dragos** [sbt/sbt#1372]
This is a problem for stateful clients, like IDEs. Warnings (and possibly errors) may simply be lost. By stateful I mean "the client maintains a GUI with error markers that need to be added/removed in response to compilations). The fundamental difference between Sbt and stateful clients is that Sbt reports errors per "compilation run" (usually a subset of all project files), while IDEs try to maintain a consistent project-wide view of errors and warnings.

Let's say that we have two files, with a deprecation warning in A, and the deprecated definition in B.
- add a new method in B
- rebuild. The IDE removes all project error/warning markers before asking Sbt to build
- Name hashing decides that A does not need to be recompiled
- Sbt does not report the deprecation warning again (it's lost now).

(name hashing isn't involved here, it just makes this problem more likely to happen).

We could clear markers only in the files that we _are_ building, but that doesn't work because of another Sbt optimization:
- A and B successfully built
- B modified, causes error in A (both files were recompiled at this step)
- revert change in B. 
- A is not recompiled (the transactional classfile manager kept the binaries around)

So if we only removed error markers for files that are recompiled, we'd have a stale error marker in A. See [this IDE ticket](https://www.assembla.com/spaces/scala-ide/tickets/1001953#/activity/ticket:) and discussion around Sbt issue #958.

IMO the second scenario is unintuitive. Not sure how useful it is in practice, but certainly complicates life. Would it be possible for Sbt to report what files it _would_ compile (even though the optimization might skip this step). Note that this won't fix the whole issue: since the file isn't recompiled, we would lose warning markers anyway (but wouldn't get stale error markers).

We seem to be caught between a rock and a hard place... See also scala-ide/scala-ide#701

**Comment by gkossakowski** [comment]
//cc @jsuereth who is interested in incremental compiler reporting

**Comment by gkossakowski** [comment]
@dragos: have you considered using [Analysis.infos](https://github.com/sbt/sbt/blob/0.13/compile/inc/src/main/scala/sbt/inc/Analysis.scala#L30) for syncing source markers when you make a transition from unsuccessful to successful incremental compilation run?
If you make a transition  from unsuccessful to successful incremental compilation result you get a new Analysis that contains source markers consistent with the source code (and bytecde) regardless of how that consistency was achieved so behavior of ClassfileManager is taken into account.

Specifcially, you could analyze all source files that were marked with errors, clear _all_ markers and then use `Analysis.infos` to bring back correct markers.

**Comment by dragos** [comment]
Interesting, I didn't know that `Analsys` stores that kind of information. Does it contain errors only, or both warnings and errors?

**Comment by gkossakowski** [comment]
Both errors and warnings. The [`printWarnings`](https://github.com/sbt/sbt/blob/0.13/main/src/main/scala/sbt/Defaults.scala#L792) command is implemented by using this information.

**Comment by dragos** [comment]
Ok, something to look into this week..

**Comment by gkossakowski** [comment]
@dragos, did you have a chance to look into it?

I'm closing this issue for now as I think there's no bug in sbt.

**Comment by dragos** [comment]
Not yet... will do

On Tue, Jul 22, 2014 at 3:40 PM, Grzegorz Kossakowski <
notifications@github.com> wrote:

> @dragos https://github.com/dragos, did you have a chance to look into
> it?
> 
> I'm closing this issue for now as I think there's no bug in sbt.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sbt/sbt/issues/1372#issuecomment-49739780.

## 

« Je déteste la montagne, ça cache le paysage »
Alphonse Allais
