### ISSUE TITLE
Global setting keys don't show up in autocomplete (sbtVersion)

### ISSUE THREAD

**Issue by dragos** [sbt/sbt#1373]
(using 0.13.5-RC5)

```
akka > sbt
sbtBinaryVersion    sbtClearOnFailure   sbtDependency       sbtPlugin           sbtPopOnFailure     sbtResolver         sbtStashOnFailure   
akka > sbtV
{invalid input}   
akka >
```

An interesting factoid: 78 upvotes for [how to check sbt version](http://stackoverflow.com/questions/8461013/how-to-check-sbt-version).

**Comment by jsuereth** [comment]
I believe this is a duplicate.  Basically, the autocompletion we do doesn't fully account for delegation, and therefore ignores "Global" settings, like `sbtVersion`.

On my machine:

```
> sbtV
{invalid input}   
> sbtVersion
[info] 0.13.5-RC5
```

**Comment by jsuereth** [comment]
Ah, related to #1337, which was closed.  I'll repurpose/relabel this ticket.

**Comment by dragos** [comment]
Yes, `sbtVersion` (typed fully), works for me as well. But I still think this is a very basic thing that can leave people very frustrated. For example, when I saw that tab-completion doesn't show it, I didn't even bother typing it (even though I vaguely remembered about `sbtVersion`). It's telling that the answer on SOF had 78 upvotes...

**Comment by jsuereth** [comment]
I don't disagree.  Was just categorizing/describing the underlying issue.

**Comment by dwijnand** [comment]
This works in 0.13.11, and it also works in 0.13.5.

**Comment by dwijnand** [comment]
Also, completion of build-level keys is better in 0.13.12+

**Comment by dwijnand** [comment]
Also, completion of build-level keys is better in 0.13.12+: https://github.com/sbt/sbt/pull/2469

**Comment by jvican** [comment]
I've just encountered this issue when trying to do autocompletion on `parallelExecution`. I can confirm it works for `sbtVersion`, but it doesn't for `parallelExecution`, which I believe is also scoped in `Global`.
  
Can we reopen this issue and aim at getting autocompletion that fully accounts for delegation?

**Comment by dwijnand** [comment]
Sure. My guess is that it works with sbtVersion because it's Def.derive-d.
