### ISSUE TITLE
means to access plugin classpath; classifiers

### ISSUE THREAD

**Issue by retronym** [sbt/sbt#138]
We need this to configure the 'project' submodule in IntelliJ with idea-sbt.

I've hacked together something similar, but I had to duplicate a few function in IvySbt that aren't accessible. I would prefer if this was provided as a standard task, especially in light of the recent changes to plugin cross building.

Potentially these could be included in the existing update-sbt-classifiers task, either way we can configure the classpath correctly.

**Comment by harrah** [comment]
https://github.com/harrah/xsbt/wiki/Build-State

You can get the State from the 'state' key.

Then, see LoadedBuildUnit:

http://harrah.github.com/xsbt/latest/api/sbt/Load%24%24LoadedBuildUnit.html

`loadedUnit.classpath` gives the classpath used for quick configuration.  `loadedUnit.unit.plugins.classpath` gives the classpath for the full build file (it is the same as `loadedUnit.classpath` except for the class directory of the full build).

imports contains the list of imports used for the quick configuration.  If just you want the names of the detected plugins and builds, those are 

``` scala
loadedUnit.unit.plugins.pluginNames
loadedUnit.unit.definitions.buildNames
```

The constant imports are I think `Load.baseImports`.

See:
http://harrah.github.com/xsbt/latest/sxr/Load.scala.html#231653

**Comment by retronym** [comment]
That's more or less what I started with. With the classpath, I extracted the module IDs, substituted the cross build version, and run `IvyActions.transitiveScratch(...).`

I would expect that this is useful for other IDEs, so I think it makes sense to include in the update-sbt-classifers task. I can submit a patch if you're open to that idea.

**Comment by harrah** [comment]
Is this still relevant and do you still plan to implement it?

**Comment by retronym** [comment]
It's still relevant -- I didn't add this to sbt-idea directly. I don't have a patch prepared against sbt, either.

Are you happy to add these to `update-sbt-classifiers`?
