### ISSUE TITLE
Publishing test and integration test dependencies in .pom problem

### ISSUE THREAD

**Issue by guntiso** [sbt/sbt#1380]
Dependencies like "com.typesafe" % "config" % "1.2.0" % "it" are published in default [compile] scope in pom. I think integration test dependencies should be published in test scope instead. But if "it" is replaced with "it,test", dependency is published in test scope. There is a contradiction here. If "it" dependency is published in compile scope, "it,test" should also be published in compile scope. Luckily this problem can be used as a workaround for the first one to improve generated pom.

**Comment by jsuereth** [comment]
Thanks for the report. I think the MakePom.scala file may have some limtiations right now in handling configurations.  Pull requests welcome, but this looks like a legitimate bug right now.

**Comment by chEbba** [comment]
Made a workaround with
```scala
makePomConfiguration := makePomConfiguration.value.withConfigurations(Configurations.defaultMavenConfigurations)
```
`sbt.librarymanagement.MakePomConfiguration` contains an optional list of configurations which should be kept in pom and it's empty by default, so all unknown configurations go to compile (empty).
https://github.com/sbt/librarymanagement/blob/c9e4ace8dee2b0e4a2eec5b4daba73d71e7f543d/ivy/src/main/scala/sbt/internal/librarymanagement/MakePom.scala#L493

Can we enable this filter by default?

**Comment by 2m** [comment]
We just stepped on this in https://github.com/akka/alpakka-kafka/issues/504

I applied @chEbba workaround and it seems to do the right thing: "it" dependency is gone from the POM and no other changes to the generated POM file.

I am adding one more +1 to having that `makePom` configuration as default.

**Comment by eed3si9n** [comment]
@chEbba 

> so all unknown configurations go to compile (empty).

That sounds like a bad behavior on whoever's part.

> Can we enable this filter by default?

Sounds good to me too.

**Comment by Philippus** [comment]
@chEbba can you make a PR of your commit? It would be nice to have this in `1.2.0`.
