### ISSUE TITLE
sbt artifacts are missing in Maven Central, Typesafe repo location has been changed

### ISSUE THREAD

**Issue by yatskevich** [sbt/sbt#1386]
Maven Central: http://central.maven.org/maven2/org/scala-sbt/

Previous Typesafe repo location is http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/, but it is http://repo.typesafe.com/typesafe/simple/ivy-releases/org.scala-sbt/ now.

**Comment by jsuereth** [comment]
This is actually an error with our repo hosting.  It's getting fixed now.

The url you list is not the one we want traffic on, and you may notice spurious errors if you use it and we move our infrastructure yet again.

**Comment by yatskevich** [comment]
@jsuereth Thanks for a prompt response! Should I leave all of my resolvers configuration intact and just wait?

**Comment by jsuereth** [comment]
Yes please.  An alternative is to swap, temporarily, to private-repo.typesafe.com domain for the same url

**Comment by yatskevich** [comment]
Great! Thanks a lot!

**Comment by yatskevich** [comment]
@jsuereth Everything is working fine now.
