### ISSUE TITLE
"No scala version specified" for any sbt 0.13.x 

### ISSUE THREAD

**Issue by fernandoracca** [sbt/sbt#1388]
For background info, see issue 1117: https://github.com/sbt/sbt/issues/1117 

Blew up my .sbt/boot directory, and my ivy-repo/cache/org.scala-sbt/sbt folders. Changed the repositories file to 

```
typesafe-ivy-releases: http://repo.typesafe.com/typesafe/ivy-releases
```

build.properties:
sbt.version=0.13.5

Runner is 0.13.5

C:\sse>sbt
Getting org.scala-sbt sbt 0.13.5 ...
downloading http://repo.typesafe.com/typesafe/ivy-releases/org/scala-sbt/sbt/0.13.5/sbt-0.13.5.jar ...
        [SUCCESSFUL ] org.scala-sbt#sbt;0.13.5!sbt.jar (663ms)
:: retrieving :: org.scala-sbt#boot-app
        confs: [default]
        1 artifacts copied, 0 already retrieved (20kB/35ms)
Error during sbt execution: No Scala version specified or detected

C:\sse>sbt
Error during sbt execution: No Scala version specified or detected

ivy.xml

<?xml version="1.0" encoding="UTF-8"?>
<ivy-module version="2.0">
    <info organisation="org.scala-sbt"
        module="sbt"
        revision="0.13.5"
        status="release"
        publication="20140602134641"
        default="true"
    />
    <configurations>
        <conf name="default" visibility="public"/>
    </configurations>
    <publications>
        <artifact name="sbt" type="jar" ext="jar" conf="default"/>
    </publications>
</ivy-module>
# ivy cached data file for org.scala-sbt#sbt;0.13.5
# Mon Jun 02 13:46:42 BST 2014

artifact:sbt#jar#jar#2016651756.exists=true
artifact:sbt#jar#jar#2016651756.location=http://repo.typesafe.com/typesafe/ivy-releases/org/scala-sbt/sbt/0.13.5/sbt-0.13.5.jar
artifact:sbt#jar#jar#2016651756.is-local=false

I always get the ".sbt/boot/other" folder.

In Build.scala:
  lazy val buildScalaVersion          = "2.11.1"

I was using 2.10.3 before but changing the version doesn't make any difference on which folder it creates in .sbt/boot/<scalaVersion>

sbt.update.log:

typesafe-ivy-releases: no namespace defined: using system
    no ivy file in cache for org.scala-sbt#sbt;0.13.5: tried C:\ivy-repository\cache\org.scala-sbt\sbt\ivy-0.13.5.xml
     trying http://repo.typesafe.com/typesafe/ivy-releases/org/scala-sbt/sbt/0.13.5/sbt-0.13.5.pom
        tried http://repo.typesafe.com/typesafe/ivy-releases/org/scala-sbt/sbt/0.13.5/sbt-0.13.5.pom
HTTP response status: 404 url=http://repo.typesafe.com/typesafe/ivy-releases/org/scala-sbt/sbt/0.13.5/sbt-0.13.5.pom
CLIENT ERROR: Not Found url=http://repo.typesafe.com/typesafe/ivy-releases/org/scala-sbt/sbt/0.13.5/sbt-0.13.5.pom
    typesafe-ivy-releases: resource not reachable for org/scala-sbt#sbt;0.13.5: res=http://repo.typesafe.com/typesafe/ivy-releases/org/scala-sbt/sbt/0.13.5/sbt-0.13.5.pom
     trying http://repo.typesafe.com/typesafe/ivy-releases/org/scala-sbt/sbt/0.13.5/sbt-0.13.5.jar
        tried http://repo.typesafe.com/typesafe/ivy-releases/org/scala-sbt/sbt/0.13.5/sbt-0.13.5.jar
    typesafe-ivy-releases: no ivy file found for org.scala-sbt#sbt;0.13.5: using default data
    checking org.scala-sbt#sbt;0.13.5[default] from typesafe-ivy-releases against [none]
    module revision kept as first found: org.scala-sbt#sbt;0.13.5[default] from typesafe-ivy-releases
    found org.scala-sbt#sbt;0.13.5 in typesafe-ivy-releases
Nbr of module to sort : 1
Sort dependencies of : org.scala-sbt#sbt;0.13.5 / Number of dependencies = 0
Sort done for : org.scala-sbt#sbt;0.13.5
storing dependency org.scala-sbt#sbt;0.13.5 in props
    resolved ivy file produced in cache
:: downloading artifacts ::
     trying http://repo.typesafe.com/typesafe/ivy-releases/org/scala-sbt/sbt/0.13.5/sbt-0.13.5.jar
        tried http://repo.typesafe.com/typesafe/ivy-releases/org/scala-sbt/sbt/0.13.5/sbt-0.13.5.jar
downloading http://repo.typesafe.com/typesafe/ivy-releases/org/scala-sbt/sbt/0.13.5/sbt-0.13.5.jar ...
    typesafe-ivy-releases: downloading http://repo.typesafe.com/typesafe/ivy-releases/org/scala-sbt/sbt/0.13.5/sbt-0.13.5.jar
        to C:\ivy-repository\cache\org.scala-sbt\sbt\jars\sbt-0.13.5.jar.part
sha1 file found for http://repo.typesafe.com/typesafe/ivy-releases/org/scala-sbt/sbt/0.13.5/sbt-0.13.5.jar: checking...
    typesafe-ivy-releases: downloading http://repo.typesafe.com/typesafe/ivy-releases/org/scala-sbt/sbt/0.13.5/sbt-0.13.5.jar.sha1
        to C:\Users\x\AppData\Local\Temp\ivytmp7828610082371711060sha1
sha1 OK for http://repo.typesafe.com/typesafe/ivy-releases/org/scala-sbt/sbt/0.13.5/sbt-0.13.5.jar
    [SUCCESSFUL ] org.scala-sbt#sbt;0.13.5!sbt.jar (683ms)
:: resolution report :: resolve 1017ms :: artifacts dl 686ms
Nbr of module to sort : 1
Sort dependencies of : org.scala-sbt#sbt;0.13.5 / Number of dependencies = 0
Sort done for : org.scala-sbt#sbt;0.13.5
    report for org.scala-sbt#boot-app;1.0 default produced in C:\Users\x.sbt\boot\resolution-cache\org.scala-sbt-boot-app-default.xml
    resolve done (1017ms resolve - 686ms download)
:: retrieving :: org.scala-sbt#boot-app
    checkUpToDate=true
post 1.3 ivy file: using exact as default matcher
no explicit confs given for retrieve, using ivy file: file:/C:/Users/x/.sbt/boot/resolution-cache/resolved-org.scala-sbt-boot-app-1.0.xml
    confs: [default]
    retrieving C:\ivy-repository\cache\org.scala-sbt\sbt\jars\sbt-0.13.5.jar
        to C:\Users\x.sbt\boot\other\org.scala-sbt\sbt\0.13.5\sbt-0.13.5.jar
    1 artifacts copied, 0 already retrieved (20kB/12ms)
    retrieve done (12ms)

**Comment by jsuereth** [comment]
Your repositories file looks anemic.  Can you make it as follows:

```
[repositories]
local
maven-central
typesafe-ivy-releases: http://repo.typesafe.com/typesafe/ivy-releases
```

It looks like your SCALA cache may be off right now (i.e. the launcher can't find it).  It's unrelated to your build scala version, it's sbt itself.  It shouldn't land in the other directory, but in a `scala_2.10.4` folder.  If it's landing in an other directory it's because Ivy is unable to find the Ivy which sbt relies on.

**Comment by fernandoracca** [comment]
the repo file contains other internal nexus repos. Do i need local ?

I've tried adding adding them, but it makes no difference.

I've switched everything to 0.13.1 (my previous setup) but it does exactly the same:

build.properties:
sbt.version=0.13.1
Runner: 0.13.1

C:\sse>sbt
Getting org.fusesource.jansi jansi 1.11 ...
:: retrieving :: org.scala-sbt#boot-jansi
        confs: [default]
        1 artifacts copied, 0 already retrieved (111kB/20ms)
Getting org.scala-sbt sbt 0.13.1 ...
downloading http://repo.typesafe.com/typesafe/ivy-releases/org/scala-sbt/sbt/0.13.1/sbt-0.13.1.jar ...
        [SUCCESSFUL ] org.scala-sbt#sbt;0.13.1!sbt.jar (637ms)
:: retrieving :: org.scala-sbt#boot-app
        confs: [default]
        1 artifacts copied, 0 already retrieved (20kB/12ms)
Error during sbt execution: No Scala version specified or detected

C:\sse>sbt
Error during sbt execution: No Scala version specified or detected

Creates boot/other, ivy xml is the wrong one.

I don't understand how this URL will get produced in ivy-0.13.1.properties:
artifact:sbt#jar#jar#2016626744.location=http://repo.typesafe.com/typesafe/ivy-releases/org/scala-sbt/sbt/0.13.1/sbt-0.13.1.jar

Where the file is here:
http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.1/ivys/ivy.xml

I'm running in circles here.

**Comment by jsuereth** [comment]
The "1 artifacts copied looks bad".  IF you look at the ivy file, you'll see a bunch of dependencies listed.   Can you show me what the ivy.xml looks like inside your cache?

Also your proxy repositories in your `~/.sbt/repositories` file looks fine.

**Comment by fernandoracca** [comment]
```
<ivy-module version="2.0">
<info organisation="org.scala-sbt"
    module="sbt"
    revision="0.13.1"
    status="release"
    publication="20140602152111"
    default="true"
/>
    <configurations>
    <conf name="default" visibility="public"/>
    </configurations>
    <publications>
        <artifact name="sbt" type="jar" ext="jar" conf="default"/>
    </publications>
</ivy-module>
```

ivy-properties
        #ivy cached data file for org.scala-sbt#sbt;0.13.1
        #Mon Jun 02 15:21:51 BST 2014
        artifact:sbt#jar#jar#2016626744.exists=true
        resolver=redefined-public
        artifact:sbt#jar#jar#2016626744.is-local=false
        artifact:sbt#jar#jar#2016626744.location=http://repo.typesafe.com/typesafe/ivy-releases/org/scala-sbt/sbt/0.13.1/sbt-0.13.1.jar

I've been trying to capture the output of the resolution-cache folder, but it deletes it before i have time to stop the shell (in windows)

**Comment by jsuereth** [comment]
That ivy.xml file is wrong.  Is that what you see when you download from our repository?  Somehow you're getting a bad ivy.xml file.  Check what yous ee in our repo, when Id ownload the URL you list, I get a different ivy.xml file.

**Comment by fernandoracca** [comment]
resolution-cache:

```
  <ivy-module version="2.0">
        <info organisation="org.scala-sbt"
        module="boot-app"
        revision="1.0"
        status="release"
        publication="20140602152745"
        />
        <configurations>
            <conf name="default" visibility="public" description=""/>
        </configurations>
        <publications>
        </publications>
        <dependencies>
            <dependency org="org.scala-sbt" name="sbt" rev="0.13.1" conf="default->default(compile)">
                <artifact name="sbt" type="jar" ext="jar" conf=""/>
            </dependency>
            </dependencies>
     </ivy-module>
```

Resolution cache properties
      #org.scala-sbt#boot-app;1.0 resolved revisions
      #Mon Jun 02 15:27:46 BST 2014
      +revision:#@#:+0.13.1:#@#:+module:#@#:+sbt:#@#:+organisation:#@#:+org.scala-sbt:#@#:+branch:#@#:+@#:NULL:#@:#@#:=0.13.1 release 0.13.1

Yes, the ivy.xml file is wrong. But that's exactly what i get every time. I deleted the folder at least 20 times to try different things. No other plugin is pulled.

That's what i don't understand, why the url is different.

When i access this URL on the browser: 

```
      http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.1/ivys/ivy.xml
```

I can see the correct output

```
  <ivy-module version="2.0"><info organisation="org.scala-sbt" module="sbt" revision="0.13.1" status="release" publication="20131210101538"><description>
    sbt
    </description></info><configurations><conf name="compile" visibility="public" description=""/><conf name="runtime" visibility="public" description="" extends="compile"/><conf name="test" visibility="public" description="" extends="runtime"/><conf name="optional" visibility="public" description=""/><conf name="provided" visibility="public" description="" transitive="false"/><conf name="sources" visibility="public" description=""/><conf name="docs" visibility="public" description=""/><conf name="pom" visibility="public" description=""/></configurations><publications><artifact name="sbt" type="jar" ext="jar" conf="compile"/><artifact name="sbt" type="src" ext="jar" conf="sources" e:classifier="sources"/></publications><dependencies><dependency org="org.scala-lang" name="scala-library" rev="2.10.3" conf="compile->default(compile)"/><dependency org="org.scala-sbt" name="main" rev="0.13.1" conf="compile->default(compile)"/><dependency org="org.scala-sbt" name="compiler-interface" rev="0.13.1" conf="compile->default(compile)"/><dependency org="org.scala-sbt" name="precompiled-2_8_2" rev="0.13.1" conf="compile->default(compile)"/><dependency org="org.scala-sbt" name="precompiled-2_9_2" rev="0.13.1" conf="compile->default(compile)"/><dependency org="org.scala-sbt" name="precompiled-2_9_3" rev="0.13.1" conf="compile->default(compile)"/><dependency org="org.scala-sbt" name="scripted-sbt" rev="0.13.1" conf="test->test"/></dependencies></ivy-module>
```

**Comment by jsuereth** [comment]
What resolvers do you have listed first?  CHeck these guys as they may be generating a bad ivy.xml file so you never hit the typesafe one for an Ivy.xml file.

**Comment by fernandoracca** [comment]
The project in question, and other projects i've tried on, don't define any resolver. It should use the default Typesafe.resolver right?

But this is even before my project kicks in, since it's SBT itself that downloads incorrectly, whichever version i try to use, which means i'm stuck without SBT.

What's baffling to me is that i'm trying to resolve 
/org/scala-sbt
instead of 
org.scala-sbt

If you go to the URL that it says it just got the jars from: http://repo.typesafe.com/typesafe/ivy-releases/org/scala-sbt/sbt/0.13.1/

you get this:

```
   Index of ivy-releases/org/scala-sbt/sbt/0.13.1
 Name  Last modified      Size
 ../
 Artifactory Online Server at repo.typesafe.com Port 80
```

How can it download the Jar ??

**Comment by jsuereth** [comment]
That's just a trick of artifactory.  It always lists empty directories if your URL looks like a directory listing.

And it's trying to hit maven-style layout if you don't have the ivy pattern defined for your resolve setting.  Again, can we see your `repositories` file?

**Comment by fernandoracca** [comment]
The file i was using in the end, and with which i was able to reproduce the problem with, was just this:

[repositories]
    typesafe-ivy-releases: http://repo.typesafe.com/typesafe/ivy-releases

I renamed the repositories file, ran sbt again, and it started to download jars:

```
Getting org.fusesource.jansi jansi 1.11 ...
:: retrieving :: org.scala-sbt#boot-jansi
        confs: [default]
        1 artifacts copied, 0 already retrieved (111kB/17ms)
Getting org.scala-sbt sbt 0.13.1 ...
downloading http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.1/jars/sbt.jar     ...
        [SUCCESSFUL ] org.scala-sbt#sbt;0.13.1!sbt.jar (710ms)
downloading http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.1    /jars/main.jar ...
        [SUCCESSFUL ] org.scala-sbt#main;0.13.1!main.jar (3797ms)
           downloading http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-interface/0.13.1/jars/compiler-interface-src.jar ...
        [SUCCESSFUL ] org.scala-sbt#compiler-interface;0.13.1!compiler-interface-src.jar (733ms)
       downloading http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-interface/0.13.1/jars/compiler-interface-bin.jar ...
        [SUCCESSFUL ] org.scala-sbt#compiler-interface;0.13.1!compiler-interface-bin.jar (1601ms)
           downloading http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/precompiled-2_8_2/0.13.1/jars/compiler-interface-bin.jar ...
        [SUCCESSFUL ] org.scala-sbt#precompiled-2_8_2;0.13.1!compiler-interface-bin.jar (1061ms)
       downloading http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/precompiled-2_9_2/0.13.1/jars/compiler-interface-bin.jar ...
        [SUCCESSFUL ] org.scala-sbt#precompiled-2_9_2;0.13.1!compiler-interface-bin.jar (1068ms)
       downloading http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/precompiled-2_9_3/0.13.1/jars/compiler-interface-bin.jar ...
```

I have an other and a scala-2.10.3 (the build version)

Ivy Xmls now look correct.

I've now restored my repositories, and all jars resolve back ok. 

I've switched to 0.13.5, and all jars downloaded correctly.....

```
       Getting org.scala-sbt sbt 0.13.5 ...
       downloading http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.5/jars/sbt.jar ...
    [SUCCESSFUL ] org.scala-sbt#sbt;0.13.5!sbt.jar (690ms)
       downloading http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.5/jars/main.jar ...
    [SUCCESSFUL ] org.scala-sbt#main;0.13.5!main.jar (3821ms)
       downloading http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-interface/0.13.5/jars/compiler-interface-src.jar ...
    [SUCCESSFUL ] org.scala-sbt#compiler-interface;0.13.5!compiler-interface-src.jar (593ms)
```

Somehow, removing the repositories file seems to have triggered the fix....

Any ideas?

**Comment by jsuereth** [comment]
One of the repositories in your old repositories file is incorrectly autogenerating an Ivy.xml for you which is bad.  You need to figure out which one (and that can be difficult).

**Comment by fernandoracca** [comment]
Given all the issues around Nexus and Ivy, i think going forward i'll try to setup my own Nexus repo with less dependencies on proxying other repos. 

However, something is particularly broken when SBT tries to download itself. Once it's in the boot directory, it seems to be ok.

I'm ok with the issue for now, but i can't say i have a definitive answer on the cause.

Thanks a lot for your constant support!

**Comment by jsuereth** [comment]
I'm running a proxy Artifactory repository which seems to be going really well.  If you have a chance to write down the steps you do in setting up a proxy, that'd be great.   We do need some better documentation around the specific repositories, as e.g. Nexus needs some custom tricker to support ivy-style layouts (just as Artifactory needs to be configured with the approrpriate artifact patterns)

**Comment by fernandoracca** [comment]
What makes me very uneasy, is that before i renamed the repositories file, the only line i had was:

```
[repositories]
    typesafe-ivy-releases: http://repo.typesafe.com/typesafe/ivy-releases
```

And it wasn't working. Somewhere, somehow, something was been either cached, or blocked.

I'll have a look at Artifactory then. I was hoping to be able to reuse existing infrastructure rather than rolling out my own repo, but there seem to be too much instability around ivy.

**Comment by jsuereth** [comment]
@fractal Yeah, that wouldn't work.   The ivy-releases _ONLY_ has sbt, and not scala, so you woudln't be able to find anyythign else.  You'd at a minimum have to add maven-central or jcenter to that so we can find non-sbt artifacts.

**Comment by fernandoracca** [comment]
I would expect that jars would fail to resolve a dependency, not fail saying that there is no Scala version.

The boot folder looks very different after i removed the repositories file.

now i have:

other   //jansi
scala-2.10.3  // sbt-0.13.1
scala-2.10.4  //sbt-0.13.5

When the file was present, it would add everything inside other and then fail.

**Comment by jsuereth** [comment]
This is an artifact of how the launcher works. My guess is it's not detecting the error correctly.  The launcher marks all artifacts as optional as a workaround for other issues.   You can open a ticket about that.
