### ISSUE TITLE
Do you know what does sbt means in chinese?

### ISSUE THREAD

**Issue by ghost** [sbt/sbt#1392]
This is no issue , just for fun.
Do you know what doese SBT means in chinese words ?
S   => Si  
B   => Bian
T   => Tai

死变态

Translate them into english, means  scum pervert or what ever

LOL

**Comment by eed3si9n** [comment]
sbt is sometimes called 酢豚 (read "subuta") in Japan, which is the Japanese name for 咕嚕肉. If you could come up with some other nicer characters that doesn't involve death or perverts it'll be appreciated.

**Comment by cuipengfei** [comment]
舒伯特
