### ISSUE TITLE
Weird compileOrder behavior

### ISSUE THREAD

**Issue by tpolecat** [sbt/sbt#1404]
In 0.13.5 mixed Scala/Java projects occasionally just start ignoring Java files in Mixed mode, even after clean. For one subproject simply restarting sbt fixed it. In another there were no mutual dependencies and switching to "Java first" worked, and then when I switched _back_ to Mixed mode it _still_ worked. So, something sketchy is going on. 

It's a very large build with many sub-projects; I couldn't get it to fail with a minimal example. Not a lot of clues, sorry, but maybe this rings a bell for someone.

**Comment by eed3si9n** [comment]
Are you using Play 2.2.0 or any other plugins? Name hashing?
