### ISSUE TITLE
Space in user directory name breaks SBT on Windows

### ISSUE THREAD

**Issue by zilti** [sbt/sbt#1412]
```
Error:[info] Loading global plugins from C:\Users\Daniel Ziltener\.IdeaIC13\system\SBT\plugins
[info] Loading project definition from C:\Users\Daniel Ziltener\projects\histrag\project
[info] Set current project to histrag (in build file:/C:/Users/Daniel%20Ziltener/projects/histrag/)
[error] Command file(s) not readable: 
[error]     C:\Users\Daniel
[error]     Ziltener\AppData\Local\Temp\sbt-commands2266811155874878144.lst
```

**Comment by jsuereth** [comment]
Can you post your build definition in the ~/.sbt/plugins directory?

**Comment by purijatin** [comment]
I am facing a similar issue. Posted the details at: https://stackoverflow.com/questions/47122678/java-net-urisyntaxexception-sbt-space-in-path

What is a temporary turnaround to this problem?

**Comment by er1c** [comment]
@purijatin this might be an old ticket, I'm pretty sure this specific issue works fine now on windows

**Comment by purijatin** [comment]
As far as sbt 0.13.16 is concerned it is still an issue

**Comment by SethTisue** [comment]
how about sbt 1.1.1?

**Comment by er1c** [comment]
I can build projects, and I have a space in my name on 1.0.3

**Comment by eed3si9n** [comment]
So this can be closed now?

**Comment by er1c** [comment]
I believe closing is appropriate
