### ISSUE TITLE
Hitting Esc+d at EOL kills the shell

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#1413]
I often use Readline's Esc+d (delete the next word). However for some reason in sbt's shell if I hit this at the end of the line, it does something that makes the shell unusable (can't type or see anything). A fix would be excellent, and a for-now temporary workaround would be great. Thanks.

**Comment by jsuereth** [comment]
It appears like you're triggering something which prevents JLine's "reset" from correctly restoring the console from its tab-completion state.   We may be workign on this area in sbt 1.0, but I'm not quite sure how you're tripping the system right now.  Any more info on exceptions you see, or logs would be appreciated.

**Comment by dwijnand** [comment]
There's no exception and no logs (unless there's some jline-level logging I can enable somehow). Is this reproducable for you? This is on 0.13.5 FYI.

**Comment by dwijnand** [comment]
Some info from the jline trace log (`-Djline.internal.Log.trace=true`)- after hitting Esc+d/Alt+d:

```
[TRACE] Keystroke: 27
[TRACE] Keystroke: 100
[TRACE] Binding: KILL_WORD
[TRACE] Running: [sh,-c,stty -a < /dev/tty]
[TRACE] Result: speed 38400 baud; 66 rows; 231 columns;
lflags: -icanon isig iexten -echo echoe echok echoke -echonl echoctl
    -echoprt -altwerase -noflsh -tostop -flusho -pendin -nokerninfo
    -extproc
iflags: -istrip -icrnl -inlcr -igncr -ixon -ixoff ixany imaxbel -iutf8
    -ignbrk brkint -inpck -ignpar -parmrk
oflags: opost onlcr -oxtabs -onocr -onlret
cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb -crtscts -dsrflow
    -dtrflow -mdmbuf
cchars: discard = ^O; dsusp = ^Y; eof = ^D; eol = <undef>;
    eol2 = <undef>; erase = ^?; intr = ^C; kill = ^U; lnext = ^V;
    min = 1; quit = ^\; reprint = ^R; start = ^Q; status = ^T;
    stop = ^S; susp = ^Z; time = 0; werase = ^W;

[TRACE] Running: [sh,-c,stty -a < /dev/tty]
[TRACE] Result: speed 38400 baud; 66 rows; 231 columns;
lflags: -icanon isig iexten -echo echoe echok echoke -echonl echoctl
    -echoprt -altwerase -noflsh -tostop -flusho -pendin -nokerninfo
    -extproc
iflags: -istrip -icrnl -inlcr -igncr -ixon -ixoff ixany imaxbel -iutf8
    -ignbrk brkint -inpck -ignpar -parmrk
oflags: opost onlcr -oxtabs -onocr -onlret
cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb -crtscts -dsrflow
    -dtrflow -mdmbuf
cchars: discard = ^O; dsusp = ^Y; eof = ^D; eol = <undef>;
    eol2 = <undef>; erase = ^?; intr = ^C; kill = ^U; lnext = ^V;
    min = 1; quit = ^\; reprint = ^R; start = ^Q; status = ^T;
    stop = ^S; susp = ^Z; time = 0; werase = ^W;
```

**Comment by dwijnand** [comment]
Oh, forgot the most important part: it looks like an infinite loop (note the `Running: [sh,-c,stty -a < /dev/tty]` repetition)

**Comment by dwijnand** [comment]
This is no longer broken in sbt 1.0.2.
