### ISSUE TITLE
running private main method

### ISSUE THREAD

**Issue by scalasolist** [sbt/sbt#1415]
SBT gives me error when I try to run main object that contains private class.
## How to reproduce:

Put two files into a folder and run sbt inside

build.sbt:

``` scala
mainClass in (Compile, run) := Some("One")
```

One.scala:

``` scala
object One {
  private[this] def main(args : Array[String]) = {
    println("Welcomes from the One")
  }
}
```

run sbt:

```
sbt compile:run
```
## problem

receive the error:

```
[info] Compiling 1 Scala source to /home/ayvango/Work/scala/test/sbt-fail/target/scala-2.10/classes...
[info] Running One 
[error] (run-main-1) java.lang.NoSuchMethodException: One.main([Ljava.lang.String;)
java.lang.NoSuchMethodException: One.main([Ljava.lang.String;)
        at java.lang.Class.getMethod(Class.java:1665)
```
## notes

Source of the error (my speculation)

http://www.scala-sbt.org/release/sxr/sbt/Run.scala.html#sbt;Run.getMainMethod uses Class.getMethod to retrieve main method. Oracle documentation (http://www.scala-sbt.org/release/sxr/sbt/Run.scala.html#sbt;Run.getMainMethod) states:
Returns a Method object that reflects the specified public member method of the class or interface represented by this Class object

So main method is required to be public, but private[this] switched private modifier for the method. Unless SBT uses custom ClassLoader that neglect private modifier this may be the source of the error.

**Comment by jsuereth** [comment]
So what you're saying is this isn't a bug.   You're trying to run an unrunnable class, and the behavior of sbt is undefined.

Would you like a better error message?   I don't think we'll be adding support for running non-runnable classes, as the goal of `run` is to mimic running your application for real.

**Comment by scalasolist** [comment]
Then why ever sbt contains code that converts (with reported errors actually) private main method to public? Pre java 1.5 private main methods were acceptable, so I have though that sbt mimics that functionality.

**Comment by eed3si9n** [comment]
@scalasolist wrote:

> Pre java 1.5 private main methods were acceptable

According to [Java language spec 1.0](http://titanium.cs.berkeley.edu/doc/java-langspec-1.0/12.doc.html#47024), 

> The method `main` must be declared `public`, `static`, and `void`. It must accept a single argument that is an array of strings.

Scala Language Spec doesn't exactly spell this out:

> A _program_ is a top-level object that has a member method `main` of type `(Array[String])Unit`. Programs can be executed from a command shell. The program’s command arguments are are passed to the `main` method as a parameter of type `Array[String]`.
> The `main` method of a program can be directly deﬁned in the object, or it can be inherited.

But running `scala` from the shell, you would get the same error as sbt if `main` is declared `private[this]`:

```
$ ~/App/scala-2.11.0/bin/scala hello.scala                  
java.lang.NoSuchMethodException: Main.main([Ljava.lang.String;)
        at java.lang.Class.getMethod(Class.java:1665)
        at scala.reflect.internal.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:64)
        at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:99)
        at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:22)
        at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
```

Since Scala is not Java, I don't think it requires further rationalization, but one way of looking at it is the output of `javap` after compiling `hello.scala` with `scalac`.

``` java
$ javap -cp ~/App/scala-2.11.0/lib/scala-library.jar:. Main 
Compiled from "hello.scala"
public final class Main {
}
```

As you can see `main` is quite literally missing from `class Main` when declared with `private[this]`.
