### ISSUE TITLE
SBT Assembly  "Not a Valid Command"

### ISSUE THREAD

**Issue by madhest** [sbt/sbt#1417]
I am using SBT 0.13.5 version
## Simple.sbt

name := "Simple Project"

version := "1.0"

scalaVersion := "2.10.4"

exportJars := true

retrieveManaged := true

libraryDependencies += "org.apache.spark" %% "spark-core" % "1.0.0"

libraryDependencies += "org.apache.cassandra" % "cassandra-all" % "2.0.2"

libraryDependencies += "org.apache.hadoop" % "hadoop-client" % "2.2.0"

resolvers += "Akka Repository" at "http://repo.akka.io/releases/"

resolvers += Resolver.url("artifactory", url("http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases"))(Resolver.ivyStylePatterns)

 addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.11.2")
## SBT compile:

[root@PCSHQ-RSVR my_project]# sbt compile
[info] Loading project definition from /home/pcs/my_project/project
[info] Set current project to Simple Project (in build file:/home/pcs/my_project/)
[info] Updating {file:/home/pcs/my_project/}my_project...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[success] Total time: 59 s, completed Jun 22, 2014 6:44:52 PM
[root@PCSHQ-RSVR my_project]#
## SBT assembly:

[root@PCSHQ-RSVR my_project]# sbt assembly
Java HotSpot(TM) Client VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
[info] Loading project definition from /home/pcs/my_project/project
[info] Set current project to Simple Project (in build file:/home/pcs/my_project/)
[error] Not a valid command: assembly
[error] Not a valid project ID: assembly
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: assembly
[error] assembly
[error]         ^
[root@PCSHQ-RSVR my_project]#
## Error: while executing example program:

14/06/22 18:17:07 INFO TaskSetManager: Serialized task 0.0:1 as 1432 bytes in 1 ms
14/06/22 18:17:07 INFO Executor: Running task ID 0
14/06/22 18:17:07 INFO Executor: Running task ID 1
14/06/22 18:17:07 INFO Executor: Fetching http://10.234.60.249:46433/jars/spark-examples-1.0.0-hadoop1.0.4.jar with timestamp 1403446625638
14/06/22 18:17:07 INFO Utils: Fetching http://10.234.60.249:46433/jars/spark-examples-1.0.0-hadoop1.0.4.jar to /tmp/fetchFileTemp6490344531350556451.tmp
14/06/22 18:17:08 INFO Executor: Adding file:/tmp/spark-5020f4dc-74d4-4893-8434-6ce28ddcf2e8/spark-examples-1.0.0-hadoop1.0.4.jar to class loader
14/06/22 18:17:08 INFO BlockManager: Found block broadcast_0 locally
14/06/22 18:17:08 INFO BlockManager: Found block broadcast_0 locally
14/06/22 18:17:08 INFO NewHadoopRDD: Input split: ColumnFamilySplit((-9223372036854775808, '-4611686018427387904] @[10.234.31.213])
14/06/22 18:17:08 INFO NewHadoopRDD: Input split: ColumnFamilySplit((0, '4611686018427387904] @[10.234.31.214])
14/06/22 18:17:10 ERROR Executor: Exception in task ID 1
java.lang.NoClassDefFoundError: org/codehaus/jackson/annotate/JsonClass
        at org.codehaus.jackson.map.introspect.JacksonAnnotationIntrospector.findDeserializationType(JacksonAnnotationIntrospector.java:524)
        at org.codehaus.jackson.map.deser.BasicDeserializerFactory.modifyTypeByAnnotation(BasicDeserializerFactory.java:732)
        at org.codehaus.jackson.map.deser.BasicDeserializerFactory.createCollectionDeserializer(BasicDeserializerFactory.java:229)

**Comment by eed3si9n** [comment]
Hi. sbt project uses GitHub issues for internal todo list. Please see https://github.com/sbt/sbt/blob/0.13/CONTRIBUTING.md#where-to-get-help-andor-file-a-bug-report on how to get help on using sbt.
