### ISSUE TITLE
`sbt test -- -Dkey=value` does not pass args through...

### ISSUE THREAD

**Issue by johanatan** [sbt/sbt#1418]
... although 

```
$ sbt
> test-only -- -Dkey=value does.
```

This seems like an arbitrary distinction. Any reason why the former can't or doesn't work?

Also, the following equally does not work (but would be nice if it did):

```
sbt test-only -- -Dkey=value
```

**Comment by eed3si9n** [comment]
Hi. sbt project uses Github issues for internal todo list. If you would like to get community help, please open a Stackoverflow question or post it on sbt-dev mailing list. Also see https://github.com/sbt/sbt/blob/0.13/CONTRIBUTING.md.

**Comment by johanatan** [comment]
I don't need any help. It's a bug report/ feature request. Do with it what you wish.
