### ISSUE TITLE
Configurations extending IntegrationTest does not inherit Defaults.testTasks

### ISSUE THREAD

**Issue by pdalpra** [sbt/sbt#1420]
I may be missing something or I may be doing something wrong, but it looks like, the way it's defined, that configurations extending `IntegrationTest` does not "correctly" inherit `Default.testTasks`.

Notice : I'm the maintainer of Gatling's (a load testing tool) SBT plugin, and I will therefore rely on it to show this possible "bug".
## Steps

From this repo : https://github.com/gatling/gatling-sbt/ 
- `publishLocal` to get the plugin in the Ivy cache
- Launch SBT in [this scripted test project](https://github.com/gatling/gatling-sbt/tree/master/sbt-plugin/src/sbt-test/sbt-plugin/copyConfigFiles) using `sbt -Dplugin.version=1.0-SNAPSHOT`
- `show` the value of `gatling:testFrameworks`, notice that the Gatling testing framework is set: 

```
show gatling:testFrameworks
[info] List(TestFramework(WrappedArray(io.gatling.sbt.GatlingFramework)))
```
-  `show` the value of `gatling:loadedTestFrameworks`, notice the framework has been loaded and therefore settings from `testTasks` are applied :

```
> show gatling:loadedTestFrameworks
[info] Map(TestFramework(WrappedArray(io.gatling.sbt.GatlingFramework)) -> io.gatling.sbt.GatlingFramework@a6cf742)
```
- `show` the value of `gatling-it:testFrameworks`, notice that the Gatling testing framework is set: 

```
> show gatling-it:testFrameworks
[info] List(TestFramework(WrappedArray(io.gatling.sbt.GatlingFramework)))
```
-  `show` the value of `gatling-it:loadedTestFrameworks`, notice the framework hasn't been loaded (sidenote: for some reason, it doesn't show up in task completion):

```
> show gatling-it:loadedTestFrameworks
[info] Map()
```
## Problems

Gatling's SBT plugin ([source code](https://github.com/gatling/gatling-sbt/blob/master/sbt-plugin/src/main/scala/io/gatling/sbt/GatlingPlugin.scala)) defines two configurations : 
-  `Gatling`, which extends `Test`
-  `GatlingIt`, which extends `IntegrationTest`

The first one works as intended, and SBT has no trouble loading the test framework and execute Gatling "simulations" as planned.

But the second one, inheriting `IntegrationTest`, doesn't work since the framework hasn't been loaded, even with the framework defined and the testing framework in the classpath.

The `GatlingIt` configuration is configured the same way as the `Gatling` configuration : the related settings combines the parent config default settings and Gatling own settings and scope them into the child configuration.

Again, I may be missing something here.
## Expectations

The testing framework should have been loaded and work as expected for the `GatlingIt` config, as it does for the `Gatling` configuration.

**Comment by eed3si9n** [comment]
> (sidenote: for some reason, it doesn't show up in task completion)

Try running `inspect gatling-it:loadedTestFrameworks`. I suspect it's delegating the task to `IntegrationTest`. Also this should be discussed on Stackoverflow or sbt-dev list until it's confirmed to be an sbt bug.

**Comment by pdalpra** [comment]
You were right, the task was delegated to `IntegrationTest`.
(Re)adding `Defaults.testTasks` to the settings did the trick, but isn't there a way to make it work out of the box ?

**Comment by eed3si9n** [comment]
The documentation talks about extending `Test` configuration http://www.scala-sbt.org/0.13/docs/Testing.html#Additional+test+configurations+with+shared+sources, but I don't know if we support extending `IntegrationTest`. In general extending configuration and rewiring only the specific tasks is a bit flakey.
