### ISSUE TITLE
Spurious caching of old compilation even after clean

### ISSUE THREAD

**Issue by Woodz** [sbt/sbt#1421]
Hello,

I came across an issue with SBT today. I was in a cycle of modifying the code and manually running "test", to make a single failing test pass. Eventually I got the tests passing in the IDE (using a separate compiler) but it was still failing in SBT.

I ran "clean", which executed successfully and forced a compile of the modified files on the next run of "test". However, the test was still failing. Only by killing SBT (ctrl+c) and restarting did the test then pass.

My understanding is the clean should delete all caches of compiled code, meaning that the test should have passed after the clean.

**Comment by eed3si9n** [comment]
Hi, I appreciate the report, but it's difficult to follow up with this description without more info. Could you provide the version of your sbt, whether you're using name hashing, content of `target` directory after `clean`, and whether you can reproduce the issue on demand? Also see - https://github.com/sbt/sbt/blob/0.13/CONTRIBUTING.md

**Comment by Woodz** [comment]
Unfortunately this is a spurious error, so reproduction is not possible on demand. I am using SBT 0.13.0. I don't know if I am using name hashing - the .sbt file does not specify whether it is enabled or not. I am not able to provide the contents of the target directory as this contains commercially sensitive information.
I understand that this problem is very vague and doesn't meet your bug requirements, but I am unable to accurately reproduce this issue which means that I cannot post my build.sbt or source code here.

**Comment by eed3si9n** [comment]
If `clean` worked properly, the content of `target` directory should be empty. There has been lots of bug fixes and enhancements to incremental compiler throughout 0.13.x series, so try 0.13.2 or 0.13.5 and see if you the problem persists. I'm closing the case for now, but feel free to reopen it if you find problem with 0.13.5.
