### ISSUE TITLE
Explain what to do in the message "The global sbt directory is now versioned"

### ISSUE THREAD

**Issue by jaceklaskowski** [sbt/sbt#1427]
The question on StackOverflow [Why is the message “The global sbt directory is now versioned” in 0.13?](http://stackoverflow.com/q/24422115/1305344) shows that there's at least one person who considers the message confusing.

When I read it once more, it is indeed a bit confusing as it doesn't explain what a user should do to get rid of the message (aka comply to the new global directory layout).

We could _even_ point at the document in the docs.

**Comment by eed3si9n** [comment]
Please bring this up to sbt-dev instead since Github issues are for confirmed bugs and internal todos. See https://github.com/sbt/sbt/blob/0.13/CONTRIBUTING.md.
