### ISSUE TITLE
0.13.6-MSERVER-4 not looking for plugins in the right place

### ISSUE THREAD

**Issue by havocp** [sbt/sbt#1432]
In sbt-remote-control, if we try to open a project using say the eclipse plugin, it looks in `http://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.10/sbt_0.13.6-MSERVER-4/2.3.0/ivys/ivy.xml` which of course does not exist. `[sbtVersion]` in the ivy pattern should be just 0.13 not 0.13.6-MSERVER-4.
It seems that sbt can't find the right binary version with the `-MSERVER-4` on there.

**Comment by eed3si9n** [comment]
Workaround:

``` scala
addSbtPlugin("com.typesafe.sbt" % "sbt-gh-pages" % "0.5.2", "0.13")
```

**Comment by dwijnand** [comment]
rip sbt-remote-control
