### ISSUE TITLE
scalaInstance is different from scalaVersion

### ISSUE THREAD

**Issue by MasseGuillaume** [sbt/sbt#1436]
maybe it's a bug ?

http://stackoverflow.com/questions/24619283/why-scalainstance-is-different-from-scalaversion-in-sbt

**Comment by eed3si9n** [comment]
I don't think this is a bug. It's behaving as its currently designed as explained by @lpiepiora on the linked question. If you have ideas on improving the current design, please bring it up to sbt-dev.
