### ISSUE TITLE
doc nav is slightly irritating

### ISSUE THREAD

**Issue by tpolecat** [sbt/sbt#1443]
In a reasonably-sized browser window the "go left" and "go right" regions take up about 25% of the width of the window and it's really easy to click over to the next or previous page as you're mousing around. At least for me; I do it every single time I look at the doc. What would you think about maybe just making the buttons hot instead of the entire margin?

**Comment by eed3si9n** [comment]
Could you move this issue to sbt/website?

**Comment by tpolecat** [comment]
Oops, sorry.
