### ISSUE TITLE
Macro implementation when using triggers is not working

### ISSUE THREAD

**Issue by huntc** [sbt/sbt#1444]
This works:

```scala
discoveredDist <<= (dist in ReactiveRuntime)
  .storeAs(discoveredDist in Global)
  .triggeredBy(dist in ReactiveRuntime)
```

however this doesn't:

```scala
discoveredDist := (dist in ReactiveRuntime)
  .storeAs(discoveredDist in Global)
  .triggeredBy(dist in ReactiveRuntime)
  .value
```

**Comment by liff** [comment]
Minimal repro:

``` scala
// build.sbt
val hello = taskKey[Unit]("hello")
val world = taskKey[Unit]("world")

hello := println("hello")
world := println("world")

world := (world triggeredBy hello).value // prints "hello", should print "hello\nworld"

// world <<= world triggeredBy hello // works
```

Run with `sbt hello`.

**Comment by cunei** [comment]
It seems this issue is only incidentally related to the macro expansion. The code that is generated when this expression is expanded:
```
world := (world triggeredBy hello).value
```
in the end happens to be similar to:
```
world <<= ((world triggeredBy hello) map ( a => a ))
```
In the latter expression, the ``triggeredBy`` for some reason gets ignored; that happens on 0.12.x as well. I'm doing some debugging now.

**Comment by eed3si9n** [comment]
### old logic

If we consider a task to consists of two parts, `value` function and *an attribute list*, the existing behavior is defensible. `<<=` binds both the parts to the LHS task key whereas `:=` creates a brand new task using the given value and a blank attribute list. 

In that logic,

```scala
world := (world triggeredBy hello).value
```

is not much different from

```scala
world := {
  val x = (world triggeredBy hello).value
  123
}
```

or 

```scala
world := 123
```

### Functor law

The part that starts to break down is `map`.
The first functor law states that mapping with `identity` should not modify the original functor.
See also http://eed3si9n.com/herding-cats/Functor.html
It might not be strictly enforced, but the law matches the intuitive feel people on the standard collections too.

### new ideas?

Even though it's forgetful, focusing only on the value using `:=` is very valuable in flattening the learning curve of sbt.

One workaround might be to track triggers as a separate key:

```scala
onComplete in hello += world
```

This would move the trigger as if they are values, and at the end of the loading we can put them to the appropriate task attributes.

**Comment by gabro** [comment]
Is there a workaround to this issue that will achieve the same behavior without triggering a deprecation warning in sbt?

**Comment by cunei** [comment]
@dwijnand 👍

**Comment by jcranky** [comment]
This fix is not available on 0.13.x yet, right?

**Comment by dwijnand** [comment]
It's available in 0.13.14-RC1.

**Comment by jcranky** [comment]
thanks, worked fine with that version :)

**Comment by fdietze** [comment]
Hi, this does not seem to be fixed for me:

```scala
refreshBrowsers <<= refreshBrowsers.triggeredBy(WebKeys.assets in Assets)
```
works, while
```scala
refreshBrowsers := refreshBrowsers.triggeredBy(WebKeys.assets in Assets)
```
does not.

```
sbt.version=0.13.15
```

Project source: https://github.com/woost/wust2/blob/dff8fdcdd13d39dfaf51e61b9ec251b99d1e619c/build.sbt#L232

Do you need more information?

**Comment by jvican** [comment]
Did you miss '.value' intentionally in the code snippet that uses `:=`?

**Comment by fdietze** [comment]
Good catch! That was not intentional, it works with `.value`. Thank you!

It's strange though that I didn't get a compile error...

**Comment by eed3si9n** [comment]
It's because the expected `Unit` discards value, so it didn't catch the lack of `.value` invocation.

**Comment by mborra** [comment]
Hi to all, I have tried with :

compile in MultiJvm := ( compile in MultiJvm ).triggeredBy( compile in Test ).value

instead of:

compile in MultiJvm <<= ( compile in MultiJvm ) triggeredBy ( compile in Test )

But doesn't works

**Comment by jvican** [comment]
Which sbt version?

**Comment by mborra** [comment]
Sorry, 0.13.13

**Comment by jvican** [comment]
This thread says that the fix for `triggeredBy` is only available in 0.13.14. You need to update.

**Comment by mborra** [comment]
Sorry, you're right.

**Comment by cheevo** [comment]
// Here is a snippet that might  help those that 
// have had the same problem and need  some example code showing a
// brief solution that works
> sbt sbtVersion
 [info] 1.0.2

Within build.sbt
>lazy val copyDocAssetsTask = taskKey[Unit]("Copy doc assets")
target in Compile in doc :=  baseDirectory.value /"public/wiki"
copyDocAssetsTask := {
  println("Copying doc Images")
  val sourceDir =  baseDirectory.value / "extra-resources"
  val targetDir = (target in (Compile, doc)).value  
  val targ = targetDir / "/extra-resources"
  println("From "+ sourceDir)
  println("To "+ targ)
  IO.copyDirectory(sourceDir, targ)
}
copyDocAssetsTask := (copyDocAssetsTask triggeredBy (doc in Compile)).value

call doc
>sbt compile doc
>[info] Main Scala API documentation successful.
Copying doc Images
From /root/fogcomput/code/Appliance/fogcomputlabs/extra-resources
To /root/fogcomput/code/Appliance/fogcomputlabs/public/wiki/extra-resources

Thanks to  all on thread for doing the hard work.
