### ISSUE TITLE
When HOME is not set, sbt shows a 'dirname: missing operand' error on launch

### ISSUE THREAD

**Issue by raboof** [sbt/sbt#1445]
I'd like to provide a pull request but I can't find the start script (found in /usr/share/sbt-launcher-packaging/bin/sbt on Debian) in git.

**Comment by jsuereth** [comment]
IT's in `sbt/sbt-launcher-package`.  Please open this bug there, and thanks for the report/pending PR!

**Comment by raboof** [comment]
Created https://github.com/sbt/sbt-launcher-package/pull/69

**Comment by rainabba** [comment]
I hit this on WSL/Ubuntu for an unrelated project, but it turns out to be because readlink isn't available in my environment (docker container) and so a script was failing at that point, which resulting in the dirname error. When the script was updated to use realpath, I stopped seeing this.
