### ISSUE TITLE
Avoid updating snapshots in continuous run mode

### ISSUE THREAD

**Issue by mariussoutier** [sbt/sbt#1446]
Hi,

first off, I'm not sure if this is related rather to sbt or Play, so please give me an indication where this problem might be rooted.

When developing client-side-heavy apps with Play, I'm usually running Play in continuous mode ( `sbt ~run`) and make many small changes that get reflected in the browser instantly via play-autorefresh. I have a couple of snapshot dependencies, and these are checked again and again when recompiling code or assets.

Especially if I have multiple sbt processes running, one that is checking snapshots for the 1000th time can block the others with the dreaded `Waiting for lock on ~/.ivy2/.sbt.ivy.lock to be available...`.

My guess is that this error stems from the fact that compile depends on update, but it is driving me insane, and stands in stark contrast to the otherwise wonderful development experience that is Play and sbt.

Cheers

**Comment by jsuereth** [comment]
Hmm, are you doing something like including the timestamp in the version?   Sbt should not be running update unless it detects that your calls to ivy are out of date, or something else is cleaning out the `target/resolution-cache` and `target/streams` directories.

**Comment by mariussoutier** [comment]
No, the snapshots are normal libraryDeps:

``` scala
libraryDependencies ++= Seq(
  "org.reactivecouchbase" %% "reactivecouchbase-play" % "0.3-SNAPSHOT",
  "org.couchbase.mock" % "CouchbaseMock" % "0.7-SNAPSHOT" % "test")
```

One of the sub-projects has itself a snapshot version, could that cause this behavior?

**Comment by mariussoutier** [comment]
From time to time I also get:

``` scala
ResolveException: unresolved dependency: org.reactivecouchbase#reactivecouchbase-play_2.10;0.3-SNAPSHOT: not found
unresolved dependency: org.couchbase.mock#CouchbaseMock;0.7-SNAPSHOT: not found
```

**Comment by eed3si9n** [comment]
Are you experiencing this issue? If so what's the Play and sbt version? Also do you have any dependencyOverrides? Running `run` continuously shouldn't trigger re-resolution if the dependency list hasn't changed. But there was at least one bug that was invalidating the cache incorrectly, so you could be hitting something like that.

**Comment by mariussoutier** [comment]
I just experienced this issue again, using Play 2.3.7 and sbt 0.13.7. I do not use `dependencyOverrides`.

**Comment by mariussoutier** [comment]
Here is what the console looks like:
http://pastebin.com/GrYpnNC3

Just one thing, ReactiveCouchbase is only a transitive dependency, we are depending on "org.reactivecouchbase" %% "reactivecouchbase-play" % "0.3.1", i.e. a non-snapshot.

**Comment by evanbennett** [comment]
@mariussoutier Have you confirmed this happens without the play-autorefresh plugin?

**Comment by mariussoutier** [comment]
@evanbennett Yes I have disabled it a while ago and it still occurs, even with sbt 0.13.8.

**Comment by skdangi** [comment]
Any update on this. This is frustrating slow.

**Comment by eed3si9n** [comment]
Not sure if this is still relevant, but sbt 1.3.0 switches to Coursier so SNAPSHOTs handling would be different.
