### ISSUE TITLE
0.13.5: autoImports always applied even if plugin not enabled

### ISSUE THREAD

**Issue by pfn** [sbt/sbt#1449]
I have an AutoPlugin that looks like the following:

```
object AndroidPlugin extends AutoPlugin {

  override def trigger = noTrigger
  override def requires = plugins.JvmPlugin

  object autoImport extends KeysContainer {
    type ProjectLayout = android.ProjectLayout
    val ProjectLayout = android.ProjectLayout

    type ProguardCache = android.ProguardCache
    val ProguardCache = android.ProguardCache
    type ProguardInputs = android.ProguardInputs
    val ProguardInputs = android.ProguardInputs

    import Dependencies.artifacts
    def apklib(m: ModuleID, n: String): ModuleID = artifacts(m, n, "apklib")
    def apklib(m: ModuleID): ModuleID            = artifacts(m, m.name, "apklib")
    def aar(m: ModuleID, n: String): ModuleID    = artifacts(m, n, "aar")
    def aar(m: ModuleID): ModuleID               = artifacts(m, m.name, "aar")

    val AutoLibraryProject = Dependencies.AutoLibraryProject
    type AutoLibraryProject = Dependencies.AutoLibraryProject

    type LibraryProject = Dependencies.LibraryProject
    val LibraryProject = Dependencies.LibraryProject
  }
}
```

I get this error when I run my scripted tests:

```
[error] C:\Users\pfnguyen\AppData\Local\Temp\sbt_ccd486fb\lib-with-resources\build.sbt:7: error: reference to platformTarget is ambiguous;
[error] it is imported twice in the same scope by
[error] import android.Keys._
[error] and import _root_.android.AndroidPlugin.autoImport._
[error] platformTarget in Android := "android-17"
[info] [error] Type error in expression
[error] ^
```

The plugin is added via addSbtPlugin(......) and the test case can be found here https://github.com/pfn/android-sdk-plugin/tree/master/sbt-test/android-sdk-plugin/lib-with-resources

I would expect that autoImport is not applied unless enablePlugins() is called explicitly. Even if addSbtPlugin is used.

**Comment by pfn** [comment]
Additionally, Keys and autoImport extend from a KeysContainer trait so that users of the plugin need not enablePlugin to use the existing, pre-0.13.5 functionality.

**Comment by jsuereth** [comment]
Just a note: The autoImport, AFAIK is meant to be ALWAYS imported, not just when the plugin is active.   They're two different systems, that doesn't mean the plugin itself is active, just that the autoImport is there.

**Comment by eed3si9n** [comment]
Thanks for this report. Auto import got merged into auto plugin feature at the last minute, and this could have been an oversight on my part.

> I would expect that autoImport is not applied unless enablePlugins() is called explicitly.

Set aside the fact that auto plugin can be enabled via trigger, I agree with your expectation. Maybe we should discuss this with others on sbt-dev. Could you start a thread there?

**Comment by jsuereth** [comment]
@eed3si9n Whether or not it SHOULD be enabled is a good question.  It is working as initially designed.  I agree it's subtle and confusing, but I'm not sure we can actually implement it to work as you'd expect (again fun with scala compilation).  You need to have the imports in place to compile the build BEFORE you know which plugins are enabled on the build.

**Comment by pfn** [comment]
Are we talking about .sbt files or .scala?

I'm of the opinion that .scala files should absolutely not have
autoimports. And by the time .sbt files are processed, the Project object
should be configured with autoplugins, I kind of expect?

**Comment by jsuereth** [comment]
@pfn We're talking about sbt files for the import magic.   And no, we can't expand autoPlugins before the .sbt because the .sbt file could be defining the Project instance.  e.g.

``` scala
lazy val root = (project in file(".")).enablePlugins(MoarPlugin)
```

SO, technically, we're constrained here unless we further constrain build.sbt environment (a possibility, but not something that will happen in the 0.13.x series).

In any case, just as previously in the `Plugin` API, you should try to keep to a minimum of exposed DSL in `autoImport` to avoid conflicts and give your users the best experience.

**Comment by jvican** [comment]
I can fix this in a breeze. Will do if someone doesn't beat me to it.

**Comment by jvican** [comment]
Actually, I think this cannot ever be fixed. As Josh points out, it's not possible to know whether a plugin is enabled or not at compile time, so the imports are required.
  
The ticket already explains why this is the case. Honestly, I would just close this issue.

**Comment by dwijnand** [comment]
Yeah. We might want to put a warning in the plugin docs, but this isn't getting fixed.
