### ISSUE TITLE
preload scripts in sbt console

### ISSUE THREAD

**Issue by thirstycrow** [sbt/sbt#1453]
Is there a setting to specify scripts to preload in sbt console. I know there is initialCommands, but it takes only scala code rather than repl commands, so with a value of ":load debug.scala", the console failed to start with an error:

```
<console>:1: error: illegal start of definition
       :load debug.scala
       ^
```

**Comment by som-snytt** [comment]
You can

```
$ sbt -Dscala.repl.autoruncode=script console
```

with one file.

**Comment by jsuereth** [comment]
I'm going to migrate this into a feature request that anyone is free to implement.  I think you'd have to adapt our hooks into the REPL.

**Comment by thirstycrow** [comment]
I found a workaround: when starting the REPL, sbt passes scalacOptions to the interpreter as the argument of the main method of scala.tools.nsc.interpreter.ILoop, and the interpreter checks the argument to find files to load. So files to be loaded can be specified like following:

``` scala
scalacOptions in (Compile, console) ++= Seq(
  "-i", file1.getPath,
  "-i", file2.getPath,
  ...
)
```

**Comment by eed3si9n** [comment]
I am closing this since there's a workaround.
