### ISSUE TITLE
Ability to set baseDirectory

### ISSUE THREAD

**Issue by 404-** [sbt/sbt#1457]
I'd like to have a way of specifying baseDirectory. I don't see a good reason why all sources, resources, etc. must be contained in the same directory. The best analogy I can think of is Ant's basedir attribute in the project element - does this concept not exist in SBT (or is it just not exposed properly)?

Please, see the [related StackOverflow post](http://stackoverflow.com/questions/21029916/can-buildbase-point-to-directory-outside-current-project-in-sbt) for more details

**Comment by jsuereth** [comment]
I think this question was answered sufficiently on stackoverflow.  Please refrain from opening issues unless you have a specific feature request, preferably discussed on sbt-dev first, or broken behavior which can be reproduced.

Thanks!

**Comment by 404-** [comment]
[I tried that](https://groups.google.com/forum/#!searchin/sbt-dev/$20basedirectory/sbt-dev/X1C_JVs0y9M/vF0LL28BBmMJ) to no avail. Would you like to go back to that thread and answer my question there?
