### ISSUE TITLE
Explicit subproject dependencies bringing names into scope

### ISSUE THREAD

**Issue by copumpkin** [sbt/sbt#1460]
This might be too weird/magic, but conceptually a dependency on something is basically parametrizing yourself on it.

What I'd like in my multi-project build is:

in the root `build.sbt`:

```
val subproject1 = project
val subproject2 = project
val subproject3 = project.dependsOn(subproject1)
val subproject4 = project.dependsOn(subproject3, subproject2)
```

then in individual subproject-specific `.sbt` files (in the respective folders), the dependencies would be in scope. That is, in e.g. `subproject3/build.sbt`, I would be able to refer to `subproject1`. I can currently do that in an unstructured way with `LocalProject("subproject1")` but that can obscure project interdependencies. Crucially, I don't want to be able to refer to `subproject2` in `subproject3`, because I have not stated that I depend on it.

Does that make sense?

**Comment by eed3si9n** [comment]
Hi Dan,

Although we sometimes we allow bug reports to be directly reported on Github issues, we mainly use it for internal todo list (see https://github.com/sbt/sbt/blob/0.13/CONTRIBUTING.md for more details). If you have enhancement idea on build.sbt DSL, could you bring it up on sbt-dev list first where others interested in this topic can participate?
