### ISSUE TITLE
Track provenance of references to undefined settings

### ISSUE THREAD

**Issue by copumpkin** [sbt/sbt#1461]
I'm in an unpleasant situation where I get a bunch of errors along the lines of:

```
References to undefined settings: 
  */compile:compile from */compile:compile
```

which is utterly unhelpful for debugging. If I could have some sort of indication of where that reference came from, be it a source location, a chain of settings calls, or whatever else, that'd be hugely helpful. Is there some sort of debugging feature that would help?

**Comment by eed3si9n** [comment]
This would also be an interesting topic for sbt-dev. I don't think we have Pos on the settings.
