### ISSUE TITLE
Make pluginParser working with autoplugins (for plugin command)

### ISSUE THREAD

**Issue by jaceklaskowski** [sbt/sbt#1464]
As per [the discussion in sbt-dev](https://groups.google.com/d/msg/sbt-dev/oiypIgdCHtY/_WcAMWi5j2oJ), executing `plugin` command with no autoplugin specified gives an error message:

```
> plugin
[error] plugin usage:
[error]
[error]
[error] plugin
[error]       ^
```

**Comment by eed3si9n** [comment]
Duplicate of #1416 fixed by #1426.
