### ISSUE TITLE
Obscure error in .sbt files: "error: not found: object $0ff9ef6ceddbe4a02c28"

### ISSUE THREAD

**Issue by copumpkin** [sbt/sbt#1465]
## steps

builld.sbt

``` scala
lazy val common = project
lazy val boink  = project
lazy val woof   = project

organization := "org.foo.bar"

name         := "oink"

version      := "0.0.1"

scalaVersion := "2.10.4"
```

project/build.properties

```
sbt.version=0.13.5
```

boink/boik.sbt

``` scala
val commonP = LocalProject("common")

// This is needed to make it fail
name := "boink"
```

woof/woof.sbt

``` scala
val commonP = LocalProject("common")

name := "woof"
```
## original report

Or some other random-looking hash. This is in a fairly meaty complex build, so I haven't been able to reduce it to a small failing test case yet, but it appears to be happening in generated code to process the .sbt files.

The more complete error is:

```
path/to/my/subproject/build.sbt:0: error: not found: object $0ff9ef6ceddbe4a02c28
import $0ff9ef6ceddbe4a02c28._
```

Not really sure what made it start happening. My build was working just fine and then this started happening, and even blowing away all intermediate build results in the project (or a completely fresh clone) doesn't seem to resolve it.

Err, my sbt version is 0.13.5.

Edit: okay, that's really weird. I reran the exact same build again and it worked :(

Edit 2: and it happened again (this is one contiguous session, with no external file changes):

```
[info] Loading project definition from /path/to/my/project
/path/to/my/project/subproject1/foo.sbt:0: error: not found: object $2760190dc5713da08b6a
import $2760190dc5713da08b6a._
       ^
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? r
[info] Loading project definition from /path/to/my/project
/path/to/my/project/subproject2/bar.sbt:0: error: not found: object $ca47cce92c49b31ace91
import $ca47cce92c49b31ace91._
       ^
/path/to/my/project/subproject2/bar.sbt:11: error: not found: value x
  val someVal = x
                ^
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? r
[info] Loading project definition from /path/to/my/project
[info] Set current project to lightspeedRoot (in build file:/path/to/my/project/)
> 
```

Note how the first time it complains about one file. I then tell it to reload and it complains about a different file. I then tell it to reload again and it succeeds. Some sort of race condition perhaps?

**Comment by copumpkin** [comment]
Additional information:
- It's always the same two sbt files that fail, in the same order. Retrying twice always succeeds.
- The autogenerated/hash name is different every time.
- Decompiling the object it imports reveals that it's an object that only contains the val definition I stuck at the top of my failing .sbt files.
- At the point where it asks me to retry/quit/last/ignore, the relevant .class files (with and without trailing dollar signs for object/class) already exist. I'm assuming it's generating them asynchronously and they don't exist at the moment it tries to compile, and by the time I see the message they've entered existence.
- It seems to be failing at https://github.com/sbt/sbt/blob/9df5882766b57af046899d1724f60b909549bf9e/main/actions/src/main/scala/sbt/compiler/Eval.scala#L164. I see no relevant log output in my last command. Do I need to build my own sbt and hack up the relevant compilation code to see what's going wrong, or is there a better way?

I still haven't been able to reduce this bug on a smaller build, so I apologize for a less-than-ideal bug report, but I'm willing to experiment if anyone has ideas.

**Comment by copumpkin** [comment]
I've "fixed" it for now. I added some dummy `val foo = 0` declarations to the failing files and they stopped failing. Another one started failing after that, and then after I added some dummy `val`s to that one too, everything worked again. It seems to be repeatable in that I can delete my sbt build files (`project/target` and such) and have it rebuild consistently.

Disturbing :cold_sweat:.

**Comment by eed3si9n** [comment]
Could you describe the nature of your build? Are you using auto plugins?

**Comment by copumpkin** [comment]
No auto-plugins. I currently have a root `build.sbt`, some common Scala logic under `project` along with some (old-style) plugins in `project/plugins.sbt`. Then I have a bunch (over a dozen) of subprojects, each with subproject-specific settings under `<subproject>/<subproject>.sbt`. I'm not completely sold on this project structure, and am actively trying to simplify the build to minimize the amount of customizations, but it used to be in a monolithic file and this seemed like a stepping stone to simplifying the build.

**Comment by eed3si9n** [comment]
ok. It would be super helpful if you could come up with a reproducible test project that you can make public, but dozen project, subprojects having their own sbt, and wacky import statement could be a good starting point for us to start digging into.

**Comment by copumpkin** [comment]
I've been trying to without much luck so far (might have something to do with the scale). I'll try some more :smile:

**Comment by copumpkin** [comment]
To be clear, the wacky import statement is autogenerated by sbt for `val` definitions in .sbt files, it seems.

**Comment by copumpkin** [comment]
Okay, here it is on a silver platter: https://www.dropbox.com/s/g4wj35lxr6ifdmp/bug.tar.gz :smile:

**Comment by jsuereth** [comment]
Yeah, that's the internal hackery of how sbt compiles your .sbt files.  Thanks for the reproducible test case, I'll take a look now.

**Comment by jsuereth** [comment]
@eed3si9n This appears to be an issue with namespaces, which we were discussing before.

While we pretend that .sbt files each have an individual namespace, I think the way we HASH setting instances is idempotent by the string which defines them.  @copumpkin here has defined the same val, using the same string, in more than on sbt file.  

@copumpkin in sbt 0.13.6 (milestone released soon), you'll get ambiguity errors when trying to `set` or `consoleProject` with this type of setup.  For now, a legitimate workaround is to not have to `val`s with the same name.   Theoretically, they have different namespaces, but practically, they are in the same namespace right now.

Shouldn't be a hard workaround for now, just add the .sbt filename to the HASH when generating the object to contain the value.   This should match the scoping rules @eed3si9n and I discussed we'll have in .sbt files for now.

**Comment by copumpkin** [comment]
Interesting! Why did adding dummy `val`s (without renaming the original duplicate one) fix it?

**Comment by jsuereth** [comment]
@copumpkin It's a hash conflict.  I think position may be a part of the hash (line number) or some other aspect.   I'm just super glad your reproducible test case is small enough to be reproducible and demonstrate the issue :)

**Comment by copumpkin** [comment]
Aha, I think I see, thanks!

**Comment by copumpkin** [comment]
@jsuereth you mentioned that in 0.13.6 I'll get ambiguity errors if I do consoleProject or set, but what's the long-term right behavior here? I'd expect it to either keep them in separate namespaces or give me a sensible error on startup.

**Comment by eed3si9n** [comment]
Should we discuss scoping semantics of sbt DSL with regards to `def`s and `val`s on sbt-dev first?

**Comment by jsuereth** [comment]
@eed3si9n Perhaps.

@copumpkin That is the expected behavior.  `consoleProject` and `set` implicitly import ALL .sbt scopes, so it is ambiguous in that scenario.  FYI - in sbt 0.13.5 you just can't reference them at all...

**Comment by jsuereth** [comment]
The code in interest: https://github.com/sbt/sbt/blob/0.13/main/actions/src/main/scala/sbt/compiler/Eval.scala#L116-L118

**Comment by paulp** [comment]
This change is almost certainly behind the regression seen in #1568.

**Comment by deepakmbr** [comment]
We are facing the exact issue now. Strangely though, it does not happen on dev machines ever, but happens always while running in github actions (self hosted runner). Re-running the workflow succeeds. @jsuereth  @eed3si9n Any ideas ? Thank you.

sbt version : 1.7.2

```
/path/to/my/project/subproject1/build.sbt:0: error: not found: object $3572535fcafeb4da8716
import $3572535fcafeb4da8716._
```

**Comment by eed3si9n** [comment]
@deepakmbr Let me create a fresh issue instead of necromancing issue from 2014.
