### ISSUE TITLE
Give ability to stop/kill a running task without exiting SBT.

### ISSUE THREAD

**Issue by aloiscochard** [sbt/sbt#1471]
Currently if a long compilation/test start, there is no way to stop it without restarting.

What would be great is to be able to use `CTRL+D` for that purpose, I think that's what folks will try intuitively.

**Comment by eed3si9n** [comment]
Hi Alois, sbt project currently uses Github issues for internal todo list. If you have enhancement ideas, please send us pull req or bring it up on sbt-dev list. - https://github.com/sbt/sbt/blob/0.13/CONTRIBUTING.md
