### ISSUE TITLE
Kill/Stop current task on filesystem change.

### ISSUE THREAD

**Issue by aloiscochard** [sbt/sbt#1472]
Currently if a long test/compilation was triggered in `~` mode, and then the user do an other file change during that task, the task is not restarted.

Which mean the enduser will have to wait for the test to finish, and then a new task will automatically created.

One could avoid wasting all that time, by directly killing the running task and restart when a change occur (we could argue about making that configurable).

Related: https://github.com/sbt/sbt/issues/1471

**Comment by copumpkin** [comment]
:+1:

**Comment by eed3si9n** [comment]
Hi Alois, sbt project currently uses Github issues for internal todo list. If you have enhancement ideas, please send us pull req or bring it up on sbt-dev list. - https://github.com/sbt/sbt/blob/0.13/CONTRIBUTING.md
