### ISSUE TITLE
Add auto-retry command line flag

### ISSUE THREAD

**Issue by joscha** [sbt/sbt#1481]
In the last few days travis builds fail quite often because a download could not be finished, e.g.

``` console
[error] (*:update) sbt.ResolveException: download failed: commons-io#commons-io;2.4!commons-io.jar
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

as it is an automated install, there is no way to react to those via input at that time, so I wanted to find out if there would be the possibility to add a command line flag for sbt for automated installs that could control this (e.g. retry X times).

**Comment by eed3si9n** [comment]
Hi sbt project uses Github issue for internal todo list. If you have ideas for enhancements, please send us a pull req or bring it up to sbt-dev - https://github.com/sbt/sbt/blob/0.13/CONTRIBUTING.md
