### ISSUE TITLE
[error] Not a valid command: / (similar: <, -, ~)

### ISSUE THREAD

**Issue by kry** [sbt/sbt#149]
My build file looks like this:

name := "Invoices"

version := "1.0"

scalaVersion := "2.9.0"

libraryDependencies += "junit" % "junit" % "4.8.1" % "test"

libraryDependencies ++= Seq(
    "org.scalatest" % "scalatest" % "1.6.1"
)

resolvers += "Scala-Tools Maven Repository" at "http://scala-tools.org/repo-releases/org/scalatest/scalatest_2.9.0/1.6.1/"

When I run sbt I get the following:

[error] Not a valid command: / (similar: <, -, ~)
[error] /usr/bin/sbt
[error]  ^

**Comment by harrah** [comment]
Please use the mailing list for questions.
