### ISSUE TITLE
libraryDependency mangled

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#1496]
I have a library dependency declared as

```
"org.scala-lang" %% "scala-swing" % "1.0.1-SNAPSHOT-java7"
```

which was published with maven and everything about the published artifact looks good.

But sbt 0.13.5 keeps trying to resolve it as

```
REPO/org/scala-lang/scala-swing_2.9.2/1.0.1-SNAPSHOT-java7/scala-swing_2.9.2-1.0.1-SNAPSHOT-java7.java-source
```

instead of

```
REPO/org/scala-lang/scala-swing_2.9.2/1.0.1-SNAPSHOT-java7/scala-swing_2.9.2-1.0.1-SNAPSHOT-java7.jar
```

so what is going on?

**Comment by eed3si9n** [comment]
Hi Sam, sbt project uses Github issues as a public todo list. If you want help on sbt, please open a question on Stackoverflow. See https://github.com/sbt/sbt/blob/0.13/CONTRIBUTING.md

**Comment by fommil** [comment]
@eed3si9n this is a bug, I'm not looking for support.

sbt is not correctly identifying this `ModuleID` as a jar dependency. Workaround is to explicitly use `jar()` after the declaration.

**Comment by eed3si9n** [comment]
Suspect is Ivy.scala's [`mergeDuplicateDefinitions`](https://github.com/sbt/sbt/blob/fc504d87d73856526374a0f1b9d8768e45bf81d9/ivy/src/main/scala/sbt/Ivy.scala#L728-L756) that was added in sbt/sbt@74c07c64a78447274be47804a6f5f5019c571dab, which lists #468 and #285.

**Comment by fommil** [comment]
just looking through old bugs, I don't really care about this one anymore.
