### ISSUE TITLE
increment-version should be intransitive

### ISSUE THREAD

**Issue by lambdaknight** [sbt/sbt#15]
If I run the "increment-version" action, like any good ol' Task, it acts on the projects dependencies and then on the project itself.  Unfortunately, that is odd behaviour for "increment-version".  Could you make it intransitive?

Actually, in general, would it be possible to make a task intransitive?

**Comment by harrah** [comment]
1) increment-version has been dropped in 0.9.
2) Aggregation of tasks can be controlled in 0.9.  See for example https://github.com/harrah/xsbt/wiki/Full-Configuration
