### ISSUE TITLE
Add plugins via a command

### ISSUE THREAD

**Issue by jsuereth** [sbt/sbt#1502]
It would be ideal, in many scenarios, to be able to add a plugin to the build via a command.

E.g. automated tooling sometimes has customization hooks that need to be added to a build.  Currently, these can use the `apply -cp <classpath> <command class>` mechanism to modify a build and add their hooks, but this leads to some less-than-ideal issues, e.g. classpath detection and cross-publishing.

Ideally, tools/users should be able to experiment with a plugin via a command like:

```
> apply-plugin "com.typesafe.sbt" % "sbt-pgp" % "1.5"
```

and have this automatically reload the build with the plugin enabled.

reference: http://stackoverflow.com/questions/25137042/how-do-i-add-a-sbt-plugin-in-to-an-sbt-session-ie-without-saving?noredirect=1#comment39130312_25137042

**Comment by dwijnand** [comment]
How viable is this in nowadays sbt (AutoPlugins, sbt-server etc)? I'd very much like this but I wanted to looking for insight on it beforehand. Thanks.

**Comment by jastice** [comment]
I am very interested in improving sbt integration with the IntelliJ Scala plugin for sbt v1.0. Being able to add an sbt plugin on boot or by command would make it somewhat easier. I have a vague idea how plugins are loaded, but some more concrete pointers on how to implement a command for it would be appreciated.

I do have a workaround in mind: create a custom sbt global dir with our own plugin added, and munge the user's stuff into it. Would that cause any weird issues?

**Comment by jastice** [comment]
Note: For our current IDE integration purposes, it would be even sufficient to just be able to add via environment variable additional "global" directories that get loaded into the build.
Loading by command would still be neat for other purposes.

**Comment by jastice** [comment]
any insights on how to accomplish this? for practical purposes #3443 is caused by not having a robust way to inject plugins when starting sbt. I am able to spend some time on this, given a little guidance.

**Comment by dwijnand** [comment]
Here's an old commit of mine when I tried to accomplish this: https://github.com/sbt/sbt/commit/81a4d07b1e1657d3fb5ac23b52c63fb91bf37547

I can't even remember how well that worked or not.

**Comment by jastice** [comment]
Thanks, Dale. That would work even without modifying sbt itself since it's just a sequence of commands, but the `session save` part modifies the user's build, which is something I definitely want to avoid. What I would need is a way to make a plugin sticky for the lifetime of the sbt process, but not have any effects to other instances of sbt started during or after the process runs.

**Comment by eed3si9n** [comment]
@jastice suggested allowing additional global directories. That probably would get things done with least amount of hassle.

**Comment by laughedelic** [comment]
I guess everybody here is already aware of it, but just for the record, the @Duhemm's [load-plugin](https://github.com/scalacenter/load-plugin) project achieves somewhat similar to the original `apply-plugin` proposal and I think it fits exactly @jastice's requirements:

> What I would need is a way to make a plugin sticky for the lifetime of the sbt process, but not have any effects to other instances of sbt started during or after the process runs.

**Comment by jastice** [comment]
No I didn't know @laughedelic ! I will try this out.

**Comment by eed3si9n** [comment]
I haven't tried load-plugin, but if the main use case is for IDE support and Language Server injection, wouldn't it be faster if the program launching sbt can specify the plugin(s) from the beginning?

Suppose we had:

`sbt -Dsbt.vendorglobal.base=/something/IDE/sbt1/`

IDE or editor plugins could just invoke that, and guarantee that the plugin gets loaded by the time sbt session is up and running.

**Comment by laughedelic** [comment]
> if the main use case is for IDE support and Language Server injection, wouldn't it be faster if the program launching sbt can specify the plugin(s) from the beginning?

No, if there is already running sbt server in the project, an IDE/LS wants to connect to it (not launch a new sbt instance which is very slow), load its plugin if needed and run necessary setup commands.

**Comment by dwijnand** [comment]
Additionally it needless introduces the complexity of multiple global directories.

**Comment by jastice** [comment]
@laughedelic Ideally we'd connect to a running server to save startup costs, but modifying the state of an sbt instance that is not managed by the IDE seems like it would cause unexpected behavior for the user. Also, having a server already running is not the usual case. Given this, avoiding additional state reloads for adding plugins would be helpful
