### ISSUE TITLE
Name hashing: Methods with structural types in their signatures are not supported

### ISSUE THREAD

**Issue by gkossakowski** [sbt/sbt#1545]
Let's assume we have the following code structure:

``` scala
// A.scala
object A {
  def x: Int = 3
}

// B.scala
object B {
  def onX(m: { def x: Int } ) = m.x
}

// C.scala
object C {
  def abc = B.onX(A)
}
```

Now, if we change `A.scala` to be

``` scala
// A.scala
object A {
  def x: Byte = 3
}
```

then `C.scala` should get recompiled and error reported that `A` does not longer conform to structural type in `onX` method. However, the name hashing won't trigger recompilation f `C.scala` because only `x` name has been changed in `A.scala` and `x` is nowhere mentioned in `C.scala`.

This a limitation of name hashing algorithm which was designed with nominal types in mind. Fixing this might involve marking as used all names that appear in signatures of methods referred from a given source file.

**Comment by jvican** [comment]
Can we close this in favor of https://github.com/sbt/zinc/pull/239?

**Comment by eed3si9n** [comment]
Yea. And also because the issue has been ported as https://github.com/sbt/zinc/issues/240

**Comment by jvican** [comment]
Oops, in fact I meant that issue link!
