### ISSUE TITLE
Infinite loop when typing !!!!

### ISSUE THREAD

**Issue by mauhiz** [sbt/sbt#1562]
So I had this console where I usually type `!!` (previous command)... then typed `!!` again (that makes 4 of them).. and SBT started an infinite loop of displaying `!!!!`

Crazy !!!! See #1562 for recursion issues.

Also, there was no breaking out of it short of killing the console.

(sbt 0.13.5 on Windows 7 console)

**Comment by dwijnand** [comment]
This isn't 0.13.5 or Windows specific, and by that I mean I can reproduce it with 0.13.8 on Mac (in sbt's build FWIW).

**Comment by kzys** [comment]
Fixed due to #2025? I couldn't reproduce the issue on sbt 0.13.9 @ OS X.

**Comment by dwijnand** [comment]
Looks like it did, thanks @kzys.
