### ISSUE TITLE
SBT does not replace SNAPSHOT with a date when publishing

### ISSUE THREAD

**Issue by pkolaczk** [sbt/sbt#1564]
When I publish SNAPSHOT artifacts locally to .m2 or remote maven repository, SBT publishes them as `<artifact-name>-<version>-SNAPSHOT`. Then maven cannot find them, because it expects a timestamp instead of a SNAPSHOT. They should be published as `<artifact-name>-<version>-<timestamp>`.

SBT 0.13.5.

Any workaround to get the original "maven-like" behavior?

I do have `publishMavenStyle := true`.

**Comment by jsuereth** [comment]
I think this is a limitation in Ivy, what we use for dependency resolution.   As a workaround, I'd try the sbt-aether-deploy plugin.

**Comment by eed3si9n** [comment]
Closing this as won't fix.

**Comment by shijinkui** [comment]
add build time to fix this problem: 
https://www.jfrog.com/confluence/display/RTF/SBT+Repositories
