### ISSUE TITLE
RFE: ignore web caching

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#1567]
As discussed in http://stackoverflow.com/questions/25624218 it is sometimes necessary (e.g. dodgy corporate proxies) to request uncached files when downloading from a repository.

(This is not about the local cache)

**Comment by jsuereth** [comment]
Related, I think we actually need to redo the entire Ivy URL hook mechanism so we have full control over the solution.   I.e. Ivy alters its resolution mechanism if a plugin puts commons-httpclient 3.x on the classpath.

@fommil FYI - @eed3si9n has the beginnings of an ivy rewrite started.   It's not clear how far this will go, or whether Ivy can be salvaged, but if you find other caching concerns, please raise them.

**Comment by fommil** [comment]
I have a workaround for this, so it is no longer an issue

Put this in ~/.sbt/0.13/proxy.sbt (insert proxy address in place of localhost):

```
val WorkaroundShittyProxy = {
  new java.net.URL("http://127.0.0.1/").openConnection().setDefaultUseCaches(false)
}
```
