### ISSUE TITLE
improve logging when incompatible Java classes are encountered

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#1571]
SBT doesn't output any meaningful error message when there is a java version incompatibility. It would be useful if it output the offending source/classfile.

What follows is my original report and serves as an example of how confusing the current logging is, and the steps one may sensibly take whilst getting nowhere. The problem turned out to be due to the inclusion of Lucene, which is compiled for Java 7+.

Attempting to `sbt compile` a branch of my project [ENSIME](https://github.com/fommil/ensime-server/tree/lucene_refactor) (experiment if you're interested) under Java 6 is giving a bizarre compiler warning:

```
    [info] Compiling 48 Scala sources to /home/fommil/Projects/ensime-server/target/scala-2.11/classes...
    [error] Class java.lang.invoke.MethodHandle not found - continuing with a stub.
    [error] two errors found
    [error] (compile:compile) Compilation failed
    [error] Total time: 18 s, completed 03-Sep-2014 22:57:44
```

It works under Java 7.

Calling `last` reveals nothing more than the classpath of the compile (this would be equivalent to setting `--debug` level).

I've removed all the plugins from the project, and the problem still shows.

If I remove all my code - leaving just the build system and dependencies - with some stub scala entry points then there is no problem.

However, I can't exactly bisect my source code file because then it doesn't compile.

When the code is compiled, a grep (including binaries) of MethodHandle doesn't give any hits (although there is a jdk8 file in the tests resources, it is not relevant because the problem appears if it is removed).

It is only one (big) patch that has caused the problem (the previous commit compiles ok).
1. **How can I debug this further in sbt?** it doesn't want to give any more info
2. is this a known problem, or can anyone make an informed guess what is going on?

This has been asked as a question at http://stackoverflow.com/questions/25654496 but it's looking likely to be a bug in `sbt`.

**Comment by jsuereth** [comment]
What does raw Scalac report for the same error?   Are we somehow hiding a more useful error message?

If not, we'll need to create our own error-handling hook.  I'd also recommend opening a feature request against Scalac if you find the underlying error message is the same sbt displays.
