### ISSUE TITLE
Add setting for unmanaged sources

### ISSUE THREAD

**Issue by Alefas** [sbt/sbt#1576]
It would be really valuable for IDE. We have unmanagedJars, but we can't connect any sources to them. In our case we need sources of IntelliJ IDEA, and it's quite important to have them.

**Comment by jsuereth** [comment]
@Alefas would you mind giving us a sample of how your unmanaged source jars are laid out?  I'd like to work out a user-story for this.

**Comment by Alefas** [comment]
Our unmanaged sources is very big sources.zip file (110 Mb) with lots of source roots. These source roots are placed in some complex tree structure, some of them starts from folder with name "src" or "tests", some is not. I want to have possibility to put to this setting paths like 'sources.zip!/CSS/css-api/'.
We will scan new sources.zip file to find all source roots by parsing java files (and looking for package statement).

**Comment by dwijnand** [comment]
I assume that this feature request has long since been worked around and is no longer necessary, so I'll close it. Please re-open it if I'm mistaken.
