### ISSUE TITLE
Code cache is filling up in travis builds

### ISSUE THREAD

**Issue by copumpkin** [sbt/sbt#1580]
Probably makes them slower than they need to be. Check the logs in https://travis-ci.org/sbt/sbt/builds/34608220 829.15 and 829.17 for lots of spam about the code cache being full and the compiler being turned off.

**Comment by jsuereth** [comment]
Feel free to bump: https://github.com/sbt/sbt/blob/0.13/.travis.yml.

**Comment by eed3si9n** [comment]
Here'a document on how to bump it up - http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
