### ISSUE TITLE
Fix #485 to respect actual Maven repo location

### ISSUE THREAD

**Issue by briantopping** [sbt/sbt#1589]
https://github.com/sbt/sbt/commit/2f13b7a8c726b51f5765830a5ee810c9906760bd creates the "publish-m2" command, but if the repo is not at the default location, everything breaks and there's no configuration to change it.

I put a note on the offending line in that commit.

**Comment by jsuereth** [comment]
@topping You're very correct.  PR welcome if you have a chance.

**Comment by briantopping** [comment]
Thanks Josh, getting this in could solve a lot of problems locally. Will report back.

**Comment by briantopping** [comment]
Resolving this issue with PR merged to master.
