### ISSUE TITLE
A mechanism for influencing order of AutoPlugins *settings additions

### ISSUE THREAD

**Issue by copumpkin** [sbt/sbt#1594]
I have some keys in my `AutoPlugin` that I want to provide default values for. In `projectSettings` in my plugin, I use `myKey := Seq(someDefaultValue)`, and in the `build.sbt` that uses my plugin, I write `myKey += anotherValue`. Unfortunately, the `projectSettings` seem to get added afterward, so my build fails complaining that `myKey` has no value.

Alternately, I just need a mechanism for defining the "default value" of a key.

**Comment by jsuereth** [comment]
Technically there is a mechanism (`autoSetttings`) except, autoPlugins come _before_ `build.sbt/build.scala` by default.    I'd have to see your build to know, but you probably have an alternative issue here somewhere.

**Comment by copumpkin** [comment]
Dammit, now I have to cook up a small repro :smile:

**Comment by jsuereth** [comment]
K., I marked this as "invalid" for now (autoSettings is this mechanism) but "NeedInfo" for the repro, as I think you're just running into a wierd issue.

**Comment by dwijnand** [comment]
Please open a new, more specific issue if you ever reproduce this one day. :)
