### ISSUE TITLE
A mechanism for auto-importing multiple names

### ISSUE THREAD

**Issue by copumpkin** [sbt/sbt#1597]
My situation: I have an object `ObjectWithSomeTypes` with some types in it that I want to be visible to my build. I also have some sbt-specific keys that I want to be visible in my build.

In my `AutoPlugin`, I can define an `autoImport` object or value, but Scala doesn't have a notion of re-exporting symbols from a module, so I can't say

``` scala
object autoImport {
  export ObjectWithSomeTypes._

  val key1 = settingKey[Foo]("key1")
  val key2 = taskKey[Bar]("key2")
}
```

So the only options I can see are:
- Reshuffle my types so that they end up in a place more amenable to the current `autoImport` mechanism. This violates the clean separation of concerns that I have right now.
- Junk up my `autoImport` object with a big chain of boilerplate like `type MyType = ObjectWithSomeTypes.MyType` and similarly for all the case class constructors. For the latter, I can write `val MyCaseClass = ObjectWithSomeTypes.MyType.apply _` but if the type is polymorphic or there are optional arguments, I lose that.

**Comment by jsuereth** [comment]
You have one additonal option:  Expose "ObjectWIthSomeTypes".

I agree this is an issue, but more of one relating to scala, as you suggest.   The idea behind autoImport is allow plugins to provide a nice "base syntax", with full Scala as a "fallback", but that your "90% use-case" API is exposed/documented right there.

I think it's an open question (and a good one for sbt-dev) to discuss how/whether to allows multiple autoImport values...

@eed3si9n any opinions?

**Comment by eed3si9n** [comment]
I don't think we can solve this in sbt.
See maybe https://contributors.scala-lang.org/t/pre-sip-export-dual-of-import/1758
