### ISSUE TITLE
[error] impossible to get artifacts when data has not been loaded

### ISSUE THREAD

**Issue by hsn10** [sbt/sbt#1598]
during compiling apache spark 1.1.0 sources available at http://spark.apache.org/downloads.html  with command line:
./sbt/sbt -Dhadoop.version=2.4.1 -Pyarn -mem 1024 assembly

i got error:

[info] Resolving org.eclipse.jetty.orbit#javax.transaction;1.1.1.v201105210645 .[info] Resolving org.eclipse.jetty.orbit#javax.mail.glassfish;1.4.1.v20100508202[info] Resolving org.eclipse.jetty.orbit#javax.activation;1.1.0.v201105071233 ..[info] Resolving org.spark-project.akka#akka-remote_2.10;2.2.3-shaded-protobuf .[info] Resolving org.spark-project.akka#akka-actor_2.10;2.2.3-shaded-protobuf ..[info] Resolving org.spark-project.akka#akka-slf4j_2.10;2.2.3-shaded-protobuf ..[info] Resolving org.spark-project.akka#akka-zeromq_2.10;2.2.3-shaded-protobuf .[info] Resolving org.spark-project.akka#akka-testkit_2.10;2.2.3-shaded-protobuf [info] Resolving org.fusesource.jansi#jansi;1.4 ...
[error] impossible to get artifacts when data has not been loaded. IvyNode = org.slf4j#slf4j-api;1.6.1

this error is similar to https://issues.apache.org/jira/browse/IVY-1399 which can be solved by upgrading ivy included in sbt to 2.4.0

**Comment by jsuereth** [comment]
@hsn10 Ivy 2.4.0-RC1 (when we were on it temporarily for last release) was riddled with issues around maven resolution.   We can give it a go in 0.13.7, but I'm a bit nervous about that.

Thanks for linking the Ivy issue though. I'm sure we can find a way to fix this.

**Comment by hsn10** [comment]
apache ivy 2.4.0-rc1 do not have fix for this problem. trunk ivy does. commit fixing bug is https://github.com/apache/ant-ivy/commit/c66b23747627a2b432e0068561d457cab9f97ead

**Comment by jsuereth** [comment]
@hsn10 I'm trying to backport that fix into ivy 2.3.0.  It looks like it should be feasible. If I'm successful, we'll include it in 0.13.7.

**Comment by jsuereth** [comment]
Ok, attempting backport: https://github.com/sbt/ivy/pull/12

We'll see if it passes the full test suite.  Sometimes these things open up other bugs.

**Comment by mavarazy** [comment]
I switched to 0.13.7, but this still happens to me with https://github.com/inoio/solrs dependency.
What do I need to do?
