### ISSUE TITLE
update-classifiers should update sources for snapshots as well

### ISSUE THREAD

**Issue by yang** [sbt/sbt#160]
Sometimes (I'm not sure when) sbt will update to the latest class jar for some snapshot dependency. After running `update-classifiers`, however, the source jar for the snapshot release is not downloaded.

**Comment by hseeberger** [comment]
I know this could be hard, but it would be good to have a reproducible test case. Maybe you could set up a local repo to deploy snapshots there in order to show the issue?

**Comment by yang** [comment]
I don't know how to set up a repository - I remember looking into this a while back and being pretty bewildered. Maybe I'll eventually have another look, but at the moment this is a low-priority issue (for me), since the workaround is easy - just remove the sources.

**Comment by harrah** [comment]
Need a reproducible test case.
