### ISSUE TITLE
Natural whitespace handling for SBT configuration parser AKA 'no more blankies'

### ISSUE THREAD

**Issue by ajozwik** [sbt/sbt#1606]
Open list to implement/check:
- [x] Add tests around the new no-blank-lines files and session-save
- [ ] Possibly expand the notion of "position" we have in Setting[_] to include start/stop so we can more accurately alter a build.sbt file without changing it.
- [x] Investigate @dragos [comments about tokenizer/parser](https://github.com/sbt/sbt/pull/1574#discussion-diff-17551216).
- [ ] Current SBT parser cuts line by line. If we have:

``` scala
val a = <a/><b/>

val r = 4
```

SBT parser split it to: `val a = <a/><b/>` and `val r = 4`. Scala parser will compile one by one separate.

``` scala
scala> val a = <a/><b/>
a: scala.xml.NodeBuffer = ArrayBuffer(<a/>, <b/>)
```

But this code will not compile.

``` scala
scala> :pa
// Entering paste mode (ctrl-D to finish)

val a = <a/><b/>

val r = 4

// Exiting paste mode, now interpreting.

<console>:3: error: ';' expected but 'val' found.
val r = 4
^
```

For backward compatibility we have to find, where is xml code - and at least add ; to the end (now I will add brackets ()). The code to add bracket can be rewritten.
- [x] Write acceptance tests.
- [x] I think for all sbt part - how to split code to atomic parts - it is easier to test. 
  In #noblankies we extracted `EvaluateConfigurations.splitExpressions` and  `SessionSettingsNoBlankies.oldLinesToNew` for `session save`. Both methods can be tested by unit tests - without running whole sbt.
- [x] Scala parser should be corrected. See [Scala parser cuts last bracket](http://stackoverflow.com/q/25547149/651140)

**Comment by jsuereth** [comment]
@ajozwik Let me know if you have time for a skype sometime this week to discuss the TODOs on here and what each of us can to do make sure this gets merged soon.  I'd like to have a 0.13.7-M3 for this as soon as we can to flush out more issues.

**Comment by ajozwik** [comment]
@jsuereth
Point 4 and 7 are related to scala parser. They are out of scope. We have work - around.
Only point 2: `Possibly expand the notion of "position" we have in Setting[_] to include start/stop so we can more accurately alter a build.sbt file without changing it` is still open.

**Comment by eed3si9n** [comment]
For easier code review, I rebased wip/no-blankies on top of 0.13, and made no-blankies-rebased.
https://github.com/sbt/sbt/compare/wip/no-blankies-rebased

The only thing that stands out to me is `.gitignore`, which should be handled using https://help.github.com/articles/ignoring-files/#create-a-global-gitignore.
