### ISSUE TITLE
publish sbt's source to maven center

### ISSUE THREAD

**Issue by He-Pin** [sbt/sbt#1612]
Could you please publish sbt's source code to maven center?

**Comment by jsuereth** [comment]
This ask is a bit more intense than you realize.

a. we may be pubishing more pieces of sbt to maven in the future.  We can certainly do so then
b. the repackaing project is the one not pushing source: https://github.com/typesafehub/sbt-republish

In any case, which sources are currently missing?

**Comment by He-Pin** [comment]
re:
1,thanks for that info,cause currently ,the document lack some use pattern ,and some time user may need to read the source code to realize how to use it,and how sbt works.just as akka.and Play now is publish to maven center too.
2,for the source maybe not missing,but I could not locate where to find it correctly,I am using IDEA with scala plugin,and when It ask me to setup the source code ,I provide it the git clone ,but it's hard to locate the right one.

thanks

**Comment by fernandoracca** [comment]
+1. Source code available to navigate in Intellij is a plus. Is this to be fixed in sbt-idea as well or will it just work ?

**Comment by dwijnand** [comment]
IntelliJ now has a "import sbt sources" or similar option on import, so at least that angle seems to work ok.

Do we still want to keep this open?

**Comment by He-Pin** [comment]
@dwijnand yes,I think it should be fine to close it.the latest IDEA's scala plugin works fine.

**Comment by He-Pin** [comment]
reopen this ,sorry ,let @jsuereth make the work :).

**Comment by dwijnand** [comment]
This will be the case in 1.0.0. (See as an example 1.0.0-M4: http://repo1.maven.org/maven2/org/scala-sbt/sbt/1.0.0-M4/)
