### ISSUE TITLE
Maven local resolver with parent POM

### ISSUE THREAD

**Issue by charlessimpson** [sbt/sbt#1616]
Somewhere between 0.13.5 and 0.13.6, the Maven local resolver stopped being able to resolve parent POM's from Maven projects.

If I have a parent pom:

``` xml
<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>example-parent</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

</project>
```

a child pom:

``` xml
<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.example</groupId>
        <artifactId>example-parent</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <groupId>com.example</groupId>
    <artifactId>example-child</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

</project>
```

both of which are installed to my local M2 repo using `mvn install`. The following build.sbt works in 0.13.5:

```
name := "example-sbt"

version := "1.0-SNAPSHOT"

libraryDependencies += "com.example" % "example-child" % "1.0-SNAPSHOT"

resolvers += Resolver.mavenLocal
```

but fails in 0.13.6 with the error:

```
<snip>

[info] Updating {file:/Users/csimpson/Desktop/sbt-mvn-parent/sbt/}sbt...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.example#example-child;1.0-SNAPSHOT:  Maven2 Local: no ivy file nor artifact found for com.example#example-parent;1.0-SNAPSHOT
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]      com.example:example-child:1.0-SNAPSHOT (/Users/csimpson/Desktop/sbt-mvn-parent/sbt/build.sbt#L5-6)
[warn]        +- example-sbt:example-sbt_2.10:1.0-SNAPSHOT
sbt.ResolveException: unresolved dependency: com.example#example-child;1.0-SNAPSHOT:    Maven2 Local: no ivy file nor artifact found for com.example#example-parent;1.0-SNAPSHOT

<snip>
```

It might be an issue with Ivy caching, since if I run SBT 0.13.5 first, then 0.13.6 will succeed, but if I delete `~/.ivy2/cache/com.example`, then 0.13.6 fails to resolve again. I've verified that Maven is able to resolve the parent POM when depending on the child and that SBT is able to resolve Maven artifacts that don't have a parent POM.

**Comment by jsuereth** [comment]
Hey @charlessimpson, been a long time!  I'll look into this, but first jsut wanted to say 'hi'. I see you've left APL, ping me sometime, would love to catch up.

**Comment by jsuereth** [comment]
Think this may be related to the ChainResolver fixes we added in 0.13.6 to fix correctness/freshness issues with Maven -SNAPSHOTs.

**Comment by manuelbernhardt** [comment]
I'm not entirely sure if this is related, but it certainly seems similar enough: using a local repository, an artifact can't seem to resolve a dependent SNAPSHOT library (tested with 0.13.7-M2, 0.13.6 vs. 0.13.5).

In our case we are working with a plugin (and not a direct library dependency). Adding that dependency to the local repository does not help.

If it helps, here are the steps to reproduce the exact case I'm struggling with:
- checkout https://github.com/manuelbernhardt/xsbt-cucumber-plugin/tree/scala-update (make sure it's the `scala-update` branch) and run `sbt publish-local`
- on an empty sbt project
  - add the local ivy repo to the plugin resolvers
  - add the plugin depdendency `addSbtPlugin("templemore" % "sbt-cucumber-plugin" % "0.9.0-SNAPSHOT")`
- watch it fail to resolve `info.cukes#cucumber-scala_2.11;1.2.0-SNAPSHOT`

**Comment by manuelbernhardt** [comment]
I created a test project that demonstrates the problem at https://github.com/manuelbernhardt/sbt-1616

It would be awesome to have this fixed before 0.13.7 gets released!

**Comment by dispalt** [comment]
This is effecting me as well, +1 to fixing it.

**Comment by charlessimpson** [comment]
@jsuereth Good to hear from you! Glad to see this bug landed in capable hands.

I left APL a couple of years ago and am now working for a small company. Let me know if there's any other information that could help you with this bug.

**Comment by PatrickSauts** [comment]
+1

**Comment by mackler** [comment]
+1

**Comment by ebolinger** [comment]
+1

**Comment by dplate** [comment]
I can confirm there is a problem with parent poms and 0.13.6. For me it even not works with a remote repository (Nexus):
internal.snapshot-repo: no ivy file nor artifact found
With 0.13.5 it works.

**Comment by kahliburke** [comment]
+1 

Ran into this issue today with a remote repo

**Comment by nitay** [comment]
I've been having this issue as well. Anyone have a workaround in the meantime while this gets fixed?

**Comment by PatrickSauts** [comment]
go back to 0.13.5

**Comment by SrividyaKasu** [comment]
+1

**Comment by jsuereth** [comment]
@charlessimpson I'm actually unable to reproduce this with sbt 0.13.7.  I can push my test case if you'd like, but I'm curious if there's anything else on yur machine that may be leading to the failure that I need to look into.    Which version of Maven are you using to push locally (I'm using Maven 3.0.3)

@manuelbernhardt What I'm seeing locally on your test case is a scala 2.11 vs. scala 2.10 issue.  I'm actually unable to duplicate as-is in your repo, could you provide some better instructions.
