### ISSUE TITLE
`optional` config for library dependency maps to incorrect scope

### ISSUE THREAD

**Issue by indrajitr** [sbt/sbt#162]
`"optional"` config for library dependency is just a flag and shouldn't really map to a scope.

For example, having the following as library dependency:

``` scala
libraryDependencies ++= "com.h2database" % "h2" % "1.2.147" % "optional"
```

results in the relevant dependency section as thus:

``` xml
<dependency>
  <groupId>com.h2database</groupId>
  <artifactId>h2</artifactId>
  <version>1.2.147</version>
  <scope>optional</scope>
  <optional>true</optional>
</dependency>
```

Per [Maven's POM Reference](http://maven.apache.org/pom.html#Dependencies), the scope is not a valid one. In this particular case, it should have been `<scope>compile</scope>` (the default).

This also means that the following _rare and edge_ case is actually valid:

``` xml
<dependency>
  <groupId>com.h2database</groupId>
  <artifactId>h2</artifactId>
  <version>1.2.147</version>
  <scope>runtime</scope>
  <optional>true</optional>
</dependency>
```

But there isn't a way to add such a dependency because `"runtime"` and `"optional"` are both treated as Configuration, and multiple Configurations are not allowed.

**Comment by harrah** [comment]
In Ivy, there is no concept of optional, so it has to be handled with a configuration.  I've cleaned up the handling a bit.  The test case included in the commit is probably the easiest way to see the behavior now.

**Comment by indrajitr** [comment]
Thanks much!
