### ISSUE TITLE
SBT should support define external Project and could add the external at the dependencies

### ISSUE THREAD

**Issue by He-Pin** [sbt/sbt#1623]
currently ,I have a project ,which used some source from other two projects,and the external projects are not managed by maven,or sbt,and not packaged with jar,So I choose the way to add the source in the 
`unmanagedSourceDirectories in Compile`,this compiles well from the console ,but not in the IDE,IDEA just said that cannot mapping this into IDEA's project model,and the reference of the code will not resolve symbols,.SO i start to defined a project for these external projects.

And I want to keep the project structure cleaner,so I put them out ,here I defined the`Build.scala` as

```
lazy val gameMasterServer = ProjectRef(file("../GMServer","gameMasterServer"))

lazy val gameServer = Project(".","gameServer").dependsOn(gameMaster)
```

now the SBT starting complain:

```
GMServer is not contained in build root ,then both the IDEA and sbt cannot work.
```

To fix this,I have only two option:
1,put the GMServer in the build root of `gameServer`,then the project structure goes not that clean
2,import that GMServer as module ,add then add as the module dependencies,at the same time write code like 

```
      unmanagedSourceDirectories in Compile += baseDirectory.value.getParentFile.getParentFile.getParentFile / "GMServer/src/com/gm/webservice",
```

the tree like this:

```
server$ tree -d -L 1
.
├── GMServer
├── LittleJianghu-Server
├── StatServer
```

and the LittleJianghu server look like this

```
LittleJianghu-Server$ tree -L 2
.
├── app
│   ├── base
│   ├── camel
│   ├── db
│   ├── io
│   ├── king
│   ├── monster
│   ├── overload
│   ├── resourceManager
│   ├── sharding
│   ├── statServer
│   └── xxjh
├── framework
│   ├── akka-utils
│   ├── json
│   ├── protobuf
│   ├── serializers
│   ├── server
│   └── ws
├── project
│   ├── build.properties
│   ├── Build.scala
│   ├── plugins.sbt
│   ├── project
│   └── target
├── README
├── src
│   └── main
└── target
    └── streams
```

So any ideas?
Just as what I said ,I think SBT should support some thing just like the module dependency.

**Comment by jsuereth** [comment]
Yeah, this i an issue with the conflagration of IDE-integration, sbt-terminal, and how we deal with external builds.   While I hope we have a fix eventually, it's a bit hairy, so I'm only expecting thing sto get better (not be nice) by sbt 1.0.

**Comment by He-Pin** [comment]
thanks for that information,sbt will be better and better :P

**Comment by akauppi** [comment]
@hepin1989 I believe this is implemented, and this Issue could be closed.

Please check [this answer](http://stackoverflow.com/questions/11653435/how-to-reference-external-sbt-project-from-another-sbt-project#answer-15229301) at StackOverflow. Is there something missing, which would warrant keeping this issue still open?

**Comment by eed3si9n** [comment]
Closing this.
