### ISSUE TITLE
ClassNotFoundException when unserializing object from file

### ISSUE THREAD

**Issue by emchristiansen** [sbt/sbt#163]
Code that works when run outside SBT (with Eclipse) generates a ClassNotFoundException when run with "sbt run" using 0.1. See this StackOverflow question: http://stackoverflow.com/questions/7236015/scala-sbt-possible-bug

**Comment by opyate** [comment]
Does the solution proposed in https://github.com/harrah/xsbt/issues/89 work?

**Comment by harrah** [comment]
Yes, that is the same issue.  It is the usual ObjectInputStream issue in the presence of class loaders solved either by forking or subclassing, like in:

https://github.com/scala/scala/blob/master/src/actors/scala/actors/remote/JavaSerializer.scala#L20

**Comment by emchristiansen** [comment]
@opyate Yes, adding "fork in run := true" to build.sbt fixes the problem. Maybe run should be forked by default?

**Comment by harrah** [comment]
This is not the place for such a discussion, which would require a substantial consensus.  Please use the mailing list.

**Comment by SethTisue** [comment]
here's a Scala version of the subclassing workaround: https://github.com/NetLogo/NetLogo/blob/master/src/main/org/nlogo/util/ClassLoaderObjectInputStream.scala

everyone should be clear this is not an sbt issue per se. people doing classloader stuff were hitting this issue years before sbt was even a twinkle in Mark's eye.
