### ISSUE TITLE
EvictionOptions not allowing to turn off warnings?

### ISSUE THREAD

**Issue by manuelbernhardt** [sbt/sbt#1636]
I'm trying to turn off eviction warnings for intransitive dependencies at the moment since I have little or no influence on the dependencies (using Play).

I'm now using the following settings:

```
evictionWarningOptions := EvictionWarningOptions.default.withWarnTransitiveEvictions(false).withWarnDirectEvictions(false).withWarnScalaVersionEviction(false),
ivyScala := ivyScala.value map { _.copy(overrideScalaVersion = true) }
```

but still get to see eviction warnings upon update etc.

Any idea what I might be doing wrong? This is a multi-module project and I have the settings enabled for each module.

**Comment by eed3si9n** [comment]
Could you try:

```
evictionWarningOptions in update := EvictionWarningOptions.default.withWarnTransitiveEvictions(false).withWarnDirectEvictions(false).withWarnScalaVersionEviction(false)
```

**Comment by manuelbernhardt** [comment]
@eed3si9n thanks, that was it. Indeed worth adding to the documentation, I'll take a look.

**Comment by manuelbernhardt** [comment]
From what I can see, the eviction topic is not documented yet. Would a good place be a new sub-topic of http://www.scala-sbt.org/0.13/docs/Dependency-Management-Index.html, e.g. `viii. Eviction warnings`? I could try to have a shot at it.

**Comment by metasim** [comment]
I might suggest having the warning message point to that documentation since the setting recommended in the message isn't sufficient, at least in a multi-module context.

**Comment by eed3si9n** [comment]
Another thing we should add is `EvictionWarningOptions.empty`.

**Comment by eed3si9n** [comment]
At least there's a documentation that mentions Eviction Warning now - http://www.scala-sbt.org/0.13/docs/Library-Management.html#Eviction+warning

**Comment by metasim** [comment]
Do you think the documentation maintainers would consider adding the example settings from above to the documentation? In my case, the warning seemed to be about some internal SBT dependency:

```
Scala version was updated by one of library dependencies:
       [warn]   * org.scala-lang:scala-library:(2.11.1, 2.11.0) -> 2.11.2
       [warn] To force scalaVersion, add the following:
       [warn]   ivyScala := ivyScala.value map { _.copy(overrideScalaVersion = true) }
       [warn] Run 'evicted' to see detailed eviction warnings
```

(this is even though my `scalaVersion` is set to `2.11.4` in all my modules). I don't think I would have been able figure out how to quiet it without the `evectionWarningOptions` example you provided!

**Comment by eed3si9n** [comment]
@metasim We don't have documentation maintainers. It's mostly me and @jsuereth doing everything, so if you want improvements on the docs, the best way to do it is to write it and send pull requests to [sbt/website](https://github.com/sbt/website).
However, if you're getting eviction warning `(2.11.1, 2.11.0) -> 2.11.2` even when you're setting `2.11.4`, that should be reported as a bug.

**Comment by metasim** [comment]
I'll attempt to create an independent test case and bug report in the next few weeks. Right now it's in the midst of a multi-faceted project structure that's not automatically reducible.

**Comment by eed3si9n** [comment]
#1615 added `EvictionWarningOptions.empty` that's available on 0.13.8.

**Comment by davidhoyt** [comment]
Working on a play 2.3.9 project with SBT v0.13.8, set `scalaVersion := "2.11.6"` as well as `evictionWarningOptions in update := EvictionWarningOptions.empty` and am seeing lots of eviction-related info. when I expicitly run `sbt evicted`. It's not a warning which may satisfy the requirements, but especially w/ the scala libs, it pollutes potential real problems.

**Comment by davidhoyt** [comment]
For those interested, this cleared up scala-lang spew for me when running `sbt evicted`: `evictionWarningOptions in evicted := EvictionWarningOptions.default.withWarnScalaVersionEviction(false)`

**Comment by adamw** [comment]
@eed3si9n suggestion to add `evictionWarningOptions in update := EvictionWarningOptions.default.withWarnTransitiveEvictions(false)` helped a lot after upgrading to 1.0 and getting loads of transitive eviction warnings - thanks :)

**Comment by SethTisue** [comment]
I'm on sbt 1.3.12 and my build.sbt is:

```scala
libraryDependencies += "org.dispatchhttp" %% "dispatch-core" % "1.2.0"
update / evictionWarningOptions :=
  EvictionWarningOptions.default
    .withWarnTransitiveEvictions(false)
    .withWarnDirectEvictions(false)
    .withWarnScalaVersionEviction(false)
```

but I still get eviction warnings:

```scala
sbt:root-20200603> update
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[success] Total time: 0 s, completed Jun 3, 2020 11:25:52 AM
sbt:root-20200603> evicted
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 	* io.netty:netty-handler:4.1.42.Final is selected over 4.1.34.Final
[warn] 	    +- org.asynchttpclient:async-http-client:2.10.4       (depends on 4.1.42.Final)
[warn] 	    +- io.netty:netty-codec-http:4.1.42.Final             (depends on 4.1.42.Final)
[warn] 	    +- com.typesafe.netty:netty-reactive-streams:2.0.3    (depends on 4.1.34.Final)
```

my other attempt to make the warning go away had no effect, either:

```scala
dependencyOverrides += "io.netty" % "netty-handler" % "4.1.42.Final"
```

**Comment by agilesteel** [comment]
Same here. Sbt 1.3.13 and none of these do what they should:
```scala
Global    / update / evictionWarningOptions := EvictionWarningOptions.empty
ThisBuild / update / evictionWarningOptions := EvictionWarningOptions.empty
            update / evictionWarningOptions := EvictionWarningOptions.empty
```
I still see:
```sh
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
```

**Comment by eed3si9n** [comment]
Eviction warning will be removed in sbt 1.5.0 - https://github.com/sbt/sbt/pull/6221

**Comment by AnirudhVyas** [comment]
Hello @eed3si9n -  for those who cannot upgrade to higher version as they arrive immediately, is there a workaround? I have tried setting EvictionWarningOptions.empty as above but still get :
```scala
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
```
