### ISSUE TITLE
Can SBT resolve .pom file dependencies that just contain configurations/properties?

### ISSUE THREAD

**Issue by hfguedes** [sbt/sbt#1641]
So, as the title suggests, can sbtresolve .pom files dependencies that contain only configurations/properties and have no .jar file associated?

Im currently developing a new frontend app using Play! Framework and angularjs. Here's the scenario:

**Root Project** _(à la maven compilation/deploy)_

<ul>
 <li><strong>Core business Module</strong>(maven)<i>pom.xml</i></li>
 <li><strong>Web modules</strong></li>
           <ul>
               <li><strong>Rest API</strong> - <i>pom.xml</i></li>
                   <ul>
                        <li><i>Module - pom.xml</i></li>
                        <li><i>Module - pom.xml</i></li>
                   </ul>
               <li><strong>Frontend</strong> <i>(à la SBT compilation, multi-module project)</i></li> 
                   <ul>
                      <li><i>Mod1 - build.sbt</i></li>
                      <li><i>Mod2 - build.sbt (depends on mod1)</i></li>
                           <ul>
                                <li><i>More modules inside - build.sbt</i></li>
                           </ul>
                   </ul> 
                   <i>build.sbt</i><br/>
                   <i>project/build.scala</i>
               <li><strong>Web Commons</strong> <i>(used on the Rest API and Frontend) - pom.xml</i></li>
<i>pom.xml</i>
</ul>

<i>pom.xml</i>

The sbt compilation is ran via maven using a plugin, sbt-launcher if im not mistaken. Everything runs and compiles as expected, however, we ran into a problem when we added WebCommons as a dependency in the frontend's build.sbt file project.
The problem relys on the fact that, the root's pom.xml has a parent of his own, lets call it X, and X contains several .pom files that delegate to child modules (in this case the root project) config/properties/dependencies that are necessary to ease RPM packaging. 
Running maven clean install, the compilation process goes perfectly fine, we reach the frontend and the sbt compilation cycle starts as expected. When sbt tries to resolve the web-commons dependency, resolves every parent of the dependency. In this case, web-commons->web-modules->root->X. When he reaches X, finds that there are several dependencies with him (not relevant at all for the frontend...) but these are made of .pom files not jar's. These .pom files are downloaded correctly using resolvers but then, sbt searches for the corresponding .jar files taking an enormous time to finish the build, and when it does, errors, errors everywhere (missing dependencies).
I've tried several possible solutions:
1.        **intransitive()** in web-commons dependency, not effective, still trying to find parents dep.
2.        **exclude(organization,filename*)**, again not effective
3.        **excludeAll( ExclusionRule(org,dep1) ExclusionRule(org,dep2) ... )**, sadly, not effective.

Im currently using sbt 0.13.2/6 (tried both).
My next step was to define an ivy.xml and ivysettings.xml that configures this dependency and force the type=pom. Might this work? Any other sugestion/workaround? 

Thanks in advance.

**Comment by eed3si9n** [comment]
There's a Stackoverflow question [Can SBT resolve only .pom files as dependencies without jars?](http://stackoverflow.com/questions/26187667), which I'm guessing you've opened so I'm closing this one here (I think SO is a better forum for this type of questions). Hopefully someone from our team can take a look at it there.
