### ISSUE TITLE
selectPackageMain should always warn about ambiguous main class

### ISSUE THREAD

**Issue by kretes** [sbt/sbt#1648]
In

https://github.com/sbt/sbt/blob/0.13/main/src/main/scala/sbt/Defaults.scala#L668

sbt guesses main class for a package, but do not warn if there is more than one.

sbt should use some strategy to warn about the fact, like two lines above for selectRunMain

**Comment by jsuereth** [comment]
Agreed.  Pull request to that effect welcome (and possibly not too hard to add).

**Comment by kretes** [comment]
I could try
9 paź 2014 01:54 "Josh Suereth" notifications@github.com napisał(a):

**Comment by eed3si9n** [comment]
Looks like this has been addressed in https://github.com/sbt/sbt/pull/1669 etc.
