### ISSUE TITLE
Cached resolution does not respect excludes

### ISSUE THREAD

**Issue by rossabaker** [sbt/sbt#1649]
In cached resolution, minigraph keys do not consider excluded dependencies.  If one project excludes a transitive dependency, and another does not, it becomes non-deterministic which minigraph will be used under cached resolution.

Minimal repro:
- Clone https://github.com/rossabaker/sbt-cached-resolution-exclusion
- Run `sbt clean test`

Expectation:
- Both specs should pass: two projects should be able to independently prune their transitive dependencies.

Result:
- One will not.  For me it's ExcludeSpec, but I suspect this may be non-deterministic.

Real world motivation:
- hadoop-core brings in old servlet-apis under the `org.mortbay.jetty` organization.  This is not evicted by the Java Servlet API from `javax.servlet`, resulting in two conflicting versions of `javax.servlet` on the classpath.  If the user has compiled another Hadoop project that does not exclude the servlet-api, the cache is polluted for the project that does need to exclude it.

Extra credit:
- Works with `excludeAll`
- Works with `ivyXML`

**Comment by eed3si9n** [comment]
Thanks for the report!

**Comment by eed3si9n** [comment]
#1653 fixes simple `exclude` case. I'll keep this open for `excludeAll`. I don't know if I can get to ivyXML.

**Comment by rossabaker** [comment]
Nice!  I figured the ivyXML would be very difficult.  I'd be happy to add a brief note in the docs about whichever exclude styles are left undone.

Is there something wrong with the nightly build?  The last I see is [September 23](http://repo.typesafe.com/typesafe/ivy-snapshots/org.scala-sbt/sbt-launch/).

**Comment by eed3si9n** [comment]
It seems Jenkins jobs have been failing.

**Comment by OlegYch** [comment]
still fails for me if you add sbt-multijvm into the mix https://github.com/OlegYch/sbt-cached-resolution-exclusion-multijvm
