### ISSUE TITLE
how to determine application mode in build.sbt

### ISSUE THREAD

**Issue by cnrudd** [sbt/sbt#1650]
Hi,

building a site on playframework 2.3.4
just wondering if anyone can tell me how i can determine the application mode (dev, prod) from within the build.sbt file?

Thanks,
Colin

**Comment by eed3si9n** [comment]
Have you tried one of these options first, for Play support? - https://www.playframework.com/get-involved
Let me know if they sent you here.

**Comment by cnrudd** [comment]
no, I had not.  I will give it a try.
Thanks!
Colin
