### ISSUE TITLE
0.13.7-M3  does not resolve part of play2 dependencies

### ISSUE THREAD

**Issue by antonkulaga** [sbt/sbt#1654]
Whenever I change sbt from 0.13.6 to 0.13.7-M3  in my project ( https://github.com/antonkulaga/scala-js-binding ) I get:
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::              FAILED DOWNLOADS            ::
[warn]  :: ^ see resolution messages for details  ^ ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.typesafe.play#play-json_2.11;2.3.0!play-json_2.11.jar(doc)
[warn]  :: com.typesafe.play#play-iteratees_2.11;2.3.0!play-iteratees_2.11.jar(doc)
[warn]  :: com.typesafe.play#play-functional_2.11;2.3.0!play-functional_2.11.jar(doc)
[warn]  :: com.typesafe.play#play-datacommons_2.11;2.3.0!play-datacommons_2.11.jar(doc)

**Comment by jsuereth** [comment]
These are the source + doc jars for play.  Are you forcing these things to be resolved in your dependency specification?

Also, it'd be nice to have  abit more of that failure message.

**Comment by jsuereth** [comment]
Additionally, I'm unable to duplicate:

```
[info] Done updating.
[success] Total time: 52 s, completed Oct 8, 2014 7:48:33 PM

```

**Comment by antonkulaga** [comment]
Strange, I will check again when I will have time for this.

**Comment by eed3si9n** [comment]
Closing this since it's likely no longer relevant.
