### ISSUE TITLE
Update the Using Sonatype documentation to include a more comprehensive build.sbt example

### ISSUE THREAD

**Issue by dlpb** [sbt/sbt#1656]
The page about using sonatype (http://www.scala-sbt.org/0.13/docs/Using-Sonatype.html) is great for getting started with publishing artefacts to maven, but it does not include information about how to set the artefact id, group id etc of the artefact that is produced.

The documentation should include reference to the organisation, name, etc keys with a reference to what they do.

e.g. organisation := com.example, name: test-library ...

**Comment by eed3si9n** [comment]
This was fixed in https://github.com/sbt/website/pull/716/commits/806ba0940e6758e73f9494972b7ae899a174af75
