### ISSUE TITLE
Add the ability for sbt to pull src/doc jars during update

### ISSUE THREAD

**Issue by jsuereth** [sbt/sbt#1657]
Instead of forcing users to use `updateClassifiers`, allow users to configure whether or not ivy will pull src/doc jars during regular update.

**Comment by everpeace** [comment]
I would be happy if sbt could provide some way to pull all sources of transitive dependencies.

**Comment by dwijnand** [comment]
> .. allow users to configure whether or not ivy will pull src/doc jars during regular update

Isn't this fixed by `withSources()`? Closing optimistically...
