### ISSUE TITLE
reflective compilation has failed: '=' expected but eof found in 0.13.7-M3

### ISSUE THREAD

**Issue by jaceklaskowski** [sbt/sbt#1661]
It appears that defining multiple projects in a single line `lazy val a, b = project` is broken in 0.13.7-M3. It works fine in 0.13.6 (and I'm sure worked fine in 0.13.7-M3 today, but just out of the sudden stopped).

The messages are:

```
➜  jacoco4sbt-root-no-sources  xsbt
JAVA_HOME=/Library/Java/JavaVirtualMachines/java8/Contents/Home
SBT_OPTS= -Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled -Dfile.encoding=UTF-8
[info] Loading global plugins from /Users/jacek/.sbt/0.13/plugins
[info] Updating {file:/Users/jacek/.sbt/0.13/plugins/}global-plugins...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Loading project definition from /Users/jacek/sandbox/jacoco4sbt-root-no-sources/project
[info] Updating {file:/Users/jacek/sandbox/jacoco4sbt-root-no-sources/project/}jacoco4sbt-root-no-sources-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[error] [/Users/jacek/sandbox/jacoco4sbt-root-no-sources/build.sbt]:2: reflective compilation has failed:
[error]
[error] '=' expected but eof found.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

When I change `project/build.properties` to `sbt.version=0.13.6` it works fine.

**Comment by jsuereth** [comment]
Thanks for the report.

**Comment by jsuereth** [comment]
Looks to be an issue with range posiitons, i.e.

``` scala
scala> orig.substring(a.pos.start, a.pos.end)
res38: String = val a

scala> orig.substring(b.pos.start, b.pos.end)
res39: String = b = project
```

Going to ping @dragos for some ideas on ways to fix this besides getting the "reparse" hackery to also handle this case.

**Comment by dragos** [comment]
I'd need a bit more context. What is `orig`? How can I reproduce it?

**Comment by jsuereth** [comment]
Ok,s o I think we're going to add an error message which deprecates this kind of syntax, as it opens up a  HUGE can of worms in the architecture of using hte scala parser to chunk strings.  One which we can't realistically tackle.

Instead we'll be issuing an appropriate error message here about how this syntax is not supported.  You _Can_ work around this by using the following:

``` scala
val x = bar

{
  val a,b = project
}
```

Which will appropriately embedd the value into a `Block` AST and that works fine in the current semantics.  HOwever, given how the range positions lay out in the `val a,b = project` feature, it's just not soemthing we can support.

**Comment by jaceklaskowski** [comment]
I'm glad it's nailed down and ultimately fixed, but sad that such a nice feature of sbt to define many projects in a single line got disabled.

**Comment by eed3si9n** [comment]
I personally think the `val a, b = project` makes it hard to understand what's going on, and given `project` would return different objects in this context, it's somewhat evil syntax of Scala.

**Comment by paulp** [comment]
You broke this with no deprecation period from 0.13.6 to 0.13.7. If that's an option, why such gyrations for backward compatibility in other cases? If it isn't, then on what basis was it done?

**Comment by eed3si9n** [comment]
@paulp Our effort in keeping the bincompat across 0.13.x I think is primarily for published plugins.

We do care about builds, and if possible we would've kept source-level backward compatibility of the builds. But I think we couldn't when we switched to using Scala compiler to parse `build.sbt` for whitespace. So the workaround was to fail the build from loading when we detect pattern on lhs.

**Comment by paulp** [comment]
I wonder how many thousands of man-years could have been saved (this is not hyperbole) by having working source positions in the compiler. Oh well, carry on.

**Comment by jsuereth** [comment]
@paulp I'd give my left elbow for working source positions.... but in this case, we did the damage to ourselves.   The reason we can't use the original source position is around refactoring of settings, and the reason we even care about "val x,y = ...." is because we haven't gone hole-hog into owning the parser ourselves, we're still in half-donkey, half-man land.  Sorry for the breakage.  We didn't make the decision lightly and we hope to never have changes like this.   In reality, it's always a balance of "never break things" and "improve things".   Hopefully the improvement outweighs (dramatically) the breakage.   Additionally, you can turn off the new parser to get the old behavior if needed.

**Comment by paulp** [comment]
The ability to omit blank lines would be worth it even if it came with ten new bugs injected into each project.
