### ISSUE TITLE
Getting started example from official tutorial doesn't work

### ISSUE THREAD

**Issue by coryfklein** [sbt/sbt#1675]
The [official tutorial in the docs](http://www.scala-sbt.org/0.13/tutorial/Hello.html) gives this example:

```
$ mkdir hello
$ cd hello
$ echo 'object Hi { def main(args: Array[String]) = println("Hi!") }' > hw.scala
$ sbt
...
> run
...
Hi!
```

However, when I try to do this, this is what I get:

```
$ mkdir hello
$ cd hello
$ echo 'object Hi { def main(args: Array[String]) = println("Hi!") }' > hw.scala
$ sbt
[info] Set current project to hello (in build file:/Users/coryklein/playground/hello/)
[error] export usage:
[error]   export <tasks>+   Executes tasks and displays the equivalent command lines.
[error]
[error] export
[error]
```

Here is my sbt version:

```
$ sbt --version
sbt launcher version 0.13.6
```

**Comment by eed3si9n** [comment]
Works on my machine. How did you install sbt, and what does the script look like?

**Comment by coryfklein** [comment]
I installed with `brew install sbt`.

Here's the output of `sh -x sbt`

```
+ '[' -f /Users/coryklein/.sbtconfig ']'
+ exec /usr/local/Cellar/sbt/0.13.6/libexec/sbt
[info] Set current project to hello (in build file:/Users/coryklein/playground/hello/)
[error] export usage:
[error]   export <tasks>+   Executes tasks and displays the equivalent command lines.
[error]
[error] export
[error]       ^
```

It appears to be looking for `~/.sbtconfig`, but that file doesn't exist. Might that be the problem?

> what does the script look like?

What script?

**Comment by coryfklein** [comment]
Ah, I just read [this](https://github.com/sbt/sbt/blob/0.13/CONTRIBUTING.md). I am closing this issue and will look for resolution on stackoverflow and the sbt-dev group.

**Comment by coryfklein** [comment]
[Here](http://stackoverflow.com/questions/26372157/export-usage-error-when-doing-example-from-sbt-docs) is the SO question
