### ISSUE TITLE
test running before classfiles flushed to disk

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#1678]
One of our tests https://github.com/ensime/ensime-server/blob/master/src/test/scala/org/ensime/indexer/SearchServiceSpec.scala

fails about 10% of the time when typing `test` in sbt whereas it always succeeds when doing a two phase `test:compile`, then `test`.

This test is relying on the `.class` files of the project being flushed to disk before running (it's indexing them to test the search functionality). I strongly suspect that classes are being written AFTER the tests start running.

Creating a minimal working example is quite tough because it is more likely for larger projects, but it would looks something like this:
- have a big (single module) project with lots of sources and tests
- in one of the tests, first thing, touch a file
- `sbt test` from clean
- do a `find -newer FILE` to show that `.class` files have been written out AFTER the tests started.

Does this sound possible?

**Comment by eed3si9n** [comment]
Since we do caching and parallel processing, I don't doubt that it's possible, but if this is happening wouldn't there be more reports on NoClassFoundException?

**Comment by fommil** [comment]
yeah, it's a weird one. When running a test, are you doing any analysis about which classes must be compiled for a test to be able to run? We're parsing `.class` files that we don't depend on (from a compilation point of view).

**Comment by eed3si9n** [comment]
> When running a test, are you doing any analysis about which classes must be compiled for a test to be able to run?

Not specifically for testing, but the incremental compiler's logic sounds similar to what you're describing. But as far as I know the `test:compile` task _should_ be done by the time it does testing. It is possible that there's some loose thread that hasn't caught up in closing file or something.

**Comment by fommil** [comment]
this seems to have gone away with increasing 0.13.6-RCs. Weird.

**Comment by jsuereth** [comment]
Is this a mutli-project build and were some classes being read from other modules?

**Comment by fommil** [comment]
nope, one module.
