### ISSUE TITLE
Broken links in "Running Project Code" docs

### ISSUE THREAD

**Issue by alexeyr** [sbt/sbt#1685]
http://www.scala-sbt.org/release/docs/Running-Project-Code.html gives two example links for "the deserialization code avoids ensures that the right class loader is used". Both are currently broken.  "avoids" should be removed from that sentence as well.

**Comment by adinath** [comment]
It looks like default branches for https://github.com/NetLogo/NetLogo/ and https://github.com/scala/scala/ has changed from `master` to their respective release branches. Can we point it to it? 
It will need change in URL .

**Comment by eed3si9n** [comment]
The repo is at sbt/website if either of you want to send us a pull request.

**Comment by adinath** [comment]
submitted pull request. https://github.com/sbt/website/pull/87

**Comment by eed3si9n** [comment]
Thanks @adinath
