### ISSUE TITLE
Fasttrack version bump of SBT to Scala 2.11.x

### ISSUE THREAD

**Issue by mdedetrich** [sbt/sbt#1691]
This is more of a general discussion in regards to getting SBT to bump their Scala version to 2.11.x faster than what the apparent timeline is.

This is mainly in regards to the case class 22 arity limit. Normally this isn't an issue for standard scala code, because there is much more control over the version of the Scala compiler and ways to work around that, however with SBT we are essentially just stuck with Scala 2.10.4, and because SBT plugins are only compiled for 2.10.x, its much harder to just compile SBT with Scala 2.11.x and be done with it

The arity limit is of particular concern, because there is no way around this. There are class generators, such as https://github.com/eed3si9n/scalaxb, where the plugin basically does not work. Its not like you can bypass this limitation with macros or something along those lines, as long as we are stuck with SBT 2.10.x, we are actually unable to use SBT code generators when they happen to create case classes with more then 22 parameters (and there are many legitimate reasons why you will have more than 22 parameters in your case class)

Is it possible to fastback the bump in SBT's version for this reason. It is definitely understandable why you want to be stable, as possible, with your build tool, however at the same time, having a hard coded arity limit of 22 is frankly quite ridiculous especially since the SBT tool has been stuck with this limitation for years (our company has been waiting for over a year now for this issue to resolve itself). Its also not like cross compiling SBT plugins is out of the question, its pretty much standard practice for normal Scala code, and there is nothing stopping SBT from supporting Scala 2.10.x and Scala 2.11.x equally

**Comment by eed3si9n** [comment]
I happen to be a committer of both sbt and scalaxb, but I don't think sbt going to 2.11 is going to help or hinder scalaxb since it just generates `String` without using Scala's AST.

**Comment by eed3si9n** [comment]
The Scala version being used by sbt only effects Scala written in plugins and build files.
