### ISSUE TITLE
Resolvers doc out of sync: bintrayRepo and jcenterRepo don't exist

### ISSUE THREAD

**Issue by erikkaplun** [sbt/sbt#1696]
The doc at http://www.scala-sbt.org/0.13/docs/Resolvers.html has:

> Resolver.bintrayRepo("owner", "repo") This is the Bintray repository at https://dl.bintray.com/[owner]/[repo]/
> Resolver.jcenterRepo This is the Bintray JCenter repository at https://jcenter.bintray.com/

However, these do not seem to exist in reality:

> error: value jcenterRepo is not a member of object sbt.Resolver
> error: value bintrayRepo is not a member of object sbt.Resolver

I haven't checked the rest of the helpers.

**Comment by jsuereth** [comment]
Which version of sbt are you using?

**Comment by erikkaplun** [comment]
0.13.6 (sorry, should've mentioned)

**Comment by jsuereth** [comment]
Can yu try sbt 0.13.7-RC1

**Comment by erikkaplun** [comment]
Actually before it even gets to the `build.sbt` part, I get:

```
java.lang.NoSuchMethodError: sbt.Def$.derive(Lsbt/Init$Setting;ZLscala/Function1;Lscala/Function1;)Lsbt/Init$Setting;
    at wartremover.package$.wartremoverSettings$lzycompute(package.scala:20)
    at wartremover.package$.wartremoverSettings(package.scala:11)
    at wartremover.WartRemover$.projectSettings$lzycompute(WartRemover.scala:16)
    at wartremover.WartRemover$.projectSettings(WartRemover.scala:16)
```

**Comment by jsuereth** [comment]
Hmm, this looks like a binary compatibility issue with 0.13.7-RC1 and the wart remover plugin.  Let me investigate that one.

**Comment by jsuereth** [comment]
Hmm, that incompatibility existed in 0.13.6, so I'm curious how you're only hitting it now....

**Comment by dwijnand** [comment]
Doh, having just fixed it.. oh well :)

https://github.com/typelevel/wartremover/issues/123

**Comment by avdv** [comment]
Hi.

I also get this error:

```
build.sbt:8: error: value bintrayRepo is not a member of object sbt.Resolver
resolvers += Resolver.bintrayRepo("scalaz", "releases")
                      ^
[error] Type error in expression
```

sbt about:

```
[info] This is sbt 0.13.7
[info] No project is currently loaded
[info] sbt, sbt plugins, and build definitions are using Scala 2.10.4
```

Looking at https://github.com/sbt/sbt/blob/v0.13.7/ivy/src/main/scala/sbt/Resolver.scala#L183 that function should exist. Am I missing something?

**Comment by cocodrino** [comment]
@avdv did you solve the error?..I'm getting the same error even when I've an updated sbt.....

**Comment by avdv** [comment]
> did you solve the error?..I'm getting the same error even when I've an updated sbt.....

I just tried it with SBT 0.13.8 and 0.13.7 and it works for me.

Don't know what the issue was but seems it's gone...

**Comment by seykron** [comment]
I'm experiencing the same issue with sbt 0.13.8

**Comment by avdv** [comment]
> I'm experiencing the same issue with sbt 0.13.8

Is that the version of your sbt launcher or the sbt version you're using in your project? What's the output when you run `sbt about` in your project folder?

**Comment by seykron** [comment]
> [info] This is sbt 0.13.5
> [info] The current project is built against Scala 2.11.2
> [info] Available Plugins: sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.CorePlugin, > sbt.plugins.JUnitXmlReportPlugin, scoverage.ScoverageSbtPlugin, sbtrelease.ReleasePlugin, > spray.revolver.RevolverPlugin, org.sbtidea.SbtIdeaPlugin, com.typesafe.sbteclipse.plugin.EclipsePlugin, > net.virtualvoid.sbt.graph.Plugin, sbtbuildinfo.Plugin
> [info] sbt, sbt plugins, and build definitions are using Scala 2.10.4

It seems the launcher is using sbt 0.13.5. Is it any way to force or upgrade the sbt version? I didn't find it in the plugin documentation.

Thanks

**Comment by seykron** [comment]
By the way, I get here trying to make work the sbt-scoverage plugin. I configured the plugin as [it is specified in the documentation](https://github.com/scoverage/sbt-scoverage) and it couldn't resolve dependencies. I found [a workaround](https://github.com/sbt/sbt/issues/2125) that worked fine for me. The issue seems to be fixed right now.

**Comment by avdv** [comment]
> It seems the launcher is using sbt 0.13.5. Is it any way to force or upgrade the sbt version?

Edit your `project/build.properties` file (or create it) and set the `sbt.version` there:

```
sbt.version=0.13.8
```

**Comment by mcamou** [comment]
This just started happening to me today. I had 0.13.8 in my `build.properties`, tried updating to 0.13.11 but it still will not find `Resolvers.bintrayRepo`.

**Comment by avdv** [comment]
@mcamou please double check that you're realling running the specified version. what's the output of `about` when you run that in SBT?

**Comment by TimSoethout** [comment]
For me it turned out that this line in `~/.sbt/0.13/plugins/plugins.sbt`:
```addSbtPlugin("net.virtual-void" % "sbt-optimizer" % "0.1.0")``` was causing the problem. 

I guess it somehow got an old sbt jar on the path.

**Comment by eed3si9n** [comment]
Closing this since it doesn't look relevant anymore.
