### ISSUE TITLE
High CPU usage on sys.exit while Akka project `run` task (and it doesn't exit)

### ISSUE THREAD

**Issue by He-Pin** [sbt/sbt#1697]
I found this issue when I was writing an akka REPL,when I run the program via `sbt run`,and then call `sys.exit()` in an actor;will cause cpu 100%
code like this below
in an actor onReceive block

```
  def handleCommand(command: String):Unit = command match {
    case "help" =>
      println(
        """
          |help     print this help
          |exit     exit this program
          |
          |
        """.stripMargin)
    case "exit"=>
      //if only call sys.exit in sbt run,will cause cpu load high to 100%,and never exit
      context.stop(self)
      context.system.shutdown()
      sys.exit()
    case _ => //NOOP
  }
```

**Comment by eed3si9n** [comment]
Related #1293

**Comment by jsuereth** [comment]
Are there any threads running when you call sys.exit?

Because sbt does not fork, it has special code to avoid having sys.exit crash the build itself.  Also, this spinning is because sbt is waiting for all generated threads in `run` task to be shut down before it returns.

As a workaround you can set `fork in (Compile, run) := true` and you should be good to go.

**Comment by He-Pin** [comment]
yes,cause I call sys.exit in an actor
so ,seems this could close for now?thanks

**Comment by He-Pin** [comment]
when I turn to using fork.it become OOM
seems it fork to many instance.

**Comment by jsuereth** [comment]
OOM? huh.... would like to learn more.  We'll try to help anyway we can.

**Comment by He-Pin** [comment]
yes,I am running a akka system, after I add the `fork` in the sbt,sbt start to many instance,and finally ,OOM at java heap

**Comment by jsuereth** [comment]
So somehow `run` is forking a whole bunch of new instances... that sounds wrong/bad.  Any chane you can show us a log?

**Comment by He-Pin** [comment]
maybe I could show up a simple project:P,cause current with to many noise

**Comment by jsuereth** [comment]
would be great

**Comment by He-Pin** [comment]
After I try a simple akka project,your advice of add `fork` works.the only different in my project is that I create a module which has actor via reflection.I will learn more about it.

**Comment by eed3si9n** [comment]
Closing this since there's a workaround.
