### ISSUE TITLE
StackOverflow error when analyzing class with self-referential static member

### ISSUE THREAD

**Issue by scroyston** [sbt/sbt#17]
When trying to compile a project with a generated google protobuf  class, I get a StackOverflow exception during the analysis phase.

I believe it's due to the class having a static member of itself, the core infinite recursion happens in sbt.ClassToAPI.merge

I was able to "fix the glitch" with the patch below, though I don't think it handles things like multihop circular dependencies.

The actual class I had a problem with was:
http://code.google.com/apis/protocolbuffers/docs/reference/java/com/google/protobuf/GeneratedMessage.ExtendableMessage.html

def merge[T](of: Class[_], self: Seq[T], public: Seq[T], f: T => Seq[api.Definition], splitStatic: Seq[T] => %28Seq[T],Seq[T]%29, isInherited: T => Boolean): Defs =
  {
                val (selfStatic, selfInstance) = splitStatic(self)
                val (inheritedStatic, inheritedInstance) = splitStatic(public filter isInherited)
-               Defs(selfInstance flatMap f, inheritedInstance flatMap f, selfStatic flatMap f, inheritedStatic flatMap f)
-    val selfStaticItems = selfStatic.filterNot(_ == of) flatMap f
-               Defs(selfInstance flatMap f, inheritedInstance flatMap f, selfStaticItems, inheritedStatic flatMap f)
      }

**Comment by harrah** [comment]
Is it possible for you to provide a relatively small, self-contained source code example that causes this?  I'd like to make a test case for this.

**Comment by scroyston** [comment]
I'm not sure this is as self-contained as you were thinking, but here's a one java class project example:

https://github.com/scroyston/sbt_example_overflow

If you run sbt compile, it will StackOverflow

**Comment by scroyston** [comment]
Got it down to sefl contained source:

public class Person {
    public class ExtendableMessage extends Person {}
}

Will do it

**Comment by harrah** [comment]
Great, thanks!

**Comment by harrah** [comment]
Referenced wrong issue in the commit.  Fixed in https://github.com/harrah/xsbt/commit/1d36be9b0023e6061e7d90c440af01a3c7bacd32
