### ISSUE TITLE
"sbt console" in SBT 0.10.1 with Scala 2.9.1 is broken in Windows.

### ISSUE THREAD

**Issue by seanparsons** [sbt/sbt#170]
So far I've found the following symptoms:
1) Any expression or command causes the REPL to lock up.
2) Pressing the up or down cursor keys results in a system beep only and also then causes subsequent key presses to system beep.

Have also tried this in Ubuntu and it worked without any issues.

**Comment by harrah** [comment]
It is rather likely this is a bug in the repl as there have been bugs reported in this area.  Please use the mailing list to track this down, as others may have had a similar issue.

**Comment by seanparsons** [comment]
The REPL itself worked fine standalone, I updated to 2.9.1 and tried all the above and that worked, seems like it's an interaction between the two that is problematic.
