### ISSUE TITLE
Resolving plugins from snapshot repo not working

### ISSUE THREAD

**Issue by hseeberger** [sbt/sbt#171]
I updated sbteclipse to use sbt 0.11-RC0. Using the sbteclipse release 1.4-RC1 works fine, but I cannot use 1.4-SNAPSHOT.

This is my build.sbt in ~/.sbt/plugins:

``` scala
resolvers += Classpaths.typesafeSnapshots

addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse" % "1.4-SNAPSHOTS")
```

This is the error message:

[warn]  module not found: com.typesafe.sbteclipse#sbteclipse;1.4-SNAPSHOTS
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbteclipse/sbteclipse/scala_2.9.1/sbt_0.11.0-RC0/1.4-SNAPSHOTS/ivys/ivy.xml
[warn]   -- artifact com.typesafe.sbteclipse#sbteclipse;1.4-SNAPSHOTS!sbteclipse.jar:
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbteclipse/sbteclipse/scala_2.9.1/sbt_0.11.0-RC0/1.4-SNAPSHOTS/jars/sbteclipse.jar
[warn] ==== local: tried
[warn]   /Users/heiko/.ivy2/local/com.typesafe.sbteclipse/sbteclipse/scala_2.9.1/sbt_0.11.0-RC0/1.4-SNAPSHOTS/ivys/ivy.xml
[warn]   -- artifact com.typesafe.sbteclipse#sbteclipse;1.4-SNAPSHOTS!sbteclipse.jar:
[warn]   /Users/heiko/.ivy2/local/com.typesafe.sbteclipse/sbteclipse/scala_2.9.1/sbt_0.11.0-RC0/1.4-SNAPSHOTS/jars/sbteclipse.jar
[warn] ==== typesafe-ivy-snapshots: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-snapshots/com.typesafe.sbteclipse/sbteclipse/scala_2.9.1/sbt_0.11.0-RC0/1.4-SNAPSHOTS/ivys/ivy.xml
[warn]   -- artifact com.typesafe.sbteclipse#sbteclipse;1.4-SNAPSHOTS!sbteclipse.jar:
[warn]   http://repo.typesafe.com/typesafe/ivy-snapshots/com.typesafe.sbteclipse/sbteclipse/scala_2.9.1/sbt_0.11.0-RC0/1.4-SNAPSHOTS/jars/sbteclipse.jar
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/typesafe/sbteclipse/sbteclipse_2.9.1_0.11.0-RC0/1.4-SNAPSHOTS/sbteclipse-1.4-SNAPSHOTS.pom
[warn]   -- artifact com.typesafe.sbteclipse#sbteclipse;1.4-SNAPSHOTS!sbteclipse.jar:
[warn]   http://repo1.maven.org/maven2/com/typesafe/sbteclipse/sbteclipse_2.9.1_0.11.0-RC0/1.4-SNAPSHOTS/sbteclipse-1.4-SNAPSHOTS.jar
[warn] ==== Scala-Tools Maven2 Repository: tried
[warn]   http://scala-tools.org/repo-releases/com/typesafe/sbteclipse/sbteclipse_2.9.1_0.11.0-RC0/1.4-SNAPSHOTS/sbteclipse-1.4-SNAPSHOTS.pom
[warn]   -- artifact com.typesafe.sbteclipse#sbteclipse;1.4-SNAPSHOTS!sbteclipse.jar:
[warn]   http://scala-tools.org/repo-releases/com/typesafe/sbteclipse/sbteclipse_2.9.1_0.11.0-RC0/1.4-SNAPSHOTS/sbteclipse-1.4-SNAPSHOTS.jar
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.typesafe.sbteclipse#sbteclipse;1.4-SNAPSHOTS: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]      com.typesafe.sbteclipse:sbteclipse:1.4-SNAPSHOTS (sbtVersion=0.11.0-RC0, scalaVersion=2.9.1)
[warn] 
[error] {file:/Users/heiko/.sbt/plugins/}default-418414/*:update: sbt.ResolveException: unresolved dependency: com.types

**Comment by harrah** [comment]
1.4-SNAPSHOT, not 1.4-SNAPSHOTS.

**Comment by hseeberger** [comment]
Well ... sorry ;-)
