### ISSUE TITLE
[0.13.7-RC3] java.lang.SecurityException in Jetty

### ISSUE THREAD

**Issue by japgolly** [sbt/sbt#1718]
With 0.13.7-RC3 the unit tests for a Lift & Jetty based webapp fail consistently.

I've compared dependencyTree output for both 0.13.5 and 0.13.7-RC3 but they're identical.

```
[info] Exception encountered when attempting to run a suite with class name: x.webapp.app.PermissionTest *** ABORTED ***
[info]   java.lang.ExceptionInInitializerError:
[info]   at org.eclipse.jetty.servlet.ServletContextHandler.newSessionHandler(ServletContextHandler.java:241)
[info]   at org.eclipse.jetty.servlet.ServletContextHandler.getSessionHandler(ServletContextHandler.java:334)
[info]   at org.eclipse.jetty.servlet.ServletContextHandler.relinkHandlers(ServletContextHandler.java:180)
[info]   at org.eclipse.jetty.servlet.ServletContextHandler.<init>(ServletContextHandler.java:157)
[info]   at org.eclipse.jetty.webapp.WebAppContext.<init>(WebAppContext.java:245)
[info]   at org.eclipse.jetty.webapp.WebAppContext.<init>(WebAppContext.java:193)
[info]   at x.webapp.test.Jetty.newServer(Jetty.scala:57)
[info]   at x.webapp.test.Jetty.start(Jetty.scala:27)
[info]   at x.webapp.test.LiveTest$class.beforeAll(LiveTest.scala:27)
[info]   at x.webapp.app.PermissionTest.beforeAll(PermissionTest.scala:14)
[info]   ...
[info]   Cause: java.lang.SecurityException: class "javax.servlet.http.HttpSessionIdListener"'s signer information does not match signer information of other classes in the same package
[info]   at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
[info]   at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
[info]   at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
[info]   at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[info]   at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
[info]   at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[info]   at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
[info]   at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[info]   at java.security.AccessController.doPrivileged(Native Method)
[info]   at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
[info]   ...
```

**Comment by jsuereth** [comment]
We'll need the classpath for this one. My guess is someone is sneaking a javax.servlet classfile set into one of the JARs on your classpath, and the new classpath ordering means it gets loaded first (vs. previous resolution), leading to the exception you see.

**Comment by japgolly** [comment]
Ah cool, i'll take another look this arvo. So a `show fullClasspath` comparison would be helpful you're saying?

**Comment by eed3si9n** [comment]
Is this with or without cached resolution?

**Comment by japgolly** [comment]
Whatever the default is. I didn't change any of my settings apart from the SBT version. If you like I can try it with and without. Just let me know any permutation of settings and I'll add them and try it.

**Comment by eed3si9n** [comment]
If you didn't change anything it's likely without cached resolution. Here's how to turn it on, if you want to give it a shot:

``` scala
updateOptions := updateOptions.value.withCachedResolution(true)
```

**Comment by japgolly** [comment]
This isn't exactly a test case but it should be a means of deterministically reproducing the issue.

Here is a skeleton SBT project. It contains no code, just the build setup from my main project at work in which I encountered this issue and #1711. I believe if you inspect the {compile, test, runtime} scoped classpaths of modules {base-test, webapp-server}, then drop the version back to 0.13.6 to re-inspect and compare, you'll see discrepancies.

https://github.com/japgolly/sbt/tree/skeleton

**Comment by japgolly** [comment]
FYI these issues still exist 0.13.7 final with both consolidated and cached resolution.

**Comment by SethTisue** [comment]
this seems so old that we might as well just close it at this point, unless someone comes forward with evidence that the problem still exists in sbt 1.9
