### ISSUE TITLE
How to solve this sbt error?

### ISSUE THREAD

**Issue by byam** [sbt/sbt#1726]
sbt is not running properly. 

```
[warn] Scala version was updated by one of library dependencies:
[warn]  * org.scala-lang:scala-library:(2.11.1, 2.11.2, 2.11.0) -> 2.11.4
[warn] To force scalaVersion, add the following:
[warn]  ivyScala := ivyScala.value map { _.copy(overrideScalaVersion = true) }
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  * org.scalikejdbc:scalikejdbc-config_2.11:2.0.0 -> 2.1.0
[warn]  * org.scalikejdbc:scalikejdbc_2.11:2.0.0 -> 2.1.4
[warn] Run 'evicted' to see detailed eviction warnings
```

**Comment by byam** [comment]
old sbt version was 0.13.5 and i reinstalled it to 0.13.7. But didn't work too. project's  sbt is 0.13.6

**Comment by eed3si9n** [comment]
That's not an error. It's a warning about potentially conflicting eviction.
You can resolve scala version warning by picking 2.11.4 manually, and the rest using `dependencyOverrides` - http://www.scala-sbt.org/release/docs/Library-Management.html#Forcing+a+revision+without+introducing+a+dependency
