### ISSUE TITLE
killing the sbt script doesn't kill the java process

### ISSUE THREAD

**Issue by obfusk** [sbt/sbt#1728]
Would it be possible to have the sbt script kill the java process when it is killed? I used `sbt run` as a daemon (from a script that starts and kills web apps on demand) and ran into the fact that killing the sbt process that was started did not kill the java process. I now use the following wrapper for sbt (renamed to `sbt.real`) to get the desired behaviour, but it would be nice if the sbt script could do that.

``` bash
#!/bin/bash
code='trap '\''pkill -TERM -P $$; wait'\'' EXIT; source "$0" "$@"'
real="$( which sbt.real )"
args=( "$@" )
exec bash -c "$code" "$real" "${args[@]}"
```

\- Felix

**Comment by eed3si9n** [comment]
I am going to close this due to inactivity, but let us know if this issue is still relevant.
