### ISSUE TITLE
Cannot add local plugins to project defined in build.sbt

### ISSUE THREAD

**Issue by hseeberger** [sbt/sbt#173]
But works for project defined in Build.scala.

See the two commits "fails" and "works" in https://github.com/hseeberger/sbt-foo

**Comment by harrah** [comment]
The error message may be instructive.  May I suggest using the mailing list?

**Comment by harrah** [comment]
sbt needs to prefix automatic imports with `_root_`

**Comment by indrajitr** [comment]
This now has an interesting side effect :)

For a build.scala with `<empty>` package, like so:

``` scala
import sbt._
import Keys._

object FooBuild extends Build {
  // stuff
}
```

`set` throws error like so:

``` console
sbt> set logLevel := Level.Debug
<set>:0: error: object Build is not a member of package <root>
import _root_.org.sbtidea.SbtIdeaPlugin._, _root_.org.scala_tools.sbt.ScalaToolsPlugin._, _root_.net.liftweb.sbt.YuiCompressorPlugin._, _root_.FooBuild._
```

Of course, things are back to normal with an explicit `package foo` header in build.scala.
