### ISSUE TITLE
Publish to maven repository with custome location

### ISSUE THREAD

**Issue by C-h-e-r-r-y** [sbt/sbt#1735]
When command `publishM2` is invoked it tries to publish to `%userDri%/.m2`. But what if maven repository has diffferent location? It is usefull to add new java option for that like `sbt.maven.repo`. With that I can pass `-Dsbt.maven.repo=...` from command line or modify `sbtconfig.txt` settings and set maven location forever without modifying files `build.sbt` in every project.

**Comment by jsuereth** [comment]
Actually, I think this will use the maven conventions of `M2_LOCAL_REPO` environment variable.

See: https://github.com/sbt/sbt/blob/0.13/ivy/src/main/scala/sbt/Resolver.scala#L304-L324

If you're interested, you could also add a Java properter than and submit a PR.

**Comment by dwijnand** [comment]
I think the original link was to this section of code: https://github.com/sbt/sbt/blob/v0.13.9/ivy/src/main/scala/sbt/Resolver.scala#L332-L351.

@jsuereth what do you think is the correct precedence ordering? `M2_LOCAL_REPO` trumps all?

**Comment by eed3si9n** [comment]
https://www.scala-sbt.org/1.x/docs/Publishing.html#Define+the+repository
