### ISSUE TITLE
Impossible to tell what line caused test failure

### ISSUE THREAD

**Issue by benmccann** [sbt/sbt#1749]
To reproduce just add the line `org.junit.Assert.assertTrue(false);` to a JUnit test. If you need a project with a JUnit test to test with, then run `activator new` and select `play-java` to create one. (The minimal-java project does not currently have an example test, but I've submitted a pull request to add one)

When you run the tests, here's the output. It's impossible to figure out what line the test is failing on when it's a large file with multiple assertions. All we get is "failed: null" and no line number or stacktrace, which is a recurring source of frustration for the developers on our team

```
$ ./activator test
[info] Loading project definition from /home/bmccann/src/play-java/project
[info] Set current project to play-java (in build file:/home/bmccann/src/play-java/)
[error] Test ApplicationTest.simpleCheck failed: null, took 0.02 sec
[error] Failed: Total 3, Failed 1, Errors 0, Passed 2
[error] Failed tests:
[error]     ApplicationTest
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 5 s, completed Nov 20, 2014 10:16:48 PM
```

[Play 2.3.0 & 2.3.1 did it's own magic](https://github.com/playframework/playframework/blob/92e4a4a90710c51556d1cdc85c38ebc09ca1bfc0/framework/src/sbt-plugin/src/main/scala/test/JUnitXmlTestListener.scala) to print out much better output as shown below. However, it depended on Play's junit xml report generator, which we removed in favor of [the built-in SBT one](http://www.scala-sbt.org/0.13/sxr/sbt/JUnitXmlTestsListener.scala.html#sbt;JUnitXmlTestsListener), and so now we're back to the output above, which doesn't have enough info to let us know where a test is failing.

```
$ ./activator test
[info] Loading project definition from /home/bmccann/src/play-java/project
[info] Updating {file:/home/bmccann/src/play-java/project/}play-java-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to play-java (in build file:/home/bmccann/src/play-java/)
[info] Updating {file:/home/bmccann/src/play-java/}root...
[info] Resolving jline#jline;2.11 ...
[info] Done updating.
[error] Test ApplicationTest.simpleCheck failed: null, took 0.016 sec
[info] ApplicationTest
[info] x ApplicationTest.simpleCheck
[error] sbt.ForkMain$ForkError
[error]     at org.junit.Assert.fail(Assert.java:86)
[error]     at org.junit.Assert.assertTrue(Assert.java:41)
[error]     at org.junit.Assert.assertTrue(Assert.java:52)
[error]     at ApplicationTest.simpleCheck(ApplicationTest.java:35)
[info] + ApplicationTest.renderTemplate
[info] 
[info] 
[info] Total for test ApplicationTest
[info] Finished in 0.082 seconds
[info] 2 tests, 1 failures, 0 errors
[info] IntegrationTest
[info] + IntegrationTest.test
[info] 
[info] 
[info] Total for test IntegrationTest
[info] Finished in 0.001 seconds
[info] 1 tests, 0 failures, 0 errors
[error] Failed: Total 3, Failed 1, Errors 0, Passed 2
[error] Failed tests:
[error]     ApplicationTest
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 7 s, completed Nov 21, 2014 8:33:09 AM
```

**Comment by eed3si9n** [comment]
So we need to port @jroper's playframework/playframework#2517 to sbt somehow?

**Comment by benmccann** [comment]
I'm not really sure. I believe what the Play class did is that it both generated the XML report and it logged test output, which ended up going to the console. It seems that these two functions are separated in SBT. [This is the class that SBT uses to generate the XML report](http://www.scala-sbt.org/0.13/sxr/sbt/JUnitXmlTestsListener.scala.html#sbt;JUnitXmlTestsListener). If you open up the reports in target/test-reports when a test fails then they have a stack trace with the line number that the test failed on - it's just not output to the sccreen. Do you know what is responsible for determining what gets printed to the screen when a test runs in SBT?

**Comment by sebdotv** [comment]
I'm happy with the following setup since the migration to Play 2.3:

// ref: https://github.com/sbt/junit-interface
// -v log "test run started" / "test started" / "test run finished" events on log level "info" instead of "debug"
// -q suppress stdout for successful tests
// -a show stack traces and exception class name for AssertionErrors
testOptions += Tests.Argument(TestFrameworks.JUnit, "-v", "-q", "-a")

**Comment by benmccann** [comment]
@sebdotv THANK YOU! I didn't know that there was -a option. I can't believe this isn't the default since the output is completely useless without it. I filed a bug to make it the default. https://github.com/sbt/junit-interface/issues/62. I suppose I'll close this issue since adding -a works.

Btw, I strongly recommend not using -q due to https://github.com/sbt/sbt/issues/1706
