### ISSUE TITLE
Make -Yrepl-sync option default for all console tasks

### ISSUE THREAD

**Issue by kahliburke** [sbt/sbt#175]
See https://groups.google.com/group/simple-build-tool/browse_thread/thread/e7580241f3df3d4f#

Scala 2.9.1's REPL has issues with sbt, hanging occurs when import statements are executed in the initial commands. Currently console-project uses this setting by default and this should be extended to the other console tasks.

**Comment by harrah** [comment]
I added this and then realized that this option is only available for 2.9.1 and causes problems for other Scala versions.  That was why it was only added to console-project.  It is tough to add default options without knowing what the valid options are.  So, this is `wontfix` until there is a way to handle this better.
