### ISSUE TITLE
Incremental compilation, wildcard import is not handled correctly

### ISSUE THREAD

**Issue by niklasfors** [sbt/sbt#1751]
I have experimenting a bit with the incremental compiler in sbt, and I have found some bugs regarding wildcard imports.
### Example: Adding String class to package

The following example illustrates the problem. The problem is the wildcard import (import p._) in combination with name shadowing.

```
// A.scala
import p._
class A {
  def f(): String = "10"
}
// B.scala
package p {
  class B
}
```

First, we compile the above code. Then, an empty class String is added to the package p. When compiling again, only B.scala will be re-compiled and not A.scala. The compiler should re-compile A.scala too and complain that the type p.String is not compatible with the String literal "10" that is of type java.lang.String.
### Example 2

Consider the following code

```
// A.scala
import p._
class A {
  def foo(): Int = new B().f()
}

// p.scala
package p {
  class B {
    def f(): Int = 1
  }
}
```

We first compile the code above, then we add the class B to a new file B.scala:

```
// B.scala
class B {
  def f(): String = "1"
}
```

When compiling again, only B.scala is re-compiled, and not A.scala. The file A.scala should be re-compiled since the use of B in class A now refers to B in B.scala and not B in p.scala. Hence, a type error should be reported due to the changed return type of the method f().
### Version

```
$ sbt --version
sbt launcher version 0.13.7
$ scala -version
Scala code runner version 2.11.2 -- Copyright 2002-2013, LAMP/EPFL
```

**Comment by niklasfors** [comment]
Another example:

```
// A.scala
import p1._
import p2._
class A {
  val b = new B()
}

// p1.scala
package p1 {
  class B
}

// p2.scala
package p2 {
}
```

Then adding class B to p2 should give an error in A.scala (ambiguous reference to B), but only p2.scala is re-compiled and no errors are reported.

**Comment by jvican** [comment]
I propose to close this issue in favor of https://github.com/sbt/zinc/issues/226.

**Comment by dwijnand** [comment]
sure
