### ISSUE TITLE
Cached resolution interferes with exclusions and custom configs

### ISSUE THREAD

**Issue by OlegYch** [sbt/sbt#1758]
see https://github.com/OlegYch/sbt-cached-resolution-exclusion-multijvm
try to execute 'test' - with cached resolution scalatest is not found and compilation fails

**Comment by eed3si9n** [comment]
Thanks for the repro project.
It seems to work with 0.13.7.

**Comment by OlegYch** [comment]
pretty sure it doesn't work with 0.13.7, thats what repro is using

**Comment by OlegYch** [comment]
neither does 0.13.8-M5

**Comment by eed3si9n** [comment]
I'm able to get the following using sbt 0.13.7:

```
cache> clean
[success] Total time: 0 s, completed Feb 25, 2015 6:30:44 PM
cache> test
[info] Updating {file:/Users/eugene/work/quick-test/sbt-cached-resolution-exclusion-multijvm/}cache...
[info] Done updating.
[info] Run completed in 10 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] No tests were executed.
[success] Total time: 0 s, completed Feb 25, 2015 6:30:45 PM
```

**Comment by OlegYch** [comment]
looks like something's wrong with my ~.sbt\0.13\dependency\static
here it is https://dl.dropboxusercontent.com/u/15055701/static.zip , seems to reliably cause missing scalatest from multi-jvm test classpath
