### ISSUE TITLE
Modules were resolved with conflicting cross-version suffixes only when cached resolution is on

### ISSUE THREAD

**Issue by rajish** [sbt/sbt#1761]
A project compiled with cached dependencies enabled complains about conflicting cross-version suffixes of a library (see [this gist](https://gist.github.com/rajish/223041144513446bd5c7)).

The same project when compiled without cached dependencies (i.e. the `~/.sbt/0.13/dependency` directory removed and the `updateOptions := updateOptions.value.withCachedResolution(false)`) compiles without errors.

**Comment by eed3si9n** [comment]
If quasiquotes_2.10 and quasiquotes_2.10.3 are both found in the graph, the warning is legitimate.
The actual error may be #1760.

**Comment by wz2326** [comment]
i know
