### ISSUE TITLE
support HTCPCP

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#1762]
Seriously guys, catch up to 1998 and support HTCPCP http://en.wikipedia.org/wiki/Hyper_Text_Coffee_Pot_Control_Protocol 

(I can wait a little longer for an update to RFC 7168)

**Comment by jsuereth** [comment]
PR welcome.   I'd do it myself but I keep drinking the coffee and don't have any spare clean pots.

**Comment by eed3si9n** [comment]
We already have [a project](https://github.com/sbt/sbt-remote-control) that controls sbt via unicorns and forks. I'd like to see [avian carriers](https://tools.ietf.org/html/rfc1149) in the mix as well.

**Comment by fommil** [comment]
Avian carriers -  well, at least it'll be faster than ivy :-P

**Comment by som-snytt** [comment]
This is what [sbt-extras](https://github.com/paulp/sbt-extras) is for.
