### ISSUE TITLE
sbt 0.13.7 has lots of caching bugs with plugins

### ISSUE THREAD

**Issue by Sciss** [sbt/sbt#1767]
I instantly see two bugs with plugins that stop working correctly:
- [sbt-updates](https://github.com/rtimush/sbt-updates/issues/37)
- [sbt-dependency-graph](https://github.com/jrudolph/sbt-dependency-graph/issues/58)

This is a regression against sbt 0.13.6 for which these plugins work as expected.

**Comment by benhutchison** [comment]
I also hit a problem in 0.13.7, rollback to 0.13.6 fixed it:

```
$ sbt
[info] Loading global plugins from /Users/ben_hutchison/.sbt/0.13/plugins
[info] Loading project definition from /Users/ben_hutchison/swork/halfthrone-client/project
java.lang.NoClassDefFoundError: net/virtualvoid/sbt/graph/Plugin$
    at $6e87f339643ce0c217ef$.$sbtdef(/Users/ben_hutchison/.sbt/0.13/build.sbt:1)
```

**Comment by eed3si9n** [comment]
I am closing this since it's likely no longer relevant.
