### ISSUE TITLE
maven properties in dependencies pom.xml are not expanded to values

### ISSUE THREAD

**Issue by hsn10** [sbt/sbt#1774]
reflections 0.9.9-RC2 can not be used because sbt does not expand ${javassist.version} macro  to values listed in properties section.

libraryDependencies ++= Seq(
    "org.scala-lang" % "scala-reflect" % scalaVersion.value,
    "org.reflections" % "reflections" % "0.9.9-RC2",
    "com.google.code.findbugs" % "jsr305" % "2.0.1"
)

reflections pom.xml is here: https://github.com/ronmamo/reflections/blob/master/pom.xml

tested with sbt 0.13.5 to 0.13.7

←M[info] Resolving org.reflections#reflections;0.9.9-RC2 ...
←M[info] Resolving org.javassist#javassist;${javassist.version} ...
[warn]  module not found: org.javassist#javassist;${javassist.version}

**Comment by hsn10** [comment]
it seems to be due to incorrect pom.xml file defining properties inside profile. More information at https://github.com/ronmamo/reflections/issues/52

**Comment by martin-g** [comment]
It is not incorrect. It is perfectly fine to declare the `<properties>` in `<profile>` (in Maven).
Either the `<profile>` is not activated by Ivy/SBT or it is not even used.
