### ISSUE TITLE
SNAPSHOT issues

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#1780]
There seems to be a number of SNAPSHOT related issues, so I'm going to make an epic issue to track them, and perhaps discuss expected behavior around SNAPSHOT.
### Re-resolution

R-1.1. Assuming the dependency graph stays constant, calling `compile` should NOT re-resolve SNAPSHOTs.
R-1.2. Starting up sbt should NOT re-resolve build or meta-build. This is partially due to IDEs spawning sbt from shell repeatedly.
### Force

R-2.1. Calling `update` re-resolves SNAPSHOTs.
R-2.2. To short-circuit or check all resolvers. (configurable?)
R-2.3 The list of resolvers to look for SNAPSHOTs. (configurable?)
R-2.4 Subproject re-resolution should be cached.
### Maven local m2

R-3. Should work with local m2.
### Resolver mixup
- #1495  SNAPSHOT dependency does not get resolved up while compiling a dependent project after publishing depended-on jar to remote repository when both operations are on the same box
### Short circuiting
- #1514 sbt doesn't see new SNAPSHOT dependency versions (Fixed but not enabled by default)
### Classifier
- #641 sbt SNAPSHOT dependency with classifiers not updating
- #1676 SNAPSHOT dependency with classifiers not updated
- #1750 updateClassifiers doesn't download sources and docs for updated snapshot dependencies
### Maven local m2
- #321 SBT doesn't see new SNAPSHOT dependency versions in local maven repos
- #1061 SNAPSHOT dependency not updated
- #1616 Maven local resolver with parent POM
- #2053 publishM2 doesnt write maven-metadata-local.xml which make SNAPSHOT work near impossible
- #2088 Fail to download the first SNAPSHOT publish to Artifactory
### Offline
- #1552 SNAPSHOT won't work offline
- #1824 Cannot parse snapshot xml from local ivy while offline
### Continuous
- #1446 Avoid updating snapshots in continuous run mode 
### Maven SNAPSHOT/uniqueVersions support
- <s>#679 Incorrect Maven Snapshot file resolution</s>
- #1322 SBT doesn't honor Maven's uniqueVersions 
- #1564 SBT does not replace SNAPSHOT with a date when publishing

**Comment by shijinkui** [comment]
http://xxx/ffff-xxx/1.0.0-20140312.020225-4/ffff-xxx-1.0.0-20140312.020225-4.pom

when i download pom, sbt show this url, 404. It should be `http://xxx/ffff-xxx/1.0.0-SNAPSHOT/ffff-xxx-1.0.0-20140312.020225-4.pom`

**Comment by matanox** [comment]
I have a case where a snapshot dependency in a sub-project (of a multi-project build) gets perfectly resolved when updating from inside the sub-project, but fails to resolve when the sub-project is updated from the root of the multi-project build. Would that map to any of the existing bugs here?

In this case I am handling, it seems to ignore the resolver where the snapshot is coming from, when updating from the root project ― but not when updating from within the sub-project. Trying to figure how to work around it...

**Comment by matanox** [comment]
Okay, the workaround in my case is to superfluously include the resolver for the snapshot which fails to resolve ― in all sub-projects, not just in the sub-project it should be required for. This somehow avoids the superfluous re-resolution of the snapshot dependency ― from failing.

**Comment by eed3si9n** [comment]
Since the adoption of Coursier, hopefully some of these issues are now resolved.
