### ISSUE TITLE
-Xelide-below does not work as scalacOptions option

### ISSUE THREAD

**Issue by kydos** [sbt/sbt#1790]
Trying to use:

```
scalacOptions += "-Xelide-below 123"
```

In a build.sbt file cause sbt to fail with the following error:

```
[error] bad option: '-Xelide-below 123'
[error] (compile:compile) Compilation failed
[error] Total time: 2 s, completed Dec 29, 2014 8:03:16 PM
```

A+

**Comment by kydos** [comment]
Found the issue, the argument to -Xelide-below has to be passed as a separate string, this now works fine:

``` scala
scalacOptions ++= Seq(
  "-Xelide-below", "123",
  "-Xdev",
  "-optimise",
  "-deprecation",
  "-unchecked",
  "-language:postfixOps",
  "-feature",
  "-Yinline-warnings"
)
```

**Comment by eed3si9n** [comment]
Looks like this can be closed now.

**Comment by som-snytt** [comment]
I'm just happy someone is using `-Xelide-below`.

They ought to do marketing studies before naming options.
