### ISSUE TITLE
Scripting example out of date

### ISSUE THREAD

**Issue by k4y3ff** [sbt/sbt#1792]
The [Scripts, REPL, and Dependencies](http://www.scala-sbt.org/0.13/docs/Scripts.html) page includes an example that no longer runs:

```
[error] (run-main) java.lang.RuntimeException: Extractor 'results ! dispatch.json.Js$list$$anon$1 does not match JSON: {"errors" : [{"message" : "The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.", "code" : 64}]}
java.lang.RuntimeException: Extractor 'results ! dispatch.json.Js$list$$anon$1 does not match JSON: {"errors" : [{"message" : "The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.", "code" : 64}]}
```

The example should be updated to use v1.1 of the Twitter REST API, or remove the Twitter REST API altogether (it doesn't seem necessary here...?).

**Comment by eed3si9n** [comment]
>  it doesn't seem necessary here...?

I guess the original author thought it would be a fun example to show case Scala scripting that'll use external library. I can substitute the example with something from http://eed3si9n.com/scripting-with-scala.
