### ISSUE TITLE
Detect class duplication in classpath

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [sbt/sbt#1794]
After reading the thread: https://groups.google.com/forum/#!topic/sbt-dev/LKICLjcVXlA
I'm motivated to open this feature request.

Sometimes, a transitive dependency brings the same artifact with a different naming, and it gets duplicated.  If the versions are incompatible, it can cause serious bugs, that don't always happen.  It is random which version will be used.

It would be interesting to be able to detect this.

Related Stackoverflow question:

http://stackoverflow.com/questions/27635346/how-can-i-find-duplicate-classes-amongst-dependencies-with-sbt

**Comment by eed3si9n** [comment]
Much like Maven, I think this is a feature that could probably be implemented as a community plugin.

**Comment by DavidPerezIngeniero** [comment]
I think so.

**Comment by DavidPerezIngeniero** [comment]
If I have time, I'll try to write one.

**Comment by pdalpra** [comment]
There is an implementation for this issue here : https://github.com/sbt/sbt-duplicates-finder

**Comment by raisercostin** [comment]
Nice one. It works wonderfully. The issue could be closed.
I already detected collisions like

```
[warn] Detected classes conflicts:
[warn]
[warn] - javax/xml/stream/XMLOutputFactory.class: content differ
[warn]   - C:\Users\costin\.ivy2\cache\xml-apis\xml-apis\jars\xml-apis-1.4.01.jar
[warn]   - C:\Users\costin\.ivy2\cache\stax\stax-api\jars\stax-api-1.0.1.jar
```

and

```
[warn] Detected resources conflicts:
[warn]
[warn] - reference.conf: content differ
[warn]   - C:\Users\costin\.ivy2\cache\io.spray\spray-can\bundles\spray-can-1.2.2.jar
[warn]   - C:\Users\costin\.ivy2\cache\com.typesafe.akka\akka-actor_2.10\jars\akka-actor_2.10-2.3.4.jar
```

**Comment by eed3si9n** [comment]
Closing this since there's a plugin for it.
