### ISSUE TITLE
OpenSuse: "Unable to bind key for unsupported operation" shows up on each command

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [sbt/sbt#1796]
I'm using SBT 0.13.7, and in the interactive command prompt, I receive this logging for each command I enter:

```
[INFO] Unable to bind key for unsupported operation: backward-delete-word
[INFO] Unable to bind key for unsupported operation: backward-delete-word
[INFO] Unable to bind key for unsupported operation: down-history
[INFO] Unable to bind key for unsupported operation: up-history
[INFO] Unable to bind key for unsupported operation: up-history
[INFO] Unable to bind key for unsupported operation: down-history
[INFO] Unable to bind key for unsupported operation: up-history
[INFO] Unable to bind key for unsupported operation: down-history
[INFO] Unable to bind key for unsupported operation: up-history
[INFO] Unable to bind key for unsupported operation: down-history
[INFO] Unable to bind key for unsupported operation: up-history
[INFO] Unable to bind key for unsupported operation: down-history
[INFO] Unable to bind key for unsupported operation: up-history
[INFO] Unable to bind key for unsupported operation: down-history
[INFO] Unable to bind key for unsupported operation: up-history
[INFO] Unable to bind key for unsupported operation: down-history
[INFO] Unable to bind key for unsupported operation: up-history
[INFO] Unable to bind key for unsupported operation: down-history
```

How do I remove it?

The answer to this [other question](http://stackoverflow.com/questions/13091617/getting-info-unable-to-bind-key-for-unsupported-operation-backward-delete-wo) makes me think that it is related to the jline library, that is used internally by SBT for reading input.

References: 
- [unanswered StackOverflow question](http://stackoverflow.com/questions/27823977/noise-logging-for-each-command-i-issue-in-sbt)

**Comment by jsuereth** [comment]
Do you have a `~/.jlinrc` file?  It's probably jline choking on that file.  I've never done that sort of customization, so I'm not sure.

Additionally, what platform?  For jline, this really matters.

**Comment by DavidPerezIngeniero** [comment]
I don't have any.
I'm using Linux.  I have dual boot with a shared /home folder.
- When using KUbuntu 14.10 no warnings are shown, 
- but when using OpenSuse 13.2, the warnings are shown.

**Comment by eed3si9n** [comment]
I'm guessing it's jline/jline2#73. Do you have `~/.inputrc` or `/etc/inputrc`?

**Comment by DavidPerezIngeniero** [comment]
After reinstalling my system, this problem has disappeared.
Thanks for your suggestions.
