### ISSUE TITLE
incremental compile dependency check is very slow

### ISSUE THREAD

**Issue by scroyston** [sbt/sbt#18]
Running the compile on a multi-project build with no changes is very slow (around 30+ seconds).

I ran yourkit on it, the patch below takes my time down to 1 second.

diff --git a/tasks/Execute.scala b/tasks/Execute.scala
index cc791ea..0158ba8 100644
--- a/tasks/Execute.scala
+++ b/tasks/Execute.scala
@@ -262,7 +262,7 @@ final class Execute[A[_] <: AnyRef](checkCycles: Boolean, triggers: Triggers[A])
                dependencies( node ) foreach { dep =>
                        def onOpt[T](o: Option[T])(f: T => Boolean) = o match { case None => false; case Some(x) => f(x) }
                        def checkForward = onOpt( forward.get(node) ) { _ contains dep }
-                       def checkReverse = onOpt( reverse.get(dep) ){ _.toSet contains node }
-                       def checkReverse = onOpt( reverse.get(dep) ){ lst => lst.exists(_ == node) }
                      assert( done(dep) ^ ( checkForward && checkReverse ) )
              }
      }

**Comment by scroyston** [comment]
Oops.  I was running from the wrong sub-project after the change.  It still cuts the time down to 10 seconds.

**Comment by scroyston** [comment]
Profiling again after the above change shows most of the time spent in SameAPI.  It looks like it's comparing all the "external" sources.  Shouldn't the stamps be checked first?

Thanks

**Comment by harrah** [comment]
That part of the code (in Execute) is only used for assertions.  You could also try disabling all assertions completely.  (In the build, change the argument to -Xelide-below to something like 3000).

What stamps are you talking about?

**Comment by scroyston** [comment]
The Source objects it seems to be checking are dependencies from my other sub-projects.  
Given that sbt already checked for changes in that dependent sub-project, it seems like sbt shouldn't have to to run through the SameAPI.apply to do the explicit check.  

I was looking at the Analysis class and saw the stamps, I assumed they were used to shortcut external dependency checks as well as internal, binary and product.  (But I now see they are not).

Does that make sense?  I'd really like to get the SameAPI checks down, as right now it's faster to do an old xsbt compile when nothing's changed...

I've been looking at wrapping the Source objects with a file hash to shortcut the checks, do you think that's a productive avenue?

Thanks again

**Comment by harrah** [comment]
The problem is that source file hashes are insufficient.  It is possible for a class file from the same source file to be different due to binary or source dependencies changing.  Source tracks this information.  Now, you could hash all class files that came from the source.  I think that will work.  I don't know how expensive that will be, though.

As for why it checks the api in other projects, consider projects A and B, with B depending on A.  B needs to know the Source for A when B was last compiled, not when A was last compiled.  It isn't important whether the source files for A have changed or not.  What is important is whether the Source has changed since the last time B was compiled.  Make sense?

If you are sure the API comparison is a bottleneck, we can probably generate a unique ID for each API when it's created and use that to shortcut things for the common case where the API hasn't changed at all.  If you want to look at doing this, let me know.  Otherwise, I'll do it.  Either way, thanks for the work you have done so far on this.

**Comment by scroyston** [comment]
Thanks, that makes a bit of sense.  I'll have to poke around a bit more to get my head around it completely.

I'm pretty sure that's the bottleneck, but I'll re-benchmark as soon as I finish porting the plugins I need.

Thanks again!

**Comment by ijuma** [comment]
In my case, it takes 7 seconds for a build with no changes. Scott, have you made any progress since your last message?

**Comment by scroyston** [comment]
I've started a branch playing around with some optimizations related to this and memory consumption, but haven't had time to touch it in awhile.  See:
https://github.com/harrah/xsbt/issues/21

**Comment by harrah** [comment]
The idea to uniquely identify APIs and shortcut the checking is a solid idea.  The main problem is figuring out how to generate the unique ID.  The best option I see so far is to combine the hash of the source with the time at which compilation was performed.  I will try to implement this today.

**Comment by ijuma** [comment]
Mark, did you notice any difference with this change? My initial testing shows no difference. I used a version I compiled myself from the v0.9.10 tag, but I'll try again later with the binary from the Maven repository. Btw, it seems like 0.9.10 is missing for the scripted plugin:

http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-tools.sbt/scripted-plugin_2.8.1/

**Comment by aolshevskiy** [comment]
Yeah, it's missing.

**Comment by harrah** [comment]
Ah, sorry.  I ran publish from the wrong subproject (Simple Build Tool instead of the root project).  I'd have to push a new release.  Is this worth it for you?

**Comment by aolshevskiy** [comment]
Sure, I'll build myself.

**Comment by harrah** [comment]
I've checked this out and as far as I can tell it is working properly.

**Comment by scroyston** [comment]
After fixing some weird build/sync issues.  My time has gone down on my laptop from ~10 seconds to 5-6 seconds.  (which is great!  I will take ~2x)

Looking at the remaining time, a bunch seems to be in sbinary writing stuff?  The call path is something like:
sbt.Tracked$$anonfun$inputChanged$1.apply(Object)
sbt.Tracked$$anonfun$lastOutput$1.apply(Object)
sbt.CacheIO$.toFile(Object, File, Format, Manifest)
