### ISSUE TITLE
sbt  ~run error (windows 8.1)

### ISSUE THREAD

**Issue by alisa-rend** [sbt/sbt#1809]
``` shell
name@PC-NAME:[~/projects/pl-scala]:                                                          
$ sbt  ~run                                                                                   
[info] Loading project definition from C:\Users\name\projects\pl-scala\project               
[info] Set current project to pl-scala (in build file:/C:/Users/name/projects/pl-scala/)     
[error] Expected key                                                                         
[error] Expected '*'                                                                         
[error] C:/Program Files (x86)/Git                                                           
[error]   ^                                                                                  
```

![](http://i.imgur.com/Z5eeMUF.png)

**Comment by eed3si9n** [comment]
Please follow [What to report](https://github.com/sbt/sbt/blob/0.13/CONTRIBUTING.md#what-to-report) and list out all environment that could be contributing to this behavior:
- how your sbt was installed
- what version of sbt
- list of your global settings and plugins
- your build

**Comment by alisa-rend** [comment]
Scala version 2.11.5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_7
sbt.version=0.13.5

**Comment by alisa-rend** [comment]
video -> http://a.pomf.se/aycalg.mp4

**Comment by eed3si9n** [comment]
Thanks for the video.
So `~run` works from the Activator shell, but 

```
$ sbt ~run
```

doesn't work on what seems to be Cygwin running with Bash.
Could it be [tilde expansion](http://www.gnu.org/software/bash/manual/bashref.html#Tilde-Expansion)? On my Mac and zsh I get 

```
$ sbt ~compile       
zsh: no such user or named directory: compile
```

but

```
$ sbt "~compile"
```

seems to work. Could you try with double quotes?

**Comment by alisa-rend** [comment]
nice!

@eed3si9n thanks!! :+1:
