### ISSUE TITLE
Unify sbt shell and build.sbt syntax

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#1812]
The sbt 0.13 shell syntax

```
{<build-uri>}<project-id>/config:intask::key
```

and sbt 0.13 build.sbt DSL syntax discrepancy makes learning curve steep. There has been several proposal of unifying the two. 

## idea 1: improve both shell notation and build.sbt syntax so they can be unified

```
> Test/compile
> Test/run foo
> root/IntegrationTest/testOnly x.y
> projectA/IntegrationTest/compile
```

<s>

## older idea: allow build.sbt expression in sbt shell

Things to consider are scoping and passing in input task arguments.

```
> compile in Test
> (run in Test).toTask(" foo")
```

This is not going to be usable.

## appendix: making Scala REPL the sbt shell

[consoleProject](http://www.scala-sbt.org/0.13/docs/Console-Project.html) is a useful experiment on what it's like to be to integrate REPL and sbt shell (idea 0). We will have to provide all the feature we currently provide via commands:
- [ ] Multi-project support. `project foo` is a command.
- [ ] Cross build support. `++2.11.5`
- [ ] Reload support.
- [ ] Delegation of tasks `compile` should work, not `compile in Compile`.
- [ ] `.eval` should be called automatically.
- [ ] Continuous execution support. `~compile`
- [ ] `last`
- [ ] `;foo;bar;`
</s>

**Comment by jsuereth** [comment]
I really like this idea.   Does this mean the Command engine disappears?  cosnoleProject is very much not compatible with it.

**Comment by jsuereth** [comment]
i.e. I think you need to add notes of `<command>` working and `<last>` etc.

**Comment by eed3si9n** [comment]
I don't know if we can get there in time. All I'm saying is that if people want to experiment with unified syntax, we already have `consoleProject`.

**Comment by eed3si9n** [comment]
The other direction @lihaoyi suggested is implementing REPL friendly Scala notation. I just tried implementing `:` method:

``` scala
scala> class Configuration  { def `:`(task: Any): Unit = () }
defined class Configuration

scala> val Test = new Configuration
Test: Configuration = Configuration@be633d8

scala> object compile
defined object compile

scala> Test:compile
<console>:14: error: not found: type compile
       Test:compile
            ^
```

so something other than `:`.

**Comment by dwijnand** [comment]
I don't think we can simultaneously change both syntaxes..

**Comment by eed3si9n** [comment]
We can use slash everywhere:

``` scala
scala> object Task { def value = ()  }
defined object Task

scala> class Configuration  { def /(task: Any) = Task }
defined class Configuration

scala> val Test = new Configuration
Test: Configuration = Configuration@10f54b9f

scala> val compile = Task
compile: Task.type = Task$@258382e8

scala> compile.value

scala> Test/compile
res1: Task.type = Task$@258382e8

scala> val x = (Test / compile).value
x: Unit = ()
```

This character is relatively easy to type, and the meaning is close enough.
We might need to introduce the notion of top-level `/` and current `./` to disambiguate between a configuration named `IntegrationTest` and a subproject that could be named `IntegrationTest`.

If we can implement this on top of the existing shell, we could even experiment during 0.13.x.
