### ISSUE TITLE
Resource limit for initialisation

### ISSUE THREAD

**Issue by wwaites** [sbt/sbt#1814]
I had to patch sbt-launch-lib.bash to make sbt run on the computing cluster at my school. The reason is that resources, memory in this case, are controlled and though sbt will itself start java with -Xmx512M by default which is perfectly acceptable, part of the startup routines attempt to call java on its own to detect the version. This meant changing the following line,

  java_version=$("$java_cmd" -version 2>&1 | awk -F '"' '/version/ {print $2}')

to

  java_version=$("$java_cmd" -Xmx512M -version 2>&1 | awk -F '"' '/version/ {print $2}')

It might be better to use the actual configured memory options rather than hard-coding a value here, but this does the trick for me.

I could not find this file in the source repository, otherwise I would send a pull request the normal way.

**Comment by dwijnand** [comment]
Here is what you want https://github.com/sbt/sbt-launcher-package/blob/1735b0b7ecd4636ce2890961024e015e74c1c2db/src/universal/bin/sbt-launch-lib.bash#L136

**Comment by jsuereth** [comment]
So, you should be reporting to teh sbt-launcher-package project.  However, check out:

https://github.com/sbt/sbt-launcher-package/blob/1735b0b7ecd4636ce2890961024e015e74c1c2db/src/universal/bin/sbt-launch-lib.bash#L188-L195

And

https://github.com/sbt/sbt-launcher-package/blob/1735b0b7ecd4636ce2890961024e015e74c1c2db/src/universal/bin/sbt-launch-lib.bash#L75-L92

If you want to fully fix the script, you'll most likely want ot change that second location....

**Comment by jsuereth** [comment]
I'm marking this "wontfix" in sbt/sbt and you can re-open in sbt-launcher.  Feel free to ping sbt-dev with more about your use-case if you'd like to discuss possible alternative solutions.
