### ISSUE TITLE
Can't use Scala 2.11 -Ywarn-unused-import because it trips up the initialCommands

### ISSUE THREAD

**Issue by deanwampler** [sbt/sbt#1815]
I'm trying to use the Scala 2.11 `-Ywarn-unused-import` option while compiling, but not in the console, where it effectively disables the ability to use most imports, especially in `initialCommands`.

Here's a sample `./project/Build.scala` file:

```
import sbt._
import sbt.Keys._

object MyBuild extends Build {
  import Resolvers._
  import BuildSettings._

  val commonScalacOptions = Vector("-deprecation", "-unchecked", "-feature",
        "-encoding", "utf8",
        "-Yno-adapted-args", "-Ywarn-dead-code",
        "-Ywarn-numeric-widen", "-Ywarn-value-discard")
  val compileScalacOptions = commonScalacOptions ++ Vector("-Ywarn-infer-any", "-Ywarn-unused-import")

  val scalaTest = "org.scalatest" %% "scalatest" % "2.2.1" % "test"

  lazy val myProject = Project(
    id = "SampleProject",
    base = file("."),
    settings = buildSettings ++ Seq(
      version      := "0.1.0",
      scalaVersion := "2.11.4",
      scalacOptions in Compile := compileScalacOptions,
      scalacOptions in console := commonScalacOptions,
      libraryDependencies ++= Seq(scalaTest)))
}
```

Here's a sample `./build.sbt`:

```
initialCommands += """
  import org.example.foo._
  """
```

Once I start sbt, I see the following:

```
> show *:console::scalacOptions
[info] Vector(-deprecation, -unchecked, -feature, -encoding, utf8, -Yno-adapted-args, -Ywarn-dead-code, -Ywarn-numeric-widen, -Ywarn-value-discard)
[success] Total time: 0 s, completed Jan 18, 2015 9:12:22 AM
> show compile:scalacOptions
[info] Vector(-deprecation, -unchecked, -feature, -encoding, utf8, -Yno-adapted-args, -Ywarn-dead-code, -Ywarn-numeric-widen, -Ywarn-value-discard, -Ywarn-infer-any, -Ywarn-unused-import)
```

But when I start the console, I get this:

```
> console
[info] Starting scala interpreter...
[info]
<console>:12: warning: Unused import
         import org.example.foo._
                                          ^
import org.example.foo._
Welcome to Scala version 2.11.4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0).
...
```

It appears that the full set of compile options are being used. Using `:power` and `:settings` confirms this.

On the mailing list, someone suggested adding `-Ywarn-unused-import:false` to the `scalacOptions in console`. However, this appears to have no benefit.

**Comment by dwijnand** [comment]
This is because console is actually `compile:console`, see http://stackoverflow.com/questions/26940253/in-sbt-how-do-you-override-scalacoptions-for-console-in-all-configurations

**Comment by deanwampler** [comment]
I now and that's the problem. It should be overridable.

**Comment by deanwampler** [comment]
Okay, it looks like 

```
scalacOptions in (Compile, console) := Seq(... without -Ywarn-unused-imports...)
```

does work, so I'll close this. However, it would be nice if  

```
scalacOptions in console := Seq(... without -Ywarn-unused-imports...)
```

were flagged as a no-op.

**Comment by som-snytt** [comment]
It sure is nice having config in Scala, because if it compiles, it just works.

**Comment by jsuereth** [comment]
@deanwampler There's a feature request for that.  The issue with flagging it as a no-op was the false-alarm rate was super-high.   I'll talk with @havocp to see if we can revive the branch.

**Comment by dwijnand** [comment]
Warning no-ops aside, I think `scalacOptions in console` should do what it says on the tin.
