### ISSUE TITLE
sbt fails to correctly determine binary compatibility for scala-actors-migration

### ISSUE THREAD

**Issue by sgronblo** [sbt/sbt#1818]
I am trying to get rid of a warning I am getting when using the SBT plugin in Intellij.

```
[warn] Binary version (1.1.0) for dependency org.scala-lang#scala-actors-migration_2.11;1.1.0
[warn] in org.company.package#rd$sources_javadoc_2.11;1.0 differs from Scala binary version in project (2.11).
```

I am still researching the problem, but I just wanted to put this up quickly and see if anyone has any idea what's going on. Judging by the patterns `CrossversionUtil.scalaApiVersion` it seems that SBT always expects the version to contain the full semantic version as a substring of the dependency name but in this case we seem to oddly have `2.11;1.1.0`. Any ideas?

**Comment by jsuereth** [comment]
WE hardcode the binary version detection to "org.scala-lang". i.e. we assume all "org.scala-lang" JARS should have the same version, while "org.scala-lang.modules" are things which have regular sbt cross-version semantics.    Actors Migration appears to be neither of these, so there's not a lot we can do without special casing actors-migration..   THe warning is erronous, so thanks for the report!
