### ISSUE TITLE
There should be an error when scalaVersion conflicts with a dependencies scala-library requirement

### ISSUE THREAD

**Issue by sgronblo** [sbt/sbt#1819]
Today I spent many hours debugging why Intellij stopped being able able to set the Scala SDK for subprojects in a multi-project configuration.

In the end it turned out that we had set scalaVersion to 2.11.2 while ScalikeJDBC 2.2.0 (which we were using) had a dependency on scala-library 2.11.4

Is this something that SBT should be raising an error for or would this be an Intellij Scala plugin problem?

**Comment by jsuereth** [comment]
which version of sbt?   You should be getting warnings in 0.13.7.

**Comment by sgronblo** [comment]
It seems we were setting sbt.version to 0.13.5 in our build.properties. I tried upping it to 0.13.7 and then I can actually see warnings that the scalaVersion got increased. Unfortunately the message is vague and doesn't mention the exact library that caused the scalaVersion to be updated. That would be a very useful addition. Additionally when using sbt 0.13.7, the Scala plugin seems to pick up the Scala SDK version correctly. Even setting it to different versions for different modules.

**Comment by jsuereth** [comment]
interesting.   BTW - have you seen `show update` or hte update reports we generate?

Also `evicted` should dump a report of evicted libraries and "callers" which should show you at least what libraries depend on scala (one of them caused the bump, but we actually don't' remember who caused the bump during resolution, we only unify the dependency node to the latest version).

**Comment by sgronblo** [comment]
`show update`? I'm a quite new sbt user and I am trying to maximize the amount of work I can get done from inside of Intellij.

Could you add a feature that retains at least one or all of the dependencies that caused the bump? It sounds like it could be useful so you don't need to go through the dependencies manually to check it.

**Comment by eed3si9n** [comment]
I'm glad eviction warning (#1201) is doing at least some of the jobs raised in the original issue.
I think it already says:

```
[warn] Run 'evicted' to see detailed eviction warnings
```

We can print more stuff, but we also get lots of complaints that eviction warnings are too loud, so we can't please everyone. I guess it's useful the first time you find out, but after a while it gets old.
Can we close this issue, as far as the Scala version thing is concerned?

As per better integration with IDEs, we are working on sbt server, and that should bring tighter integration with tools like IntelliJ and Activator UI mode.

**Comment by sgronblo** [comment]
Yeah I'm ok with closing it. It seems I was just using a too old version of SBT.
