### ISSUE TITLE
Extra logger doesn't catch all log messages (SBT v >= 0.13.6)

### ISSUE THREAD

**Issue by shkate** [sbt/sbt#1822]
We have a small plugin that register extra loggers to wrap SBT log messages in a way TeamCity (JetBrains CI solution) can catch them. 
The source code is here and it is really very simple: https://github.com/JetBrains/sbt-tc-logger
Extra logger is registered here: https://github.com/JetBrains/sbt-tc-logger/blob/master/logger/src/main/scala/jetbrains/buildServer/SbtTeamCityLogger.scala

For SBT v 0.13.0 - 0.13.5 it works perfectly. For sample project (https://github.com/JetBrains/sbt-tc-logger/tree/master/test/testdata/compileerror) the output was like this:

```
[info] Loading global plugins from /Users/shkate/Work/sbt-tc-logger/test/sbt/plugins
[info] Loading project definition from /Users/shkate/Work/sbt-tc-logger/test/testdata/compileerror/project
##teamcity[compilationStarted compiler='Scala compiler']
[info] Updating {file:/Users/shkate/Work/sbt-tc-logger/test/testdata/compileerror/project/}compileerror-build...
--> TCLogger (extra logger) catches: info - Updating {file:/Users/shkate/Work/sbt-tc-logger/test/testdata/compileerror/project/}compileerror-build...
##teamcity[message status='NORMAL' flowId='29' text='Updating {file:/Users/shkate/Work/sbt-tc-logger/test/testdata/compileerror/project/}compileerror-build...']
--> TCLogger (extra logger) catches: debug - Other repositories:
--> TCLogger (extra logger) catches: debug -    FileRepository(publish-m2-
(a lot of debug messages goes here - resolving, this, that, really huge amount)
--> TCLogger (extra logger) catches: info - Resolving org.scala-sbt#control;0.13.5 ...
--> TCLogger (extra logger) catches: info - Done updating.
##teamcity[message status='NORMAL' flowId='39' text='Done updating.']
--> TCLogger (extra logger) catches: info - Compiling 1 Scala source to /Users/shkate/Work/sbt-tc-logger/test/testdata/compileerror/target/scala-2.10/classes...
##teamcity[message status='NORMAL' flowId='40' text='Compiling 1 Scala source to /Users/shkate/Work/sbt-tc-logger/test/testdata/compileerror/target/scala-2.10/classes...']
--> TCLogger (extra logger) catches: error -   def main(args: Array[String]) = 123println("Hi!")
##teamcity[message status='ERROR' flowId='40' text='  def main(args: Array|[String|]) = 123println("Hi!")']
[error]                                   ^
--> TCLogger (extra logger) catches: error -                                   ^
##teamcity[message status='ERROR' flowId='40' text='                                  ^']
[error] one error found
--> TCLogger (extra logger) catches: error - one error found
##teamcity[message status='ERROR' flowId='40' text='one error found']
--> TCLogger (extra logger) catches: debug - Compilation failed (CompilerInterface)
##teamcity[compilationFinished compiler='Scala compiler']
[error] (compile:compile) Compilation failed
--> TCLogger (extra logger) catches: error - (compile:compile) Compilation failed
##teamcity[message status='ERROR' flowId='1' text='(compile:compile) Compilation failed']
[error] Total time: 1 s, completed Jan 21, 2015 12:08:55 PM
```

As soon as I set the SBT version for my sample project the output lacks of any log messages other then debug.

```
[info] Loading global plugins from /Users/shkate/Work/sbt-tc-logger/test/sbt/plugins
[info] Loading project definition from /Users/shkate/Work/sbt-tc-logger/test/testdata/compileerror/project
##teamcity[compilationStarted compiler='Scala compiler']
--> TCLogger (extra logger) catches: debug - Initial source changes: ...
--> TCLogger (extra logger) catches: debug - All initially invalidated sources: Set()
##teamcity[compilationFinished compiler='Scala compiler']
--> TCLogger (extra logger) catches: debug - Copy resource mappings: 

[info] Set current project to compileerror (in build file:/Users/shkate/Work/sbt-tc-logger/test/testdata/compileerror/)
[info] Compiling 1 Scala source to /Users/shkate/Work/sbt-tc-logger/test/testdata/compileerror/target/scala-2.10/classes...
[error] /Users/shkate/Work/sbt-tc-logger/test/testdata/compileerror/hw.scala:19: Invalid literal number
[error]   def main(args: Array[String]) = 123println("Hi!")
[error]                                   ^
[error] one error found
[error] (compile:compile) Compilation failed
[error] Total time: 1 s, completed Jan 21, 2015 12:04:43 PM
```

(The line  println("--> TCLogger (extra logger) catches: " + level + " - " + message) in TCLogger.log is not in version control, I've added it only locally just to simplify result presentation)

Should I change something in my code? Or it is kind of a bug in SBT? Any your ideas are highly appreciated.

**Comment by eed3si9n** [comment]
> As soon as I set the SBT version for my sample project the output lacks of any log messages other then debug.

If debug message works, but nothing else, there may be two reasons. sbt's log somehow changed its behavior, or the log is no longer listening to what used to produce log messages. What's interesting about debug, however, is that [TCLogger.scala](https://github.com/JetBrains/sbt-tc-logger/blob/f9c6360f07b5d9ffa10afddfa1a64428dbfd33b2/logger/src/main/scala/jetbrains/buildServer/TCLogger.scala#L30-L39) says it's not listening to them.

## Reproducing the problem

I'm having trouble reproducing the problem. Here are my steps.

```
$ cat project/build.properties 
sbt.version=0.13.1
$ cat project/plugin.sbt      
resolvers += Resolver.url("sbt-plugin-snapshots", new URL("http://repo.scala-sbt.org/scalasbt/sbt-plugin-snapshots/"))(Resolver.ivyStylePatterns)

addSbtPlugin("org.jetbrains" % "sbt-teamcity-logger" % "0.1.0-SNAPSHOT")
$ cat build.sbt 
lazy val root = (project in file("."))
$ env TEAMCITY_VERSION=1.0 sbt compile
....
##teamcity[compilationStarted compiler='Scala compiler']
[info] Updating {file:/xxx/sbt-1822/}root...
##teamcity[message status='NORMAL' flowId='52' text='Updating {file:/xxx/sbt-1822/}root...']
##teamcity[message status='NORMAL' flowId='52' text='Other repositories:']
....
```

So that works for sbt 0.13.1. Now let's change this to sbt 0.13.7.

```
$ echo "sbt.version=0.13.7" > project/build.properties 
$ cat project/build.properties 
sbt.version=0.13.7
$ env TEAMCITY_VERSION=1.0 sbt compile
....
##teamcity[compilationStarted compiler='Scala compiler']
[info] Updating {file:/xxx/sbt-1822/}root...
##teamcity[message status='NORMAL' flowId='57' text='Updating {file:/xxx/sbt-1822/}root...']
##teamcity[message status='NORMAL' flowId='57' text='Other repositories:']
....
```

What am I missing here?

## Avoid overriding settings

Since I can't reproduce the issue this may or may not be relevant to this discussion, but looking at the code, I thought the way `settings` are used in `SbtTeamCityLogger` is problematic.

``` scala
  override lazy val settings = if (tcFound) loggerOnSettings else loggerOffSettings

   lazy val loggerOnSettings =  Seq(
        commands += tcLoggerStatusCommand,
        testListeners += tcTestListener,
        extraLoggers := {
          val currentFunction = extraLoggers.value
          (key: ScopedKey[_]) => {
            tcLogger +: currentFunction(key)
          }
        },
        startCompilationLogger := {
             tcLogAppender.compilationBlockStart()
        },
        startTestCompilationLogger := {
             tcLogAppender.compilationTestBlockStart()
        },
        compile in Compile <<= ((compile in Compile) dependsOn startCompilationLogger)
          andFinally {tcLogAppender.compilationBlockEnd()},

        compile in Test <<= ((compile in Test) dependsOn startTestCompilationLogger)
               andFinally {tcLogAppender.compilationTestBlockEnd()}
  )
```

sbt has always discouraged plugin authors from using `settings` directly.
"Avoid overriding settings" was the first item on [Plugins Best Practices](http://www.scala-sbt.org/0.13.0/docs/Extending/Plugins-Best-Practices.html) for sbt 0.13.0:

> sbt will automatically load your plugin's settings into the build. Overriding val settings should only be done by plugins intending to provide commands. Regular plugins defining tasks and settings should provide a sequence named after the plugin

Prior to sbt 0.13.5, our recommendation for plugin that wants to change the behavior of `compile in Compile` would be to come up with a custom setting sequence.
For sbt 0.13.5+, the recommended approach would be to use auto plugins, which puts the projectSettings at the right place. Auto plugins are much less invasive on build.sbt, so it should suit your needs here.

**Comment by shkate** [comment]
Thank you for your comments. Regarding "TCLogger.scala says it's not listening to them" - I've changed it locally, so it was listening. 
I will try to figure out what to do with auto plugin in my case. Thank you to pointing me there. Maybe you know some projects which use extra loggers? It would be really helpful to take a look on them.

**Comment by eed3si9n** [comment]
> Regarding "TCLogger.scala says it's not listening to them" - I've changed it locally, so it was listening.

Could you clarify what you mean? Do you still suspect that there's some issue with sbt, or it's now resolved?

> Maybe you know some projects which use extra loggers?

I just did a Github search on [extraLoggers and found many hits](https://github.com/search?l=scala&q=extraLoggers&type=Code). Hope this helps!

**Comment by shkate** [comment]
I've just found the problem was not in extra logger itself but in a way how the plugin was registered. We've added it as a jar we put in /plugins folder. And before sbt 0.13.6 it worked. And then occasionally stopped.  It was my fault not to check this option. But as far as some log messages appeared in our logger it didn't come to my mind. If I add plugin the way you did - it works.
So I can say for sure that there is no problem with extra loggers, could you please close this issue? 
What I faced was related to plugin itself (or its assembly) and its registration as a global plugin. I am not an experienced user of SBT so I will try to check everything one more time and if I will be able to describe the situation we met - I will back to you.
Also I will update the plugin and use AutoPlugin as you advised.
Thank you for you help! And sorry for bothering you :)

**Comment by eed3si9n** [comment]
No problem. Good luck.
