### ISSUE TITLE
Mixed java/scala project build

### ISSUE THREAD

**Issue by apathanrb** [sbt/sbt#1826]
I have an existing Java project with Ant build that I am trying to set up to build with mixed source (Java and Scala).

I hava a Java interface defined as - `public interface One<T extends Two<? super T>>` that when I run scalac from Ant build, I get the following error at `<? super T>`:

```
error: illegal cyclic reference involving type T.
```

Since I want the Scala and Java class to be inter-dependent in my project, I first run the scalac task before running javac in the Ant build. My scalac block looks as follows:

```
<scalac srcdir="${src.path}" destdir="${build.classes}" encoding="UTF-8" >
            <classpath refid="compile.classpath" />
            <include name="**/*.scala"/>
            <include name="**/*.java"/>
</scalac> 
```

Is there any way getting around this; I can't modify the Java code since there is tons of other code that uses it. 

I am using Java 7 and Scala 2.11.5

**Comment by eed3si9n** [comment]
Is this an Ant question? This is an issue tracker for sbt.

**Comment by apathanrb** [comment]
Actually it is a scalac issue which is still open; See my stackoverflow issue at http://stackoverflow.com/questions/28158173/building-a-project-with-mixed-scala-and-java-source-files-using-ant-illegal-cy
