### ISSUE TITLE
Better crossScalaVersions default behavior

### ISSUE THREAD

**Issue by pauldraper** [sbt/sbt#1828]
**build.sbt**

``` scala
scalaVersion := "2.11.4"
```

**project/build.properties**

```
sbt.version=0.12.4
```

Then

``` bash
$ sbt 'show scalaVersion'
[info] 2.11.4
$ sbt 'show crossScalaVersions'
[info] List(2.11.4)
```

---

**build.sbt**

``` scala
scalaVersion := "2.11.4"
```

**project/build.properties**

```
sbt.version=0.13.7
```

Then

``` bash
$ sbt 'show scalaVersion'
[info] 2.11.4
$ sbt 'show crossScalaVersions'
[info] List(2.10.4)
```

---

It seems that the default behavior for `crossScalaVersions` was better in 0.12. Is there a deliberate reason this changed?

**Comment by eed3si9n** [comment]
I'd say this is a regression. You can find out why this is happening by running inspect:

```
root> inspect crossScalaVersions
[info] Setting: scala.collection.Seq[java.lang.String] = List(2.10.4)
[info] Description:
[info]  The versions of Scala used when cross-building.
[info] Provided by:
[info]  */*:crossScalaVersions
[info] Defined at:
[info]  (sbt.Defaults) Defaults.scala:237
[info] Delegates:
[info]  *:crossScalaVersions
[info]  {.}/*:crossScalaVersions
[info]  */*:crossScalaVersions
[info] Related:
[info]  */*:crossScalaVersions
```

`crossScalaVersions` isn't defined at the project level, so it delegated to `crossScalaVersions in Global`, which uses `scalaVersion in Global`. We can probably define something at the project level that checks if `scalaVersion` has been rewired.

**Comment by dwijnand** [comment]
I'd love this to be fixed. But I'm having difficulty finding where and how to do what you describe above. If you have any more ideas I'll be happy to try and make a pull request for this change. Thanks.

**Comment by dwijnand** [comment]
Scratch that, I found something that seems to work, see linked PR.
