### ISSUE TITLE
Wrong properties file name in error message

### ISSUE THREAD

**Issue by waywardmonkeys** [sbt/sbt#183]
When I'm loading a custom Launcher properties file via the @ syntax on the command line, the error messages give the incorrect file name.

I get this:

> Error during sbt execution: No scala.version specified in
> /Users/bruce/Development/foopy/project/build.properties10

I should have gotten:

> Error during sbt execution: No scala.version specified in
> /Users/bruce/Development/foopy/.sbt/sbt.boot.properties

(From my thread on the list about running side-by-side 0.7 and 0.11 builds.)

**Comment by harrah** [comment]
Please post the contents of project/build.properties10 and .sbt/sbt.boot.properties.  It isn't obvious that the error message is wrong.

**Comment by waywardmonkeys** [comment]
.sbt/sbt.boot.properties:

```
[scala]
  version: 2.9.1

[app]
  org: org.scala-tools.sbt
  name: sbt
  version: read(sbt.version)[0.11.0-RC1]
  class: ${sbt.main.class-sbt.xMain}
  components: xsbti,extra
  cross-versioned: true

[repositories]
  local
  maven-local
  typesafe-ivy-releases: http://repo.typesafe.com/typesafe/ivy-releases/, [organization]/[module]/[revision]/[type]s/[artifact](-[classifier]).[ext]
  maven-central
  scala-tools-releases
  scala-tools-snapshots

[boot]
  directory: ${sbt.boot.directory-project/boot/}
  properties: project/build.properties10

[ivy]
  ivy-home: ${sbt.ivy.home-${user.home}/.ivy2/}
```

project/build.properties10:

```
sbt.version=0.11.0-RC1
```

Get rid of the [scala] block and you'll get the error with the wrong filename.

**Comment by harrah** [comment]
The error message is correct.  When no `[scala]` section is provided, the default is to look in the properties file for a `scala.version` property. 

So, obviously I simplified my answer on the mailing list.  Some things have hard coded defaults, but in practice, it is not very flexible and each property should be explicitly specified.

**Comment by waywardmonkeys** [comment]
I'd tried putting a scala.version in the build.properties10 as well I think and it didn't work ... but I may be remembering wrong.
