### ISSUE TITLE
`<developers>` section is not rendered correctly in the pom.xml

### ISSUE THREAD

**Issue by OlegIlyenko** [sbt/sbt#1834]
This change introduced the bug:

https://github.com/sbt/sbt/commit/183c2bcfe2a84295deea82eed2179a72c50289cc#diff-6e0d918801855e22733193038a712c35R108

The output in pom.xml looks like this:

```
<developers> moduleInfo.developers.map&lt;function1&gt; </developers>
```

**Comment by jozic** [comment]
+1

**Comment by jozic** [comment]
I see this still happening with 0.13.8. Is this part of 0.13.9?

**Comment by dwijnand** [comment]
It's part of what will be 0.13.9.

**Comment by jozic** [comment]
got it, milestone set to 0.13.8 confused me

**Comment by eed3si9n** [comment]
Fixed the milestone.
