### ISSUE TITLE
"completions" command prevents completion of "compile"

### ISSUE THREAD

**Issue by jozic** [sbt/sbt#1835]
Small usability issue I'v talked with @eed3si9n today about

in sbt if you type "comp" and hit tab, it shows you available completions where all except one ("completions") start with "compile".
Renaming "completions" to something like "showCompletions" will make completion mechanism to stop on "compile" which is a much widely used task as opposed to "completions" 

can go to 1.0 as a braking change :)

**Comment by eed3si9n** [comment]
You can try @MasseGuillaume's [sbt-alias](https://github.com/MasseGuillaume/sbt-alias), or make up your own aliases by creating `~/.sbt/0.13/alias.sbt`:

``` scala
addCommandAlias("c", "compile")
```

**Comment by dwijnand** [comment]
I think you can also alias it in ~/.sbtrc as described in http://www.scala-sbt.org/0.13/docs/Best-Practices.html as such:

```
alias c = compile
```

**Comment by jozic** [comment]
sure, that's the first thing i thought about
it's not a problem for me as of now, but no workaround is better than any good workaround :)
