### ISSUE TITLE
sbt-launcher fails to detach session when launching services

### ISSUE THREAD

**Issue by jsuereth** [sbt/sbt#1838]
When sbt-launcher launches a server we fail to call `setsid` in linux, leading to any signal passed to the client also reaching the server.    We should properly daemonize.

On linux, this should be as simple as checking for a utility called `setsid` on the command line and using this to fork the server process.

See: http://bytes.com/topic/java/answers/528276-subject-detach-daemon

**Comment by eed3si9n** [comment]
Not likely relevant since we don't use the feature.
