### ISSUE TITLE
SBT publishes inconsistent ivy.xml

### ISSUE THREAD

**Issue by matthughes** [sbt/sbt#1839]
Running with 0.13.7 final.

I've been trying to track down an issue where products downstream of mine don't see the upstream library.

I believe I've tracked it down to the publishing of the main artifact's ivy.xml file.  It is completely inconsistent.  I wrote a script that runs in a loop:

```
sbt ";clean;publishLocal"
cat ~/.ivy/my/artifact/ivys/ivy.xml | grep artifact
```

Half the time, the JAR gets added to the file; half it is not.   I have no other SBT builds running.  I have no plugins installed.  If the artifact isn't listed there, the downstream project seems to quietly omit it from the classpath.  The downstream project _resolves_ the artifact, but since there is no artifact with type=jar listed, it doesn't show up on the classpath.

**Comment by jsuereth** [comment]
Can you let us know what plugins you may be using, or is this on any generic project?

**Comment by matthughes** [comment]
```
    sbt.plugins.IvyPlugin: enabled in core
    sbt.plugins.JvmPlugin: enabled in project
    sbt.plugins.CorePlugin: enabled in project
    sbt.plugins.JUnitXmlReportPlugin: enabled in project
```

Plus some company plugins.  I'm going to try and disable them one by one and see if I can't find the culprit.  Creating a completely empty project, I'm unable to reproduce.

**Comment by matthughes** [comment]
@jsuereth Problem appears to be an AutoPlugin that is setting `artifacts` and `publishArtifacts` in their own configuration.  

It seems like the default configuration which sets the main jar/sources artifacts flip flops with my custom configuration that right now products no artifacts.  I'd be happy to send you the gist privately.

The real problem that I'm trying to solve is to _conditionally_ attach artifacts to the build.  addArtifact works when you have a task that definitely produces an artifact; but my task might not depending on how the project is set up.

**Comment by eed3si9n** [comment]
> @jsuereth Problem appears to be an AutoPlugin that is setting artifacts and publishArtifacts in their own configuration.

Is this one of your company plugins? Does it depend on `JvmPlugin` so the setting comes after our default values?

> The real problem that I'm trying to solve is to conditionally attach artifacts to the build. 

You can take a look at the implementation of `addArtifact` and conditionally add things to `artifacts` and `packagedArtifacts`.

**Comment by matthughes** [comment]
Here's a reproduction of the bug: https://github.com/matthughes/sbt-artifact-bug

https://github.com/matthughes/sbt-artifact-bug/blob/master/the-plugin/src/main/scala/TestPlugin.scala

**Comment by SethTisue** [comment]
seems like one we could just close at this point — unless someone steps forward and says it's still reproducible and still a concern

**Comment by eed3si9n** [comment]
Yea, it's unclear if this is really an sbt issue or the plugin issue.
Closing as won't fix.
