### ISSUE TITLE
Improve docs on VC ignore list

### ISSUE THREAD

**Issue by fernandezpablo85** [sbt/sbt#184]
The wikipage talks about ignoring

```
target/
project/boot/
```

Actually in project there is also

```
project/target
```

Which contains a bunch of autogenerated stuff. This should be ignored too IMHO.

On the **#scala** channel some folks seemed to be adding:

```
project/plugins/build.sbt
```

To their VC system, but this is somewhat advanced (if you know how to use plugins, you know you have to defined them there, ergo you might consider versioning that file too).

I'd change the wiki to state that anything under /project can be safely ignored until you start using plugins or other advanced stuff that I'm not taking into consideration right now.

**Comment by harrah** [comment]
The wiki is correct.  In a `.gitignore` file, the `target/` says `project/target/` should be ignored as well.  It is not correct that the `project/` directory should be ignored by default.  Please use the mailing list if you have questions.
