### ISSUE TITLE
Add "macro" dependency configuration

### ISSUE THREAD

**Issue by jedesah** [sbt/sbt#1848]
Apologies if this already exists or was already discussed, but I was unable to find anything that discusses it.

I am writing a library that essentially consists of a macro. I would like to use some cool libraries like shapeless, scalaz, spire to implement the macro. If I do this however, my clients will then transitively depend on these libraries even though they don't actually need these libraries at runtime (they need them to compile their code though).

It would be nice if sbt could be made aware of this and was able to add such a dependency to the classpath of the client project during compilation but not during runtime (or in the published jar). This would make it easier for a macro writer to use cool libraries for the implementation of the macro that are not required by the code produced by the macro.

Does this make sense?

**Comment by eed3si9n** [comment]
Do you think `% Provided` would work?

**Comment by jedesah** [comment]
Yes, I think that `% Provided` should do. Thx for answering what amounted to a question I suppose. Sorry for creating noise on the issue tracker.
