### ISSUE TITLE
SBT ingores the HTTP_PROXY or HTTPS_PROXY on win7

### ISSUE THREAD

**Issue by hansgru** [sbt/sbt#1852]
SBT seems to ignore the `HTTP_PROXY` or `HTTPS_PROXY` on Windows 7.
and `-Dhttp.proxyHost=host -Dhttp.proxyPort=8080`  too (if done in sbt.bat)
so it's not working behind proxies.

**Comment by hansgru** [comment]
IMO this is a critical issue.

As a note, I would like to mention that all other build tools work behind that proxy (or other similar proxies that companies use): Maven, NPM, Bower, Gradle, Grails, Lein. Also the installed Curl, Wget and Git work too.

SBT is the only tool that doesn't like to play nicely.

**Comment by jsuereth** [comment]
there is an sbtconfig.txt file (check your start menu for location) where you can put the -D variables, which should work.  YOu may be missing the -Dhttps.proxy\* variables, as by default we use https repositories.

as far as HTTP_PROXY and HTTPS_PROXY, I agree we should support that. I believe there's already another open ticket.

**Comment by hansgru** [comment]
> there is an sbtconfig.txt file (check your start menu for location) where you can put the -D variables, which should work. YOu may be missing the -Dhttps.proxy\* variables, as by default we use https repositories.

I tried those of course too, but they're not working :(.
I was trying to build e.g. this Scala (SBT) project: https://github.com/takezoe/gitbucket

but I'm getting at best: 

```
.....
[info] downloading http://repo1.maven.org/maven2/org/specs2/specs2_2.11/2.3.12/specs2_2.11-2.3.12.jar ...
[warn]  [FAILED     ] org.specs2#specs2_2.11;2.3.12!specs2_2.11.jar: Connection reset (261ms)
[warn]  [FAILED     ] org.specs2#specs2_2.11;2.3.12!specs2_2.11.jar:  (0ms)
[warn] ==== local: tried
[warn]   C:\Users\xxxxx\.ivy2\local\org.specs2\specs2_2.11\2.3.12\jars\specs2_2.11.jar
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/org/specs2/specs2_2.11/2.3.12/specs2_2.11-2.3.12.jar
.....
```

Of course, I can reach the above URL, get it with curl/wget/maven, etc.

**Comment by eed3si9n** [comment]
Could you try running

```
eval sys.props("http.proxyHost")
```

From the sbt shell to see if the setting is actually passed on?

**Comment by hansgru** [comment]
@eed3si9n 
Yes, the setting is passed on:

```
> eval sys.props("http.proxyHost")
[info] ans: String = xx.xxx.xxx.xxx
```

and the value is correct. The same for:

```
"https.proxyHost"
```

**Comment by hansgru** [comment]
Any news on this? Is there any script that I could run or extra log files that I could send you to help pinpoint/trace the problem?

I'm having this problem at 3 different customers in their intranet with their own hardware.

**Comment by antoniocali** [comment]
Still have same issue here.
Always get a connection timed out because proxy

**Comment by OpsRJ** [comment]
Same here...

**Comment by murisly** [comment]
same here

**Comment by pJunger** [comment]
And same here.

**Comment by alelk** [comment]
+1

**Comment by eed3si9n** [comment]
As far as I know sbt 0.13 does respect the HTTP_PROXY, and sbt 1 works for HTTP only, which is tracked by https://github.com/sbt/sbt/issues/4307, so I am closing this issue for now.
