### ISSUE TITLE
Outdated documentation on website

### ISSUE THREAD

**Issue by benmccann** [sbt/sbt#1854]
I wanted to fix this page:
http://www.scala-sbt.org/0.13/tutorial/Installing-sbt-on-Linux.html

Turns out it was fixed five months ago:
https://github.com/sbt/website/commit/37ce347144dfd4370b5d71b33c69ab57d8f2bfb9

Can we get a new version of the website published?

**Comment by eed3si9n** [comment]
I think the website is up to date.
The commit you link to is for http://www.scala-sbt.org/download.html

**Comment by benmccann** [comment]
@eed3si9n both the page you linked to and the one I linked to have `http` on it. That doesn't seem right since the commit I linked to changed `http` to `https` everywhere. I really don't think that the website does match the code

**Comment by eed3si9n** [comment]
The download page does some architecture detection, so there may be some bug, but I'm sure whatever we have on the site is based on the latest commit that added new skin: https://github.com/sbt/website/commit/8e88215fd33bb2f1398e10b040a5267465109447

**Comment by eed3si9n** [comment]
The Ubuntu instruction still has http in the latest - https://github.com/sbt/website/blob/8e88215fd33bb2f1398e10b040a5267465109447/src/tutorial/01-Setup/c.md

**Comment by benmccann** [comment]
Ah, thanks. GitHub was giving me an old version and I didn't realize it. Just submitted a PR

https://github.com/sbt/website/pull/102
