### ISSUE TITLE
CustomPomParser produces unparsable ivy descriptor when POM has a parent

### ISSUE THREAD

**Issue by chasebradford** [sbt/sbt#1856]
#1191 is closed, so I'm opening this because it's still an issue.

If a child POM has a parent section, the transformed child will have an e:sbtTransformHash tag without the corresponding namespace declaration.

Here's why:
- The parent POM is processed and addExtra is used.  This adds e:sbtTransformHash to its extraInfo and adds the extra namespace
- Ivy's PomModuleDescriptorParser adds the parent's extra info to the child before finishing parseDescriptor
- CustomPomParser begins transforming the child module, but it already has the sbtTransformHash tag, so it skips addExtra

Because addExtra is never run on the child module, the child is left with the extraInfo sbtTransformHash tag but never gets the addExtraNamespace.

**Comment by eed3si9n** [comment]
Thanks for doing the leg work on this.

**Comment by jsuereth** [comment]
@chasebradford As an aside, if you use the new maven resolver, does the problem show up?   see: https://github.com/sbt/sbt/blob/0.13/notes/0.13.8.markdown#maven-resolver-plugin for how to set it up with sbt 0.13.8-M5.

I'm thinking we may need to deprecate and remove Ivy's inbred maven integration in favor of the Aether work sooner rather than later....

**Comment by chasebradford** [comment]
@jsuereth I get many "Failed to read descriptor dependency" errors when I add the plugin.

Here's my project/Build.scala.  The error reproduces very easily with this bare minimum project.

```
import sbt._
import Keys._
object TestBuild extends Build {
  lazy val Deps = Project("Deps", file("deps")).settings(
    libraryDependencies += "org.apache.hadoop" % "hadoop-mapreduce-client-jobclient" % "2.5.0-cdh5.3.0",
    resolvers += "Cloudera" at "https://repository.cloudera.com/artifactory/cloudera-repos/"
  )
  lazy val root = Project("root", file(".")).dependsOn(Deps)
}
```
