### ISSUE TITLE
build.sbt can't have projects with the same base directory

### ISSUE THREAD

**Issue by pauldraper** [sbt/sbt#1861]
This `Build.scala` has two projects:

``` scala
object AppBuild extends Build {
  lazy val foo = Project("foo", file(".")).settings(target := baseDirectory.value / "foo-target")
  lazy val bar = Project("bar", file(".")).settings(target := baseDirectory.value / "bar-target")
}
```

but this `build.sbt` results in only one (`bar`):

``` scala
lazy val foo = Project("foo", file(".")).settings(target := baseDirectory.value / "foo-target")
lazy val bar = Project("bar", file(".")).settings(target := baseDirectory.value / "bar-target")
```

Perhaps this is intended. I never have been crystal clear on the .sbt peculiarities.

**Comment by eed3si9n** [comment]
This is I think intentional because we need to refer to subprojects defined in other `*.sbt` using `Project("foo", file("."))` too. Generally all subprojects should have different base directory to avoid caching errors.
