### ISSUE TITLE
aspectjtools.jar hides Play definition when imported

### ISSUE THREAD

**Issue by wsargent** [sbt/sbt#1863]
If you import aspectj into your Play project:

```
addSbtPlugin("com.typesafe.sbt" % "sbt-aspectj" % "0.10.0")
```

Then the aspectjtools jar happens to have a Play class in the root package -- and a build.sbt uses the root package as well, and then auto imports all the auto plugins, meaning the following error shows up:

```
build.sbt:0: warning: imported `Play' is permanently hidden by definition of object Play"
```

**Comment by eed3si9n** [comment]
I was able to reproduce the situation:

```
/Users/eugene/work/play-scala/build.sbt:0: warning: imported `Play' is permanently hidden by definition of object Play
import _root_.sbt.plugins.IvyPlugin, _root_.sbt.plugins.JvmPlugin, _root_.sbt.plugins.CorePlugin, _root_.sbt.plugins.JUnitXmlReportPlugin, _root_.sbtmeow.SbtMeowPlugin, _root_.sbtsh.ShPlugin, _root_.play.Play, _root_.play.PlayJava, _root_.play.PlayScala, _root_.play.twirl.sbt.SbtTwirl, _root_.com.typesafe.sbt.jse.SbtJsEngine, _root_.com.typesafe.sbt.jse.SbtJsTask, _root_.com.typesafe.sbt.web.SbtWeb, _root_.com.typesafe.sbt.webdriver.SbtWebDriver, _root_.com.typesafe.sbt.coffeescript.SbtCoffeeScript, _root_.com.typesafe.sbt.less.SbtLess, _root_.com.typesafe.sbt.jshint.SbtJSHint, _root_.com.typesafe.sbt.rjs.SbtRjs, _root_.com.typesafe.sbt.digest.SbtDigest, _root_.com.typesafe.sbt.mocha.SbtMocha
                                                                                                                                                                                                            ^
```

but I don't see this as a problem of sbt. I think it's a general issue of anyone trying to put things into root package.

What do you expect sbt to output?

**Comment by wsargent** [comment]
I'd like sbt to output "You imported a library which defined an object "Play" in the root package, and it is interfering with the Play auto plugin." :-)

**Comment by eed3si9n** [comment]
"imported 'Play' is permanently hidden by definition of object Play" comes pretty close to the situation at hand. Maybe Scala compiler can print out the JAR name in which the symbol `Play` was defined?
It does bring up an interesting issue of all auto plugin names introducing in scope, so if everyone used generic sounding name, we'll have more conflicts.

**Comment by wsargent** [comment]
Yeah, there really isn't much to go on on where this Play object is defined.  Having something pull the location out:

```
clobberingInstance.getClass.getProtectionDomain.getCodeSource.getLocation
```

would be very useful.

**Comment by adriaanm** [comment]
We could improve the compiler to output more details about the definitions involved in the shadowing, but I don't know of any tweaks that apply to the current compiler. Agreed it would be useful.

**Comment by williamho** [comment]
for anyone else having the same issue with this specific plugin (myself included), it's been [fixed](https://bugs.eclipse.org/bugs/show_bug.cgi?id=464749#c1) in a later version of sbt-aspectj -- I don't get the error when using 0.10.4.
