### ISSUE TITLE
RFE: kill forked job

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#1865]
This has been asked on SO and received a lot of attention http://stackoverflow.com/questions/5137460 but the answer is rather inconvenient.

It would be incredibly useful if a key command (e.g. `C-]`) could kill the forked process. It is a real pain to have to hunt it down and kill the pid.... especially since visualvm doesn't offer a kill option.

**Comment by eed3si9n** [comment]
Is this sort of a duplicate of #1442? `TaskCancellationStrategy.Signal` seems like a related topic.

**Comment by fommil** [comment]
that's exactly it, thank you!
