### ISSUE TITLE
artificial root should not publish by default

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#1869]
Suggested by @softprops at nescala. Please comment on this issue, if someone wants to send PR for this.

**Comment by gkossakowski** [comment]
:+1:

**Comment by dwijnand** [comment]
What would be the best criteria for "artificial" do you think?

**Comment by eed3si9n** [comment]
@dwijnand  By "artificial" I mean the root that gets created automatically when you don't specify one.

**Comment by softprops** [comment]
it's too late now to chime in, but I thought it would be cool to have a `Defaults.unpublished` member which  is a Seq of the settings you need to disable publishing. then have the default aggregated project append those settings. That way for other projects that you may also wish to be unpublished, you can just use Defaults.unpublished :)

**Comment by dwijnand** [comment]
So move this: [noArtifacts](https://github.com/paulp/psp-libsbt/blob/3e1618fa65ff1371eb6dd9394bac8837b9f04162/libsbt/src/main/scala/Ops.scala#L87) into sbt's Defaults basically

**Comment by softprops** [comment]
@dwijnand nice!

**Comment by retronym** [comment]
This breaks IntelliJ's import, I'll raise a [bug](https://youtrack.jetbrains.com/issue/SCL-8425).

https://github.com/retronym/sbt-structure-bare-root

**Comment by jeffmay** [comment]
:+1: I forget this a lot on projects and it prevents my cross compiled version from publishing. Looks like the bug was fixed in IntelliJ 13 and I don't think many people would depend on this. Should we bump this issue again?
