### ISSUE TITLE
Launcher prioritizes PlainApplication over traditional xsbti.AppMain

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#1874]
Originally reported by @n8han over https://twitter.com/n8han/status/569687808396398592

> @scala_sbt The 0.13.7 launcher seems to call my launched (conscript) app's `main` rather than `run`. Are there updated docs?
## notes

b0f6f9483918f7e7aeca321e0ff44f745fd5e167 introduced:

``` scala
        def newMain(): xsbti.AppMain = {
          if(PlainApplication.isPlainApplication(entryPoint)) PlainApplication(entryPoint)
          else mainClass.newInstance
        }
```

it's checking `isPlainApplication` first.

**Comment by n8han** [comment]
You probably know this already, but from testing I see the problem is introduced in version 0.13.1.

**Comment by dwijnand** [comment]
Super-seeded by https://github.com/sbt/launcher/pull/3?

**Comment by eed3si9n** [comment]
Yea. We can close this.
