### ISSUE TITLE
non-determinism from conflicting AutoPlugins

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#1875]
See #1839.

## steps
Suppose two auto plugins set some key `X`.

## problems
Is there a non-determism now? In other words, depending on the environment or randomness, you could end up with different build results.

## expectations

build should be stable across machines.

**Comment by jsuereth** [comment]
Can you elucidate more on this ticket?  What is the outcome and goals.

Right now, this is a known "limitation".   Also, there is nothing non-deterministic, it's just the order is "unspecified" which is two different things.   The only way to enforce order is via dependencies.  

SO, I think this ticket needs an explanation of its goals/desires.

**Comment by eed3si9n** [comment]
I want to confirm if things "flip flop" as mentioned in the linked case. If so we should sort things by name or something so at least it's consistent behavior between the builds.

**Comment by jsuereth** [comment]
yeah, so I'd like to see a legit test case before we open this, otherwise it should be closed.

**Comment by matthughes** [comment]
@jsuereth There is a test case on #1839 now.

**Comment by armanbilge** [comment]
I ran into this in https://github.com/http4s/sbt-http4s-org/pull/120#issuecomment-1008454875.

"Flip-flop" is exactly how I'd describe it. Results seemed to be consistent on any particular machine, but different across machines (cloud workspace vs local and GHA CI).

**Comment by rossabaker** [comment]
> we should sort things by name or something so at least it's consistent behavior between the builds.

We just got eaten by this and floated the same idea internally.  We have two orthogonal plugins that each append a GitHub workflow job, and the `githubWorkflowCheck` on the serialized YAML fails because the unspecified order in CI is different from the unspecified order on at least two developer workstations.  Using the fully-qualified classnames to resolve ambiguities in the dependency graph seems quite reasonable (he says from his perch outside the SBT internals).

**Comment by eed3si9n** [comment]
A potentially analogous/related build stability issues that I fixed a while back:
- https://github.com/sbt/sbt/pull/5447
- https://github.com/sbt/sbt/pull/5448

**Comment by eed3si9n** [comment]
I have a PR attempt for this - https://github.com/sbt/sbt/pull/7404
