### ISSUE TITLE
Problem with aggregation and new contexts

### ISSUE THREAD

**Issue by paulbutcher** [sbt/sbt#188]
In both 0.10.1 and 0.11.0-RC0, the following Build.scala:

``` scala
import sbt._

object MockBuild extends Build {
  lazy val root = Project("root", file(".")) aggregate(subProject)

  lazy val Mock = config("mock")
  lazy val mockSettings = inConfig(Mock)(Defaults.configSettings)
  lazy val subProject = Project("subProject", file("subProject")) settings(mockSettings: _*) configs(Mock)
}
```

Gives:

```
> mock:compile
[error] Not a valid key: mock (similar: doc, fork)
[error] mock:compile
[error]     ^
```

Comment out the `lazy val root` line and it works just fine:

```
> mock:compile
[info] Updating {file:/Users/paul/scala/foo/}subProject...
[info] Done updating.
[info] Compiling 1 Scala source to /Users/paul/scala/foo/subProject/target/scala-2.9.1/mock-classes...
[success] Total time: 3 s, completed 11-Sep-2011 19:45:56
```

**Comment by paulbutcher** [comment]
Mark - I was slightly confused by your comment on the mailing list:

> Yes, it may not be a bug, but there is enough evidence to open a ticket and continue there.

_Should_ I expect this to work? Is there an alternative way for me to structure things that would fit better with "the sbt-way"?

**Comment by jsuereth** [comment]
Paul -

In the scala build, I manually aggregate tasks in the root project with the specific projects they should call.   This means the task has a setting on the root project.   There are some tasks, however, that you must specify the project for a.la.

```
> subProject/mock:compile
```

From my understanding of the aggregate feature it's a "work in progress".   I'm curious what Mark's goal is to have the aggregate feature become or what usage it entails.   This seems like a good use case for it.

**Comment by harrah** [comment]
Ok, the answer is that this behavior is expected.  Aggregation only kicks in once the task/setting to aggregate is known.  The reason is parsing efficiency, especially for tab completion.  Implementing the requested behavior is possible, but would multiply the parsing/completion work by the number of aggregated projects.

**Comment by paulbutcher** [comment]
Thanks, Mark - that makes sense,

For completeness (and in case anyone else stumbles across the same thing), I have got things working the way that I want with this:

``` Scala
import sbt._
import sbt.inc.Analysis
import Keys._

object MockBuild extends Build {
  lazy val Mock = config("mock")

  lazy val root = Project("root", file(".")) settings(compile in Mock := Analysis.Empty) configs(Mock) aggregate(subProject)

  lazy val mockSettings = inConfig(Mock)(Defaults.configSettings)
  lazy val subProject = Project("subProject", file("subProject")) settings(mockSettings: _*) configs(Mock)
}
```
