### ISSUE TITLE
how to configure the sbt-0.13.7 to use local maven repository ?

### ISSUE THREAD

**Issue by liu-hongwei** [sbt/sbt#1882]
hi,
i downloaded the msi here for Windows https://dl.bintray.com/sbt/native-packages/sbt/0.13.7/sbt-0.13.7.msi ,

i want to use the my local maven repository, the folder structure as below:

D:\dev\
          |----mysample
          |              |----src
          |              |       |---scala
          |              |               |---mysample.scala
          |              |----project
          |              |         |--assembly.sbt
          |              |         |--build.properties
          |              |---build.sbt 
          |----Externals
                     |---MavenRepository
                           |--xxx

i configured the local repository using relative path in the d:\dev\mysample\build.sbt as:

  resolvers += "local maven" at "file:///../Externals/MavenRepository"

and also in d:\dev\mysample\project\build.properties as 

 resolvers += "local maven" at "file:///../../Externals/MavenRepository"
 sbt.version=0.13.7

but when run the "sbt assembly " command under d:\dev\mysample, it reports unable to get 
org.fusesource.jansi#jansi;1.11

which actually is under the MavenRepository.

so my questions are:
1. since i configured the sbt.version, so it will try to download SBT with that version,  i don't have network access, so need it to look from local maven repository. How can i configure it?
2. for mysample project, whenever it requires a external jar, i want SBT look up from locam maven repository, How to do that?

Thanks in advance

**Comment by eed3si9n** [comment]
The sbt issue tracker is not a support system. Please see [how can I get help?](http://www.scala-sbt.org/community.html#how-can-I-get-help)
