### ISSUE TITLE
Error: Could not retrieve sbt 0.13.7: missing xsbt.Main

### ISSUE THREAD

**Issue by liu-hongwei** [sbt/sbt#1884]
hi

i want to customized the SBT to use local maven repository, 

the sbtconfig.txt is configured as below, with the "-Dsbt.boot.properties":

D:\Dev\Tools\sbt\0.13.7\conf\sbtconfig.txt
# Set the java args to high

-Xmx512M

-XX:MaxPermSize=256m

-XX:ReservedCodeCacheSize=128m
# Set the extra SBT options

-Dsbt.log.format=true

-Dsbt.boot.properties="file:///D:/Dev/Tools/sbt/0.13.7/bin/sbt.boot.properties"

and the config of the sbt.boot.properties as below:

D:\Dev\Tools\sbt\0.13.7\bin\sbt.boot.properties
[scala]
version:${sbt.scala.version-auto}

[repositories]
local

[ivy]
ivy-home:C:\Users\xx.ivy2\

[log]
level:debug

but when run "sbt assembly" , i get below error:

[debug] Parsed configuration: LaunchConfiguration(auto,IvyOptions(Some(C:\Users\xx.ivy2),Classifiers(List(),List()),List(Predefined(local,false)),List(sha1, md5),false),Application(org.scala-sbt,sbt,sbt.version,xsbt.Main,List(default),Binary,[Ljava.io.File;@5b464ce8),BootSetup(D:\Dev\mysample\project\boot,true,D:\Dev\mysample\project\build.properties,Search(none,List()),,false,false),xsbt.boot.Logging@57829d67,List(),None)
[debug] Resolved configuration: LaunchConfiguration(auto,IvyOptions(Some(C:\Users\b-holiu\bk.ivy2),Classifiers(List(),List()),List(Predefined(local,false)),List(sha1, md5),false),Application(org.scala-sbt,sbt,0.13.7,xsbt.Main,List(default),Binary,[Ljava.io.File;@5b464ce8),BootSetup(D:\Dev\mysample\project\boot,true,D:\Dev\mysample\project\build.properties,Search(none,List()),,false,false),xsbt.boot.Logging@57829d67,List(),None)
Getting org.fusesource.jansi jansi 1.11 ...
:: retrieving :: org.scala-sbt#boot-jansi
    confs: [default]
    1 artifacts copied, 0 already retrieved (111kB/31ms)
Getting org.scala-sbt sbt 0.13.7 ...
:: retrieving :: org.scala-sbt#boot-app
    confs: [default]
    51 artifacts copied, 0 already retrieved (15709kB/156ms)
Getting Scala 2.10.4 (for sbt)...
:: retrieving :: org.scala-sbt#boot-scala
    confs: [default]
    5 artifacts copied, 0 already retrieved (24459kB/125ms)
Error: Could not retrieve sbt 0.13.7: missing xsbt.Main

what i missed in the .ivy2 cache ?

thanks

**Comment by eed3si9n** [comment]
The sbt issue tracker is not a support system. Please see [how can I get help?](http://www.scala-sbt.org/community.html#how-can-I-get-help)
