### ISSUE TITLE
integration test dependencies are being added to the main dependency list

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#1888]
``` scala
  lazy val server = Project("ensime", file("server")).dependsOn(
    api, swank,
    sexpress % "test->test",
    testingEmpty % "it", testingSimple % "it", testingDebug % "it"
  )
```
## original report

In this exact cut of ensime-server

https://github.com/ensime/ensime-server/blob/bcf87d3ed217cc0c51c3d1749f74765e6533cab5/project/EnsimeBuild.scala#L140

we have some modules that only the `it` phase depends upon.

e.g. in the pom we see this sort of thing

``` xml
<dependency>
<groupId>testingempty</groupId>
<artifactId>testingempty_2.11</artifactId>
<version>0.1-SNAPSHOT</version>
</dependency>
<dependency>
<groupId>testingsimple</groupId>
<artifactId>testingsimple_2.11</artifactId>
<version>0.1-SNAPSHOT</version>
</dependency>
<dependency>
<groupId>testingdebug</groupId>
<artifactId>testingdebug_2.11</artifactId>
<version>0.1-SNAPSHOT</version>
</dependency>
```

Ideally these shouldn't be referenced at all.

**Comment by eed3si9n** [comment]
pom should scope that in `it`. Not sure if this is our problem, or just the reality of pom/ivy.

**Comment by fommil** [comment]
As a workaround, I'd be happy to simply exclude it. I really couldn't give a damn about publishing test artefacts. In fact, I'd really rather not, because it's confusing and verbose.

**Comment by gslowikowski** [comment]
Maven has no `it` scope, only `test` for both unit and integration test dependencies.

**Comment by fommil** [comment]
I'd like to exclude both from appearing in the pom, is that possible with sbt?

**Comment by fommil** [comment]
perhaps a better behaviour for `sbt` would be to automatically add artefacts to the `test` scope if the `Configuration` extends from `Test` (i.e. `IntegrationTest` or user user-defined test phases).

Otherwise the workaround is that all test dependencies (whether they be intg or user-defined: slow, nightly, os-specific, unreliable, regression, performance, etc) all **have** to be added to the `test` Configuration as well.

NOTE: that this actually plays well for me in `ensime-sbt` because it means that I don't need to run `update` and `updateClassifiers` for all `Configuration`s because I know they'll all already be included in the single run on the root project (which does at least `Compile` `Test`, but not `IntegrationTest` or any other phases)

**Comment by eed3si9n** [comment]
> As a workaround, I'd be happy to simply exclude it.

I agree on excluding it.

**Comment by chEbba** [comment]
Hi there. Any news here? The problem is still presented in 0.13.x branch (haven't tested 1.0 yet).
Btw, same issue #1380

**Comment by fommil** [comment]
I see this behaviour in sbt 1.1.2 still https://gitlab.com/fommil/sbt-neojmh/issues/1

*sigh*

**Comment by fommil** [comment]
@chEbba yes thanks, this looks like a dupe
