### ISSUE TITLE
Undefined settings from ProjectRef

### ISSUE THREAD

**Issue by MasseGuillaume** [sbt/sbt#1892]
this gives me undefined setting for `... foo/*:package`

```
lazy val plugin = ProjectRef(file("../a"), "foo")

lazy val main = project.settings(Seq(
  scalacOptions += {
    val jar = (Keys.`package` in plugin).value
    "-Xplugin:" + jar.getAbsolutePath
  }): _*)
```

**Comment by MasseGuillaume** [comment]
If you define a project that `dependsOn` plugin it works fine

``` scala
lazy val plugin = ProjectRef(file("../a"), "foo")
lazy val fake = project.settings(buildSettings: _*).dependsOn(plugin) // not used
lazy val main = project.settings(Seq(
  scalacOptions += {
    val jar = (Keys.`package` in plugin).value
    "-Xplugin:" + jar.getAbsolutePath
  }): _*)
```

`sbt main/compile` ok!

**Comment by eed3si9n** [comment]
See http://www.scala-sbt.org/0.13/docs/Compiler-Plugins.html

**Comment by MasseGuillaume** [comment]
@eed3si9n I'm using a compiler plugin has an example. The real problem is that I cannot reference an external project ref settings if I don't create that fake project.

**Comment by eed3si9n** [comment]
I feel like this is just the way sbt is designed. If you think this is a bug, could you phrase it in terms of steps, problems, and expectations? http://www.scala-sbt.org/community.html#how-can-I-help
