### ISSUE TITLE
SNAPSHOT pom download url is wrong

### ISSUE THREAD

**Issue by shijinkui** [sbt/sbt#1895]
http://xxx/ffff-xxx/1.0.0-20140312.020225-4/ffff-xxx-1.0.0-20140312.020225-4.pom

when i download pom, sbt show this url, 404. 
It should be http://xxx/ffff-xxx/1.0.0-SNAPSHOT/ffff-xxx-1.0.0-20140312.020225-4.pom

i think  ivy use `revision` but maven nexus want version。

**Comment by eed3si9n** [comment]
This is duplicate of #679.

**Comment by shijinkui** [comment]
thx
