### ISSUE TITLE
SNAPSHOT Resolver not working

### ISSUE THREAD

**Issue by criccomini** [sbt/sbt#190]
My build.sbt:

```
name := "some project"

version := "0.1.0"

scalaVersion := "2.8.1"

resolvers ++= Seq(
  "Apache Snapshots" at "http://repository.apache.org/content/repositories/snapshots"
)

libraryDependencies ++= Seq(
  "org.apache.hadoop" % "hadoop-yarn-api" % "0.24.0-SNAPSHOT"
)
```

When I try to run this, I get:

[warn]  ==== local: tried
[warn]    /Users/criccomini/.ivy2/local/org.apache.hadoop/hadoop-yarn-api/0.24.0-SNAPSHOT/ivys/ivy.xml
[warn]    -- artifact org.apache.hadoop#hadoop-yarn-api;0.24.0-SNAPSHOT!hadoop-yarn-api.jar:
[warn]    /Users/criccomini/.ivy2/local/org.apache.hadoop/hadoop-yarn-api/0.24.0-SNAPSHOT/jars/hadoop-yarn-api.jar
[warn]  ==== Apache Snapshots: tried
[warn]    http://repository.apache.org/content/repositories/snapshots/org/apache/hadoop/hadoop-yarn-api/0.24.0-SNAPSHOT/hadoop-yarn-api-0.24.0-SNAPSHOT.pom
[warn]    -- artifact org.apache.hadoop#hadoop-yarn-api;0.24.0-SNAPSHOT!hadoop-yarn-api.jar:
[warn]    http://repository.apache.org/content/repositories/snapshots/org/apache/hadoop/hadoop-yarn-api/0.24.0-SNAPSHOT/hadoop-yarn-api-0.24.0-SNAPSHOT.jar
[warn]  ==== public: tried
[warn]    http://repo1.maven.org/maven2/org/apache/hadoop/hadoop-yarn-api/0.24.0-SNAPSHOT/hadoop-yarn-api-0.24.0-SNAPSHOT.pom
[warn]    -- artifact org.apache.hadoop#hadoop-yarn-api;0.24.0-SNAPSHOT!hadoop-yarn-api.jar:
[warn]    http://repo1.maven.org/maven2/org/apache/hadoop/hadoop-yarn-api/0.24.0-SNAPSHOT/hadoop-yarn-api-0.24.0-SNAPSHOT.jar
[warn]  ==== Scala-Tools Maven2 Repository: tried
[warn]    http://scala-tools.org/repo-releases/org/apache/hadoop/hadoop-yarn-api/0.24.0-SNAPSHOT/hadoop-yarn-api-0.24.0-SNAPSHOT.pom
[warn]    -- artifact org.apache.hadoop#hadoop-yarn-api;0.24.0-SNAPSHOT!hadoop-yarn-api.jar:
[warn]    http://scala-tools.org/repo-releases/org/apache/hadoop/hadoop-yarn-api/0.24.0-SNAPSHOT/hadoop-yarn-api-0.24.0-SNAPSHOT.jar
[warn]      ::::::::::::::::::::::::::::::::::::::::::::::
[warn]      ::          UNRESOLVED DEPENDENCIES         ::
[warn]      ::::::::::::::::::::::::::::::::::::::::::::::
[warn]      :: org.apache.hadoop#hadoop-yarn-api;0.24.0-SNAPSHOT: not found
[warn]      ::::::::::::::::::::::::::::::::::::::::::::::

When I look in:

http://repository.apache.org/content/repositories/snapshots/org/apache/hadoop/hadoop-yarn-api/0.24.0-SNAPSHOT/

I see hadoop-yarn-api-0.24.0-20110914.034918-1.jar listed.

When I read the maven website http://www.sonatype.com/books/mvnref-book/reference/pom-relationships-sect-pom-syntax.html#pom-relationships-sect-version-build-numbers I see:

"Maven versions can contain a string literal to signify that a project is currently under active development. If a version contains the string “SNAPSHOT,” then Maven will expand this token to a date and time value converted to UTC (Coordinated Universal Time) when you install or release this component. For example, if your project has a version of “1.0-SNAPSHOT” and you deploy this project’s artifacts to a Maven repository, Maven would expand this version to “1.0-20080207-230803-1” if you were to deploy a release at 11:08 PM on February 7th, 2008 UTC. "

It seems to me that SBT is not properly handling the revision expansion.

**Comment by harrah** [comment]
The repository/dependency definitions don't work for maven either, so I assume there is a problem with those or the pom.  Please use the mailing list for further questions.

**Comment by darkfrog26** [comment]
I'm having this same problem.  Harrah, I don't understand your response as this appears to be a missing features in SBT to support Maven's unique build ids?  Also, this is not optional in Maven 3, it is the default behavior and I don't believe there's any way to turn it off.

**Comment by darkfrog26** [comment]
Upon further investigation this appears to be happening because of authentication failure.  It should still be considered a bug since SBT doesn't tell you that the reason it's not getting your dependency properly is because it failed to authenticate properly but misleads you to believe that it's looking for the wrong URL.
