### ISSUE TITLE
Description about system property xsbt.inc.debug is missing in documentation.

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [sbt/sbt#1901]
http://www.scala-sbt.org/0.13/docs/Combined+Pages.html#Command+Line+Reference

**Comment by eed3si9n** [comment]
There are number of flags we've been adding over time.

**Comment by er1c** [comment]
I believe this can be closed, it is added under: https://www.scala-sbt.org/1.x/docs/Combined+Pages.html#Command+Line+Reference

```
xsbt.inc.debug | Boolean | false | Extra debugging for the incremental debugger.
```

**Comment by eed3si9n** [comment]
Cool.
