### ISSUE TITLE
Stop support for running sbt under java 6

### ISSUE THREAD

**Issue by raboof** [sbt/sbt#1903]
Java 6 reached 'end of life' status in february 2013. 

IMHO it'd make sense to stop support for running sbt with it, opening up the possibility of using java 7 features such as new java.nio.file API's.

**Comment by eed3si9n** [comment]
Unless Java 6 is actively preventing your build, probably a better forum to discuss this would be sbt-dev list.

I've heard the word End of Life associated with Java 6, but sbt 0.13.x series also needs to keep binary compatibility with 0.13.0. Or it's ok as long as we're not breaking the plugins?
[Oracle Java SE Support Roadmap](http://www.oracle.com/technetwork/java/eol-135779.html) says the public release has ended in February 2013, but "Extended Support**" is till 2018. In the same logic though, Java 7's end of public release is coming up in a month.

**Comment by raboof** [comment]
This is not preventing my build :).

It'd indeed make sense to do this for 0.14.

I hadn't noticed Oracle is still 'supporting' versions for which it isn't issuing updates anymore, interesting. Still, for a build tool, I'd say it'd make sense to require a relatively recent version of Java for running the build tool (still giving your the option to target older versions for your own bulids, of course).

I'll take this to sbt-dev as you suggested, thanks.
