### ISSUE TITLE
Display the name(s) of build files

### ISSUE THREAD

**Issue by david-bouyssie** [sbt/sbt#1911]
I recently ran into the following issue: I have copied the file build.sbt. The new file was named "build - copie.sbt".

I was expected that the file "build.sbt" to be still used. I spent 4 hours to understand that "build - copie.sbt" was used instead of "build.sbt".

It would be really great to display the name of script being used for the compilation process.

Thanks !

**Comment by pauldraper** [comment]
FYI, _all_ *.sbt files are used.

I'm not sure if there is a defined precedence order.

If you are curious where a setting or task is, `inspect my-setting-or-task-key` will tell you.

**Comment by david-bouyssie** [comment]
Ok but it's not obvious for beginners that all sbt files are used. Maybe it would be interesting to display the number or names of files being used at the first step of the process.

**Comment by david-bouyssie** [comment]
Thanks !
