### ISSUE TITLE
SBT occasionally doesn't load other .sbt files in the same folder

### ISSUE THREAD

**Issue by vsabella** [sbt/sbt#1912]
I've noticed a bug where SBT occasionally doesn't load other files in the same folder. I can only get it to repro on a specific set of AMIs and Java Versions in Linux.

For example, we have a common.sbt we drop in that is shared team-wide, as a poor man's plugin while we experiment and figure out what we want to finally include in an appropriate plugin. Everywhere else SBT will load build.sbt and common.sbt. the inspect command will show stuff in the common.sbt scope.

On specific build servers based on specific amazon linux instances, it behaves as if common.sbt doesn't exist, but it doesn't do it all the time. (Rebooting the system occasionally makes it work). 

I'll dig up the information and add to the issue, but is there a quick way to get a very verbose debug of what SBT tries to load to see if this is deeper filesystem / linux / java bug?

**Comment by eed3si9n** [comment]
Do you specify specific sbt version using `build.properties`?

**Comment by vsabella** [comment]
I believe i found the issue and it was my stupidity in ordering of version vs Version in ThisBuild.
