### ISSUE TITLE
Allow test frameworks implementations to participate in test discovery

### ISSUE THREAD

**Issue by michaelpigg** [sbt/sbt#1924]
The current approach to test discovery makes it difficult to use a test framework like partest from sbt. Partest defines test names with a combination of directory and file names rather than with type features of the test class.

My initial thought is to add a `enumerateTests` method to [Framework](https://github.com/sbt/test-interface/blob/master/src/main/java/sbt/testing/Framework.java) that would be called during discovery to allow the implementation to provide a set of test names.

**Comment by dwijnand** [comment]
Closing. See #1949.
