### ISSUE TITLE
cached resolution: updateClassifiers with cached resolution is really slow

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#1930]
This impacts multi-module projects in ENSIME and IntelliJ (at least), since anything that requires the sources/docs will need to call updateClassifiers on a per-module basis for export.

e.g. use `sbt gen-ensime` on https://github.com/ensime/ensime-server The command is doing this work: https://github.com/ensime/ensime-sbt/blob/master/src/main/scala/EnsimePlugin.scala#L142

**Comment by fommil** [comment]
still slow with 0.13.9-M1 :cry:

**Comment by fommil** [comment]
btw, this isn't just relevant for ENSIME. Something similar is being called by IntelliJ's sbt integration for "reload project"... which is notoriously slow for this very reason.

**Comment by mdedetrich** [comment]
+1

This is having an impact at our work (we use `IntelliJ`), which uses a similar mechanism), since our project is actually comprised of around 26 sbt projects, doing changes takes ages to resolve when the SBT project reloads

**Comment by fommil** [comment]
In the hope that somebody looks at this, I'm seeing this take as long as an hour on my work project.

The reason it takes so long is because `update` and `updateClassifiers` has to be called for each `Project` (and for each `Configuration` within each `Project`) so we can work out which jars are introduced at each stage. If the `UpdateReport` contained this information, it would help **a lot** because we could just run the report once (hmm, how to do that to aggregate all configs?) and then work out what goes where.

**Comment by eed3si9n** [comment]
@Duhemm is currently revisiting updateClassifiers for another issue. I wonder if he can piggyback his brain cycle to take a look at this one if it's not too much work.

**Comment by fommil** [comment]
@eed3si9n @Duhemm that'd be awesome! at this stage, I'm just looking for a workaround as this is killing me at work. I was thinking about implementing a hack where I run `updateClassifiers` **once** and then just throw all the collected sources/javadocs into a fake module that everything depends on. But that's probably going to miss all the test phases (we have 6 at work).

**Comment by fommil** [comment]
(plus something similar for the `update` task... really minimise the number of calls to generate reports... see #2266 for an example project of what I have to support )

**Comment by joprice** [comment]
+1

I have this same problem in several projects. It winds up punishing best practices that encourage modularity.

**Comment by smithjessk** [comment]
+1

**Comment by timothyklim** [comment]
:+1:

**Comment by ancane** [comment]
+1

**Comment by diego-alvarez-hs** [comment]
+1

**Comment by jotsif** [comment]
+1

**Comment by pbatko** [comment]
+1

**Comment by laughedelic** [comment]
+1

**Comment by kpadmasola** [comment]
+1

**Comment by sebigavril** [comment]
:+1:

**Comment by skchrnko** [comment]
+1

**Comment by JHK** [comment]
+1

**Comment by chinmaybijwe** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by Astrac** [comment]
:+1:

**Comment by stephenjudkins** [comment]
Please consider using the new reaction feature and choosing :+1: there instead of adding another comment.

**Comment by fommil** [comment]
and if you do that, also Subscribe to the thread for updates (an advantage of the old :+1: technique)

**Comment by jvvasques** [comment]
+1

**Comment by phucnh** [comment]
+1

**Comment by fommil** [comment]
I think coursier fixes this
