### ISSUE TITLE
Add SLF4J backend

### ISSUE THREAD

**Issue by hseeberger** [sbt/sbt#1931]
See https://github.com/sbt/sbt-git/issues/69.

**Comment by dwijnand** [comment]
Which module should this live in?

**Comment by raboof** [comment]
We could look at https://github.com/eirslett/sbt-slf4j for some inspiration.

**Comment by raboof** [comment]
How would we like this to work?

It's pretty common in slf4j to get a static reference to the logger - which seems to make it tricky to attach this to a task/stream.

Are there any other similar log frameworks that are already supported?

**Comment by raboof** [comment]
https://github.com/vast-engineering/sbt-slf4j is a little nicer by putting the logger to be returned from `SbtLoggerFactory.getLogger` in a `DynamicVariable`. However:
- it ignores the `name`
- needs an explicit call from the task
- it's out of our hands once the client code has called `getLogger`

**Comment by raboof** [comment]
Reliably attaching the slf4j loggers to the task streams seems impossible.

Perhaps we should provide a default implementation, but allow users to override it?

Perhaps that default should send logging to some global slf4j streams ('slf4j-error', 'slf4j-warning', 'slf4j-info', 'slf4j-debug'), and the 'error' and 'warning' streams should be sent to STDOUT?

**Comment by orium** [comment]
Any news on this issue?

**Comment by larsrh** [comment]
Fixed by #3382.

**Comment by dwijnand** [comment]
Will be in the sbt 1.0.0-RC3 release.
