### ISSUE TITLE
Config traversal - unexpected behaviour

### ISSUE THREAD

**Issue by muuki88** [sbt/sbt#1932]
I read the [travelling the 4th dimension](http://eed3si9n.com/4th-dimension-with-sbt-013) guide and related SO questions [1](http://stackoverflow.com/questions/23162874/sbt-config-extend-vs-defaultsettings) and [2](http://stackoverflow.com/questions/23586436/make-one-sbt-config-depend-on-another). However I'm still struggling with the sbt behaviour.

I want to define as task _once_ and depending on the scope I run it, it should pickup
different settings. In my small example I have a `testSetting` and a `testTask`.
The `testTask` only  returns the `testSetting`. There are two additional Scopes
`traversal-conf` and `traversal-ext-conf`. I define the task _once_ and only change the settings. I expect

``` scala
> show testTask
[info] top-level
> show traversal-conf:testTask
[info] in-traversal-conf
> show traversal-ext-conf:testTask
[info] in-traversal-ext-conf
```

However I get

``` scala
> show testTask
[info] top-level
> show traversal-conf:testTask
[info] top-level
> show traversal-ext-conf:testTask
[info] top-level
```

Only if I copy the task definition in the `inConfig` sections,
the correct setting value is used. I'm using `sbt 0.13.8`
## Sample Code

``` scala
import sbt._

object ConfigTraversalPlugin extends AutoPlugin {

  val TraversalConf = config("traversal-conf")
  val TraversalExtConf = config("traversal-ext-conf") extend (TraversalConf)

  object autoImport {
    val testSetting = SettingKey[String]("testSetting", "What a setting!")
    val testTask = TaskKey[String]("testTask", "returns testSetting")
  }

  import autoImport._

  override lazy val trigger = AllRequirements

  // smoothing things a bit
  override def projectConfigurations = Seq(TraversalConf, TraversalExtConf)

  override def projectSettings = Seq(
    testSetting := "top-level",
    testTask := testSetting.value
  ) ++ inConfig(TraversalConf)(Seq(
      testSetting := "in-traversal-conf"
      // if this is copied multiple in each config, then it works
      //, testTask := testSetting.value 
    )) ++ inConfig(TraversalExtConf)(Seq(
      testSetting := "in-traversal-ext-conf"
    ))
}
```

**Comment by jsuereth** [comment]
Currently in sbt, you need to push your task out to all dimensions you want it in.   You'll see we do this for Compile/Test in the default build.

There is an advanced feature called "Def.derive" where we can automatically propogate settings out to configurations/dimensions, but it doesnt' really do exactly what you (we) want, so it's not advertise and won't help in this scenario.

**Comment by muuki88** [comment]
Thanks @jsuereth :) Is this something that will be available in the future?

**Comment by eed3si9n** [comment]
"define ABC once and depending on (insert magic), it should pickup XYZ" pattern generally makes thing more difficult to understand, especially when it doesn't fully work. Related: [In sbt, how do you override scalacOptions for console in all configurations?](http://stackoverflow.com/q/26940253/3827), `fork in test` vs [`fork in Test`](https://github.com/sbt/sbt/issues/975).

In my opinion, what's missing here is a better documentation of the delegation mechanism. In your example, `testTask` only exists at the Global-configuration level. When you typed in `traversal-conf:testTask`, the key didn't exist in `TraversalConf`. sbt silently delegated the incoming command `traversal-conf:testTask` to the unscoped `testTask` task, which should explain why you saw

```
> show traversal-conf:testTask
[info] top-level
```

Maybe we should display to the user:

```
> show traversal-conf:testTask
[warn] what?! the key doesn't exist in that scope, delegating to *:testTask
[info] top-level
```

If we did that for all the keys, it would be annoying, so probably top-level only.

**Comment by muuki88** [comment]
> Maybe we should display to the user

This would be a nice starting point.

All people posting questions on this topic seem to have the same understanding. When you create a config that `extends` another config, it should inherit all values. And if you run a task within a scope (or dimension) it searches from special to general. 

``` scala
// what I imagine a scope looks like
val extScope = Scope {
   val settingValues: Map[Setting, Value] = Map()
   val outerScope = globalScope

   def settingValue(setting: Setting): Option[Value] = settingValues
      .get(setting)
      .orElse(outerScope.settingValue) 
}

// what I image a task run looks like
task.run(settings: Seq[Setting], scope: Scope) {
   val values = settings.map { setting => 
       scope.settingValue(setting).getOrElse(
           sys.error(s"Setting ${setting.name} is not defined in any scope")
       )
   }

   task.runWithValues(values)
}
```

Is there like a visual thing how setting/task resolving works?

**Comment by dwijnand** [comment]
Not sure if it answers your question, but I've found using `inspect actual` in addition to `inspect` to help me at times, for instance for dependencies understanding what scoped setting it's actually going to use vs what scoped setting it could use.
