### ISSUE TITLE
Missing docs for ProjectRef & RootProject

### ISSUE THREAD

**Issue by benmccann** [sbt/sbt#1936]
I don't see `ProjectRef` or `RootProject` mentioned anywhere in the documentation. A good place to include these docs might be in [the section for multi-project builds](http://www.scala-sbt.org/0.13.5/docs/Getting-Started/Multi-Project.html).

I have a lot of questions about how to setup multi-project builds as our codebase grows larger. Should we put our entire codebase in a single SBT build split amongst standard SBT sub-projects? Or should we make each library it's own SBT project and wire them all together with `ProjectRef` external references?

**Comment by eed3si9n** [comment]
Generally documentation related issues should be tracked in sbt/website, but in this case a better forum might be sbt-dev list to discuss what to document and how to set up multi-project builds.

**Comment by benmccann** [comment]
Thanks. I've created an issue on sbt/website to track this. I'll email sbt-dev for more info and then potentially with some pointers I'll be able to create a PR
