### ISSUE TITLE
dsl for common license

### ISSUE THREAD

**Issue by MasseGuillaume** [sbt/sbt#1937]
I just scraped all scala poms on maven central. If sbt could define some dsl over common license, it could clean up this mess:

```
(2155) Apache 2
(1809) Apache License, Version 2.0
(1286) MIT
(1123) Apache-2.0
(1041) BSD-style
(920) MIT-style
(893) MIT License
(430) Affero GPLv3
(275) MIT license
(268) The Apache Software License, Version 2.0
(246) Apache 2.0
(191) GPL v2+
(187) MPL-2.0
(165) LGPL v2.1+
(135) BSD New
(132) BSD
(131) The MIT License
(114) Apache License, Version 2.0Apache License, Version 2.0
(109) The Apache License, Version 2.0
(100) Apache V2
(97) BSD-like
(92) Apache2
(92) GPL v3+
(91) W3C
(76) the Apache License, ASL Version 2.0
(74) Apache License 2.0
(71) Apache-style
(71) Apache
(63) BSD 3-Clause
(55) Three-clause BSD-style
(55) Apache License
(52) BSD 3-clause
(48) BSD-3-Clause
(45) LGPL-3.0
(45) GPLv3
(44) Apache License, Verison 2.0
(44) GNU Lesser General Public License, Version 2.1
(42) Apache 2.0 License
(38) LGPL v3
(34) Two-clause BSD-style license
(32) Apache license
(28) ASL
(27) GPL version 3 or any later version
(24) Apache License, ASL Version 2.0
(24) BSD Simplified
(24) BSD-2-Clause
(23) LGPL
(19) LGPL v3+
(18) BSD Software License, 2-clause version
(17) LGPL3
(16) APSL-2.0
(16) MPL-2.0W3C
(13) The MIT License (MIT)
(13) Apache v2
(13) GPL-3.0
(13) APACHE-2.0
(12) GNU Lesser General Public License v3.0
(11) Scala License
(11) GNU Library or Lesser General Public License (LGPL)
(11) The BSD 3-Clause License
(11) MIT Licence
(11) MITBSD New
(11) CC BY 4.0.
(10) Scala license
(10) MIT licencse
(10) The Apache Software Licence, Version 2.0
(9) mit
(9) Public domain
(8) Apache 2.0Academic License (for original lex files)Apache 2.0 (for supplemental code)
(8) Apache 2.0 
(8) New BSD
(8) DO WHAT YOU WANT TO PUBLIC LICENSE, Version 1
(8) LGPLv3
(7) 3-clause BSD
(7) MPL-2.0MPL-2.0
(7) Figaro License
(7) GPL-2.0
(6) The Apache License, ASL Version 2.0
(6) GNU Lesser General Public Licence
(6) LGPL 3.0 license
(6) Creative Commons Attribution-ShareAlike 4.0 International
(5) Apache 2 License
(5) GNU General Public License v2
(5) Apache Public License 2.0
(5) AGPL
(5) BSD 3-Clause License
(4) Mozilla Public License Version 2.0
(4) LGPL-2.1
(4) Apache License Version 2.0
(4) The BSD 2-Clause License
(3) Public domainBSD-like
(3) BSD-Style
(3) GNU General Public License (GPL)
(3) GNU Lesser General Public License, Version 2.1Eclipse Public License, Version 1.0
(2) ISC
(2) New BSD License
(2) ISC License
(2) Apache 2 license
(2) Apache License, Version 2
(2) Apache-2.0Apache-2.0
(2) AGPL-3.0
(1) LGPLv2.1
(1) AGPL v3
(1) Apache-2.0MIT
(1) lgpl
(1) GNU GENERAL PUBLIC LICENSE, Version 3.0
(1) The MIT LicenseGNU General Public License, version 2 (GPL-2.0)
(1) MIT-style license
(1) Eclipse Public License - v 1.0
(1) GNU LESSER GENERAL PUBLIC LICENSE, Version 3
(1) AThe MIT License (MIT)
(1) Atlassian 3.0 End User License Agreement
(1) Apache License Version 2.0The New BSD License
(1) WTFPL, Version 2
(1) GNU Gpl v3
```

**Comment by dwijnand** [comment]
That's a nice aggregate, can you share the code for that by chance?

Dale

**Comment by MasseGuillaume** [comment]
It's part of this
https://github.com/metadoc/metadoc/blob/develop/bintrayScape/src/main/scala/3_PomToJson.scala#L3

**Comment by dwijnand** [comment]
Thanks!

**Comment by MasseGuillaume** [comment]
@dwijnand Regarding this ticket, do you think it make sense ?

http://www.scala-sbt.org/0.13.7/sxr/sbt/Keys.scala.html#sbt.Keys.licenses

``` scala
val licenses = SettingKey[Seq[(String, URL)]]("licenses", "Project licenses as (name, url) pairs.", BMinusSetting)
```

http://www.scala-sbt.org/0.13/docs/Publishing.html#Modifying+the+generated+POM

``` scala
pomExtra :=
  <licenses>
    <license>
      <name>Apache 2</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
    </license>
</licenses>
```

**Comment by dwijnand** [comment]
If you mean "wouldn't it be nice if this weren't so many variants of the
same idea" then yes.

Just personally not sure if it must be part of sbt: could just create a
nicely publicised community plugin to solve this.

Dale

**Comment by MasseGuillaume** [comment]
I will start with the sbt plugin, that's a good idea. I hope we can merge this into sbt at some point :-), as you see Seq[(String, URL)] is not the most precise type to define a license.

**Comment by jsuereth** [comment]
Did you see sbt-license-report? I tmay have some you're missing, but I think not.

If you'd like to make a DSL, I'd be happy to have it.

**Comment by MasseGuillaume** [comment]
I got some WIP here:
https://github.com/MasseGuillaume/super-winner/blob/master/src/main/scala/License.scala#L35

**Comment by eed3si9n** [comment]
In terms of the list of opensource licenses, and its string notation, what affects me personally is Bintray API - https://bintray.com/docs/api/#_footnote_1
This list is fairly comprehensive, and I think it's a good start.

**Comment by MasseGuillaume** [comment]
Hum, sure I can add those licenses. I know that what I have covers 99% of the use cases because I have the list of all open source libraries.

**Comment by eed3si9n** [comment]
I feel like it's better to have top 10 rather than trying to aim for completion. How does the histogram look like?

**Comment by eed3si9n** [comment]
Also what's your plan for the `URL`? If we take Apache-2.0 as an example, which seems to be the overwhelming majority (over 6000), https://www.apache.org/licenses/LICENSE-2.0.txt is licensed to `[name of copyright owner]`. The person who is trying to apply it needs to substitute that part.

**Comment by MasseGuillaume** [comment]
For the histogram, I have a lot of duplicate to filter first. We can see the trend from the raw data: Apache2, MIT, LGPL, GPL, AGPL.

For the URL it's defined via [Spdx license trait](https://github.com/MasseGuillaume/super-winner/blob/master/src/main/scala/License.scala#L43)

regarding the `[name of copyright owner]` I'm not sure it's an issue:
https://github.com/apache/spark/blob/master/LICENSE#L189
https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/annotation/Since.scala#L1-L16
https://github.com/apache/spark/blob/d83c2f9f0b08d6d5d369d9fae04cdb15448e7f0d/NOTICE#L1-L2

**Comment by MasseGuillaume** [comment]
![image](https://cloud.githubusercontent.com/assets/921490/14841307/9b98a366-0c0a-11e6-9a3e-97315891634e.png)

```
Apache License 2.0                               , 24 804
MIT License                                      ,  9 856
BSD 4-clause "Original" or "Old" License         ,  2 499
Typesafe Subscription Agreement                  ,  1 486
BSD 3-clause "New" or "Revised" License          ,    916
GNU Affero General Public License v3.0           ,    588
GNU Lesser General Public License v3.0 only      ,    503
BSD 2-clause "Simplified" License                ,    377
Mozilla Public License 2.0                       ,    347
GNU Library General Public License v2.1 or later ,    298
GNU General Public License v2.0 or later         ,    282
GNU General Public License v3.0 or later         ,    174
GNU General Public License v3.0 only             ,    166
GNU General Public License v2.0 only             ,    137
W3C Software Notice and License                  ,    107
GNU Library General Public License v2.1 only     ,     79
Eclipse Public License 1.0                       ,     30
Scala License                                    ,     29
Creative Commons Zero v1.0 Universal             ,     23
Academic Free License                            ,     22
GNU Lesser General Public License v3.0 or later  ,     20
Public Domain                                    ,     19
Apple Public Source License 2.0                  ,     16
Creative Commons Attribution 4.0                 ,     14
Do What The F*ck You Want To Public License      ,      9
The Unlicense                                    ,      8
Creative Commons Attribution Share Alike 4.0     ,      6
Beerware License                                 ,      1
```

**Comment by dwijnand** [comment]
Cool

**Comment by fommil** [comment]
Stallman would prefer you referred to Mit as the Expat License :-P

Very good to see this. Apache is a good Libre License. It would be good to see more projects, especially Scala itself, use it instead of BSD/MIT. It frees us from the concern of patent lock-in (JVM itself aside).

**Comment by fommil** [comment]
Btw GPL3 is implicitly "or later" unless they've gone out of their way to say so.

**Comment by fommil** [comment]
Does this double count projects with multiple releases or modules comprising the project?

**Comment by MasseGuillaume** [comment]
@fommil good point, I double counted projets (the total is more or less the amount of scala poms on maven central).

**Comment by fommil** [comment]
Why are so many people using 4 clause BSD? As users of these libraries we have obligations to publicise the copyright holder's names when our apps start up.

**Comment by MasseGuillaume** [comment]
@fommil that's a mistake on my end. Let's connect over gitter.im

**Comment by eed3si9n** [comment]
My proposal would be support only three as predefined:
- `Apache-2.0`: Apache License 2.0
- `MIT`: MIT License
- `CC0-1.0`: Creative Commons Zero v1.0 Universal

**Comment by bplommer** [comment]
I think there should be at least one GPL variant in there. Not that copyleft licenses are very common in the Scala world, but it would be a shame for them to be completely unrepresented given their historical and cultural significance.

**Comment by eed3si9n** [comment]
@bplommer I was _really_ close to suggesting **GNU Affero General Public License 3.0 only** as a predefined for similar sentiment, but there are so many nuances around GPL (Affero or not, 3.0 only or 3.0 and later) that predefined I don't think is a good idea.

**Comment by bplommer** [comment]
@eed3si9n yeah, that’s reasonable

**Comment by fommil** [comment]
if you're picking a GPL variant for inclusion, I recommend "GPLv3 or any later version".

I'd not aware of any Scala projects that uses AGPL, besides anything related to neo4j, and it isn't even really a GNU license anyway.

All my tooling has been "GPLv3 or any later version" for a long time. It's an excellent choice for anybody who is developing a Scala developer tool. For other uses of the GPL in your tooling chain, see "linux kernel", "git" and "emacs"... and the world hasn't ended 😉

**Comment by eed3si9n** [comment]
ok. Added `GPL-3.0-or-later` - https://github.com/sbt/librarymanagement/pull/395
