### ISSUE TITLE
SBT says no artefact or ivy file for a folder which does contain them

### ISSUE THREAD

**Issue by kk00ss** [sbt/sbt#1939]
Hello, I'm trying to build [puck](https://github.com/dlwh/puck) and SBT says that no ivy file nor artifact found for [com.nativelibs4java#nativelibs4java-parent;1.10-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/nativelibs4java/nativelibs4java-parent/1.10-SNAPSHOT/) which does contain pom file and for which ivy does create properties file with the following content:
# ivy cached data file for com.nativelibs4java#nativelibs4java-parent;1.10-SNAPSHOT
# Wed Mar 25 12:31:33 EET 2015

artifact:ivy#ivy#xml#1941803316.exists=true
artifact:nativelibs4java-parent#pom.original#pom#-1996117221.location=https://oss.sonatype.org/content/repositories/snapshots/com/nativelibs4java/nativelibs4java-parent/1.10-SNAPSHOT/nativelibs4java-parent-1.10-20150320.012541-2.pom
artifact:nativelibs4java-parent#pom.original#pom#-1996117221.exists=true
artifact:nativelibs4java-parent#pom.original#pom#-1996117221.is-local=false
artifact:ivy#ivy#xml#1941803316.is-local=false
artifact:ivy#ivy#xml#1941803316.location=https://oss.sonatype.org/content/repositories/snapshots/com/nativelibs4java/nativelibs4java-parent/1.10-SNAPSHOT/nativelibs4java-parent-1.10-20150320.012541-2.pom
resolver=sbt-chain

**Comment by kk00ss** [comment]
It looks similar to [another issue](https://github.com/sbt/sbt/issues/321). But I'm new to SBT so cannot tell if it's the same

**Comment by jsuereth** [comment]
the issue could be the dependency is listed as "jar" instead of pom, and the check for the jar file is failing.  

Can you verify if this works when using the Aether resolver in sbt 0.13.8?

**Comment by kk00ss** [comment]
Sorry for bothering you, just upgrade to 0.13.8 fixed the issue.
