### ISSUE TITLE
transient: sbt-plugin-releases seems to be missing/rejecting requests

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#1948]
something funny with scala-sbt.org, any ideas?

```
[error] Server access Error: Connection refused url=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.sonatype.forge/forge-parent/10/jars/forge-parent.jar
[error] Server access Error: Connection refused url=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.sonatype.spice/spice-parent/17/jars/spice-parent.jar
[error] Server access Error: Connection refused url=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.codehaus.plexus/plexus/3.3.1/jars/plexus.jar
[error] Server access Error: Connection timed out url=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.codehaus.plexus/plexus-classworlds/2.5.1/bundles/plexus-classworlds.jar
```

**Comment by eed3si9n** [comment]
It seems to work fine now. Not sure what happened at the time.

**Comment by dwijnand** [comment]
If that's Artifactory on Typesafe's (or is it EPFL's? :-/) servers, there was talk on one of the mailing lists of an outage a few days ago which is what this could've been.. not that it matters now..

**Comment by fommil** [comment]
I've never understood why the plugins don't just use central. A separate nexus just means that the chance of failure doubles. For sbt 1.0 I would love to see Maven-style plugins, not ivy, on central.
