### ISSUE TITLE
addMavenResolverPlugin breaks sbt 0.13.8 on Windows

### ISSUE THREAD

**Issue by fspeech** [sbt/sbt#1952]
For test I created a project with only "hello world" hw.scala (from scala-sbt.org website) and added a build.sbt with a single line of

```
addMavenResolverPlugin
```

I then ran `sbt run` and it failed with:

```
...\proj\scala\test\build.sbt:1: error: not found: value addMavenResolverPlugin
addMavenResolverPlugin
^
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

```
$ sbt --version
sbt launcher version 0.13.8
$ cat project/build.properties
#Project properties
sbt.version=0.13.8

```

**Comment by fommil** [comment]
:+1: this is impacting all ENSIME users on Windows.

**Comment by fommil** [comment]
BTW, why on earth are sbt still distributing their own `sbt` script when everybody ends up using https://github.com/paulp/sbt-extras/blob/master/sbt anyway to work around the plethora of issues that it addresses?

**Comment by eed3si9n** [comment]
You need to add it to `project/maven.sbt`. See http://www.scala-sbt.org/0.13/docs/sbt-0.13-Tech-Previews.html#Maven+resolver+plugin

**Comment by fommil** [comment]
errr... ok. That's a bit magical.

**Comment by fommil** [comment]
```
To enable this plugin, add the following to project/maven.sbt (or project/plugin.sbt the file name doesn’t matter):
```

**Comment by fommil** [comment]
recommend re-open.

**Comment by fommil** [comment]
@fspeech the ENSIME project puts the maven plugin in the `project/plugins.sbt`. I think the effect is the same, but I don't think it's ever going to work in `build.sbt`

**Comment by fommil** [comment]
https://github.com/sbt/sbt/issues/1963
