### ISSUE TITLE
build.properties file line ending is platform sensitive

### ISSUE THREAD

**Issue by wsargent** [sbt/sbt#1963]
If you have a build properties file checked with MS-DOS line ending style with <CR><LF>, so that vi +b project/build.properties produces

```
sbt.version=0.13.5^M
```

and you are on a Linux or MacOS platform, you get the following:

```
➜  intellij-scala git:(master) ✗ sbt
:ownloading sbt launcher for 0.13.5
/sbt-launch.jartypesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.5
/sbt-launch.jarwsargent/.sbt/launchers/0.13.5
/sbt-launch.jar. Obtain the jar manually and place it at /Users/wsargent/.sbt/launchers/0.13.5
```

because it thinks that the ^M is part of the build version string.

**Comment by eed3si9n** [comment]
Interesting. Thanks for the report.

**Comment by dwijnand** [comment]
FWIW it works for me, and one reason that could be is that I use the https://github.com/paulp/sbt-extras script:

```
 $ sbt
Downloading sbt launcher for 0.13.5:
  From  http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.5/sbt-launch.jar
    To  /Users/dnw/.sbt/launchers/0.13.5/sbt-launch.jar
[info] Loading global plugins from /Users/dnw/.dotfiles/.sbt/0.13/plugins
[info] Loading project definition from /Users/dnw/Desktop/t-2015-04-09.2034/project
[info] Set current project to t (in build file:/Users/dnw/Desktop/t-2015-04-09.2034/)
```

Please note: https://github.com/paulp/sbt-extras/pull/94/files#diff-eadc1bacb17aea28d29fefc19868b5e1

**Comment by wsargent** [comment]
@dwijnand try with https://github.com/JetBrains/intellij-scala/

**Comment by wsargent** [comment]
Pretty sure this is the problem as removing the line ending resulted in sbt starting normally.  My guess is that there's special git metadata on project/build.properties.

**Comment by dwijnand** [comment]
Same:

```
 $ git remote -v
origin  git://github.com/JetBrains/intellij-scala.git (fetch)
origin  git://github.com/JetBrains/intellij-scala.git (push)
 $ sbt
Downloading sbt launcher for 0.13.5:
  From  http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.5/sbt-launch.jar
    To  /Users/dnw/.sbt/launchers/0.13.5/sbt-launch.jar
[info] Loading global plugins from /Users/dnw/.dotfiles/.sbt/0.13/plugins
[info] Loading project definition from /Users/dnw/dev/intellij-scala/project
[info] Set current project to ScalaCommunity (in build file:/Users/dnw/dev/intellij-scala/)
```

**Comment by wsargent** [comment]
@dwijnand 

```
mkdir -p testproj/project
cd testproj
vi +b project/build.properties
```

```
sbt.version=0.13.5
```

Hit A to go to append to end of file.  Hit Ctrl-V and then Ctrl-M to enter a CR-LF.  Hit Escape, then :ZZ to exit and save the file.  

```
➜  project  vi +b build.properties
➜  project  cd ..
➜  test  sbt
:ownloading sbt launcher for 0.13.5
/sbt-launch.jartypesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.5
/sbt-launch.jarwsargent/.sbt/launchers/0.13.5
/sbt-launch.jar. Obtain the jar manually and place it at /Users/wsargent/.sbt/launchers/0.13.5
```

**Comment by dwijnand** [comment]
Still works.

Are you sure you're running the rebel cut of sbt? https://github.com/paulp/sbt-extras

I've no great one-liner to ask you to run, the first that comes to mind is `head $(which sbt)`
which for me returns this which indicates I'm using sbt-extras:

```
#!/usr/bin/env bash
#
# A more capable sbt runner, coincidentally also called sbt.
# Author: Paul Phillips <paulp@improving.org>

# todo - make this dynamic
declare -r sbt_release_version="0.13.8"
declare -r sbt_unreleased_version="0.13.8"
declare -r buildProps="project/build.properties"
```

as opposed to the non-sbt-extras homebrew install (`head /usr/local/bin/sbt`):

```
#!/bin/sh
if [ -f "$HOME/.sbtconfig" ]; then
  echo "Use of ~/.sbtconfig is deprecated, please migrate global settings to /usr/local/etc/sbtopts" >&2
  . "$HOME/.sbtconfig"
fi
exec "/usr/local/Cellar/sbt/0.13.7/libexec/sbt" "$@"
```

As a sidenote, thanks for the vim trick to inserting `^M`/`CR`/`0x0d`, I used `unix2dos` earlier.

**Comment by fommil** [comment]
I can't let Vim receive any praise without pointing out how much more awesome `emacs` is at this :stuck_out_tongue: `M-x set-buffer-file-coding-system`.

Or, `C-x RET f`

**Comment by jsuereth** [comment]
@wsargent What sbt launching file are you using?  This looks like an sbt-extras specific issue.  Please re-open the issue there.

**Comment by jsuereth** [comment]
@wsargent IF you're not using sbt-extras directly, I can guarantee the downloading bit isn't from this project.   Please let us know where you got your sbt script and open a bug there.  The scripts we support are downloadable from scala-sbt.org and located here:  https://github.com/sbt/sbt-launcher-package   IF you determine it is one of the scripts we promote, then we please re-open directly against that project.

**Comment by wsargent** [comment]
@jsuereth It's a paul phillips script https://gist.github.com/wsargent/044b734580d15d09ecb2

**Comment by eed3si9n** [comment]
So this is a dupe of paulp/sbt-extras#93

**Comment by dwijnand** [comment]
Thanks @wsargent for the gist of the script, that helped a lot.

You're using a older version of sbt-extras, as you can see by:
https://gist.github.com/wsargent/044b734580d15d09ecb2#file-sbt-L33
which predates the original pull request I mentioned earlier that specifically fixed this problem:
https://github.com/paulp/sbt-extras/pull/94/files#diff-eadc1bacb17aea28d29fefc19868b5e1

So you should update your script.

Alternatively you could consider the officially Typesafe supported script as mentioned above.

**Comment by fommil** [comment]
The official Typesafe one is rubbish! Paulp's script is far superior.
