### ISSUE TITLE
Better handling of javac options when invoking directly

### ISSUE THREAD

**Issue by jroper** [sbt/sbt#1968]
On upgrading to sbt 0.13.8:

```
[debug] Attempting to call com.sun.tools.javac.api.JavacTool@572e024c directly...
java.lang.IllegalArgumentException: invalid flag: -J-Xmx512m
    at com.sun.tools.javac.api.JavacTool.processOptions(JavacTool.java:206)
```

We need to increase the memory for javac, so if it does fork, we need it to use that setting, but if it doesn't fork, then it fails.  Some possibilities:
- Automatically exclude `-J` options, possibly warning if present
- Make it possible to check whether javac will be forked or not
- Provide a separate set of options that only get used when javac is forked

**Comment by nightwolfzor** [comment]
+1 I am having this problem. How Can i force javac to be forked? Really need to up Xmx

**Comment by nightwolfzor** [comment]
@jroper @jsuereth +1 I am having this problem. How Can i force javac to be forked? Really need to up Xmx

**Comment by sebigavril** [comment]
+1 I need this feature

**Comment by dwijnand** [comment]
FWIW I have a feeling this is fallout from https://github.com/sbt/sbt/pull/1702

**Comment by andrewdbate** [comment]
+1
