### ISSUE TITLE
The "Source for this page" footer link at scala-sbt.org is incorrect

### ISSUE THREAD

**Issue by AnthonyMastrean** [sbt/sbt#1969]
For example, the footer on this page 

http://www.scala-sbt.org/0.13.5/docs/Getting-Started/Running.html

Links to the non-existing page

https://github.com/sbt/sbt/raw/0.13.5/src/sphinx/Getting-Started/Running.rst

The page source appears to be

https://github.com/sbt/sbt.github.com/blob/master/0.13.5/docs/Getting-Started/Running.html

**Comment by eed3si9n** [comment]
Fixed in sbt 1 - https://github.com/sbt/website/pull/635
