### ISSUE TITLE
Same file can't be packaged multiple times

### ISSUE THREAD

**Issue by jroper** [sbt/sbt#1972]
On sbt 0.13.8 (haven't tested other versions), if I do:

``` scala
mappings ++= Seq(
  foo -> "foo1",
  foo -> "foo2"
)
```

Only `foo2` ends up in the packaged jar.  Both should be packaged.

**Comment by muuki88** [comment]
@jroper this is interesting. Is this still the case? On native-packager we haven't had any reports with such an issue yet.

**Comment by jroper** [comment]
Wouldn't have a clue, this was 3 years ago. I do remember having this issue, I don't remember where. Probably sbt-web. I think there was a place that we worked around it by creating an additional file on disk.

**Comment by jroper** [comment]
Ah, a Google search for the issue URL turned it up:

https://github.com/playframework/jnotify/blob/master/build.sbt#L36-L40

**Comment by jroper** [comment]
This bug still exists in sbt 1.2.0:

```scala
mappings in (Compile, packageBin) := {
  val readme = baseDirectory.value / "README.txt"
  Seq(
    readme -> "README1.txt",
    readme -> "README2.txt"
  )
}
lazy val extract = taskKey[Unit]("extract jar file")
extract := {
  IO.unzip((packageBin in Compile).value, target.value / "extracted")
}
```

```
$ sbt extract
[info] Loading project definition from /home/jroper/tmp/package-bug/project
[info] Loading settings for project package-bug from build.sbt ...
[info] Set current project to package-bug (in build file:/home/jroper/tmp/package-bug/)
[success] Total time: 0 s, completed 13/08/2018 11:59:14 AM
$ ls target/extracted/
META-INF  README2.txt
```

**Comment by jroper** [comment]
I guess the most likely cause is that `mappings in packageBin` is at some point converted to a map, losing multiple mappings for the same source file.

**Comment by muuki88** [comment]
Thanks for the fast reply and detailed research. I'll try to tackle this issue 😎
