### ISSUE TITLE
PathFinder.distinct is based on file name, not path

### ISSUE THREAD

**Issue by jroper** [sbt/sbt#1973]
If I have the following files:
- `a/b/foo.txt`
- `a/c/foo.txt`

And I do:

``` scala
file("a").***.distinct
```

I end up with only one file, even though there are two distinct paths, because the implementation of `distinct` matches on file name, not file path.

See https://github.com/playframework/playframework/issues/4208 for an example of issues this can cause.

**Comment by eed3si9n** [comment]
I was able to reproduce this.

``` scala
scala> import sbt._, Path._
import sbt._
import Path._

scala> file("a").***.distinct
res0: sbt.PathFinder = 

   a
   a/b
   a/c
   a/c/foo.txt
```

**Comment by eed3si9n** [comment]
This could actually be by design.

http://www.scala-sbt.org/0.13.7/api/index.html#sbt.PathFinder

> Create a PathFinder from this one where each path has a unique name. A single path is arbitrarily selected from the set of paths with the same name.

Maybe we should deprecate and rename to `distinctName`.

**Comment by jroper** [comment]
If it's by design, can you think of a an actual use case for that behaviour? I can't. In contrast, I can think of plenty of actual use cases of doing a full path distinct, including the one in Play that was impacted by this bug.

**Comment by eed3si9n** [comment]
Given `***` is recursive, it is confusing. But..  

`PathFinder` is a path's finder, not path itself, so you can think of it as a data structure only concerned of its `head` element. I can only think of contrived example like you have Ivy cache and Maven cache locally one called with potential overlap and you want to list out all the versions of a library. You can get union of two `PathFinder`s using `+++`.
