### ISSUE TITLE
testOnly has inclusion logic, but no exclusion one

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [sbt/sbt#1977]
I'd like testOnly to be able to exclude some test.
What about if I want to run all tests but one.

Suggested syntax:

```
testOnly com.mycompany.* -com.mycompany.package.*
```

With a minus prefix, it would be an exclusion.

I know that there a some framework specific tests, but they haven't worked for me easily.

**Comment by jsuereth** [comment]
You're in luck. CHeck out @matthewfarwell's pull request.

**Comment by dwijnand** [comment]
Fixed as of https://github.com/sbt/sbt/pull/1970. Released as a part of 0.13.9.

**Comment by DavidPerezIngeniero** [comment]
Thanks!
