### ISSUE TITLE
javaHome doesn't change JDK for Scala

### ISSUE THREAD

**Issue by pauldraper** [sbt/sbt#1978]
**build.sbt**

```
javaHome := Some(file("/usr/lib/jvm/java-7-openjdk-amd64"))
```

**project/build.properties**

```
0.13.7
```

**src/main/java/Example.java**

``` java
import java.nio.file;
```

**src/main/scala/Example.scala**

``` scala
import java.nio.file
```

```
$ java -version
java version "1.6.0_34"
OpenJDK Runtime Environment (IcedTea6 1.13.6) (6b34-1.13.6-1ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)
$ sbt compile
[info] Loading project definition from /home/paul/example/project
[info] Set current project to root-50 (in build file:/home/paul/example/)
[info] Compiling 1 Scala source and 1 Java source to /home/paul/example/target/scala-2.10/classes...
[error] /home/paul/example/src/main/scala/Example.scala:1: object file is not a member of package java.nio
[error] import java.nio.file
[error]        ^
[error] one error found
[error] (compile:compile) Compilation failed
[error] Total time: 2 s, completed Apr 16, 2015 10:02:24 PM
```

Remove the Scala source, and keep the Java source, and compilation works.

---

If this behavior is actually intentional -- that `javaHome` only works for Java, and not for Scala -- it'd at least be  good to document it.

Current documentation: "Selects the Java installation used for compiling and forking."

**Comment by eed3si9n** [comment]
Works as designed.

The only page in the documentation that mentions `javaHome` is the forking page, besides ".sbt build examples."
