### ISSUE TITLE
jrebel & sbt auto reload when scala file changed.

### ISSUE THREAD

**Issue by arden** [sbt/sbt#198]
i'm use jrebel & sbt that to auto reload when scala source file have changed.
but i have to open two console for do it,
one is：sbt ~compile    (for compile continuancelly.)
two is：sbt run              (for run main class)
but i'm won't to open console, because it's very bother.
i'm hope to only use  " sbt run " command can auto compile scala source file when that changed.

**Comment by jrudolph** [comment]
If I understand you correctly you may use the [sbt revolver plugin](https://github.com/spray/sbt-revolver) for this.

**Comment by harrah** [comment]
Covered by sbt-revolver.
