### ISSUE TITLE
URI-Referenced project cannot find commands from local project

### ISSUE THREAD

**Issue by jsuereth** [sbt/sbt#199]
Step 1:  Create a build file that has a URI referenced project
Step 2:  Create an onLoad script that add a command in the local project to the state
Step 3:  On SBT command line, type "project {uri}default-???" for the referenced project
Step 4: Change a setting or reload the project in some other manner.
Step 5: Read the error message.

Not sure if this one should be fixed or not, but it sure would be handy for me....

**Comment by jsuereth** [comment]
Note: I suspect that part of this is that "ThisBuild" type settings are not shared between the two projects (and perhaps rightly so!!!)

**Comment by harrah** [comment]
Need a reproducible test case.  There is too much ambiguity in the steps.
