### ISSUE TITLE
externalIvySettings and defining a publishTo resolver

### ISSUE THREAD

**Issue by enijns** [sbt/sbt#1999]
I'm trying to use a custom Ivy repository from an SBT build and after some fiddling with externalIvySettingsURL I am able to resolve dependencies from this repository.

In the ivysettings.xml we have a resolver chain defined that gives preference to some of the company's custom repos.

I'm having some issues in trying to publish to one of these ivy repositories though - I don't know how to reference the resolver to publish to.

I've had succes in publishing by commenting out the externalIvySettingsURL and redefining the resolver repo to publish to in sbt speak.

When I try to use both externalIvySettingsURL and the repo defined in sbt (using resolvers += Resolver.file("my-test-repo" ...) this doesn't seem to work anymore.
When running 'publish' I'm now getting the error message "(*:publish) Undefined resolver 'my-test-repo'"

Any ideas on how to resolve this issue?

**Comment by enijns** [comment]
I've learned this workaround from @jsuereth through typesafe's support:

> 1. In the ivysettings xml specify your publishing resolver with a specific name string
> 2. In the publishTo in sbt specify the exact same resolver with the exact same name. Ignore the errors. The one from ivysettings.xml should win.

With this in my build.sbt publishing now works fine:

```
publishTo := Some(Resolver.file("publishingResolverName"))
```

This is not the cleanest of workarounds, but at least it works. Maybe it's enough to have this documented somewhere?

**Comment by eed3si9n** [comment]
Closing this since we now default to using Coursier.
