### ISSUE TITLE
No subject alternative DNS name matching dl.bintray.com found for repo.typesafe.com

### ISSUE THREAD

**Issue by benmccann** [sbt/sbt#2004]
Add `addSbtPlugin("me.lessis" % "bintray-sbt" % "0.3.0")` to your `project/plugins.sbt`

> [error] Server access Error: java.security.cert.CertificateException: No subject alternative DNS name matching dl.bintray.com found. url=https://repo.typesafe.com/typesafe/ivy-releases/me.lessis/bintray-sbt/scala_2.10/sbt_0.13/0.3.0/ivys/ivy.xml
> [error] Server access Error: java.security.cert.CertificateException: No subject alternative DNS name matching dl.bintray.com found. url=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/me.lessis/bintray-sbt/scala_2.10/sbt_0.13/0.3.0/ivys/ivy.xml

**Comment by eed3si9n** [comment]
When you say "your `project/plugins.sbt`", you mean this happens with any arbitrary sbt project?

**Comment by benmccann** [comment]
Hmmm. I thought it would. But I just tried on Activator's "minimal-java" project and it didn't happen. I ran into this with the sbteclipse project, so I'm not sure if there's something weird with that project

**Comment by benmccann** [comment]
I just had a teammate hit this on another project with different libraries.

**Comment by eed3si9n** [comment]
Are you running Nexus?

**Comment by benmccann** [comment]
Nope

**Comment by benmccann** [comment]
@eed3si9n sorry, I messed up the initial posting. I can repro now. If you add `addSbtPlugin("me.lessis" % "bintray-sbt" % "0.3.0")` the the `project/plugins.sbt` of any project it should cause the error

**Comment by eed3si9n** [comment]
bintray-sbt 0.3.0 hasn't been published yet tho.

**Comment by benmccann** [comment]
Whoah, weird. I could have sworn I saw it in the repo this morning, but I can't find it now. However, the [project readme](https://github.com/softprops/bintray-sbt) definitely references 0.3.0 as being the current version. Did you accidentally bump the version in the README or do you think it got deleted from the repo somehow? https://github.com/softprops/bintray-sbt/commit/69583ba8355b0742a24983793e55860922b49a1e

**Comment by eed3si9n** [comment]
I bumped it up on purpose because I completely changed the plugin.

**Comment by benmccann** [comment]
Ah. Maybe better not to update the README until the version is published. Looks like I'm not the only one who got confused by it: https://github.com/softprops/bintray-sbt/issues/55

I can't reproduce this error message anymore. Maybe bintray flakiness? I'll close for now and check with my co-worker tomorrow to see if it's stopped for him as well
