### ISSUE TITLE
Holding developer's hand when autoplugin has no dependencies

### ISSUE THREAD

**Issue by 2m** [sbt/sbt#2013]
We have been recently bit by our creation - an AutoPlugin implementation that defines no dependencies (implemented here: https://github.com/akka/akka/pull/17397). This AutoPlugin did:

``` scala
val ValidatePR = config("pr-validation") extend Test
override lazy val projectSettings = inConfig(ValidatePR)(Defaults.testTasks) ++ ...
```

which in combination with defining no dependencies resulted in a `test` (with no configuration scope) task to be resolved to `pr-validation:test` instead of `test:test`.

[Here is](https://github.com/2m/sbt-sandbox/tree/05c38451cb3587eda9f714d10f2ab31ebb867799/autoplugin-no-requirements) a small reproducer that illustrates the situation. If you run `sbt test` you will see `Running custom tests` printed out.

Given all of the above, this issue is a request to have more insight into autoplugin application order.

**Comment by eed3si9n** [comment]
This should occur much less frequently in sbt 1 now that plugins depend on JvmPlugin by default.
