### ISSUE TITLE
[error] java.lang.IllegalStateException: impossible to get artifacts when data has not been loaded.

### ISSUE THREAD

**Issue by kukido** [sbt/sbt#2015]
Per discussion with @jsuereth opening a ticket for sbt project.

After switching from 0.12.4 to 0.13.8 of sbt we are getting the following error in the build:

```
[error] impossible to get artifacts when data has not been loaded. IvyNode = org.apache.httpcomponents#httpmime;4.2.3
[trace] Stack trace suppressed: run last playful2/*:update for the full output.
[error] (playful2/*:update) java.lang.IllegalStateException: impossible to get artifacts when data has not been loaded. IvyNode = org.apache.httpcomponents#httpmime;4.2.3
```

overrideDependencies did not work, the only workaround found was to explicitly include httpmime:4.2.3 in the list of dependencies. sbt issues a warning as the result, but at least the build goes through.

```
[warn] Multiple dependencies with the same organization/name but different versions. To avoid conflict, pick one version:
[warn] * org.apache.httpcomponents:httpmime:(4.2.3, 4.3.1)
```

It seem that similar issue was reported here:
https://github.com/sbt/sbt/issues/1598

And discussed here:
http://stackoverflow.com/questions/16614794/illegalstateexception-impossible-to-get-artifacts-when-data-has-not-been-loaded

**Comment by oscarbatori** [comment]
I also had this issue. In my case I added a dependency on Hbase 0.98.0-hadoop2, and the error introduced was "java.lang.IllegalStateException: impossible to get artifacts when data has not been loaded. IvyNode = junit#junit;4.10". The above mentioned workaround of introducing Junit as an explicit dependency did not work.

I was able to get the dependency to resolve by adding an exclusion rule to the Hbase dependency that excluded Junit.

**Comment by huitseeker** [comment]
I can confirm this happens on 0.13.8 as well.

**Comment by eed3si9n** [comment]
Does anyone have a reproducible build file I can use? It seems like it's related to transitive dependencies and manually added exclude introducing some kind of inconsistency.

**Comment by minroh** [comment]
I get the following error when I type `sbt assembly`:

`[error] (sql/compile:compile) java.lang.AssertionError: assertion failed: List(object package$DebugNode, object package$DebugNode)
[error] (hive/*:update) java.lang.IllegalStateException: impossible to get artifacts when data has not been loaded. IvyNode = org.scala-lang#scala-library;2.10.3
[error] Total time: 106 s, completed Feb 15, 2016 11:36:07 PM`

I have Mac (OS El Capitan) with spark 1.6.0, java 1.8.0_73 and sbt 0.13.9

sbt.build file reads:

```
name := "sbt-pom-reader"
organization := "com.typesafe.sbt"
sbtPlugin := true
publishMavenStyle := false

libraryDependencies ++= Dependencies.pluginDependencies

git.baseVersion := "1.0"

versionWithGit

scriptedLaunchOpts <+= version apply { v => "-Dproject.version="+v }

initialCommands :=
  """| import com.typesafe.sbt.pom._
     | import sbt._
     | val localRepo = file(sys.props("user.home")) / ".m2" / "repository"
     | val pom = loadEffectivePom(localRepo, file("src/sbt-test/simple-pom/can-extract-basics/pom.xml"))
     |""".stripMargin


scriptedSettings

scriptedLaunchOpts <+= version apply { v => "-Dproject.version="+v }

publishTo <<= (version) { v =>
  def scalasbt(repo: String) = ("scalasbt " + repo, "http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-" + repo)
  val (name, repo) = if (v.endsWith("-SNAPSHOT")) scalasbt("snapshots") else scalasbt("releases")
  Some(Resolver.url(name, url(repo))(Resolver.ivyStylePatterns))
}
```

[sbt_assembly_output.docx](https://github.com/sbt/sbt/files/132041/sbt_assembly_output.docx)

**Comment by eed3si9n** [comment]
@minroh That's a build file for sbt-pom-reader 1.0. I'm a bit confused as to why you're using that - https://github.com/sbt/sbt-pom-reader/blob/v1.0/build.sbt

**Comment by minroh** [comment]
@eed3si9n I know but that's the only type of build.sbt on my computer when I use `find` command. I installed it using `brew install sbt` inside my spark folder.

**Comment by eed3si9n** [comment]
@minroh Do you have `project/Build.scala` in your spark folder?

**Comment by minroh** [comment]
@eed3si9n No, In my project folder inside spark folder, I have the following and the subfolders do not contain Build.scala either. Scala and Spark folders are in the same level on my computer, and `which scala` outputs `/usr/local/bin/scala`

```
MimaBuild.scala     build.properties    target
MimaExcludes.scala  plugins.sbt
SparkBuild.scala    project
```

**Comment by eed3si9n** [comment]
@minroh I guess I should've said `project/*.scala`, since the exact name doesn't matter. So the reproduction step is git clone https://github.com/apache/spark and run assembly?

**Comment by minroh** [comment]
Yes. I downloaded spark from [Apache Spark Download page](http://spark.apache.org/downloads.html) instead of `git clone` and the version is the latest (1.6.0).

**Comment by eed3si9n** [comment]
@minroh I was able to reproduce this issue for the `hive` subproject of Spark 1.6.0.
At least for this particular case, a workaround can be bumping up the sbt version to 0.13.9, by editing `project/build.properties` to `sbt.version=0.13.9`.

**Comment by minroh** [comment]
@eed3si9n OMG, your fix worked! I spent so many hours trying to fix it myself but could not figure out a way. Thank you so much @eed3si9n!

**Comment by eed3si9n** [comment]
@Duhemm 

``` diff
diff --git a/src/java/org/apache/ivy/core/report/ResolveReport.java b/src/java/org/apache/ivy/core/report/ResolveReport.java
index 983f514..54479e5 100644
--- a/src/java/org/apache/ivy/core/report/ResolveReport.java
+++ b/src/java/org/apache/ivy/core/report/ResolveReport.java
@@ -232,7 +232,11 @@ public class ResolveReport {
         for (Iterator iter = dependencies.iterator(); iter.hasNext();) {
             IvyNode dependency = (IvyNode) iter.next();
             if (!dependency.isCompletelyEvicted() && !dependency.hasProblem()) {
-                artifacts.addAll(Arrays.asList(dependency.getSelectedArtifacts(artifactFilter)));
+                try {
+                    artifacts.addAll(Arrays.asList(dependency.getSelectedArtifacts(artifactFilter)));
+                } catch (Exception e) {
+                    e.printStackTrace();
+                }
             }
```

**Comment by vlad17** [comment]
Why isn't the workaround by @eed3si9n the solution (i.e., there's no pull request to resolve this issue)? There should be no breaking changes between minor versions of sbt.

**Comment by dragisak** [comment]
There seems to be a regression in 0.13.12 regarding to this bug. With our project, we don't get "impossible to get artifacts ..." with 0.13.11. But with 0.13.12, we do.

**Comment by fommil** [comment]
I also see a regression when combined with sbt-ensime, e.g. in our scripted tests

**Comment by paul-lysak** [comment]
With sbt 0.13.13 issue still persists (though for me error happens only when importing project in Intellij IDEA, not when building from console). With 0.13.11 it works just fine.
And I have excludeAll applied to dependencies:

```
libraryDependencies ++= Seq(...).map(
  /* avoids dependency conflict: https://github.com/holdenk/spark-testing-base/issues/116*/
  _.excludeAll(ExclusionRule(organization = "javax.servlet"))
)
```

which is a necessary condition for reproducing the issue, the project imports OK if i comment it out.

**Comment by kumarshirish** [comment]
Bumping the sbt version to 0.13.9 worked for me.
