### ISSUE TITLE
How should one try a nightly build?

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2020]
## steps

try using a nightly build
## problem
1. Nightlies are published on bintray: https://dl.bintray.com/sbt/ivy-snapshots/org.scala-sbt/sbt/
2. Launcher isn't going to hit it by default.
3. There's no documentation instructing how to point at it.
## expectation
1. Do we need to create proxy/forwarder for better URL like repo.scala-sbt.org/xxx?
2. Launcher should probably include that by default.
3. Document how to point at it.

**Comment by dwijnand** [comment]
For 1. https://dl.bintray.com/sbt/ivy-snapshots is addressable at https://repo.scala-sbt.org/scalasbt/ivy-snapshots

For 2. I've fixed this in sbt-extras: https://github.com/paulp/sbt-extras/pull/120

I don't understand 3.

Btw, there are gaps in the nightly builds.

**Comment by eed3si9n** [comment]
https://www.scala-sbt.org/1.x/docs/Nightly-Builds.html
