### ISSUE TITLE
provided transitive dependency mismatch should issue a warning

### ISSUE THREAD

**Issue by MasseGuillaume** [sbt/sbt#2021]
given
spray httpx 1.3.1 and spray json 1.3.1
when
sbt ... (some task at runtime)
actual
no eviction warning during update
crashes at runtime
expected
sbt warns me that spray-httpx 1.3.1 uses spray-json 1.2.5
https://github.com/spray/spray/blob/v1.3.1/project/Build.scala#L89

**Comment by suhailshergill** [comment]
@eed3si9n should this be closed given that we have eviction warnings ([`EvictionWarningOptions.full`](https://www.scala-sbt.org/0.13.11/sxr/sbt/EvictionWarning.scala.html#sbt;EvictionWarningOptions) seems to do the right thing)?
also, is there an option to promote eviction warnings into errors? `-Xfatal-warnings` in `project/` sub-build doesn't seem to cover it

**Comment by eed3si9n** [comment]
@suhailshergill Yes. Let's close this. Please open an issue for adding an option to escalate eviction warnings to errors.
