### ISSUE TITLE
C:\Program Files (x86)\sbt\\bin

### ISSUE THREAD

**Issue by jzhang28** [sbt/sbt#2023]
Environment: windows 10
Purpose: Practice Scala
Repro:
1. Download sbtxxx.msi, then install it. 
2. Go to computer "System Variables", edit path
3. See invalid path as C:\Program Files (x86)\sbt\bin  -- Note: two slash after sbt.

Repro Date: 5/17/2015

Expectation: you know how to do it, right?! :)

**Comment by jsuereth** [comment]
Yeah, this is some odd escaping issue when using WIX xml.

Would you mind reopening this against sbt/sbt-launcher-packager?  That's where the windows MSI code is defined.

Thanks!
