### ISSUE TITLE
unresolved dependency on heroku

### ISSUE THREAD

**Issue by fdietze** [sbt/sbt#2024]
Hi,

I just wanted to tell you about a problem I had and the workaround I found:

When pushing my Play 2.3.9 app (one sbt subproject) to Heroku, sbt was not able to resolve some dependencies from typesafe repositories. On my pc it built. I didn't have any local repositories installed. Adding resolvers to the projects/subprojects didn't help.

The issue was solved by moving the subproject into the root project.

I found several other people having similar problems:
https://stackoverflow.com/questions/25104336/play-2-2-2-heroku-unresolved-dependencies

Is this a bug?

**Comment by jsuereth** [comment]
It looks like it may have been a bug in an early release of sbt (0.13.0).   Since migrating to 0.13.5 fixes it, I'd say stick with that for now.

Note: Scala 2.10.2 has beena  source of issues on TravisCI due to how maven-central is currently hosting those artifacts.
