### ISSUE TITLE
Consider using sbt-mima to mechanically verifying we're not breaking bincompat.

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#2037]
I had a look and didn't see this mentioned in any issue, pull request or mailing list thread.

Thoughts?

**Comment by dwijnand** [comment]
I've not personally setup sbt-mima before, and I'm not intimate with sbt's build, but I'm willing to have a go at this, but I guess with precompiled what-not I'll hit complications..

**Comment by eed3si9n** [comment]
The problem is that with 0.13 codebase the boundary between internal implementation vs API is blurred, so we occasionally do break the bincompat. For 1.0 code base I really hope we can do MIMA or publish API JAR so compatibility is enforced by the type system.

**Comment by dwijnand** [comment]
I understand, but doesn't that mean just adding exceptions as a part of the relevant pull request?

**Comment by eed3si9n** [comment]
You're right, and we can time-box and try it, but ultimately, if we had X hours I think the effort would be better spent on modularizing 1.0 code base.

**Comment by dwijnand** [comment]
So from the conversation on gitter, we don't want to do this until 1.0, as it'll be more of a burden to maintain and workaround in 0.13, given the legacy state of 0.13.

So I've pushed out what I was working on https://github.com/dwijnand/sbt/tree/add-sbt-mima, and labeled this for 1.0, as I think we should have this done by the first final 1.0 release.
