### ISSUE TITLE
Autoreload build definition

### ISSUE THREAD

**Issue by pauldraper** [sbt/sbt#2045]
Users frequently forget to reload after modifying the build definition. Or pulling SCM changes that modified it, etc.

I don't know of a common case in which you would want to use a build definition different than the one saved to disk.

One solution is to reload in interactive mode input if any sources have changed. This would be checked when "user input" happens...probably when running a command (or it could be for tab completion too...I'm not sure on that one).

**Comment by eed3si9n** [comment]
Duplicate in spirit of #241
