### ISSUE TITLE
Change publishTo type from setting Key to task Key

### ISSUE THREAD

**Issue by fredericnowak** [sbt/sbt#2059]
I want to use the credentials taskKey in the definition of the publishTo resolver (S3 Resolver) but I can't.
Is there another way to do this ?

**Comment by eed3si9n** [comment]
Not during 0.13.x for bin compat reasons. Needs some thinking if we can for future version.

**Comment by fredericnowak** [comment]
Ok Thx

2015-06-23 8:13 GMT+02:00 eugene yokota notifications@github.com:

> Not during 0.13.x for bin compat reasons. Needs some thinking if we can
> for future version.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sbt/sbt/issues/2059#issuecomment-114374574.

## 

Frédéric NOWAK
96 rue Nollet
75017 Paris
06 11 14 62 46
