### ISSUE TITLE
Triggered execution broken in some cases in sbt 0.11.0

### ISSUE THREAD

**Issue by ijuma** [sbt/sbt#206]
So far I have only been able to reproduce it in multi-module projects. I don't have an isolated test case, but I have instructions that involve an open-source project. Hopefully that is good enough. Instructions follow:
1. git clone git://github.com/ijuma/spark.git
2. cd spark
3. git checkout -t origin/sbt-0.11
4. sbt
5. ~ test:products
6. edit core/src/main/scala/spark/ParallelCollection.scala (or any other file)

Expected: Edited file triggers recompilation.
Actual: No recompilation happens.

It goes without saying that this is a major problem for all of us who rely on SBT to continuously compile our code.

**Comment by harrah** [comment]
As a workaround, put this in your shared settings:

``` scala
watchTransitiveSources <<= 
  Defaults.inDependencies[Task[Seq[File]]](
    watchSources.task, const(std.TaskExtra.constant(Nil)), aggregate = true, includeRoot = true) apply {
      _.join.map(_.flatten)
  }
```

**Comment by ijuma** [comment]
Thanks for the quick fix and even more for the workaround. Saves me a few reverts at work. :)
