### ISSUE TITLE
SBT should respond gracefully on unsupported JDK versions

### ISSUE THREAD

**Issue by russel** [sbt/sbt#2061]
SBT currently throws an exception and terminates when started using JDK9, working fine with JDK8. SBT should detect the JDK version and terminate gracefully if it is known not work on that JDK version.

**Comment by dwijnand** [comment]
Can you detail what exception you're seeing please?

**Comment by eed3si9n** [comment]
@dwijnand See #2060.

```
[error] scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
```

**Comment by SethTisue** [comment]
this ticket is obsolete now that JDK 9 is supported, yes?

**Comment by eed3si9n** [comment]
Yes. Let's close it.
