### ISSUE TITLE
Snapshot dependencies with test classifiers are not updated

### ISSUE THREAD

**Issue by benjaminparker** [sbt/sbt#2063]
The issue described in 

https://github.com/sbt/sbt/issues/641

Is still present in sbt 0.13.8

**Comment by jsuereth** [comment]
Are you using any of the new features? (sbt-maven resolver plugin or cached resolution)?

**Comment by benjaminparker** [comment]
No. I'm not

Ben Parker
(sent from my iPhone)

**Comment by eed3si9n** [comment]
There's actually a open issue #1676 on this.
