### ISSUE TITLE
sbt launcher needs a shebang

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#2064]
Docs here

http://www.scala-sbt.org/0.13/tutorial/Manual-Installation.html#Unix

don't start the file with a `#!/bin/bash` which means the script doesn't work when launched from emacs (and possibly other locations).

**Comment by jsuereth** [comment]
Please reopen this against the sbt/website project (or just issue a PR)

**Comment by fommil** [comment]
I think somebody did already.
