### ISSUE TITLE
`:replay options` breaks printing input

### ISSUE THREAD

**Issue by hseeberger** [sbt/sbt#2065]
The REPL commands `:replay` and `:reset` take optional compiler settings. When provided, the compiler is recreated and hence classes reloaded. When the REPL is started from sbt via `console`, such an action leads to no more input shown, i.e. you can't see what you type.

**Comment by jsuereth** [comment]
Sounds like the REPL is trying to reinitialize JLINE in a faulty way....  

Which version of Scala, and thanks for reporting.

**Comment by hseeberger** [comment]
Scala 2.11.6 (it has to be 2.11, else `:replay <options>` won't recreate the compiler).

**Comment by hseeberger** [comment]
BTW, if you run the REPL standalone, i.e. not from sbt, that stuff works. Therefore I have created this ticket against sbt.

**Comment by jsuereth** [comment]
Yeah, I'm guessing it's related to jline reinitializatoin. Sbt customized the REPL so that it doesn't try to override the STTY session completely, so sbt can take it back over later.  I'd guess this new feature doesn't account for that.

**Comment by dwijnand** [comment]
No longer broken in sbt 1 (tested on 1.1.1):

```scala
> console
[info] Updating ...
[info] Done updating.
[info] Starting scala interpreter...
Welcome to Scala 2.12.4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_144).
Type in expressions for evaluation. Or try :help.

scala> System.currentTimeMillis
res0: Long = 1519752991532

scala> :replay
Replaying: System.currentTimeMillis
res0: Long = 1519752993334


scala> 2
res1: Int = 2
```
