### ISSUE TITLE
Syntax highlighting in scalac errors

### ISSUE THREAD

**Issue by japgolly** [sbt/sbt#2066]
It would be great if SBT applying a few ansi colours to scalac output to make it easier to read. When I get 50 messgaes in a row like this ↓ it's pretty hard to even see which file the error's in.

```
[error] /home/golly/XxxXxx/projects/xxxxx/Code/webapp-client/src/main/scala/xxxxx/webapp/c
lient/app/ui/xxxx/edit/ColumnEditors.scala:136: not enough arguments for method apply: (in
itial0: Seq[xxxxx.webapp.base.data.Pubid], subjectId: xxxxx.webapp.base.data.XxxId, column
: xxxxx.webapp.client.app.ui.Xxxtable.Column, project: japgolly.scalajs.react.extra.Px[xxx
xx.webapp.base.data.Project], textSearch: japgolly.scalajs.react.extra.Px[xxxxx.webapp.bas
e.text.TextSearch], lookupM: japgolly.scalajs.react.extra.Px[xxxxx.base.util.Must[xxxxx.we
bapp.client.app.ui.Xxxtable.edit.ImplicationEditor.Lookup]], update: xxxxx.webapp.client.a
pp.ui.Xxxtable.Cell.State => scalaz.effect.IO[Unit], finish: xxxxx.webapp.client.app.ui.Xx
xtable.edit.EditResult[xxxxx.base.util.SetDiff[xxxxx.webapp.base.data.XxxId]] => scalaz.ef
fect.IO[Unit])xxxxx.webapp.client.app.ui.Xxxtable.Cell.State in object ImplicationEditor.
[error] Unspecified value parameter finish.
```

Btw, is it possible to add this as setting in my own SBT config? 
I was hoping to intercept all error logging messages and just apply a few regexs it doesn't seem possible to modify the global logger. All I could find was info on `extraLoggers`, where as in this case you'd wouldn't want to _add_ loggers, just replace the global one.

**Comment by jsuereth** [comment]
It's called "compilerReporter", and you can provide your own implementation which will output ANSI art if you like :)

Here's our implementation: https://github.com/sbt/sbt/blob/9ee8299383afb8c64f175acd9d3cb8648be519b6/compile/src/main/scala/sbt/LoggerReporter.scala#L46-L135

And here's the key to hook: 
https://github.com/sbt/sbt/blob/9ee8299383afb8c64f175acd9d3cb8648be519b6/main/src/main/scala/sbt/Keys.scala#L373-L374

It's still marked experimental, but that will go away once sbt-server is stabilized.  It looks like this has to be a permanent hook in the build.

**Comment by japgolly** [comment]
@jsuereth Thanks, it needed a bit of hack to work to get around the `private[sbt]` but otherwise I created my own and got it set.

There's a problem though in that it doesn't seem to be used. I've got:

``` scala
compilerReporter := Some(new MyLoggerReporter(5, streams.value.log)),
compilerReporter in Compile := Some(new MyLoggerReporter(5, streams.value.log)),
```

and I can confirm it's set...

```
webapp-base> show compile:compilerReporter
[info] Some(sbt.CustomLoggerReporter@9a183e7)
```

but when I run `compile`, the output is just the same as before. The logger isn't used at all. (Not even initialised until I call `show`.) Is there something else needed for this setting to take effect?

**Comment by laughedelic** [comment]
Any solutions here?

**Comment by dansanduleac** [comment]
I suspect this is because `Defaults.scala:849` (in sbt 0.13.9) scopes `compilerReporter` under both the `Compile` configuration _and_ the `compile` task. You can see this using `inspect` and notice that for `compile:compilerReporter` there are no reverse dependencies and hence it's not used by anything, whereas `compile:compile::compilerReporter` tells a different story:

```
> inspect compile:compilerReporter
[info] No entry for key.
...

> inspect compile:compile::compilerReporter
[info] Task: scala.Option[xsbti.Reporter]
[info] Description:
[info]  Experimental hook to listen (or send) compilation failure messages.
[info] Provided by:
[info]  {file:/data/home/dsandul/testProj/}testProj/compile:compile::compilerReporter
[info] Defined at:
[info]  (sbt.Defaults) Defaults.scala:849
[info] Reverse dependencies:
[info]  testProj/compile:compileIncremental
...
```

So I'd just set

``` scala
compilerReporter in (Compile, compile) := Some(new MyLoggerReporter(5, streams.value.log))
```

**Comment by eed3si9n** [comment]
I think this should be something implemented in Scala itself.
