### ISSUE TITLE
sbt 0.13.8 start stuck on centos 7 with jdk 1.7.0_40

### ISSUE THREAD

**Issue by tonydeck** [sbt/sbt#2067]
I installed sbt 0.13.8 for linux on CentOS 7 and I also installed jdk 1.7.0_40. when I run "sbt". It just displayed "Getting org.scala-sbt sbt 0.13.8 ..." and hanged with no further information.
could you give me some clue how to debug to find why?
thanks.
Tony

**Comment by tonydeck** [comment]
I does not use proxy. As it even did not go into the command mode ">", how can I get the log?
thanks.
Tony

**Comment by eed3si9n** [comment]
One thing you could try is creating `project/debug.sbt`:

``` scala
logLevel := Level.Debug
```

**Comment by tonydeck** [comment]
1. I set the debug.sbt. 
2. as I current event cannot go into the command mode ">", where I can see the debug log?

**Comment by tonydeck** [comment]
currently, when I input 'sbt'. it only displays "Getting org.scala-sbt sbt 0.13.8 ..." and hang. It is not relate to any project. how can I debug to get more log for your investigation?
thanks.
Tony

**Comment by eed3si9n** [comment]
If you have the problem with the build itself, the debug log should display on the terminal.

Another thing to try:

``` sh
$ mkdir debugsbt
$ cd debugsbt
$ wget https://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar
$ wget https://raw.githubusercontent.com/sbt/sbt/v0.13.8/src/main/conscript/sbt/launchconfig
$ touch debugsbt.sh
$ chmod +x debugsbt.sh
```

Edit `debugsbt.sh` to be:

``` sh
#/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
java -Xmx2G -jar $DIR/sbt-launch.jar @$DIR/launchconfig "$@"
```

Append the following lines to `launchconfig`:

``` yml
[log]
  level: debug
```

Try using `debugsbt.sh` instead the `sbt` command.

**Comment by tonydeck** [comment]
I've done with the guideline you provided. and got the log file. where can I attache the log file? actually it is the information in the log file.

```
------ start of the log file -------
[debug] Parsed configuration: LaunchConfiguration(auto,IvyOptions(Some(/root/.ivy2),Classifiers(List(),List()),List(Predefined(local,false), Ivy(typesafe-ivy-releases,https://repo.typesafe.com/typesafe/ivy-releases/,[organization]/[module]/[revision]/[type]s/[artifact](-[classifier]).[ext],[organization]/[module]/[revision]/[type]s/[artifact](-[classifier]).[ext],false,true,false,false), Predefined(maven-central,false)),List(sha1, md5),false),Application(org.scala-sbt,sbt,sbt.version[0.13.8],sbt.xMain,List(xsbti, extra),Disabled,[Ljava.io.File;@1cfcc426),BootSetup(/root/.sbt/boot,true,/opt/debugsbt/project/build.properties,Search(none,List()),,false,false),xsbt.boot.Logging@16b1a9a8,List(),None)
[debug] Resolved configuration: LaunchConfiguration(auto,IvyOptions(Some(/root/.ivy2),Classifiers(List(),List()),List(Predefined(local,false), Ivy(typesafe-ivy-releases,https://repo.typesafe.com/typesafe/ivy-releases/,[organization]/[module]/[revision]/[type]s/[artifact](-[classifier]).[ext],[organization]/[module]/[revision]/[type]s/[artifact](-[classifier]).[ext],false,true,false,false), Predefined(maven-central,false)),List(sha1, md5),false),Application(org.scala-sbt,sbt,0.13.8,sbt.xMain,List(xsbti, extra),Disabled,[Ljava.io.File;@1cfcc426),BootSetup(/root/.sbt/boot,true,/opt/debugsbt/project/build.properties,Search(none,List()),,false,false),xsbt.boot.Logging@16b1a9a8,List(),None)
Getting org.scala-sbt sbt 0.13.8 ...
--- end of log file ---
```

**Comment by tonydeck** [comment]
you can see that in the end, the message of "Getting org.scala-sbt sbt 0.13.8..." appeared with no further information.

**Comment by tonydeck** [comment]
Hi, 
I found the problem. it seems that it cannot access "repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.8/sbt-0.13.8.jar" when it try to get the file. please check the "update.log" in the .sbt directory. 

I will send you the directories of .sbt and .ivy2 through email.
thanks
Tony

**Comment by tonydeck** [comment]
Hi, eed3si9n,I attach the log files for you. it is on sbt @2067. please check the update.log from .sbt directorythanks.Tony

Date: Fri, 19 Jun 2015 08:24:47 -0700

**Comment by eed3si9n** [comment]
`repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.8/sbt-0.13.8.jar` does not exist. Our stuff is under `repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/`.

**Comment by eed3si9n** [comment]
Also the email you're getting is from Github, so attaching files to it won't work. Try https://gist.github.com/?

**Comment by tonydeck** [comment]
It seems that https://gist.github.com/ only gets the source code and it cannot get .zip file. where can I upload the zip file for the sbt?
thanks.
Tony

**Comment by eed3si9n** [comment]
Sending me the entire content of your `.sbt` and `.ivy` is actually not very helpful.
What would help is the exact step that I can reproduce the issue on my machine - https://github.com/sbt/sbt/blob/0.13/CONTRIBUTING.md

**Comment by tonydeck** [comment]
what I did is as follows.
0. env. centos 7.0. jdk 1.7.0_40
1. yum install sbt
2. run sbt
3. I got the message "Getting org.scala-sbt sbt 0.13.8 ..." and pending...

I did not use proxy.
just let me know if you need more data/log.
thanks a lot.

**Comment by eed3si9n** [comment]
@tonydeck Thanks for the steps!

Anyone from the community want to diagnose what's going on using CentOS 7?

**Comment by eed3si9n** [comment]
Another possibility is that Bintray is slow from Shanghai, assuming that's where you're running it.
You could try changing `https` to `http` in for `debugsbt` - https://raw.githubusercontent.com/sbt/sbt/v0.13.8/src/main/conscript/sbt/launchconfig

**Comment by tonydeck** [comment]
regarding to the debugsbt. I can download with below url you sent me.
$ wget https://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar
$ wget https://raw.githubusercontent.com/sbt/sbt/v0.13.8/src/main/conscript/sbt/launchconfig

the problem was that when run the "debugsbt", it still displays the message "getting ..." and pending.

**Comment by tonydeck** [comment]
I tried other way. I used manual install based on the guideline from sbt. The result is the same.
http://www.scala-sbt.org/0.13/tutorial/Manual-Installation.html (the manual installation guide.)
I checked update.log and found the same error message. I think the reason is the same, i.e., the url to download is not correct. (https://repo1.maven.org/maven2...). 
so I think the solution would be change the url to a correct url. can you tell what configuration file to deal with the url and what is the correct url I need to input?
thanks.

----begin of the error message----

```
 ==== Maven Central: tried

          https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.8/sbt-0.13.8.pom

          -- artifact org.scala-sbt#sbt;0.13.8!sbt.jar:

          https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.8/sbt-0.13.8.jar

                ::::::::::::::::::::::::::::::::::::::::::::::

                ::          UNRESOLVED DEPENDENCIES         ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: org.scala-sbt#sbt;0.13.8: not found

                ::::::::::::::::::::::::::::::::::::::::::::::


:::: ERRORS
        Server access Error: Connection refused url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.8/ivys/ivy.xml

        Server access Error: Connection refused url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.8/sbt-0.13.8.pom

        Server access Error: Connection refused url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.8/sbt-0.13.8.jar
```

----- end of error message.

**Comment by eed3si9n** [comment]
```
Server access Error: Connection refused url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.8/ivys/ivy.xml
```

That's a problem. Could you

```
$ wget https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.8/ivys/ivy.xml
```

**Comment by tonydeck** [comment]
how can I use the command when running sbt? the message is displayed when I run 'sbt'. as I said the message is from 'update.log'. so I need to modify the url to the correct one somewhere. correct? the question is which file I need to update before I run 'sbt'. or I just need to download the file somewhere?
thanks.

**Comment by eed3si9n** [comment]
I am just trying to find out if your machine can hit `https://repo.typesafe.com/`.

If you want to change where sbt gets it JAR from you change `launchconfig` file.
https://github.com/sbt/sbt/issues/2067#issuecomment-113547575

**Comment by tonydeck** [comment]
I found that the following 3 url  would be invoked to download. but the url  begins with "repo1.maven..." will display 404 error. I think this cause the problem. in the launchconfig file. I only saw the 'maven-central' but there is nowhere to define the url of maven_central. any way out?
thanks.
--- begin of launch config on maven-central ----

```
[repositories]
  local
  typesafe-ivy-releases: https://repo.typesafe.com/typesafe/ivy-releases/, [organization]/[module]/[revision]/[type]s/[artifact](-[classifier]).[ext], bootOnly
  maven-central
```

---- end of launch config on maven-central----

------ begin of error message on the repository ----

```
"Server access Error: Connection refused url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.8/ivys/ivy.xml
        Server access Error: Connection refused url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.8/sbt-0.13.8.pom
        Server access Error: Connection refused url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.8/sbt-0.13.8.jar"
```

--- end of error message on the repository ----

**Comment by tonydeck** [comment]
I found the issue. @eed3si9n you are correct. it is relevant to the network connection problem. https connection is very slow compared with http connection.
env: cent os 70, scalar 2.10.4. sbt application 0.13.8 installed through "yum install"
1. When start 'sbt', it will display "Getting org.scala-sbt sbt 0.13.8 ...". actually it is getting update "jar" files and copied to $HOME/.ivy2 in the relevant directories. the update message can be seen in real from $HOME/.sbt/boot/update.log.
2. I found the updated jar files constantly downloaded with failure. so here is what I've done.
1) I add proxy in the "/usr/share/sbt-launcher-packaging/bin/sbt-launch-lib.bash" by modify the following lines.

```
"execRunner "$java_cmd" \
    ${SBT_OPTS:-$default_sbt_opts} \
    $(get_mem_opts $sbt_mem) \
          ${JAVA_OPTS} -Dhttp.proxyHost=xxxx -Dhttp.proxyPort=xxxx \
    ${java_args[@]} \
    -jar "$sbt_jar" \
    "${sbt_commands[@]}" \
    "${residual_args[@]}"
```

“ by adding "-Dhttp.proxyHost=xxxx -Dhttp.proxyPort=xxxx -Dhttp.proxyUser=username -Dhttp.proxyPassword=mypassword" (original line does not have the proxy direction., if 
2) add env variable "export username:password@http_proxy=<host address>:<port>" (if you do not have user name/password, just remove the username:password@ ).
3) in this case, you can see that the sbt is downloading the jar file in its first run. but it still often downloaded with failure. but you will easily find where the jar file will go to. just go the directory under the $HOME/.ivy2/cache directory and download the jar file manually. with 'wget'. one important thing is that the original downloading through sbt uses the 'https'. you just use 'http' in wget instead. it will be much faster than using 'https'. after your downloading manually, just start 'sbt' again to see whether you need download manually for the next jar module.
4) in my case. I found that even I downloaded all the jar files with the directory. it will still have error messages. I refered message "https://github.com/mpeltonen/sbt-idea/issues/187"
and copied scala-reflect.jar back to $HOME/root/.sbt/boot/scala-2.10.4/lib. 
5) then the "sbt" can start now.

Suggestion. Could in the future, sbt update package can be downloaded and there have somewhere that we can configure to use the downloaded update package so that make the installation and configuration sbt much easily.
thanks.
Tony

**Comment by tonydeck** [comment]
@eed3si9n I will close the issue. and thanks a lot for your kindly help and direction.
Tony.

**Comment by eed3si9n** [comment]
Typesafe Activator comes with all the JARs up front - http://www.typesafe.com/get-started

**Comment by jackeylu** [comment]
Thanks for the help. and I found it could be helpful to know that, we can set the proxy in conf/sbtconfig.txt file in the $SBT_HOME. like this,
-Dhttp.proxyHost=proxy.xxx.xxx
-Dhttp.proxyPort=8080

**Comment by BIPASHAPRAMANIK** [comment]
when i downloaded sbt , with that openjdk automatically installed .
So, is there any way to install sbt without openjdk?
