### ISSUE TITLE
Incremental compiler doesn't detect JDK change

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2074]
1. `compileOrder := CompileOrder.JavaThenScala`
2. I'm using all Java project
3. Compile using Java 7
4. Exit sbt, and change to Java 6
5. Compile again

It looked like the compiler didn't noticed that the underlying JDK was changed.
I kept getting "Unsupported major.minor version 51.0" on the consuming side.

**Comment by retronym** [comment]
Related: https://github.com/sbt/zinc/issues/825

**Comment by retronym** [comment]
I suggest that previous products (ie generated class files) should be considered invalid after a JDK change.

**Comment by eed3si9n** [comment]
sbt does initialize extraIncOptions as follows:

https://github.com/sbt/sbt/blob/9e98b6daa1c5021b852661feb2a5b263bda9ce67/main/src/main/scala/sbt/Defaults.scala#L190
