### ISSUE TITLE
AutoPlugin added resourceGenerators being dropped

### ISSUE THREAD

**Issue by tmandke** [sbt/sbt#2081]
I am trying to write an autoplugin that provides some resource generation. The task added by the autoplugin gets removed. Here is a minimum Build.scala needed to reproduce the problem

``` scala
import sbt.Keys._
import sbt._

object TestP extends AutoPlugin {
  override def projectSettings: Seq[Setting[_]] = Seq(
    resourceGenerators in Compile <+= Def.task {
      println("resource generated in plugin")
      Nil
    }
  )
}


object Build extends Build {
  lazy val test123 = Project(id = "test123", base = file("."))
    .enablePlugins(TestP)
    .settings(resourceGenerators in Compile <+= Def.task {
      println("resource generated in settings")
      Nil
    })
}
```

Produces

```
10:26 $ sbt test
[info] Loading project definition from /Users/tejas.mandke/code/test123/project
[info] Set current project to test123 (in build file:/Users/tejas.mandke/code/test123/)
resource generated in settings
[success] Total time: 0 s, completed Jun 28, 2015 10:26:33 AM
```

If you look at the second last line it only prints out "resource generated in settings" but not the "resource generated in plugin".

**Comment by eed3si9n** [comment]
You're silently depending on `JvmPlugin`, which adds `resourceGenerators`.
Note all sbt's built-in keys are added via auto plugins as well.
You likely need to declare `requires` to `JvmPlugin` so yours run _after_ `JvmPlugin` wipes out the `resourceGenerators`.

**Comment by yanns** [comment]
Thx @eed3si9n for the hint!
I was looking for this cause for so long time.

**Comment by dwijnand** [comment]
Could we close this, in favour of discussing the meta-problem in #2082?
