### ISSUE TITLE
Auto plugins should depend on JvmPlugin out of the box

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2082]
Since the launch of AutoPlugin there's been confusions caused by auto plugins not depending on `JvmPlugin` by default, most recently #2081.
For 100% of the plugin authors, it's most natural to assume that initialization of the so-called built-in keys have already taken place, and that they can safely call `+=` on them.
Even for the plugin authors wishing to substitute the default behaviors, they should explicitly override `requires`. By adopting affordance principle (aka principle of least surprise/resistance) auto plugins should depend on `JmvPlugin` out of the box.

Likely we need to do this when we can break semantic compat in 1.0.

**Comment by muuki88** [comment]
+1 for this. I hit this two times now.

**Comment by pdalpra** [comment]
+1 for me too, scratched my head for some time before understanding that my plugin was being initialized too soon.

**Comment by daniel-trinh** [comment]
+1, had no idea why the auto plugin behavior wasn't working in sbt-scalariform until this was recommended to me

**Comment by jsuereth** [comment]
Sounds like we should do it:). Thanks for the feedback
