### ISSUE TITLE
sbt dependency url is different from sbt-repos

### ISSUE THREAD

**Issue by joelin** [sbt/sbt#2086]
Hi all
     i am new guys in sbt and scala. i meet some trouble when compile some project.
sbt repos setting eg.

```
my-ivy-repo: http://localhost/, [organization]/[module]/[revision]/[type]s/[artifact](-[classifier]).[ext]
```

the problem is:
the sbt resolve the plugin from this url: com.twitter/scrooge-sbt-plugin/3.13.0/ivys/ivy.xml
but the truly url is like this: com.twitter/scrooge-sbt-plugin/scala_2.10/sbt_0.13/3.13.0/ivys/ivy.xml
so i can't download the scrooge plugin from my proxy repo site.
what's wrong ？

**Comment by eed3si9n** [comment]
The sbt issue tracker is not a support system. Please see [how can I get help?](http://www.scala-sbt.org/community.html#how-can-I-get-help)

**Comment by joelin** [comment]
thx！

**Comment by joelin** [comment]
thx! I found the problem. I set the sbt-tools and typesafe in a nexus group repos.
but them are different. sbt-tools:https://dl.bintray.com/sbt/sbt-plugin-releases/ has the sbt version and scala version in the path.
so resolve this problem. i need set the repos like this 

```
my-ivy-typesafe-repo: http://localhost/, [organization]/[module]/[revision]/[type]s/[artifact](-[classifier]).[ext]
my-ivy-sbt-tools-repo: http://localhost/,[organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
```

**Comment by eed3si9n** [comment]
awesome. I'm glad you found the issue :)
