### ISSUE TITLE
Fail to download the first SNAPSHOT publish to Artifactory

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#2088]
In trying to figure out #1750 I've hit this snag. Asides from it getting in the way, I wonder if it's indicative of anything, such as my setting up wrong.
## steps

1) Setup:

```
sbt.version=0.13.8
```

Dependency project, `sbt-gh1750-bippy`:

``` scala
organization := "com.dwijnand"
        name := "sbt-gh1750-bippy"
     version := "0.1.0-SNAPSHOT"
scalaVersion := "2.11.7"

val localRelease  = "local-release"  at "http://localhost:8081/artifactory/libs-release-local"
val localSnapshot = "local-snapshot" at "http://localhost:8081/artifactory/libs-snapshot-local"

publishTo := Some(if (isSnapshot.value) localSnapshot else localRelease)
credentials := Seq(Credentials("Artifactory Realm", "localhost", "admin", "password"))
```

Dependee project, `sbt-gh1750-myapp`:

``` scala
organization := "com.dwijnand"
        name := "sbt-gh1750-myapp"
     version := "0.1.0-SNAPSHOT"
scalaVersion := "2.11.7"

val localRelease  = "local-release"  at "http://localhost:8081/artifactory/libs-release-local"
val localSnapshot = "local-snapshot" at "http://localhost:8081/artifactory/libs-snapshot-local"

resolvers += localSnapshot

libraryDependencies += "com.dwijnand" %% "sbt-gh1750-bippy" % "0.1.0-SNAPSHOT"
```

2) In `sbt-gh1750-bippy`, `publish`
3) In `sbt-gh1750-myapp`, `reload` and `update`
## problem

`update` outputs:

```
[info] Updating {file:/Users/dnw/Desktop/sbt-gh1750-myapp/}sbt-gh1750-myapp...
[info] Resolving jline#jline;2.12.1 ...
[warn]  [NOT FOUND  ] com.dwijnand#sbt-gh1750-bippy_2.11;0.1.0-SNAPSHOT!sbt-gh1750-bippy_2.11.jar (4ms)
[warn] ==== local-snapshot: tried
[warn]   http://localhost:8081/artifactory/libs-snapshot-local/com/dwijnand/sbt-gh1750-bippy_2.11/0.1.0-SNAPSHOT/sbt-gh1750-bippy_2.11-0.1.0-20150706.083249-1.jar
[warn]   http://localhost:8081/artifactory/libs-snapshot-local/com/dwijnand/sbt-gh1750-bippy_2.11/0.1.0-SNAPSHOT/sbt-gh1750-bippy_2.11-0.1.0-SNAPSHOT.jar
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::              FAILED DOWNLOADS            ::
[warn]  :: ^ see resolution messages for details  ^ ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.dwijnand#sbt-gh1750-bippy_2.11;0.1.0-SNAPSHOT!sbt-gh1750-bippy_2.11.jar
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[trace] Stack trace suppressed: run last *:update for the full output.
[error] (*:update) sbt.ResolveException: download failed: com.dwijnand#sbt-gh1750-bippy_2.11;0.1.0-SNAPSHOT!sbt-gh1750-bippy_2.11.jar
[error] Total time: 1 s, completed 06-Jul-2015 09:34:48
```
## expectation

No error, downloads the published snapshot on `update`.
## note

It feels to me like it's related to the fact that `http://localhost:8081/artifactory/libs-snapshot-local/com/dwijnand/sbt-gh1750-bippy_2.11/0.1.0-SNAPSHOT/` shows:

```
maven-metadata.xml                                              06-Jul-2015 09:32  1.17 KB
maven-metadata.xml.md5                                          06-Jul-2015 09:32  32 bytes
maven-metadata.xml.sha1                                         06-Jul-2015 09:32  40 bytes
sbt-gh1750-bippy_2.11-0.1.0-20150706.083249-1-javadoc.jar       06-Jul-2015 09:32  340.70 KB
sbt-gh1750-bippy_2.11-0.1.0-20150706.083249-1-javadoc.jar.md5   06-Jul-2015 09:32  32 bytes
sbt-gh1750-bippy_2.11-0.1.0-20150706.083249-1-javadoc.jar.sha1  06-Jul-2015 09:32  40 bytes
sbt-gh1750-bippy_2.11-0.1.0-20150706.083249-1-sources.jar       06-Jul-2015 09:32  438 bytes
sbt-gh1750-bippy_2.11-0.1.0-20150706.083249-1-sources.jar.md5   06-Jul-2015 09:32  32 bytes
sbt-gh1750-bippy_2.11-0.1.0-20150706.083249-1-sources.jar.sha1  06-Jul-2015 09:32  40 bytes
sbt-gh1750-bippy_2.11-0.1.0-20150706.083249-1.pom               06-Jul-2015 09:32  821 bytes
sbt-gh1750-bippy_2.11-0.1.0-20150706.083249-1.pom.md5           06-Jul-2015 09:32  32 bytes
sbt-gh1750-bippy_2.11-0.1.0-20150706.083249-1.pom.sha1          06-Jul-2015 09:32  40 bytes
sbt-gh1750-bippy_2.11-0.1.0-20150706.083249-2.jar               06-Jul-2015 09:32  1.46 KB
sbt-gh1750-bippy_2.11-0.1.0-20150706.083249-2.jar.md5           06-Jul-2015 09:32  32 bytes
sbt-gh1750-bippy_2.11-0.1.0-20150706.083249-2.jar.sha1          06-Jul-2015 09:32  40 bytes
```

Note that the jar is `-2.jar` rather than `-1.jar`.

Re-publishing `bippy` "solves" this, but it's not ideal.

**Comment by eed3si9n** [comment]
You're using a 0.13 snapshot that has #2075 fix, I assume? If so what does the `maven-metadata.xml` say?

**Comment by dwijnand** [comment]
For the purposes of reproducing the error I was sticking to released 0.13.8, but occasionally checking with 0.13.9-RC1, but I just realised that doesn't include #2075.. I'll try.

**Comment by dwijnand** [comment]
With a local release of the HEAD of sbt (47a9a6db), switching `sbt.version` to `0.13.9-SNAPSHOT`, I'm getting essentially the same result, although it says `FAILED` instead of `NOT FOUND`.

Here's `maven-metadata.xml`:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata>
  <groupId>com.dwijnand</groupId>
  <artifactId>sbt-gh1750-bippy_2.11</artifactId>
  <version>0.1.0-20150706.083249-1</version>
  <versioning>
    <snapshot>
      <timestamp>20150706.083249</timestamp>
      <buildNumber>1</buildNumber>
    </snapshot>
    <lastUpdated>20150706083250</lastUpdated>
    <snapshotVersions>
      <snapshotVersion>
        <classifier>javadoc</classifier>
        <extension>jar</extension>
        <value>0.1.0-20150706.083249-1</value>
        <updated>20150706083249</updated>
      </snapshotVersion>
      <snapshotVersion>
        <classifier>sources</classifier>
        <extension>jar</extension>
        <value>0.1.0-20150706.083249-1</value>
        <updated>20150706083249</updated>
      </snapshotVersion>
      <snapshotVersion>
        <extension>jar</extension>
        <value>0.1.0-20150706.083249-2</value>
        <updated>20150706083249</updated>
      </snapshotVersion>
      <snapshotVersion>
        <extension>pom</extension>
        <value>0.1.0-20150706.083249-1</value>
        <updated>20150706083249</updated>
      </snapshotVersion>
    </snapshotVersions>
  </versioning>
</metadata>
```

**Comment by dwijnand** [comment]
No solution yet, but I've put two pieces together:

Given the `maven-metadata.xml` above, [`IBiblioResolver#findSnapshotVersion`](https://github.com/sbt/ivy/blob/c5d1b95fdcc1e1007740ffbecf4eb07abc51ec93/src/java/org/apache/ivy/plugins/resolver/IBiblioResolver.java#L176-L182) will only use this part:

``` xml
<snapshot>
  <timestamp>20150706.083249</timestamp>
  <buildNumber>1</buildNumber>
</snapshot>
```

and completely ignore the fact that (for whatever reason) the actually jar is versioned as `0.1.0-20150706.083249-2`.

**Comment by dwijnand** [comment]
For reference, this doesn't happen with Nexus, as the JARs are served with the `SNAPSHOT` suffix as opposed to timestamp and build number.

**Comment by tdesvenain** [comment]
I have the same problem, using sbt 0.13.9 and artifactory 3.8.0

**Comment by mallman** [comment]
We are also having this problem, in our case with sbt 0.13.8 and 0.13.9 (haven't tested other versions) and artifactoryonline.com. ~~As a workaround, adding this to our build files works:~~

```
import Classpaths._
packagedArtifacts <<= packaged(defaultArtifactTasks.reverse)
```

**Update: The above does not fully fix the problem. While it does ensure that the binary jars and pom files are published correctly, source and javadoc jars are still published incorrectly.**

@dwijnand Apparently Maven 3 has removed support for so-called "non unique" snapshots. So from the perspective of compatibility with maven 3, using the approach of overwriting previous snapshots is undesirable.

I'm trying to get in touch with jfrog's support team to raise the issue and get a solution that doesn't involve adding a workaround to our build files. I'll update the thread if/when I learn anything valuable from then. Until then, would it make sense to reverse/modify the default sbt artifact publication order to work within the constraints of the artifactory repo? Or would that break compatibility with other repos?

Cheers.

**Comment by dwijnand** [comment]
That's interesting about reversing the artifacts, thanks. Good workaround to have here.

I wouldn't just change the default though without further investigating as to why, we can't risk regressions.

**Comment by mallman** [comment]
@dwijnand Apparently the "workaround" we made does not work for the javadoc and source jars. The old versions are still published/imported. I've started an e-mail thread with JFrog support about this. We are pursuing a real fix, and I will be sure to post here when I get a good solution.

**Comment by mallman** [comment]
The advice I received from JFrog support was to add `";build.timestamp=" + new java.util.Date().getTime` to the snapshot publish repo. I'm not sure as yet whether this will work, but it does appear that all four snapshot artifacts are now being published in sync.

**Comment by mallman** [comment]
At this point we still don't have a full solution that works with our original repo configuration. The problem with the `";build.timestamp=" + new java.util.Date().getTime` solution is that it only works for publishing once per sbt reload. Of course, we could configure our sbt builds to generate a new timestamp on every publish, but we're trying to avoid any solution that requires a change to our build files.

We do now have working snapshot repos however. What we've done is set our snapshot repos to use the "non-unique" configuration for storing snapshots. While this is supposedly incompatible with Maven 3, we don't use Maven in-house so we're not concerned about that. And this works with sbt snapshot artifact publication and resolution.

**Comment by n3ziniuka5** [comment]
having the same issue, sbt 0.13.9, artifactory 4.2.0

**Comment by szeiger** [comment]
I can't get it to work with `build.timestamp`. All attempts at publishing a POM fail with status code 409 when I set build.timestamp. There is no previous artifact with that name in the repo. Without a fixed build.timestamp I can publish but I get the inconcistent build numbers.

Update: The ";build.timestamp=..." part must not be placed directly after a "/". Removing the trailing slash from the URL fixed my problem.

**Comment by dwijnand** [comment]
Ok, I spent some time on this, and this looks entirely like an implementation detail of Artifactory.

Artifactory deals with the publishing (and republishing) of SNAPSHOTs using a strict rule on the order of publishing. The `;build.timestamp=...` suffix is the alternative.

The strict rule is:
- publish the main artefact (which has no classifier)
- publish the POM/ivy.xml file
- publish additional artefacts which have a classifier

Sources:
- http://stackoverflow.com/a/9908168/463761
- http://stackoverflow.com/q/18859378/463761

What sbt does currently is:
- publish the POM/ivy.xml file (which sbt calls "deliver")
- publish the artefacts, which are in a Map, and get .toSeq at some point

So in my original case as soon as my main artefact gets published Artifactory bumps the "batch number" from 1 to 2, because the main artefact should've arrived to Artifactory before the POM/ivy.xml file.

Because deliver is its own task, I'm not exactly sure how or if we can weave it into the order that Artifactory seems to want. But perhaps @jsuereth or @eed3si9n might see that it is possible.

**Comment by dwijnand** [comment]
The `;build.timestamp=...` suffix appears to only work when publishing in Maven style.

When publishing in Ivy style, for example for sbt plugins, it doesn't:

```
[error] (plug/*:publish) java.io.IOException: PUT operation to URL http://localhost:8081/artifactory/libs-snapshot-local;build.timestamp=1473844295479/com/dwijnand/releash-plug_2.10_0.13/0.1.0-SNAPSHOT/releash-plug-0.1.0-SNAPSHOT.pom failed with status code 409: Conflict
```

**Comment by dwijnand** [comment]
Oh no, sorry. That 409 means POM consistency checks failure.

**Comment by dwijnand** [comment]
The solution from @eed3si9n is to fold `deliver` into `publish` so that we can publish in the correct order.

**Comment by MansurAshraf** [comment]
bump! any resolution to this?

**Comment by dwijnand** [comment]
@MansurAshraf The solution is to add a defined `build.timestamp` your snapshot repository URL:

``` scala
def buildTimestampSuffix = ";build.timestamp=" + new java.util.Date().getTime

def localArtifactorySnapshotLocal =
  "local-artifactory-snapshot-local" at
    "http://localhost:8081/artifactory/libs-snapshot-local" + buildTimestampSuffix
```

**Comment by MansurAshraf** [comment]
yeah i tried that and it didnt work for me :-(

**Comment by RootViz** [comment]
build timestamp solution works. Sbt is weird, it created separate timestamp for each of the artifacts.

**Comment by oeuftete** [comment]
For those people for whom https://github.com/sbt/sbt/issues/2088#issuecomment-261134192 doesn't work, https://stackoverflow.com/a/23585401/7674 may be your solution, configuring the Artifactory repository to use non-unique snapshots.

**Comment by eed3si9n** [comment]
Preemptively closing this as maybe-fixed-in-Coursier.

**Comment by dwijnand** [comment]
> Given the `maven-metadata.xml` above, [`IBiblioResolver#findSnapshotVersion`](https://github.com/sbt/ivy/blob/c5d1b95fdcc1e1007740ffbecf4eb07abc51ec93/src/java/org/apache/ivy/plugins/resolver/IBiblioResolver.java#L176-L182) will only use this part:
> 
> ```
> <snapshot>
>   <timestamp>20150706.083249</timestamp>
>   <buildNumber>1</buildNumber>
> </snapshot>
> ```
> 
> and completely ignore the fact that (for whatever reason) the actually jar is versioned as `0.1.0-20150706.083249-2`.

Perhaps this is inverted in Coursier, avoiding the effect of publishing in an order Artifactory doesn't expect.
