### ISSUE TITLE
2.12 builds of sbt-io

### ISSUE THREAD

**Issue by jroper** [sbt/sbt#2096]
I'm just going through Play's dependencies and working out what we need before we can upgrade to Scala 2.12.  We'll need 2.12 builds of sbt-io.  I know, we probably shouldn't be using sbt cross builds, but sbt-io is just so useful.  Can these be cut retroactively after sbt is released?

**Comment by jroper** [comment]
We'll also need sbt-rc 2.12 builds.

**Comment by eed3si9n** [comment]
We also have sbt/io.

**Comment by jsuereth** [comment]
The answer to your question is yes.  Will have to look into it.

**Comment by benjaminjackman** [comment]
Has this happened? not having any luck finding it maven central searches.

**Comment by eed3si9n** [comment]
https://github.com/sbt/io is the IO now.
