### ISSUE TITLE
Colorized Scala REPL

### ISSUE THREAD

**Issue by jawshooah** [sbt/sbt#2099]
I'd like to be able to get the equivalent of `scala -Dscala.color` when running `sbt console`. Perhaps with a new `SettingKey` called `scalaOptions` that would be used as follows:

``` sbt
(scalaOptions in console) += "-Dscala.color"
```

**Comment by dwijnand** [comment]
One way to do this is to create `~/.sbt/0.13/colour.sbt` with:

``` scala
initialize ~= (_ => if (ConsoleLogger.formatEnabled) sys.props("scala.color") = "true")
```

**Comment by jawshooah** [comment]
Just tried that, doesn't seem to be working. Same old monochrome console.

Edit: Scratch that, I was testing in the `root-0-13` project. Works fine in an outer project. Thanks!

**Comment by jawshooah** [comment]
Out of curiosity, why doesn't it work in `root-0-13`? Here's a console dump for reference:

```
joshuahagins in /Users/joshuahagins/.sbt/0.13
$ sbt
[info] Loading global plugins from /Users/joshuahagins/dev/github/dotfiles/scala/sbt.symlink/0.13/plugins
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] Set current project to root-0-13 (in build file:/Users/joshuahagins/dev/github/dotfiles/scala/sbt.symlink/0.13/)
> console
[info] Starting scala interpreter...
Welcome to Scala version 2.10.4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_45).
Type in expressions to have them evaluated.
Type :help for more information.

scala>
```

**Comment by dwijnand** [comment]
No idea sorry.

**Comment by m-sp** [comment]
it seems this is a repl for scala 2.10, i think the flag was added only with scala 2.11.4

**Comment by dwijnand** [comment]
Ah now I see. With sbt 0.13.8 the default scala version is sbt's built Scala version, 2.10.4, whose REPL doesn't support colours as you say.

**Comment by jawshooah** [comment]
Makes sense. Thanks for the help!
