### ISSUE TITLE
withConsolidatedResolution(true) - update gets slower and slower as more time is spent parsing and saving graph.json

### ISSUE THREAD

**Issue by edeustace** [sbt/sbt#2100]
I have a fairly large multi module project and I'm looking to improve the speed of its dependency resolution. `withConsolidatedResolution` looks like exactly the thing I'm looking for, however when I enable it, and run `update`, the saving and parsing of the `graph.json` gets slower and slower up to a point where the option isn't usable. The json files become enormous (I see one here that's 169mb). Have you seen this issue occur, anyway to keep the json at reasonable size?

I can do up a sample - but to really see it in action one has to have a large project (say ~12+ modules).

**Comment by eed3si9n** [comment]
> Have you seen this issue occur, anyway to keep the json at reasonable size?

Yes, I'm aware of this issue. Basically it's #1763.
There's a fix that got merged today called #2097 (improved #2030) which should keep the JSON size down.

**Comment by eed3si9n** [comment]
sbt 0.13.9-RC2 is coming up soon with the fix.
