### ISSUE TITLE
make settings lazy

### ISSUE THREAD

**Issue by antonkulaga** [sbt/sbt#2104]
Making settings lazy will allow to safely make circular references between projects, that is very useful in many cases.
An example of typical usecase where it is useful is scalajs crossproject used for the whole app.
Here is an example:

``` scala
lazy val app = crossProject
        .crossType(CrossType.Full)
        .in(file("app"))
        .settings(
            name := "gsea",
            version := Versions.gsea
        )
        .jvmConfigure(p=>p.enablePlugins(SbtTwirl,SbtWeb))
        .jvmSettings(Revolver.settings:_*)
        .jvmSettings(
            libraryDependencies ++= Dependencies.akka.value ++ Dependencies.webjars.value,
            mainClass in Compile :=Some("org.denigma.preview.Main"),
            mainClass in Revolver.reStart := Some("org.denigma.preview.Main"),
            libraryDependencies ++= Dependencies.RLang.value ++ Dependencies.compilers.value,
            (managedClasspath in Runtime) += (packageBin in Assets).value
        )
        .jsSettings(
            libraryDependencies ++= Dependencies.sjsLibs.value,
            persistLauncher in Compile := true,
            persistLauncher in Test := false,
            jsDependencies += RuntimeDOM % "test"
        )

    lazy val appJS = app.js
    lazy val appJVM = app.jvm settings ( //I know it is unsafe, because settings are not lazy :((((
        resourceGenerators in Compile <+=
            (fastOptJS in Compile in appJS,    packageScalaJSLauncher in Compile in appJS) map(
                (f1, f2) => Seq(f1.data, f2.data)
                ),
        watchSources <++= (watchSources in  appJS)
        )
```

here jvm project is akka-http server to run the app
js project is scalajs frontend
shared code is in src folder

Here when akka-http project is started then it runs fastOptJS on js project and compiles javascript.

Such kind of circular references is so often done by scalajs users, that @gzm0 even had to add warning to scalajs docs http://www.scala-js.org/api/sbt-scalajs/0.6.0/index.html#org.scalajs.sbtplugin.cross.CrossProject

That means that there is clearly a demand for fixing this.

**Comment by yakticus** [comment]
+1

**Comment by gzm0** [comment]
As a clarification: The methods involved in Scala.js' `crossProject` are not lazy since they use `Project#settings` under the hood (which does not take a by-name param).

In plain sbt, the following is problematic:

``` scala
lazy val p1 = project
  .settings(resources += (`package` in p2 in Compile))

lazy val p2 = project
  .settings(sources += (sources in p1 in Compile))
```

There are two escape hatches:
1. Use the project identifier as a string: `package in "p2" in Compile`
2. Use the old `Project` constructor whose settings is a by-name parameter

Situations like the above start to arise more commonly, if projects are interlinked more strongly. Especially the combination of sharing sources (in the Scala.js use case: shared code between browser and server), but having one project depend on the compilation product of the other (in the Scala.js use case: the produced JS file to be served by the server).

**Comment by virtualirfan** [comment]
+1

**Comment by eed3si9n** [comment]
@gzm0 Thanks for the clarification.

> Situations like the above start to arise more commonly, if projects are interlinked more strongly. Especially the combination of sharing sources (in the Scala.js use case: shared code between browser and server), but having one project depend on the compilation product of the other (in the Scala.js use case: the produced JS file to be served by the server).

Could we somehow turn the interlinkedness (A depends on B, which depends on A) into hierarchical dependency somehow? Sharing code is typically expressed via Ivy configuration hierarchy or library dependencies in sbt. What if `Compile` is reserved for the JVM usage only, and create some other independent configuration called `Shared` or something?

**Comment by sjrd** [comment]
> Sharing code is typically expressed

Yes, _typically_. But cross-compiling shared code is not your typical Ivy setup. So your suggestion is not applicable.

**Comment by eed3si9n** [comment]
> Yes, typically. But cross-compiling shared code is not your typical Ivy setup. So your suggestion is not applicable.

Doesn't the underlying issue stem from overloading more meaning into `Compile` configuration? sbt itself does that by cross building multiple Scala versions going through `++` command, but we don't try to mix and match different Scala versions on a single project (normally).

If the code is in `Shared` configuration, and `Compile` configuration is for JVM, and Javascript had its own `JS` configuration couldn't they co-exist? We could try sorting this out, but laziness of  `settings` feels like a side issue.

**Comment by antonkulaga** [comment]
@eed3si9n 

the ways how sbt does cross-compiling to different Scala versions is usells for scalajs usecases because one needs to run a command to switch between scala-s to run them. In projects with scalajs one usually just ~re-start 's the web app and opens it in the browser, whenever any changes occur in either scalajvm or sclalajs code it automaticly incrementally recompiles and one can see changes on browser refresh because scalajvm project watches scalajs one.

**Comment by sjrd** [comment]
> Doesn't the underlying issue stem from overloading more meaning into Compile configuration?

No, we actually preserve the meaning of the `Compile` (and `Test`) configuration. But we target a different platform.

> but we don't try to mix and match different Scala versions on a single project (normally).

As @antonkulaga explained, that is not even an option for Scala.js.

> If the code is in Shared configuration, and Compile configuration is for JVM, and Javascript had its own JS configuration couldn't they co-exist?

No, they cannot co-exist, because the output of the Scala compiler with or without the Scala.js compiler plugin is different. The shared code _must_ be compiled twice: once to target the JVM .class files, and once to target the Scala.js .sjsir files (and no, we _really_ cannot do both in the same run with one combined output).

> We could try sorting this out, but laziness of settings feels like a side issue.

We have tried to sort this out for more than a year. In Scala.js, we (the core devs at least) try _very hard_ not to require anything from upstream dependencies. When we do, that's because we ran out of options and workarounds for not doing so. That means we have already thought about a lot of other potential solutions and ruled them out. We had for example already thought about all the suggestions you've made so far in this thread. Having better knowledge of sbt, I'm sure you can come up with ideas we did not explore, so I'm definitely open to suggestions. Although one thing we know is that the way we organize the projects and the configurations is the right way.

**Comment by eed3si9n** [comment]
The fact that `crossProject` or Javascript is involved is a red herring. @gzm0 had it right in his comment about:

``` scala
lazy val p1 = project
  .settings(resources += (`package` in p2 in Compile))

lazy val p2 = project
  .settings(sources += (sources in p1 in Compile))
```

In the original case presented by @antonkulaga,

``` scala
    lazy val appJVM = app.jvm settings ( //I know it is unsafe, because settings are not lazy :((((
        resourceGenerators in Compile <+=
            (fastOptJS in Compile in appJS,    packageScalaJSLauncher in Compile in appJS) map(
                (f1, f2) => Seq(f1.data, f2.data)
                ),
        watchSources <++= (watchSources in  appJS)
        )
```

The above is actually safe. If you create a project with just the above you'd see that the `resourceGenerators` in `appJVM` can reference `fastOptJS in Compile in appJS` fine.
My guess is that it becomes an issue when you try to refer to each other.

In sbt we have a workaround for that called `ProjectReference`. You can define a reference to a local subproject like this:

```
lazy val appJVMRef = LocalProject("appJVM")
```

The following works for me:

``` scala
lazy val app = (crossProject.crossType(CrossType.Full) in file("app"))
  .settings(
    name := "foo",
    version := "0.1.0-SNAPSHOT",
    scalaVersion := "2.11.7"
  )

lazy val appJVMRef = LocalProject("appJVM")
lazy val appJS = app.js.
  settings(
    name := (name in appJVMRef).value + ".JS"
  )
lazy val appJVM = app.jvm.
  settings (
    resourceGenerators in Compile <+=
     (fastOptJS in Compile in appJS,    packageScalaJSLauncher in Compile in appJS) map(
         (f1, f2) => Seq(f1.data, f2.data)
         ),
    watchSources <++= (watchSources in  appJS)
  )
```

See the `name` of `appJS` is using the name from `appJVM`.

**Comment by gzm0** [comment]
> lazy val appJVMRef = LocalProject("appJVM")

This is basically what I proposed as workaround. It is really ugly, since you now need two names to refer to the same project (and you rely on strings to not get out of sync... type safety goodbye...).

This is a regression from the old project constructors:

``` scala
lazy val appJS: Project = Project("appJS", file("appJS"), settings = Seq(
  name := (name in appJVMRef).value + ".JS"
))

lazy val appJVM: Project = Project("appJVM", file("appJVM"), settings = Seq(
  watchSources <++= (watchSources in appJS)
))
```

works like a charm (and no unsafety).

**Comment by sjrd** [comment]
IIUC, we could add two methods `.jvmRef` and `.jsRef` in `CrossProject`, which would return `LocalProject`s (which means `CrossProject` takes care of the strings), and we could use those to have `.jvmSettings(...)` safely reference `.jsRef` and conversely? It would be better than having to do it manually, although it still feels like a regression indeed: it's definitely less nice than being able to just use `.jvm` and `.js`, especially because one has to remember to call the right thing, since the mistake will silently compile.

**Comment by eed3si9n** [comment]
> since the mistake will silently compile.

If it compiled it should be ok. `.jsRef` would be needed only when you have the circular situation.

**Comment by gzm0** [comment]
Yes. That would solve the problem for the `CrossProject` specifically. But for example in the Scala.js build, we run into issues like that with plain JVM builds.

**Comment by gzm0** [comment]
I just don't understand why we cannot have the lazyness back :-/

**Comment by eed3si9n** [comment]
@gzm0  I haven't completely ruled out adding laziness, but it would _likely_ break the binary compatibility of sbt 0.13, so either it needs to wait or we'll have to introduce a new method.

**Comment by eed3si9n** [comment]
Also I'm not sure if the original authors of sbt 0.13 syntax may have done this intentionally to discourage circular dependencies among the subprojects settings (and tasks).

**Comment by antonkulaga** [comment]
> but it would likely break the binary compatibility of sbt 0.13, so either it needs to wait 

Are there any estimations of how soon new major version of sbt will arrive?
I think for 0.13.x series addition of _.jvmRef_ and _.jsRef_ in next scalajs version can be a temporal workaround.

**Comment by eed3si9n** [comment]
@antonkulaga No. It's currently feature-boxed, but we have no ETA.

**Comment by gzm0** [comment]
> we'll have to introduce a new method

That might be necessary anyways, since you currently cannot have a by-name vararg param IIUC. (I don't know if it is intentional, but the parser doesn't allow you to write the type...).

**Comment by eed3si9n** [comment]
Also @dwijnand magically pulled off #1902 (allows `Seq[Setting[_]]`) without breaking bincompat, so maybe he can do it.

**Comment by dwijnand** [comment]
Well, [as @jsuereth explained](https://github.com/sbt/sbt/pull/1902#issuecomment-77771849), that was WRT using a super type.

By-names are radically different in bytecode, so I think chances are slim.

Also, I trust MiMa more than my ability to mock up some tests, see https://gist.github.com/dwijnand/bcdcb70b672db8cfa5ec.

**Comment by sjrd** [comment]
Sure. It might be possible to preserve binary compat using clever overloads and dummy default parameters / `DummyImplicits`.

> That might be necessary anyways, since you currently cannot have a by-name vararg param IIUC. (I don't know if it is intentional, but the parser doesn't allow you to write the type...).

In Scala 2, it is indeed impossible to have a by-name varargs. (There's nothing fundamentally wrong about the idea, though; Martin wants to add that in Dotty.) One way to partially simulate a by-name varargs API is via an implicitly convertible by-name box:

``` scala
final class ByNameBox[+A](getValue: () => A) {
  def value: A = getValue()
}

object ByNameBox {
  implicit def box[A](value: => A): ByNameBox[A] =
    new ByNameBox[A](() => value)
  implicit def boxSeq[A](values: Seq[A]): Seq[ByNameBox[A]] =
    values.map(v => new ByNameBox[A](() => v))
}

object ScalaJSExample extends js.JSApp{
  def byNameVarargs(params: ByNameBox[Int]*): Int = {
    println("begin")
    params.foreach(p => println(p.value))
    val values = params.map(_.value) // second access re-evaluates
    val sum = values.sum
    println("end")
    sum
  }

  def main(): Unit = {
    def one = { println("one"); 1 }
    def two = { println("two"); 2 }
    byNameVarargs(one, two)

    println("---")

    /* this does not work because type inference
     * pushes the expected type inside the block, unfortunately
     * (but for the .settings() case, it should not have a real impact)
     */
    byNameVarargs(
        { println("one"); 1 },
        { println("two"); 2 })

    println("---")

    // this implementation does not provide actual laziness for expanded seqs
    def seq = { println("seq"); Seq(1, 2) }
    byNameVarargs(seq: _*)
  }
}
```

Fiddle: http://www.scala-js-fiddle.com/gist/8e4c10ec0a54ef757138

**Comment by eed3si9n** [comment]
Currently `Seq[Setting[_]]` is converted in `SettingsDefinition`.

``` scala
  object SettingsDefinition {
    implicit def unwrapSettingsDefinition(d: SettingsDefinition): Seq[Setting[_]] = d.settings
    implicit def wrapSettingsDefinition(ss: Seq[Setting[_]]): SettingsDefinition = new SettingList(ss)
  }
```

Not sure if you can prioritize lazy one over eager one:

``` scala
trait SettingsDefinition0 {
  implicit def wrapSettingsDefinition(ss: Seq[Setting[_]]): SettingsDefinition = new SettingList(ss)
}
object SettingsDefinition extends SettingsDefinition0 {
  implicit def wrapLazySettings(ss: => Seq[Setting[_]]): SettingsDefinition = new LazySettingList(ss)
}
```

**Comment by dwijnand** [comment]
Looks like call-by-name implicit conversions don't work: https://issues.scala-lang.org/browse/SI-3237

**Comment by sjrd** [comment]
@dwijnand Yes, that is precisely why my second "test case" does not work as expected. But it is also very likely that this is not really an issue for the `.settings()` method, because individual arguments do not tend to be blocks. They tend to be a call to `:=`, which will be converted as we want.

**Comment by sjrd** [comment]
@eed3si9n It's possible to prioritize the lazy conversion while still remaining backwards binary compatible very easily: just make the non-lazy one non-`implicit`. It will only be called by code previously compiled against the old API, but will not be materialized anymore.

And in cases where it's not an implicit something (so you actually call the method in source), you can instead make it a `protected[EnclosingClass]`. That will not be visible by callers, so no chance to be picked by overload resolution, but it will be emitted as a public method with a non-mangled name in the bytecode, so it will be binary compatible.

@dwijnand For the call-by-name implicit doesn't work, there [is actually a workaround](http://stackoverflow.com/questions/32064375/magnet-pattern-and-overloaded-methods).
