### ISSUE TITLE
cached resolution: remove transitive dependencies from callers array when using consolidated resolution

### ISSUE THREAD

**Issue by edeustace** [sbt/sbt#2105]
@eed3si9n - I hope I'm describing the issue correctly - let me know..

When using `withConsolidatedResolution(true)` can the graph.json size be further reduced by removing transitive dependencies from the `callers` array? For small projects it's manageable, but for a large project the json files mushroom in size and the performance of consolidated resolution deteriorates.

Steps: 

``` sh
    git@github.com:edeustace/sbt-callers-sample.git
    cd sbt-callers-sample/lib-two
    sbt publish-local
    cd ../lib-one
    sbt publish-local
    cd ..
    sbt update
```

Then inspect the graph.json for module `a`. You should see something like: 

``` javascript
     [
      {
        "caller": {
          "organization": "org.scala-sbt.temp",
          "name": "temp-resolve-1fd7120a8dac7d10ffc45ff63fc42f19d0d148e1",
          "revision": "1.0",
          //...
        },
        //...
      },
      {
        "caller": {
          "organization": "com.ee",
          "name": "lib-one_2.10",
          "revision": "0.0.1-SNAPSHOT",
          //...
        },
        //...
      },
      {
        "caller": {
          "organization": "com.ee",
          "name": "lib-two_2.10",
          "revision": "0.0.1-SNAPSHOT",
          //...
        },
      }
      //...
    ]
```

The tmp org (`org.scala-sbt.temp`) is fine as is the direct dependency `lib-one`.

The issue is that `lib-two` is listed as a caller even though it's a transitive dependency of `a`.

**Comment by eed3si9n** [comment]
@edeustace Thanks for the report. This case is a generalized one for #1763.
@paddymahoney reported he's seeing OOM in 0.13.9-RC2.

**Comment by edeustace** [comment]
Just ran 0.13-RC3 against the project that was grinding to a halt, it's now making use of consolidated resolution with a `clean update` averaging ~80s (was ~240s). Thanks @eed3si9n

**Comment by eed3si9n** [comment]
@edeustace Thanks for the confirmation. Were old cached resolution grinding to the halt, or the plain `update` too? I'm curious about the performance comparison. Never mind you said ~240s.
