### ISSUE TITLE
Optional eviction for selected artifact

### ISSUE THREAD

**Issue by wxiang7** [sbt/sbt#2110]
I'm wondering if it's possible to make artifact eviction optional for selected artifacts.

My problem is I need to use multiple versions of the same artifact in the final assembly jar (by sbt-assembly), e.g. older version of protobuf from dependencies, and newer version of protobuf.

Since both versions of protobuf might not be compatible with each other, one of them need to be shaded.
I tweaked sbt-assembly plugin with some shading rules, but the problem is that, older version of protobuf was evicted by newer one before sbt-assembly started.

So my question is, is it possible to make artifact eviction for selected jars optional.

**Comment by eed3si9n** [comment]
No, we can't make eviction optional. But you can put it the shaded JARs in `lib` and it should work for you. Or you can make another configuration to resolve it and then customize the `externalDependencyClasspath`.
