### ISSUE TITLE
Merge Ant parent license fix

### ISSUE THREAD

**Issue by benmccann** [sbt/sbt#2118]
We need to merge https://github.com/apache/ant-ivy/pull/7 into this repo's Ant fork to fix https://github.com/sbt/sbt-license-report/issues/7

**Comment by jsuereth** [comment]
It's actually the sbt/ivy repo that needs to merge it. I'll look at that today.

**Comment by jsuereth** [comment]
I looked into migrating that into our ivy branch. Just FYI, the tests are not passing for that patch on our back-port, so it'll be a while to merge it.
