### ISSUE TITLE
Multiple javaOption arguments in the same string are not parsed correctly

### ISSUE THREAD

**Issue by asgereir** [sbt/sbt#2119]
Consider the case that we want to pass two VM arguments to Run or Test.
In Eclipse we would write something like this in the launch configuration's VM Argument's box:

-Dbusinessobjects.connectivity.directory=/Users/nn/BOConnectionServer -Dlogback.configurationFile=/Users/nn/BI_Reporting_Sources/Tools/bpm-tools/src/main/resources/logback.xml

However, passing the same string in SBT as follows will not work:

javaOptions in run += "-Dbusinessobjects.connectivity.directory=/Users/nn/BOConnectionServer -Dlogback.configurationFile=/Users/nn/BI_Reporting_Sources/Tools/bpm-tools/src/main/resources/logback.xml"

It looks like only the second -D parameter is accepted. This can be seen if inspecting the VM Arguments using e.g. JavaVisualVM. 

This was seen when running SBT 0.13 and Scala 2.11.

**Comment by jsuereth** [comment]
This is by design in sbt.  If you'd like to pass multiple options, each one should be its own string and you should append the sequence.

``` scala
javaOptions in run ++= 
  Seq("-Dbusinessobjects.connectivity.directory=/Users/nn/BOConnectionServer",
         "-Dlogback.configurationFile=/Users/nn/BI_Reporting_Sources/Tools/bpm-tools/src/main/resources/logback.xml")
```
