### ISSUE TITLE
SBT should require a project/build.properties or some other mechanism to avoid assuming any directory is a valid project.

### ISSUE THREAD

**Issue by mdedetrich** [sbt/sbt#2123]
This is more of a nice to have (and I don't think there is an issue on this), but if you start `SBT` in a folder which isn't a valid `SBT` project, `SBT` should either delete the `target` folder on shutdown, or not create it in the first place

The former I think is more realistic. This just came out because I always have a habit of starting SBT in the wrong place, and it always leaves behind `target` folders.

**Comment by jsuereth** [comment]
The issue is that sbt considers an empty directory a valid sbt project. I'm going to retitle this request.

**Comment by dwijnand** [comment]
As a reference, sbt-extras has [this logic](https://github.com/paulp/sbt-extras/blob/b9c8cb273d38e0d8da9211902a18018fe82aa14e/sbt#L447-L456) which avoids that.

**Comment by mdedetrich** [comment]
@jsuereth Actually I think this is a breaking solution. If I am making a blank project, I typically run `sbt` in a folder (which will usually be blank), and then do something like this.

```
set name := "something"
set scalaVersion := "2.11.7"
// do other stuff
session save
```

This will then save the `build.sbt` file, thereby creating an actual `sbt` project. If you can't start `sbt` in any folder, than this functionality is lost

**Comment by SethTisue** [comment]
I wouldn't mind if I had to answer a "are you sure (y/n)?" type prompt before being able to proceed as @mdedetrich describes.

**Comment by nafg** [comment]
I think the best solution is that sbt should be lazy in creating `target`.
I think it's beneficial to be allowed to run sbt anywhere. You don't _need_ any sbt config or setting to be able to use many of sbt's capabilities. For example you can go into any directory, create a few .scala (or .java) files (they don't even need to be in src/main/xxx), and `sbt run`. (Not sure about currently but sbt used to be able to read pom.xml files as well.) So there isn't really such a thing as "is this directory an sbt project or not." Instead, a valid question might be "does this directory have any sbt-specific customization?"
However that doesn't help for the case where you accidentally type "sbt" in the wrong directory. I think the solution to that is that sbt should only create `target/` when you ask it to do something that requires it.

**Comment by mdedetrich** [comment]
On another note, there are SBT tasks from SBT plugins that are out there that don't need a SBT project to be relevant. A good example is https://github.com/xerial/sbt-sonatype, which provides a `sonatypeRelease` task that promotes all of your current sonatype libraries from staging to release (this doesn't need to be done in any relevant SBT project)

**Comment by SethTisue** [comment]
> I wouldn't mind if I had to answer a "are you sure (y/n)?" type prompt before being able to proceed as @mdedetrich describes.

Such a prompt could also suggest `sbt new` as an alternative, as per discussion at #6772

**Comment by eed3si9n** [comment]
I don't know if this feature ever worked but there's https://github.com/sbt/sbt/blob/4318b5384b194911b4801befc69731c4d5674f44/sbt#L571 

which seems to indicate that at some point this there was such mechanism?
