### ISSUE TITLE
sbt plugin repo returns 404 Not Found

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2125]
https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/

**Comment by softside** [comment]
anyone working on this?

**Comment by eed3si9n** [comment]
I'm working on it.

```
resolvers += Resolver.url("fix-sbt-plugin-releases", url("https://dl.bintray.com/sbt/sbt-plugin-releases"))(Resolver.ivyStylePatterns)
```

should work as a _temporary_ workaround. (We can't promise the URL will always be dl.bintray.com)

**Edit:** I fixed http to be **https**.

**Comment by lamdor** [comment]
Also creating a `~/.sbt/repositories` file with 

```
[repositories]
  bintray-sbt-plugin-releases: http://dl.bintray.com/sbt/sbt-plugin-releases/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
```

will fix it without having to change `project/plugins.sbt`. Especially helpful if you have a lot of different projects.

**Comment by aborg0** [comment]
Is [this issue](https://github.com/scoverage/sbt-scoverage/issues/125) related? (Maybe it is just not yet synced on bintray, though the release was more than 24 hours ago.)

**Comment by jsuereth** [comment]
@aborg0 no.   This is actually an issue with the linked scoverage package moving around in bintray.  I have some legwork to do to correct that.

**Comment by eed3si9n** [comment]
This issue is now resolved.

**Comment by szeiger** [comment]
@eed3si9n What's the solution? I'm still getting these errors on Travis CI (even with the workaround; see https://travis-ci.org/slick/slick/builds/73001195). Do I need a newer sbt or some extra configuration?

**Comment by eed3si9n** [comment]
No workaround should be required at this point. Could you try undoing any workarounds, and clearing the Travis cache?

It's downloading from wrong URL (note "simple"): http://repo.scala-sbt.org/scalasbt/simple/sbt-plugin-releases/de.johoop/sbt-testng-interface_2.11/3.0.2/ivys/ivy.xml

```
[warn] ==== local: tried
[warn]   /home/travis/.ivy2/local/de.johoop/sbt-testng-interface_2.11/3.0.2/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/de/johoop/sbt-testng-interface_2.11/3.0.2/sbt-testng-interface_2.11-3.0.2.pom
[warn] ==== sonatype-snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/de/johoop/sbt-testng-interface_2.11/3.0.2/sbt-testng-interface_2.11-3.0.2.pom
[warn] ==== scala-sbt simple releases: tried
[warn]   http://repo.scala-sbt.org/scalasbt/simple/sbt-plugin-releases/de.johoop/sbt-testng-interface_2.11/3.0.2/ivys/ivy.xml
```

**Comment by szeiger** [comment]
@eed3si9n My other branches are running on the old Travis infrastructure (which doesn't support caching) and do not have the workaround. They fail the same way (e.g. https://travis-ci.org/slick/slick/builds/72990052)

**Comment by SethTisue** [comment]
hmm. what's adding that `simple` to the URL?

**Comment by szeiger** [comment]
Maybe the most interesting thing about the problem with sbt-testng-interface: This is happening in a cross-build for Scala 2.10 and 2.11. sbt resolves the plugin without issues when building for 2.10 and then fails to resolve the same plugin when switching to 2.11.

**Comment by szeiger** [comment]
@eed3si9n How can we move this ahead? This problem breaks all Slick CI builds at the moment.

**Comment by jsuereth** [comment]
@szeiger It's just a bug on the test-ng plugin, see this line: https://github.com/sbt/sbt-testng-interface/blob/master/plugin/src/main/scala/de/johoop/testngplugin/TestNGPlugin.scala#L33-L34

Just add the correct scala-sbt repo to your resolvers and your build should pass.

**Comment by szeiger** [comment]
Thanks, I'll give it a try. Why did it work before the migration and why does it only fail on the 2nd resolver run of the cross build? Is there a redirect missing in the new repo setup?

**Comment by jsuereth** [comment]
No, it was using an unsupported URL (i.e. a domain name we do not have any control over and a URL we did not support or redirect).

It probably fails on 2nd resolution because the first time it hits the cache.

artifactoryonline.com is owned by JFrog and we can't run a redirection server in front of their servers.

**Comment by szeiger** [comment]
Hm, no luck, it doesn't even try the resolver. Am I doing something wrong here? https://travis-ci.org/slick/slick/builds/73405601 https://github.com/slick/slick/commit/29d11c1f20edae06564fff1824655282d4ff1060

**Comment by szeiger** [comment]
Never mind, it works. The resolver is needed at the project level, not the plugin level: https://travis-ci.org/slick/slick/builds/73421612

**Comment by szeiger** [comment]
Created https://github.com/sbt/sbt-testng-interface/pull/8 to fix this at the source

**Comment by sathyajitb** [comment]
I am trying to build chisel3
I see in projects/plugins.sbt
resolvers += Resolver.url("scalasbt", new URL("http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases")) (Resolver.ivyStylePatterns)

The URL is broken. I replaced it with https://dl.bintray.com/sbt/sbt-plugin-releases
Yet I see that I get this
`[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /home/sathya/riscv/rocket-chip/chisel3/project
[info] Updating ProjectRef(uri("file:/home/sathya/riscv/rocket-chip/chisel3/project/"), "chisel3-build")...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scalastyle#scalastyle-sbt-plugin;1.0.0: Resolution failed several times for dependency: org.scalastyle#scalastyle-sbt-plugin;1.0.0 {compile=[default(compile)]}:: 
[warn] 	typesafe-ivy-releases: unable to get resource for org.scalastyle#scalastyle-sbt-plugin;1.0.0: res=https://repo.typesafe.com/typesafe/ivy-releases/org.scalastyle/scalastyle-sbt-plugin/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[warn] 	sbt-plugin-releases: unable to get resource for org.scalastyle#scalastyle-sbt-plugin;1.0.0: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scalastyle/scalastyle-sbt-plugin/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[warn] 	public: unable to get resource for org/scalastyle#scalastyle-sbt-plugin;1.0.0: res=https://repo1.maven.org/maven2/org/scalastyle/scalastyle-sbt-plugin_2.12_1.0/1.0.0/scalastyle-sbt-plugin-1.0.0.pom: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[warn] 	sbt-plugin-releases: unable to get resource for org.scalastyle#scalastyle-sbt-plugin;1.0.0: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scalastyle/scalastyle-sbt-plugin/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[warn] 	:: org.scoverage#sbt-scoverage;1.5.1: Resolution failed several times for dependency: org.scoverage#sbt-scoverage;1.5.1 {compile=[default(compile)]}:: 
`

I am new to scala and want to get going with building my application. Can you please let me know what I am missing?

**Comment by eed3si9n** [comment]
@sathyajitb Your error says "javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty", which is a known issue on Linux. See https://stackoverflow.com/questions/6784463/error-trustanchors-parameter-must-be-non-empty for various workarounds posted.

If you're still stuck, please open a new question on Stackoverflow with exact reproduction steps instead.
