### ISSUE TITLE
Recompilation should take into account unused import statements

### ISSUE THREAD

**Issue by ijuma** [sbt/sbt#213]
The following happened to me recently.
- Run ~test:products in root project.
- Rename a class.
- Fix all compiler errors.
- Push to branch.
- CI system doing clean builds reports compiler errors in files that have unused import statements that reference old name of renamed class.

I'll try to create an example too soon.

**Comment by harrah** [comment]
Known limitation since sbt 0.1 (not 0.10), unfortunately.  The compiler does not record these symbols in CompilationUnit.depends.

**Comment by ijuma** [comment]
Oh, I see. Is there a way around it or will we have to live with it?

**Comment by harrah** [comment]
I haven't recently looked into fixing it, so I don't know off-hand, but I left it open instead of wontfix to reevaluate.

**Comment by stephenjudkins** [comment]
Is there a Scala issue open for this? Should there be?

**Comment by harrah** [comment]
There isn't a Scala issue that I know of.  There is the more general issue of unused imports of packages, which probably would not be a scalac-only fix.  I wouldn't open a Scala issue until someone works on the sbt side and confirms the work needed on the scalac-side.

**Comment by gkossakowski** [comment]
Unused imports of classes are taken into account when name hashing algorithm is enabled. See 6cf79aba08da5145b1a85466305a23928a031ba2 for the test that covers it.

The tracking of imported packages is not tracked but I think this is a minor problem. I'm closing the ticket.
