### ISSUE TITLE
Default scalaVersion to latest release

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#2133]
In sbt 0.13.8 `scalaVersion` defaults to 2.10.4.

Perhaps every release of sbt should set the default of `scalaVersion` to the latests release, eg. 2.11.7.

**Comment by SethTisue** [comment]
this often trips me up. I guess the rationale is that sbt 0.13 itself uses 2.10, so projects default to that too?

**Comment by dwijnand** [comment]
Indeed that's what seems to be the case at the moment, which I suggesting we should change.

**Comment by dwijnand** [comment]
`crossScalaVersions` will be already a little saner as of #1992

**Comment by eed3si9n** [comment]
It's not always straightforward. See #2068

**Comment by dwijnand** [comment]
I don't want to bump the version of Scala used for sbt, I want to set the default of `scalaVersion` to (for instance) "2.11.7" for end users of sbt.

**Comment by eed3si9n** [comment]
@dwijnand ok. I re-read this issue, and it makes sense now. Now sure what I was thinking 2 days ago.
However, this would break the semantics of 0.13.x, so probably not a good idea, even tho in theory it is a good idea as sbt to keep pace with the Scala ecosystem.

**Comment by dwijnand** [comment]
I've been thinking about semantics too, to the extent I was thinking perhaps a better default is being unset.

But I think given, it's pinned on the `sbt.version` in `build.properties`, and we highly encourage that that be set (and sbt-extras enforces this), I think having a good, up-to-date, out-the-box default is a good thing.

In terms of it "breaking" the semantics of 0.13.x, I think it's on par to the `crossScalaVersions` change in 0.13.9 (#1992), communicated loudly in "Fixes with compatibility implications" (good call).

If you still think it's too much of a change, I trust your judgement, and feel free to close this.

**Comment by eed3si9n** [comment]
Yea. I can imagine sbt plugin project for example would be assuming the default value to be the Scala version used by sbt. [Getting Started guide](http://www.scala-sbt.org/0.13/tutorial/Hello.html) promises that:

> By default, sbt will build projects with the same version of Scala used to run sbt itself.

**Comment by dwijnand** [comment]
That is true about plugins assuming that default ([I do so myself](https://github.com/dwijnand/sbt-project-graph/blob/v0.1.0/build.sbt)). Potentially could be solved with `sbtPlugin`, but anyways.

Actually, maybe we should re-open this and target it for 1.0, where we can break semantics.

**Comment by eed3si9n** [comment]
sbt 1.0 will likely be based on 2.11, so when 2.12 comes out and becomes predominant we'll have the same problem.
