### ISSUE TITLE
Make SBT give some notification when you don't have compile/test/runtime classpaths setup

### ISSUE THREAD

**Issue by mglazer** [sbt/sbt#214]
See this thread for details:

http://groups.google.com/group/simple-build-tool/browse_thread/thread/55f76e8a969f0000?hl=en

The docs were updated, but there should be some sensible defaults or at least a notification that pops up when you're using an external ivy file, and you haven't done this mapping. Documentation is now good, but people will probably miss this step if there's no warning.

**Comment by harrah** [comment]
1. classpathConfiguration in X should be the first defined configuration of XInternal or X.
2. If neither is defined, delegate according to X's delegates.
3. If still undefined, use the first defined of Compile or Default.
4. If no default configuration is successfully found by 1-3, log a warning.  This could possibly be an error at classpathConfiguration use-sites as well.
