### ISSUE TITLE
Remove dependency on json4s-core

### ISSUE THREAD

**Issue by karthicks** [sbt/sbt#2144]
Can we have [sbt depend on the 0.1.3 version](https://github.com/sbt/sbt/blob/0.13/project/Dependencies.scala#L15) of serialization, so that it [doesn't depend on json4s-core](https://github.com/sbt/serialization/commit/0ea91d2c0e7b14d113a2ccfa3e89fa15fb35c503) anymore?

**Comment by eed3si9n** [comment]
We still have transitive dependency to json4s-ast, which is not long term bincompat as it stands.
This partially motivated the creation of https://github.com/json4s/json4s-ast, but its development is still underway.

**Comment by dwijnand** [comment]
What's the plan here? sjson-new? json4s-ast?

**Comment by eed3si9n** [comment]
sjson-new + SLIP-28 JSON

**Comment by dwijnand** [comment]
Blocked on https://github.com/mdedetrich/scala-json-ast/issues/13

[edit: not really blocked, but we need that to ship 1.0.0]

**Comment by dwijnand** [comment]
No part of sbt 1 depends on json4s. We severed that dependency when we moved away from sbt/serialization.
