### ISSUE TITLE
Edge case in incremental compile

### ISSUE THREAD

**Issue by danchia** [sbt/sbt#2155]
Download https://s3.amazonaws.com/coursera-misc/danchia/broken.tgz
### Steps to reproduce in sample case

```
$ sbt
> project foo
> run
```

in bar/build.sbt
comment out

``` scala
libraryDependencies += "com.typesafe.scala-logging" %% "scala-logging-slf4j" % "2.1.2"
```

and uncomment

``` scala
libraryDependencies += "com.typesafe.scala-logging" %% "scala-logging" % "3.1.0"
```

in bar/src/main/scala/org/example/bar.scala
uncomment out

``` scala
import com.typesafe.scalalogging.Logger
```

and comment

``` scala
import com.typesafe.scalalogging.slf4j.Logger
```

now back in sbt

```
> reload
> run
```
### problem

```
java.lang.AbstractMethodError: org.coursera.Foo.org$coursera$Bar$_setter_$org$coursera$Bar$$logger_$eq(Lcom/typesafe/scalalogging/Logger;)V
at org.coursera.Bar$class.$init$(bar.scala:8)
at org.coursera.Foo.<init>(foo.scala:3)
at org.coursera.Main$.main(foo.scala:10)
at org.coursera.Main.main(foo.scala)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
```

**Comment by dwijnand** [comment]
@danchia Thank you for the step-by-step bug report!

**Comment by Duhemm** [comment]
Actually this bug describes a known issue of the incremental compiler. A pending test case has been introduced in c6b0043336a48c713eec5202fc6ef88006c5275b.

The problem comes from `Bar` being a trait. If `Bar` is an abstract class, then this issue is not observed.
The two classes having the same name (`Logger`) has no effect on this issue.

**Comment by Duhemm** [comment]
Including the private definitions in the computation of the the API hash seems to fix this issue. I tried it in duhemm/sbt@f58a96e7c436f3df9b515a7a6b8815a5f87475ea. I'm afraid always including the private definitions would greatly degrade the performances of the incremental compiler.

We could try to include the private definitions only for traits, but this would require to rework a great part of `HashAPI.scala` (in the current implementation, private definitions are immediately filtered out if they are not to be included in the hash).
