### ISSUE TITLE
Directory filtering is not working

### ISSUE THREAD

**Issue by sasajib** [sbt/sbt#2157]
I am trying to include a gulp, angular project within a play-framework 2.4.X app.

There is a **node_modules** folder, which contain lots of files and folders. SBT is including those files in my build process; this make my build process very slow.

So I want to exclude that and other unnecessary files and folders. My build.sbt files partial code

``` scala
lazy val gulpDirectory = baseDirectory { _ / "admin-panel" }
unmanagedResourceDirectories in Assets <+= gulpDirectory

//includeFilter in Assets in unmanagedResourceDirectories := {
//    new SimpleFileFilter( file =>
//        file.getParent == "bower_components" ||
//                file.getParent == "tmp" ||
//                file.getParent == "dist"
//    )
//}

//includeFilter in Assets in unmanagedResourceDirectories := "bower_components" || "dist" || "tmp"
//excludeFilter in Assets in unmanagedResourceDirectories := new SimpleFileFilter(_.getParent == "node_modules")

//excludeFilter in (Assets, unmanagedResources) := {
//    val nodeModules = (gulpDirectory.value / "node_modules").getCanonicalPath
//    new SimpleFileFilter(_.getCanonicalPath startsWith nodeModules)
//}

excludeFilter in (Assets, unmanagedResourceDirectories) := {
    val nodeModules = (gulpDirectory.value / "node_modules").getCanonicalPath
    new SimpleFileFilter(_.getCanonicalPath startsWith nodeModules)
}
```

But none of those working, and SBT including all files and folders from admin-panel folder. Can anyone help me out, as I am new to SBT and SCALA.

I already posted a question at [Stackoverflow](http://stackoverflow.com/q/32000681/1086183), but unable to get any response.

**Comment by eed3si9n** [comment]
This seems like something specific to Play maybe try their mailing list instead of sbt-dev? - https://www.playframework.com/get-involved

**Comment by mmizutani** [comment]
unmanagedSourceDirectories have includeFilter and excludeFilter keys, whereas unmanagedResourceDirectories do not. This is what sasajib likes to resolve. Is it feasible to add filters for  unmanagedResourceDirectories?
