### ISSUE TITLE
Difficult to create empty Analysis with an explicitly specified `nameHashing` value

### ISSUE THREAD

**Issue by stuhood** [sbt/sbt#2159]
`Analysis.empty(nameHashing: Boolean)` is package private in sbt 0.13.9 ... it seems that it needs to be exposed in order to use `IC.incrementalCompile`, which is recommended instead of `AggressiveCompile`.

Because using mismatched analysis with `MixedAnalyzingCompiler` or `IC` causes runtime exceptions, it's not always possible to use the `IncOptions.defaultNameHashing` value.

**Comment by eed3si9n** [comment]
Won't fix in 0.13. Hopefully improved incremental compiler API in sbt/incrementalcompiler.
