### ISSUE TITLE
Blank lines in triple-quoted strings break .sbt parsing

### ISSUE THREAD

**Issue by yang** [sbt/sbt#216]
Can't have blank lines in triple-quoted strings because of the way sbt parses .sbt files.

**Comment by harrah** [comment]
As specified.  Please use the mailing list.

**Comment by yang** [comment]
Didn't really have any questions to ask or anything to discuss. I understand how the parser works. Not a big deal, just came up over lunch with colleagues as an annoyance of sbt.
