### ISSUE TITLE
support .jvmopts like paulp's script

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#2161]
It would be nice to read the JAVA_FLAGS from `.jvmopts` like paulp's script does.

**Comment by nafg** [comment]
Any reason @paulp's script isn't adopted as the default?

**Comment by eed3si9n** [comment]
@nafg paulp/sbt-extras requires `bash` whereas the official launch script we maintain on sbt/sbt-launcher-package supports both Mac/Linux and Windows batch file.
If we can get pull requests with parity Windows feature we'd be happy to review them.

**Comment by fommil** [comment]
Err, are you sure about that? We are forever getting bug reports on ENSIME where the fix is "add the hash bang to the start of the script".

**Comment by fommil** [comment]
btw, which one is the official start script. http://www.scala-sbt.org/0.13/tutorial/Manual-Installation.html doesn't agree with the `/usr/bin/sbt` that I see when installing the `.deb` file. The deb file one seems to be a really old version of paulp's script.

**Comment by eed3si9n** [comment]
Historically sbt did not ship or endorse any scripts or installers, and the manual installation page still reflects that style. The script included in our `.deb` installer is in https://github.com/sbt/sbt-launcher-package, which in fact was forked from sbt-extras.
