### ISSUE TITLE
-java-home should set JDK_HOME and JAVA_HOME

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#2162]
to align with paulp's script.

This fixes a lot of integration issues, in particular allows plugins such as `gen-idea` and `gen-ensime` to correctly detect the JDK.

For now, we recommend that all users use paulp's script.

**Comment by fommil** [comment]
actually, I'd be happy if you reset JAVA_HOME and JDK_HOME when they are already set. The big problem here is that the user can provide `-java-home` but this can easily be inconsistent with the envvars.

Even if you unset them, it would be a help.

**Comment by dwijnand** [comment]
Funnily we were just talking a little about some of this over in sbt/sbt-remote-control#298.

I wonder if this is a ticket for here (sbt), [sbt-launcher-package](https://github.com/sbt/sbt-launcher-package) or [sbt-remote-control](https://github.com/sbt/sbt-remote-control)...

**Comment by fommil** [comment]
https://github.com/google/github-issue-mover :wink:

**Comment by eed3si9n** [comment]
If we can do this for both Mac/Linux and Windows, I'd be happy to accept a pull req for https://github.com/sbt/sbt-launcher-package.

**Comment by dwijnand** [comment]
Fixed in https://github.com/sbt/sbt-launcher-package/pull/112
