### ISSUE TITLE
new sbt install fails downloading commons-codec

### ISSUE THREAD

**Issue by benwing** [sbt/sbt#217]
I tried downloading the new sbt (version 0.11).  This is the first time I've used it.  When I run 'sbt', it fails, unable to load commons-codec.  This is on Mac OS 10.6.8, although I'm not sure it matters much.  This makes it totally unusable for me.

Getting org.scala-tools.sbt sbt_2.8.1 0.10.1 ...

:: problems summary ::
:::: WARNINGS
        [NOT FOUND  ] commons-codec#commons-codec;1.2!commons-codec.jar (2ms)

```
==== Maven2 Local: tried

  file:///Users/benwing/.m2/repository/commons-codec/commons-codec/1.2/commons-codec-1.2.jar

    ::::::::::::::::::::::::::::::::::::::::::::::

    ::              FAILED DOWNLOADS            ::

    :: ^ see resolution messages for details  ^ ::

    ::::::::::::::::::::::::::::::::::::::::::::::

    :: commons-codec#commons-codec;1.2!commons-codec.jar

    ::::::::::::::::::::::::::::::::::::::::::::::
```

:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
download failed: commons-codec#commons-codec;1.2!commons-codec.jar
Error during sbt execution: Error retrieving required libraries
  (see /Users/benwing/devel/junto-1.2.0/project/boot/update.log for complete log)
Error: Could not retrieve sbt 0.10.1

**Comment by harrah** [comment]
Please use the mailing list for help.  At a minimum, the launcher version (0.11) and main sbt version (0.10) are incompatible.

**Comment by benwing** [comment]
harrah, this is a real issue.  This is not some "mailing list" issue.  The 0.11 vs. 0.10 issue is a typo; that run was 0.10.  No 0.11 vs 0.10 incompatibilities.

Let me repeat this:

The _FIRST_ time I downloaded sbt 0.11, and did _NOTHING_ other than run 'sbt' with _NO_ setup of anything, and _NO_ cache, it starts trying to download lots of files, and crashes on commons-codec.

Please, try removing commons-codec from both your Maven cache and your Ivy cache and anywhere else you might have it cached, then try running 'sbt update' or anything using version 0.11, and see if it is able to successfully load commons-codec.  I suspect the reason more people aren't seeing this is because it's already cached.

I did a search on the internet and saw various people with the same complaint; this indicates that it's real.

Please reopen; thanks.

**Comment by harrah** [comment]
I removed my caches the first time.  The request to use the mailing list is for your benefit.  I cannot reproduce, so you are unlikely to get a fix.  You may get better help from others there as well.

**Comment by benjaminparker** [comment]
I am experiencing the same problem i.e. sbt 0.11 failed on downloading common-codec 1.2

**Comment by Hockenberry** [comment]
I downloaded the sbt-launch.jar as featured. I'm experience the same problem as above
.

**Comment by Hockenberry** [comment]
Clearing all of $HOME/.ivy2, $HOME/.m2 and $HOME/.sbt solved the problem for me

**Comment by miguel-negrao** [comment]
I installed sbt 0.11 and got the exact same error... not a very bright start... Doing the above fixed it...

**Comment by lordB8r** [comment]
This error happened to me as well.  I cleary ~/.ivy2 and ~/.m2/repository/commons-codec and then it finally installed.

**Comment by fredferrao** [comment]
Same here. Same ~/.ivy and ~/m2 solution.

**Comment by laura-dietz** [comment]
Alternatively you can install the commons-codec v1.2 jar manually in your local mvn repository from a jar file.

Download jar from here: http://mvnrepository.com/artifact/commons-codec/commons-codec/1.2

Then call mvn install:install-file -DgroupId=commons-codec -DartifactId=commons-codec -Dversion=1.2 -Dpackaging=jar -Dfile=<your download directory here>/commons-codec-1.2.jar

**Comment by jfmwz** [comment]
I have the same problem with sbt 0.12.2.jar
I remove the directory commons-codec in .m2 and .ivy2

Then the problem was resolved.

**Comment by jsuereth** [comment]
This is most likely due to a bad cache from prior sbt/ivy usages.   At one point during some repository migration, there was a "bad" commons-code pom.xml floating around. If you managed to cache that, then the only solution was to remove it.   Sorry for an inconveinience.  Most likely, that's what you ran into.
