### ISSUE TITLE
0.13.9 no longer honors semantic versioning of artifacts if 'latest.integration' is provided

### ISSUE THREAD

**Issue by khvatov** [sbt/sbt#2170]
In 0.13.8 when I specified an artifact version to be 'latest.integration' it would pull the latest SNAPSHOT available. After the upgrade to 0.13.9 same setup does not treat SNAPSHOT version as numbers. For example we have an artifact SNAPSHOT version going from _0.0.1-SNAPSHOT_ to _0.0.15-SNAPSHOT_. The upgraded version pulled 0.0.3-SNAPSHOT as the latest. 
I guess it is not sorting the version in character mode where _0.0.3-SHAPSHOT > 0.0.15-SNAPSHOT_, but must be **0.0.3-SNAPSHOT < 0.0.15-SNAPSHOT**

**Comment by dwijnand** [comment]
Can you provide the `maven-metadata.xml` for the artifact from the repository?

**Comment by dwijnand** [comment]
Move over, a step-by-step reproduction of the problem would be helpful. Here's [our guide](https://github.com/sbt/sbt/blob/v0.13.9/CONTRIBUTING.md#what-to-report).

**Comment by khvatov** [comment]
After looking at the  _maven-metadata.xm_ I noticed the latest artifact version was in fact listed as _0.0.3-SNAPSHOT_. The artifact was published with sbt and it used to work with 0.13.8. I'll look into why the version is not updating when publishing to Nexus from sbt.
Thank you.

**Comment by dwijnand** [comment]
Ah, as I suspected.

See http://www.scala-sbt.org/0.13/docs/sbt-0.13-Tech-Previews.html#Maven+compatibility+fix for details on that change in 0.13.9.

As I understand it you need to set Nexus up to behave correctly in terms on refreshing/rebuilding `maven-metadata.xml`. See http://stackoverflow.com/questions/4878808/maven-metadata-xml-is-not-updated-when-deploying-to-nexus for an example.

Also http://books.sonatype.com/nexus-book/reference/install.html might help.

**Comment by eed3si9n** [comment]
Nice work @dwijnand!
