### ISSUE TITLE
Unable to Pass Quotes to JavaDoc -tag Option

### ISSUE THREAD

**Issue by phancox** [sbt/sbt#2179]
In "build.sbt" have: 
`javacOptions in (doc) += "-tag todo:a:\"To Do:\""`

Run "publishLocal" and get:
`[error] javadoc: error - invalid flag: -tag todo:a:`

**Comment by SethTisue** [comment]
this is expected as that's two arguments, not one. you need to `++= Seq("-tag", ...)`
