### ISSUE TITLE
triple quote unexpected added parenthesis in sbt 0.13.7

### ISSUE THREAD

**Issue by MikaelMayer** [sbt/sbt#2182]
I came up with a bug while using triply-quoted strings in sbt 0.13.7
## Steps

Create an empty directory. Create a file `build.sbt` with the following content (make sure you have a newline between the definition and the implementation)

```
lazy val strangeBehavior= TaskKey[Unit]("strangeBehavior", "Perform strange behavior")

strangeBehavior:= {
    println("Value:")
    System.out.println("a<c p=\"\"/>")
    System.out.println("""a<c p=""/>""")
}
```

Create a file `project/build.properties` with the following content:

```
sbt.version=0.13.7
```

Run the following command

```
sbt strangeBehavior
```
## Problem

```
a<c p=""/>
a(<c p=""/>)
```
## Expectation

```
a<c p=""/>
a<c p=""/>
```
## Note

This is an almost-minimal reproduction bug. Removing the `build.properties` reverts to sbt version 0.13.0, which meets the expectation. Removing any part inside the string make the parenthesis disappear. I guess there is some kind of looking for xml entries? But nothing else justifies this bug.

**Comment by MikaelMayer** [comment]
Sorry now it is working if I switch to 0.13.9

**Comment by eed3si9n** [comment]
Yea. it's a known issue #1738 with 0.13.7.
