### ISSUE TITLE
Dependency resolution issues after upgrading to SBT 13.9

### ISSUE THREAD

**Issue by jpbetz** [sbt/sbt#2184]
With SBT 13.9 we have been observing build errors like the below.

The basic situations is:
- We have a largish project previously built on SBT 13.8 that we recently upgraded to SBT 13.9.
- When we bump a version of an sbt-plugin or project dependency, we sometimes see the below error during the next build.  We have also seen it after pulling seemingly minor changes from git.
- If we clear the entire ivy cache (`rm -rf ~/.ivy2`). SBT rebuilds the ivy cache and then appears to stabilize.

```
[error] /Users/nick/base/coursera/infra-services/libs/courTest/src/main/scala/org/coursera/test/JsAssertions.scala:3: object api is not a member of package play
[error] import play.api.libs.json.Json
```

Are there any known issues with ivy caches when upgrading to SBT 13.9?

I would love to give an exact means to reproduce but have not been able to find one yet. If I do I'll post it.

**Comment by eed3si9n** [comment]
```
[error] /Users/nick/base/coursera/infra-services/libs/courTest/src/main/scala/org/coursera/test/JsAssertions.scala:3: object api is not a member of package play
[error] import play.api.libs.json.Json
```

How do you know it's a "dependency resolution issue"? `show externalDependencyClasspath` can show the list of dependencies. Could you define a task that sorts that by file name? When the error happens again you can compare the list to see if it's missing a jar.

> Are there any known issues with ivy caches when upgrading to SBT 13.9?

Not that I know of.

**Comment by jpbetz** [comment]
Continuing to try to isolate the issue so it can be reproduced.

I've noticed that in many cases the first error reported is:

```
[error] missing or invalid dependency detected while loading class file 'SSealMessage.class'.
[error] Could not access type StrictLogging in value com.typesafe.scalalogging,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[error] A full rebuild may help if 'SSealMessage.class' was compiled against an incompatible version of com.typesafe.scalalogging.
[error] one error found
```

**Comment by jpbetz** [comment]
I'm still unable to build a reproducible case :(  I'll close this issue for now and open a new issue if we're able to isolate the issue better.

Thanks for looking at this @eed3si9n

**Comment by eed3si9n** [comment]
Thanks for the report anyway. I actually won't mind half-baked issue reports since the community may able to step in and fill the gap if they are seeing similar issue.
