### ISSUE TITLE
Download fails due to untrusted cert

### ISSUE THREAD

**Issue by benmccann** [sbt/sbt#2187]
I tried to follow the [install instructions](http://www.scala-sbt.org/download.html):

> echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
> sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
> sudo apt-get update
> sudo apt-get install sbt

However, I can't download run `sudo apt-get update` after adding the repository.

> Err https://dl.bintray.com  Packages
>   server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
> Ign https://dl.bintray.com  Translation-en_US
> Ign https://dl.bintray.com  Translation-en  
> Fetched 763 kB in 7s (106 kB/s)  
> W: Failed to fetch https://dl.bintray.com/sbt/debian/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

It seems this error indicates the certificate used isn't trusted by my new Linux Mint 17.2 Rafaela machine.

**Comment by benmccann** [comment]
Hmm, maybe this is more of a Bintray problem than SBT problem. Still I can't figure it out. https://dl.bintray.com/sbt/debian/ loads just fine in my browser

Bintray is using "Geo Trust CA - G4" cert with SHA-256 and SHA-1 fingerprints

**Comment by benmccann** [comment]
This seems to happen only on Linux Mint. I've tried Ubuntu 14.04, 14.10, and 15.04 and they all work. It fails on both Linux Mint 17 and Linux Mint 17.2

**Comment by benmccann** [comment]
Seems to be working for me now

**Comment by benmccann** [comment]
Tips for debugging from Bintray in case anyone else runs into this.

Please run the following steps and help send us the results.
1. In your Linux Mint machine, run the following command (see here for more details)
   update-ca-certificates -v
2. See if your issue has been resolved (You can also test the connection using curl https://dl.bintray.com/sbt/debian/ => You should not see any certificate issue. Instead, you should see a result similar to 
   
   $ curl https://dl.bintray.com/sbt/debian/
   &lt;html>
   &lt;head>
   &lt;script>
   //1441054088520
   function navi(e){
    location.href = e.target.href.replace('/%','/'); e.preventDefault();
   }
   &lt;/script>
   &lt;/head>
   &lt;body>
   &lt;pre>&lt;a onclick="navi(event)" href="%.work_1439324526009/" rel="nofollow">.work_1439324526009/&lt;/a>&lt;/pre>
   &lt;pre>&lt;a onclick="navi(event)" href="%Packages" rel="nofollow">Packages&lt;/a>&lt;/pre>
   &lt;pre>&lt;a onclick="navi(event)" href="%Packages.bz2" rel="nofollow">Packages.bz2&lt;/a>&lt;/pre>
   &lt;pre>&lt;a onclick="navi(event)" href="%Packages.gz" rel="nofollow">Packages.gz&lt;/a>&lt;/pre>
   &lt;pre>&lt;a onclick="navi(event)" href="%Release" rel="nofollow">Release&lt;/a>&lt;/pre>
   &lt;pre>&lt;a onclick="navi(event)" href="%Release.gpg" rel="nofollow">Release.gpg&lt;/a>&lt;/pre>
   &lt;pre>&lt;a onclick="navi(event)" href="%sbt-0.12.4.deb" rel="nofollow">sbt-0.12.4.deb&lt;/a>&lt;/pre>
   &lt;pre>&lt;a onclick="navi(event)" href="%sbt-0.12.4.deb.md5" rel="nofollow">sbt-0.12.4.deb.md5&lt;/a>&lt;/pre>
   &lt;pre>&lt;a onclick="navi(event)" href="%sbt-0.13.0.deb" rel="nofollow">sbt-0.13.0.deb&lt;/a>&lt;/pre>
   &lt;pre>&lt;a onclick="navi(event)" href="%sbt-0.13.0.deb.md5" rel="nofollow">sbt-0.13.0.deb.md5&lt;/a>&lt;/pre>
   &lt;pre>&lt;a onclick="navi(event)" href="%sbt-0.13.1.deb" rel="nofollow">sbt-0.13.1.deb&lt;/a>&lt;/pre>
   &lt;pre>&lt;a onclick="navi(event)" href="%sbt-0.13.1.deb.md5" rel="nofollow">sbt-0.13.1.deb.md5&lt;/a>&lt;/pre>
   &lt;pre>&lt;a onclick="navi(event)" href="%sbt-0.13.2.deb" rel="nofollow">sbt-0.13.2.deb&lt;/a>&lt;/pre>
   &lt;pre>&lt;a onclick="navi(event)" href="%sbt-0.13.2.deb.md5" rel="nofollow">sbt-0.13.2.deb.md5&lt;/a>&lt;/pre>
   &lt;pre>&lt;a onclick="navi(event)" href="%sbt-0.13.5.deb" rel="nofollow">sbt-0.13.5.deb&lt;/a>&lt;/pre>
   &lt;pre>&lt;a onclick="navi(event)" href="%sbt-0.13.5.deb.md5" rel="nofollow">sbt-0.13.5.deb.md5&lt;/a>&lt;/pre>
   &lt;pre>&lt;a onclick="navi(event)" href="%sbt-0.13.6.deb" rel="nofollow">sbt-0.13.6.deb&lt;/a>&lt;/pre>
   &lt;pre>&lt;a onclick="navi(event)" href="%sbt-0.13.6.deb.md5" rel="nofollow">sbt-0.13.6.deb.md5&lt;/a>&lt;/pre>
   &lt;pre>&lt;a onclick="navi(event)" href="%sbt-0.13.7.deb" rel="nofollow">sbt-0.13.7.deb&lt;/a>&lt;/pre>
   &lt;pre>&lt;a onclick="navi(event)" href="%sbt-0.13.7.deb.md5" rel="nofollow">sbt-0.13.7.deb.md5&lt;/a>&lt;/pre>
   &lt;pre>&lt;a onclick="navi(event)" href="%sbt-0.13.8.deb" rel="nofollow">sbt-0.13.8.deb&lt;/a>&lt;/pre>
   &lt;pre>&lt;a onclick="navi(event)" href="%sbt-0.13.8.deb.md5" rel="nofollow">sbt-0.13.8.deb.md5&lt;/a>&lt;/pre>
   &lt;pre>&lt;a onclick="navi(event)" href="%sbt-0.13.9.deb" rel="nofollow">sbt-0.13.9.deb&lt;/a>&lt;/pre>
   &lt;pre>&lt;a onclick="navi(event)" href="%sbt-0.13.9.deb.asc" rel="nofollow">sbt-0.13.9.deb.asc&lt;/a>&lt;/pre>
   &lt;pre>&lt;a onclick="navi(event)" href="%sbt-0.13.9.deb.md5" rel="nofollow">sbt-0.13.9.deb.md5&lt;/a>&lt;/pre>
   &lt;pre>&lt;a onclick="navi(event)" href="%sbt-0.13.9.deb.md5.asc" rel="nofollow">sbt-0.13.9.deb.md5.asc&lt;/a>&lt;/pre>
   &lt;/body>
   &lt;/html>)
3. If not, then manually copy the root and intermediate certificates of dl.bintray.com by copying the attached certificate (unzip pem files.zip) then running the commands below
   openssl x509 -in gw.crt -text >> /etc/ssl/certs/ca-certificates.crt
4. See if your issue has been resolved
5. If it is still not resolved, then we suspect that your Operating System came with one of outdated root and intermediate certificates for dl.bintray.com. Please run the following command and send us complete result:

openssl x509 -in /etc/ssl/certs/ca-certificates.crt -text -noout

**Comment by akshyag** [comment]
It could be because of the wrong date as well. Try updating the system date and then re-run the apt-get update.

**Comment by forzagreen** [comment]
I had the same problem. I figured out that my company blocks https://dl.bintray.com/sbt/debian
Try with another network.
