### ISSUE TITLE
[0.13.9] Memory settings in SBT_OPTS overridden by defaults in sbt-launch-lib.bash

### ISSUE THREAD

**Issue by ConradHughes** [sbt/sbt#2194]
Memory settings made in SBT_OPTS are not picked up by sbt-launch-lib.bash; it then overrides these by putting its own default memory settings _after_ SBT_OPTS when invoking the JVM.  Consequently attempts to increase heap limits using -Xmx in SBT_OPTS fail: they're always overridden back down to 1024m.

This can be verified by setting SBT_OPTS to -Xmx2G, invoking sbt and then looking at it using jvisualvm.

You can see that an attempt to detect memory settings in JAVA_OPTS is made in get_mem_opts() in sbt-launch-lib.bash, but the same isn't done for SBT_OPTS.  Consequently default memory options will be appended to the command line, overriding any values set in SBT_OPTS.

This may affect various other bug reports (e.g. #1610) where people are running out of memory even while setting very large heap limits in SBT_OPTS.

One fix might be to extend the current memory options test to look at SBT_OPTS as well as JAVA_OPTS; another might be to remove this test altogether and order the command line as follows:

  {default memory options} $JAVA_OPTS $SBT_OPTS

.. the last option specified on the command line is the one that counts.

**Comment by eed3si9n** [comment]
Ref paulp/sbt-extras#25

**Comment by ConradHughes** [comment]
[Thinking about it, the "default" memory options are changed by the -mem switch, so my "just use command line ordering" suggestion above would break '-mem' if JAVA_OPTS or SBT_OPTS were already set: you'd need to put settings from -mem last really.  Hi ho.]

**Comment by eed3si9n** [comment]
https://github.com/paulp/sbt-extras/blob/382a95926fb489c1757052925aa02460367c8815/sbt#L403-L413 should be ported to https://github.com/sbt/sbt-launcher-package/blob/master/src/universal/bin/sbt-launch-lib.bash. Ref #2161

**Comment by perovic** [comment]
Is there any progress on this bug? I am aware that you are searching for a more robust, portable solution, based on sbt-extras, but maybe fixing this ordering as a first step would help mitigate the issue?

Details:
I have encountered this bug too. After noticing that setting SBT_OPTS did not work, I tried passing arguments to the JVM directly (using -J), which worked. Hovering the appropriate "java" process in the System Monitor showed this command:
<code>java -Xms4G -Xmx4G -Xms1024m -Xmx1024m -XX:ReservedCodeCacheSize=128m -XX:MaxMetaspaceSize=256m -Xms3G -Xmx3G -jar /usr/share/sbt-launcher-packaging/bin/sbt-launch.jar</code>

The first set of arguments comes from SBT_OPTS set in .bashrc:
<code>export SBT_OPTS="-Xms4G -Xmx4G"</code>

The second set of arguments comes from get_mem_opts() ([get_mem_opts comes after SBT_OPTS in sbt-launch-lib.bash](https://github.com/sbt/sbt-launcher-package/blob/master/src/universal/bin/sbt-launch-lib.bash#L190)):
<code>local mem=${1:-1024}</code>
<code>...</code>
<code>echo "-Xms${mem}m -Xmx${mem}m -XX:ReservedCodeCacheSize=${codecache}m -XX:${class_metadata_opt}=${class_metadata_size}m"</code>

And finally, the third set comes from running sbt like:
<code>sbt -J-Xms3G -J-Xmx3G</code>

From what I have seen, most of the JVM implementations use the rightmost arguments when encountering duplicates. In this case SBT_OPTS is overridden by default settings from get_mem_opts() (I believe an unwanted behavior), and default settings are overridden by -J arguments (wanted behavior).

**Comment by dwijnand** [comment]
I've moved this to sbt/sbt-launcher-package#99.

**Comment by DanielGGordon** [comment]
Unfortunately for a project I'm stuck with this version of sbt for the time being. What is the workaround? Do I just need to specify `Xmx` in the `JAVA_OPTS` environment variable? Or will the `sbt-launch` script override that?

**Comment by dwijnand** [comment]
Projects should declare their sbt version in `project/build.properties` (under the `sbt.version` key), so you can upgrade your local sbt version without impacting the version used in your project.

**Comment by dwijnand** [comment]
An alternative is switching to bash launcher in sbt-extras: https://github.com/paulp/sbt-extras
