### ISSUE TITLE
Classpaths refers to repositories that don't actually exist

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#2195]
Classpaths (Defaults.scala) refers to repositories that don't exist:
- [typesafeSnapshots](https://github.com/sbt/sbt/blob/v0.13.9/main/src/main/scala/sbt/Defaults.scala#L1651) (Ivy)
- [sbtPluginSnapshots](https://github.com/sbt/sbt/blob/v0.13.9/main/src/main/scala/sbt/Defaults.scala#L1659)

There's also [typesafeRepo(status: String)](https://github.com/sbt/sbt/blob/v0.13.9/ivy/src/main/scala/sbt/Resolver.scala#L207) (Maven) which alludes to a possible Typesafe Maven snapshots repository.

The URLs are:
- https://repo.typesafe.com/typesafe/snapshots/
- https://repo.typesafe.com/typesafe/ivy-snapshots/
- https://repo.scala-sbt.org/scalasbt/sbt-plugin-snapshots/

Which redirect to:
- https://dl.bintray.com/typesafe/snapshots/
- https://dl.bintray.com/typesafe/ivy-snapshots/
- https://dl.bintray.com/sbt/sbt-plugin-snapshots/

which then 404.

Note, Bintray doesn't support snapshots.

**Comment by eed3si9n** [comment]
Those are used only implementation, so we should be able to get rid of them safely.

Here's where I see `typesafeSnapshots` used. As you said the repo no longer exists, so we can remove that and no one would notice.

```
sbtResolver := { if (sbtVersion.value endsWith "-SNAPSHOT") Classpaths.typesafeSnapshots else Classpaths.typesafeReleases },
```

`sbtPluginSnapshots`, I don't think is used in Defaults.scala.

**Comment by dwijnand** [comment]
There's a few more references in [DefaultOptions](https://github.com/sbt/sbt/blob/v0.13.9/main/src/main/scala/sbt/Opts.scala#L49-L56) but those aren't used anywhere else in the codebase.
