### ISSUE TITLE
error: recursive value needs type

### ISSUE THREAD

**Issue by kflorence** [sbt/sbt#2200]
I have a multi-project build where I have three projects defined: `interface`, `client` and `service` (root project):

``` scala
lazy val interface = (project in file("interface"))
  .settings(...)

lazy val client = (project in file("client"))
  .dependsOn(interface, service % "test->test")
  .settings(...)

lazy val service = (project in file("."))
  .dependsOn(interface)
  .settings(...)
```

As you can see, `client` and `service` both depend on `interface`, and `client` test scope also depends on `service` test scope. This works fine. However, I would like service, as the root project, to also `aggregate` the `client` project -- however, if I add this line to the `service` config:

``` scala
.aggregate(client)
```

I get the following error in the `client` project definition:

```
/Users/kflorence/dev/mosaic/utility-service/build.sbt:42: error: recursive value service needs type
  .dependsOn(interface, service % "test->test")
```

Is there any way to make this work?

**Comment by eed3si9n** [comment]
Related #2104 and #2183. This is because aggregate doesn't take the by-name parameter.
You could try working around this issue by creating a `Ref` value:

```
lazy val interface = (project in file("interface"))

lazy val client = (project in file("client"))
  .dependsOn(interface, service % "test->test")
lazy val clientRef = LocalProject("client")

lazy val service = (project in file("."))
  .aggregate(clientRef)
  .dependsOn(interface)
```

**Comment by kflorence** [comment]
@eed3si9n Thanks, using `LocalProject("client")` does indeed work.

I am still confused why using the by-name parameter works fine when I remove `service % "test->test"` from the `dependsOn` like so:

``` scala
lazy val interface = (project in file("interface"))
  .settings(...)

lazy val client = (project in file("client"))
  .dependsOn(interface)
  .settings(...)

lazy val service = (project in file("."))
  .dependsOn(client, interface)
  .settings(...)
```

**Comment by eed3si9n** [comment]
`aggregate` method does not take a [by-name parameter](https://www.artima.com/pins1ed/control-abstraction.html#9.5):

``` scala
  def aggregate(refs: ProjectReference*): Project = copy(aggregate = (aggregate: Seq[ProjectReference]) ++ refs)
```

but `Project#apply` does:

``` scala
  def apply(id: String, base: File, aggregate: => Seq[ProjectReference] = Nil, dependencies: => Seq[ClasspathDep[ProjectReference]] = Nil,
    delegates: => Seq[ProjectReference] = Nil, settings: => Seq[Def.Setting[_]] = Nil, configurations: Seq[Configuration] = Nil,
    auto: AddSettings = AddSettings.allDefaults): Project =
    unresolved(id, base, aggregate, dependencies, delegates, settings, configurations, auto, Plugins.empty, Nil)
```

Until [SIP-24](http://docs.scala-lang.org/sips/pending/repeated-byname.html) we can't mix vararg and by-name.

**Comment by bosyi** [comment]
Any updates on this? Workaround with LocalProject is still only way?

**Comment by dwijnand** [comment]
Yeah you need to either provide the type or use a project reference like `LocalProject`.

**Comment by bosyi** [comment]
I tried to set type `ProjectReference` to root project, sbt runs, but configuration of root project not applied then. like fork/true in settings. without `ProjectReference` all good

**Comment by eed3si9n** [comment]
Closing this since there's a workaround.
