### ISSUE TITLE
include managed sources in `packageSrc`?

### ISSUE THREAD

**Issue by aryairani** [sbt/sbt#2205]
class files built from managed sources go into the `packageBin` jar, but the managed sources for those class files don't go into the `packageSrc` jar.

Is there a straightforward way to get them included?

**Comment by eed3si9n** [comment]
+1

**Comment by aryairani** [comment]
I ended up using this formula I found somewhere online:

```
mappings in (Compile, packageSrc) ++= { // publish generated sources
  val srcs = (managedSources in Compile).value
  val sdirs = (managedSourceDirectories in Compile).value
  val base = baseDirectory.value
  (((srcs --- sdirs --- base) pair (relativeTo(sdirs) | relativeTo(base) | flat)) toSeq)
}
```

**Comment by mpollmeier** [comment]
also, `import Path._` is your friend

**Comment by anilkumarmyla** [comment]
Ran into this today (although this comment doesn't count as a vote up 🙈)

**Comment by ScalaWilliam** [comment]
@Friendseeker this is awesome. Would it be possible to do the same for _resources_ as well? It's in `resourceMapping`, and would be great for consistency/not having another bug ticket.

**Comment by Friendseeker** [comment]
> @Friendseeker this is awesome. Would it be possible to do the same for _resources_ as well? It's in `resourceMapping`, and would be great for consistency/not having another bug ticket.

I am currently busy with my undergraduate study so I cannot immediately look into it. I appreciate the feedback and will look into it once I have more free time.

By the way, may I ask for an example use case for including managed resources? While omission of managed sources causes inconvenience by hindering IDE source navigation, I don't know if omission of managed resources causes similar trouble.

**Comment by jroper** [comment]
I've opened #7630 which modifies `packageSrc` to gather `resources`, which includes both `managedResources` and `unmanagedResources`.
