### ISSUE TITLE
UpdateOptions does not have a tostring

### ISSUE THREAD

**Issue by OlegYch** [sbt/sbt#2208]
in 0.13.9 show updateOptions tells smth like sbt.UpdateOptions@b970d734
i'd prefer something useful like updateOptions.withCachedResolution(true).etc

**Comment by eed3si9n** [comment]
Hopefully gets fixed in 1.0 using sbt-datatype.
See also sbt/librarymanagement/pull/6.

**Comment by dwijnand** [comment]
Closing this as the equivalent ticket exists in sbt/librarymanagement#6.
