### ISSUE TITLE
Add buildTool property

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2211]
For #1827, maybe we should add something in POM so we know it's sbt origin:

```
<properties>
  <buildTool>org.scala-sbt:sbt:0.13.9;someotherthings</buildTool>
</properties>
```

What do you think? /cc @jsuereth, @dwijnand, @Duhemm

**Comment by dwijnand** [comment]
I always thought that it's quite the situation sbt is in that we model things with Ivy (for its superior model) but then accept Maven as the lingua franca for distribution, which means we have to re-interpret our own stuff having been mangled/shoehorned into Maven metadata.

Therefore if we need to add some metadata to the POM to recognise ourselves, I think it makes sense.

Granted we might want to use it as a last resort, if we're truly out of options (not referring to 1827, which I haven't looked at fully).

:+1:

**Comment by eed3si9n** [comment]
Not sure if this is still needed, but I am closing for now.
