### ISSUE TITLE
Strange behavior with string interpolation

### ISSUE THREAD

**Issue by MikaelMayer** [sbt/sbt#2221]
This is the smallest step that reproduce one bug. One step ahead is to insert a variable k in the middle assigned `"/>"` which trigger weird xml exceptions (although it is in a string)
### Steps
1. Create a `build.sbt` in an empty folder
2. Inside `project/build.properties`, add `sbt.version=0.13.9`
3. Add the following content to it:

```
lazy val strangeBehavior= TaskKey[Unit]("strangeBehavior", "Perform strange behavior")

strangeBehavior:= {
    val t = s""
    t
}
```
1. Type in the console `sbt`
### Expected

The sbt console opens.
### Actual

```
build.sbt:5: error: value
t is not a member of String
possible cause: maybe a semicolon is missing before `value t'?
    t
    ^
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

**Comment by eed3si9n** [comment]
This a known Scala 2.10 bug - https://issues.scala-lang.org/browse/SI-7919 (also see https://issues.scala-lang.org/browse/SI-9027 aka #1666). You can reproduce this without sbt:

``` scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

object A {
  val a = s""
  1
}

// Exiting paste mode, now interpreting.

<console>:3: error: ';' expected but integer literal found.
         1
         ^
```

The workaround would be to put the semicolon:

``` scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

object A {
  val t = s"";
  t
}

// Exiting paste mode, now interpreting.

<console>:9: warning: a pure expression does nothing in statement position; you may be omitting necessary parentheses
         t
         ^
defined module A
```
