### ISSUE TITLE
sbt crashes on Lustre and NFS because lock0 isn't implemented

### ISSUE THREAD

**Issue by dino-** [sbt/sbt#2222]
sbt uses a file locking mechanism that isn't supported on networked filesystems like Lustre and NFS.

Using the latest sbt downloaded [from the official website](http://www.scala-sbt.org/0.13/tutorial/Manual-Installation.html). Java version is 1.7.0_45

```
$ sbt --version
java.io.IOException: Function not implemented
        at sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
        at sun.nio.ch.FileDispatcherImpl.lock(FileDispatcherImpl.java:90)
        at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1063)
        at java.nio.channels.FileChannel.tryLock(FileChannel.java:1154)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:86)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
        at xsbt.boot.Using$.withResource(Using.scala:10)
        at xsbt.boot.Using$.apply(Using.scala:9)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at xsbt.boot.Launch.locked(Launch.scala:238)
        at xsbt.boot.Launch.app(Launch.scala:147)
        at xsbt.boot.Launch.app(Launch.scala:145)
        at xsbt.boot.Launch$.run(Launch.scala:102)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
        at xsbt.boot.Launch$.launch(Launch.scala:117)
        at xsbt.boot.Launch$.apply(Launch.scala:18)
        at xsbt.boot.Boot$.runImpl(Boot.scala:41)
        at xsbt.boot.Boot$.main(Boot.scala:17)
        at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: java.io.IOException: Function not implemented
```

**Comment by eed3si9n** [comment]
I don't see a good solution for this. Maybe implement a flag that says "YOLO I don't need locking" and run one instance of sbt at a time?
/cc @jsuereth

**Comment by gbersac** [comment]
I have the same error. Please fix it.

**Comment by holgerbrandl** [comment]
Same with me. Please provide a no-lock flag or something similar

**Comment by xfguo** [comment]
Same with me.

**Comment by dwijnand** [comment]
Upstream issue: https://bugs.openjdk.java.net/browse/JDK-8193594

**Comment by dwijnand** [comment]
The (long-winded, but currently available) workaround involves creating a custom launch config file and defining `lock` in the `[boot]` section as `false`.

**Comment by BassirouRabo** [comment]
what is the solution to fix it

**Comment by dwijnand** [comment]
One solution is fix the JDK (if possible). Another is to change the code in sbt/launcher to avoid using `lock0` (if possible). Another is to change the launchconfig file in sbt to expose a system property for the lock file so you can opt-out (what Eugene is referring to as the "YOLO I don't need locking" flag).

I'm happy to try and give more details if you let me know what solution you're interested in.

**Comment by BassirouRabo** [comment]
I think the second option to change the launcher.
find bellow my sbt-launcher.jar
`" zip.vim version v28

-  META-INF/
- org/
- org/apache/
- org/apache/ivy/
- org/apache/ivy/core/
- org/apache/ivy/core/cache/
- org/apache/ivy/core/deliver/
- org/apache/ivy/core/event/
- org/apache/ivy/core/event/download/
- org/apache/ivy/core/event/resolve/
- org/apache/ivy/core/event/retrieve/
- org/apache/ivy/core/install/
- org/apache/ivy/core/module/
- org/apache/ivy/core/module/descriptor/
- org/apache/ivy/core/module/id/
- org/apache/ivy/core/module/status/
- org/apache/ivy/core/publish/
- org/apache/ivy/core/report/
- org/apache/ivy/core/repository/
- org/apache/ivy/core/resolve/
- org/apache/ivy/core/retrieve/
- org/apache/ivy/core/search/
- org/apache/ivy/core/settings/
- org/apache/ivy/core/sort/
- org/apache/ivy/osgi/
- org/apache/ivy/osgi/core/
- org/apache/ivy/osgi/util/
- org/apache/ivy/plugins/
- org/apache/ivy/plugins/circular/
- org/apache/ivy/plugins/conflict/
- org/apache/ivy/plugins/latest/
- org/apache/ivy/plugins/lock/
- org/apache/ivy/plugins/matcher/
- org/apache/ivy/plugins/namespace/
- org/apache/ivy/plugins/parser/
- org/apache/ivy/plugins/parser/m2/
- org/apache/ivy/plugins/parser/xml/
- org/apache/ivy/plugins/report/
- org/apache/ivy/plugins/repository/
- org/apache/ivy/plugins/repository/file/
- org/apache/ivy/plugins/repository/url/
- org/apache/ivy/plugins/resolver/
- org/apache/ivy/plugins/resolver/util/
- org/apache/ivy/plugins/trigger/
- org/apache/ivy/plugins/version/
- org/apache/ivy/util/
- org/apache/ivy/util/extendable/
- org/apache/ivy/util/filter/
- org/apache/ivy/util/url/
- sbt/
- scala/
- scala/collection/
- scala/collection/convert/
- scala/collection/generic/
- scala/collection/immutable/
- scala/collection/mutable/
- scala/compat/
- scala/math/
- scala/reflect/
- scala/runtime/
- scala/sys/
- scala/util/
- scala/util/control/
- scala/util/hashing/
- scala/util/matching/
- scala/xml/
- xsbt/
- xsbt/boot/
- xsbti/
- module.properties`

**Comment by dwijnand** [comment]
So the line of the launcher that eventually calls `lock0` is: https://github.com/sbt/launcher/blob/v1.0.2/launcher-implementation/src/main/scala/xsbt/boot/Locks.scala#L88

Looks like some quite tricky code (I've never seen it before) what with dealing with potential dead locks and catching null pointer exceptions.

What I suggest is to attack this problem by testing: try and write an interesting test around that code, run it and see it fail on your NFS disk, and then try and see if you can rewrite it in a way that the intended behaviour is preserved and works on NFS.

Let me know how it goes.

**Comment by BassirouRabo** [comment]
I'm not scala developper, but java. So to writing test could take me time. What is the easiest way to fix it

**Comment by dwijnand** [comment]
Then I think the 3rd option, for which I've created https://github.com/sbt/sbt/pull/3927.

**Comment by BassirouRabo** [comment]
In which file should i add sbt.boot.lock-true

**Comment by dwijnand** [comment]
In the file `sbt/sbt.boot.properties` inside `~/.sbt/launchers/1.1.0/sbt-launch.jar`.

**Comment by brabo-hi** [comment]
I've extract the file sbt-launch.jar using (jar xf sbt-launch.jar), made changes and recreate the jar (jar cvf sbt-launch.jar *) . But got manifest error when i run (java -jar sbt-launch.jar)  "no main manifest attribute, in sbt-launch.jar"

**Comment by BassirouRabo** [comment]
**Is it what i have to add ?**
       [boot]
directory: ${sbt.boot.directory-${sbt.global.base-${user.home}/.sbt}/boot/}
lock: ${sbt.boot.lock-true}

**Comment by dwijnand** [comment]
correct

**Comment by BassirouRabo** [comment]
lock: ${sbt.boot.lock-true} should i put it true or false  (sbt.boot.lock) i mean?
