### ISSUE TITLE
farsi (utf8) strings in subProjects in multiProject mode compile mangled.

### ISSUE THREAD

**Issue by YounesRahimi** [sbt/sbt#2225]
for example a string like "ااردبیل"  will be compiled to a nonsense string and in runtime it will be a complete different string.

**Comment by YounesRahimi** [comment]
i'm using play 2.4.2 and scala 2.11.7 and sbt 0.13.8 and I'm using windows 10 with files with UTF8 format.

**Comment by ritschwumm** [comment]
what kind of code are you talking about? how is it compiled? to what?

**Comment by YounesRahimi** [comment]
I'm coding java and compile with 'activator compile' and compile to bytecode

**Comment by SethTisue** [comment]
Maybe you need to add an appropriate `-encoding ...` to `javacOptions` and/or `scalacOptions` to tell the compiler that your source files are UTF-8 encoded. Doesn't Java on Windows have a different default encoding?

It seems highly unlikely that whatever you're experiencing is actually an sbt issue, per se.

**Comment by eed3si9n** [comment]
> farsi (utf8) strings in subProjects in multiProject mode compile mangled. 

Is farsi string used as the name of the subproject?
Also could you tell how you're running sbt?
I've had issue sbt mangling Japanese text on the sbt shell personally, so what I do is I pass in an environment variable `$SBT_OPTS`, which is set as follows:

```
-XX:MaxPermSize=512M -Dfile.encoding=UTF-8
```

(My actual variable is called `$CONSCRIPT_OPTS` but that's a different story).

**Comment by YounesRahimi** [comment]
thanks @SethTisue :+1:   I added  the code below to all of my build.sbt files and it worked.

```
scalacOptions ++= Seq("-encoding", "UTF-8")

javacOptions ++=Seq("-encoding", "UTF8")
```

@eed3si9n:

> is farsi string ...?  

no

> Also could you tell...?

yes. I'm using activator 1.3.6 as a wrapper of sbt.  

thank you all people.
