### ISSUE TITLE
Ability to signal problems whose call stack is not relevant

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [sbt/sbt#2227]
Currently we have this API:

``` scala
package object sys {
  /** Throw a new RuntimeException with the supplied message.
   *
   *  @return   Nothing.
   */
  def error(message: String): Nothing = throw new RuntimeException(message)
}
```

I'd like to have an API to signal errors whose call stack is not relevant.

A call stack is quite noisy, and for known problem is useless.

It could be implemented by throwing an special exception type, that when catched, would produce no call stack report.

**Comment by eed3si9n** [comment]
https://stackoverflow.com/a/53525281/3827
