### ISSUE TITLE
Compile after clean breaks in a multi-project w/GenBCode enabled

### ISSUE THREAD

**Issue by lespea** [sbt/sbt#2231]
See my demo project [here](https://github.com/lespea/SbtBuiltError) for info on the problem.

**Comment by eed3si9n** [comment]
Duplicate of sbt/sbt#2076, which was worked around in scala/scala#4588?

**Comment by lespea** [comment]
Ah sorry I tried searching for GenBCode but I must have mistyped it. So if I understand correctly once scala 2.11.8 is released this should be fixed?

**Comment by eed3si9n** [comment]
I guess so.

**Comment by SethTisue** [comment]
@lespea if you don't want to wait for 2.11.8, you can test it now with a 2.11.x nightly

**Comment by lespea** [comment]
I tried it with the latest nightly and everything worked as expected. Thanks!
