### ISSUE TITLE
Initialization ordering of subprojects is undefined

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2232]
Ref #2090
## steps

Use sbt 0.13.9. Create 

``` scala
import sbt._
import Keys._

object FooBuild extends Build {
  lazy val intTask = taskKey[Int]("int task")
  val api = project.
    settings(
      intTask := 0
    )
  val database = project
  val web = project.
    dependsOn(api, database).
    settings{
      intTask in api := 1
    }
  val foo = project
}
```

Run `show api/intTask`. It should display:

```
[info] 0
```

Next comment out `val foo = project`:

``` scala
  // val foo = project
```

Run `show api/intTask`. It should display:
## problem

```
[info] 1
```

Note that `foo` subproject has no relationship with `api` or `web`.
It seems like the initialization ordering of the subproject is not clearly defined.
## expectation

There should be a clear ordering on which one wins, or forbid initializing other subproject's keys.
## note

I'm not sure if this is the smoking gun, but... https://github.com/sbt/sbt/blob/0.13.9/main/src/main/scala/sbt/Load.scala#L319

``` scala
      (new sbt.PartBuildUnit(unit, defined.map(d => (d.id, d)).toMap, rootProjects.map(_.id), buildSettings(unit)), externals)
```

`toMap` has no notion of ordering. This is transformed into a `LoadedBuildUnit`. See code around https://github.com/sbt/sbt/blob/0.13.9/main/src/main/scala/sbt/Load.scala#L385-L408. Somehow this `Map` it turned into `Seq`, which I suspect non-determinism.

**Comment by eed3si9n** [comment]
A potential workaround at least for #2090:

``` scala
import sbt._
import Keys._

object FooBuild extends Build {
  lazy val intTask = taskKey[Int]("int task")
  lazy val preIntTask = taskKey[Unit]("pre int task")
  lazy val helloTask = taskKey[Unit]("hello task")
  val api = project.
    settings(
      intTask := 0,
      intTask <<= intTask dependsOn preIntTask,
      preIntTask <<= preIntTask or Def.task {()}
    )
  val database = project
  val web = project.
    dependsOn(api, database).
    settings(
      helloTask := { println("hello") },
      preIntTask in api := { helloTask.value }
    )
  val foo = project
}
```

`preIntTask` is defined twice but protected by `or`.

**Comment by eed3si9n** [comment]
Perhaps we should emulate top-to-bottom semantics within a same file by keeping the position around.

**Comment by jsuereth** [comment]
That's not the smoking gun.

The list is later sorted.   The issue, I think, is the `extends sbt.Build` support using reflection to find root projects ant not sharing the logic with the load code.    You'll want to dive into how we detect what the root project is in various scenarios.  I think for "Buiild.scala" it's "the first in the sequence" whereas for .sbt files it's more complicated (and involves a name-sort).
