### ISSUE TITLE
High memory consumption with name hashing enabled

### ISSUE THREAD

**Issue by dmmartinez** [sbt/sbt#2238]
See:

https://github.com/dmmartinez/sbt-memory

It's a dumbed derivative from a real project I am working in. Can't compile (Out Of Memory) with 4G memory heap with name hashing enabled (Needs 8G).

Real (private) project can't compile with name hashing even with 24G memory heap, whithout name hashing under 8G

**Comment by eed3si9n** [comment]
@Duhemm This is something we should hunt down to at least get some rough idea of where it's coming from.

**Comment by adriaanm** [comment]
This compiles (slowly -- takes 136s on my laptop) with my local build of sbt. I think https://github.com/adriaanm/sbt/commit/25b047b726f0a22f173e6b486dfff30d580ed839 fixed it (when applied to 0.13.8). It indeed OOMs for me on 0.13.8. I'm planning to submit a PR with this fix, but don't have a firm date for that yet.

**Comment by adriaanm** [comment]
(That said, we should probably also see whether we can make this compile faster?)

**Comment by eed3si9n** [comment]
.@Duhemm said a large number of symbols are coming from macros. When I saw that [the example code](https://github.com/dmmartinez/sbt-memory/blob/master/src/main/scala/Data.scala) is using Pickling, it sorted of made sense. It would be nice if we can speed things up, but I'm more concerned about carrying name hashes around in the memory if it stays around beyond xsbt-dependency phase if that becomes too large.

**Comment by gkossakowski** [comment]
This issue can be reproduced without macros involved but by deeply nesting classes:

``` scala
class A0 {
  def foo: Int = 7
  class A1 {
  def foo: Int = 7
  class A2 {
  def foo: Int = 7
  class A3 {
  def foo: Int = 7
  class A4 {
  def foo: Int = 7
  class A5 {
  def foo: Int = 7
  class A6 {
  def foo: Int = 7
  class A7 {
  def foo: Int = 7
  class A8 {
  def foo: Int = 7
  class A9 {
  def foo: Int = 7
  class A10 {
  def foo: Int = 7
  class A11 {
  def foo: Int = 7
  class A12 {
  def foo: Int = 7
  class A13 {
  def foo: Int = 7
  class A14 {
  def foo: Int = 7
  class A15 {
  def foo: Int = 7
  class A16 {
  def foo: Int = 7
  class A17 {
  def foo: Int = 7
  class A18 {
  def foo: Int = 7
  class A19 {
  def foo: Int = 7
  class A20 {
  def foo: Int = 7
  class A21 {
  def foo: Int = 7
  class A22 {
  def foo: Int = 7
  class A23 {
  def foo: Int = 7
  class A24 {
  def foo: Int = 7 
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
```

The problem is exponential time complexity of the tree walk that collects symbols. The logic recurses into the same `Template` tree multiple times. Pickling happens to generate deeply nested classes hence triggers the problem.

**Comment by romanowski** [comment]
I think this commit adriaanm@58b80186fb6caaf16aa690342cfad21f9a66020e fixed mentioned problem.

**Comment by gkossakowski** [comment]
Yes, this problem is fixed.
