### ISSUE TITLE
Alt-d hangs sbt if there is nothing to delete

### ISSUE THREAD

**Issue by SRGOM** [sbt/sbt#2239]
SBT version: 0.13.9
Reproduction: Hit alt-d in a situation where there is nothing in front of the cursor.
.jline.rc contents:

```
set editing-mode-emacs
jline.inputrc=$HOME/.inputrc.b
```

.inputrc.b contents:

```
#empty 
```

This is somewhat annoying because sbt takes a bit to load and for someone who prefers shortcuts.

**Comment by dwijnand** [comment]
Duplicate of #1413
