### ISSUE TITLE
'exclude' command shouldn't be repeated in children projects build.sbt

### ISSUE THREAD

**Issue by takiri** [sbt/sbt#2241]
Hi,

I have a Play project containing many modules. I use a project/CommonBuild.scala for common dependancies, and write the module-specific dependancies in each module build.sbt using   libraryDependencies += ...

In both CommonBuild.scala and some build.sbt files, I have denpendancies importing the slf4j-simple jar, resulting in a "Class path contains multiple SLF4J bindings" error (see [issue #3206 on playframework GitHub](https://github.com/playframework/playframework/issues/3206) ).

So I added the following line to correct it:
libraryDependencies ~= { _.map(_.exclude("org.slf4j", "slf4j-simple")) }
The problem is: I have to add this line in each build.sbt (with the buggy dep) as well as in the CommonBuild. I thought having the exclude in the CommonBuild (or at least in the parent build.sbt) would be sufficient due to projects inheritance. Did I miss something ?

I am using Activator 2.3.5 with SBT 0.13.9.

Many thanks

**Comment by takiri** [comment]
I went on and found the 'excludeDependencies' key. But neither adding it in my CommonSettings.scala/settings nor in my parent build.sbt did the trick.

**Comment by jsuereth** [comment]
I'll let @eed3si9n comment here for more details.
1. Look at module-level excludes, rather than libraryDependency level excludes.  If you're not interfacing with Maven (or pom.xml files) it should help you immensely.
2. If you're going to interface with maven in any way (or pom.xml files) you HAVE to do it the way you are doing it now, as that's the only real supported mechanism outside of parent-poms and we don't have an Ivy<->ParentPom bridge.  I agree this is frustrating.

**Comment by takiri** [comment]
Thanks a lot for the answer!

The jars importing the ****\*  "slf4j-simple" are indeed Maven projects. Is that what you mean by "interfacing with Maven"?
The rest of my project is full Play/SBT.

**Comment by eed3si9n** [comment]
As noted here
http://www.scala-sbt.org/0.13/docs/sbt-0.13-Tech-Previews.html#Project-level+dependency+exclusions

project-level dependency exclusions is an experimental feature that's not translated into pom.xml.

**Comment by jvican** [comment]
What do you mean by your last comment @eed3si9n ? It's not clear to me whether this is a bug or not, and if it is what's failing. Can you please elaborate?

**Comment by eed3si9n** [comment]
At the time `excludeDependencies` was introduced it was treated as an experimental feature without full Maven compatibility. Since then @dwijnand has added support to pom.xml in #2035

**Comment by jvican** [comment]
Any reason why this isn't closed then?

**Comment by eed3si9n** [comment]
Probably an oversight. We can close this.
