### ISSUE TITLE
``fork in run := true`` behaves differently depending on how it is employed

### ISSUE THREAD

**Issue by frgomes** [sbt/sbt#2245]
SBT version 0.13.9
## Scenario 1

A multiproject build with configurations and `fork in run := true` associated to the root project. Something like this:

``` scala
lazy val root = project in(file(".")).settings( fork in run := true )

lazy val module = project in(file("module")
  .configs(MyRunner)
  .settings(inConfig(MyRunner)(mainClass in Compile := ...))
```

In this case, when you run the application in a subprocess `module/MyRunner:run`, it runs the application in a subprocess but does not properly return to SBT command line after a

Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "AWT-EventQueue-0"
## Scenario 2

A multiproject build with configurations and `fork in run := true` associated only to the configuration which needs to be forked. Something like this:

``` scala
lazy val root = project in(file("."))

lazy val module = project in(file("module")
  .configs(MyRunner)
  .settings(inConfig(MyRunner)(
    Seq(
      fork in run := true,
      mainClass in Compile := ...):_*)
```

In this case, when you run the application in a subprocess `module/MyRunner:run`, it runs the application in a subprocess, finishes properly and returns properly to SBT command prompt after a 

Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "AWT-EventQueue-0"

**Comment by frgomes** [comment]
Possibly related to https://github.com/sbt/sbt/issues/1293

**Comment by jsuereth** [comment]
Regarding scenario 1, what do you mean "after a Exception: sbt.TrapExitSecurityException".  That should only happen if we're not actually creating a sub-process....

Regarding Scenario 2, I actually don't expect that to actually be forking gi en the configuration you've written (see my comment on one of your other bugs).   Are you positive these are actually forking?  Given the design of things, neither of these examples shoudl actually be forking AND the exception thrown seems to support that theory.

**Comment by frgomes** [comment]
I will work more on these examples and provide the sources in github in case the alleged error turns out to be confirmed. Thanks a lot.

**Comment by frgomes** [comment]
This is actually a duplicate of #2247, before the issue was properly understood and circumvented.
So, it can be closed.
