### ISSUE TITLE
Enhancement: api for task execution status

### ISSUE THREAD

**Issue by matanox** [sbt/sbt#2248]
Closest ticket I found was https://github.com/sbt/sbt/issues/1209.
How can task execution state be reported by an external tool, or an sbt plugin? I think it would be easy to provide a front-end that shows execution flow for complex sbt builds, if only the state could be known to an sbt plugin.

One thought about an API enabling that would comprise these endpoints:
- querying status
- registering callbacks for status change (`Starting`, `Finished`)
- Getting the task's execution result (success/fail/interrupted) may probably be done with existing API, same as a handle to its logger/s.

There is already a simple way to get the topology of the graph (e.g. https://github.com/jrudolph/sbt-dependency-graph), so the rest is easy to implement, if there is API.

Does this sound like a big change in the code?

**Comment by eed3si9n** [comment]
There's https://github.com/sbt/sbt-core-next#sendeventserviceplugin

**Comment by SethTisue** [comment]
is https://github.com/sbt/sbt/pull/7350 relevant here?

**Comment by eed3si9n** [comment]
Yea. I think it's exactly that.
