### ISSUE TITLE
publishArtifact := false will not prevent ivy files from being published

### ISSUE THREAD

**Issue by matanox** [sbt/sbt#2249]
Looks like ivy files will get locally published, by the `publishLocal` task of subprojects in a multi-project build. sbt 0.13.9. 

`show artifacts` gives an empty List for the subproject, but still ivy files get locally published.

That happens when `publishArtifact := false` is placed outside any project definition. When it is placed inside the root project's `.settings()` no ivy files (nor other files) are locally published, for the root project.

**Comment by l15k4** [comment]
this is also a strange behavior in `0.13.13` : 
```
> example/publishArtifact
[info] false
> example/publish
[info] :: delivering :: net.globalwebindex#saturator-example_2.11;0.06-SNAPSHOT :: 0.06-SNAPSHOT :: integration :: Fri Jan 27 01:43:02 UTC 2017
[info] 	delivering ivy file to /home/lisak/src/gwi/saturator/example/target/scala-2.11/ivy-0.06-SNAPSHOT.xml
[trace] Stack trace suppressed: run last example/*:publishConfiguration for the full output.
[error] (example/*:publishConfiguration) Repository for publishing is not specified.
[error] Total time: 0 s, completed Jan 27, 2017 1:43:02 AM
```

It tries to publish even though it is disabled ...

**Comment by eed3si9n** [comment]
`publish / skip` - https://github.com/sbt/sbt/pull/3380
