### ISSUE TITLE
Replace last resolution output line when -Dsbt.log.noformat=true is not used

### ISSUE THREAD

**Issue by matanox** [sbt/sbt#2250]
In the default output mode (unlike when using `-Dsbt.log.noformat=true`), asci control codes are used to flash the resolution messages such that they all show on the same row on screen. So many lines like follows will flash until the resolution for the current update task finishes, at which point the last resolution will remain.

```
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
```

This makes screen outputs arbitrarily confusing and even misleading. The correct way should likely be not to keep the last resolution message at all (replace it by a vanilla message saying update is done, if for technical reasons asci codes require a new line). 

`-Dsbt.log.noformat=true` can keep its current behavior of course.

This would provide a more correct user experience, unless you somehow assume projects with a single library dependency were the norm or the most often case.

**Comment by eed3si9n** [comment]
We no longer display Resolving.. message.
