### ISSUE TITLE
illegal dynamic reference when passing a `ProjectReference` to an `in`

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#2267]
This

``` scala
    scalacOptions ++= plugins.map { plugin: ProjectReference =>
      "-Xplugin:" + packageBin.in(Compile).in(plugin).value
    }
```

results in a compile error

```
[error] D:\my\project\MyBuild.scala:192: Illegal dynamic reference: plugin
[error]         "-Xplugin:" + packageBin.in(Compile).in(plugin).value
```

note that this also happens if the `plugin` is defined more strictly as a `LocalProject` (which is the implementation I am using).

It would appear that the macro is using too much magic.

Is there a workaround? (That doesn't involve generating the build definition file).

My current workaround is a massive hack that only works for my one project (i.e. effectively hardcoding the path to the plugin file in the build definition, and then remembering to run packageBin on the relevant plugin modules before doing a build).

**Comment by eed3si9n** [comment]
Not sure if this is what you're looking for, but the following works for me:

``` scala
lazy val core = project

def allPackages(filter: ScopeFilter) = Def.taskDyn {
  packageBin.all(filter)
}
scalacOptions += {
  val pkgs = allPackages(ScopeFilter(inProjects(LocalProject("core")), inConfigurations(Compile))).value
  "-Xplugin:" + pkgs.head.toString
}
```

**Comment by fommil** [comment]
ok cool, I'll try that out tomorrow and let you know. Shouldn't the original syntax support this though? This use of `taskDyn` seems a bit hacky.

**Comment by eed3si9n** [comment]
This is somewhat expected of the build.sbt DSL since anything that gets called with `(xxxx).value` means `(xxxx)` part is expanded by the macro as a dependency of the current task, which runs prior to the current task's curly brace. This requires everything to be resolved statically.

**Comment by fommil** [comment]
:+1:

**Comment by fommil** [comment]
This should be reopened, I'm still seeing `illegal dynamic reference` when using your code.

Try making your `"core"` a `Seq[String]` and map over it.

**Comment by fommil** [comment]
yes, I believe the issue here is using an `explicit` `String` vs using a value.

**Comment by eed3si9n** [comment]
You have to push any dynamic part into the dynamic task.

``` scala
lazy val core = project
lazy val nameOfProjects = settingKey[Seq[String]]("something")
lazy val allPackages = Def.taskDyn {
  val filter = ScopeFilter(inProjects(nameOfProjects.value map { LocalProject(_) }: _*), inConfigurations(Compile))
  packageBin.all(filter)
}
nameOfProjects := List("core")
scalacOptions += {
  val pkgs = allPackages.value
  "-Xplugin:" + pkgs.head.toString
}
```

**Comment by fommil** [comment]
I don't know the `nameOfProjects` in advance, so I have to do something like this and it's still giving the same warning (note that `plugins` is also not known in advance, it is calculated by parsing an Eclipse project definition):

```
       scalacOptions ++= plugins.map { plugin =>
        "-Xplugin:" + Def.taskDyn {
          packageBin.all(ScopeFilter(inProjects(plugin), inConfigurations(Compile)))
        }.value
      }
```

**Comment by fommil** [comment]
have a look at https://gist.github.com/fommil/aa6b71397ccb474a0660 to see what I mean.

**Comment by fommil** [comment]
line 124 ish

**Comment by fommil** [comment]
I got it! Defining

```
     val internalPlugins = Def.taskDyn {
      packageBin.all(ScopeFilter(inProjects(plugins: _*), inConfigurations(Compile)))
    }
```

outside the `.settings` for the `Project` that I'm declaring, and then calling it with

```
      scalacOptions ++= internalPlugins.value.map {
        plugin => "-Xplugin:" + plugin
      }
```

inside the `Project`'s `settings` seems to do the trick.

Very subtle! Thanks :smile:
