### ISSUE TITLE
unmanagedJars doesn't work as documented

### ISSUE THREAD

**Issue by samthebest** [sbt/sbt#2269]
The documentation says this should work:

```
unmanagedBase <<= baseDirectory { base => base / "custom_lib" }
```

But I get

```
...build.sbt:25: error: type mismatch;
 found   : java.io.File
 required: sbt.Task[sbt.Keys.Classpath]
  unmanagedJars <<= baseDirectory { base => base / "custom_lib" }
```

Also, I can't see any simple way to just use an absalute path.

**Comment by samthebest** [comment]
Problem was the epic complexity in these super super simple things it's difficult to see little errors like mixing up "unmanagedBase" with "unmanagedJars"

Solution to getting an absalute path is: 

```
unmanagedBase <<= baseDirectory { base => new File("/foo/bar") }
```

**Comment by fommil** [comment]
you could also do

```
unmanagedBase := file("/foo/bar")
```

(or maybe wrap the `file` with `{ Attributed.blank(file("/foo/bar")) }` ... depends on the type signature)
