### ISSUE TITLE
compile only the selected project / config

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#2270]
my work project is gigantic and even if I make a change in a lower-level project that doesn't change the ABI, the incremental compiler does 30+ minutes of needless work.

It would be extremely good if it were possible to have a compile variant that disabled transient dependency tracking between projects / configs. e.g.

```
disableCompileDependencies := true
my_low_level_lib/compile
my_app/test
```

**Comment by easel** [comment]
Agreed large projects need more ability to fine-tune. The "best practice" using lots of sub modules tends to really fall apart between slow resolution times and needlessly recompiling all dependencies. Another option would be a way to flag dependsOn to behave as if module dependencies were actually published -- I sometimes work around this by adding them manually and running publishLocal on the individual projects.

**Comment by eed3si9n** [comment]
> my work project is gigantic and even if I make a change in a lower-level project that doesn't change the ABI, the incremental compiler does 30+ minutes of needless work.

I've seen similar behavior. You might be hitting some bug of incremental compiler, but in theory it shouldn't take 30+ minutes if you didn't change anything. Does the compiler actually compile things if you see the debug log?

**Comment by eed3si9n** [comment]
@easel 

> Another option would be a way to flag dependsOn to behave as if module dependencies were actually published

``` scala
exportJars := true
```

See  http://www.scala-sbt.org/0.13/docs/Howto-Package.html

**Comment by fommil** [comment]
@eed3si9n I do change something in the dependency module, but it doesn't change the API or ABI (e.g. changes to the internals of a method) so it shouldn't be recompiling everything all the way up.

**Comment by fommil** [comment]
(btw, somewhat related to exportJar, but I'm absolutely certain that if `scalac` output directly into the `jar` file on windows, it would dramatically speed up compile times. The Windows filesystem is **terrible**)

**Comment by easel** [comment]
exportJar's gets half way there in that it builds the jars and uses them, but it doesn't prevent the dirty checking and recompilation of the entire tree. If there was a "compile -intransitive" option that just skipped that stuff entirely I think we'd have a working solution.

**Comment by fommil** [comment]
I thought of a workaround involving `exportJar`. If it was possible to do this, it would work:

1. compile my low-level package (producing the jar)
2. flag all projects as "up to date"
3. run my top-level app / tests

is this possible?

**Comment by fommil** [comment]
after some testing, the `exportJar` approach above **does not work**.  Two use cases:
1. standard incremental compile (no changes to source code, expect a no-op, measures just the overhead cost of scanning) : `my_app/compile` --- takes about 1 minute scanning all the dependency jars to determine that no compilation is necessary. This should be instant.
2. make a change to `my_low_level_lib`, generate the jar, then `my_app/run-main` --- still takes 30+ minutes as it checks/recompiles everything. This should also be instant.

One small thing would allow this to be fixed: if the `exportJar` for all transient dependencies (i.e. the `packageBin` ) could be flagged as "up to date" then it should be possible to have a workflow such that both the usecases result in near-instant compiles. Consider this workflow of `sbt` commands for the above step 2, 
1. `exportJarTracking` // disables tracking (enabled by default)
2. (make internal change to `my_low_level_lib`)
3. `my_low_level_lib/compile` (generates `packageBin`)
4. `my_app/run` (instant)
5. `exportJarTracking` // enables tracking
6. (make API/ABI change to `my_low_level_lib`)
7. `my_app/compile` // recompiles everything necessary, go for coffee

note that it would be useful if test configs aggressively checked if their compile configs are up to date, e.g. `my_app/test` should run `my_app/compile` if the sources are newer than the jar.

**Comment by fommil** [comment]
This is looking suspicious: https://github.com/sbt/sbt/blob/v0.13.9/main/src/main/scala/sbt/Defaults.scala#L604

The thing with `exportJars` is that it adds `packageBin.value` for each dependency onto the classpath of each project. But `packageBin` is a `Task` not a `Setting`! That means packaging is effectively invoked for the entire tree.

Perhaps a better approach would be for `exportJars := true` (or an alternative) to simply add the `File` of the dependency jars onto the classpath. It could remain a `Task` so that it can fall back to `packageBin.value` if the file doesn't exist. A possible problem with this approach as that `my_app/compile` will not generate the `packageBin` so a subsequent call to `my_app/test` would actually use the old code. The `compile` task would have to be updated to update the jar file.

**Comment by fommil** [comment]
using the example in #2266 with `-Dsbt.task.timings=true` gives

```
> obf-518286142/compile
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
Total time: 33600.107703 ms
  {REMOVED}/compile:packageBin: 2765.726925 ms
  {REMOVED}/compile:compileIncremental: 2670.3013309999997 ms
  {REMOVED}/compile:packageBin: 2527.2058079999997 ms
  {REMOVED}/compile:packageBin::mappings: 1821.446489 ms
  {REMOVED}/compile:packageBin::mappings: 1730.042544 ms
...
```

then thousands of lines down to sub-ms timings. Interestingly, the task took 42s, even though the profiler only reports 34s, so there is still a further fixed overhead.

**Comment by fommil** [comment]
I've looked into the possibility of augmenting the behaviour of `exportJars` and tracked the part I need to override to `Classpaths.productsImplTask`, which is unfortunately `private` and on an `object`.

`Classpaths.exportProductsTask` is the next method up, but unfortunately there is no possibility of overriding it since it lives on an `object`.

Up one more level is:

```scala
  private[this] def classpaths: Seq[Setting[_]] = Seq(
    fullClasspath <<= concatDistinct(exportedProducts, dependencyClasspath),
    exportedProducts <<= exportProductsTask
    ...)
```

`exportedProducts` is referenced in several places throughout the codebase so I probably don't want to touch it incase it messes something up. Although it may come to this.

`classpaths` is only referenced by `Defaults.configSettings`, but it is used by `Defaults.configSettings` and that is used by pretty much everything.

So I think what I want to do is provide an alternative implementation of `fullClasspath` which does not use `exportedProducts`. However, I haven't got a clue how to do that because it seems I'd need to. 

@eed3si9n am I going in the right direction here or is there a cleaner way to override `fullClasspath` / `exportedProducts` such that `exportProductsTask` is never called?

**Comment by fommil** [comment]
uugh, `APIMappings` is `private`, ok, provide my own `store`

**Comment by fommil** [comment]
The dumb / simple approach doesn't work

```
    exportedProducts <<= myExportProductsTask
```

giving `References to undefined settings`, even if I do it on each `Project`.

Hmm, I'm running out of ideas now... short of cutting a custom build of `sbt`.

**Comment by fommil** [comment]
I suppose overriding `packageBin.task` would also achieve the same thing, but that has the same problem of working out how to actually override it.

**Comment by eed3si9n** [comment]
You can implement `packageBin` that does nothing if the file exists. And `realPackageBin` in case you want to package normally.

**Comment by fommil** [comment]
But how do I actually **set** that? Reference to undefined setting joy.

**Comment by eed3si9n** [comment]
``` scala
packageBin in Compile := {
  if (disableCompileDependencies.value && somefile.exists) ()
  else do_the_packaging()
  somefile
}
```

See https://github.com/sbt/sbt-zero-thirteen/blob/c5b7fc1d9c9fed8d210463d623eaecff4761d9c5/main/src/main/scala/sbt/Defaults.scala#L683-L700

**Comment by fommil** [comment]
Weird, I tried that and got undefined setting. Oh, I didn't use Compile! I'll try that out first thing, thanks!

**Comment by fommil** [comment]
ok, that seems to let me do some stuff! There seems to be a fixed overhead to invoking the new `packageBin` the first time, and I can't refer to the original `packageBin` (it gives an `undefined settings` error if I try to) but this gets one step closer to the workaround, thanks!

**Comment by fommil** [comment]
uuh, weirdness...

```scala
    packageBin in Compile := {
      println("MY PACKAGER")
      (packageBin in Compile).value
    }
```

gives

```
 my_lib/packageBin
[info] Packaging D:\my_app\scala-2.10\my_app_2.10-0.1-SNAPSHOT.jar ...
[info] Done packaging.
MY PACKAGER
```

which seems to suggest that there is some reverse ordering happening here :confounded:

**Comment by fommil** [comment]
hmm, there is no way to get a config for the location of the `packageBin` `File`, I'll have to hack that. It would be good to expose this as a key in mainline `sbt` (and in fact that might be all that is needed to fulfil this ticket since if my workaround works!)

**Comment by eed3si9n** [comment]
That's how sbt's DSL works. http://www.scala-sbt.org/0.13/tutorial/Custom-Settings.html#Execution+semantics+of+tasks
You can either use dynamic task or call the underlying impl, which I linked 3h ago.

**Comment by fommil** [comment]
this is as far as I got, but it's still calling out to the underlying impl of `packageBin` even thought the `if` returns true. Any hints? I tried changing to call `Defaults.packageTask` instead but it given "undefined setting". Is this going to involve some kind of `Task` zipping magic? I'll read the execution docs tonight, thanks, I hadn't read them in enough detail obviously.

```scala
    packageBin in Compile := {
      val module = projectID.value
      val dir = crossTarget.value
      val scala = scalaBinaryVersion.value
      val bin = dir / s"${module.name}_${scala}-${module.revision}.jar"
      println(s"PACKAGE $bin")

      //if (bin.exists()) bin
      // test that we're not *always* calling the packageBin
      if (true) bin
      else (packageBin in Compile).value
    }
```

**Comment by fommil** [comment]
oh this is probably macro joy, isn't it. I'll try to rewrite without `.value` on the `packageBin`

**Comment by fommil** [comment]
now testing this...

```scala
    packageBin in Compile <<= (
      projectID,
      (packageConfiguration in packageBin in Compile),
      (streams in packageBin in Compile)
    ).map { (module, config, s) =>
      val bin = config.jar
      if (!bin.exists()) Package(config, s.cacheDirectory, s.log)
      bin
    }
```

if this works, the question is if there is anything `sbt` core should do? Perhaps this is really just something that belongs in a plugin.

**Comment by fommil** [comment]
nope, that doesn't work... something is still calling out to the classpath scanning. I must have the wrong configuration or something

**Comment by fommil** [comment]
is the very act of asking for the `packageConfiguration` and `streams` in the `packageBin` scope causing the `packageTask` to be invoked?

**Comment by fommil** [comment]
I've narrowed it down to `mappings` as is the slow part. Need to reimplement that...

**Comment by fommil** [comment]
hmm, `packageOptions` also seems to force the slow bit too.

**Comment by eed3si9n** [comment]
> Fundamentally, this workaround is going to need a way to lazily invoke a dependent task. 

http://www.scala-sbt.org/0.13/docs/Tasks.html#Dynamic+Computations+with

**Comment by fommil** [comment]
**headslap** ok, that's my weekend sorted!

**Comment by fommil** [comment]
This seems to be doing something vaguely approximating what I'm after! :grinning: 

```scala
    packageBin in Compile := dynamicPackageBinTask.value
  )

  // WORKAROUND https://github.com/sbt/sbt/issues/2270
  // by reimplementing packageTask to only run Package if the jar doesn't exist
  // http://www.scala-sbt.org/0.13/docs/Tasks.html#Dynamic+Computations+with
  val dynamicPackageBinTask = Def.taskDyn {
    // WORKAROUND: asking for artifactPath can invoke a recursive packageBin
    //val jar = (artifactPath in Compile in packageBin).value
    val module = projectID.value
    val dir = crossTarget.value
    val scala = scalaBinaryVersion.value
    val jar = dir / s"${module.name}_${scala}-${module.revision}.jar"

    if (jar.exists()) Def.task {
      jar
    } else Def.task {
      val s = streams.value
      s.log.info(s"Rebuilding $jar")
      val config = (packageConfiguration in packageBin in Compile).value
      Package(config, s.cacheDirectory, s.log)
      jar
    }
  }
```

thanks for all your help @eed3si9n this gives me something useful I can optimise this weekend!

A `my_lib/compile` on my project now takes 5 seconds instead of 60 seconds! I'm keen to see what it does to `my_app/compile`...

**Comment by eed3si9n** [comment]
Nice. I'd recommend that you add a sanity flag there like `disableCompileDependencies.value` so you're not caught off guard by that behavior.

**Comment by fommil** [comment]
Yeah, there is quite a lot of utility stuff needed around this to magically support common use cases. But this is the back broken.

**Comment by fommil** [comment]
@eed3si9n FYI https://github.com/fommil/sbt-big-project-tests

**Comment by fommil** [comment]
I'm now pretty convinced that there is a lot that can be done to workaround big project workflows with plugins. Therefore I'm closing this ticket and tracking this independently at https://github.com/fommil/sbt-big-project

Of course, improved performance of sbt for multi-project builds would remove the need for any workaround, so this is certainly not the end of the story.
