### ISSUE TITLE
Allow for graceful termination of the program started by sbt run

### ISSUE THREAD

**Issue by pkolaczk** [sbt/sbt#2274]
Enabling  `cancelable in Global := true` allows to press Ctrl+C and terminate the running program without terminating SBT, however the way how it is handled is quite surprising and doesn't really do what is typically expected from Ctrl+C.

Ctrl+C sends the TERM signal to the application, not KILL. Unfortunately SBT behaves as if it was requested a KILL and interrupts the application. In forked mode, it also seems to kill the JVM very quickly after the application receives the TERM signal. This gives no way for the application to terminate gracefully as it would do when running without SBT supervision.

Hitting Ctrl+C inside of sbt run should pass the TERM signal to the running application and just let the application decide how it handles it. Most of applications know what to do. Maybe, if some users still insist on hard terminating of the process (if it was frozen or doesn't respond to normal TERM), the second Ctrl+C would invoke the current behaviour and interrupt / kill the application.

**Comment by PanAeon** [comment]
Hi,
the one thing why this feature is very hard to implement properly is that process signals are platform dependant. That is you are talking about a POSIX signals which are available in Linux, but not in Windows.
There're some solutions out there to solve this on windows, but this will introduce windows-dependent code into sbt codebase. (IMHO preferable way is to link against a native dll that will call windows API to achieve this). Maybe a sbt plugin will be a more acceptable solution.
Also I tested `cancelable in Global := true` on linux, using `Runtime.getRuntime().addShutdownHook`. When I press Ctrl+C my shutdown hook executes properly, as expected, same as with `kill -15 $pid`. For comparison when I call `kill -9 $pid` nothing gets executed. Also it looks like it is the 'official' way to implement signal handling in java.
But this is not the case on Windows, on windows when you press Ctrl+C the program will most probably terminate without calling the shutdown hook, so it looks like this is Windows-only problem.
~~P.S. - probably we can easily achieve the same effect with `taskkill` on windows.~~

**Comment by qayshp** [comment]
I definitely would love to see this capability.
It looks like there was at least one previous issue (#228) opened (and closed) for this type of feature.

**Comment by axaluss** [comment]
+1

**Comment by SmedbergM** [comment]
+1

**Comment by pascr** [comment]
+1

**Comment by barambani** [comment]
+1

**Comment by otto-dev** [comment]
I sometimes use `sbt` to quickly test some cluster based code. I start the app using sbt, the app joins a development cluster, I hit `ctrl-c`... and bam, the whole cluster is in an inconsistent state, because my program under development didn't have time to say goodbye first.

**Comment by Rasie1** [comment]
+1, very inconvenient to grab ports inside sbt because of this thing

**Comment by eatkins** [comment]
This can't really be done in a platform independent way for the forked jvm. For in process `run` we can interrupt the main thread and the application will have an opportunity to recover and clean up after itself.

**Comment by Rasie1** [comment]
I just put `fork in Global := true` to my build.sbt and now it works as expected. I can Ctrl+C my running process and it lets my code handle it. I also have `cancelable in Global := true`
