### ISSUE TITLE
Ctrl-C Should Cancel Current Task

### ISSUE THREAD

**Issue by djspiewak** [sbt/sbt#228]
This is something I do at least two or three times a day:
1. Open SBT
2. Start some long-running task (`test` being the most common culprit)
3. Realize part-way through the task that I don't want to run it at all
4. Hit Ctrl-C
5. _facepalm_ as SBT exits

Ctrl-C should be captured and defined to cancel the currently-running task, or `exit` if no task is running.

**Comment by okapies** [comment]
related issue?
https://github.com/harrah/xsbt/issues/219

**Comment by djspiewak** [comment]
Not really.  I want a generic way of killing _any_ task.  That's not really related to `console` cleanup.

**Comment by harrah** [comment]
You win the prize.  You get to encourage frameworks, libraries, etc... to respond properly to an InterruptedException on their main thread.

**Comment by djspiewak** [comment]
> You win the prize. You get to encourage frameworks, libraries, etc... to respond properly to an InterruptedException on their main thread.

Sweet!  That's not actually so onerous, in fact.  The only two things I really want to be interuptable are the compiler and Specs2.  I would imagine the compiler is already doing this right, and Eric is _extremely_ responsive with respect to specs.  A start is really all we needed; thanks for the impl!

**Comment by harrah** [comment]
A basic test with the compiler indicated otherwise, but perhaps it was too much of a toy example.  Nevertheless, you have the support of paulp where you need it.  Also, there will be more extensive documentation on the many pitfalls of this, but at least read the short notes in the commit.

**Comment by etorreborre** [comment]
Mark, Daniel,

I don't have a recent build of sbt at hand. Did you try to see how specs2 was reacting to a ctrl-C?

What is it you think I should take care of? Making sure that the ExecutorService I'm using is always shutdown in a finally clause?

Thanks.

**Comment by harrah** [comment]
I have not tested specs2, no.  I expect a finally clause will work if you are waiting for submitted futures to complete, but I don't know the details of the future implementation specs2 uses.

**Comment by etorreborre** [comment]
Ok, what I have now should work then. I'll try it out when 0.11.1 is out.

**Comment by SethTisue** [comment]
I filed a feature request for ScalaTest to support this: https://github.com/scalatest/scalatest/issues/97

**Comment by efuquen** [comment]
So, I'm confused because in my daily use this doesn't seemed to have fixed the issue.  I'm using the latest sbt version, 0.13.1, and I've tried Ctrl-C on many different tasks: compile, run, test (I understand this might be a scalatest from the above comment), running the sbt-native-packager.  Anytime I press Ctrl-C it will exit sbt entirely; in what exact context is this suppose to work because I haven't seen it successfully exit a task without bringing down sbt?

**Comment by jsuereth** [comment]
So, I think the issue is that handling ctl-c safely is only one step of the proces.  Knowing how to cancel arbitrary code appears not to be a solved issue.

My plan:
1. Ensure ctl-c works when tasks fork their proces.
2. Encourage users who want ctl-c to always work to use forked tests/runs
3. Do our best to make sure we work with common test frameworks which aren't forked.

**Comment by SethTisue** [comment]
re #3, over at the ScalaTest issue Bill says “I think mainly this is an sbt enhancement request”

**Comment by darthdeus** [comment]
+1

**Comment by axaluss** [comment]
+1

**Comment by hraban** [comment]
+1

**Comment by ritschwumm** [comment]
i don't think you can cancel "arbitrary code" in a sane way. what you can do is provide a "please die asap" flag and rely on peer pressure to make people react to it.

**Comment by hraban** [comment]
@ritschwumm any particular reason why not? I'm trying to come up with one other REPL that doesn't do this but I'm drawing a blank. For a REPL to evaluate running tasks in a separate thread from the UI (and interrupt / signal handling) code doesn't seem like that much of a stretch, tbh.

Or am I missing something?

EDIT --- I see now this is about the sbt cli in general, not just the console task. My bad. But it looks like this is under way for sbt itself, too, right?

**Comment by SethTisue** [comment]
@hraban see http://stackoverflow.com/questions/16504140/thread-stop-deprecated

**Comment by hraban** [comment]
_gasp_ I'm shocked. I see what you meant, now, @ritschwumm.

**Comment by DavidPerezIngeniero** [comment]
+1

**Comment by YA2O** [comment]
+1...

**Comment by kazuar** [comment]
+1

**Comment by DavidPerezIngeniero** [comment]
There is this useful setting:

```
cancelable in Global := true
```

Normally, it can cancel the running task, when set to `true`.

**Comment by vn971** [comment]
@DavidPerezIngeniero doesn't work with compilation though. _Very_ sad, this one.

**Comment by eed3si9n** [comment]
@vn971 Have you tried the latest 2.12? - https://github.com/scala/scala/pull/6479

**Comment by vn971** [comment]
@eed3si9n Thanks for the answer.
I'm not sure, there's also a weird specifics of my environment that I don't want to get into here, so best just to disregard this comment for now.

**Comment by vn971** [comment]
Thanks for the answer regardless...
