### ISSUE TITLE
build/sbt gem-idea  spark 1.5.2

### ISSUE THREAD

**Issue by xiaoge56** [sbt/sbt#2289]
when I cd spark1.5.2 home，
run sbt/sbt gen－idea

the info show  Server access Error

Server access Error: Connection refused url=http://maven.twttr.com/org/apache/hadoop/hadoop-yarn-server/2.2.0/hadoop-yarn-server-2.2.0.jar

and I can not find hadoop-yarn-server-2.2.0.jar on Internet，
this confuse me the whole afternoon

I have no idea to deal with it
does the pom file or some other file has mistake？

java version "1.7.0_79"
cala code runner version 2.11.7
MacOS 10.11.1
 plz

**Comment by reverocean** [comment]
I think this is a bug of SBT. The hadoop-yar-server is a parent project and it is only a pom. SBT resolve hadoop-yarn-server as a jar rather than a pom When SBT to resolving dependencies.

**Comment by xiaoge56** [comment]
I use mvn to built the project instead,and get done.
