### ISSUE TITLE
No error indication with forked test run

### ISSUE THREAD

**Issue by avdv** [sbt/sbt#2292]
I'm using SBT 0.13.9 and specs2.

In our project a single specification suddenly started to fail with a spurious failure:

```
info] SearchSpec
[error] Error: Total 7, Failed 0, Errors 1, Passed 6
[error] Error during tests:
[error]     SearchSpec
[error] (search/test:testOnly) sbt.TestsFailedException: Tests unsuccessful
```

As you can see, there is no message and no exception printed. It just died silently.

On investigation, it was apparent that the spec would only run successfully when there where 10 or less examples in it. :suspect: 

Luckily, when running under jdb and with `fork in Test := false` I was able to produce a stacktrace:

```
[info] SearchSpec
[trace] Stack trace suppressed: run last search/test:testOnly for the full output.
[error] java.io.FileNotFoundException: /src/project/search/target/streams/test/test/$global/streams/succeeded_tests (Too many open files)
Could not create file /src/project/search/target/streams/compile/$global/$global/discoveredMainClasses/datajava.io.IOException: Too many open files
```

After increasing the file descriptor limit, the tests ran successfully again.

Is it possible to abort with a meaningful exception (when forking a new JVM for the tests) in this case?

Could this be related to #2256?

[originally reported as etorreborre/specs2#435]

**Comment by SethTisue** [comment]
this is now so old (sbt 0.13.x) I think maybe we should just close it. it could be reopened if someone comes along and says they're able to reproduce it in sbt 1
