### ISSUE TITLE
Allow to remove Ivy entirely

### ISSUE THREAD

**Issue by alexarchambault** [sbt/sbt#2294]
My [coursier](https://github.com/alexarchambault/coursier) project is an inch away (ok, maybe two :-) from having a SBT plugin able to provide an `UpdateReport`, as a replacement for the default `update` command provider.

To ensure the default Ivy plugin doesn't override the `update` command after the coursier SBT plugin, the latter will have to actually _require_ the former, although it aims at just replacing it!

Would it be straightforward / would there be a way, to get an SBT launcher able to use something else than Ivy to resolve dependencies from the ground up (including those resolved when SBT itself starts)? Totally free of Ivy.

This point was briefly evoked in https://github.com/sbt/sbt/issues/2266 too, but with no clear answer there.

**Comment by jsuereth** [comment]
For sbt/launcher to migrate teh key would be the ability for coursier to MINIMIZE via proguard into the desired 1MB launcher jar.  If that can happen cool.

If not, don't worry about the launcher.  You could leave that for just resolving sbt and sbt itself could use something idfferent, as long as coursier is using an alternative caching location and doesnt' corrupt the sbt-launcher.

**Comment by alexarchambault** [comment]
@jsuereth The launcher of coursier is now ~8 kB (it's basically a bootstrap Java program, downloading the real JARs of coursier, then launching them). No need of proguard I think ;-)

About resolving SBT, I guess I just need to add some basic support for Ivy repositories (not necessarily configurations à la Ivy instead of Maven scopes I think), and then loosely mimicking conscript with https://github.com/sbt/sbt/blob/1.0.x/src/main/conscript/sbt/launchconfig should allow to launch SBT itself.

That said, the thing that worries me (and pushed me to open this ticket) is that the Ivy plugin (the one that provides the default implementation of `update`) seems to be enabled no matter what. Am I right on this point? Or is there a way to disable it?

**Comment by eed3si9n** [comment]
I think a good intermediate goal to shoot for in sbt 1.0 would be getting to Ivy-abstraction in https://github.com/sbt/librarymanagement so things like `ModuleID` are Ivy-free, and make sure that backend is completely swappable. The `IvyPlugin` can be renamed to something more generic sounding, but I think `update` task will stay.

**Comment by eed3si9n** [comment]
Closing this since we now have lm API.
