### ISSUE TITLE
Link isn't working

### ISSUE THREAD

**Issue by dkotrada** [sbt/sbt#2298]
http://www.scala-sbt.org/0.13/tutorial/Hello.html

on that page.
this link:  Scala REPL
leads to Not Found

**Comment by dwijnand** [comment]
I think it might have been a glitch in Typesafe/EPFL's infrastructure as it's linking nicely now. Thanks for taking the time to open the issue though.

**Comment by eed3si9n** [comment]
@dwijnand The link [Scala REPL](http://www.scala-lang.org/node/2097?_ga=1.27665662.356407433.1395040523) is broken for me. If I remove `?_ga=1.27665662.356407433.1395040523` (I am guessing is inserted by Google Analytics) the link redirects fine to http://www.scala-lang.org/old/node/2097.

**Comment by dwijnand** [comment]
I must have some Chrome extension tearing that out for me. My bad.
