### ISSUE TITLE
sbt in interactive mode hangs in git for windows bash

### ISSUE THREAD

**Issue by TLmaK0** [sbt/sbt#2299]
## Steps
- Download a windows git version from https://git-scm.com/download/win .
- During install check `Use mintty (the default terminal of MSys2)`.
- Run `git-bash.exe`
- Run `sbt`
- Type `tasks` and press enter
## Problems
- Console hangs, and only can exit with Ctrl+C
## Expectations
- Console should return sbt tasks

**Comment by TLmaK0** [comment]
Moved to sbt-launcher-package https://github.com/sbt/sbt-launcher-package/issues/95

**Comment by wsargent** [comment]
There is a fix merged, but for ease of use:

https://github.com/sbt/sbt-launcher-package/pull/96/commits/92a06fc5da81ce05a28ee1239e3a99752e067218

```
 case "$os" in
 CYGWIN*) return 0 ;;
 MINGW*) return 0 ;;
 *)  return 1 ;;
esac
```
