### ISSUE TITLE
.sbt.cache.lock is hard coded to user's home directory

### ISSUE THREAD

**Issue by marcsaegesser** [sbt/sbt#230]
In IvyCache.scala:

```
def lockFile = new File(System.getProperty("user.home"), ".sbt.cache.lock")
```

There is no way to override the location of the .sbt.cache.lock file.  This makes it difficult to use sbt within an automated build environment that runs as a user with no home directory.

**Comment by harrah** [comment]
Should default to Ivy home as of https://github.com/harrah/xsbt/commit/dcea4f2293793e7ead07d6743a8f912b405d0a3c

That commit will be in 0.11.1.  The line you reference now looks like:

https://github.com/harrah/xsbt/blob/0.11/ivy/IvyCache.scala#L33
