### ISSUE TITLE
Illegal dynamic reference

### ISSUE THREAD

**Issue by joan38** [sbt/sbt#2305]
Hi,

```
jniPath := {
    val subProjectPath = projectDependencies.value map (module => (jniPath in LocalProject(module.name)).value)

    val path = libraryDependencies.value flatMap (_.name)

    path ++ subProjectPath mkString File.pathSeparator
  }
```

Does anyone have a workaround? It seems that the issue is coming from the `(jniPath in LocalProject(module.name)).value` but I can't see any way to do so is this a limitation of SBT?

Cheers

**Comment by eed3si9n** [comment]
The sbt issue tracker is not a support system. Please see [how can I get help?](http://www.scala-sbt.org/community.html#how-can-I-get-help)

**Comment by joan38** [comment]
@eed3si9n I was asking a similar question as here: https://github.com/sbt/sbt/issues/2267

But fair enough, I created this:
http://stackoverflow.com/questions/34162484/illegal-dynamic-reference-module
