### ISSUE TITLE
Missing 'Date' entry in APT Release file

### ISSUE THREAD

**Issue by paolieri** [sbt/sbt#2308]
The release file `https://dl.bintray.com/sbt/debian/Release` is missing a '`Date`' field. The result of "`apt-get update`" (on Debian sid, using apt-get 1.1.4) is

```
W: Failed to fetch https://dl.bintray.com/sbt/debian/Release  Voce "Date" nel file Release /var/lib/apt/lists/dl.bintray.com_sbt_debian_Release non valida
```

The same issue was resolved in https://github.com/rethinkdb/rethinkdb/issues/5174 by simply adding a Date field to the Release file:
`Date: $(date -R)`

**Comment by eed3si9n** [comment]
Thanks for the report.

**Comment by mljsimone** [comment]
Temporal solution to install sbt:

```
wget https://dl.bintray.com/sbt/debian/sbt-0.13.9.deb && dpkg -i sbt-0.13.9.deb
```

**Comment by eed3si9n** [comment]
I think the metadata file is generated by Bintray. I am contacting their support, but I might not be able to fix it myself.

**Comment by eed3si9n** [comment]
Bintray support person got back to me:

> We wanted to update you that we have modified the Debian index calculation to include the 'Date' field and thus resolve the issue for the future Apt versions. Please note that in order for the new indexing to take affect you will need to trigger the Debian indexing mechanism. This can be done in three ways; uploading a deb package, deleting a deb package, or manually triggering the metadata calculation.

Following the API documentation, here's what I did:

```
$ curl --user username:key --data '' https://bintray.com/api/v1/calc_metadata/sbt/debian
{"message":"Calculation was successfully scheduled for '/sbt/debian'"}%
$ curl -L https://bintray.com/artifact/download/sbt/debian/Release
Origin: Bintray
Label: Bintray
Suite:
Codename:
Date: Mon, 11 Jan 2016 18:44:37 UTC
Component:
Architecture:
MD5Sum:
 3e78ae7411117800f40a1688cbf6d190             4331 Packages
 d59136d8459ebc18f3d57293d249b6c5             1026 Packages.bz2
 40f09a4d54aca47e7991db9a2978e017              796 Packages.gz
SHA1:
 a8191ccae22d118e46fd14757514ff072ed81684             4331 Packages
 50fcb73a48a1dde9f845e16d89fce3829f713b51             1026 Packages.bz2
 7f4ba3956b91d9d6563cc320034d9e40b500feb2              796 Packages.gz
```
