### ISSUE TITLE
ScalaTest dependency not downloaded?

### ISSUE THREAD

**Issue by mslinn** [sbt/sbt#231]
$ cat project/build.sbt
version := "0.1"

scalaVersion := "2.9.1"

resolvers += Classpaths.typesafeResolver

resolvers += "sbt-idea-repo" at "http://mpeltonen.github.com/maven/"

libraryDependencies += "org.scalatest" %% "scalatest" % "1.6.1" % "test"

addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "0.11.0")

addSbtPlugin("com.typesafe.startscript" % "xsbt-start-script-plugin" % "0.3.0")

addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse" % "1.4.0")

$ sbt update test
[info] Loading project definition from E:\work\experiments\scala\helloblueeyes\project
[info] Updating {file:/E:/work/experiments/scala/helloblueeyes/project/}default-3b8c51...
[info] Done updating.
[info] Set current project to helloblueeyes (in build file:/E:/work/experiments/scala/helloblueeyes/)
[success] Total time: 0 s, completed Oct 18, 2011 12:15:08 PM
[info] Compiling 1 Scala source to E:\work\experiments\scala\helloblueeyes\target\scala-2.9.1\test-classes...
[error] E:\work\experiments\scala\helloblueeyes\src\test\scala\StackSpec.scala:1: object scalatest is not a member of package org
[error] import org.scalatest.FlatSpec
[error]            ^
[error] E:\work\experiments\scala\helloblueeyes\src\test\scala\StackSpec.scala:2: object scalatest is not a member of package org
[error] import org.scalatest.matchers.ShouldMatchers
[error]            ^
[error] E:\work\experiments\scala\helloblueeyes\src\test\scala\StackSpec.scala:8: value should is not a member of java.lang.String
[error]   "A Stack" should "pop values in last-in-first-out order" in {
[error]             ^
[error] E:\work\experiments\scala\helloblueeyes\src\test\scala\StackSpec.scala:16: not found: value it
[error]   it should "throw EmptyStackException if an empty stack is popped" in {
[error]   ^
[error] four errors found
[error] {file:/E:/work/experiments/scala/helloblueeyes/}default-40d9ce/test:compile: Compilation failed
[error] Total time: 1 s, completed Oct 18, 2011 12:15:09 PM

**Comment by harrah** [comment]
Please use the mailing list for support.  Thanks!
