### ISSUE TITLE
Adding a method to a class forces dependent (by inheritance) files to recompile

### ISSUE THREAD

**Issue by gkossakowski** [sbt/sbt#2320]
`A.scala`

``` scala
class A {
  //def foo: Int = 153
}

class A2
```

`B.scala`

``` scala
class B extends A2
```
1. `compile`
2. Uncomment line in `A.scala`
3. `compile`. Both sources are recompiled because we have dependency introduced by inheritance between `B.scala` and `A.scala`. Name hashing is disabled for dependencies introduced by inheritance and incremental compiler track dependencies at source level so it cannot determine that change happened to `A` that `B` doesn't inherit from.

**Comment by jvican** [comment]
Let's close this ticket since https://github.com/eed3si9n/sbt/commit/9a0c400c29c000a892fc45b7267eac5dbc6d889b fixes it.

**Comment by dwijnand** [comment]
eed3si9n@9a0c400 isn't merged into any stable branch (sbt/sbt#0.13 or sbt/zinc#1.0) so this isn't fixed.

**Comment by jvican** [comment]
Class-based dependencies +name hashing solves this issue. This was fixed [in this PR](https://github.com/sbt/zinc/issues/86) and #1104 mentions that it's fixed in the issue description.

**Comment by dwijnand** [comment]
Cool!
