### ISSUE TITLE
ivyPaths in globalSettings for a plugin

### ISSUE THREAD

**Issue by joan38** [sbt/sbt#2330]
Hi,

``` scala
object BlaBlaPlugin extends AutoPlugin {

  object autoImport {
    lazy val blabla = settingKey[Unit]("")
  }
  import autoImport._

  override lazy val globalSettings = Seq(
    blabla := println(ivyPaths.value.ivyHome.get.getPath)
  )
}
```

```
[error] Reference to undefined setting:
[error]
[error]   */*:ivyPaths from */*:blabla ((BlaBlaPlugin) BlaBlaPlugin.scala:11)
```

Isn't ivyPaths defined at a Global scope?
I can access it in `.sbt/global.sbt` but not in the globalSettings of a plugin.

Merry christmas

**Comment by eed3si9n** [comment]
The sbt issue tracker is not a support system. Please see [how can I get help?](http://www.scala-sbt.org/community.html#how-can-I-get-help)

**Comment by joan38** [comment]
I am not looking for support but reporting bug.
As you wrote [here](http://stackoverflow.com/a/34523591/599728) could you reopen this ticket?

Cheers
