### ISSUE TITLE
Option to resolve from Ivy cache when offline

### ISSUE THREAD

**Issue by stummb** [sbt/sbt#2331]
A problem with the offline mode is that once you do a "clean", dependencies need to be resolved again and without a local proxy, you need to be online for that. Having an option to resolve from the local ivy _cache_ would remedy this case, and one could really work offline even if some dependencies need to be resolved. There is already a slightly cumbersome way to do it here: http://stackoverflow.com/questions/24395307/working-offline-with-sbt-and-snapshot-dependencies/. Another option would be to put this information explicitly in the appropriate section of the sbt documentation to prevent people from wasting a lot of time trying to figure it out themselves.

**Comment by jvican** [comment]
This can be closed now. Will be ready in 1.0. Some changes need to be done in sbt/sbt, but the most important changes are already merged in sbt/librarymanagement.

**Comment by eed3si9n** [comment]
Closing this.

@jvican Could you send a release note PR a la https://github.com/sbt/sbt/blob/1.0.x/notes/1.0.0/sample.md?

**Comment by jvican** [comment]
Sure, I will as soon as I implement the small remaining changes in sbt/sbt.
