### ISSUE TITLE
Potential performance issue related to transactional ClassfileManager

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2333]
- REF 925ec98900cb7d8af4a6d4dc5656f035c2c9bff3
- https://github.com/sbt/sbt/blob/v0.13.9/compile/inc/src/main/scala/sbt/inc/ClassfileManager.scala

By default sbt will first relocate the `*.class` files that are about to be invalidated into a temporary directory before a round of incremental compilation. When the compilation results to failure, it restores the `*.class` files back from the refuge.
## potential problems

This could result to thousands of `*.class` file moving from one directory to another. On some filesystems this could be slow specially if the temporary directory is created on `C:\` but the code is located on non-`C:\`.

I think I've seen someone report that sbt creates a few temporary directory and deletes them every second. I am wondering if it's related to `~compile` and transactional combined causing that.

**Comment by dwijnand** [comment]
Do you mean #2185?

**Comment by eed3si9n** [comment]
@dwijnand :hamburger:

**Comment by eed3si9n** [comment]
Closing this as duplicate.
