### ISSUE TITLE
scripted filter

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#2334]
it would be good to be able to run just one scripted test. I have two in my project: simple and complex. Simple is designed for a fast turnaround, whereas complex is designed for regression testing. Current workaround is to just temporarily delete complex (and get it back from git after).

**Comment by Duhemm** [comment]
You can already run a single scripted test by using `scripted foo/bar`. Doesn't that work?

**Comment by fommil** [comment]
ah, I was trying `scripted bar`. Ok, silly me.
