### ISSUE TITLE
Provide a Setting that points to the (eventual) config:packageBin

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#2348]
Currently the `packageBin` task is the only way to get hold of the jar output from a project/config. (actually `(artifactPath in Compile in packageBin).value` would be enough but it amounts to the same).

However, it is often useful to know where the file is going to be without necessarily invoking the compilation (e.g. projects that are compiler plugins and need to be referenced by IDEs, caching strategies).

Proposed implementation:

```
  val packageBinFile = SettingKey[File](
    "packageBinFile",
    "The (eventual) location of the packageBin."
  )

  def packageBinFileSetting = Def.setting {
    val append = configuration.value match {
      case Compile => ""
      case Test    => "-tests"
      case _       => "-" + configuration.value.name
    }
    crossTarget.value / s"${projectID.value.name}_${scalaBinaryVersion.value}-${projectID.value.revision}$append.jar"
  }
```

**Comment by eed3si9n** [comment]
It's `artifactPath in packageBin`.

**Comment by fommil** [comment]
I don't think you read the ticket in enough detail, that forces many ivy Tasks to run, all the way down (resulting in hundreds of IO heavy tasks) which is very slow on windows.

**Comment by fommil** [comment]
(BTW configuration is needed too)

**Comment by fommil** [comment]
I should really from a tasktimings trace of the current approach to show what is being triggered.

**Comment by eed3si9n** [comment]
Using sbt-big-project-test on Windows XP, `compile:packageBin::artifactPath` returns immediately for me even after issuing `clean` first.

**Comment by fommil** [comment]
Its possible I was getting crosstalk from other tasks or settings. Did you do a TaskTimings to trace that?

**Comment by eed3si9n** [comment]
> Did you do a TaskTimings to trace that?

I did it anyway, but I didn't have to because `artifactPath` is a `settingKey`, which by design does not invoke the task engine.

What you might see in the task timing if you run sbt from the shell is the compilation of the build i.e. `project/ClusterFsckBuild.scala` itself, not the processing of `compile:packageBin::artifactPath`.

**Comment by fommil** [comment]
OK, cool, I'll confirm this tonight and close the ticket if that's the case. And remove my workaround.
