### ISSUE TITLE
Macro usage fails clean compile, but works with incremental compilation

### ISSUE THREAD

**Issue by khernyo** [sbt/sbt#2360]
Code can be found at: https://github.com/khernyo/sbt-clean-compile-failure-of-macro-usage

Compilation of the project results in an error, but it can be successfully compiled by the following steps:
1. remove the problematic line (`println(...)` in Main.scala)
2. compile the project
3. reinsert the problematic line
4. compile the project

Running the project produces the expected output, so the generated classfiles seem to be correct.

After cleaning the project, we are back to square one: the code does not compile.

This is quite frustrating because everything seems to work during development, but e.g. on a build server it will fail to compile.

**Comment by eed3si9n** [comment]
I can't reproduce this issue using sbt 1.2.6 and Scala 2.11.12:

### build.sbt

```scala
ThisBuild / scalaVersion := "2.11.12"

lazy val test = (project in file("."))
  .settings(
    libraryDependencies ++= Seq("com.github.alexarchambault" %% "argonaut-shapeless_6.1" % "0.3.1")
  )
```
