### ISSUE TITLE
Global plugin properties need fully qualified name (not document, not POLA)

### ISSUE THREAD

**Issue by fanf** [sbt/sbt#2364]
I'm using global sbt configuration, for example for eclipse. As each member of our team uses whatever the best editor for her, it absolutly impossible to put sbteclipse configuration in projets config file. And in all case, that's not the place they belong to. 

So I tried to set-up the plugin configuration as explain in http://www.scala-sbt.org/0.13/docs/Global-Settings.html which does NOT works. 
The work around is to use fully qualified name for properties. For example, for the sbteclipse "withSource" properties, one has to use: "com.typesafe.sbteclipse.core.EclipsePlugin.EclipseKeys.withSource"

This must AT LEAST be documented, but it should just be corrected. I see it as a bug, because: 
- it is not POLA at all (so much not POLA that the people having documented how to set up global properties didn't thought it was necessary to use fully qualified names); 
- no plugin ever documents the fully qualified names of properties, so the user must find it by itself - not exaclty the best user experience.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/website/pull/213
