### ISSUE TITLE
SBT run issue

### ISSUE THREAD

**Issue by mshafieluru** [sbt/sbt#2365]
Hi

I am basically behind a firewall and proxy settings are well configured. My maven works fine with java projects. i am using sbt 0.13.9.2 and scala 2.11.7. I am using JDK 8 and cacerts is available in the correct folder.

here is the error i am getting in a hello project suggested on sbt documentation site

```
D:\scalaworkspace\hello>sbt
Getting org.scala-sbt sbt 0.13.9 ...

:: problems summary ::
:::: WARNINGS
                module not found: org.scala-sbt#sbt;0.13.9

        ==== local: tried

          C:\Users\M1035362\.ivy2\local\org.scala-sbt\sbt\0.13.9\ivys\ivy.xml

          -- artifact org.scala-sbt#sbt;0.13.9!sbt.jar:

          C:\Users\M1035362\.ivy2\local\org.scala-sbt\sbt\0.13.9\jars\sbt.jar

        ==== jcenter: tried

          https://jcenter.bintray.com/org/scala-sbt/sbt/0.13.9/sbt-0.13.9.pom

          -- artifact org.scala-sbt#sbt;0.13.9!sbt.jar:

          https://jcenter.bintray.com/org/scala-sbt/sbt/0.13.9/sbt-0.13.9.jar

        ==== typesafe-ivy-releases: tried

          https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.9/ivys/ivy.xml

        ==== Maven Central: tried

          https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.9/sbt-0.13.9.pom

          -- artifact org.scala-sbt#sbt;0.13.9!sbt.jar:

          https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.9/sbt-0.13.9.jar

                ::::::::::::::::::::::::::::::::::::::::::::::

                ::          UNRESOLVED DEPENDENCIES         ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: org.scala-sbt#sbt;0.13.9: not found

                ::::::::::::::::::::::::::::::::::::::::::::::


:::: ERRORS
        Server access Error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderExcepti
on: unable to find valid certification path to requested target url=https://jcenter.bintray.com/org/scala-sbt/sbt/0.13.9/sbt-0.13.9.pom

        Server access Error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderExcepti
on: unable to find valid certification path to requested target url=https://jcenter.bintray.com/org/scala-sbt/sbt/0.13.9/sbt-0.13.9.jar

        Server access Error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderExcepti
on: unable to find valid certification path to requested target url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.9/ivys/ivy.xml

        Server access Error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderExcepti
on: unable to find valid certification path to requested target url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.9/sbt-0.13.9.pom

        Server access Error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderExcepti
on: unable to find valid certification path to requested target url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.9/sbt-0.13.9.jar


:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
unresolved dependency: org.scala-sbt#sbt;0.13.9: not found
Error during sbt execution: Error retrieving required libraries
  (see C:\Users\M1035362\.sbt\boot\update.log for complete log)
Error: Could not retrieve sbt 0.13.9

D:\scalaworkspace\hello>
```

This is very irritating. however, the same code works on machine which is not behind firewall.

**Comment by mshafieluru** [comment]
i have http_proxy, https_proxy set.

**Comment by SethTisue** [comment]
have you consulted e.g. http://stackoverflow.com/questions/13626965/how-to-ignore-pkix-path-building-failed-sun-security-provider-certpath-suncertp? offhand, the problem you are having doesn't appear to be SBT-specific

**Comment by eed3si9n** [comment]
I agree. This should move to StackOverflow to get community support - http://www.scala-sbt.org/community.html#how-can-I-get-help

**Comment by lespea** [comment]
I had this same issue. Your proxy is most likely mitm-ing the ssl connections and java isn't trusting that cert as being valid (since it technically isn't).  While you can set an env var to bypass that check (I think) the better approach is to add your company's root cert to the java cert store.  I'd give you the command I use but I don't have access to it atm; will update when I can if you can't figure it out.

Also be warned that if you use like intellij or something that bundles their own version of java you need to add the root cert to those stores as well.

**Comment by mshafieluru** [comment]
Thanks

**Comment by abdulhaju** [comment]
> I had this same issue. Your proxy is most likely mitm-ing the ssl connections and java isn't trusting that cert as being valid (since it technically isn't).  While you can set an env var to bypass that check (I think) the better approach is to add your company's root cert to the java cert store.  I'd give you the command I use but I don't have access to it atm; will update when I can if you can't figure it out.
> Also be warned that if you use like intellij or something that bundles their own version of java you need to add the root cert to those stores as well.

Hi,
Thanks, looks like good answer, but can you tell me how to add the root cert to the stores as I am using IBM Jdk 8.
