### ISSUE TITLE
Failure to build 0.13.9 release with 0.13.8

### ISSUE THREAD

**Issue by frediz** [sbt/sbt#2368]
Hi,
I downloaded 0.13.9 source tarball from github : https://github.com/sbt/sbt/archive/v0.13.9.tar.gz and tried to build it with sbt 0.13.8 from the web site : https://dl.bintray.com/sbt/native-packages/sbt/0.13.8/sbt-0.13.8.tgz .
But from those official tarballs, I'm unable to build sbt : 

```
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  * com.typesafe.sbt:sbt-site:0.6.2 -> 0.7.1
[warn] Run 'evicted' to see detailed eviction warnings
java.lang.RuntimeException: Setting value cannot be null: {file:/build/sbt/sbt-0.13.9/}/*:gitCurrentBranch
    at scala.sys.package$.error(package.scala:27)
    at sbt.EvaluateSettings$INode.setValue(INode.scala:143)
    at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
    at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
    at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
    at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
    at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
[error] Setting value cannot be null: {file:/build/sbt/sbt-0.13.9/}/*:gitCurrentBranch
```

strace-ing the process it seems to be related to sbt-git looking for info in .git .
As the tarball is a release, .git is not present.
I stumble on this issue in sbt-git.
https://github.com/sbt/sbt-git/issues/36
Not sure if it was related to my problem. I wanted to force a dependency on sbt-git 0.7.1 (but I don't know the best way) so I changed : 
scala_2.10/sbt_0.13/com.typesafe.sbt/sbt-ghpages/ivy-0.5.1.xml and
scala_2.10/sbt_0.13/com.typesafe.sbt/sbt-ghpages/ivy-0.5.1.xml.original
especially : 

```
<dependency org="com.typesafe.sbt" name="sbt-git" rev="0.7.1" conf="compile->default(compile)" e:scalaVersion="2.10" e:sbtVersion="0.13"/>
```

I tried this on top of build.sbt but it didn't seem to help : 

```
libraryDependencies += "com.typesafe.sbt" % "sbt-git" % "0.7.1" force()
```

but modifying the xml file, I got the following log : 

```
[info] Resolving com.typesafe.sbt#sbt-git;0.7.1 ...
[warn]  module not found: com.typesafe.sbt#sbt-git;0.7.1
[warn] ==== local: tried
[warn]   /build/sbt/sbt-0.13.9/debian/sbt_home/.ivy2/local/com.typesafe.sbt/sbt-git/0.7.1/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-git/0.7.1/sbt-git-0.7.1.pom
[warn] ==== bintray-typesafe-ivy-releases: tried
[warn]   https://dl.bintray.com/typesafe/ivy-releases/com/typesafe/sbt/sbt-git/0.7.1/sbt-git-0.7.1.pom
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-git/0.7.1/ivys/ivy.xml
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-git/0.7.1/ivys/ivy.xml
[warn] ==== sonatype-snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/sbt/sbt-git/0.7.1/sbt-git-0.7.1.pom
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt.sxr/sxr_2.10/0.3.0/jars/sxr_2.10.jar ...
[info]  [SUCCESSFUL ] org.scala-sbt.sxr#sxr_2.10;0.3.0!sxr_2.10.jar (4277ms)
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.10.2/scala-library-2.10.2.jar ...
[info]  [SUCCESSFUL ] org.scala-lang#scala-library;2.10.2!scala-library.jar (6003ms)
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.typesafe.sbt#sbt-git;0.7.1: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]      com.typesafe.sbt:sbt-git:0.7.1 (/build/sbt/sbt-0.13.9/build.sbt#L10-11)
[warn]        +- org.scala-sbt:sbtroot:0.13.9
sbt.ResolveException: unresolved dependency: com.typesafe.sbt#sbt-git;0.7.1: not found
```

So, is it really a know problem of sbt-git ? what to do about it ? How come sbt-git 0.7.1 is not found ?
Thanks,
F.

**Comment by dwijnand** [comment]
Hi @frediz,

The problem isn't sbt-git, it's because the release source tarball isn't a git repository, which is a problem because you can't even launch sbt in the project then.

The source tarballs aren't often they way in which users get sbt releases, but this bug definitely limits their usefulness.

As a workaround, provided you have or can install git, you can initialise a repository in `sbt-0.13.9` (move inside the `sbt-0.13.9` directory and run `git init`) and it then it loads and the version is still set to `0.13.9`.

Thanks for the report.

**Comment by frediz** [comment]
Do you mean sbt can only work in a git tree project then ? So I can't use it for a release tarball of any other project or with any other project using a different vcs ?
Anyway, the git workaround worked :) thanks!

**Comment by dwijnand** [comment]
Not exactly, I mean that sbt's release tarball (and any other sbt project that uses sbt-git and doesn't pay attention to what that means for the release tarball, like sbt 0.13.9 doesn't) can't be really used until you apply the git workaround.

**Comment by frediz** [comment]
oh right, I forgot about sbt-git!

**Comment by eed3si9n** [comment]
This would be a good use for [Build Level](https://github.com/sbt/sbt/wiki/User-Stories:-Build-Level), which is just an idea at this point.

Maybe sbt-git should provide some mechanism to fall back to some `String` if `.git` is not there.

/cc @jsuereth

**Comment by eed3si9n** [comment]
Maybe we just need to bump up the sbt-git version number.
