### ISSUE TITLE
`sbt run` and `sbt ~run` have differing behavior

### ISSUE THREAD

**Issue by danielyli** [sbt/sbt#2369]
# Problem

The output differs when running the following program using `sbt run` and `sbt ~run`:

```
import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.Future

object Main {
  def main(args: Array[String]): Unit = {
    Future().onSuccess { case _ =>
      Thread.sleep(1000)  // this is purely to delay execution of the following message
      println("This message prints when this program is run with `sbt ~run`,")
      println("but not when run with `sbt run`.")
    }
  }
}
```
# Steps to Reproduce
1.  Copy the code above into a new file (e.g. `Main.scala`) in an empty directory.
2.  Execute `sbt run` in that directory; you should see no output.
3.  Now execute `sbt ~run`, wait for it to finish executing once, then `touch Main.scala` to force sbt to rerun the program.
4.  You should see output.
5.  You'll see output in subsequent reruns as well.
# Expectation

`sbt ~run` should behave like `sbt run` by not executing the `onSuccess` callback after program termination.
# Discussion

My best guess is that when using `sbt ~run`, sbt reuses the global execution context's thread pool across executions, and therefore the callback in the code above is allowed to finish executing.

**Comment by eed3si9n** [comment]
Hello from 2019.

This was fixed in sbt 1.3.2 I think, specifically https://github.com/sbt/sbt/pull/5081

```
$ sbt
sbt:gh-2369> run
[info] Compiling 1 Scala source to /private/tmp/gh-2369/target/scala-2.12/classes ...
[warn] there was one deprecation warning (since 2.11.0)
[warn] there was one deprecation warning (since 2.12.0)
[warn] there were two deprecation warnings in total; re-run with -deprecation for details
[warn] three warnings found
[info] running Main
[success] Total time: 3 s, completed Oct 1, 2019 8:37:25 PM
sbt:gh-2369> This message prints when this program is run with `sbt ~run`,
but not when run with `sbt run`.

sbt:gh-2369> ~run
[info] running Main
[success] Total time: 0 s, completed Oct 1, 2019 8:37:35 PM
[info] 1. Monitoring source files for gh-2369/run...
[info]    Press <enter> to interrupt or '?' for more options.
This message prints when this program is run with `sbt ~run`,
but not when run with `sbt run`.
sbt:gh-2369> :q
[info] shutting down sbt server
```

So using sbt 1.3.2 the message is printed for both `run` and `~run`.
