### ISSUE TITLE
nightlies not publishing ivy style launcher

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#2370]
A couple of things with the nightlies:

Firstly, I had to add this to my `project/plugins.sbt`, but it would be really nice if this was added automatically (just for nightlies! obviously not for release versions). If not automatically added, it should be added to the docs at http://www.scala-sbt.org/0.13/docs/Nightly-Builds.html

``` scala
resolvers += Resolver.url("sbt-nightlies", url("https://dl.bintray.com/sbt/ivy-snapshots"))(Resolver.ivyStylePatterns)
```

(@dwijnand tells me we can use `Resolver.bintrayIvyRepo("sbt", "ivy-snapshots")` now)

I'm also adding this to the build definition (also be good if it was automated), but even then, an `update` fails when trying to resolve `sbt-launch`. It tries to resolve this

```
https://dl.bintray.com/sbt/ivy-snapshots/org.scala-sbt/sbt-launch/0.13.10-20160115-062758/ivys/ivy.xml
```

but the contents of https://dl.bintray.com/sbt/ivy-snapshots/org.scala-sbt/sbt-launch/0.13.10-20160115-062758/ is just a single `sbt-launch.jar`.

This can all be reproduced by trying to use the `scripted` plugin with a nightly, e.g. use `0.13.10-20160115-062758` for https://github.com/fommil/sbt-big-project

**Comment by dwijnand** [comment]
Thanks for opening and filling out the report.

**Comment by fommil** [comment]
Well with the two performance fixes recently I'd be insane not to be using them! :smile:

**Comment by eed3si9n** [comment]
See #2338 Include sbt-ivy-snapshots to launchconfig.
We should update the doc too.

`sbt-launch.jar` is a launcher app intended for human consumption. Why are you depending on them?

**Comment by fommil** [comment]
I'm not, it seems to be pulled in transitively by scripted.
