### ISSUE TITLE
Decide what Scala version to support in 1.x

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#2389]
I might be being forgetful but what Scala version(s) do we want to support in 1.0.x?

Currently all sbt modules and sbt/sbt support 2.10 and 2.11, although sbt/sbt is only published in 2.10.

Don't we want to drop 2.10 support in 1.0.x?

**Comment by dwijnand** [comment]
The answer is Scala 2.11.

**Comment by eed3si9n** [comment]
See http://www.scala-sbt.org/0.13/docs/Coding-Guideline.html

**Comment by dwijnand** [comment]
Perhaps we should open this again following the thoughts in #2388.

**Comment by eed3si9n** [comment]
Yea..

**Comment by darkfrog26** [comment]
With sbt-server would it be possible to support multiple Scala versions simultaneously and have them encapsulated in their own JVM instance or in a separate classloader?  It would allow support for all the latest versions of Scala without compromising older plugins.

**Comment by eed3si9n** [comment]
We might have to keep 2.11 for Zinc if IDEs need it, but sbt/sbt should be able to migrate to Scala 2.12 including the plugin space.

**Comment by xuwei-k** [comment]
Will Scala 2.11.9 or later support Java 9? if not, I vote sbt 1.x should support Scala 2.12.x because we can't use Java 9 with sbt 1.x

**Comment by eed3si9n** [comment]
sbt 1.x will target Scala 2.12.x. We'll update the coding guideline.

**Comment by dwijnand** [comment]
Done, given https://github.com/sbt/website/pull/324 from @raboof (Thank you!).
