### ISSUE TITLE
Maven resolver syntax does not work as documented

### ISSUE THREAD

**Issue by greenrd** [sbt/sbt#2400]
This does not work

```
Resolver.url("my-test-repo", url("https://example.org/repo-releases/"))
```

This does

```
"my-test-repo" at "https://example.org/repo-releases/"
```

Both are documented to work, so both should work.

**Comment by eed3si9n** [comment]
I'm guessing you're referring to the doc here http://www.scala-sbt.org/0.13/docs/Resolvers.html:

> ## URL
> 
> Define a URL repository at "https://example.org/repo-releases/".
> 
> ```
> resolvers += Resolver.url("my-test-repo", url("https://example.org/repo-releases/"))
> ```
> 
> To specify an Ivy repository, use:
> 
> ```
> resolvers += Resolver.url("my-test-repo", url)(Resolver.ivyStylePatterns)
> ```
> 
> or customize the layout pattern described in the Custom Layout section below.

It's totally plausible that `at` has diverged from `Resolver.url`.

**Comment by dwijnand** [comment]
Resolver.url: https://github.com/sbt/sbt/blob/v0.13.9/ivy/src/main/scala/sbt/Resolver.scala#L295
vs
String#at: https://github.com/sbt/sbt/blob/v0.13.9/ivy/src/main/scala/sbt/impl/DependencyBuilders.scala#L64-L68

**Comment by eed3si9n** [comment]
Fixed the doc https://www.scala-sbt.org/1.x/docs/Resolvers.html#Maven+resolvers
