### ISSUE TITLE
Problem with resource loading on multi project builds

### ISSUE THREAD

**Issue by PapaCharlie** [sbt/sbt#2404]
Suppose the following project structure:

```
.
├── build.sbt
├── core
│   └── src
│       └── main
│           └── scala
│               └── Main.scala
└── plugin
    └── src
        └── main
            └── scala
                └── Foo.scala
```

build.sbt:

```
name := "bar"

lazy val plugin =
  (project in file("plugin"))

lazy val core =
  (project in file("core"))
    .aggregate(plugin).dependsOn(plugin)

lazy val bar =
  (project in file("."))
    .aggregate(core).dependsOn(core)

mainClass in (Compile, run) := Some("bar.core.Main")
```

Main.scala:

```
package bar.core

import bar.plugin.Foo

object Main extends App {

  println(getClass.getResource("/"))
  println(Foo.rootDir)

}
```

Foo.scala:

```
package bar.plugin

object Foo {

  val rootDir = Foo.getClass.getResource("/")

}
```

In this case, calling `sbt run` prints:

```
file:${PROJECT_HOME}/core/target/scala-2.10/classes/
file:${PROJECT_HOME}/core/target/scala-2.10/classes/
```

Shouldn't the expected behavior be the following?

```
file:${PROJECT_HOME}/core/target/scala-2.10/classes/
file:${PROJECT_HOME}/plugin/target/scala-2.10/classes/
```

Otherwise, code in individual projects cannot load resources defined in their own `resources` folders.

As far as I can tell, it seems that classes will only look in the classpath of the project in which the main class is located, regardless of the actual project they are contained in. This is a problem because this causes behavior that is different to how the code behaves when it is packaged and all resources are copied to a single directory.

**Comment by PapaCharlie** [comment]
As is turns out, as long as the file/directory is referenced by name directly, the resource is resolved correctly. On the other hand, said directory cannot be "/", otherwise it will point to the classpath directory that contains the Main class. Below is the modified project that shows this behavior:

```
.
├── build.sbt
├── core
│   └── src
│       └── main
│           └── scala
│               └── Main.scala
├── plugin
│   └── src
│       └── main
│           ├── resources
│           │   └── foo.conf
│           └── scala
│               └── Foo.scala
└── project
    └── build.properties
```

Main.scala:

```
package bar.core

import bar.plugin.Foo

object Main extends App {

  println(getClass.getResource("/"))
  println(Foo.rootDir)
  println(Foo.confFile)

}
```

Foo.scala:

```
package bar.plugin

object Foo {

  val rootDir = Foo.getClass.getResource("/")
  val confFile = Foo.getClass.getResource("/foo.conf")

}
```

This new project prints the following when calling `sbt run`:

```
file:${PROJECT_HOME}/core/target/scala-2.10/classes/
file:${PROJECT_HOME}/core/target/scala-2.10/classes/
file:${PROJECT_HOME}/plugin/target/scala-2.10/classes/foo.conf
```

Just something to look out for when some projects need to have access to whole directories, not just files.

**Comment by dwijnand** [comment]
Nice one.
