### ISSUE TITLE
Merge sbt-doge into sbt for 1.0.0

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#2408]
As it stands sbt (currently version 0.13.9) doesn't support variant `crossScalaVersions` across sub-projects, which is why @eed3si9n created [sbt-doge](https://github.com/sbt/sbt-doge).

This support is so useful that sbt/sbt itself actually uses it for its own build: https://github.com/sbt/sbt/blob/v0.13.9/project/p.sbt#L18

I think it's proven to be useful and working, so I think we should merge it in (the functionality, not git merge).

**Comment by eed3si9n** [comment]
I don't see why not

**Comment by dwijnand** [comment]
Thanks @eed3si9n, changed the ticket into an enhancement.

**Comment by dwijnand** [comment]
Done in #2613, thanks to @jroper

**Comment by jroper** [comment]
Ha, I didn't even realise there was an open issue for this!
