### ISSUE TITLE
[0.13.10] Source compatibility breakage due to ambiguous imports

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2415]
Ref #2399

@fommil wrote in https://gitter.im/sbt/sbt?at=56a3c957586242210adf1d87

> is anybody seeing this with 0.13.10-RC1?
> 
> ``` scala
>  /home/fommil/.sbt/0.13/global.sbt:8: error: reference to useGpgAgent is ambiguous;
> it is imported twice in the same scope by
> import com.typesafe.sbt.pgp.PgpKeys._
> and import _root_.com.typesafe.sbt.SbtPgp.autoImport._
> useGpgAgent := true
> ```
> 
> is there now an implicit dependency on the pgp plugin?

Us importing `autoImport._` might be breaking source compatibility.

"not doing a wildcard import" is apparently a workaround, but this is a sticky situation because global settings are used across all 0.13 builds. Maybe we need to hide this feature behind a flag?

 /cc @timcharper

**Comment by dwijnand** [comment]
A global feature flag is (I think) a first.

Would moving the notes for #2399 up in the notes under "Fixes with compatibility implications" (with additional information) not suffice?

**Comment by eed3si9n** [comment]
I don't know how often people read "Fixes with compatibility implications", but if we keep it, we probaby need a migration section to explain what's going on.

`sys.props.get("sbt.repository.secure")` might be another example where we changed the runtime behavior. Not being able to even start the build is pretty bad. When you have dozens of projects, and when only a few of them are using 0.13.10, one would be confused why they need to keep changing the global setting.

**Comment by dwijnand** [comment]
:+1: for a migration section, as well as exploring better ways to communicate these kind of things (though I have no ideas right now).

Given that we handle .sbt files compilation ourselves (somewhat), do you think we might be able to capture and communicate "reference to XXX is ambiguous" types of errors and explain there? The explanation would include how to write cross-0.13 version global configuration.

**Comment by timcharper** [comment]
I see the problem; People were working around the issue before, but now they no longer need to.

I think the appropriate thing to do is to catch the flag and show an explanation. Is there already a flag to turn off auto-imports? What does the cross-0.13 version global configuration look like?

**Comment by eed3si9n** [comment]
I really don't want to break source compatibility from the previous version. Novice users are going to be super confused. This needs be an opt-in feature.

The cross-0.13 version would directly import

``` scala
import com.typesafe.sbt.pgp.PgpKeys.{ fooKey, barKey }
```
