### ISSUE TITLE
Undeprecate DefinableTask.task

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#2417]
```
    @deprecated("No longer needed with new task syntax and SettingKey inheriting from Initialize.", "0.13.2")
    def task: SettingKey[Task[S]] = scopedSetting(scope, key)
```

means that it is not possible to use the no-macro version of the API.

I want to use the no-macro version because
1. I find the macros to be extremely confusing and misleading (they obfuscate what is actually happening)
2. neither scala interactive compiler nor IntelliJ understand the macros, so there is no editor support for the macro syntax

**Comment by fommil** [comment]
workaround

``` scala
  implicit class NoMacroTaskSupport[T](val t: TaskKey[T]) extends AnyVal {
    def theTask: SettingKey[Task[T]] = Scoped.scopedSetting(t.scope, t.key)
  }
```

**Comment by fommil** [comment]
and also providing a mechanism for defining macro-less `InputTask`s as an advanced (undocumented) developer feature.

@eed3si9n you said you'd consider this for 1.0

**Comment by fommil** [comment]
similar thing for `InputTask`, e.g. I can't do this anymore

``` scala
  def compileOnlyTask: Def.Initialize[InputTask[Unit]] = InputTask(
    (s: State) => Def.spaceDelimited()
  ) { (argTask: TaskKey[Seq[String]]) =>
  ... // my stuff
  }
```

**Comment by dwijnand** [comment]
fixed in https://github.com/sbt/sbt/commit/a90832b5935340425088a84a4fed96f35c4f4dac#diff-d26b07d0122948faf43bd080f3bdd501R327, it'll be in 1.2.0.
