### ISSUE TITLE
Better control over memory usage

### ISSUE THREAD

**Issue by jroper** [sbt/sbt#2426]
If I want to change the `MaxMetaspaceSize` used by sbt to be 1GB on every invocation, currently, I have two options:
1. Configure all memory options using the `-mem` flag - so if I want 1GB of metaspace, I have to give 4GB of heap to my process, because that's the way `-mem` works.  This is not an option, I want 1GB of metaspace, but 4GB of heap space is far too much.
2. Configure the `JAVA_OPTS` environment variable so that _every_ java process (or at least, every java process that uses the very well supported `JAVA_OPTS` environment variable) on my system gets 1GB of metaspace too.  This is also not an option.

Setting `-J-XX:MaxMetaspaceSize` in my `sbtopts` file doesn't work because when the `-mem` processing checks to see whether it should set the memory options, it only checks `JAVA_OPTS`.  An ideal solution would be for it to check both `JAVA_OPTS` and the `-J` arguments.

**Comment by DavidPerezIngeniero** [comment]
You can call directly `java -jar -Xmx1G sbt-launch.jar`, or write your own custom script.
This is what I do.

**Comment by jroper** [comment]
Of course, I can do that too, but my use case is for a framework (similar to Play) that is likely to have thousands of users, and it will require increasing the metaspace for sbt - making thousands of users write their own script is not a solution.

**Comment by DavidPerezIngeniero** [comment]
I have in my version control `sbt-launcher.jar` and a one-line custom script, that can be shared by all the developers.  In this way, there is no need to have SBT installed.

I provide one script for MacOSX & Linux and other for Windows.  It is a simple solution and it works.

**Comment by eed3si9n** [comment]
> Setting -J-XX:MaxMetaspaceSize in my sbtopts file doesn't work because when the -mem processing checks to see whether it should set the memory options, it only checks JAVA_OPTS. An ideal solution would be for it to check both JAVA_OPTS and the -J arguments.

We should fix this before 0.13.10 comes out.

**Comment by eed3si9n** [comment]
Moving this to https://github.com/sbt/sbt-launcher-package/issues/104

**Comment by eed3si9n** [comment]
https://github.com/sbt/sbt-launcher-package/pull/105
