### ISSUE TITLE
Range-versioned dependencies are not correctly found in the local cache.

### ISSUE THREAD

**Issue by nuttycom** [sbt/sbt#244]
If a transitive dependency of one of my project dependencies has a version that is specified as a range, the correct version is not found in the local cache when offline:

[info] Updating {file:/Users/nuttycom/reportgrid/services/}analytics...
[warn]  module not found: org.xsocket#xSocket;[2.8.13, 2.9)
[warn] ==== local: tried
[warn]   /Users/nuttycom/.ivy2/local/org.xsocket/xSocket/[revision]/ivys/ivy.xml
[warn]   -- artifact org.xsocket#xSocket;[2.8.13, 2.9)!xSocket.jar:
[warn]   /Users/nuttycom/.ivy2/local/org.xsocket/xSocket/[revision]/jars/xSocket.jar
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/org/xsocket/xSocket/[revision]/xSocket-[revision].pom
[warn]   -- artifact org.xsocket#xSocket;[2.8.13, 2.9)!xSocket.jar:
[warn]   http://repo1.maven.org/maven2/org/xsocket/xSocket/[revision]/xSocket-[revision].jar
[warn] ==== Scala-Tools Maven2 Repository: tried
[warn]   http://scala-tools.org/repo-releases/org/xsocket/xSocket/[revision]/xSocket-[revision].pom
[warn]   -- artifact org.xsocket#xSocket;[2.8.13, 2.9)!xSocket.jar:
[warn]   http://scala-tools.org/repo-releases/org/xsocket/xSocket/[revision]/xSocket-[revision].jar
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.xsocket#xSocket;[2.8.13, 2.9): not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[error] {file:/Users/nuttycom/reportgrid/services/}analytics/_:update: sbt.ResolveException: unresolved dependency: org.xsocket#xSocket;[2.8.13, 2.9): not found
[error] {file:/Users/nuttycom/reportgrid/services/}common/_:update: sbt.ResolveException: unresolved dependency: org.xsocket#xSocket;[2.8.13, 2.9): not found
[error] Total time: 123 s, completed Oct 26, 2011 9:19:19 AM

This keeps me from building, even though a valid version is available locally:

nuttycom@yggdrasil services (master)]$ ll ~/.ivy2/cache/org.xsocket/xSocket/
total 56
-rw-r--r--  1 nuttycom  staff   3978 Jan  9  2011 ivy-2.8.15.xml
-rw-r--r--  1 nuttycom  staff  15975 Jan  9  2011 ivy-2.8.15.xml.original
-rw-r--r--  1 nuttycom  staff    681 Oct 26 09:47 ivydata-2.8.15.properties
-rw-r--r--  1 nuttycom  staff    143 Oct 26 09:47 ivydata-[2.8.13, 2.9).properties
drwxr-xr-x  3 nuttycom  staff    102 Oct  3 14:09 jars
[nuttycom@yggdrasil services (master)]$ ll ~/.ivy2/cache/org.xsocket/xSocket/jars/
total 696
-rw-r--r--  1 nuttycom  staff  355123 Jan  9  2011 xSocket-2.8.15.jar

When back online, the dependency is found and allows the build to proceed.

**Comment by harrah** [comment]
This specific problem is probably already handled by 'offline', but i need to look at making snapshot and offline handling better by default.  So, I'll merge this into #290 and address them together.
