### ISSUE TITLE
allow monkey patching the compiler

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#2444]
It would be useful to be able to deploy quick fixes against `scala-compiler` by putting 100% ABI-compatible classes ahead of the `scala-compiler` jars. This is an approach that has proven successful in ENSIME as suggested in SI-9632

**Comment by eed3si9n** [comment]
Note to someone trying to implement this: https://github.com/sbt/sbt/blob/0.13/compile/src/main/scala/sbt/compiler/AnalyzingCompiler.scala

**Comment by fommil** [comment]
when creating a `ScalaInstance` it would appear that monkey jars would need to make it into the `extraJars` field.

**Comment by fommil** [comment]
the smoking gun... https://github.com/sbt/sbt/blob/v0.13.12/main/src/main/scala/sbt/Defaults.scala#L400

**Comment by fommil** [comment]
damn, `def jars` in `ScalaInstance` is returning `extraJars` at the end... but they need to be in front for monkeys :cry:

**Comment by fommil** [comment]
@eed3si9n watch out for an `sbt` plugin over the next week or so on this :wink:

There might be a few things you could do in `Defaults.scala` to clean up my implementation.
