### ISSUE TITLE
source changes not tracked in non-aggregated subproject

### ISSUE THREAD

**Issue by aryairani** [sbt/sbt#2446]
It looks like source changes aren't tracked propertly in a subproject in a multiproject build, if the subproject isn't an aggregate of the root.

I have 

``` scala
lazy val root = project.in(file("."))
lazy val foo = project
```

With the root project selected, I can compile `foo` with the command `foo/compile` or `~foo/compile`.  However, if foo's sources change while `~foo/compile` is "Waiting for source changes", it doesn't trigger a recompile.  Pressing enter to interrupt, and using the `~foo/compile` command again does compile once, on account of the previous change, but again further changes do not trigger a recompile.

If I use `; project foo; ~compile` instead, changes are detected, and recompiles are triggered as expected.  I wouldn't expect `~foo/compile` and `; project foo; ~compile` to behave differently.

`~foo/compile` works as expected if root `.aggregate(foo)`.

Affects at least 0.13.8 and 0.13.9

**Comment by eed3si9n** [comment]
I personally think `~` is working as expected since `~` command doesn't know what it's about to execute. For example, we can use it with sbt-doge as follows:

```
~ so bar/compile
```

`~` won't know what sbt-doge's `so` command would take action on `bar` subproject. I think this is more of a documentation than anything. As you wrote, if aggregation works, then I think that's what we have to live with.

**Comment by dwijnand** [comment]
See also related https://github.com/sbt/website/issues/150

**Comment by dwijnand** [comment]
> I wouldn't expect ~foo/compile and ; project foo; ~compile to behave differently.

I agree (as I did back in 2015: https://gitter.im/sbt/sbt?at=5563d8961d3343c66cf02dd5)

(More generally I think `currentProject` should be removed from sbt, if possible)

When you run `~<anything>` it just executes `<anything>`, so ideally that would return some information on how to determine when to execute `<anything>` again.

**Comment by eed3si9n** [comment]
This was one of the main feature of sbt 1.3.0's watch rewrite by @eatkins (https://github.com/sbt/sbt/pull/4512?).
`~foo/compile` now works as expected without aggregation from the current subproject.
