### ISSUE TITLE
glassfish-jar should be added to JarPackagings

### ISSUE THREAD

**Issue by gshegosh** [sbt/sbt#2449]
https://github.com/sbt/sbt/blob/3e5449f02d082c1326da7e6319d70d5b26b84bfd/sbt-maven-resolver/src/main/scala/sbt/mavenint/MavenRepositoryResolver.scala#L46 should be modified to include "glassfish-jar".

libraryDependencies ++= Seq(
(...)
    "org.glassfish.main.appclient" % "gf-client-module" % "4.0",
(...)

results in SBT trying to download files with .glassfish-jar extension instead of .jar one:

[info] downloading http://artifactory.pisystems.pl/artifactory/proxy/org/glassfish/main/appclient/gf-client-module/4.0/gf-client-module-4.0.jar ...
[info]  [SUCCESSFUL ] org.glassfish.main.appclient#gf-client-module;4.0!gf-client-module.jar (1295ms)
[warn]  [FAILED     ] org.glassfish.main.common#common-util;4.0!common-util.glassfish-jar:  (0ms)
[warn] ==== local: tried
[warn]   /home/gk/.ivy2/local/org.glassfish.main.common/common-util/4.0/glassfish-jars/common-util.glassfish-jar
[warn] ==== pi-artifactory: tried
[warn]   http://artifactory.pisystems.pl/artifactory/proxy/org/glassfish/main/common/common-util/4.0/common-util-4.0.glassfish-jar
[warn]  [FAILED     ] org.glassfish.main.ejb#ejb-full-container;4.0!ejb-full-container.glassfish-jar:  (0ms)

**Comment by eed3si9n** [comment]
I think it's fine if ppl had to customize via classpathTypes setting.
