### ISSUE TITLE
Issue with a test Dependency scope when it includes a classifier

### ISSUE THREAD

**Issue by imsdu** [sbt/sbt#2451]
Hello,

I have not been able to see the issue so I am posting this here.
With the 0.13.9, when I create a first project with the following dependencies:

``` scala
libraryDependencies ++= Seq(
  "org.apache.hadoop" % "hadoop-common" % "2.6.0",
  "org.apache.hadoop" % "hadoop-common" % "2.6.0" % "test" classifier "tests",
  "org.scalatest" %% "scalatest" % "2.2.1" % "test"
)
```

It produces the following ivy file:

``` xml
...
<dependencies>
   <dependency org="org.scala-lang" name="scala-library" rev="2.11.7" conf="compile>default(compile)"/>
   <dependency org="org.apache.hadoop" name="hadoop-common" rev="2.6.0" conf="compile>default(compile);test->default(compile)">
    <artifact name="hadoop-common" type="jar" ext="jar" conf="compile"/>
    <artifact name="hadoop-common" type="jar" ext="jar" conf="*" e:classifier="tests"/>
   </dependency>
  <dependency org="org.scalatest" name="scalatest_2.11" rev="2.2.1" conf="test>default(compile)"/>
</dependencies>
```

And if I look at the fullClasspath key, it doesn't include the hadoop-common-tests. Good.

But if I add my first project as a dependency of a second one, then hadoop-common-tests appears in fullClasspath and pollutes the assembly of my applications.

``` shell
> show fullClasspath
[info] List(Attributed(.../scala-2.11/classes), 
Attributed(.../.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.7.jar), 
Attributed(.../com.test/first-project_2.11/0.1-SNAPSHOT/jars/classifier_2.11.jar), Attributed(.../org.apache.hadoop/hadoop-common/jars/hadoop-common-2.6.0.jar), Attributed(.../org.apache.hadoop/hadoop-common/jars/hadoop-common-2.6.0-tests.jar), ...)
```

**Comment by eed3si9n** [comment]
```
   <dependency org="org.apache.hadoop" name="hadoop-common" rev="2.6.0" conf="compile>default(compile);test->default(compile)">
    <artifact name="hadoop-common" type="jar" ext="jar" conf="compile"/>
    <artifact name="hadoop-common" type="jar" ext="jar" conf="*" e:classifier="tests"/>
   </dependency>
```

This doesn't look right. sbt needs to merge two of your `ModuleID`s and it seems to be losing the test configuration. Here's a workaround I've come up with:

``` scala
lazy val root = (project in file(".")).
  settings(
    inThisBuild(Seq(
      scalaVersion := "2.11.7",
      organization := "com.example",
      version := "0.1.0-SNAPSHOT",
      publishMavenStyle := false
    )),
    name := "foo-2451",
    libraryDependencies += "org.apache.hadoop" % "hadoop-common" % "2.6.0" artifacts(
      Artifact("hadoop-common", "jar", "jar", classifier = None, configurations = List(Compile), url = None),
      Artifact("hadoop-common", "jar", "jar", classifier = Some("tests"), configurations = List(Test), url = None)
    )
  )
```

**Comment by imsdu** [comment]
Thanks for the quick answer and the workaround, the fullClasspath key doesn't include the test library anymore.

**Comment by eed3si9n** [comment]
Ref #2002

**Comment by edmondop** [comment]
The workaround doesn't work anymore in 0.13.16

**Comment by cchepelov** [comment]
I am hitting the same issue (hi @simondumas 😉) in 1.1.6, and the workaround also no longer works.

**Comment by cchepelov** [comment]
It seems the ~~bug~~ issue with the workaround no longer working is coursier-related! 

Testing now on sbt-1.1.6 and coursier 1.0.3 or 1.1.0-M4; having updated the workaround to read:

```scala
libraryDependencies += "org.apache.hadoop" % "hadoop-common" % "2.6.0" artifacts(
    Artifact("hadoop-common", `type` = "jar", extension = "jar", classifier = None, configurations = Vector(conf),
            url = None, extraAttributes = Map[String, String](), checksum = None),
          Artifact("hadoop-common", `type` = "jar", extension = "jar", classifier = Some("tests"), configurations = Vector(testConfig),
            url = None, extraAttributes = Map[String, String](), checksum = None)
    )
```

Apparently, sometime around up to sbt-0.13.16, coursier (1.0.3 & 1.1.0-M4) no longer understands when an explicit Artifact is destined only to certain configurations and not others.

The culprit seems to be here: https://github.com/coursier/coursier/blob/master/sbt-shared/src/main/scala/coursier/FromSbt.scala#L80 

Will try to filter explicitArtifacts for the proper configuration and submit a patch there.

(in the mean time, I'll use the dirtier workaround, which is to deal with debris at Assembly time)

**Comment by cchepelov** [comment]
having disabled Coursier, the same misbehaviour happens including with improper injection of (in this example) hadoop-common's test artifact within (non-test) dependents' runtime or assembly classpath, and the workaround doesn't seem to have any effect.

**Comment by cchepelov** [comment]
I think we can close this now; when running with SBT 1.1.6 and without Courier, without the workaround,

```scala
libraryDependencies += Seq(
   "org.apache.hadoop" % "hadoop-common" % "2.6.0",
   "org.apache.hadoop" % "hadoop-common" % "2.6.0" % "test" classifier "tests"
)
```

does the right thing. It still misbehaves with Courier on, but this doesn't seem to me to be a SBT problem any longer.

**Comment by eed3si9n** [comment]
Thanks for the comment. I am closing this for now.

**Comment by danielkza** [comment]
@cchepelov Did you ever manage to get the issue fixed in Coursier? Is there any know workaround that does not require removing it?

**Comment by cchepelov** [comment]
Turns out some of the artifacts were built with sbt 1.1.3 to 1.1.5, and 
rebuilding them with sbt 1.1.6 cured the Test/non-Test pollution in 
dependents issue.

**Comment by jaceklaskowski** [comment]
I ran into it today when tried to use the following dependency with `classifier` and the latest coursier. I had to disable coursier.

```
resolvers +=
  "splicemachine-public" at "http://repository.splicemachine.com/nexus/content/groups/public"
libraryDependencies += "com.splicemachine" % "splice_spark" % "latest.version" classifier "mapr6.1.0"
```
