### ISSUE TITLE
SBT incompatible with --srcpath: ClassCastException: xsbt.API$ApiPhase cannot be cast to scala.tools.nsc.Global$GlobalPhase

### ISSUE THREAD

**Issue by retronym** [sbt/sbt#2452]
The `--sourcepath` setting is needed when compiling the Scala standard library. However, when using this in SBT, and recompiling a subset of files in the library, we can run into a CCE.

Here's a [demonstration project](https://github.com/retronym/sbt-sourcepath-bug).

```
% sbt clean compile
[info] Loading global plugins from /Users/jason/.sbt/0.13/plugins
[info] Loading project definition from /Users/jason/code/sbt-sourcepath-bug/project
[info] Set current project to sbt-sourcepath-bug (in build file:/Users/jason/code/sbt-sourcepath-bug/)
[success] Total time: 0 s, completed 10/02/2016 10:32:45 PM
[info] Updating {file:/Users/jason/code/sbt-sourcepath-bug/}sbt-sourcepath-bug...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Compiling 1 Scala source to /Users/jason/code/sbt-sourcepath-bug/target/scala-2.11/classes...
java.lang.ClassCastException: xsbt.API$ApiPhase cannot be cast to scala.tools.nsc.Global$GlobalPhase
    at scala.tools.nsc.Global$Run$$anonfun$compileLate$2$$anonfun$apply$1.apply(Global.scala:1609)
    at scala.tools.nsc.Global$Run$$anonfun$compileLate$2$$anonfun$apply$1.apply(Global.scala:1609)
    at scala.reflect.internal.SymbolTable.enteringPhase(SymbolTable.scala:235)
    at scala.tools.nsc.Global$Run$$anonfun$compileLate$2.apply(Global.scala:1609)
    at scala.tools.nsc.Global$Run$$anonfun$compileLate$2.apply(Global.scala:1608)
    at scala.collection.Iterator$class.foreach(Iterator.scala:742)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
    at scala.tools.nsc.Global$Run.compileLate(Global.scala:1608)
    at scala.tools.nsc.Global$Run.compileLate(Global.scala:1598)
```

/cc @Blaisorblade (who mentioned this before https://groups.google.com/d/msg/scala-internals/-E7Q7DXW-BE/Nw6kRhoTkRgJ) and /cc https://github.com/scoverage/sbt-scoverage/issues/116 (which is the same sort of issue.)

It seems that one should always extends `GlobalPhase`, rather than `Phase` (other than the sentinel phases `NoPhase` and `SomePhase`!)

I am working on a fix in SBT itself here: https://github.com/sbt/sbt/compare/0.13...retronym:topic/sourcepath?expand=1

**Comment by dwijnand** [comment]
(yes! my hopes for scala/scala sbt-usage-driven bug fix contributions is becoming a reality!)

**Comment by Blaisorblade** [comment]
(Thanks for the mention, but turns out that I utterly forgot about all that after almost 3 years. Still, it's nice that soon `zinc` might work there).

Your patch makes sense, but doesn't go far enough.

> It seems that one should always extends GlobalPhase, rather than Phase (other than the sentinel phases NoPhase and SomePhase!)

If that's actually true, unenforced and undocumented, that's a bad smell.
Could one enforce that through sealing? I imagine something like:

``` scala
sealed trait Phase
final class NoPhase extends Phase
final class SomePhase extends Phase
trait GlobalPhase extends Phase //*not* sealed and extensible
```

Without enforcement, the casts that are failing are incorrect and should be fixed, beyond your patch.

**Comment by retronym** [comment]
I don't know the history or intent of the `Phase` hierarchy. It could definitely take some cleanup, though.

I guess part of the issue is that `GlobalPhase#run` needs to be in the compiler cake to get at `currentRun`.

**Comment by retronym** [comment]
https://github.com/sbt/sbt/pull/2453
