### ISSUE TITLE
Cache resolution sporadically fails with the IntegrationTest configuration

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#2459]
I just realised I never submitted this.

We are unable to use the cached resolution in ensime-server as it will randomly (yes, unfortunately it sometimes passes) fail to add shapeless to our integration test phase.

Reproduction (not necessarilly minimal) in https://github.com/ensime/ensime-server/tree/08be528a2e4eb33acd5cc499e416e32189e61919/project and anything before that for about a year. Caching not enabled here https://github.com/ensime/ensime-server/blob/08be528a2e4eb33acd5cc499e416e32189e61919/project/EnsimeBuild.scala#L102

**Comment by dwijnand** [comment]
For clarity, you mean cached resolution here, right?

**Comment by fommil** [comment]
That's right yes

**Comment by dwijnand** [comment]
For the benefit of not introducing confusing alternative vocabulary like "updateCache" and "IntegrationTest phase", I tweaked your title a little.

**Comment by fommil** [comment]
I can't remember how sporadic this was, but it seems to work again. Will reopen if it crops up.
