### ISSUE TITLE
Dependency is not resolved

### ISSUE THREAD

**Issue by mravey** [sbt/sbt#2462]
# steps

have a look at the following repo: https://github.com/matthieu-ravey/sbtbug
basically it has two dependencies which are:

``` scala
"com.google.cloud.bigtable" % "bigtable-hbase-1.1" % "0.2.2",
"org.apache.hbase" % "hbase-client" % "1.1.1"
```

hbase-client has itself a dependency on hbase-common as you can see on http://maven-repository.com/artifact/org.apache.hbase/hbase-client/1.1.1

type `sbt console` and `org.apache.hadoop.hbase.TableName` and you'll get `TableName is not a member of package org.apache.hadoop.hbase` . 
# problem

TableName is defined in hbase-common and should be available as far as I understand.
# expectation

TableName should be defined

**Comment by eed3si9n** [comment]
Here's what happens on sbt 1.3.2:

```
scala> org.apache.hadoop.hbase.TableName
<console>:11: error: object org.apache.hadoop.hbase.TableName is not a value
       org.apache.hadoop.hbase.TableName
                               ^

scala> org.apache.hadoop.hbase.TableName.NAMESPACE_DELIM
res1: Char = :
```
