### ISSUE TITLE
withSources() and withJavadocs() fails in build.sbt

### ISSUE THREAD

**Issue by mslinn** [sbt/sbt#247]
Is the following line properly specified in build.sbt?

libraryDependencies += "org.scalatest" %% "scalatest" % "latest.integration" % "test" withSources() withJavadocs()

I get "error: value withJavadocs is not a member of sbt.ModuleID"

I also tried these, which yield the same error message:

libraryDependencies += "org.scalatest" %% "scalatest" % "latest.integration" withSources() withJavadocs() % "test"

libraryDependencies += "org.scalatest" %% "scalatest" % "latest.integration" withSources() withJavadocs()

**Comment by retronym** [comment]
Please direct questions the the SBT mailing list.

In this case, the method is called `withJavadoc`.

```
> set libraryDependencies += "org.scalatest" %% "scalatest" % "latest.integration" % "test" withSources() withJavadoc()
[info] Reapplying settings...
[info] Set current project to default-f686fe (in build file:/Users/jason/code/scratch/20111030/)
```

BTW, if you're using `sbt-idea` to generated an IntelliJ project, you don't need `withSources` or `withJavadoc`; these are automatically downloaded by that plugin.

**Comment by mslinn** [comment]
Thanks! Also I did not know about the IntelliJ information. I use sbt standalone and with IntelliJ.

After some experimenting, I discovered the syntax for `Seq()`. This might be helpful to add to the docs:

```
libraryDependencies ++= Seq(
  "se.scalablesolutions.akka" % "akka-actor"       % "latest.integration"              withSources(),
  "se.scalablesolutions.akka" % "akka-stm"         % "latest.integration"              withSources(),
  "se.scalablesolutions.akka" % "akka-typed-actor" % "latest.integration"              withSources(),
  "com.reportgrid"           %% "blueeyes"         % "latest.integration"  % "compile" withSources(),
  "org.scalatest"            %% "scalatest"        % "latest.integration"  % "test"    withSources()
)

```

This also works:

```
libraryDependencies += "se.scalablesolutions.akka" % "akka-actor"       % "latest.integration" withSources()

libraryDependencies += "se.scalablesolutions.akka" % "akka-stm"         % "latest.integration" withSources()

libraryDependencies += "se.scalablesolutions.akka" % "akka-typed-actor" % "latest.integration" withSources()

libraryDependencies += "com.reportgrid"           %% "blueeyes"         % "latest.integration" % "compile" withSources()

libraryDependencies += "org.scalatest"            %% "scalatest"        % "latest.integration" % "test" withSources()
```
