### ISSUE TITLE
[0.13.11] wrong sbtVersion

### ISSUE THREAD

**Issue by metc** [sbt/sbt#2473]
A wrong version number is returned.
## steps
1. Downloaded the `sbt` intaller for Windows from here: https://dl.bintray.com/sbt/native-packages/sbt/0.13.11/sbt-0.13.11.msi
2. Run the Windows installer
3. Run the `sbt sbtVersion` command in a console
## problem

The wrong sbt version is returned:

``` sh
$ sbt --version
sbt launcher version 0.13.8
$ sbt sbtVersion
[info] Set current project to bin (in build file:/D:/sbt/bin/)
[info] 0.13.8
```
## expectation

The correct sbt version should be returned (0.13.11).

**Comment by SethTisue** [comment]
is this the return of #2181?

**Comment by eed3si9n** [comment]
It seems that way. I'm not exactly sure why it happens. Maybe windows publishing requires `clean`, and I'm not `clean`ing?

**Comment by eed3si9n** [comment]
Published another Windows installer - https://bintray.com/sbt/native-packages/sbt/0.13.11.2/view#files/sbt/0.13.11.2
The website should be updated soon.

**Comment by metc** [comment]
Thanks @eed3si9n the issue is fixed. Is the msi generator script open-sourced ?

The links on the website are not updated correctly. The current [download page](http://www.scala-sbt.org/download.html) has a broken link to the Windows installer. [All these pages](https://github.com/sbt/sbt.github.com/search?utf8=%E2%9C%93&q=sbt-0.13.11.2.msi) should be updated accordingly.

**Comment by eed3si9n** [comment]
MSI stuff is all here - https://github.com/sbt/sbt-launcher-package
If you can track down the bug in the build or the native packager, that'll be great.

Fixed the website link - https://github.com/sbt/website/commit/ae066a2f1048f2f6f42ac6e20cbc7fcc135da551

**Comment by metc** [comment]
Thanks for your fast support, have a nice day.
