### ISSUE TITLE
Documentation missing for punctuation methods in SettingKey

### ISSUE THREAD

**Issue by mikebridge** [sbt/sbt#2477]
The documentation at http://www.scala-sbt.org/0.13.11/api/index.html#sbt.SettingKey does not contain descriptions for the various obfuscation rockets like `<+=`, `<++=`, `~=` etc.  Even basic methods like `:=` are are missing.

**Comment by DavidPerezIngeniero** [comment]
+1

**Comment by mikebridge** [comment]
This should really read "The API documentation is almost completely absent".  I originally went there to  decode the punctuation that appears everywhere in .sbt files but now I see that almost nothing is documented, even for prior sbt versions.

**Comment by eed3si9n** [comment]
The best source of explanation for sbt 0.12 style operators is sbt 0.12 documentation - https://www.scala-sbt.org/0.12.4/docs/Getting-Started/More-About-Settings.html

Closing this since those are now removed in sbt 1.
