### ISSUE TITLE
New line character "\n" is escaped to "^J" in the sbt console's prompt in 0.13.10

### ISSUE THREAD

**Issue by hohonuuli** [sbt/sbt#2480]
## steps

Add the following to _build.sbt_:

```
// set the prompt (for this build) to include the project id.
shellPrompt in ThisBuild := { state =>
  val user = System.getProperty("user.name")
   "\n" + user + "@" + Project.extract(state).currentRef.project + "\nsbt> "
}
```

In _project\build.properties_ set `sbt.version=0.13.10` (or 0.13.11)

In a terminal, run `sbt`
## problem

In sbt 0.13.10 and 0.13.11, the new line character `\n` in the prompt is being transformed to [emacs caret notation](http://ergoemacs.org/emacs/emacs_line_ending_char.html) `^J`. The resulting prompt looks like:

```
^Jbrian@my-cool-project^Jsbt>
```
## expectation

In all prior versions of sbt the prompt appears like so:

```

brian@my-cool-project
sbt>
```
## notes

If this is a _feature_ some guidance on how to create a prompt with line feeds in it would be much appreciated. My development platform is Mac OS X 10.11.3, java version "1.8.0_72".

**Comment by eed3si9n** [comment]
I think this is a bug caused by JLine bump to 2.13 #2173, which has jline/jline2#205 issue.

**Comment by hohonuuli** [comment]
@eed3si9n Good catch. Bummer. Right now the workaround is to revert to sbt 0.13.9

**Comment by eed3si9n** [comment]
you might be able to force a downgrade of JLine from `project/plugins.sbt` using http://www.scala-sbt.org/0.13/docs/Library-Management.html#Overriding+a+version

**Comment by hohonuuli** [comment]
Thanks for the tip. I tried this first:

```
dependencyOverrides += "jline" % "jline" % "2.11"
```

and then tried this instead:

```
libraryDependencies += "jline" % "jline" % "2.11" force()
```

I tried that in both `project\plugins.sbt` and `build.sbt`. But I still get the funky `^J`.

**Comment by japgolly** [comment]
Not sure if this is the same but since SBT 0.13.11, I'm getting an issue in Linux where after SBT is open for a while, newlines become `^M`s and I have to use ctrl-enter instead.

**Comment by scalway** [comment]
+
