### ISSUE TITLE
sbt compiles forever

### ISSUE THREAD

**Issue by jk-1** [sbt/sbt#2489]
## steps

Extract the attached file into a HibTool2 directory
[HibToolError.tar.gz](https://github.com/sbt/sbt/files/151372/HibToolError.tar.gz)
. Run sbt compile.
## problem

Compile does not end nor does it show any error messages.
## expectation

Compile should show OK or error messages after a while.
## notes

Error happens in file ConfigUtil.scala in line:

```
val conf = read[HibToolConfFile](appConf.toString())
```

If you comment that line out then the compilation goes to end.

**Comment by xuwei-k** [comment]
minimize example 
- https://github.com/xuwei-k/sbt-2489
- https://travis-ci.org/xuwei-k/sbt-2489/builds/112818829

I think this is not sbt bug. upickle bug? /cc @lihaoyi

**Comment by lihaoyi** [comment]
quite plausibly, we've had https://github.com/lihaoyi/upickle-pprint/issues/107 and I'm not sure what version you're using but maybe you're using a version before that fix or maybe there's another related problem we haven't fixed

**Comment by eed3si9n** [comment]
@jk-1's build says:

``` scala
    "com.lihaoyi" %% "upickle" % "0.3.7" withJavadoc(),
```

Minimized repro created by @xuwei-k says 

``` scala
libraryDependencies += "com.lihaoyi" %% "upickle" % "0.3.8"
```

**Comment by lihaoyi** [comment]
Ok well open a uPickle issue and I'll get to it some day

**Comment by eed3si9n** [comment]
I'm going to close this for now then.
