### ISSUE TITLE
Private members included in API hash confuse name hashing

### ISSUE THREAD

**Issue by gkossakowski** [sbt/sbt#2490]
The #2441 made private members of traits to contribute to the API hash but left behavior of name hashing undefined. The current implementation doesn't include private members in name hashes. For example:

``` scala
trait A {
  // uncomment B 
  // private object B
}
```

The overall api hash of `A` will change if you uncomment `B` but the hash of the _name_ `A` will remain the same. This breaks a contract in incremental compiler that says there's always at least one name changed if api has changed (or its hash). Nothing blows up at the moment because that contract hasn't been enforced but it's enough to add

``` scala
assert(modifiedNames.regularNames.nonEmpty || modifiedNames.implicitNames.nonEmpty,
    s"Modified names for $modified0 is empty")
```

to the `sbt.inc.NamesChange` and run `trait-private-object` scripted test to see:

```
[info] java.lang.AssertionError: assertion failed: Modified names for A is empty
[info]  at scala.Predef$.assert(Predef.scala:179)
[info]  at sbt.inc.NamesChange.<init>(Changes.scala:30)
[info]  at sbt.inc.IncrementalNameHashing.sameAPI(IncrementalNameHashing.scala:33)
[info]  at sbt.inc.IncrementalCommon.sameClass(IncrementalCommon.scala:146)
[info]  at sbt.inc.IncrementalCommon$$anonfun$6.apply(IncrementalCommon.scala:129)
[info]  at sbt.inc.IncrementalCommon$$anonfun$6.apply(IncrementalCommon.scala:129)
```

I've run into this problem while debugging class-based dependency branch.

The unenforced contract can be seen here:
https://github.com/sbt/sbt/blob/0.13/compile/inc/src/main/scala/sbt/inc/IncrementalNameHashing.scala#L23

``` scala
  override protected def sameAPI[T](src: T, a: Source, b: Source): Option[APIChange[T]] = {
    if (SameAPI(a, b))
      None
    else {
      val aNameHashes = a._internalOnly_nameHashes
      val bNameHashes = b._internalOnly_nameHashes
      val modifiedNames = ModifiedNames.compareTwoNameHashes(aNameHashes, bNameHashes)
      val apiChange = NamesChange(src, modifiedNames)
      Some(apiChange)
    }
  }
```

The code assumes that if the api is not the same it's because some names has changed.

**Comment by gkossakowski** [comment]
@Duhemm, I think the best way to fix this problem is to introduce a new type of API change `TraitPrivateMembersModified` and have a separate hash for private members to catch this is indeed the change you're looking at when invalidating dependencies.

Having a separate type of the API change makes sense because you want only to invalidate dependencies by inheritance from traits. The member ref dependencies shouldn't be invalidated. At the moment they're not because the set of changed names is empty so member reference invalidation becomes a dummy operation.

**Comment by gkossakowski** [comment]
To unblock my test of class-based dependency tracking, I'll revert hashing of private members for now.

**Comment by jvican** [comment]
Related https://github.com/pantsbuild/pants/issues/4185.

**Comment by dwijnand** [comment]
@jvican is this in your list of SC zinc issues? I don't see it under https://github.com/sbt/zinc/issues/212, but i see this issue under the 1.0.0 milestone, so I think it should be, maybe?

**Comment by dwijnand** [comment]
@jvican Ping again. Is this on your radar? Is there a ticket (or tickets) for this sbt/zinc side? Is this fixed or worth fixing for zinc 1.0?

**Comment by jvican** [comment]
It is super important. It's one of the first things in my Zinc list. You can close it, there's a related ticket in sbt/zinc.

**Comment by dwijnand** [comment]
I don't want to close it until/unless we can provide a forward link in sbt/zinc. Just for paper-trail reasons.

**Comment by jvican** [comment]
There's such a forward link, have a look 6 comments before this one.

**Comment by dwijnand** [comment]
For clarity: https://github.com/sbt/zinc/issues/118 apparently
