### ISSUE TITLE
classloaders leaking memory and file locks through JarFiles

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#2496]
# steps

scripted test running on Windows (e.g. appveyor)

`build.sbt`

```
libraryDependencies += "com.novocode" % "junit-interface" % "0.11" % "test"
ivyLoggingLevel := UpdateLogging.Quiet
exportJars := true
fork := true
```

`test`

```
# this test is only relevant on Windows
# where stale references to the jars will
# block file deletion of the jars.
> test
$ exists target/scala-2.10/exportjars_2.10-0.1-SNAPSHOT.jar
$ exists target/scala-2.10/exportjars_2.10-0.1-SNAPSHOT-tests.jar
$ delete target/scala-2.10/exportjars_2.10-0.1-SNAPSHOT.jar
$ delete target/scala-2.10/exportjars_2.10-0.1-SNAPSHOT-tests.jar
$ absent target/scala-2.10/exportjars_2.10-0.1-SNAPSHOT.jar
$ absent target/scala-2.10/exportjars_2.10-0.1-SNAPSHOT-tests.jar
```
## problem

There is a well-known bug in the JVM, that classloaders do not release their jars
- http://management-platform.blogspot.co.uk/2009/01/classloaders-keeping-jar-files-open.html
- https://github.com/ancoron/apache-cxf/blob/master/common/common/src/main/java/org/apache/cxf/common/logging/JDKBugHacks.java
- http://stackoverflow.com/questions/7371277

this manifests as a memory leak on all platforms, but on Windows it is particularly bad because file handles mean a lock on the jars, which means they cannot be deleted, moved or changed.

A catastrophic consequence is that compilations silently fail (!!!) on Windows. This is not a corner case, it happens every single time reliably.

I experience this when I run tests when the `junit-interface` is loaded but after spending the evening reading the `junit-interface` code, I am pretty convinced that the bug can only be worked around at the level of the classloader, and sbt is the owner of that lifecycle.
## expectation

no leaks, no file locks.
## notes

Originally raised at https://github.com/sbt/junit-interface/issues/67

This escapes the workaround proposed in https://github.com/sbt/sbt/issues/1223 as classloader jars seem to get "lost" in the heap and are never reclaimed by explicit GC or `runFinalizers`.

The scala compiler is also doing a similar thing, as I observed in https://issues.scala-lang.org/browse/SI-9682

**Comment by fommil** [comment]
If this isn't an Elmo, it's at least an Ernie ![DEFCON](https://www.geekandproud.net/terror/images/terror-all.jpg)

**Comment by retronym** [comment]
Note that `URLClassLoader` has a public `close()` method in JDK7+: http://docs.oracle.com/javase/7/docs/technotes/guides/net/ClassLoader.html

**Comment by fommil** [comment]
cool, that simplifies the workaround... just call it reflectively. Good find! I was going to suggest changing the classloader.

**Comment by fommil** [comment]
Ok, I have a reproduction in the sbt codebase for this https://github.com/fommil/sbt/commits/fix-classloaders

It passes in Linux, but fails on Windows. Can somebody please add appveyor? I can set it up to only run this one test initially and then maybe we can look at expanding its scope to cover more tests.

**Comment by fommil** [comment]
I'm looking for classloaders in sbt and being a little perturbed by the fact that there is an entire package called `classpath` with many many implementations. Here are some suspicious locations that require further investigation. Every single one of these instantiations really needs a `close()` call when its done, which is somewhat terrifying:

```
compile/src/main/scala/sbt/compiler/AnalyzingCompiler.scala:115:11:      new URLClassLoader(Array(interfaceJar.toURI.toURL), dual)
util/classpath/src/main/scala/sbt/classpath/ClasspathUtilities.scala:17:76:  def toLoader(finder: PathFinder, parent: ClassLoader): ClassLoader = new URLClassLoader(finder.getURLs, parent)
util/classpath/src/main/scala/sbt/classpath/ClasspathUtilities.scala:20:74:  def toLoader(paths: Seq[File], parent: ClassLoader): ClassLoader = new URLClassLoader(Path.toURLs(paths), parent)
util/classpath/src/main/scala/sbt/classpath/ClasspathUtilities.scala:23:9:    new URLClassLoader(Path.toURLs(paths), parent) with RawResources { override def resources = resourceMap }
util/classpath/src/main/scala/sbt/classpath/ClasspathUtilities.scala:26:9:    new URLClassLoader(Path.toURLs(paths), parent) with RawResources with NativeCopyLoader {
util/classpath/src/main/scala/sbt/classpath/ClasspathUtilities.scala:30:14:        s"""|URLClassLoader with NativeCopyLoader with RawResources(
util/classpath/src/main/scala/sbt/classpath/ClasspathUtilities.scala:103:24:      val loader = new URLClassLoader(Path.toURLs(classpath))
util/classpath/src/main/scala/sbt/classpath/ClassLoaderCache.scala:36:24:      val loader = new URLClassLoader(files.map(_.toURI.toURL).toArray, commonParent)
util/classpath/src/main/scala/sbt/ScalaInstance.scala:145:9:    new URLClassLoader(jars.map(_.toURI.toURL).toArray[URL], launcher.topLoader)
main/src/main/scala/sbt/PluginManagement.scala:40:57:  final class PluginClassLoader(p: ClassLoader) extends URLClassLoader(Array(), p) {
main/actions/src/main/scala/sbt/compiler/Eval.scala:148:53:          val loader = (parent: ClassLoader) => new URLClassLoader(Array(back.toURI.toURL), parent)
```

for this specific bug, perhaps `TestFramework` could provide a hacky workaround.

**Comment by fommil** [comment]
the good news is that there are more `toLoader` methods than users.

```
compile/integration/src/main/scala/sbt/compiler/AggressiveCompile.scala:119:45:            val loader = ClasspathUtilities.toLoader(searchClasspath)
compile/integration/src/main/scala/sbt/compiler/javac/AnalyzingJavaCompiler.scala:62:39:      val loader = ClasspathUtilities.toLoader(searchClasspath)
scripted/plugin/src/main/scala/sbt/ScriptedPlugin.scala:32:39:      val loader = ClasspathUtilities.toLoader(classpath, scala.loader)
project/Scripted.scala:72:47:    val loader = classpath.ClasspathUtilities.toLoader(scriptedSbtClasspath.files, noJLine)
main/src/main/scala/sbt/Load.scala:830:30:          ClasspathUtilities.toLoader(data(defcp), parentLoader)
main/command/src/main/scala/sbt/BasicCommands.scala:129:54:      val loader = if (cp.isEmpty) parentLoader else toLoader(cp.map(f => new File(f)), parentLoader)
```

**Comment by fommil** [comment]
I have appveyor running off my branch https://ci.appveyor.com/project/fommil/sbt

**Comment by fommil** [comment]
how can I turn off this error temporarily for this one test? It's never going to pass on JDK6

```
java.lang.RuntimeException: javac version 1.7.0_79 may not be used to publish, it has to start with 1.6 due to javacVersionPrefix setting
```

**Comment by fommil** [comment]
I have a hack.

**Comment by eed3si9n** [comment]
@fommil remove `Release.javaVersionCheckSettings` from https://github.com/sbt/sbt/blob/0.13/build.sbt#L36

**Comment by fommil** [comment]
Thanks, but we'll need a repeatable test. I've got it listening to an envvar.

**Comment by fommil** [comment]
got a repeatible test in CI and also locally with my VirtualBox Windows 7 image. I'll try throwing some rocks in some random directions tomorrow and hope one lands on the bug.

**Comment by fommil** [comment]
fundamentally, `ClassLoader` should be treated like a `Closeable` resource. That looks like it would be a mad crazy refactor.

**Comment by fommil** [comment]
minimised to `definedTests` (not just `test`)

**Comment by fommil** [comment]
well, some progress. By explicitly closing the `root` of the `ClasspathFilter` I'm now getting failures to lookup the `JUnitRunner` when **running** the tests, but the `definedTests` piece now passes!

I think all I need to do now is to have a classloader that allows the jars to be closed, but still work when somebody tries to access them again.

I'm completely confused why this only breaks for `junit` tests and not scalatest tests. @bvenners (sorry to drag you into this) can you think of anything obvious? How does the scalatest `TestFramework` interact with the classloader?

**Comment by fommil** [comment]
oh, Java. Why oh why did you implement `close()` to be such a final thing. We need to get in at this private member

```java
    private WeakHashMap<Closeable,Void>
        closeables = new WeakHashMap<>();
```

(we must `synchronize` on it) and go close all the `JarFile` instances. Then I think the classloader can continue to operate.

I'll try doing that, but I don't have much hope because reflection doesn't tend to work on these core classes (the JVM lies)

**Comment by fommil** [comment]
as expected, `getDeclaredField` gives a `NoSuchFieldException` :cry:

it might be possible to subclass `URLClassLoader` to get access.

**Comment by fommil** [comment]
aha! I was using `.getClass` and you've already subclassed it. This is looking good.

**Comment by fommil** [comment]
I won't be able to look at this for a week, so if anybody wants to pick up my branch, I got as far as reflectively looking up the `closeables` field and finding that it was empty. Which was somewhat unexpected.

**Comment by fommil** [comment]
I'm dedicating today to this and coming up with a workaround.

**Comment by fommil** [comment]
the classloader I found is only holding references to `sbt-launch.jar` and `jre\lib\resources.jar`, but at least the reflective approach to closing the cached jars in the URLClassLoader is working OK.

**Comment by fommil** [comment]
even running an explicit GC / runFinalizers / GC after `detectTests` I can still see the `jar`s in the finalizer queue. Either the finalizer thread is getting stuck, or it just can't reach the objects anymore to `finalize` them. I can see the references in a heap dump. This is very very weird.

**Comment by fommil** [comment]
I'm back to thinking that maybe this could be fixed in `junit-interface`

**Comment by fommil** [comment]
ok, I've got hold of the `URLClassLoader` with the reference to the jars! However, it is claiming that it doesn't have `JarFile` references, so I'm not 100% sure what's going on.

**Comment by fommil** [comment]
lovely, the `URLClassPath` could also have the `JarFile`s http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/sun/misc/URLClassPath.java

**Comment by fommil** [comment]
W0000000000000000TTTTTT!!!!! Through evil manipulation of the deepest, darkest, corners of `sun.misc` `private final` fields, I have slayed the beast!

**Comment by fommil** [comment]
Given that my fix is insane, I can't see this ever making it into `sbt` proper. I'll package this up as a standalone workaround... which will involve using reflection to read private fields in `sbt`'s classloaders.

``` diff
new file   main/src/main/scala/sbt/CloseClassloader.scala
@@ -0,0 +1,81 @@
+// Copyright (C) 2016 Sam Halliday
+// Licence: http://www.apache.org/licenses/LICENSE-2.0
+package sbt
+
+import scala.annotation.tailrec
+
+object CloseClassloader {
+  def close(cl: ClassLoader, log: Logger): Unit = {
+    cl match {
+      case u: java.net.URLClassLoader =>
+        // do not use .getClass here as it is likely subclassed
+        val closeablesField = classOf[java.net.URLClassLoader].getDeclaredField("closeables")
+
+        log.info(s"classloader = ${u.getURLs.toList}")
+
+        closeablesField.setAccessible(true)
+        val closeables = closeablesField.get(u).asInstanceOf[java.util.WeakHashMap[java.io.Closeable, Void]]
+
+        closeables synchronized {
+          val it = closeables.keySet().iterator()
+          while (it.hasNext()) {
+            val closeable = it.next()
+            closeable match {
+              case jar: java.util.jar.JarFile =>
+                log.warn(s"closing ${jar.getName}")
+              case _ =>
+                log.warn(s"closing $closeable")
+            }
+
+            closeable.close()
+            it.remove()
+          }
+        }
+
+        // source of sun.misc.URLClassPath is not typically distributed with the JDK
+        // https://github.com/awh/openjdk7/blob/master/jdk/src/share/classes/sun/misc/URLClassPath.java
+        val urlClassPathField = classOf[java.net.URLClassLoader].getDeclaredField("ucp")
+        urlClassPathField.setAccessible(true)
+        val urlClassPath = urlClassPathField.get(u).asInstanceOf[sun.misc.URLClassPath]
+
+        // We need to close the Loaders (specifically the JarLoaders),
+        // yet trick the URLClassPath into being re-usable. Three ways to do this:
+        //
+        // 1. manually close the Loaders (its a private class, tricky)
+        // 2. close the loaders and then reset the collections
+        // 3. close the classpath and put a new one in the classloader
+        //
+        // None of this is thread-safe in the slightest
+        //
+        // option #3 it is...
+        val replacementUrlClassPath = new sun.misc.URLClassPath(u.getURLs)
+        urlClassPathField.set(u, replacementUrlClassPath) // FINAL, may not be seen...
+        urlClassPath.closeLoaders() // nothing should be able to reference this now
+
+        // partial impl of option 2
+        // val closedField = classOf[sun.misc.URLClassPath].getDeclaredField("closed")
+        // closedField.setAccessible(true)
+        // closedField.setBoolean(classPath, false)
+
+        val parentField = classOf[java.lang.ClassLoader].getDeclaredField("parent")
+        parentField.setAccessible(true)
+        val parent = parentField.get(u).asInstanceOf[ClassLoader]
+        if (parent != null)
+          close(parent, log)
+
+      case f: sbt.classpath.ClasspathFilter =>
+        close(f.parent, log)
+        close(f.root, log)
+
+      case f: sbt.classpath.DualLoader =>
+        close(f.parentA, log)
+        close(f.parentB, log)
+
+      // not accessible
+      //case f: xsbt.boot.BootFilteredLoader =>
+
+      case o =>
+        log.warn(s"classloader wasn't a supported ClassLoader: ${o.getClass}")
+    }
+  }
+}
modified   main/src/main/scala/sbt/Defaults.scala
@@ -575,7 +575,7 @@ object Defaults extends BuildCommon {
         }
     }
     val output = Tests.foldTasks(groupTasks, config.parallel)
-    output map { out =>
+    val results = output map { out =>
       val summaries =
         runners map {
           case (tf, r) =>
@@ -583,6 +583,8 @@ object Defaults extends BuildCommon {
         }
       out.copy(summaries = summaries)
     }
+    CloseClassloader.close(loader, s.log)
+    results
   }

   def selectedFilter(args: Seq[String]): Seq[String => Boolean] =
@@ -602,8 +604,10 @@ object Defaults extends BuildCommon {
         includeFilters.map { f => (s: String) => (f.accept(s) && !matches(excludeFilters, s)) }
       }
     }
-  def detectTests: Initialize[Task[Seq[TestDefinition]]] = (loadedTestFrameworks, compile, streams) map { (frameworkMap, analysis, s) =>
-    Tests.discover(frameworkMap.values.toList, analysis, s.log)._1
+  def detectTests: Initialize[Task[Seq[TestDefinition]]] = (testLoader, loadedTestFrameworks, compile, streams) map { (loader, frameworkMap, analysis, s) =>
+    val discovered = Tests.discover(frameworkMap.values.toList, analysis, s.log)._1
+    CloseClassloader.close(loader, s.log)
+    discovered
   }
   def defaultRestrictions: Initialize[Seq[Tags.Rule]] = parallelExecution { par =>
     val max = EvaluateTask.SystemProcessors
modified   util/classpath/src/main/scala/sbt/classpath/ClassLoaders.scala
@@ -45,7 +45,8 @@ final class SelfFirstLoader(classpath: Seq[URL], parent: ClassLoader) extends Lo
 }

 /** Doesn't load any classes itself, but instead verifies that all classes loaded through `parent` either come from `root` or `classpath`.*/
-final class ClasspathFilter(parent: ClassLoader, root: ClassLoader, classpath: Set[File]) extends ClassLoader(parent) {
+final class ClasspathFilter(val parent: ClassLoader, val root: ClassLoader, classpath: Set[File]) extends ClassLoader(parent) {
+
   override def toString =
     s"""|ClasspathFilter(
         |  parent = $parent
@@ -177,4 +178,4 @@ trait NativeCopyLoader extends ClassLoader {
       IO.copyFile(f, target)
       target.getAbsolutePath
     }
-}
\ No newline at end of file
+}
modified   util/classpath/src/main/scala/sbt/classpath/DualLoader.scala
@@ -31,8 +31,8 @@ class DifferentLoaders(message: String, val loaderA: ClassLoader, val loaderB: C
  * Otherwise, if `bOnlyResources` is `true` for a resource path, lookup delegates to `parentB` only.
  * If neither are `true` for a resource path and either `parentA` or `parentB` return a valid URL, that valid URL is returned.
  */
-class DualLoader(parentA: ClassLoader, aOnlyClasses: String => Boolean, aOnlyResources: String => Boolean,
-    parentB: ClassLoader, bOnlyClasses: String => Boolean, bOnlyResources: String => Boolean) extends ClassLoader(new NullLoader) {
+class DualLoader(val parentA: ClassLoader, aOnlyClasses: String => Boolean, aOnlyResources: String => Boolean,
+    val parentB: ClassLoader, bOnlyClasses: String => Boolean, bOnlyResources: String => Boolean) extends ClassLoader(new NullLoader) {
   def this(parentA: ClassLoader, aOnly: String => Boolean, parentB: ClassLoader, bOnly: String => Boolean) =
     this(parentA, aOnly, aOnly, parentB, bOnly, bOnly)
   override final def loadClass(className: String, resolve: Boolean): Class[_] =
```

**Comment by fommil** [comment]
@retronym the `URLClassLoader.close()` means it cannot be used again, whereas this hack puts the classloader into a reusable state. Arguably, we could call `close()`, then hotswap the `ucp: URLClassPath` instance, but that is "less" thread safe because threads could be using the `ucp` whereas my approach hotswaps and then cleans the old one (I say "less" because the code above is in no way thread safe).

**Comment by fommil** [comment]
well, unfortunately this workaround doesn't work in my work, despite it working in my standalone tests on Windows. I have no idea what is going wrong: perhaps the version of the JDK or number of cores is somehow relevant, in which case I have no idea what to do except to patch sbt to not re-use the test loader (and to close it after use).

**Comment by fommil** [comment]
I finally worked around this. In a nutshell, use a java agent to monkey patch `URLClassLoader` so that we have a much more sensible backend implementation of `URLClassPath`.

I think going forwards it would be very useful for both scala-compiler and sbt to have their own classloader, more similar to mine (I'm happy to discuss changing the licence if that's interesting, but we can't re-licence the OpenJDK test suite). There is a lot of optimisation can be done at the classloader level, especially when you're in a very persistent JVM process.

:microphone: drop https://github.com/fommil/class-monkey => https://ci.appveyor.com/project/fommil/sbt-big-project/build/1.0.18

**Comment by fommil** [comment]
I consider this closed with the above workaround
