### ISSUE TITLE
wiki: Docs on testing have invalid code

### ISSUE THREAD

**Issue by waywardmonkeys** [sbt/sbt#250]
On https://github.com/harrah/xsbt/wiki/Testing, some of the code refers to `TestFilter` rather than `Tests.Filter`.  There are other errors in the same blocks of code as well, like not assigning a `Seq` back, but the bare filter.

**Comment by harrah** [comment]
It looks like Daniel fixed this.  Note that the wiki is editable, so you can fix smaller issues like this yourself.
