### ISSUE TITLE
Document the release process

### ISSUE THREAD

**Issue by copumpkin** [sbt/sbt#2502]
It's not entirely clear from the build.sbt or documentation I've been able to find what actually produces the various parts of the release. I know the launcher is involved, as is this repo, and a couple of other repos. Is there a single command that publishes the various parts and produces the final launcher tarball that is uploaded to the main website?

**Comment by eed3si9n** [comment]
Yes: https://github.com/sbt/sbt/blob/0.13/build.sbt#L563-L597

There are other miscellaneous side projects like Zinc and Linux installers, but the main parts is releasing using the `release-sbt` command.

**Comment by dwijnand** [comment]
With regards to the launcher, the code is in sbt/launcher and a jar is released from there, then it's re-bundled and re-deployed from here (with this version number).

**Comment by eed3si9n** [comment]
Hopefully current https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md addresses this.
