### ISSUE TITLE
Configuring Parallel Execution

### ISSUE THREAD

**Issue by alltonp** [sbt/sbt#251]
Hi,

I'm trying to get my WebDriver specs2 tests to run with Parallel Execution. 

How can I specify the number of worker threads that are used? It seems to be using about 4 (is this based on number of core's?) and unfortunately my machine melts with 4 browsers running.

Also, is it possible to have finer grained control about what is executed in parallel? 

Specifcally I would like to be able to choose between running
- all examples for a given spec in parallel (but each spec serially)
- all specs in parallel (but each example serially)
- everything in parallel

Many thanks,

Paul

**Comment by harrah** [comment]
More flexible control was implemented as part of:

https://github.com/harrah/xsbt/commit/eb2ec8c7815b225e556fc88d0c775b5ad01d77c3

and documented here:

https://github.com/harrah/xsbt/wiki/Parallel-Execution

Configuring parallel execution of examples is handled by the test framework and is not integrated with sbt's parallel execution (unfortunately.  this has been discussed on the mailing list in detail.).
