### ISSUE TITLE
Used ivy is too old

### ISSUE THREAD

**Issue by gaydenko** [sbt/sbt#2511]
Hi!

Please look at:

https://groups.google.com/forum/#!topic/play-framework/dRj4VPbFJAA
https://groups.google.com/forum/#!topic/play-framework/xTt5WQMtTY0

And it is possible to find plenty of other similar ones. I guess the root is here:

https://issues.apache.org/jira/browse/IVY-1487

SBT seems to use custom ivy 2.3.0, while the mentioned ivy issue was fixed in 2.4.0. Can the patch be applied to sbt-ivy?

**Comment by eed3si9n** [comment]
Could you comment on #1920?
Maybe we can revive the discussion.

**Comment by gaydenko** [comment]
OK, have moved there.
