### ISSUE TITLE
DslEntry does not support addSbtFiles

### ISSUE THREAD

**Issue by Atry** [sbt/sbt#2514]
I want to share sbt files across multiple projects, especially Scala.js and JVM projects. https://github.com/ThoughtWorksInc/Binding.scala

At the moment I use `lazy val coreJS = core.js.addSbtFiles(file("../build.sbt.shared"))` in the parent project.

I hope I could put the `addSbtFiles` directive in sub-project.

How do you guys think about that?

**Comment by eed3si9n** [comment]
One of the unwritten philosophy about sbt is that a build should be repeatable.
Once you start pulling in build files from outside of the build, you could easily get yourself into a situation where it works one day, but it doesn't in another even though it's on the same commit. If you're looking for a way to share the settings, I think the plugin or plain `List` is the way to go.

**Comment by Atry** [comment]
I understand the unwritten philosophy. Unfortunately we have to create multiple similar projects for some technical reasons. We usually create two sbt sub-projects for a code base that target both JVM and Scala.js . 

What is the best practice to share common settings for the two projects?

**Comment by eed3si9n** [comment]
I don't know much about Scala.js, but I am guessing people are using http://www.scala-js.org/doc/project/cross-build.html

``` scala
name := "Foo root project"

lazy val root = project.in(file(".")).
  aggregate(fooJS, fooJVM).
  settings(
    publish := {},
    publishLocal := {}
  )

lazy val foo = crossProject.in(file(".")).
  settings(
    name := "foo",
    version := "0.1-SNAPSHOT",
    scalaVersion := "2.11.5"
  ).
  jvmSettings(
    // Add JVM-specific settings here
  ).
  jsSettings(
    // Add JS-specific settings here
  )

lazy val fooJVM = foo.jvm
lazy val fooJS = foo.js
```
