### ISSUE TITLE
Need SBT 1.0 Feature Migration Guide

### ISSUE THREAD

**Issue by jbyler** [sbt/sbt#2517]
Filing per request of Josh Suereth on the sbt-dev mailing list in a [message](https://groups.google.com/d/msg/scala-tools/uuFsGN1DhNs/JRQdaCUKUjAJ) about AutoPlugin usage.
## problem

Developer has sbt 0.13.1 build which uses `Defaults.defaultSettings`.  Developer upgrades to sbt 1.0 and receives warnings about defaultSettings being deprecated.  Developer looks for migration guide to detail changes needed, but finds none.
## expectation

A migration guide should be provided in the SBT documentation, detailing how to convert pre-1.0 projects into idiomatic SBT 1.0 projects.  In particular, the guide should cover how the usage of AutoPlugins changes build definitions.
## notes

Josh's description:

```
Hope that helps!  Also, please open a ticket about an sbt 1.0 feature migratoin guide.
As we backport sbt 1.0 features into 0.13, we should keep such a guide up-to-date
(e.g. AutoPlugins is one such aspect).   The 0.13.2 guide you see basically needs
to be morphed into the 1.0 guide.
```

**Comment by jbyler** [comment]
Here is a [draft](https://github.com/sbt/sbt/blob/fde0ac88079fb8a65c1b7871f1c0d416cbd0eaab/src/sphinx/Migrations/MigrationGuide_0.13.2.rst) of an 0.13.2 migration guide which can possibly be used as a starting point.

**Comment by eed3si9n** [comment]
Thanks

**Comment by SRGOM** [comment]
> The follow project definition from a  project/Build.scala  will fail in 0.13.2

> To fix you need to add both the  autoPlugins  and  projectSettings  includes as shown

I was under the impression that project/Build.scala had been deprecated.

**Comment by jeffwilde** [comment]
Since this page pops-up for google searches of "sbt 1.0 migration", it's worth noting that [the completed guide is available](http://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html) and that this issue should probably be closed.

**Comment by eed3si9n** [comment]
Yea. Let's close this up.
