### ISSUE TITLE
off-the-grid/offline installation of sbt

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2518]
## steps

Suppose I'm behind some firewall or just no internet.
I'd like to create a file image that can launch sbt.
## problem

Prior to sbt 0.13.11 I probably could have created a file image based on all the JARs sbt will download during boot and it might have worked. With sbt 0.13.11 the compiler bridge is resolved from the repository.
## expectation

A command `install` or something that creates installation image that's runnable without hitting Ivy cache OR Ivy local.

Ideally a single JAR version of sbt that does not need to hit the Internet.

**Comment by dwijnand** [comment]
Does that single JAR include the contents of sbt-launch.jar?

**Comment by eed3si9n** [comment]
The single-jar might diverge too much from the current implementation, so a better option might be preloaded-local repository like that of Activator, and some way of denotation in the `launchconfig` to look at the preloaded-local, such as `preloaded-local`. See http://www.scala-sbt.org/0.13/docs/Launcher-Configuration.html

**Comment by dwijnand** [comment]
That sounds like a lot of machinery...

I've been thinking recently that I'm not so sure about sbt-launcher..

In my ideal world, given an `sbt.version` in `project/build.properties` and `sbt-extras` a single uniquely-versioned fat jar of sbt is downloaded (unless already present) and then run.

**Comment by fommil** [comment]
There aren't enough +1s in the world for this.

**Comment by dwijnand** [comment]
Fixed in #2564

**Comment by eed3si9n** [comment]
I don't think #2564 fully work.

**Comment by eed3si9n** [comment]
Another idea around this is defining a local preloaded repo name "preloaded-local", "preloaded-local-ivy" or something like that on a pre-agreed location on the machine, such as `~/.sbt/preloaded-local/`.
Installer then can place sbt artifacts to the location up front.

**Comment by dwijnand** [comment]
Why a new location? Why not place them in the ivy cache?

**Comment by eed3si9n** [comment]
Ivy cache is opaque to us, whereas additional "preloaded" local repo is perfectly safe. See also Activator.

**Comment by dwijnand** [comment]
I don't think we should duplicate artefacts more. Surely Ivy must provide some API for injecting artefacts into its cache. Either directly or indirectly.

Activator introducing yet-another-repo is a bad precedent. See ~/.ivy2/cache vs ~/.m2/repository vs ~/coursier/cache. sbt shouldn't introduce another one.

**Comment by eed3si9n** [comment]
When we know for fact that this particular technique works. Attempting to inject stuff into Ivy cache is undocumented, and unsafe (this is why we have global lock). The problem with Activator was that it didn't correctly do this, but injected it into repositories override.

**Comment by dwijnand** [comment]
That's why I said "indirectly" - use a temporary ivy repository, load it with artefacts and then resolve the artefacts from there. Done. You've preloaded the cache.

**Comment by alexarchambault** [comment]
My [custom coursier-based launcher](https://github.com/alexarchambault/coursier/blob/master/csbt) allows just that: once everything's in cache, set ttl to infinity (`export COURSIER_TTL=Inf` should do), and enjoy an offline mode.

**Comment by fommil** [comment]
@alexarchambault I'm not sure that helps with offline **installation** of sbt though, it's more like an offline mode? The original motivation for this ticket was "how to install sbt in a corporate environment that only allows for one file to get through a heavyweight internal packaging process". I'm not entirely sure if the ivy solution proposed here meets that criteria either.

**Comment by alexarchambault** [comment]
@fommil Agreed, the coursier-based launcher would still need the required JARs to be shipped in one way or another.
