### ISSUE TITLE
Add an install command to install new dependencies

### ISSUE THREAD

**Issue by armandgrillet** [sbt/sbt#2521]
Hi,

I just started using Scala and sbt and I was wondering why there is no equivalent to `npm install` in sbt. 
## steps

Currently the steps to install new dependencies are (after updating `build.sbt`):

```
$ sbt
> reload
> update
```
## problem

Could these steps be reduced to:

```
$ sbt
> install
```

The word `install` being more logical to install a new dependency than `update` and a standard keyword to install new dependencies (e.g. it is used to install libraries with npm and Homebrew). `install` could do the same things as `reload` and `update` or only install new dependencies without updating the ones already installed.
## notes

`install` would not allow to add a dependency to the project using a command like `sbt install breeze`, it would only work by reading `build.sbt` and install the unresolved dependencies.

My logic is maybe contrary to the Scala/sbt philosophy, this issue is a remark on the only thing that has not been smooth for me when starting to use `sbt`. If there is a reason why `sbt install` does not exist, I would happily continue to use `reload` and `update`.

**Comment by dwijnand** [comment]
As another alternative, given ant and ivy, this can be achieved with [`ivycp`](https://github.com/paulp/sbt-extras/blob/20ec18a9761715b4dbb436754e1e2d5e69024550/ivycp) in `sbt-extras`.

**Comment by soc** [comment]
Such a command could be useful, but I'm not sure `install` as an abbreviation for `reload & upddate` makes sense ... plus, what about all the other imaginable `reload & ...` combinations?

**Comment by armandgrillet** [comment]
I agree, it should be a command installing the unresolved dependencies without updating the ones that are already installed. Does such a command already exist?

**Comment by eed3si9n** [comment]
sbt 1.3.0 implements auto reloading.
