### ISSUE TITLE
How to make `compile` 5x faster when nothings needs compiling

### ISSUE THREAD

**Issue by gkossakowski** [sbt/sbt#2525]
## steps
1. Checkout https://github.com/gkossakowski/sbt-slow-compile
2. Run `compile`
3. Run `compile sub4/compile`
## problem

The second compile is slow taking about 1500ms to run even when there's nothing to compile.
## expectation

The `compile` should run much faster. The lower bound how long `compile` should take is about 7ms (on MacOs). The lower bound is determined by how much time does it take to check if any of the sources in `sub4` project has been modified:

``` scala
def lastModified(fileName: String): Long = (new File(fileName)).lastModified
time { for (i <- 0 to 999) yield lastModified(s"sub4/E$i.scala") }
// Elapsed time: 5ms
```
## notes

The bulk of the time goes into a complicated way of looking up `Analysis` object instances for dependencies coming from other subprojects. When you invoke `compile`, two things are checked:
1. Whether external dependencies of a project has changed
2. Whether sources has changed

The incremental compiler tracks dependencies from other subprojects by a binary class name. Binary class names are mapped to Analysis objects that track information about dependencies. The mapping first maps a binary class name to a classpath element with a classpath lookup and then another lookup is performed to find out which Analysis object is tracking the given class file. Each classpath lookup in sbt requires a few calls to OS to check file status.
The more direct way of looking up Analysis would be to go from the binary class name to the Analysis instance.

I was curious how expensive the classpath lookup part is so I've hacked a prototype of directly going from a binary class name to an instance of Analysis. The experiment was done with sbt 1.0 and zinc. I've used `sbt-slow-compile` project to compare performance.

The performance of sbt 1.0:

```
scala> time { cpHelpers.taskKeyEvaluate(compile in Compile in sub4).eval }
Elapsed time: 1505ms
res5: T = Analysis: 1000 Scala sources, 1000 classes, 4000 external source dependencies, 1 binary dependency

scala> time { cpHelpers.taskKeyEvaluate(compile in Compile in sub4).eval }
Elapsed time: 1573ms
res6: T = Analysis: 1000 Scala sources, 1000 classes, 4000 external source dependencies, 1 binary dependency

scala> time { cpHelpers.taskKeyEvaluate(compile in Compile in sub4).eval }
Elapsed time: 1727ms
res7: T = Analysis: 1000 Scala sources, 1000 classes, 4000 external source dependencies, 1 binary dependency
```

My prototype:

```
scala> time { cpHelpers.taskKeyEvaluate(compile in Compile in sub4).eval }
Elapsed time: 261ms
res9: T = Analysis: 1000 Scala sources, 1000 classes, 4000 external source dependencies, 1 binary dependency

scala> time { cpHelpers.taskKeyEvaluate(compile in Compile in sub4).eval }
Elapsed time: 270ms
res10: T = Analysis: 1000 Scala sources, 1000 classes, 4000 external source dependencies, 1 binary dependency

scala> time { cpHelpers.taskKeyEvaluate(compile in Compile in sub4).eval }
Elapsed time: 265ms
res11: T = Analysis: 1000 Scala sources, 1000 classes, 4000 external source dependencies, 1 binary dependency
```

The code can be found in these branches:

https://github.com/gkossakowski/zinc/tree/lookup
https://github.com/gkossakowski/sbt/tree/lookup

**Comment by gkossakowski** [comment]
I'm leaving this up for grabs.

**Comment by gkossakowski** [comment]
//cc @fommil who I suspect would like to know about this

**Comment by gkossakowski** [comment]
I think fixing this would take around 30-40 hours in sbt 1.0 branch where compatibility constrains are less severe.

**Comment by fommil** [comment]
what if source change lookup was all async? Like with https://github.com/ensime/java7-file-watcher ... that should really speed up the detection of file changes (which is much much slower on Windows).

**Comment by gkossakowski** [comment]
On Mac (and I'm guessing on Linux) checking the file status of 1k Scala files takes just 5ms so it's a non-issue. How much slower is that on Windows?

**Comment by fommil** [comment]
slow enough that I have to turn it off inside ENSIME or it eats the CPU. I'll run a small test case tomorrow to answer that.

**Comment by gkossakowski** [comment]
You can check it with the repo and the snippet I left above. It would be great to compare the numbers.

Speaking of detecting source file changes, the incremental compiler compare hashes of file contents at the moment. It does it without any optimization like checking last modification date. I believe that improving this part would yield 10x instead of 5x improvement.

**Comment by fommil** [comment]
I won't be able to use your repo in work, as it'll need to be approved. I'll write a script to check modified times on a realistically sized project. What's the hash algorithm? If it's simple enough, I could add that to the script. A warm `git grep` on my codebase takes about 30 seconds (much longer for full grep).

**Comment by fommil** [comment]
oh, absolutely, check modified date and file size first. That's a reasonable assumption to make. Remember file timestamp fidelity is 1 second (even on Linux / OS X), which tends to crop up in testing a lot more than you'd want.

**Comment by gkossakowski** [comment]
The hash algorithm can be found here: https://github.com/sbt/sbt/blob/0.13/util/io/src/main/scala/sbt/Hash.scala

**Comment by fommil** [comment]
oh, wow, `for` comprehensions over `Byte`. I bet that churns through memory allocations. Rewriting with `while` would probably make a big difference too // @rorygraves

**Comment by rorygraves** [comment]
Ok, quick review 
https://github.com/sbt/sbt/blob/0.13/util/io/src/main/scala/sbt/Hash.scala#L16 - scala does not optimise the simple case out - so it creates a thunk representing the comprehension
Same here https://github.com/sbt/sbt/blob/0.13/util/io/src/main/scala/sbt/Hash.scala#L33

Thats only one object allocation per call but also I believe this 
https://github.com/sbt/sbt/blob/0.13/util/io/src/main/scala/sbt/Hash.scala#L31 creates a thunk for the lazy error string (or worse creates the String)

This is potentially the worst:
https://github.com/sbt/sbt/blob/0.13/util/io/src/main/scala/sbt/Hash.scala#L83 - one per call to toHex

Replacing the first two with while loops and the third and forth with an if statement would make it significantly faster I believe (proof is in the testing as always)

**Comment by fommil** [comment]
@gkossakowski 25 seconds to scan all source files in my project, on a warm load (it can take several minutes on first boot). I don't think I'll have time to run the hash calculator today but I am certain it's a lot bigger than 25 seconds.

**Comment by gkossakowski** [comment]
How many source files do you scan?

On Wednesday, 30 March 2016, Sam Halliday notifications@github.com wrote:

> @gkossakowski https://github.com/gkossakowski 25 seconds to scan all
> source files in my project, on a warm load (it can take several minutes on
> first boot). I don't think I'll have time to run the hash calculator today
> but I am certain it's a lot bigger than 25 seconds.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/sbt/sbt/issues/2525#issuecomment-203359218

## 

Grzegorz Kossakowski
twitter: @gkossakowski http://twitter.com/gkossakowski
github: @gkossakowski http://github.com/gkossakowski

**Comment by fommil** [comment]
@gkossakowski can you ask Eugene confidentially?

**Comment by jvican** [comment]
I'd love to see this feature in the next release of sbt. Any chance?

**Comment by fommil** [comment]
If I worked on this, would you accept an Apache 2.0 licensed file? I am not signing the Typesafe CLA because of the deviations from the Apache / Scala CLA, most importantly this clause

```
10. The Agreement shall be governed by and construed and enforced in accordance with, the
laws of the State of California, without reference to conflicts of laws. The application of the
United Nations Convention on the International Sale of Goods to the Agreement is disclaimed in
its entirety. This Agreement is the entire agreement, both written or oral, with respect to the
Contributions between the parties.
```

**Comment by eed3si9n** [comment]
Using the current sbt 1.0.0-SNAPSHOT the number I get is something like:

```
> check
running compile took 570.49902 ms
> check
running compile took 927.169266 ms
> check
running compile took 295.587101 ms
> check
running compile took 305.026124 ms
> check
running compile took 306.711616 ms
```

so I am guessing a lot of the slowness was coming from my sbt/zinc#100 bug. Implementing this will speedup but it's probably not going to be as dramatic as "5x" any more.

**Comment by gkossakowski** [comment]
Did you get the numbers for sbt 1.0.0-SNAPSHOT using `sbt-slow-compile` project and compiling the `sub4` project?

**Comment by eed3si9n** [comment]
@gkossakowski Yea. I added a command that does the timing - https://github.com/eed3si9n/sbt-slow-compile/commit/beffd7eecf4950490787bf2459d379fd820d4085

**Comment by eed3si9n** [comment]
Fixed via https://github.com/sbt/zinc/pull/180
