### ISSUE TITLE
Type alias and object does not work correctly in REPL

### ISSUE THREAD

**Issue by kxbmap** [sbt/sbt#2526]
## steps
1. Clone https://github.com/kxbmap/repl-alias-error.git
2. Run sbt console
3. Type `com.example.Alias.zero` twice
## problem

Compilation error on the second input.

``` scala
Welcome to Scala 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_77).
Type in expressions for evaluation. Or try :help.

scala> com.example.Alias.zero
res0: com.example.Alias = Foo(0)

scala> com.example.Alias.zero
<console>:12: error: value zero is not a member of object com.example.Alias
       com.example.Alias.zero
                         ^

scala>
```
## expectation

No error.

**Comment by eed3si9n** [comment]
I think you're hitting https://issues.scala-lang.org/browse/SI-7139

**Comment by kxbmap** [comment]
Yes, that's right. I'll close this issue.
