### ISSUE TITLE
Error message could be better

### ISSUE THREAD

**Issue by aragnon** [sbt/sbt#2529]
I get

```
java.io.IOException: Permission denied
        at java.io.UnixFileSystem.createFileExclusively(Native Method)
<ELIDED BY ME>
```

The problem is that it doesn't say _what_ exactly it tried to access. I expect that all exceptions of this kind are caught and display a proper error message like "Dear user, we tried to create a file named foo in directory /bar/za. Unfortunately, the w bit in directory za is not set for user $RUNNING_USER, so as a result this program will now have to exit. Please correct this situation and run the program again".

**Comment by dwijnand** [comment]
I agree. Could you provide a reproducing case so we can pin-point what needs changing?
