### ISSUE TITLE
Apply AutoPlugin to all Test configurations

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#2534]
With the move to `build.sbt` and away from `Build.scala` there will be no easy way to apply settings to all user-defined configurations.

With `Build.scala` this was never pretty, but a workaround was possible such that a method could be called explicitly with the list of `Configuration`s to enable.

e.g. this could take the form of a method in `AutoPlugin` which will always be called `inConfig` for all configurations that are enabled for that `Project` that derive from `Test` (possibly even for `Test` also).

**Comment by dwijnand** [comment]
Why is this not similarly achievable in `build.sbt`?

Alternatively put, how is this related to the removal of the `Build` trait?

**Comment by fommil** [comment]
Hmm. Yeah, I guess it is still possible to call out.

OK, then I retract this being a blocker for 1.0 but it would certainly be an improvement of the `AutoPlugin` API and be another reason for people to move over.

**Comment by fommil** [comment]
Maybe the method could be called `projectTestSettings`, as opposed to `projectSettings` ?

**Comment by fommil** [comment]
@eed3si9n can this please be considered for the 1.0 milestone? It's one of the main reasons I don't like autoplugins (typically I end up having to manually add settings for IntegrationTests, defeating the effort of writing everything as an auto plugin in the first place).

Suggested interface `projectConfigSettings(config: Configuration): Seq[Setting[_]]` called for everything except `Compile` (which is handled by `projectSettings`).

**Comment by eed3si9n** [comment]
As suggested in #2580, can derived task (https://gist.github.com/eed3si9n/bf561bce36ca72b5f659) work here?

**Comment by fommil** [comment]
not really, it is too much of a hack (and I couldn't even get it to work for IntegrationTest)

**Comment by fommil** [comment]
even being able to get at the `Seq[Configuration]` (i.e. `ivyConfigurations`) outside of a `Setting` context would be really useful for this.

**Comment by fommil** [comment]
@eed3si9n the reason derived task is no good is because the `Seq[Configuration]` needs to be obtained outside of a task assignment. We basically need a `customConfigs` method like this `customConfigs(project).flatMap(projectSettings)` outside of a `Setting` context.

**Comment by fommil** [comment]
doh! @dwijnand just pointed out that this sits on `Project` so I have a workaround for manual addition of settings.

**Comment by fommil** [comment]
another possible impl could be `configSettings` which gets called per config, wrapped in `inConfig` already. Or a `projectSettingsFor(config: Configuration)`

**Comment by fommil** [comment]
will be solved by  https://github.com/sbt/sbt/issues/2899
