### ISSUE TITLE
Add quiet flag to sbt

### ISSUE THREAD

**Issue by erip** [sbt/sbt#2535]
I propose a quiet flag to be added to sbt to remove all noise aside from stdout. This includes `[info]` messages and success messages.
## current workaround

```
echo "showSuccess := false" >> build.sbt
sbt --error run
```

**Comment by eed3si9n** [comment]
I have to wade into the logging when server happens. I'll keep this one in mind too.

**Comment by SethTisue** [comment]
very similar to #840

**Comment by eed3si9n** [comment]
Closing this in favor of #840 then.
