### ISSUE TITLE
how to use Keys build settings for resource filtering

### ISSUE THREAD

**Issue by max8github** [sbt/sbt#2548]
## steps

From an sbt plugin, create a `Map[String,String]` of entries like

```
"baseDirectory" -> whateverPathSbtFiguresOutAtCompileTime
```

for all interesting Settings in object `sbt.Keys` (like `target`, etc).
## problem

In order to do resource filtering (like in Maven) with an sbt plugin or some sbt code, you somehow need to get hold of all interesting keys that sbt knows about when building, for example the _target_ directory or the _base directory_.
But how do you do that? Can you suggest a way without using reflection on Keys?
Or, even better, is there a plugin? Seems pretty standard functionality, but i was not able to find anything near to whatever Maven has out of the box on this. The two plugins i found, _xsbt-filter_ and _sbt-editsource_, are close in functionality, but do not satisfy the use case (see `baseDirectory`, for example).
## expectation

The expectation would be to have a standard sbt plugin doing resource filtering like in Maven for resource files in different scopes (main, test, it) with tokens like `${mytoken}` that the user defines from a filter file or standard ones like `${baseDirectory}`.
In lack of that, the expectation would be to get hold of a simple API that provides what is needed, that is all standard tokens like "baseDirectory".
## notes

Maybe the answer to this is trivial, in which case, i am simply not knowledgeable enough on scala or sbt to code this. In that case, some direction will help.
I tried reach out on stackoverflow (http://stackoverflow.com/questions/36510188/token-substitution-resource-filtering-with-sbt), but got no answers.

**Comment by eed3si9n** [comment]
Github issue is set up for bug reports. "But how do you do that?" is not a problem of sbt.
Resource filtering does sound like a fun problem to solve tho.
http://www.scala-sbt.org/community.html#how-can-I-get-help

**Comment by max8github** [comment]
I am sure is fun, but unsure if it can be done with this version of sbt.
I guess by "_how do you do that_" i meant "_there is no way to do that currently_".
So, is this the place for feature requests, or only bugs?

If it is the place for feature requests, then the request is (should i open another item?):
_provide an API in such a way that the sbt user can possibly do resource filtering_ (given that there is no such thing out of the box).
If there is a way to do this without reflection, then please say "yes, there is" and then please close this item.

**Comment by max8github** [comment]
never mind, just noticed your answer on stackoverflow: will try that, and then maybe open a feature request if needed. Thanks
