### ISSUE TITLE
Add evicted version information to callers in output of evicted command

### ISSUE THREAD

**Issue by jedesah** [sbt/sbt#2550]
## steps

Call the `evicted` command
## problem

Each library which has evicted versions is listed along with which versions are evicted and what libraries for bringing in these versions. However, it can be hard to tell which one of the callers is bringing in which version of the evicted library.
## expectation

I think it would be really nice if each caller was listed along with the version of the evicted library that they are bringing in.

**Comment by eed3si9n** [comment]
I guess this was fixed in https://github.com/sbt/sbt/pull/3204
