### ISSUE TITLE
Where can we find sbt jar in repositories?

### ISSUE THREAD

**Issue by saifellafi** [sbt/sbt#2558]
## problem

My intelliJ plugin is trying to resolve the following but cant find it.
https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.9/sbt-0.13.9.jar

Indeed SBT is no longer in maven2, and typesafe resolver redirects to bintray, which doesnt have such structure either
## expectation

This sounds silly but I am not sure what repository to point to in my system to get SBT right now.
org/scala-sbt/sbt doesnt exist anywhere I know of right now.

Thanks in advance,
Saif

**Comment by eed3si9n** [comment]
It's under https://repo.typesafe.com/typesafe/ivy-releases/, which redirects to Bintray, but please don't link directly to Bintray because we might change the underlying repo (and we have in the past).
