### ISSUE TITLE
0.13.11 regression: incremental compiler misses when macro expansion references another source

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2560]
## steps
1. Macro expansion in `A.scala` references another source `B.scala`.
2. Change `B.scala`.
## problem

`A.scala` doesn't get compiled.
## expectation

`A.scala` gets compiled.
## notes

This can be confirmed when "member reference internal dependencies" doesn't contain the entry from `A.scala` to `B.scala`.

This was caused by 0f616294c4e713dc415f5dc3ae7aef257decb228:

``` scala
   override def traverse(tree: Tree): Unit = tree match {
     ....
      case MacroExpansionOf(original) if inspectedOriginalTrees.add(original) => traverse(original)
      case other => super.traverse(other)
    }
```

This won't traverse into an `Apply` tree, for instance if it has `MacroExpansionAttachment`. The fix is to call `super.traverse(tree)` for `MacroExpansionOf` case as well.

**Comment by gkossakowski** [comment]
Do you know why existing scripted tests for macros didn't catch the regression?

**Comment by eed3si9n** [comment]
@gkossakowski See the new repro in #2563. The existing scripted tests didn't catch this because the macro is too simple, and it doesn't introduce new member ref beyond the original tree.
