### ISSUE TITLE
incorrect scalaBinaryVersion inference (specifically for typelevel scala)

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#2561]
## steps

use a `scalaVersion` such as `2.11.8-tl-201604131941`
## problem

the `scalaBinaryVersion` is inferred as `2.11.8-tl-201604131941`
## expectation

the `scalaBinaryVersion` should be inferred as `2.11`
## notes

workaround is to force the `scalaBinaryVersion` but this results in lots of `Binary version` warnings.

https://github.com/milessabin/si2712fix-demo/issues/7

**Comment by eed3si9n** [comment]
This is by design. See http://www.scala-sbt.org/0.13.11/sxr/CrossVersionUtil.scala.html#sbt.cross.CrossVersionUtil.scalaApiVersion

The naming convention of bincompat Scala substitute is `2.11.8-bin-*` e.g. `2.11.8-bin-tl-201604131941`.
