### ISSUE TITLE
sbt.bat from the msi installer mangles command line arguments

### ISSUE THREAD

**Issue by jrd-rocks** [sbt/sbt#2562]
## steps

run

```
sbt.bat -Dsbt.log.noformat=true saveClasspath
```
## problem

the sbt.bat scripts then tries to execute
`
"C:\Program Files\Java\jre1.8.0_77\bin\java.exe" -Dfile.encoding=UTF8 -Xms2G -Xmx6G -XX:ReservedCodeCacheSize=500M -XX:+TieredCompilation -XX:-UseGCOverheadLimit -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC -Dsbt.log.format=true -cp "C:\Program Files (x86)\sbt\bin\sbt-launch.jar" xsbt.boot.Boot -Dsbt.log.noformat true saveClasspath
`

notice the missing = , it's `-Dsbt.log.noformat true` instead of `-Dsbt.log.noformat=true`
## Fix

in sbt.bat replace the loop that extracts the -jvm-debug parameter with

```
set t=%*
:debugloop
for /f "tokens=1*" %%a in ("%t%") do (
  if "%%a" == "-jvm-debug" (
    set JVM_DEBUG=true
    set /a JVM_DEBUG_PORT=5005 2>nul >nul
  ) else if "!JVM_DEBUG!" == "true" (
    set /a JVM_DEBUG_PORT=%%a 2>nul >nul
    if not "%%a" == "!JVM_DEBUG_PORT!" (
      set SBT_ARGS=!SBT_ARGS! %%a
    )
  ) else (
    set SBT_ARGS=!SBT_ARGS! %%a
  )
  set t=%%b
)
if defined t goto :debugloop
```

See http://stackoverflow.com/questions/1707058/how-to-split-a-string-in-a-windows-batch-file

**Comment by dwijnand** [comment]
I wonder if this is still valid as we've done a number of iteration changes on the bat file around these things. Perhaps sbt/sbt-launcher-package#122 fixes this?
