### ISSUE TITLE
Reduce string duplication

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#2571]
In this project https://github.com/fommil/sbt-big-project/tree/master/src/sbt-test/sbt-big-project/clusterfsck if you run it for a while (e.g. a day's coding) you can easily generate 1GB of duplicated strings... almost all coming from the directory paths. Judicious use of `.intern()` would solve the problem, but I don't know where the creation is happening. A java agent on String allocation could probably find it no problem.

**Comment by jvican** [comment]
This is interesting, I may have a closer look to this one sometime in the future. How did you realise that 1GB of duplicated strings was created? I've wanted to add name interning to Zinc for a long time. This may be the motivation to do so.

**Comment by fommil** [comment]
Your Kit has an analysis for string dupes in a heap hump

**Comment by jvican** [comment]
I am trying to reproduce locally in a open sbt instance, but cannot find those duplicated strings. Do you tested this with a very big sbt project?
  
I would like to get a reproduction of this issue so that I can start working on it.

**Comment by fommil** [comment]
Is only relevant for huge projects. I don't work on a huge project anymore so my motivation is quite low. Try out the biggest project you can find any look at the heap size portion by String. On Windows for extra points.

**Comment by dwijnand** [comment]
By big I assume we mean in terms of number of projects. Akka and Scala.js are builds with lots of projects.

**Comment by jvican** [comment]
> By big I assume we mean in terms of number of projects. Akka and Scala.js are builds with lots of projects.
  
If this is the case I may be able to test with Scala Meta, that has over 16 projects. But no Windows.

**Comment by fommil** [comment]
VirtualBox Windows 7 image? I have one you're welcome to.
