### ISSUE TITLE
Issue warning for "broken builds"

### ISSUE THREAD

**Issue by mdedetrich** [sbt/sbt#2579]
## steps

Pull this specific version of https://github.com/scala-js/scalajs-cross-compile-example/tree/db2f78b971a49d7327bf3524d0dbd4c94d682a94
run `show scalaVersion` in SBT

Should see the following

```
[info] scalaJsonASTJS/*:scalaVersion
[info]  2.11.6
[info] scalaJsonASTJVM/*:scalaVersion
[info]  2.11.6
[info] root/*:scalaVersion
[info]  2.10.5
```
## problem

The problem is that `scalaVersion` is not the same across all of the projects, and this causes issues with tools like ensime. @fommil says that arguably these types of builds are broken, and shouldn't occur in the majority of use cases.
## expectation

Since there are some very rare corner cases where you need such builds, SBT should provide a warning if it sees that `scalaVersion` differs amongst different projects/sub-projects. Documentation should also be updated to recommend using

``` scala
scalaVersion in ThisBuild := "2.11.8"
```

In the root of the`build.sbt` (especially now since that `Build.scala` is being deprecated, which has its own ways of handling this) when using more complex setups.

If there aren't any corner cases, ideally this should be disallowed with a helpful error message.
## notes

See https://github.com/scala-js/scalajs-cross-compile-example/issues/7 and https://github.com/ensime/ensime-sbt/issues/138 for more information.

**Comment by dwijnand** [comment]
I don't think there's anything generally illegal in having in different Scala versions. It might be the wrong setup for a project, but I don't think there's anything that sbt should warn about.

That being said, documentation improvement PRs are always welcome.

**Comment by mdedetrich** [comment]
Apparently a lot of tools (like scoverage and compile plugins, @fommil can expand here) will stop working if you have the above problem. This is also true of ensime, and other IDE's apparently have to code workarounds for these types of projects.

Its its not something thats illegal but shouldn't be done typically, then I don't see any issue in showing a warning when SBT starts up (if it is illegal then it should be disallowed)

**Comment by fommil** [comment]
it's not limited to `scalaVersion`, I think it's just a general misconception about where to put shared settings in multi-project builds. Pragmatically, I know to find such breakages by looking for projects with differing `scalaVersion` (lowest common denominator), but I accept that it can be valid if that's what the author really intended (I'd always encourage people to split such projects into two).

**Comment by dwijnand** [comment]
Still doesn't sound like something that sbt should always constantly be warning about, at least to me.

**Comment by fommil** [comment]
It's almost going down the road of a validity checker of "did you really mean X?" I could see that getting annoying. In ENSIME we're ok doing this warning because almost always it means a broken build definition.

**Comment by mdedetrich** [comment]
Well the thing is, if this is being classified as "broken" then SBT itself should warn about it. If its not broken, then arguably Ensime should look into making a fix for it in the long term. A line should be cut somewhere.

> Still doesn't sound like something that sbt should always constantly be warning about, at least to me.

This is common practice in programming languages, so I am not sure why its such an issue. The whole "compile and getting a page of warnings" is something that pretty much every programmer is used to, and this would only come up when you load the project in SBT, so its not like it would be spammy.

The whole point of warnings is to give a notice to the user that "what you are doing is probably wrong, but it may be intentional if you absolutely do know what you are doing" which is where this seems to fall

**Comment by dwijnand** [comment]
Warnings are only useful if you read them, which requires not having noise. So at a minimum this requires a way to opt-out of the warning. But first I'm not 100% convinced that this is a problem in sbt, or rather a problem with the plugins.

**Comment by mdedetrich** [comment]
> Warnings are only useful if you read them, which requires not having noise.

Actually people tend to read the first instance of a warning, and then ignore it afterwards for different reasons, i.e.
- They have seen it before
- They are in a rush (must push this to production, don't care about warnings)

Or other reasons. I also think there isn't that much noise when you load SBT (ideally this is when the warning would be displayed). In any case, we should clarify what "broken" means. If the SBT guys say this is perfectly valid and is not a problem, then ensime should probably take that into account and work around it even if it does happen to be hard.

You can only claim something is broken if its not intended to work that way by the designers of the product else its an intended feature.

**Comment by fommil** [comment]
Let's keep ensime's concerns separate from this ticket. If you were to put together a PR that does what Dale is suggesting (with the opt-out for the warning), it could be reviewed and discussed in the context of sbt.

As for ensime, the evidence on our ticket is extremely strong that we detect broken builds a **lot** more than false positives, and I've had people message me to say "thanks, that fixed a bunch of other stuff with our build that always confused us". If an ensime contributor really wants to have a build with different versions of scala in sub modules (e.g. if Sebastien wanted to use ensime to hack on `scalajs-reflect`) then it's possible to use the ensime-sbt transformer feature to set up a workflow for that one project, but nobody has asked us how to do that to date.

**Comment by mdedetrich** [comment]
Well first things first, if we are going to call something "broken", it heavily implies that it shouldn't even work (and that SBT shouldn't even load the project). From the response we are getting from the SBT guys, it seems like this is a case of the build being misconfigured (at worst). Either that or its entirely intentional.

If its completely intentional then there is no point in having a warning message. If its intentional but not ideal then it should display a warning so at least users get some flag that "they are possibly doing something wrong".

In regards to ensime I also had no idea that `ensime-sbt transformer` existed, it was just consistently communicated to me that my build was broken.

**Comment by eed3si9n** [comment]
- A build is a set of subprojects that often generate some JARs.
- A subproject may support its own set of Scala versions that it cross builds. (An sbt plugin might only be built for 2.10 while you might want to run tests in 2.11 for most other subprojects.)
- A subproject may depend on other subprojects, and normally\* the Scala version should line up for the dependencies.
- Running `+compile` with vanilla sbt behaves in unexpected way. As `aggregate` takes higher precedence than `crossScalaVersions`. I fixed this using [sbt-doge](https://github.com/sbt/sbt-doge).

```
> ;so clean; such test; very publishLocal
```

*) Under some rare occasion, a subproject may depend on multiple Scala versions. See for instance sbt 1.13.9 (https://github.com/sbt/sbt/blob/v0.13.9/build.sbt#L445-L446).

**Comment by dwijnand** [comment]
@fommil where can I read about this use-case in the context of ensime? I want to understand:
- why is it looking for scalaVersion on the root project?
- what's it doing with that version?
- what happens if there's an outlier sub-project on another version (such as an sbt 0.13 plugin)?

**Comment by fommil** [comment]
It's using the scala version to know which version of ensime to use.

**Comment by dwijnand** [comment]
what happens if there's an outlier sub-project on another version (such as an sbt 0.13 plugin)?

**Comment by fommil** [comment]
ensime will use the root project version of scala. We basically don't support this, but we have support to allow the user to create a `.ensime` excluding that subproject, and it should be possible to create a custom workflow to have a `.ensime` for that one subproject using the different version of scala.

**Comment by dwijnand** [comment]
So ensime doesn't support having variant scala versions, which to be fair is a pretty rare (even sbt doesn't fully support it, given sbt-doge is needed to fix `+`).

So I'd say the build isn't "broken", it's either very niche or (more probably) miss-configured. I think this could more easily solved in sbt-ensime when running `ensimeConfig`, but I'm happy to provide a warning (with opt-out) in sbt proper, so it can inform users with miss-configured builds that aren't using ensime.

**Comment by fommil** [comment]
FYI

``` scala
      log.error(
        s"""You have a different version of scala for your build (${scalaV}) and ${project.id} (${scalaVersion.gimme}).
           |It is highly likely that this is a mistake with your configuration.
           |Please read https://github.com/ensime/ensime-sbt/issues/138""".stripMargin
      )
```

**Comment by dwijnand** [comment]
Oh right, thanks Sam.

**Comment by eed3si9n** [comment]
The Scala version of the root subproject should have no bearing on the rest of the subprojects (which themselves are allowed to be different among them).
I am closing this.
