### ISSUE TITLE
access user Configurations in autoplugin

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#2580]
Somewhat related to https://github.com/sbt/sbt/issues/2533 (which is probably a dependency of this) it would be incredibly useful to be able to provide `projectSettings` in an autoplugin for user-custom configurations.

e.g. adding an `InputTask` to `Compile`, `Test` and all `extends Test` configurations. Currently, the user always has to jump through hoops to add plugins to phases such as integration / functional tests.

**Comment by eed3si9n** [comment]
Derived task - https://gist.github.com/eed3si9n/bf561bce36ca72b5f659

**Comment by fommil** [comment]
@eed3si9n can this please be considered for the 1.0 milestone? It's one of the main reasons I don't like autoplugins (typically I end up having to manually add settings for IntegrationTests, defeating the effort of writing everything as an auto plugin in the first place). I can't get the derived tasks to do what I want.

**Comment by fommil** [comment]
suggested interface `projectConfigSettings(config: Configuration): Seq[Setting[_]]` called for everything except `Compile` (handled by `projectSettings`).

**Comment by fommil** [comment]
I was having a bad day, this is a total dupe of #2534
