### ISSUE TITLE
SBT with Nailgun

### ISSUE THREAD

**Issue by jvican** [sbt/sbt#2587]
I've seen that zinc has integration with nailgun. It would be very cool if sbt would sport this feature as well, therefore caching scala compilers and making it faster.

Is this possible?

**Comment by jvican** [comment]
This is another alternative to nailgun that is worth checking it out. https://github.com/ninjudd/drip

**Comment by dwijnand** [comment]
this can now be built with sbt's server, and a thin client (https://github.com/sbt/sbt/issues/3915)
