### ISSUE TITLE
Stuck at "Getting org.scala-sbt sbt 0.13.11"

### ISSUE THREAD

**Issue by LaoDaGe** [sbt/sbt#2602]
Run `sbt` stuck at "Getting org.scala-sbt sbt 0.13.11"
## Steps
1. Install [sbt-0.13.11](https://dl.bintray.com/sbt/native-packages/sbt/0.13.11.2/sbt-0.13.11.2.msi) on Windows
2. Run `sbt --version` in console
## Problem

Output `Getting org.scala-sbt sbt 0.13.11`
It seems still need to downoad  `org.scala-sbt sbt 0.13.11`, that doesn't make sense.
Is SBT an acronym of Stupid Baby Tool ?
## Expectation

Please use your brain to think,please.

**Comment by eed3si9n** [comment]
Maybe you're behind a firewall that's preventing download of https?
Try `-Dsbt.repository.secure=false`.
