### ISSUE TITLE
semicolon separated commands no longer working in 0.11.1

### ISSUE THREAD

**Issue by ghost** [sbt/sbt#261]
we used to be able to do this in 0.10.0:
`; clean ; compile`
this now results in
`; clean ; compile
; clean ; compile
[error] Expected end of input.
[error] clean 
[error]      ^`

**Comment by retronym** [comment]
Workaround is to remove the interstitial whitespace.

> ;clean;compile
> [success] Total time: 0 s, completed 08/11/2011 7:02:52 PM
> [info] Updating {file:/C:/code/scratch/xjc/}default-54ea66...
> [info] Resolving org.scala-lang#scala-library;2.9.1 ...
> [info] Done updating.
> [success] Total time: 0 s, completed 08/11/2011 7:02:53 PM

**Comment by ghost** [comment]
thx, will use that for the time being
