### ISSUE TITLE
todo: Codacy issues on 1.0.x

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2611]
Currently there are some issues reported by Codacy (https://www.codacy.com/app/eed3si9n/sbt/dashboard) on code style and error prone category.
I've excluded scripted directory, but if things get included back again, we can ignore them.

For example, Codacy says "Fatal exception is being caught" in main-command/src/main/scala/sbt/Watched.scala.

**Comment by dwijnand** [comment]
I'll take care of this.

**Comment by dwijnand** [comment]
@eed3si9n Did you use a code standard setting in https://www.codacy.com/app/eed3si9n/sbt/dashboard ? If not, could you export and share your settings please? I'm trying to mirror your setup, thanks.

**Comment by eed3si9n** [comment]
@dwijnand https://gist.github.com/eed3si9n/c80926386de6ce174e31b7a419b988d4

**Comment by dwijnand** [comment]
Looks like codacy's import doesn't work.. getting "Unsupported format".

**Comment by eed3si9n** [comment]
@dwijnand Works for me using the file I downloaded and picking "Codacy" format.
Did I copy-paste the JSON incorrectly?

**Comment by dwijnand** [comment]
I tried the updated gist.. still nothing. `¯\_(ツ)_/¯`

Here's what it looks like:

![Unsupported format](http://i.imgur.com/rKc4exI.png)

**Comment by dwijnand** [comment]
https://github.com/sbt/sbt/pull/2655

**Comment by eed3si9n** [comment]
Where it says "Brakeman" change it to "Codacy".

**Comment by dwijnand** [comment]
Doh! Worked. Thanks.
