### ISSUE TITLE
[sbt 1.0] todo: Migrating to sbt-datatype

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2612]
All case classes in the public API should be replaced with using sbt-datatype.

**Comment by dwijnand** [comment]
I'm kind of 👎 this. I don't want every data type in the API (for which some APIs there are many, see [lm](https://github.com/sbt/librarymanagement/tree/138787f55e5fbcbeac751196b000855ff6ba1625/librarymanagement/src/main/scala/sbt/librarymanagement)) to be coded in JSON.

To this end I experimented a few months ago with an alternative to case classes that dealt with binary compatibility, using a macro-annotation instead: https://github.com/dwijnand/dataclasses.

_Note_: dataclasses isn't ready yet, it only supports some initial features.

**Comment by eed3si9n** [comment]
As shown in Gigahorse, we can generate straight into `src` for source browsing purpose.

**Comment by dwijnand** [comment]
Right, I'd forgotten.

[This](https://github.com/eed3si9n/gigahorse/blob/65574172c1195156def56e97c1f85287621d23f6/core/src/main/scala/gigahorse/Config.scala#L70-L71) is perhaps a bit much, and I'm still authoring it in JSON, but at least I can read the code once it's generated, instead.

**Comment by eed3si9n** [comment]
This is done
