### ISSUE TITLE
AddSettings must not be internal._, because it is used in public APIs

### ISSUE THREAD

**Issue by sjrd** [sbt/sbt#2617]
Similarly to #2616, `sbt.internal.AddSettings` should not be internal, as it is used in the public method `Project.settingSets`.

**Comment by eed3si9n** [comment]
Do you guys use `settingSets(..)`? It's one of the features that I don't know if we should keep or drop.

**Comment by sjrd** [comment]
No, we do not use it. We only have a forwarder for it in `CrossProject`: https://github.com/scala-js/scala-js/blob/v0.6.9/sbt-plugin/src/main/scala/scala/scalajs/sbtplugin/cross/CrossProject.scala#L264-L270

I'm equally fine if you drop it, in which case we'll drop our forwarder.

**Comment by dwijnand** [comment]
Given this comment in `Load.loadTransitive`:

> ... the SettingSet API should be deprecated/removed with sbt 1.0

https://github.com/sbt/sbt/blob/v1.0.0-M4/main/src/main/scala/sbt/internal/Load.scala#L524

Maybe we should just remove it.

@eed3si9n are you happy to go with that decision?

**Comment by eed3si9n** [comment]
@dwijnand Yes. Let's drop it.
