### ISSUE TITLE
Consider merging sbt-cross-building

### ISSUE THREAD

**Issue by jroper** [sbt/sbt#2619]
With binary compatibility breaking in sbt, many core sbt plugins will probably want to cross build against both 0.13 and 1.0.  [sbt-cross-building](https://github.com/jrudolph/sbt-cross-building) is an existing project that does this, and the possibility of merging it into sbt has already been discussed (over 3 years ago) [here](https://github.com/jrudolph/sbt-cross-building/issues/17).

I'd like to reinitiate that discussion, I think having sbt cross building support in sbt 1.0.x itself will greatly help in facilitating the move.

That said, sbt-cross-building will probably, in the short term, have to also be updated to be able to cross build against sbt 1.0.x, since the really core projects that everything depends on (eg, sbt-bintray, sbt-pgp, sbt-git, sbt-release, sbt-buildinfo) all depend on each other, and won't be able to upgrade to sbt 1.0.x for their own builds until they're all cross built.

cc @jrudolph

**Comment by eed3si9n** [comment]
We've broken source compatibility too, so I am not sure if cross building is possible without some #IFDEF macro kind of a thing.

**Comment by jroper** [comment]
That's ok, that's what `src/main/scala-sbt-0.13` etc is for, any source compatibility breakages can be put behind a trait that's implemented in the sbt version specific directories.

**Comment by eed3si9n** [comment]
The change would need to happen on almost all sources, but this morning @jrudolph reminded me of the possibility of a shim library, which probably would make source compat possible for many of the plugins.

**Comment by dwijnand** [comment]
aka sbt-compat

**Comment by dwijnand** [comment]
Please note that, thanks to the efforts by @jroper and @jrudolph, sbt-cross-building has received recent updates in preparation for sbt 1:

* https://github.com/jrudolph/sbt-cross-building/pull/34
* https://github.com/jrudolph/sbt-cross-building/pull/35

The issue on the sbt-cross-building side for 1.0 support is https://github.com/jrudolph/sbt-cross-building/issues/33

**Comment by eed3si9n** [comment]
Now that sbt 1.0.0-M5 is out and I'm cross building a few plugins from 0.13, I find sbt-cross-building to be extremely useful (mine is locally patched with https://github.com/jrudolph/sbt-cross-building/pull/36). Using sbt-cross-building, I can keep the plugin source intact from 0.13 and cross publish.

The milestone "1.0.0" could be interpreted as "before 1.0.0 ships", but if we port this it should be ported to **0.13** and 1.0.0. The quaint thing about sbt-cross-building is that it uses `sbt.Plugin` (perhaps for 0.12 compatibility) you have to add crossBuildingSettings, so I'd migrate that to an `AutoPlugin` named `CrossPluginPlugin` or something.
