### ISSUE TITLE
No javaOptions set in run from build.sbt

### ISSUE THREAD

**Issue by AmazingDreams** [sbt/sbt#2622]
## Steps

I have the following in my build.sbt:

``` scala
lazy val root = (project in file(".")).enablePlugins(PlayScala)

scalaVersion := "2.11.8"

resolvers += "scalaz-bintray" at "http://dl.bintray.com/scalaz/releases"

fork in Test := true
fork in run := true

javaOptions in Test ++= Seq("-Dconfig.resource=testing.conf")
javaOptions in run ++= Seq("-Dconfig.resource=development.conf")
```

This should set my run and Test to fork and use specific configuration files. I got a service which tries to read a specific configuration value and it throws an exception if not present.
## Problem

Test forks fine and uses the testing.conf configuration file. The tests run fine without the service throwing an exception.

The `run` command however does not seem to set the `config.resource` property. The configuration value is not read and my service throws it's exception. When I try to log the value through `System.getProperty("config.resource")` nothing is contained there. 

Now when I run `run "-Dconfig.resource=development.conf"` it works fine and the configuration is loaded.
## Expectation

I expected the `config.resource` property to be set.
## Notes

I have used this setup many many times though for some reason unknown it doesn't work now. I tried to replicate the exact setup by setting scala version, play framework version etc to the other projects' values to no avail.

Let me know if you need any more information.

**Comment by AmazingDreams** [comment]
Should have mentioned `sbt.version=0.13.11`

**Comment by TeraWilliam** [comment]
I believe the recommended approach is:

```scala
PlayKeys.devSettings += "key" -> "value"
```

**Comment by AmazingDreams** [comment]
@ScalaWilliamTeralytics thanks that seems to have worked

```scala
PlayKeys.devSettings += "config.resource" -> "development.conf"
```
