### ISSUE TITLE
watchSources is not scoped to task

### ISSUE THREAD

**Issue by scf37** [sbt/sbt#2623]
## steps

```
watchSources in Compile := sourceDirectories.in(Compile).value
~compile
```
### related to steps above

When I modify tests, sbt triggers recompilation while compilation does NOT depend on test sources.
### in general

I want to configure `watchSources` on task level, e.g. to run application using sbt-revolver's `re-start` and then write and execute tests against running application. Problem is changes to tests (which belong to the same project) trigger applicaton restart which is not desirable.
## expectation

changes to tests will not trigger re-compilation
## notes

Sbt is designed to be stateless - why "triggered execution feature" can not examine tasks to find out exact set of files this task depend on?

**Comment by eed3si9n** [comment]
I think this is now fixed in the latest sbt 1.3.x series.
