### ISSUE TITLE
project/project.sbt and macro extractor for Projects

### ISSUE THREAD

**Issue by acdenhartog** [sbt/sbt#2624]
#### problem

More easy transition away from `Build.scala` is needed.
Some people _really_ do not want build files in the root directory.
`build.sbt` file looks silly and is an extra point of failure for those preferring `.scala`
#### proposed solution

`project/project.sbt` to keep the root clean (should be easy to implement)
`includeProjectsFrom(...)` macro to extract from arbitrary classes (mostly implemented below)
### The long verison:

I only just found out about deprecating `Build.scala`. Incidentally I had been screwing around in the [dotty](https://github.com/lampepfl/dotty) a bit lately and they also use `Build.scala` style, which I personally prefer as well.

I decided to do [the minimal update required](https://github.com/sbt/sbt/pull/2524#issuecomment-214068994) for their SBT file to move away from `Build.scala`. (better for me to do it than one of them spending time on it)

Essentially nothing is lost in the removal of `Build.scala`; but as [soc was asking about repeatedly](https://github.com/sbt/sbt/pull/2524#issuecomment-203796170): how do we keep build files out of the root directory?

I have come up with a possible compromise solution: `project/project.sbt` which should function _exactly identical_ to `root/build.sbt`. All that is required if for SBT to find that file then pretend that it is still in the root directory to avoid the error from `project.in(file(".."))`. That should just work right?

I think this would be nice because it puts all the SBT files into the same folder. And the naming seems more obvious since `project/build.sbt` is referring to the build _itself_ and `project/project.sbt` refers to the project. It also seems more natural for a file like `project/DottyBuild.scala` to be directly in scope from `project/project.sbt` because they are just in the same folder.

And if this becomes standard you no longer have people (like me) getting confused about what the difference is between `build.sbt` depending on which folder you put it in.

Anyway, I did the transformation in the dotty repository, but I am not going to make a pull request any time soon, largely because:

``` scala
def y = DottyBuild
val s = y.dotty
val b = y.`dotty-bench`
val t = y.`dotty-interfaces`
val ? = y.sjsSandbox
inThisBuild(y.thisBuildSettings)
```

That is what perfectly valid `build.sbt` looks like now. It is not wrong per say, but really. yuck.

This also means that if you want to add another project in a `.scala` you now have to edit two different files.

So my other suggestion is this: use a macro function that just takes any object and extracts all vals that are Projects. So in that case of dotty: `project/project.sbt` could become:

``` scala
includeProjectsFrom(DottyBuild)
inThisBuild(DottyBuild.thisBuildSettings)
```

Where DottyBuild could be an almost completely arbitrary Scala reference.
### I have written a macro to implement _one part_ of this: [gist here]()

It is not really elegant since it uses a reflective call due to: either a bug in the compiler or my ignorance of some arcane macro functions. But it should be quite robust and fast enough since those reflective call are safe and only made once per Project that is found. Perhaps somebody can make it better, or just leave it until scala.meta.

(and it only just dawned on me that "compile-time" for SBT scripts is essentially run-time: i.e. type-level magic saves no time; what a strange program you guys have created.)

The part that is still missing is an implementation of  `includeProject(project:Project)`, but I obviously have no idea how that should be done. If an `includeProject` method is somehow not possible, then a more complicated (and likely fragile) macro is needed to generate valDefs. It does not matter to me if `includeProject` itself becomes public API or is just an internal method.

`includeProject` would, like those arbitrarily named vals above, allow one to easily comment out a whole projects. Another arguably better way to get "comment it out flexibility" is defining Projects and settings in traits and then:

``` scala
includeProjectsFrom(
    new AnyRef
    with SubBuild1
    with SubProject2
    with ExtrasForSubProject2
    with SJSModule
)
```

Here `ExtrasForSubProject2` may not contain any new Project itself but can also be easily toggled. Such things could already be done, but I think the extractor macro makes it easier an less human-error prone.

Unfortunately, I have not been able to test this macro on an _actual SBT build_ because of some issues with Ivy, not having the right Java/Scala versions installed, and hitting various strange errors etc.

(insertion point for macro would be at the bottom of this file: [`main\src\main\scala\sbt\Project.scala`](https://github.com/sbt/sbt/blob/1.0.x/main/src/main/scala/sbt/Project.scala#L617))

I would welcome any and all comments and suggestions.
Maybe somebody knows what is going on with all those 'wrong' methods listed in that gist...

(i do not know if anyone else was working on the "rewrites for existing `Build.scala`" issue)

**Comment by eed3si9n** [comment]
`project/project.sbt` won't work as it is the build script for the meta-build, which most people know as `project/plugins.sbt`.

**Comment by acdenhartog** [comment]
**edit:** _warning:_ contains basic misunderstandings of sbt project structure see next comment

Could have sworn I read the documentation at some point... apparently not much.
So just to be clear, it goes like this:

(`project/plugins.sbt`∨`project/project.sbt`)=>(`project/__.sbt`)=>(`root/__.sbt`)

And each layer sets things up (enables macros?) for the next? And after that last compilation it runs a resulting program? Or have I gotten this all completely wrong?

Introducing _even more names_ seems undesirable. Allowing any arbitrary name that is not already taken in `project/` might work, but you can count on people calling it `project.sbt` sometimes and getting confused.

How about: `project/sbt.sbt` :skull:

Or `gradle.sbt` or `make.sbt` or `not.sbt` or `co-meta-build.sbt` or `magic.sbt` or just `.sbt`

Or maybe add this completely alternative pathway:
(`build/plugins.sbt`)=>(`build/build.sbt`)=>(`build/project.sbt`)

On the other hand, do you think that missing internal method (`includeProject`) in my macro could be done easily? It seem there is already a way to extract `Setting` _expressions_, given that hook exists it should not be necessary to introduce valDefs. But with that I am extra certainly out of my depth...

(and maybe I should add this because it all seems so negative: I think you guys have been doing great work and SBT has gotten so much better in the last few versions. I was using Gradle for quite a while but am glad I gave SBT another chance. Sorry if I am a bit frustrating to deal with.)

**Comment by acdenhartog** [comment]
Okay, so having actually read some more of the docs it seems the sequence is just:
(`root/project/__.sbt`)=>(`root/__.sbt`) where is `__` any number of files of any name.

And there is _nothing special_ about files named: `plugins.sbt`/`project.sbt`/`build.sbt`.

> `project/project.sbt` won't work as it is the build script for the meta-build,
> which most people know as `project/plugins.sbt`.

This seems to be "technically" false, or at least misleading: it is not _the_ build script for the _meta-_build, it is just _a_ build script in the _meta-meta-_build. I am merely echoing [what this documentation says](www.scala-sbt.org/1.0/docs/Organizing-Build.html).

So in fact `project/project.sbt` could still be used:
- If there exists no `root/__.sbt` look for a `root/project/project.sbt` instead.
- And for meta-meta-build: if the root directory contains no `.sbt` files: ignore `project.sbt`.

This only breaks down in the corner case where some _wants_ to use `project/project.sbt` for a meta-meta-build but _also_ does not define any meta-build. (so no `root/__.sbt`)

Which is to say: everything I said in the original issue should still hold.

**Comment by eed3si9n** [comment]
Going back to the first problem statement,

> Some people really do not want build files in the root directory.
> build.sbt file looks silly and is an extra point of failure for those preferring .scala

Ultimately, I don't see this as a big problem for sbt 1.0.
What I want from sbt 1.0 is fewer ways of writing build definition, not more, so it's easier to document and learn. If you want to push majority of the build logic to `project/X.scala` that's up to you, but I have no intention of providing a way of removing `build.sbt`.

I would encourage you provide further feedback on this, but before jumping into the solution space, I think both of our times would be better spent if we first agree on the problem space on forums like sbt-dev list. (See also https://github.com/sbt/sbt/blob/1.0.x/CONTRIBUTING.md#where-to-get-help-andor-file-a-bug-report)

**Comment by acdenhartog** [comment]
> but I have no intention of providing a way of removing build.sbt.

I did not suggest removing `build.sbt`, but optionally moving it out of the root directory; and into a place that I think makes more sense anyway.

> so it's easier to document and learn.

I do not see how the current folder structure is helpful in that regard. There is nothing at all intuitive about having half of the build description in `root/__.sbt` and the other half in `project/__.scala`.

Just consider how Scala and Java behave: you could literally put them into any directory structure, it is only the package statements at the top that define how things are connected. But nobody does that because it is confusing. But really my point is: directory structure does not change behavior.

But in SBT which folder you put things in determines everything. Binding a _file name_ onto a specific function is a relatively normal thing to do. Even in SBT documentation the files are often called `root/build.sbt` and `project/build.sbt` which have the same name; that is just pointlessly confusing. I get that it makes sense _to SBT developers_, but who else really needs to think about build definitions recursively?

I bet it would be easier for beginners to learn: you _must_ call the project definition exactly `project/project.sbt`, and all other `.sbt` files go in that same place. One can still use the original structure if more than one `root/__.sbt` file is really needed. Though just look at your own repository: so many `.scala` build files, but you really need _only one_ `root/build.sbt`.

> I don't see this as a big problem for sbt 1.0.

The thing is that _now_ is when you are deprecating `Build.scala`, so if there is _ever_ going to be good time to introduce changes to structure this is it.

> What I want from sbt 1.0 is fewer ways of writing build definition, not more

Look, I agree with that. And I just came up with a line of argument that might convince you:

The way `.sbt` basically works is you force people to define Projects directly into a val. That is good, it gives you nice possibilities with static analysis.

Perhaps you could add another constraint: if people define a Project in `.scala` code, _force_ them to use `includeProjectsFrom` or something like that. And why? Because it is a macro in which you can make sure nothing weird happens.

Somewhat contrived but consider this pathological but valid `.sbt` that brings in projects from `.scala`:

``` scala
val myProject = if(isWeekend) Weekend.getProject else Work.getProject 
```

Pulling out projects manually is one more layer of opportunity to create non-deterministic builds.

If a macro like the one above is used you could _enforce_ that the origin of the Project is the same val on which is was first defined. (i.e. extracted method must have the same full name as that from which the project gets its own name)

Perhaps implementing some of those guarantees is not worth doing right now, but you could at least make sure that _while_ people have to rewrite they use a method on which you could enforce such constraints later.

> both of our times would be better spent if we first agree on the problem space

Unfortunately my time now is better spent doing student stuff because of exams soon.
But sorry for missing that rule about submitting issues here.
Although I do really dislike using Google groups.

Anyway, no more long posts from me for a while.
