### ISSUE TITLE
Wrong value being added to path variable on installation

### ISSUE THREAD

**Issue by gauravmokhasi** [sbt/sbt#2626]
## steps

Install SBT from http://www.scala-sbt.org/download.html.
Open cmd and run "sbt sbt-version".
You will get error "sbt is not recognized as an internal..."
## problem

C:\Program Files (x86)\sbt\\bin being added to path variable instead of C:\Program Files (x86)\sbt\bin
## expectation

Set path variable automatically to C:\Program Files (x86)\sbt\bin
## notes/resolution

When you go and change the path variable and restart cmd, "sbt sbt-version" works fine. I also added the path to JRE bin to the path variable (path to JDK bin was already existing).

**Comment by dwijnand** [comment]
> C:\Program Files (x86)\sbt\bin being added to path variable instead of C:\Program Files (x86)\sbt\bin

That's "C:\Program Files (x86)\sbt\bin", twice.

Also, I believe there was an issue with how the path was set for Windows that we've since resolved. So I think this can be closed. Please reopen if I'm mistaken.
