### ISSUE TITLE
Where does sbt artifacts goes? no version larger than 0.13.9

### ISSUE THREAD

**Issue by wpc009** [sbt/sbt#2627]
(See the guidelines for contributing, linked above)
## problem

I thought that the sbt repo is located at  `http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/`.
But after upgrading to `0.13.11` , I got some unresolved dependency error. 
It seems that sbt version larger than `0.13.9` does not exists in that repo .
Where can I find the `0.13.11` version of sbt ?

**Comment by eed3si9n** [comment]
Could you try again?
- http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.11/
- https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.11/

both http and https work for me.

**Comment by wpc009** [comment]
There's no `0.13.11` folder under this link `http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/`. When I start sbt, it complains could not found `0.13.11`, and it already tried the typesafe repo.

**Comment by wpc009** [comment]
Sorry, my fault. My private artifactory proxy need authentication. I didn't notice that `sbt` needs additional `SBT_CREDENTIALS` env or boot args to specify the credential property file. 
It's working now. 
But the [link](http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/)     show no greater version than `0.13.9`, that's strange.
