### ISSUE TITLE
Publish SNAPSHOT on commit on master

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2638]
Instead of nightly build, publish on commit from Travis CI.

**Comment by dwijnand** [comment]
I agree, duplicate of #2376?

**Comment by eed3si9n** [comment]
#2376 says timestamped. I'm thinking more like per commit as suggested by Miles on Gitter chat.
https://gitter.im/sbt/sbt?at=575716ee07e77197794ffb1a

**Comment by dwijnand** [comment]
Timestamped doesn't mean nightly. But anyways the intent is the same, except I prefer timestamps, but we can also just do both.

**Comment by eed3si9n** [comment]
I'll close this and comment there.
