### ISSUE TITLE
-Xlint warnings and -Werror errors are not being parsed or shown

### ISSUE THREAD

**Issue by iadcode** [sbt/sbt#2639]
## steps

1) In my build.sbt, I put this:

``` scala
libraryDependencies += "xalan" % "xalan" % "2.7.2"

lazy val project = (project in file("."))
  .settings(
    javacOptions ++= Seq("-Xlint", "-Werror"),
  )
```

2) From SBT, I run this:

``` bash
$ sbt clean compile
```

3) xalan 2.7.2 has a `Class-Path:` entry in its MANIFEST file. Since xalan has been resolved as a managed dependency, the jars listed in the `Class-Path:` entry cannot be located. This becomes a warning due to `-Xlint:path`, and an error due to `-Werror`

```
warning: [path] bad path element "C:\Users\abc\.ivy2\cache\xalan\xalan\jars\xercesImpl.jar": no such file or directory
warning: [path] bad path element "C:\Users\abc\.ivy2\cache\xalan\xalan\jars\xml-apis.jar": no such file or directory
error: warnings found and -Werror specified
```
## problem

In SBT 0.13.7, we see this when we execute the sbt command:

```
[error] warning: [path] bad path element "C:\Users\abc\.ivy2\cache\xalan\xalan\jars\xercesImpl.jar": no such file or directory
[error] warning: [path] bad path element "C:\Users\abc\.ivy2\cache\xalan\xalan\jars\xml-apis.jar": no such file or directory
[error] error: warnings found and -Werror specified
[error] 1 error
[error] 2 warnings
[error] (silk/compile:compile) javac returned nonzero exit code
[error] Total time: 17 s, completed 10/06/2016 3:14:07 PM 
```

But in 0.13.11, we get this:

```
[error] (silk/compile:compile) javac returned nonzero exit code
[error] Total time: 17 s, completed 10/06/2016 3:14:07 PM 
```

That is, the warnings and errors are not shown.

This left us scratching our heads as to why our build is failing. We had to revert from 0.13.11 to 0.13.7 to be able to fix our `-Xlint` configuration problem.
## expectation
- That sbt parses and shows `-Xlint` warnings and `-Werror` errors correctly.
## notes
- This issue looks semi-related to #2256, especially with regards to @shajra-cogscale's comments.

**Comment by SethTisue** [comment]
in sbt 1.9.6, if I change `lazy val project` to `lazy val myproj` and add a Java source file at the root level just to be sure (`J.java` containing `public class J { }`), `sbt clean compile` succeeds. Closing as not currently reproducible.

Perhaps some further adjusted reproduction would demonstrate the same underlying issue? But in any case, I leave it up to others to supply an updated reproduction if there is one.
