### ISSUE TITLE
extracted.append is not sticky but `:: state` is

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2641]
Initially found by @szeiger 
## steps

``` scala
lazy val root = (project in file(".")).
  settings(
    inThisBuild(List(
      scalaVersion := "2.11.8",
      organization := "com.example"
    )),
    name := "hello-world",

    commands += Command.command("hi") { state =>
      val extracted: Extracted = Project.extract(state)
      extracted.append(
        (name ~= {_ + "1"}) ::
        Nil, state)
    },
    commands += Command.command("hello") { state =>
      """set name :=  name.value + "1" """ :: state
    }
  )
```

Run `hi` command twice, and then run `name`
## problem

```
hello-world1> name
[info] hello-world1
```

I'm not sure if there's a problem in `Project.extract(state)` or `extracted.append`, but the `name` is calculated off of the state from `build.sbt`.
## expectation

```
hello-world11> name
[info] hello-world11
```
## notes

It works for `hello` command that uses `:: state`.
Shouldn't the new state returned by `extracted.append` stick around?

**Comment by dwijnand** [comment]
fixed with https://github.com/sbt/sbt/pull/3865 in 1.1.1
