### ISSUE TITLE
AutoPlugin additionalProjects

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2645]
As transition path from `sbt.Build`, consider defining the following method to AutoPlugin:

``` scala
def additionalProjects: List[Project]
```
## expectation

When an auto plugin is enabled, it adds `additionalProjects` to the build.
## notes

I'm not 100% sure if this feature is feasible. By the time auto plugins are enabled per subprojects, Load should know the list of subprojects already.

**Comment by dwijnand** [comment]
@eed3si9n is this a duplicate of #2532?

**Comment by dwijnand** [comment]
I'm going to close this as duplicate of #2532, let me know what I'm missing if I'm wrong.
