### ISSUE TITLE
batch-mode operation: prompt-me-not

### ISSUE THREAD

**Issue by retronym** [sbt/sbt#265]
Just ended up with a 31GB log file on our build server full of:

```
Project loading failed: (r)etry, (q)uit, or (i)gnore? Invalid response.
```

Can you add a system-property to disable such prompting? 

This should be exposed to plugins.

**Comment by harrah** [comment]
`sbt < /dev/null` is the recommended way to run sbt on a build server.

**Comment by softprops** [comment]
ha. clever.

**Comment by paulp** [comment]
Alternatively, https://github.com/paulp/sbt-extras (now) accepts -batch to accomplish the same.

**Comment by quelgar** [comment]
What is the solution for Windows? I tried changing my launch batch file to:

java [sbt jar etc] < NUL

but I still get the "Project loading failed" prompt.

**Comment by pfn** [comment]
Need this for scripted-tests as well since project loading failure results in the test case just sitting there...

**Comment by mikla** [comment]
@quelgar +1
Have you found solution for Windows?
I have tried `sbt command > NUL` without any success, it't not showing "Project loading failed" but it's still waiting interaction from user.

**Comment by quelgar** [comment]
I "solved" it by making more Linux build agents.

**Comment by jameskoch2** [comment]
I bumped into this today on a Windows build agent. @mikla did you ever come up w/ a Windows solution? Is it fair game to reopen this defect given if there's no good Windows work-around?

**Comment by dwijnand** [comment]
> What is the solution for Windows? I tried changing my launch batch file to:
> 
> java [sbt jar etc] < NUL
> 
> but I still get the "Project loading failed" prompt.

Given this answer https://stackoverflow.com/a/313115/463761 (by Jon Skeet no less) it's strange that doesn't work. I wonder if perhaps the JDK on Windows with `< NUL` doesn't behave the same as `< /dev/null` on Unix-like platforms.

**Comment by dwijnand** [comment]
Perhaps the solution is to use `javaw`? See `javaw` in https://docs.oracle.com/javase/8/docs/technotes/tools/windows/java.html.
