### ISSUE TITLE
Unable to reparse org.apache.flink#flink-parent;1.1-SNAPSHOT from

### ISSUE THREAD

**Issue by joan38** [sbt/sbt#2650]
Hi,

When I `update` I get those looping warnings:

```
[warn] Unable to reparse org.apache.flink#flink-parent;1.1-SNAPSHOT from drivetribe.remote, using Wed Jun 22 14:32:19 BST 2016
[warn] Unable to reparse org.apache.flink#flink-parent;1.1-SNAPSHOT from apache.snapshots, using Wed Jun 22 04:59:34 BST 2016
[warn] Sorrting results from org.apache.flink#flink-parent;1.1-SNAPSHOT, using Wed Jun 22 04:59:34 BST 2016 and null
[warn] Sorrting results from org.apache.flink#flink-parent;1.1-SNAPSHOT, using Wed Jun 22 14:32:19 BST 2016 and null
[warn] Choosing drivetribe.remote for org.apache.flink#flink-parent;1.1-SNAPSHOT
[warn] Unable to reparse org.apache.flink#flink-scala_2.11;1.1-SNAPSHOT from drivetribe.remote, using Wed Jun 22 14:32:18 BST 2016
[warn] Unable to reparse org.apache.flink#flink-parent;1.1-SNAPSHOT from drivetribe.remote, using Wed Jun 22 14:32:31 BST 2016
[warn] Unable to reparse org.apache.flink#flink-parent;1.1-SNAPSHOT from apache.snapshots, using Wed Jun 22 04:59:34 BST 2016
[warn] Sorrting results from org.apache.flink#flink-parent;1.1-SNAPSHOT, using Wed Jun 22 04:59:34 BST 2016 and null
[warn] Sorrting results from org.apache.flink#flink-parent;1.1-SNAPSHOT, using Wed Jun 22 14:32:31 BST 2016 and null
[warn] Choosing drivetribe.remote for org.apache.flink#flink-parent;1.1-SNAPSHOT
[warn] Unable to reparse org.apache.flink#flink-scala_2.11;1.1-SNAPSHOT from apache.snapshots, using Wed Jun 22 05:03:23 BST 2016
[warn] Sorrting results from org.apache.flink#flink-scala_2.11;1.1-SNAPSHOT, using Wed Jun 22 05:03:23 BST 2016 and null
[warn] Sorrting results from org.apache.flink#flink-scala_2.11;1.1-SNAPSHOT, using Wed Jun 22 14:32:18 BST 2016 and null
[warn] Choosing drivetribe.remote for org.apache.flink#flink-scala_2.11;1.1-SNAPSHOT
[warn] Unable to reparse org.apache.flink#flink-parent;1.1-SNAPSHOT from drivetribe.remote, using Wed Jun 22 14:32:54 BST 2016
[warn] Unable to reparse org.apache.flink#flink-parent;1.1-SNAPSHOT from apache.snapshots, using Wed Jun 22 04:59:34 BST 2016
[warn] Sorrting results from org.apache.flink#flink-parent;1.1-SNAPSHOT, using Wed Jun 22 04:59:34 BST 2016 and null
[warn] Sorrting results from org.apache.flink#flink-parent;1.1-SNAPSHOT, using Wed Jun 22 14:32:54 BST 2016 and null
[warn] Choosing drivetribe.remote for org.apache.flink#flink-parent;1.1-SNAPSHOT
[warn] Unable to reparse org.apache.flink#flink-core;1.1-SNAPSHOT from drivetribe.remote, using Wed Jun 22 14:32:54 BST 2016
[warn] Unable to reparse org.apache.flink#flink-parent;1.1-SNAPSHOT from drivetribe.remote, using Wed Jun 22 14:33:04 BST 2016
[warn] Unable to reparse org.apache.flink#flink-parent;1.1-SNAPSHOT from apache.snapshots, using Wed Jun 22 04:59:34 BST 2016
[warn] Sorrting results from org.apache.flink#flink-parent;1.1-SNAPSHOT, using Wed Jun 22 04:59:34 BST 2016 and null
[warn] Sorrting results from org.apache.flink#flink-parent;1.1-SNAPSHOT, using Wed Jun 22 14:33:04 BST 2016 and null
[warn] Choosing drivetribe.remote for org.apache.flink#flink-parent;1.1-SNAPSHOT
...
```

This makes SBT unusable as it's extremely slow.

The affected versions are 0.13.11 and 0.13.10 only, it works well with 0.13.9

Cheers

**Comment by eed3si9n** [comment]
SNAPSHOT is slow because to guarantee it's using the latest it needs to check all the resolvers.
You can try disabling this behavior as follows:

``` scala
updateOptions := updateOptions.value.withLatestSnapshots(false)
```

In general I don't recommend using SNAPSHOTs unless you're doing a quick integration test  locally.

**Comment by joan38** [comment]
Thanks for the disable config option.

But surely there is something going wrong as it says "Unable to reparse org.apache.flink" in a warning.
Is this the expected behavior? Why did it change from 0.13.10?

Thanks

**Comment by richard77** [comment]
FYI, running into same problem with sbt 0.13.12
Any scheduled work on this issue? I've done some googling around and find more people having this issue. It hinders the development work. Disabling the use of snapshots is not always the solution..

**Comment by caoilte** [comment]
Documentation on 

`updateOptions := updateOptions.value.withLatestSnapshots(false)`

http://www.scala-sbt.org/1.0/docs/sbt-0.13-Tech-Previews.html#Latest+SNAPSHOTs

There doesn't seem to be any downside to setting it to false if you only ever work with local SNAPSHOTs. 

What I don't understand is why if this feature was introduced in 0.13.6 it didn't become a problem until 0.13.10.

**Comment by eed3si9n** [comment]
This setting flip flopped a bit:
- https://github.com/sbt/sbt/pull/1520 (true)
- https://github.com/sbt/sbt/pull/1683 (false)
- https://github.com/sbt/sbt/pull/2313 (true) 0.13.11 - http://www.scala-sbt.org/0.13/docs/sbt-0.13-Tech-Previews.html#sbt+0.13.11

**Comment by SoboLAN** [comment]
I have the same issue after upgrading to `0.13.12`.

Are there any news about this?

**Comment by jvican** [comment]
I've addressed this issue here: https://github.com/scalacenter/librarymanagement/commit/ecbb20b55ee14bc252549dbb9d143719f60f021b. Previously, we were showing these logs for all the failures that could happen while re-fetching module descriptors for SNAPSHOTs.
  
My commit only warns on parser errors now, and it will add as debug information other reasons that could have happened these annoying bugs in your sbt logs: resources with other implementations, missing descriptor in resolver, etc.
  
For the record, the underlying snapshot resolution has not changed, but only how the logs are handled. If you still want to address the fact that SNAPSHOT resolution is slow, pick one:
  
1. Disable `latestSnapshots` and only work locally with SNAPSHOTs.
2. For God's sake, use a versioning scheme based on git information. Sbt-dynver (https://github.com/dwijnand/sbt-dynver) gives a good example of how it looks like.

**Comment by joan38** [comment]
@jvican Looks good thanks.
You can add a 3rd option that is:

3. Use [sbt-coursier](https://github.com/coursier/coursier) because life is too short to waist in artifact fetching.

**Comment by jvican** [comment]
Yes, and the best option. But the nondeterminism of snapshots is still there. Avoid snapshots. If you can't, I would say you have a tooling problem.
