### ISSUE TITLE
Option to turn off the new macro recompilation info message

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2654]
Ref #2614 #2637

@milessabin wrote:

> With 0.13.12-RC1 I'm getting a lot of output of the form,

```
[info] Because /home/miles/projects/shapeless/core/src/main/scala/shapeless/typeable.scala contains a macro definition, the following dependencies are invalidated unconditionally:                                                                                                     
[info]  /home/miles/projects/shapeless/core/jvm/target/scala-2.12.0-M5/src_managed/main/shapeless/tupletypeables.scala                      
[info]  /home/miles/projects/shapeless/core/src/main/scala/shapeless/alacarte.scala                                                         
[info]  /home/miles/projects/shapeless/core/src/main/scala/shapeless/ops/maps.scala                                                         
[info]  /home/miles/projects/shapeless/core/src/main/scala/shapeless/ops/traversables.scala                                                 
[info]  /home/miles/projects/shapeless/core/src/main/scala/shapeless/syntax/typeable.scala
```

> I think the idea of encouraging people to move macro definitions to subprojects makes sense, but having done that, those subprojects will want to have the warning disabled.
> Otherwise it's a warning which can't be fixed and that's ... unhelpful.

**Comment by dwijnand** [comment]
How do we want to provide an option to turn this off?

**Comment by dwijnand** [comment]
Also do we want to keep it default on or off?

**Comment by eed3si9n** [comment]
The whole point of it is to inform the general public about intentional over-compilation, so it should be on by default.

**Comment by dwijnand** [comment]
PR merged. Forward port issue is at https://github.com/sbt/zinc/issues/142.

**Comment by cvogt** [comment]
@dwijnand @eed3si9n is this available via typesafehub/zinc? Also, is there an option to switch off re-compilation of code depending on macros (which was the behavior in earlier versions of SBT AFAIK).

**Comment by eed3si9n** [comment]
@cvogt typesafehub/zinc (aka the old repackaged Zinc) should have all the features in sbt.
See https://github.com/sbt/sbt/blob/v0.13.13/compile/inc/src/main/scala/sbt/inc/IncOptions.scala for various switches. The option to turn off recompilation for macro users is recompileOnMacroDef.

**Comment by cvogt** [comment]
@eed3si9n ah, great , so `recompileOnMacroDef` is available for command line `zinc`. This flag logRecompileOnMacro however is not AFAICT, just FYI.
