### ISSUE TITLE
Consider using a non-SNAPSHOT version for scripted tests

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#2658]
## steps

`scripted`
## problem

Scripted takes a long time to run. Testing manually (via `$ pause`) shows (at least in part) that it takes a long time to resolve all the pieces of sbt, due to the fact that it's a SNAPSHOT version.
## expectation

Quick feedback loop.
## notes

Related to #2648 ("Scripted should do less").

**Comment by dwijnand** [comment]
http://www.scala-sbt.org/0.13/docs/Testing-sbt-plugins.html#step+1%3A+snapshot expressly talks about using `-SNAPSHOT`, so maybe this issue is invalid.

**Comment by eed3si9n** [comment]
Publishing -SNAPSHOT locally to do testing is a horrible workaround. I would like to see scripted working without needing to set SNAPSHOT version or put things in my local environment.
