### ISSUE TITLE
trouble with Key: dependencyClasspath (sbt 0.11.0)

### ISSUE THREAD

**Issue by cessationoftime** [sbt/sbt#266]
I am working with the ProguardPlugin and a Multi-Build Project.  I have two subprojects and a root project.  The root project will be a library that contains common code for the two subprojects, this root project does not YET contain any code whatsoever, it only contains the sbt build definition for my overall project.  So my two subprojects are set to depend on my root project even though there isn't any code to depend on yet.  With this setup I attempt to use the ProguardPlugin on one of the subprojects.

The ProguardPlugin executes the following code:

```
def proguardInJarsTaskImpl: Initialize[Task[Seq[File]]] = {
    (dependencyClasspath in Compile, proguardInJars, proguardLibraryJars) map {
        (dc, pij, plj) =>
            import Build.data
        data(dc).filterNot(plj.contains) ++ pij
    }
}
```

When it runs this code the Key: "dependencyClasspath in Compile" has the dependency of my root project included:
"C:\Users\username\gits\rootProject\target\scala-2.9.1\classes" which is great except that there is no code in the root project yet, so "C:\Users\username\gits\rootProject\target\scala-2.9.1\classes" is never created.  And I end up with a Proguard error when it looks for that dependency: No such file or directory.

```
 [error] {file:/C:/Users/cvanvranken.URMC-SH/gits/datawarehousequery/}datawarehousequery-client/*:proguard: java.io.IOException: Can't read [C:\Users\cvanvranken.URMC-SH\gits\datawarehousequery\target\scala-2.9.1\classes(;;;;!META-INF/MANIFEST.MF)] (No such file or directory)
```

So the question is where should this problem be tackled?  Within sbt, or within the ProguardPlugin?  My feeling is that sbt should always create the "\target\scala-2.9.1\classes" directory if it is going to report that it is a dependency.  Alternatively it should not report a classpath dependency for a project if the classes folder is not created.

**Comment by harrah** [comment]
Please don't open an issue while the mailing list discussion is still active.  I also see that you opened the issue on the proguard plugin, so I'm closing this.
