### ISSUE TITLE
Windows installer sets Path environment variable incorrectly

### ISSUE THREAD

**Issue by distinctdan** [sbt/sbt#2665]
The windows installer set the sbt path incorrectly. It added a double backslash somewhere, I think it was like `C:\Program Files (x86)\\sbt\bin`, which of course caused it to point to the wrong place. After I removed the double backslash, it appeared to be working fine. I'm running Windows 10.

**Comment by dwijnand** [comment]
Duplicate of https://github.com/sbt/sbt-launcher-package/issues/76

**Comment by eed3si9n** [comment]
@distinctdan Dale (@dwijnand) fixed the bug so I published a new installer for Windows for 0.13.12. Could you try using it, and see if it fixes the issue for you?
http://www.scala-sbt.org/download.html

**Comment by distinctdan** [comment]
Yup, it now sets the path correctly. Thanks!

**Comment by dwijnand** [comment]
Awesome. Thanks for the quick turnaround @distinctdan.
