### ISSUE TITLE
when fetching a maven dependency, sbt fails to evaluate a property at runtime and select the profile

### ISSUE THREAD

**Issue by dportabella** [sbt/sbt#2666]
this maven artifact depends on a dependency with a variable that needs to be evaluated at runtime.
`"org.apache.hbase" % "hbase-testing-util" % "1.2.1"` depends on `org.apache.hbase:${compat.module}:1.2.1`

maven correctly evaluates the variable at runtime, selects the right profile, and then gets the said dependency (variables are allowed in all parts of dependency coordinates). This artifact relies on "[property isn't defined at invocation](http://books.sonatype.com/mvnref-book/reference/profiles-sect-activation.html#profiles-sect-activation-by-absence)" activation to set a bunch of defaults around what version of hadoop gets used.

But sbt fails to evaluate the property and download the dependency.

See the [ticket on hbase 1.2.2](https://issues.apache.org/jira/browse/HBASE-15925) on solving this issue for tools (such as sbt) that fail to activate profiles. they "fixed" the problem on hbase 1.2.2 by ensuring we have defined defaults for all the needed properties that match that default profile, so that when tools fail to activate the profiles we ask for they get something that works-at-all.

https://github.com/apache/hbase/blob/1.2.2RC2/pom.xml#L1935
https://github.com/apache/hbase/commit/f245fe106e80d3eb08c172903cbc70900a5b8a51

However, this sbt bug should be fixed.

**Comment by dwijnand** [comment]
This is probably more a limitation of Apache Ivy, for which sbt uses a forked version (https://github.com/sbt/ivy).

This issue was also reported in #1774.

**Comment by busbey** [comment]
does Ivy handle the profile activation or just dependencies once handed an effective pom?

**Comment by ctongfei** [comment]
This affects `jcuda`.
```
[warn]   https://repo1.maven.org/maven2/org/jcuda/jcuda-natives/0.8.0/jcuda-natives-0.8.0-${jcuda.os}-${jcuda.arch}.jar
```

Macros `${jcuda.os}` and `${jcuda.arch}` are not expanded by SBT.

I'm developing something that uses CUDA in Scala and this is a blocking problem.

**Comment by eed3si9n** [comment]
@ctongfei See this workaround for CUDA - https://stackoverflow.com/a/46763742/3827

**Comment by levinson** [comment]
The workaround requires the library maintainer to define defaults in their pom.xml (or to fork the library and add them yourself), which isn't always a practical solution. It would be nice to have a way to override maven properties when resolving dependencies to workaround the issue until it can be resolved.
**EDIT**: Ah, so I think the workaround provided *does* work to override maven properties, just that I was running into a separate issue: https://github.com/sbt/sbt/issues/3618. What finally resolved it for me was this comment: https://github.com/sbt/sbt/issues/3618#issuecomment-454528463

**Comment by eed3si9n** [comment]
I am closing this for now since Couriser I think handles Maven profiles better.
