### ISSUE TITLE
XML encoded chars in artifact descriptions/names causes corrupt artifacts on publish

### ISSUE THREAD

**Issue by wfaler** [sbt/sbt#268]
XML encoded chars in project descriptions causes corrupt artifacts, for instance:
description := "Hello & good bye"

The "&" will cause the corrupt artifact descriptors when running publish or publish-local.
I found this by pure accident, after having trouble with dependencies magically dissappearing of my classpath despite being defined.

Correcting the character in the ivys/ivy.xml file fixed the problem, but I think any text that goes into the xml descriptors should probably be filtered for characters that need XML encoding.

**Comment by indrajitr** [comment]
ivys/ivy.xml generation is done by Ivy which has [this problem](https://issues.apache.org/jira/browse/IVY-1237). But we have to handle this somehow I guess.

**Comment by harrah** [comment]
Then, a new Ivy release would fix this, right?

**Comment by indrajitr** [comment]
Yes, a new Ivy release should fix that ideally. But I am not aware of their roadmap or timeline.

**Comment by ijuma** [comment]
If you need a new release from them, it's a good idea to send a message to the mailing list explaining that. It may motivate them to do it sooner.

**Comment by harrah** [comment]
Fixed by [moving to Ivy 2.3.0-RC1](https://github.com/harrah/xsbt/commit/3f92b33350380bc7661be6873d2617ebc4285101) (and eventually to final).
