### ISSUE TITLE
updateSbtClassifiers broken with sbt 0.13.12 on Scala 2.9 projects

### ISSUE THREAD

**Issue by jastice** [sbt/sbt#2686]
## steps

Create a simple project with this in `build.sbt`:

``` scala
scalaVersion := "2.9.3"
```

run `sbt -Dsbt.version=0.13.12 updateSbtClassifiers`
## problem

Task fails with resolve error:

```
[error] (*:updateSbtClassifiers) sbt.ResolveException: unresolved dependency: org.scala-lang#scala-reflect;2.9.3: not found
```
## notes

This problem does not occur up to sbt 0.13.11

**Comment by dwijnand** [comment]
I wonder if this is fallout from #2634. (/cc @milessabin).

**Comment by eed3si9n** [comment]
Interesting. Because of the precompiled compiler bridges, sbt does depend on multiple Scala versions.

**Comment by milessabin** [comment]
I think it probably is a consequence of #2634. I'll investigate ... feel free to assign to me.

**Comment by dwijnand** [comment]
I would assign you if I could. I think you need to join the sbt org to do so. /cc @eed3si9n

**Comment by eed3si9n** [comment]
@milessabin Invited you to sbt-committer team.

**Comment by milessabin** [comment]
Thanks!

**Comment by dwijnand** [comment]
Welcome!

**Comment by drewhk** [comment]
I actually had the same issue with the Akka build, which uses Scala 2.11.8. Had to downgrade to 0.13.11 to solve the issue.

**Comment by drewhk** [comment]
[error] impossible to get artifacts when data has not been loaded. IvyNode = org.scala-lang#scala-reflect;2.11.8

**Comment by dwijnand** [comment]
Fixed in https://github.com/sbt/sbt/pull/2692
