### ISSUE TITLE
sbt runs on a different directory

### ISSUE THREAD

**Issue by intracer** [sbt/sbt#2688]
(See the guidelines for contributing, linked above)
## steps

Basic idea of what I did is the following, but I could not reproduce it from the clean start.

```
git clone git@github.com:intracer/wlxjury.git
cd  wlxjury
sbt run/package etc.
cd ..
mv  wlxjury wlxjury_old
git clone git@github.com:intracer/wlxjury.git
cd wlxjury
sbt run/package etc.
```
## problem

sbt is run in one directory: ~/wm/wlxjury 
but works on another which is unrelated: ~/wm/wlxjury_old

**~/wm/wlxjury$** sbt packageDebianSystemD
[info] Loading global plugins from /home/ilya/.sbt/0.13/plugins
[info] Loading project definition from **/home/ilya/wm/wlxjury_old/**project
[info] Set current project to wlxjury (in build file:**/home/ilya/wm/wlxjury_old/**)
[info] Packaging **/home/ilya/wm/wlxjury_old/**target/scala-2.11/wlxjury_2.11-0.8-javadoc.jar ...
[info] Packaging **/home/ilya/wm/wlxjury_old/**target/scala-2.11/wlxjury_2.11-0.8-sources.jar ...
[info] Done packaging.
[info] Done packaging.
[info] Updating {file:**/home/ilya/wm/wlxjury_old/**}root...
[info] Wrote **/home/ilya/wm/wlxjury_old/**target/scala-2.11/wlxjury_2.11-0.8.pom
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Compiling 102 Scala sources and 1 Java source to **/home/ilya/wm/wlxjury_old/**target/scala-2.11/classes...
[info] Packaging **/home/ilya/wm/wlxjury_old/**target/scala-2.11/wlxjury_2.11-0.8-web-assets.jar ...
[info] Done packaging.
[warn] **/home/ilya/wm/wlxjury_old/**app/controllers/SendMail.scala:29: object MailerPlugin in package mailer is deprecated: Use injected MailerClient instead
[warn]     MailerPlugin.send(email)(play.api.Play.current)
[warn]     ^
[warn] one warning found
[info] Packaging **/home/ilya/wm/wlxjury_old/**target/scala-2.11/wlxjury_2.11-0.8.jar ...
[info] Done packaging.
[info] Packaging **/home/ilya/wm/wlxjury_old/**target/scala-2.11/wlxjury_2.11-0.8-sans-externalized.jar ...
[info] Done packaging.
[info] Building debian package with native implementation
[info] dpkg-deb: building package `wlxjury' in`../wlxjury_0.8_all.deb'.
[success] Total time: 47 s, completed Aug 2, 2016 6:55:44 AM

**~/wm/wlxjury$** 
## expectation

when ran from  ~/wm/wlxjury sbt should work on ~/wm/wlxjury not ~/wm/wlxjury_old which does not seem to 
be related
Actually this happened only once, and did not reproduce again, but still is quite strange.

**Comment by dwijnand** [comment]
For an issue like this, without being able to reproduce it it would be very difficult to diagnose and fix the problem.. So I'm going to close this, but feel free to open it if you figure out how to reproduce it!
