### ISSUE TITLE
brew install fails with 404 Not Found on OSX 10.11.6

### ISSUE THREAD

**Issue by ron-totango** [sbt/sbt#2694]
(See the guidelines for contributing, linked above)
## steps

brew install sbt
## problem

==> Downloading http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.5/sbt-launch.jar

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "sbt"
Download failed: http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.5/sbt-launch.jar
## expectation

sbt should install
## notes

running on mac OSX El Capitan 10.11.6

**Comment by ron-totango** [comment]
typesafe.artifactoryonline should be replaced with repo.typesafe 

Used _brew edit sbt_ to fix this

**Comment by dwijnand** [comment]
You should update your homebrew setup (and not just to fix this issue, in general), because the sbt formula hasn't downloaded from artifactoryonline.com since September 2014:

https://github.com/Homebrew/legacy-homebrew/commit/93e6d67a8485f71a931cbae81e9a0069f6652327

**Comment by ron-totango** [comment]
Sorry for asking the obvious, but how do I update the homebrew setup?

Thanks,
Ron

בתאריך 6 באוג׳ 2016 7:54 אחה״צ,‏ "Dale Wijnand" notifications@github.com
כתב:

**Comment by dwijnand** [comment]
Try `brew update`. That _is_ the way that brew is updated, but lots of things have changed in 2 years that the update might be smooth (for example the reason I linked to legacy-homebrew is homebrew a few months ago split their repo into brew and homebrew-core), so... good luck :)
