### ISSUE TITLE
equal (=) appearing passed in as batch argument requires quotation on Windows

### ISSUE THREAD

**Issue by hossameldeen** [sbt/sbt#2695]
## steps
- Installed sbt 0.13.8 on Windows 7 64-bit.
- Went to a directory that has a simple hello-world sbt project (probably doesn't matter).
- From the commandline, called: `sbt -Dsbt.log.noformat=true`.
## problem
- It says: Warning: invalid system property 'sbt.log.noformat'
## expectation
- To not show this message, because the documentation seems to say it's a valid property.
  http://www.scala-sbt.org/0.13/docs/Command-Line-Reference.html
## notes
- OS: Windows 7 64-bit.
- sbt: 0.13.8
- Screenshot showing the error and showing sbt version
  ![sbt-log-noformat-error](https://cloud.githubusercontent.com/assets/6719916/17526074/f8c4776a-5e65-11e6-929b-dca6ef2279e6.PNG)

## workaround

```
sbt "-Dsbt.log.noformat=true"
```

**Comment by eed3si9n** [comment]
Does this still happen on the latest sbt 0.13.12?

**Comment by hossameldeen** [comment]
Yes, it does. The steps I just did to check:
- Removed sbt's installation from Control Panel.
- Downloaded `sbt-0.13.12.msi` from [here](http://www.scala-sbt.org/download.html)
- Created an empty directory and called `sbt -Dsbt.log.noformat=true` in it. The same problem occurred. (But kept downloading stuff for some time since this is the first time in the new installation).
- Then, called `sbt sbtVersion` to make sure of the installed version.

Screenshot:
![sbt-log-noformat-12](https://cloud.githubusercontent.com/assets/6719916/17529187/af96c284-5e72-11e6-802f-b870c8a2a82d.PNG)

Note: The screenshot is for calling `sbt -Dsbt.log.noformat=true` for a second time after the first time that downloaded many stuff. That's why there're no `downloading..` lines. And to confirm: The error message showed in both the first and second calls.

**Comment by kpbochenek** [comment]
you have `>sbt -Dsbtlog.noformat=true` (you missed dot after sbt)

**Comment by eed3si9n** [comment]
I'm guessing it's a capability gap between the shell script shipped for Mac and Linux vs this batch script - https://github.com/sbt/sbt-launcher-package/blob/e4e3e54c33a4b26e3e0a82270581c9038bae9ddc/src/windows/sbt

**Comment by hossameldeen** [comment]
Oops, my mistake. That's why screenshots are cool. But the problem still occurs with it written correctly.

Screenshot:
![sbt-log-noformat-12-corrected](https://cloud.githubusercontent.com/assets/6719916/17529523/f15feaa0-5e73-11e6-8b1a-22fa3936e87e.PNG)

Were any of you able to reproduce it?

**Comment by wobu** [comment]
We have the same error with a custom property we are setting. Everything worked with sbt 0.13.12 on Windows 7, but since we switched to Windows 10 this annoys us as hell.

Current workaround: 
Setting the System Property via `-Dsample=true` in `C:\Program Files (x86)\sbt\conf\sbtconfig.txt`

**Comment by dwijnand** [comment]
Actually I think the issue is in

* https://github.com/sbt/sbt-launcher-package/blob/f9f389ec5e3ee75c7b335840a4aae2ad689a9cc5/src/universal/bin/sbt.bat

rather than

* https://github.com/sbt/sbt-launcher-package/blob/f9f389ec5e3ee75c7b335840a4aae2ad689a9cc5/src/windows/sbt

From what I understand the former is used for Window's CMD, while the latter for Cygwin and MSYS.

**Comment by dwijnand** [comment]
Here's another workaround, only when using that BAT script (on Windows):

```bat
sbt "-Dsbt.log.noformat=true"
```

**Comment by deterdw** [comment]
Another workaround is to edit the BAT script on Windows and replace

    call :run %SBT_ARGS%

with 

    call :run %*

although this may cause broken/unexpected behaviour when passing the `-jvm-debug` parameter (untested).

The issue is that `=` is a hard-coded parameter separator in batch files, so any looping through the parameters (as is done to build up `SBT_ARGS`) will break parameters of the form `X=Y` into two separate parameters `X` and `Y`. (`%*` avoids this by passing the entire parameter set through as is.)

**Comment by eed3si9n** [comment]
There's a blog post on this topic - https://blogs.oracle.com/quinn/a-little-trick-with-windows-bat-scripts-argument-processing-and-equals-signs

> What worked for me was to write the for loop this way:

```
:recurse
for /F "tokens=1*" %%a in ("%*") do
  rem do something
  ...
  if NOT x%%b==x call :recurse %%b
)
```

**Comment by eed3si9n** [comment]
Looping with `for /F` works for `=` sign handling, but it uses whitespace and tab as delimiter, so it cannot handle `sbt --java-home "C:\Program Files\Java\jdk1.8.0_161"`. It would split it at `"C:\Program"`.

**Comment by eed3si9n** [comment]
Providing a special case handling for arguments starting with `-D` was much easier to do - https://github.com/sbt/sbt-launcher-package/pull/290
