### ISSUE TITLE
overzealous cycle detection

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#2698]
create a project containing `build.sbt`

``` scala
lazy val c = project.dependsOn(LocalProject("a") % "test")
lazy val a: Project = project.dependsOn(c)
```

start sbt, expecting a valid (if not crazy) project. Get

```
[error] Cyclic reference involving 
[error]    Project(id c, ...
[error]    Project(id a, ...
```

**Comment by eed3si9n** [comment]
I fixed this in #2543 for sbt 1.0

**Comment by fommil** [comment]
oh cool! Can it be back ported?

**Comment by eed3si9n** [comment]
Actually what you're describing may not be handled by my simply lazy evaluation since you're already using LocalProject.

**Comment by fommil** [comment]
yeah, I had to do this to avoid scala blowing up.

**Comment by eed3si9n** [comment]
Isn't this a legitimate cyclic reference since a/Compile -> c/Compile -> a/Test -> a/Compile?

**Comment by fommil** [comment]
No, it is `c`'s test config depending on `a`. `a/compile` only depends on `c/compile`.

**Comment by eed3si9n** [comment]
I guess you're right, but sbt basically currently thinks in terms of project a depends on project c depends on project a, like this topological sorting here - https://github.com/sbt/sbt/blob/0.13/main/src/main/scala/sbt/BuildDependencies.scala

**Comment by fommil** [comment]
yeah, I guessed as much. I think this dependency is completely nuts, so my preference is to just push for it to be changed in the project. Gradle supports it, unfortunately.

**Comment by fommil** [comment]
sounds like a WontFix

**Comment by dwijnand** [comment]
I don't think this is a WontFix. I've talked about this bug many times, including today.

**Comment by vkostyukov** [comment]
I faced this very problem in Finagle (trying to mitigate the scope of the changes while decoupling it from Netty 3). Anyways, the following workaround seems to work:

```scala
lazy val c = project.settings(
  unmanagedClasspath in Test <++= (fullClasspath in (LocalProject("a"), Compile))
)
lazy val a = project.dependsOn(c)
```

**Comment by fommil** [comment]
"corkscrew dependencies" is how I heard one delusional team justify it.
