### ISSUE TITLE
Ivy Scala component version check misfires with alternative `scalaOrganization`

### ISSUE THREAD

**Issue by milessabin** [sbt/sbt#2701]
The version check in `IvyScala` [here](https://github.com/sbt/sbt/blob/0.13/ivy/src/main/scala/sbt/IvyScala.scala#L98-L118) is only correct where `scalaOrganization` is actually `org.scala-lang`, and then only so long as the collection of artefacts under that organization remains fixed.

With an alternative organization (eg. "org.typelevel") _all_ other artefacts (aside from the two whitelisted explicitly in that test, if they exist) will have their binary version tested against the Scala binary version. In particular, with a build of the form,

```
scalaOrganization := "org.typelevel"

scalaVersion := "2.11.8"

libraryDependencies += "org.typelevel" %% "cats" % "0.6.1"
```

We'll see the spurious (and very confusing) warning,

```
[warn] Binary version (0.6.1) for dependency org.typelevel#cats_2.11;0.6.1
[warn]   in org.dummy#scala-organization_2.11;0.1-SNAPSHOT differs from Scala binary version in project (2.11).
```

because of a mismatch between the cats binary version (0.6.1) and the Scala binary version (2.11.8).

I think the right fix here is to explicitly list the artefact names which we intend to validate, possibly making it a configurable setting.

**Comment by dwijnand** [comment]
Perhaps it's just me, but it took me a while to understand what exactly the error is.

So for clarity: @milessabin has configured `scalaOrganization` to be "org.typelevel" which is also the organisation of cats. _That's_ why it's triggering.

**Comment by milessabin** [comment]
Yes, that's exactly right ... apologies for not making that clear enough.

**Comment by dwijnand** [comment]
I'm happy with an opt-in approach, personally.

If you can wire it through (without breaking binary compatibility) then even better.

**Comment by milessabin** [comment]
What do you mean by an "opt-in" approach?

**Comment by dwijnand** [comment]
Explicitly list the artefact names which we intend to validate.

**Comment by milessabin** [comment]
Oh I see ... right. I'm part way through making it configurable with the obvious defaults :-)

**Comment by milessabin** [comment]
See also #1818 and #1899.

**Comment by milessabin** [comment]
FTR I would be happy to retain the current semantics where `scalaVersion` is in fact `org.scala-lang` ... see @jsuereth's comment on #1899 [here](https://github.com/sbt/sbt/pull/1899#issuecomment-77170064).

**Comment by dwijnand** [comment]
I agree to Josh's general sentiment, but not at the cost of special-casing org.scala-lang over alternative scala organisations.
