### ISSUE TITLE
Can't invoke non-build level keys

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#2707]
## steps

```
> show baseDirectory
[error] Ambiguous keys: {.}/*:baseDirectory, *:baseDirectory
[error] show baseDirectory
[error]                   ^
> show {.}/*:baseDirectory
[info] /s/t
> show *:baseDirectory
[error] Ambiguous keys: {.}/*:baseDirectory, *:baseDirectory
[error] show *:baseDirectory
[error]                     ^
```
## problem

sbt suggests a key that doesn't work.
## expectation

`show *:baseDirectory` should show the base directory.
## notes

This is broken as of 0.13.12 and works in 0.13.11, so I have a feeling it might be due to #2469. /cc @Duhemm

**Comment by eed3si9n** [comment]
Yea, I'm getting this too using 0.13.13-SNAPSHOT:

```
foo> baseDirectory
[error] Not a valid command: baseDirectory
[error] Ambiguous keys: {.}/*:baseDirectory, *:baseDirectory
[error] baseDirectory
[error]              ^
```

**Comment by eed3si9n** [comment]
So we should exclude build-level keys when there's a key that's scoped to project level?
This might make sense if we think in a multi-project example.

**Comment by dwijnand** [comment]
Yeah project level should trump build-level. The original PR was just to add them to completion, but they shouldn't compete at the same priority.

**Comment by Duhemm** [comment]
What would be the correct behaviour then?

How about (for https://github.com/sbt/sbt/blob/0.13/main/src/main/scala/sbt/Act.scala#L79-L84):
- If we have nothing, choose the default
- If we have a single project level key and 0 or more build level keys, choose the project level key
- If we have 0 project level keys and a single build level key, chose the build level key
- If we have multiple possibilities, say that the key is ambiguous

**Comment by dwijnand** [comment]
yep, sounds good.
