### ISSUE TITLE
version command

### ISSUE THREAD

**Issue by btilford** [sbt/sbt#271]
The docs and google havn't pointed me to a --version or -v type of command. Is there one? If not it would be really useful especially when having to compile plugins that for instance don't work on 0.11.0 but do work on 0.11.1

**Comment by mslinn** [comment]
`sbt help` for v0.11.1 reports the version (incorrectly) as 0.11

If you need to know the exact version, open `sbt-launch.jar` (it is a zip file) and look at `sbt/sbt.boot.properties`. For v0.11.1, Line 7 should say:

```
version: read(sbt.version)[0.11.1]
```

**Comment by harrah** [comment]
@btilford use the 'about' command.

@mslinn 'help' doesn't list the version, but 'about' does.  Where does it say

**Comment by harrah** [comment]
Not sure where the rest of the sentence went, but it was supposed to be "Where does it say 0.11 incorrectly?"

**Comment by mslinn** [comment]
Sorry, I mean ``sbt about`. It shows version 0.11, not 0.11.1

**Comment by harrah** [comment]
Not sure how that could happen.  It pulls the version directly from the version in project/build.properties or if that is unspecified, from the launcher properties as you indicate.  Have you customized anything about the launcher, or perhaps using something like sbt-extras?

**Comment by mslinn** [comment]
Nope no customization. Do you see different output from sbt about?

**Comment by harrah** [comment]
```
> about
[info] This is sbt 0.11.1
[info] The current project is {file:/home/mark/tmp/a/}default-d02948
[info] The current project is built against Scala 2.9.1
[info] Available Plugins: sbtinspectr.Plugin
[info] sbt, sbt plugins, and build definitions are using Scala 2.9.1
```
