### ISSUE TITLE
Stopping Play does not release Slick's connection pool

### ISSUE THREAD

**Issue by lasimon** [sbt/sbt#2727]
## steps

sbt run a Play 2.4 app using Slick 3.1
Ctrl-d and start it again or edit a source file so it auto-recompiles & starts
## problem

The connection pool is now twice as large as it should be (i.e. it appears not to have been released when play was stopped and a new one was created when play was restarted).  Repeat and the connection pool continues to grow until eventually the number of allowed connections to the database is exceeded.  Exiting and restarting sbt clears the connection pool as expected.
## expectation

Connection pool is cleared on each restart.

**Comment by richdougherty** [comment]
Hi @lasimon. I'm a dev on the Play Framework project and I'd guess this is probably not an sbt issue. If you're using the Slick plugin for Play can you raise an issue over here: https://github.com/playframework/play-slick. If you're using Slick without a plugin then you need to remember to clean up your Slick resources each time the application stops. See: https://www.playframework.com/documentation/2.5.x/ScalaDependencyInjection#Stopping/cleaning-up. If you have more issues the first thing to do is post a message on the Play mailing list. Then if it still seems like a Play bug you can raise a Play issue: https://github.com/playframework/playframework.

**Comment by lasimon** [comment]
@richdougherty Thanks.  Yes play-slick looks like a more likely culprit.  We'll try switching from play-slick 1.1.0 to 1.1.1 and see if that fixes it.
