### ISSUE TITLE
Provision for running more than one app under sbt at once?

### ISSUE THREAD

**Issue by mslinn** [sbt/sbt#273]
My [project](https://github.com/mslinn/hanuman) has two apps; one is dependent on the other. 

```
$ sbt run
[info] Loading global plugins from C:\Users\Mike Slinn\.sbt\plugins
[info] Loading project definition from E:\work\experiments\scala\hanuman\project
[info] Set current project to hanuman (in build file:/E:/work/experiments/scala/hanuman/)

Multiple main classes detected, select one to run:

 [1] net.interdoodle.hanuman.AppServer
 [2] net.interdoodle.httpstaticfileserver.HttpStaticFileServer
```

App 2 must be run before app 1. How can I set up sbt to run them in this order?

**Comment by harrah** [comment]
For full flexibility, you'd want to implement a task yourself.  However, I could see extending `run-main` to allow a comma-separated list of main classes to run in that order.  That is an interactive task, however, and perhaps you are looking for something not requiring manual intervention.  As another alternative or in addition to the `run-main` option, the `mainClass` setting could be allowed to be a comma or whitespace separated list of main classes.

**Comment by harrah** [comment]
Closed, no response.
