### ISSUE TITLE
`sbt about` is taking too much time to start.

### ISSUE THREAD

**Issue by tandon-aman** [sbt/sbt#2732]
Hi,

I am following the coursera tutorial to install scala and sbt. But when i am running the command `sbt about` it is taking so much time.

Link to coursera scala tools setup link https://www.coursera.org/learn/progfun1/supplement/BNOBK/tools-setup-please-read

Link of stackoverflow for the same problems faced by others users http://stackoverflow.com/questions/29599309/stuck-at-getting-org-scala-sbt-sbt-0-13-6-when-running-sbt-in-terminal

My OS is MAC OSX 10.11.5
JAVA version: 1.8.45

It should run faster or it should inform the user that it doing some downloading, if it is. If it is a bug please help here.

**Comment by eed3si9n** [comment]
`sbt` when you install for the first time only installs the launch jar and a shell script, but it needs to download the actual program itself again from the Internet. Depending on the network environment (we've had complaints from users in Australia, India, China etc.) this process could take very long time.

> It should run faster or it should inform the user that it doing some downloading, if it is.

It normally does once the downloading starts. We've also heard complaints that sbt should _not_ display anything to the console during startup (#840)
