### ISSUE TITLE
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0

### ISSUE THREAD

**Issue by Roshanson** [sbt/sbt#2733]
## steps

run  sbt  command  
## problem

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0 
## notes

JDK 1.8.102  sbt 0.13.12.1  scala 2.11.8

**Comment by dwijnand** [comment]
Is this on Windows?

**Comment by Roshanson** [comment]
yes  ,on win8 x64

**Comment by hntd187** [comment]
@Roshanson Java8 removed permgen (permanent generation) in 8, so it's a warning saying there is no need to set a size for it anymore. It should be safe to ignore.

**Comment by mr-git** [comment]
Same happens on Mac, SBT installed using brew.
It is safe to ignore, but it is useless output too.
It would be nice to remove anything that causes it to be printed.

**Comment by yosualb** [comment]
I got this warning too, using Java 8 on Win 10 x64.

I am googling and found this (just trying to help for improvement):
http://java-latte.blogspot.co.id/2014/03/metaspace-in-java-8.html

**Comment by xuwei-k** [comment]
Maybe sbt-launcher and launcher-package fixed this issue :confused: ?
- https://github.com/sbt/sbt-launcher-package/commit/cb12ec1eaa6907273edd
- https://github.com/sbt/launcher/commit/0c120409c9590ca0e08c2f875
- https://github.com/sbt/sbt-native-packager/commit/daad0bbb690e20f8cd80

**Comment by PeterLambCSA** [comment]
I removed this VM option from sbtconfig.txt in the conf directory of SBT and it no longer gives me this error.

**Comment by asakaev** [comment]
macOS 10.14.6
OpenJDK11U-jdk_x64_mac_hotspot_11.0.4_11
sbt 1.3.0 via brew

The same message:
"OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0"

**Comment by mkurz** [comment]
Same here with sbt 1.3.0 on Ubuntu.
```bash
$ sbt
OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
```

**Comment by eed3si9n** [comment]
Do you have either SBT_OPTS or JAVA_OPTS environment variables set?

**Comment by eed3si9n** [comment]
At least on Ubuntu I no longer see this, so I am closing this issue.

**Comment by PeterLambCSA** [comment]
The Windows distribution of SBT includes this option in sbtconfig.txt hence why the warning keeps coming up. You have to manually remove it from the distribution. At least last I checked. It may have been removed from the distribution now.

**Comment by mkurz** [comment]
@eed3si9n I think you were too fast closing this issue: I guess you used Java 8 to test this on Ubuntu. Please try Java 11...
```
$ java -version
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)
```

In Ubuntu, the `sbt` shell script contains following condition (`class_metadata_opt` being `MaxPermSize`):
```bash
  if [[ (( $java_version < 8 )) ]]; then
    addJava "-XX:${class_metadata_opt}=${class_metadata_size}m"
  fi
```
That works fine if `java_version` is of value `8` or `9`, but won't work when the value is `10` or `11` as the `if` condition becomes `true`...

**Comment by mkurz** [comment]
Reported here as well: https://github.com/sbt/sbt/issues/5031

**Comment by eed3si9n** [comment]
@mkurz Interesting. I thought `((` would do the arithmetic comparison.

**Comment by mkurz** [comment]
Maybe `$java_version` is a string? (I am not very experienced programming shell scripts)

**Comment by eed3si9n** [comment]
@mkurz Even though this issue has the same error message, I think the mechanism is different, so let's track this new variant in https://github.com/sbt/sbt/issues/5031.

**Comment by mkurz** [comment]
@eed3si9n Closing in favor of #5031?
