### ISSUE TITLE
ivy2 local preeceds ivy2 cache when version defined with wildcard

### ISSUE THREAD

**Issue by codesurf42** [sbt/sbt#2744]
(See the guidelines for contributing, linked above)
## steps

Your project depends on library and the version is defined like "0.0.+"
You have this library published locally (sbt publishLocal), e.g. 0.0.18
but you have also higher versions in your local cache e.g. 0.0.26
## problem

Sbt is picking up the latest from .ivy2/local, not the latest available in both .ivy2/local and .ivy2/cache (or available on remote repo to be cached)

If there is no locally published version, sbt will pick up the latest from cache or download it, so it will get the latest available version.

If I define version without wildcard, as 0.0.26 - it will pick up the one from cache.
## expectation

Sbt with version like "0.0.+" should get the latest version available, not the latest published locally.
## notes

It is somehow opposite to https://github.com/sbt/sbt/issues/2687

sbt.version=0.13.12

**Comment by dwijnand** [comment]
It's interesting (in a sad way) how this doesn't mirror -SNAPSHOT behaviour reported in #2687, and I wonder if that's intentional.

In my eyes there're both legitimate bugs.

**Comment by eed3si9n** [comment]
I am closing this since 1.3.0 switches to Coursier.
