### ISSUE TITLE
Remove the tuple map enrichments

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#2762]

**Comment by dwijnand** [comment]
Remove or maybe move into sbt.internal.

**Comment by dwijnand** [comment]
This is under discussion now. See #3083 and what it links to.

**Comment by eed3si9n** [comment]
Tuple syntax is here to stay for sbt 1.0. Should we un-deprecate? I'm somewhat neutral on this topic.

**Comment by jvican** [comment]
[Given that the use of tuple enrichments has differents than `.value`](https://github.com/sbt/sbt/pull/3079), I lean towards removing `deprecated` -- I don't find a reason why we should punish users with a deprecation when its use could be justified :smile:.
