### ISSUE TITLE
0.13.13-RC2 issue, commons-compress incorrect dependency

### ISSUE THREAD

**Issue by dispalt** [sbt/sbt#2765]
## steps

I made a small repo to demonstrate it. 

```
$ git clone https://github.com/dispalt/sbt-sjs-issue
$ sbt web-plugin:webJarsNodeModules
```

This isn't supposed to fail but it does.

if you change the build.properties to `0.13.12` it and re-run it it work
## problem

I am running into an issue with 0.13.13-RC2 specifically around the conflict of two plugins.  It seems to be local to 0.13.13-RC2.   It's not clear from introspection of the build why it's happening.  But a plugin has a dependency on `commons-compress:1.9` and somehow version 1.6 is leaking into the build.
## expectation

It should work since there are only two plugins in the repo and no source code, there shouldn't be a conflict
## notes

The only thing I could find of interest is if you do

```
> reload plugins
// now your in the project build
> provided:dependencyTree
// there appears to be a dependency on 1.6 from jgit
```

**Comment by eed3si9n** [comment]
Thanks for the report with the repro steps!
We have #2761 tracking this issue already, and hopefully we have a fix soon.
I'm closing this for now as duplicate.

**Comment by dispalt** [comment]
Oh whoops, I was wondering why I started getting SBT emails. Thanks 😀
