### ISSUE TITLE
"help" with no options does not display a full command list

### ISSUE THREAD

**Issue by 0branch** [sbt/sbt#277]
For example,

<pre>
> help
  help command*               Displays this help message or prints detailed help on requested commands.
  about                       Displays basic information about sbt and the build.
  reboot [full]               Reboots sbt and then executes the remaining commands.
  &lt; file*                     Reads command lines from the provided files.
  !!                          Execute the last command again
  !:                          Show all previous commands
  !:n                         Show the last n commands
  !n                          Execute the command with index n, as shown by the !: command
  !-n                         Execute the nth command before this one
  !string                     Execute the most recent command starting with 'string'
  !?string                    Execute the most recent command containing 'string'
  ~ &lt;command&gt;                 Executes the specified command whenever source files change.
  exit                        Terminates the build.
  reload                      Loads the project in the current directory
  projects                    Displays the names of available projects.
  project [project]           Displays the current project or changes to the provided `project`.
  - command                   Registers 'command' to run if a command fails.
  iflast command              If there are no more commands after this one, 'command' is run.
  ( ; command )+              Runs the provided semicolon-separated commands.
  shell                       Provides an interactive prompt from which commands can be run.
  set &lt;setting-expression&gt;    Evaluates the given Setting and applies to the current project.
  tasks                       Displays the tasks defined for the current project.
  inspect &lt;key&gt;               Prints the value for 'key', the defining scope, delegates, related definitions, and dependencies.
  eval &lt;expression&gt;           Evaluates the given Scala expression and prints the result and type.
  alias                       Adds, removes, or prints command aliases.
  append command              Appends `command` to list of commands to run.
  last &lt;key&gt;                  Prints the last output associated with 'key'.
  last-grep &lt;pattern&gt; &lt;key&gt;   Shows lines from the last output for 'key' that match 'pattern'.
  session ...                 Manipulates session settings.  For details, run 'help session'..
  show &lt;key&gt;                  Displays the result of evaluating the setting or task associated with 'key'.
</pre>

Note the lack of 'console', 'compile', etc.

**Comment by harrah** [comment]
'console' and 'compile' are tasks that can be seen by running 'tasks'.  When you run 'tasks', you can see this is because there are many tasks and it would make help fairly noisy to list these.  
1. It would be nice to figure out some heuristic to trim the list of tasks displayed to the important ones
2. Perhaps there is something about the output of help that could be improved to make 'tasks' more obvious?
3. `help compile` will show the description of `compile`

**Comment by 0branch** [comment]
Thanks for clarifying, I completely missed that.

I agree: perhaps direct help for the common cases (e.g. compile and console) could be provided; descriptions could refer the user to the 'tasks' command for a full listing.

**Comment by harrah** [comment]
I think the commits comprising 0.12.0-Beta are sufficient to close this issue.  The `help` list is about half the length as before and the `tasks` command is near the top.  `help compile` shows the description of `compile`.  `help classpath` lists all tasks/settings/commands containing "classpath".  (The argument is interpreted as a regular expression if a command/task/setting with that name doesn't exist).  The `tasks` command itself is a short list of the main tasks, with the option to view more tasks.  There is a similar command `settings`.

This is now the output of `help`:

```
> help

  help                         Displays this help message or prints detailed help on requested commands (run 'help <command>').
  about                        Displays basic information about sbt and the build.
  reload                       (Re)loads the project in the current directory
  settings                     Lists the settings defined for the current project.
  tasks                        Lists the tasks defined for the current project.
  projects                     Lists the names of available projects or temporarily adds/removes extra builds to the session.
  project                      Displays the current project or changes to the provided `project`.
  set                          Evaluates a Setting and applies it to the current project.
  session                      Manipulates session settings.  For details, run 'help session'.
  inspect                      Prints the value for 'key', the defining scope, delegates, related definitions, and dependencies.
  ; <command> (; <command>)*   Runs the provided semicolon-separated commands.
  ~ <command>                  Executes the specified command whenever source files change.
  last                         Displays output from a previous command or the output from a specific task.
  last-grep                    Shows lines from the last output for 'key' that match 'pattern'.
  exit                         Terminates the build.
  show <key>                   Displays the result of evaluating the setting or task associated with 'key'.

More command help available using 'help <command>' for:
  !, -, <, alias, append, apply, eval, iflast, reboot, shell
```

The output of `tasks`:

```
> tasks

This is a list of tasks defined for the current project.
It does not list the scopes the tasks are defined in; use the 'inspect' command for that.
Tasks produce values.  Use the 'show' command to run the task and print the resulting value.

  clean             Deletes files produced by the build, such as generated sources, compiled classes, and task caches.
  compile           Compiles sources.
  console           Starts the Scala interpreter with the project classes on the classpath.
  console-project   Starts the Scala interpreter with the sbt and the build definition on the classpath and useful imports.
  console-quick     Starts the Scala interpreter with the project dependencies on the classpath.
  copy-resources    Copies resources to the output directory.
  doc               Generates API documentation.
  package           Produces the main artifact, such as a binary jar.  This is typically an alias for the task that actually does the packaging.
  package-bin       Produces a main artifact, such as a binary jar.
  package-doc       Produces a documentation artifact, such as a jar containing API documentation.
  package-src       Produces a source artifact, such as a jar containing sources and resources.
  publish           Publishes artifacts to a repository.
  publish-local     Publishes artifacts to the local repository.
  run               Runs a main class, passing along arguments provided on the command line.
  run-main          Runs the main class selected by the first argument, passing the remaining arguments to the main method.
  test              Executes all tests.
  test-only         Executes the tests provided as arguments or all tests if no arguments are provided.
  test-quick        Executes the tests that either failed before, were not run or whose transitive dependencies changed, among those provided as arguments.
  update            Resolves and optionally retrieves dependencies, producing a report.

More tasks may be viewed by increasing verbosity.  See 'help tasks'.
```

And `settings`:

```
> settings

This is a list of settings defined for the current project.
It does not list the scopes the settings are defined in; use the 'inspect' command for that.

  auto-compiler-plugins            If true, enables automatically generating -Xplugin arguments to the compiler based on the classpath for the plugin configuration.
  auto-scala-library               Adds a dependency on scala-library if true.
  base-directory                   The base directory.  Depending on the scope, this is the base directory for the build, project, configuration, or task.
  class-directory                  Directory for compiled classes and copied resources.
  cross-paths                      If true, enables cross paths, which distinguish output directories for cross-building.
  fork                             If true, forks a new JVM when running.  If false, runs in the same JVM as the build.
  initial-commands                 Initial commands to execute when starting up the Scala interpreter.
  java-home                        Selects the Java installation used for compiling and forking.  If None, uses the Java installation running the build.
  java-source                      Default Java source directory.
  library-dependencies             Declares managed dependencies.
  managed-resource-directories     List of managed resource directories.
  max-errors                       The maximum number of errors, such as compile errors, to list.
  name                             Project name.
  offline                          Configures sbt to work without a network connection where possible.
  organization                     Organization/group ID.
  publish-artifact                 Enables (true) or disables (false) publishing an artifact.
  publish-to                       The resolver to publish to.
  resource-directory               Default unmanaged resource directory, used for user-defined resources.
  sbt-version                      Provides the version of sbt.  This setting should be not be modified.
  scala-home                       If Some, defines the local Scala installation to use for compilation, running, and testing.
  scala-source                     Default Scala source directory.
  scala-version                    The version of Scala used for building.
  source-directories               List of all source directories, both managed and unmanaged.
  source-directory                 Default directory containing sources.
  target                           Main directory for files generated by the build.
  unmanaged-base                   The default directory for manually managed libraries.
  unmanaged-resource-directories   Unmanaged resource directories, containing resources manually created by the user.
  unmanaged-source-directories     Unmanaged source directories, which contain manually created sources.
  version                          The version/revision of the current module.

More settings may be viewed by increasing verbosity.  See 'help settings'.
```
