### ISSUE TITLE
Slightly better message for sbt's first run

### ISSUE THREAD

**Issue by ghost** [sbt/sbt#2774]
## steps

Downloaded and installed sbt as given [here](http://www.scala-sbt.org/download.html).
## problem

During the first run it waits for a **long** time at "Getting org.scala-sbt sbt 0.13.9 ...". 
## expectation

It would be nice to have the message go something like 
"Please wait, first time initialization of sbt. (Step takes time)". Or something along those lines. 
## notes

It takes a really long time the first time. So much so that I thought my installation was broken and I found answers on stackoverflow. Though that too was not convincing untill I checked ~/.ivy2 's size. Ideally, a progress bar would be good. But the above should be easy to do and would be immensely helpful for first time users.

**Comment by jamesfe** [comment]
Is this something that should be added to the project?  It seems like low-hanging fruit and if the maintainers of this project want it, I can add it.

**Comment by eed3si9n** [comment]
Sure. The code I think is here - https://github.com/sbt/launcher/blob/d318b76f36d5eb727d7227d4dd8b20c1764550b8/launcher-implementation/src/main/scala/xsbt/boot/Update.scala#L144

**Comment by jamesfe** [comment]
@eed3si9n thanks!  I will get cracking on this - progress might be slow since I am new to this project but I appreciate your help.

**Comment by jamesfe** [comment]
Also - @eed3si9n or anyone else, should we move this issue to the sbt/launcher project?  And given your familiarity with the project, what conditions generally indicate that this is a 'first run' situation?

**Comment by eed3si9n** [comment]
We have a bunch of repos, but the end user may or may not be familiar with our internal structure, so I'm ok with it staying here.

**Comment by eed3si9n** [comment]
> what conditions generally indicate that this is a 'first run' situation?

The launcher will check for the specified module under boot directory, when it doesn't find it it uses Ivy to download the module along with its dependencies.

**Comment by eed3si9n** [comment]
Closing this since this was fixed in https://github.com/sbt/launcher/pull/27
