### ISSUE TITLE
Unable to a global autoplugin SBT key in a CrossType.pure CrossProject

### ISSUE THREAD

**Issue by mdedetrich** [sbt/sbt#2775]
## steps

Clone the repository at https://github.com/mdedetrich/cross-type-pure-unable-to-set-key
## problem

It appears to be impossible to set the key `kioTeamName` before it throws a `sys.error` stating that the key must be set. Combinations of setting the `kioTeamName` in the server/client project (or the root project) haven't worked, nor has using `in ThisBuild` worked. I have basically tried all known permutations of setting `kioTeamName` and it hasn't worked.

This may be due to the fact that this a `CrossType.pure` project (its a cross compiled Play/Scala-js project) and due to some initialisation order when doing `CrossType.pure` there are issues with the key being set.

Note that https://github.com/zalando-incubator/sbt-stups is being used without problems in other sbt projects, it just appears to be causing problems in crosstype-pure projects
## expectation

Be able to set the `kioTeamName` key before `sys.error` is called in `CrossType.pure` sbt projects
## notes

This is an issue with the current latest version of SBT (0.13.12), the version is set in `build.properties`.

**Comment by mdedetrich** [comment]
Note that I managed to figure out how to get sbt to work with an autoplugin for settings that either don't have a default setting (or ones that use `sys.error`), you however have to set the settings in 5 different places
- Root
- lazy val server
- lazy val client
- shared jsSettings
- shared jvmSettings

Pinging @dwijnand

**Comment by mdedetrich** [comment]
Okay, so turns out there is a difference between `sys.error` and leaving a setting undefined in regards to initialisation order. If you just leave a setting undefined then its possible to use `in ThisBuild` to initialise the setting just once

**Comment by dwijnand** [comment]
More specifically, when sbt is initialising the value of a key in a scope (say project) it'll fold all the definitions at that scope together, so it'll hit your first sys.error definition and blow up.

If you don't define it, it won't. And if you define it at the lowest scope Global, then any definition in ThisBuild or project level will be used, if present - which is what you want.
