### ISSUE TITLE
Test sbt 1.0.x on JDK 9

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#2778]

**Comment by retronym** [comment]
Referencing #2951, which adds some basic compatibility with Java 9 to the 0.13 branch.

**Comment by dwijnand** [comment]
https://github.com/scala/scala-dev/issues/139 is the Scala ticket about support JDK 9 in general.

Also @smarter reports on sbt/zinc-contrib that:

> Guillaume Martres @smarter Apr 25 15:43
> Ah, the good news is that this seems to be fixed in zinc: I can reproduce the problem in sbt 0.13.15 but not 1.0.0-M5
