### ISSUE TITLE
Can't run Sbt

### ISSUE THREAD

**Issue by lucaster** [sbt/sbt#278]
I followed the installation instructions on the wiki:
- download sbt-launcher.jar
- create the script
- launch the script

I get the following error:

Getting net.java.dev.jna jna 3.2.3 ...

:: problems summary ::
:::: WARNINGS
        [NOT FOUND  ] net.java.dev.jna#jna;3.2.3!jna.jar (2ms)

```
==== Maven2 Local: tried

  file:///home/luca/.m2/repository/net/java/dev/jna/jna/3.2.3/jna-3.2.3.jar

    ::::::::::::::::::::::::::::::::::::::::::::::

    ::              FAILED DOWNLOADS            ::

    :: ^ see resolution messages for details  ^ ::

    ::::::::::::::::::::::::::::::::::::::::::::::

    :: net.java.dev.jna#jna;3.2.3!jna.jar

    ::::::::::::::::::::::::::::::::::::::::::::::
```

:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
download failed: net.java.dev.jna#jna;3.2.3!jna.jar
Error during sbt execution: Error retrieving required libraries
  (see /home/luca/.sbt/boot/update.log for complete log)
Error: Could not retrieve JNA

**Comment by indrajitr** [comment]
I see that too! In fact, I was wondering how you guys are doing full build right now. 
- Indrajit

**Comment by indrajitr** [comment]
You might, in fact, try cleaning `~/.sbt/boot`, `~/.m2/repository` and make sure that you have the correct launcher.

**Comment by indrajitr** [comment]
This is likely a duplicate of #217.

**Comment by wspringer** [comment]
I keep seeing no solutions for this problem, just workarounds, and then the issue is getting closed. Perhaps rather leave it open then, since nothing seems to have been solved yet. (I still have it with 0.12.0.)
