### ISSUE TITLE
SBT Launcher doesn't handle spaces in system properties

### ISSUE THREAD

**Issue by jatcwang** [sbt/sbt#2787]
## steps

```
sbt -v -Dsbt.override.build.repos=true -Dsbt.boot.realm='Sonatype Nexus Repository Manager' -Dsbt.boot.host='nexus.company.com' -Dsbt.boot.user='myusername' -Dsbt.boot.password='mypassword'
```
## problem

For the above command I get the following output:

SBT Launcher doesn't handle spaces in system properties.

```
[process_args] java_version = '1.8.0_102'
# Executing command line:
java
-Dsbt.override.build.repos=true
-Dsbt.boot.realm='Sonatype
Nexus
Repository
Manager'
-Dsbt.boot.host='nexus.company.com'
-Dsbt.boot.user='myusername'
-Dsbt.boot.password='mypassword'
-jar
/usr/share/sbt/bin/sbt-launch.jar

Error: Could not find or load main class Nexus

```

It seems to be splitting on spaces naively and thus Nexus appears as a new command
## expectation

Should handle spaces when it's quoted.
## notes

I had a look at the launcher script /bin/sbt but I cannot put my finger on where exactly it's splitting it.
If someone can point me in the right direction I'll send in a PR.

Stumbled upon this when trying to get sbt launcher to download sbt through a proxy nexus server (#576 #731)

**Comment by monktastic** [comment]
Fixed :)

**Comment by eed3si9n** [comment]
Closing this thanks to https://github.com/sbt/sbt-launcher-package/pull/146

**Comment by jatcwang** [comment]
Sweet thanks!

**Comment by rmcloughlin** [comment]
A similar problem arises when one tries to set these values via SBT_OPTS:

```
$ export SBT_OPTS="-Dsbt.override.build.repos=true -Dsbt.boot.realm='Sonatype Nexus Repository Manager' -Dsbt.boot.host=localhost -Dsbt.boot.user=user -Dsbt.boot.password=password"
$ sbt run
Error: Could not find or load main class Nexus
```

**Comment by jatcwang** [comment]
What version of SBT launcher are you using? This should be fixed as of 0.13.14 (note the issue is in the launcher script I believe. setting the version in project/build.properties won't help)

**Comment by rmcloughlin** [comment]
This is with SBT 0.13.15.  The arguments are parsed correctly when they are defined as separate system properties.

This works fine:
`$ sbt -Dsbt.boot.realm='Sonatype Nexus Repository Manager'`

This does not:
`$ export SBT_OPTS=-Dsbt.boot.realm='Sonatype Nexus Repository Manager'`
`$ sbt`
`Error: Could not find or load main class Nexus`

**Comment by monktastic** [comment]
@rmcloughlin have you tried `$ sbt "-Dsbt.boot.realm=Sonatype Nexus Repository Manager"`?
