### ISSUE TITLE
 sbt-io: Publish 2.12.0-RC2 (0.13.12)

### ISSUE THREAD

**Issue by schmitch** [sbt/sbt#2793]
Well is there any chance to get sbt-io 13.12 published for 2.12.0-RC2?

**Comment by SethTisue** [comment]
this is one of Play's dependencies, which is an obviously important project we'd like to be sure is 2.12 compatible

**Comment by dwijnand** [comment]
PR in #2794, merged into the 0.13.13 branch, cut as 0.13.13-RC3 http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/io_2.12.0-RC2/0.13.13-RC3/jars/

**Comment by SethTisue** [comment]
thanks Dale! I was going to add it to https://github.com/scala/make-release-notes/blob/2.12.x/projects-2.12.md, but maybe I shouldn't if it's only published to bintray and not to maven central.

**Comment by eed3si9n** [comment]
The authoritative URL is https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/io_2.12.0-RC2/0.13.13-RC3/jars/ (then we redirect to Bintray), which is Typesafe repo where rest of the sbt 0.13 artifacts are also published.
