### ISSUE TITLE
Minimal sbt thin client

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2798]
## steps
1. Start sbt server on terminal1 where a build is located: `sbt server`
2. Start sbt client on terminal2 from anywhere like `~/temp/`: `sbt client localhost:5001`
3. In the thin client, I can type in sbt shell expressions such as `echo-server/compile`
## expectation

The shell expressions are queued up to the sbt server and it gets executed.
## not part of the scope

Seeing the intermediate outputs out of the commands and tasks.

**Comment by dwijnand** [comment]
#2859

**Comment by eed3si9n** [comment]
This was implemented in #2859

**Comment by eed3si9n** [comment]
Opening this again for 1.1.0 server.
