### ISSUE TITLE
JSON encoding for useful tasks and settings

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2803]
## steps
1. Start sbt server on terminal1 where a build is located: sbt server
2. Start sbt client on terminal2 from anywhere like ~/temp/: sbt client localhost:5001
3. On terminal2 type `show update`
## expectation

Textual representation of `update` report is displayed on terminal2.
## note

JSON databindings should be derived automatically using sbt-datatype.

**Comment by dwijnand** [comment]
This took 7 weeks. But it's done. https://github.com/sbt/sbt/pull/2892
