### ISSUE TITLE
Abstract "run" task over JSON

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2804]
## steps
1. Start sbt server on terminal1 where a build is located: sbt server
2. Start sbt client on terminal2 from anywhere like ~/temp/: sbt client localhost:5001
3. On terminal2 type `project echo-server`, and then `run`.
## expectation

The standard output from "echo-server" is displayed on terminal2.

**Comment by dwijnand** [comment]
@eed3si9n Is this done now?

**Comment by eed3si9n** [comment]
No the standard out is not abstracted out.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/5620
