### ISSUE TITLE
Abstract "console" task over JSON

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2805]
## steps
1. Start sbt server on terminal1 where a build is located: sbt server
2. Start sbt client on terminal2 from anywhere like ~/temp/: `sbt client localhost:5001`
3. On terminal2 type `project echo-client`, and then `console`.
## expectation

Scala REPL works on terminal2.

**Comment by dwijnand** [comment]
Pushing to 1.1.0

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/5620
