### ISSUE TITLE
Job list

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2807]
Given https://github.com/sbt/sbt/issues/2806
## steps
1. Start sbt on a multi-project build: for instance echo-server and echo-client
2. Run `echo-server/bgrun` to start background "run" task in the background
3. Run `jobList`
## expectation

`jobList` displays the list of all jobs under control by sbt's command engine.
Each job is associated with:
- job id
- command line
- initiating channel
- (optional) subproject scoping

In addition I can run `jobStop 2` to stop job id 2.

**Comment by dwijnand** [comment]
I think this is done with background run in https://github.com/sbt/sbt/pull/2936. It's called `ps`.
