### ISSUE TITLE
Concurrent processing of settings

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2808]
Given https://github.com/sbt/sbt/issues/2798 and https://github.com/sbt/sbt/issues/2807
## steps
1. Start sbt server on terminal1 where a build is located: `sbt server`
2. Start sbt client on terminal2 from anywhere like ~/temp/: `sbt client localhost:5001`
3. On terminal1 `project echo-server`
4. On terminal2 `project echo-client`
5. On terminal1 type `run`
6. On terminal2 type `name`
## expectation

On terminal1 blocks on `run`, on terminal2 I see "echo-client". In other words, run doesn't block other terminal from querying settings.

**Comment by dwijnand** [comment]
Oh! This is what I'm working on. Query settings. WIP in https://github.com/sbt/sbt/pull/2935.
