### ISSUE TITLE
Concurrent processing of run

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2809]
Given https://github.com/sbt/sbt/issues/2798 and https://github.com/sbt/sbt/issues/2807
## steps
1. Start sbt server on terminal1 where a build is located: sbt server
2. Start sbt client on terminal2 from anywhere like ~/temp/: sbt client localhost:5001
3. On terminal1 `project echo-server`
4. On terminal2 `project echo-client`
5. On terminal1 type `run`
6. On terminal2 type `test`
## expectation

On terminal1 blocks on `run`, on terminal2 I see the test results. In other words, run doesn't block other commands.
## note

The command processing should prevent an incoming command from making destructive changes to running jobs. The alternative might be to export to JAR and copy the JAR with some hash.

**Comment by dwijnand** [comment]
@eed3si9n is this done with background run?

**Comment by eed3si9n** [comment]
I guess so.
