### ISSUE TITLE
Scaladoc being run on Java code

### ISSUE THREAD

**Issue by espringe** [sbt/sbt#281]
When running "doc" on an sbt project that has some java code, scaladoc appears to be being run against the Java code and failing there. This can easily be reproduced:

git clone git@github.com:espringe/scoobi.git
cd scoobi
git checkout java-bindings
sbt doc   # this will fail in the Java code
rm -rf src/main/java
sbt doc # now it passes

**Comment by harrah** [comment]
Yes, sbt ran scaladoc on the Java code for a couple reasons.  First, there wasn't any support for running javadoc.  Second, scaladoc doesn't link to javadoc.  Regardless, I believe the changes by @indrajitr fix this by running javadoc on Java sources and scaladoc on Java sources (the changes are slated for 0.12.0).  Indrajit, please reopen if I'm wrong here.

**Comment by indrajitr** [comment]
scaladoc runs on both Scala and Java sources for the reason @harrah mentioned. That part is not going to change with 0.12.0.

@espringe, in this particular case, I think you would need to provide type parameter to `PartianFunction` and `Function1`. FWIW, I could compile through by providing type parameters `<scala.collection.immutable.List<String>, T>` in line 48 and line 60.

**Comment by espringe** [comment]
Thanks @indrajitr although adding type parameters is getting scaladoc to work -- it breaks javac from compiling. I've yet to find a combination of type parameters that works with javac and scaladoc (only for the function "orElse" the rest is fine)

**Comment by indrajitr** [comment]
@espringe, indeed, `orElse` would require appropriate co and contra variance mapping :) I would guess it is more of a Scala - Java interoperability problem and less of a problem with SBT. Build tool like SBT shouldn't come in the way of what compiler wants to do.

**Comment by harrah** [comment]
@indrajitr Thanks for the correction on scaladoc+Java sources.

@espringe if you want better control, you should probably put the Java sources in a separate project or some other customization.  (Use the mailing list if you have questions.)
