### ISSUE TITLE
sbt-datatype: more natural JSON encoding of ADTs

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2811]
## steps

Suppose interface `Fruit`, and record `Apple` and `Orange`.
## expectation

I can encode it as:

``` json
{ "type": "apple", "kind": "honeycrisp" }
```

using a configurable field as the splitter (in this case `type`).

**Comment by ritschwumm** [comment]
you can use "" instead of "type" and be pretty sure it will not ever clash with a field name.

**Comment by eed3si9n** [comment]
This is now done
