### ISSUE TITLE
Docs inconsistent about where to put sonatype.sbt

### ISSUE THREAD

**Issue by ryan-williams** [sbt/sbt#2815]
## steps
- http://www.scala-sbt.org/release/docs/Using-Sonatype.html#Fourth+-+Adding+credentials says `~/.sbt/0.13/sonatype.sbt`
- http://www.scala-sbt.org/release/docs/Using-Sonatype.html#%7E%2F.sbt%2Fsonatype.sbt says `~/.sbt/sonatype.sbt`.
## problem

the latter doesn't seem to work
## expectation

the latter should match the former

**Comment by dwijnand** [comment]
It doesn't say `~/.sbt/sonatype.sbt` any more. (Fixed in https://github.com/sbt/website/commit/72ae10c25bb248c469a64c4ed0b864674df25556?)
