### ISSUE TITLE
sbt 0.13.13.tgz has a different directory layout than 0.13.12.tgz

### ISSUE THREAD

**Issue by graingert** [sbt/sbt#2816]
(See the guidelines for contributing, linked above)

## steps
```
export SBT_VERSION='0.13.12'
cp ./sbt.pub /tmp/sbt.pub
curl -fSL https://dl.bintray.com/sbt/native-packages/sbt/$SBT_VERSION/sbt-$SBT_VERSION.tgz -o sbt.tgz \
                 https://dl.bintray.com/sbt/native-packages/sbt/$SBT_VERSION/sbt-$SBT_VERSION.tgz.asc -o sbt.tgz.asc \
    && export GNUPGHOME="$(mktemp -d)" \
    && gpg --import /tmp/sbt.pub \
    && rm /tmp/sbt.pub \
    && gpg --batch --verify sbt.tgz.asc sbt.tgz \
    && rm -r "$GNUPGHOME" sbt.tgz.asc \
    && tar -zxC /root/ -f sbt.tgz \
    && rm sbt.tgz
export PATH="/root/sbt/bin:$PATH"
```

Works, but
## problem

If you set SBT_VERSION to 0.13.13 it doesn't because the directory has been renamed from 'sbt' to `sbt-launcher-0.13.13`

## expectation

I expect the directory layout to be the same

## notes

otherwise I'd consider it a semver break.

**Comment by eed3si9n** [comment]
Thanks for the report. I wonder if it's related to our bumping up sbt-native-packager.

**Comment by graingert** [comment]
although if you change it back, you're going to break me again, as I've now updated to the new path.

**Comment by dwijnand** [comment]
@eed3si9n Yes, I believe that is correct. The same happened to @fommil in Ensime for Windows: https://github.com/ensime/ensime-server/pull/1632

**Comment by graingert** [comment]
can you restore the old structure?

**Comment by eed3si9n** [comment]
On Mac, the old one expanded to a directory named "sbt".
New one is now called "sbt-launcher-packaging-0.13.13". This is the problem right?

I think we should change it back to "sbt".

**Comment by dwijnand** [comment]
I'm not familiar with sbt-native-packager, but I've started a conversation with @muuki88 to try and fix this post-upgrade, for the next release.

**Comment by graingert** [comment]
@eed3si9n this isn't for macOs, this is on a Linux machine

**Comment by eed3si9n** [comment]
My recommendation would be to fix soon and release 0.13.13.1.tgz.

**Comment by eed3si9n** [comment]
In the meantime, could we come up with a workaround to buffer this change? http://unix.stackexchange.com/questions/11018/how-to-choose-directory-name-during-untarring

**Comment by graingert** [comment]
I'm using `export PATH="/root/sbt-launcher-packaging-$SBT_VERSION/bin:$PATH"`

**Comment by muuki88** [comment]
I haven't had the time yet to look at the new sbt release. Can I reproduce this behaviour when I publish sbt locally from the `0.13` branch and upgrade native-packager?

**Comment by eed3si9n** [comment]
@muuki88 here's the repo - https://github.com/sbt/sbt-launcher-package/blob/master/CONTRIBUTING.md. start sbt with something like

```
$ sbt -Dsbt.build.version=0.13.13
```

**Comment by muuki88** [comment]
I submitted a PR (https://github.com/sbt/sbt-launcher-package/pull/127)

**Comment by eed3si9n** [comment]
This is now fixed, I think.

**Comment by graingert** [comment]
@eed3si9n nope it's still in sbt-launcher-packaging-$SBT_VERSION can you reopen until you upload a 3.13 that's not a semver break?
