### ISSUE TITLE
Cannot access an artifactory repo protected by HTTP basic authentication on Windows

### ISSUE THREAD

**Issue by salimfadhley** [sbt/sbt#2817]
I'm trying to use sbt behind a corporate firewall. The only access to the outside world is via an Artifactory installation. After setting up a ~/.sbt/repositories file I was initially able to bootstrap SBT and subsequently download any artifacts I needed for my project... unfortunately when I switched on HTTP basic-auth on thiis server things started to fail.

When I run sbt I see the following error message:

`[error] Unable to find credentials for [Artifactory Realm @ xx.bigco.com].

Naturally there's a ~/.sbt/,credentials file whose content looks like:

```
realm=Artifactory Realm
host=xx.bigco.com
user=<my username>
password=<my password>
```
`
## problem

Looking through the trace there's no evidence that the .credentials file was being read. There's no evidence that the credentials are being used.

I'm pretty sure that Artifactory is working - I was able to verify that it failed with a consistent error when I fail to provide authentication.

```
(venv35) username@hostnameC:\Users\<username>\workspace\scala_playspace
> curl http://xx.bigco.com:8081/artifactory/virtual-sbt/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml
{
  "errors" : [ {
    "status" : 401,
    "message" : "Authentication is required"
  } ]
}
```

But when I hit the exact same repo with credentials, everything seems fine:

```
(venv35) username@hostname C:\Users\<username>\workspace\scala_playspace
> curl http://xx.bigco.com:8081/artifactory/virtual-sbt/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml -u <username>:<password>
<?xml version="1.0" encoding="UTF-8"?>
<ivy-module version="2.0" xmlns:e="http://ant.apache.org/ivy/extra">
```

But when I try the exact same thing in sbt:

```
[error] Unable to find credentials for [Artifactory Realm @ xx.bigco.com].
[debug] CLIENT ERROR: Unauthorized url=http://xx.bigco.com:8081/artifactory/virtual-sbt/org/scala-lang/scala-compiler/2.10.6/scala-compiler-2.10.6.pom
```

Here is the same issue on StackOverflow: http://stackoverflow.com/questions/40224921/sbt-is-unable-to-find-credentials-when-attempting-to-download-from-an-artifactor

**Comment by ngbinh** [comment]
We are having the same issue. Not sure if there is a work around?

**Comment by memelet** [comment]
Really, can this be an open bug with no workaround?

**Comment by daologger** [comment]
I struggled with the same problem for several hours. Then [this gist](https://gist.github.com/is/7453145) saved my day.
We have a artifactory repo that needs authentication. The `repositories` file is properly configured like this:
```
[repositories]
local
maven-local
my-ivy-proxy-releases: http://mydomain.com/artifactory/sbt/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
my-maven-proxy-releases: http://mydomain.com/artifactory/sbt/
```

Also, we've created a `.credentials` file, `~/.sbt/.credentials`:

```
realm=Artifactory Realm
host=mydomain.com
user=<your-username>
password=<your-password>
```

Still, running `sbt` would still fail. According to [the gist](https://gist.github.com/is/7453145), add `SBT_CREDENTIALS` to env:

```bash
export SBT_CREDENTIALS=${HOME}/.sbt/.credentials
```

Now run `sbt` commands and see how magic happens.

--------------------

I noticed that [this comment](https://github.com/sbt/sbt/issues/2627#issuecomment-221162094) in #2627 referred to the same env.

**Comment by michaelahlers** [comment]
Is it possible to provide credentials to SBT for bootstrapping _without_ setting an environment variable? Say, by adding a `credentials.sbt` to a location in `$HOME/.sbt`? Setting in the environment is fine for CLI usage, but may not (easily) work with an IDE.

**Comment by wawaberry** [comment]
I tried above steps and still do not see my creds passing to private artifactory in pod logs.  client NA from my IP.   any updates to this old issue?

**Comment by eed3si9n** [comment]
Currently both sbt launcher and sbt it self uses some version of Couriser to resolve sbt and the dependency graph of the subprojects, and they should both have mechanism to accept HTTP basic auth. I'm going to close this for now, but it this issue is still relevant, please open a new one.
