### ISSUE TITLE
Good theory, but how do I get the library

### ISSUE THREAD

**Issue by francisl** [sbt/sbt#282]
I read all the https://github.com/harrah/xsbt/wiki/Getting-Started-Library-Dependencies

I defined as written a few library that I need.

But after all that time spend, I have no idea how to make sbt to download them ...

**Comment by eed3si9n** [comment]
The general questions probably should be thrown to the [Google Group](https://groups.google.com/forum/#!forum/simple-build-tool).
The libraries would be downloaded automatically when you reload the project, and compile the code. The jars would be part of the classpath during compilation.
