### ISSUE TITLE
Publish debian archive for 0.13.13

### ISSUE THREAD

**Issue by jodersky** [sbt/sbt#2820]
I have installed sbt via the bintray debian archive. Whilst trying the `sbt new` command introduced in sbt 0.13.13, I realized that it wasn't available, even after an `apt upgrade`. Checking the archive, it does not contain the latest version.

## steps
Follow the download steps for Debian [here](http://www.scala-sbt.org/download.html)

## problem
The [archive](http://dl.bintray.com/sbt/debian/) does not contain the latest sbt version.

## expectation
The archive should contain a `sbt-0.13.13.deb` and update the corresponding Packages file.

**Comment by eed3si9n** [comment]
Done. Could you try it now?

**Comment by jodersky** [comment]
Works now, thanks!
