### ISSUE TITLE
Feature Request: test:clean

### ISSUE THREAD

**Issue by ctataryn** [sbt/sbt#2825]
I've been in situations where I've upgraded a library in my project and have received several deprecation warnings. My typical workflow is to fix `src/main/scala` stuff first, and then tackle `src/test/scala`. 

I refactor the main code by running `~;clean;compile`, fixing each error/deprecation warning displayed on the console. Similarly I'd like to tackle the test code by running `~;test:clean;test:compile`. However, it appears that `test:clean` is just an alias for `clean` because when I run `test:compile` I see it re-compiling all the `src/main/scala` classes as well, where I only wanted the `src/test/scala` classes to be recompiled so as to show all the deprecations/errors remaining in the test classes.

Is it possible to add a true `test:clean` task to sbt?

**Comment by yarulan** [comment]
+1

**Comment by laughedelic** [comment]
I think https://github.com/sbt/sbt/pull/3678 implements exactly what you want. There was some argument about correct scoping for this, so you may want to add your opinion to the discussion.

P.S. I don't know how I encountered this old issue, I thought it's a new one 😅

**Comment by eed3si9n** [comment]
sbt 1.3.0 implements this.
