### ISSUE TITLE
Change ivy-releases to direct URL

### ISSUE THREAD

**Issue by pauldraper** [sbt/sbt#2830]
```
$ curl -L -I https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.12/jars/main.jar
HTTP/1.1 302 Moved Temporarily
Content-Length: 160
Content-Type: text/html
Date: Mon, 14 Nov 2016 17:37:06 GMT
Location: https://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.12/jars/main.jar
Server: nginx/1.8.0
Connection: keep-alive

HTTP/1.1 200 OK
Server: nginx
Date: Mon, 14 Nov 2016 17:39:33 GMT
Content-Type: application/java-archive
Content-Length: 2591547
Connection: keep-alive
Last-Modified: Sat, 16 Jul 2016 03:56:40 GMT
Accept-Ranges: none
ETag: 7b6954a099451d9fe124bcaaf815115d9357dab3fe5d8b22912c4b1e5d1affd0
X-Checksum-Sha1: 6c346ceae480ee26811a617371c80a7136e47670
X-Checksum-Sha2: 7b6954a099451d9fe124bcaaf815115d9357dab3fe5d8b22912c4b1e5d1affd0
```

Since ivy resolves synchronously and (it appears to me) without keep-alives and SSL session caching, redirecting every request *significantly* affects overall resolution time. Back of the envelope is 0.5s/request * 150 requests = a minute just for resolving SBT.

The ivy releases URL should be changed to dl.bintray.com. (Alternatively, the admins for repo.typesafe.com could just make it a CNAME.)

**Comment by eed3si9n** [comment]
I don't think we should use the direct URL as we don't want to permanently commit to using Bintray. (We've switched from Artifactory Online to Bintray in the past)

It would make sense for Network API to cache the redirection rule somehow tho.
https://github.com/sbt/sbt/issues/2189

**Comment by eed3si9n** [comment]
Closing this as won't fix for now.
Hopefully not a huge issue now that sbt core artifacts are on Maven Central and only plugins remain on Bintray.
