### ISSUE TITLE
sbt new leaves behind target litter

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2835]
## steps

1. sbt new scala/scala-seed.g8

## problem

As pointed out by @dwijnand (https://github.com/sbt/sbt/pull/2780#discussion_r83523717) and @djspiewak (https://twitter.com/djspiewak/status/798976727095635968), new command leaves behind unwanted `target/` directory. 

## expectation

No mess.

**Comment by djspiewak** [comment]
In case people find this via google, the following is a perfectly reasonable workaround:

``` sbt
import java.io.File

target := {
  val buildSbt = baseDirectory.value / "build.sbt"
  val projectSbt = baseDirectory.value / "project.sbt"
  val project = baseDirectory.value / "project"

  if (buildSbt.exists() || projectSbt.exists() || project.exists())
    target.value
  else
    new File("/tmp") / "sbt" / sbtVersion.value / "target"
}
```

Put this in `~/.sbt/0.13/target-relocate.sbt` and all will be well.

**Comment by dwijnand** [comment]
@paulp Has come up with a different workaround https://gist.github.com/paulp/ba9bd0b5808a808c67cbd2bb9db08005

**Comment by note** [comment]
I observed that `g8 scala/scala-seed.g8` there's no such issue. g8 version:

```
> g8 --version
g8 0.10.0
```

**Comment by note** [comment]
Ah, probably it does not matter as `target` is probably leftover from sbt itself (I guess that `g8` just creates temporary dir for cloned repo)

**Comment by SethTisue** [comment]
this came up on Gitter again today (from a language newcomer). idk about priority relative to everything else, but a fix would help give a good first impression.

**Comment by eed3si9n** [comment]
Fixed in #4033

**Comment by vamanose** [comment]
New to SBT, so pardon the question.

Is it normal for SBT to create a new "project" and "target" folder for every new SBT project created using:

$ sbt new sbt/scala-seed.g8

**Comment by SethTisue** [comment]
@vamanose make sure you're using sbt 1.1.2 or later, that's when the fix landed

re: getting help as a new sbt user, see https://www.scala-sbt.org/support.html
