### ISSUE TITLE
scalafmt still broken in 0.13.14-SNAPSHOT

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#2837]
## steps

1. `publishLocal` sbt 0.13.14-SNAPSHOT. I built it off of a58b184.
2. Run `sbt new djspiewak/base.g8`
3. Change `sbt.version` in `project/build.properties` to `0.13.14-SNAPSHOT`
4. Add `addSbtPlugin("com.geirsson" % "sbt-scalafmt" % "0.4.10")` to `project/plugins.sbt`
5. Remove references to 'coursier' in `build.sbt` and `project/plugins.sbt` (to remove potential feature interaction)
3. Run `scalafmt`

## problem

`scalafmt` still very broken:

```
> scalafmt
[info] Formatting 3 Scala sources {file:/s/unmediate/}unmediate ...
[trace] Stack trace suppressed: run last compile:scalafmt for the full output.
[error] (compile:scalafmt) java.lang.NoClassDefFoundError: Could not initialize class org.scalafmt.config.ScalafmtConfig$
[error] Total time: 0 s, completed 16-Nov-2016 23:41:30
```

## expectation

Not broken.

## notes

i.e. #2827 didn't fix it

**Comment by eed3si9n** [comment]
It seems to be slightly different error message than what's mentioned in https://github.com/sbt/sbt/issues/2786:

```
[error] Modules were resolved with conflicting cross-version suffixes in {file:/Users/heiko/projects/scala/new-in-scala-212/}new-in-scala-212:
[error]    org.scala-lang.modules:scala-xml _2.11, _2.12.0-RC1

OR

java.lang.NoClassDefFoundError: scala/Product$class
    at org.scalafmt.config.Docstrings$ScalaDoc$.<init>(Docstrings.scala:8)
    at org.scalafmt.config.Docstrings$ScalaDoc$.<clinit>(Docstrings.scala)
    at org.scalafmt.config.ScalafmtConfig$.apply$default$2(ScalafmtConfig.scala:2)
    at org.scalafmt.config.Settings$class.$init$(Settings.scala:17)
    at org.sc
```

**Comment by dwijnand** [comment]
https://github.com/lucidsoftware/neo-sbt-scalafmt is a thing, but also sbt-scalafmt just got a rewrite: https://github.com/scalameta/scalafmt/pull/1085. So I think this issue is no longer valid.

**Comment by olafurpg** [comment]
FYI The new sbt-scalafmt plugin will be sbt 1.0 only.
