### ISSUE TITLE
Stuck at "Getting org.scala-sbt sbt 0.13.13" running sbt behind sock5 proxy

### ISSUE THREAD

**Issue by markhuyong** [sbt/sbt#2839]
Run sbt stuck at "Getting org.scala-sbt sbt 0.13.13"

## steps
-  install sbt 0.13.13 with Homebrew
-  run sbt -v in console behind sock5 proxy

## problem

Output "Getting org.scala-sbt sbt 0.13.13".
then stuck with no response

I try this, make no sense.
- [Stuck at "Getting org.scala-sbt sbt 0.13.11" · Issue #2602 · sbt/sbt](https://github.com/sbt/sbt/issues/2602)

## notes
config in ` /usr/local/etc/sbtopts`
```bash
-Dsbt.override.build.repos=true
-Dsbt.repository.secure=false

```

verbose log:
[process_args] java_version = '1.8.0_31'
# Executing command line:
java
-Xms1024m
-Xmx1024m
-XX:ReservedCodeCacheSize=128m
-XX:MaxMetaspaceSize=256m
-Dsbt.override.build.repos=true
-Dsbt.repository.secure=false
-jar
/usr/local/Cellar/sbt/0.13.13/libexec/sbt-launch.jar

Getting org.scala-sbt sbt 0.13.13 ...

**Comment by eed3si9n** [comment]
We use GitHub issue mostly to track bugs and tasks on sbt development. If you need help, please check this out - https://www.scala-sbt.org/support.html
