### ISSUE TITLE
Increase the magic number for RichTaskableN and ApplyN

### ISSUE THREAD

**Issue by hseeberger** [sbt/sbt#284]
Right now there is a limit of 9. Why not go for 22 like Scala's tuples?
And no, I really have a use case lacking a natural structure for breaking down the settings into segments.
Actually this looks like a trivial (yet cumbersome) contribution. Would be glad to help via a pull request.

**Comment by holdenk** [comment]
I'm coding this up right now, I'll send a pull request when I'm done :)

**Comment by harrah** [comment]
@holdenk unless you've already got it done, I have a branch locally to bump it up to 12 (more will have to wait for a different approach).

**Comment by holdenk** [comment]
@harrah I wrote a script to generate the additional code so I've also got a branch with it (for up to 15).
