### ISSUE TITLE
sbt new should launch sbt after creating project

### ISSUE THREAD

**Issue by adriaanm** [sbt/sbt#2840]
## steps
```
$ sbt new $someTemplate
```

## problem
Once this is done, need to cd into the new directory (first need to figure out what it's called) and run sbt again.

## expectation
I end up in an sbt shell immediately after `sbt new` completes.

**Comment by eed3si9n** [comment]
This would be a useful enhancement to sbt and Giter8 cooperation.

**Comment by eed3si9n** [comment]
`*.local` templates added in https://github.com/sbt/sbt/pull/7228:
- creates a build on the same directory, and
- launches into sbt session immediately
so I'd claim that as a win
