### ISSUE TITLE
Let me configure Ivy cache

### ISSUE THREAD

**Issue by mikesperber** [sbt/sbt#2845]
## problem

I'd like to configure a project-local Ivy cache. (Some people working on the project don't have direct Internet connectivity, hence the Ivy cache gets checked into the repo.)

## expectation

I'd expect there some way to configure this in SBT directly. However, this:

http://stackoverflow.com/questions/3142856/how-to-configure-ivy-cache-directory-per-user-or-system-wide

... only shows how to configure it user- or system-wide.

I can use `externalIvSettings`, but that causes resolution to fail sometimes when the `inter-project` resolver is in there. (I.e. resolution fails when `inter-project` is in there, works when I comment it out.)

**Comment by dwijnand** [comment]
you can, along with other jvm options, setup `sbt.ivy.home` in either .jvmopts or .sbtopts.
