### ISSUE TITLE
Sbt does not resolve dependencies with classifiers.

### ISSUE THREAD

**Issue by anikifoss** [sbt/sbt#285]
There are multiple problems here. First of all, having "org.lwjgl.lwjgl" % "lwjgl-platform" % lwjglVersion" should be enough to download all the artifacts. But it does not work.

Having failed that, manually putting all the artifact as a dependencies also fails, because only one of those is downloaded and the rest is ignored. The choise appears to be arbitrary.
Surpisingly listing only one artifact works.

Here is the build:

``` scala
import sbt._
import Keys._


object MyBuild extends Build {

  val lwjglVersion = "2.8.2"

  lazy val broken = Project(
    id = "broken",
    base = file("."),
    settings = Defaults.defaultSettings ++ Seq(
      scalaVersion := "2.9.1",
      target := new File("target/broken"),
      libraryDependencies += "org.lwjgl.lwjgl" % "lwjgl-platform" % lwjglVersion classifier "natives-windows",
      libraryDependencies += "org.lwjgl.lwjgl" % "lwjgl-platform" % lwjglVersion classifier "natives-linux",
      libraryDependencies += "org.lwjgl.lwjgl" % "lwjgl-platform" % lwjglVersion classifier "natives-osx"
    )
  )

  lazy val working = Project(
    id = "working",
    base = file("."),
    settings = Defaults.defaultSettings ++ Seq(
      scalaVersion := "2.9.1",
      target := new File("target/working"),
      libraryDependencies += "org.lwjgl.lwjgl" % "lwjgl-platform" % lwjglVersion classifier "natives-linux"
    )
  )
}
```

**Comment by indrajitr** [comment]
Although Ivy (and thus SBT) doesn't prevent you from doing this in the DSL, AFAIK having multiple classifier for a dependency is incorrect according to Maven. Thus in this case, Ivy is just retaining one of the libraries in the dependency list and discarding the others. In the second case, everything works perfectly because there is no ambiguity to resolve.

**Comment by anikifoss** [comment]
Here is the pom in question, it seems to be using multiple classifiers:
http://repo1.maven.org/maven2/org/lwjgl/lwjgl/lwjgl/2.8.2/lwjgl-2.8.2.pom

I do not have much experience with maven, so I am wondering if the pom is incorrect. If so, why does maven allow to publish it.

**Comment by indrajitr** [comment]
Maven doesn't allow multiple classifier in _one_ dependency. Thus you cannot have two `<classifier/>` elements within one `<dependency> ... ... </dependency>` block. But it is fine to have multiple dependencies having everything same except the `<classifier/>` block (since classifier is part of resolution). In Ivy, I suspect, the first part is honored, but not the second part.

**Comment by anikifoss** [comment]
Indeed, ivy is to blame. It allows multiple dependency elements with artifacts that have different classifiers. However it does not resolve them properly. Here is a sample ivy config that fails to retrieve all the dependencies:

```
<ivy-module version="2.0" xmlns:m="http://ant.apache.org/ivy/maven">
    <info organisation="test" module="test"/>
    <dependencies>
        <dependency org="org.lwjgl.lwjgl" name="lwjgl-platform" rev="2.8.2">
            <artifact name="lwjgl-platform" type="jar" ext="jar" m:classifier="natives-windows"/>
        </dependency>
        <dependency org="org.lwjgl.lwjgl" name="lwjgl-platform" rev="2.8.2">
            <artifact name="lwjgl-platform" type="jar" ext="jar" m:classifier="natives-linux"/>
        </dependency>
        <dependency org="org.lwjgl.lwjgl" name="lwjgl-platform" rev="2.8.2">
            <artifact name="lwjgl-platform" type="jar" ext="jar" m:classifier="natives-osx"/>
        </dependency>
    </dependencies>
</ivy-module>
```

My workaround was to create multiple bogus projects, each having one dependency with classifier.

I am guessing the only way to patch this at the SBT level would be to make Ivy do several resolution runs, one for each dependency with a classifier. Not a clean approach to say the least, so I wouldnt be surpised if this remains unresolved until Ivy fixes it.

**Comment by harrah** [comment]
While you're testing an Ivy file, what happens if you put all of the artifact definitions under a single <dependency> element?

**Comment by anikifoss** [comment]
Good catch, it works as expected! Here is the working Ivy.xml:

```
<ivy-module version="2.0" xmlns:m="http://ant.apache.org/ivy/maven">
    <info organisation="test" module="test"/>
    <dependencies>
        <dependency org="org.lwjgl.lwjgl" name="lwjgl-platform" rev="2.8.2">
            <artifact name="lwjgl-platform" type="jar" ext="jar" m:classifier="natives-windows"/>
            <artifact name="lwjgl-platform" type="jar" ext="jar" m:classifier="natives-linux"/>
            <artifact name="lwjgl-platform" type="jar" ext="jar" m:classifier="natives-osx"/>
        </dependency>
    </dependencies>
</ivy-module>
```

I have constructed the original, broken Ivy.xml using snippets from the cached ivy files. Those are auto-generated from the pom files. So the problem must be in the code that translates .pom into ivy.xml.

**Comment by harrah** [comment]
Ok, the equivalent inline syntax is:

``` scala
libraryDependencies += 
  "org.lwjgl.lwjgl" % "lwjgl-platform" % lwjglVersion classifier "natives-windows" classifier "natives-linux" classifier "natives-osx"
```

If this works, I propose that the solution to this issue is to mention this in the documentation.

**Comment by anikifoss** [comment]
libraryDependencies +=  "org.lwjgl.lwjgl" % "lwjgl-platform" % lwjglVersion classifier "natives-windows" classifier "natives-inux" classifier "natives-osx"

It works. Having the documentation mention it would definitly solve the issue.

**Comment by harrah** [comment]
Alright, fixed.

**Comment by tobidelbruck** [comment]
Thanks  a lot for this useful thread. It solves the problem also with usb4java, which requires multiple classifiers for the various native libraries. For usb4java, the workaround is to use

 ```
<dependency org="org.usb4java" name="libusb4java" rev="1.2.0">
            <artifact name="libusb4java" type="jar" ext="jar" m:classifier="osx-x86_64"/>
            <artifact name="libusb4java" type="jar" ext="jar" m:classifier="osx-x86"/>
            <artifact name="libusb4java" type="jar" ext="jar" m:classifier="windows-x86_64"/>
            <artifact name="libusb4java" type="jar" ext="jar" m:classifier="windows-x86"/>
            <artifact name="libusb4java" type="jar" ext="jar" m:classifier="linux-arm"/>
            <artifact name="libusb4java" type="jar" ext="jar" m:classifier="linux-x86_64"/>
            <artifact name="libusb4java" type="jar" ext="jar" m:classifier="linux-x86"/>
        </dependency>
```

_xmlns:m="http://ant.apache.org/ivy/maven"_ in the ivy module definition is somehow needed since simply specifying a classifier for each artifact causes an exception.
