### ISSUE TITLE
Allow junit test-reports folder to be more finely configured

### ISSUE THREAD

**Issue by ashleymercer** [sbt/sbt#2853]
## Steps

- follow instructions to [create a separate integration test phase](http://www.scala-sbt.org/1.0/docs/Testing.html#Integration+Tests)
- create a simple unit test under `src/test/scala`
- create a simple integration test under `src/integration/scala`
- run both test phases e.g. `sbt test it:test`

## Problem

Junit XML is generated for both tests under target/test-reports. However:

1. there is no obvious (or documented) way to have the reports placed in a different folder. After hunting around the code base, I figured out the following by trial and error:

```scala
testListeners in IntTest := Seq(new JUnitXmlTestsListener("target/integration-report"))
```

This is useful to be able to separate test reports from different test phases so that they can be reported on independently.

2. the JUnitXmlTestsListener always places XML files in a subfolder of the given path called "test-reports", see [the source code](https://github.com/sbt/sbt/blob/57a655478f2fdf1de3e90acf2755b50c0459fd50/testing/src/main/scala/sbt/JUnitXmlTestsListener.scala#L25)

```scala
/**The dir in which we put all result files. Is equal to the given dir + "/test-reports"*/
val targetDir = new File(outputDir + "/test-reports/")
```

so in (1) above the actual output path is target/integration-report/test-reports, which is not what I want.

## Expectation

- save XML reports to the specified folder, and not to a hardcoded subfolder `test-reports`
- include at least a brief mention of JUnitXmlTestsListener and how to use it in the ["Testing > Output"](http://www.scala-sbt.org/0.13/docs/Testing.html#Output) section of the manual
- alternatively, provide a way to more directly configure the output path for each test phase

**Comment by vm-udayya** [comment]
Hi Team, I have a use case and have issue in getting the consolidated report at the final stage due to this issue
sbt clean coverage test coverageReport -- generate unit res and places on test-reports
sbt clean coverage it:test coverageReport-- generate it res and places on test-reports
and finally I wanted an aggregated report
sbt coverageReport coverageAggregate ---> This pick only last integration results doesn't have unit results due to the reports saving in same folder which is hardcoded in sbt.

**Comment by ashleymercer** [comment]
Gosh, this is getting rather elderly! 

@eed3si9n I would be willing to have a go at a PR for this with some guidance - I assume a requirement is going to be to maintain backwards-compatibility with the current behaviour? If so I'd suggest something like 

- adding another setting (!) which exposes `targetDir` directly (and defaults to `outputDir + "/test-reports"`)? 

- or else we could expose the `"/test-reports"` value as a setting (and make it clear that internally we use the concatenation of the two) so that I and others could then set this value to `""`

Thoughts?

**Comment by AlexisBRENON** [comment]
No idea what is the best solution but this feature could be nice, at least to separate test results from integration test results.

**Comment by eed3si9n** [comment]
@ashleymercer sorry I didn't see the comment earlier.

I guess we can think of `test-reports` as dependency configuration name + `-report`, and generalize it based on the principle. `IntegrationTest` should then be `/it-reports` automatically.
