### ISSUE TITLE
`show` and `set` should accept the same syntax

### ISSUE THREAD

**Issue by dragos** [sbt/sbt#2860]
In the Sbt console, `show` and `set` should accept the same syntax for settings.

## steps

```
> show dotty-library/*:scalacOptions 
[info] * -feature
[info] * -deprecation
[info] * -encoding
[info] * UTF8
[info] * -language:existentials,higherKinds,implicitConversions
[success] Total time: 2 s, completed Dec 3, 2016 4:34:16 PM
> set dotty-library/*:scalacOptions  := "-verbose"
<set>:1: error: unclosed comment
dotty-library/*:scalacOptions  := "-verbose"
             ^
[error] Error parsing expression.  Ensure that there are no blank lines within a setting.
> 
```

## expectation

I'd expect the syntax used to show a setting should work for setting it.

**Comment by eed3si9n** [comment]
I'd say this is a variant of https://github.com/sbt/sbt/issues/1812.

**Comment by dragos** [comment]
That's definitely the root of it. I wonder if there's value in fixing this more modest manifestation of it. 

Is it part of the current design to refer to settings in two different ways when showing and when setting them, meaning this can't be fixed without the overall unification in #1812? If the answer is "not without overall unification", feel free to close this.

Note the interesting coincidence (`/*` being the beginning of a Scala comment) and the fact that it's an error only in `set`.

**Comment by eed3si9n** [comment]
`show` command has higher affinity with command invocation in the sbt shell than to `set`.
The shell notation (`test:compile`, `*:scalacOptions` etc.) supports tab completion and input args.
So changing the behavior of `show` I think should coincide with changing the shell notation altogether.

`set` has affinity with `build.sbt`.

One thing that's potentially possible to provide a third command, like `get` that uses `build.sbt` notation, like `set`. That's something a plugin could potentially provide as an experiment.

**Comment by dragos** [comment]
I understand there are implementation details that explain this behavior. My bug report was purely from a usability point of view. A moderately experienced user, IMO, won't be able to figure our how to get around this error (I couldn't, I couldn't find this in the Sbt Reference either). I strongly believe that the notation used to refer to an entity should be the same in reading and writing it.

If that is not the case, what "show" prints out should point to the syntax for changing it. For instance, at the end of "show" you can add "Use `set <??? scalacOptions ???> := <newValue>` to change this setting".

My 2c.

**Comment by eed3si9n** [comment]
`set` and `show` can accept slash syntax using sbt 1.1.0-RC4:

```
> show root/scalacOptions
[info] *
[success] Total time: 1 s, completed Jan 3, 2018 3:50:26 PM
> set root/scalacOptions += "-feature"
```

or `root/Zero/scalacOptions` if you want to capture `*:scalacOptions`.

Ref https://github.com/sbt/sbt/pull/3434
