### ISSUE TITLE
SBT incorrectly enforces improper version of a Maven dependency in case of usage of <dependencyManagement>

### ISSUE THREAD

**Issue by pshirshov** [sbt/sbt#2861]
I guess it's an Ivy issue, so here is the description: https://issues.apache.org/jira/browse/IVY-1551

Probably it may be resolved at SBT level as well, so I'm opening a ticket here.

**Comment by eed3si9n** [comment]
I am not sure if this is a confirmed bug, but it's unlikely to be fixed by us if it's something to do with parent POM handling.
