### ISSUE TITLE
sbt maven interoperatbility

### ISSUE THREAD

**Issue by geoHeil** [sbt/sbt#2865]
## steps

Installing a maven project (e.g. https://github.com/dmlc/xgboost/tree/master/jvm-packages) via `mvn install` installs it to `~/.m2/repository/....` which sounds fine.

## problem 1
My resolver which is defined like resolvers += "Local Maven Repository" at "file:///" + Path.userHome + "/.m2/repository" is only picked up when defined in the main `build.sbt` and not if defined in the `plugins.sbt` file

## problem 2
Error Message is:` com.typesafe.akka#akka-actor_${scala.binary.version};2.3.11: not found` Could it be the problem, that the ${} is not resolved?

On Ubuntu, this does not happen. Rather, it tries to access the library at `~/.iviy2/local/..`. but only copied it to `~/.ivy2/cache/`

## expectation

Correct resolution of dependencies originally contained in `~/.m2/repository/...` folder

**Comment by geoHeil** [comment]
caused by https://github.com/dmlc/xgboost/issues/1858, but still this should produce a better error message.

**Comment by eed3si9n** [comment]
Not sure what the actual reported issue is here. Let me know if this is still a problem on the latest sbt 1.
