### ISSUE TITLE
macro tasks do not apply to the correct project

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#2866]
I have a "minimal" reproduction of a macro bug in

  https://github.com/fommil/sbt-big-project/pull/47

(minimal in the sense that I minimised the diff to my project that causes the bug).

It seems that by rewriting

```scala
private def dynamicTransitiveUpdateTask: Def.Initialize[Task[Seq[UpdateReport]]] =
    (thisProject, transitiveUpdate.theTask).flatMap {
      (proj, transitiveUpdateTask) =>
        val key = LocalProject(proj.id)
        val cached = transitiveUpdateCache.get(key)
        if (cached != null) task(cached)
        else (transitiveUpdateTask).map { calculated =>
          transitiveUpdateCache.put(key, calculated)
          calculated
        }
```

to

```scala
private def dynamicTransitiveUpdateTask: Def.Initialize[Task[Seq[UpdateReport]]] = Def.taskDyn {
    val key = LocalProject(thisProject.value.id)
    val cached = transitiveUpdateCache.get(key)
    if (cached != null) Def.task(cached)
    else Def.task {
      val calculated = transitiveUpdate.value
      transitiveUpdateCache.put(key, calculated)
      calculated
      }
  }
```

the `transitiveUpdate` doesn't seem to be applying to the same Project as before.

if you are confident that this is a bug in the api... it's probably a blocker for 1.0 since it means some old style tasks can't be migrated. Otherwise, I guess you'll say the tasks in dynamic tasks should explicitly list which project they should run in?

**Comment by jvican** [comment]
@eed3si9n @dwijnand What's the verdict here? I'm not that familiar with the sbt API, but this looks like a bug.

**Comment by dwijnand** [comment]
I've not triaged this issue here, but if I'm remembering correctly @jastice fixed the issue in @fommil's project at ScalaSphere. But I never saw the diff, nor can I find it now..

**Comment by jvican** [comment]
Interesting. Is it considered an implementation problem then? I'm curious to what happened to this in ScalaSphere :smile:.

**Comment by fommil** [comment]
No that was something else. This is still a bug in the macro semantics. Or, at least a subtlety.
