### ISSUE TITLE
Sbt problem with multiple scala versions 

### ISSUE THREAD

**Issue by geoHeil** [sbt/sbt#2869]
There is a warning in maven which results in an fatal issue with sbt. 

https://github.com/dmlc/xgboost/issues/1858

**Comment by akauppi** [comment]
@geoHeil You probably intended the issue to contain more details?

**Comment by geoHeil** [comment]
@akauppi https://github.com/dmlc/xgboost/issues/1858 more details are there Problem is that sbt is not interpreting properties set in a maven profile, only general properties are read.

**Comment by eed3si9n** [comment]
As of sbt 0.13.12, sbt will align Scala versions to whatever specified in `scalaVersion`.
I am closing this for now as resolved.

Ref https://github.com/sbt/sbt/pull/2634
