### ISSUE TITLE
Scream on accidental := usage

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#2870]
A feature request from @paulp (https://gitter.im/typelevel/general?at=58519daf589f411830e4ab74):

> Can sbt be made to scream about it if you use := and the previous occupant is a non-default value?

**Comment by eed3si9n** [comment]
As I wrote on the Gitter channel:

> `inspect scalacOptions` can show the defined position, so you might be able to track that way.

Another thing to consider is when the screaming kicks in. For example, a company or a project could write plugins that intentionally overwrite existing `scalacOption` values.
I could then call `enablePlugins(FooPlugin)` to pick and chose the features. It's hard to tell what's accidental here.

See also https://github.com/pfn/sbt-unused

**Comment by dwijnand** [comment]
Yeah.. interesting food for thought.. Add some flag to be explicit you're throwing the old value away? `:=` vs `:==` maybe?

Also, closely related to this issue, maybe we should allow `:==` in user-land (ie. make it public) and recommend it to be used in `globalSettings` when defining the default value for a brand-new key introduced by a plugin.

**Comment by eed3si9n** [comment]
Making `:==` public would be pouring fuel to the "sbt is too complicated / undocumented" fire.

**Comment by dwijnand** [comment]
Yeah.

In suggesting it I'm obviously biased, but I wonder, given:

* := is very common and reasonably well understood
* :== is only 1 char different than :=
* and it operates almost exactly like it
* we would only recommend it for plugins (when defining new keys)
* and we document it well

.. then maybe it's fine?

**Comment by dwijnand** [comment]
Another option is to put the definition of the default value of a key _in_ the key definition. Then `a :=b` would _only_ mean "redefine a to b".

Note that this couldn't just be the bare value `A`, it has to be an `Initialize[A]` as it's very common for the default value to be defined in terms of other keys.

Something like

```scala
val foo = settingKey[Int](
  "Do foo things with bar results",
  bar.value + 1
)
```

**Comment by Milyardo** [comment]
You could also make `:=` preserve references to the previous value, much like how `Append` shows all lines applying to a key, `:=` could do the same:

It could report something like

```
Defined by: Foo:12.  Replaces Bar:24, Baz:20
```
