### ISSUE TITLE
Unable to download jars for 0.13.13 from maven central or scala-sbt

### ISSUE THREAD

**Issue by meta-forte** [sbt/sbt#2871]
## steps
I installed scala 2.12.1 and sbt 0.13.13 on my windows office pc that's behind proxy.
I use our enterprise artifactory through which I have to download the jars and run sbt
sbt is failing to get the latest jars from maven central repo or scala-sbt
I searched in search.maven.org and I could not find the latest version /sbt-0.13.13.jar there..

Here is the error message I got:
Please could you advise how I can fix this.. 
Should I run a previous version of sbt with latest version scala..

  ==== my-maven-proxy-releases: tried

    https://artifactory/artifactory/maven-central/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.pom

    -- artifact org.scala-sbt#sbt;0.13.13!sbt.jar:

    https://artifactory/artifactory/maven-central/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.jar
  ==== my-maven-proxy-releases: tried

    https://artifactory/artifactory/maven-central/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.pom

    -- artifact org.scala-sbt#sbt;0.13.13!sbt.jar:

    https://artifactoryartifactory/maven-central/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.jar
          ::::::::::::::::::::::::::::::::::::::::::::::

          ::          UNRESOLVED DEPENDENCIES         ::

          ::::::::::::::::::::::::::::::::::::::::::::::

          :: org.scala-sbt#sbt;0.13.13: not found

          ::::::::::::::::::::::::::::::::::::::::::::::

**Comment by dwijnand** [comment]
The repo you want to add is https://repo.lightbend.com/typesafe/ivy-releases/

**Comment by meta-forte** [comment]
Hi, this repo is not accessible as I am behind the firewall. Pls could you advise if and when the latest scala, sbt jars be posted to maven central..

thank you

**Comment by dwijnand** [comment]
sbt has never published to Maven Central (there are a few recent 1.0.0 pre-releases published, because starting from 1.0.0 we'll published to Maven Central).

So you'll need to add that ivy repository to your Artifactory.

**Comment by meta-forte** [comment]
Got the URL added to our artifactory. It's working fine now.. thanks a lot
