### ISSUE TITLE
Where can i put my own external IvySettings?

### ISSUE THREAD

**Issue by zhengsg** [sbt/sbt#2876]
## problem
I want to put external IvySettings  and use it as the default ,how can i fix it? I didn't find it on the official
document. The officer document just provide externalIvySettings method. I know one way to repack sbt-launch.jar, but any other simple configuration way ?

**Comment by eed3si9n** [comment]
The sbt issue tracker is not a support system. Please see [how can I get help?](http://www.scala-sbt.org/community.html#how-can-I-get-help)
