### ISSUE TITLE
Feature request: fetch/launch artifact api (à la Coursier)

### ISSUE THREAD

**Issue by olafurpg** [sbt/sbt#2879]
## Problem

When writing an sbt build or plugin, fetching an artifact coordinate (moduleid) and then launching a main class from that classpath is currently difficult. It would be nice if it was as simple as using the [coursier command line interface](https://github.com/alexarchambault/coursier#command-line-1)

```bash
$ ./coursier fetch org.apache.spark:spark-sql_2.11:1.6.1
$ ./coursier launch com.lihaoyi:ammonite_2.11.8:0.7.0
$ ./coursier launch com.lihaoyi:ammonite_2.11.8:0.7.0 # jars are cached
```

### Potential use-cases

- wrap a command line tool into an sbt plugin, for example [scalafmt](https://olafurpg.github.io/scalafmt/#sbt)
- manually add a compiler plugin to `scalacOptions` with `-Xplugin:/path/to/jar`, for example scoverage and scalafix. I can't say why scoverage favors this approach over `addCompilerPlugin`. In scalafix, I bumped into
  1. problems because the scalafix compiler plugin has dependencies
  2. "ignoring duplicate plugin" warnings when I used `addCompilerPlugin`
  3. problems when I wanted to optionally enable the sbt plugin if `scalafixEnabled in Global := true` (same is true for `scoverageEnabled`).

Nice-to-have additional features on top of plain fetch/launch:
- classpath is cached between `launch` invocations to benefit from JIT
- custom in/out/err streams
- custom working directory (e.g., depending from which project the command/task was executed)

### Explored alternatives
 To my best knowledge, the idiomatic way to accomplish the same in sbt is to use `libraryDependencies += ModuleId` and then call `update.value`. You can use this trick in several ways and each of them have some caveats:

- build project in default configuration. Problems
  1. the dependency is a dependency to the project's application
  2. you need to support the defined scalaVersion in that project causing issues like 
https://github.com/sbt/sbt/issues/2786
  3. it's super slow (as in takes minutes) when testing on large cross-built (Scala.js) projects with `-SNAPSHOT` versions because you need to resolve the same locally published `-SNAPSHOT` version in every single project.
- build project in custom configuration. Problems:
  1. Problems 2 and 3 still apply from before.
  2. it requires quite a bit of ceremony to work (e.g., `configurations += config("foo").hide`).
- synthetic project (>0.13.13 only). Scalafmt and scalafix use this approach. Problems:
  1. you're still at the mercy of what `++$SCALA_VERSION` (https://github.com/olafurpg/scalafmt/issues/641) or `fork in ThisBuild` (https://github.com/olafurpg/scalafmt/issues/654) settings the user defines.
  1. you need to disable publishing for the synthetic projects
  2. requires quite a bit of ceremony, esp. if your cross-build to multiple scala versions.
  3. synthetic projects are silently ignored in sbt <0.13.13 causing cryptic error messages

Alternatively, I could use the coursier api to fetch and launch the jars myself. The downside to this is that
1. I still need to implement the `launch` (+ nice-to-have features) since the coursier cli is 2.11 only and
2. coursier pulls in dependencies like scalaz which can conflicts with other libraries on the build classpath.

cc/ @sjrd @alexarchambault

**Comment by dwijnand** [comment]
There is not-really-public, bit-of-a-pain API to do this right now. And in sbt 1 we can build a proper API in sbt/librarymanagement to provide this.

Good issue Olaf, thank you for opening it. I've seen this need.

**Comment by hseeberger** [comment]
+1

**Comment by fommil** [comment]
the obligatory ensime workaround https://github.com/ensime/ensime-sbt/blob/2.0/src/main/scala/CoursierHelper.scala

**Comment by dwijnand** [comment]
I wonder to what degree this issue is solved with the API now available in lm: https://github.com/sbt/librarymanagement/blob/v1.0.0-RC3/README.md

**Comment by olafurpg** [comment]
@dwijnand That seems to be the API I am missing in 0.13, thanks.

For a 0.13 workaround, I recommend using coursier like @fommil links above.
