### ISSUE TITLE
Create a config-something macro to create a config

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#2890]
In the spirit of the `project`, `settingKey`, `taskKey` and `inputKey` macros, create a `config-something` macro to avoid this duplication:

```scala
val Foo = config("foo")
```

@eed3si9n WDYT?

**Comment by eed3si9n** [comment]
You mean like:


```scala
lazy val Compile = config
```

I think it makes sense.

**Comment by dwijnand** [comment]
Yep. Except we'd have to pick another name.

Unless you want to recover that name in 1.0 (deprecate/rename in 0.13).

**Comment by eed3si9n** [comment]
We just need to be source compat, so can't we overload `def config`?

**Comment by dwijnand** [comment]
Oh yeah.. overloading :-)

lol, I've been avoiding overloading that I actually forgot it was an option. Doh.

**Comment by dwijnand** [comment]
@eed3si9n Was it intentional in https://github.com/sbt/librarymanagement/pull/113 that it still takes a string parameter?

**Comment by eed3si9n** [comment]
Yes. Ivy configuration names are lowercase (and hyphenated) like `it` for `IntegrationTest`, and `compile-internal`.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/librarymanagement/pull/113
