### ISSUE TITLE
Transitive dependency causes wrong evictions

### ISSUE THREAD

**Issue by dstibbe** [sbt/sbt#2891]
## steps
The following build.sbt 

```scala
lazy val root = (project in file(".")).
  settings(
      name := "test",
      version := "1.0",
      scalaVersion := "2.11.7",
      libraryDependencies ++= Seq(
       "org.webjars.npm" % "angular" % "1.4.9",
       "org.webjars.npm" % "angular-material-icons" % "0.7.1"
      ),
      scalacOptions in Test ++= Seq("-Yrangepos")
  )
```
## problem
The dependency _"org.webjars.npm" % "angular-material-icons" % "0.7.1"_ has maven dependency 
```
    <dependency>
            <groupId>org.webjars.bower</groupId>
            <artifactId>angular</artifactId>
            <version>(1.3,)</version>
        </dependency>
```

which should be satisfied by _"org.webjars.npm" % "angular" % "1.4.9"_,
however, upon resolving the dependencies, the following happens:
```
[info] test:test_2.11:1.0 [S]
[info]   +-org.webjars.npm:angular-material-icons:0.7.1
[info]   | +-org.webjars.npm:angular:1.6.1
[info]   | 
[info]   +-org.webjars.npm:angular:1.4.9 (evicted by: 1.6.1)
[info]   +-org.webjars.npm:angular:1.6.1
```

## expectation
When the dependency resolver is resolving the transitive dependency of  _angular-material-icons_ and sees it requires _angular_ (1.3,) , it should see that this requirement is already met by the project dependency of 1.4.9.

- [Ivy doc](https://ant.apache.org/ivy/history/2.3.0/ivyfile/dependency.html#revision) clearly states that (1.0,) matches all versions greater or equal to 1.0 - which 1.4.9 satisfies
- [Maven doc](http://maven.apache.org/components/enforcer/enforcer-rules/versionRanges.html) clearly states: (1.0,) 	x > 1.0

## notes
There was a previous issue, similar to this: [Issue 2291](https://github.com/sbt/sbt/issues/2291)

That issue was closed with the remark : 

>  but mathematically x >= 1.3 simply is a restriction on x that says it's greater or equal to 1.3. So, technically it's not wrong when x is the largest number on the internet or some other "common sense" number. 

Which is simply incomplete. It is correct that is a restriction on x that says it's greater or equal to 1.3. But it is wrong to use the latest version from the internet when the dependency tree has already narrowed the scope of versions to use (1.4.9), which meets the restriction x>=1.3.

**Comment by eed3si9n** [comment]
ok. Let me close this, reopen #2291, and we can continue the discussion there.
