### ISSUE TITLE
Eviction warning (overrideScalaVersion) lies and is unclear

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#2894]
## steps

sbt.version=0.13.13

```scala
scalaVersion := "2.12.0"
libraryDependencies += "com.github.julien-truffaut" %% "monocle-core" % "1.4.0-M2"
```

Note I'm setting `scalaVersion` to `"2.12.0"` but monocle-core 1.4.0-M2 depends on `org.scala-lang : scala-library : 2.12.1`.

```scala
package t

object Hi {
  def main(args: Array[String]): Unit = {
    println(classOf[Seq[Int]].getProtectionDomain().getCodeSource());
  }
}
```

## problem

Invoking `run` shows 2 things, first:

```
[warn] Scala version was updated by one of library dependencies:
[warn] 	* org.scala-lang:scala-library:2.12.0 -> 2.12.1
[warn] To force scalaVersion, add the following:
[warn] 	ivyScala := ivyScala.value map { _.copy(overrideScalaVersion = true) }
```

secondly:

```
[info] Running t.Hi
(file:/Users/dnw/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.12.0.jar <no signer certificates>)
```

Firstly, the message "To force scalaVersion" is unclear. Does it mean to force the upgrade or to force it not to upgrade?

Secondly, actually adding `ivyScala := ivyScala.value map { _.copy(overrideScalaVersion = true) }` removes the warning, and running results in

```
[info] Running t.Hi
(file:/Users/dnw/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.12.0.jar <no signer certificates>)
```

i.e. no change at all - it made no difference at all (except remove the warning).

## expectation

I expected a clearer message, and I expected something to actually change (either from 2.12.1 to 2.12.0 or vice-versa).

Also, with `scalaVersion` set to `"2.12.0"` and a dependency to that version of monocle-core I expected scala-library 2.12.1 to be used at compile-time and runtime, given that's what monocle depends on.

**Comment by eed3si9n** [comment]
This is a feature interaction between eviction warning and scalaVersion mediator.
Effectively we now have overrideScalaVersion turned on by default.

**Comment by eed3si9n** [comment]
Reflecting the scalaVersion mediator, we could issue a warning like:

```
[warn] Some library dependencies use a newer Scala version than this project:
[warn] 	* org.scala-lang:scala-library:2.12.0 -> 2.12.1
[warn] We recommend you upgrade to the latest scalaVersion patch:
[warn] 	scalaVersion := 2.12.1
```

if we know that the mediator is turned on.

**Comment by jvican** [comment]
:+1: I really like the new warning message.
