### ISSUE TITLE
Do something with Def.derive

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#2898]
We should do something with Def.derive. Some combination of:

* kill it,
* document it,
* fix it and make it the implicit default behaviour of settings
* .. any other option?

**Comment by eed3si9n** [comment]
Do we have to do anything with it?

**Comment by dwijnand** [comment]
Yeah. It's out there, both in the sbt codebase and in other codebases (eg. wartremover). At the very minimum we should document what we know about it, warts, caveats and all.

**Comment by eed3si9n** [comment]
IIRC it allows automatic derivation of setting expressions on the configuration axis, but it requires the incoming expressions to be unscoped, so it doesn't work well with task scoping.
Caveat emptor.
