### ISSUE TITLE
Improve "run 'last <task>' for the full log" to include task name

### ISSUE THREAD

**Issue by ijuma** [sbt/sbt#29]
Including the task name is important because it is often not the task that the user invoked. For example, if the user invokes "compile" and there's an error during update, "last compile" results in no output while "last update" does the right thing.

Alternatively the last command could be more intelligent.

**Comment by harrah** [comment]
A sample output is:

[error] Incomplete tasks (run 'last <task>' for the full log):
[error]   {file:/...}default/*:publish-configuration: java.lang.RuntimeException: Repository for publishing is not specified.

There could be multiple tasks that fail and be listed here, especially in a multi-module build.

'last' is more general than just showing errors.  By default it will show logging at the debug level and so it can be used to view debugging for the last compile or update whether or not it failed, for example.

So, I'm not sure about the task name, but yes, it could be clearer.  Thoughts?

**Comment by ijuma** [comment]
Oh, I see. Sorry, I had not noticed that the name of the task is included in the error. It seems to me that the main issue in my case is that the task name was lost in the noise of the project path and name (my path was quite a bit longer than yours).

Perhaps move the path to the end of the message? Also, what does the asterisk mean in this context? Is it really needed?

**Comment by harrah** [comment]
The asterisk means it is not specific to a configuration (i.e., Global).  Something I'd considered eventually doing is to show only enough of the path to be unambiguous.  That will take some effort and I'm not sure about it yet.

I was thinking perhaps the task could be highlighted in red.  This would pick it out pretty well.  I've pushed this change to try it out.

**Comment by ijuma** [comment]
Interesting idea about changing the colour. Maybe that's good enough. I suggest we close this and reopen if more users complain.
