### ISSUE TITLE
Feature request: Allow resolve libraryDependencies from other project of a Multi-Project Builds.

### ISSUE THREAD

**Issue by Atry** [sbt/sbt#291]
I maintain an open source project `foo`, which uses another project `bar`. Both of the two projects are used by a private project `baz`. I have directory layout like this:
- root/
  - project/
    - Build.scala
  - foo/
    - project/
      - Build.scala
    - build.sbt
  - bar/
    - build.sbt
  - baz/
    - build.sbt

I add `libraryDependencies` in `foo/build.sbt`:

```
libraryDependencies += "org.bazGroup" %% "bar" % "1.0"
```

This is necessary because foo is a solid project. I expect users of `foo` can checkout `foo`'s source and run sbt, then the baz is automatically downloaded.

But I have a forked version of `bar`. I expect to aggregate `foo`, `bar` and `baz` together, and frequently modify all the three projects. So I write `root/project/Build.scala`:

``` scala
import sbt._
import Keys._

object RootBuild extends Build {

  lazy val foo = Project(id = "foo", base = file("foo")).aggregate(bar)

  lazy val bar = Project(id = "bar", base = file("bar"))

  lazy val baz = Project(id = "baz", base = file("baz")).aggregate(foo, bar)

}
```

But It does not work. There are two problem:
1. `foo/project/Build.scala` is ignored.
2. `"org.bazGroup" %% "bar" % "1.0"` does not resolved to my forked version of bar, instead, it uses the one in repository.

The second problem is even more terrible than maven. Maven's [Multiple Modules](http://maven.apache.org/pom.html#Aggregation) can resolve dependencies between sub-modules.

**Comment by indrajitr** [comment]
Can you try `dependsOn(bar)` instead of `aggregate(bar)` and see what happens?

Something like:

``` scala
import sbt._
import Keys._

object RootBuild extends Build {

  lazy val foo = Project(id = "foo", base = file("foo")).dependsOn(bar)
  lazy val bar = Project(id = "bar", base = file("bar"))
  lazy val baz = Project(id = "baz", base = file("baz")).dependsOn(foo, bar)
}
```

**Comment by Atry** [comment]
`dependsOn` can add new build dependency between these projects, but this should be done automatically.

I write some complex setting code to detect dependencies between current projects.

``` scala
import sbt._
import Keys._

object RootBuild extends Build {

  private def addBuildDependencyIfMatches(matching: Project) =
    buildDependencies <<= (
      buildDependencies,
      libraryDependencies,
      thisProjectRef,
      name in matching,
      organization in matching,
      thisProjectRef in matching) { (origin, moduleIDs, self,
                                     matchingName, matchingOrganization,
                                     matchingProject) =>
      moduleIDs.find { moduleID =>
        moduleID.name == matchingName &&
        moduleID.organization == matchingOrganization
      } match {
        case Some(moduleID) =>
          origin.addClasspath(
            self,
            ResolvedClasspathDependency(matchingProject,
                                        moduleID.configurations))
        case None =>
          origin
      }
    }

  private lazy val defaultSettings =
    Project.defaultSettings ++
    (projects map addBuildDependencyIfMatches)

  private def newProject(path: String) =
    Project(id = path, base = file(path),
            settings = defaultSettings)

  lazy val foo = newProject("foo")

  lazy val bar = newProject("bar")

  lazy val baz = newProject("baz")

}
```

But the `subpath/project/Build.scala` is still ignored. this behavior prevent sbt from being used in complex project which contains multiple hierarchical sub-projects.

**Comment by harrah** [comment]
@indrajitr note that the subprojects define their own `project/`, so they have to be treated as external builds.

@Atry I see that the documentation describing this particular feature is not as prominent after the getting started guide rewrite, but it is described on the original page.  See the project references section on:

https://github.com/harrah/xsbt/wiki/Full-Configuration

Please use the mailing list if you have further questions.

**Comment by indrajitr** [comment]
@harrah thanks for pointing that out. It went off my head, sorry.
