### ISSUE TITLE
Error: File exists and is not a directory

### ISSUE THREAD

**Issue by waywardmonkeys** [sbt/sbt#292]
After updating to 0.11.2 (from 0.11.1), we seem to get this sort of thing a lot:

```
[error] {file:/Users/bruce/Development/foo/}bar/compile:compile: Could not create directory
   /Users/bruce/Development/foo/tools/bar/target/scala-2.9.1/cache/compile/compile:
   file exists and is not a directory.
```

**Comment by indrajitr** [comment]
Can you please do `clean` once before doing `compile` and see if the problem persists?

**Comment by waywardmonkeys** [comment]
I've done cleans before and then later gotten this error. Or do you mean that a `clean` should allow me to re-run `compile` and have it work?

**Comment by indrajitr** [comment]
Do a `clean` after you have moved to 0.11.2. Subsequently, re-running `compile` should work every time. If that is not the case for you, put together an example project where you can recreate this and we'll see.

**Comment by waywardmonkeys** [comment]
I've definitely done a `clean` since moving. And it happens seemingly randomly. I've no idea what the trigger is.

**Comment by indrajitr** [comment]
SBT's `compile` task always creates `compile` file under `cache/compile` directory. That is failing in this case because `cache/compile` is a file (you can verify when you encounter this). It could be possible that some plugin is creating such file. What plugins are you using?

**Comment by harrah** [comment]
No reports since original fix attempt, so closing.
