### ISSUE TITLE
sbt doesn't use scala version from build.sbt on Fedora 24

### ISSUE THREAD

**Issue by vasigorc** [sbt/sbt#2923]
Env:
OS - Fedora 24 (KDE Plasma Desktop)
sbt version - 0.13.8

I installed sbt following the official web-site's guide:

```
curl https://bintray.com/sbt/rpm/rpm | sudo tee /etc/yum.repos.d/bintray-sbt-rpm.repo
sudo yum install sbt
```

Worth your attention that Fedora's package manager (dnf) skips sbt in updates as having broken dependencies:

```
[vgorcinschi@localhost ~]$ sudo dnf update
[sudo] password for vgorcinschi: 
Last metadata expiration check: 0:21:43 ago on Sun Jan 15 17:25:20 2017.
Dependencies resolved.
================================================================================
=================================================================================
 Package                         Arch                               Version                                   Repository                                    Size
================================================================================
=================================================================================
Skipping packages with broken dependencies:
 sbt                             noarch                             0.13.13.1-1                               bintray--sbt-rpm                             1.0 M
```

I have then created a simple "Hello, world!" sbt project (using Intellij IDEA 2016.2 Community edition). Running `compile` fails with this exception: 

```
[error] uncaught exception during compilation: scala.reflect.internal.MissingRequirementError
scala.reflect.internal.MissingRequirementError: class scala.annotation.serializable in compiler mirror not found.
```

What might explain the failure are the first error lines in the compile stack (sbt <= 2.10.4 isn't compatible with jdk 8):

```
[error]      while compiling: /home/vgorcinschi/Documents/ideaProjects/CourseraScalaOne/example/src/main/scala/example/ExampleApp.scala
[error]         during phase: typer
[error]      library version: version 2.10.4
[error]     compiler version: version 2.10.4
```

In build.sbt file scala version is set to 2.12.1:

```
scalaVersion := "2.12.1"
```

Similar issue has been raised for Fedora 20 before: https://github.com/jodersky/flow/issues/11

More information about my issue is tagged under sbt on stackoverflow - http://stackoverflow.com/questions/41656565/scala-versions-confusion

**Comment by eed3si9n** [comment]
Thanks for bringing this to our attention.

**Comment by eed3si9n** [comment]
I recently created 0.13.13.1 because we messed up the RPM installer for 0.13.13.
On EC2 environment I did confirm that Redhat was able to display hello world. I picked whatever that was on EC2 so I think it was Red Hat Enterprise Linux 7.3 (HVM), SSD Volume Type - ami-b63769a1.
The output looked like this:

```
$ curl https://bintray.com/sbt/rpm/rpm | sudo tee /etc/yum.repos.d/bintray-sbt-rpm.repo
....
$ sudo yum install sbt
....
Total download size: 46 M
Installed size: 153 M
Is this ok [y/d/N]: y
....
Installed:
  sbt.noarch 0:0.13.13.1-1
....
$ sbt new scala/scala-seed.g8
Getting org.scala-sbt sbt 0.13.13 ...
....

Minimum Scala build.

name [My Something Project]: hello

Template applied in ./hello

$ cd ./hello/
$ sbt run
....
[info] Done updating.
[info] Compiling 1 Scala source to /home/ec2-user/hello/target/scala-2.12/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.12.1. Compiling...
[info]   Compilation completed in 21.297 s
[info] Running example.Hello
hello
[success] Total time: 28 s, completed Jan 4, 2017 9:59:42 PM
```

**Comment by eed3si9n** [comment]
Currently the `rpmRequirements` we list on the [installer](https://github.com/sbt/sbt-launcher-package/blob/86afaaebb43ec4d6278f139700912893314a16b1/build.sbt#L85) are

```scala
    rpmRequirements :=Seq("java","java-devel","jpackage-utils")
```
 
Are the above requirements now outdated? What should they be?

/cc @rparree @manub @jonathandbyrd from https://github.com/sbt/sbt-launcher-package/issues/126

**Comment by eed3si9n** [comment]
If sbt 0.13.13 can be installed, that should work.
If sbt 0.13.8 can be installed, that should also work with JDK 8.

**Comment by vasigorc** [comment]
Thank you, eed3si9n. I have a different issue with 0.13.13.1 now - I already [reported it here](https://github.com/sbt/sbt-launcher-package/issues/140).
