### ISSUE TITLE
using ssh resolver on jfrog repository in not downloading the dependencies

### ISSUE THREAD

**Issue by 123avi** [sbt/sbt#2946]
Hi, I am using 

> sbt 0.13.13

I have private ssh repository on jfrog. however when I set the resolver, it seems that it is not downloading the dependency 
## steps
tried to follow the example shown [here](http://www.scala-sbt.org/1.0/docs/Resolvers.html)
`resolvers += Resolver.ssh("foo repo" , "myname.jfrog.io/mypath/libs-release") as("myUserName", "myPassword")`

## problem

> sbt.ResoveException : unresoved dependency 

## notes

works fine when using maven .

am I missing something ?

any plugins that I need to add ?

**Comment by SethTisue** [comment]
I suggest we close this as lacking sufficient detail to be actionable (and for being really old/stale).
