### ISSUE TITLE
Bash shell will not echo after running sbt script

### ISSUE THREAD

**Issue by ekrich** [sbt/sbt#2963]
After running a sbt script in version 1.0.x the shell becomes corrupt. This does not occur using 0.13.x versions.

Steps: 

1. Run a simple sbt script such as the following where `xsbt` is a simple launcher script :
```
#!/usr/bin/env xsbt -Dsbt.version=1.0.0-SNAPSHOT -Dsbt.main.class=sbt.ScriptMain -error

/***
name := """sbt-test"""
version := "1.0"
scalaVersion := "2.12.1"
logLevel in Global := Level.Debug
*/

println(args.toList)
```
2. Try to type a command like `env` and press return/enter.
3. Just press the return/enter key.

Problem:
- The shell will not echo characters
- The shell does accept the characters and will run the command
- Hitting return will just repeat the prompt on the same line in the shell

Workaround:
- Type `stty echo` to restore the shell. It is like `stty -echo` got executed by running the script.

Related issues:
https://github.com/sbt/sbt/issues/2065
https://github.com/sbt/sbt/issues/1681
https://github.com/sbt/sbt/issues/1413

Notes:
Mac OS 10.11.6 
Terminal Application (bash)
Scala 2.12.1
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

**Comment by ekrich** [comment]
Here is a stack over flow that may be helpful.
http://stackoverflow.com/questions/42258226/strange-problems-with-term-apple-terminal-on-macos-sierra-10-12-3/42258505

**Comment by dwijnand** [comment]
@ekrich Mind triaging this against 1.0.0-M5 and letting us know what its updated status is, please?

**Comment by ekrich** [comment]
@dwijnand Works great - shell prompt comes back now - super!

**Comment by dwijnand** [comment]
woot! Thanks, friend.

**Comment by NicolasRouquette** [comment]
Thanks for looking into this issue; however, what is the expected behavior?

I tried this:

```
#!/usr/bin/env sbt -Dsbt.version=1.0.0-M6 -Dsbt.main.class=sbt.ScriptMain -error

/***
name := """sbt-test"""
version := "1.0"
scalaVersion := "2.12.1"
logLevel in Global := Level.Debug
*/

println(args.toList)
```

On MacOS Sierra, with TERM=Apple_Terminal, I get a similar stack trace than in the SO question:

```
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "`\327a\:f\241g\261h#i\360jjkkllmmnno\370p\370q\321rrssttuuvvwwxxy\262z\263{\271|\255}\243~\245"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
	at jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:242)
	at jline.UnixTerminal.<init>(UnixTerminal.java:65)
	at jline.UnixTerminal.<init>(UnixTerminal.java:50)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at jline.TerminalFactory.getFlavor(TerminalFactory.java:211)
	at jline.TerminalFactory.create(TerminalFactory.java:102)
	at jline.TerminalFactory.get(TerminalFactory.java:186)
	at jline.TerminalFactory.get(TerminalFactory.java:192)
	at sbt.internal.util.ConsoleAppender$.ansiSupported(ConsoleAppender.scala:161)
	at sbt.internal.util.ConsoleAppender$.<init>(ConsoleAppender.scala:155)
	at sbt.internal.util.ConsoleAppender$.<clinit>(ConsoleAppender.scala)
	at sbt.internal.util.GlobalLogging$.initial(GlobalLogging.scala:62)
	at sbt.StandardMain$.initialGlobalLogging(Main.scala:116)
	at sbt.StandardMain$.initialState(Main.scala:135)
	at sbt.ScriptMain.run(Main.scala:83)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
```

With TERM=xterm-256color, I have to use `stty echo` to restore the shell afterwards.

Is this normal?

**Comment by ekrich** [comment]
No that would not be normal. In the first case, `sbt` should probably be able to restore your shell. In the second case it works for me. I tested originally on `M5` but `M6` works as well. Have you reinstalled `sbt` to the newest `0.13` version? The launcher has changed and that is the only suggestion I have at this time. cc @dwijnand

**Comment by NicolasRouquette** [comment]
I did update sbt to 0.13.15 (`brew upgrade sbt`)
I cleaned my `~/.sbt` folder

In the 1st case (`TERM=Apple_Terminal`), `sbt` fails but the shell is restored.
In the 2nd case (`TERM=xterm-256color`), `sbt` succeeds but I need to do `stty echo` afterwards.

**Comment by ekrich** [comment]
Could you try removing the source from `~/.sbt/boot/<some hash>/src_managed` so it will regenerate the source file and then recompile. Just grasping at straws now. If I `export TERM=Apple_Terminal` I get the following and a stack trace but the terminal returns and the script still runs:
```
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "`\327a\:f\241g\261h#i\360jjkkllmmnno\370p\370q\321rrssttuuvvwwxxy\262z\263{\271|\255}\243~\245"
```

When I tried to define an "Apple_Terminal" in the "Terminal App" it was not even a choice. You can look in `.bash_profile` to see if there is an `export TERM=Apple_Terminal` in there or go to terminal Preferences and see what you have there - I never messed with any of those settings.
```
Erics-MBP:scala-native-complex eric$ echo $SHELL
/bin/bash
```

**Comment by NicolasRouquette** [comment]
In `~/.sbt/boot/<hash>/src_managed`, there was a single `.scala` file with the script above!
I removed it -- same behavior.

With `export TERM=Apple_Terminal`, the exception happens each time `sbt` needs to display a prompt:

```
 mkdir AT; cd AT; sbt  -Dsbt.version=1.0.0-M6 -no-share -no-global -sbt-create
Getting org.scala-sbt sbt 1.0.0-M6  (this may take some time)...
...
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "`\327a\:f\241g\261h#i\360jjkkllmmnno\370p\370q\321rrssttuuvvwwxxy\262z\263{\271|\255}\243~\245"
...
> project
[info] at (in build file:/Users/rouquett/tmp/AT/)
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "`\327a\:f\241g\261h#i\360jjkkllmmnno\370p\370q\321rrssttuuvvwwxxy\262z\263{\271|\255}\243~\245"
...
```

After exiting `sbt`, the shell is properly restored.

With `TERM=xterm-256color`, I did this:

```
mkdir BT; cd BT; sbt  -Dsbt.version=1.0.0-M6 -no-share -no-global -sbt-create
Getting org.scala-sbt sbt 1.0.0-M6  (this may take some time)...
....
[info] Set current project to bt (in build file:/Users/rouquett/tmp/AT/BT/)
[info] sbt server started at 127.0.0.1:5716
> project
[info] bt (in build file:/Users/rouquett/tmp/BT/)
> exit
```

The shell is properly restored!

But, if I execute the script:

```
#!/usr/bin/env sbt -Dsbt.version=1.0.0-M6 -Dsbt.main.class=sbt.ScriptMain -error

/***
name := """sbt-test"""
version := "1.0"
scalaVersion := "2.12.1"
logLevel in Global := Level.Debug
*/

println(args.toList)
```

Then the shell is not properly restored -- I need to do: `stty echo`

**Comment by dwijnand** [comment]
The problem here is reported and tracked as https://github.com/sbt/sbt/issues/3240.

**Comment by dpovey** [comment]
Please note I still have this problem on the sbt 1.0 release on MacOS Sierra 10.12.6
When sbt exits (in both interactive and non-interactive mode) terminal does not echo.

**Comment by dwijnand** [comment]
@dpovey tracked as https://github.com/sbt/sbt/issues/3453.
