### ISSUE TITLE
Support applying input derived from settings in the := macro

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#2975]
From http://www.scala-sbt.org/0.13/docs/Input-Tasks.html#Preapplying+input

> Note: the current implementation of := doesn’t actually support applying input derived from settings yet.

**Comment by SethTisue** [comment]
is there a workaround?

**Comment by dwijnand** [comment]
none to my knowledge

**Comment by dwijnand** [comment]
you can run the input task "out-of-band" of the task graph evaluation (see the "CAVEAT" in https://github.com/sbt/sbt-buildinfo/tree/v0.7.0#usage) by using `Extracted#runInputTask`, e.g:

```scala
bar := {
  val input = foo.value
  val e = Project.extract(s)
  e.runInputTask((runMain in Compile), " " + input, s)
}
```

**Comment by dwijnand** [comment]
or maybe I've missed the memo and this is now supported by `Def.taskDyn`??

```scala
val foo = settingKey[String]("")
val bar = taskKey[Unit]("")

foo := "blah"
bar := Def.taskDyn {
  runMain in Compile toTask s" ${foo.value}"
}.value
```
