### ISSUE TITLE
change <<= to := {} not working

### ISSUE THREAD

**Issue by NeuroNex** [sbt/sbt#2977]
This is probably not a bug, I'm seeking advice to fix the obsolete syntax

## steps
Current project/Testing.scala
```
object Testing {
  import Configs._
  lazy vall testAll = TaskKey[Unit]("test-all")

  private lazy val itSettings = 
    inConfig(IntegrationTest)(Defaults.testSettings) ++ Seq(
      fork in IntegrationTest := true,
      parallelExecution in IntegrationTest := false,
      scalaSource in IntegrationTest : = baseDirectory.value / "src/it/scala"
   )

  lazy val settings = itSettings ++ Seq(
    testAll <<= (test in IntegrationTest).dependsOn(test in Test)
  )
}
```

## problem
 > warning: `<<=` operator is deprecated. 
>  Use `key := { x.value }` or `key ~= (old => { newValue })`.

If the line `testAll <<= (test in IntegrationTest).dependsOn(test in Test)`
is replaced by `testAll := { (test in IntegrationTest).dependsOn(test in Test) }`
the behaviour of the `testAll` task is disabled.

Invoking `sbt testAll` now does nothing. The task terminates immediately.

## expectation
Replace the `<<=` syntax while keeping the same behaviour than before.

**Comment by dwijnand** [comment]
It also says

> See http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html

http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html#Migrating+when+using+%2C++or
