### ISSUE TITLE
trait Build in package sbt is deprecated

### ISSUE THREAD

**Issue by NeuroNex** [sbt/sbt#2978]
Sorry for using the issue as support forum. I'll like to fix the warning [trait Build in package sbt is deprecated: Use .sbt format instead](http://stackoverflow.com/questions/42488840/trait-build-in-package-sbt-is-deprecated-use-sbt-format-instead) Described in the linked Stackoverflow post. 

## steps
The content of the Build.scala is
```
import sbt._
object MyBuild extends Build  {
  lazy val root = Project("MyProject", file("."))
    .configs(Configs.all: _*)
    .settings(Testing.settings ++ Docs.settings: _*)
}
```

## problem
How to migrate that build.scala code into build.sbt?

**Comment by dwijnand** [comment]
> Sorry for using the issue as support forum.

Please don't. Please see http://www.scala-sbt.org/community.html#how-can-I-get-help

Feel free to come chat in the sbt/sbt gitter room.
