### ISSUE TITLE
Colour output broken on mingw on Windows

### ISSUE THREAD

**Issue by keirlawson** [sbt/sbt#2979]
## steps

Run SBT

## problem

Garbage characters instead of colours

## expectation

Coloured output

## notes

I know coloured output is supported by this terminal as npm is able to produce coloured output without issue.

**Comment by SethTisue** [comment]
does anyone know if this has progressed?

**Comment by eed3si9n** [comment]
So much has changed around Windows and JLine so maybe we should close it for now, and reopen if others still run into this.
