### ISSUE TITLE
Line editing not working on mingw on Windows

### ISSUE THREAD

**Issue by keirlawson** [sbt/sbt#2980]
## steps

Run sbt from minigw
Start typing command
Attempt to delete characters in command

## problem

Characters are not deleted, instead garbage characters are printed to the line

## expectation

Characters are deleted

## notes

Fix seems to be present in JLine 3.1.1+, see https://github.com/jline/jline3/commit/85e44edfd6d424b17fafca8769fabf7272b211f6

**Comment by SethTisue** [comment]
seems like something we could safely close at this point
