### ISSUE TITLE
Rationalise and rename branches

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#2988]
We should rationalise and rename our repo branches.

Current we have:

* sbt/sbt#0.13
* sbt/sbt#1.0.x
* sbt/zinc#1.0
* sbt/librarymanagement#1.0
* sbt/util#1.0

@eed3si9n do we need to just rename sbt/sbt's 1.0.x branch to 1.0?

On a very related note, when are we allowing binary breaking changes?

* 1.1, aka Scala SemVer, or
* 2.0, aka Semver / Java SemVer

And is the answer different between sbt/sbt and the sbt modules?

**Comment by eed3si9n** [comment]
I think we should try to keep (mostly) bincompat during 1.x.y aka Java SemVer across all modules.

**Comment by dwijnand** [comment]
1. Does it not make sense to rename all the branches 1.x then? (The alternative name "1" is too common to be useful)

2. What do you mean by "(mostly)" keep bincompat?

**Comment by jvican** [comment]
Java SemVer (normal semantic versioning) is the way to go IMO.

**Comment by dwijnand** [comment]
Done! All repos are now 1.x.
