### ISSUE TITLE
Global scalaVersion/sbtVersion settings confuse SBT

### ISSUE THREAD

**Issue by Blaisorblade** [sbt/sbt#3006]
Saw mention of this but I haven't double-checked—@Dris101 reported in 2016 that setting `scalaVersion := "2.11"` in `~/.sbt/0.13/global.sbt` confuses SBT into looking for 2.11 versions of plugins.

Assuming this is confirmed, I'd guess the user expected SBT to default to Scala 2.11 for *projects*, not plugins; a more appropriate behavior (if possible somehow) could arguably be an error, since such a user would create projects that don't work on other computers. (But arguably that's always the case, since you can use local settings for global plugins—both things are problematic).

(https://github.com/typesafehub/sbteclipse/issues/315#issuecomment-217710151):
> I think the plugins should be looking to resolve vs. the scala version that sbt was built with (which I think is 2.10), not the scala version that the project is using (2.11 in my case). In any case, using project\plugins.sbt worked for me. The artifact at https://bintray.com/sbt/sbt-plugin-releases/sbteclipse/4.0.0/view#files/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.10/sbt_0.13/4.0.0 does exist but not one called .../scala_2.11/...
(https://github.com/typesafehub/sbteclipse/issues/315#issuecomment-238266058)
> I found a work-around: do not use any global version settings in ~.sbt/0.13/global.sbt -- neither scalaVersion nor sbtVersion -- as these will confuse the resolution process.

**Comment by eed3si9n** [comment]
Yes, the user-global settings affect the metabuild. The following could be used as a workaround:

```scala
scalaVersion := {
  if (sbtPlugin.value) scalaVersion.value
  else "2.11.12"
}
```
