### ISSUE TITLE
Package.makeJar deletes folder recursively

### ISSUE THREAD

**Issue by larsrh** [sbt/sbt#3010]
## steps

Call [`Package.makeJar`](https://github.com/sbt/sbt/blob/v0.13.13/main/actions/src/main/scala/sbt/Package.scala#L93-L99) with `jar` set to an existing _folder_.

Exhibited in a plugin (sbt/sbt-assembly#216), but can probably also be exhibited by setting the a path for `packageBin`, ... which is a directory.

## problem

Here's the relevant code:

```scala
  def makeJar(sources: Seq[(File, String)], jar: File, manifest: Manifest, log: Logger): Unit = {
    log.info("Packaging " + jar.getAbsolutePath + " ...")
    IO.delete(jar)
    log.debug(sourcesDebugString(sources))
    IO.jar(sources, jar, manifest)
    log.info("Done packaging.")
  }
```

The code assumes that `jar` is a file and deletes it. If however `jar` is a folder, it will get recursively deleted.

## expectation

My expectation is that any code which is tasked with writing out _a regular file_ should overwrite existing _regular files_ but not a _folder._ Hence, `makeJar` should error out when `jar` is anything but a regular file (or non-existing).

## notes

* Can be easily changed by adding a guard there (`if (jar.isFile() || !jar.exists())`).
* There are potentially other occurrences of the same problem.

**Comment by eed3si9n** [comment]
Thanks for the detailed report. Do you mind sending in a PR?, otherwise I'll fix it myself.

**Comment by larsrh** [comment]
I can send a PR, if you tell me for which branch :smile:

**Comment by eed3si9n** [comment]
https://github.com/sbt/sbt/tree/0.13.14 please
