### ISSUE TITLE
[0.13.14-RC1] com.typesafe.sbt:sbt-interface:0.13.14-RC1 is not published

### ISSUE THREAD

**Issue by smarter** [sbt/sbt#3012]
I tried upgrading the dotty build to 0.13.14-RC1 and got:
```scala
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.typesafe.sbt#sbt-interface;0.13.14-RC1: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]          com.typesafe.sbt:sbt-interface:0.13.14-RC1 (/home/smarter/opt/dotty/project/Build.scala#L244)
[warn]            +- ch.epfl.lamp:dotty-compiler_2.11:0.1.1-SNAPSHOT
```

**Comment by smarter** [comment]
Note that I could use "org.scala-sbt" % "interface" % sbtVersion.value but this was intentionally changed a while ago: https://github.com/lampepfl/dotty/pull/1324

**Comment by dwijnand** [comment]
Ugh. At a guess I would say "com.typesafe.sbt:sbt-interface" is a typesafehub/zinc artefact?

**Comment by smarter** [comment]
According to https://github.com/coursier/coursier/issues/284 which I just dug up, we should be able to use org.scala-sbt:interface with coursier if we just fix how we set up our resolvers in our build, so this isn't actually a big deal for us.

**Comment by smarter** [comment]
This is actually more of a problem than I thought it was because it requires adding an extra resolver when depending on dotty: https://github.com/lampepfl/sbt-dotty/blob/60b1bad8bf25d5cb4ed87ae73ec3c1409f3b8ecb/src/main/scala/com.felixmulder.dotty.plugin/DottyPlugin.scala#L55-L56

**Comment by smarter** [comment]
Fixed by https://github.com/typesafehub/sbt-republish/pull/15 .
