### ISSUE TITLE
ScriptedPlugin: Add support for paginated tests (scripted foo/*1of3)

### ISSUE THREAD

**Issue by smarter** [sbt/sbt#3013]
This is another issue like https://github.com/sbt/sbt/issues/2601 where `ScriptedPlugin` is less powerful than the internal `Scripted` used by sbt, which supports paginated tests which are very useful when running on a CI: https://github.com/sbt/sbt/commit/5d5d7a6c0551beaeefffce61638ac0c8c29e57ec

**Comment by eed3si9n** [comment]
sure. Would you like to send in a PR?

**Comment by smarter** [comment]
On my way!
