### ISSUE TITLE
packageBin shouldn't package stale class files

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#3018]
See https://github.com/rickynils/scalacheck/issues/318 for the user-land result..

**Comment by eed3si9n** [comment]
@dwijnand, @rickynils, or @xuwei-k could one of you describe the repro steps?
I see that ScalaCheck 1.13.4 and ScalaCheck 1.12.6 got released simultaneously. So can I reproduce this by:

```
git checkout 1.12.6
sbt package
git checkout 1.13.4
sbt package
```

or was it something like:

```
git checkout master
sbt package
git checkout 1.13.4
sbt package
```

If so the question is, if the file in question have later timestamp than in 1.12.6?
https://github.com/rickynils/scalacheck/commit/259607f788ce9d32ff86515ab1648797284b94d1 happened on Jun 22, 2015, but there's been https://github.com/rickynils/scalacheck/commit/224a7ad1fb993423a0e60da0be00b972081ea3df#diff-c8345e81ae750f53d481247eb90c97ce on Aug 9, 2015.

Is the expectation, "detect changes to source code even if the timestamp is older than the previous source"? I'm sure we could try this, but there might be some consequences to performance if we can't assume that the time is monotonically increasing.
