### ISSUE TITLE
Consider using -J-XX:CICompilerCount=2

### ISSUE THREAD

**Issue by jvican** [sbt/sbt#3021]
By default, JVM interpreter runs with one thread while compiler (C2) does with two. Adding `CICompilerCount` to two tells the JVM to use two threads for interpreter.
  
In my experience, this flag has a positive impact on sbt startup time (for example, it goes down from ~9 seconds to ~7.5 in the scala/scala repository). I'm using Oracle JDK8.
  
This flag will not affect behaviour of sbt when it's hot, but it does when it's not (or it's unstable).
  
I still haven't found any case in which this flag has a bad impact in performance (if you have, bring it to my attention). Because of that, I propose that:
  
1. We document this in the sbt docs just in case people want to try it out.
2. We consider using this flag by default.
  
WDYT @eed3si9n @dwijnand ?

**Comment by smarter** [comment]
> By default, JVM interpreter runs with one thread while compiler (C2) does with two. Adding CICompilerCount to two tells the JVM to use two threads for interpreter.

For me the default settings are:
```java
% java -XX:+UnlockDiagnosticVMOptions -XX:+PrintFlagsFinal -version|grep CICompilerCount
     intx CICompilerCount                          := 4                                   {product}
     bool CICompilerCountPerCPU                     = true                                {product}
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.10.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```
So using 2 would be a reduction in the number of threads.

Furthermore, you say this is used for the interpreter, but [the official documentation](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/java.html) says:
> Sets the number of compiler threads to use for compilation. By default, the number of threads is set to 2 for the server JVM, to 1 for the client JVM, and it scales to the number of cores if tiered compilation is used.

**Comment by dwijnand** [comment]
> 1. We document this in the sbt docs just in case people want to try it out.

Fine for me.

> 2. We consider using this flag by default.

How? In the launcher scripts? Correct me, but aren't -XX flags non-standard, and probably HotSpot (aka Oracle Java) only? I'm quite the noob here.

**Comment by dwijnand** [comment]
oh, my output is the same as @smarter's, on 25.112-b16 for macOS.

**Comment by eed3si9n** [comment]
On Mac, using Oracle JDK 8.

```
$ java -XX:+UnlockDiagnosticVMOptions -XX:+PrintFlagsFinal -version|grep CICompilerCount
     intx CICompilerCount                          := 4                                   {product}
     bool CICompilerCountPerCPU                     = true                                {product}
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```

**Comment by jvican** [comment]
> For me the default settings are:
  
Good point, this is pretty weird. I'll look into it.

**Comment by eed3si9n** [comment]
I am going to close this for now as invalid.
