### ISSUE TITLE
puzzle in sbt 1.0.0-m4

### ISSUE THREAD

**Issue by marsxu1984** [sbt/sbt#3029]
I want to updated my all sbt plugins into 1.0.x, some I did some test/try works.
example code from:
http://www.scala-sbt.org/1.0/docs/Plugins.html

## steps

```
import sbt._
import Keys._

object SpawnLarvaePlugin extends AutoPlugin {
    object autoImport {
        val obfuscate = TaskKey[Seq[File]]("Obfuscates files.")
        val obfuscateLiterals = SettingKey[Boolean]("Obfuscate literals.")

        lazy val baseObfuscateSettings: Seq[Def.Setting[_]] = Seq(
            obfuscate := {
                Obfuscate(sources.value)
            },
            obfuscateLiterals in obfuscate := false
        )

        lazy val helloCommand = Command.command("hello") { (state: State) =>
            println("Hi!")
            state
        }
    }

    import autoImport._
    override def requires = sbt.plugins.JvmPlugin
    override def trigger = allRequirements
    override val projectSettings = Seq(commands += helloCommand) ++
    **inConfig**(**Compile**)(baseObfuscateSettings) ++
      **inConfig**(**Test**)(baseObfuscateSettings)
}

object Obfuscate {
    def apply(sources: Seq[File]): Seq[File] = {
        Seq[File]()
     }
 }
```
## problem

[info] Packaging C:\Users\marsx\projects\zagara\tools\spawn_larvae\target\scala-2.11\sbt-1.0.0-M4\spawn_larvae-0.0.1-sources.jar ...
[info] Done packaging.
[info] Wrote C:\Users\marsx\projects\zagara\tools\spawn_larvae\target\scala-2.11\sbt-1.0.0-M4\spawn_larvae-0.0.1.pom
[info] :: delivering :: io.marsdigital#spawn_larvae;0.0.1 :: 0.0.1 :: release :: Fri Mar 17 21:30:38 CST 2017
[info]  delivering ivy file to C:\Users\marsx\projects\zagara\tools\spawn_larvae\target\scala-2.11\sbt-1.0.0-M4\ivy-0.0.1.xml
[info] Main Scala API documentation to C:\Users\marsx\projects\zagara\tools\spawn_larvae\target\scala-2.11\sbt-1.0.0-M4\api...
[info] Compiling 1 Scala source to C:\Users\marsx\projects\zagara\tools\spawn_larvae\target\scala-2.11\sbt-1.0.0-M4\classes...
[error] C:\Users\marsx\projects\zagara\tools\spawn_larvae\src\main\scala\io\marsdigital\tools\SpawnLarvaePlugin.scala:35: not found: value inConfig
[error]     inConfig(Compile)(baseObfuscateSettings) ++
[error]     ^
[error] C:\Users\marsx\projects\zagara\tools\spawn_larvae\src\main\scala\io\marsdigital\tools\SpawnLarvaePlugin.scala:35: not found: value Compile
[error]     inConfig(Compile)(baseObfuscateSettings) ++
[error]              ^
[error] C:\Users\marsx\projects\zagara\tools\spawn_larvae\src\main\scala\io\marsdigital\tools\SpawnLarvaePlugin.scala:36: not found: value inConfig
[error]       inConfig(Test)(baseObfuscateSettings)
[error]       ^
[error] C:\Users\marsx\projects\zagara\tools\spawn_larvae\src\main\scala\io\marsdigital\tools\SpawnLarvaePlugin.scala:36: not found: value Test
[error]       inConfig(Test)(baseObfuscateSettings)
[error]                ^
[error] C:\Users\marsx\projects\zagara\tools\spawn_larvae\src\main\scala\io\marsdigital\tools\SpawnLarvaePlugin.scala:35: not found: value inConfig
[error]     inConfig(Compile)(baseObfuscateSettings) ++
[error]     ^
[error] C:\Users\marsx\projects\zagara\tools\spawn_larvae\src\main\scala\io\marsdigital\tools\SpawnLarvaePlugin.scala:35: not found: value Compile
[error]     inConfig(Compile)(baseObfuscateSettings) ++
[error]              ^
[error] C:\Users\marsx\projects\zagara\tools\spawn_larvae\src\main\scala\io\marsdigital\tools\SpawnLarvaePlugin.scala:36: not found: value inConfig
[error]       inConfig(Test)(baseObfuscateSettings)
[error]       ^
[error] C:\Users\marsx\projects\zagara\tools\spawn_larvae\src\main\scala\io\marsdigital\tools\SpawnLarvaePlugin.scala:36: not found: value Test
[error]       inConfig(Test)(baseObfuscateSettings)
[error]                ^
[info] No documentation generated with unsuccessful compiler run
[error] four errors found
[error] four errors found
[error] (spawn_larvae/compile:doc) Scaladoc generation failed
[error] (spawn_larvae/compile:compileIncremental) Compilation failed
[error] Total time: 2 s, completed 2017-3-17 21:30:40

**Comment by dwijnand** [comment]
Looks like you're using `InConfig` instead of `inConfig`.

Also I believe in M4 we still had some things moved to a sbt.Import object. Those are back on the sbt package object now.

We'll release a more up to date prerelease of sbt 1 soon.

**Comment by marsxu1984** [comment]
inConfig also compile error, I see doc 1.0, say taskKey and settingKey, but also fail. So I change into TaskKey and SettingKey, it works. But inConfig did not.

**Comment by dwijnand** [comment]
Don't read the 1.0 docs :)

taskKey and settingKey are different to TaskKey and SettingKey. I think you're missing `import sbt.Import._` for M4.

But what you really need is to wait a second while we get you a real prerelease that you can test against and open issues about.

Therefore, I'll close this, but I'll come back and let you know when that happens.

Thank you for working on us by trying out sbt 1.
