### ISSUE TITLE
Please make version for jna more flexible

### ISSUE THREAD

**Issue by thkoch2001** [sbt/sbt#303]
Hi,

when trying to run my self-built sbt on Debian, it tries to get jna version 3.2.3 but Debian has version 3.2.7. The only way I could fix this was to change the version in launch/Launch.scala.
Could you either make this more flexible, like [3.2.3,) or make this configurable?

Regards, Thomas Koch

**Comment by harrah** [comment]
If JNA 3.2.7 is binary compatible with 3.2.3, the dependency can be bumped in the build file.  Otherwise, a patch is welcome for making it configurable or I'll get to it eventually.  Version ranges can be slower to resolve than fixed versions, so I'd like to avoid them.

**Comment by harrah** [comment]
As discussed on the mailing list, I misunderstood this.  There is no point to making it configurable at runtime as there are other constraints, unfortunately.
