### ISSUE TITLE
~ in sbt.boot.credentials is not correctly understood by SBT bootstrapper

### ISSUE THREAD

**Issue by salimfadhley** [sbt/sbt#3039]
I'm trying to boot a new installation of SBT behind a password protected corporate firewall. I noticed an oddity which may be a bug or just an undocumented feature:

This works just fine:

`java -jar sbt-launch.jar -Dsbt.boot.credentials=/home/<username>/.sbt/.credentials -Dsbt.override.build.repos=true`

But this does not work:

`java -jar sbt-launch.jar -Dsbt.boot.credentials=~/.sbt/.credentials -Dsbt.override.build.repos=true`

The problem seems to be that the ~ symbol is not expanded to the user's homedir. I found this somewhat unintuative.

The obvious work-around is:

`java -jar sbt-launch.jar -Dsbt.boot.credentials=${HOME}/.sbt/.credentials -Dsbt.override.build.repos=true`

But I think it would be much nicer if ~ was understood by the command in the normal way.

**Comment by jvican** [comment]
Thanks for reporting @salimfadhley! I think this is a bug, `~` should be expanded. This should be pretty easy to fix, would you like to give it a try? :wink: Happy to help in anything you need.
  
@eed3si9n I'm curious, do you know if this happens to all the sbt options passed through Java properties? Or is this an exception?

**Comment by dwijnand** [comment]
I wouldn't be surprised if `~` didn't work in most places. I feel into a similar trap, when dealing with file paths in Rust, assuming that `~` was a universal alias for the current user's home dir.

**Comment by jvican** [comment]
Hmmm, interesting.
  
I would propose to add the `bug` | `feature` label in this issue. Lots of tools recognise `~` and I feel that sbt should. Most people when writing scripts make an extensive use of it and the current behaviour is non-intuitive.

**Comment by salimfadhley** [comment]
Hey, thanks for the feedback. I'd love to give this a go but I'm new to the code-base. Would you give me a clue as to where I might look to make this change?

**Comment by PanAeon** [comment]
Hi,
I think this ticket is a bit tricky to implement. `~` expansion is defined for the POSIX shell [here](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_01) And the main problem is that tilde could refer to other's user home directory as in `~otheruser/`. Also `~` is a perfectly valid character in the path so we might introduce a problem with files that starts with tilde.
So my suggestion is to close this ticket, as it's the shell job to expand it.

Here's a similar JDK ticket for a reference. [JDK-8152072](https://bugs.openjdk.java.net/browse/JDK-8152072)

**Comment by eed3si9n** [comment]
I am ok with making incremental improvements here.
But we should make sure we substitute `~/` not `~`.
