### ISSUE TITLE
update-sbt-classifiers doesn't work for SNAPSHOT plugins

### ISSUE THREAD

**Issue by scroyston** [sbt/sbt#304]
Plugins were added to update-sbt-classifiers awhile ago, but the ivy resolve path is just the launcher core.  If a plugin in not a SNAPSHOT, then it resolves fine from ~/.ivy2/local.  However, if it's a SNAPSHOT, it's not put in ~/.ivy2/local

The real solution seems to be to add the plugin resolvers if the plugins are going to be included.  I tried various contortions of scopes and Setting but couldn't get it to work.

**Comment by mpeltonen** [comment]
This seems to be the reason behind this too: https://github.com/mpeltonen/sbt-idea/issues/119

i.e. when I add any plugin (snapshot or not) which is not in the default repositories into build, update-sbt-classifiers break because plugin repositories are not included in resolution.

**Comment by retronym** [comment]
Related: https://github.com/harrah/xsbt/issues/138
