### ISSUE TITLE
Support for: lazy val foo = someCompositeProject (e.g., CrossProject)

### ISSUE THREAD

**Issue by sjrd** [sbt/sbt#3042]
## Problem

When defining a cross-compiling Scala/JVM + Scala.js project, one needs to use the following pattern:
```scala
lazy val foo = crossProject.
  settings(
    ...
  )

lazy val fooJVM = foo.jvm
lazy val fooJS = foo.js
```
When we initially designed `CrossProject`, we were hoping we would be able to do something like:
```
lazy val foo @ CrossProject(fooJVM, fooJS) = ...
```
but this cannot work because of #2290.
Now, with Scala Native coming along too, together with [a new, generic `CrossProject`](https://github.com/scala-native/sbt-crossproject), that approach wouldn't even work/scale even if we could make it work.

Nevertheless, this has been a pain point of defining Scala.js cross-projects, and it's confusing people (especially when they forget the two additional vals).

## Suggested solution

To solve this issue in a way that I think should have minimal impact on sbt, I propose the following. We add the following interface to sbt:
```scala
package sbt

trait CompositeProject {
  def componentProjects: Seq[Project]
}
```
Then, we augment the mechanism in sbt that discovers the list of all projects in a build, so that it recognizes (lazy) vals of type `<: CompositeProject` in addition to those of type `Project`. The mechanism would call the `componentProjects` methods to get a list of all the projects that need to be part of the build.

**Subtlety:** If there is a `val` of type `Project` in the build whose ID matches that of a component project, the top-level `val` of type `Project` needs to shadow/overwrite the component project. This is required for backwards compatibility, and to prevent further confusion when people do the following (which we discourage, but people do it anyway):
```scala
lazy val foo = crossProject.
  ...
lazy val fooJVM = foo.jvm.settings(moreJVMSettings)
lazy val fooJS = foo.js.settings(moreJSSettings)

// instead of the recommended
lazy val foo = crossProject.
  ...
  jvmSettings(moreJVMSettings).
  jsSettings(moreJSSettings)
lazy val fooJVM = foo.jvm
lazy val fooJS = foo.js
```

## Benefits

With the above notion of `CompositeProject` added to sbt, we can enhance Scala.js' `CrossProject` as follows:
```scala
class CrossProject(...) extends CompositeProject {
  ...
  def componentProjects: Seq[Project] = Seq(jvm, js)
}
```
and we can now simply write:
```scala
lazy val foo = crossProject.
  settings(
    ...
  )
```
and have everything work as expected.

## About derived projects and extra projects

When sbt 0.13.13 added *derived* projects and *extra* projects, I considered using those mechanisms to solve the above issue. However, this doesn't work out, because a `CrossProject` itself is *not* a `Project`, and should not be considered as such. Even in builds that *do* add `Project` with the pseudo-ID of the cross-project, it serves as an aggregate for the platform-specific parts, but the aggregate project must definitely not have the `settings` of its platform parts (or all hell breaks loose).

**Comment by dwijnand** [comment]
Perhaps, similar to Setting/SettingDefinition, such an interface can be a parent of Project, where it would return `this :: Nil`. So `ProjectDefinition`, maybe.

**Comment by sjrd** [comment]
sbt seems to already have a [`ProjectDefinition`](https://github.com/sbt/sbt/blob/317085a458ca2caceaa2e40913a2e367cf75d76d/main/src/main/scala/sbt/Project.scala#L23), although I have no idea what abstraction it provides.

**Comment by dwijnand** [comment]
I'm not surprised. There's also a ProjectDef if memory serves..

**Comment by eed3si9n** [comment]
`CompositeProject` sounds like a good idea worth exploring.

In terms of some implementation details,

```scala
lazy val foo = crossProject.
  settings(
    ...
  )
```

If I needed to aggregate on `foo.jvm` for example, should it return `ProjectRef` instead of `Project` so the following doesn't end up declaring `fooJvm` twice?:

```scala
lazy val foo = crossProject.
  settings(
    ...
  )
lazy val fooJvm = foo.jvm

lazy val bar = project.aggregate(fooJvm)
```

**Comment by sjrd** [comment]
See my "Subtlety" paragraph in the original post. I believe it addresses that potential issue as well.

In a design from scratch I agree that `.jvm` should return a `ProjectRef`. But at least in Scala.js 0.6.x we cannot change that. Potentially we could do it in 1.0.0 if by the time we release it, there is a released version of sbt with this feature.

**Comment by ghost** [comment]
Is anyone looking at this already? Would seem to be super important, IMHO 

If not, and [referencing a chat on sbt-crossproject](https://gitter.im/scala-native/sbt-crossproject?at=5abe9f492b9dfdbc3a3d0652), I might have some free time over the holiday period to have a look

**Comment by ghost** [comment]
Early WIP at https://github.com/BennyHill/sbt/tree/fix/3042

If no  feedback, WIP PR coming tomorrow
