### ISSUE TITLE
Reg:- Sbt compiler issue

### ISSUE THREAD

**Issue by shyamraj242** [sbt/sbt#3048]
(See the guidelines for contributing, linked above)

## steps
We have installed sbt compiler successfully. 

## problem
1) I have installed sbt compiler successfully. When I am going to next step that is running **sbt compile** command it is downloading all the jar files and creating directories of **.ivy2** and **.sbt.**
2) We have created our own repositories in our maven central. 
3) I have replaced the **typesafe-ivy-releases**(**https://repo.typesafe.com/typesafe/ivy-releases/**)  and **sbt-ivy-snapshots(https://repo.scala-sbt.org/scalasbt/ivy-snapshots/)** url's with our maven cenral repository.
4) The problem for me is when I want to replace the **http://repo1.maven.org/maven2/** which is present in the **IBiblioResolver.class** file with our maven central URL **(http://mavencentral.it.att.com:8084/nexus/content/repositories/repo1-manven2-proxy/).**
5) I am unable to do this, because this is **.class** file. I have decompiled and ran as a **.Java** file. I am getting an error as shown in the images(**compile.jpeg
![compile](https://cloud.githubusercontent.com/assets/21132337/24368632/6475d35a-12de-11e7-9280-6c5ea4be2e0e.jpg)
![classfileconvertedtojava](https://cloud.githubusercontent.com/assets/21132337/24368646/6db16b00-12de-11e7-8693-89cc94ad6896.jpg)

**). Please help me on this. 

## expectation
1) Need to replace the repo1.maven.org url which is present in .class file into our maven central url.

## notes
Please find the attachments

**Comment by eed3si9n** [comment]
I'm failing to understand this issue. How is "I have installed sbt compiler successfully. When I am going to next step that is running sbt compile command it is downloading all the jar files and creating directories of .ivy2 and .sbt." your problem statement?

If you're trying to avoid hitting Maven Central, please read http://www.scala-sbt.org/0.13/docs/Proxy-Repositories.html

**Comment by shyamraj242** [comment]
eed3si9n,
Thanks for the reply.
I tried that also It didn't worked for me. Actually I need to replace the URL **(https://repo1.maven.org/maven2/)** which is present in sbt-launch.jar file. I have extracted the jar file and I am trying to edit the IBiblioResolver.class file (I have decompiled and saved as .Java file) still I am getting the error.  The only solution for us is to replace the url  with the **http://mavencentral.it.att.com:8084/nexus/content/repositories/repo1-manven2-proxy/**.  Please let me know in case of any concerns.

**Comment by eed3si9n** [comment]
If you're trying to get sbt installed, try 0.13.14-RC2 that implements offline installation - https://bintray.com/sbt/native-packages/download_file?file_path=sbt%2F0.13.14-RC2%2Fsbt-0.13.14-RC2.zip

In general thought, the sbt issue tracker is not a support system. Please see [how can I get help?](http://www.scala-sbt.org/community.html#how-can-I-get-help)

**Comment by shyamraj242** [comment]
Hi eed3si9n,

If I need to install sbt compiler in my cluster I need to edit the IBiblioResolver.class file and I need to replace the https://repo1.maven.org/maven2/ with http://mavencentral.it.att.com:8084/nexus/content/repositories/repo1-manven2-proxy/. Can you please help me on this. The reason for replacing this URL is, our cluster are in protected mode. Please help me on this.

**Comment by eed3si9n** [comment]
Sorry we don't support editing of *.class file. Please follow http://www.scala-sbt.org/0.13/docs/Proxy-Repositories.html that should allow you to use your Nexus.

**Comment by shyamraj242** [comment]
Hi Eed3si9n,

I followed the repository documentation which is mentioned above.

Step1: I have edited the sbt-launch.jar file by extracting the .jar file

Step2: Replaced the override-build-repos: property as below

**override-build-repos: -Dsbt.override.build.repos-true**

Step3: Replaced the repository-config: -Dsbt.repository.config property as below

**repository-config: -Dsbt.repository.config = http://mavencentral.it.att.com:8084/nexus/content/repositories/repo1-manven2-proxy/**

Then I have again exported the jar file. Still not working please help me on this.

Please find the images. 

[sg865w@blpd212 ~]$ sbt
Getting org.scala-sbt sbt 0.13.13 ...

:: problems summary ::
:::: WARNINGS
                module not found: org.scala-sbt#sbt;0.13.13

        ==== local: tried

          /home/sg865w/.ivy2/local/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml

          -- artifact org.scala-sbt#sbt;0.13.13!sbt.jar:

          /home/sg865w/.ivy2/local/org.scala-sbt/sbt/0.13.13/jars/sbt.jar

        ==== Maven Central: tried

          https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.pom

          -- artifact org.scala-sbt#sbt;0.13.13!sbt.jar:

          https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.jar

        ==== typesafe-ivy-releases: tried

          https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml

        ==== sbt-ivy-snapshots: tried

          https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml

                ::::::::::::::::::::::::::::::::::::::::::::::

                ::          UNRESOLVED DEPENDENCIES         ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: org.scala-sbt#sbt;0.13.13: not found

                ::::::::::::::::::::::::::::::::::::::::::::::


:::: ERRORS
        Server access Error: Connection timed out url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.pom

        Server access Error: Connection timed out url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.jar

        Server access Error: Connection timed out url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml

        Server access Error: Connection timed out url=https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml


:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
unresolved dependency: org.scala-sbt#sbt;0.13.13: not found
Error during sbt execution: Error retrieving required libraries
  (see /home/sg865w/.sbt/boot/update.log for complete log)
Error: Could not retrieve sbt 0.13.13


![sbtlaunchjarfileedited](https://cloud.githubusercontent.com/assets/21132337/24913827/fd42397e-1e97-11e7-83d2-d77d3a6312ee.jpg)
