### ISSUE TITLE
libraryDependencies defined inThisBuild not picked up in crossProject/test

### ISSUE THREAD

**Issue by olafurpg** [sbt/sbt#3053]
Using 0.13.13
## steps
- `git clone https://github.com/olafurpg/inThisBuild`

The build file should look like this

```scala
lazy val myproject = crossProject.settings(
  scalaVersion := "2.12.1",
  libraryDependencies += "org.scalatest" %%% "scalatest" % "3.0.1" % Test
)
lazy val myprojectJVM = myproject.jvm
lazy val myprojectJS = myproject.js
```

- `sbt test` runs tests, as expected
- `git checkout 05b6a38697c7ea8e460143af464e43b9fbc31e8d` // same build except uses inThisBuild

The build file should look like this
```scala
inThisBuild(Seq(
  scalaVersion := "2.12.1",
  libraryDependencies += "org.scalatest" %%% "scalatest" % "3.0.1" % Test
))

lazy val myproject = crossProject
lazy val myprojectJVM = myproject.jvm
lazy val myprojectJS = myproject.js
```

- `sbt test` runs no tests, unexpected

## problem

The tests don't run when using `inThisBuild`.

## expectation

I expected the tests to run when using `inThisBuild`.

## notes

This is a crossProject. I have not tried tested outside of a crossProject.

**Comment by eed3si9n** [comment]
For now, I think a good workaround might be to define `commonSettings` or an ad-hoc AutoPlugin.

**Comment by eed3si9n** [comment]
This is now likely fixed in sbt 2.x https://github.com/sbt/sbt/pull/6746/commits/dbaa34bdacb796dfca54ecc83e8ed85ea27b5756
