### ISSUE TITLE
Add suffix ';' syntax

### ISSUE THREAD

**Issue by jvican** [sbt/sbt#3060]
See https://github.com/sbt/sbt/issues/3051.

Example:

> clean; compile;
> clean; compile

Similar to the current

> ;clean ;compile

except it doesn't stop at a failure.

**Comment by jvican** [comment]
I think that the current behaviour in `;clean; compile` should not be removed, to protect all the users that are already relying on it and its concrete semantics.

**Comment by milessabin** [comment]
Don't we _always_ want stop on failure?

**Comment by jvican** [comment]
@milessabin For that, see https://github.com/sbt/sbt/issues/3061.

**Comment by dwijnand** [comment]
Agreed, Jorge. If we choose to remove it I think we should have a deprecation cycle for it.

**Comment by eed3si9n** [comment]
As per stop-on-failure, not stopping does _not_ match my expectation of how procedural statements (or `;` monad) should be composed.
I think @dwijnand brought up testing example, users are far more likely to expect stop-on-failure for `;clean; test; publishSigned` whether the semicolon is located on prefix or postfix.

**Edit**: To clarify, as with Miles, I think we should stop on failure.
