### ISSUE TITLE
Add infix '&&' notation to run sequential sbt commands

### ISSUE THREAD

**Issue by jvican** [sbt/sbt#3061]
See https://github.com/sbt/sbt/issues/3051.
  
Example:

> clean && compile

Equivalent in behaviour to the current

> ;clean ;compile

That it runs the commands sequentially, and stops at the first failure.

**Comment by milessabin** [comment]
-1 from me ... this should be the default semantics for `clean ; compile`.

**Comment by jvican** [comment]
I agree, that's the point I was trying to make in #3051.

**Comment by eed3si9n** [comment]
I've experimented with `&&` in https://github.com/sbt/sbt-sh a while back. I would actually support `&&` if it comes with more useful `||`.
