### ISSUE TITLE
Intellij does not understand sbt 1.0

### ISSUE THREAD

**Issue by jvican** [sbt/sbt#3062]
(See the guidelines for contributing, linked above)

## steps
Open sbt 1.0 in Intellij.

## problem
Intellij does not understand sbt because contraband-generated class files are not picked up by it.

## expectation
Intellij understands sbt 1.0 as it does 0.13.

## notes
/cc @jastice

**Comment by dwijnand** [comment]
Cross-linking to the issue in contraband: https://github.com/sbt/contraband/issues/76
