### ISSUE TITLE
Explain breaking changes of plugins in sbt 1.0

### ISSUE THREAD

**Issue by jvican** [sbt/sbt#3063]
"Hello, I am a random sbt plugin author.
  
I am very excited about 1.0!
  
I'd like to know what breaking changes are in 1.0 and how they affect me to migrate my plugin compatible with 0.13. Where should I have a look at? Is there any history of changes to the plugin API?

Thank you"

**Comment by eed3si9n** [comment]
I've been keeping some in https://github.com/sbt/sbt/blob/1.0.x/MIGRATION.md.
There's also http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html during 0.13 series.
We should merge them and make a single migration guide eventually instructing what to do.

**Comment by jvican** [comment]
Now seriously.
  
Yes,thanks for the link. I was trying to replicate the kind of questions that will be asked here in some months. It's important to prepare before they happen.
  
To move this forward, I think these resources will help plugin authors migrate their builds:
  
* A clear document explaining the breaking changes (deprecations that are gone, etc). Please, explain also *why*. Often, knowing why reduces the frustration of migrating changes because we understand the *context*. Try to convince that changes are for users' own good and that there is a coherent story behind them (if there is).
* Provide *one* relatively complex example of a plugin migrated from the old API to the new one.
* Provide some tools to help migration. I see you're doing that already here: https://github.com/sbt/sbt/issues/2619. Good.
* Migration rules seem to be simple and only syntactic. I volunteer to create some rewrites with Scalameta to perform some migrations like the removal of `<<=` and friends automatically.

**Comment by dwijnand** [comment]
> Provide _one_ relatively complex example of a plugin migrated from the old API to the new one.

By actually doing the migration of a number of plugins I think we'll find a good example. I'm doing Scala.js right now, not sure yet if it's a good candidate.

**Comment by eed3si9n** [comment]
I've written out the release notes - http://www.scala-sbt.org/1.0/docs/sbt-1.0-Release-Notes.html and there's now https://github.com/sbt/sbt/pull/3133 to help cross build plugins, so I'm closing this issue.

**Comment by jvican** [comment]
Can we please add some of those in an independent plugin maintenance website?
  
I also suggest that the changes explained there follow a tutorial-like style, illustrating with examples how things should be rewritten (or at least the most important ones).
  
What I would find more useful is a clear distinction between syntactic changes and semantic changes. I think that nailing these sections down would be a huge win for readers of that document, and even me for the migration rewrites.
