### ISSUE TITLE
Repeated unresolved dependency

### ISSUE THREAD

**Issue by greenrd** [sbt/sbt#307]
I repatedly get

```
sbt.ResolveException: unresolved dependency: commons-codec#commons-codec;1.4: configuration not found in commons-codec#commons-codec;1.4: 'compile'. It was required from com.googlecode.jsontoken#jsontoken;1.0 compile
```

and I have to delete ~/.ivy2/cache/commons-codec/commons-codec/ and try again.

This may be occurring repeatedly because I'm running "play dependencies", which uses Ivy internally (though not always correctly).

This time, I copied the problematic directory instead of deleting it, so I could see what was going on. I will attach the different versions of this directory that I captured.

**Comment by greenrd** [comment]
[Before running sbt publish-local](http://www.4shared.com/file/JfDUUQSC/before.html?)

[After running sbt publish-local unsuccessfully](http://www.4shared.com/file/RnJI8VjW/during.html?)

[After deleting commons-codec dir and re-running sbt publish-local](http://www.4shared.com/file/0d0HhG5Y/after.html)

**Comment by harrah** [comment]
Please use the mailing list for questions. https://github.com/harrah/xsbt/wiki/FAQ
