### ISSUE TITLE
SBT dies unexpectedly in a silent way.

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [sbt/sbt#3084]
(See the guidelines for contributing, linked above)

## steps

`sbt myTask`

## problem

About 10% of cases SBT dies silently.
If I relaunch with the same parameters, it succeeds.
`myTask` does a lot of parallelism.
It can die in many different points.

## expectation

If it has some problem, to report it clearly.

## notes

1) More info in this [stackoverflow question|http://stackoverflow.com/questions/43248042/how-to-diagnose-why-the-jvm-ends-unexpectedly]

2) In order to gather more information when it happens, I have done this:

```scala
initialize := {
	System setSecurityManager new SecurityManager() {
		override def checkPermission(perm: Permission) = {}

		override def checkPermission(perm: Permission, context: scala.Any) = {}

		override def checkExit(status: Int) = {
			super.checkExit(status)
			println("Trying to exit from: ")
			Thread.currentThread.getStackTrace.foreach { p ⇒
				println(p.toString)
			}
		}
	}
}
```
No output is collected.

3) I have activated a shutdown hook in order to measure the time it takes to run the different tasks.
When it dies, it reports a duration of a task of 63 days, even when the whole SBT process runs for only a few minutes or even some seconds.  This is the only common pattern that I've observed that remains constant.    When it dies, some task takes 63 days with a variation of minutes.

4) Working in Linux 64 bits, SBT 0.13.11, Java 8.

**Comment by jvican** [comment]
@DavidPerezIngeniero Can you provide a reproducible example or open source the code that produces this error?

**Comment by DavidPerezIngeniero** [comment]
Sorry, it isn't an open source project. :-(
Now I'm checking if I'm hitting a thread count limit or open file limit.

**Comment by eed3si9n** [comment]
The sbt issue tracker is not a support system. Please see [how can I get help?](http://www.scala-sbt.org/community.html#how-can-I-get-help)
