### ISSUE TITLE
Sbt 0.13.15 on windows can't startup without being connected to internet 

### ISSUE THREAD

**Issue by LogicalTime** [sbt/sbt#3092]
## steps
On windows.
Delete all dependency caches on your machine (ivy, maven, etc)
Run sbt from a empty directory or even simple project with just build.sbt and build.properties
See the error message that sbt can't find a dependencies and it won't start.

## problem
Sbt needs dependencies to start up that aren't in the preloaded cache

## expectation
That sbt can start without internet connection, when user has no ivy or maven cache.

## notes
The first dependency not found is:  org.fusesource.jansi#jansi;1.11: not found
The cache only has  org.fusesource.jansi#jansi;1.4

Ref https://github.com/sbt/sbt/pull/2993

**Comment by eed3si9n** [comment]
Thanks for the report. Could you copy paste the full error output to here or gist plz?

**Comment by eed3si9n** [comment]
FWIW here's the log of sbt running on from an OpenJDK 9 Docker container while disconnected from wifi - https://gist.github.com/eed3si9n/5d80ea9d6e1f6f59ff80231cb2ecab46

**Comment by LogicalTime** [comment]
Just checked linux and it works fine. That is primarily what I care about. Looks like the issue is just for windows?

My log of sbt running I put as a comment to your gist.
https://gist.github.com/eed3si9n/5d80ea9d6e1f6f59ff80231cb2ecab46

**Comment by dwijnand** [comment]
Fixed in 0.13.16 (and 1.0.0) with https://github.com/sbt/sbt-launcher-package/pull/160.
