### ISSUE TITLE
'show full-classpath' should work when there are compiler errors

### ISSUE THREAD

**Issue by ijuma** [sbt/sbt#31]
I ran into an issue where my code failed to compile because a dependency was causing an earlier version of the Servlet API to be included in my classpath. I wanted to print the classpath in order to investigate this issue, but the task forced the compilation and failed as a result.

This would be a nice to have, but by no means essential (and there are workarounds like removing the offending code, although this can sometimes be difficult). So, if it's difficult to implement, feel free to close.

**Comment by harrah** [comment]
You want:

> show dependency-classpath

full-classpath = dependency-classpath + products

products is what implies compilation.  You can figure these things out with 'inspect full-classpath' and looking at the dependencies.

**Comment by ijuma** [comment]
Oh, I see. Sorry for the noise and thanks!

**Comment by harrah** [comment]
No problem at all.
