### ISSUE TITLE
Tasks in ThisBuild are secondary citizens

### ISSUE THREAD

**Issue by jsuereth** [sbt/sbt#310]
Completion completely borks for these tasks.  Just try the sbt-git-plugin on 0.11.2 and type `git <tab>`

Also, aggregating projects makes "ThisBuild" tasks be executed over and over and over again (i.e. they are aggregated).   This second complaint is either a bug, or a "JOSH go use commands" moment.  (See https://github.com/sbt/sbt-git-plugin/issues/8)

**Comment by jsuereth** [comment]
Note: The only issue here is the second class citizen part.  I've moved my "Task in ThisBuild" to be commands and all is good.  I'd move this issue to low priority.

**Comment by harrah** [comment]
As specified.  Use the mailing list if you want to discuss it.
