### ISSUE TITLE
Boot repositories (Typesafe Ivy Releases) leak into the resolver

### ISSUE THREAD

**Issue by GaalDornick** [sbt/sbt#3100]
I have a corporate artifact repository that proxies external repositories. According to our corporate policy, we are not supposed to pull artifacts straight from public repos, although they have provided some leeway and allow us to go outside, even if we aren't supposed to. However, I know they are going to clamp down pretty soon. So, I am trying to figure out how to use proxy repository and disable public repos

I have setup the resolvers in build.sbt and plugins.sbt to point to my corporate repo. All the dependencies in build.sbt are pulled fine. The problem is that plugins are always pulled from public repo first before sbt goes to my proxy

## steps
To reproduce this problem, I have created a small hello world program with a plugin enabled. Also, when I run this, I have configured my machine so it doesn't go out onto the internet. This allows me to check which repo the set is pulling the plugin from

* The source code
- hw.scala
```
object Hi { def main(args: Array[String]) = println("Hi!") }
```
- build.sbt
```
name := "hello"

version := "1.0"
scalaVersion := "2.12.1"
```
- project/build.properties
```
sbt.version=0.13.8
```
- project/plugins.sbt
```
addSbtPlugin("com.waioeka.sbt" % "cucumber-plugin" % "0.1.0")
```

➜  sbt run   
```                                              
[info] Loading project definition from /Users/gxc772/work/problems/sbtplugin/hello/project
[info] Updating {file:/Users/gxc772/work/problems/sbtplugin/hello/project/}hello-build...
[info] Resolving com.waioeka.sbt#cucumber-plugin;0.1.0 ...
[error] Server access Error: Operation timed out (Connection timed out) url=https://repo.typesafe.com/typesafe/ivy-releases/com.waioeka.sbt/cucumber-plugin/scala_2.10/sbt_0.13/0.1.0/ivys/ivy.xml
```

This is expected. It's going out to type safe repo

* Fixin to go to my repo
I changed project/plugins.sbt to
```
externalResolvers := Seq[Resolver](
  Resolver.defaultLocal,
  ("my-nexus" at "https://cloudnexus.bigbrother.com/nexus/content/repositories/thirdparty/")
)
addSbtPlugin("com.waioeka.sbt" % "cucumber-plugin" % "0.1.0")
```
And I get
```                                              
[info] Loading project definition from /Users/gxc772/work/problems/sbtplugin/hello/project
[info] Updating {file:/Users/gxc772/work/problems/sbtplugin/hello/project/}hello-build...
[info] Resolving com.waioeka.sbt#cucumber-plugin;0.1.0 ...
[error] Server access Error: Operation timed out (Connection timed out) url=https://repo.typesafe.com/typesafe/ivy-releases/com.waioeka.sbt/cucumber-plugin/scala_2.10/sbt_0.13/0.1.0/ivys/ivy.xml
```
Huh?! Why isn't it going to my nexus. If I wait long enough it does fail over to my-nexus. However, it spends a huge time trying to pull every file from type safe. A 20 minute build would probably take close to 6 hours. Note that the same thing happens if I change my ~/.sbt/repositories file to point my-ivy-proxy-releases to my-nexus.

* Weird workaround that I figured out
SO, after debugging through sbt all night, I figured that this works. I changed project/plugins.sbt to 
```
externalResolvers := Seq[Resolver](
  Resolver.defaultLocal,
  ("my-nexus" at "https://cloudnexus.bigbrother.com/nexus/content/repositories/thirdparty/")
)
addSbtPlugin("com.waioeka.sbt" % "cucumber-plugin" % "0.1.0")
sbtPlugin := false
```
Now, I get 
```
  hello sbt run                                                 
[info] Loading project definition from /Users/gxc772/work/problems/sbtplugin/hello/project
[info] Updating {file:/Users/gxc772/work/problems/sbtplugin/hello/project/}hello-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] downloading https://cloudnexus.bigbrother.com/nexus/content/repositories/thirdparty/com/waioeka/sbt/cucumber-plugin_2.10_0.13/0.1.0/cucumber-plugin-0.1.0.jar ...
[info]  [SUCCESSFUL ] com.waioeka.sbt#cucumber-plugin;0.1.0!cucumber-plugin.jar (314ms)
```
Aha! Now it goes to my corporate repo

## problem

The problem is that when I add  plugins.sbt to the project, then the control goes to this bit of code in Load.scala

```
 /** These are the settings defined when loading a project "meta" build. */
  val autoPluginSettings: Seq[Setting[_]] = inScope(GlobalScope in LocalRootProject)(Seq(
    sbtPlugin :== true,
    pluginData := {
      val prod = (exportedProducts in Configurations.Runtime).value
      val cp = (fullClasspath in Configurations.Runtime).value
      val opts = (scalacOptions in Configurations.Compile).value
      PluginData(removeEntries(cp, prod), prod, Some(fullResolvers.value), Some(update.value), opts)
    },
    onLoadMessage := ("Loading project definition from " + baseDirectory.value)
  ))
```
It seems that whenever an autoPlugin is activated, sbtPlugin is forced to be true. This triggers this bit of code in Defaults.scala

```
fullResolvers <<= (projectResolver, externalResolvers, sbtPlugin, sbtResolver, bootResolvers, overrideBuildResolvers) map { (proj, rs, isPlugin, sbtr, boot, overrideFlag) =>
      boot match {
        case Some(repos) if overrideFlag => proj +: repos
        case _ =>
          val base = if (isPlugin) sbtr +: sbtPluginReleases +: rs else rs
          proj +: base
      }
    }
```
isPlugin is true. So, it prepends the sbtResolver and sbtPluginReleases to externalResolver
## expectation

* My understanding is that sbtPlugin should be true if you have a project that implements a plugin. It shouldn't be enabled automatically. Why is it being enabled in the autoPlugin initialization?
* Both sutra and sbtPluginReleases are hard-coded within SBT. Why does SBT prepend hardcoded repositories into the resolvers?

**Comment by eed3si9n** [comment]
The sbt issue tracker is not a support system. Please see [how can I get help?](http://www.scala-sbt.org/community.html#how-can-I-get-help)

For connecting to corporate proxy repository, check out http://www.scala-sbt.org/0.13/docs/Proxy-Repositories.html

**Comment by GaalDornick** [comment]
This is not a support request. It's a bug report. The steps in the linked document don't work. Even if you follow the steps, SBT goes out to the public repo

**Comment by liff** [comment]
Yeah this is rather annoying. Maybe it could be:

```scala
rs ++ sbtResolverValue :+ sbtPluginReleases
```

In [Defaults.scala](https://github.com/sbt/sbt/blob/develop/main/src/main/scala/sbt/Defaults.scala#L1982) so that proxy resolvers would at least be preferred instead of the hardcoded ones?

**Comment by eed3si9n** [comment]
@GaalDornick You're right. This seems to be a legit bug report. Sorry about my original response.

**Comment by eed3si9n** [comment]
When I run `sbt -Dsbt.override.build.repos=true`, then the fullResolvers are listing just the override resolvers both in the proper build and meta build.

**Comment by eed3si9n** [comment]
`fullResolvers` has included sbtResolver since 2011 - https://github.com/sbt/sbt/commit/ac280e5fe77933397b8fd89f9ae2d8089eec5425
As far as I can tell, it works as designed.

**Comment by eatkins** [comment]
This started showing up in the sbt main project. I have to run with -Dsbt.override.build.repos=true in order to not see tons of
```
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-ivy-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
```

**Comment by seansabour** [comment]
hi @eed3si9n I'm having this exact issue as-well,
Here is a sample :
```
logLevel := Level.Warn

// Need these here for the meta-build
// if the build fails you most likely need to put the repo online:
// You can use slackbot and do something like /artifactory repository put-online <repo_name> to turn it on for 30 minutes.
// Example: /artifactory repository put-online sbt-plugins2
val metaBuildResolvers = Seq(
  Resolver.defaultLocal,
  "maven-central-proxy" at "https://artifactory.company.com/artifactory/virtrelease/",
  Resolver.url("typesafe-ivy2", url("https://artifactory.company.com/artifactory/typesafe2-ivy")),
  Resolver.url("typesafe-ivy2-local", url("https://artifactory.company.com/artifactory/typesafe2-ivy-local"))(
    Patterns("[organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]")
  ),
  Resolver.url("sbt-plugins2", url("https://artifactory.company.com/artifactory/sbt-plugins2"))(
    Patterns("[organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]")
  ),
  Resolver.url("kamon-io-sbt-plugins", url("https://artifactory.company.com/artifactory/kamon-io-sbt-plugins"))(
    Patterns(false, "[orgPath]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]")
  )
)
credentials += Credentials(Path.userHome / ".sbt_credentials")

resolvers := metaBuildResolvers
fullResolvers := metaBuildResolvers
externalResolvers := metaBuildResolvers

addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.7.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-multi-jvm" % "0.4.0")
addSbtPlugin("io.kamon" % "sbt-kanela-runner-play-2.7" % "2.0.6")


```

And my ~/.sbt/boot/update.log
```
	no ivy file in cache for org.apache.logging.log4j#log4j;2.11.2: tried /root/.ivy2/cache/org.apache.logging.log4j/log4j/ivy-2.11.2.xml
	 trying https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j/2.11.2/log4j-2.11.2.pom
		tried https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j/2.11.2/log4j-2.11.2.pom
	Maven Central: found md file for org.apache.logging.log4j#log4j;2.11.2
		=> https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j/2.11.2/log4j-2.11.2.pom (2.11.2)
	parser = pom parser
	no ivy file in cache for org.apache.logging.log4j#log4j;2.11.2: tried /root/.ivy2/cache/org.apache.logging.log4j/log4j/ivy-2.11.2.xml
downloading https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j/2.11.2/log4j-2.11.2.pom ...
	Maven Central: downloading https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j/2.11.2/log4j-2.11.2.pom
		to /root/.ivy2/cache/org.apache.logging.log4j/log4j/ivy-2.11.2.xml.original.part
sha1 file found for https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j/2.11.2/log4j-2.11.2.pom: checking...
	Maven Central: downloading https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j/2.11.2/log4j-2.11.2.pom.sha1
		to /tmp/ivytmp2474830654105006017sha1
sha1 OK for https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j/2.11.2/log4j-2.11.2.pom
	[SUCCESSFUL ] org.apache.logging.log4j#log4j;2.11.2!log4j.pom(pom.original) (177ms)
....
```

if I set a ~/.sbt/repositories file with the repos instead of putting the resolvers inside project/plugins.sbt it behaves as expected. Let me know if you want me to open a new issue to track this or re-use this one.
