### ISSUE TITLE
Default `sbt new` transport to https when accessing github

### ISSUE THREAD

**Issue by ignasi35** [sbt/sbt#3102]
`sbt new` uses `g8` under the covers. `g8` defaults to GitHub when provided a  repo of formant`user/repo.g8`. When accessing Github repositories, `g8` will use `git:` protocol by default and will fallback to `ssh:` (aka `git@`) if `git:` fails.

`git:` doesn't provide server verification and doesn't require client authentication. While user authentication should not be necessary to run `sbt new` it'd be good if server was verified to avoid man-in-the-middle attacks. 

Given https' ubiquity and that it provides server-side verification it could be interesting to default to `https:` via rewriting `user/repo.g8` arguments in `sbt new` to `https://github.com/user/repo.g8.git` when invoking `g8`underneath.

Related issues: https://github.com/sbt/sbt-giter8-resolver/issues/7 and https://github.com/lagom/lagom/issues/683

ps: I'll happily work on a PR but will need some guidance to locate the area of code where I should focus my attention.

**Comment by eed3si9n** [comment]
Technically speaking `sbt new` just forwards the `user/repo.g8` argument to Giter8, so this issue should be opened against Giter8.

The relevant code here I think is https://github.com/foundweekends/giter8/blob/8761f4aeded5ee65ef1d823afe242cb955836230/library/src/main/scala/giter8/GitRepository.scala#L32-L35

**Comment by ignasi35** [comment]
Thanks @eed3si9n for the comment. I didn't open the issue no Giter8 in the first place since asking for that change could be considered as braking the current behaviour.

Actually, adding a third fallback to `https:` in Giter8 [here](https://github.com/foundweekends/giter8/blob/0edcc3540de4e59b0ba08fbac40b42da30427c38/library/src/main/scala/giter8/Git.scala#L47-L47) could do the trick. Opened: https://github.com/foundweekends/giter8/issues/287

**Comment by eed3si9n** [comment]
Hopefully https://github.com/foundweekends/giter8/pull/313 will now be propagated to sbt in 1.2.0.
