### ISSUE TITLE
network connection issue turned out to be scala version problem

### ISSUE THREAD

**Issue by zinking** [sbt/sbt#3107]
## steps

```
git clone https://github.com/siddhartha-gadgil/ProvingGround.git
#switch to scala 2.11 or you are already on it. 
sbt mantle/test:console  
```

## problem

```
[info] Fetched artifacts of client/com/scalawarrior/scalajs-ace_sjs0.6_2.12/0.0.4/scalajs-ace_sjs0.6_2.12-0.0.4.jar
coursier.ResolutionException: 1 download error
  Caught java.net.SocketException: Connection reset (Connection reset)
[error] (client/*:update) coursier.ResolutionException: 1 download error
[error]   Caught java.net.SocketException: Connection reset (Connection reset)
[error] Total time: 3 s, completed Apr 14, 2017 11:28:36 PM
```

## expectation

enter sbt console

## notes

this isn't a network issue, but the error reporting leads me to believe that I have a network problem and wasted time on that. if I switched to 2.12.1 then everything is fine. 

of course I should have spotted that this project is on 2.12.1 and this issue could never happen, but this suggests at least some part of the error reporting could be improved

**Comment by eed3si9n** [comment]
So this is an interaction between Scala JS and Coursier? I'm not sure what sbt can do if the error is caused by the rewired `update` task.
