### ISSUE TITLE
Migration for FileFunctions.cached requires boilerplates

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3109]
Ref https://github.com/sbt/util/pull/45

## steps

Migrate something like the following from sbt 0.13 to sbt 1:

```scala
val f = FileFunction.cached(s.cacheDirectory / "gen-api", FilesInfo.hash) { _ => gen().toSet }
```

## problem

This requires unnecessarily complicated boilerplate.

```diff
+import sjsonnew.IsoString
+import sjsonnew.support.scalajson.unsafe.{ CompactPrinter, Converter, Parser }
+import sbt.internal.util.DirectoryStoreFactory
+import scala.json.ast.unsafe.JValue

+  implicit val jvalueIsoString: IsoString[JValue] = IsoString.iso(CompactPrinter.apply, Parser.parseUnsafe)

-    val f = FileFunction.cached(s.cacheDirectory / "gen-api", FilesInfo.hash) { _ => gen().toSet } // TODO: check if output directory changed
+    import sbt.internal.util.CacheImplicits._
+    val store = new DirectoryStoreFactory[JValue](s.cacheDirectory / "gen-api", Converter)
+    val f = FileFunction.cached(store, FileInfo.hash) { _ => gen().toSet } // TODO: check if output directory changed
```

## expectation

We need something simpler.

## notes

I'm seeing this pattern in multiple places as I'm porting things to sbt 1.

- https://github.com/sbt/contraband/commit/9af32b2944d09f4098bb4196053489f5e88d6a2f
- https://github.com/sbt/sbt/commit/983bf006174c0218f4791f46232f48fba023692a#diff-48248655e71e3636cbf06033755303f1L27

**Comment by dwijnand** [comment]
I think part of that boilerplate goes away if you use s.cacheStoreFactory (https://github.com/sbt/sbt/pull/2892/commits/7fcfec8b8e2b58b33b028606ecafc8ae03f7cdd4#diff-73eff18ed70141748327530263b4d402R75) and then .sub (https://github.com/sbt/util/pull/45/commits/c395bd14a8194b67a79fc53d3bbd6358a3880fde).

**Comment by eed3si9n** [comment]
In https://github.com/sbt/util/pull/78 I added delegate from `object FilesInfo.hash` to `object FileInfo.hash` etc:

```diff
+  def full: FileInfo.Style = FileInfo.full
+  def hash: FileInfo.Style = FileInfo.hash
+  def lastModified: FileInfo.Style = FileInfo.lastModified
+  def exists: FileInfo.Style = FileInfo.exists
```

Next I created `def apply(file: File)` constructor in `object CacheStoreFactory` that simply uses standard JSON, and added overrides to `FileFunction` and `Tracked` method that accepts `cacheFile: File`. This should get us to source compatibility.

```diff
+  def cached(cacheBaseDirectory: File, inStyle: FileInfo.Style, outStyle: FileInfo.Style)(action: Set[File] => Set[File]): Set[File] => Set[File] =
+    cached(CacheStoreFactory(cacheBaseDirectory), inStyle, outStyle)((in, out) => action(in.checked))
```

For smoother migration to the new way, I've just added `/` to CacheStoreFactory:

```diff
+  /** A symbolic alias for `sub`. */
+  final def /(identifier: String): CacheStoreFactory = sub(identifier)
```

so hopefully 

```scala
val f = FileFunction.cached(s.cacheDirectory / "gen-api", FilesInfo.hash) { _ => gen().toSet }
```

can survive as is, or written as:

```scala
val f = FileFunction.cached(s.cacheStoreFactory / "gen-api", FilesInfo.hash) { _ => gen().toSet }
```
