### ISSUE TITLE
Add `extract` to the state API

### ISSUE THREAD

**Issue by jvican** [sbt/sbt#3112]
This is a common sbt idiom:
```scala
sbt.Project.extract(state.value)
```
  
I don't know the reasons why extract was added in `Project`, but my guess would be that it was done to make it binary compatible.
  
I think that this use case should be optimized, by adding `extract` directly into the state API. For newcomers unfamiliar with the sbt API, it is difficult to find `Extracted` and that you can get it via the methods in the `Project` companion object.
  
Having all this functionality in the state API makes all these options both IDE-friendly and user-friendly, since one just has to browse through the methods of the API to find what they are looking for.
  
What do you think @dwijnand @eed3si9n ? I want to PR this to sbt 1.0.

**Comment by jvican** [comment]
ping @dwijnand & @eed3si9n.

**Comment by dwijnand** [comment]
I know now more why this is. `State` is defined in the commands module, which is not specific to a build system, while `Project` (defined in the main module) is build system specific - `extract` being the way to get the `BuildStructure` and `SessionSettings` from the state.

So to add it it would have to be via an implicit enrichment.

**Comment by jvican** [comment]
> So to add it it would have to be via an implicit enrichment.
  
Yes, that's my suggestion. @Duhemm: do you remember we were discussing about this at some point? We concluded that a nicer API would be better. Do you have any suggestion in mind?
