### ISSUE TITLE
Add sbt-doge implementation upstream

### ISSUE THREAD

**Issue by jvican** [sbt/sbt#3113]
The following paragraph appears in the README of sbt-doge:
```
Current implementation of + cross building operator does not take in account for the crossScalaVersions of the sub projects. Until that's fixed, here's an alternative implementation of it.
```
  
That suggests that the current implementation upstream is incorrect. In my view, sbt-doge is one of the most used sbt plugins, especially in big Scala projects.
  
I suggest that we merge its implementation upstream now that we can :smile:.

**Comment by Duhemm** [comment]
I think this has already been done in https://github.com/sbt/sbt/pull/2613

**Comment by jvican** [comment]
Oh, great, thanks for the pointer @Duhemm! Great to see it merged, we should add this to the feature list in sbt 1.0. Closing.
