### ISSUE TITLE
debugging output when running tests in sbt 1.0.0-M5

### ISSUE THREAD

**Issue by SethTisue** [sbt/sbt#3116]
when I run my ScalaTest tests I see:

```
[debug] 
[debug] 
[debug] 
[info] TestItemEvent(Some(Passed), Vector(TestItemDetail(net.tisue.euler.Problem52, Success, Some(4456))))
[info] EndTestGroupEvent(net.tisue.euler.Problem52, Passed)
[info] StartTestGroupEvent(net.tisue.euler.Problem94)
[info] TestItemEvent(Some(Passed), Vector(TestItemDetail(net.tisue.euler.Problem66, Success, Some(1799))))
```

I'm using Scala 2.12.2 and ScalaTest 3.0.2.

**Comment by CucumisSativus** [comment]
Hey @dwijnand it doesnt look like something complicated. I would be grateful if you could just let me know where can I search for the cause of the problem. I'd love to fix this :)

**Comment by eed3si9n** [comment]
I can tell you where this was added/implemented to help you reverse engineer the behavior:

- https://github.com/sbt/sbt/pull/3066
- https://github.com/sbt/util/pull/74

**Comment by eed3si9n** [comment]
To add a bit more notes, in sbt 1.0.x we adopted log4j 2 instead of using our own logging like we did in sbt 0.13. On one hand, the new code allows us separate log producer (like plugins, or logger) and log consumers, which are implemented as Appender. For the interest of time and backward compatibility older sbt logging was retrofitted in, which may or may not be the most efficient/idiomatic log4j style.

**Comment by SethTisue** [comment]
still present in M6

**Comment by dwijnand** [comment]
Using Seth's Project Euler solutions reproduction (in #3117), here's a before and after for testing just Problem1:

![image](https://user-images.githubusercontent.com/344610/27031477-4d0a1b42-4f68-11e7-8588-4888e4704634.png)

![image](https://user-images.githubusercontent.com/344610/27031485-577c14d6-4f68-11e7-9122-2e2846fe3cec.png)

**Comment by jvican** [comment]
Can you try with a failing test? The logger as it is in M5 is neither showing failing test cases nor stack traces.

**Comment by dwijnand** [comment]
![image](https://user-images.githubusercontent.com/344610/27031755-77f759fe-4f69-11e7-862f-9297bb4b52d8.png)

![image](https://user-images.githubusercontent.com/344610/27031780-949e121e-4f69-11e7-9332-f43adbf13f0d.png)
