### ISSUE TITLE
sbt new command does not accept newline character

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3126]
## steps

Using sbt 1.0.0-M5

1. `$ sbt new sbt/scala-seed.g8`
2. `name [My Something Project]: hello-world`

## problem

When I hit return key it displays `^M`, and does not enter.

## expectation

Return key works.

**Comment by dwijnand** [comment]
I can't reproduce the error:

```bash
$ java -jar ~/.sbt/launchers/1.0.0-M5/sbt-launch.jar new scala/scala-seed.g8
WARN: No sbt.version set in project/build.properties, base directory: /s/sbt1new
[warn] Executing in batch mode.
[warn]   For better performance, hit [ENTER] to switch to interactive mode, or
[warn]   consider launching sbt without any commands, or explicitly passing 'shell'
[info] Set current project to sbt1new (in build file:/s/sbt1new/)

Minimum Scala build.

name [My Something Project]: hello-world

Template applied in ./hello-world
```

**Comment by eed3si9n** [comment]
Hmm. I can't repro it either.

**Comment by lasekio** [comment]
It happens with tmux

**Comment by eed3si9n** [comment]
Ah. I do use tmux sometimes.

**Comment by lasekio** [comment]
Idk but i can reproduce it with tmux having this working on native bash normally on the same machine (Mac os) I use zsh on top of tmux btw.

**Comment by dwijnand** [comment]
Is zsh a pre-condition for this failure?

If it's just a tmux problem, if you could provide steps including whatever tmux steps (I don't know/use tmux) we could reopen this.

**Comment by ignasi35** [comment]
I can reproduce the error in OSX Catalina + iTerm2 + `zsh`: (first attempt runs on `zsh`)

```
~/wip/deleteme
▶ sbt new scala/scala-seed.g8
[info] Loading settings for project global-plugins from build.sbt ...
[info] Loading global plugins from /Users/ignasi/.sbt/1.0/plugins
[info] Set current project to deleteme (in build file:/Users/ignasi/wip/deleteme/)
[info] Set current project to deleteme (in build file:/Users/ignasi/wip/deleteme/)

A minimal Scala project.

name [Scala Seed Project]:
Template applied in /Users/ignasi/wip/deleteme/./myprojectzsh


~/wip/deleteme
▶ /bin/sh
sh: _direnv_hook: command not found
%n@%m %1~ %# sbt new scala/scala-seed.g8
[info] Loading settings for project global-plugins from build.sbt ...
[info] Loading global plugins from /Users/ignasi/.sbt/1.0/plugins
[info] Set current project to deleteme (in build file:/Users/ignasi/wip/deleteme/)
[info] Set current project to deleteme (in build file:/Users/ignasi/wip/deleteme/)

A minimal Scala project.

name [Scala Seed Project]: MyProjectBinSh

Template applied in /Users/ignasi/wip/deleteme/./myprojectbinsh
```

I've been doing some tests with and without `oh-my-zsh` and multiple themes inside  `oh-my-zsh` and the only constant setup was "Catalina + iTerm2 + `zsh`".

Note I haven't tried different OS's or terminal emulators, only changes the shell implementation and settings.

**Comment by ignasi35** [comment]
Ah, just found https://github.com/sbt/util/pull/233 with the fix.
