### ISSUE TITLE
Run `doc` in CI, to catch scaladoc issues

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#3127]
h/t to @fommil for the idea.

This depends on #2812 ("Errors running sbtRoot/compile:doc") to be fixed first.

# Mentoring Instructions

## Links

sbt's Travis CI is split into a matrix of CI, which is found at:

https://github.com/sbt/sbt/blob/1d7b35bd67722511b9a058113e7a1070984e6758/.travis.yml#L31-L45

## Solution

The solution is to either add a new matrix entry of `doc` or add `doc` to one of the existing ones, depending on the relative impacts.

## Testing

The best way to test this is to enable Travis CI on your own fork, and experiment with it building your branch.

## Motivation

The motivation is to catch any scaladoc issues well before a release is cut.

## Background

Historically we've had bad Scaladoc, which we've had to last-minute workaround during a release.

**Comment by jvican** [comment]
This could be a Scala Center spree ticket. Are you gonna be in Scaladays Chicago @dwijnand ?

**Comment by dwijnand** [comment]
Copenhagen*, and yes I will. Labelled.
