### ISSUE TITLE
SBT 0.11.2 Does Not Support Older Versions of Git?

### ISSUE THREAD

**Issue by omervk** [sbt/sbt#313]
Was trying to run an SBT build on an Amazon EC2 machine. The only version of Git that existed for this machine type was 1.5.4.3-3.fc8 and it kept failing while trying to get from a git:// URL because it was trying to clone into an existing directory.

Is this as designed?

**Comment by indrajitr** [comment]
Quite likely a case of a very old git client. Don't remember exact version, but old git clients did have problem with `git` protocol over `ssh`.

Please use a newer version of git client and report back if it still fails.

**Comment by omervk** [comment]
I tried with a newer version prior to filing this issue and it worked, which is why I know this is the issue. However, nothing in the documentation indicates that an older version of git is not supported.

What is the oldest version of git supported by SBT 0.11.2?
