### ISSUE TITLE
Is project/build.properties optional?

### ISSUE THREAD

**Issue by mslinn** [sbt/sbt#314]
The docs seem a bit fragmented when talking about the current role of `project/build.properties` in an SBT project. I have been writing only one line in the file for my projects:

```
sbt.version=0.11.2
```

This means that I need to update the file for all projects each time I download the latest version of the `sbt-launch.jar`. Because I want to always use the latest and greatest version of SBT for development, I tried deleting `project/build.properties` and the projects continue to build as before.

It also seems that most of the former reasons for using project/build.properties have now been migrated to other files.

Is it true that for SBT v0.11+:
- the default value of `sbt.version` is taken from the version of `sbt-launch.jar`?
- the only reason for providing ``projects/build.properties` in an SBT project is to be able to maintain binary compatibility with prior versions of SBT?

Mike

**Comment by ijuma** [comment]
projects/build.properties is optional, but very useful for reproducible builds and it means you don't need to download a new launcher to go from 0.11.0 to 0.11.2 (as an example).

**Comment by indrajitr** [comment]
Yes, `sbt.version` in `project/build.properties` allow you to override the version of SBT used to build project (which could e different from that of the launcher).

One example where you might need to do this is, if your project is dependent on a plugin built for a specific SBT version.
