### ISSUE TITLE
https://dl.bintray.com/sbt/debian/Release not publicly accessible

### ISSUE THREAD

**Issue by zoltanmaric** [sbt/sbt#3144]
Hi everyone! My `sudo apt update` command fails because this file is not publicly accessible (it returns `403 Forbidden`).

## steps
run `sudo apt update` on Ubuntu 16.04
the command fails with
```
Err:17 https://dl.bintray.com/sbt/debian  Release                                                                     
  403  Forbidden
(...)
Reading package lists... Done                                     
E: The repository 'https://dl.bintray.com/sbt/debian  Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

## problem
https://dl.bintray.com/sbt/debian/Release is not publicly accessible

## expectation
https://dl.bintray.com/sbt/debian/Release is publicly accessible

**Comment by dwijnand** [comment]
This root cause is tracked in #3108.
