### ISSUE TITLE
Upgrade the keys in Keys to the macros in Def

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#3146]
This would reduce verbosity and enforce the code-name/runtime-name invariant.

**Comment by dwijnand** [comment]
Most of them won't translate because the macro doesn't allow for the key rank to be defined, and Keys does define ranks for them.

**Comment by dwijnand** [comment]
Or we can add a method to change the rank.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/3367.
