### ISSUE TITLE
tasks list should be made comprehensible

### ISSUE THREAD

**Issue by idot** [sbt/sbt#315]
the output of 'tasks' for a newly generated play2.0 application is 226 lines - this is not useful. it contains a mixture of tasks and settings.

It would be good to have something like:

tasks tasks => show only tasks
tasks settings => show only settings
tasks tasks:play => show only tasks coming from play plugin
tasks settings:play => show only settings coming from play plugin

help tasks does not show any options into this direction ATM.

**Comment by harrah** [comment]
`tasks` only shows tasks and shows a good initial list.  `settings` does the same for settings.  See `help settings` and `help tasks` for details.  Keys do not remember where they came from, which would require compiler support (possibly SourceContext in 2.10).  Even then, I'm not sure it would be sufficient.

This enhancment will require plugin authors to tag keys to have them displayed at the appropriate verbosity level.

Further work may reduce initial tab completions as well, so I'll actually reopen this until that is resolved.

**Comment by harrah** [comment]
I've made some other improvements to the settings/tasks/help commands that I think address this issue.  They will be in 0.12.0-Beta.
