### ISSUE TITLE
[sbt 0.13] Consider backporting withXXX methods for ModuleID and Artifact

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3159]
## steps

1. Cross build plugins.

## problem

Using sbt 0.13.16-M1, plugins can now be cross built between 0.13 and 1.0.
One pattern that comes up is the lack of `.copy(..)` methods.
`ModuleID` came up a few times. https://github.com/sbt/sbt-pgp/pull/100/commits/d1bfc03931a873c27bea79f4b1b43f044210e688

## expectation

For `ModuleID` and `Artifact` it might make sense to "backport" the withXXX methods so we can keep source compat. It would require change to plugin code, but it's still better than rolling out shim yourself.

## notes

The shim looks like this currently:

```scala
// for sbt 0.13
def subExplicitArtifacts(m: ModuleID, artifacts: Vector[Artifact]): ModuleID =
  m.copy(explicitArtifacts = artifacts)

// for sbt 1.0.0-M5
def subExplicitArtifacts(m: ModuleID, artifacts: Vector[Artifact]): ModuleID =
  m.withExplicitArtifacts(artifacts)
```

**Comment by dwijnand** [comment]
I agree this is a good idea. It's great ROI and low risk.
