### ISSUE TITLE
Eviction warning not shown on update

### ISSUE THREAD

**Issue by patrick-premont** [sbt/sbt#3171]
With the following build.sbt

```
lazy val service = (project in file("."))
  .settings(
    scalaVersion := "2.12.2",
    libraryDependencies ++= Seq(
      "de.heikoseeberger"          %% "akka-log4j"               % "1.4.0",
      "com.typesafe.akka"          %% "akka-http"                % "10.0.6"
    )
  )
```

using sbt 0.13.15

I would expect the `sbt clean update` to give the same eviction warning that is visible when I use `sbt evicted`, but it does not appear. 

@eed3si9n, this is the issue you were able to reproduce.

**Comment by eed3si9n** [comment]
Thanks for reporting this. I added `    scalaVersion := "2.12.2",` in the above.
