### ISSUE TITLE
Changing level of verbosity forces update

### ISSUE THREAD

**Issue by jvican** [sbt/sbt#3175]
## steps
1. `compile`.
2. `debug`.
3. `compile`.

## problem
The third `compile` will update again, even if the compiler interface has already been resolved and compiled. The cached compiler is not reused.

## expectation
The level of verbosity should not affect the `compile` task nor force a resolution update.

**Comment by eed3si9n** [comment]
I can't reproduce it on 1.1.0-RC4. Hopefully this was some early bug during the beta.
