### ISSUE TITLE
Server connection error when exiting forcefully in sbt 1.0

### ISSUE THREAD

**Issue by jvican** [sbt/sbt#3176]
(See the guidelines for contributing, linked above)

## steps
1. `sbt`.
2. <C-C> (exit from sbt without using exit).
3. `sbt`.

## problem
```
[error] server failed to start on 127.0.0.1:4985. java.net.BindException: Address already in use (Bind failed)
```

## expectation
Server can successfully start up because there are exit hooks that even in the event of a forceful exit, will shut down the server.

**Comment by eed3si9n** [comment]
Using sbt 1.1.0-RC4, I can't reproduce this on Mac or Ubuntu using the (default) named pipe or TCP:

```
serverConnectionType in Global := ConnectionType.Tcp,
```
