### ISSUE TITLE
updateClassifiers fails to resolve javadocs & sources when target ivy config extends a private config

### ISSUE THREAD

**Issue by linjer** [sbt/sbt#3185]
This was originally posted to the sbt-dev Google group and is being moved here on request from Eugene.

Original thread here: https://groups.google.com/d/msg/sbt-dev/DTFcHXtrU00/82Pd1Ja1BgAJ

## steps

Checkout the branch `bad-ivy-robustness` which you can see here: https://github.com/linjer/sbt/commit/f937b075bbf0eede8182c038f5bec790d0306a6b

i.e., 
1. `git clone git@github.com:linjer/sbt.git`
2. `git checkout bad-ivy-robustness`

Then, the following sequence of commands from the `sbt` project root.

```shell
$ cd sbt/src/sbt-test/ivy-deps-management/update-classifiers-snapshot-srcs
$ sbt bippy/publishLocal
$ cp changes/ivy-1.0-SNAPSHOT.xml target/ivy/local/org.example/bippy_2.11/1.0-SNAPSHOT/ivys/ivy.xml
$ sbt
```

```scala
> myapp/updateClassifiers
> check 1
```
## problem

The problem is that SBT refuses to resolve the javadoc and sources for the `bippy` library because the public configuration that is depended on extends a private configuration. It resolves the main jar just fine.

## expectation

The javadoc and source is still resolved and linked.

## notes

This is reproducible using SBT versions `0.13.11` to `0.13.15`. Sources and libraries are robustly resolved in version `0.13.9`. No other versions have been tested.

SBT refuses to publish Ivy files where a public configuration extends a private, hence what I am calling a "bad ivy" file.

However, it seems that the Ivy specification seems to allow this kind of conf and even include an example that does so: An example of such a configuration is shown in the Ivy configuration example here:
http://ant.apache.org/ivy/history/2.3.0/ivyfile/conf.html

**Comment by eed3si9n** [comment]
Given most users are on Coursier now, I am closing this as won't fix.
