### ISSUE TITLE
Sbt build failes due to proxy depending on used scala version

### ISSUE THREAD

**Issue by martin-riedl** [sbt/sbt#3190]
(See the guidelines for contributing, linked above)

## steps
Being behind a company proxy, I want to compile a simple project using sbt with an external dependeny:
```
libraryDependencies += "com.github.gphat" %% "wabisabi" % "2.2.0"
scalaVersion := "2.12.2"
```
This gives the output
```
[info] Resolving com.github.gphat#wabisabi_2.12;2.2.0 ...
[error] Unable to find credentials for [ @ proxy.xxxxxx.de].
```
whereas for another scalaVersion  
```
libraryDependencies += "com.github.gphat" %% "wabisabi" % "2.2.0"
scalaVersion := "2.11.11"
```
the project compiles successfully. 

## problem
Just to detail the output: 
```
...
[info] Resolving com.github.gphat#wabisabi_2.12;2.2.0 ...
[error] Unable to find credentials for [ @ proxy.xxxxxx.de].
[warn] Your proxy requires authentication.
[warn]  module not found: com.github.gphat#wabisabi_2.12;2.2.0
[warn] ==== local: tried
[warn]   /root/.ivy2/local/com.github.gphat/wabisabi_2.12/2.2.0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/github/gphat/wabisabi_2.12/2.2.0/wabisabi_2.12-2.2.0.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /root/.sbt/preloaded/com.github.gphat/wabisabi_2.12/2.2.0/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////root/.sbt/preloaded/com/github/gphat/wabisabi_2.12/2.2.0/wabisabi_2.12-2.2.0.pom
[info] Resolving jline#jline;2.14.1 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.github.gphat#wabisabi_2.12;2.2.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
```

## expectation
By only using different versions of Scala no difference regarding the compilation process is expected. Here the compilation process behaves differently, at least such that is expects some credentials for the proxy, which are actually not required, as can be seen when using a 2.11 scala version.

**Comment by eed3si9n** [comment]
Do you have `"com.github.gphat" %% "wabisabi" % "2.2.0"` for Scala 2.11 cached in Ivy?
What if you start with an alternative `-Dsbt.ivy.home`?

**Comment by martin-riedl** [comment]
After a number of trials I found out that it's due to the proxy authentication. To distinguish the sbt-traffic from others, the user-agent of the http header is used. BUT: For a transaction numerous requests are posed, with different user-agent entries: 
User-Agent: Java/1.8.0_131
User-Agent: Apache Ivy/2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4
User-Agent: Java/1.8.0_131
This makes it hard to distinguish SBT-Traffic in order to define a rule that lets the requests pass the proxy without authentication. Is it possible to define a consistent USER-AGENT string for SBT for all requests being send?

**Comment by dwijnand** [comment]
sbt doesn't make deal with proxies differently according to what scala version is used. you simply had the 2.11 jar cached locally, but not the 2.12 jar.
