### ISSUE TITLE
Allow for keys (settings/tasks) to be Plugin-Private

### ISSUE THREAD

**Issue by imarios** [sbt/sbt#3192]
There cases where you want to have auxiliary tasks/settings under `projectSettings` so that they have access to properly scoped keys, such as class paths, project names, version, etc. At the same time, those settings/tasks are not meant to be directly usable/viewable/changeable by the plugin users. Even though you want them to be project-scoped you want only other plugin tasks/settings to be allowed to use them. 

It would be great if you could define setting/tasks inside your plugin that are only visible to other tasks/settings defined inside the plugin.

**Comment by eed3si9n** [comment]
> It would be great if you could define setting/tasks inside your plugin that are only visible to other tasks/settings defined inside the plugin.

Could you elaborate what you mean here, please?

Does that mean I can't inspect the setting values from the sbt shell?
Or you're saying that the key should not be exposed to tab completion?
Or referring to the key outside of the plugin would (somehow) result to compilation error?
Isn't it enough just exclude the key from the `autoImport`?

Edit: s/just not exclude/just exclude/

**Comment by imarios** [comment]
Hey Eugene, thank you for taking the time to think about this. Regarding your questions I think they are all answered with "yes". It means that there is no way for someone: (1) to trigger the task from the shell, (2) refer to it inside their own settings or tasks, and (3) to see it listed under help and get it auto-completed. These settings/tasks are only there to be used from within the plugin code. 

Now, a natural question for you to ask is: "Why don't you define them to be just constants and functions?" 

Well, I want these settings/tasks to be executed in the right context/scope. So if my private task asks for the name or the version or classpath or whatever, I want it to get the values defined by the scope it currently runs on. So if it's called on a subproject it will behave differently than if it get's called from ThisBuild, etc. 

Probably, I can just define these as functions and then make sure I pass the proper arguments to them all the way, but (personally I feel that) defining them as task/settings makes it a bit more idiomatic sbt? 

I would love to hear your thoughts.

**Comment by imarios** [comment]
About excluding them from autoImport is an interesting idea. I think I did try that. The problem is that those settings/tasks are defined inside buildSettings, projectSettings, etc so they are actually still viewable/usable by the plugin users. 

Let me confirm this one again.

**Comment by imarios** [comment]
Ok, just gave it a try, I can still call a setting from sbt shell even if I define it outside the `object autoImport`. I still implement it inside `projectSettings` since I want it to be project scoped. If I define it outside there, then I don't know how to scope it properly ...

**Comment by eed3si9n** [comment]
> It means that there is no way for someone: (1) to trigger the task from the shell, (2) refer to it inside their own settings or tasks, ...

As of now (sbt 0.13.x or sbt 1.0.0-M5), sbt does not change behavior from one plugin to another, so sbt defining a built-in settings are no different from the user rewriting it using a plugin or `build.sbt` in terms of the semantics. It's just the matter of scoping and loading order. Changing this to introduce a notion of plugin privacy would be a major change, so tbh I doubt it will happen anytime soon.

What you could try to do is make it very difficult for someone to define the setting by using package-private class.

**Comment by jvican** [comment]
> What you could try to do is make it very difficult for someone to define the setting by using package-private class.
  
... which works, except for the fact that you can reference to the setting or task by using its id: `TaskKey("myPrivateKey")`. But yes, this is the way to go, just wanted to point out its limitations.
  
I side with @eed3si9n, your idea is good @imarios, but it would provoke major changes in the plugin ecosystem and the whole sbt way to reason about settings/tasks, so I would prefer to revisit this in the future.
  
However, it seems that part of your proposal is to make those settings invisible to the end users. To accomodate that use case, we could add an `invisible` annotation that will prevent that setting from being shown in the autocompletion and `inspect` traces. Would that address at least some of the current inconvenience @imarios?
  
```scala
@invisible private val myPrivateKey = settingKey[String]("myPrivateKey", "Oh yes, I'm invisible")
```

**Comment by imarios** [comment]
guys thank you very much for listening. 

@eed3si9n: I understand that this might be quite bit of a change, and obviously this is not a deal breaker. However, just for the record: I  found at least two other developers on SO and gitter that had the same question, so this might be fairly popular question among plugin authors.

@jvican: That would really be helpful! If I don't tell my users the settings are there and they cannot autocomplete them and they need to use the TaskKey("myPrivateKey") to get it working then that would solve 99% of what I worry about. So that would be amazing! 

let me get this right. 


```scala
private lazy val myPrivateKey: SettingKey[File] = settingKey[File]("myPrivateKey")
object autoImport {
     // ... my private key is not here
}
override lazy val projectSettings: Seq[Setting[_]] = myPrivateKey := file(".") :: Nil
```

Does this means that myPrivateKey should not be visible from sbt shell of the projects that use this plugin?

**Comment by jvican** [comment]
>  I found at least two other developers on SO and gitter that had the same question, so this might be fairly popular question among plugin authors.
  
Yes, we should post this information in the docs and link to this thread too.
  
@imarios I think it's okay to define `myPrivateKey` inside `autoImport`, that will prevent plugin authors from importing that value from `autoImport`.
  
The other thing you need to take care of is the sbt shell. By default, the commands that show and inspect the settings will show your private setting no matter if it's private or not.
  
To my surprise, however, I have stumbled upon something that may be *really* useful here: the concept of local settings and tasks. Those local settings and tasks, to my best knowledge, fulfill your need: they are invisible (i.e. not shown on inspect and completions).
  
In `Defaults.scala`, you have an example of how they are used:
```scala
  /** Constructs a setting that declares a new artifact `artifact` that is generated by `taskDef`. */
  def addArtifact(artifact: Initialize[Artifact],
                  taskDef: Initialize[Task[File]]): SettingsDefinition = {
    val artLocal = SettingKey.local[Artifact]
    val taskLocal = TaskKey.local[File]
    val art = artifacts := artLocal.value +: artifacts.value
    val pkgd = packagedArtifacts := packagedArtifacts.value updated (artLocal.value, taskLocal.value)
    Seq(artLocal := artifact.value, taskLocal := taskDef.value, art, pkgd)
  }
```
  
At compile-time, `artLocal` will have a generated free name (this is created in `Attributes.scala`, inside `sbt-util`), so local settings and tasks don't have a name, only an identifier where they are created.
  
It seems that local settings and tasks were hacked to support `local.sbt` files and it seems that they do exactly what you want.
  
I suggest that you:
* Play around with local tasks.
* Put them in a place where they are only accessible to your plugin, like `private[myNamespace]` or something similar.
  
Please, let me know if this works for you.

**Comment by imarios** [comment]
Well, that `SettingKey.local` might be the answer! Let me investigate more and come back with some results. Thank you guys!

**Comment by jvican** [comment]
Hey @imarios, I double-checked this is what we want and wrote a blog post about it: https://jvican.github.io/post/local-tasks-sbt-plugin/. It's not there ready to be announced in the open -- I'd like to make some small remarks and edits -- but I think it can be useful for people wondering the same as you did two weeks ago.

**Comment by imarios** [comment]
@jvican looks really good! this helps a lot for sure.

**Comment by dwijnand** [comment]
Looks to me like `SettingKey.local` is the solution here (undocumented).
