### ISSUE TITLE
Oddity in 1.0.0-M5 when using sbt libs. Message "value xxx is not a member"

### ISSUE THREAD

**Issue by cunei** [sbt/sbt#3196]
### steps
```
$ cat K.scala 
package xyz
class A() {
 def c(s:sbt.ModuleID): sbt.ModuleID = {
    s.copy(name="xxx")
  }
}
$ cat build.sbt
scalaVersion := "2.12.2"
scalacOptions ++= Seq("-Ydebug","-Ylog-classpath")
libraryDependencies += "org.scala-sbt" % "sbt" % sbtVersion.value % "provided"
$ cat project/build.properties 
sbt.version=1.0.0-M5
```
### problem
```
$ sbt compile
[...]
[info] [running phase typer on K.scala]
[error] /home/cunei/iii/kkk/K.scala:4:7: value copy is not a member of <root>.this.sbt.ModuleID
[error]     s.copy(name="xxx")
[error]       ^
```
### expectation
```
[warn] one warning found
[success] Total time: 15 s, completed May 17, 2017 9:19:07 PM
```
(which is what happens with 1.0.0-M4)

**Comment by eed3si9n** [comment]
copy method is actually gone. plz use `.withName("xxx")`.

**Comment by dwijnand** [comment]
See:

* https://github.com/sbt/contraband/pull/38 "Add support for public, overloaded, bincompat copy"
* https://github.com/sbt/contraband/pull/44 "Allow by-name selection by adding parameter default values"
* https://github.com/sbt/contraband/issues/48 "exposing copy is not safe"
* https://github.com/sbt/contraband/issues/49 "Default Arguments vs Interspersed Growth (Design Decision)"
* https://github.com/sbt/contraband/pull/50 "Remove public copy method"
