### ISSUE TITLE
Error when updating sbt using apt: "java: command not found"

### ISSUE THREAD

**Issue by akwala** [sbt/sbt#3197]
(See the guidelines for contributing, linked above)

## steps
When the sbt [Linux (deb) repo](http://www.scala-sbt.org/download.html) has a new update for sbt, do the following at the command prompt:
`> sudo apt-get upgrade`
Enter password if asked, then enter 'Y' when asked whether to proceed.

## problem

> Setting up sbt (0.13.15.3) ... 
> /usr/share/sbt/bin/sbt-launch-lib.bash: line 73: java: command not found
> dpkg: error processing package sbt (--configure): subprocess installed post-installation script returned error exit status 127

## expectation
The sbt update should succeed without error.

## notes
I have the Java bin directory in PATH and I've also set JAVA_HOME:
```
$ java -version
openjdk version "1.8.0_131" OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by ConeyLiu** [comment]
Yeah, I meet the same error when install the sbt with the command `sudo apt-get install sbt`.  The install steps are followed the [document](http://www.scala-sbt.org/download.html). And the error as follow:
```
/usr/share/sbt/bin/sbt-launch-lib.bash: line 73: java: command not found
dpkg: error processing package sbt (--configure):
 subprocess installed post-installation script returned error exit status 127
Errors were encountered while processing:
 sbt
E: Sub-process /usr/bin/dpkg returned an error code (1)

```

**Comment by kYroL01** [comment]
Same error of @ConeyLiu also for me after `apt-get upgrade`.

**Comment by Doriphor** [comment]
`sudo apt-get install default-jre`
fixed it for me!

**Comment by okbonhahaha** [comment]
Same error @ ConeyLiu!! 
please help to fix it, thanks!

**Comment by okbonhahaha** [comment]
Hi all, I just fix this issue. 
To install sbt, we have to install Java first.
https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-get-on-ubuntu-16-04

**Comment by akwala** [comment]
@okbonhahaha As I said in my issue report above, I have Java 8. The issue remains unresolved.

**Comment by akwala** [comment]
The problem seems to be OpenJDK (8) which is what I've been using. Apparently, what's needed is the Oracle Java package -- the installation completed when I installed _Oracle_  Java 8.

**Comment by bovin-a** [comment]
I've had very similar issue.

I've installed JDK manually by downloading *.tar.gz archive from Oracle site. In manual configuration phase I've only added path to JDK to environment variable $PATH:
```
export JAVA_HOME=path_to_jdk
export PATH=$PATH:path_to_jdk/bin
```

After that i've tried to install SBT as official site says:
```
echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
sudo apt-get update
sudo apt-get install sbt
```
And have got the very similar error as @akwala posted. I've resolved this issue when add this step in manual configuration phase:
```
sudo update-alternatives --install /usr/bin/java java path_to_jdk/bin/java 1
```

**Comment by daniel-sali** [comment]
For me, on CentOS 7, the solution to the issue was actually installing the `bc` command with `sudo yum install bc`, as the sbt runscript uses it to compare the installed Java version with the required 1.6 version.

**Comment by james-turner** [comment]
This has happened to me in the last 30 minutes (builds were fine before this point). And I concur with daniel-sali that adding bc to the list of dependencies seemed to do it for me (i'm using openjdk so i dont know if this is the cause or coincidence).
  
    [Container] 2017/10/27 21:41:12 Running command sbt docker
    /usr/share/sbt/bin/sbt-launch-lib.bash: line 207: bc: command not found

    The java installation you have is not up to date
    requires at least version 1.6+, you have
    version 1.8

    Please go to http://www.java.com/getjava/ and download
    a valid Java Runtime and install before running .

It may be worth saying that I don't know if there is some race condition with the package installations. I'm doing this in 1 line

    apt-get install bc openjdk-8-jre sbt -y

**Comment by AlistairB** [comment]
I get this issue as of `1.0.3`. `1.0.2` reliably works.

```Dockerfile
FROM openjdk:8u141-jdk

RUN  apt-get update \
  && apt-get install -y \
    apt-transport-https \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /var/tmp/*

RUN echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list \
    && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823

ENV SBT_VERSION 1.0.3

RUN apt-get update \
  && apt-get install -y sbt=$SBT_VERSION \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /var/tmp/*
```

EDIT: `apt-get install bc` does fix it

**Comment by dwijnand** [comment]
`bc` will be a dependency of 1.0.4: https://github.com/sbt/sbt-launcher-package/pull/191.

**Comment by dejan2609** [comment]
Just FYI: sbt `1.0.3` has same issues on Windows:

```
dejans@BEG-IT-09 MINGW64 ~
$ sbt version
/c/Program Files (x86)/sbt/bin/sbt-launch-lib.bash: line 207: bc: command not found

The java installation you have is not up to date
requires at least version 1.6+, you have
version 1.8

Please go to http://www.java.com/getjava/ and download
a valid Java Runtime and install before running .


dejans@BEG-IT-09 MINGW64 ~
$ java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

dejans@BEG-IT-09 MINGW64 ~
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.19]

dejans@BEG-IT-09 MINGW64 ~
$ date
05 Nov 2017 16:45:09

dejans@BEG-IT-09 MINGW64 ~
```

**Comment by skonto** [comment]
Same issue here with sbt 1.0.3 and java oracle sdk 8.
```$ java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```
Machine: ubuntu 16.04 with clean install. Installing bc fixed it (as mentioned earlier).

**Comment by tanel3203** [comment]
Same situation as previous poster (ubuntu, java 1.8.0_151). installing bc solved it for me also.

Issue:
"The java installation you have is not up to date
requires at least version 1.6+, you have
version 1.8"

Solution from AlistairB's post: `apt-get install bc`

**Comment by philliptann** [comment]
Had the same problem, AlistairB solution worked for me :)
sudo apt-get install bc

**Comment by Angel-Solis-Gozar** [comment]
> `sudo apt-get install default-jre` fixed it for me!

Love you!
