### ISSUE TITLE
Introduce quietErrorSummary setting and use it in compile task

### ISSUE THREAD

**Issue by ijuma** [sbt/sbt#32]
Mark said:

" It can probably be done like aggregation, with a quietErrorSummary setting that can be set per-task and the summarizing code checks the setting for each task in the list.  'compile' can have it quiet by default."

The use-case that motivated this is the compile task. An example of output:

[error] /media/ssd1/src/sbt-idea/sbt-idea-core/src/main/scala/com/github/mpeltonen/SbtIdeaPlugin.scala:10: ')' expected but 'val' found.
[error]     val structure = extracted.structure
[error]     ^
[error] one error found
[error] Incomplete tasks (run 'last <task>' for the full log):
[error]   {file:/media/ssd1/src/sbt-idea/}core/compile: Compilation failed
[error] Total time: 0 s, completed 02-Jun-2011 19:05:51

The "Incomplete tasks.." message doesn't add much value and it would be good to exclude it for something as common as reporting of compiler errors.

This was discussed here:
https://groups.google.com/d/topic/simple-build-tool/zik0-_uk4r4/discussion

**Comment by harrah** [comment]
I'm not clear on what this should do anymore.  It is obvious for a single-module project where the only failure is the compile task.  However, in a multi-module project, I want to know which sub-module failed.  Even in a single-module project, I want to know whether it was compile or test:compile.  One thing you can do is disable the final success/failure message.  Or, we can allow the "Incomplete tasks" line to be disabled.  What do you think?

**Comment by ijuma** [comment]
The  "Incomplete tasks" line is indeed what I'd like to disable. It makes it sound like there is more to it than the compiler error and suggests an action that is not particularly helpful. I agree that the rest is useful.

**Comment by harrah** [comment]
This is probably easy to do either way, but do you think it should be removed completely or have a setting for it?  If a setting, should it be on/off by default?  I don't care personally because I know about the 'last' command already.

**Comment by ijuma** [comment]
Good question. It is true that once a user knows that he can use "last", he probably doesn't care for that message. I wouldn't mind if it was simply removed.

On the other hand, it's useful for new users who don't read documentation. I think it's particularly helpful for tasks that can fail _and_ generally need debugging (e.g. update). So, perhaps the ideal scenario would be to have a setting and have it off for tasks that are known to fail frequently and that include the useful information in the normal output.

But as I said earlier, I'd also be happy with just removing it for now and waiting for a possible reintroduction depending on feedback.
