### ISSUE TITLE
Configuration inheritance doesn't guarantee versions match

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#3201]
## steps

1. Publish library foo version 1.0.0, which contains `package object foo { def x = 1 }`
2. Publish library foo version 1.0.1, which contains `package object foo { def x = 2 }`
3. Publish library bar, which depends on library foo version 1.0.1
4. In project bippy, depends on foo and bar:

```scala
libraryDependencies += "com.dwijnand" %% "foo" % "1.0.0"
libraryDependencies += "com.dwijnand" %% "bar" % "1.0.0" % Test
```

## problem

When bippy is published it will be compiled against foo 1.0.0 & declare foo 1.0.0 as its dependency in its POM (or ivy.xml).

However, because of the dependency of bar on foo 1.0.1, bippy is never tested against foo 1.0.0: it's tested against foo 1.0.1.

There are no guarantees that bippy _actually_ works with the dependencies it declares (in its POM).

```scala
> runMain Main
[info] Running Main
foo.x = 1
[success] Total time: 0 s, completed 19-May-2017 18:44:21
>
> test:runMain Main
[info] Running Main
foo.x = 2
[success] Total time: 0 s, completed 19-May-2017 18:44:23
```
## expectation

I expect that the same version dependencies that results version conflict resolution in 'compile' are used when running tests. And similar for runtime, etc configurations.

**Comment by eed3si9n** [comment]
It seems like you're describing class shadowing, which is a feature/behavior of how classpath-based ClassLoader loads class. To prevent that you might want to look into OSGi or Java Modules. I think it's out of scope for sbt.

**Comment by dwijnand** [comment]
There's no class shadowing going on.  The example is more of a demonstration of how the transitive dependencies of test dependencies can compromise the quality of the test.

I'm fine with closing this off, but I think the solution is to move to version ranges following semver (or a Scala version of semver for bincompat), along with the necessary safe-guards/pinning/freezing for reproducible builds.  Then this could be solved with one of the following two solutions:
1. assuming the compile dependency on foo 1.0.0 means ">=1.0.0 <1.1.0", then foo 1.0.1 would be resolved because that's the latest semver-compliant version, so `runMain Main` would always return "foo.x = 2"; or
1. assuming the compile dependency on foo 1.0.0 means "==1.0.0", then the test configuration wouldn't be solvable because you can't satisfy both foo==1.0.0 and foo==1.0.1.
