### ISSUE TITLE
^^ sbt-crossbuilding does not set scalaVersion correctly

### ISSUE THREAD

**Issue by jastice** [sbt/sbt#3205]
## steps

1. create an sbt plugin: `sbt new sbt/sbt-autoplugin.g8`
2. set `sbt.version=0.13.16-M1`
2. try to cross-compile: `^^ 1.0.0-M5 compile`

## problem

the scripted plugin isn't resolved for 1.0 because the scalaVersion is incorrect:

```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scala-sbt#scripted-sbt_2.10;1.0.0-M5: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

## expectation

The scalaVersion is set to a version compatible with the sbt version targeted

**Comment by jvican** [comment]
Can someone add this to the sbt 1.0 RC milestone? Solving this issue inside sbt is a must before a RC.

**Comment by dwijnand** [comment]
This is correlated to the request to requiring scalaVersion be set, aka not defaulting scalaVersion: https://github.com/sbt/sbt/issues/2795

FWIW I solved this for myself by defining a SbtVersionSeries sum type:

```scala
import sbt._, Keys._

sealed trait SbtVersionSeries
case object Sbt013 extends SbtVersionSeries
case object Sbt1   extends SbtVersionSeries

object CrossBuildingPlugin extends AutoPlugin {
  override def requires = plugins.JvmPlugin
  override def trigger  = allRequirements

  object autoImport {
    val sbtPartV = settingKey[Option[(Int, Int)]]("")
    val sbtVersionSeries = settingKey[SbtVersionSeries]("")
  }
  import autoImport._

  override def globalSettings = Seq(
    sbtPartV := CrossVersion partialVersion (sbtVersion in pluginCrossBuild).value,
    sbtVersionSeries := (sbtPartV.value match {
      case Some((0, 13)) => Sbt013
      case Some((1, _))  => Sbt1
      case _             => sys error s"Unhandled sbt version ${(sbtVersion in pluginCrossBuild).value}"
    })
  )
}
```

and in build.sbt defining

```scala
scalaVersion :=
  (sbtVersionSeries.value match { case Sbt013 => "2.10.6"; case Sbt1 => "2.12.2" })
```

**Comment by jvican** [comment]
Thanks for that snippet. I saw something similar in sbt-structure and I wanted to use it, but was not sure it solved the issue.
  
Do you have any idea how we can solve this upstream?

**Comment by dwijnand** [comment]
I'll give it some thought.

**Comment by dwijnand** [comment]
I had a long look and attempt to fix this, but, depending on what kind of fix we want, I don't see an obvious way to fix this. Here are some notes:

The way the plugin cross-building functionality works is by defining `sbtVersion in GlobalScope in pluginCrossBuild` here: https://github.com/sbt/sbt/blob/v1.0.0-M6/main/src/main/scala/sbt/PluginCross.scala#L44

My attempts were to define `scalaVersion` in accordance to the sbt version given, but there's no clear and simply way to do that. For instance this massive block of code is how `++2.12.2` changes scala version: https://github.com/sbt/sbt/blob/v1.0.0-M6/main/src/main/scala/sbt/Cross.scala#L191-L297. While this other is how `set every` works: https://github.com/sbt/sbt/blob/v1.0.0-M6/main/src/main/scala/sbt/internal/SettingCompletions.scala#L27-L58.

One other solution I looked at is that of defining, defaulting and using a set of scala version keys, like so:

```scala
val scala29 = SettingKey[String]("scala29", "The version of Scala 2.9.x to use", BSetting)
val scala210 = SettingKey[String]("scala210", "The version of Scala 2.10.x to use", BSetting)
val scala211 = SettingKey[String]("scala211", "The version of Scala 2.11.x to use", BSetting)
val scala212 = SettingKey[String]("scala212", "The version of Scala 2.12.x to use", BSetting)
val scala213 = SettingKey[String]("scala213", "The version of Scala 2.13.x to use", BSetting)
val scala214 = SettingKey[String]("scala214", "The version of Scala 2.14.x to use", BSetting)
val scala215 = SettingKey[String]("scala215", "The version of Scala 2.15.x to use", BSetting)
```

That way a plugin author wouldn't define `scalaVersion` any more, but instead would define:

```scala
sbtPlugin := true
 scala210 := "2.10.5"
 scala212 := "2.12.1"
```

and then use `^^` without issue.

Un-assigning myself for now.

**Comment by dwijnand** [comment]
Note that this affects not just `^^` usage but also `^` (and therefore `crossSbtVersions`) usage (https://github.com/sbt/sbt/issues/3305)

**Comment by eed3si9n** [comment]
btw this actually works if you just comment out `scalaVersion`:

```scala
// scalaVersion := "2.10.6"
```

We can potentially override Scala version in `^^` again.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/3362.
