### ISSUE TITLE
org.scala-sbt#sbt;0.13.15: not found

### ISSUE THREAD

**Issue by duytruong** [sbt/sbt#3206]
## steps
1. download [sbt-0.13.15.zip](https://github.com/sbt/sbt/releases/download/v0.13.15/sbt-0.13.15.zip)
2. extract to `/usr/local/sbt`
3. set SBT_HOME and add $SBT_HOME/bin to PATH
4. run `sbt` in terminal

## problem
Can't run sbt, got `org.scala-sbt#sbt;0.13.15: not found`
Full log:
```
Getting org.scala-sbt sbt 0.13.15  (this may take some time)...

:: problems summary ::
:::: WARNINGS
		module not found: org.scala-sbt#sbt;0.13.15

	==== local: tried

	  /home/duyrau/.ivy2/local/org.scala-sbt/sbt/0.13.15/ivys/ivy.xml

	  -- artifact org.scala-sbt#sbt;0.13.15!sbt.jar:

	  /home/duyrau/.ivy2/local/org.scala-sbt/sbt/0.13.15/jars/sbt.jar

		::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: org.scala-sbt#sbt;0.13.15: not found

		::::::::::::::::::::::::::::::::::::::::::::::



:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
unresolved dependency: org.scala-sbt#sbt;0.13.15: not found
Error during sbt execution: Error retrieving required libraries
  (see /home/duyrau/.sbt/boot/update.log for complete log)
Error: Could not retrieve sbt 0.13.15
```

## expectation
`sbt` run successfully without download dependencies due to [offline-installation](https://github.com/sbt/sbt-launcher-package/pull/145)

## notes
OS: Ubuntu 16.04 LTS 64 bit
Scala: 2.11.8
JDK: Oracle JDk 1.8.0_102

**Comment by duytruong** [comment]
Fixed, I created `local` directory in `~/.ivy2` and copy `local-preloaded` to `~/.ivy2/local`

**Comment by feliperazeek** [comment]
good idea @duytruong!

**Comment by scadgek** [comment]
Shouldn't this be fixed somehow or at least documented?

**Comment by sahil-sawhney** [comment]
@duytruong could you please elaborate your solution
Thanks

**Comment by duytruong** [comment]
Hi @sahil-sawhney 
As mentioned, I created a directory named `local` manually in `~/.ivy2` and copy the `local-preloaded`'s content to `~/.ivy2/local` (`local-preloaded` is shipped with universal sbt tgz package).

Hope this helps!
If you have any problem, feel free to ask me!

**Comment by sahil-sawhney** [comment]
I tried with the solution you proposed but it dint worked.
Used following command to copy stuff
**cp -r /usr/local/sbt/lib/local-preloaded /root/.ivy2/local**

**Comment by duytruong** [comment]
@sahil-sawhney the destination is `~/.ivy2/local`, not `/root/.ivy2/local`. The `~/.ivy2/local` must contain all sub-directories of `local-preloaded`

**Comment by lmazzon** [comment]
That worked for me!
Thanks a lot

**Comment by JLucky** [comment]
Thanks, it solved the problem. Actually, copy the ~/sbt/lib/local-preloaded's sub-directories to ~/.ivy2/local/

**Comment by sandip-bhosale** [comment]
[New folder.zip](https://github.com/sbt/sbt/files/3844339/New.folder.zip)
