### ISSUE TITLE
cross-building to milestones doesn't set major version source directories

### ISSUE THREAD

**Issue by jastice** [sbt/sbt#3217]
## steps

```
^^ 1.0.0-M5 compile:sourceDirectories
```

## problem

Instead of adding `src/main/scala-sbt-1.0` to the source directory, only the full version is set (`src/main/scala-sbt-1.0.0-M5`)

```
[info] 	List(/Users/jast/workspace/sbt-structure/extractor/src/main/scala-2.12, /Users/jast/workspace/sbt-structure/extractor/src/main/scala, /Users/jast/workspace/sbt-structure/extractor/src/main/java, /Users/jast/workspace/sbt-structure/extractor/src/main/scala-sbt-1.0.0-M5, /Users/jast/workspace/sbt-structure/shared/src/main/scala,  /Users/jast/workspace/sbt-structure/extractor/target/scala-2.12/sbt-1.0.0-M5/src_managed/main)
```

## expectation

`src/main/scala-sbt-1.0` is added instead of, or in addition to, the milestone version.

**Comment by jvican** [comment]
Yes, it's normal that this happens with milestones since no guarantee of bincompat is provided. This cannot be fixed in a general way because module resolution always expects the binary version to be full for milestone and bin for "stable" releases.

**Comment by jastice** [comment]
The issue here is not bincompat or module resolution, just source compatibility. of course that's also not guaranteed for milestones, but anyway :)

**Comment by jvican** [comment]
@jastice You're right, I only wanted to remark that changing this in a general way is not possible. How severe do you think this issue is? Hopefully, we'll be out milestone in one month and X days.

**Comment by jastice** [comment]
not very severe, I can work around it easily, it just makes my build even more ugly :P

**Comment by dwijnand** [comment]
My feeling is this isn't worth fixing.
