### ISSUE TITLE
Publish fails because it does not create folders in artifact path

### ISSUE THREAD

**Issue by tlazaro** [sbt/sbt#323]
I'm trying to publish into my Cloudbees repository and got into a problem where folders are no created. I get a 'Forbidden' error because of that.

I asked over at Cloudbees forum: https://cloudbees.zendesk.com/entries/20836643

If I change the version of my artifact it would end up in a different path. That would require me to manually create the required folders.

Perhaps other servers handle this in a different way and it just works. But, would it be possible to have SBT create the folder path before sending the file?

**Comment by dlecan** [comment]
+1, same problem for me when publishing with webdav protocol.

**Comment by martiell** [comment]
Another +1 vote. :o)

The maven webdav plugin creates directories as required. The logic is here:
http://maven.apache.org/wagon/wagon-providers/wagon-webdav-jackrabbit/xref/org/apache/maven/wagon/providers/webdav/WebDavWagon.html#123

It'd be cool if sbt would do this too.

**Comment by literalice** [comment]
+1, I've had the same problem when publishing to Cloudbees.

**Comment by stephanos** [comment]
Tip: I use the plugin [arktekk/sbt-aether-deploy](https://github.com/stephanos/sbt-aether-deploy/blob/master/src/sbt-test/deploy/webdav/build.sbt) - works great!

**Comment by diversit** [comment]
Not knowing about Aether, I created a specific Sbt plugin to create the required Webdav collections so the publish task works as expected.
See https://bitbucket.org/diversit/webdav4sbt

**Comment by eed3si9n** [comment]
Given that there seems to be plugins to close the gap, I'm closing this issue.
