### ISSUE TITLE
Redirect sbt documentation for 0.12.x

### ISSUE THREAD

**Issue by jvican** [sbt/sbt#3231]
The docs for 0.12.x are a source of confusion for users visiting our documentation. Lots of the links in Google redirect to the 0.12.x instead of 0.13.x, and while there's a popup suggesting users to visit 0.13.x, the link to the docs does not always work.
  
I believe that having these docs available is not useful anymore -- we should encourage people to upgrade to 1.0.x. I propose to remove the docs for 0.12.x. *To avoid rendering the existing doc links unusable*, I suggest that we redirect the existing 0.12.x links directly to docs for the 0.13.x series.

**Comment by eed3si9n** [comment]
I'm against removing old docs.
We should use site maps with priorities instead, or try to exclude it from indexing via `robots.txt`.

**Comment by jvican** [comment]
@eed3si9n Can you please elaborate why you want to keep those outdated docs? *Note* that in the ticket description I say clearly that I would like them to be automatically redirected to the new ones (i.e. 0.13.x), not completely removed.
  
Soon we'll have 3 different documentation sites for sbt, and I think that's not acceptable. As evidenced in the [Scala Contributors thread](https://contributors.scala-lang.org/t/asking-for-your-feedback-on-sbt-scala-center-announcement/738/31), people feel this is confusing.
  
I have to add that, IMO, they are not only confusing but increase the time users spend browsing the docs until they get to the desired destination. I wouldn't qualify this as the best docs experience.

**Comment by eed3si9n** [comment]
The current situation is partially caused by the lack of Google site map XML that I removed.
I think any responsible library and tooling should keep the old documentations around since you occasionally have to dig them up.

**Comment by jvican** [comment]
Sure, and you can keep those docs locally if you wish so, or put them in another namespace. Your observations do not seem to block my proposals.

**Comment by eed3si9n** [comment]
See also:

- http://akka.io/docs/other-releases.html
- https://www.playframework.com/documentation/2.0.x/Home

**Comment by jvican** [comment]
My proposal is the following:
  
1. Keep old docs in an archive with a different namespace.
2. Link to it in the bottom of every page (or even show a non-intrusive popup window saying something like "Are you looking for docs of previous versions? Check the archive.")
3. Redirect the links used for old sbt docs to the new ones.

**Comment by olafurpg** [comment]
The 0.12 docs are still the top search results on Google when looking for sbt topics

<img width="665" alt="screen shot 2017-06-30 at 14 51 20" src="https://user-images.githubusercontent.com/1408093/27736238-a62317da-5da3-11e7-9f28-f39f6960ed3b.png">

<img width="666" alt="screen shot 2017-06-29 at 10 48 41" src="https://user-images.githubusercontent.com/1408093/27679345-b8e2da9a-5cb8-11e7-88dc-60d46639b527.png">

I wouldn't be surprised if many beginners click on the 0.12 links. The scaladocs and sxr don't show any warning that those docs are outdated.

**Comment by eed3si9n** [comment]
https://github.com/sbt/website/pull/738 added outdated banner like Akka.

https://github.com/sbt/sbt.github.com/commit/60f8cdff5a3d20c34baff8bceb182f912582f50c should exclude 0.13 or 0.12 docs from future indexing.
