### ISSUE TITLE
Capture stack trace on task failure

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3234]
## steps

Some task fails.

## problem

`last` doesn't show the stack trace.

**Comment by dwijnand** [comment]
This is more logging related breakage. I can't grok how it's meant to work and why it's broken. I have some incomplete bits and pieces patches locally that I'll review and publish, but I suspect that this is the first place that should be changed: https://github.com/sbt/util/blob/v1.0.0-M24/internal/util-logging/src/main/scala/sbt/internal/util/ManagedLogger.scala#L18
