### ISSUE TITLE
deb install - sbtopts location

### ISSUE THREAD

**Issue by yurique** [sbt/sbt#3243]
## steps

* install via deb channel (`https://dl.bintray.com/sbt/debian`)
* run `sbt -h`
```
Usage:  [options]
// ...
  /etc/sbt/sbtopts   if this file exists, it is prepended to the runner args
// ...
```
* edit `/etc/sbt/sbtopts` and add some settings
* run sbt 

## problem

The parameters from the `/etc/sbt/sbtopts` are not applied.

## expectation

The parameters from `/etc/sbt/sbtopts` to be applied.

## notes

In the `/usr/bin/sbt` there's this
```
declare -r etc_sbt_opts_file="${sbt_home}/conf/sbtopts"
```

so it looks for `sbtopts` file in `/usr/share/sbt/conf/sbtopts` - putting the settings there actually works.

But when sbt package gets updated `/usr/share/sbt/conf/sbtopts` gets overwritten.

**Comment by yurique** [comment]
I'm sorry for bothering anyone seeing this again, but this one is bad. Today `apt upgrade` updated the sbt package without me noticing it.

I started getting `java.lang.OutOfMemoryError: Metaspace` when running tests - walked through a dozen of files to see where I might have broken thingst. And it turned out that the `/usr/share/sbt/conf/sbtopts` was silently replaced by the default one from the deb package and `OutOfMemoryError` was coming from the now-missing memory settings for sbt :)

**Comment by yurique** [comment]
It's me again, sorry. Got another update from the deb channel and it's overwritten my `sbtopts` again. Should I report this somewhere else?

**Comment by eed3si9n** [comment]
Hi, it hasn't been a priority to look into this. I just set environment variable like `SBT_OPTS`.

The relevant bits are here (https://github.com/sbt/sbt-launcher-package/tree/master/src/universal/bin) if you'd like to look into fixing it, or suggest a fix.

**Comment by yurique** [comment]
@eed3si9n, thanks for pointing me to that location! I've created a PR to fix this issue: 
https://github.com/sbt/sbt-launcher-package/pull/179

> it hasn't been a priority to look into this

Of course, it was a busy summer for sbt :)

**Comment by eed3si9n** [comment]
Thanks again for the contribution!
Fixed in https://github.com/sbt/sbt-launcher-package/pull/179
