### ISSUE TITLE
sbt 1.0.0-M6 depends on scalafmt

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt#3244]
## steps

curl https://dl.bintray.com/sbt/maven-releases/org/scala-sbt/main_2.12/1.0.0-M6/main_2.12-1.0.0-M6.pom

```xml
        <dependency>
            <groupId>com.geirsson</groupId>
            <artifactId>scalafmt-core_2.11</artifactId>
            <version>0.6.8</version>
        </dependency>
        <dependency>
            <groupId>com.lucidchart</groupId>
            <artifactId>scalafmt-impl</artifactId>
            <version>0.3-0.6</version>
        </dependency>
```

## problem
I think scalafmt dependency is unnecessary

**Comment by jvican** [comment]
Totally unnecessary, thanks for the report.

**Comment by olafurpg** [comment]
Those dependencies should be restricted to the `Scalafmt` configuration, see https://github.com/lucidsoftware/neo-sbt-scalafmt/blob/545079f93f3fdf428c9611b7eb7f575bf978cf59/sbt-scalafmt/src/main/scala/com/lucidchart/sbt/scalafmt/ScalafmtCorePlugin.scala#L207 fwiw, the configuration doesn't seem to be hidden.

I would like to use this opportunity to further motivate https://github.com/sbt/sbt/issues/2879 If there was some approachable `getJars(ModuleId): Def.Initialize[Task[Seq[File]]]` interface that does not do weird stuff with scala-library then this issue could have been avoided in the first place.

cc/ @pauldraper

**Comment by pauldraper** [comment]
Like @olafurpg is correct; sbt-scalafmt restricts the dependency to scalafmt config.

I changed scalafmt to a hidden config in 0.4 of sbt-scalafmt; not sure if that will have an effect.

**Comment by dwijnand** [comment]
I ran `publishLocal` and `publishM2` on the latest of the 1.0.x branch and there are no references to scalafmt in either:

```
14:43:57 $ grep scalafmt ~/.ivy2/local/org.scala-sbt/main_2.12/1.0.0-SNAPSHOT/poms/main_2.12.pom

14:45:15 ! grep scalafmt ~/.m2/repository/org/scala-sbt/main_2.12/1.0.0-SNAPSHOT/main_2.12-1.0.0-SNAPSHOT.pom

14:45:19 !
```
