### ISSUE TITLE
please add toString and more debug logging

### ISSUE THREAD

**Issue by thkoch2001** [sbt/sbt#325]
I finally found the sbt log file in /tmp/sbt*.log. I missed it before because 
I thought the update.log file in the boot folder would be the log.
Now I can see the debug output, but there isn't that much information to help 
me debugging.

Could you/we/me please add toString methods to:
- xsbt.boot.Provider
- xsbt.boot.AppConfiguration
- sbt.State

and log.debug sbt.State.toString at 
sbt.MainLoop.runWithNewLog before run(loggedState)

I tried to just add 
state.log.debug("...")
at that point but it complained
Global logging misconfigured

Google's Guava libraries have the toStringHelper. Is there anything similar in 
Scala?

(mail copied from mailing list, posted 22. dec)

**Comment by eed3si9n** [comment]
I'm closing this case since there hasn't been any progress. fwiw sbt uses `Show` typeclass in some places instead of `toString`.
