### ISSUE TITLE
Print ugly warning when using http resolver

### ISSUE THREAD

**Issue by benmccann** [sbt/sbt#3251]
Time and time again I see people using http resolvers when https versions are available. Can we please print a huge warning on the screen when http is used as it's a big security risk? See http://www.ontoillogical.com/blog/2014/07/28/how-to-take-over-any-java-developer/

**Comment by SethTisue** [comment]
@eed3si9n this can be closed now, yes? as per #4905

**Comment by eed3si9n** [comment]
Yes!

@benmccann such insight. I should've done this earlier.
