### ISSUE TITLE
"Illegal character in path" on Windows when username is with spaces makes sbt unusable

### ISSUE THREAD

**Issue by michalzubkowicz** [sbt/sbt#3253]
![screenshot_39](https://user-images.githubusercontent.com/3389709/26867832-2d06aebe-4b67-11e7-98ef-7f92317e0262.png)
## steps
1) Create user on Windows 10 with spaces like "LaLa LaLa"
2) Execute "sbt run"

## problem
It shows exception "Illegal character in path at index 25" 

## expectation
Should run application

## notes

sbt version: 0.13.15

**Comment by laughedelic** [comment]
Same: https://github.com/sbt/sbt/issues/1412.

**Comment by eed3si9n** [comment]
I think this is now fixed.
