### ISSUE TITLE
Making stand-alone jar

### ISSUE THREAD

**Issue by mslinn** [sbt/sbt#326]
Is there an idiot's guide to making a stand-alone jar for a simple project with SBT 0.11.2? All the StackOverflow postings I found either did not work because SBT changed so much, or the information provided required the reader to fill in more blanks than I was able to.

Thanks,

Mike

**Comment by softprops** [comment]
Have you checked out @eed3si9n's https://github.com/sbt/sbt-assembly? It should be pretty straight forward

**Comment by mslinn** [comment]
Worked perfectly, thank you!

**Comment by softprops** [comment]
Don't thank me, thank @eed3si9n. He's and sbt wizard.

**Comment by softprops** [comment]
You can probably close this then @harrah
