### ISSUE TITLE
download dependence from ftp url not working

### ISSUE THREAD

**Issue by abdelrahmanmohamed** [sbt/sbt#3264]
takes a long time and doesn't resolve
 libraryDependencies ++="javaxwsdl" % "javax.wsdl" % "1.6.2" from "ftp://ftp.no.freebsd.org/pub/eclipse/releases/luna/201406250900/plugins/javax.wsdl_1.6.2.v201012040545.jar"

**Comment by eed3si9n** [comment]
Thanks for the report. Could you tell us what version of sbt were you using?

**Comment by abdelrahmanmohamed** [comment]
0.13

**Comment by dwijnand** [comment]
Do you mean 0.13.0?

You should find the version of sbt you're using for your build in `project/build.properties`.

**Comment by abdelrahmanmohamed** [comment]
0.13.15

**Comment by SethTisue** [comment]
```
% curl -O -L 'ftp://ftp.no.freebsd.org/pub/eclipse/releases/luna/201406250900/plugins/javax.wsdl_1.6.2.v201012040545.jar'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (9) Server denied you to change to the given directory
```

🤷
