### ISSUE TITLE
Having sbt cache separate per project

### ISSUE THREAD

**Issue by usamec** [sbt/sbt#3270]
## steps

Run sbt in two project simultaniously.

## problem
Second one says:
Waiting for lock on /home/usamec/.ivy2/.sbt.ivy.lock to be available...

Also sometimes dependencies gets messed up.

## expectation
Both projects compile at the same time.
Ability to configure sbt to have caches not per HOME directory put per project directory.

## notes

sbt version: 0.13.15

**Comment by xuwei-k** [comment]
http://www.scala-sbt.org/0.13/docs/Library-Management.html#Ivy+Home+Directory

**Comment by usamec** [comment]
`sbt -ivy ./.ivy2`
works.
But I did not find any option how to set this globally.

**Comment by dwijnand** [comment]
You could set:

```scala
ivyPaths := new IvyPaths(baseDirectory.value, Some((baseDirectory in ThisBuild).value / ".ivy2")
```

in `~/.sbt/0.13/global.sbt`

**Comment by jonas-db** [comment]
@dwijnand Sorry for re-opening, but is there something similar I can do to avoid, when running mulitple sbt builds at the same time?:
`Waiting for lock on /home/.../.sbt/boot/sbt.boot.lock to be available`

**Comment by cbrunnkvist** [comment]
@jonas-db yup .. discovered that the hard way. When exceeding a certain level of build-paralellism & `sbt.boot.lock to be available`, later on random versions start resolving as `NaN` and version `0.0` and there goes the neighborhood.

**Comment by cbrunnkvist** [comment]
Ex:
```
Downloading https://repo.typesafe.com/typesafe/ivy-releases/org.codehaus.plexus/plexus/3.3.1/ivys/ivy.xml.sha1
https://repo.typesafe.com/typesafe/ivy-releases/org.apache.commons/commons-parent/34/ivys/ivy.xml.sha1 (NaN %, 0 / 0)
https://repo.typesafe.com/typesafe/ivy-releases/org.apache.commons/commons-parent/34/ivys/ivy.xml (NaN %, 0 / 0)
https://repo.typesafe.com/typesafe/ivy-releases/org.codehaus.plexus/plexus-components/1.3.1/ivys/ivy.xml.sha1 (NaN %, 0 / 0)
https://repo.typesafe.com/typesafe/ivy-releases/org.codehaus.plexus/plexus-components/1.3.1/ivys/ivy.xml (NaN %, 0 / 0)
```

**Comment by cbrunnkvist** [comment]
(note that the `.sbt.boot.lock` issue is unrelated to the topic of this ticket which is about `.sbt.ivy.lock` - perhaps it deserves a ticket for itself @jonas-db ?)

**Comment by hacetin** [comment]
> ```scala
> ivyPaths := new IvyPaths(baseDirectory.value, Some((baseDirectory in ThisBuild).value / ".ivy2")
> ```

An update to this:

For sbt 1.9.8, you can set `ivyPaths := IvyPaths(baseDirectory.value, Some((baseDirectory in ThisBuild).value / ".ivy2"))
` in `~/.sbt/1.0/global.sbt`
