### ISSUE TITLE
Reconsider warning about (re)publishing final version locally

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3271]
```
[warn] Attempting to overwrite /home/cunei/iii/097/com.typesafe.dbuild/build_2.12//0.9.7/jars/build_2.12.jar
[warn] This usage is deprecated and will be removed in sbt 1.0.
```

IMO publishLocal with final looking version number is already bad.
Maybe we prompt the user:

```
Hey you're about to mess up your Ivy cache. Plz don't blame us when things break: [y/N]
```

**Comment by jvican** [comment]
I totally agree. However, what I propose is to fail if users try to do this. If they really want to do it, we can add a `force` setting inside publish local and they need to enable it before proceeding.

**Comment by cunei** [comment]
This was not a publishLocal, incidentally: it was a regular `publish` with `publishTo` set to `Some(Resolver.file("rover-pub", new java.io.File("/home/cunei/iii/097"))(Resolver.ivyStylePatterns))`
