### ISSUE TITLE
Scala JSON AST final

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3273]
We need Scala JSON AST 1.0 final.

If it doesn't happen by June 26th (2wk prior to RC-1), we should consider other options:
- Keep using whatever it's there
- Fork under some name so we can maintain
- Adopt other AST

https://github.com/mdedetrich/scala-json-ast/issues/13

**Comment by dwijnand** [comment]
I think we should either fork it or switch to a more battle-tested AST.

**Comment by jvican** [comment]
There's no rush. Sigh. I remind you there are still 13 days until RC and there are no binary incompatible changes you have to catch up with.
  
Release happens very soon. The Committee has accepted Scala JSON AST into the Scala Platform, successfully ending the incubation period.

**Comment by dwijnand** [comment]
I'm tired of "soon" and "very soon". When 1.0.0 going to be released?

This was requested in March and reminding 2 weeks ago. A deadline was set and ignored. So I'm indicating my preference for an alternative solution.

**Comment by fommil** [comment]
:+1: for using whatever sbt is currently using. This shouldn't block 1.0 and there are serious flaws with the proposal.

**Comment by eed3si9n** [comment]
As discussed in https://github.com/mdedetrich/scalajson/issues/13, we should shade the latest milestone.

**Comment by eed3si9n** [comment]
For now sjson-new shades ScalaJSON milestone.
I am reassigning this to RC-2.

**Comment by dwijnand** [comment]
We're using the shaded version. When ScalaJSON goes final we'll switch.
