### ISSUE TITLE
Please provide sbt version information

### ISSUE THREAD

**Issue by KenMcDonald** [sbt/sbt#328]
Hi Mark,

I've been bit a couple of times now because of using a version of sbt different from what I think I'm using. If not too much trouble, could you put the version number in a couple of places? Namely:
- name the sbt jar files sbt-launch-nn.nn.n.jar, instead of sbt-launch.jar? (This also helps those of us how have different versions installed on our system for older and newer projects).
- In the output of sbt when it starts up?

Hopefully these are small easy changes.

Thanks,
Ken

**Comment by jsuereth** [comment]
Note:  In any build, type sbt-version and you'll see the version you're using.  The launch jar can support different versions of SBT.   If you're specifically interested in which version of the _launch jar_, that deserves a feature request.

**Comment by KenMcDonald** [comment]
Nope, thanks for clarifying why launch.jar isn't versioned.

Ken

**Comment by harrah** [comment]
Please use the mailing list for questions and discussions.
