### ISSUE TITLE
sbt shell doesn't print until [return] is pressed on sbt 1.0.0-M6 on Windows 10

### ISSUE THREAD

**Issue by Duhemm** [sbt/sbt#3282]
## steps
- Install Windows 10, build 15063.0
- Install Oracle JDK 8u131
- Install sbt 0.13.15 from the msi file linked on scala-sbt.org
- Create an empty sbt project:

`project/build.properties`:
```
sbt.version=1.0.0-M6
```
`build.sbt`:
```
```
- launch `sbt` in `Command Prompt`
- type something in the shell
## problem
- Nothing appears until `[return]` is pressed.

## expectation
- the shell shows what I'm typing.

## notes
- it appears the arrow keys are not working either.

sbt version: 1.0.0-M6

**Comment by ndimas** [comment]
Can this be reproduced with Quick Edit mode turned off too?

Had these problems too with Windows 10.

https://stackoverflow.com/questions/30418886/how-and-why-does-quickedit-mode-in-command-prompt-freeze-applications

**Comment by romanowski** [comment]
I've got same problems on Windows 7 and sbt from [1.0.0-M6](https://github.com/sbt/sbt/releases/tag/v1.0.0-M6) release ( from extracted zip).

**Comment by eed3si9n** [comment]
Here's a repro snippet to test on Windows (writing this from a vm):

```scala
{
  import sbt.internal.util._
  import sbt.internal.util.complete.DefaultParsers._
  val p = success[Int](0)
  val r = new FullReader(None, p, false, true)
  r.readLine("> ", None)
}
```

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/3358. This will in next RC.
