### ISSUE TITLE
Is there any docs about config sbt globally? 

### ISSUE THREAD

**Issue by acearth** [sbt/sbt#3292]
Not found valid settings about configure sbt globally, such as how to config "~/.sbt/" dir.

Version 0.13

**Comment by dwijnand** [comment]
Hey @acearth, here's the page in the docs we have for global settings: http://www.scala-sbt.org/0.13/docs/Global-Settings.html

Also, please have a look at this section about where to get help: https://github.com/sbt/sbt/blob/1.0.x/CONTRIBUTING.md#where-to-get-help-andor-file-a-bug-report

Finally, if you notice any issues in the documentation, we track and make changes to it at https://github.com/sbt/website.
