### ISSUE TITLE
Re-expose or offer alternative public API for things hidden in 1.0

### ISSUE THREAD

**Issue by jastice** [sbt/sbt#3296]
[sbt-structure](https://github.com/jetbrains/sbt-structure) uses parts of the sbt API that have been hidden in the sbt 1.0 line. This forced me to work around it by [this shim](https://github.com/JetBrains/sbt-structure/blob/master/extractor/src/main/scala-sbt-1.0/sbt/jetbrains/apiAdapter.scala) that I import into otherwise compatible code to provide the definitions previously available under the `sbt._` import.
It would be helpful to have these things, or an appropriate replacement available under a public API.

Pasted for reference:
```
object apiAdapter {
  val Load = sbt.internal.Load
  type Load = sbt.internal.Load.type

  val SessionSettings = sbt.internal.SessionSettings
  type SessionSettings = sbt.internal.SessionSettings

  type GetClassifiersModule = sbt.internal.librarymanagement.GetClassifiersModule
  type LoadedBuildUnit = sbt.internal.LoadedBuildUnit
  type BuildStructure = sbt.internal.BuildStructure
  type BuildDependencies = sbt.internal.BuildDependencies
  type ScalaInstance = sbt.internal.inc.ScalaInstance
  type MavenRepository = sbt.librarymanagement.MavenRepository
}
```

**Comment by eed3si9n** [comment]
### GetClassifiersModule

This will be public in https://github.com/sbt/librarymanagement/pull/124 -
 https://github.com/sbt/librarymanagement/blob/74f6a492de82873d925dd4581efe229d2b1f9d30/core/src/main/contraband-scala/sbt/librarymanagement/GetClassifiersConfiguration.scala.
We probably should add them to Import.scala so there's an alias under sbt package.

### MavenRepository

We can add an alias for this.

### ScalaInstance

I think the current stance is that `xsbti.compile.ScalaInstance` is the public API and `sbt.internal.inc.ScalaInstance` is implementation detail.
We probably should add factory method in https://github.com/sbt/zinc/blob/1.0/zinc/src/main/java/xsbti/compile/ZincCompilerUtil.java /cc @jvican 

### Load

`Load` I think is squarely in the internal. What do you need from it? I see

```scala
Load.transformSettings(Load.projectScope(projectRef), projectRef.build, rootProject, projectSettings)
```

These are simple functions that can be copy-pasted in to your plugin.

### SessionSettings, LoadedBuildUnit, BuildStructure, BuildDependencies

I think these are internal wiring of sbt build, but we might want to change to Contraband so we can keep bincompat if we have to evolve them.
Generally we should aim to provide some other facility to query things about the build both using Scala and using server, but in 1.x.

**Comment by jastice** [comment]
Thanks @eed3si9n 

I updated sbt-structure based on this and changes in RC2, so now only the last point is open (SessionSettings, LoadedBuildUnit, BuildStructure, BuildDependencies)

**Comment by dwijnand** [comment]
@jastice I'm going to try to update sbt-project-graph this week, so I'll be in the same situation, so I might be PRing a solution.

**Comment by leonardehrenfried** [comment]
What about ` Cross.crossVersions`?

**Comment by eed3si9n** [comment]
I am hoping we're good here.

**Comment by dwijnand** [comment]
Probably not.  Lots of plugins rely on the internal APIs of structure/loading.

There's also the issue that things are defined in "internal" but then expose as non-external in the sbt package object, which is the worst of both worlds because for sbt maintainers it looks like you can break it, but for users it looks like public API.

And I think there's also stuff not exposed but should be to use features, like the parser/complete API.
