### ISSUE TITLE
Sbt ignores last line of the .sbtopts file

### ISSUE THREAD

**Issue by dragos** [sbt/sbt#3301]
(This seems to be a problem only on Linux)

## steps
- `sbt -help` suggests to use `.sbtopts` for passing additional arguments
- add some sbt options in `.sbtopts`, like `-J-XmxBlahBlah`, something that should make the JVM fail. **Don't** add a new line at the end, so the EOF is on the line you just added

## problem

- run sbt. The setting is ignored

## expectation

- All settings in .sbtopts are picked up

## notes

I used the tarball to install in my $HOME and symlinked to `bin/sbt` inside the untarred distro.

sbt version: 0.13.15

**Comment by dwijnand** [comment]
JFYI the script(s) are in https://github.com/sbt/sbt-launcher-package, so we track these issues there. But it's common to receive them here. I mention it in part in an attempt to see if you'd be willing to fix it yourself. 😄

**Comment by dragos** [comment]
Here it is: https://github.com/sbt/sbt-launcher-package/pull/169
