### ISSUE TITLE
classloader errors between test runs

### ISSUE THREAD

**Issue by simao** [sbt/sbt#3306]
I am observing some strange classpath/classloader issues when running `sbt test`.

I keep getting errors equivalent to the following: 

`[info]   java.lang.ClassCastException: net.i2p.crypto.eddsa.EdDSAPublicKey cannot be cast to net.i2p.crypto.eddsa.EdDSAPublicKey`

The first test execution always works correctly, but subsequent executions fail with errors of this nature.

Which suggest sbt is somehow messing with the classloader between test executions, which makes `asInstanceOf` and equivalent statements to not work properly.

## steps

I created a [small project](https://github.com/simao/sbt-classloader-issue
) that reproduces this issue. You can follow the following steps to reproduce the problem:

```
git clone https://github.com/simao/sbt-classloader-issue
cd sbt-classloader-issue
sbt
test
test
```

The output of these commands is available at: https://github.com/simao/sbt-classloader-issue/blob/master/sbt_output.txt

## problem

The first execution is green, while subsequent executions are red. 

## expectation
I expect all test executions to have the same green result.

## notes

sbt version: 0.13.5

**Comment by dk14** [comment]
This is a quick-fix (without forking JVM):

```
class SbtIssueTest extends FunSuite with Matchers {
  val provider = new BouncyCastleProvider()
  Security.addProvider(provider)

  test("generates a key pair key") {
    SbtIssue.generateKeyPair() shouldBe a[KeyPair]
    Security.removeProvider(provider.getName())
  }
}

```
I think it's related to this "problem": https://stackoverflow.com/questions/9420190/do-security-providers-cause-classloader-leaks-in-java

**Comment by Facsimiler** [comment]
This is not an _SBT_ issue as such. Since information is being stored in the _JVM_ run-time (in this case. multiple security providers, causing exceptions when re-initializing a single `KeyPairGenerator` instance), this issue can be avoided by forking the tests so that they run in separate _JVM_ instances. Alternatively, the tests should be written so that they clean up after themselves, as pointed out above.

**Comment by dwijnand** [comment]
Indeed. Here's a few resources about forking tests:

+ http://www.scala-sbt.org/0.13/docs/Forking.html
+ http://www.scala-sbt.org/0.13/docs/Testing.html#Forking+tests
+ https://stackoverflow.com/questions/15798341/how-to-fork-the-jvm-for-each-test-in-sbt

**Comment by simao** [comment]
Thank you all for your help fixing the issue. Forking the jvm or using `testOptions in Test += Tests.Cleanup(() => java.security.Security.removeProvider("BC"))` works.
