### ISSUE TITLE
SBT echo $<3 each time <delete> is pressed when run under iTerm2 on macOS

### ISSUE THREAD

**Issue by eswenson1** [sbt/sbt#3307]
(See the guidelines for contributing, linked above)

## steps

1. start iTerm2 on macOs
2. don't change bindings for <delete> key, or if you already have, bind to either send ^? or ^H (backspace).
3. start sbt
4. type at sbt command prompt "foo"
5. type <delete> key
6. Note that sbt erases the last "o" of "foo" and replaces with "$<3>".

## problem

When running sbt under iTerm2 shell, sbt incorrectly handles <delete> key. This occurs with default iTerm2 key bindings, or with them set to send ^? or ^H when <delete> is pressed. There appears to be no key binding in iTerm2 that will provide the proper behavior.

Needless to say, it is difficult to read/parse what you've typed in the face of correcting with the <delete> key mistakes you've made.

Typing ^H (backspace) has the same effect.

Using macOS Terminal does not exhibit the same problem.

## expectation

When <delete> or <rubout> or <control-H> is typed (in iTerm2) to SBT shell, I expect the last character to be erased and the cursor to be moved to the appropriate posistion.

## notes

I originally filed a bug with iTerm2, since Terminal doesn't exhibit this problem.  After discussions on the thread, and the iTerm2 maintainer's statement that iTerm2 is just sending a ^? or ^H and a debug log verifying that, the maintainer suggested I enter a ticket here.  The iTerm2 issue is here:  https://gitlab.com/gnachman/iterm2/issues/5848

sbt version: 

> abot$<3$<3>ut
[info] This is sbt 0.13.15
[info] The current project is {file:/Users/eswenson/Projects/Modulus/ws/modulus-shared-libraries/}root 1.0.dev
[info] The current project is built against Scala 2.11.11
[info] Available Plugins: sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.CorePlugin, sbt.plugins.JUnitXmlReportPlugin, sbt.plugins.Giter8TemplatePlugin, com.typesafe.sbt.SbtNativePackager, com.typesafe.sbt.packager.archetypes.AkkaAppPackaging, com.typesafe.sbt.packager.archetypes.AshScriptPlugin, com.typesafe.sbt.packager.archetypes.JavaAppPackaging, com.typesafe.sbt.packager.archetypes.JavaServerAppPackaging, com.typesafe.sbt.packager.archetypes.jar.ClasspathJarPlugin, com.typesafe.sbt.packager.archetypes.jar.LauncherJarPlugin, com.typesafe.sbt.packager.debian.DebianDeployPlugin, com.typesafe.sbt.packager.debian.DebianPlugin, com.typesafe.sbt.packager.debian.JDebPackaging, com.typesafe.sbt.packager.docker.DockerPlugin, com.typesafe.sbt.packager.docker.DockerSpotifyClientPlugin, com.typesafe.sbt.packager.jdkpackager.JDKPackagerDeployPlugin, com.typesafe.sbt.packager.jdkpackager.JDKPackagerPlugin, com.typesafe.sbt.packager.linux.LinuxPlugin, com.typesafe.sbt.packager.rpm.RpmDeployPlugin, com.typesafe.sbt.packager.rpm.RpmPlugin, com.typesafe.sbt.packager.universal.UniversalDeployPlugin, com.typesafe.sbt.packager.universal.UniversalPlugin, com.typesafe.sbt.packager.windows.WindowsDeployPlugin, com.typesafe.sbt.packager.windows.WindowsPlugin, org.scalajs.sbtplugin.ScalaJSJUnitPlugin, org.scalajs.sbtplugin.ScalaJSPlugin, buildtools.BuildToolsPlugin, com.typesafe.sbt.web.SbtWeb, pl.project13.scala.sbt.SbtAsciidoctor, sbtassembly.AssemblyPlugin
[info] sbt, sbt plugins, and build definitions are using Scala 2.10.6

**Comment by vmarquez** [comment]
I have this problem too when running SBT inside a terminal window in Vim on OS X.

**Comment by eswenson1** [comment]
@vmarquez That's interesting. I had originally reported this ticket to the iTerm2 dev team because that is the only place I saw this happening, but the iTerm2 developer said that iTerm2 was sending the correct characters. So glad to see that other shell environments on OS/X are causing the same issue.

**Comment by eed3si9n** [comment]
I am assuming this is some bad interaction between JLine and your terminal environment. Do you set `TERM`? Mine is set to `xterm-256color`. Not sure if that would help.

**Comment by eswenson1** [comment]
Wow!  So long and noone has been able to come up with a reason. Yes!  I had TERM set to vt100.  Setting it to xterm-256color makes the problem go away.  Of course, I'm on a Mac and not running xterm, so I don't know what xterm-256color does on a Mac.  But at least I can delete now in SBT without those ugly $<3> characters.  Thanks much.

**Comment by eed3si9n** [comment]
I am macOS as well, using iTerm2. I am closing this as resolved.
