### ISSUE TITLE
Make `~` fail if command is not found

### ISSUE THREAD

**Issue by jvican** [sbt/sbt#3309]
This is a ticket for the Scala Center spree at Scala Wave (Gdansk, Poland).
  
The goal of this ticket is to fix this "behaviour" that should fail when the task is not found.

## steps
Run `~myNonExistingTask`.

## problem
The `~` command waits for user input even if `myNonExistingTask` does not exist.

## expectation
  
It should fail straight away without entering in the watch cycle. That means no user input is expected, normal error is reported to the user.

## notes

sbt version: 1.0.0 (master branch)

**Comment by jvican** [comment]
@eed3si9n Can you label this as `spree`?

**Comment by perbellinioa** [comment]
I've done this ticket during the Dublin Scala Spree.

**Comment by eed3si9n** [comment]
See my comments in https://github.com/sbt/sbt/pull/3532#discussion_r140157900 onwards. The parser is intentionally kept relaxed so it can compose with other commands.

**Comment by dwijnand** [comment]
Fixed in https://github.com/sbt/sbt/pull/4335/commits/28aa1de32a1108e8b42cf7606c962df6e5dc6f52 looks like?

**Comment by eatkins** [comment]
Yes. #3884 is related but not yet fixed.
