### ISSUE TITLE
Better prompt out of the box

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3313]
## steps

Use sbt with a multi project build.

## problem

The prompt just says `>`.

## expectation

The prompt defaults to something that tells what your current project is.

**Comment by dwijnand** [comment]
We should poll the peoples. Because I like the minimal/no boilerplate default we have currently (and hate sbt-play messing with it).

**Comment by eed3si9n** [comment]
This is analogous to sbt not shipping bash script `sbt` so ppl can customize it, like solder-it-yourself mechanical keyboard kit. Advanced users can change it back to `>`.

**Comment by dwijnand** [comment]
The equivalent to "solder-it-yourself mechanical keyboard kit" is probably "custom build sbt with your own prompt". We provide convenient settings to change the prompt. This is just about the default value.

The current implementation (0.13.x/1.0.x) is `> `. You mentioned current project. What about current directory? What about current date/time? Current user? Current branch? Current git status? Current battery percent? Current song playing? Current AAPL price?

You and I can change it to whatever. But to change the default we should poll the users, see what wins, and switch to that.

**Comment by eed3si9n** [comment]
https://twitter.com/eed3si9n/status/884914670351659009

**Comment by LogicalTime** [comment]
Project name would be really nice for first time users. It makes it easier and more comfortable to make a multi project build too.

**Comment by SethTisue** [comment]
> Current user? Current branch? Current git status? Current battery percent? Current song playing? Current AAPL price?

lol

**Comment by SethTisue** [comment]
fwiw, I almost never use `project` to change projects, typing `foo/` before things seems to me like a cheap price to pay for the gold of statelessness. ymmv

**Comment by dwijnand** [comment]
One nice side-effect of using the current project as the default prompt is there will probably be less root projects named "root".

**Comment by kpmeen** [comment]
I believe it makes life easier for beginners if the current project name is displayed by default. Anything that makes the shell a friendlier experience for beginners is a good thing IMO.
I've seen quite a few really confused devs losing track of where they are inside the shell. Until I've given them a customized prompt with a bit more contextual info.

Personally I just customize the prompt. But that's not something beginners will do.
