### ISSUE TITLE
Flag to prevent interactive mode (running from Windows)

### ISSUE THREAD

**Issue by ldj** [sbt/sbt#332]
As has been filed before, sbt should have a flag that prevents it from entering interactive mode. I know the common suggestion is to use < /dev/null, but I'm running on a Windows system. I've tried using NUL with "java -Xmx512M -jar sbt-launch.jar < NUL" (which is supposed to be the Windows equivalent of /dev/null) but cannot get this to work. I had no success invoking from either the java task in ANT or directly from the command line.

Additionally, I would like to invoke sbt from ant using build files that work on both windows and linux without having to check my environment as part of the build script. So even if there is a way to get NUL working, I still believe there should be a way to do it in a platform independent way.

**Comment by harrah** [comment]
Please do not open a new bug when a bug already exists.  Even better, use the mailing list.
