### ISSUE TITLE
Generated sources .class files removed during package or run

### ISSUE THREAD

**Issue by michaelpnash** [sbt/sbt#333]
Hi: 

I've struck what might be a bug, or perhaps more likely I'm just doing something wrong :)

When I'm using a plugin that generates sources (specifically, the scalate-precompile template, but I believe it's generic), I see the compile step build the .class files from my src_managed files just fine. 

When I go to do a "package" (or an assembly, or a run), however, the .class files, which were present in the "classes" dir inside target/$scala-version, suddenly go away.

This appears to have happened sometime between 11.0 and 11.2, as best I can tell.

Is this expected behaviour? Something perhaps I can turn off?

Thanks!

Mike

**Comment by harrah** [comment]
Please use the mailing list for questions. https://github.com/harrah/xsbt/wiki/FAQ
