### ISSUE TITLE
++ reverts ^^

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#3330]
## steps

1. Change the target sbt version with `^^`: `^^1.0.0-RC2`
2. Change the target Scala version with `++`: `++2.12.2`

## problem

The target sbt version has been reverts:

```
> show pluginCrossBuild::sbtVersion
[info] 0.13.16-M1

> ^^1.0.0-RC2
[info] Setting `sbtVersion in pluginCrossBuild` to 1.0.0-RC2
[info] Set current project to t (in build file:/s/t-2017-07-17.1722/)

> show pluginCrossBuild::sbtVersion
[info] 1.0.0-RC2

> ++2.12.2
[info] Setting version to 2.12.2
[info] Reapplying settings...
[info] Set current project to t (in build file:/s/t-2017-07-17.1722/)

> show pluginCrossBuild::sbtVersion
[info] 0.13.16-M1
```

## expectation

I expect my session-set target sbt version to not be affected by `++`.

## notes

sbt version: 0.13.16-M1

Workaround: Call `++` first, then `^^`. 😞

**Comment by eed3si9n** [comment]
With https://github.com/sbt/sbt/pull/3356 ++ is no longer needed, so I am closing this.

**Comment by sjrd** [comment]
Don't be so sure. You can have a multi-project build with an sbt plugin depending on other non-sbt-plugin projects. In such a case you still need to `++` for the other projects to have the right Scala version, don't you?

It's a pretty common setup too. A lot of sbt plugins try to abstract away their core logic from sbt integration, so that the core logic can be reused in other build tools or as CLI applications.

**Comment by eed3si9n** [comment]
ok. I'll keep it open to validate with multi-sbt-plugin builds.

**Comment by eed3si9n** [comment]
Given the workarounds (e.g. not specifying `scalaVersion` for the subproject, or call `++` before `^^`), I am going to remove this out of 1.0.0-RC3 milestone.

**Comment by dwijnand** [comment]
Situation's pretty complicate now:

```
> show pluginCrossBuild::sbtVersion
[info] 0.13.16

> ^^1.0.0-RC3
[info] Setting `sbtVersion in pluginCrossBuild` to 1.0.0-RC3
[info] Set current project to sbt-whitesource (in build file:/d/sbt-whitesource/)

> show pluginCrossBuild::sbtVersion
[info] 1.0.0-RC3

> show scalaVersion
[info] 2.12.2

> ++2.12.3
[info] Setting version to 2.12.3
[info] Reapplying settings...
[info] Set current project to sbt-whitesource (in build file:/d/sbt-whitesource/)

> show pluginCrossBuild::sbtVersion
[info] 0.13.16
```

... I'm going back to using `set`.
