### ISSUE TITLE
Classloading problem in scripted plugin

### ISSUE THREAD

**Issue by larsrh** [sbt/sbt#3333]
## steps

1. Clone [sbt-slf4j](https://github.com/larsrh/sbt-slf4j), branch `topic/sbt-1`
2. Run `sbt scripted`

## problem

`[error] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".`

As far as I can tell, there is only one reason why this would fail, which is when the file `src/main/resources/slf4j-impl-helper` doesn't end up in the classpath. It works properly when running `sbt console` instead of `sbt scripted`.

## expectation

Works as before in 0.13.x

## notes

sbt version: 1.0.0-M6

**Comment by xuwei-k** [comment]
IIRC, sbt depends on slf4j since version 1.0.

**Comment by larsrh** [comment]
Interesting. Why would it work in `console`, then? But maybe this plugin is obsolete, then.

**Comment by xuwei-k** [comment]
- [0.13.15](https://gist.github.com/xuwei-k/1d44ad6ae1ac42d5e547eb42a4022993)
- [1.0.0-M6](https://gist.github.com/xuwei-k/907f3a5340155b42730cc4825c8a330d)
- [1.0.0-RC2](https://gist.github.com/xuwei-k/45cf610e56bec3a0ca46cf3a7d6444b2)

**Comment by larsrh** [comment]
OK, but is there a `org.slf4j.impl.StaticLoggerBinder` somewhere?

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/3382

**Comment by larsrh** [comment]
@eed3si9n Am I right in assuming that my plugin (`sbt-slf4j`) can be deprecated now?

**Comment by eed3si9n** [comment]
Yes. Next RC of sbt 1.0 will include a SLF4J binding.

**Comment by larsrh** [comment]
Perfect, thanks!
