### ISSUE TITLE
Test all commits in CI

### ISSUE THREAD

**Issue by Duhemm** [sbt/sbt#3334]
Currently, we merge branches as they are in the PR, without caring much about the individual commits. Note that this has not always been the case, I remember being asked to clean up individual commits in my first contributions to sbt.

In my experience, this not-so-nice history had made sbt difficult to debug using `git bisect` for several reasons:

 - Some commits do not compile
 - Some commits depend on `-SNAPSHOT`s
 - Some commits do not pass all the tests

One solution to solve this issue would be to use the `squash and merge` option from GitHub's UI when merging PRs that do not have a nice history. Unfortunately, [Github doesn't create merge commits when using this option](https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits). Given that we want to keep the merge commits, we should probably go for having the CI test all commits.

Travis CI doesn't support testing all commits in a PR, so we need to either push each commit individually or move to another CI. A more complicated build script for Travis could also do the trick, but we would most likely hit the 60-minutes limit.

**Comment by eed3si9n** [comment]
I think clean Git history is a worthy goal, but I am guessing this won't happen for a while, so I am closing this. PR or proposal around this would be welcome.
