### ISSUE TITLE
ansiCodesSupported regression in 1.0.0-RC2

### ISSUE THREAD

**Issue by liff** [sbt/sbt#3336]
(See the guidelines for contributing, linked above)

## steps

Create a test project (run in shell):

```bash
mkdir -p rainbows/project
cd rainbows
echo 'sbt.version=1.0.0-RC2' > project/build.properties
cat > build.sbt <<EOF
val rainbows = taskKey[Boolean]("rainbows")
rainbows := streams.value.log.ansiCodesSupported
EOF
sbt 'show rainbows'
```

## problem

Value of `streams.log.ansiCodesSupported` is `false` on the last line of:

```
[info] Loading settings from build.sbt ...

[info] Set current project to rainbows (in build file:/private/tmp/rainbows/)

[info] false
```

## expectation

It should be `true` like in 0.13.

## notes

sbt version: 1.0.0-RC2.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/util/pull/101
