### ISSUE TITLE
Code Example in Docs Raises Error

### ISSUE THREAD

**Issue by mslinn** [sbt/sbt#334]
The following code example in [More Kinds of Setting](https://github.com/harrah/xsbt/wiki/Getting-Started-More-About-Settings) errors when I try it with SBT 0.11.2:

```
> name <<= (name, organization, version) { (n, o, v) => "project " + n + " from " + o + " version " + v }
[error] Expected end of input.
[error] name <<= (name, organization, version) { (n, o, v) => "project " + n + " from " + o + " version " + v }
[error]     ^
```

The code example lives in the section _Complex Initialize[T]: depending on multiple keys with <<=_

**Comment by mslinn** [comment]
I just realized that expressions setting key/value pairs do not work interactively with SBT, so ~= and <<= cannot be typed into an SBT prompt. Perhaps the docs could be enhanced to say that the code could be added to build.sbt, and the value displayed like this:

```
sbt 'show name'
```

... and that :=, <<= and ~= expressions may not be invoked interactively in the sbt shell.

**Comment by mslinn** [comment]
... actually, that is not quite true. All of those expressions can be entered in the sbt console project, which can be initiated like this:

```
sbt console-project
```

**Comment by harrah** [comment]
Please use the mailing list for questions. https://github.com/harrah/xsbt/wiki/FAQ
