### ISSUE TITLE
Bump to sbt 1.0.0-RC3

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3340]
## steps

Bump to sbt 1.0.0-RC2
Drink our own Champaign

**Comment by eed3si9n** [comment]
This is blocked by Zinc + sbt-protoc + sjson-new LL format, so I am removing this from the milestone.

**Comment by dwijnand** [comment]
Re-purposed to RC3.

**Comment by dwijnand** [comment]
#3396
