### ISSUE TITLE
Managed dependencies not updated

### ISSUE THREAD

**Issue by earldouglas** [sbt/sbt#335]
It would be useful if there were a way to manually force dependencies to be re-retrieved.  Some examples of this are:
- `-SNAPSHOT`
- `uri(git://...)`

Others might fall into this bucket too, though I haven't tried them myself:
- Ivy dependencies with a `+` in their revision
- `file(...)`
- Other types of `uri(...)`

Here are some threads about where the community has run into this:
- http://stackoverflow.com/questions/8864317
- http://groups.google.com/group/simple-build-tool/browse_thread/thread/7ca098521557062c
- http://groups.google.com/group/simple-build-tool/browse_thread/thread/5b59604bb08114b3

**Comment by alexanderdean** [comment]
+1 - this would be great

**Comment by Rogach** [comment]
+1 - it really painful to remove directories in .sbt/staging every time something changes.

**Comment by tomasherman** [comment]
+1 from me aswell

**Comment by gthiruva** [comment]
+1 Guess I'll climb on the me too boat as well!

**Comment by aryairani** [comment]
+1 boom

**Comment by Rogach** [comment]
About "-SNAPSHOT" - somebody told me, that running "clean" and then "update" solves the issue.

**Comment by earldouglas** [comment]
Rogach, thanks for the workaround.  This is how I have to do it currently, but I'd prefer a less drastic way, since outside of this issue a full `clean` isn't usually necessary.  The optimal solution would be for sbt to check for snapshot dependencies whenever `update` is run and `offline` is false.

**Comment by aryairani** [comment]
Agreed.

**Comment by jlarmstrong** [comment]
+1

**Comment by xerial** [comment]
Thanks for the update. When this fix will be available?

**Comment by harrah** [comment]
It will be in 0.12.0.

**Comment by justwrote** [comment]
The current fix (used sbt snapshot from today) always initializes a full update. We have a project with lots of dependencies (update takes about 150 seconds) and an "update-quick" which only refreshes SNAPSHOTS would be really nice.

**Comment by greenrd** [comment]
That it takes 150 seconds for a full update should probably be another bug, no?

**Comment by earldouglas** [comment]
It seems like it should be unnecessary to update non-snapshot dependencies.  If a given dependency is in "release" status, it would not be expected to ever change, so there would be no point in re-resolving it.  On the other hand, if a dependency is in "integration" status, there is a high probability that it will change, and it should be updated frequently.

**Comment by aryairani** [comment]
Agreed -- snapshots and source dependencies, I suppose!

On Fri, Apr 6, 2012 at 11:37 AM, James Earl Douglas <
reply@reply.github.com

**Comment by keynan** [comment]
+1

**Comment by harrah** [comment]
The above mentioned fix was included in 0.12.0.  Running 'update' explicitly will force an update to run, which should retrieve new versions of -SNAPSHOTs and other dynamic revisions.  If this does not fix issues for you, please make a reproducible test case and file a separate bug.

**Comment by williscool** [comment]
I'm still having this issue after running

`update`

and then `clean`

output of `about`

```
> about
[info] This is sbt 0.12.1
[info] The current project is {file:<project_directory>}default-92dac0
[info] The current project is built against Scala 2.10.0
[info] Available Plugins: twirl.sbt.TwirlPlugin, spray.revolver.RevolverPlugin, sbtassembly.Plugin, com.gu.SbtJasminePlugin
[info] sbt, sbt plugins, and build definitions are using Scala 2.9.2
```

**Update:** clearing `.sbt/staging` worked and I agree with @Rogach it is rather painful

**Comment by ptrbrtz** [comment]
+1
This is not working for managed .git dependencies, having to delete .sbt/staging manually

**Comment by ephe-meral** [comment]
+1
Agreed, update for GIT deps would be cool.

Another workaround is to identify which project needs updating and then do the "git pull ..." in the appropriate staging subdir manually.

**Comment by axel22** [comment]
Yes, please -- update git dependencies too.

**Comment by 404-** [comment]
+1
i'm using 0.13.0 - definitely doesn't work for Git projects

**Comment by notmandatory** [comment]
I'm using play 2.2.1 with sbt 0.13.0 with a SNAPSHOT dependency from my local .m2 updating to my .ivy2 cache.  I can confirm that my SNAPSHOT dependency does not get updated in the .ivy2 cache, even after a clean and update.  I tried adding changing() to my SNAPSHOT dependency config in build.sbt but that did not help.  Only if I manually delete my SNAPSHOT package from .ivy2/cache does it then get updated.
