### ISSUE TITLE
show update doesn't work on sbt 1.0.0-RC2 or RC3

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3357]
## steps

```
> show update
```

## problem

It displays the `toString` of case class?

```
[info] OrganizationArtifactReport(org.scala-lang, scala-compiler, Vector(		org.scala-lang:scala-compiler:2.12.2: (Artifact(scala-compiler, jar, jar, None, Vector(master), None, Map(), None),/Users/eed3si9n/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.12.2.jar)
```

## expectation

0.13 has better String formatting.

**Comment by jvican** [comment]
I think this happens for lots of other cases. It looks like it has to be fixed for any key returning a Contraband-generated Java or Scala class. And even for all of them: users could be returning them in plugins.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/librarymanagement/issues/146

**Comment by eed3si9n** [comment]
@dwijnand So 1.0.0-RC3 is an improvement, but it's not the same as 0.13:

[info] 	org.scala-lang:scala-library
[info] 		- 2.12.2
[info] 			status: release
[info] 			publicationDate: java.util.GregorianCalendar[time=1492071551000,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id="America/New_York",offset=-18000000,dstSavings=3600000,useDaylight=true,transitions=235,lastRule=java.util.SimpleTimeZone[id=America/New_York,offset=-18000000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=3,startMonth=2,startDay=8,startDayOfWeek=1,startTime=7200000,startTimeMode=0,endMode=3,endMonth=10,endDay=1,endDayOfWeek=1,endTime=7200000,endTimeMode=0]],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=2017,MONTH=3,WEEK_OF_YEAR=15,WEEK_OF_MONTH=3,DAY_OF_MONTH=13,DAY_OF_YEAR=103,DAY_OF_WEEK=5,DAY_OF_WEEK_IN_MONTH=2,AM_PM=0,HOUR=4,HOUR_OF_DAY=4,MINUTE=19,SECOND=11,MILLISECOND=0,ZONE_OFFSET=-18000000,DST_OFFSET=3600000]
[info] 			resolver: sbt-chain
[info] 			artifactResolver: sbt-chain
[info] 			evicted: false
[info] 			homepage: http://www.scala-lang.org/
[info] 			textraAttributes: Map(info.apiURL -> http://www.scala-lang.org/api/2.12.2/)
[info] 			isDefault: false
[info] 			configurations: default, compile, runtime, default(compile), master
[info] 			licenses: (BSD 3-Clause,Some(http://www.scala-lang.org/license.html))
[info] 			callers: com.example:helloworld_2.12:0.1-SNAPSHOT

**Comment by dwijnand** [comment]
Line to change: https://github.com/sbt/librarymanagement/blob/v1.0.0-RC3/core/src/main/scala/sbt/librarymanagement/UpdateReportExtra.scala#L64
