### ISSUE TITLE
Avoid interactive console in batch mode

### ISSUE THREAD

**Issue by zxydi1992** [sbt/sbt#3374]
(See the guidelines for contributing, linked above)

## problem
When a "sbt run ..." in batch mode is done, the sbt does not exit automatically and hangs there.

## expectation
Is there any options to close sbt after the job is finished?

## notes

sbt version: *insert sbt version*

**Comment by dwijnand** [comment]
What version of sbt are you using? Can you provide a minimal reproduction?

**Comment by qdrk** [comment]
hmm same issue here, I have `sbt.version=0.13.15` in my build.properties.

**Comment by eed3si9n** [comment]
There might be a legitimate issue here (see for example https://github.com/sbt/sbt/issues/1697), but likely workaround is to use forking, so I am closing this unless there's more details we can act on.

```scala
Compile / run / fork := true
```
