### ISSUE TITLE
1.0.0-RC2 cross build cannot find fileToRichFile method

### ISSUE THREAD

**Issue by muuki88** [sbt/sbt#3378]
## steps

Create a scripted test with an inlined task like this

```scala
TaskKey[Unit]("check") := {
  val application = (target in Universal).value / "tmp" / "conf" / "application.ini"
  val content = IO.read(application)
  val options = (javaOptions in Linux).value
  options.foreach { opt =>
    assert(content.contains(opt), "Option [" + opt + "] is missing")
  }
}
```

Cross build with

```
; ++2.12.2 ; ^^1.0.0-RC2 ; scripted universal/application-ini-from-javaoptions
```

Example is taken from this pull request: 
https://github.com/sbt/sbt-native-packager/pull/1000

## problem

An exception is thrown

```
[info] [error] java.lang.NoSuchMethodError: sbt.package$.fileToRichFile(Ljava/io/File;)Lsbt/io/RichFile;
[info] [error] 	at $f99bf77d124917c77ead$.$anonfun$$sbtdef$1(/tmp/sbt_4bd421e4/application-ini-from-javaoptions/build.sbt:12)
[info] [error] 	at $f99bf77d124917c77ead$.$anonfun$$sbtdef$1$adapted(/tmp/sbt_4bd421e4/application-ini-from-javaoptions/build.sbt:11)
[info] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[info] [error] (*:check) java.lang.NoSuchMethodError: sbt.package$.fileToRichFile(Ljava/io/File;)Lsbt/io/RichFile;
[info] [error] Total time: 0 s, completed 27.07.2017 20:16:19
```

## expectation

The implicit method is found.

## notes

sbt version build: *0.13.16*
sbt version for scripted test: *1.0.0-RC2*

If I import the method explicitly the implicit conversion is not applied.

**Comment by muuki88** [comment]
If I move the testing logic into an AutoPlugin in the scripted test everything works.

**Comment by eed3si9n** [comment]
Gaa! This is my fault. I keep forgetting about Maven semantics! This is happening because we do all the testing using Ivy semantics. https://github.com/sbt/sbt/blob/v1.0.0-RC2/project/Dependencies.scala#L12

I opened https://github.com/sbt/sbt/issues/3381 to prevent this from happening...

**Comment by eed3si9n** [comment]
So basically the fix is before we publish the next RC, we need to make sure ALL the module versions are up to date.

**Comment by eed3si9n** [comment]
My theory is confirmed by the fact that the problem goes away if I add

```scala
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % sys.props("project.version"))
dependencyOverrides += "org.scala-sbt" %% "io" % "1.0.0-M13"
```

to `project/plugin.sbt`:

```
Running universal / application-ini-from-javaoptions
[success] Total time: 73 s, completed Jul 27, 2017 11:12:33 PM
```

**Comment by muuki88** [comment]
Npnp 😁 thanks for the quick feedback. I kept back with opening issues until now, because most of the problems where my fault. But this one was pretty resistant 😜

**Comment by eed3si9n** [comment]
Thanks for spending your time to try the beta! These inputs are super useful.

**Comment by dwijnand** [comment]
This isn't a bug in sbt. In your branch you're expressly compiling against io 1.0.0-M11, which is binary incompatible with sbt 1, which is why you're failing at runtime:

https://github.com/sbt/sbt-native-packager/pull/1000/commits/cf8cf4a579bfaae39235356c001f05be38f5ef4f

**Comment by muuki88** [comment]
Thanks a lot for the quick response and fix :)
