### ISSUE TITLE
java.lang.IncompatibleClassChangeError when launching SBT

### ISSUE THREAD

**Issue by leonardschneider** [sbt/sbt#338]
Hi,

I've installed STB 0.11 through MacPorts and I've got this error. I've set up classpath to "", but I still have the same error. Launching with java -jar has the same result, even on sbt-launch.jar downloaded.

**Comment by retronym** [comment]
The MacPorts distribution isn't supported officially here.

I can't reproduce this error with a directly downloaded launcher. Can you follow these steps and paste the output?

```
  ~/code/scratch/20120122 curl http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-tools.sbt/sbt-launch/0.11.2/sbt-launch.jar > sbt-launch.jar  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1017k  100 1017k    0     0   191k      0  0:00:05  0:00:05 --:--:--  221k
  ~/code/scratch/20120122 java -version
java version "1.6.0_29"
Java(TM) SE Runtime Environment (build 1.6.0_29-b11-402-11M3527)
Java HotSpot(TM) 64-Bit Server VM (build 20.4-b02-402, mixed mode)
  ~/code/scratch/20120122 java -jar ./sbt-launch.jar 
[info] Loading global plugins from /Users/jason/.sbt/plugins
[info] Set current project to default-c9c345 (in build file:/Users/jason/code/scratch/20120122/)
> 
```

**Comment by leonardschneider** [comment]
Here it is.

OSX5114:~ leo$ curl http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-tools.sbt/sbt-launch/0.11.2/sbt-launch.jar > sbt-launch.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1017k  100 1017k    0     0   277k      0  0:00:03  0:00:03 --:--:--  346k

OSX5114:~ leo$ java -version
java version "1.6.0_29"
Java(TM) SE Runtime Environment (build 1.6.0_29-b11-402-10M3527)
Java HotSpot(TM) 64-Bit Server VM (build 20.4-b02-402, mixed mode)

OSX5114:~ leo$ export CLASSPATH=""; java -jar ./sbt-launch.jar
java.lang.IncompatibleClassChangeError: Expected static method scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;
    at xsbt.boot.Boot$.runImpl(Boot.scala:25)
    at xsbt.boot.Boot$.main(Boot.scala:15)
    at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: java.lang.IncompatibleClassChangeError: Expected static method scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;

**Comment by axaluss** [comment]
Coud this be related to different scala buid versions?

**Comment by leonardschneider** [comment]
OSX5114:~ leo$ scala -version
Scala code runner version 2.9.1.final -- Copyright 2002-2011, LAMP/EPFL

Does it help?
