### ISSUE TITLE
Autoplugin default settings applied after user defined settings

### ISSUE THREAD

**Issue by godenji** [sbt/sbt#3389]
## steps

Create an autoplugin:
```
object SamplePlugin extends AutoPlugin {
  override def trigger = allRequirements
  override def requires = JvmPlugin

  object autoImport {
    val myTask = taskKey[Seq[File]]("task files")

    def myPluginSettings(cond: Boolean) = {
      println(s"condition: $cond")

      inConfig(Compile)(Seq(myTask := Seq.empty)) ++ (
        if(!cond) Seq.empty
        else {
          val input = compileInputs in (Compile, compile)
          input := (input dependsOn (myTask in Compile)).value
        }
      )
    }
  }
  import autoImport._

  override def projectSettings = myPluginSettings(cond = true)
}
```

Use non-default settings in client `build.sbt`:
`myPluginSettings(cond = false)`

## problem

Observe that reverse dependency on `compile::compileInputs` exists for `myTask` despite having set `cond` to `false`.

## expectation

No reverse dependency on `compile::compileInputs` is set for `myTask` when `cond` is `false`. Furthermore, not even reload `projectSettings`, but I guess that's the effect of changing build settings.

## notes

sbt version: 0.13.15

Example [repo here](https://github.com/godenji/sbt-autoplugin-double-load) illustrates the issue. Clone; then run `sbt scripted` to see above problem condition manifested.

**Comment by eed3si9n** [comment]
Suppose sbt is working as expected, it should load

JvmPlugin, SamplePlugin, and then your build.sbt in the oder.

That would expand to:
1. `myPluginSettings(cond = true)`
2. `myPluginSettings(cond = false)`

That would expand to:

```scala
myTask := Seq.empty
val input = compileInputs in (Compile, compile)
input := (input dependsOn (myTask in Compile)).value
myTask := Seq.empty
```

**Comment by godenji** [comment]
> Suppose sbt is working as expected

Let's not suppose anything, the ordering is exactly the reverse:

1. myPluginSettings(cond = false)
2. myPluginSettings(cond = true)

[Illustrated here](https://github.com/godenji/sbt-autoplugin-double-load/blob/master/src/main/scala/org/example/sbt/SamplePlugin.scala#L12), the steps:

- Add an `AtomicBoolean` flag, `processed`, with default `false`
- Set `processed` to `true` within `myPluginSettings`
- In `projectSettings` only invoke `myPluginSettings` when `processed` is `false`

With `myPluginSettings(cond = false)` the `compileInputs` setting is *not* initialized. If the ordering were as you say then `compileInputs` setting would be initialized. 

Of course, without the atomic check ordering isn't important since `projectSettings` will be invoked no matter what, and the setting at hand is not shared, but rather presence or absence of a setting. The deeper issue is that there doesn't appear to be a way to encode `Option`ality into a setting. For example, if one could:
```
val input = compileInputs in (Compile, compile)
input := {
  if(myFlag.value) Some( (input dependsOn (myTask in Compile)).value )
  else None
}
```
then everything could be handled at build time.

**Comment by eed3si9n** [comment]
The initialization of tasks I don't think is relevant to the semantics of build.sbt DSL.

At the project level, you can enable or disable an auto plugin.
Within a task, you can use dynamic task to use the result of another task or setting to branch your execution - http://www.scala-sbt.org/0.13/docs/Tasks.html#Dynamic+Computations+with
In general build.sbt DSL represents graph (http://www.scala-sbt.org/0.13/docs/Task-Graph.html), not a procedural code.

**Comment by godenji** [comment]
> At the project level, you can enable or disable an auto plugin

Thanks, but we're aiming for keeping the plugin enabled while providing the user the ability to `compile` *without* invoking `myTask`. Disabling the plugin disables it entirely, so the user cannot manually invoke `myTask`.

> Within a task, you can use dynamic task

I don't see how that helps resolve the problem of conditionally setting `compileInputs`. There doesn't appear to be a way to optionally set a setting, whether that happens at build time or run time via `Def.taskDyn`.

~~[`Def.sequential`](http://www.scala-sbt.org/0.13/docs/Tasks.html#Using+Def.sequential) *may* work, haven't tried, but it looks like that may be one way to optionally "shim" in a task (or dummy task) based on some build time value.~~ No, none of sequential, task, or taskDyn are useful wrt to conditionally setting a setting (i.e. being able to return `Seq[Setting[_]]` vs. `Seq.empty`)

**Comment by jroper** [comment]
@godenji The order is being applied correctly. If I have the following code:

```
def myPluginSettings(setName: Boolean) = {
 if (setName) Seq(name := "foo") else Nil
}
```

And then I apply it to the build like this:

```
myPluginSettings(true)
myPluginSettings(false)
```

I effectively get `myPluginSettings(true) ++ myPluginSettings(false)`, which is `Seq(name := "foo") + Nil`, which is `Seq(name := "foo")`. It doesn't matter how many times I apply `myPluginSettings(false)`, it will always return `Nil`, and so always have no effect. If you have an enabled autoplugin, its settings will always be applied, you can't unapply the settings, you can only override them, returning `Nil` from `myPluginSettings` overrides nothing.

If in contrast, I had this:

```
def myPluginSettings(setName: Boolean) = {
 if (setName) Seq(name := "foo") else Seq(name := "bar")
}
```

Then the result would be `Seq(name := "foo") ++ Seq(name := "bar")`, and the `name := "bar"` would win, because this time I have returned something that overrides it.
