### ISSUE TITLE
download is very slow or not accessible at all

### ISSUE THREAD

**Issue by zenglian** [sbt/sbt#3390]
(See the guidelines for contributing, linked above)

## steps

(1) download sbt 0.3.15/16 from scala-sbt.org
(2) run sbt

## problem

Download is very slow or timed out.   
"http://11a36.http.tor01.cdn.softlayer.net/sbt/0.13.16/sbt-0.13.16.msi": DNS resovle failure.

## expectation

Switch to a better/fast/stable CDN. 

## notes

sbt version: *all versions*

**Comment by eed3si9n** [comment]
```
$ time curl -L https://cocl.us/sbt01316msi > sbt-0.13.16.msi
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   520    0   520    0     0    130      0 --:--:--  0:00:03 --:--:--   130
100 58.2M  100 58.2M    0     0  4052k      0  0:00:14  0:00:14 --:--:-- 9574k
curl -L https://cocl.us/sbt01316msi > sbt-0.13.16.msi  0.11s user 0.48s system 4% cpu 14.739 total
```

The download completed in ~15s. We are still in the process of tuning this deployment up, so hopefully we'll see better stability over time.

**Comment by zenglian** [comment]
You'd test it from different areas ... also it's not cocl.us.

**Comment by zenglian** [comment]
here is one test tool:  https://www.dotcom-tools.com/website-speed-test.aspx, 

my url: none is accesible (shanghai has error)
![image](https://user-images.githubusercontent.com/5268434/28994135-601316ba-79f9-11e7-883b-701a6f20147f.png)
