### ISSUE TITLE
source generation hooks?

### ISSUE THREAD

**Issue by zentrope** [sbt/sbt#34]
Hi--

(This is for 0.10.0.)

I think we need a bit more help with the sourceGenerator hooks for those of us who'd like to integrate the use of (say) templating languages, or coffeescript, or what-have-you into our builds.

I'd really love to see a Plugin example, for instance, that would give us some tips about hooking in source files such that sbt automatically detects which ones of changed and invokes a task to compile them. Or however such things have been done.

Looking at plugins for the older sbt (0.7.x) has been really helpful in learning how not to misuse the system, at least for me.

Thanks!

Some context:

https://groups.google.com/d/topic/simple-build-tool/Fo1uhhSXgrs/discussion

**Comment by harrah** [comment]
Done.  https://github.com/harrah/xsbt/wiki/Common-Tasks
