### ISSUE TITLE
Is there a Scala-Java-SBT official docker image ?

### ISSUE THREAD

**Issue by gammabowl** [sbt/sbt#3420]
## steps
* Checked docker hub, didn't find any official docker images

## problem
* I was trying to search for official docker images for scala/java with sbt
* I was mainly interested in Scala with SBT official docker images

## notes
* It would be great to have official images.

**Comment by eed3si9n** [comment]
sbt project does not currently maintain any Docker image. What were you planning to do with it? I see that people make Docker images of their apps using sbt-docker or sbt-native-packager, but are you planning to develop inside a container?

**Comment by gammabowl** [comment]
Thanks for the quick reply.
Yes, we develop scala based apps and we usually make them run inside a docker container. Right now we take a base amazonlinux image and load java, scala and sbt onto it and other required stuff. something like this

```
FROM amazonlinux:2017.03

ENV SCALA_VERSION 2.11.8
ENV SBT_VERSION 0.13.13

# Install Java8 
RUN yum install -y java-1.8.0-openjdk-devel

# Install Scala and SBT
RUN yum install -y https://downloads.lightbend.com/scala/2.11.8/scala-2.11.8.rpm
RUN yum install -y https://dl.bintray.com/sbt/rpm/sbt-0.13.13.rpm
```

**Comment by gammabowl** [comment]
@eed3si9n - Is there is any plan for SBT or Scala repository to maintain Docker images ?

**Comment by eed3si9n** [comment]
We don't have an active plan for it for now.

**Comment by kikicarbonell** [comment]
We are interested to get official support of Docker image with sbt to use in CI pipeline to build sbt projects without installed dependencies.

Please, reopen this issue to implement it. We create a fork of the project to include a Docker file ref: https://github.com/thebijuus/sbt

**Comment by magro** [comment]
Could this issue be reopened?

**Comment by Amos-85** [comment]
Many modern CI systems using docker images as pipeline as code in stage blocks to build packages.
I think it will be very helpful if we'll have an official sbt docker images.

**Comment by stanislavkozlovski** [comment]
I am surprised that no docker image exists.

**Comment by codingthat** [comment]
Anyone finding this thread may be interested in https://github.com/mozilla/docker-sbt

**Comment by ankit-asthana-epam** [comment]
Any update on this to get official support of Docker image with sbt to use in CI pipeline to build sbt projects without installed dependencies.

**Comment by Echo9k** [comment]
Here are some community **SBT** images that you can use.

| Image                                                        | Compressed size (Mb) | Downloads |
| -----------------------------------------------------------: | :------------------: | :-------: |
| [mozilla/sbt](https://hub.docker.com/layers/mozilla/sbt/latest/images/sha256-32950ea7d0a87c7547f9ca9134046cb779046277e534fc095a4d13e8d92ecc62?context=explore) | 350                  | 1M        |
| [bigtruedata/sbt](https://hub.docker.com/r/bigtruedata/sbt)  | 430                  | 500k      |
| [1science/sbt](https://hub.docker.com/r/1science/sbt/tags)   | 70                   | 100k      |
| [gambtho/sbt-docker-alpine](https://hub.docker.com/r/gambtho/sbt-docker-alpine) | 160                  | 100k      |
| [gambtho/sbt](https://hub.docker.com/r/gambtho/sbt)          | 140                  | 50k       |
| [eed3si9n/sbt](https://hub.docker.com/r/eed3si9n/sbt)        | 280                  | 50k       |
| [ictgroupdevops/sbt](https://hub.docker.com/r/ictgroupdevops/sbt) | 404                  | 10k       |

**Comment by eed3si9n** [comment]
There's also https://hub.docker.com/r/hseeberger/scala-sbt/tags with compressed size ranging from 422.39 MB to 815.48 MB (graalvm), and has 10M downloads.
