### ISSUE TITLE
sbt-launch 1.0.0 jar

### ISSUE THREAD

**Issue by pjfanning** [sbt/sbt#3424]
Is there a plan to release an sbt-launch jar for 1.0.0?
The Apache Spark build fetches the launch jars from https://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/

**Comment by eed3si9n** [comment]
We switched to Maven Central - https://repo1.maven.org/maven2/org/scala-sbt/sbt-launch/1.0.0/

I guess we should include that in release note.
