### ISSUE TITLE
Project runtime dependencies are not available

### ISSUE THREAD

**Issue by jodersky** [sbt/sbt#3425]
## steps
Define two projects, one with a runtime dependency on the other

```scala
lazy val proj1 = (project in file("proj1"))  // this project includes some resource that project 2 will need to run
lazy val proj2 = (project in file("proj2")).dependsOn(proj1 % Runtime)
```
## problem
Any resources produced by project 1 are not available on the classpath when running project 2.

## expectation
All classes and resources produced by project 1 should be available to project 2 during runtime 

## notes
This is a regression in sbt 1. The expected behaviour was available in sbt 0.13

sbt version: 1.0.0

**Comment by jodersky** [comment]
Maybe this could help identify the issue:

Inspecting the `run` task in sbt 0.13 gives me the following dependency:
```
root/runtime:fullClasspath
```
whereas in sbt 1.0, I get
```
root/compile:fullClasspath
```

**Comment by eed3si9n** [comment]
That sounds like a bug. Thanks for the report!

**Comment by jodersky** [comment]
In case someone else runs into this, I have a super hacky workaround for now: https://github.com/jodersky/sbt-jni/blob/10b2564b49da87d7567024a27365edf2706bce1c/plugin/src/main/scala/ch/jodersky/sbt/jni/plugins/RunDependencyFixPlugin.scala

**Comment by dwijnand** [comment]
I'm also seeing weird classpath changes upgrading to 0.13.16 in https://github.com/sbt/sbt/pull/3408. Maybe the same issue?

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/3477

**Comment by asflierl** [comment]
The fix for this changes the semantics of externalDependencyClasspath in Runtime: previously it was possible to add directories (e.g. containing resources like .conf files) to the unmanaged classpath in the runtime config. Now this classpath only allows jars.

Should this be added to the release notes? Seems like an incompatible / breaking change.

**Comment by eed3si9n** [comment]
@asflierl That sounds like a regression.
I'll open a new issue for it.
