### ISSUE TITLE
sbtVersion

### ISSUE THREAD

**Issue by ysden123** [sbt/sbt#3429]
(See the guidelines for contributing, linked above)

## steps
run: sbt sbtVersion

## problem
Console output: [info] 0.13.15

## expectation
[info] 1.0.0

## notes

sbt version: *insert sbt version*

**Comment by eed3si9n** [comment]
1. What gets printed when you run `sbt about` in a completely empty directory?
2. Do you have `project/build.properties` for your current build?

**Comment by eed3si9n** [comment]
Here's my output running `sbt sbtVersion` in fresh `/tmp/what`:

```
$ sbt sbtVersion
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0
[warn] No sbt.version set in project/build.properties, base directory: /tmp/what
[info] Set current project to what (in build file:/private/tmp/what/)
[info] 1.0.0
```

**Comment by ysden123** [comment]
1. What gets printed when you run sbt about in a completely empty directory?
sbt about:
"C:\Users\yuriys\.sbt\preloaded\org.scala-sbt\sbt\"1.0.0"\jars\sbt.jar"
[warn] Executing in batch mode.
[warn]   For better performance, hit [ENTER] to switch to interactive mode, or
[warn]   consider launching sbt without any commands, or explicitly passing 'shell'
[info] Loading project definition from C:\Users\yuriys\project
[info] Set current project to yuriys (in build file:/C:/Users/yuriys/)
[info] This is sbt 0.13.15
[info] The current project is {file:/C:/Users/yuriys/}yuriys 0.1-SNAPSHOT
[info] The current project is built against Scala 2.10.6
[info] Available Plugins: sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.CorePlugin, sbt.plugins.JUnitXmlReportPlugin, sbt.plugins.Giter8TemplatePlugin
[info] sbt, sbt plugins, and build definitions are using Scala 2.10.6

Do you have project/build.properties for your current build?
No, I run from work directory

**Comment by ysden123** [comment]
Fixed. It was my fault.

**Comment by eed3si9n** [comment]
ok. So I somehow messed up the Windows installer, which has happened before too:

- https://github.com/sbt/sbt/issues/2181
- https://github.com/sbt/sbt/issues/2473

**Comment by eed3si9n** [comment]
> Fixed. It was my fault.

ok.
