### ISSUE TITLE
Debian package runs /usr/share/sbt/bin/sbt about in postinst and hangs

### ISSUE THREAD

**Issue by Debilski** [sbt/sbt#3448]
(See the guidelines for contributing, linked above)

## steps

Follow the instructions to add the sbt repo to Debian.

    $ apt install sbt
    […]
    Setting up sbt (1.0.0) ...
    Creating system group: sbt
    Creating system user: sbt in sbt with sbt daemon-user and shell /bin/false
    Getting org.scala-sbt sbt 1.0.0 ...
    Progress: [ 66%] [#################################################################...............................]

And then nothing happens anymore.

## problem

Package clutters the `/root` folder with `.ivy2` and `.sbt` folders and hangs while doing `/usr/share/sbt/bin/sbt about`.

Responsible seems to be the last line in DEBIAN/postinst:

    $ dpkg --control sbt_1.0.0_all.deb
    tail -7 DEBIAN/postinst                                                                             
    addGroup sbt ""
    addUser sbt "" sbt "sbt daemon-user" "/bin/false"

    # Chown definitions created by SBT Native Packager

    /usr/share/sbt/bin/sbt about

## expectation

Package should not create files in `/root`, package should not run `sbt` at all as root (!), package should not hang.

## notes

sbt version: sbt_1.0.0_all.deb

**Comment by eed3si9n** [comment]
Released 1.0.0.1.
