### ISSUE TITLE
SBT 1.0.0 is missing in `ivy-releases`

### ISSUE THREAD

**Issue by amanjpro** [sbt/sbt#3449]
I am accessing sbt behind proxy, and I wanted to upgrade to sbt 1.0.0, however the resolution of the sbt itself failed.

For setting up my proxy, I followed this page:
http://www.scala-sbt.org/1.0/docs/Proxy-Repositories.html

And when looking at (what I think) the right repo, I cannot see sbt 1.0.0:
http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt/

**Comment by dwijnand** [comment]
sbt 1+ is released on Maven Central: http://repo1.maven.org/maven2/org/scala-sbt/sbt/1.0.0/

**Comment by amanjpro** [comment]
Mmm, then how can sbt resolve it if it is running behind the proxy?

**Comment by dwijnand** [comment]
Make sure that your proxy repository is configured for Maven Central.

**Comment by amanjpro** [comment]
It is, and it still fails

I have added maven central as mvn-releases proxy though, maybe that is why sbt fails.

```
Getting org.scala-sbt sbt 1.0.0 ...

:: problems summary ::
:::: WARNINGS
		module not found: org.scala-sbt#sbt;1.0.0

	==== local: tried

	  ~/.ivy2/local/org.scala-sbt/sbt/1.0.0/ivys/ivy.xml

	  -- artifact org.scala-sbt#sbt;1.0.0!sbt.jar:

	 ~/.ivy2/local/org.scala-sbt/sbt/1.0.0/jars/sbt.jar

	==== my-ivy-proxy-releases: tried

	  https://myproxy.jfrog.io/myproxy/sbt-proxy/org.scala-sbt/sbt/1.0.0/ivys/ivy.xml

	==== my-maven-proxy-releases: tried

	  https://myproxy.jfrog.io/myproxy/mvn-release/org/scala-sbt/sbt/1.0.0/sbt-1.0.0.pom

	  -- artifact org.scala-sbt#sbt;1.0.0!sbt.jar:

	  https://myproxy.jfrog.io/myproxy/mvn-release/org/scala-sbt/sbt/1.0.0/sbt-1.0.0.jar

		::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: org.scala-sbt#sbt;1.0.0: not found

		::::::::::::::::::::::::::::::::::::::::::::::

```

**Comment by amanjpro** [comment]
See how the pom is found, but somehow SBT fails to resolve the jar:

```
==== my-maven-proxy-releases: tried

	  https://myproxy.jfrog.io/myproxy/mvn-release/org/scala-sbt/sbt/1.0.0/sbt-1.0.0.pom

	  -- artifact org.scala-sbt#sbt;1.0.0!sbt.jar:

	  https://myproxy.jfrog.io/myproxy/mvn-release/org/scala-sbt/sbt/1.0.0/sbt-1.0.0.jar

		::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: org.scala-sbt#sbt;1.0.0: not found

		::::::::::::::::::::::::::::::::::::::::::::::
```

And by following the path, I can clearly see the jar

**Comment by amanjpro** [comment]
So, the issue is with the credentials. Apparently the 0.13 way for providing credentials is not sufficient. In 0.13 I had:
`credentials += Credentials(Path.userHome / ".sbt" / ".credentials")` in `~/.sbt/0.13/plugins/credentials.sbt`

But sbt 1.0.0 wasn't able to read the same line from: `~/.sbt/1.0/plugins/credentials.sbt`

I had to call sbt with: `export SBT_CREDENTIALS=~/.sbt/.credentails; sbt compile` for the credentials to be loaded.

Is this a known change/bug?
@dwijnand

**Comment by dwijnand** [comment]
I'm surprised you say that `~/.sbt/0.13/plugins/credentials.sbt` works, because it should be `~/.sbt/0.13/credentials.sbt`, which for sbt 1 is `~/.sbt/1.0/credentials.sbt`. Does that fix it?

**Comment by amanjpro** [comment]
Yup, putting `credentials.sbt` directly under `1.0` works. Maybe another thing to add to the migration notes?

**Comment by dwijnand** [comment]
Nothing changed here. If you go to an sbt 0.13 build and use `inspect credentials` you should see where you're getting them. For example mine:

```
> inspect credentials
[info] Task: scala.collection.Seq[sbt.Credentials]
[info] Description:
[info] 	The credentials to use for updating and publishing.
[info] Provided by:
[info] 	{file:/s/t-a/}t/*:credentials
[info] Defined at:
[info] 	/Users/dnw/.sbt/0.13/credentials.sbt:2
[info] 	/Users/dnw/.sbt/0.13/credentials.sbt:5
[info] 	/Users/dnw/.sbt/0.13/credentials.sbt:7
[info] Dependencies:
[info] 	*:organization
[info] Reverse dependencies:
[info] 	*:ivySbt
[info] Delegates:
[info] 	*:credentials
[info] 	{.}/*:credentials
[info] 	*/*:credentials
[info] Related:
[info] 	*/*:credentials
```

**Comment by amanjpro** [comment]
Strange, I get the following:

```
inspect credentials
[info] Task: scala.collection.Seq[sbt.Credentials]
[info] Description:
[info] 	The credentials to use for updating and publishing.
[info] Provided by:
[info] 	*/*:credentials
[info] Defined at:
[info] 	(sbt.Defaults) Defaults.scala:100
[info] Reverse dependencies:
[info] 	adgear-identifyd/*:ivySbt
[info] Delegates:
[info] 	adgear-identifyd/*:credentials
[info] 	{.}/*:credentials
[info] 	*/*:credentials
[info] Related:
[info] 	*/*:credentials
```

I also have this line in my `/usr/local/etc/sbtopts`:

`-Dsbt.boot.credentials=~/.sbt/.credentials`

~Moving~ Copying the credentials to `~/.sbt/0.13/` gives a result like yours

**Comment by amanjpro** [comment]
So, if I remove the entry in `sbtopts` the launcher fails to download the specified sbt version from artifactory. And if I move credentials from `0.13/plugins/` to `0.13` artifactory fails to download the dependencies!

**Comment by dwijnand** [comment]
Ah, now I understand. You need the credentials to download sbt. Now `~/.sbt/0.13/plugins/credentials.sbt` makes sense.

**Comment by ghost** [comment]
The IntelliJ IDEA Scala plugin uses Bintray to present a list of available SBT versions in the new project wizard. See https://github.com/JetBrains/intellij-scala/blob/42e1a01bef54aa21a50e9938277f9759eb6565b9/src/org/jetbrains/plugins/scala/project/Versions.scala#L64
