### ISSUE TITLE
Tuple enrichments are deprecated in 0.13 but not in 1.0

### ISSUE THREAD

**Issue by olafurpg** [sbt/sbt#3454]
## steps

- 0.13: https://github.com/sbt/sbt/blob/96ddc33a3e5ecc36ee34a2f032e307501390f4d8/main/settings/src/main/scala/sbt/Structure.scala#L295 
- 1.0: https://github.com/sbt/sbt/blob/037559c8d3f1aee3db95c63650ef8cfd265b28fb/main-settings/src/main/scala/sbt/Structure.scala#L570

## problem

Code that uses tuple enrichments in 0.13 compiles with deprecation warnings while it compiles clean in 1.0.

## expectation

I expect tuple enrichments to compile without deprecation warnings in 0.13.

## notes

I'm working on sbtfix and I'd like the expected output code to compile without deprecation warnings. Users expect a migration tool to remove deprecation warnings.

sbt version: 0.13.16

**Comment by dwijnand** [comment]
One distinction that is omitted is that in 1.0 they're not deprecated, but they're opt-in: https://github.com/sbt/sbt/pull/3291

**Comment by olafurpg** [comment]
Fair enough. Is it possible to import `TupleSyntax` in 0.13? The deprecation warnings should in either case be updated to reflect this change.

**Comment by dwijnand** [comment]
> The deprecation warnings should in either case be updated to reflect this change.

Agreed.

> Is it possible to import TupleSyntax in 0.13?

I'm not sure if it's possible simultaneously:
+ keep tuple syntax is deprecated without the import,
+ make it non-deprecated with the import, and
+ maintain backwards compatibility

**Comment by olafurpg** [comment]
I see. How about we remove the deprecation warnings as in #3455  and add a mention to TupleSyntax in the migration guide? There are other breaking changes in 1.0 that did not get deprecation cycles. False deprecation warnings create unnecessary fear to upgrade to 1.0. Some builds use tuple enrichments a lot.

**Comment by dwijnand** [comment]
In sbtfix are you "fixing" it by importing TupleSyntax?

**Comment by olafurpg** [comment]
I haven't handled tuple enrichments yet, but that is what I had in mind yes.

**Comment by dwijnand** [comment]
Reason I asked is because I'd prefer if we fixed people's builds/plugins by moving to `.value` instead..

**Comment by olafurpg** [comment]
Rewriting tuple syntax might be doable, but to my best knowledge it's not possible to translate tuple enrichments to `.value` in some cases without changing semantics. I'd like to prioritize the rewrites on lower hanging fruits.

**Comment by dwijnand** [comment]
> to my best knowledge it's not possible to translate tuple enrichments to .value in some cases without changing semantics.

I believe it's possible to rewrite from tuple syntax to .value syntax and reserve the same behaviour. And if it's not possible for all cases, it's possible for >90% of them, imo.

What you are referring to is that the `.value` macro introduces some changes in semantics to Scala's semantics. See also Jorge's and Eugene's chat about that in PR #3079.

You have more knowledge of Scalafix and rewrites, but I think it's a mistake to ship a rewrite (especially out the box!) that migrates every sbt 1 build to opt into tuple syntax. I would much rather have a more conservative tuple-to-value-macro rewrite that we incrementally (and conservatively) improve to different shapes and uses of the tuple syntax.

**Comment by olafurpg** [comment]
I am happy to discuss tuple syntax rewriting in https://github.com/scalacenter/scalafix/issues/292

Regardless of the rewrite, what should be done about the deprecation warnings on tuple enrichments?

**Comment by dwijnand** [comment]
> Regardless of the rewrite, what should be done about the deprecation warnings on tuple enrichments?

I'm as of yet still unconvinced the solution is to remove the deprecations in 0.13.17+.

As I said above the (imo) ideal solution would be one that:
+ keeps the tuple syntax deprecated without the import,
+ makes it non-deprecated with the import, and
+ maintains backwards compatibility

though I'm not sure if it's possible.

**Comment by olafurpg** [comment]
I agree that would be an ideal solution. What do you propose as the next actionable step? I find the current deprecation warnings confusing.

**Comment by dwijnand** [comment]
The current deprecation warnings read:

> The sbt 0.10 style DSL is deprecated: '(k1, k2) map { (x, y) => ... }' should now be '{ val x = k1.value; val y = k2.value }'.\nSee http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html

In my opinion referring to it as "deprecated" is correct. Perhaps having the example is confusing. Also (somewhat confusingly) that page has become "Migrating from sbt 0.13.x" in the sbt 1 docs, to include additional changes; compare:

+ http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html
+ http://www.scala-sbt.org/1.0/docs/Migrating-from-sbt-013x.html

Do you think the following message helps remove your source of confusion?

> The sbt 0.10 DSL is deprecated; see http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html

(I like dropping the newline because I've answered lots of questions where users read the first line and not the second line..)

and then mention the `import sbt.TupleSyntax` opt-in in the sbt 1 migration guide? WDYT?

**Comment by olafurpg** [comment]
Saying "The sbt 0.10 DSL is deprecated" is confusing IMO when `import TupleSyntax._` is enough to keep using the same DSL in sbt 1.0. I understand the motivation to encourage users to move to `.value` but I feel `@deprecated` should be reserved for features that are truly deprecated. Bumping a big old sbt build from 0.13.6 to 0.13.16 typically results in a ton of deprecation warnings, which might scare off users who want to migrate to 1.0. I think sbt 1.0 is currently in a critical phase where there is momentum towards migrating.

Semantic tooling to encourage best practices hasn't been there so far so I totally understand the usage of `@deprecated`. However, maybe this will change soon. I'm currently adding support to implement linters in scalafix https://github.com/scalacenter/scalafix/pull/291 "use .value instead of tuple enrichment" could maybe be a linter warning instead of deprecation warning.

**Comment by dwijnand** [comment]
What are you defining as "features that are truly deprecated"? Do you mean `@deprecated` should only be used for things that are being dropped, not also for things that are being moved?


Here are some useful references I looked up.

The relevant definition of "deprecate" in the Oxford dictionary:

> be usable but regarded as obsolete and best avoided, typically because it has been superseded.

(https://en.oxforddictionaries.com/definition/deprecate)

and from the Java documentation:

> A deprecated class or method is [..] so unimportant, in fact, that you should no longer use it, since it has been superseded and may cease to exist in the future.
>
> Java provides a way to express deprecation because, as a class evolves, its API (application programming interface) inevitably changes: methods are renamed for consistency, new and better methods are added, and fields change. But such changes introduce a problem. You need to keep the old API around until developers make the transition to the new one, but you don't want them to continue programming to the old API.

(https://docs.oracle.com/javase/8/docs/technotes/guides/javadoc/deprecation/deprecation.html)

By those definitions moving the tuple syntax out of implicit scope means that the original implicit defs are deprecated.

Now, Scalafix changes the game and I'm a strong supporter of it, but I don't think we can redefine `@deprecated`. Maybe we need to find another name and add another annotation in the stdlib. `@dropped`, maybe?

**Comment by olafurpg** [comment]
You have convinced me that it is OK to keep the `@deprecated` on tuple enrichments.

My worry comes from the fact that there are lots of deprecation warnings that may demotivate users to upgrade.

>  Maybe we need to find another name and add another annotation in the stdlib. @dropped, maybe?

Might be a cool idea, but I prefer to invest my efforts on helping people upgrade to sbt 1.0 😉

**Comment by dwijnand** [comment]
Hopefully we can reassure them by promoting the availability of great tooling: the sbt 1 scalafix rewrites.

**Comment by olafurpg** [comment]
I have updated the PR following your advice. The message is now

> The sbt 0.10 style DSL is deprecated; see http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html

**Comment by eed3si9n** [comment]
Closing this since I'm guessing many builds have now moved on.
