### ISSUE TITLE
Code references to 0.14.0 outdated?

### ISSUE THREAD

**Issue by yawaramin** [sbt/sbt#3457]
Since sbt is moving to version 1 from 0.13, these references should be updated:

* https://github.com/sbt/sbt/blob/31ac8c940cfdfdf2fe984b61ff0f36ad1a58cd83/main/src/main/scala/sbt/internal/PluginDiscovery.scala#L61
* https://github.com/sbt/sbt/blob/31ac8c940cfdfdf2fe984b61ff0f36ad1a58cd83/main-command/src/main/scala/sbt/BasicCommandStrings.scala#L184
* https://github.com/sbt/sbt/blob/31ac8c940cfdfdf2fe984b61ff0f36ad1a58cd83/main/src/main/scala/sbt/Project.scala#L112

**Comment by xuwei-k** [comment]
https://github.com/sbt/sbt/issues/3411

**Comment by yawaramin** [comment]
Closing as duplicate.
