### ISSUE TITLE
SBT issues

### ISSUE THREAD

**Issue by mukesh14j** [sbt/sbt#3461]
Error during SBT execution: Label <!Doctype html> is not in section
sbt version: 0.13

**Comment by dwijnand** [comment]
Hi! In order to be able to solve issues we need to be able to understand and reproduce them, which is why we have defined an issue template, which you can find at https://github.com/sbt/sbt/blob/1.x/ISSUE_TEMPLATE.md. Unfortunately without that we cannot solve the issue you're seeing.
