### ISSUE TITLE
Reinstallation of SBT doesn't work

### ISSUE THREAD

**Issue by mukesh14j** [sbt/sbt#3463]
## steps
1) Install the SBT in windows 7.
2) uninstall and install again SBT
3) set the path of SBT in path variable
4) now open the command prompt and type sbt

## problem
It gives an error 
Error during SBT execution:Label <!DOCTYPE html> is not in section

## expectation

Should run successfully without any error

## notes
Both times the installation path are different and environment variables also have been updated

sbt version: 0.13.0

**Comment by eed3si9n** [comment]
@mukesh14j Thanks for the report.
We only support the latest patch versions. Could you try installing 0.13.16 please?
Also does this happen with any builds? If not, could you upload a sample build somewhere?

**Comment by mukesh14j** [comment]
This happens with all builds, latest build too

**Comment by SethTisue** [comment]
still an issue in sbt 1.x? if so, let us know and we'll reopen
