### ISSUE TITLE
Use a semantic version as defaut version : 0.0.1-SNAPSHOT

### ISSUE THREAD

**Issue by fredericnowak** [sbt/sbt#3467]

**Comment by dwijnand** [comment]
This is an easy one for the community: https://github.com/sbt/sbt/blob/v1.0.0/main/src/main/scala/sbt/Defaults.scala#L198

Personally I think "0.0.1-SNAPSHOT" makes little sense - I think it should be "0.1.0-SNAPSHOT".

**Comment by Yudi26** [comment]
What is use of SNAPSHOT?

**Comment by dwijnand** [comment]
It's a Maven thing, from its resolution engine Aether.
