### ISSUE TITLE
Logs are full of connection leak warnings during update.

### ISSUE THREAD

**Issue by dpratt** [sbt/sbt#3485]
(See the guidelines for contributing, linked above)

## steps

Open a project and run the 'update' task.

## problem

The logs are filled intermittently with entries that look like the following - 

```
WARNING: A connection to https://my.maven.server/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
```

## expectation

This isn't a huge deal, but it might be an indication of an iceberg problem w.r.t. artifact download and resolution.

## notes

sbt version: 1.0.0 and 1.0.1

**Comment by eed3si9n** [comment]
Fixed in #3511
