### ISSUE TITLE
Upgrade to latest version of Giter8

### ISSUE THREAD

**Issue by marconilanna** [sbt/sbt#3488]
Giter8 now has [support for conditionals](https://github.com/foundweekends/giter8/issues/157). To ease adoption by template authors, it is desirable to upgrade Giter8 in the next version of sbt, making it available through the `sbt new` command (the recommended way to get users started through templates).

May require updating sbt-giter8-resolver accordingly.

**Comment by rossabaker** [comment]
I just started using the `maven(org.scala-lang, scala-library, stable)` syntax, which is wonderful, and broke the `sbt new` use case.

**Comment by VEINHORN** [comment]
@eed3si9n @dwijnand @marconilanna Conditionals are still not working (SBT 1.1.0). Can you please upgrade to the latest version of Giter to fix this issue?

sbt/sbt-giter8-resolver#12

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/4263
