### ISSUE TITLE
0.13.16 SBT firing errors with sbteclipse-plugin: how to resolve them?

### ISSUE THREAD

**Issue by heoa** [sbt/sbt#3492]
I am trying to get this plugin working for the Apache Spark course [here](https://www.coursera.org/learn/scala-spark-big-data) that relies on an old version of Eclipse Scala IDE 2.11 and old version of SBT 0.13.*.

## steps

I run the 0.13.16 SBT from the [website](http://www.scala-sbt.org/download.html) but I am getting the below error with the sbteclipse-plugin. i run things on macOS.

## problem

```
$ /Applications/sbt/bin/sbt
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /Users/hhh/Spark_Scala_2.11/hello-world-template/project
[info] Updating {file:/Users/hhh/Spark_Scala_2.11/hello-world-template/project/}hello-world-template-build...
[warn]  module not found: com.typesafe.sbteclipse#sbteclipse-plugin;5.1.0
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0//5.1.0/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0//5.1.0/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /Users/hhh/.ivy2/local/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0//5.1.0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/sbteclipse/sbteclipse-plugin_2.12_1.0/5.1.0/sbteclipse-plugin-5.1.0.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /Users/hhh/.sbt/preloaded/com.typesafe.sbteclipse/sbteclipse-plugin/5.1.0/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////Users/hhh/.sbt/preloaded/com/typesafe/sbteclipse/sbteclipse-plugin_2.12_1.0/5.1.0/sbteclipse-plugin-5.1.0.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.typesafe.sbteclipse#sbteclipse-plugin;5.1.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]      com.typesafe.sbteclipse:sbteclipse-plugin:5.1.0 (scalaVersion=2.12, sbtVersion=1.0)
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]      com.typesafe.sbteclipse:sbteclipse-plugin:5.1.0 (scalaVersion=2.12, sbtVersion=1.0) (/Users/hhh/Spark_Scala_2.11/hello-world-template/project/plugins.sbt#L1-2)
[warn]        +- default:hello-world-template-build:0.1-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.sbteclipse#sbteclipse-plugin;5.1.0: not found
[error]     at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:331)
[error]     at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:205)
[error]     at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:229)
[error]     at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:190)
[error]     at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]     at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]     at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
[error]     at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
[error]     at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
[error]     at xsbt.boot.Using$.withResource(Using.scala:10)
[error]     at xsbt.boot.Using$.apply(Using.scala:9)
[error]     at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
[error]     at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
[error]     at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]     at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]     at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]     at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:185)
[error]     at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:182)
[error]     at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:228)
[error]     at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:190)
[error]     at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error]     at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error]     at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:38)
[error]     at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:91)
[error]     at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:64)
[error]     at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:104)
[error]     at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error]     at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:104)
[error]     at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:87)
[error]     at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:141)
[error]     at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:118)
[error]     at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2313)
[error]     at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]     at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error]     at sbt.std.Transform$$anon$4.work(System.scala:64)
[error]     at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error]     at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[error]     at sbt.Execute.work(Execute.scala:266)
[error]     at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error]     at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error]     at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]     at java.lang.Thread.run(Thread.java:748)
[error] (*:update) sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.sbteclipse#sbteclipse-plugin;5.1.0: not found
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

## expectation

![image](https://i.stack.imgur.com/Evxg1.png)

## notes

sbt version: *0.13.16*

**Comment by kitschen** [comment]
Same problem here (same course, same issue). Already downgraded from SBT 1.x.x. to 0.13.16 to check whether this was the problem - it is not.
Running on Windows 10, if that matters

**Comment by eed3si9n** [comment]
@heoa I am not taking the course, so I am unable to reproduce your problem. Could you copy all the files in your build somewhere like gist.github.com, plz?

**Comment by eed3si9n** [comment]
From the stacktrace, I am pretty sure it's not using sbt 0.13.16.
The first step likely is you create `project/build.properties`:

```
sbt.version=0.13.16
```

**Comment by kitschen** [comment]
@eed3si9n Thanks, in fact the build.properties contained `sbt.version=1.0.3`. Changing the version fixes the issue.
This test project was made using
`sbt new scala/hello-world.g8`
Unclear, why sbt 0.13 would create a build file referencing sbt 1.0.

**Comment by eed3si9n** [comment]
With sbt, you can set the version of sbt using `project/build.properties` so the version of sbt you have it installed system-wide is not super important. This is somewhat analogous to gradle wrapper being able to invoke different versions of gradle if you're familiar with that.

`sbt new` delegates the call to Giter8, when the template ends with `.g8`, and Giter8 template are just a bunch of files on GitHub (in this case https://github.com/scala/hello-world.g8).

**Comment by priya-aishh** [comment]
i am having the same problem . i m using sbt version 1.1.4
and scala 2.12 in ubuntu 16.04 .

i changed the sbt version to 1.1.4 in build.properties still i m facing the same problem

**Comment by priya-aishh** [comment]
I am trying to get this plugin working for the Apache Spark course here that relies on an old version of Eclipse Scala IDE 2.12 and SBT 1.1.4. but I am getting the below error with the sbteclipse-plugin on ubuntu 16.04.

[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /home/hadoop1/workspace/coursera/hello-world/project
[info] Updating ProjectRef(uri("file:/home/hadoop1/workspace/coursera/hello-world/project/"), "hello-world-build")...
[warn]  module not found: com.typesafe.sbteclipse#sbteclipse-plugin;5.1.0
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/5.1.0/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/5.1.0/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /home/hadoop1/.ivy2/local/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/5.1.0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/sbteclipse/sbteclipse-plugin_2.12_1.0/5.1.0/sbteclipse-plugin-5.1.0.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /home/hadoop1/.sbt/preloaded/com.typesafe.sbteclipse/sbteclipse-plugin/5.1.0/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////home/hadoop1/.sbt/preloaded/com/typesafe/sbteclipse/sbteclipse-plugin_2.12_1.0/5.1.0/sbteclipse-plugin-5.1.0.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.typesafe.sbteclipse#sbteclipse-plugin;5.1.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]   com.typesafe.sbteclipse:sbteclipse-plugin:5.1.0 (scalaVersion=2.12, sbtVersion=1.0)
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]   com.typesafe.sbteclipse:sbteclipse-plugin:5.1.0 (scalaVersion=2.12, sbtVersion=1.0) (/home/hadoop1/workspace/coursera/hello-world/project/plugins.sbt#L1-2)
[warn]     +- default:hello-world-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.sbteclipse#sbteclipse-plugin;5.1.0: not found
[error]  at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:334)
[error]  at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error]  at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error]  at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error]  at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]  at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]  at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error]  at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error]  at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error]  at xsbt.boot.Using$.withResource(Using.scala:10)
[error]  at xsbt.boot.Using$.apply(Using.scala:9)
[error]  at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error]  at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error]  at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]  at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]  at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]  at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error]  at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error]  at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error]  at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
[error]  at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error]  at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error]  at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:46)
[error]  at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:99)
[error]  at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error]  at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:112)
[error]  at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error]  at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:112)
[error]  at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:95)
[error]  at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error]  at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:126)
[error]  at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2385)
[error]  at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]  at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]  at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]  at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error]  at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]  at sbt.Execute.work(Execute.scala:271)
[error]  at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error]  at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]  at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error]  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]  at java.lang.Thread.run(Thread.java:748)
[error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.sbteclipse#sbteclipse-plugin;5.1.0: not found
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

**Comment by oyes704** [comment]
Same Scala training. 
Had the same UNRESOLVED DEPENDENCIES issue with default SBT installation 1.1.1.
Downgraded SBT to 0.13.12 but not able to load the hello-world project. Guess now it's Java compatibility. Using 1.8 for Eclipse, but have 10.0 by default. Could that be a problem?

sbt new scala/hello-world.g8
[info] Loading global plugins from /Users/oly/.sbt/0.13/plugins
java.lang.NullPointerException
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1769)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1130)
	at java.base/java.util.regex.Pattern.split(Pattern.java:1249)
	at java.base/java.util.regex.Pattern.split(Pattern.java:1322)
	at sbt.IO$.pathSplit(IO.scala:797)
	at sbt.IO$.parseClasspath(IO.scala:912)
	at sbt.compiler.CompilerArguments.extClasspath(CompilerArguments.scala:66)
	at sbt.compiler.MixedAnalyzingCompiler$.withBootclasspath(MixedAnalyzingCompiler.scala:188)
	at sbt.compiler.MixedAnalyzingCompiler$.searchClasspathAndLookup(MixedAnalyzingCompiler.scala:166)
	at sbt.compiler.MixedAnalyzingCompiler$.apply(MixedAnalyzingCompiler.scala:176)
	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
	at sbt.Compiler$.compile(Compiler.scala:152)
	at sbt.Compiler$.compile(Compiler.scala:138)
	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:860)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:851)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:849)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
[error] (compile:compileIncremental) java.lang.NullPointerException
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q

**Comment by mysteryDave** [comment]
Had the same issue using SBT 1.2.1 on Windows 10.
I did the following steps:
Changed scala version to 1.2.1 in build.sbt
Changed scala version to 1.2.1 in /project/build.properties
ran sbt from the /project directory

**Comment by mysteryDave** [comment]
Also changed in build.sbt

**Comment by eed3si9n** [comment]
We use GitHub issue mostly to track bugs and tasks on sbt development. If you need help, please check this out - https://www.scala-sbt.org/support.html
