### ISSUE TITLE
"publish" Scoping

### ISSUE THREAD

**Issue by eaplatanios** [sbt/sbt#3493]
I've been trying to scope a setting key to the publish task scope and I've been unable to. To provide a bit more context:

I have a library that uses some JNI bindings. Normally, whenever you run "compile" and "test", I compile these bindings using the GCC in your machine. My native compilation task is using a boolean setting to determine whether to cross-compile for other system architectures. By default that flag is set to `false` (that is because most users would not want to cross-compile and because I use docker containers for cross-compiling and many users might not have docker installed -- plus it takes more time). I would like to be able to set the cross-compilation setting key to `true` only for the `publish` and `publishSigned` tasks, but I see unable to do so. Specifying `crossCompilationFlag in publish := true` does not seem to work.

Do you have any idea what the problem may be?

Thank you!

**Comment by eed3si9n** [comment]
We use GitHub issue mostly to track bugs and tasks on sbt development. If you need help, please check this out - https://www.scala-sbt.org/support.html
