### ISSUE TITLE
cant　download sbt1.0.1

### ISSUE THREAD

**Issue by blueway** [sbt/sbt#3494]
(See the guidelines for contributing, linked above)
 
## problem
i cant download the lastest sbt version1.0.1 from `scala-sbt.org` website。My country cant access the  cdn.

**Comment by dwijnand** [comment]
As a workaround can you:

1. Download and use sbt 1.0.0 from the release on GitHub: https://github.com/sbt/sbt/releases/tag/v1.0.0
2. Defines `sbt.version=1.0.1` in your project's `project/build.properties`

Then it'll download the jars for sbt 1.0.1 and run that.

**Comment by eed3si9n** [comment]
@blueway Are you in China? If so this is a duplicate of #3558, and we need to do something to fix.

What do you see when you run:

```
$ curl -v https://cocl.us/sbt-1.0.1.tgz > sbt-1.0.1.tgz
```

or

```
$ curl -v https://62a44.https.cdn.softlayer.net/sbt/1.0.1/sbt-1.0.1.tgz > sbt-1.0.1.tgz
```

I am trying to figure out which URL or server is being blocked. Thanks.

**Comment by blueway** [comment]
@eed3si9n  yes,I am in China, these urls cannot be  downloaded

echo here: 
```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:19 --:--:--     0* Could not resolve host: 62a44.https.cdn.softlayer.net
* Closing connection 0
curl: (6) Could not resolve host: 62a44.https.cdn.softlayer.net
```

**Comment by eed3si9n** [comment]
@blueway I've uploaded to another CDN. Please check - http://www.scala-sbt.org/download.html

**Comment by blueway** [comment]
@eed3si9n , ok , the amazonaws always can download, thanks
