### ISSUE TITLE
sbt 1.x fails to compile against current 1.x modules

### ISSUE THREAD

**Issue by cunei** [sbt/sbt#3503]
Compiling the current 1.x sbt and modules together (using dbuild), the following error appears:
```
[sbt212] [error] /localhome/jenkinssbt/workspace/sbt-validator/target-0.9.9/project-builds/sbt212-1cc041bfbf3c945f1b96bd4072b9d7aed2253484/sbt/src/main/scala/Import.scala:54:37: object Source is not a member of package sbt.internal.io
[sbt212] [error] Note: class Source exists, but it has no companion object.
[sbt212] [error]   val WatchSource = sbt.internal.io.Source
[sbt212] [error]                                     ^
```
Relevant SHAs:
sbt/sbt@34945af6314dee3c9ea55a76c882007f44819509
sbt/zinc@ef3a2c48a4e6b6126c8f1d0a99e530d64925c7d3
sbt/io@50fa1529cdfd8a57b614b9279024595a584408a6
sbt/librarymanagement@6fc7bc6dc9241ba1c668a61e5a80c87563d7b21f
sbt/util@cba6f83447b84cc1e967f25a930d4f411f6f0664

**Comment by dwijnand** [comment]
Should be fixed with https://github.com/sbt/io/pull/75.

**Comment by cunei** [comment]
Yes, it's ok now. Validation run: https://jenkins.scala-sbt.org:8592/job/sbt-validator/151/console
