### ISSUE TITLE
run doesn't support directory based `externalDependencyClasspath in Runtime`

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3504]
Originally reported by @asflierl in https://github.com/sbt/sbt/issues/3425#issuecomment-325613510 as: 

> The fix for this changes the semantics of externalDependencyClasspath in Runtime: previously it was possible to add directories (e.g. containing resources like .conf files) to the unmanaged classpath in the runtime config. Now this classpath only allows jars.

## steps

1. Add directory to `externalDependencyClasspath in Runtime`
2. `run`

## problem

`run` doesn't recognize the conf file etc that's in it.

## expectation

`run` recognizes

## notes

sbt version: 1.0.1

**Comment by asflierl** [comment]
awesome, much appreciated
