### ISSUE TITLE
compile dependencies missing

### ISSUE THREAD

**Issue by samuelbernardo** [sbt/sbt#3506]
## steps
Error when compiling the following command with release 1.0.1
sbt-allsources.sh -Dsbt.log.noformat=true compile

## problem
Missing dependencies
sbt.ResolveException: unresolved dependency: com.typesafe#sbt-mima-plugin;0.1.17: not found
unresolved dependency: org.foundweekends#sbt-bintray;0.5.1: not found
unresolved dependency: org.scala-sbt#sbt-contraband;0.3.0: not found
unresolved dependency: com.jsuereth#sbt-pgp;1.1.0-M1: not found
unresolved dependency: com.lucidchart#sbt-scalafmt;1.10: not found

## expectation

Ajust the necessary dependency versions inside sbt.build

## notes

sbt version: *0.13*

**Comment by eed3si9n** [comment]
sbt-allsources.sh should work now, but I am not sure if we should recommend it as a way of contribution.
