### ISSUE TITLE
Sbt to Support Session Cookies on Ivy Resolve

### ISSUE THREAD

**Issue by d80tb7** [sbt/sbt#3509]
## steps

1. Set up a mvn repo (e.g. artifactory) that passes back a session cookie when artifacts are resolved.
2. Instruct sbt to use the repo for resolving dependencies.
3. Run a sample sbt build that requires artifacts to be resolved.
4. See that SBT doesn't respect the Set-Cookie header passed back from the repo.

## notes

1. This behaviour is caused because the Apache Ivy BasicUrlHandler doesn't have any cookie support.
2. The effect of this can be to make artifact resolution unusably slow (in this case session cookie is used for authentication so by omitting the session cookie authentication now has to be performed on every request)
3. This definitely occurs on 0.13.  Unfortunately I can't easily test on 1.x, but having looked at the code I suspect that the issue would be the same as you've done a fairly straight port of  BasicUrlHandler, just using the Gigahorse client.
4. A fix in 1.x would be fine!

**Comment by d80tb7** [comment]
@eed3si9n 

I've take a look at this and can confirm that this is still an issue on 1.x. I would propose the following fix- which I'm happy to implement if you're ok with it.  Changes would be made in sbt/librarymanagement

- Create an implementation of okhttp3.CookieJar which stores cookies in memory and uses an accept-all policy.
- Update line 218 of GigahorseURLHandler so it constructs the ok http client with a new instance of this cookie jar.

couple of notes:

- CookieJar would probably better long term live somewhere lower down the stack (Gigahorse or OkHttp itself) as it seems pretty generic. For now, however, I'd propose leaving it in the sbt/librarymanagement project.
-  This change could be controlled by a system property which defaults to off if you want.  I'd personally prefer not to do this, but if you're worried it might break things for someone then we could go with that.
-  AFAICT there are no unit tests for GigahorseURLHandler so I wouldn't propose adding any for this change.  The cookie jar should be readily testable though.

**Comment by d80tb7** [comment]
Actually, rather than create our own cookie handler It'd probably be enough to just use OKHttp's JavaNetCookieJar so you'd end you with something like:

```scala
private lazy val okHttpClient: OkHttpClient = {
    http
      .underlying[OkHttpClient]
      .newBuilder()
      .authenticator(new JavaNetAuthenticator)
      .cookieJar(new JavaNetCookieJar(new CookieManager()))
      .followRedirects(true)
      .followSslRedirects(true)
      .build
  }
```

**Comment by eed3si9n** [comment]
I am closing this since sbt 1.3.0 will switch to using Coursier.
Please reopen the issue there if this is still an issue.
