### ISSUE TITLE
SBT 1.0.1 - java.lang.VerifyError: Uninitialized object exists on backward branch

### ISSUE THREAD

**Issue by ni1ius99** [sbt/sbt#3516]
## steps
Install JDK 1.8.0_144
Install sbt 1.0.1
run 'sbt new scala/hello-world.g8'

## problem
Exact same error as in https://github.com/sbt/sbt/issues/3471

## expectation
Expected that this wouldn't occur because I have JDK 1.8.0_144 installed.

## notes
Running Windows 10
I had first installed sbt by running 'sbt run' on the first example at https://playframework.com/download#examples, when I had an earlier JDK 8 installed. I encountered the backward branch error there too, so tried installing sbt using the installer.

sbt version: 1.0.1

**Comment by eed3si9n** [comment]
If it's anything related to the same JDK bug - https://bugs.openjdk.java.net/browse/JDK-8046233, could you print the output of `java -version`?
I see that you've installed 1.8.0_144, but I'd like to see what `java -version` prints out at the terminal.

**Comment by ni1ius99** [comment]
Sure, here it is -

> ***\playframework>java -version
> java version "1.8.0_144"
> Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
> Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
>

**Comment by ni1ius99** [comment]
Problem solved - JAVA_HOME environment variable was still set to a JDK 1.7 folder. I removed the environment variable. The same folder was also in the PATH variable, although after the Oracle javapath. sbt runs now.

**Comment by eed3si9n** [comment]
Cool. Thanks for reporting back!

**Comment by karthisampath** [comment]
I'm getting this error while running my sbt , even when i use IDE i'm getting the same error
java.lang.VerifyError: Uninitialized object exists on backward branch 487

**Comment by ryan-williams** [comment]
FWIW I've seen this in IntelliJ twice recently and switching the project JDK from `1.8.0_05` to `1.8.0_111` (just the two I happen to have installed+configured in IJ, idk if there is more significance than that) fixes it.
