### ISSUE TITLE
Source/Github dependency on a plugin gives an  NPE, while file dependency of the same code works fine.

### ISSUE THREAD

**Issue by max-l** [sbt/sbt#352]
Launching SBT in a project with a Source/Github dependency on this plugin https://github.com/max-l/pegdown-sbt
gives an  NPE, while file dependency of the same code (plugin) works fine.

Steps to reproduce : https://groups.google.com/d/topic/simple-build-tool/z5-YUQEuoqE/discussion

**Comment by harrah** [comment]
Works for me.  I would need to see the stack trace to see if there is an actual problem.
