### ISSUE TITLE
Is there a way to make transitive dependency conflicts resolve to the latest version?

### ISSUE THREAD

**Issue by hgiddens** [sbt/sbt#3525]
#### build.sbt

```scala
scalaVersion := "2.11.11"
resolvers += "bintray-backline-open-source-releases" at "https://dl.bintray.com/backline/open-source"
libraryDependencies := Seq(
  "backline" %% "akka-http-metrics" % "1.0.0",
  "com.typesafe.akka" %% "akka-http" % "10.0.9"
)
```

#### App.scala

```
object App extends App {
  println(classOf[akka.http.scaladsl.model.ContentType.WithMissingCharset].getSimpleName)
}
```

Then try to run `sbt compile`.

## problem

The set of transitive dependencies contains `com.typesafe.akka:akka-http-core_2.11:10.0.6` (a dependency of the metrics library) and `com.typesafe.akka:akka-http-core_2.11:10.0.9` (a dependency of `com.typesafe.akka:akka-http_2.11:10.0.9`). However, even though the `latestRevision` conflict manager is being used, the _earlier_ revision is selected, and compilation fails (as the `WithMissingCharset` class isn't present in 10.0.6).

## expectation

The latest revision is selected – is there some way to do this? It's rather inconvenient to have to specify the versions of the transitive dependencies manually.

#### `<dependency>` elements from metrics `pom.xml` & translated `ivy.xml`

```xml
<dependency>
  <groupId>com.typesafe.akka</groupId>
  <artifactId>akka-http-core_2.11</artifactId>
  <version>10.0.6</version>
</dependency>
```

```xml
<dependency org="com.typesafe.akka" name="akka-http-core_2.11" rev="10.0.6" force="true" conf="compile->compile(*),master(compile);runtime->runtime(*)"/>
```

#### `<dependency>` elements from Akka HTTP `pom.xml` & translated `ivy.xml`

```xml
<dependency>
  <groupId>com.typesafe.akka</groupId>
  <artifactId>akka-http-core_2.11</artifactId>
  <version>10.0.9</version>
</dependency>
```

```xml
<dependency org="com.typesafe.akka" name="akka-http-core_2.11" rev="10.0.9" force="true" conf="compile->compile(*),master(compile);runtime->runtime(*)"/>
```

sbt version: 1.0.1

**Comment by eed3si9n** [comment]
Using sbt 1.3.0-RC3, which uses Coursier, this issue seems to be fixed.
