### ISSUE TITLE
No debug messages in MavenResolverPlugin 

### ISSUE THREAD

**Issue by Wasapl** [sbt/sbt#3535]
I use MavenResolverPlugin to publish artefact to Nexus. And I want to see which files plugins reads from and writes to Nexus.

## steps
I have `addMavenResolverPlugin` statement in `project/plugins.sbt`
I use `UniversalDeployPlugin` since I need to package some additional files into tar.gz alone with assembly Jar file. I have next line in `build.sbt` for that:
```
enablePlugins(JavaAppPackaging, UniversalDeployPlugin)
``` 
To enable debug logging I have added next line to build.sbt:
```
logLevel in Universal := Level.Debug
```

## problem
MavenResolverPlugin prints nothing: I get only list of tared files and Success message at the end of  output of next command: `sbt clean universal:publish`.

## expectation
I want to see all uploads to and downloads from Nexus, was it successful or not. 

## notes

sbt version: 0.13.15

**Comment by dwijnand** [comment]
`Universal` is an sbt-native-packager configuration. /cc'ing @muuki88

**Comment by eed3si9n** [comment]
MavenResolverPlugin has always been an experimental plugin, and I've split out MavenResolverPlugin for sbt 1.0 to https://github.com/sbt/sbt-maven-resolver so it can be updated independent of sbt.

If someone wants to maintain it, we'd welcome a contributor but it's unlikely that we will add new feature to it unless we are asked from a Lightbend subscriber. Could we close as won't fix?

**Comment by Wasapl** [comment]
@eed3si9n something went wrong in sbt-maven-resolver repo. I cant even clone it:
```
# git clone git@github.com:sbt/sbt-maven-resolver.git
Cloning into 'sbt-maven-resolver'...
remote: Counting objects: 218, done.
remote: Total 218 (delta 0), reused 0 (delta 0), pack-reused 218
Receiving objects: 100% (218/218), 48.54 KiB | 310.00 KiB/s, done.
Resolving deltas: 100% (42/42), done.
warning: remote HEAD refers to nonexistent ref, unable to checkout.
#```
Could it be the reason you cannot find a contributor for it ?

**Comment by andrey-gatash** [comment]
@eed3si9n, since you're saying it's experimental and looks like sbt does not have a lot of interest in supporting Maven Repo publishing, any other plugins/approaches you can recommend to work with Maven Repos?

**Comment by eed3si9n** [comment]
@andrey-gatash For me, sbt + sbt-pgp works fine publishing to either Sonatype or Bintray.

**Comment by Wasapl** [comment]
@eed3si9n how you update  maven-metadata.xml then? Does sbt + sbt-pgp updates it for you ?

**Comment by eed3si9n** [comment]
@Wasapl Something went wrong with the branch name it seems. I created "master" branch, and pushed it again. Please try again.

As per `maven-metadata.xml`, I just let the repositories like Sonatype generate it. One of the problems sbt had early on was that it did not read from the metadata correctly because we customized the publishing layout. I fixed that issue here https://github.com/sbt/ivy/pull/13.

**Comment by eed3si9n** [comment]
See also [sbt-aether-deploy](https://github.com/arktekk/sbt-aether-deploy) that's been maintained actively.

**Comment by Wasapl** [comment]
@eed3si9n now https://github.com/sbt/sbt-maven-resolver clones successfuly. 

I'll try to use sbt alone and sbt + sbt-aether-deploy. 

You may close this issue as wont fix.
Thank you!
