### ISSUE TITLE
sbt.version in properties file is overly insistent

### ISSUE THREAD

**Issue by paulp** [sbt/sbt#354]
I can't seem to override the sbt version specified in project/build.properties from the command line.  This is highly suboptimal for me, can it be changed to honor either the version in the launcher of the version which I explicitly indicate somehow, as in the below?

```
% java -Dsbt.version=0.11.2 -jar /r/sbt-extras/.lib/0.11.2/sbt-launch.jar about
[info] Loading project definition from /s/blueeyes/project
[info] Set current project to blueeyes (in build file:/s/blueeyes/)
[info] This is sbt 0.11.0

% java -jar /r/sbt-extras/.lib/0.11.2/sbt-launch.jar 'set sbtVersion := "0.11.2"' about
[info] Loading project definition from /s/blueeyes/project
[info] Set current project to blueeyes (in build file:/s/blueeyes/)
[info] Reapplying settings...
[info] Set current project to blueeyes (in build file:/s/blueeyes/)
[info] This is sbt 0.11.0

% java -Dsbt.version=0.11.3-SNAPSHOT -jar /r/sbt-extras/.lib/0.11.3-SNAPSHOT/sbt-launch.jar --version
sbt launcher version 0.11.3-20111207-052114
% java -Dsbt.version=0.11.3-SNAPSHOT -jar /r/sbt-extras/.lib/0.11.3-SNAPSHOT/sbt-launch.jar about
[info] Loading project definition from /s/blueeyes/project
[info] Set current project to blueeyes (in build file:/s/blueeyes/)
[info] This is sbt 0.11.0
```

**Comment by harrah** [comment]
I've implemented this, but it isn't going to work for earlier launchers, obviously.  You might consider just using the latest launcher, generating your own sbt.boot.properties file, and passing that to the launcher.  You can look at the /sbt/sbt.boot.properties file in each launcher to see the settings for each previous version.

**Comment by paulp** [comment]
Is it your belief that I could use a single launcher for all 0.9+ versions of sbt by having a stable of sbt.boot.properties files and passing them in to it? Or have there been changes which make that impossible? That would simplify matters quite a bit, because I could embed all the properties files in the runner and be down to a one-jar dependency plus the 0.7 series.

**Comment by harrah** [comment]
Yes, you should be able to just use the sbt.boot.properties file from previous launcher versions with the 0.12 launcher.  The launcher has remained compatible (in theory).  I tried the sbt.boot.properties from the 0.7.7 launcher and that worked ok with the launcher from the 0.12 branch.
