### ISSUE TITLE
Investigate scripted run/error

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3543]
```
[error] x run / error 
[error]  Cause of test exception: {line 18}  Command succeeded but failure was expected
```

**Comment by cunei** [comment]
The scripted test invokes: `run`. I just determined that in certain cases the jar that is packaged for later use by `scripted` does not contain the classfile of the source file that has just been compiled, but the classfile that were there prior to the invocation of `run`. For example:
Inside `target/scala-2.12/error_2.12-0.1-SNAPSHOT.jar`:
```
  public void main(java.lang.String[]);
    Code:
       0: iconst_0
       1: invokestatic  #21                 // Method java/lang/System.exit:(I)V
       4: return
```
Inside `target/scala-2.12/classes/Spawn$.class`:
```
  public void main(java.lang.String[]);
    Code:
       0: iconst_1
       1: invokestatic  #21                 // Method java/lang/System.exit:(I)V
       4: return
```
I'll do some more debugging to find out why this is happening.
