### ISSUE TITLE
sbt 1.0.x native-packages not published to bintray

### ISSUE THREAD

**Issue by jarreds** [sbt/sbt#3547]
Not seeing the native-packages for 1.0.x here https://bintray.com/sbt/native-packages/sbt

**Comment by eed3si9n** [comment]
This is intentional.
Please download from http://www.scala-sbt.org/download.html

**Comment by jarreds** [comment]
@eed3si9n Thank you. Shall we have automated build tools download it from here as well?

**Comment by eed3si9n** [comment]
Yes. We plan to use `https://cocl.us/sbt-x.y.z.tgz`.

**Comment by MPV** [comment]
@eed3si9n: This change seems to break the asdf (global version manager) plugin for SBT: https://github.com/lerencao/asdf-sbt

It uses BinTray to list the available releases, and for installing `sbt`:
https://github.com/lerencao/asdf-sbt/blob/master/bin/list-all
