### ISSUE TITLE
javac options cannot be blindly passed to javadoc

### ISSUE THREAD

**Issue by paulp** [sbt/sbt#355]
This currently prevents the scala trunk build from succeeding.  javadoc doesn't take the same options javac does.  Is this configurable somewhere? I couldn't find it.  It seems to be new to 0.11.3-SNAPSHOT, 0.11.2 doesn't fail, but of course I can't build trunk with 0.11.2 so this presently prevents the scala build from completing.

```
% cat build.sbt 
javacOptions ++= Seq("-source", "1.5", "target", "1.5")

% sbt publish-local
[error] javadoc: error - invalid flag: -target
[error] usage: javadoc [options] [packagenames] [sourcefiles] [@files]
[error] -overview <file>          Read overview documentation from HTML file
[error] -public                   Show only public classes and members
[error] -protected                Show protected/public classes and members (default)
```

**Comment by indrajitr** [comment]
This would be like scaladoc options in fact. So specifying additional axes should work:

```
javacOptions in (Compile, doc) = Seq("-source", "1.5")
```

**Comment by paulp** [comment]
Thank you; this did not work for me, but it may just be because I don't know exactly where I'm supposed to change it.  I settled for disabling documentation generation completely, which meets my personal needs but probably doesn't scale worldwide.  Stepping back: perhaps I'm naive but I take the position that an option called "javacOptions" should not be breaking the build by passing the "javac options" to a program which is not javac and which does not accept the javac options.  (I'm not suggesting anyone is saying otherwise, but just in case.)

**Comment by vigdorchik** [comment]
This is indeed confusing. The following worked for me however:

<code>
javacOptions  ++= Seq("-source", "1.5", "-target", "1.5"),
javacOptions in doc := Seq("-source", "1.5")
</code>

**Comment by indrajitr** [comment]
The confusion I think has few sources:
- `Compile` is an `sbt.Configuration` and thus belongs to configuration axis (Ivy has this predefined)
- `compile`, `doc` etc. are `sbt.TaskKey`s and thus belong to the task axes (note the subtle difference in case)
- `scalacOptions`, `javacOptions` are `sbt.Setting`s that capture CLI options for the corresponding compiler interface (which cover both scalac and scaladoc -- likewise for java). This point is a dangerous attempt at reading into the mind of @harrah :)

So my settings would look somewhat like this:

``` scala
lazy val myProjectSettings: Seq[Setting[_]] = Seq(
  // ...
  // Scala compiler interface settings
  scalacOptions ++= DefaultOptions.scalac,  // the obvious, globally relevant stuff
  scalacOptions in (Compile) += Opts.compile.deprecation,  // all stuff that are good for Compile config
  scalacOptions in (Compile, compile) ++= ...  // additional stuff that are good for Compile config and compile task
  scalacOptions in (Compile, doc) <++= (name in (Compile,doc), version in (Compile,doc)) map DefaultOptions.scaladoc, // additional stuff that are good for Compile config and doc task

  // Java compiler interface settings
  javacOptions ++= DefaultOptions.javac,  // the obvious, globally relevant stuff
  javacOptions in (Compile) += Opts.compile.deprecation,  // all stuff that are good for Compile config
  javacOptions in (Compile, compile) ++= ...  // additional stuff that are good for Compile config and compile task
  javacOptions in (Compile, doc) ++= ...  // additional stuff that are good for Compile config and doc task
)
```

Obviously, `scalacOptions` is not the point of discussion here. The reason I brought them here is because they are very similar settings wise. Further, I might not really need to go this granular in simpler cases.

Overall, I cannot deny that this took me a while to wrap my head around this -- till I realized `scalacOptions` has more to do with the interface (and thus relates to both `compile` and `doc`). With that settled, `javacOptions` worked out likewise.

A different name for `scalacOptions` (and `javacOptions`) might be a way out -- just wondering aloud.

**Comment by harrah** [comment]
@indrajitr has it right about targeting a compiler interface.  Either you have the doc options take the compiler options by default or you duplicate them.  It will be surprising in either case.  If you enable -Ysomeoption for the compiler, you will have to enable it for doc as well or it will fail.  I don't care if this isn't the default, but I would prefer using the mailing list for discussions.  Most people don't read bug report discussions.

**Comment by greenrd** [comment]
This is a documentation issue and should be reopened. The documentation says:

> Pass options to the Java compiler by setting javac-options:
> 
> ``` scala
> javacOptions += "-g:none"
> ```

This is wrong!

**Comment by jsuereth** [comment]
Good catch. Patches more than welcome: https://github.com/sbt/sbt/blob/0.13/src/sphinx/Detailed-Topics/Java-Sources.rst

The documentation isn't wrong necessarily, but it should definitely use a more specific `javacOption in (Compile, compile)` as well as describe how sbt tries to share options between javadoc + java similarly to how it shares options between scaladoc + scalac.

**Comment by fommil** [comment]
argh, just been bitten by this in a multi-module project where the lowest level project is pure Java. Any ideas for a workaround?

**Comment by fommil** [comment]
play seem to workaround it this way but when I try this the `-target 1.6` is still being passed to my java module's javadoc stage https://github.com/playframework/playframework/blob/master/framework/project/Build.scala

**Comment by fommil** [comment]
got it working, i applied the source and target to both case versions of compile and now it works. bizarre.

**Comment by indrajitr** [comment]
What exactly were you trying? Mind putting the snippet?

**Comment by fommil** [comment]
``` scala
    ...
    scalacOptions in Compile ++= Seq(
      "-encoding", "UTF-8", "-target:jvm-1.6", "-Xfatal-warnings",
      "-language:postfixOps", "-language:implicitConversions"),
    javacOptions in (Compile, compile) ++= Seq("-source", "1.6", "-target", "1.6", "-Xlint:all", "-Xlint:-options", "-Werror"),
    javacOptions in (Compile, compile) ++= Seq("-source", "1.6"),
    ...
```

**Comment by fommil** [comment]
oh, crap! I just realised I made a typo :-P  that should have been

``` scala
    javacOptions in (Compile, compile) ++= Seq("-source", "1.6", "-target", "1.6", "-Xlint:all", "-Xlint:-options", "-Werror"),
    javacOptions in (doc) ++= Seq("-source", "1.6"),
```

which does work, thankfully!

**Comment by indrajitr** [comment]
See https://github.com/sbt/sbt/issues/355#issuecomment-3817629 for specificity rule :)

You might pull up the common options by just doing the following and be done with it:

``` scala
    javacOptions in (Compile) ++= Seq("-source", "1.6"),
    javacOptions in (Compile, compile) ++= Seq("-target", "1.6", "-Xlint:all", "-Xlint:-options", "-Werror"),
```

Feel free to take up additional inputs or suggestions in sbt-dev.
