### ISSUE TITLE
`sbt -debug` should set the logLevel to Debug

### ISSUE THREAD

**Issue by jvican** [sbt/sbt#3555]
## problem
`sbt -debug` used to show information logged by `timed` et al. Now, it doesn't show anything.

## expectation
`sbt -debug` should behave like any 0.13 build, where debug logs are displayed.

## notes
I think this is a bug, but I'm not sure.

sbt version: 1.x

**Comment by jvican** [comment]
It shows only debug logs from resolution, but not from all the load, as before.

**Comment by eed3si9n** [comment]
This is a bug in bash script (https://github.com/sbt/sbt-launcher-package). The launcher scripts are likely consuming `-debug` and they don't pass `-debug` to sbt JAR.

**Comment by adamkasztenny** [comment]
Hasn't this been done in https://github.com/sbt/sbt-launcher-package/commit/8727faa8b37066c7570457931854195d285675c0#diff-edd0ab5838b2fa424d30f94df800e1f9?

**Comment by eed3si9n** [comment]
Yes. Looks like I fixed it in https://github.com/sbt/sbt-launcher-package/pull/226
