### ISSUE TITLE
SBT uses sun.misc.Signal, breaking usability on other JVMs!

### ISSUE THREAD

**Issue by markehammons** [sbt/sbt#3557]
[OpenJ9](https://github.com/eclipse/openj9) has been released, and I've been testing it. Unfortunately, I discovered it will not work with SBT because SBT [is using sun.misc.Signal](https://github.com/eclipse/openj9/issues/40). 

So far, this problem has only bitten me when using SBT in interactive mode. SBT in batch mode compiles and works fine.

I could write an implementation of Signal and SignalHandler for SBT using JNA (or JNI if JNA has the same problem) to make SBT more cross JVM if you guys are interested....

sbt version: 0.13 to present (probably older too)

**Comment by eed3si9n** [comment]
I think that would be cool if we can support OpenJ9.

**Comment by markehammons** [comment]
Right now, sbt seems to work for the most part aside from the interactive shell and (probably) the console mode. I'll go ahead and write a simple JNA binding to the posix signals that mimics sun.misc.Signal and do a merge request for a version of SBT that uses and depends on that.

**Comment by eed3si9n** [comment]
Would using JNA support Linux, Mac, and Windows?

**Comment by markehammons** [comment]
I'll have to look into it. It should work for linux and mac, but windows is a big question mark for me. I'll also look and see if there's any already existing sun.misc.Signal replacement that I could make a shim for that sbt could use in the meantime

**Comment by markehammons** [comment]
I don't see that there's a good signal handling lib for java aside from sun.misc.Signal

however, it doesn't look like it will be hard to replace sun.misc.Signal. JNA can bind against the c signal library, which windows has, and mac osx being posix compatible definitely has. sigcont is not one of the supported signals for windows according to the documentation [here](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/signal), but apparently neither sbt nor jline actually relies on sigcont for windows users. in any case, JNA would be able to bind against it in a cross platform manner without introducing any windows/linux/mac osx specific compilation like JNI.

In any case, I'll make the JNA binding to signal.h and see what happens when i drop it into place in SBT. I assume it won't work because it looks like jline also calls sigcont on its own, and I'll probably need to contact their maintainer and get this integrated should they be willing to make that change.

**Comment by markehammons** [comment]
It's been a while since I responded to this, but the jnr-ffi project has a signal library. It can be used in place of sun.misc.Signal: https://github.com/jnr/jnr-posix

Here's a link to an example of using jnr-ffi for signals handling: https://github.com/jnr/jnr-posix/blob/master/src/test/java/jnr/posix/SignalTest.java

**Comment by dwijnand** [comment]
note that OpenJ9 have resolved https://github.com/eclipse/openj9/issues/40, which means that interactive sbt usage should now work.

**Comment by dwijnand** [comment]
note the fix is in Eclipse OpenJ9 v0.8.0
