### ISSUE TITLE
Consider using ParallelGC on Java 9 to avoid severe performance regression

### ISSUE THREAD

**Issue by smarter** [sbt/sbt#3559]
Java 9 switched the default garbage-collector algorithm to G1GC which optimizes for low-latency at the expense of high-throughput, this is especially visible for Scala compilation. @retronym reports slowdowns of 30% for Scala 2.11.8 and 10% for Scala 2.12.3 (tested by enabling G1GC with Java 8). I've observed a 20% slowdown for Dotty when using Java 9, see discussion at https://gitter.im/scala/compiler-benchmark?at=59c05780bc464729744e667e.

There's an easy way to get back to the level of performance we had before: run with `-XX:+UseParallelGC`, this was the default GC in Java 8 and is still supported in Java 9.

**Comment by dwijnand** [comment]
I'm assuming that the proposed action is to tweak the scripts in https://github.com/sbt/sbt-launcher-package. Please let me know if you were thinking of other (or more) actions.

**Comment by smarter** [comment]
> I'm assuming that the proposed action is to tweak the scripts in https://github.com/sbt/sbt-launcher-package. 

Pretty much yes, are the options passed to the launcher script also propagated to the forked JVMs?

**Comment by eed3si9n** [comment]
> Pretty much yes, are the options passed to the launcher script also propagated to the forked JVMs?

I don't think they are.

https://github.com/sbt/sbt/blob/v1.0.2/main/src/main/scala/sbt/Defaults.scala#L154

```
      javaOptions :== Nil,
```

**Comment by dwijnand** [comment]
> are the options passed to the launcher script also propagated to the forked JVMs?

No that's why we merged https://github.com/sbt/sbt/pull/2103

**Comment by jrudolph** [comment]
To offer a counter-point: I've been running sbt with G1 for a long while even if it is a bit slower because it seems to release unused classes more reliably than other GC (i.e. favoring long running sbt sessions). I also run with quite big heaps, so GC might be less of an issue.

**Comment by dwijnand** [comment]
This shipped in 1.0.3

**Comment by eed3si9n** [comment]
@smarter @retronym Does this still hold true today?
Given some of the memory hogging behavior of sbt, I'd want to give G1GC another shot.

**Comment by smarter** [comment]
G1GC is supposed to be better under Java 11, but I haven't run any benchmark to confirm this.

**Comment by eed3si9n** [comment]
[FYI: Changes to Garbage Collection in JDK11](http://mail.openjdk.java.net/pipermail/hotspot-gc-use/2018-June/002759.html)
