### ISSUE TITLE
abiVersion 

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3562]
This is a proposal to consider a new `Option[String]` setting called `abiVersion`.

This is intended to track the ABI compatibility. For example, a Scala library with two-segment versioning (epoch.major.minor) will set this to `Some("2.4")`, whereas a library adopting Semantic Versioning will set to `Some("2")`.

This also allows partial adoption of Semantic Versioning, like in the case of Akka where 2.x artifacts are binary compatible where `x >= 3`. In this case, they might set the `abiVersion` to `Some("2.3")`.

When evaluating eviction warning, `Some(x)` and `Some(y)` are evaluated as `String` equality. When `None` is mixed in, it will infer either the SemVer or the two-segment versioning.

**Comment by sjrd** [comment]
That looks *perfect*!

What happens exactly during the transition, i.e., if I have a `None` in an old version, say 2.4.1 (because the mechanism did not exist yet when it was published) and a `Some("2")` in the new version 2.5.0?

**Comment by eed3si9n** [comment]
@sjrd 

We can use [`VersionNumber`](https://github.com/sbt/librarymanagement/blob/v1.0.0/core/src/main/scala/sbt/librarymanagement/VersionNumber.scala) to parse the available `abiVersion`, in this case `Some("2")`.

Since it has one segment, we will infer that it only cares about the first segment, and parse `version` without abiVersions using `VersionNumber` and infer abiVersion to be `"2"` as well.

A more trickier example would be if we have a `None` with `version` set to `2.0.0-RC1`. In this case, inference needs to be smart enough to say that the abiVersion is `2.0.0-RC1`, not compatible with `Some("2")` series.

**Comment by sjrd** [comment]
That sounds reasonable.

**Comment by ktoso** [comment]
This sounds good; 
I'm a bit confused why Akka would set it to 3...?

2.5.x is backwards compatible with 2.4.x, is backwards compatible to 2.3.x even
doc.akka.io/docs/akka/current/scala/common/binary-compatibility-rules.html

**Comment by ktoso** [comment]
How would we set these rules for external libraries, that are published as plain java but we "know about them"? This is more useful for projects with lager dependency graphs, like Play for example, though would be good to think about here too

**Comment by eed3si9n** [comment]
@ktoso 

> I'm a bit confused why Akka would set it to 3...?

My suggestion was that Akka sets it to  `Some("2.3")` during the 2.x series.

> How would we set these rules for external libraries, that are published as plain java but we "know about them"?

These are used during eviction warning, so if we need special handling, we could tweak things there, or make it more extensible.

**Comment by ktoso** [comment]
> My suggestion was that Akka sets it to Some("2.3") during the 2.x series.

I see; so sbt would just equality check between the artifacts, and they'd all have the same "compatible with" ABI marker... Could work yeah

> These are used during eviction warning, so if we need special handling, we could tweak things there, or make it more extensible.

Yeah, for Play and similar "many dependencies" projects, they have plugins, so it may be fine to just allow adding to the list by artifact name and what the ABI is

**Comment by nafg** [comment]
Where would the setting go and how would it work? Some kind of extra metadata in artifacts on maven?

**Comment by eed3si9n** [comment]
@nafg Yes, I was envisioning something like apiURL that sbt injects in POM:

https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.6/scala-library-2.12.6.pom

```xml
<properties>
  <info.apiURL>http://www.scala-lang.org/api/2.12.6/</info.apiURL>
</properties>
```

Assuming that we can recover that information back during or after resolution, we can affect the eviction warning etc.

**Comment by nafg** [comment]
As long as it doesn't have to affect resolution, I guess you have a lot of options

**Comment by julienrf** [comment]
Should we close this issue now that `versionScheme` solves the same problem?

**Comment by eed3si9n** [comment]
I think so.
