### ISSUE TITLE
Eval statement fails when using SBT to test plugins

### ISSUE THREAD

**Issue by davidmweber** [sbt/sbt#3563]
## steps
Built a test script for a sbt plugin (http://www.scala-sbt.org/1.0/docs/Testing-sbt-plugins.html#step+4%3A+write+a+script). Use the `eval` statement in that script:

```
> eval System.setProperty("a.b.c", "d")
```

Now run the script using `scripted` from the sbt command line

## problem
Sbt crashes with the following message and partial trace:

```
[error] <eval>:1: error: not found: value d
[error] System.setProperty("a.b.c", d )
[error]                             ^
[info] [error] sbt.compiler.EvalException: Type error in expression
[info] [error] 	at sbt.compiler.Eval.checkError(Eval.scala:425)
[info] [error] 	at sbt.compiler.Eval.compileAndLoad(Eval.scala:213)
[info] [error] 	at sbt.compiler.Eval.evalCommon(Eval.scala:179)
[info] [error] 	at sbt.compiler.Eval.eval(Eval.scala:112)
```

## expectation

The `eval` statement correctly sets the `a.b.c` property to `d`

## notes

sbt version: 1.0.2

**Comment by davidmweber** [comment]
`'eval System.setProperty("a.b.c", "d")'` does the job

**Comment by dwijnand** [comment]
What a weird bug..
