### ISSUE TITLE
test-only runs all tests in all projects if invoked directly from the command line

### ISSUE THREAD

**Issue by randomcoder** [sbt/sbt#357]
If I run `sbt test-only *SingleTestSuite` from the command line with a multi module project, then sbt actually runs **all** the tests in **all** the projects.

Running `sbt` and then `test-only *SingleTestSuite` results in the expected behaviour, i.e. sbt searches all sub projects for tests that match the given pattern.

**Comment by harrah** [comment]
Please use the mailing list for questions.  https://github.com/harrah/xsbt/wiki/FAQ

**Comment by randomcoder** [comment]
I didn't mean to ask a question. Is this not a bug then?

**Comment by bytbox** [comment]
@randomcoder `sbt "test-only *SingleTestSuite"` gives the expected behaviour - the first command-line argument to sbt is interpreted as the entire line entered into sbt's console - future arguments are ignored.
