### ISSUE TITLE
sbt 1.0.2 reads HeapDumpOnOutOfMemoryError option from .sbtopts incorrectly

### ISSUE THREAD

**Issue by hoff2** [sbt/sbt#3571]
Exits with the following error:
```
~/dev/mobile-data-services(delete-jwt) $ sbt
Unrecognized VM option 'HeapDumpOnOutOfMemoryErro'
Did you mean '(+/-)HeapDumpOnOutOfMemoryError'?
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
To get sbt to run, one must either remove this option, or, curiously, add an extra `r` to the end of the option name so that it reads `HeapDumpOnOutOfMemoryErrorr` (this doesn't work with just any character, it must be an `r`)

## steps
1. Have a HeapDumpOnOutOfMemoryError option set in the project directory's `.sbtopts` file
2. try to run sbt

## problem
The above described error

## expectation
expected SBT to run normally

## notes

sbt version: 1.0.2

**Comment by eed3si9n** [comment]
I think this is now fixed by https://github.com/sbt/sbt-launcher-package/pull/187
