### ISSUE TITLE
conda-forge package for sbt

### ISSUE THREAD

**Issue by abhi18av** [sbt/sbt#3574]
Hi guys,

I've been working on the [`conda-forge`](https://conda-forge.org/) package for `sbt` in this [PR](https://github.com/conda-forge/staged-recipes/pull/4037) 

I'm running into issues, could you help me get `sbt` into the `conda` management space ?

**Comment by eed3si9n** [comment]
Travis says:

> RuntimeError: SHA256 mismatch: 'c3f063d8122d87f0d80b25221d76b0a164e9247d35190f31ec360edcb4352ef0' != '48b78793b824b6ca641d56b525052986c26b53f7f78c2b2e70191f923041b687'

**Comment by abhi18av** [comment]
@eed3si9n , yup thanks :)

I've corrected that one ( this is always the first issue ) but now the real story begins. 

Travis gave a more sophisticated error log now

```sh

RuntimeError: Can't build {'undefined_jinja_vars': [], 'config': <conda_build.config.Config object at 0x111b63e80>, 'meta_path': '/Users/travis/build/conda-forge/staged-recipes/recipes/sbt-scala/meta.yaml', 'path': '/Users/travis/build/conda-forge/staged-recipes/recipes/sbt-scala', 'requirements_path': '/Users/travis/build/conda-forge/staged-recipes/recipes/sbt-scala/requirements.txt', 'meta': {'package': {'name': 'sbt-scala'}, 'source': {'url': 'https://github.com/sbt/sbt/releases/download/v1.0.2/sbt-1.0.2.tgz', 'sha256': 'c3f063d8122d87f0d80b25221d76b0a164e9247d35190f31ec360edcb4352ef0'}, 'build': {'number': '0'}, 'requirements': {'run': ['java']}, 'test': {'commands': ['sbt -help']}, 'about': {'home': 'https://github.com/sbt/sbt', 'license': 'OTHER', 'license_family': 'OTHER', 'summary': 'sbt, the interactive build tool ', 'description': 'sbt, the interactive build tool\n', 'doc_url': 'http://scala-sbt.org/', 'dev_url': 'https://github.com/sbt/sbt'}, 'extra': {'recipe-maintainers': ['abhi18av'], 'final': True}}} due to environment creation error:

  - sbt-scala  0

  - java

```
This can be found at https://travis-ci.org/conda-forge/staged-recipes/builds/279145162?utm_source=github_status&utm_medium=notification

Which is a bit cryptic to me.

**Comment by eed3si9n** [comment]
I am not really familiar with what conda is, and I don't know if these are specifically sbt issues.

**Comment by abhi18av** [comment]
Well, let me try to explain why it's relevant.

`Scala` is often used in `Data Science` and so is `Python` , `Julia` and `R`. So, instead of treating each language as an island there's a language-agnostic and platform-agnostic package manager called [`conda`](https://conda.io/docs/) which is an initiative from [`Anaconda`](https://www.anaconda.com/what-is-anaconda/).

Think of `brew` but completely cross platform and it creates isolated environments for installed software which can't interfere with each other.

The main advantage is that it's result of push towards reproducible research and analysis. I think that `scala` community would greatly benefit from `conda`. `conda-forge`, like `bio-conda` is an entirely community driven effort towards this goal.

@eed3si9n  Please re-consider your decision about closing this issue.

**Comment by eed3si9n** [comment]
We use GitHub issue mostly to track bugs and discuss feature or bugs on sbt.
If you need help, please check this out - http://www.scala-sbt.org/community.html#how-can-I-get-help

**Comment by abhi18av** [comment]
Okay 👍
