### ISSUE TITLE
Add a "-nobootcp" option to run task

### ISSUE THREAD

**Issue by djspiewak** [sbt/sbt#358]
When the run task forks, it uses `ForkJava` or `ForkScala`.  Unfortunately, when `ForkScala` is used, the Scala libraries are put onto the boot classpath and there is _no_ way to change this (see https://github.com/harrah/xsbt/blob/0.12/run/Fork.scala#L89).  This is a problem in situations where changing the boot classpath disrupts functionality in the application (some JNI-backed libraries have this issue).

It is for precisely this reason that the `scala` command has a `-nobootcp` option to disable this behavior.  SBT should provide the same functionality.  At present, the only recourse is to override the `run` task altogether, forcing it to use `ForkJava` for all classes.

**Comment by krasserm** [comment]
+1 on this. For all who are interested, a concrete workaround example is [here](https://github.com/eligosource/eventsourced/wiki/Installation#wiki-native).

**Comment by harrah** [comment]
As of 0.13.0, sbt uses `java` for all classes and does not put the Scala libraries onto the boot classpath by default.

**Comment by vr2013** [comment]
Hi guys,
I installed the most recent play activator (1.2.10) and I am getting this error while running my test app.
java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no leveldbjni6
4-1.7 in java.library.path, no leveldbjni-1.7 in java.library.path, no leveldbjn
i in java.library.path, C:\Users\myuser\AppData\Local\Temp\leveldbjni-6
4-1-4954089879853047029.7: Can't find dependent libraries]
Does this issue still exist? the sbt 0.13.5 was used.
