### ISSUE TITLE
Zinc sometimes doesn't invalidate files where trait definitions are inherited

### ISSUE THREAD

**Issue by djspiewak** [sbt/sbt#3586]
Ok, I don't have a nice and minimal test case for you guys, unfortunately, but I do have a reproducer.  It seems like this issue is broadly related to the cake pattern, which is used heavily in some older parts of the quasar codebase (sadface…).  Changing upstream functions (in inherited traits) will cause some downstream compilation units to explode at runtime with `AbstractMethodError` due to Zinc improperly believing the files in question did not need to be invalidated.

This happens intermittently in local development (my steps below point to a changeset which will reproduce the issue) and 100% deterministically in CI.  The reason it is happening deterministically in CI is because we cache our target directories for PR builds in Travis (as discussed with @jvican) in order to bring down our horrendously-long compilation times.  This worked almost flawlessly with SBT 0.13.x for the last eight months (we only needed to cache flush twice), which is quite impressive!  However, on SBT 1.0, we can't even get a single PR build to work, as the slower matrix builds will get the new caches from the faster builds, and themselves run into mutual-invalidation issues.  This is kind of an edge case, but it does demonstrate how much less reliable current Zinc is from its state in 0.13.

## steps

1. Clone [my fork of quasar](https://github.com/djspiewak/quasar)
2. Check out commit `a6b7a91010faf8d06ef678653db53bafdaceaa5e`
3. Run `sbt test:compile`
4. Check out commit `66c97fd9ed3e36eec1a058e5b9a546c80ab6309b`
5. Run `sbt mimir/test`

## notes

sbt version: 1.0.2

**Comment by djspiewak** [comment]
Oh another tidbit that might be relevant: we are using typelevel Scala 2.11.8.  This particular code isn't touching any TLS features, but it is that compiler which is in play.

**Comment by jvican** [comment]
Ok, this is concerning. Will be leading with this as soon as I'm done with the 2.12.4 release.
  
Thanks for opening this issue @djspiewak, can you please move this discussion to sbt/zinc?

**Comment by djspiewak** [comment]
Would you like a new issue on sbt/zinc?

**Comment by jvican** [comment]
Yes, that would be ideal. We barely use this repo for zinc bug reports.

**Comment by djspiewak** [comment]
Closing in favor of https://github.com/sbt/zinc/issues/417

**Comment by eed3si9n** [comment]
Re-opening this to track on sbt/sbt's milestone. Any discussions should continue on sbt/zinc#417.

**Comment by shonzilla** [comment]
@eed3si9n When should [sbt 1.0.3](https://github.com/sbt/sbt/milestone/32) be released?

AFAICT all currently open issues (this one, #3569 and #3573) were left open for tracking purposes by referring to issues in other repositories (sbt/zinc#417 / sbt/zinc#424, sbt/librarymanagement#169 and  sbt/librarymanagement#170) that have been resolved and merged upstream.

Could it be that the downstream projects ([sbt/zinc 1.0.3](https://github.com/sbt/zinc/milestone/7) and [sbt/librarymanagement 1.0.3](https://github.com/sbt/librarymanagement/tree/1.0.x)) need to be released first before releasing sbt 1.0.3 itself?

**Comment by eed3si9n** [comment]
I am releasing it today.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/3674
