### ISSUE TITLE
upgrade to Scala 2.12.4 for improved Java 9 (JDK 9) compatibility

### ISSUE THREAD

**Issue by SethTisue** [sbt/sbt#3587]
2.12.4 isn't out yet, but it will be pretty soon. I think you'll want to upgrade to get https://github.com/scala/scala/pull/6097 which fixes https://github.com/scala/scala-dev/issues/304

**Comment by mkurz** [comment]
Scala 2.12.4 is released (but not announced yet). You can fetch it already.
