### ISSUE TITLE
An alternative to reboot full

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3590]
This for ease of hacking on sbt:

## steps

```
> reboot full
```

## problem

This wipes out the boot directory, so I'd avoid this.

## expectation

Provide:

```
> reboot dev
```

This deletes only the directory under boot that is relevant to the current -SNAPSHOT version.

**Comment by dwijnand** [comment]
SGTM! Just a clarification by "the current -SNAPSHOT version" I think we should read the value from `project/build.properties` (see https://github.com/sbt/sbt/issues/1055).
