### ISSUE TITLE
Consider adding JCenter to the list of default resolvers

### ISSUE THREAD

**Issue by laughedelic** [sbt/sbt#3594]
I remember that at some point JCenter was in the list of default resolvers, but I missed that it was removed and only recently discovered this:
- https://github.com/sbt/sbt/issues/2217
- https://github.com/sbt/sbt/pull/2335

I understand that there were some problems with making JCenter the new default resolver and replacing Maven Central, but I don't quite understand why it cannot be just another resolver in the default chain. Could it be added again (in addition to Maven Central) or it is unlikely for some technical reason?

Note, `useJCenter` setting is not a solution. I'd like to be able to publish to JCenter without forcing users to use `useJCenter := true` or `resolvers += Resolver.jcenterRepo`.

**Comment by eed3si9n** [comment]
To resolve dynamic revisions such as range and -SNAPSHOT correctly, it will need to traverse all resolvers, so each remote resolvers that we add by default will add a second of lookup (could be more if you're in Asia/Pacific/Africa), and when they become unreachable (due to capacity or outage) it fails the entire build. 

We added `useJCenter` to opt-in per build basis, so hopefully those who need it can use it, but not subject the entire community to performance and reliability issue.
http://www.scala-sbt.org/0.13/docs/sbt-0.13-Tech-Previews.html#sbt+0.13.11

**Comment by laughedelic** [comment]
Right, I didn't think about dynamic revisions 😒
Isn't it considered bad practice nowadays to use dynamic revisions? (especially overwritable snapshots)

**Comment by dwijnand** [comment]
I [discourage it](https://github.com/dwijnand/sbt-dynver) 😃

**Comment by laughedelic** [comment]
> I discourage it 😃

Also, [sbt-lock](https://github.com/tkawachi/sbt-lock) exists for a reason.

**Comment by jvican** [comment]
Yes, but sbt-lock does not solve the problem for SNAPSHOTs, only version ranges and "latest".

**Comment by francisdb** [comment]
Just a note on my 👎 
Maven central is run by an open organisation (Apache)
JCenter is run by a commercial company (JFrog)
It's not hard to set up a sync to maven central
As already mentioned above, less repos is better

**Comment by dwijnand** [comment]
Maven Central is run by Sonatype, Inc, not by the Apache Software Foundation.

**Comment by francisdb** [comment]
> Maven Central is run by Sonatype, Inc, not by the Apache Software Foundation.

Pretty sure it's owned by the Apache Software Foundation, management could indeed be subcontracted to Sonatype.
Sonatype oss is managed by Sonatype but they are merely a gatekeeper for maven central. (Apache projects don't even use it)

**Comment by dwijnand** [comment]
I can't find any reference to that. In http://takari.io/2015/10/28/google-maven-central.html it says it started at ASF, and as of late 2015 "everything is managed by Jason Swank, Joel Orlina and a few other members of Sonatype’s technical operations team". It's definitely not clear who "owns" Maven Central.

**Comment by brianf** [comment]
Sonatype has always provided Central and owns the maven.org domain. If you want to use a neutral dns, then repo.maven.apache.org/maven2 is what you want. This is currently a cname to repo1.maven.org but is there to maintain neutrality in the Maven code.

**Comment by dwijnand** [comment]
Oh interesting.

**Comment by francisdb** [comment]
Thanks for the clarification @brianf. Do I understand it correctly Sonatype could just discontinue maven central if it wanted?

**Comment by brianf** [comment]
We've been providing Central for over 10 years as a corporation and Jason personally funded it for several years prior to that. Simply dropping it and walking away would be tantamount to commercial suicide. Given it's prominence in the community, I think it's fair to say this is far less likely to happen to Central, the canonical repository than to other commercial proxies around it.

Separately, we work with the Maven PMC (of which I am also a member) to ensure that there are sufficient protections for the community. The previously mentioned DNS is one, the extra copy at Google is another.

**Comment by brianf** [comment]
As a follow up, anyone here interested in the history of Central, I was recently on a podcast describing it. https://manifest.fm/6

**Comment by eed3si9n** [comment]
@brianf On behalf of Scala community, I just wanted to say thanks to you and Sonatype for all the work and funding on Maven Central.

As per this issue, I think we can safely close this as wontfix.
