### ISSUE TITLE
`-sbt-dir` option is not respected for the `preloaded` directory

### ISSUE THREAD

**Issue by ayekat** [sbt/sbt#3598]
## steps

1. Run `sbt -sbt-dir /path/to/some/directory`
2. Notice `~/.sbt` being created

## problem

The `boot` and `staging` directories are correctly created under `/path/to/some/directory`, but the `preloaded` directory ends up in `~/.sbt`.

## expectation

Running with `-sbt-dir ...`, I expect *all* files that would normally show up in `~/.sbt` to be stored in the specified directory instead.

## notes

sbt version: 1.0.2 on Arch Linux

**Comment by dwijnand** [comment]
`-sbt-dir` sets the system property `sbt.global.base` which isn't be honoured.

**Comment by ayekat** [comment]
I will dare referencing #3681 here, as I actually only use `-sbt-dir` as a workaround for the non-compliance with the XDG base directory specification on Linux.

I have a wrapper script for sbt to set `-sbt-dir "$XDG_DATA_HOME/sbt"`, to fight the clutter of "dotfiles" in my home directory—hence my slightly allergic reaction when I suddenly encountered `~/.sbt` :smile:.

**Comment by wrighton** [comment]
I think the problem is right here:

bin/sbt-launch-lib.bash

```
syncPreloaded() {
  if [[ "$init_sbt_version" == "" ]]; then
    # FIXME: better $init_sbt_version detection
    init_sbt_version="$(ls -1 "$sbt_home/lib/local-preloaded/org.scala-sbt/sbt/")"
  fi
  [[ -f "$HOME/.sbt/preloaded/org.scala-sbt/sbt/$init_sbt_version/jars/sbt.jar" ]] || {
    # lib/local-preloaded exists (This is optional)
    [[ -d "$sbt_home/lib/local-preloaded/" ]] && {
      command -v rsync >/dev/null 2>&1 && {
        mkdir -p "$HOME/.sbt/preloaded"
        rsync -a --ignore-existing "$sbt_home/lib/local-preloaded/" "$HOME/.sbt/preloaded"
      }
    }
  }
}

```

That is an odd bit of scripting there, IMO.

**Comment by wrighton** [comment]
I found that this fix did not work for me, with bash 3 (which is the default where I work). Changing to Bash4 solved it. If this can be reproduced, maybe should do some sort of version check on bash.
