### ISSUE TITLE
Forking tests does not seem to work

### ISSUE THREAD

**Issue by asflierl** [sbt/sbt#36]
Hi,

using the following settings in sbt 0.10:

fork in run := true

javaOptions in run += "-Xblabla"

when I type "test", the tests run, but they should not. Instead, the forked VM should complain like "Unrecognized option: -Xblabla" and "Could not create the Java virtual machine.".  It works as expected for "run".

I am using specs2 to run the tests, so I am not sure whether this is a specs2 or an sbt issue. (Or maybe it's not an issue at all and I'm doing something wrong?)

**Comment by harrah** [comment]
https://github.com/harrah/xsbt/wiki/Forking

When you say `fork in run`, you are configuring the `run` task.  Regardless, sbt doesn't support forking tests.  If there is some documentation that led you to believe otherwise, we can try to make it more clear.

**Comment by ijuma** [comment]
It's also worth noting that being able to fork tests is a desired feature and mentioned here:

https://github.com/harrah/xsbt/wiki/Opportunities

**Comment by asflierl** [comment]
I read this wiki page:
https://github.com/harrah/xsbt/wiki/Forking
which says
"To enable forking all run-like methods (run, run-main, test:run, and test:run-main), set fork to true.
fork in run := true
To only fork test:run and test:run-main:
fork in (Test,run) := true"
which is what led me to believe that tests can run forked. Sorry if I misunderstood that.

**Edit:** I guess what I wanted to say was: It is not immediately obvious that "(Test, run)" does not mean "test" but "test:run" (at least at the moment I think it means that).
