### ISSUE TITLE
Runtime reflection of classes in the empty package broken under JDK 9

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3614]
Originally tracked in https://github.com/scala/scala-dev/issues/304

## steps

1. Declare auto plugins without package names.
2. Run the build on JDK 9.

## problem

I am guessing you'd get:

```
java.lang.AssertionError: assertion failed: no symbol could be loaded from class X in package with name X and classloader java.net.URLClassLoader@199806aa
```

## expectation

It works.

**Comment by dwijnand** [comment]
Duplicate of #3587.
