### ISSUE TITLE
sbt launcher still looks in repositories not mentioned in sbt.boot.properties

### ISSUE THREAD

**Issue by greenrd** [sbt/sbt#362]
```
sbt @/etc/sbt/sbt.boot.properties
```

ignores the fact that I've only specified local and a couple of internal repositories under [repositories]. So it shouldn't be going outside the local network, but it is, even for downloading sbt itself. So I don't know any way to stop sbt from trying to go outside the network (other than custom firewall rules in the OS, but that's a bit of a hack).

**Comment by greenrd** [comment]
BTW, in case it matters, I'm using a self-built .deb package from https://github.com/sbt/sbt-launcher-package to launch sbt.

**Comment by harrah** [comment]
Please use the mailing list for questions.  https://github.com/harrah/xsbt/wiki/FAQ
