### ISSUE TITLE
www.scala-sbt.org should use HTTPS

### ISSUE THREAD

**Issue by PetrGlad** [sbt/sbt#3628]
Site www.scala-sbt.org uses plain HTTP. The site hosts links and download instructions which poses a security risk as these instructions/links can be altered by an attacker.
There are already services that provide free HTTPS certificates (e.g. https://letsencrypt.org/) so providing HTTPS is much easier now.

The site should use HTTPS, optionally with [Strict transport security](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) header.

**Comment by dwijnand** [comment]
Duplicate of https://github.com/sbt/website/issues/275.
