### ISSUE TITLE
Warn if same name is used for different resolvers

### ISSUE THREAD

**Issue by dacr** [sbt/sbt#363]
Consider this build.sbt fragment, where the same name "JAnalyse Repository" is used both for lib and sftp resolvers : 

resolvers += "JAnalyse Repository" at "http://www.janalyse.fr/repository/"

publishTo := Some(
     Resolver.sftp(
         "JAnalyse Repository",
         "www.janalyse.fr",
         "/home/xxxxxxx/repository"
     ) as("yyyyy", new File(util.Properties.userHome+"/.ssh/id_rsa"))
)

sbt will try to publish using http put request instead of using the configured SFTP resolver definition.

This is quite annoying when the project has dependencies from the same repository it want to publish to. The work around is use different names for the same repository, although the same URL is used.

**Comment by harrah** [comment]
Using different names is not a workaround, but is a requirement.  This bug is to warn when the same name is used for different repositories.

**Comment by dacr** [comment]
let's rather say that it is a workaround only for the case where this is the same repository  used for both dependencies and publishing destination.

**Comment by harrah** [comment]
Although the repository is physically the same, the access mechanism is not.  One uses sftp and one uses http.

**Comment by dacr** [comment]
Warn message would be great and enough. It'll avoid anyone who first encounter this problem, to wonder what's going on. 
Thanks.

**Comment by harrah** [comment]
Fixed by pull request #367
