### ISSUE TITLE
file watching stops after changing javascript on windows 10

### ISSUE THREAD

**Issue by Enalmada** [sbt/sbt#3630]
After upgrading sbt from 0.13.16 to 1.0.2 on my windows 10 machine, the compiler stops detecting any kind of changes after I change a javascript file.  Works fine when I go back to 0.13.16.  There are no errors in the console when the watching stops.

## steps
- fire up a windows 10 machine (i suspect this is relevant)
- sbt new playframework/play-scala-seed.g8
-  update project/build.properties to sbt.version=1.0.2
    (remove scaffold.sbt so it will compile with latest sbt)
-  run  (same problem confirmed also with ~run)
-  Add any valid javascript to the existing blank public/javascripts/main.js, for ex:
-    function testFunction() { return true; }
-  Refresh browser.  At this point silently crashes file watching.
- Make a change to index.scala.html and note that it no longer is detected for recompile on refresh.

sbt version: 1.0.2

**Comment by Enalmada** [comment]
Anyone else using windows able to confirm that file watching stops after js change?

**Comment by Enalmada** [comment]
Noting that another user has reported detecting change issues that may or may not be related:

> I can confirm that something is off with regards to detecting changes. In my case, any change to a Twirl template (*.scala.html) will not trigger reload.
> I am running on Linux (Ubuntu, with disk encryption)
> 
> The project is a vanilla project created off the template - the only thing I had to do to get the project to work was to manually replace a seed `maven()` value (that apparently did not get inlined) with SBT 1.0.2.
> 
> Manuel

https://groups.google.com/d/msg/play-framework/N1ozDOe5sU4/jKkSLhZ1AQAJ

**Comment by gmethvin** [comment]
@Enalmada I suspect this is a Play issue, not an sbt issue. Play uses its own file watcher. Can you try with the latest Play 2.6.7? If you still see problems open an issue here: https://github.com/playframework/playframework/issues

**Comment by Enalmada** [comment]
@gmethvin Good news...2.6.7 with sbt 1.0.2 does seem to be ok so far...limited testing but so far changing javascripts is no longer crashing file watching.   Thanks!
