### ISSUE TITLE
addSbtPlugin does not respect sbtVersion

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#3636]
when attempting to upgrade https://gitlab.com/fommil/sbt-sensible to sbt 1.0 I discovered that the cross build support does not work: no matter which `sbtVersion` I choose as the default, the *other* one always tries to resolve the wrong depednencies.

This is because my plugin depends on other plugins with `addSbtPlugin` and this method does not appear to respect the correct `sbtVersion`.

**Comment by fommil** [comment]
https://github.com/sbt/sbt/pull/3397

**Comment by dwijnand** [comment]
Fix should be available in 1.0.1.
