### ISSUE TITLE
addSbtPlugin  :  Not a valid command: assembly

### ISSUE THREAD

**Issue by ravi5237** [sbt/sbt#3641]
(See the guidelines for contributing, linked above)

## steps

```
D:\sbt>sbt assembly
"C:\Users\irk77_dp6hvo8\.sbt\preloaded\org.scala-sbt\sbt\"1.0.2"\jars\sbt.jar"
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[info] Loading settings from assembly.sbt ...
[info] Loading project definition from D:\sbt\project
[info] Updating {file:/D:/sbt/project/}sbt-build...
[info] Done updating.
[info] Loading settings from build.sbt ...
[info] Set current project to MovieSimilarities1M (in build file:/D:/sbt/)
[error] Not a valid command: assembly
[error] Not a valid project ID: assembly
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: assembly
[error] assembly
[error]         
```

## problem
When I try to run the "sbt assembly", I am getting the above exception... Please help

## notes
assembly.sbt
-------------
`addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.7.0")`

sbt version: *insert sbt version*
sbt.version=1.0.2

**Comment by EnverOsmanov** [comment]
@ravi5237  what is your expectation? Maybe you should add such plugin [sbt-assembly](https://github.com/sbt/sbt-assembly)

**Comment by dwijnand** [comment]
You're getting sbt-buildinfo and sbt-assembly mixed up. Try adding:

```scala
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.5")
```

**Comment by aklahoty** [comment]
after running sbt assembly command, how do I run the scala project..

The command to use is java -jar target/scala-2.10/lixr-assembly-0.1.jar Model.scala input.xml

What is definition.scala file here..

here is the snippet of Main.scala

package eu.liderproject.lixr

import com.twitter.util.Eval
import java.io.File

object Main {
  def loadModelFromFile(fileName : String) = Eval[Model](
    "import eu.liderproject.lixr._\n" + io.Source.fromFile(fileName).mkString)

  def main(_args : Array[String]) {
    var args = collection.mutable.Buffer(_args:_*)
    for(a <- args) {
      if(a.startsWith("-D")) {
        val Array(p, v) = a.drop(2).split("=")
        System.setProperty(p, v)
      }
    }
    args = args.filterNot(_.startsWith("-D"))
    if(args.length < 2) {
      System.err.println("Usage: java -jar lixr.jar <model> <file> params...")
      System.exit(-1)
    }
    val gen = new DOMGenerator()
    val model = try {
      loadModelFromFile(args(0))
    } catch {
      case x : Exception =>
        x.printStackTrace()
        System.err.println()
        System.err.println("Could not load %s as \"%s\"" format (args(0), 
          x.getMessage()))
        System.exit(-1)
        null
    }
    val in = new java.io.FileReader(args(1))
    val results = gen.read(in,model)
    
    for(result <- results) {
      result match {
        case t : TripleResult =>
          println(t.toString)
        case _ =>
      }
    }


  }
}
