### ISSUE TITLE
xception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/SparkContext

### ISSUE THREAD

**Issue by ravi5237** [sbt/sbt#3642]
(See the guidelines for contributing, linked above)

## steps

import org.apache.spark.SparkContext

import org.apache.spark.SparkContext._

import org.apache.spark.SparkConf

/** Count up how many of each star rating exists in the MovieLens 100K data set. */
object RatingsCounter {
 
  /** Our main function where the action happens */
  def main(args: Array[String]) {
   
    // Set the log level to only print errors
   // Logger.getLogger("org").setLevel(Level.ERROR)
        
    // Create a SparkContext using every core of the local machine, named RatingsCounter
    val sc = new SparkContext("local[*]", "RatingsCounter")
   
    // Load up each line of the ratings data into an RDD
    val lines = sc.textFile("D:/Data/source/ml-100k/u.data")
    
    // Convert each line to a string, split it out by tabs, and extract the third field.
    // (The file format is userID, movieID, rating, timestamp)
    val ratings = lines.map(x => x.toString().split("\t")(2))
    
    // Count up how many times each value (rating) occurs
    val results = ratings.countByValue()
    
    // Sort the resulting map of (rating, count) tuples
    val sortedResults = results.toSeq.sortBy(_._1)
    
    // Print each result on its own line.
    sortedResults.foreach(println)
  }
}

## problem

When running the program in Intellij ID, I am getting the below error

## expectation

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/SparkContext
	at RatingsCounter$.main(RatingsCounter.scala:19)
	at RatingsCounter.main(RatingsCounter.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.SparkContext
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more

Process finished with exit code 1

## notes

sbt version: *insert sbt version*
sbt.version = 0.13.15

**Comment by dwijnand** [comment]
This doesn't appear to have anything to do with sbt.
