### ISSUE TITLE
Use logback with slf4j in sbt custom tasks (override default dependencies for SBT tasks runtime)

### ISSUE THREAD

**Issue by fedefernandez** [sbt/sbt#3645]
## steps

Create a new SBT project

`project/build.properties`
```properties
sbt.version=1.0.2
```

`project/plugins.sbt`
```scala
libraryDependencies ++= Seq(
  "org.slf4j" % "slf4j-api" % "1.7.25",
  "ch.qos.logback" % "logback-classic" % "1.2.3"
)
excludeDependencies += "org.apache.logging.log4j" % "log4j-slf4j-impl"
// Also tried this:
// excludeDependencies += ExclusionRule("org.apache.logging.log4j", "log4j-slf4j-impl")
```

`build.sbt`
```scala
name:="Test SBT"

scalaVersion:="2.12.3"

lazy val myTestTask = TaskKey[Unit]("my-test-task")

myTestTask := {
  val logger = org.slf4j.LoggerFactory.getLogger("sbt")
  println(logger.getClass.getName)
}
```

## problem

The `LoggerFactory.getLogger` returns a *log4j logger* but it should return a *logback logger*. If we change to sbt `0.13.16` it works flawlessly.

## expectation

```bash
> myTestTask
ch.qos.logback.classic.Logger
```

But got

```bash
sbt:Test SBT> myTestTask
org.apache.logging.slf4j.Log4jLogger
```

## notes

sbt version: *1.0.2*

**Comment by dwijnand** [comment]
This is because log4j2 is used as the logging framework of sbt 1, and the selected backend for slf4j. So you can't use logback instead. :-/

**Comment by benhutchison** [comment]
A request for warning of this limitation/gotcha in the docs for writing a SBT plugin. The process of figuring out why my custom tasks SLF4J logging wasn't working has consumed much of my morning...

**Comment by juanjoDiaz** [comment]
Indeed.

I would also appreciate an example of how to create a custom logger.
the documentation is pretty poor in that sense.

**Comment by dwijnand** [comment]
Feel free to open issues detailing the documentation requests in https://github.com/sbt/website/.

@benhutchison I'm not sure what you mean by "my custom tasks SLF4J logging wasn't working" but if you believe there's a bug or possible improvement to be had, feel free to open an issue detailing it (in sbt/sbt if it's code related, in sbt/website if it's docs related).

**Comment by benhutchison** [comment]
"my custom tasks SLF4J logging wasn't working": I was setting log level flags but no logging appeared. It was because in actuality log4j was being used as the slf4j backend.

**Comment by dwijnand** [comment]
Don't you get https://www.slf4j.org/codes.html#multiple_bindings fatal errors if you add logback while log4j2 is present?
