### ISSUE TITLE
sbt ansi colors unreadable on some backgrounds

### ISSUE THREAD

**Issue by paulp** [sbt/sbt#365]
I have exactly the issue described here, but with sbt:

  https://github.com/etorreborre/specs2/issues/16

Can this be made configurable in a similar fashion (perhaps we could even spawn a standard way of configuring it) or some other resolution pursued:

```
def labelColor(level: Level.Value) =
    level match
    {
        case Level.Error => RED
        case Level.Warn => YELLOW
        case _ => RESET
    }
```

**Comment by paulp** [comment]
I hacked jenkins not to use a white background and it makes a huge difference, not entirely appreciable in this link:

  http://imgur.com/a/IxF0o

But the jenkins default is solid white and all the little images appear to be designed for that (it starts looking pretty stupid as one steers further from white - the picture at the link is #D8D8D8 .)

**Comment by Blaisorblade** [comment]
Have you investigated -Dsbt.log.noformat=true to disable coloring at all, which I use in my local Jenkins configuration? The disadvantage is of course the lack of highlighting. I'd suggest having shortcut options for dark and light backgrounds, using respectively only light or dark colors (as done in Vim); any further configurability should only be an addition, if it is implemented at all.

**Comment by paulp** [comment]
Disabling the colors is not a good remedy given that the colors are the entire point of the ticket.

**Comment by harrah** [comment]
Covered by https://github.com/dblock/jenkins-ansicolor-plugin/issues/4 and fixed by https://github.com/dblock/jenkins-ansicolor-plugin/pull/9
