### ISSUE TITLE
Add key to know whether we're inside CI or not

### ISSUE THREAD

**Issue by jvican** [sbt/sbt#3653]
## problem
Builds often need to know where they are run. In my experience, it is very common that you want to change the definition of a key depending on where it's run; whether it's in the CI or in my computer.
  
Currently, there's no mechanism to do so.

## expectation
I propose to add a boolean setting key called `insideCI`, along with a default implementation. This will allow users implement it depending on the concrete CI they use.

## notes
sbt already has checks to know whether it runs in the CI or not. See the following definition in `Defaults.scala`:
```scala
        ivyLoggingLevel :== {
          // This will suppress "Resolving..." logs on Jenkins and Travis.
          if (sys.env.get("BUILD_NUMBER").isDefined || sys.env.get("CI").isDefined)
            UpdateLogging.Quiet
          else UpdateLogging.Default
        },
```
  
It uses the standard `CI` environment option or `BUILD_NUMBER`. I propose `sys.env.get("CI").isDefined` to be the default implementation of `insideCI`, and make the definition of `ivyLoggingLevel` a call site of this key.

sbt version: 1.x

**Comment by eed3si9n** [comment]
Sounds like a good idea.
