### ISSUE TITLE
Scripted could define default settings in Global for sbt friendliness

### ISSUE THREAD

**Issue by jvican** [sbt/sbt#3656]
## problem
The scripted plugin does not follow the good practice of defining the default values for settings in `Global`. I also think that the scopes of the scripted task keys should be revisited. Currently, everything is crammed into `projectSettings`.
  
A direct consequence of this issue is that it's not possible to disable the buffer log globally or per build. There are more examples, but you get the direction where this is going. The configuration of scripted could be more sbt-friendly in this regard, in my opinion.

## expectation
I'd like keys like `scriptedSbt`, `sbtTestDirectory`, `scriptedLaunchOpts` and `scriptedBufferLog` to be scoped globally.

**Comment by ryan-williams** [comment]
Having this issue too; [the recommended way of running scripted tests](http://www.scala-sbt.org/1.x/docs/Testing-sbt-plugins.html#step+2%3A+scripted-plugin) requires settings which can't be set for all modules in a project.

A related question is whether the default value of `scriptedLaunchOpts` and `scriptedBufferLog ` should just be set to the values suggested in that tutorial… are those defaults ever *not* wanted? (if so, they could still be overridden per-project, afaict?)

**Comment by ryan-williams** [comment]
I suppose there is always [this work-around that I recently learned from @2m on gitter](https://gitter.im/sbt/sbt?at=5a4f94e3232e79134dccf1fa):

`project/Scripted.scala`:

```scala
import sbt._
import sbt.Keys._
import sbt.PluginTrigger.AllRequirements
import ScriptedPlugin.autoImport._

object Scripted extends AutoPlugin {
  override def trigger = AllRequirements
  override def requires = super.requires && ScriptedPlugin
  override def projectSettings: Seq[Def.Setting[_]] =
    Seq(
      scriptedLaunchOpts := { scriptedLaunchOpts.value ++
        Seq("-Xmx1024M", "-Dplugin.version=" + version.value)
      },
      scriptedBufferLog := false
    )
}
```

which in general is a good way to set default settings in multi-module projects where some upstream plugin is setting a non-`Global` default that's not overridden by `in ThisBuild`

**Comment by dwijnand** [comment]
My guess is this is the status quo because generally sbt plugins are single project builds. Happy to accept a PR to change this.
