### ISSUE TITLE
SBT proxy with authentication

### ISSUE THREAD

**Issue by dportabella** [sbt/sbt#366]
## steps

I've tried as follows:

```
$ export SBT_OPTS="-Dhttp.proxyHost=... -Dhttp.proxyPort=8080 -Dhttp.proxyUser=... -Dhttp.proxyPassword=..."
$ sbt
```

also as follows:

```
$ java -Dhttp.proxyHost=... -Dhttp.proxyPort=8080 -Dhttp.proxyUser=... -Dhttp.proxyPassword=... -Xmx512M -jar /usr/local/Cellar/sbt/0.11.2/libexec/sbt-launch.jar
```
## problem

but I get this error:

```
Getting org.scala-tools.sbt sbt_2.9.1 0.11.2 ...

:: problems summary ::
:::: WARNINGS
    Your proxy requires authentication.

    Your proxy requires authentication.
```

**Comment by dlecan** [comment]
NTLM proxy ?

**Comment by delor** [comment]
I have the same error with SSO via Kreberos.

**Comment by eed3si9n** [comment]
Sorry for the late response. Does this still happen with the latest sbt? If so we need better repro steps that we can recreate in our environment.

**Comment by eed3si9n** [comment]
Closing this for now. Also see https://github.com/sbt/sbt/blob/0.13/CONTRIBUTING.md

**Comment by jurajkochjar** [comment]
Try making file called `jvmargs` in `~/.sbt`
Add your proxy settings as you are used to:
`-Dhttp.proxyHost=...`
`-Dhttp.proxyPort=...`
`-Dhttp.nonProxyHosts=..`
`-Dhttp.proxyUser=...`
`-Dhttp.proxyPassword=...`

Supports also `https` variants.
Hope it helps!

**Comment by OpsRJ** [comment]
I'm trying to running version 0.13.13 behind a proxy. I've also tried the same steps that @dportabella tried with no success. Everything else works (browser, apt, wget, curl, etc...)

**Comment by wendersonferreira** [comment]
Try this

in my ubuntu change ~/.profile at end of file 

export SBT_OPTS="$SBT_OPTS -Dhttp.proxyHost=host -Dhttp.proxyPort=port -Dhttp.proxyUser=username -Dhttp.proxyPassword=password -Dhttps.proxyHost=host -Dhttps.proxyPort=port -Dhttps.proxyUser=username -Dhttps.proxyPassword=password"

enjoy it

**Comment by EdgarLemaire** [comment]
Hello !

SBT has a very hard time with proxies which require authentication.
The solution is to by-pass this proxy authentication, if you cannot turn off the proxy (a corporate proxy for example).
To do so, I have installed a Squid Proxy, which I configured to have access to my corporate proxy.
Then, I configure SBT to interact with my Squid Proxy instead of my corporate proxy :+1: 

> export JAVA_OPTS = "-Dhttps.proxyHost=localhost -Dhttps.proxyPort=3128 -Dhttp.proxyHost=localhost -Dhttp.proxyPort=3128"

You can copy/paste this command line in your bashrc file without changing anything.

Thus, SBT will access your Squid Proxy, which does not require any authentication. Then your Squid Proxy will authenticate with the corporate proxy, independently from SBT.

Hope it helps !

**Comment by schlichtanders** [comment]
@EdgarLemaire can you share your squid configuration?

I have a very hard time to find out how squid needs to be configured for this. I haven't worked with squid before and google is not of much help here, as squid is a proxy itself, so "proxy through squid" won't give you anything unfortunately.

**Comment by EdgarLemaire** [comment]
Sure : 

You just have to change and uncomment the line beginning by "cache_peer" as follows : 
> cache_peer PROXYHOST parent 80 0 no-digest no-query proxy-only login=USERNAME:PASSWORD


(just set your own PROXYHOST (without the http://, just the domain name like "proxy.myproxy.org"), USERNAME and PASSWORD).


Normally, it should work fine, but as I am not very proficient in this kind of stuff, I might have forgotten something. Feel free to ask if the problem persists and I will ask to my colleague which told me how to configure my Squid Proxy :)

Regards,

Edgar Lemaire

**Comment by ipiret** [comment]
@EdgarLemaire yes please have modified the line cache_peer as indicated i don't have anymore the error your proxy requires authentication but now 
SERVER ERROR: Service Unavailable url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.1.6/sbt-1.1.6.pom

	SERVER ERROR: Service Unavailable url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.1.6/sbt-1.1.6.jar
	SERVER ERROR: Service Unavailable url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/1.1.6/ivys/ivy.xml
	SERVER ERROR: Service Unavailable url=https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/1.1.6/ivys/ivy.xml

Does that ring any bell?
Tx in advance

**Comment by EdgarLemaire** [comment]
@ipiret I think you should also change the "acl" according to your corporate proxy domain name. I am sorry, I cannot share the file as it contains information on my company's proxy, and I don't want to take any risk as my company is very strict concerning cyber security.

Normally, there is a line in squid's configuration where are listed some "acl" things.

Maybe you can ask your network administrator to get the required domain names.

Regards,

Edgar

**Comment by ipiret** [comment]
@EdgarLemaire It had nothing to do with acl, but was the port which in my case was "8080" and i also had to uncomment "never_direct allow all" so after lots oh head scratching and reading docs got it eventually to work :smiley:

**Comment by EdgarLemaire** [comment]
@ipiret oh ok, cool then :-)
I thought squid was always connected to port 3128. Thank you for sharing your solution !

Regards,

Edgar

**Comment by ipiret** [comment]
@EdgarLemaire it was the port for my proxy server (the one specified in cache_peer)
