### ISSUE TITLE
client/server API documentation

### ISSUE THREAD

**Issue by MasseGuillaume** [sbt/sbt#3664]
Hey,

I'm a tool author and I want to use sbt 1.X client/server architecture. I would be happy to write some documentation but right now, I'm in the dark/reverse engineering.

I took a look around and I found this:

https://github.com/sbt/sbt/blob/1.x/protocol/src/main/contraband/jsonrpc.contra

I also found it's possible to connect to sbt via telnet, so I assume the transport is over raw tcp. It would help if there was a diagram showing what messages I need to send over the wire to execute sbt task and get back their result.

I found:

https://github.com/sbt/sbt/blob/1.x/server.md

but the sbt instance I started did not generate a token in ~/.sbt/1.0/server/

**Comment by laughedelic** [comment]
Check https://github.com/sbt/sbt/issues/3508 and some other issues with the [`server`](https://github.com/sbt/sbt/labels/server) label. 
Also to use https://github.com/sbt/sbt/pull/3556 you need to sbt 1.1.0-M1. The `server.md` document you linked also describes the format that _will_ be used in 1.1.0 (and is available as preview in M1). So try starting sbt with
```
sbt -sbt-version 1.1.0-M1
```

**Comment by eed3si9n** [comment]
It's here http://www.scala-sbt.org/1.x-beta/docs/sbt-server.html, but it's not ready until 1.1 comes out.

**Comment by MasseGuillaume** [comment]
@eed3si9n awesome, this is exactly what I wanted.
