### ISSUE TITLE
How to find what went wrong when sbt gives javac returned non zero exit code

### ISSUE THREAD

**Issue by smadishetti** [sbt/sbt#3665]
## steps
Compiling a play framework app (play 2.6.5, Scala 2.12.3) with sbt 0.13.15. This is what I get:

```
[debug] Scala compilation took 25.900606705 s  
[error] (MyProject/compile:compileIncremental) javac returned nonzero exit code  
[error] Total time: 71 s, completed Oct 24, 2017 6:39:22 PM
```

## problem
Scala errors are shown fine. But, for java compilation errors, it just says the javac returned non zero exit code. No information on the errors. How to find out what is wrong? Its a blocker and there is no way to proceed until the errors are found.
I tried with debug logging as well, but didn't help.

## expectation
Sbt should provide the compile errors from javac. At least provide a flag to control the behavior. Based on the search on similar issues, looks like this used to work fine until sbt 0.13.7. 

## notes
sbt version: 0.13.15

**Comment by SethTisue** [comment]
under what conditions does this occur?

**Comment by smadishetti** [comment]
All the time, whenever there are java compile errors. Java compilation fails but doesn't give details about what is wrong.

**Comment by SethTisue** [comment]
@smadishetti here's an attempt to reproduce the problem on MacOS 10.13.6, Java 1.8.0_181, and sbt 1.1.6:

```
% mkdir sbt3665
% cd sbt3665   
% mkdir project
% echo "sbt.version=1.1.6" > project/build.properties
% echo "this isn't valid Java code" > J.java
% sbt
[info] Loading project definition from /Users/tisue/tmp/sbt3665/project
[info] Updating ProjectRef(uri("file:/Users/tisue/tmp/sbt3665/project/"), "sbt3665-build")...
[info] Done updating.
[info] Set current project to sbt3665 (in build file:/Users/tisue/tmp/sbt3665/)
[info] sbt server started at local:///Users/tisue/.sbt/1.0/server/0ccbf257f6b7e50c205c/sock
sbt:sbt3665> compile
[info] Updating ...
[info] Done updating.
[info] Compiling 1 Java source to /Users/tisue/tmp/sbt3665/target/scala-2.12/classes ...
[error] /Users/tisue/tmp/sbt3665/J.java:1:1: class, interface, or enum expected
[error] this isn't valid Java code
[error] /Users/tisue/tmp/sbt3665/J.java:1:1: unclosed character literal
[error] this isn't valid Java code
[error] (Compile / compileIncremental) javac returned non-zero exit code
[error] Total time: 1 s, completed Jul 17, 2018 7:44:01 PM
```

as you can see, compilation errors are reported successfully

can you help narrow down the conditions under which this does or does not occur? is the problem even reproducible with a current version of sbt such as 0.13.17, 1.1.6, or 1.2.0-RC3?

**Comment by eed3si9n** [comment]
This issue was re-reported as https://github.com/sbt/zinc/issues/376 and https://github.com/sbt/zinc/issues/520, and I've been trying to hunt it down. There are several theories surrounding the bug, but one of them is the presence of JAVA_HOME causing `javaHome` to be set (potentially a sbt-extra stuff?), and that changes the behavior of Zinc's interaction with javac.

**Comment by eed3si9n** [comment]
See also https://github.com/sbt/zinc/pull/557 that is shipped with 1.2.0-RC3.

**Comment by SethTisue** [comment]
shall we close this one and leave https://github.com/sbt/zinc/issues/520 as the ticket of record...?

**Comment by eed3si9n** [comment]
People can come to sbt/sbt to find issues, so I normally keep both open with sbt labelled with "Blocked on Upstream"

**Comment by olafurpg** [comment]
A workaround is documented in https://github.com/sbt/zinc/issues/520#issuecomment-410677766

**Comment by poojasundar99** [comment]
Hello, I'm also getting the same issue that,

[warn] javac exited with exit code -1073740791
[error] (Compile / compileIncremental) javac returned non-zero exit code

What can I do now, can anyone suggest me what to do.

**Comment by SethTisue** [comment]
maybe running with `sbt -debug` would provide some clues that would help you investigate

**Comment by poojasundar99** [comment]
> maybe running with `sbt -debug` would provide some clues that would help you investigate

My sbt doesn't show any errors, it's was build successfully. Right now I'm using Play framework in Scala. Play framework only supports with JDK 8, so I was using jdk8. But I was try to connect my api it shows '.class files are compiled with jdk 7 version you have to change into jdk8' But I create a project with JDK 8 version. I checked all my project structure and all. It doesn't shows other then that the version error.

**Comment by SethTisue** [comment]
That doesn't seem related to this ticket, then.
