### ISSUE TITLE
Resolving sbt-plugins from cache is slow

### ISSUE THREAD

**Issue by jrudolph** [sbt/sbt#368]
At least everytime something in your global sbt plugin configuration changes all projects have to re-resolve the plugin dependencies. This is particularly slow because ivy produces broken ivy.xml files in the cache for sbt plugins leading to warnings like this:

```
[debug] No entry is found in the ModuleDescriptorCache : /home/johannes/.ivy2/cache/scala_2.9.1/sbt_0.11.2/net.databinder/posterous-sbt/ivy-0.3.2.xml
[debug] post 1.3 ivy file: using exact as default matcher
[debug]     problem while parsing cached ivy file for: net.databinder#posterous-sbt;0.3.2: [xml parsing: ivy-0.3.2.xml:9:3: cvc-complex-type.3.2.2: Attribute 'sbtVersion' is not allowed to appear in element 'info'. in file:/home/johannes/.ivy2/cache/scala_2.9.1/sbt_0.11.2/net.databinder/posterous-sbt/ivy-0.3.2.xml
[debug] , xml parsing: ivy-0.3.2.xml:9:3: cvc-complex-type.3.2.2: Attribute 'scalaVersion' is not allowed to appear in element 'info'. in file:/home/johannes/.ivy2/cache/scala_2.9.1/sbt_0.11.2/net.databinder/posterous-sbt/ivy-0.3.2.xml
```

In consequence that means that at least the metadata has to be re-downloaded from the repositories which is slow.

If you look into those cached ivy files it seems that ivy generates additional non-namespace-qualifed attributes in the `<info>` tag for the `scalaVersion` and `sbtVersion` classifiers coming from poms.

Here's a possibly related bug in Ivy's bugtracker: https://issues.apache.org/jira/browse/IVY-1322

A workaround could be to switch off `ivy.xml` validation for the cache resolver as long as the problem is not properly fixed on the ivy side.

**Comment by jrudolph** [comment]
I implemented that workaround by overriding validation for the cache with a file `~/.sbt/plugins/project/IvyChanger.scala`:

``` scala
    import org.apache.ivy.core.cache.{CacheMetadataOptions, DefaultRepositoryCacheManager}
    import org.apache.ivy.core.module.descriptor.DependencyDescriptor
    import org.apache.ivy.core.module.id.ModuleRevisionId
    import sbt._
    import Keys._

    object IvyChanger {
      def removeCacheValidation(streams: TaskStreams, ivy: IvySbt): IvySbt = {
        ivy.withIvy(streams.log) { ivy =>
          val settings = ivy.getSettings
          val cacheDir = settings.getDefaultRepositoryCacheBasedir
          val newManager = new DefaultRepositoryCacheManager("default-cache", settings, cacheDir) {
            override def findModuleInCache(dd: DependencyDescriptor, revId: ModuleRevisionId, options: CacheMetadataOptions, r: String) = {
              options.setValidate(false) // switch off validation
              super.findModuleInCache(dd,revId,options,null)
            }
          }

          settings.setDefaultRepositoryCacheManager(newManager)
        }

        ivy
      }
    }
```

and adding this line to the `~/.sbt/plugins/plugins.sbt`:

``` scala
    ivySbt <<= (streams, ivySbt) map IvyChanger.removeCacheValidation
```

This change could also be added directly in sbt's `IvySbt` if no other ivy fix is found.

**Comment by jrudolph** [comment]
Maybe I spoke to soon. After some further experiments the workaround doesn't seem to work. I'm now using a patched version of sbt with this additional commit.

**Comment by vigdorchik** [comment]
I can't reproduce unqualified scalaVersion and sbtVersion for my plugins and sbt 0.11.2.
Can you hint what are the plugins that suffer from this defficiency?

**Comment by jrudolph** [comment]
For me it's for every plugin. E.g.:

```
> cat ~/.ivy2/cache/scala_2.9.1/sbt_0.11.2/com.github.mpeltonen/sbt-idea/ivy-1.0.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<ivy-module version="2.0" xmlns:m="http://ant.apache.org/ivy/maven">
    <info organisation="com.github.mpeltonen"
        module="sbt-idea"
        revision="1.0.0"
        status="release"
        publication="20120121101907"
        sbtVersion="0.11.2" scalaVersion="2.9.1"
    >
snip...
```

The last line feature the problematic attributes which should be in the namespace `http://ant.apache.org/ivy/maven`. To clarify, this happens only in the `ivy.xml` files generated by ivy for the cache from a downloaded pom file.

**Comment by vigdorchik** [comment]
Ah, stupid me. I completely missed pom-to-ivy step.

**Comment by harrah** [comment]
@vigdorchik thanks for looking into this, the follow-up information helped.

@jrudolph Thanks for the report and all of the information.  This commit fixed it for me, please verify.

**Comment by jrudolph** [comment]
I cherrypicked your commit on a custom 0.11.2 build and the problem seems now fixed for me as well. Excellent. Thanks.
