### ISSUE TITLE
testQuick is slow

### ISSUE THREAD

**Issue by OlegYch** [sbt/sbt#3680]
## steps
a large project with lots of tests and complex source dependencies

## problem
testQuick spins cpu for several minutes in sbt.Defaults#testQuickFilter

## notes
sbt version: 1.0.2
https://github.com/sbt/sbt/commit/f8ef4497891cb8b7defd10fb6fadee457e3390af?w=1 this commit appears to remove caching of 'stamps'

**Comment by OlegYch** [comment]
note that this is also reproducible on sbt project itself

**Comment by dwijnand** [comment]
Fixed with https://github.com/sbt/sbt/pull/3720, due in 1.0.4.
