### ISSUE TITLE
sbt.watch.mode not defined on macOS installed by Homebrew

### ISSUE THREAD

**Issue by hseeberger** [sbt/sbt#3685]
sbt version 1.0.3
macOS 10.13
Java 8

The contents of `/usr/local/etc/sbtopts` don't contain an entry for `sbt.watch.mode`. Executing `console` in an sbt session:

``` scala
scala> sys.props("sbt.watch.mode")
res0: String = null
```

This is in contrast to the release notes which state that "polling" should be the default on macOS.

**Comment by dwijnand** [comment]
Right, the release notes are accidentally misleading. What's mean is that polling is the default on macOS: https://github.com/sbt/sbt/pull/3597/files#diff-623bb403e2764f9244d1e109c8fba387R138

**Comment by hseeberger** [comment]
Thanks. Yet I don‘t see any improvements, i.e. either polling doesn‘t give any advantages or sbt doesn‘t use it.

**Comment by dwijnand** [comment]
Are you on a Play project? Play doesn't use sbt's polling.

**Comment by hseeberger** [comment]
Nah, I don't play ;-)
Plain old sbt project.
