### ISSUE TITLE
Unable to upgrade sbt on mac with brew.

### ISSUE THREAD

**Issue by madhurakhal** [sbt/sbt#3686]
(See the guidelines for contributing, linked above)

## steps
Install java 9
<img width="829" alt="screen shot 2017-10-28 at 7 10 33 pm" src="https://user-images.githubusercontent.com/839882/32136768-1fbec868-bc14-11e7-9b1c-db43bede4d7d.png">

## problem

Cannot upgrade sbt using brew.

## expectation
sbt: Java 1.8 is required to install this formula.
JavaRequirement unsatisfied!

## notes
I have installed java 9
sbt version: *insert sbt version*
1.0.3

**Comment by RainbowHerbicides** [comment]
Same issue when i am trying to update to/install last version of sbt via brew:

> ~ brew install sbt
sbt: Java 1.8 is required to install this formula.
JavaRequirement unsatisfied!
You can install with Homebrew-Cask:
 brew cask install caskroom/versions/java8
You can download from:
 https://www.oracle.com/technetwork/java/javase/downloads/index.html
Error: An unsatisfied requirement failed this build.

Even though i have required version of java installed:
>  ~ java -version
Picked up _JAVA_OPTIONS: -Xms1024m -Xmx2G -Xss256m -XX:MaxPermSize=4G
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=4G; support was removed in 8.0
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

**Comment by albertvila** [comment]
Same issue here, any workaround?

**Comment by ademagic** [comment]
Had the same issue.
```
$ brew install sbt
sbt: Java 1.8 is required to install this formula.
JavaRequirement unsatisfied!
You can install with Homebrew-Cask:
  brew cask install java
You can download from:
  https://www.oracle.com/technetwork/java/javase/downloads/index.html
Error: An unsatisfied requirement failed this build.
```
Running `brew cask install java` installed v9, which didn't meet the requirements. **It worked** when I uninstalled it, and installed `JDK 8 Update 151` from the Oracle website.

**Comment by pawelkrol** [comment]
Same problem here. Java 1.8 is installed. Any ideas if there is a workaround?

```
$ brew install sbt
sbt: Java 1.8 is required to install this formula.
JavaRequirement unsatisfied!

You can install with Homebrew-Cask:
  brew cask install java

You can download from:
  https://www.oracle.com/technetwork/java/javase/downloads/index.html
Error: An unsatisfied requirement failed this build.
$ java -version
Picked up _JAVA_OPTIONS: -Xms1024m -Xmx2G -Xss256m -XX:+CMSClassUnloadingEnabled
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)
```

**Comment by albertvila** [comment]
The workaround I found is to uninstall java 9 and install java 8 instead.

```
brew cask uninstall java
brew cask install java8
brew install sbt
```

**Comment by rainsoupah** [comment]
I installed `sbt` manually in the following way:
1. first download and extract SBT-1.0.2.ZIP from [here](http://www.scala-sbt.org/download.html?_ga=2.90510557.633784364.1509729881-670080350.1509724070)
2. `cd sbt/bin`
3. `sudo mv sbt-launch.jar /usr/local/bin/sbt-launch.jar`
4. `java -Xmx512M -jar /usr/local/bin/sbt-launch.jar`
5.  `sudo chmod +x /usr/local/bin/sbt` 
Invoking the `sbt` command led me to the console

**Comment by ademagic** [comment]
Judging from responses, the people who had 1.8 installed but were _still unsuccessful_, were using `1.8.0_152`. Installing `1.8.0_151` works for me @pawelkrol.

What version does `brew cask install java8` install @albertvila?

**Comment by hannahlindsley** [comment]
@ademagic I think you have to do brew cask install caskroom/versions/java8, for what it's worth. 
It's currently installing 1.8.0_152, looks like. 152 works fine for sbt installation for me.

**Comment by wuv1982** [comment]
brew checks java version by `/usr/libexec/java_home`.
So to pass the requirement check, u just need link a JDK path in `/Library/Java/JavaVirtualMachines` where can be found by `java_home`.

**Comment by eed3si9n** [comment]
Hopefully this was fixed in https://github.com/Homebrew/homebrew-core/pull/21052
