### ISSUE TITLE
Scripted test `source-dependencies/binary` fails with Scala 2.12.{0,1,2,3}

### ISSUE THREAD

**Issue by Duhemm** [sbt/sbt#3691]
## steps
1. Checkout sbt @ 4ce4fb72bde3b8acfaf526b79d32ca1463bc687b
2. Modify the `scalaVersion` inside the `build.sbt` of the scripted test `source-dependencies/binary` so that it reads:
```scala
scalaVersion in ThisBuild := "2.12.3"
```
3. Run `scripted source-dependencies/binary`
## problem
- The test fails

## expectation
- The test succeeds

## notes
- It passes with Scala 2.11.11, 2.12.4 or if the `scalaVersion` is not set.

sbt version: 1.0.3-SNAPSHOT (@ 4ce4fb72bde3b8acfaf526b79d32ca1463bc687b)

**Comment by smarter** [comment]
This was a bug in scalac that got fixed in 2.12.4: https://github.com/scala/bug/issues/10295 (and the fix was ported to dotty: https://github.com/lampepfl/dotty/pull/3116), I don't think there's anything more that sbt should be doing now.

**Comment by dwijnand** [comment]
Closing as fixed upstream.
