### ISSUE TITLE
Unresolved dependencies (sbt version 0.13.13)

### ISSUE THREAD

**Issue by algimantasligeikis** [sbt/sbt#3692]
## steps
1. Installed sbt 0.13.13.1 (windows installer)
2. Executed sbt run on project
3. SBT_HOME is set correctly, sbt sbtVersion returns 0.13.13.1

## problem
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.typesafe.play#sbt-plugin;2.5.10: not found
[warn]  :: com.typesafe.sbt#sbt-digest;1.1.1: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::

Installation previously was working, only when new developer joined and tried fresh installation it failed (two month ago issue was not present, fresh installation was working).

[sbtError.txt](https://github.com/sbt/sbt/files/1426706/sbtError.txt)
## notes

sbt version: 0.13.13.1

**Comment by dwijnand** [comment]
Your project is using sbt 1. You have to upgrade to Play 2.6.6 and sbt-digest 1.1.4.
