### ISSUE TITLE
Reference to 0.14.0 in 1.0.3 warning message

### ISSUE THREAD

**Issue by vhiairrassary** [sbt/sbt#3693]
Using `sbt.version = 1.0.3`, launch `sbt --info`:
```
/opt/app # sbt --info
Picked up _JAVA_OPTIONS: -Duser.language=en -Duser.country=US -Duser.timezone=UTC
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /opt/app/project
[info] Loading settings from build.sbt ...
[info] Set current project to walmart (in build file:/opt/app/)
[warn] The `-` command is deprecated in favor of `onFailure` and will be removed in 0.14.0
```

Source code link: https://github.com/sbt/sbt/blob/1.x/main-command/src/main/scala/sbt/BasicCommandStrings.scala#L197

**Comment by rsoeldner** [comment]
What the point here, remove the warning ?

**Comment by vhiairrassary** [comment]
That is weird to see a warning about the `0.14.0` while we are running the `1.0.3`

**Comment by kshakir** [comment]
Re: this warning message fix--

Do the docs need updating too? The [current 1.x website](https://github.com/sbt/website/blob/6ba3b960418e1afb396b78376ecdc6e7edf6555e/src/reference/04-Howto/06-Howto-Logging.md#change-the-logging-level-globally) says:

> To set the logging level before any commands are executed on startup, use -- before the logging level.

If so I or someone can file an issue on the docs. As the original report on this issue states `sbt --info` now prints:

> [warn] The \`-\` command is deprecated in favor of \`onFailure\` and will be removed

Btw, what _should_ the docs say is the way to set the logging level before any commands are executed on startup? Running `sbt 'set logLevel := Level.Warn' …` changes the level too late after several `[info]` startup messages are printed out.
