### ISSUE TITLE
Performance observations (sbt 1.0 startup performance)

### ISSUE THREAD

**Issue by jrudolph** [sbt/sbt#3694]
Here's an adhoc observation I've seen in a flamegraph I recently captured with async-profiler during startup of sbt. On runs where all `.sbt` files should already have been compiled, they still seem to be parsed which is where quite some time is spent because a compiler instance needs to be initialized for that (with all the classloading that happens because of that).

Another hotspot seems to be json deserialization of caches. Might make sense to optimize at least big caches like classpaths to use something better performing than json serialization.

[flamegraph-akka-http-sbt.svg.txt](https://github.com/sbt/sbt/files/1427223/flamegraph-akka-http-sbt.svg.txt)

**Comment by jvican** [comment]
> On runs where all .sbt files should already have been compiled, they still seem to be parsed which is where quite some time is spent because a compiler instance needs to be initialized for that (with all the classloading that happens because of that).

To the best of my knowledge this is the intended behaviour. Sbt caches at the statement level because it hoists up every statement to its own class -- I cannot think of a way we can remove that without changing the whole evaluation algorithm. You can check this in the `.config-classes` directory typically placed in `project/target`.

**Comment by jrudolph** [comment]
Superseded by https://github.com/sbt/sbt/issues/4012.

**Comment by jrudolph** [comment]
> I cannot think of a way we can remove that without changing the whole evaluation algorithm

It was possible to do that by just introducing another layer of caching just for the result of `splitExpressions`. See https://github.com/jrudolph/xsbt/commit/b7a9f740b3426ac46ee92eec0efdb8cd2a8d16cb.
