### ISSUE TITLE
sbt proxy configuration problems

### ISSUE THREAD

**Issue by ghost** [sbt/sbt#3696]
It seems that I have a problem configuring proxy for SBT. I tried the following methods

## steps

1. Configured the following parameters in %SBT_HOME%\conf\stbconfig.txt:
```
-Dhttp.proxySet=true 
-Dhttp.proxyHost=proxy_server
-Dhttp.proxyPort=proxy_port 
-Dhttp.nonProxyHosts="localhost|127.0.0.1" 
-Dhttp.proxyUser=username
-Dhttp.proxyPassword=password
-Dhttps.proxyHost=proxy_server
-Dhttps.proxyPort=proxy_port 
-Dhttps.nonProxyHosts="localhost|127.0.0.1" 
-Dhttps.proxyUser=username
-Dhttps.proxyPassword=password
```
2. I added the above parameters sbtopts file but didn't work.

3. I tried the solutions that said to pass the configurations in command line as environment variables ( JAVA_OPTS or SBT_OPTS) but it seems that it didn't worked for me.

## problem

Unresolved dependencies) and/or warnings ( [warn] Your proxy requires authentication.)

The output of the sbt new scala/hello-world.g8 is:
```
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; sup
port was removed in 8.0
[info] Set current project to workspace (in build file:/D:/workspace/)
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scala-sbt.sbt-giter8-resolver#sbt-giter8-resolver_2.12;0.1.3: Res
olution failed several times for dependency: org.scala-sbt.sbt-giter8-resolver#s
bt-giter8-resolver_2.12;0.1.3 {compile=[default(compile)]}::
[warn]  sbt-releases-repo: unable to get resource for org.scala-sbt.sbt-giter8-r
esolver#sbt-giter8-resolver_2.12;0.1.3: res=http://repo.typesafe.com/typesafe/iv
y-releases/org.scala-sbt.sbt-giter8-resolver/sbt-giter8-resolver_2.12/0.1.3/ivys
/ivy.xml: java.net.ConnectException: Failed to connect to repo.typesafe.com/34.2
06.225.108:80
[warn]  sbt-plugins-repo: unable to get resource for org.scala-sbt.sbt-giter8-re
solver#sbt-giter8-resolver_2.12;0.1.3: res=http://repo.scala-sbt.org/scalasbt/sb
t-plugin-releases/org.scala-sbt.sbt-giter8-resolver/sbt-giter8-resolver_2.12/0.1
.3/ivys/ivy.xml: java.net.ConnectException: Failed to connect to repo.scala-sbt.
org/34.206.162.65:80
[warn]  maven-central: unable to get resource for org/scala-sbt/sbt-giter8-resol
ver#sbt-giter8-resolver_2.12;0.1.3: res=http://repo1.maven.org/maven2/org/scala-
sbt/sbt-giter8-resolver/sbt-giter8-resolver_2.12/0.1.3/sbt-giter8-resolver_2.12-
0.1.3.pom: java.net.ConnectException: Failed to connect to repo1.maven.org/151.1
01.44.209:80
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[error] java.lang.RuntimeException: Retrieval of org.scala-sbt.sbt-giter8-resolv
er:sbt-giter8-resolver:0.1.3 failed.
[error]         at scala.sys.package$.error(package.scala:27)
[error]         at sbt.TemplateCommandUtil$.classpathForInfo(TemplateCommand.sca
la:119)
[error]         at sbt.TemplateCommandUtil$.infoLoader(TemplateCommand.scala:81)

[error]         at sbt.TemplateCommandUtil$.$anonfun$run$1(TemplateCommand.scala
:48)
[error]         at sbt.TemplateCommandUtil$.$anonfun$run$1$adapted(TemplateComma
nd.scala:47)
[error]         at scala.collection.LinearSeqOptimized.find(LinearSeqOptimized.s
cala:111)
[error]         at scala.collection.LinearSeqOptimized.find$(LinearSeqOptimized.
scala:108)
[error]         at scala.collection.immutable.List.find(List.scala:86)
[error]         at sbt.TemplateCommandUtil$.run(TemplateCommand.scala:47)
[error]         at sbt.TemplateCommandUtil$.runTemplate(TemplateCommand.scala:34
)
[error]         at sbt.TemplateCommandUtil$.$anonfun$templateCommand$2(TemplateC
ommand.scala:17)
[error]         at sbt.Command$.$anonfun$applyEffect$4(Command.scala:125)
[error]         at sbt.Command$.$anonfun$applyEffect$2(Command.scala:121)
[error]         at sbt.MainLoop$.processCommand(MainLoop.scala:121)
[error]         at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:105)
[error]         at sbt.State$$anon$1.runCmd$1(State.scala:227)
[error]         at sbt.State$$anon$1.process(State.scala:233)
[error]         at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:105)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.sc
ala:16)
[error]         at sbt.MainLoop$.next(MainLoop.scala:105)
[error]         at sbt.MainLoop$.run(MainLoop.scala:98)
[error]         at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:76)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.MainLoop$.runWithNewLog(MainLoop.scala:70)
[error]         at sbt.MainLoop$.runAndClearLast(MainLoop.scala:52)
[error]         at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:37)
[error]         at sbt.MainLoop$.runLogged(MainLoop.scala:29)
[error]         at sbt.StandardMain$.runManaged(Main.scala:104)
[error]         at sbt.xMain.run(Main.scala:71)
[error]         at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error]         at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error]         at xsbt.boot.Launch$.run(Launch.scala:109)
[error]         at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error]         at xsbt.boot.Launch$.launch(Launch.scala:117)
[error]         at xsbt.boot.Launch$.apply(Launch.scala:18)
[error]         at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error]         at xsbt.boot.Boot$.main(Boot.scala:17)
[error]         at xsbt.boot.Boot.main(Boot.scala)
[error] Retrieval of org.scala-sbt.sbt-giter8-resolver:sbt-giter8-resolver:0.1.3
 failed.
```

## notes

Tried also with sbt 1.0.0 and I also have the above mentioned error. Is not a proxy configuration problem because the same info( proxy server/port, username/password) I use for another tool and everything works excellent.

sbt version: 1.0.2

**Comment by howardlinus** [comment]
i have the same issue, any update, very frustrated...

**Comment by jackyxuebin** [comment]
me too

**Comment by howardlinus** [comment]
i found this, and hopefully is useful to everyone. the solution of using ~/.sbt/repositories posted by @bignano works for me

**Comment by sukeshlaghate** [comment]
+1 Me too

**Comment by linkTDP** [comment]
The same problem also for me

**Comment by meequee** [comment]
Same. Any Update?

**Comment by SIkebe** [comment]
I also have this problem.

@howardlinus @bignano
>the solution of using ~/.sbt/repositories posted by @bignano works for me

Could you tell me any link of this, please?

**Comment by alelk** [comment]
+1

**Comment by lwu08** [comment]
Already set SBT_OPT env, and my proxy works well for other tools...
Still get the following error:


[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scala-sbt#compiler-bridge_2.12;1.1.0: public: unable to get resource for org/scala-sbt#compiler-bridge_2.12;1.1.0: res=https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.12/1.1.0/compiler-bridge_2.12-1.1.0.pom: java.io.IOException: Failed to authenticate with proxy

**Comment by webskin** [comment]
+1

**Comment by aishinoharac** [comment]
me too

I saw the post someone wrote his java command pointed to jre not jdk and it was reason proxy authentication failed. So I checked my java it was no problem.

Finally I gave up and got through it by setting local proxy to bridge PROXY with authentication.

I spent almost 2 days for this issue, very frustrated also

**Comment by SIkebe** [comment]
@aishinoharac Using Fiddler or something similar?

**Comment by aishinoharac** [comment]
@SIkebe Squid. easier than Apache i think. only 1 minute to set up.

**Comment by SIkebe** [comment]
@ardeleanasm Thanks!

**Comment by jamesporritt** [comment]
I set up mitmproxy between myself and my proxy to see the traffic flow. I was careful to set the settings above and the maven proxy settings and ensured there were no env vars. When I do an 'sbt new' on a project that requires fetching some maven dependency, I see the github traffic go through mitmproxy fine, but then sbt exits with:

Unknown exception: Connection to https://repo1.maven.org refused

There is no record of it going through the proxy! Some how it is ignoring the proxy settings.

**Comment by SIkebe** [comment]
Any update on this issue?

**Comment by eed3si9n** [comment]
sbt uses Gigahorse with OkHttp for parallel downloading, which does not support HTTPS proxy. You can try turning it off by passing `-Dsbt.gigahorse=false`. 

Another thing you could try is running an internal Artifactory that proxies all the remote repositories, and use that, or try turning off https, and use http by passing `-Dsbt.repository.secure=false`.

Ref https://github.com/square/okhttp/issues/3787

**Comment by SIkebe** [comment]
@eed3si9n Thanks! `-Dsbt.gigahorse=false` worked for me :smile:

**Comment by eed3si9n** [comment]
@SIkebe Thanks for the confirmation.

**Comment by leobenkel** [comment]
You can also add `updateOptions := updateOptions.value.withGigahorse(false)` to `build.sbt`
