### ISSUE TITLE
Local Maven Repository syntax does not work

### ISSUE THREAD

**Issue by ngocdaothanh** [sbt/sbt#37]
I am using sbt 0.10.0.

I installed Netty snapshot into my local Maven repository.

I have these lines in build.sbt:
resolvers += "Local Maven Repository" at "file://" + Path.userHome + "/.m2/repository"
libraryDependencies += "org.jboss.netty" % "netty" % "4.0.0.Alpha1-SNAPSHOT"

But "sbt update" cannot find Netty's jar file.

The log says that sbt has tried this URL:
file://sbt.RichFile@1f80cb01/.m2/repository/org/jboss/netty/netty/4.0.0.Alpha1-SNAPSHOT/netty-4.0.0.Alpha1-SNAPSHOT.jar

I think "file://sbt.RichFile@1f80cb01/.m2/repository..." is not correct. I think the problem is at Path.userHome.

**Comment by harrah** [comment]
Thanks for the report.  You are right that there is an additional `.absolutePath` needed on `userHome`.  I have updated the documentation and will probably make it unnecessary in a future release.

**Comment by retronym** [comment]
We found we needed three '/' to make it work on Windows., e.g. `file:///c:/repo`

**Comment by harrah** [comment]
I think I saw a build that used:

```resolvers += "Local Maven Repository" at Path.userHome.asURL + "/.m2/repository"

```

If that works for you, perhaps we should use that instead.
```

**Comment by retronym** [comment]
Will give it a shot at work and report back.

**Comment by rlegendi** [comment]
@retronym Either `/` or `///` works, but `//` doesn't. Any hints why Windows handles URI-s this way?
