### ISSUE TITLE
object apache is not a member of package org, compiling Spark (Scala) with SBT

### ISSUE THREAD

**Issue by antoniocachuan** [sbt/sbt#3700]
## steps
I just run this code in CMD
`sbt package`

![error](https://user-images.githubusercontent.com/4010332/32252314-d735eb8e-be62-11e7-9750-dbc36d172e06.png)

## problem
I'm developing a Spark process in Scala (Eclipse IDE) I am trying to packaged in a .jar with sbt but in getting this error (see picture). Please any help I will be grateful.

Spark 1.6.0
Scala 2.10.5
SBT 0.13.16

## expectation
A .jar compiled

## notes
When I Run in Eclipse works fine.
sbt version: *0.13.16*

**Comment by eed3si9n** [comment]
Please see https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md

> The most important thing to remember about bug reporting is to clearly distinguish facts and opinions. What we need first is the exact steps to reproduce your problems on our computers. This is called reproduction steps, which is often shortened to "repro steps" or "steps."

You wrote:

> I just run this code in CMD
>
> `sbt package`

We can't possibly reproduce your issue with only the information you gave us.
