### ISSUE TITLE
Failure to resolve genjavadoc-plugin

### ISSUE THREAD

**Issue by raboof** [sbt/sbt#3703]
(See the guidelines for contributing, linked above)

## steps

* clone git@github.com:akka/akka
* set project/build.properties to 1.0.3
* `rm -r /home/aengelen/.ivy2/local/com.typesafe.genjavadoc/genjavadoc-plugin_2.12.4`
* `rm -r /home/aengelen/.ivy2/cache/com.typesafe.genjavadoc/genjavadoc-plugin_2.12.4`
* `sbt -Dakka.genjavadoc.enabled=true ++2.12.4 compile`

## problem

sbt fails to download com.typesafe.genjavadoc/genjavadoc-plugin_2.12.4

## expectation

no failure

## notes

sbt version: 1.0.3 (1.0.2 appears to work)

**Comment by xuwei-k** [comment]
https://github.com/sbt/sbt/issues/3684#issuecomment-340142250 ?

**Comment by raboof** [comment]
Looks like it! Sorry didn't find it before...
