### ISSUE TITLE
Sbt keeps throwing weird java error

### ISSUE THREAD

**Issue by reikdas** [sbt/sbt#3704]
Running any sbt command throws a java error - 

"The java installation you have is not up to date
requires at least version 1.6+, you have
version 1.8"

This is after the last sbt update . I am unable to check the current sbt version because I run into the above mentioned error on running sbt sbt-version.

**Comment by ritschwumm** [comment]
which operating system do you use?
could this be related to the change in sbt-laucher using bc to compare java versions?

**Comment by Tello-Wharton** [comment]
I fixed this by removing SBT:
rpm -e sbt

And deliberately installing the 1.0.2 version
 wget https://dl.bintray.com/sbt/rpm/sbt-1.0.2.rpm
rpm -ivh sbt-1.0.2.rpm

(done on centos)

**Comment by reikdas** [comment]
@ritschwumm Debian Stretch

**Comment by reikdas** [comment]
Installing bc solved the issue.

**Comment by aurabindo** [comment]
@reikdas I believe the debian package must include bc as a dependency or, fail with appropriate message. Only then the issue need to be closed IMO as that is an appropriate fix.

**Comment by reikdas** [comment]
Okay. Reopened it.

**Comment by ritschwumm** [comment]
wouldn't it be better to just get rid of bc again?
treating version numbers as floats is a bit of a hack anyway.

**Comment by eed3si9n** [comment]
`bc` is now removed in https://github.com/sbt/sbt-launcher-package/pull/199.
