### ISSUE TITLE
sbt pending on resolving plugin

### ISSUE THREAD

**Issue by acearth** [sbt/sbt#3706]
(See the guidelines for contributing, linked above)

## steps
1. Open my project which used one sbt plugin. 
The related file is 
1) $PROJECT_NAME/project/plugins.sbt
```
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.6.2")
```
2) $PROJECT_NAME/build.sbt
```
lazy val root = (project in file(".")).enablePlugins(PlayScala)
```
2. Run command: sbt compile
Then the output is:
[info] Loading project definition from /ppcc/project
[info] Updating {file:/$MY_PROJECT/project/}... ... ...
[info] Resolving com.typesafe.play#sbt-plugin;2.6.2 ...
The sbt is pending at here.

## problem
So, how to make the sbt resolve PlayScala plugin as expected?

I try to use curl to track this problem. And finally  found the TLS connection between my machine to the plugin repo is pending. 
The command is :  curl -vvv   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/
The output is: 
* Hostname was NOT found in DNS cache
*   Trying 34.206.225.108...
* Connected to repo.scala-sbt.org (34.206.225.108) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):

and pending at here.

And I found above URL is redirected to https://dl.bintray.com/sbt/sbt-plugin-releases
So I try to resolve the repo to this URL. 
I add resolver in project/plugins.sbt and build.sbt, but it not works. The added line is 
`resolvers += Resolver.url("bintray-sbt-plugins", url("https://dl.bintray.com/sbt/sbt-plugin-releases/"))(Resolver.ivyStylePatterns)`
I also changed the repo settings on ~/.sbt/0.13/repositories, ~/.repositories, ~/.sbt/repositories, .
BUT ALL OF MY TRIALS ARE FAILED TO WORK.
 

## expectation
Can anyone help me to solve this problem? I just want make "sbt compile" works when I used PlayScala plugin.
## notes

sbt version: 0.13.16

**Comment by eed3si9n** [comment]
I don't think this is an sbt issue we can resolve.
