### ISSUE TITLE
How does one get the "Project does not exist" prompt?

### ISSUE THREAD

**Issue by Berkana** [sbt/sbt#371]
I installed SBT in order to play with the Lift framework. (The book I'm using is Lift in Action, by Manning Publications.)

The book was written while SBT was still at version 0.7, but when I installed SBT using MacPort, it installed the latest version of SBT (0.11). I figured that shouldn't be a problem, but I'm not sure how to figure out this one:

It seems that SBT used to prompt the user upon starting in a directory without a project, with the following prompt:

Shell output:

---

```
Project does not exist, create new project? (y/N/s)
```

---

When I run SBT in a new directory, all I get is:

Shell output:

---

```
[info] Set current project to default-a016fc (in build file: ... )
>
```

---

I explored the commands that show up under help, but nothing appears to change this default behavior, or at least I haven't been able to find it. How does one set SBT to prompt me about creating a new project?

**Comment by harrah** [comment]
Please use the mailing list for questions.
