### ISSUE TITLE
Version model and Ordering

### ISSUE THREAD

**Issue by MasseGuillaume** [sbt/sbt#3710]
sbt should provide a way to compare version.

for example, I want to add a library if the scalaVersion is > 2.12.

Currently I would so something like:

```scala
libraryDependencies += {
    val scalaBV = scalaBinaryVersion.value
    if (scalaBV == "2.10" || scalaBV == "2.11" || scalaBV == "2.12") lib1
    else lib2
}
```

what I really want to do is:

```scala
libraryDependencies += {
    val scalaBV = scalaBinaryVersion.value
    if (Version(scalaBV) > Version("2.12")) lib2
    else lib1
}
```

In scaladex we have a model and an ordering for this:
https://github.com/scalacenter/scaladex/blob/master/model/src/main/scala/ch.epfl.scala.index.model/SemanticVersion.scala

**Comment by dwijnand** [comment]
For anyone looking to implement this API it would be best to define it using the logic already defined in https://github.com/sbt/librarymanagement/blob/v1.1.2/core/src/main/scala/sbt/librarymanagement/VersionNumber.scala (and then re-implement the `VersionNumberCompatibility` implementations in terms of this ordering API).

**Comment by MasseGuillaume** [comment]
see also: https://github.com/scalacenter/versions

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/librarymanagement/pull/239
