### ISSUE TITLE
30% performance degradation in 1.0 due to logger abuse

### ISSUE THREAD

**Issue by pshirshov** [sbt/sbt#3711]
I've noticed ~30% build performance drop since I migrated my stuff to 1.0.

I've investigated that with jprofiler/jvisualvm and found just one hotspot taking ~30% of cpu time. Unexpectedly it's... logging routine:

<img width="930" alt="screen shot 2017-11-04 at 00 50 58" src="https://user-images.githubusercontent.com/295225/32408106-8831958a-c18a-11e7-9034-951daf4b7e29.png">
<img width="935" alt="screen shot 2017-11-04 at 00 51 07" src="https://user-images.githubusercontent.com/295225/32408107-88479cfe-c18a-11e7-8873-d944fe8fb9c0.png">
<img width="1013" alt="screen shot 2017-11-04 at 00 56 57" src="https://user-images.githubusercontent.com/295225/32408108-885cc5a2-c18a-11e7-9a7a-a4ec0cc72f8f.png">
<img width="1088" alt="screen shot 2017-11-04 at 01 19 45" src="https://user-images.githubusercontent.com/295225/32408109-8871916c-c18a-11e7-9f03-94e4c5cecf30.png">
<img width="1093" alt="screen shot 2017-11-04 at 01 19 56" src="https://user-images.githubusercontent.com/295225/32408110-8887106e-c18a-11e7-9d05-30e55abf73f3.png">

Maybe I've misconfigured something but it is the same even for any trivial/empty project.

From what I can understand if you avoid calling `AbstractLogger#log` for log events below logging threshold everything will be okay.

sbt version: 1.0.3

**Comment by godenji** [comment]
@pshirshov what are the results of `sbt -Dsbt.task.timings=true` after a few `compile`s? I see `compileIncremental` and `update` at the top.

Visualvm shows that most of the cpu time is spent in `sbt.io.Hash$.apply` and `Log4j2-TF-1-AsyncLogger[AsyncContext@5bcab519]-1`, this in a mixed Play/Scala.js app with around 30 subprojects.

There's an upstream [Zinc PR](https://github.com/sbt/zinc/pull/371) that should address the hashing issue. This and logging are the top consumers in my experience.

**Comment by pshirshov** [comment]
Please look closer at self time and jprofiler output. I'm okay/happy with all other stuff but there is clean and obvious issue with logger caused by stack processing. Please look closer.

Hash#apply takes just 1sec of self time while logger eats 16 seconds out of 35 seconds build. Default settings, default everything, just empty project with several dependencies added.

**Comment by leonardehrenfried** [comment]
@pshirshov Where do you think would be the best place to filter out the logging events? In `sbt.util.Logger` or `sbt.internal.util.ManagedLogger`?

**Comment by leonardehrenfried** [comment]
Would be pretty easy to write a fix for this. I'd volunteer if there is a chance of it being merged.

**Comment by eed3si9n** [comment]
Thanks for the report, and all the work that went into this.

**Comment by pshirshov** [comment]
@leonardehrenfried from what I can see it would be logical to put it into sbt.util.Logger. Though I may be wrong, I'm not familiar with the codebase.

**Comment by pshirshov** [comment]
why did you move this to 1.0.5? it would be great to make it available asap

**Comment by eed3si9n** [comment]
sbt 1.0.4 will include https://github.com/sbt/util/pull/132 that's been merged, but I am not sure if that alone will solve everything, so I am keeping this open for future 1.0.5.

**Comment by dwijnand** [comment]
I think sbt/util#132 should help. Therefore I think we should keep this targeting 1.0.4, and if there's further work to do we should open a new issue (which can of course link to this prior investigations).

**Comment by pshirshov** [comment]
So, the issue seems to be fixed. Now build time is adequate again. Thanks.
If you wish I may profile a bit more (though it's not a rocket science).

**Comment by eed3si9n** [comment]
Awesome. I'll close this then.
