### ISSUE TITLE
Inconsistent Test Count

### ISSUE THREAD

**Issue by etorreborre** [sbt/sbt#372]
This issue comes primarily from the specs2 project ([issue 62](https://github.com/etorreborre/specs2/issues/62)).

I'm thinking that this could be a sbt issue with some kind of concurrency problem when incrementing the counts [here](https://github.com/harrah/xsbt/blob/0.10/testing/TestReportListener.scala).

**Comment by vigdorchik** [comment]
I think sbt should use AtomicIntegers here, or, since the performance is not so critical - synchronize.

**Comment by etorreborre** [comment]
Thanks for the fix!
