### ISSUE TITLE
Debian packaging missing prerequisite dependency on bc

### ISSUE THREAD

**Issue by jmellor** [sbt/sbt#3728]
Debian packaging is missing a new prerequisite dependency on bc

## steps
normal install of sbt 1.0.3

## problem
Invoking sbt 1.0.3 calls a shell script that uses bc.  bc is normally only installed on a full workstation, and not on a server.  E.g, running sbt on a Jenkins node will fail to start, due to the missing bc utility.

## expectation
no abort.

## notes

sbt version: 1.0.3
This problem does not occur in sbt 1.0.2

**Comment by ritschwumm** [comment]
why using bc and not pure shell in the first place?

**Comment by bhoppi** [comment]
The script should avoid using bc to compare the versions, because in many env it has trouble installing bc, such as bash in Windows.
Please use the more env-compatible command 'expr' instead.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt-launcher-package/pull/199
