### ISSUE TITLE
Test sources and docs are classified as jars

### ISSUE THREAD

**Issue by inkytonik** [sbt/sbt#373]
I just noticed that when I publish-local with 

   publishArtifact in Test := true

then the _test-javadoc._ and _test-sources._ files are put in the jars folder of the Ivy local folder for the project.

I expected to see them in the docs and srcs folders, respectively.

I'm not sure if this will cause any problems (it doesn't seem to, but client projects are presumably not looking for these files).

**Comment by harrah** [comment]
Fixed in 45073ee7f1c37a1a87185127907e8f04a661a777
