### ISSUE TITLE
sbt 1.0.3 unable to update enumeratum-circe

### ISSUE THREAD

**Issue by akauppi** [sbt/sbt#3741]
I prepared a [sample repo](https://github.com/akauppi/sbt-bug-enumeratum-circe) that showcases the problem.

## problem

- `sbt update` fails for the artefact `enumeratum-circe`, on sbt 1.0.3 and 1.0.5 (but succeeds on 0.13.16)

## steps

Clone the repo above. Try `sbt update`. It will fail.

Change `project/build.properties` to use sbt `0.13.16`. Retry. The artefact downloads.

## notes

I did try `updateOptions := updateOptions.value.withGigahorse(false)` as instructed [here](https://github.com/sbt/sbt/issues/3570), and twice it worked, but not consistently. Weird.

**Comment by xuwei-k** [comment]
https://github.com/sbt/sbt/issues/3684 https://github.com/sbt/sbt/issues/3726

**Comment by xuwei-k** [comment]
https://github.com/sbt/sbt/issues/3684#issuecomment-346993442
