### ISSUE TITLE
Homebrew installation failed with Java 9 (JDK 9.0.1)

### ISSUE THREAD

**Issue by aeroxy** [sbt/sbt#3747]
(See the guidelines for contributing, linked above)

## steps
Remove all JDK packages
Install JDK 9.0.1
Run `brew install sbt`

## problem
Installation failed:
sbt: Java 1.8 is required to install this formula.
JavaRequirement unsatisfied!

## expectation
Installation successful

## notes
Homebrew-core
sbt version: *insert sbt version*

**Comment by eed3si9n** [comment]
Hopefully we can address this in 1.0.4.

**Comment by xuwei-k** [comment]
https://github.com/Homebrew/homebrew-core/commit/df32257b65564c43a463bce618747183a5974524

**Comment by dwijnand** [comment]
Optimistically closing as fixed with sbt 1.0.4 and https://github.com/Homebrew/homebrew-core/pull/21052.
