### ISSUE TITLE
Illegal reflective access by org.apache.ivy.util.url.IvyAuthenticator (file:sbt-launch.jar) to field java.net.Authenticator.theAuthenticator

### ISSUE THREAD

**Issue by aeroxy** [sbt/sbt#3748]
(See the guidelines for contributing, linked above)

## steps
Run sbt

## problem
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.ivy.util.url.IvyAuthenticator (file:/usr/local/sbt/bin/sbt-launch.jar) to field java.net.Authenticator.theAuthenticator
WARNING: Please consider reporting this to the maintainers of org.apache.ivy.util.url.IvyAuthenticator
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

## expectation
No WARNING

## notes

sbt version: 1.0.3

**Comment by eed3si9n** [comment]
Duplicate of https://github.com/sbt/sbt/issues/3676.
This will be fixed in 1.0.4.
