### ISSUE TITLE
!: and !! does not work because history does not preserve order

### ISSUE THREAD

**Issue by Blaisorblade** [sbt/sbt#375]
With sbt 0.11.2, whenever I use '!:', the order of entries is unpredictable; therefore !! repeats the last command of an list with unspecified order, i.e. is unusable.

I'd have guessed history entries to be unordered because they were stored in a Set, but it does not seem to be the case (I can see duplicate entries).
If the entries are to be stored in a Set to avoid duplicates, might I suggest a variation of a LinkedHashSet? A variation is needed because when retyping an old command, it must be moved to the end of the Set. That seems implementable on the client side, rather than on the LinkedHashSet itself.

**Comment by harrah** [comment]
Please provide steps to reproduce or use the mailing list for questions.

**Comment by Blaisorblade** [comment]
I was finally\* able to discover that the issue only happens when `-Djline.terminal=jline.UnsupportedTerminal` is used, and that option is forced when using https://github.com/orfjackal/idea-sbt-plugin, which runs sbt inside IntelliJ (without having a proper terminal implementation).

Moreover, the actual issue seems to be that either JLine or SBT, under those conditions, completely disables history management, apparently for no good reason - no terminal support is needed for that. But it's not so clear to me whether and how JLine disables history management in that case, or whether that happens in SBT.

I am reporting the issue against the IntelliJ plugin [1], but it seems that the issue cannot be fixed without altering sbt or JLine themselves.

*I had stopped using SBT outside of IntelliJ for a different issue, which I finally solved.
[1] https://github.com/orfjackal/idea-sbt-plugin/issues/55

**Comment by harrah** [comment]
Thanks for following up.  Note that the `!` commands are provided by sbt, not JLine.  JLine provides things like up/down and ctrl+R, which need terminal support in order to replace the contents of the current line.  It would probably be possible to support the `!` commands even when using UnsupportedTerminal.  This isn't a priority for me, but a pull request would be welcome.
