### ISSUE TITLE
Hive

### ISSUE THREAD

**Issue by ravi5237** [sbt/sbt#3753]
(See the guidelines for contributing, linked above)

## problem

hive> show tables;
FAILED: SemanticException org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient

## expectation

hive> show tables;
FAILED: SemanticException org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient

## notes

sbt version: *insert sbt version*

**Comment by dwijnand** [comment]
This is sbt, not Hive. For Hive you probably want to report it over here: https://issues.apache.org/jira/projects/HIVE.
