### ISSUE TITLE
How to obtain scalaVersion from sbt

### ISSUE THREAD

**Issue by qingwei91** [sbt/sbt#3755]
I am trying to obtain scalaVersion of my project using sbt, and have it available to external tools

## steps
sbt scalaVersion

## problem
The output is not easily parseable, making sbt hard to compose with other terminal tools

## expectation
Can we have an option to change this behaviour, so that sbt can behave more like unix tool that output easy to parse string.

Currently, it outputs the following

```
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /Users/limqingwei/projects/mlb/device-service/project
[info] Loading settings from build.sbt ...
[info] Set current project to device-service (in build file:/Users/limqingwei/projects/mlb/device-service/)
[success] Total time: 2 s, completed 21-Nov-2017 09:41:05
[info] core/*:scalaVersion
[info] 	2.12.4
[INFO] [11/21/2017 09:41:05.207] [Thread-5] [CoordinatedShutdown(akka://sbt-web)] Starting coordinated shutdown from JVM shutdown hook
```

It would be more useful if it outputs something like

```
core/*:scalaVersion: 2.12.4
```

without all the extra logging

## notes

sbt version: *1.0.3*

**Comment by jeffreyolchovy** [comment]
Maybe consider implementing this as your own plugin / command / task?

For example, in your given project, place the following in `project/PrintPlugin.scala`:

```scala
package sbt // necessary as we are accessing package private members

import Keys._
import complete.Parser
import complete.DefaultParsers._
import internal.{Act, Aggregation, SettingCompletions}

object PrintPlugin extends AutoPlugin {

  override def trigger = allRequirements

  override def projectSettings = Seq(commands += print)

  val PrintCommand = "print"

  val printBrief = (PrintCommand, "print fqn key name and value to stdout, separated by ,")

  val printDetailed = s"$PrintCommand <setting>"

  def print: Command = Command(PrintCommand, printBrief, printDetailed)(printParser) {
    case (s, sk) =>
      val extracted = Project.extract(s)
      import extracted._
      val results = Act.keyValues(s)(Seq(sk))
      val keyString = showKey.show(sk)
      Aggregation.printSettings(results, value => println(s"$keyString,$value"))
      s
  }

  // parse a scoped key from user input.
  // unsure what is best, the current impl gives detailed descriptions during tab completion,
  // but one can also use something like: `Space ~> token(Act.scopedKeyParser(extracted))`
  def printParser: State => Parser[ScopedKey[_]] = (s: State) => {
    val extracted = Project.extract(s)
    import extracted._
    Space ~> token(SettingCompletions.scopedKeyParser(structure.index.keyMap, structure.data, currentProject))
  }
}
```

And from your project directory, run the following:

```sh
$ sbt 'print scalaVersion'
[info] Loading project definition from <elided>
[info] Loading settings from foo.sbt ...
[info] Set current project to foo
./.:.::scalaVersion,2.12.4
```

It should work with arbitrary setting keys (and chaining) as well:

```sh
$ sbt ';print scalaVersion ;print sbtVersion ;print version'
[info] Loading project definition from <elided>
[info] Loading settings from foo.sbt ...
[info] Set current project to foo
./.:.::scalaVersion,2.12.4
./.:.::sbtVersion,1.0.4
./.:.::version,0.1-SNAPSHOT
```

[According to the documentation](http://www.scala-sbt.org/1.0/docs/Howto-Logging.html#Change+the+logging+level+globally) you should be able to suppress even the `[info]` stamps by passing `--error` before your args:

> To set the logging level before any commands are executed on startup, use -- before the logging level.

...but that doesn't seem to work (any longer?) with the current version of sbt :( I still see the `[info]` lines at startup, along with an additional warning: `[warn] The `-` command is deprecated in favor of `onFailure` and will be removed in 0.14.0`.

If it did work, you'd pretty much have the functionality you were looking for by using this "plugin". e.g.

```sh
$ sbt --error 'print scalaVersion'
./.:.::scalaVersion,2.12.4
```

There is always `grep -v` for now though...

```sh
$ sbt 'print scalaVersion' | grep -vE '^\[(info|warn|error|debug)\]'
./.:.::scalaVersion,2.12.4
```

**Comment by qingwei91** [comment]
@jeffreyolchovy 
Thanks for your reply, we went down the path of parsing using bash script.
