### ISSUE TITLE
Possible URLHandlerRegistry conflict with fm-sbt-s3-resolver plugin

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#3758]
Tracking upstream https://github.com/sbt/librarymanagement/issues/175.

## notes

sbt version: *1.0.3*

**Comment by tpunder** [comment]
This is fixed via https://github.com/sbt/librarymanagement/pull/183

**Comment by tpunder** [comment]
This is resolved in SBT 1.0.4.  Thanks!
