### ISSUE TITLE
java.library.path is mangled

### ISSUE THREAD

**Issue by tomasjura** [sbt/sbt#3764]
(See the guidelines for contributing, linked above)

## steps
1. setup in build.sbt  java.library.path
val ojdbc_dir = file("/usr/local/oracle/instantclient_12_2")
unmanagedJars in Compile += Attributed.blank( ojdbc_dir / "ojdbc8.jar" )
javaOptions in Compile += s"-Djava.library.path=$ojdbc_dir"

2. invoke console and run a small program which just tries to connect to DB.
Test_JDBC.main(Array("jdbc:oracle:oci:@XE","HR","<password>"))
java.lang.UnsatisfiedLinkError: /tmp/sbt_b98188ad/sbt_66aacc30/libocijdbc12.so: libclntsh.so.12.1: cannot open shared object file: No such file or directory
scala> System.getProperty("java.library.path")
System.getProperty("java.library.path")
res3: String = /usr/local/oracle/instantclient_12_2
// Yes, the sbt was started explicitly with the -Djava.library.path=/usr/local/oracle/instantclient_12_2
// and obviously 
shell>ls -l /usr/local/oracle/instantclient_12_2/libclntsh.so*
-rwxrwxr-x 1 root staff 71638263 led 26  2017 /usr/local/oracle/instantclient_12_2/libclntsh.so.12.1

## problem
sbt tries to do a magic with a classloader and .so loading, which it can't safely do. This task is beyond it's limitations. It can't know what is the expectations of the binary code.
At least there should be an option in sbt to turn the magic off for nontrivial cases. See also:
https://stackoverflow.com/questions/30396853/unsatisfiedlinkerror-native-library-already-loaded-in-another-classloader-in

## expectation
hold the java.library.path set up given in the build.sbt script or environment.

## notes
sbt version: 1.0.3
workaround: LD_LIBRARY_PATH setup is a workround for U*X systems. On Windows setup of PATH probably do the trick.

scala program:

```scala
/*
 This progam serves for tesing the JDBC connection from SCALA.
*/

import scalikejdbc._

object Test_JDBC {
  def main (args: Array[String]): Unit = {
    if ( args.length != 3 ) {
      println("""
program tests an Oracle JDBC connection from a scala program
it dumps list of tables taken from  USER_TABLES system dictionary
usage : Tests_JDBC <jdbc_connection_string> <user> <password>

example: Tests_JDBC jdbc:oracle:oci:@XE" "HR" "password"

or in scala
Test_JDBC.main(Array("jdbc:oracle:oci:@XE","HR","password"))

""")
      return ;
    }
    Class.forName("oracle.jdbc.OracleDriver")
    ConnectionPool.singleton(args(0),args(1),args(2))

    implicit val session=AutoSession
//    sql"select table_name from user_tables".map(rs=>rs.string("table_name")).list.apply().foreach(println)
    println( sql"select table_name from user_tables".map(rs=>rs.string("table_name")).list.apply().mkString("\n"))
  }
}
```

**Comment by eed3si9n** [comment]
This might now be fixed by https://github.com/sbt/zinc/pull/473.
Could you test using sbt 1.1.0-RC4 plz?

**Comment by tomasjura** [comment]
Tested on sbt 1.1.2. It works correctly now.
