### ISSUE TITLE
sbt launch rejects windows java version 1.8 under a cygwin bash session

### ISSUE THREAD

**Issue by philwalk** [sbt/sbt#3769]
(See the guidelines for contributing, linked above)

## steps
launch sbt from a cygwin bash session with windows java version 1.8 in PATH

## problem
symptom with current code is to exit with complaint that java version 1.8 is not new enough

The fix is to modify line 183 of sbt-launch-lib.bash to convert carriage returns to newlines, e.g.:
```
tr '\r' '\n'
```

current code:
```
  java_version=$("$java_cmd" -Xmx512M -version 2>&1 |                grep ' version "' | sed 's/.*version "\([0-9]*\)\(\.[0-9]*\)\{0,1\}\(.*\)*"/\1\2/; 1q')
```
fixed code:
```
  java_version=$("$java_cmd" -Xmx512M -version 2>&1 | tr '\r' '\n' | grep ' version "' | sed 's/.*version "\([0-9]*\)\(\.[0-9]*\)\{0,1\}\(.*\)*"/\1\2/; 1q')
```

line 183 of sbt-launch-lib.bash needs to convert '\r' to '\n' before grepping for 'version'

## expectation
should launch without complaining about java version 1.8

## notes

sbt version: 1.0.3

**Comment by tomasjura** [comment]
I was unhappy with sbt shell launcher, so wrote own [one](https://github.com/sbt/sbt/files/1596440/sbt.txt). Published under MIT licence. Wrote in pure shell, Java 1.9 probably not (yet) supported (copyRt missing).

**Comment by eed3si9n** [comment]
A note to potential contributor: It's here https://github.com/sbt/sbt-launcher-package/blob/cb6bae6c4590a42c92d8c5c93c4b98fcf6322955/src/universal/bin/sbt-launch-lib.bash#L183

**Comment by philwalk** [comment]
Thanks, sorry for the noise.   I guess the alternate launcher is not part of this project, so I'm not sure how I ended up using the alternate launcher in order to encounter the problem.

**Comment by dwijnand** [comment]
Fixed in https://github.com/sbt/sbt-launcher-package/pull/205.
