### ISSUE TITLE
Eviction spam

### ISSUE THREAD

**Issue by japgolly** [sbt/sbt#3773]
(See the guidelines for contributing, linked above)

## steps

In a multi-module project with a significant number of modules and not 100% up-to-date dependencies, (and/or with Scala.JS) run:

```
;clean ;test:compile
```

## problem

Entire screens of spam about eviction notices. Like this:
```
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 	* org.postgresql:postgresql:42.1.4 is selected over 9.4.1211
[warn] 	    +- org.tpolecat:doobie-postgres_2.12:0.4.1            (depends on 9.4.1211)
[warn] 	    +- com.blah.blah-db_2.12:047c51d9c07796d53c6c7cae4301f550f1ac66a1-dev-SNAPSHOT (depends on 9.4.1211)
[warn] 	    +- com.blah.blah:webapp-macro_2.12:047c51d9c07796d53c6c7cae4301f550f1ac66a1-dev-SNAPSHOT (depends on 9.4.1211)
[warn] 	* com.google.auth:google-auth-library-credentials:0.7.1 is selected over 0.4.0
[warn] 	    +- com.github.japgolly.fork.google-cloud-trace.v1:grpc-consumer:0.3.3 (depends on 0.7.1)
[warn] 	    +- com.google.auth:google-auth-library-oauth2-http:0.7.1 (depends on 0.7.1)
[warn] 	    +- io.grpc:grpc-auth:1.5.0                            (depends on 0.4.0)
[warn] 	* com.google.code.findbugs:jsr305:3.0.0 is selected over 1.3.9
[warn] 	    +- com.google.instrumentation:instrumentation-api:0.4.3 (depends on 3.0.0)
[warn] 	    +- io.grpc:grpc-core:1.5.0                            (depends on 3.0.0)
[warn] 	    +- com.google.http-client:google-http-client:1.19.0   (depends on 1.3.9)
```

"some are suspected to be binary incompatible" ← yeah well SBT, you're wrong in nearly all cases. Most libraries don't follow semver religiously if at all. Plus incompatibility depends on the API portion in use.

Since 0.13.16 (and to be clear: in 1.0.4),
* It prints every time you clean-compile
* It prints a lot

## expectation

* 0.13.15 had this behaviour right: when you first start SBT it shows you a small summary of eviction notices then it leaves you alone. I could clean-compile and still see what was going on in my console, and be able to see the compilation output.
* The warnings are too big. They shouldn't print the whole tree and then say `Run 'evicted' to see detailed eviction warnings`. It makes more sense just to list one line per library and then if someone wants, they can run `evicted` as instructed to the tree.

## notes

Related side-note: I get ScalaCSS users complaining that SBT is incorrectly telling them scalajs-react is incompatible with scalacss which is rubbish (*I know the details of these libraries' interaction*). I have to repeatedly defend against the idea of meaninglessly releasing ScalaCSS every time I update scalajs-react, and I have to repeatedly tell users that SBT is wrong.

**Comment by dwijnand** [comment]
Here was requesting issue: https://github.com/sbt/sbt/issues/2699 (and PR https://github.com/sbt/sbt/pull/3204).

One angle to improve the status quo we're thinking is by defining an "abiVersion", https://github.com/sbt/sbt/issues/3562, which we've tentatively added to the 1.2.0 milestone.

**Comment by eed3si9n** [comment]
A note to potential contributor:

It would be good to provide a setting that can globally opt out of eviction warning during `update`. There's a setting already called `evictionWarningOptions in update`.

```scala
    evictionWarningOptions in update := EvictionWarningOptions.default,
```

First step might be to change the project level to:

```scala
    evictionWarningOptions in update := (evictionWarningOptions in update).value,
```

and add an assignment for the setting at global level.

Next, we could add `EvictionWarningOptions.summary` that tells the users to call "evicted".

**Comment by dwijnand** [comment]
> First step might be to change the project level to:
> 
>     evictionWarningOptions in update := (evictionWarningOptions in update).value,
> and add an assignment for the setting at global level.

I don't understand what you mean, the code block looks like a circular definition.

**Comment by cbrunnkvist** [comment]
@dwijnand I suppose what @eed3si9n meant was, in a slightly fuller example:
```
evictionWarningOptions in update := EvictionWarningOptions.default
    .withWarnTransitiveEvictions(false)

mySubProject.settings(
  evictionWarningOptions in update := (evictionWarningOptions in update).value
)
```
which as far as I can tell doesn't turn out to be circular, since (x in scope).value apparently evaluates in the global scope _before_ the value in current project in update is assigned in the current project. 

Classic n-dimensional SBT mess IMO.

**Comment by eed3si9n** [comment]
Yes.

```scala
Global / update / evictionWarningOptions := EvictionWarningOptions.default
    .withWarnTransitiveEvictions(false)

lazy val foo = project
  .settings(
    update / evictionWarningOptions := (update / evictionWarningOptions).value,
  )
```

RHS should delegate to globally scoped evictionWarningOptions.

**Comment by eed3si9n** [comment]
sbt 1.2.0-RC1 is now out that defaults to summary mode.
