### ISSUE TITLE
sbt 1.0 - offline package command fail with spark-core dependency

### ISSUE THREAD

**Issue by ozmad** [sbt/sbt#3778]
(See the guidelines for contributing, linked above)

## steps
- create simple project by running: 
   sbt new sbt/scala-seed.g8
- add dependency in build.sbt: 
   libraryDependencies += "org.apache.spark" %% "spark-core" % "2.2.0"
- run sbt
- in sbt:
   - clean
   - package
   - set offline := true
   - clean
   - package

[sbt-proj.zip](https://github.com/sbt/sbt/files/1511663/sbt-proj.zip)

## problem
Dependency not found in offline mode. This error is specific for spark-core and might be relevant for other libs, but it isn't happen for all (e.g in the attached zip file you can find "jackson" dependency that works fine)

## expectation
To be able to work offline.

## notes
- attached: zip file of the project
- running on ubuntu 16.04 with java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
- it might be a transitive dependency that isn't stored in ivy2 cache

sbt version: *1.0.2*

**Comment by Benji81** [comment]
Hi @ozmad same problem here (1.0.3 and 1.1.1). Did you solve it?

**Comment by ozmad** [comment]
@Benji81  unfortunately no. I gave up working offline this way. I've installed a local Artifactory service as a proxy to the real repositories.
It required explicit adding it in build.sbt instead of the default scala and maven public repositories.
when I'm online the Artifactory keeps a copy of downloaded files, this way I can compile even when offline.
I used the following (ugly) trick to allow running with the local Artifactory if it is running and with remote otherwise:
```
val repos: Array[String] = Try(scala.io.Source.fromURL(localArtifactoryUrl)) match {
	case Success(bufSrc) =>
		println(s"************ found local repository: $localArtifactoryUrl")
		bufSrc.close()
		Array(localArtifactoryUrl,
			s"$localArtifactoryUrl/maven2",
			s"$localArtifactoryUrl/sbt-plugins/",
			s"$localArtifactoryUrl/sonatype/",
			s"$localArtifactoryUrl/typesafe/")

	case Failure(_) =>
		Array(equalumArtifactoryUrl,
			"https://repo1.maven.org/maven2/",
			"https://dl.bintray.com/sbt/sbt-plugin-releases/",
			"https://oss.sonatype.org/content/repositories/releases/",
			"https://repo.typesafe.com/typesafe/ivy-releases/")
}

val artifactoryUrl = repos(0)
val mavenRepoUrl = repos(1)
val sbtPluginsRepoUrl = repos(2)
val sonaTypeRepoUrl = repos(3)
val typesafeRepoUrl = repos(4)
 
```

**Comment by Benji81** [comment]
@ozmad thanks for your answer. I'll continue my research

**Comment by Benji81** [comment]
Hi @ozmad, I have installed the coursier plugin (https://github.com/coursier/coursier) in the sbt plugin file and it seems to work. Maybe a better cache management.

**Comment by eed3si9n** [comment]
This works with sbt 1.3.0-RC3 that uses Coursier internally.
