### ISSUE TITLE
Significant performance regression between SBT 0.13.16 and 1.0.4 for the singleton-ops library

### ISSUE THREAD

**Issue by soronpo** [sbt/sbt#3783]
The [singleton-ops library](https://github.com/fthomas/singleton-ops) suffers from long build (& test) times after moving to SBT 1.0.4 from 0.13.16.  

[Travis build with SBT 1.0.4](https://travis-ci.org/fthomas/singleton-ops/builds/308911207) 
Documented build times:
 - Scala 2.11.11: 34min.
 - Scala 2.12.4: 28min.

[Travis build with SBT 0.13.16](https://travis-ci.org/fthomas/singleton-ops/builds/309206517)
Documented build times:
 - Scala 2.11.11: 20min.
 - Scala 2.12.4: 20min.

## steps
I cleared the Travis cache and ran the build with the following commits:
* Use [this commit](https://github.com/fthomas/singleton-ops/pull/42/commits/9c3b04b79a291ec0ffe0311c74fd8da3a14124ca) to build singleton-ops with SBT 1.0.4

* Use [this commit](https://github.com/fthomas/singleton-ops/pull/44/commits/b3febe4ad2a1ada832e9fc0fcd5625641760dc3b) to build singleton-ops with SBT 0.13.16

## problem
The build for SBT 1.0.4 takes 40% more time on Scala 2.12.4 and **70%(!)** more time on Scala 2.11.11.
Additionally, after running and testing the builds a few times, the build is more likely to hang with SBT 1.0.4, triggering the 50min. timeout for the build job in Travis.

## expectation
Please return build times more closer to what they were.

## notes

sbt version: 1.0.4

**Comment by eed3si9n** [comment]
Thanks for the report. Having repro project like this is very helpful.

**Comment by soronpo** [comment]
Fixed long ago in some 1.x.x SBT version
