### ISSUE TITLE
sbt blows up when publishing, during basic auth, if the username or password is too long

### ISSUE THREAD

**Issue by sclasen** [sbt/sbt#379]
Looks like the base64encoder is inserting newlines after a certain number of characters, which breaks basic auth(Maven is broken in an identical way)

java.lang.IllegalArgumentException: Illegal character(s) in message header value: Basic 

scott$ cat build.sbt 

publishTo := Some("repo" at "https://oss.sonatype.org/service/local/staging/deploy/maven2/")

credentials += Credentials("Sonatype Nexus Repository Manager", "oss.sonatype.org", "someUsername", "someLooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooongPassword")

scott$ sbt publish
[info] Set current project to default-90e060 (in build file:/Users/scott/dev/heroku/ffs/)
[info] Updating {file:/Users/scott/dev/heroku/ffs/}default-90e060...
[info] Wrote /Users/scott/dev/heroku/ffs/target/scala-2.9.1/default-90e060_2.9.1-0.1.pom
[info] Done updating.
[info] :: delivering :: default#default-90e060_2.9.1;0.1 :: 0.1 :: release :: Wed Feb 22 16:25:49 PST 2012
[info]  delivering ivy file to /Users/scott/dev/heroku/ffs/target/scala-2.9.1/ivy-0.1.xml
[error] {file:/Users/scott/dev/heroku/ffs/}default-90e060/*:publish: java.lang.IllegalArgumentException: Illegal character(s) in message header value: Basic c29tZVVzZXJuYW1lOnNvbWVMb29vb29vb29vb29vb29vb29vb29vb29vb29vb29vb29vb29vb29v
[error] b29vb29vb29vb29vb29vb29vb29vb29vb29vb29vb29vb25nUGFzc3dvcmQ=
[error] Total time: 1 s, completed Feb 22, 2012 4:25:50 PM

**Comment by harrah** [comment]
http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=6947917

**Comment by sclasen** [comment]
Right, I saw that bug, but its definitely possible to make an HTTP request from a JVM using BasicAuth/Base64Encoder with long credentials and not hit this bug, if you are willing to write code/use libs do do so... 

So does closing this without comment mean not worth fixing or wont accept a fix or what?

**Comment by harrah** [comment]
Sorry for not elaborating.  Yes, many things are fixable by writing more code and we do workaround third party libraries in some cases.  This issue is several steps removed from sbt (sbt -> Ivy -> httpclient -> Java SDK), which makes it rather unlikely that it can be worked around reasonably.  A patch would probably accepted if it doesn't have to reimplement parts of Ivy/httpclient.

**Comment by softprops** [comment]
damn. I just ran into this!

**Comment by softprops** [comment]
If anyone else lands here. _Don't try to patch this in HttpUrlConnection_. You will fail. Instead the problem can be worked around by defining your own [custom resolver](https://github.com/softprops/bintray-sbt/blob/master/src/main/scala/resolver.scala#L14-L16) and using it via sbt's `RawRespository(resolver)` interface
