### ISSUE TITLE
ncurses throws expcetion with 0.13.15 (Also not colour in terminal)

### ISSUE THREAD

**Issue by Fenwick17** [sbt/sbt#3796]
(See the guidelines for contributing, linked above)

## steps
Run `sbt test` with ncurses-6.0+20170902-3 and sbt 0.13.15

## problem
I am using sbt 0.13.15 as our application has dependencies set for this, and I had to update ncurses to the latest version due to another OS issue. When doing this my terminal throws an exception before running `sbt test` `java.lang.NumberFormatException: For input string: "0x100"` However test does run successfully. Further issue is there is no longer any colour code in the command, no green/red for tests.

## expectation
Sbt to run without error and colour green or red for each test

## notes

sbt version: Installed 1.1.2-1. Application is locked to 0.13.15
ncurses version ncurses-6.0+20170902-3

**Comment by Fenwick17** [comment]
Downgraded ncurses has worked (OS issue currently not occuring)

**Comment by Fenwick17** [comment]
Turns out the OS issue I have is with `libtinfo` which is resolved by using the latest version of `ncurses` which means my issue still occurs

**Comment by dwijnand** [comment]
This is https://github.com/sbt/sbt/issues/3240, which was fixed in sbt 0.13.16.

What's the reason you can't upgrade to 0.13.16?

**Comment by Fenwick17** [comment]
@dwijnand It appears moving to 0.13.16 seems to be fine for sbt. I tried the latest sbt, but I think that was too much of a jump for the project.
