### ISSUE TITLE
Documentation mentions Project.settingsSets which no longer exists, no alternative given

### ISSUE THREAD

**Issue by mechkg** [sbt/sbt#3797]
See http://www.scala-sbt.org/1.0/docs/Setting-Initialization.html

I was looking for a way to override some of the sub-project settings specified in their internal build.sbt files from the top-level build.sbt.

settingsSets looked like something that would allow me to do that, why was it removed? Is there any alternative way of changing the order of how the settings are applied (at the moment it seems like subprojects' build.sbt always override the main build.sbt)?

## notes

sbt version: 1.0.4

**Comment by dwijnand** [comment]
Here's the issue that lead to the removal: https://github.com/sbt/sbt/issues/2617.

**Comment by mechkg** [comment]
Do I understand correctly that with this change it is no longer possible to
override settings pulled from sub-projects?

Related SO question: https://stackoverflow.com/questions/47662021/how-to-change-the-order-in-which-settings-are-applied-to-an-sbt-subproject

**Comment by dwijnand** [comment]
I'm not sure what you mean exactly by "override settings pulled from sub-projects", but it's no longer possible to customise the order in which sbt loads settings, at a project level (http://www.scala-sbt.org/1.0/docs/Setting-Initialization.html#Controlling+Initialization).
