### ISSUE TITLE
Allow subprojects to define their own plugins

### ISSUE THREAD

**Issue by n3ziniuka5** [sbt/sbt#3798]
## problem
At my workplace, we are currently moving to a monorepo approach. We manage dependencies with internal artifactory and when you have project dependencies such as A -> B -> C and need to constantly make changes and test for example modules A and C, it gets a bit tedious with artifact publishing and updating, that's the main reason we are moving to monorepo with a single root `build.sbt` and many subprojects.

The issue we face now is that we have 3 subprojects that are based on different versions of play framework. On of the projects runs a much older version of play and we only update that project with bugfixes, but we are not adding any new features to that code so there is no need to upgrade to a more recent play version. Also, that subproject depends on other subprojects, so moving it our to a separate repo brings back the problems we had before. 

## expectation

It would be great to be able to define plugins at `<root>/subproject/project/plugins.sbt`, that would allow us to use different plugins for different subprojects.

**Comment by dwijnand** [comment]
There is no classpath isolation of plugins between different projects of a build, and adding that isn't feasible.

What I suggest you look at doing is creating multiple builds within the repository and use source dependencies between projects of different builds, for example something like:

**projA/build.sbt**
```scala
val projA = project dependsOn ProjectRef(file(".").getParentFile / "projB", "projB")
```

**projB/build.sbt**
```scala
val projB = project dependsOn ProjectRef(file(".").getParentFile / "projC", "projC")
```

**projC/build.sbt**
```scala
val projC = project
```

That way your different Play apps are distinct builds, with distinct plugin versions.
