### ISSUE TITLE
nix scala-tools resolver and add a new default

### ISSUE THREAD

**Issue by softprops** [sbt/sbt#380]
If scala-tools is on the way out, which I heard is, we should start thinking about a new default and clean up [these references](https://github.com/harrah/xsbt/search?choice=code&langOverride=&q=ScalaToolsReleases&start=&start_value=2)

I also propose a new default, SbtPluginReleases,

```
Resolver.url("sbt-plugin-releases",
  new URL("http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases/"))(
    Resolver.ivyStylePatterns)
```

 which could go somewhere [near here](https://github.com/harrah/xsbt/blob/3ed1bdda22672356f23a82a56b23e1ec69df5eec/ivy/IvyInterface.scala#L150).

As more an more plugins migrate their artifacts here, it will make more and more sense for people not to have to explicitly add it to new projects.

I can get cracking on this after I migrate my projects to new homes.

**Comment by harrah** [comment]
Those references are from all of history.  scala-tools is already removed from the default list in 0.12.0-M1.  The new default is welcome.  It should only be added by default when sbtPlugin := true.
