### ISSUE TITLE
File URIs sent by server is incompatible with editors that expect RFC 3986

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3801]
## steps

run server, and compile.

## problem
 
```
langNotify: JsonRpcNotificationMessage(2.0, textDocument/publishDiagnostics,
{"uri":"file:/Users/xxx/work/hellotest/Hello.scala","diagnostics":[{"range":{"start":{"line":1,"character":21},"end":{"line":1,"character":22}},"severity":1,"source":"sbt","message":"not found: value bar"}]})
```

## expectation

```
langNotify: JsonRpcNotificationMessage(2.0, textDocument/publishDiagnostics, 
{"uri":"file:///Users/xxx/work/hellotest/Hello.scala","diagnostics":[{"range":{"start":{"line":1,"character":21},"end":{"line":1,"character":22}},"severity":1,"source":"sbt","message":"not found: value bar"}]})
```

`file:///`

This was also reported in https://github.com/sbt/sbt/issues/3702

## notes

Under RFC 8089, published in February 2017, an aboslute POSIX file path can be encoded into URI in two different ways.

First is `file:/etc/hosts` with no authority field. Let's call this u1 notation. u1 is the new, minimal representation, and it's what we have been doing (i.e via `f.toURI`) by accident.

Second is `file:///etc/hosts` with an empty authority field. Let's call this u3 notation. u3 is how traditionally file path were supposed to be represented in RFC 3986 (2005) and Kerwin draft (2013). Due to sbt server, we are going to interface non-JVM systems that might not be up to RFC 8089.

For example, Vim's LSP sends URI using u3 `{"textDocument":{"uri":"file:///Users/foo/work/hellotest/Hello.scala"}})`, and more importantly it also *expects* u3 for the compiler error messages to be notified correctly.

https://github.com/sbt/sbt/issues/3702 reported that Atom also expected u3 notation until https://github.com/atom/atom-languageclient/pull/129 fixed it.

I've confirmed that Vim's LSP plugin issue was resolved with this patch and some changes to use it on sbt/sbt.

**Comment by laughedelic** [comment]
I thought it works well in VSCode. I also fixed it in atom-languageclient library. Both formats are valid URIs.

**Comment by eed3si9n** [comment]
You are right that single slash (I call them u1 notation) is recommended/correct under [RFC 8089](https://tools.ietf.org/html/rfc8089), published in February 2017.

But previous [RFC 3986](https://tools.ietf.org/html/rfc3986) or 2013 Kerwin Draft (https://tools.ietf.org/id/draft-kerwin-file-scheme-07.html) uses /// (u3 notation):

```
file:///etc/hosts
```

For the sake of compatibility, I think it would be better if sbt used u3 notation which is also permitted under RFC 8089 https://tools.ietf.org/html/rfc8089#section-2:

> To maximize compatibility with
>  previous specifications, users MAY choose to include an "auth-path"
>  with no "file-auth" when creating a URI.

**Comment by laughedelic** [comment]
👍 I was just confused by the word "wrong" in the initial issue title.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/3805 etc.
