### ISSUE TITLE
Broken (?) transitive dependencies handling with non-default classifiers

### ISSUE THREAD

**Issue by nrinaudo** [sbt/sbt#3803]
## steps
Set up a project such that:

- module `a` depends on library `b` that depends on `lib classifier tests`
- module `a` depends on library `c` that depends on `lib`

## problem

Inspecting the `dependencyClasspath`, I observe that `lib` is only present in its "non-classified" version (that is, `lib classifier tests` is absent from the CLASSPATH).

## expectation

I would expect both `lib` and `lib classifier tests` to be present on the CLASSPATH.

## notes

Coursier (v 1.00-RC12) behaves that way I'd expect, not the way vanilla SBT does.

Making the dependencies explicit, rather than relying on transitive dependencies, fixes the issue.

See [this](https://gitter.im/sbt/sbt?at=5a27faf83ae2aa6b3f932a5f) gitter conversation.

sbt version: 1.0.4

**Comment by eed3si9n** [comment]
I'm going to close this since sbt 1.3.0-RC3 uses Coursier internally.
