### ISSUE TITLE
"Error: Unable to access jar file" on Windows + JDK 9

### ISSUE THREAD

**Issue by svj13** [sbt/sbt#3804]
I am using windows powershell and trying to use sbt.

Attached is an image of my error. I think it has something to do with "1.0.4" being encapsulated in quotes, but am unsure. I am also unsure as to how to remove these quotes from the file path 

![image](https://user-images.githubusercontent.com/18566065/33812642-a79d2568-de83-11e7-938c-452b74c1219e.png)

**Comment by martijnhoekstra** [comment]
as a workaround, run from `cmd`

**Comment by svj13** [comment]
@martijnhoekstra  The same error occurs in cmd

**Comment by timurgen** [comment]
Same error occurs in both CMD and Powershell, GIT bash shell works OK.

**Comment by eed3si9n** [comment]
Thanks for reporting this. The quote does seem odd.
In terms of the actual access, is the `.sbt\preloaded\` directory under your access? Can you `cd` into it etc?

**Comment by eed3si9n** [comment]
There's a quote at line 56:

```
set INIT_SBT_VERSION="1.0.4"
```

That's likely the problem.

**Comment by dwijnand** [comment]
It's not the only problem, but anyways we can fix it with https://github.com/sbt/sbt-launcher-package/pull/200.

**Comment by eed3si9n** [comment]
I have a repro on AppVeyor - https://ci.appveyor.com/project/eed3si9n/sbt-launcher-package/build/1.0.30

```
C:\projects\sbt-launcher-package\citest>"freshly-baked\sbt\bin\sbt" check 
Error: Unable to access jarfile 
Copying runtime jar.
The filename, directory name, or volume label syntax is incorrect.
Error: Unable to access jarfile 
"C:\Users\appveyor\.sbt\preloaded\org.scala-sbt\sbt\1.0.4\jars\sbt.jar"
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
[info] Loading project definition from C:\projects\sbt-launcher-package\citest\project
[info] Loading settings from build.sbt ...
[info] Set current project to Hello (in build file:/C:/projects/sbt-launcher-package/citest/)
```

**Comment by aaccioly** [comment]
Hi @eed3si9n and @dwijnand.

Looks like  `:copyrt` is still not working correctly after applying https://github.com/sbt/sbt-launcher-package/pull/201.

**Environment:** Windows 10 + JDK 9+  CMD or PowerShell

```
C:\Users\Anthony\test>sbt sbtVersion
Error: Unable to access jarfile C:\Program
Copying runtime jar.
The filename, directory name, or volume label syntax is incorrect.
Error: Unable to access jarfile C:\Program
[warn] No sbt.version set in project/build.properties, base directory: C:\Users\Anthony\test
[info] Set current project to test (in build file:/C:/Users/Anthony/test/)
[info] 1.0.2
```
Removing double quotes around `"!rtexport!"` fixed the issue for me. 

```batchfile
:copyrt
if /I "%JAVA_VERSION%" GEQ "9" (
  set rtexport="%SBT_HOME%java9-rt-export.jar"

  "%_JAVACMD%" %_JAVA_OPTS% %SBT_OPTS% -jar !rtexport! --rt-ext-dir > "%TEMP%.\rtext.txt"
  set /p java9_ext= < "%TEMP%.\rtext.txt"
  set java9_rt=!java9_ext!\rt.jar

  if not exist "!java9_rt!" (
    echo Copying runtime jar.
    mkdir "!java9_ext!"
    "%_JAVACMD%" %_JAVA_OPTS% %SBT_OPTS% -jar !rtexport! "!java9_rt!"
  )
  set _JAVA_OPTS=!_JAVA_OPTS! -Dscala.ext.dirs="!java9_ext!"
)
exit /B 0
```
While I was testing with 1.0.2, I think that this will be an issue with 1.1.0 as well. Can you please double check?

**Comment by eed3si9n** [comment]
@aaccioly Your observation makes sense because I've removed the double quotes for `set java9_rt`, but not `set rtexport`. The line I have to fix is line 132.

**Comment by aaccioly** [comment]
@eed3si9n, good catch. `set rtexport=!SBT_HOME!java9-rt-export.jar` works for me if I reinsert the double quotes.

```batchfile
> echo "!rtexport!"
"C:\Program Files (x86)\sbt\bin\java9-rt-export.jar"
```

**Comment by eed3si9n** [comment]
sbt 1.1.0 uses the latest launcher package so this should be fixed now.

**Comment by gaeljw** [comment]
I'm having the same error after upgrading Java from 8 to 11 but I'm on Linux (Fedora) and running sbt 1.4.

Everything works fine but this message at sbt startup:

```
Error: Unable to access jarfile /usr/bin/java9-rt-export.jar
copying runtime jar...
mkdir: unable to create directory «  »: no such file or directory
Error: Unable to access jarfile /usr/bin/java9-rt-export.jar
```
