### ISSUE TITLE
"Can not initialize cryptographic mechanism" on OpenJDK 9

### ISSUE THREAD

**Issue by vvasuki** [sbt/sbt#3806]
sbt 1.0.4 and 1.1.0-RC failed to work with open jdk 1.9, but worked fine when open jdk 1.8 (build 1.8.0_151-8u151-b12-0ubuntu0.17.10.2-b12 or oracle jdk 9 (build 9.0.1+11) were installed.

Log: https://pastebin.com/raw/UzX2DX7P .

(I don't know if you knew of this problem already - wanted to let you know just in case.)

**Comment by eed3si9n** [comment]
The log says:

```
Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:118)
```

This is https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=866924 (https://github.com/docker-library/openjdk/issues/101)

Could you try the following workaround:

```
$ ([[ ! -d $JAVA_HOME/conf ]] && ln -s $JAVA_HOME/lib $JAVA_HOME/conf)
```

**Comment by vvasuki** [comment]
Ah I see - I gave up on the openjdk9 setup and would have to reinstall it on my computer to check (which I don't want to) - So, I'm fine with closing this bug for now. 🙏

**Comment by eed3si9n** [comment]
I'm closing this for now as upstream issue.
