### ISSUE TITLE
Faiures should identify something tangible (and use real words)

### ISSUE THREAD

**Issue by paulp** [sbt/sbt#381]
This is a transcript of the scala build if I change the sbt version to 0.12.0-M1.  I understand that most of this output must be coming from some plugin.  But sbt could at least tell me something, like what plugin that is, or even that a plugin is involved.  As it stands I'm there with a broken build, the failure "module not found: org.scala-tools.sbt#scripted-plugin", and the empirically derived knowledge that scripted-plugin is used exactly nowhere.  (I realize it must be being used transitively, these being exactly the dots I would like sbt to connect.)

Also, who is the audience for default-2ac879, eff7d7476f58ab859d23, default-9f14df in console output? Is sbt being used by super-robots to build the next generation of death-dealing automatons? Am I the last of the puny flesh beings, the only one who can't pronounce 2ac879 but would still like to know what's happening, a lone McCoy in a world of Spocks? Is the code being built in secret underground laboratory 2A-C879 so thoroughly anonymous that no meaningful label is possible? Dammit Jim, I'm a programmer, not a hexadecimal scanner.

```
[info] Loading project definition from /scratch/trunk1/project/project
[info] Updating {file:/scratch/trunk1/project/project/}default-2ac879...
... snip 38 lines of resolving ...
[info] Done updating.
Cloning into '/Users/paulp/.sbt/0.12.0-M1/staging/eff7d7476f58ab859d23'...
[info] Loading project definition from /Users/paulp/.sbt/0.12.0-M1/staging/eff7d7476f58ab859d23/project
[info] Updating {file:/Users/paulp/.sbt/0.12.0-M1/staging/eff7d7476f58ab859d23/project/}default-9f14df...
[info] Resolving org.scala-tools.sbt#scripted-plugin_2.9.1;0.12.0-M1 ...
[warn]  module not found: org.scala-tools.sbt#scripted-plugin_2.9.1;0.12.0-M1

... blah blah lots more resolving
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scala-tools.sbt#scripted-plugin_2.9.1;0.12.0-M1: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[error] {file:/Users/paulp/.sbt/0.12.0-M1/staging/eff7d7476f58ab859d23/project/}default-9f14df/*:update: sbt.ResolveException: unresolved dependency: org.scala-tools.sbt#scripted-plugin_2.9.1;0.12.0-M1: not found
```

**Comment by jsuereth** [comment]
Can we rename this to:  Source dependencies need better error messages?  Right now they're still second class citizens.

**Comment by eed3si9n** [comment]
New management. We need repro steps to work on this.

**Comment by eed3si9n** [comment]
Closing this case, but we can continue at #1422.
