### ISSUE TITLE
Scripted name clashing

### ISSUE THREAD

**Issue by doncorsean-private** [sbt/sbt#3812]
#https://github.com/foundweekends/giter8/issues/360

# problem
Scripted is hardcoded to use a file called `test`. When using giter8 to create a play template with a `test` folder the scripted tests fail as scripted finds the `test` dir and not the script named `test` 

## expectation
be able to run scripted tests against projects that define a test directory. could be as simple as changing the filename scripted is looking for to scriptedTest or similar.

**Comment by xuwei-k** [comment]
https://github.com/sbt/sbt/issues/630 ?

**Comment by dwijnand** [comment]
Oh wow, a three digit issue.

Duplicate of #630.
