### ISSUE TITLE
Transitive plugin with extra fails to resolve

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#382]
## steps

I'm using 0.11.2.
Here's what I have in sbt-appengine's build.sbt:

``` scala
libraryDependencies <++= (scalaVersion, sbtVersion) { (scalaV, sv) => Seq(
  "com.github.siasia" %% "xsbt-web-plugin" % (sv + "-0.2.10"),
  "cc.spray" % "sbt-revolver" % "0.6.0" extra("scalaVersion" -> scalaV, "sbtVersion" -> sv)
)}

resolvers += "Maven.org" at "http://repo1.maven.org/maven2"

resolvers += "spray repo" at "http://repo.spray.cc"
```

They can be resolved fine when I am compiling the plugin.
## problem

When sbt-appengine is used from another build, I get error message:

``` scala
update: sbt.ResolveException: unresolved dependency: cc.spray#sbt-revolver;0.6.0: not found
```

This can be resolved by adding the resolver explicitly:

``` scala
resolvers += "spray repo" at "http://repo.spray.cc"
```
## expectation

The resolver should not be necessary, since it's already in the pom.
## note
- Here's the [pom.xml](https://gist.github.com/1900575).
- Related issue: #212

**Comment by harrah** [comment]
This is standard behavior for normal dependencies as well.  Resolvers are ignored in a pom.xml.

**Comment by pwendell** [comment]
Does this mean that any project which depends on new repositories requires users to add those resolvers manually to the build? We (Spark) also depend on Typesafe - so basicaly this means we have to have people add typesafe manually to their resolvers in addition to specifying the dependency on Spark?
