### ISSUE TITLE
Starting multiple instances of sbt gives: java.io.IOException: sbt server is already running.

### ISSUE THREAD

**Issue by gavares** [sbt/sbt#3823]
## steps
In a single project directory, start multiple instances of sbt

## problem
The 2nd instance of sbt logs an error with message: `java.io.IOException: sbt server is already running.`

## expectation
No error is logged. The sbt instances should either share the sbt server or start separate instances. Either way, no error should be logged.

## notes

sbt version: 1.1.0-RC2

**Comment by gavares** [comment]
The original sbt instances logs the following into the sbt shell after the 2nd instance starts:
```
[master] run [info] new client connected: network-1
[info] new client connected: network-2
```

Notice the logging is inserted into my prompt entry inside the REPL. I was just about to type `run` and before I pressed enter, the log message showed up.

**Comment by gavares** [comment]
A little more info, the IOException is actually printed at the end of each command executed in the repl.

**Comment by eed3si9n** [comment]
Generally speaking, running multiple instances of sbt on a single build is unsupported and dangerous (as in we can't really guarantee any behavior to be correct), so maybe we should display a warning at startup to the effect.

I'll also look into if it's possible to avoid trying to run server over and over again.

**Comment by gavares** [comment]
Hi Eugene,

  Thanks for taking a look at this.

   We have a number of use cases for running multiple sbt instances in a
project. I was hoping that the shift to a client server model was going to
improve the experience around this a bit  by letting the multiple sbt
shells share a warm/jitted backend jvm and faster shell startup time. I
think Gradle benefits from something like this.

If the sbt process starts and stops a new server each time it starts and
exits, what is the benefit of having the background server exactly?

As for our usage, we sometimes start sever instances in one she'll and then
run tests against that instance in another. Without multiple shells, I
suppose we'd need to invest some time in `bgRun` and getting all of that
wired up properly. Not trivial with Play applications. We also lose a bit
shell interactivity with the process as well as easily consumable logging
output since we would need to send logs to a file.

Just wanted to give some info about how/why we use sbt this way.

**Comment by eed3si9n** [comment]
> As for our usage, we sometimes start sever instances in one she'll and then
run tests against that instance in another. 

Our eventual goal is to support usage like that by connecting to a running sbt server.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/3828
