### ISSUE TITLE
It's not possible to order sbt.complete.Completions

### ISSUE THREAD

**Issue by MasseGuillaume** [sbt/sbt#3829]
The signature is:

https://github.com/sbt/sbt/blob/34d311f9cef2732d0427060fd7c8e704a46cba52/internal/util-complete/src/main/scala/sbt/internal/util/complete/Completions.scala#L17

this does not allow an ordering.

https://github.com/sbt/sbt/blob/34d311f9cef2732d0427060fd7c8e704a46cba52/internal/util-complete/src/main/scala/sbt/internal/util/complete/JLineCompletion.scala#L82

but the underlying implementation can be ordered

**Comment by dwijnand** [comment]
What's the use-case here, given those signatures are internal only?

**Comment by MasseGuillaume** [comment]
I want to simulate the `git diff <tab>` output.
https://github.com/scalacenter/scalafix/pull/520#discussion_r157899629

There is a list of the last 20 commits.

**Comment by dwijnand** [comment]
Looks like the whole completion library is internal, which makes it very hard to use.. 😄

https://github.com/sbt/sbt/tree/v1.0.4/internal/util-complete/src/main/scala/sbt

**Comment by MasseGuillaume** [comment]
I found a workaround. The display is sorted
https://github.com/sbt/sbt/blob/34d311f9cef2732d0427060fd7c8e704a46cba52/internal/util-complete/src/main/scala/sbt/internal/util/complete/JLineCompletion.scala#L88

```
scalafix --diff-base 
0.1.0                                                                    
0.2.0                                                                    
HEAD                                                                     
master                                                                   
origin/HEAD                                                              
origin/bloop                                                             
origin/master                                                            
sonatype                                                                 
|0| a3b691b7 -- 0.2.0 (2 weeks ago)                                      
|1| bccb7763 -- split SemanticVersion and Version implemtation (2 weeks a
|2| 8d8f4bf3 -- Merge pull request #2 from auroredea/bintray (2 weeks ago
|3| 776ba793 -- Add bintray repo (2 weeks ago)                           
|4| 2d6f3e85 -- Import from Scaladex (2 weeks ago) 
```

**Comment by dwijnand** [comment]
Yep, Set exposes an iterator, that does have a stable order (or at least I think iterators should have a stable order). So it's more like a sequence without duplicates, where adding or removing can reorder the resulting elements.

On the other hand, how have plugins in the ecosystem cross-built to sbt 1 if none of the completions API is public? 😒

**Comment by eed3si9n** [comment]
I'm going to close this for now, since Guillaume seems to have find a workaround.
