### ISSUE TITLE
Provide good error when git dependency can't be satisfied

### ISSUE THREAD

**Issue by espringe** [sbt/sbt#383]
Our project uses a plugin which is fetched via git. In the case of one user who had a corporate firewall that didn't allow the plugin to get downloaded, really unclear errors resulted ([Full thread](https://groups.google.com/d/msg/scoobi-users/dxtOZJ8b9As/5uywdPQ1ucMJ)). It would be highly preferable if sbt would immediately quit with a clear error.

**Comment by harrah** [comment]
Can you clarify?  What was the error and how could it be improved?

**Comment by espringe** [comment]
The error was:

https://groups.google.com/d/msg/scoobi-users/dxtOZJ8b9As/16wIIRE7-x8J

Where "package-hadoop" is a task that is provided by our plugin. So instead of sbt loudly complaining that the plugin couldn't be downloaded, it instead complained of the task not being available.

**Comment by vigdorchik** [comment]
Weird. In the full thread I see the second output containing the error that the plugin cannot be downloaded, so is this really a problem?
Still a more serious problem, I think, is that sbt doesn't support git over http(s). This should be fixed.

**Comment by vigdorchik** [comment]
I was too quick my judgement about git over https, need to investigate more.

**Comment by vigdorchik** [comment]
Git over https works for me here. What was precisely the problem?

**Comment by espringe** [comment]
> In the full thread I see the second output containing the error that the plugin cannot be downloaded, so is this really a problem?

Yes, because he should have got that error (But a lot clearer) the first time around, not the second

**Comment by vigdorchik** [comment]
Yes, but at first he really tried to resolve wrong version of the plugin, so I guess sbt can't give a correct error when asked to work on a wrong environment? When everything was clean, the error was clear, wasn't it?

**Comment by espringe** [comment]
It's possible, but I'm not sure what makes you think he was trying to resolve the wrong version of the plugin?

Anyway, I can see this is getting no where, and with the next version of sbt going to support https this isn't much of a concern for me, so feel free to close it. :)

**Comment by vigdorchik** [comment]
git over https support should be available in 0.1 if I understand it correctly. Please file another issue if it doesn't work for you.

**Comment by vigdorchik** [comment]
Sorry, I missed https://github.com/harrah/xsbt/issues/384. No need for a new request :)
