### ISSUE TITLE
SBT evalute an InputTask even when I have un-matched condition to run it

### ISSUE THREAD

**Issue by tweetingReza** [sbt/sbt#3838]
## steps
I have this `build.sbt` file
```

lazy val t1 = inputKey[Unit]("T1")

lazy val t2 = inputKey[Unit]("T2")

t1 in Compile := { false match {
    case true => (run in Compile).evaluated
    case false => (run in Compile).evaluated
}}


t2 in Compile := { false match {
    case true => (run in Compile).evaluated
    case false => () // nothing
}}
```

## problem
When I run it
```
sbt:sbt-bug> t1
[info] Running Main 
[info] Running Main 
Main.scala
Main.scala

sbt:sbt-bug> t2
[info] Running Main 
Main.scala

```

## expectation
I expect in `t1` the `run` be evaluated just once, and not evaluating for `t2` at all.

## notes
tested with `1.0.4` and `0.13.16`

**Comment by eed3si9n** [comment]
`.evaluated` is a macro call that expands to _happens-before_ relationship - http://www.scala-sbt.org/1.x/docs/Task-Graph.html.

If you want to branch out the task dependencies based on a condition you have to use a dynamic task.
