### ISSUE TITLE
append to setting does not work in 0.13.16 in an AutoPlugin's projectSettings

### ISSUE THREAD

**Issue by pelepelin** [sbt/sbt#3843]
## steps
project/MyPlugin.scala
```scala
import sbt._
import sbt.Keys._

object MyPlugin extends AutoPlugin {
  override def projectSettings = Seq(
    sourceDirectories in Compile += baseDirectory.value / "blah"
  )
}
```

build.sbt
```
lazy val root = (project in file("."))
  .enablePlugins(MyPlugin)
```

do `show compile:sourceDirectories`

## problem

In 1.0.x the value is added to the list, in 0.13.16 it is not.

Also, in 0.13.16 this line mysteriously fixes the problem:
```
  override def requires = plugins.JvmPlugin
```
Found here: https://stackoverflow.com/a/29848730/1531945

## expectation

Should work in 0.13.x as well.

## notes

I've tried `sourceGenerators += ...` as well.
I could not find similar issue here.

**Comment by xuwei-k** [comment]
https://github.com/sbt/sbt/issues/2082

**Comment by pelepelin** [comment]
@xuwei-k Thank you very much!

Is this documented?

[This comment](https://github.com/sbt/sbt/issues/2081#issuecomment-116313174) describes the behavior, but this requirement seems still not mentioned in docs.

How can one find which setting comes from which plugin? `inspect` does not provide such hints, it only points to the place where setting macro is applied.

**Comment by pelepelin** [comment]
I can rewrite the issue to documentation issue.

**Comment by eed3si9n** [comment]
I'm closing this since it's now fixed in sbt 1. You're welcome to send us a PR on https://github.com/sbt/website/blob/0.13/src/reference/02-DetailTopics/05-Plugins-and-Best-Practices/02-Plugins.md
