### ISSUE TITLE
Sbt don't use .credentials when trying to update

### ISSUE THREAD

**Issue by deblockt** [sbt/sbt#3844]
## steps

try to update sbt using custom nexus with authentifcation.
On `~/.sbt/repositories`, I have custom repository : 
```
repositories]
  local
  my-ivy-proxy-releases: https://nexus.......com/repository/ivy-releases/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  my-maven-proxy-central: https://nexus......com/repository/maven-central/
  my-maven-snapshot: https://nexus......com/repository/maven-snapshots
  oss-snapshot: https://oss.sonatype.org/content/repositories/snapshots
  my-maven-local: file:///Users/tdeblock/.m2/repository
```

This nexus contains 1.0.0 version of SBT: `https://nexus.....com/repository/maven-central/org/scala-sbt/sbt/1.0.0/sbt-1.0.0.pom`

I have create a `.credentials` file on `~/.ivy2/.credentials` : 
```
realm=Sonatype Nexus Repository Manager
host=nexus......com
user=xxxx
password=yyyy
```

## problem

When sbt try to download `https://nexus.....com/repository/maven-central/org/scala-sbt/sbt/1.0.0/sbt-1.0.0.pom` there are a 401 error : 
```
my-maven-proxy-central: no namespace defined: using system
        no ivy file in cache for org.scala-sbt#sbt;1.0.0: tried /Users/tdeblock/.ivy2/cache/org.scala-sbt/sbt/ivy-1.0.0.xml
         trying https://nexus......com/repository/maven-central/org/scala-sbt/sbt/1.0.0/sbt-1.0.0.pom
                tried https://nexus.......com/repository/maven-central/org/scala-sbt/sbt/1.0.0/sbt-1.0.0.pom
try to get credentials for: Sonatype Nexus Repository Manager@nexus.norauto.com
authentication: k='Sonatype Nexus Repository Manager@nexus.norauto.com' c='null'
HTTP response status: 401 url=https://nexus.norauto.com/repository/maven-central/org/scala-sbt/sbt/1.0.0/sbt-1.0.0.pom
CLIENT ERROR: Unauthorized url=https://nexus.norauto.com/repository/maven-central/org/scala-sbt/sbt/1.0.0/sbt-1.0.0.pom
```

I think that `.credentials` file is not used.

## expectation

sbt use credential and download sbt 1.0.0

## notes

sbt version: *0.13.13*

**Comment by eed3si9n** [comment]
Could you define:

```
export SBT_CREDENTIALS="$HOME/.ivy2/.credentials"
```

and see if that solves it plz?

**Comment by deblockt** [comment]
Yes, It's works, thanks.

Maybe add this information on documentation.
And, if we run sbt on an existing project, why sbt don't use `credentials` defined on `build.sbt`?

Why sbt don't use `$HOME/.sbt/0.13/plugins/credentials.sbt` file?

**Comment by eed3si9n** [comment]
I think it needs to be documented too, so I added the Documentation tag.

The problem is that to parse `build.sbt` you need `sbt.jar`, which we download using the launcher JAR, which needs your proxy information.

**Comment by pshirshov** [comment]
Check that you have `www-authenticate` header set. It may be the issue.
