### ISSUE TITLE
Deleted files do not trigger ~

### ISSUE THREAD

**Issue by blast-hardcheese** [sbt/sbt#3845]
Followup to https://github.com/sbt/sbt/issues/3695

## steps

Create a file, `src/main/foo.scala` with some content (`foo.scala!` in my test case)
Watch for the recompile (and error, as our file was invalid syntax)
Delete the file
Nothing happens

## problem

Deleted files don't trigger recompile

## expectation

Deleted files modify the parent directory, which triggers recompile

## notes

MacOS 10.12.6
sbt versions: 0.13.13, 1.1.0-RC4

**Comment by dwijnand** [comment]
fixed by @eatkins in https://github.com/sbt/sbt/pull/4098. coming in sbt 1.1.5.
