### ISSUE TITLE
Unable to download SBT from official website (India)

### ISSUE THREAD

**Issue by OutToLearn** [sbt/sbt#3846]
(See the guidelines for contributing, linked above)

## steps
1. Go to http://www.scala-sbt.org/download.html
2. Click on any download link.
3. Wait for the file to download completely (100%) - which it fails to. It stops after about 10-15 MB of the 55 MB download and throws a "Network Error" message.

## problem
I am facing this issue from Pune, India. It's frustrating. I am not able to download the SBT from the official website. After about 25% download completion, it fails due to a "Network error". My internet is working perfectly fine, I've tried different browsers. My friend is facing the same problem from a different machine / ISP in Bangalore. Something is definitely wrong with the website download link.

I have tried downloading the MSI and the ZIP, latest and prior versions. I am setting this up on my Windows 10 system. All links behave in the same erroneous way. Downloads from other websites work perfectly.

## expectation

Download from official website to a Windows 10 system should complete fine on either Chrome or Firefox.

## notes

sbt version: *insert sbt version*

**Comment by OutToLearn** [comment]
I could finally download a really old version thanks to the links on this post: https://github.com/sbt/sbt/issues/3108

Link: https://downloads.typesafe.com/sbt/0.13.15/sbt-0.13.15.msi

But now after installing, the launch at command line fails. Error message:
```
       
                [SUCCESSFUL ] org.scala-sbt#template-resolver;0.1!template-resolver.jar (1045ms)

:: problems summary ::
:::: WARNINGS
                [FAILED     ] org.scala-lang#scala-library;2.10.6!scala-library.jar: Downloaded file size doesn't match expected Content Length for https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.jar. Please retry. (438444ms)

                [FAILED     ] org.scala-lang#scala-library;2.10.6!scala-library.jar: Downloaded file size doesn't match expected Content Length for https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.jar. Please retry. (438444ms)

        ==== Maven Central: tried

          https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.jar

                ::::::::::::::::::::::::::::::::::::::::::::::

                ::              FAILED DOWNLOADS            ::

                :: ^ see resolution messages for details  ^ ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: org.scala-lang#scala-library;2.10.6!scala-library.jar

                ::::::::::::::::::::::::::::::::::::::::::::::



:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
download failed: org.scala-lang#scala-library;2.10.6!scala-library.jar
Error during sbt execution: Error retrieving required libraries
  (see C:\Users\shrutijalali\.sbt\boot\update.log for complete log)
Error: Could not retrieve sbt 0.13.15

D:\scala projects\Filesearcher>
```

**Comment by eed3si9n** [comment]
Could you post the exact URL that you are having problem with?

Are you saying that both download links and Maven Central are failing?
It might be possible that these services are doing some maintenance during the down time, but if it keeps happening, maybe something else is going on your end of the network.
