### ISSUE TITLE
Unable to download sbt-native-packager plugin on Ubuntu with OpenJDK 9 headless (certificate issue)

### ISSUE THREAD

**Issue by akauppi** [sbt/sbt#3847]
Partly out of curiosity, was trying to build my sbt project using `openjdk-9-jdk-headless` on our CI machine. It fails with what seems to be a certificate issue.

I understand that once JDK 9 was still being developed, but it's been out for a while now, and the behaviour was surprising to me. I don't know if this is directly an sbt issue.

## problem

The build stops with:

```
01:05:20[warn] [FAILED ] com.typesafe.sbt#sbt-native-packager;1.3.2!sbt-native-packager.jar: sbt-plugin-releases: unable to get resource for com.typesafe.sbt#sbt-native-packager;1.3.2: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.3.2/jars/sbt-native-packager.jar: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: No trusted certificate found (176ms)
```

This seems to be an issue known to StackOverflow: [link](https://stackoverflow.com/questions/40165525), but it seems weird now that JDK 9 has been officially out.

## expectation

Updating the libraries and plugins should work, on both JDK 8 and JDK 9.

## notes

sbt version: 1.0.4

**Comment by eed3si9n** [comment]
As far as I know, sbt 1.0.4 runs ok on JDK 9 (sbt 1.1.0-RC4 would be better), but OpenJDK 9 packaging has had several issues (on Ubuntu and/or Docker):
- https://github.com/docker-library/openjdk/issues/19
- https://github.com/docker-library/openjdk/issues/101
- https://github.com/docker-library/openjdk/issues/145
- https://bugs.java.com/view_bug.do?bug_id=JDK-8189131
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=866924

In the past I've done something like:

```
([[ ! -d $JAVA_HOME/conf ]] && ln -s $JAVA_HOME/lib $JAVA_HOME/conf)
```

to work around them but hopefully those are no longer needed. I think the following works: https://gist.github.com/eed3si9n/e0ff34162cdafa00c4b7776bf54b1c56

**Comment by asottile** [comment]
Ah!  I was hitting this as well.  I was able to get `sbt` to work by upgrading the version specified in `project/build.properties`
