### ISSUE TITLE
"early(error)" and "-error" do not suppress startup logs

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3849]
## steps

1. Use sbt 1.1.0-RC4
2. Run `sbt -error` or `sbt "early(error)"`

## problem

```
[info] Loading project definition from ....
```

## expectation

I do not see info level logs.

## notes

Originally #840

**Comment by mrveera** [comment]
Just for clearing, While specifying  -error flag We just need to console error level logs
Am I correct?

**Comment by dwijnand** [comment]
yes that's right.

for a little more context you might want to look at https://github.com/sbt/sbt/issues/2734.

**Comment by mrveera** [comment]
@eed3si9n  Could you please assign this to me?

**Comment by eed3si9n** [comment]
I can only assign to committers unfortunately using GitHub UI, but I am sure this comment would be enough as signal.

**Comment by laughedelic** [comment]
@veera83372 I think you have to be a collaborator (with push rights) to be able to be assigned

**Comment by dwijnand** [comment]
you only need read access to be assigned issues in github orgs: https://help.github.com/articles/repository-permission-levels-for-an-organization/

so I've invited @veera83372 to the sbt org.

**Comment by dwijnand** [comment]
correction: and you have to be a part of a team that has read access to sbt/sbt, so there's no an "sbt-read-access" team that has read access to sbt/sbt, and @veera83372 is in it :D

**Comment by mrveera** [comment]
Hey I need someone who has context on this so that I can ask few questions

**Comment by dwijnand** [comment]
sure, we can chat in https://gitter.im/sbt/sbt-contrib

**Comment by veera83372** [comment]
Hey, can someone verify whether following code is working or not?
I think a problem with this code according to my observation it is not setting the log level 
https://github.com/sbt/sbt/blob/ca874d5d5f6046c4ac2d4825d81e84b97b0f1c0a/main/src/main/scala/sbt/internal/LogManager.scala#L232-L233

**Comment by veera83372** [comment]
Can someone give me places where to look?

**Comment by mrveera** [comment]
@eed3si9n  Can you please tell me places where to look for this?

**Comment by SethTisue** [comment]
@veera83372 what have you tried so far? where do you get stuck trying to pull on this thread yourself? can you be a bit more specific about the next increment of assistance that would help you?

perhaps looking at how #840 was originally fixed would help with investigating how it might have regressed?

**Comment by SethTisue** [comment]
the squeaky wheel gets the grease, but the more specific and informative the squeak, the greasier the grease.

**Comment by mrveera** [comment]
According to log manager, we supposed to use sLog for loading project but its using logger which is in configuration. it is managed logger type without using specified error level.
What should I do Know?
https://github.com/sbt/sbt/blob/ca874d5d5f6046c4ac2d4825d81e84b97b0f1c0a/main/src/main/scala/sbt/internal/LogManager.scala#L248-L261
https://github.com/sbt/sbt/blob/ca874d5d5f6046c4ac2d4825d81e84b97b0f1c0a/main/src/main/scala/sbt/internal/Load.scala#L248
https://github.com/sbt/sbt/blob/ca874d5d5f6046c4ac2d4825d81e84b97b0f1c0a/main/src/main/scala/sbt/Keys.scala#L108

**Comment by eed3si9n** [comment]
Comparing the implementation of setGlobalLogLevel in LogManager in sbt 1 https://github.com/sbt/sbt/blob/ca874d5d5f6046c4ac2d4825d81e84b97b0f1c0a/main/src/main/scala/sbt/internal/LogManager.scala#L232-L233

vs

https://github.com/sbt/sbt-zero-thirteen/blob/069865794d295ae0a2a64bd534714eba831aac36/main/src/main/scala/sbt/LogManager.scala#L88-L94

```scala
  def setGlobalLogLevel(s: State, level: Level.Value): State = {
    s.globalLogging.full match {
      case a: AbstractLogger => a.setLevel(level)
      case _                 => ()
    }
    s.put(BasicKeys.explicitGlobalLogLevels, true).put(Keys.logLevel.key, level)
  }
```

might give us insight as well. In the sbt 0.13 version, it's changing `s.globalLogging.full`. 

To make similar change, you'd probably need to swap the `GlobalLogging` instance by calling its `newAppender` function, and swapping it with older logger:

```scala
      val s1 = s.put(BasicKeys.explicitGlobalLogLevels, true).put(Keys.logLevel.key, level)
      ....
      val newLogging = s1.globalLogging.newAppender(full, out, logBacking)
      s1.copy(globalLogging = newLogging)
```

**Comment by eed3si9n** [comment]
Or possibly a direct translation would be to call `LogExchange.bindLoggerAppenders(...)`.

**Comment by eed3si9n** [comment]
Here's my PR - https://github.com/sbt/sbt/pull/4036

**Comment by danbills** [comment]
Looks like this issue is fixed for `"early(error)"` but not `--error`:

```shell
dan@genbox ~/tmp/log $ sbt --error compile
[info] Loading settings from idea.sbt ...
[info] Loading global plugins from /home/dan/.sbt/1.0/plugins
[info] Updating ProjectRef(uri("file:/home/dan/.sbt/1.0/plugins/"), "global-plugins")...
[info] Done updating.
[info] Loading project definition from /home/dan/tmp/log/project
[info] Updating ProjectRef(uri("file:/home/dan/tmp/log/project/"), "log-build")...
[info] Done updating.
[info] Set current project to log (in build file:/home/dan/tmp/log/)
[info] Executing in batch mode. For better performance use sbt's shell
[warn] The `-` command is deprecated in favor of `onFailure` and will be removed in a later version
[success] Total time: 0 s, completed May 4, 2018 1:26:03 PM
dan@genbox ~/tmp/log $ sbt "early(error)" compile
dan@genbox ~/tmp/log $ 
```
