### ISSUE TITLE
sbt-spark-submit plugin already migrated?

### ISSUE THREAD

**Issue by diraol** [sbt/sbt#3851]
On the [wiki documentation page about plugins migration](https://github.com/sbt/sbt/wiki/sbt-1.x-plugin-migration) the 'saurfang/sbt-spark-submit' plugin is marked as 'in progress', but it seems that the plugin has already been migrated (based on the reference link).

Is this right? Can the page be updated?

**Comment by dwijnand** [comment]
Looks like the PR was merged, but there is no release for sbt 1: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.github.saurfang/sbt-spark-submit/
