### ISSUE TITLE
SBT Assembly fails on Windows 10 with error 3

### ISSUE THREAD

**Issue by sarahgerweck** [sbt/sbt#3871]
Updating my project to SBT 1.1.0 reliably produces the following error on Windows 10 Pro (version 10.0.16299). I'm running SBT directly in a Windows shell (not through Cygwin).

I'm running `sbt assembly` using the SBT Assembly 0.14.6 plugin, but this error doesn't actually seem to be inside the SBT assembly plugin. Switching back to SBT 1.0.4 in my `build.properties` fixes the issue, holding everything else constant.

```text
[info] Packaging C:\[…]\projectName.jar ...
[error] java.io.IOException: CreateFile() failed with error 3
[error]         at sbt.internal.io.WinMilli$.getHandle(Milli.scala:275)
[error]         at sbt.internal.io.WinMilli$.getModifiedTimeNative(Milli.scala:281)
[error]         at sbt.internal.io.WinMilli$.getModifiedTimeNative(Milli.scala:259)
[error]         at sbt.internal.io.MilliNative.getModifiedTime(Milli.scala:66)
[error]         at sbt.internal.io.Milli$.getModifiedTime(Milli.scala:352)
[error]         at sbt.io.IO$.getModifiedTime(IO.scala:1143)
[error]         at sbt.io.IO$.getModifiedTimeOrZero(IO.scala:1212)
[error]         at sbt.io.IO$.makeFileEntry$1(IO.scala:546)
[error]         at sbt.io.IO$.addFileEntry$1(IO.scala:550)
[error]         at sbt.io.IO$.$anonfun$writeZip$3(IO.scala:559)
[error]         at sbt.io.IO$.$anonfun$writeZip$3$adapted(IO.scala:559)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:929)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:929)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
```

Unfortunately this is a proprietary project, but I don't think there's anything particularly unusual about it: it seems to be a bug in the `WinMilli` object.

**Comment by dwijnand** [comment]
Hi @sarahgerweck could you provide a bit more stack please so we know who is calling `IO.writeZip`. Thanks.

**Comment by sarahgerweck** [comment]
@dwijnand My apologies: it looked like that would probably be enough. Here's the entire error message (as well as the immediately preceding messages).

```
[…]
[warn] Merging 'overview.html' with strategy 'discard'
[warn] Merging 'reference.conf' with strategy 'concat'
[warn] Strategy 'concat' was applied to a file
[warn] Strategy 'discard' was applied to 26 files
[info] Packaging C:\[…]\target\scala-2.12\PROJECT_NAME.jar ...
[error] java.io.IOException: CreateFile() failed with error 3
[error]         at sbt.internal.io.WinMilli$.getHandle(Milli.scala:275)
[error]         at sbt.internal.io.WinMilli$.getModifiedTimeNative(Milli.scala:281)
[error]         at sbt.internal.io.WinMilli$.getModifiedTimeNative(Milli.scala:259)
[error]         at sbt.internal.io.MilliNative.getModifiedTime(Milli.scala:66)
[error]         at sbt.internal.io.Milli$.getModifiedTime(Milli.scala:352)
[error]         at sbt.io.IO$.getModifiedTime(IO.scala:1143)
[error]         at sbt.io.IO$.getModifiedTimeOrZero(IO.scala:1212)
[error]         at sbt.io.IO$.makeFileEntry$1(IO.scala:546)
[error]         at sbt.io.IO$.addFileEntry$1(IO.scala:550)
[error]         at sbt.io.IO$.$anonfun$writeZip$3(IO.scala:559)
[error]         at sbt.io.IO$.$anonfun$writeZip$3$adapted(IO.scala:559)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:929)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:929)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]         at sbt.io.IO$.writeZip(IO.scala:559)
[error]         at sbt.io.IO$.$anonfun$archive$1(IO.scala:513)
[error]         at sbt.io.IO$.$anonfun$archive$1$adapted(IO.scala:510)
[error]         at sbt.io.IO$.$anonfun$withZipOutput$1(IO.scala:595)
[error]         at sbt.io.IO$.$anonfun$withZipOutput$1$adapted(IO.scala:584)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.io.IO$.withZipOutput(IO.scala:584)
[error]         at sbt.io.IO$.archive(IO.scala:510)
[error]         at sbt.io.IO$.jar(IO.scala:489)
[error]         at sbt.Package$.makeJar(Package.scala:121)
[error]         at sbtassembly.Assembly$.makeJar$1(Assembly.scala:41)
[error]         at sbtassembly.Assembly$.$anonfun$apply$12(Assembly.scala:81)
[error]         at sbtassembly.Assembly$.$anonfun$apply$12$adapted(Assembly.scala:77)
[error]         at sbt.util.Tracked$.$anonfun$outputChanged$1(Tracked.scala:101)
[error]         at sbtassembly.Assembly$.apply(Assembly.scala:85)
[error]         at sbtassembly.Assembly$.$anonfun$assemblyTask$1(Assembly.scala:249)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:271)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error]         at java.util.concurrent.FutureTask.run(Unknown Source)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[error]         at java.util.concurrent.FutureTask.run(Unknown Source)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[error]         at java.lang.Thread.run(Unknown Source)
sbt:PROJECT_NAME> [error] (assembly) java.io.IOException: CreateFile() failed with error 3
[error] Total time: 6 s, completed Jan 11, 2018 2:18:23 AM
```

If the issue is not clear from just the stack, I'm happy to provide more information or try to produce a non-proprietary version of the project that I can share. (I would probably need to produce a non-proprietary version to share the full debug output, as there's too much stuff to redact by hand.)

This isn't a critical issue for me as I have no compelling requirement for SBT 1.1, but I'll help as much as I can.

**Comment by dwijnand** [comment]
Thank you @sarahgerweck.

For some context WinMilli (and MilliNative/Milli) is newly added in sbt 1.1 to help mitigate the jdk on some platforms rounding file times to full seconds. This interacts badly with `~` (tilde), so Toni (@cunei) worked on implementing native code for each platform.

Toni, does that looks like enough information to reproduce?

**Comment by optician** [comment]
I've got the same issue. If it would be needed I can try to implement minimal example or provide some logs.

**Comment by eed3si9n** [comment]
The workaround to disabling the use of the native timestamp is `-Dsbt.io.jdktimestamps=true`.

**Comment by cunei** [comment]
I'm trying to reproduce using `sbt assembly`, I will report soon if I cannot recreate the error. Thanks for reporting!...

**Comment by cunei** [comment]
OK, I'm unable to reproduce using `sbt assembly` directly. However, the error reported is 3, which in Windows parlance is:
```
ERROR_PATH_NOT_FOUND
3 (0x3)
The system cannot find the path specified.
```
The WinMilli error handling should display a better error message, but in this case what probably happens is:
* `sbt-assembly` tries to get the modification time of a non-existing file, in the sense that the whole path does not exist.
* WinMilli should detect that the file does not exist and convert it into a `FileNotFoundException`, further converted down the line.
* However Windows, in its infinite wisdom, has two distinct error codes for files that do not exist: `ERROR_FILE_NOT_FOUND` if the path exists, and `ERROR_PATH_NOT_FOUND` if any path component is missing.
* Only the former is caught by WinMilli, hence the latter throws an unexpected exception during `assembly`.

It is an easy fix, I will submit a pull request in short order. Thanks!

**Comment by sarahgerweck** [comment]
It's fantastic to see this fixed quickly. I have two questions:
  1. Is there an easy way for me to test this out by tweaking my build properties? (And would it be helpful?)
  1. Will we see 1.1.1 soon? It's not the end of the world, but I'm definitely stuck on 1.0.4 until this is fixed. (Doing a command-line workaround isn't really an option for me.)

**Comment by er1c** [comment]
Happy to see this issue is getting/got fixed, just ran into it today!

**Comment by cunei** [comment]
Hi @sarahgerweck, the fix will be included in the next release but we don't have a date yet. You can try a 1.1.x snapshot, however:
1) Please add to your ` ~/.sbt/repositories` (or versioned equivalent) the line:
```
sbt-snapshots: https://dl.bintray.com/sbt/maven-snapshots
```
2) Then set the sbt version in project/build.properties to:
```
sbt.version=1.1.0-bin-20180116T091335
```
This is of course unstable and untested software; while it can be used to test this particular fix, it is not recommended for regular work.

**Comment by sarahgerweck** [comment]
Thanks @cunei for the guide and the fix. I was able to confirm that this patch is working for me. 😄 
I'll hold my assembly projects at 1.0.4 for now and keep an eye out for 1.1.1.

**Comment by jameskoch2** [comment]
FWIW, I bumped into this during an upgrade from 1.0.4 to 1.1.0, without using sbt-assembly. I have a test process which runs several copies of SBT independently and hit it like so:

```
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from C:\...\project
[info] Updating ProjectRef(uri("file:/C:/.../project/"), "...-build")...
Waiting for lock on C:\Users\...\.ivy2\.sbt.ivy.lock to be available...
[error] java.io.IOException: CreateFile() failed with error 3
[error] at sbt.internal.io.WinMilli$.getHandle(Milli.scala:275)
[error] at sbt.internal.io.WinMilli$.getModifiedTimeNative(Milli.scala:281)
[error] at sbt.internal.io.WinMilli$.getModifiedTimeNative(Milli.scala:259)
[error] at sbt.internal.io.MilliNative.getModifiedTime(Milli.scala:66)
[error] at sbt.internal.io.Milli$.getModifiedTime(Milli.scala:352)
[error] at sbt.io.IO$.getModifiedTime(IO.scala:1143)
[error] at sbt.io.IO$.getModifiedTimeOrZero(IO.scala:1212)
[error] at sbt.librarymanagement.RichUpdateReport.$anonfun$recomputeStamps$1(RichUpdateReport.scala:23)
[error] at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
[error] at scala.collection.Iterator.foreach(Iterator.scala:929)
[error] at scala.collection.Iterator.foreach$(Iterator.scala:929)
[error] at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
[error] at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[error] at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[error] at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error] at scala.collection.TraversableLike.map(TraversableLike.scala:234)
[error] at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
[error] at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[error] at sbt.librarymanagement.RichUpdateReport.recomputeStamps(RichUpdateReport.scala:16)
[error] at sbt.internal.librarymanagement.IvyRetrieve$.updateReport(IvyRetrieve.scala:234)
[error] at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:336)
[error] at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:205)
[error] at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error] at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:90)
[error] at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
[error] at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
[error] at xsbt.boot.Using$.withResource(Using.scala:10)
[error] at xsbt.boot.Using$.apply(Using.scala:9)
[error] at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
[error] at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
[error] at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error] at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error] at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error] at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:190)
[error] at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error] at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error] at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:46)
[error] at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:99)
[error] at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error] at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:112)
[error] at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error] at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:112)
[error] at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:95)
[error] at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:126)
[error] at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2381)
[error] at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] at sbt.Execute.work(Execute.scala:271)
[error] at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] at java.lang.Thread.run(Thread.java:748)
[error] (update) java.io.IOException: CreateFile() failed with error 3
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
Log Files:
```

**Comment by dwijnand** [comment]
Makes sense: the issue isn't sbt-assembly dependant.

**Comment by ams-tschoening** [comment]
> Please add to your ~/.sbt/repositories (or versioned equivalent) the line:
>> sbt-snapshots: https://dl.bintray.com/sbt/maven-snapshots

For people like me not very familiar with `sbt`, simply create that file if it's missing with the following minimal content:

	[repositories]
	local
	maven-central
	sbt-snapshots: https://dl.bintray.com/sbt/maven-snapshots

https://www.scala-sbt.org/1.x/docs/Launcher-Configuration.html

That lead to the mentioned new version of `sbt` being used in my project and the error was resolved.

**Comment by cunei** [comment]
@tschoening  Please note that sbt 1.1.1 has been released, which includes this fix.

**Comment by GioAgu17** [comment]
there is no instruction on how to upgrade version of SBT on Internet! How can I do that? I have also IntelliJ integrated with SBT

**Comment by dwijnand** [comment]
Update `sbt.version` in `project/build.properties`.

**Comment by jccode** [comment]
I face a similar issue on Windows7,  sbt version is 1.1.1.  
Here are the error messages. 

     all {file:/E:/jc/code/scala-train/}scala-train/products {file:/E:/jc/code/scala-train/}scala-train/test:products
    [error] java.io.IOException: CreateFile() failed with error 32
    [error]         at sbt.internal.io.WinMilli$.getHandle(Milli.scala:290)
    [error]         at sbt.internal.io.WinMilli$.getModifiedTimeNative(Milli.scala:296)
    [error]         at sbt.internal.io.WinMilli$.getModifiedTimeNative(Milli.scala:274)
    [error]         at sbt.internal.io.MilliNative.getModifiedTime(Milli.scala:67)
    [error]         at sbt.internal.io.Milli$.getModifiedTime(Milli.scala:376)
    [error]         at sbt.io.IO$.getModifiedTime(IO.scala:1143)
    [error]         at sbt.io.IO$.getModifiedTimeOrZero(IO.scala:1212)
    [error]         at sbt.util.FileInfo$lastModified$.apply(FileInfo.scala:150)
    [error]         at sbt.util.FileInfo$lastModified$.apply(FileInfo.scala:125)
    [error]         at sbt.Sync$.$anonfun$apply$2(Sync.scala:40)
    [error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
    [error]         at scala.collection.Iterator.foreach(Iterator.scala:929)
    [error]         at scala.collection.Iterator.foreach$(Iterator.scala:929)
    [error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
    [error]         at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:178)
    [error]         at scala.collection.TraversableLike.map(TraversableLike.scala:234)
    [error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
    [error]         at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
    [error]         at scala.collection.SetLike.map(SetLike.scala:101)
    [error]         at scala.collection.SetLike.map$(SetLike.scala:101)
    [error]         at scala.collection.AbstractSet.map(Set.scala:47)
    [error]         at sbt.Sync$.$anonfun$apply$1(Sync.scala:40)
    [error]         at sbt.Defaults$.$anonfun$copyResourcesTask$1(Defaults.scala:1538)
    [error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
    [error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
    [error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
    [error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
    [error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
    [error]         at sbt.Execute.work(Execute.scala:271)
    [error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
    [error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
    [error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
    [error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    [error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    [error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    [error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    [error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    [error]         at java.lang.Thread.run(Thread.java:745)
    [IJ]sbt:scala-train>
    [error] (Compile / copyResources) java.io.IOException: CreateFile() failed with error 32
    [error] Total time: 1 s, completed 2018-2-24 15:06:26
    [IJ]sbt:scala-train>

The workaround `-Dsbt.io.jdktimestamps=true` can fix this issue temporarily.
Let me know if I need to provide more useful information.

**Comment by dwijnand** [comment]
Split @jccode's comment into a fresh issue: https://github.com/sbt/sbt/issues/3972.
