### ISSUE TITLE
sbt doesn't work if `$GREP_OPTIONS` environment variable is set with `--color=always` value

### ISSUE THREAD

**Issue by andrii-kovalenko-ct** [sbt/sbt#3873]
When environment variable `$GREP_OPTIONS=--color=always`

## steps

set environment variable:
```bash
$ export GREP_OPTIONS='--color=always'
```

## problem

any `sbt` command fails with message:
> $ sbt
> No java installations was detected.
> Please go to http://www.java.com/getjava/ and download

## expectation

`sbt` script should be independent from user's environment variables (besides specific java and sbt related options)

## notes

  - `$ unset GREP_OPTIONS` fixes issue immediately
  - `$PATH`, `$JAVA_HOME` are set to proper locations
  - `java`, `gradle`, `maven`, `Intellij IDEA` and all other java related applications work just fine

## Version info:
  - `sbt`             0.13.11
  - `java`            1.8.0_144
  - `Mac OS`      10.13.2
  - `Homebrew` 1.4.3

**Comment by andrii-kovalenko-ct** [comment]
see also suffering people:
https://stackoverflow.com/a/47247154/907576
https://stackoverflow.com/a/47180447/907576

**Comment by dwijnand** [comment]
For any contributor the issue is probably in one (or multiple) of these `grep` invocations: https://github.com/sbt/sbt-launcher-package/search?utf8=%E2%9C%93&q=grep&type=

**Comment by andrii-kovalenko-ct** [comment]
i'm pretty sure it is this line:

```bash
java_version=$("$java_cmd" -Xms128M -Xmx512M -version 2>&1 | tr '\r' '\n' | grep ' version "' | sed 's/.*version "\([0-9]*\)\(\.[0-9]*\)\{0,1\}\(.*\)*"/\1\2/; 1q')
```

https://github.com/sbt/sbt-launcher-package/blob/a8b7b5a0603a44a691a18347cd85f659d94ac3ae/src/universal/bin/sbt-launch-lib.bash#L183

though not sure what is it best way to fix?
  - unset `GREP_OPTIONS` for the script?
  - call `grep` with explicitly specified _pure_ mode (if possible at all)?

**Comment by dwijnand** [comment]
Call grep with a temporary override for `GREP_OPTIONS`:

```bash
GREP_OPTIONS= grep ' version "'
```

**Comment by dwijnand** [comment]
```bash
$ java -Xms128M -Xmx512M -version 2>&1 | tr '\r' '\n' | grep ' version "' | sed 's/.*version "\([0-9]*\)\(\.[0-9]*\)\{0,1\}\(.*\)*"/\1\2/; 1q'
1.8
$ export GREP_OPTIONS=--color=always
$ java -Xms128M -Xmx512M -version 2>&1 | tr '\r' '\n' | grep ' version "' | sed 's/.*version "\([0-9]*\)\(\.[0-9]*\)\{0,1\}\(.*\)*"/\1\2/; 1q'

$ java -Xms128M -Xmx512M -version 2>&1 | tr '\r' '\n' | GREP_OPTIONS= grep ' version "' | sed 's/.*version "\([0-9]*\)\(\.[0-9]*\)\{0,1\}\(.*\)*"/\1\2/; 1q'
1.8
```

**Comment by cunei** [comment]
Please note that `GREP_OPTIONS` is deprecated. The current advice is to define an alias, which would not work with this workaround.
```
[cunei@rover ~]$ alias grep='grep --color=always'
[cunei@rover ~]$ java -Xms128M -Xmx512M -version 2>&1 | tr '\r' '\n' | GREP_OPTIONS= grep ' version "' | sed 's/.*version "\([0-9]*\)\(\.[0-9]*\)\{0,1\}\(.*\)*"/\1\2/; 1q'

```
However, you can alter the sed expression in order to cater for the possibly inserted ANSI code:
```
$ java -Xms128M -Xmx512M -version 2>&1 | tr '\r' '\n' | grep ' version "' | sed 's/.*version "[^0-9]*\([0-9]*\)\(\.[0-9]*\)\{0,1\}\(.*\)*"/\1\2/; 1q'
1.8
```
That works because the highlight reset code does not contain digits:
```
[cunei@rover ~]$ echo "abcde" | grep abcde | od -c
0000000 033   [   0   1   ;   3   1   m 033   [   K   a   b   c   d   e
0000020 033   [   m 033   [   K  \n
```

**Comment by andrii-kovalenko-ct** [comment]
>The current advice is to define an alias, which would not work with this workaround.

as i know, aliases don't affect calls from scripts. So, guess call _pure_ `grep` is safe enough if we are ensure `GREP_OPTIONS` is not set (unless the grep behavior is changed in the future)

**Comment by dwijnand** [comment]
Even if aliases are an issue you can avoid them with `command grep`.

**Comment by andrii-kovalenko-ct** [comment]
maybe it has sense to define local grep alias in the script itself? smth like:

```bash
# optionally
# unset GREP_OPTIONS

alias grep="grep --colour=never --ignore-case"

**Comment by andrii-kovalenko-ct** [comment]
BTW, do we really need `grep`? Isn't it enough to rely only on `sed`?

```bash
$ java -Xms128M -Xmx512M -version 2>&1 | tr '\r' '\n' | sed 's/.*version "\([0-9]*\)\(\.[0-9]*\)\{0,1\}\(.*\)*"/\1\2/; 1q'
1.8
```

This works for me.

Guess `java -version` output is simple enough to avoid "filter only one line" before redirecting output to `sed`.

WDYT?

**Comment by cunei** [comment]
Aliases do not, but scripts on the path do. To be precise, modern versions of grep say:
```
$ GREP_OPTIONS="--color=always" grep xyz </dev/null
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
```
So, redefining grep locally with an alias won't work. Observe:
```
[cunei@rover ~]$ cat grep
#!/usr/bin/env bash
echo "hello" >&2
grep $*
[cunei@rover ~]$ cat offf
#!/usr/bin/env bash
alias grep="grep --colour=never --ignore-case"
echo "xyz" | grep "xyz"

[cunei@rover ~]$ PATH=.:"$PATH" offf
hello
hello
hello
hello
hello
```

Thumbs up for removing `grep` from the equation. :+1:

**Comment by dwijnand** [comment]
> Thumbs up for removing grep for the equation. 👍

ME too. 👍

**Comment by radistao** [comment]
should we fix also other places? Literally:

  - do we really need [replace line endings](https://github.com/sbt/sbt-launcher-package/blob/a8b7b5a0603a44a691a18347cd85f659d94ac3ae/src/universal/bin/sbt-launch-lib.bash#L183) `tr '\r' '\n'`. Guess in this certain case line ending doesn't have much difference.

 - would color output affect [copyRt()](https://github.com/sbt/sbt-launcher-package/blob/a8b7b5a0603a44a691a18347cd85f659d94ac3ae/src/universal/bin/sbt-launch-lib.bash#L232) functionality? And why `grep` is required here? 

 - not sure how colored `grep` behavior could affect [`execRunner()`](https://github.com/sbt/sbt-launcher-package/blob/a8b7b5a0603a44a691a18347cd85f659d94ac3ae/src/universal/bin/sbt-launch-lib.bash#L62) in _debug|verbose_ mode

**Comment by radistao** [comment]
Hm, looks like that `grep` was added by purpose:

https://github.com/sbt/sbt-launcher-package/issues/170
https://github.com/sbt/sbt-launcher-package/pull/172
https://github.com/sbt/sbt-launcher-package/commit/c487e3166e5decfa2463a1155f216de7de217ee9

**Comment by andrii-kovalenko-ct** [comment]
@dwijnand @cunei 
any suggestions? so what should be done for the fix?

**Comment by dwijnand** [comment]
I don't have time to do further research myself. Feel free to do so yourself and experiment with different potential fixes.

You're free to go as in-depth or as superficial (like my `GREP_OPTIONS= grep ' version "'` suggestion) as you'd like.
