### ISSUE TITLE
All SBT plugins in Maven Central are missing maven-metadata.xml

### ISSUE THREAD

**Issue by ryan-williams** [sbt/sbt#3879]
(See the guidelines for contributing, linked above)

## steps

Publish an SBT plugin to Maven Central, e.g. via Sonatype "releases" repository

## problem

No `maven-metadata.xml` file gets added tot he {group,artifact}-level folder, as happens with non-SBT-plugin libraries that get published.

## expectation

SBT plugins should get a `maven-metadata.xml` just like non-SBT-plugins

## notes

[repeating examples from gitter](https://gitter.im/sbt/sbt?at=5a5aa70d290a1f45618641f2)

- [multi-module project with many plugin modules and one non-plugin module](https://github.com/hammerlab/sbt-parent)
  - all published yesterday via `publishSigned`, `sonatypeRelease`
  - only [the non-plugin module has a `maven-metadata.xml`](https://repo1.maven.org/maven2/org/hammerlab/sbt/lib_2.12/)
  - [example sibling plugin-module that is missing `maven-metadata.xml`](https://repo1.maven.org/maven2/org/hammerlab/sbt/maven_2.12_1.0/)
- surveying [scoverage](https://oss.sonatype.org/content/repositories/releases/org/scoverage/sbt-coveralls_2.12_1.0/) and [org.xerial.sbt](https://oss.sonatype.org/content/repositories/releases/org/xerial/sbt/) plugins, it seems that this problem has always existed and is universal among SBT plugins published to Maven Central. I've not looked at other Maven repositories.

AFAIU, `maven-metadata.xml` should be added by Sonatype-releases, before export to Maven Central. Perhaps `sbtPlugin := true` is interfering with some setting there, or there is a problem on the Sonatype side?

sbt version: have personally observed on 0.13.16 and 1.0.4

**Comment by eed3si9n** [comment]
AFAIK `maven-metadata.xml` is generated and maintained on the repo side (like Sonatype OSS).
I wouldn't be surprised that there's a problem with sbt plugins since our URL translation is a bit unusual. For instance, https://repo1.maven.org/maven2/org/hammerlab/sbt/maven_2.12_1.0/ says maven_2.12_1.0 but the artifactId is "maven."

**Comment by ryan-williams** [comment]
is what you mean that the directory structure says `maven_2.12_1.0`, but the files in the directory are just named e.g. `maven-<version>.pom`, instead of `maven_2.12_1.0-<version>.pom`?

that seems like a pretty good guess as to why the Maven repos aren't liking it, and I feel like it's mostly on our/SBT's side to fix.

is it important that the files not contain the `_2.12_1.0` bit?

also, the published POM's `artifactId` is missing the `_2.12_1.0` as well, idk if that matters.

fwiw I ran into this trying to use giter8's `maven(…)` helper to read the most recent version of a plugin from Maven Central

**Comment by eed3si9n** [comment]
Maven POM just doesn't have the functional equivalent to Ivy's extra attribute, and what it's doing is a workaround. AFAIK all these were well thought out and done intentionally so we can cross publish sbt plugins, resolve then correctly, and make sure that it can be depended on as normal library.
This might also explain why sbt plugins are hosted typically on an Ivy repo https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases

**Comment by ryan-williams** [comment]
Thanks, though I must admit I'm still a bit confused.

> …so we can cross publish sbt plugins

what cross-publishing does this refer to? 

if SBT 1.0/0.13 cross-publishing, I believe this mismatch (between artifacts' basenames and the directory structure and artifact ID they're released as) significantly pre-dates SBT 1.0/0.13 cross-publishing

if Scala 2.1x cross-publishing, SBT plugins have never supported that, have they?

> make sure that it can be depended on as normal library

"Normal [scala] libraries" get the Scala minor version appended to their artifact ID, and the artifacts' basenames match this, so various Maven-ecosystem tooling works as intended (aside: various latest-maven-central-version-badges I've tried also break on SBT plugins for this reason).

My interpretation is:

1. SBT plugins have always had artifact-file basenames not match their artifact-IDs,
1. downstream tooling now depends on this, and it's not worth breaking those tools, but
1. if we were starting from scratch, or already breaking this, we could correct this mismatch

lmk if i'm wrong about that? thanks.

**Comment by Atry** [comment]
It's simply a bug to publish an artifact to Maven with a naming conversion that does not conform the the standard Maven repository layout.

**Comment by MateuszKubuszok** [comment]
I would say it is easy to overlook the `section Bintray for sbt plugins` - when I was reading about sbt plugins nothing indicated that it something more than courtesy of Bintray's part. Since I already had Sonatype repo I though I could simply reuse it. Only after release I learnt about the issues with this approach.

Maybe a mention in the publishing section would help? One that clearly states that publishing sbt plugins on Maven repos will end up with half broken release?

**Comment by ryan-williams** [comment]
Think I'm with @Atry here, can't really see why this "brokenness" would be unfixable or "working as intended".

A recent annoyance I came across is that coursier will fail to fetch SBT plugins, afaict because their files have the wrong names:

```
$ coursier fetch io.get-coursier:coursier_2.12:1.0.3
https://repo1.maven.org/maven2/io/get-coursier/coursier_2.12/1.0.3/coursier_2.12-1.0.3.pom
  100.0% [##########] 1.9 KiB (2.8 KiB / s)
https://repo1.maven.org/maven2/io/get-coursier/coursier_2.12/1.0.3/coursier_2.12-1.0.3.jar
  100.0% [##########] 1.4 MiB (3.6 MiB / s)
…
```

Finds [https://repo1.maven.org/maven2/io/get-coursier/coursier_2.12/1.0.3/coursier_2.12-1.0.3.{pom,jar}](https://repo1.maven.org/maven2/io/get-coursier/coursier_2.12/1.0.3/); cool!

```
$ coursier fetch io.get-coursier:sbt-coursier_2.12_1.0:1.0.2

Error:
  io.get-coursier:sbt-coursier_2.12_1.0:1.0.2
    not found: /Users/ryan/.ivy2/local/io.get-coursier/sbt-coursier_2.12_1.0/1.0.2/ivys/ivy.xml
    not found: https://repo1.maven.org/maven2/io/get-coursier/sbt-coursier_2.12_1.0/1.0.2/sbt-coursier_2.12_1.0-1.0.2.pom
```

Doesn't find [https://repo1.maven.org/maven2/io/get-coursier/sbt-coursier_2.12_1.0/1.0.2/sbt-coursier-1.0.2.pom](https://repo1.maven.org/maven2/io/get-coursier/sbt-coursier_2.12_1.0/1.0.2/), looks for `sbt-coursier_2.12_1.0-1.0.2.pom` instead 😞

We are just doing Maven wrong, right? What does this have to do with "Ivy's extra attribute"? If we named the files in the way that Maven expects when uploading to Maven repositories, a bunch of Maven-ecosystem tools would start to work, right?

**Comment by bosson** [comment]
> AFAIK `maven-metadata.xml` is generated and maintained on the repo side (like Sonatype OSS).

https://articles.javatalks.ru/articles/32

"Albeit many think that Nexus is the one, it’s actually Maven Deploy Plugin who does the trick: it first fetches existing maven-medatadata.xml from remote repo, then it updates all the required information and uploads it back to the repo. If the file doesn’t exist in the first place, then it gets created and uploaded."

The code for merging and uploading the file seems to reside here: 
https://github.com/apache/maven-artifact-transfer/blob/master/src/main/java/org/apache/maven/shared/transfer/artifact/deploy/internal/Maven31ArtifactDeployer.java

Also see: 
https://stackoverflow.com/questions/43925304/does-maven-alway-deploys-maven-metadata-xml-file-after-all-uploading-artifacts

**Comment by hugo-vrijswijk** [comment]
Should this issue be reopened? The problem still exists. Should sbt upload its own `maven-metadata.xml`? Or would this not work with the difference in file-naming? 

Another place where this issue pops up: oss.sonatype.org (nexus repository manager 2.14) does not show download statistics for sbt plugins. Which (I think) is due to missing `maven-metadata.xml`.
