### ISSUE TITLE
Advanced command example not working

### ISSUE THREAD

**Issue by durban** [sbt/sbt#3881]
## steps

1. Try to use the ["Advanced command example"](http://www.scala-sbt.org/1.x/docs/Advanced-Command-Example.html) from the documentation.

## problem

`Load.reapply` doesn't work, because it's sbt-private (`sbt.internal.Load`).

## expectation

The example should work.

## notes

sbt version: 1.1.0

**Comment by eed3si9n** [comment]
This was fixed in https://github.com/sbt/website/pull/695
