### ISSUE TITLE
Make it possible for sbt plugins to register server handlers for custom JSON-RPC methods

### ISSUE THREAD

**Issue by olafurpg** [sbt/sbt#3890]
## problem
I have integrated with sbt server in my language server and managed to trigger compile on file save https://github.com/scalameta/metals/pull/170 I am very excited about the potential for using sbt server from an IDE to simplify the "Import project" step.

Would it be possible to give sbt plugins the ability to register handlers for custom JSON-RPC methods? Currently, sbt hardcodes a handful of LSP methods in https://github.com/sbt/sbt/blob/d1071002beabc3ec4d5a19453f3cf7f49ea2612f/main/src/main/scala/sbt/internal/server/LanguageServerProtocol.scala#L54 like `initialize` and `textDocument/didSave`. I would love to be able to write an sbt plugin that adds handler to respond to custom methods. In particular, I am interested in implementing methods from https://github.com/scalacenter/bsp/blob/master/docs/bsp.md to simplify project import when the user opens a directory with an sbt build.

## expectation
Just brainstorming, maybe there could be a  `sbtServerMethods: SettingKey[List[JsonRpcMethodHandler]]` where
```
case class JsonRpcMethod[A:Encoder, B:Decoder](method: String)
case class JsonRpcMethodHandler[A, B](endpoint: JsonRpcMethod[A, B], handler: A => B)
```

## notes

sbt version: 1.1.0

**Comment by eed3si9n** [comment]
I am on board with making sbt server more extensible, especially for experimenting with new feature proposals.

**Comment by dwijnand** [comment]
SGTM too.

My only concern is I'd like to try and keep the compatibility promises to some reasonable minimum, so we have flexibility to change the internal details of the server without breaking any server-extending plugins that will have been published.

**Comment by olafurpg** [comment]
I would be OK with no compatibility promises. Internal APIs are fine. Ideally, I'd like to see these methods handled in sbt server by default in the long term. I think a good first step towards that direction would be to allow quicker experimentation via sbt plugins.
