### ISSUE TITLE
Infinite loop when running a runMain task inside another task that is triggered by compile

### ISSUE THREAD

**Issue by lloydmeta** [sbt/sbt#3895]
I'm not quite sure if this is working by design, but I came across this while trying to write a function that takes a `Task[Set[File]]` (or a `TaskKey` for one) and produces another `Task[Set[File]]`, wrapping it in `FileFunction.cached` so that the original task is only invoked according to the contract in `FileFunction.cached`.

## Steps

1. Clone https://github.com/lloydmeta/sbt-cached-filetask
2. Run `sbt compile`

#### Or

1. Have a normal main class in the project that does something
2. Define a task that runs that main class, using `runMain`
3. Use a function to wrap the task so that it is only invoked via `FileFunction.cached`, producing another `Task`
4. Define the Task as being `triggeredBy` `compile in Compile.

## Problem

The code in `master` enters an infinite task-invocation loop when `compile` is run. 
I *think* it shouldn't be looping, but again, not sure if this is by design. If there is something wrong with my code, please let me know.

The file-task-wrapping method is written like so:

https://github.com/lloydmeta/sbt-cached-filetask/blob/148e9f8cf1620dc83c50daacea997a66f3ce42ed/project/FileUtils.scala#L12-L28

## Expectation

Both `compile` and `generate` should only run the wrapped `Task` once, if needed. After that, `FileFunction.cached` should do its job and the wrapped `Task` should only be invoked when necessary whenever `compile` and `generate` are run.

## Notes

sbt version: 1.0.4 (also reproducible in 0.13.x)

I've managed to hack up a **workaround** that more or less does what I expect, but it doesn't seem ideal because it is less flexible, and probably doesn't cover all the cache-invalidation edge-cases. Simply checkout the [`workaround` branch](https://github.com/lloydmeta/sbt-cached-filetask/tree/workaround) and run `sbt compile`.

https://github.com/lloydmeta/sbt-cached-filetask/blob/3e510c8acf5445f0c7a1fc8fc67a4efbd6693916/project/FileUtils.scala#L12-L84

**Comment by eed3si9n** [comment]
Calling `Project.extract(state).runTask` inside a task is not safe because you'd end up with a parallel universe.
