### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by hseeberger** [sbt/sbt#3896]
Using sbt 1.1.0 and Java 8 on macOS 10.13.2. Since sbt 1.0 I get `OutOfMemoryError` all the time. Any ideas how to handle that?

**Comment by eed3si9n** [comment]
Give it more memory?
Do you have `JAVA_OPTS` or `SBT_OPTS` defined?

**Comment by hseeberger** [comment]
How exactly?

**Comment by eed3si9n** [comment]
```
export SBT_OPTS="-Dfile.encoding=UTF-8 -Xms2048M -Xmx2048M -Xss6M"
```

**Comment by hseeberger** [comment]
Thanks. Will give it a try.

**Comment by eed3si9n** [comment]
I am closing this for now. Let me know if you have some more details that we can reproduce.
