### ISSUE TITLE
sbt 1.1.0 tries to read a missing directory

### ISSUE THREAD

**Issue by alexdupre** [sbt/sbt#3898]
## steps
1. Create an empty project with just the following two files:

% cat build.sbt
scalaVersion := "2.12.4"
% cat project/build.properties
sbt.version=1.1.0

2. run sbt

## problem

[error] java.nio.file.NoSuchFileException: /usr/home/my-user/my-project/project/target/scala-2.12/sbt-1.0/classes
[error]         at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
[error]         at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
[error]         at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
[error]         at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
[error]         at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
[error]         at java.nio.file.Files.readAttributes(Files.java:1737)
[error]         at java.nio.file.Files.getLastModifiedTime(Files.java:2266)
[error]         at sbt.internal.io.JavaMilli$.getModifiedTime(Milli.scala:321)
[error]         at sbt.internal.io.Milli$.getModifiedTime(Milli.scala:352)
[error]         at sbt.io.IO$.getModifiedTime(IO.scala:1143)
[error]         at sbt.io.IO$.getModifiedTimeOrZero(IO.scala:1212)
[error]         at sbt.compiler.Eval$.fileModifiedBytes(Eval.scala:491)
[error]         at sbt.compiler.Eval.$anonfun$evalCommon$2(Eval.scala:165)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
[error]         at scala.collection.immutable.List.foreach(List.scala:389)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:234)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
[error]         at scala.collection.immutable.List.map(List.scala:295)
[error]         at sbt.compiler.Eval$.seqBytes(Eval.scala:482)
[error]         at sbt.compiler.Eval.evalCommon(Eval.scala:165)
[error]         at sbt.compiler.Eval.evalDefinitions(Eval.scala:150)
[error]         at sbt.internal.EvaluateConfigurations$.evaluateDefinitions(EvaluateConfigurations.scala:242)
[error]         at sbt.internal.EvaluateConfigurations$.evaluateSbtFile(EvaluateConfigurations.scala:113)
[error]         at sbt.internal.Load$.loadSettingsFile$1(Load.scala:1087)
[error]         at sbt.internal.Load$.$anonfun$discoverProjects$2(Load.scala:1095)
[error]         at scala.collection.MapLike.getOrElse(MapLike.scala:128)
[error]         at scala.collection.MapLike.getOrElse$(MapLike.scala:126)
[error]         at scala.collection.AbstractMap.getOrElse(Map.scala:59)
[error]         at sbt.internal.Load$.memoLoadSettingsFile$1(Load.scala:1094)
[error]         at sbt.internal.Load$.$anonfun$discoverProjects$4(Load.scala:1102)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
[error]         at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
[error]         at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
[error]         at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:234)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[error]         at sbt.internal.Load$.loadFiles$1(Load.scala:1102)
[error]         at sbt.internal.Load$.discoverProjects(Load.scala:1116)
[error]         at sbt.internal.Load$.discover$1(Load.scala:844)
[error]         at sbt.internal.Load$.loadTransitive(Load.scala:909)
[error]         at sbt.internal.Load$.loadProjects$1(Load.scala:714)
[error]         at sbt.internal.Load$.$anonfun$loadUnit$10(Load.scala:717)
[error]         at sbt.internal.Load$.timed(Load.scala:1343)
[error]         at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:717)
[error]         at sbt.internal.Load$.timed(Load.scala:1343)
[error]         at sbt.internal.Load$.loadUnit(Load.scala:677)
[error]         at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:477)
[error]         at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:158)
[error]         at sbt.internal.BuildLoader.apply(BuildLoader.scala:223)
[error]         at sbt.internal.Load$.loadURI$1(Load.scala:539)
[error]         at sbt.internal.Load$.loadAll(Load.scala:555)
[error]         at sbt.internal.Load$.loadURI(Load.scala:485)
[error]         at sbt.internal.Load$.load(Load.scala:464)
[error]         at sbt.internal.Load$.$anonfun$apply$1(Load.scala:253)
[error]         at sbt.internal.Load$.timed(Load.scala:1343)
[error]         at sbt.internal.Load$.apply(Load.scala:253)
[error]         at sbt.internal.Load$.defaultLoad(Load.scala:69)
[error]         at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:707)
[error]         at sbt.BuiltinCommands$.doLoadProject(Main.scala:707)
[error]         at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:680)
[error]         at sbt.Command$.$anonfun$applyEffect$4(Command.scala:134)
[error]         at sbt.Command$.$anonfun$applyEffect$2(Command.scala:130)
[error]         at sbt.MainLoop$.processCommand(MainLoop.scala:153)
[error]         at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:136)
[error]         at sbt.State$$anon$1.runCmd$1(State.scala:242)
[error]         at sbt.State$$anon$1.process(State.scala:248)
[error]         at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:136)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.MainLoop$.next(MainLoop.scala:136)
[error]         at sbt.MainLoop$.run(MainLoop.scala:129)
[error]         at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:107)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.MainLoop$.runWithNewLog(MainLoop.scala:101)
[error]         at sbt.MainLoop$.runAndClearLast(MainLoop.scala:57)
[error]         at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:42)
[error]         at sbt.MainLoop$.runLogged(MainLoop.scala:34)
[error]         at sbt.StandardMain$.runManaged(Main.scala:113)
[error]         at sbt.xMain.run(Main.scala:76)
[error]         at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error]         at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error]         at xsbt.boot.Launch$.run(Launch.scala:109)
[error]         at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error]         at xsbt.boot.Launch$.launch(Launch.scala:117)
[error]         at xsbt.boot.Launch$.apply(Launch.scala:18)
[error]         at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error]         at xsbt.boot.Boot$.main(Boot.scala:17)
[error]         at xsbt.boot.Boot.main(Boot.scala)
[error] java.nio.file.NoSuchFileException: /usr/home/my-user/my-project/project/target/scala-2.12/sbt-1.0/classes

## expectation

No exception on missing directory

## notes

sbt version: 1.1.0

After manually creating the missing directory sbt works fine. 

It seems the following function doesn't expect a missing File, so the passed directory is actually handled as a file and the attempt to read it fails.

  def fileModifiedBytes(f: File): Array[Byte] =
    (if (f.isDirectory)
       filesModifiedBytes(f listFiles classDirFilter)
     else
       bytes(IO.getModifiedTimeOrZero(f))) ++ bytes(f.getAbsolutePath)

I'm not sure if the issue is that sbt is not correctly creating such directory or that it doesn't check for its existence in the `fileModifiedBytes` function.

**Comment by cunei** [comment]
This is the same issue described in https://github.com/sbt/sbt/issues/3894, which is already fixed in https://github.com/sbt/io/pull/121. It will be included in 1.1.1, which will be released soon.
