### ISSUE TITLE
ctrl-c behavior is suboptimal

### ISSUE THREAD

**Issue by paulp** [sbt/sbt#390]
## steps
1. Hit Ctrl-C in sbt shell.
## problem
1. In addition to not exiting, it actually switches focus away from the console to an invisible "xsbt.boot.Boot" titled window.
## expectation

It exits.
## original report

Can the sigint handler not be quite so insistent? If I hit ctrl-C at an empty prompt, I want to exit.  I can understand if maybe some people who manage to achieve long running sbt sessions live in fear of fat-fingering it, so I'll surrender that one if necessary, but:  if I hit ctrl-C twice in a row, I _definitely_ want to exit.

Right now the ctrl-C behavior punishes heavily on my platform.  The first time I hit it at an empty prompt, in addition to not exiting, it actually switches focus away from the console to an invisible "xsbt.boot.Boot" titled window.  So first I have to cmd-tab my way back to the terminal before I can proceed to either ctrl-Z-and-kill-it or pursue one of the "approved" ways out.

I don't know why the window switch happens; the repl doesn't do it so I know it's not necessary.  Also, the repl has exited for ctrl-C at an empty prompt forever and nobody has ever complained.

**Comment by eed3si9n** [comment]
Sorry for the late response. I'm not seeing Ctrl-C behavior using sbt 0.13.1 on my Mac. Does this still happen?
