### ISSUE TITLE
Resolver.withDefaultResolvers got renamed to combineDefaultResolvers

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3903]
## steps

http://www.scala-sbt.org/1.x/docs/Library-Management.html

```scala
externalResolvers := Resolver.withDefaultResolvers(resolvers.value, mavenCentral = false)
```

## problem

Doesn't work.

## expectation

The doc uses combineDefaultResolvers. Also mention that in migration guide.

**Comment by dwijnand** [comment]
Just curious, any reason this is an sbt/sbt issue rather than an sbt/website issue?

**Comment by eed3si9n** [comment]
At the time I opened it, it made sense in my head that this is an sbt-wide issue, since it's not just that the documentation is outdated, but I didn't capture the breaking change in release notes or migration guide.

**Comment by jiminhsieh** [comment]
Could I work on this one? 

There are two places need to update:
* Fix `withDefaultResolvers` at https://www.scala-sbt.org/1.x/docs/Library-Management.html
* Mention how to migrate to new API, `combineDefaultResolvers`,  at https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html

The major difference between `withDefaultResolvers` and `combineDefaultResolvers` is from `Seq[Resolver]` to `Vector[Resolver]`.

**Comment by eed3si9n** [comment]
@jiminhsieh Yes, please!
