### ISSUE TITLE
.jvmopts should trim comments on Windows

### ISSUE THREAD

**Issue by MasseGuillaume** [sbt/sbt#3908]
On linux, you can use `#` to comment out a line. However, when you run it on windows it produces the following error:

```
Error: Could not find or load main class #
Command exited with code 1
```

**Comment by eed3si9n** [comment]
Note to potential contributors:
Here's the bash version:
https://github.com/sbt/sbt-launcher-package/blob/bf9cd40349b02177944d92d7c7fe1aa5fc6388ed/src/universal/bin/sbt#L138-L143

```
loadConfigFile() {
  # Make sure the last line is read even if it doesn't have a terminating \n
  cat "$1" | sed $'/^\#/d;s/\r$//' | while read -r line || [[ -n "$line" ]]; do
    eval echo $line
  done
}
```

and here's the batch file - https://github.com/sbt/sbt-launcher-package/blob/v1.1.0/src/universal/bin/sbt.bat
