### ISSUE TITLE
envVars requires forking

### ISSUE THREAD

**Issue by tindzk** [sbt/sbt#3914]
## Problem
The `envVars` setting only works when `fork` is set to true. In my case, the application is an interactive shell that reads raw input. Unfortunately, this functionality causes problems when the process is forked.

## Expectations
1. `envVars` should not require forking
2. The correct usage of `envVars` should be explained in the manual

## Workaround
Set the environment variable from within the application using [this](https://stackoverflow.com/a/42964302) code snippet.

## Notes
sbt version: 1.1.0

**Comment by eed3si9n** [comment]
sbt's `run` or `test` executes within the same JVM as sbt itself.
I can't see how we can append extra environment variables without forking.

**Comment by tindzk** [comment]
If a solution relying on reflection is viable, the `getModifiableEnvironmentMap` function from the link above could be used.
