### ISSUE TITLE
sbt thin client

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3915]
sbt thin client is the idea of splitting sbt into two parts: client and server.

## why?

This allows more batch-like operation from the shell (given we keep the server running).

The idea of splitting has long existed (for example Activator UI, https://github.com/sbt/sbt/wiki/XArchived:-Client-server-split), but full replacement of sbt frontend requires a lot of work. 

## how?

- The first step would be to get `sbt client` running again via JSON-RPC. https://github.com/sbt/sbt/issues/2798
- A useful feature would be implementing a "cursor" that tracks "current project" independently. https://github.com/sbt/sbt/issues/2799

This could get the basics like `compile` and `test`.

Other interactive tasks that require std input and output require abstraction:

- Abstract "run" task over JSON https://github.com/sbt/sbt/issues/2804
- Abstract "console" task over JSON https://github.com/sbt/sbt/issues/2805

## native

Additionally, if someone is interested, they could try implementing a client using Scala Native.

**Comment by stewSquared** [comment]
I'm curious why this issue is still open given #4227
Is there more work planned?

**Comment by eed3si9n** [comment]
I think the next steps would be supporting things like `run` and `console`.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/5620
