### ISSUE TITLE
Publish the https://dl.bintray.com/sbt/debian/sbt-0.13.17.deb file

### ISSUE THREAD

**Issue by guizmaii** [sbt/sbt#3916]
(See the guidelines for contributing, linked above)

## problem

The `.deb` release for sbt 0.13.17 doesn't exist in Bintray.

## notes

sbt version: 0.13.17

**Comment by Crazy-Hopper** [comment]
Pardon, could anyone please explain why this issue was closed?
For me it seems to be quite a legit request to publish an official Debian package for an officially released version.

**Comment by eed3si9n** [comment]
I didn't close the issue, but I think closing it makes sense. First, does apt sort by the publish date or by version number? Assuming it's by date, if we published 0.13.17 wouldn't that get pushed out to the world as the latest?

Second, sbt 1 launcher is able to launch sbt 0.13 anyway, so you won't gain much from having this deb file.

**Comment by Crazy-Hopper** [comment]
First, absolutely no.
Second, the gain is obvious. For me -- it's simplicity, for officials -- it's completeness.
Well, i could actually build the deb myself if there were deb sources in the repository (which i couldn't find).

**Comment by eed3si9n** [comment]
> First, absolutely no.

That's good to know.

> Well, i could actually build the deb myself if there were deb sources in the repository (which i couldn't find).

https://github.com/sbt/sbt-launcher-package

```
sbt -Dsbt.build.version=0.13.17 -Dsbt.build.offline=false
> Debian/packageBin
```

**Comment by imarios** [comment]
For me it has to do with docker and building a fresh image for every build we have. Using a different version of sbt mens I have to wait for sbt to download the version it needs everytime. I had an easy way to install sbt using the Debian package, but now the build takes longer because I can’t include the version I need in the image when it gets created. 

Thanks for addressing this!

**Comment by Crazy-Hopper** [comment]
This was the exact reason why I started commenting in this issue.
