### ISSUE TITLE
Scripted adds a library dependency on every project

### ISSUE THREAD

**Issue by jvican** [sbt/sbt#3917]
## steps

1. Clone https://github.com/jvican/sbt-library-deps-bug-scripted.
1. Run `show libraryDependencies`.

## problem

Sbt-scripted, which is added as a plugin, add a library dependency to my project?

## expectation

Sbt-scripted does not add anything to my projects' library dependencies. Note that my project is not an sbt plugin.

## notes

sbt version: all 1.x series.

**Comment by jvican** [comment]
```
sbt @ test > show libraryDependencies
[info] example / libraryDependencies
[info] 	List(org.scala-lang:scala-library:2.12.4, org.scala-sbt:scripted-sbt:1.1.0:scripted-sbt, org.scala-sbt:sbt-launch:1.1.0:scripted-sbt-launch)
[info] libraryDependencies
[info] 	List(org.scala-lang:scala-library:2.12.4, org.scala-sbt:scripted-sbt:1.1.0:scripted-sbt, org.scala-sbt:sbt-launch:1.1.0:scripted-sbt-launch)
```

**Comment by eed3si9n** [comment]
It makes sense:

https://github.com/sbt/sbt/blob/v1.1.0/scripted/plugin/src/main/scala/sbt/ScriptedPlugin.scala#L43-L54

```scala
    libraryDependencies ++= (partialVersion(scriptedSbt.value) match {
      case Some((0, 13)) =>
        Seq(
          "org.scala-sbt" % "scripted-sbt" % scriptedSbt.value % ScriptedConf,
          "org.scala-sbt" % "sbt-launch" % scriptedSbt.value % ScriptedLaunchConf
        )
      case Some((1, _)) =>
        Seq(
          "org.scala-sbt" %% "scripted-sbt" % scriptedSbt.value % ScriptedConf,
          "org.scala-sbt" % "sbt-launch" % scriptedSbt.value % ScriptedLaunchConf
        )
    }),
```

combined with https://github.com/sbt/sbt/issues/3514.

**Comment by jvican** [comment]
I don't understand, is this the expected behaviour? This should only happen for those projects that are sbt plugins, not for all my projects.

**Comment by eed3si9n** [comment]
> This should only happen for those projects that are sbt plugins, not for all my projects.

Right. This behavior is now considered a bug (https://github.com/sbt/sbt/issues/3514), and it's now fixed via https://github.com/sbt/sbt/pull/3875, so hopefully you won't see this in 1.2.0.
In the mean time, you'd have to disable the plugin on each subprojects.

**Comment by dwijnand** [comment]
> fixed via https://github.com/sbt/sbt/pull/3875

closing
