### ISSUE TITLE
HTTP response status: 404 url=http://repo.typesafe.com/typesafe/ivy-releases/org.apache.ivy/ivy/2.2.0/ivys/ivy.xml

### ISSUE THREAD

**Issue by fjcarretero** [sbt/sbt#392]
When launching sbt for the first time.

Version 0.11.2

**Comment by jsuereth** [comment]
A 404 means that the artifactory instance that the typesafe repo is down.   We've been having issues with artifactoryonline.com's service.   This is not an SBT bug.
