### ISSUE TITLE
sbt -Dsbt.log.noformat=true no longer works

### ISSUE THREAD

**Issue by YogoGit** [sbt/sbt#3921]
(See the guidelines for contributing, linked above)

## steps
Run the command
```
sbt -Dsbt.log.noformat=true name
```
In any project

## problem
The output contains escape characters to format the line
```
ESC[0m[ESC[0minfoESC[0m] ESC[0mLoading project definition from /Users/nate/git/authorize/projectESC[0m
ESC[0m[ESC[0minfoESC[0m] ESC[0mSet current project to authorize (in build file:/Users/nate/git/authorize/)ESC[0m
ESC[0m[ESC[33mwarnESC[0m] ESC[0mThe `-` command is deprecated in favor of `onFailure` and will be removed in 0.14.0ESC[0m
ESC[0m[ESC[33mwarnESC[0m] ESC[0mThe `-` command is deprecated in favor of `onFailure` and will be removed in 0.14.0ESC[0m
ESC[0m[ESC[0minfoESC[0m] ESC[0mauthorizeESC[0m
```

## expectation
Disabling format should disabling format characters

## notes
```
sbt sbtVersion
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
[info] 1.1.0
```

**Comment by xuwei-k** [comment]
`-Dsbt.log.noformat=true` works in my environment( use [paulp/sbt-extras](https://github.com/paulp/sbt-extras) ).
Maybe [sbt-launcher-package](https://github.com/sbt/sbt-launcher-package) issue?
How do you install sbt?

**Comment by dwijnand** [comment]
Good thinking @xuwei-k. I discovered today that sbt-launcher-package doesn't handle `-D` - you have to use `-J-D` (removed in https://github.com/sbt/sbt-launcher-package/commit/55e0dfdc65440cb02627ccbb290a9afba211a9dc).

**Comment by nateww** [comment]
Thanks for the workaround. Either the documentation should be updated, or it should be fixed in the launcher to be compatible with prior releases.

**Comment by dwijnand** [comment]
@nateww where in the docs is `-Dsbt.log.noformat=true`?

**Comment by nateww** [comment]
https://www.scala-sbt.org/0.13/docs/Command-Line-Reference.html 

https://www.scala-sbt.org/1.x/docs/Command-Line-Reference.html

```
Command Line Options 
System properties can be provided either as JVM options, or as SBT arguments, in both cases as -Dprop=value. The following properties influence SBT execution. Also see sbt launcher.
```

**Comment by dwijnand** [comment]
I don't see an error in the docs - it never says explicitly `-Dsbt.log.noformat=true`.

I would be happy to receive a PR fixing sbt-launcher-package to bring back `-D` support.

**Comment by nateww** [comment]
What part of
```
or as SBT arguments, in both cases as -Dprop=value
```
followed by the list of possible properties, including
```
sbt.log.noformat
```

That would imply to me that I could set a parameter using SBT with
```
sbt -Dsbt.ivy.home=$HOME/.ivy1
```
and it would work.  How do you read the docs as passing parameters to SBT on the command line?

**Comment by dwijnand** [comment]
My apologies, thank you for pointing out what I wasn't seeing.

**Comment by dwijnand** [comment]
Hi @nateww and/or @YogoGit do you think you guys could help me understand why `-Dsbt.log.noformat=true` doesn't work for you?

I was looking to fix the scripts in https://github.com/sbt/sbt-launcher-package/ and realised I had misunderstood how it works. See there's a `process_my_args` in https://github.com/sbt/sbt-launcher-package/blob/v1.1.0/src/universal/bin/sbt#L117 which doesn't include `-D`, however there is a `process_args` in https://github.com/sbt/sbt-launcher-package/blob/v1.1.0/src/universal/bin/sbt-launch-lib.bash#L149 which does.

So you might see my dilemma: given that `-D` is there, why isn't it working for you guys?

Do you think you could run something like `sbt -d -Dsbt.log.noformat=true exit` and share the output? `-d` should enable debug logging in the script which should give some more details about what it is and is not doing. `exit` will make sure sbt exits immediately.

Thanks in advance.

**Comment by YogoGit** [comment]
So, more information.

In the project where I'm running this, the file .sbtopts exist, with the following contents.
```
-Dhttp.port=9006 -jvm-debug=5006
```

When this file is removed, the logging format is disabled as expected.  However, when using the version [paulp/sbt-extra](https://github.com/paulp/sbt-extras) version, it works as expected with or without the existance of the .sbtopts file.

**Comment by YogoGit** [comment]
Output from 'sbt -d -Dsbt.log.noformat=true name > out 2>&1'
```
[residual] arg = '-Dsbt.log.noformat=true'
[residual] arg = 'name'
[residual] arg = '-Dhttp.port=9006'
[residual] arg = '-jvm-debug=5006'
[residual] arg = '-Dsbt.log.noformat=true'
[residual] arg = 'name'
[process_args] java_version = '1.8'
# Executing command line:
java
-Xms1024m
-Xmx1024m
-XX:ReservedCodeCacheSize=128m
-XX:MaxMetaspaceSize=256m
-jar
/usr/local/Cellar/sbt/1.1.0/libexec/bin/sbt-launch.jar
-Dhttp.port=9006
-jvm-debug=5006
-Dsbt.log.noformat=true
name

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
ESC[0m[ESC[0minfoESC[0m] ESC[0mLoading project definition from /Users/nate/git/authorize/projectESC[0m
ESC[0m[ESC[0minfoESC[0m] ESC[0mSet current project to authorize (in build file:/Users/nate/git/authorize/)ESC[0m
ESC[0m[ESC[33mwarnESC[0m] ESC[0mThe `-` command is deprecated in favor of `onFailure` and will be removed in 0.14.0ESC[0m
ESC[0m[ESC[33mwarnESC[0m] ESC[0mThe `-` command is deprecated in favor of `onFailure` and will be removed in 0.14.0ESC[0m
ESC[0m[ESC[0minfoESC[0m] ESC[0mauthorizeESC[0m
```

**Comment by er1c** [comment]
I think this has been fixed:

```
$ sbt -Dsbt.log.noformat=true name > out 2>&1
$ cat out
[info] Loading settings for project global-plugins from idea.sbt,metals.sbt ...
[info] Loading global plugins from /c/Users/Eric Peters/.sbt/1.0/plugins
[info] Loading settings for project ta-webservice-api-build from plugins.sbt ...
[info] Loading project definition from /c/Users/Eric Peters/IdeaProjects/ta-webservice-api/project
[info] Loading settings for project ta-webservice-api from build.sbt,version.sbt ...
[info] Set current project to ta-webservice-api (in build file:/c/Users/Eric%20Peters/IdeaProjects/ta-webservice-api/)
[info] Installing the s3:// URLStreamHandler via java.net.URL.setURLStreamHandlerFactory
[info] ta-webservice-api
```

same behavior on windows

The `--no-colors` was also added to support this.
