### ISSUE TITLE
copy resources directory BEFORE compiling

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#3934]
Although sbt adds the target directory to the classpath of the compiler, this causes problems if the compiler needs access to resources because they are only copied AFTER (or in parallel with) the compile. Therefore you can get a situation where compile fails the first time, then succeeds.

To avoid this, I recommend that resources are copied BEFORE compilation.

Original report below, which slightly misunderstood the root cause.

-----

Unfortunately, sbt puts test resources on the classpath in `test:test` but not `test:compile`. Compiler plugins and macros that access resources will therefore fail without this fix:

```
    compileOptions in (Test, compile) := {
      val oldOptions = (compileOptions in (Test, compile)).value
      val resDir     = (resourceDirectory in Test).value
      oldOptions.withClasspath(oldOptions.classpath :+ resDir)
    }
```

**Comment by dwijnand** [comment]
are main resources on the classpath of `compile`?

**Comment by fommil** [comment]
It does appear so.

**Comment by fommil** [comment]
Actually it looks like main resources are not on the classpath of `compile:compile` either so it boils down to if this is a palatable change or not. Maybe a bit niche?

**Comment by fommil** [comment]
To clarify, I think the `Compile,compile` one is niche.

But I think `Test,compile` should definitely have the `Compile,resources` on the compiler classpath as this is much more realistic compared to depending on a jar.

**Comment by dwijnand** [comment]
> as this is much more realistic like depending on a jar

I agree. we should definitely explore this.

**Comment by fommil** [comment]
This might be a false positive. I can see the `target` directory on the classpath and it has the resources.

The issue I'm facing might be that I want the test resources on the test compiler classpath, and that's perhaps a bit niche.

**Comment by fommil** [comment]
oh! I see the issue. The resources are copied to the classes directory AFTER the compilation!

The real bug here is that resources should be copied over before compilation.

**Comment by fommil** [comment]
@dwijnand I found the real cause of this and changed the initial report accordingly. It's an sbt bug hopefully with an easy fix.

**Comment by dwijnand** [comment]
cool, I can actually tell you exactly where this happens (AFAIK). what a rare occurrence.

https://github.com/sbt/sbt/blob/v1.1.1/main/src/main/scala/sbt/Defaults.scala#L2544-L2548

for any potential contributor: you need to make the `compile` task depends on the completion of the `copyResources` task.

**Comment by eed3si9n** [comment]
Currently the compilation and resource (potentially generation in case of web apps etc) copying are two independent tasks (i.e. "concurrent" in Lamport sense). This is by design.

Simply making `compile` task depend on `copyResources` introduces extra step to `compile` that were not previously there, and therefore might incur expensive performance penalty. (Think Windows machine copying 100MB etc) If someone need resource during compilation, it probably should be an opt-in process, not a default behavior.

**Comment by dwijnand** [comment]
I was only changing the definition of `products` such that it copied before compiling, not of `compile` in general.

however, in reviewing my suggestion, I don't think this would be a great solution anyways because I can easily see that not every invocation of compile is via `products` (e.g does `test` use `products`?)

**Comment by fommil** [comment]
note that this is another area where bloop makes the assumption that the resources are copied over by the build tool before doing any compilation, therefore departing from what the build is doing. // @jvican

**Comment by eed3si9n** [comment]
testing is specialized running so I am guessing that resource would be available one way or the other.
It should also follow suit of `bgRun` so it can run without blocking the shell.

**Comment by jvican** [comment]
@fommil In this case, this doesn't matter to us, we practically replace all sbt defaults and hand-roll our own implementations for them. In our case, managed sources and resources are copied over when we `bloopInstall`.

**Comment by fommil** [comment]
dupe
