### ISSUE TITLE
NamedPipe channel may allow snooping from other users

### ISSUE THREAD

**Issue by jameskoch2** [sbt/sbt#3938]
The null security descriptor passed [here](https://github.com/sbt/ipcsocket/blob/74e375ec9fd0f95d5165784e5a576fb18186e8ff/src/main/java/org/scalasbt/ipcsocket/Win32NamedPipeServerSocket.java#L100) looks like it would still allow other users on the same machine to snoop on traffic.

Microsoft docs:
https://msdn.microsoft.com/en-us/library/windows/desktop/aa365600(v=vs.85).aspx
The default/null security descriptor "... grant read access to members of the Everyone group and the anonymous account." 

Does anyone know if the nMaxInstances = 1 used here mitigates this in some way? If yes, doesn't this get in the way of actually multi-client server scenarios?

**Comment by eed3si9n** [comment]
Thanks for the report!

**Comment by eed3si9n** [comment]
Hopefully this was addressed in https://github.com/sbt/ipcsocket/pull/3
