### ISSUE TITLE
we're done with "done compiling"

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#3939]
This message

```
[info] Done compiling.
```

which notoriously spams all build logs, is basically pointless.

- if it's a single project build, you already know because you have the shell back
- if it's a multi project build, it's useless because you don't know which thing it's talking about.

Can we just remove it?

**Comment by fommil** [comment]
related #2332

**Comment by fommil** [comment]
Ditto

```
[info] Done packaging.
```

**Comment by LogicalTime** [comment]
I'd go with adding the name of the thing it is talking about. It is nice to see which projects have compiled so you can figure out which project the compile is taking forever on. Sometimes compiles seem to hang forever. Feedback is nice and addictive.
