### ISSUE TITLE
Command line parameters doesn't support paths with spaces

### ISSUE THREAD

**Issue by er1c** [sbt/sbt#3943]
## steps

```
$ mkdir -p "$HOME/dir with spaces/.ivy2"
$ sbt -ivy "$HOME/dir with spaces/.ivy2" update
```

## problem

`Error: Could not find or load main class with`

## expectation

There would be a way to pass in a path with spaces (or in the `.jvmopts`)

## notes

sbt version: 1.1.0

I originally discovered this issue while trying to develop on windows 10.  My "username" is `Eric Peters` so my "windows" ivy2 directory is `C:\Users\Eric Peters\.ivy2`  This is interesting, because the same behavior exists on OSX too.  This is similar issue @wsargent 
 ran into here: https://gist.github.com/wsargent/072319c2100ac0aea4305d6f6eeacc08 - where he wants to do an `sbt publishLocal` from a Windows Subsystem Linux bash prompt to the "Windows" .ivy2 directory for IntelliJ IDEA to resolve.  You can't just create a symlink to make the behavior work.  So the only good opportunity is to create a bash alias like `alias sbt='sbt -ivy "/mnt/c/Users/Eric Peters/.ivy2"'` or add in the `/usr/local/etc/sbtopts`

```
eric@Erics-MacBook-Pro:~/Work/fm-common$ grep ivy /usr/local/etc/sbtopts
# Path to local Ivy repository (default: ~/.ivy2)
-ivy /Users/eric/dir\ with\ spaces/.ivy2
```

The sbtopts file will generate something like:

```
[error] Not a valid command: with (similar: exit)
[error] Not a valid project ID: with
[error] Expected ':'
[error] Not a valid key: with (similar: watch, ivyPaths)
[error] with
[error]
```

I've tried multiple variations of escaping (as both command line arguments, and in the `sbtopts`, but no obvious (to me) work around is available:

```
eric@Erics-MacBook-Pro:~/Work/fm-common$ sbt -ivy /Users/eric/Work/dir\ with\ spaces/.ivy2 update
Error: Could not find or load main class with
eric@Erics-MacBook-Pro:~/Work/fm-common$ sbt -ivy "/Users/eric/Work/dir\ with\ spaces/.ivy2" update
Error: Could not find or load main class with\
eric@Erics-MacBook-Pro:~/Work/fm-common$ sbt -ivy "/Users/eric/Work/dir with spaces/.ivy2" update
Error: Could not find or load main class with
eric@Erics-MacBook-Pro:~/Work/fm-common$ sbt -ivy "/Users/eric/Work/dir\\ with\\ spaces/.ivy2" update
Error: Could not find or load main class with\
```

I would love an extra set of eyeballs on this problem!

Thanks,

Eric

**Comment by dwijnand** [comment]
Is this fixed with https://github.com/sbt/sbt-launcher-package/pull/280?

**Comment by eed3si9n** [comment]
`sbt -ivy "/tmp/dir with spaces/.ivy2"` works for me.
