### ISSUE TITLE
Classifier is ignored for transitive dependencies

### ISSUE THREAD

**Issue by rabejens** [sbt/sbt#3946]
(See the guidelines for contributing, linked above)

## steps

1. Create a multi-module project
2. Have one module (here `module1`) depend on another one (here `module2`)
3. Set `artifactClassifier` to the same classifier on both modules
4. Publish them Maven-style to a repository manager like nexus
5. Start a new project
6. Add a dependency on the `module1` with the classifier:
  ```scala
  libraryDependencies += "com.mycompany" %% "module1" % "0.1" classifier "myclassifier"
  ```
7. Try to build it using `sbt compile`

## problem

`module1` is pulled in with the classifier `myclassifier` but `module2` is not

## expectation

`module2` should also be pulled in with the correct classifier

## notes

sbt version: 1.1.1

**Comment by eed3si9n** [comment]
@rabejens Could you confirm if this is still an issue with sbt 1.3.x please?

**Comment by SethTisue** [comment]
provisionally closing since we don't have confirmation that the issue still exists after the Ivy->Coursier transition
