### ISSUE TITLE
sbt new scala.local

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3949]
This is a proposal related to https://github.com/sbt/sbt/issues/2668 and https://github.com/sbt/sbt-launcher-package/pull/217.

## steps

1. `sbt new` or `sbt init`

## expectation

Displays:

```
Welcome to sbt new!

  Select `1` to create a build in the current directory.
  To use an online template, select `q` to quit, and rerun
  sbt new playframework/play-scala-seed.g8

1) scala.local: Scala program
q) quit
```

I type:

```
1
```

This creates a new build similar to https://github.com/scala/scala-seed.g8 and start sbt shell inside it.

**Comment by dwijnand** [comment]
I suggest it be called `sbt init`.

**Comment by eed3si9n** [comment]
> `sbt init`

why? I think `sbt new` is easy enough to remember.

**Comment by dwijnand** [comment]
1. I think it's better than a magic "scala.local" argument
2. there's a few precedents in other tools, probably `git init` is the most well known

**Comment by itohiro73** [comment]
In my understanding (per discussion with @eed3si9n today), this issue is a suggestion to provide an offline template inside sbt itself as opposed to depending on g8 resolver.

So it may be going to have other offline templates such as `akka.local`, `finagle.local` etc. in future.

In that case using `sbt new scala.local` may make more sense than `sbt init`?

@dwickern Thoughts?

**Comment by dwijnand** [comment]
I can get behind the idea of have a few different templates available offline/out-the-box, but I think they should be sbt-generic, not that specific.

I'm thinking for example: multi-project vs single-project (which has been a great source of debate in the giter8 templates in the scala org). also an sbt plugin template out-the-box (such as https://github.com/sbt/sbt-autoplugin.g8) would probably be a good idea.

but even still I think `sbt init` should delegate to one of them.

**Comment by dwijnand** [comment]
Btw, on a plane I recently converted my 10 line bash script into a 19 line rust binary, so it can run on Windows too.

https://github.com/dwijnand/sbt-init/blob/master/src/main.rs

**Comment by 2m** [comment]
FWIW @drewhk has worked on a similar tool for creating new Akka projects:
https://github.com/drewhk/hakk

**Comment by eed3si9n** [comment]
I updated the description.

To potential contributor: Related code locations are:
- https://github.com/sbt/sbt/blob/1d7b35bd67722511b9a058113e7a1070984e6758/main/src/main/scala/sbt/TemplateCommand.scala
- https://github.com/sbt/sbt/blob/1d7b35bd67722511b9a058113e7a1070984e6758/main-command/src/main/scala/sbt/BasicKeys.scala#L98

We probably need to create a dummy `TemplateResolverInfo` value that shortcircuits this chunk of code: https://github.com/sbt/sbt/blob/1d7b35bd67722511b9a058113e7a1070984e6758/main/src/main/scala/sbt/TemplateCommand.scala#L69-L74

and just call some function.

**Comment by muuki88** [comment]
I'll try to tackle this :)

**Comment by mrveera** [comment]
@muuki88 Are you still working on it?

**Comment by kotobotov** [comment]
it would be awersome to to have list of some popular/basic online template, when i wrote "sbt new" without any argument.
