### ISSUE TITLE
SBT 1.x fails to resolve Maven2 parent dependency as a POM file

### ISSUE THREAD

**Issue by ezhulkov** [sbt/sbt#3953]
## steps

1. Create `SBT 1.1.1` project with the following content
```name := "sbt-investigation"
version := "0.1"
scalaVersion := "2.12.4"
resolvers ++= Seq(
  "SBT Investigation" at "http://nexus.dev.zeptodev.com/content/repositories/sbt-investigation"
)
libraryDependencies ++= Seq(
  "com.zeptolab.notifications" % "notifications-client-api"  % "2.32"
)
```
2. Make sure that `build.properties` contains `sbt.version = 1.1.1`
3. Launch `sbt` and try `update`
4. Get the problem with unresolved dependency `commons-dependencies-parent-2.165.jar` 

## problem
The project depends on our library `notifications-client-api`. This library itself is dependant on parent `notifications-client` which is dependant on `commons-dependencies-parent`.

 `commons-dependencies-parent` does not have `jar` file. It's just a descriptive `POM` which contains [dependency management and other stuff](http://nexus.dev.zeptodev.com/content/repositories/sbt-investigation/com/zeptolab/commons/commons-dependencies-parent/2.165/). 

All artifacts are accessible in our internal Sonatype Nexus repository. For the purpose of investigation I've set up access to these artifacts [here](http://nexus.dev.zeptodev.com/content/repositories/sbt-investigation)

The problem is that `SBT 1.x` is trying to download `commons-dependencies-parent-2.165.jar` instead of `commons-dependencies-parent-2.165.pom` and fails with error.

> sbt.librarymanagement.ResolveException: unresolved dependency: com.zeptolab.notifications#notifications-client-api;2.32: SBT Investigation: unable to get resource for com/zeptolab/commons#commons-dependencies-parent;2.165: res=http://nexus.dev.zeptodev.com/content/repositories/sbt-investigation/com/zeptolab/commons/commons-dependencies-parent/2.165/commons-dependencies-parent-2.165.jar: java.net.ProtocolException: Unexpected status line: HTTP/1.1 404 Not Found

## expectation
`SBT 1.x` must  resolve parent dependency as a `POM` file 

## notes
`SBT 0.13.x` works great with the same setup

sbt version: 1.1.1

**Comment by ezhulkov** [comment]
Found a workaround, might be useful. 
Setting `updateOptions := updateOptions.value.withGigahorse(false)` helps

**Comment by eed3si9n** [comment]
sbt 1.3.0 switches to using Coursier, so I am closing this for now.
