### ISSUE TITLE
sbt new https://<bitbucket_repo>.g8 doesn't expand maven(...) template strings in default.properties

### ISSUE THREAD

**Issue by ALPSMAC** [sbt/sbt#3977]
## steps
When I created my own template using giter8 and following the docs. from SBT and Giter8's webpages I could make the template work locally by `sbt g8` inside the repo. 

When I try to `sbt new ...` the repo from a Bitbucket instance though (or from my local filesystem via `sbt new file:///path/to/repo.g8`) (we can't use GitHub for this code in my org.) the `maven(...)` strings I'm using inside my `default.properties` file to set the default versions of libraries to their latest stable releases aren't expanding.

## problem
`maven(...)` strings in `default.properties` aren't expanding to their version - the original `maven(...)` string is in-lined in my template where the version number should be. 

## expectation
The `maven(...)` strings are replaced with the appropriate version number from maven central. 

## notes

sbt version: 0.13.15
See: http://www.foundweekends.org/giter8/template.html#Maven+properties

**Comment by mmynsted** [comment]
Yes.  I found the same issue and it is frustrating.

**Comment by eed3si9n** [comment]
This is probably now fixed in sbt 1.2.1.
