### ISSUE TITLE
Cancellation doesn't stop long-running compilation task

### ISSUE THREAD

**Issue by RomanIakovlev** [sbt/sbt#3981]
One of the classes in my project currently takes 10+ minutes to compile. When I'm trying to cancel this via Ctrl+C, it prints `[warn] Canceling execution...`, but doesn't actually stop the process. Instead it runs further, presumably until the compilation of this tricky class is over. The only way to stop this is to kill sbt process, which I'm reluctant to do because I don't want to lose my warmed-up compiler state. I think cancellation should really abort the current process on the spot, not waiting until some meaningful part of it completes.

sbt version: 1.0.4

**Comment by dwijnand** [comment]
related to #3708

**Comment by eed3si9n** [comment]
Should be fixed in https://github.com/scala/scala/pull/6479 and https://github.com/scala/scala/pull/8448
