### ISSUE TITLE
macro clients should be recompiled if any transitive dependency of the macro is updated

### ISSUE THREAD

**Issue by retronym** [sbt/sbt#399]
I'm pretty sure the treatment should be the same as `test-quick`: https://github.com/harrah/xsbt/commit/d5bf8cf6d6f22f4b6bc07055c25d2f9642488118#L0R328

**Comment by harrah** [comment]
Didn't we decide that transitive was more correct, but in practice would be annoying?

**Comment by retronym** [comment]
Now that the macro def and implementation are separated, it's more likely that we'll need that extra correctness.

I don't see that it will be annoying to use, I just wasn't sure how to go about implementing this.

**Comment by harrah** [comment]
Hmm, how are def and implementation more separate than before?  Regardless, yes, I think the test-quick treatment is correct.  I assume you mean you didn't know how to implement it before, but do now?

**Comment by retronym** [comment]
The new separation is:

`def myMacro = SomeObject.myMacro`

If `SomeObject` is in the same file, the current approximation will still work.

I expect I can figure out how to adapt the test-quick approach to this problem. I would hope that the bulk of the logic can be shared, let me know if you have suggestions on the where to put that and what to call it..

**Comment by harrah** [comment]
Yes, it should be possible to extract it to a reusable function `(classpath: Seq[Attributed[File]]) => (className: String, lastCompilation: Compilation) => Boolean`.  You can probably put it in `compile/inc/` in the Analysis object and maybe call it something like `transitiveDepsRecompiled`.

**Comment by Blaisorblade** [comment]
Isn't this fixed by quite some time, or is that just my impression? In 0.13.1, adding whitespace to some dependency of some file containing macros causes the macro clients to be recompiled. (I tested this right now with https://github.com/Blaisorblade/hoas-with-names).

On the other hand, the canonical macro usage example (linked from the macros documentation) still references this bug, so closing it matters not just to keep the database clean.
https://github.com/scalamacros/sbt-example

**Comment by harrah** [comment]
Incremental compilation of macros is an ongoing problem.  This bug requests recompilation when a dependency of the macro definition changes.  That is not implemented.  Currently, only if the file containing the macro definition changes will clients be recompiled.

**Comment by Blaisorblade** [comment]
I thought my testcase showed the contrary, but of course I was wrong; my macro definition is recompiled every time because of scalamacros/paradise#11.

**Comment by Friendseeker** [comment]
Should be fixed by https://github.com/sbt/zinc/pull/1282
