### ISSUE TITLE
No instruction for CLA in CONTRIBUTING.md.

### ISSUE THREAD

**Issue by itohiro73** [sbt/sbt#3990]
## steps
Looking into `CONTRIBUTING.md`, there is no instruction for CLA. 

https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md

## problem
Contributors would not be sure what's the legal requirement to contribute to the project.

## expectation
Looking into `zinc` project, `CONTRIBUTING.md` refers to CLA as below. I'm not sure what's the CLA requirement in `sbt` but at least expect to see similar instruction in `sbt` project's `CONTRIBUTING.md`.

```
## Signing the CLA

Contributing to Zinc requires you or your employer to sign the
[Lightbend Contributor License Agreement](https://www.lightbend.com/contribute/cla).

To make it easier to respect our license agreements, we have added an sbt task
that takes care of adding the LICENSE headers to new files. Run `createHeaders`
and sbt will put a copyright notice into it.
```

## notes
If the CLA requirement is the same as zinc, I'm happy to contribute a fix in the doc (obviously after signing the CLA:) ).

sbt version: All

**Comment by eed3si9n** [comment]
Yes, it's the same. plz contribute.
