### ISSUE TITLE
VSCode Extension Test Files Do Not Compile

### ISSUE THREAD

**Issue by ChristopherDavenport** [sbt/sbt#4007]
(See the guidelines for contributing, linked above)

## steps
Use VSCode Extension
Write Test File
Save

## problem

Test Scope is not compiled by incremental compiler, forcing manual compilation

## expectation
Saving by the incremental compiler with check all scopes, or at least relevant scopes to the files being changed.

## notes

sbt version: 1.1.1

Workaround Fix: `addCommandAlias("compile", "test:compile")`

**Comment by eed3si9n** [comment]
Thanks for the report!

**Comment by ChristopherDavenport** [comment]
I'd be very happy to help solve it. I went looking but couldn't figure out where to start.
[Incremental Compiler Compile](https://github.com/sbt/sbt/blob/1.x/main/src/main/scala/sbt/Defaults.scala#L1425) or [CompileOptions](https://github.com/sbt/sbt/blob/1.x/main/src/main/scala/sbt/Defaults.scala#L1453) Seemed to make sense, but I'm not sure how they would know of the other scopes to be compiling.

A little direction and it would be my pleasure to provide this.

**Comment by eed3si9n** [comment]
I would suggest you or whoever working on it work on top of my existing PR https://github.com/sbt/sbt/pull/3975

The code that needs changing is:


```diff
+        }, {
+          case n: JsonRpcNotificationMessage if n.method == "textDocument/didSave" =>
+            appendExec(Exec(";compile; collectAnalyses", None, Some(CommandSource(name))))
+            ()
+        }
```

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/4022
