### ISSUE TITLE
Take down sbt Google Code site?

### ISSUE THREAD

**Issue by davidtnorth** [sbt/sbt#401]
At the moment, searching for SBT documentation using Google is frustrating as often results are returned to the old, out of date documentation on the Google Code site. Although that site does its best to point people in the direction of GitHub, has the time now come to take it down altogether to avoid confusion?

**Comment by OlegYch** [comment]
that'd be nice, it's frustrating to see it come up at the top of google results

**Comment by soc** [comment]
Yes, please. The time lost on all those out-dated sites is time I will never get back.

**Comment by harrah** [comment]
Please use the mailing list where it has already been discussed: https://groups.google.com/d/msg/simple-build-tool/qH7xE0jvBMk/7MnX41yhdGkJ
