### ISSUE TITLE
update `"com.typesafe" % "config"` dependency

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#4011]
(extracted from #4000)

**Comment by eed3si9n** [comment]
The problem is that SSL Config uses 1.2.0 - https://github.com/lightbend/ssl-config/blob/master/project/Dependencies.scala
/cc @kanischev

**Comment by dwijnand** [comment]
is this not help wanted?

**Comment by eed3si9n** [comment]
The bar for "help wanted" should be that it's immediately workable.

**Comment by dwijnand** [comment]
is this for you not immediately workable because the first change required is in ssl config?

**Comment by dwijnand** [comment]
does typesafe-config follow semver? could we not depend on version 1.3.1 in sbt with or without ssl-config updating?

**Comment by eed3si9n** [comment]
> is this for you not immediately workable because the first change required is in ssl config?

Basically. I think the realistic compromise for us (or a potential contributor) might be to shade SSL Config in Gigahorse so it doesn't conflict with the latest Lightbend Config.

**Comment by dwijnand** [comment]
ah right, yeah, because of #2796 depending on typesafe-config 1.3.1 in sbt is still working around the problem.

we might want to actually deal with #2796..

**Comment by dwijnand** [comment]
(Blocked on updating of LM.  But perhaps "Blocked on Upstream" is used to mean outside of the sbt library circle.)
