### ISSUE TITLE
Sbt hangs while downloading on jvm 1.7_02 and 1.7_03

### ISSUE THREAD

**Issue by popfalushi** [sbt/sbt#402]
Hello.
Tried to install sbt - it hangs on downloading (first start or downloading dependencies after install). Researched for a while, googled, stumbled upon this link: (https://github.com/djspiewak/anti-xml/issues/14) and in the end changed jvm to 1.6 instead of 1.7_02 (or 1.7_03) and everything started to work fine.
BTW: While I was trying to solve issue on 1.7, I have cleared caches several times( this involved removing .ivy2, .sbt, .m2).

Win7 x64. JVMs are x64 too.
Sbt version=0.11.2 (i.e. last)

**Comment by popfalushi** [comment]
Stumbled upon http://blog.bielu.com/2011/11/hotspot-64bit-server-hangs-on-socket.html . There is a workaround for this problem: -Djava.net.preferIPv4Stack=true , and it seems to be jdk7 issue. So: you may close this issue, make automatical workaround or put this info to faq/troubleshooting

**Comment by harrah** [comment]
The wiki is user-editable.  You can add it to the [FAQ](https://github.com/harrah/xsbt/wiki/FAQ) or the [Setup Notes](https://github.com/harrah/xsbt/wiki/Setup-Notes) pages or both.
