### ISSUE TITLE
sbt console won't allow any input.

### ISSUE THREAD

**Issue by suewonjp** [sbt/sbt#4021]
(See the guidelines for contributing, linked above)

## steps
Just invoke sbt console in any folder

## problem
sbt console won't allow any input.
It doesn't echo back anything I type except `<Enter>` key 

It responds to my `<Enter>` and changes a line

Also pressing `CTRL-C` lets me out of the console.

## expectation
Working like a regular console (echoing back what I type)

## notes
I have installed scala and sbt through sdkman (http://sdkman.io/index.html); That may be a problem?

scala version : 2.12.4
sbt version: 1.1.1
OS : Mac OS X 10.13.3
openjdk version "1.8.0_152"

And I wonder this is related to this [issue](https://stackoverflow.com/questions/23611588/console-input-within-sbt-does-not-echo-to-the-screen) ?

**Comment by suewonjp** [comment]
Seems like sdkman has nothing to do with this issue.

This symptom appears with Installing via Homebrew anyway.

And I tried `sbt "-Djline.terminal=none"` and it worked!

Just invoking the console with typing `sbt` caused this issue (maybe, only to me?)

I think this is a bug...

**Comment by dwijnand** [comment]
just for clarity in sbt "console" is how you access the Scala REPL.

what you're referring to as "console" in sbt is referred to as sbt's "shell". :)

so this is an sbt shell / jline issue, possibly to do with your system setup (thank you for all the system details you provided!)

what do you mean by "won't allow any input"? does that just mean that:

1. it doesn't echo back what you type, but it still executes what you typed after hitting `<Enter>`? or
2. does it not execute anything after typing something blindly and hitting `<Enter>`?

**Comment by suewonjp** [comment]
2. No echoing back and no execution.

Hitting Enter just gives me a new blank line, that's all.

Looks like `sbt` or `sbt "-Djline.terminal=unix"` causes this symptom, while `sbt "-Djline.terminal=none"` lets me interact with sbt, at least.

**Comment by dwijnand** [comment]
curious... but I have no idea how to debug this.. :-/

**Comment by suewonjp** [comment]
Yes, I understand this is a hard issue to debug.

After reading https://github.com/jline/jline2/wiki/Terminal-Factory-Configuration  , I've come to the conclusion that Jline can't recognize my terminal setup.

In fact, I've used .inputrc which looks as follows

```
set editing-mode vi

set keymap vi-insert
... settings ...

set keymap vi-command
... settings ...
```

After reading [this issue](https://github.com/jline/jline2/issues/286), I changed my inputrc like so:

```
set editing-mode vi

set keymap vi-command
... settings ...

set keymap vi-insert
... settings ...
```

In short, I've flipped the order of vi-command and vi-insert configuration so that vi-insert would come last.

**And it worked!**

Good news is that they've fixed the issue - https://github.com/sbt/sbt/issues/3128

> [cause] run sbt inside the project and it would firstly enter into vi-command mode, which means I have to press keys like i/a to get into vi-insert mode; and each time a sbt command completes, it enters into vi-command mode.

> Fix is merged to upstream (jline/jline2@b241ec4). Now waiting for a new JLine 2 release.

Though the fix was 2 month ago, but still no release yet. So I've got the damage. Sad.

**Comment by dwijnand** [comment]
nice sleuthing!

**Comment by dwijnand** [comment]
Duplicate of #3128

**Comment by vegerot** [comment]
@suewonjp a year and a half later and no change.  BTW this is a demonstration of the problem: https://youtu.be/cwHybM85Vpc

My inputrc: 
```
## arrow up
"\e[A":history-search-backward
## arrow down
"\e[B":history-search-forward

set colored-stats On
set completion-prefix-display-length 3
set mark-symlinked-directories  On
set show-all-if-ambiguous On
set visible-stats On
```

Edit: I forgot to mention in the video that it makes weird files including control characters
`'hello-world'$'\177\177\177\177\177\177\177\177\177''hello'$'\177\177\177\177\177\177''wtf?!'`
