### ISSUE TITLE
SBT does not use the specified JLine

### ISSUE THREAD

**Issue by hvesalai** [sbt/sbt#4026]
While the version 0.13.x of SBT used the JLine version that it was built against, the 1.1.x version uses the one provided by Scala.

## steps

Start SBT with the -verbose:class JVM parameter

Observe the jar from which the jline classes are loaded.

## problem

On SBT 1.1.x the classes are loaded from (for example)

`.sbt/boot/scala-2.12.4/lib/jline.jar` (or equivalent lib directory)

## expectation

On SBT 0.13.x the classes are loaded from (for example

`.sbt/boot/scala-2.10.6/org.scala-sbt/sbt/0.13.16/jline-2.14.4.jar`

## notes

Gitter discussion on sbt-contrib channel: https://gitter.im/sbt/sbt-contrib?at=5aaec22f01a2b40f382df06e

**Comment by eed3si9n** [comment]
A potentially related issue is https://github.com/sbt/zinc/pull/505 whereby scala-xml version was not reflected until 1.1.2 due to transitive dependency from scala-compiler and the way classloader was setup.

**Comment by eed3si9n** [comment]
I'm guessing this can now be resolved since I think we're doing this intentionally for sbtn purpose.
