### ISSUE TITLE
updateClassifiers does not resolve classifier sources

### ISSUE THREAD

**Issue by jastice** [sbt/sbt#4027]
sbt is not resolving sources for dependencies with additional classifier such as `tests`. For instance, a project published its test sources with the setting: `publishArtifact in Test := true`.

## steps

1. publish some sources with `tests` classifier
```
git clone git@github.com:yarulan/example-idea-download-sources-for-artifacts-with-classifiers.git
cd example-idea-download-sources-for-artifacts-with-classifiers/lib
sbt publishLocal
```
These sources will be published to local ivy:
```
> pwd
/Users/jast/.ivy2/local/com.example/lib_2.12/0.1.0-SNAPSHOT/srcs
> ll
total 48
-rw-r--r--  1 jast  staff   412B Mar 13 09:12 lib_2.12-sources.jar
-rw-r--r--  1 jast  staff    32B Mar 13 09:12 lib_2.12-sources.jar.md5
-rw-r--r--  1 jast  staff    40B Mar 13 09:12 lib_2.12-sources.jar.sha1
-rw-r--r--  1 jast  staff   414B Mar 13 09:12 lib_2.12-tests-sources.jar
-rw-r--r--  1 jast  staff    32B Mar 13 09:12 lib_2.12-tests-sources.jar.md5
-rw-r--r--  1 jast  staff    40B Mar 13 09:12 lib_2.12-tests-sources.jar.sha1
```
2. Create sbt project with this in build.sbt:
```libraryDependencies += "com.example" %% "lib" % "0.1.0-SNAPSHOT" classifier "tests"```
3. run `show updateClassifiers`

## problem

* The artifact `lib_2.12-tests-sources.jar` is not resolved.
* using dependency `"com.example" %% "lib" % "0.1.0-SNAPSHOT" classifier "tests" withSources()` does not make a difference
* using coursier does not make a difference

## expectation

`tests` sources are resolved

## notes

sbt version: 1.1.1, likely present in 0.13 series

via 
* https://youtrack.jetbrains.com/issue/SCL-8018
* https://youtrack.jetbrains.com/issue/SCL-12139
* https://stackoverflow.com/questions/48929480/intellij-idea-download-sources-for-artifacts-with-classifiers

**Comment by jmthibault79** [comment]
I can reproduce it in 1.1.2, 1.13, and 1.1.4 via https://github.com/jmthibault79/sbt-4027

**Comment by glennleekg** [comment]
For the temporary workarround, I am using the dependency

"com.example" %% "lib" % "0.1.0-SNAPSHOT" classifier "tests" **classifier "tests-sources"**

**Comment by glennleekg** [comment]
@jastice @jmthibault79 

For the temporary workarround, I am using the dependency

"com.example" %% "lib" % "0.1.0-SNAPSHOT" % "test" classifier "tests" **classifier "tests-sources"**

**Comment by eed3si9n** [comment]
It might not be what you want, but the current behavior works as designed. For details see https://www.scala-sbt.org/1.x/docs/Library-Management.html#Classifiers

> To obtain particular classifiers for all dependencies transitively, run the `updateClassifiers` task. By default, this resolves all artifacts with the `sources` or `javadoc` classifier. Select the classifiers to obtain by configuring the `transitiveClassifiers` setting. For example, to only retrieve sources:
>
> ```scala
> transitiveClassifiers := Seq("sources")
> ```

So one workaround might be adding the following:

```scala
updateClassifiers / transitiveClassifiers += "tests-sources"
```
