### ISSUE TITLE
update jsch please!

### ISSUE THREAD

**Issue by bblfish** [sbt/sbt#403]
The latest version of [Jsch is  0.1.46](http://repo1.maven.org/maven2/com/jcraft/jsch/0.1.46/), and you are using a version that is 2 years old at least 0.1.31

``` bash
$ find . -name "*.scala" -exec grep -i jsch {} \; -print
/** sbt interface for an Ivy ssh-based repository (ssh and sftp).  Requires the Jsch library.. */
./ivy/IvyInterface.scala
    lazy val ivySub = baseProject(file("ivy"), "Ivy") dependsOn(interfaceSub, launchInterfaceSub, logSub % "compile;test->test", ioSub % "compile;test->test", launchSub % "test->test") settings(ivy, jsch, httpclient)
./project/Sbt.scala
    lazy val jsch = lib("com.jcraft" % "jsch" % "0.1.31" intransitive() )
./project/Util.scala
```

A lot of bugs have been fixed in cryptography in the last two years!
It took me 5 hours to work out what the problem was when I could not publish my files to my local repository. I was getting IOExceptions with a message  "Algorithm negotiation fail" and this was my first time trying to publish, so it was a long and tedious path to find where the errors came from.

**Comment by harrah** [comment]
You can make this happen in a reasonable amount of time by forking, updating the version, verying it works for you, and submitting a pull request.  Obviously I can bump the version easily, but the verification is the important part.  Thanks!

**Comment by bblfish** [comment]
I am having difficulty compiling the M2 version as it cannot download the previous version, and then there are other problems when I try compiling the previous version...

So I tried with the 0.11.2 taged branch and after changing  the jsch version 

'''diff
diff --git a/project/Util.scala b/project/Util.scala
index 9c0bffd..6ca03a7 100644
--- a/project/Util.scala
+++ b/project/Util.scala
@@ -79,7 +79,7 @@ object Common
        lazy val jline = lib(jlineDep)
        lazy val ivy = lib("org.apache.ivy" % "ivy" % "2.2.0")
        lazy val httpclient = lib("commons-httpclient" % "commons-httpclient" % "3.1")
-       lazy val jsch = lib("com.jcraft" % "jsch" % "0.1.31" intransitive() )
-       lazy val jsch = lib("com.jcraft" % "jsch" % "0.1.46" intransitive() )
      lazy val sbinary = lib("org.scala-tools.sbinary" % "sbinary_2.9.0" % "0.4.0" )
      lazy val scalaCompiler = libraryDependencies <+= scalaVersion("org.scala-lang" % "scala-compiler" % _ )
  }
  @@ -101,4 +101,4 @@ object Licensed
              if(!note.exists) Nil else
                      try { seePaths(base, IO.read(note)) }
                      catch { case e: Exception => s.log.warn("Could not read NOTICE"); Nil }
  -}
  \ No newline at end of file
  +}
  '''

I then run xsbt in which I run `compile` followed by  `publish-local` as explained on the wiki and then 
clean out my `~/.sbt/boot` directory and then run `reboot full`. But I always end up with the old version 
of jsch

`
$ find boot/ | grep jsch
boot//scala-2.9.1/org.scala-tools.sbt/sbt/0.11.1/jsch-0.1.31.jar
`

I know the latest version works because if I just replace the jar then I can publish. But I don't understand how to get xsbt to build it.

**Comment by harrah** [comment]
Thanks, that is good enough verification for me, so I bumped the version myself.  Your problem with building was probably that you didn't weren't using a 0.12 launcher.  For the older version of jsch, I'm not sure since it worked for me.

**Comment by bblfish** [comment]
thanks. I'll send you feedback here as soon as I get around to it again, which should be soon.

**Comment by philliptaylorpro** [comment]
The sbt tool is literally broken out of the box when following tutorials and trying to use the "sbt new" command. This is the experience all new scala developers are facing or even those casually copying tutorials:

```
HOST [08:40: git$] sbt new scala/hello-world.g8
[info] Loading global plugins from /home/phill/.sbt/0.13/plugins
[info] Set current project to git (in build file:/home/phill/git/)
org.eclipse.jgit.api.errors.TransportException: git@github.com:scala/hello-world.g8.git: Algorithm negotiation fail
```
I don't want to sound to rude to people I've never spoken to, but I cannot stress what a serious bug this is and how it's potentially hurting Scala's adoption.
