### ISSUE TITLE
Provide a way to disable layered classloader of scala-library and user classpath

### ISSUE THREAD

**Issue by retronym** [sbt/sbt#4039]
## steps

 - clone https://github.com/retronym/minimized-list-serialization @ 838f3fb787f0671ceb83f3af08a040623d239298
 - `sbt run`
 - See output in https://github.com/retronym/minimized-list-serialization/blob/838f3fb787f0671ceb83f3af08a040623d239298/README.md

## problem

SBT reuses a classloader for the scala library JAR (it used to be more JARs, before #3405), and adds the rest of the classpath into a child classloader.

The motivation for this is performance.

However, this non-standard classloader setup can cause problems with deserialization. It seems that these are near impossible to solve in the custom deserialization code in the Scala collections library itself due to an apparent limitation of `ObjectInputStream`

## expectation

The user should have a way to opt-out of the layered classloaders. Right now, `fork := true` does the trick, but sometimes there are other factors that might influence the decision to run in forked mode or not.

The solution to #4009 will likely be applicable to this bug, however the UI might differ a little.

## notes

sbt version: 1.1.2

**Comment by OlegYch** [comment]
i'd suggest going the opposite way https://github.com/sbt/sbt/issues/4111
reusing jvm without reusing classloaders has little to no benefit, and the libs which abuse classloaders tend to abuse other parts of jvm making it non-reentrant https://github.com/OlegYch/blog/blob/master/sbt-fork.md

**Comment by retronym** [comment]
The loaded/JIT-ted Java standard library would be at least shared, in addition to the heap.

I don't think there is a right answer in the "to fork or not to fork" question. You make a good argument that forking by default is the least surprising and makes it easiest to reason about failures.

**Comment by SethTisue** [comment]
can this be closed now that we have `classLoaderLayeringStrategy`?
