### ISSUE TITLE
SBT 1.1.2 with Windows and JDK 10 gives a warning that it does not support Java 0

### ISSUE THREAD

**Issue by dhinojosa** [sbt/sbt#4055]
(See the guidelines for contributing, linked above)

## steps
Go to a Windows Machine
Install JDK 10
Install SBT 1.1.2
Run any command in SBT

## problem
There is no such thing as JDK 0

## expectation
It should work fine with JDK 10 with no warning or error

## notes
See Image

sbt version: 1.1.2
![dzqzfkhvoaazf0o](https://user-images.githubusercontent.com/410757/38178041-6cd2953a-35c7-11e8-87ed-c9ba437635b4.jpg)

**Comment by firephil** [comment]
I have a similar problem with sbt and trying to run with jmh simple micro benchmark

**Comment by mwdruz** [comment]
Sbt scripts don't take java 10 into account
In sbt.bat apparently there's no
`>nul findstr /c:"version \"10" "%TEMP%\out.txt"`
`if /I %ERRORLEVEL% EQU 0 (set JAVA_VERSION=10)`

Also sbt-launch-lib.bash uses "<" comparison, which compares java version as strings, i.e. "10" is less than "9". Should be
`[["$java_version" -lt "8" ]]`
instead of
`[["$java_version" < "8" ]]`
etc.

**Comment by saikartik1990** [comment]
Thanks a lot, MR. SirKruk. You saved my day. 👍

**Comment by saikartik1990** [comment]
But still I'm seeing this issue "scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found." Please help @SirKruk

**Comment by eed3si9n** [comment]
Thanks for the report and detective work everyone.

Probably next step would be adding JDK 10 to the existing matrix of testing:
- https://github.com/sbt/sbt-launcher-package/blob/master/.travis.yml
- https://github.com/sbt/sbt-launcher-package/blob/master/.appveyor.yml

**Comment by Abhi-joshi** [comment]
Tried  sbt 1.1.4 and the patch is not working as expected. Getting same error mentioned in the ticket.

> The Java Development Kit (JDK) installation you have is not up to date.
> sbt requires at least version 6+, you have
> version 0
> 
> Please go to http://www.oracle.com/technetwork/java/javase/downloads/ and download
> a valid JDK and install before running sbt.

**Comment by dhinojosa** [comment]
Grr. Still not working

**Comment by eed3si9n** [comment]
Hopefully https://github.com/sbt/sbt-launcher-package/pull/227 passes the tests.

**Comment by dennisheperol** [comment]
I'm having the same error except I'm actually using Java 8, this is probably related?  

![powershell_2018-04-23_23-22-28](https://user-images.githubusercontent.com/9365457/39167699-d278daa4-4790-11e8-9d81-690e1d906130.png)

**Comment by Facsimiler** [comment]
For what it's worth, I'm seeing this error in _SBT_ 1.1.4, but I'm using _Java JDK_ 8.

Output from `java -version`:

```
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```

Initial output from `sbt`:

```
The Java Development Kit (JDK) installation you have is not up to date.
sbt requires at least version 6+, you have
version 0

Please go to http://www.oracle.com/technetwork/java/javase/downloads/ and download
a valid JDK and install before running sbt.
```

That said, the build continues OK.

**Comment by rmginv** [comment]
I'm just reiterating what MichaelJAllen said since I believe it is fairly important to really important. 
```
javac -version
javac 1.8.0_101
```

**Comment by Facsimiler** [comment]
This issue with JDK 8 is fixed for me with the 1.1.5 release. Quick work! Thanks!

**Comment by eed3si9n** [comment]
Nice. I am closing this as resolved.

**Comment by dhinojosa** [comment]
With all due respect, the ticket is in reference to JDK 10 and not 8.  Does this fix also work with 10?

**Comment by ghost** [comment]
I still get this error in windows i have java 10. sbt 1.1.5. and scala 2.12.6

**Comment by tiankchen** [comment]
> I still get this error in windows i have java 10. sbt 1.1.5. and scala 2.12.6

hi, you may check the JAVA_HOME variable, make it is not contains an space character in Windows, especially like 'c:/Program files',  then install Java in 'c:/java', it's OK

**Comment by er1c** [comment]
I'm using JDK11 and this is working (at least in `1.3.3`) - is this still an issue in 1.3.3?

**Comment by objk2001** [comment]
> I'm using JDK11 and this is working (at least in `1.3.3`) - is this still an issue in 1.3.3?

Just like erc1 I am using Java11(openjdk version "11.0.4" 2019-07-16 LTS) with sbt 1.3.3 and experiencing same exact issue.

**Comment by fancellu** [comment]
Same for me, using graal in windows 10

java version "11.0.7" 2020-04-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.7+8-LTS, mixed mode)

**Comment by eed3si9n** [comment]
Note that any bugs in `sbt.bat` needs be resolved by reinstalling the `sbt.bat` via installer. Could you run `sbt --script-version` and see what it returns?

**Comment by fancellu** [comment]
`[error] Expected ';'
[error] --script-version
[error]`

However looking at the windows installer for sbt, I see it said 0.13.16

I uninstalled that then installed the brand new sbt-1.3.10.msi

When I say --script-version again it then said 1.3.10

And most importantly, didn't complain about "java 0"

Thanks for the advice

**Comment by eed3si9n** [comment]
> When I say --script-version again it then said 1.3.10
>
> And most importantly, didn't complain about "java 0"

Closing this issue now.
