### ISSUE TITLE
Plugin detection for Dotty

### ISSUE THREAD

**Issue by liufengyun** [sbt/sbt#4073]
Dotty recently ported plugin structure from Scalac with minor adaptions https://github.com/lampepfl/dotty/pull/3438 .

One change is to use `plugin.properties` instead of `scalac-plugin.xml`, as suggested by @som-snytt and @smarter.

However, currently SBT only detects `scalac-plugin.xml`, which makes it difficult to use Dotty plugins. We need to resort to a hack in order to make SBT work for Dotty https://github.com/lampepfl/dotty/pull/4215.

I see several potential approaches to tackle the problem:

1. detect `scalac-plugin.xml` or `plugin.properties` according to current compiler is Dotty or Scalac.
     - change scope: only SBT change.
2. compiler interface should implement detection logic, SBT should be ignorant
    - change scope: SBT & compiler interface

@eed3si9n @dwijnand: could you give some direction on what is the best approach to deal with the problem? I can work on a PR for according to the decided proposal. Thanks in advance.

<details>
<summary>Relevant SBT code</summary>

https://github.com/sbt/sbt/blob/v0.13.15/util/classpath/src/main/scala/sbt/classpath/ClasspathUtilities.scala#L100-L105

```Scala
  /** Returns all entries in 'classpath' that correspond to a compiler plugin.*/
  private[sbt] def compilerPlugins(classpath: Seq[File]): Iterable[File] =
    {
      import collection.JavaConversions._
      val loader = new URLClassLoader(Path.toURLs(classpath))
      loader.getResources("scalac-plugin.xml").toList.flatMap(asFile(true))
    }
```

https://github.com/sbt/sbt/blob/v0.13.15/main/src/main/scala/sbt/Defaults.scala#L1856-L1863
</details>

**Comment by eed3si9n** [comment]
ClasspathUtilities is now in Zinc - https://github.com/sbt/zinc/blob/1.x/internal/zinc-classpath/src/main/scala/sbt/internal/inc/classpath/ClasspathUtilities.scala, so my opinion is to implement there.

> detect scalac-plugin.xml or plugin.properties according to current compiler is Dotty or Scalac.

You can try to detect both, or potentially make a version of `compilerPlugins(...)` that take additional Boolean parameter `isDotty`?

**Comment by liufengyun** [comment]
Thanks @eed3si9n . I think taking a parameter `isDotty: Boolean` seems better. I'll make a PR for `0.13.*` and `1.*` respectively.

**Comment by smarter** [comment]
@liufengyun I don't think it's worth making a pr for 0.13 since as soon as we switch Dotty itself to sbt 1, we won't be able to support user projects using 0.13

**Comment by liufengyun** [comment]
@smarter : thanks, that's good news for me :)
