### ISSUE TITLE
warn on value discard in build code

### ISSUE THREAD

**Issue by OlegYch** [sbt/sbt#4079]
## steps
someone declares TaskKey[Unit] and tries to define it, but doesn't know about .value or accidentally omits it
```scala
lazy val npmBuildTask = taskKey[Unit]("Execute the npm build command to build the ui")
npmBuildTask := {
  Process("npm run build", file(appPath))
}
lazy val npmInstallTask = taskKey[Unit]("Execute the npm install command to build the ui")
npmInstallTask := {
  Process("npm install", file(appPath))
}
lazy val npmTask = taskKey[Unit]("execute all npm tasks")
npmTask := {
  npmInstallTask
  npmBuildTask
}
```

## problem
nothing happens

## expectation
useful error message or warning

## notes
i suggest enabling -Ywarn-value-discard for builds by default

**Comment by eed3si9n** [comment]
I've discussed about this phenomena a few times with others too.

I wonder if there's something specific about `Unit`, or maybe anytime you see an `Initialized[A]` expression inside a task body is suspicious, and worth printing a warning:

```
[warn] build.sbt:11: TaskKey[Unit] 'npmInstallTask' doesn't do anything in this position. did you forget to call `.value`? 
  npmInstallTask
  ^
[warn] build.sbt:11: TaskKey[Unit] 'npmBuildTask' doesn't do anything in this position. did you forget to call `.value`? 
  npmBuildTask
  ^
```

**Comment by dwijnand** [comment]
:+1: for adding `-Ywarn-value-discard` to builds' `scalacOptions`.

if I remember correctly when I tried this it had very few false positives.

**Comment by OlegYch** [comment]
yeah i think it's useful not only for Initialize, and i get very few false positives too
on a related note, i think we should discourage Task[Unit] somehow

**Comment by eed3si9n** [comment]
Wouldn't the warning go away if the build user puts `()` at the end? Would they know to call `.value`?
It also would only pick up the one at the last position.

**Comment by OlegYch** [comment]
@eed3si9n you're right it works only in last position, so adding a specific warning is worth it
perhaps scalacs "a pure expression does nothing in statement position" could be customized
`-Ywarn-value-discard` is still valuable by itself imo

**Comment by eed3si9n** [comment]
Here's a fix - https://github.com/sbt/sbt/pull/4090
