### ISSUE TITLE
Migrate all kebab-case commands to camelCase

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4081]
This is a generalized issue for https://github.com/sbt/sbt/issues/4072

While #4072 talks about `lastGrep`, looking at https://github.com/sbt/sbt/blob/1.x/main/src/main/scala/sbt/internal/CommandStrings.scala, there are some more kebab-cased command names. It would be good to migrate them for the sake of consistency.

**Comment by Asamsig** [comment]
Looking into this!

**Comment by dwijnand** [comment]
Looks like there are only 3 left:

```
11:00:02 $ rg '"[a-z]+-[a-z]+"' -- main/src/main/scala/sbt/internal/CommandStrings.scala
60:  val OldLastGrepCommand = "last-grep"
289:  def LoadCommand = "load-commands"
292:  def LoadFailed = "load-failed"
```

**Comment by eed3si9n** [comment]
See also https://github.com/sbt/sbt/blob/v1.1.5/main-command/src/main/scala/sbt/BasicCommandStrings.scala#L188-L198

**Comment by dwijnand** [comment]
Fixed by #4159.

**Comment by naferx** [comment]
Hi @dwijnand , I know it is closed but just for curiosity 

I typed
```
sbt:test> load-commands
[error] Not a valid command: load-commands (similar: load-failed)
[error] Not a valid project ID: load-commands
[error] Expected ':'
[error] Not a valid key: load-commands (similar: commands, cleanupCommands, initialCommands)
[error] load-commands
[error]              ^
```
Is it used internally ?

**Comment by dwijnand** [comment]
@naferx In working with @Asamsig on #4159 we found out that those commands had been removed a long time ago. Which is why in #4159 we just removed the strings.

**Comment by naferx** [comment]
ah, good to know.
Thanks Dale
