### ISSUE TITLE
sbt hangs searching for files to compile

### ISSUE THREAD

**Issue by bchurchill** [sbt/sbt#409]
To reproduce:
1.  Setup a new project at sbt where sbt automatically compiles each file in your /src directory.
2.  Create a symbolic link from your project folder to your folder of sources.
3.  Create a symbolic link from your folder of sources to your projects folder.
4.  Run 'sbt clean' and 'sbt compile'.

At this point, sbt will get stuck in an infinite loop looking for files!
It would be great if sbt could detect the cyclic dependency in the symbolic links and not follow them forever :).
Please let me know if you have any trouble reproducing this.

**Comment by harrah** [comment]
It doesn't make sense to link from your sources directory to your project directory.  Even if cycles were detected, your whole project directory will be traversed looking for sources.

Should you wish to implement this anyway, you might start at directory traversal in PathFinder: https://github.com/harrah/xsbt/blob/0.12/util/io/Path.scala#L211

**Comment by bchurchill** [comment]
There are good reasons to do this...  I'm working on a large project where the source I'm primarily responsible for is several nested folders deep into the source code.  I would like a symbolic link 'mysrc' in the project home to easily navigate there from my shell.  I would also like a symbolic link backward for navigation too.  This is a very normal thing for people to do.  Unfortunately, it took me about 20 minutes to figure out why sbt was hanging (because it didn't even cross my mind this would be a problem).  From my point of view, the symbolic link wasn't for adding a new folder to sbt to search at all.

So, even if this is a very low priority issue, I recommend that it be kept open.  In fact, I would be happy to work on a patch myself if you think that a well-written one would be accepted.

**Comment by harrah** [comment]
```
<base>/
  src/main/scala/
    org/
      example/
        symlink/  -> <base>
```

Now, a source file traversal will start in `src/main/scala/` and recurse into `org/example/` and pick up all sources there.  Then it will follow the symlink to `<base>` and _continue recursing_.  It will pick up test sources, any build definition sources in `project/`, ...

**Comment by bchurchill** [comment]
ah, okay, I see why having a symlink would be rather awkward there.
