### ISSUE TITLE
Associate ModuleID to externalDependencyClasspath entries 

### ISSUE THREAD

**Issue by ijuma** [sbt/sbt#41]
It's useful to know the ModuleID for each Attributed[File] returned from externalDependencyClasspath. Mark said:

"Attributed is a typesafe heterogeneous map.  It is currently only used to track the Analysis instance for an entry, but could probably be extended to associate the ModuleID and Artifact with the entry.  Please open a ticket if this sounds good."

The context of this is explained in more detail in the following thread about sbt-idea:

https://groups.google.com/d/msg/simple-build-tool/ccIYjMBYaLA/ReWUfVCtPu0J

**Comment by ijuma** [comment]
Thanks for this and other fixes committed today. :) Do you have a rough plan for when you plan to release 0.10.1?

**Comment by harrah** [comment]
I'd like to work with the 0.10-based build some more to ensure there aren't major issues.  I think #5, #32, and #39 can be fixed for 0.10.1.  I still need to evaluate #44 and #46.  Also, there isn't anything in place to prevent additional work for plugin authors when a new version comes out.  Perhaps this won't be done for 0.10.1, though.

**Comment by ijuma** [comment]
Makes sense. I think the plugins stuff could wait until 0.10.2. For what is worth 0.10.0 has been pretty solid for me apart from polish issues and that weird issue that completely broke my build before I found the even weirder workaround:

https://groups.google.com/d/topic/simple-build-tool/2hho4BzkBDM/discussion

I still need to make some time to investigate that a bit more.
