### ISSUE TITLE
Some specific dependencies keep getting corrupted

### ISSUE THREAD

**Issue by eamelink** [sbt/sbt#410]
Hi,

I'm doing a bunch of Play 2.0 project, with the final release. On my Jenkins build server, I use plain SBT 0.11.2 to build these projects.

However, I'm running into the following issue on a daily basis:

[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.slf4j#slf4j-api;1.6.1: configuration not found in org.slf4j#slf4j-api;1.6.1: 'compile'. It was required from org.hibernate#hibernate-validator;4.2.0.Final compile
[warn]  :: commons-codec#commons-codec;1.4: configuration not found in commons-codec#commons-codec;1.4: 'compile'. It was required from org.apache.httpcomponents#httpclient;4.1.2 compile
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::

Now, the weird thing is that it's always these two. commons-codec-1.4 and slf4j-api. To fix it, I delete the .ivy2/cache/commons-codec and slf4j dirs, and then sbt re-downloads them and all is fine for a few builds, until the same happens again.

When it's broken, I notice that the file ~/.ivy2/cache/commons-codec/commons-codec/ivy-1.4.xml is much smaller than on a machine where it works, even though ivy-1.4.xml.original is identical on both machines.

Here are copies of ivy-1.4.xml from both a working and broken machine, and also the ivy-1.4.xml.original: https://gist.github.com/2168241

I hope this is enough information to figure out what may causing this and whether it's sbt's fault or something else. If not, I'll be happy to produce additional information or files if needed. I'm also in the #sbt channel as eamelink if you need anything else.

**Comment by eamelink** [comment]
Actually, it seems like it may be caused by Play 1.2.4 (non-sbt), of which some projects are also run on the same machine: 

https://play.lighthouseapp.com/projects/57987/tickets/1419-play-dependencies-creates-ivy-cache-file-with-missing-configurations-breaking-sbt

**Comment by harrah** [comment]
Closing per follow-up comment.
