### ISSUE TITLE
Issue finding Java classes defined in interfaces when compiling Scala code referencing them

### ISSUE THREAD

**Issue by pmeheut** [sbt/sbt#4101]
## steps

1. Unzip the small sbt project
2. It will create a directory foo. Enter it
3. Launch sbt (any version, I tested with 0.13, 1.1.2, 1.1.4)
4. compile

[foo.zip](https://github.com/sbt/sbt/files/1919700/foo.zip)

## problem

Compilation ends with an error:
`[error] /Users/pascal/foo/src/main/java/Bar.java:2:34: not found: type DefaultFoo
[error] 	public class DefaultBar extends DefaultFoo implements Bar {`

## expectation

No error as the code is correct and the Java compiler (1.8) processes it easily. It seems that sbt/scala does not manages scopes in subclasses properly.

## notes

An obvious workaround is to change the java code to `public class DefaultBar extends Foo.DefaultFoo`
But as we have a huge code base written this way, this is inconvenient.
We also have the same bug inside methods where scala does not see enum defined as subclasses of an interface another Java class extends.
So each time we add a scala class, part of our Java classes do not compile under sbt anymore...

sbt version: 1.1.2

**Comment by eed3si9n** [comment]
@pmeheut Thanks for the report.

I am seeing the error using `scalac`:

```
$ scalac src/main/java/Bar.java src/main/java/Foo.java src/main/scala/Quux.scala
src/main/java/Bar.java:2: error: not found: type DefaultFoo
	public class DefaultBar extends DefaultFoo implements Bar {
                                        ^
one error found
```

so I think this is a Scala problem. Please resubmit this bug to https://github.com/scala/bug/issues
