### ISSUE TITLE
Still unable to fetch org.scala-sbt:compiler-bridge_2.12:1.0.3

### ISSUE THREAD

**Issue by kolotyluk** [sbt/sbt#4105]
(See the guidelines for contributing, linked above)

## steps

Create a sample app with scala 2.12.5 and sbt 1.1.4
sbt compile

## problem

Same as https://github.com/sbt/sbt/issues/3684

## expectation

SBT should be able to fetch org.scala-sbt#compiler-bridge_2.12;1.0.3 and compile code.

## notes

sbt version:1.1.4

**Comment by dwijnand** [comment]
in order to upgrade your build to sbt 1.1.4 you need to change the `sbt.version` in `project/build.properties`. the fact that it's still referring to 1.0.3 indicates (to me) that it's still using sbt 1.0.3.

try that.

**Comment by kolotyluk** [comment]
DOH!

When IntelliJ created the SBT project, it put 1.0.3 in there for some reason. project/build.properties is another one of those "out of sight, out of mind" traps.

Thanks for the tip.

**Comment by dwijnand** [comment]
Interesting, I've never created an sbt project from within IntelliJ. Perhaps you could give that feedback and maybe they can make the selection more prominent. For sbt itself you can use the `about` command to get sbt information.
