### ISSUE TITLE
aggregate across configurations

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#4107]
This is a feature request that is a bit vague, so please consider it more of a conversation.

I have several use cases for wanting to aggregate a task at the level of the configuration, not the Project. e.g. I often create a manual alias for `cpl`, `lint` or something else to do compilation on the entire project but it needs to know which test configurations are active and therefore must be hardcoded. I also would like to generate `.ensime` files in every base source directory to allow a new architecture.

But without the ability to say "run this task for every project and configuration pair" I am unable to achieve any of this :sob:

**Comment by laughedelic** [comment]
I think it's possible to do now. Take a look at what we do in sbt-metals: this is defined globally

https://github.com/scalameta/metals/blob/fcac1cc31fedf0a2dd8a1c723cc97c59a398edca/sbt-metals/src/main/scala/scala/meta/sbt/MetalsPlugin.scala#L68-L71

then this is defined on the project level:

https://github.com/scalameta/metals/blob/fcac1cc31fedf0a2dd8a1c723cc97c59a398edca/sbt-metals/src/main/scala/scala/meta/sbt/MetalsPlugin.scala#L21-L30

and then `metalsWriteBuildInfo` key is defined finally on the project + configuration level (`projectSettings` + `inConfig`).

**Comment by fommil** [comment]
your `metalsSettings` hack is the mechanism to get access to the `Configuration`s for a `Project`. I've used this hack in the past, it is not enough.

The litmus test is if I can define a task in my `~/.sbt` that I can run in any build and will aggregate across all configurations in all projects.

**Comment by dwijnand** [comment]
> which test configurations are active

there's no concept of "active" (afaik).

if there were we could extend `ScopeFilter` to have an `inAnyActiveConfiguration` and just define the task once without "the `metalsSettings` hack".

what happens if you use `inAnyConfiguration`?

**Comment by fommil** [comment]
Hmm, maybe I should investigate this API in more detail...

**Comment by fommil** [comment]
unfortunately, that's not going to work (at least not naively).

To make a solid example, I want to run something like this (which according to https://www.scala-sbt.org/1.x/docs/Tasks.html#ScopeFilter means that it works for all configurations)

```scala
TaskKey[Unit]("fmt") := {
  scalafixTest.all(ScopeFilter()).value
}
```

but 

```
[error] Runtime reference to undefined setting: 
[error] 
[error]   scalafixTest from fmt
[error]      Did you mean Compile / scalafixTest ?
```

what I want is for `scalafixTest in config` to run for each of the projects.

Let's say we have

```scala
val a = project
val b = project.configs(IntegrationTest).dependsOn(a % "test,it")
```

I want `fmt` to run the following

```
a / Compile / scalafmtTest
a / Test / scalafmtTest
b / Compile / scalafmtTest
b / Test / scalafmtTest
b / IntegrationTest / scalafmtTest
```

**Comment by dwijnand** [comment]
> an unspecified configuration filter will select scopes in the global configuration

doesn't mean "it works for all configurations".

so you probably want

```scala
ScopeFilter(configurations = inAnyConfiguration)
```

or

```scala
ScopeFilter(inAnyProject, inAnyConfiguration)
```

or maybe try something like

```scala
ScopeFilter(inAggregates(ThisProject), inAnyConfiguration)
```

note that `inAggregates` also has an `includeRoot` default param you can turn false.

**Comment by fommil** [comment]
oh, I was reading the bit "`Default filter (inAnyProject, inAnyConfiguration, inAnyTask)`" and assumed that's what the default was doing.

**Comment by fommil** [comment]
nope, we need some concept of active configurations. This

```scala
TaskKey[Unit]("fix") := {
  scalafixTest.all(
    ScopeFilter.debug(
      ScopeFilter(
        inAggregates(ThisProject, includeRoot = false),
        inAnyConfiguration -- inConfigurations(Optional, Provided, Runtime)
      )
    )
  ).value
}
```

is giving

```
[error]   a / IntegrationTest / scalafixTest from fix
```

Ideally I'd like to be able to pass a lambda (taking `Configuration`) instead of  `inAnyConfiguration -- inConfigurations(Optional, Provided, Runtime)`.

I'd also like to be able to make the scope dependent on another task existing in that scope... e.g. maybe if I was able to say "aggregate over every (project, config) pair that has a `scalafixTest` defined"

**Comment by dwijnand** [comment]
what does `[error]   a / IntegrationTest / scalafixTest from fix` mean?

> Ideally I'd like to be able to pass a lambda (taking Configuration)

you can't, I think, because it needs constant values for the scope axes.

> that has a scalafixTest defined

I think that information isn't available to ScopeFilter.

**Comment by fommil** [comment]
(that is error output) I think it means that the integration test config for "a" is included. But integration test is not active here, so no tasks exist.

**Comment by dwijnand** [comment]
Right, more "is not defined" trouble. Maybe can fix with a Global / scalafixTest definition? Not sure if it'll still delegate.

**Comment by smarter** [comment]
I was using `Def.derive` in the sbt-dotty plugin for similar purposes and had to stop because it's broken, see https://github.com/sbt/sbt/issues/3580
