### ISSUE TITLE
Reuse more classes between non-forked runs

### ISSUE THREAD

**Issue by OlegYch** [sbt/sbt#4111]
## steps
default setup, run a main class or tests

## problem
on every run a new classloader is created with all of classpath (except for scala-library according to this https://github.com/sbt/sbt/issues/4039 )
this wastes metaspace and discards jit results between runs

## expectation
as much as possible is reused, perhaps only build products are loaded in new classloader on each run, and the rest of `fullClasspath` is retained in a hot reusable classloader

## notes

sbt version: 1.1.4

**Comment by dwijnand** [comment]
interesting idea!

**Comment by dwijnand** [comment]
I'd be interested to see if any experimentations on large enough classpaths yield significant performance improvements.

**Comment by eed3si9n** [comment]
To potential contributor: sbt emulates `run` as a function call on a separate classloader from the build. Much of the necessary information should be located inside https://github.com/sbt/sbt/blob/1.x/run/src/main/scala/sbt/Run.scala.
There's a other part that does the whole thing in the background (aka `bgRun`), which is in https://github.com/sbt/sbt/blob/1.x/main/src/main/scala/sbt/internal/DefaultBackgroundJobService.scala, but likely you won't need to mess with that part.

@dwijnand Do you think could be a candidate for "good first'?

**Comment by dwijnand** [comment]
I think not, because of the performance implications and the lack of out-the-box automated performance analysis.

**Comment by eed3si9n** [comment]
Fixed in sbt 1.3.0.
