### ISSUE TITLE
Potential further optimise build (re)load speed with some NIO

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#4116]
In optimising PR https://github.com/sbt/sbt/pull/4067 @fommil [mentioned](https://github.com/sbt/sbt/pull/4067#issuecomment-380580693):

> you'll get even better timestamp performance if you use nio to walk a directory which means you get all timestamps of a directory in one OS call. I hope a change to fully nio is on the horizon for 2.0.

I started applying that in https://github.com/sbt/sbt/pull/4094, but ran out of steam. It was failing CI due to missing files.

Mentoring Instructions:

1. See the changes in https://github.com/sbt/sbt/pull/4094 and the CI validation failures in https://travis-ci.org/sbt/sbt/jobs/365337487.
2. I think all that is missing is handling missing files when reading the last modified time.
3. In terms of testing the existing test suite is sufficient. Specifically `scripted project/flatten` should work.
4. The motivation for this change is to speed up sbt's "(re)load", which affects both sbt startup and sbt's `reload` command.
5. As fommil mentions using NIO's directory walking fetches the timestamps of all the files in a directory in one OS call, so by using that instead of listing files and then getting last modified time we should improve load performance.

**Comment by eed3si9n** [comment]
See https://travis-ci.org/sbt/sbt/jobs/365337487 from https://github.com/sbt/sbt/pull/4094. `scripted project/flatten` should work.

**Comment by lbialy** [comment]
I have researched this and opened PR https://github.com/sbt/sbt/pull/4180. Performance gain was negligible or non-existent, I think this can be closed. FYI: @fommil
