### ISSUE TITLE
Packaged JAR file not re-generated if deleted

### ISSUE THREAD

**Issue by tindzk** [sbt/sbt#4118]
## Configuration
```scala
name := "sbt-test"

version := "0.1"

scalaVersion := "2.12.5"

artifactPath in (Compile, packageBin) := unmanagedBase.value / "build.jar"
```

## Steps
1. Run `packageBin`
2. Delete the `lib/build.jar` file
3. Run `packageBin`

## Problem
The `lib/build.jar` file is not re-created.

## Workaround
Remove `target/streams/compile/packageBin/$global/streams/output`.

## Notes
sbt version: 1.1.4

**Comment by dwijnand** [comment]
This one looks like a fun one to tackle.

**Comment by dadarakt** [comment]
I'll try to have a go at this

**Comment by dwijnand** [comment]
Writing down some spoken notes:

* I think this is an sbt/sbt only change (no need to depend on the sources of sbt/io, via sbt-allsources.sh)
* My guess is this is related to non-usage, mis-usage, or a bug in sbt.util.Tracked (which is in sbt/util - so maybe you might need to depend on the sources of sbt/util 😄)

**Comment by dwijnand** [comment]
Fixed in https://github.com/sbt/sbt/pull/4161, coming in 1.1.6.
