### ISSUE TITLE
sbt-eclipse

### ISSUE THREAD

**Issue by priya-aishh** [sbt/sbt#4142]
sbt =1.1.4
os =ubuntu 16.04
scala=2.12
scala IDE=4.7

I am trying to get this plugin working for the Apache Spark course here that relies on an old version of Eclipse Scala IDE 2.12 and SBT 1.1.4. but I am getting the below error with the sbteclipse-plugin on ubuntu 16.04.

[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /home/hadoop1/workspace/coursera/hello-world/project
[info] Updating ProjectRef(uri("file:/home/hadoop1/workspace/coursera/hello-world/project/"), "hello-world-build")...
[warn]  module not found: com.typesafe.sbteclipse#sbteclipse-plugin;5.1.0
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/5.1.0/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/5.1.0/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /home/hadoop1/.ivy2/local/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/5.1.0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/sbteclipse/sbteclipse-plugin_2.12_1.0/5.1.0/sbteclipse-plugin-5.1.0.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /home/hadoop1/.sbt/preloaded/com.typesafe.sbteclipse/sbteclipse-plugin/5.1.0/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////home/hadoop1/.sbt/preloaded/com/typesafe/sbteclipse/sbteclipse-plugin_2.12_1.0/5.1.0/sbteclipse-plugin-5.1.0.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.typesafe.sbteclipse#sbteclipse-plugin;5.1.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]   com.typesafe.sbteclipse:sbteclipse-plugin:5.1.0 (scalaVersion=2.12, sbtVersion=1.0)
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]   com.typesafe.sbteclipse:sbteclipse-plugin:5.1.0 (scalaVersion=2.12, sbtVersion=1.0) (/home/hadoop1/workspace/coursera/hello-world/project/plugins.sbt#L1-2)
[warn]     +- default:hello-world-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.sbteclipse#sbteclipse-plugin;5.1.0: not found
[error]  at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:334)
[error]  at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error]  at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error]  at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error]  at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]  at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]  at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error]  at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error]  at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error]  at xsbt.boot.Using$.withResource(Using.scala:10)
[error]  at xsbt.boot.Using$.apply(Using.scala:9)
[error]  at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error]  at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error]  at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]  at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]  at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]  at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error]  at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error]  at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error]  at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
[error]  at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error]  at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error]  at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:46)
[error]  at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:99)
[error]  at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error]  at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:112)
[error]  at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error]  at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:112)
[error]  at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:95)
[error]  at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error]  at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:126)
[error]  at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2385)
[error]  at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]  at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]  at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]  at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error]  at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]  at sbt.Execute.work(Execute.scala:271)
[error]  at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error]  at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]  at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error]  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]  at java.lang.Thread.run(Thread.java:748)
[error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.sbteclipse#sbteclipse-plugin;5.1.0: not found
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

**Comment by dwijnand** [comment]
We use GitHub issue mostly to track bugs and tasks on sbt development. If you need help, please check this out - https://www.scala-sbt.org/support.html

**Comment by priya-aishh** [comment]
thank you but i sorted it out actually the problem was the directory of plugin not even the version difference . When i added my plugins.sbt in the subdirectory project of my project directory , it worked .
like this PROJECR_DIR/project/plugins.sbt
