### ISSUE TITLE
when i run sbt , it report unresolved dependency: org.scala-sbt#sbt;0.13.13: not found

### ISSUE THREAD

**Issue by dujunling** [sbt/sbt#4147]
- [ ] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps
jenkins@abc   > sbt
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
Getting org.scala-sbt sbt 0.13.13 ...

it return 

:: problems summary ::
:::: WARNINGS
                module not found: org.scala-sbt#sbt;0.13.13

        ==== local: tried

          /home/jenkins/.ivy2/local/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml

          -- artifact org.scala-sbt#sbt;0.13.13!sbt.jar:

          /home/jenkins/.ivy2/local/org.scala-sbt/sbt/0.13.13/jars/sbt.jar

        ==== mavenLocal: tried

          file:/home/jenkins/.m2/repository/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.pom

          -- artifact org.scala-sbt#sbt;0.13.13!sbt.jar:

          file:/home/jenkins/.m2/repository/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.jar

        ==== repo-main: tried

          http://maven-repo/artifactory/maven-public/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.pom

          -- artifact org.scala-sbt#sbt;0.13.13!sbt.jar:

          http://maven-repo/artifactory/maven-public/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.jar

                ::::::::::::::::::::::::::::::::::::::::::::::

                ::          UNRESOLVED DEPENDENCIES         ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: org.scala-sbt#sbt;0.13.13: not found

                ::::::::::::::::::::::::::::::::::::::::::::::

## problem

In maven-repo, sbt path is org.scala-sbt/sbt/0.13.13/sbt-0.13.13.jar
it use  org/scala-sbt/sbt/0.13.13/sbt-0.13.13.jar to look up sbt , so can not find it.

## expectation

Getting sbt 0.13.13 successfully

## notes

sbt version: *insert sbt version*

**Comment by eed3si9n** [comment]
sbt 0.13.13 is hosted on an Ivy layout repository, so you need another resolver like `  my-ivy-proxy-releases: http://repo.company.com/ivy-releases/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]` described in https://www.scala-sbt.org/0.13/docs/Proxy-Repositories.html.

If you need more help, please check this out - https://www.scala-sbt.org/support.html
