### ISSUE TITLE
SBT JUnitXmlTestsListener is missing a timestamp field

### ISSUE THREAD

**Issue by timcharper** [sbt/sbt#4153]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps

```
cat <<-EOF | base64 -D | tar xz
H4sIAARw9loAA+3WW0vjQBQHcJ/nUxwGhBbdZJI2CSz4sIv4JoL6BdLpsR03TbIzEy9Iv7snk1p3fVAQ
L4jnB+mQk8mlmfwzsdjaJp51pppHbuZ33oNSKp9OoW+LPAutSof1IE0VJJO0yKZ5kaUJqGRS5GoH1Ltc
zROd86WlS/Fm9Ww/6nZx8cz24a/Atv0iKjOzpb09xBbrOdbaoIO9vQM4w78jASAbu4icLqvSo/MSdndB
/rsKchKpKJNiLERfOmm9aWoHP7dHOKeqi37ZRbfC2vcVOuqPTu6DpBu/QB9fdrXxkjaM6SiffT++Gxvy
76yO++GLw9jGQ/G0/+2Hb3gAXn+OF/NPxYf8T3PKf5qoouD8f4S21H/KBUIYciHMqm2sh/9SH90ddfVZ
i3ofjkuvl2jdWghdlc7B9hkBvPH0BnGw6QvXxi+3/eGO4j1Hp62Z4UiGveQ4VAGMH0lnquoWwkvloQyQ
gFs2XTX/jZCE0lr0y5pfEm9niDotl6j95juA1lq0nqaCtznHS/mnD4DH/BeK5v9CTTLO/0egb77oihJK
s/ZBQlN5yuFijDHGGGOMMcYYY4wxxhhjjLEv6R7wWUmyACgAAA==
EOF

cd repro
sbt test
```

Compare `target/junit/TEST-repro.ReproTest.xml` and `target/test-reports/repro.ReproTest.xml`. Note the former has a timestamp field, but the latter does not.

```
$ cat target/junit/TEST-repro.ReproTest.xml | grep timestamp
errors="0" failures="0" hostname="bastion.lan" name="repro.ReproTest" tests="1" time="0.032" timestamp="2018-05-11T22:36:50">
$ cat target/test-reports/repro.ReproTest.xml | grep timestamp
$
```

## problem

Timestamp is missing in the report generated by the default JUnitXmlReportPlugin; Jenkins (and other CI systems) expect this field and the value shows up as null in Jenkins reports.

## expectation

Timestamp should be present.

## notes

sbt version: 1.0.2

**Comment by eed3si9n** [comment]
The expectation seems reasonable, esp if that's what Jenkins expects.

**Comment by timcharper** [comment]
It doesn't look like there is a value we can use in `sbt.testing`; maybe we can just grab the current time when calling `startGroup`, pass to TestSuite? Seem okay?

**Comment by timcharper** [comment]
(scalatest looks at the start time of the SuiteStarting event: https://github.com/scalatest/scalatest/blob/3.1.x/scalatest/src/main/scala/org/scalatest/tools/JUnitXmlReporter.scala#L157)

**Comment by timcharper** [comment]
@eed3si9n worthy of note, it is also in the Junit XML spec:

https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/4154
