### ISSUE TITLE
Recover Resolving... log under UpdateLogging.Full

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4156]
## steps

1. Run `update` under debug or `UpdateLogging.Full`

## problem

"Resolving" log is no longer available because Ivy debug logs translate to `()`.

## expectation

1. Resolving log is available under "info" level, but only when ivyLoggingLevel is set to `UpdateLogging.Full`.

## notes

Ref https://github.com/sbt/librarymanagement/pull/51

Affected code:
https://github.com/sbt/librarymanagement/blob/v1.1.4/ivy/src/main/scala/sbt/internal/librarymanagement/ivyint/SbtChainResolver.scala#L88-L89

**Comment by hakonhw** [comment]
I will try to look at this one

**Comment by dwijnand** [comment]
Fixed in https://github.com/sbt/librarymanagement/pull/240, coming in 1.1.6.
