### ISSUE TITLE
Triggered Execution / Watching Broken in 1.1.5 on Linux

### ISSUE THREAD

**Issue by jamesward** [sbt/sbt#4167]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps
1. Run a triggered execution command on Linux with sbt 1.1.5
1. Change a file

## problem
Triggered execution doesn't run

## expectation
Triggered execution should run

## notes

sbt version: 1.1.5
jvm version: 1.8.0_171

**Comment by dwijnand** [comment]
@eatkins fancy triaging this?

**Comment by eatkins** [comment]
I believe it's fixed by https://github.com/sbt/io/pull/150

**Comment by dwijnand** [comment]
Thanks @eatkins. Fix coming in sbt 1.1.6 (or 1.2.0 if we cut that instead), @jamesward. We've not yet discussed when that'll be though.

**Comment by ppurang** [comment]
@dwijnand  @eed3si9n  User experience on linux is seriously hampered because of this. Could we please release this now? thanks

**Comment by dwijnand** [comment]
I think @eed3si9n might be releasing 1.1.6 soon (tm).

**Comment by jamesward** [comment]
This seems to be fixed in 1.1.6. Thanks all!

**Comment by ppurang** [comment]
Thanks - can confirm it works.
