### ISSUE TITLE
No display in scala console (REPL) on Ubuntu 18.04

### ISSUE THREAD

**Issue by peidaqi** [sbt/sbt#4173]
- [ ] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps

Run 'scala' to get the REPL

## problem
There is no display (key echo) when typing and Ctrl+D doesn't work.
Tried to remove ~/.sbt but didn't work.

## expectation
Echo of typed words

## notes
Using Ubunutu 18.04 LTS + 4.16.0 Kernel. Tried Zsh and Bash, neither one works.

sbt version: *insert sbt version*
1.1.5

**Comment by som-snytt** [comment]
It seems you're running `scala` at a bash shell prompt, not `console` at the sbt prompt? Then it's a `scala/scala` issue with JLine, not `sbt/sbt`.

**Comment by eed3si9n** [comment]
Yea. You can try `sbt console` and see if it works, but `scala` is not our command.

**Comment by krichter722** [comment]
@peidaqi did you report this at https://github.com/scala/bug?

**Comment by lokkju** [comment]
This seems to be an issue with JLine2 being built with JDK9+, but being used on JSK8.  If you're on bionic, try this PPA for jline2: https://launchpad.net/~lokkju/+archive/ubuntu/java-compat/

(or just download and install https://launchpad.net/~lokkju/+archive/ubuntu/java-compat/+build/16458066/+files/libjline2-java_2.14.6-1ubuntu1~bionicppa1_all.deb via dpkg)

You can verify jline2 is the problem by running `scala -Ydebug`, and looking for ByteBuffer class not found error.

I've also submitted bugs to hopefully address this issue in the future.

**Comment by sciencepal** [comment]
@lokkju +1 thanks a ton, was facing with the same issue. dpkg download is verified solution !

**Comment by vrozental** [comment]
@lokkju Thank you! I installed the `libjline2-java_2.14.6-1ubuntu1~bionicppa1_all.deb` (from the link above) on Ubuntu 18.04 and the Scala REPL works like charm!

**Comment by robinsonmhj** [comment]
works for me too

**Comment by goszjacek** [comment]
works for me as well

**Comment by Ch-sriram** [comment]
@lokkju the solution works like a charm. Thx a lot 💯
