### ISSUE TITLE
sbt failed, module not found

### ISSUE THREAD

**Issue by Fangyh09** [sbt/sbt#4176]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps
macOS *10.13.4*
```bash
brew install scala
brew install apache-spark
brew install sbt@1
mkdir foo-build
cd foo-build && sbt
```

Project struture
foo-build(sbt root)
At foo-build, run `sbt`
## problem
sbt failed
```bash
[warn] 	module not found: org.scala-sbt#zinc-classpath_2.12;1.1.5
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/zinc-classpath_2.12/1.1.5/ivys/ivy.xml
...
```

## notes

sbt version: *1.1.4*

**Comment by dwijnand** [comment]
You need to make sure your maven proxy includes Maven Central, because sbt is there:

http://repo1.maven.org/maven2/org/scala-sbt/zinc-classpath_2.12/1.1.5/
