### ISSUE TITLE
module not found: org.scala-sbt#sbt;1.1.5

### ISSUE THREAD

**Issue by bijiwei1** [sbt/sbt#4177]
I installed the sbt today and it successfully installed. However, when I tried to run sbt, I got following issue.

:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
unresolved dependency: org.scala-sbt#sbt;1.1.5: not found
Error during sbt execution: Error retrieving required libraries

**Comment by dwijnand** [comment]
sbt is on Maven Central, so something must be wrong with your connection to Maven Central, perhaps?

https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.1.5/

**Comment by bijiwei1** [comment]
Yes, that's my problem. I solved it following instructions in this link https://stackoverflow.com/a/48824820/9865995.
