### ISSUE TITLE
sbt ~ repeat cmd: source changes outside project directory and outside home directory

### ISSUE THREAD

**Issue by Rich2** [sbt/sbt#4179]
The ~ repeat command is not responding to changes of sources outside of the build directory and outside of the home directory in Sbt 1.1.6. This does work in 1.1.4 in Kubuntu 18.10, but not in Ubuntu 18.10.

I've created a Hello world project to demonstrate: [sbtrepeat](https://github.com/Richtype/sbtrepeat.gitl)

Clone this project outside of your home directory structure.
Edit the BuildFolder/build.sbt file to hardcode the absolute path of the source directory.
run sbt from the BuildFolder
 command: ~run
 edit and save the MyMain.scala file in the src directory.

For me repeat command does not respond by rebuilding and rerunning. However if you run "show watchSources" the src directory will be listed. 

#3499 may be related. This stopped working for me when upgrading to sbt 1.1.0

sbt version: 1.1.6

**Comment by dwijnand** [comment]
Lemme just /cc @eatkins, Director of ~ 😄

**Comment by eed3si9n** [comment]
Does this still happen with sbt 1.3.2?

**Comment by eed3si9n** [comment]
Hopefully it's now fixed. If not let us know.
