### ISSUE TITLE
Plain print project settings

### ISSUE THREAD

**Issue by willis7** [sbt/sbt#4184]
## problem
As a build master, I want to print the project settings in plain text for consumption by other scripts. For example, setting ENV vars, or setting properties in Jenkins pipeline scripts.

``` bash
export SBT_PROJECT_VERSION=$(sbt 'show version')
```

## expectation
When I run "show", I would like an output like:

>$ sbt 'show version'
0.1-SNAPSHOT

I dont want any log output. If there's an error, just print an empty string.

## notes
If changing the behaviour of `show` is not possible, then a new task like `$sbt 'print version'` would suffice.

I was steered here from a discussion on #840

**Comment by dwijnand** [comment]
Thank you opening the issue @willis7!

**Comment by jroper** [comment]
Since this isn't part of sbt 1.2.x yet, as a work around, this works:

```bash
sbt "show version" | tail -n 1 | cut -f2 -d" "
```

**Comment by jroper** [comment]
Just wanted this agains today. sbt dynver is essentially ususable in a CD setup (which in my opinion, should be one of the most useful applications of sbt dynver) without it, because there's no way to know what version it just tagged your docker image with, so that you can then deploy whatever it just built.

**Comment by dwijnand** [comment]
Why doesn't the `print` command in sbt 1.3+ work for you?

**Comment by qingwei91** [comment]
For people who bump into similar issue, with `sbt 1.3+` you can now use the following command

```
> sbt "print <submodule>/version" | tail -n 1
0.0.1
```

Note in multi-module project, you will need to specify `submodule` or else you will get output with whitespaces like 
```
       0.0.1
```

**Comment by SethTisue** [comment]
(as I also said on the related ticket #840)

`-error` sets the logging level and will prevent most kinds of extraneous unwanted output. This seems a bit more elegant to me than relying on `tail`, and still works even when you are expecting multiple lines of output.

In a script you'll probably want to also add `-batch` (a synonym for `< /dev/null`), which turns off supershell and prevents sbt from ever presenting any kind of interactive prompt whatsoever (e.g. if `build.sbt` doesn't compile)

so a typical full invocation in a script is:

    sbt -batch -error 'print version'
