### ISSUE TITLE
intermittent ServerSpec failure

### ISSUE THREAD

**Issue by SethTisue** [sbt/sbt#4186]
seen in Scala 2.12 community build (which is on the sbt 1.1.6 tags):

```
[sbt] [info] ServerSpec:
[sbt] [info] server
[sbt] [info] - should start *** FAILED ***
[sbt] [info]   java.lang.RuntimeException: Timeout. /tmp/sbt_35163e7f/handshake/project/target/active.json is not found.
[sbt] [info]   at scala.sys.package$.error(package.scala:26)
[sbt] [info]   at testpkg.TestServer.waitForPortfile(ServerSpec.scala:85)
[sbt] [info]   at testpkg.TestServer.waitForPortfile(ServerSpec.scala:88)
[sbt] [info]   at testpkg.TestServer.waitForPortfile(ServerSpec.scala:88)
[sbt] [info]   at testpkg.TestServer.waitForPortfile(ServerSpec.scala:88)
[sbt] [info]   at testpkg.TestServer.waitForPortfile(ServerSpec.scala:88)
[sbt] [info]   at testpkg.TestServer.waitForPortfile(ServerSpec.scala:88)
[sbt] [info]   at testpkg.TestServer.waitForPortfile(ServerSpec.scala:88)
[sbt] [info]   at testpkg.TestServer.waitForPortfile(ServerSpec.scala:88)
[sbt] [info]   at testpkg.TestServer.waitForPortfile(ServerSpec.scala:88)
[sbt] [info]   ...
```

full log at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/2984/consoleFull

**Comment by eed3si9n** [comment]
@SethTisue @cunei Is community build currently running `test`?
In #4213 I split up unit tests into server test and everything else, so by running `; safeUnitTests; otherUnitTests` it should run server tests on their own, which seems to make (at least) Travis happier.

**Comment by cunei** [comment]
The nightly sbt community tests sbt using `test`; I have not seen this failure so far, however.

**Comment by SethTisue** [comment]
okay, I guess we should optimistically close this; once a new sbt comes out and I move the community build onto newer tags, I'll try your recommendation. (I have added a comment to the config file so I don't forgot.)
