### ISSUE TITLE
Sbt fails to close file before deleting it

### ISSUE THREAD

**Issue by Katrix** [sbt/sbt#4188]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

Sometimes Sbt complains that it can't delete a file, even though it is the one keeping it open. For me this only happens with snapshots. I don't know if it can be caused by other stuff.

## steps
*I'm not that familiar with the ivy format stuff, so this is mostly just a guess.*
* Compile code and update dependencies.
* Clean
* Hope that a new snapshot has been pushed and that the stars align in just the right way
* Compile again
* Sbt will complain that it can't delete the snapshot artifact

Closing and restarting sbt fixes the issue.

## problem
Sbt complains that an artifact can't be deleted. However, Sbt is the one that is keeping the file open and thus preventing itself from deleting it.

## expectation
Sbt closes the file before deleting it.

## notes
I'm running Windows, which might be the cause.

sbt version: 1.1.1

**Comment by eed3si9n** [comment]
@Katrix Thanks for the report! Could you copy paste exact error message as you see it, in case it would provide more hints?

**Comment by Katrix** [comment]
Here is a snippet of the console output where I encountered the bug which shows it not being able to delete the artifact, shutting down and starting sbt again, cleaning, and compiling just fine.

https://hastebin.com/nuqiqevaze.tex

**Comment by eed3si9n** [comment]
Could you try on sbt 1.3.0-RC3 and see if the situation has improved?
