### ISSUE TITLE
Ctrl+C doesn't stop update task when network is unreachable (at least on Windows)

### ISSUE THREAD

**Issue by alex-vv** [sbt/sbt#424]
When I try to run `sbt update` without internet access on my Windows machine SBT tries to resolve dependencies and there is a significant delay for each check because it cannot find the server. The problem is that I cannot stop it because Ctrl+C and Ctrl+Break is not working. The only solution is to kill java process manually.

**Comment by eed3si9n** [comment]
Sorry for the late response. Is this behavior still the case for sbt 0.13.1?

**Comment by alex-vv** [comment]
I'm on OS X now, but I checked 0.13.6 on Windows 7 laptop and this issue seems to be resolved. It doesn't wait now for each check.
