### ISSUE TITLE
[sbt 1.2.0-RC1] reference to test is ambiguous

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt#4242]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

### build.properties

```
sbt.version=1.2.0-RC1
```

### project/plugins.sbt

```scala
libraryDependencies += "org.scala-sbt" %% "scripted-plugin" % sbtVersion.value
```

### build.sbt

```scala
test in Test := {
  println("skip test")
}
```

just launch `sbt`

## problem

```
build.sbt:1: error: reference to test is ambiguous;
it is imported twice in the same scope by
import _root_.sbt.Keys._
and import _root_.sbt._
test in Test := {
^
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

## expectation

success compile build.sbt file

## notes

sbt version: 1.2.0-RC1

**Comment by eed3si9n** [comment]
I was aware of this when I sent https://github.com/sbt/sbt/pull/3875.
I moved implementation of `sbt.test` to `sbt.scriptedtest` but I kept the old `sbt.test` in scripted-plugin for backward compatibility. If you use `SbtPlugin`, you won't need scripted-plugin any more.
