### ISSUE TITLE
"[warn] The `load-failed` command is deprecated" displayed when tab completing in shell

### ISSUE THREAD

**Issue by retronym** [sbt/sbt#4244]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps

 - Open a project with SBT 1.2.0-RC1. (The problem doesn't appear in 1.1.6)
 - Hit `<TAB>`
 - Witness:

```
sbt:jardiff> [warn] The `load-failed` command is deprecated in favor of `loadFailed` and will be removed in a later version
[warn] The `last-grep` command is deprecated in favor of `lastGrep` and will be removed in a later version

Display all 374 possibilities? (y or n)
```

## problem

Deprecation warnings unrelated to my task.

## expectation

The deprecation warning should only be shown if the command is invoked explicitly.

## notes

sbt version: 1.2.0-RC1

**Comment by retronym** [comment]
The deprecation was added in #4080

**Comment by retronym** [comment]
WIP : https://github.com/sbt/sbt/compare/1.x...retronym:ticket/4244

**Comment by eed3si9n** [comment]
Thanks for the report! The warning message was added in https://github.com/sbt/sbt/pull/4159 during Scala Spree Berlin. We should've thought about parser getting invoked during tab completion etc.

**Comment by eed3si9n** [comment]
The WIP branch looks good to me.
