### ISSUE TITLE
The output panel steals the focus each time a build happens

### ISSUE THREAD

**Issue by inkytonik** [sbt/sbt#4247]
- [ x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps

1. Open a scala project that uses sbt 1.1.x in VSCode.
2. Wait for the sbt server to start and be connected.
3. Make a change that introduces an error in a source file in the project.
4. Save the file.
5. The build happens and the problems are reflected in the VSCode problems list.

## problem

Unfortunately as well as updating the problems list, the steps above also change the focus of the lower panel area to the Output panel that shows the "sbt Scala Language Server" output. 

## expectation

That the focus would stay how it was when the file was saved (e.g., showing the problems). At the moment each time a build happens we must switch manually back to that panel from the output panel.

The following issue and the last comment on the issue suggests that a setting to preserve the focus can be included in the data sent and that resolves this problem at least for other language extensions.

https://github.com/Microsoft/vscode/issues/31474
 
## notes

sbt version: 1.1.6
vscode version: 1.24.1

**Comment by inkytonik** [comment]
Great! Thanks for the quick response.

**Comment by eed3si9n** [comment]
@inkytonik It's been bothering me (and I am sure anyyone who used the extension). Thanks for linking to the existing case on this. That was a good hint.
