### ISSUE TITLE
Publish GPG key in public keyserver

### ISSUE THREAD

**Issue by andersonvom** [sbt/sbt#4248]
- [✓] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## Steps

    $ gpg --verify --keyserver hkp://keyserver.ubuntu.com:80 sbt-1.1.6.tgz.asc sbt-1.1.6.tgz
    gpg: Firmado el Fri Feb  9 22:45:39 2018 CET
    gpg:                usando RSA clave 99E82A75642AC823
    gpg: Imposible comprobar la firma: No public key

## Problem

The key cannot be verified. The only way around it is to manually add the key to the local keychain:

    gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv 99E82A75642AC823

But even then, you get a warning about not being able to verify authenticity:

    gpg: Firmado el Tue May 29 18:46:09 2018 CEST
    gpg:                usando RSA clave 99E82A75642AC823
    gpg: Firma correcta de "sbt build tool <scalasbt@gmail.com>" [desconocido]
    gpg: ATENCI'ON: !Esta clave no est'a certificada por una firma de confianza!
    gpg:          No hay indicios de que la firma pertenezca al propietario.
    Huellas dactilares de la clave primaria: 2EE0 EA64 E40A 89B8 4B2D  F734 99E8 2A75 642A C823

## Expectation

It should be possible to verify the GPG key. It would also be nice if the email associated to the key looked more official, since `sbt build tool <scalasbt@gmail.com>` looks rather shady. Maybe something like `build@scala-sbt.org`?

## Notes

sbt version: not a problem with sbt, but the the key used to sign it.

**Comment by eed3si9n** [comment]
Thanks for the report!

**Comment by serv-inc** [comment]
Solution at https://stackoverflow.com/questions/51983144/error-installing-sbt-on-ubuntu-18-04-gpg-keyserver-receive-failed-invalid-ar

**Comment by serv-inc** [comment]
@eed3si9n : could you please update the docs?

**Comment by eed3si9n** [comment]
Updated the documentation in https://github.com/sbt/website/pull/825, but it seems like it's more to do with bionic using a buggy GnuPG version.
