### ISSUE TITLE
atmosphere-runtime dependency not being downloaded

### ISSUE THREAD

**Issue by thompson4822** [sbt/sbt#426]
In a project of mine I'm trying to use atmosphere for websocket support.  Unfortunately, one of the dependencies involved in making this happen is the atmosphere-runtime, which sbt 0.11.2 seems to be having troubles with.  Here is my dependency:

libraryDependencies += "org.atmosphere" % "atmosphere-runtime" % "0.8.6"

and here is the error that I'm getting:

[error] {file:/C:/cygwin/home/scala/myProject/*:update: sbt.ResolveException: download failed: org.atmosphere#atmosphere-runtime;0.8.6!atmosphere-runtime.jar(bundle)

I suspect that the issue is the '(bundle)' bit at the end of the error.  Does anyone know how to deal with this situation in SBT?

Let me know,

Steve Thompson

**Comment by harrah** [comment]
Hi Steve, I can't reproduce this with or without a clean cache.  The download succeeds/update completes ok.
