### ISSUE TITLE
Ubuntu 18.04 on WSL installation problem

### ISSUE THREAD

**Issue by andb0t** [sbt/sbt#4261]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps
* Follow the steps on [the sbt reference page](https://www.scala-sbt.org/1.0/docs/Installing-sbt-on-Linux.html)

## problem
The command `sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823` breaks with the following error:

```bash
› sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
Executing: /tmp/apt-key-gpghome.ZNijMDAMGR/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.ZNijMDAMGR/S.dirmngr' failed: IPC connect call failed
gpg: keyserver receive failed: No dirmngr
```

## expectation
A smooth install, like it worked for WSL and Ubuntu 16

## notes

sbt version: not applicable - just adding the keyserver fails!

On the WSL page, there is already [this issue](https://github.com/Microsoft/WSL/issues/3286), but for another application. Maybe it would be good to document the workaround once and for all for the sbt case? I have too little knowledge to apply the suggested fix to my sbt case. Can you help me?

**Comment by eed3si9n** [comment]
https://github.com/Microsoft/WSL/issues/3286#issuecomment-403914048 says it's a bug in gpg that's been fixed for a while, but not used by Ubuntu 18.04.
You could try https://github.com/Microsoft/WSL/issues/3286#issuecomment-402594992. ymmv.

**Comment by andb0t** [comment]
Hello there! Thanks a lot for  your help, it worked wonderfully! Now I can continue developing my scala library. Cheers!

**Comment by eed3si9n** [comment]
Ran into this recently while playing on Docker, so I'll paste it here.

```
curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
```
