### ISSUE TITLE
++ randomtext scalacOptions fails on 1.2-RC1

### ISSUE THREAD

**Issue by pshirshov** [sbt/sbt#4266]
1. `mkdir -p testsbt/project`
2. `testsbt`
3. `echo "sbt.version=1.2.0-RC1" > project/build.properties`

```
[info] Loading settings for project global-plugins from idea.sbt,build.sbt ...
[info] Loading global plugins from /Users/liyon/.sbt/1.0/plugins
[info] Loading project definition from /private/tmp/project
[info] Set current project to tmp (in build file:/private/tmp/)
[info] sbt server started at local:///Users/liyon/.sbt/1.0/server/0bb743f30d95c99d8743/sock
sbt:tmp> ++show scalacOptions
[info] Setting Scala version to show on 0 projects.
[info] Excluded 1 projects, run ++ show -v for more details.
[info] Reapplying settings...
[info] Set current project to tmp (in build file:/private/tmp/)
[error] Expected key
[error] all
[error]     ^
```

facepalm.jpg

**Comment by eed3si9n** [comment]
hmmm do you mean `+`?

```
sbt:helloworld> sbtVersion
[info] 1.2.0-RC1
sbt:helloworld> crossScalaVersions
[info] * 2.12.6
[info] * 2.11.12
sbt:helloworld> +show scalacOptions
[info] Forcing Scala version to 2.12.6 on all projects.
[info] Reapplying settings...
[info] Set current project to helloworld (in build file:/Users/eed3si9n/work/hellotest/)
[info] * -deprecation
[success] Total time: 0 s, completed Jul 14, 2018 10:58:36 PM
[info] Forcing Scala version to 2.11.12 on all projects.
[info] Reapplying settings...
[info] Set current project to helloworld (in build file:/Users/eed3si9n/work/hellotest/)
[info] * -deprecation
[success] Total time: 0 s, completed Jul 14, 2018 10:58:36 PM
[info] Reapplying settings...
[info] Set current project to helloworld (in build file:/Users/eed3si9n/work/hellotest/)
```

![wee-bey](https://i.kym-cdn.com/photos/images/newsfeed/001/240/699/000.gif)

**Comment by pshirshov** [comment]
Uhu, my bad, this isn't a correct command. 

On 1.1.6 and all the previous versions:

```
sbt:xxx> ++ show scalacOptions
[info] Setting Scala version to show on 0 projects.
[info] Excluded 39 projects, run ++ show -v for more details.
[info] Reapplying settings...
[info] Set current project to xxx (in build file:/tmp/xxx)
[success] Total time: 0 s, completed 15-Jul-2018 13:29:43
```

I understand that this command makes no sense.

Though  I had a test for this behavior and noticed that it changed. Previous one was kinda logical (I'm setting wrong version, all the projects are being excluded), new one throws a cryptic message.

**Comment by eed3si9n** [comment]
ok so your expectation is `> ++ randomtext scalacOption` should still work.
<s>I agree on that actually.</s> (see later comments)

sbt 1.2.0 brings strict aggregation which allows command to run on the Scala version you switched into. This might be a regression on https://github.com/sbt/sbt/pull/3995 /cc @ruippeixotog

**Comment by eed3si9n** [comment]
Then again, even tho the failure is accidental in this case, it might make sense for `++` command to fail if no projects match the `scalaVersion`.

**Comment by eed3si9n** [comment]
Consider the following:

```
sbt:helloworld> ++ 2.12.0-magic
[info] Setting Scala version to 2.12.0-magic on 0 projects.
[info] Excluded 3 projects, run ++ 2.12.0-magic -v for more details.
[info] Reapplying settings...
[info] Set current project to helloworld (in build file:/Users/eed3si9n/work/hellotest/)
sbt:helloworld> compile
```

If I am not paying attention, I could easily mistake that `++ 2.12.0-magic` actually worked, and now I am compiling using it.

**Comment by eed3si9n** [comment]
So maybe a better thing to do is close this case as "sort of works", and open a new issue that specifies that ++ that affected 0 projects should fail with some an  error message.

**Comment by eed3si9n** [comment]
See https://github.com/sbt/sbt/issues/4267

**Comment by pshirshov** [comment]
> ok so your expectation is > ++ randomtext scalacOption should still work.
Not really. My expectation is some kind of, ehm, sane result - a readable error message or success
