### ISSUE TITLE
Cannot download sbt on Mac OS X

### ISSUE THREAD

**Issue by jameslamb** [sbt/sbt#4279]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps

I am trying to install `sbt` on Mac OS X, and not getting very far. I suspect that the package server is down?

I tried

```
brew install sbt
```

per the recommendations on [the main sbt site](https://www.scala-sbt.org/0.13/docs/Installing-sbt-on-Mac.html). This throws error `SHA256 mismatch` and references https://piccolo.link/sbt-1.1.6.tgz. 

I tried simply directly navigating to `https://piccolo.link/sbt-1.1.6.tgz` from a browser and hitting it with `wget`. Both returned 503s, leading me to suspect that the server used to host `sbt` is down.

![image](https://user-images.githubusercontent.com/7608904/43050815-ca1e965c-8dd4-11e8-8252-0638ca5dbdee.png)

I also tried clicking the [ZIP link on the main sbt site](https://www.scala-sbt.org/0.13/docs/Installing-sbt-on-Mac.html). This sent me to https://cocl.us/sbt01316zip which also eventually throws a server error.

![image](https://user-images.githubusercontent.com/7608904/43050841-203210c8-8dd5-11e8-9e8b-551e9bb0de4b.png)

I did try downloading something completely different, [Hadoop 3.0.3](http://www.apache.org/dyn/closer.cgi/hadoop/common/hadoop-3.0.3/hadoop-3.0.3-src.tar.gz) on the off chance that maybe something is just wrong with my internet connection or some other strange thing. The downloads at that link worked without issue.

## expectation

I had expected a zipped archive with the `sbt` source to be return by the server.

## notes

sbt version: 1.1.6

Although I did also try for 0.13.x and had no better luck.

**Comment by eed3si9n** [comment]
The link works for me. Could you try again please?

**Comment by jameslamb** [comment]
@eed3si9n all working well now. Maybe I was just looking during a maintenance cycle or something.

I'll close this, thanks

**Comment by AVCloud** [comment]
piccolo link is down , Please find the msg below from terminal
**curl: (7) Failed to connect to piccolo.link port 443: Operation timed out**
