### ISSUE TITLE
scalaVersion in update affects publish URL

### ISSUE THREAD

**Issue by retronym** [sbt/sbt#428]
``` scala
scalaVersion := "2.9.2",
    scalaVersion in update <<= (scalaVersion) {
      case "2.9.2" => "2.9.1"
      case x => x
    },
```

```
[info]  published scalaz_2.9.2 to https://oss.sonatype.org/content/repositories/snapshots/org/scalaz/scalaz_2.9.1/7.0-SNAPSHOT/scalaz_2.9.2-7.0-SNAPSHOT.pom.asc
```

Sample project:

https://github.com/scalaz/scalaz/tree/2ebda1df0b99f90b69fc924995f8083639dc7490

**Comment by indrajitr** [comment]
Expectedly, `scalaVersion in update` would be different from `scalaVersion in publish` :) And I doubt if `scalaVersion in update` is meant to do anything other than just update and compile.

We have had this discussion at some point earlier (see first couple of comments in #267).

However, the approach committed in #267 is actually deprecated in favor of [`CrossVersion.binaryMapped`](https://github.com/harrah/xsbt/blob/0.13/ivy/CrossVersion.scala#L23) which should be available in 0.12 (I see that you are using 0.11.2 however).

FWIW, This is what I do in Lift: https://github.com/indrajitr/sbt-lift-build-plugin/blob/master/src/main/scala/LiftBuild.scala#L74

**Comment by retronym** [comment]
Okay, feel free to close as a won't-fix...

**Comment by indrajitr** [comment]
Let @harrah take the call :)

**Comment by harrah** [comment]
It isn't `scalaVersion in update` vs. `scalaVersion in publish` so much as it is scalaVersion used for dependency management vs. plain scalaVersion.  There isn't a separate configuration for the published scala version in 0.11.2 (I don't remember one and I don't see one looking at Defaults).

Regardless, things are improved in 0.12.0, with `crossVersion in projectID` configuring the version used for the project's published identifier.  See more on the 0.12 changes page: https://github.com/harrah/xsbt/wiki/ChangeSummary_0.12.0

**Comment by indrajitr** [comment]
I doubt existence of `scalaVersion in publish` too, just mentioned it in passing reference to explicitly express the fact that any `xxx in update` will revert back to a more general scope outside `update` task.

I just assumed @retronym ended up using `scalaVersion in update` primarily for dependency management.

**Comment by indrajitr** [comment]
Closing this for now. But @retronym, feel free to ping back later if it doesn't suit.
