### ISSUE TITLE
Publish the https://dl.bintray.com/sbt/debian/sbt-0.13.17.deb file

### ISSUE THREAD

**Issue by the21st** [sbt/sbt#4281]
## problem

The `.deb` release for sbt 0.13.17 doesn't exist in Bintray.

## expectation

The file exists at https://dl.bintray.com/sbt/debian/sbt-0.13.17.deb

## notes

sbt version: 0.13.17

**Comment by eed3si9n** [comment]
Ref https://github.com/sbt/sbt/issues/3916

**Comment by Crazy-Hopper** [comment]
Thank you for restarting this. Still think it is worth creating an official package.

**Comment by imarios** [comment]
@eed3si9n @the21st  I am getting this error: 
```
dpkg-deb: error: 'sbt-0.13.17.deb' is not a debian format archive
dpkg: error processing archive sbt-0.13.17.deb (--install):
```

**Comment by the21st** [comment]
@imarios might that be because the file does not exist at https://dl.bintray.com/sbt/debian/sbt-0.13.17.deb ? That's why I opened this Issue.

**Comment by eed3si9n** [comment]
Done. It's published.
