### ISSUE TITLE
missing sbt 1.2.0-RC3 tag on GitHub

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt#4283]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps

see
- https://github.com/sbt/sbt/tags
- https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.2.0-RC3/

<img width="411" alt="screen shot 2018-07-26 at 11 58 44" src="https://user-images.githubusercontent.com/389787/43238949-530b8d28-90cb-11e8-8f95-a0772056ea4b.png">

## problem

missing sbt 1.2.0-RC3 tag on GitHub

**Comment by eed3si9n** [comment]
Done https://github.com/sbt/sbt/releases/tag/v1.2.0-RC3
