### ISSUE TITLE
Disable ANSI escape sequence automatically when stdout is not tty

### ISSUE THREAD

**Issue by itchyny** [sbt/sbt#4284]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps
Type `sbt compile | tee compile.log` at the root directory of this repository.

## problem
`compile.log` contains ANSI escape sequences.

## expectation
When redirecting the output, I expect sbt does not output ANSI escape sequences.

## notes
I know the `-no-colors` option but changing the behavior based on stdout is tty or not is widely used (git, for example). This is useful when analyzing the compile log.

sbt version: 1.1.6

**Comment by eed3si9n** [comment]
It sounds like a good idea, but sbt also runs on CI environments like Travis and Jenkins. I don't know exactly how the implementation looks like, but it might look something like `sbt compile | tee compile.log`. It would be sad if CI logs then became no colors, because they seem to support colors.

**Comment by itchyny** [comment]
OK, I understand. I confirmed that Jenkins console output is surely colored as sbt output is. I thought this would improve my experience on local machine but I don't mind you close this issue due to compatibility.

**Comment by eed3si9n** [comment]
ok. Closing this for now, but feel free to experiment on your own and report back.

**Comment by Blaisorblade** [comment]
@eed3si9n FWIW, Unix tools *default* to disabling colors on non-ttys, but have a `--color=always` option for forcing colors on non-ttys, which would serve for scenarios like CI logs, piping to `less -R`, etc. I think that would be ideal and fit Unix expectations. But feel free to keep closed if you don't like it anyway.

**Comment by eed3si9n** [comment]
I guess we can try it and see how it goes with the CIs.
