### ISSUE TITLE
Changing aggregate dependencies in buildDependencies does not seem to do anything

### ISSUE THREAD

**Issue by ksit** [sbt/sbt#4286]
## steps
Consider the following **build.sbt** file:
```
lazy val a = (project in file("a")).
  settings(
    // the following should have the same effect as ".dependsOn(b)"
    buildDependencies in Global := {
      import sbt._
      val deps = (buildDependencies in Global).value
      val classpath = deps.classpath
      val aggregate = deps.aggregate
      val aggregate2 = aggregate ++ Map(thisProjectRef.value -> List(ProjectRef(thisProjectRef.value.build, "b")))
      BuildDependencies(classpath, aggregate2)
    }
  )

lazy val b = project in file("b")
```
When I tried to run the command `show version` in project "a", the same command does not get propagated to project "b".

## problem
According to the SBT Build Loaders documentation, we should be able to change the aggregate dependencies at setting evaluation time.  However, it seems that this is not the case.

## expectation
Run the "show version" command in project "a" should prints the version of both project "a" and "b".

## notes
https://www.scala-sbt.org/0.13/docs/Build-Loaders.html

sbt version: 0.13.17

**Comment by eed3si9n** [comment]
Thanks for the report, but I am going to close this since the feature no longer exist in sbt 1.x.
