### ISSUE TITLE
sbt 1.2.0 fails to load build definition if old `~/.sbt/boot/scala-2.12.6` directory is present

### ISSUE THREAD

**Issue by SethTisue** [sbt/sbt#4289]
I'm not sure if this depends on my previously having run 1.2.0-RCx versions on my machine, or whether any sbt 1 user might be affected

but in any case, however I got there, my existing `~/.sbt/boot/scala-2.12.6` lacks the following files:

```
Only in scala-2.12.6/org.scala-sbt/sbt/1.2.0: fastparse-utils_2.12-0.4.2.jar
Only in scala-2.12.6/org.scala-sbt/sbt/1.2.0: fastparse_2.12-0.4.2.jar
Only in scala-2.12.6/org.scala-sbt/sbt/1.2.0: lenses_2.12-0.4.12.jar
Only in scala-2.12.6/org.scala-sbt/sbt/1.2.0: protobuf-java-3.3.1.jar
Only in scala-2.12.6/org.scala-sbt/sbt/1.2.0: sbinary_2.12-0.4.4.jar
Only in scala-2.12.6/org.scala-sbt/sbt/1.2.0: scalapb-runtime_2.12-0.6.0.jar
Only in scala-2.12.6/org.scala-sbt/sbt/1.2.0: sourcecode_2.12-0.1.3.jar
```

and then when I run sbt 1.2.0, I get `java.lang.NoClassDefFoundError: com/trueaccord/scalapb/GeneratedEnum`:

<details>
<pre>
[error] java.lang.NoClassDefFoundError: com/trueaccord/scalapb/GeneratedEnum
[error] 	at java.lang.ClassLoader.defineClass1(Native Method)
[error] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[error] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[error] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[error] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[error] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[error] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[error] 	at java.security.AccessController.doPrivileged(Native Method)
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	at sbt.internal.inc.FileAnalysisStore$BinaryFileStore.<init>(FileAnalysisStore.scala:46)
[error] 	at sbt.internal.inc.FileAnalysisStore$.binary(FileAnalysisStore.scala:32)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler$.staticCachedStore(MixedAnalyzingCompiler.scala:342)
[error] 	at sbt.Defaults$.$anonfun$compileAnalysisSettings$1(Defaults.scala:1585)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.lang.ClassNotFoundException: com.trueaccord.scalapb.GeneratedEnum
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	at java.lang.ClassLoader.defineClass1(Native Method)
[error] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[error] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[error] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[error] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[error] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[error] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[error] 	at java.security.AccessController.doPrivileged(Native Method)
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	at sbt.internal.inc.FileAnalysisStore$BinaryFileStore.<init>(FileAnalysisStore.scala:46)
[error] 	at sbt.internal.inc.FileAnalysisStore$.binary(FileAnalysisStore.scala:32)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler$.staticCachedStore(MixedAnalyzingCompiler.scala:342)
[error] 	at sbt.Defaults$.$anonfun$compileAnalysisSettings$1(Defaults.scala:1585)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Compile / previousCompile) java.lang.NoClassDefFoundError: com/trueaccord/scalapb/GeneratedEnum
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
</pre>
</details>

downgrading my `project/build.properties` from 1.2.0 to 1.2.0-RC3 makes the problem go away

~~workaround is to blow away `~/.sbt/boot/scala-2.12.6` before launching sbt.~~ see below

there is one past report (on sbt 1.1.x) with the same error message: https://stackoverflow.com/questions/50001870/java-lang-noclassdeffounderror-com-trueaccord-scalapb-generatedenum

**Comment by SethTisue** [comment]
on my other laptop, the same JARs aren't missing from `~/.sbt/boot/scala-2.12.6`

so perhaps we'll never figure out how my one laptop got in a state where that directory was incomplete

perhaps this ticket should just be closed, and people googling the error will know to blow away `~/.sbt/boot` and try again

**Comment by SethTisue** [comment]
the root cause here seems to be a corrupt `~/.ivy2`

the corrupt `~/.ivy2` then leads to `~/.sbt/boot/scala-2.12.6` being messed up

so the full workaround is to blow away both `~/.sbt/boot` and `~/.ivy2`

**Comment by eed3si9n** [comment]
Not sure if there's much we can do on this one besides eventually stop using Ivy in launcher.

**Comment by eed3si9n** [comment]
Closing this for now, but the issue would likely live on on the label.
