### ISSUE TITLE
Confusing warning message for sbt version mismatch

### ISSUE THREAD

**Issue by anilkumarmyla** [sbt/sbt#4291]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps
Use a different version of sbt using `-sbt-version` argument than what is present in `project/build.properties`

```
$ cat project/build.properties 
sbt.version=1.1.6
$ sbt -sbt-version 1.2.0 update
[warn] sbt version mismatch, current: 1.2.0, in build.properties: "1.1.6", use 'reboot' to use the new value.
...
```

## problem
Warning message is confusing regarding which version of sbt will be used in project

## expectation
Warning message should tell what version of sbt will be used in the project and offer alternative to switch back to version from build.properties. `new value` is ambiguous wording in the message

## notes

sbt version: 1.2.0

**Comment by eed3si9n** [comment]
Thanks for the report @anilkumarmyla. Do you have a suggestion for an exact wording? (If not, it's ok too)

**Comment by anilkumarmyla** [comment]
@eed3si9n It would be nice if it said what version of sbt it will be using for the command to be executed and optionally offer alternative to use the version in build.properties. Something in the lines of `[warn] sbt version mismatch, using: 1.2.0, in build.properties: 1.1.6, use 'reboot' to use the version in build.properties`

**Comment by eed3si9n** [comment]
ok. Also how about not showing any warnings at all if sbt.version is passed in via command line?

**Comment by anilkumarmyla** [comment]
> Also how about not showing any warnings at all if sbt.version is passed in via command line?

That is also fine, but it is always good to show the sbt version being used on the project as an info log.

**Comment by octonato** [comment]
I just run into that and found it also confusing. I was not aware of `reboot`, so I tried it and got exactly the same message.

```bash
➜ update-to-play-2.8 git:(update-to-play-2.8) ✗ sbt -Dsbt.version=1.2.8
[warn] sbt version mismatch, current: 1.2.8, in build.properties: "1.3.5", use 'reboot' to use the new value. 

...

sbt:play-grpc> reboot
[warn] sbt version mismatch, current: 1.2.8, in build.properties: "1.3.5", use 'reboot' to use the new value.

...

sbt:play-grpc> sbtVersion
[info] play-grpc-scalatest / sbtVersion
[info]  1.2.8
```

Basically, `reboot` is not changing to the version in `build.properties`.

**Comment by lcgonsalves** [comment]
Reboot is not changing the version to the one in `build.properties`. Does anyone know how to force sbt to update to the correct version?
