### ISSUE TITLE
ClassCastException: sbt.internal.util.Init$SettingList cannot be cast to sbt.internal.util.Init$Setting

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt#4299]
Hello plugin authors:
Please refrain from building sbt plugins using sbt 1.2.0, and use 1.2.6 or whatever the latest.

-eugene

## original issue

https://github.com/wartremover/wartremover/issues/433

### steps

- build and publish sbt plugin with 1.2.0
- use sbt plugin with sbt 1.1.6

### problem

```
[error] java.lang.ClassCastException: sbt.internal.util.Init$SettingList cannot be cast to sbt.internal.util.Init$Setting
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
[error] 	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
[error] 	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
[error] 	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[error] 	at sbt.Project$.transform(Project.scala:533)
[error] 	at sbt.ProjectExtra.inScope(Project.scala:826)
[error] 	at sbt.ProjectExtra.inScope$(Project.scala:825)
[error] 	at sbt.package$.inScope(package.scala:10)
```

### expectation

Don't throw `ClassCastException`

**Comment by xuwei-k** [comment]
workaround: Don't use sbt 1.2.0 in sbt-plugin build. use 1.1.6

**Comment by eed3si9n** [comment]
I wonder if it's https://github.com/sbt/sbt/commit/f459b218c47a330354111c884e4f204cd9067d02 in #4106?

```diff
-  def inThisBuild(ss: Seq[Setting[_]]): Seq[Setting[_]] =
-    inScope(ThisScope.copy(project = Select(ThisBuild)))(ss)
+  def inThisBuild(ss: SettingsDefinition*): Seq[Setting[_]] =
+    inScope(ThisScope.copy(project = Select(ThisBuild)))(ss flatMap (_.settings))
```

sbt 1.2.0 converts `Seq[Setting[_]]` to `SettingList`, since it's a vararg, it's probably passing `Seq(SettingList(...))` where `Seq(Setting)` is expected.

We want might to revert this, or explicitly warn plugin authors that building using sbt 1.2 breaks sbt 1.1 users. /cc @dwijnand

**Comment by xuwei-k** [comment]
https://github.com/lightbend/migration-manager/issues/40 🤔 ?

**Comment by xuwei-k** [comment]
https://github.com/xuwei-k/xsbt/commit/ac318755bba9b73945a26bb38de3afba62de3254 🤔 ?

**Comment by dwijnand** [comment]
Both comments seem plausible. Apologies.

**Comment by eed3si9n** [comment]
ok. Let's discuss what to do next. For sbt 0.13, we did this explicitly when we jumped 0.13.2 -> 0.13.5 to introduce AutoPlugin, but in my opinion inConfig(...) isn't big enough change to break forward compat for everyone.

In the short-term we should back it out, but if you are interested, I am wondering if vararg variety might be introduced back as an implicit extension.

**Comment by dwijnand** [comment]
Ideally it would be possible for the old binary API to exist and link, and the new API to be used for newer stuff. But I didn't know if that can be achieved.

**Comment by eed3si9n** [comment]
I wonder if we can use the evil Sébastien trick of keeping bincompat by hiding it in `private[sbt]`.

**Comment by eed3si9n** [comment]
I tried to make the overloads distinguishable as follows:

```scala
  // This is kept around for binary compatibility.
  private[sbt] def inConfig(conf: Configuration)(ss: Seq[Setting[_]]): Seq[Setting[_]] =
    inScope(ThisScope.copy(config = Select(conf)))((configuration :== conf) +: ss)

  def inConfig(
      conf: Configuration
  )(s0: SettingsDefinition, s1: SettingsDefinition*): Seq[Setting[_]] =
    inScope(ThisScope.copy(config = Select(conf)))(
      (configuration :== conf) +: ((s0 :: s1.toList) flatMap (_.settings))
    )
```

But it seems like Scala compiler gets confused if the first parameter list is ambiguous.

```
[error] /Users/eed3si9n/work/sbt-modules/sbt/main/src/main/scala/sbt/Defaults.scala:1698:42: ambiguous reference to overloaded definition,
[error] both method inConfig in trait ProjectExtra of type (conf: sbt.librarymanagement.Configuration)(s0: sbt.Def.SettingsDefinition, s1: sbt.Def.SettingsDefinition*)Seq[sbt.Def.Setting[_]]
[error] and  method inConfig in trait ProjectExtra of type (conf: sbt.librarymanagement.Configuration)(ss: Seq[sbt.Def.Setting[_]])Seq[sbt.Def.Setting[_]]
[error] match argument types (sbt.librarymanagement.Configuration)
[error]   lazy val itSettings: Seq[Setting[_]] = inConfig(IntegrationTest)(testSettings: SettingsDefinition)
[error]
```

**Comment by eed3si9n** [comment]
Here's a quick PR to revert #4106 - https://github.com/sbt/sbt/pull/4301

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/4301
