### ISSUE TITLE
SBT Version Check

### ISSUE THREAD

**Issue by patriknw** [sbt/sbt#43]
I tried sbt 0.10 and all was fine until I by misstake run sbt 0.7.7 in the same project directory. It asked me to create new project and I quit it with ctrl-c. After that the project was polluted and didn't work with 0.10. It was difficult to understand that the reason was 0.7.7. To save others from this hassle it would be nice with some kind of check for this scenario and a nice error message.

The error I got was that when I had removed my .ivy2 directory it couldn't download sbt. Unresolved dependency:
[warn]  ==== Typesafe Repository: tried
[warn]    http://repo.typesafe.com/typesafe/releases/org.scala-tools.sbt/sbt_2.8.1/[sbtversion]/0.10.0/ivys/sbt_2.8.1-0.10.0.xml
[warn]    -- artifact org.scala-tools.sbt#sbt_2.8.1;0.10.0!sbt_2.8.1.jar:
[warn]    http://repo.typesafe.com/typesafe/releases/org.scala-tools.sbt/sbt_2.8.1/[sbtversion]/0.10.0/jars/sbt_2.8.1-0.10.0.jar

**Comment by harrah** [comment]
I followed your instructions, but I don't see any problems.  In 0.7.7, the prompt for creating a new project happens before anything Ivy-related starts up, so it would be a surprise for something to be corrupted.  From the resolver pattern, it looks like you have sbteclipse installed, but I don't know how that would affect anything.  Please reopen if you have more specific instructions on reproducing.
