### ISSUE TITLE
SBT should ignore empty "project/plugins" directory

### ISSUE THREAD

**Issue by stephenjudkins** [sbt/sbt#431]
Using the "project/plugins" directory is currently deprecated in favor of "project/plugins.sbt". SBT, however, ignores plugins.sbt if the "project/plugins" directory exists, even if it is empty.

Since Git tracks files, not directories, it makes it impossible to remove directories using the "git checkout" command. Any files are removed, but empty directories remain. Thus, the behavior of any code that lives in a Git repository that depends on the presence of empty directories is defined by not only the contents of the commits, _but the order that the commits have been checked out_. Since it's likely that the majority of SBT projects are stored in Git repositories, it makes sense to ignore an empty "project/plugins" directory.

**Comment by harrah** [comment]
see comment on #432
