### ISSUE TITLE
Def.sequential doesn't honour aggregates

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#4315]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps

```scala
val foo = taskKey[Unit]("")
val bar = taskKey[Unit]("")

val root = project in file(".")
aggregateProjects(prj1, prj2)

foo := println("foo root")
bar := Def.sequential(foo).value

val prj1 = project settings (foo := println("foo 1"))
val prj2 = project settings (foo := println("foo 2"))
```

## problem

```scala
> foo
foo root
foo 2
foo 1
[success] Total time: 0 s, completed 09-Aug-2018 14:11:56
> bar
foo root
[success] Total time: 0 s, completed 09-Aug-2018 14:11:57
```

## expectation

I expect `Def.sequential` to execute the given task with the same semantics as executing it in the shell.

## notes

sbt version: 1.2.1, also *0.13.17.

Here are two workarounds:

```scala
bar := Def.sequential(foo all aggregatesFilter).value
val aggregatesFilter = ScopeFilter(inAggregates(ThisProject))
```

```scala
val aggregatesFilter = ScopeFilter(inAggregates(ThisProject, includeRoot = false))
foo := {
  foo.all(aggregatesFilter).value
  foo.value
}
```

**Comment by eed3si9n** [comment]
I disagree on the expectation here.

Aggregation is a command broadcasting tool, which is equivalent of saying `all root/bar prj1/bar prj2/bar`.

Calling `compile.value` has never been aware of the `project.aggregate(...)`, and thus the same applies to sequential tasks. If you want the same thing as typing things into the shell, you should define a command alias instead. A close emulation would be defining a AutoPlugin that defines the sequential task in all subprojects. (Sort of related to recent Q&A I did  https://stackoverflow.com/a/51688744/3827)

**Comment by dwijnand** [comment]
I see what you mean, but I think it's too subtle. If you define a top-level `doCI := Def.sequential(compile.value, doc.value)` you want the `compile` to aggregate, just like `compile` aggregates in the shell. Shouldn't need to give up on the task abstraction and using static strings like `";testNoFail;testQuick"`.

**Comment by eed3si9n** [comment]
Then you need an automatic scope filtering + sequential task.

**Comment by jvican** [comment]
What about introducing a new `Def.sequentialWithAggregates` that would do the default behaviour that Dale wants? There's not much we can do, changing the semantics of this in sbt 1.x is a breaking change and people may end up over-testing or over-running tasks in their CI.

**Comment by dwijnand** [comment]
Sometimes we change semantics and call it a bug fix 🙂

I think most aggregating projects are empty projects, and so any invocation of their tasks with `.value` are currently nooping (bug) instead of aggregating.

I'm happy to go the sbt-doge route on this: iterate in a plugin, and fold it in for the next major version.
