### ISSUE TITLE
runMain causes jar packaging on 1.2

### ISSUE THREAD

**Issue by shasts** [sbt/sbt#4319]
- [ x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps
Attached two zip files,  one with SBT 0.13.17 and other with 1.2.1. Running  `sbt clean test it:test` causes 1.2.1 to package jars including that of dependencies while 0.13.17 doesn't.

I think I'm dealing with two issues here. 
1. Of course change in behavior of SBT in 1.2.1 to package jars when `runMain`.

2. Came across 1,  while debugging a bigger/deeper issue wherein I suspect that this causes classpath issues, though I have not been able to reproduce that on a small project. The classpath issue doesn't happen when run with sequential execution of tasks.

```
Global / concurrentRestrictions := {  
  Tags.limitAll(1) :: Nil
}
```

Could be related to https://github.com/sbt/sbt/issues/3935

## problem
1. `(runMain in Compile).toTask` or `it:runMain X` causes the project and dependencies to be packaged.
2. While the above packaging is happening, if another subproject `compile`ing, classpaths seems to be messed up leading to the error below. How these two are related is not discovered yet. Though the issue doesn't happen if I do one of below.
a) disable the task which causes the jar packaging
b) let the tasks execute serially(using `Global / concurrentRestrictions`) so that jar packaging happens after compilation of another subproject.

```
Symbol 'type Y' is missing from the classpath.
This symbol is required by 'method X'.
Make sure that type Y is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
```

## expectation
Same behavior as 0.13 wherein no package task is run.

## notes

sbt version: *1.2.1*

[Sample project with SBT 1.2.1](https://github.com/sbt/sbt/files/2284158/example_1_2_1.zip)
[Same project with SBT 0.13.17](https://github.com/sbt/sbt/files/2284181/example_0_13_17.zip)

**Comment by eed3si9n** [comment]
In current sbt 1 runMain delegates to bgRunMain, so that's pretty much by design.
If you want the old behavior please try fgRunMain.
