### ISSUE TITLE
Publish should not publish javadocs if compilation fails

### ISSUE THREAD

**Issue by dragos** [sbt/sbt#4326]
- [ ] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps

- type publish in a project with a compilation error
- docs succeed, compilation fails

## problem

- docs are published
- I can't fix the problem and run `publish` again, instead I have to delete the published version 

## expectation

- publish should be atomic, and docs shouldn't be published if the main artifact failed

## notes

sbt version: 0.13.16

**Comment by dragos** [comment]
At closer inspection it looks like it was the docs for a different project than the one with the error, though the question remains whether aggregates should publish partial results.

**Comment by eed3si9n** [comment]
`publish` is a task scoped to a subproject. If you want a build-wide step 1 do this, and then do step 2, then we are now talking about commands. How about something like this?

```scala
addCommandAlias("release", ";clean;publishConfiguration;publishSigned")
```

**Comment by dragos** [comment]
That's a good suggestion. I was publishing the scala build, actually, so I didn't want to modify the build script too heavily (it's all part of an automation pipeline)

**Comment by eed3si9n** [comment]
Maybe this is another benefit to using the style of publishing that first stages to some place, like Sonatype OSS or Bintray.

I'm closing this for now.
