### ISSUE TITLE
Triggered execution not triggering when files change on Arch Linux

### ISSUE THREAD

**Issue by RatanRSur** [sbt/sbt#4327]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps
Write to source file while ~test is running in sbt

## problem
Does not recompile/test project

sbt version: 1.1.5

**Comment by eatkins** [comment]
Duplicate of https://github.com/sbt/sbt/issues/4167. You need to upgrade to 1.1.6 or higher.
