### ISSUE TITLE
Path to `CONTRIBUTING` link is broken

### ISSUE THREAD

**Issue by joshlemer** [sbt/sbt#4338]
- [] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps

create a new issue in github.com/sbt/sbt

## problem

text is auto-filled asking you to read a CONTRIBUTING guideline at `- [] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines`

This link is dead

## expectation

The link is not dead

**Comment by eed3si9n** [comment]
Thanks for the report!
