### ISSUE TITLE
`sbt new` should not create a target directory in the working directory

### ISSUE THREAD

**Issue by joshlemer** [sbt/sbt#4339]
## steps

run `sbt new scala/hello-world.g8`

## problem

this creates `./target/...` directories

## expectation

no garbage target directory is created

**Comment by eed3si9n** [comment]
This is a duplicate of https://github.com/sbt/sbt/issues/2835 that was fixed in https://github.com/sbt/sbt/pull/4033. Do you have the latest version of sbt installed?

**Comment by joshlemer** [comment]
Whoops!

**Comment by joshlemer** [comment]
To be clear, yes the problem is solved in 1.2.1

**Comment by ghost** [comment]
Is this fix ported to 1.3.2? Downgrading to 1.2.1, fixes the issue but the issue recurs in version 1.3.2.

**Comment by drewboardman** [comment]
This happens in 1.4.4
