### ISSUE TITLE
Wiki page should mention the "doc" task

### ISSUE THREAD

**Issue by x3ro** [sbt/sbt#434]
I think that the `doc` task should be mentioned in the Wiki because I think that it is not really obvious that documentation is generated in `target/<scala version>/api`.

**Comment by harrah** [comment]
It it mentioned on https://github.com/harrah/xsbt/wiki/Command-Line-Reference.  It is not usually run directly, but is instead is the input to a task like `package-doc`.  Note that you can do `show doc` to see where documentation is generated (or run find in the `target` directory).  Also, the wiki is user-editable.
