### ISSUE TITLE
Link to CONTRIBUTING is broken

### ISSUE THREAD

**Issue by ignasi35** [sbt/sbt#4344]
(this is a meta-issue)

- [ ] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

^^^ the link above to `CONTRIBUTING` is broken for both the issue and the PR templates.

**Comment by eed3si9n** [comment]
Duplicate of https://github.com/sbt/sbt/issues/4338
