### ISSUE TITLE
Compilation error when marking doobie as "provided"

### ISSUE THREAD

**Issue by prestonph** [sbt/sbt#4348]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps
Have a project, **database**, uses library [tpolecat/doobie](https://github.com/tpolecat/doobie). Mark it as "provided".
Have another project, **server**, depends on `database`.
Compiling **server** with `sbt server/compile` gives an error.

Full build file and sample code is here: https://github.com/mt40/sbt_doobie

## problem
Sbt produces this error:
```
[error] C:\Users\(...)\server\src\main\scala\main.scala:1:17: Symbol 'term <root>.doobie' is missing from the classpath.
[error] This symbol is required by 'method Repo.test'.
[error] Make sure that term doobie is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'Repo.class' was compiled against an incompatible version of <root>.
[error] trait A extends Repo
[error]                 ^
[error] one error found
[error] (server / Compile / compileIncremental) Compilation failed
```

## expectation
Compile successfully

## notes

Scala version: 2.11.12
Sbt version: 1.1.6

**Comment by eed3si9n** [comment]
I think this is by design. In other words, I disagree with your expectation.
provided means that it can be using during compile time (of `database` subproject), but will not be part of the runtime or part of the transitive dependency.

**Comment by prestonph** [comment]
This is actually a wrong usage. I just need to add that dependency to `server` to compile successfully.

**Comment by ritschwumm** [comment]
it's weird- but see https://issues.apache.org/jira/browse/MNG-2205

**Comment by prestonph** [comment]
@ritschwumm interesting, didn't know that many people run into the same situation
