### ISSUE TITLE
Javadoc generation fails on JDK10 with "error - invalid flag: -d"

### ISSUE THREAD

**Issue by stevedlawrence** [sbt/sbt#4350]
- [X] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps

1. Ensure java/javac version is JDK10
1. Create a directory with a single .java file and no .scala files, e.g.
    ```
    $ mkdir test
    $ cd test
    $ echo "public class Test {}" > Test.java
    ```
   Note that this mimics what happens when the sbt genjavadoc plugin is used and the only sources are .java files.
1. Run ``sbt doc`` to generate javadoc for the single java file.
## problem

The following error results:
```
[warn] Unexpected javac output: javadoc: error - invalid flag: -d.
[info] Usage: javadoc [options] [packagenames] [sourcefiles] [@files]
...
[info] 1 error
[warn] javadoc exited with exit code 1
[info] Main Java API documentation successful.
[success] Total time: 0 s, completed Sep 12, 2018, 8:02:56 AM
```

## expectation
No error should result from javadoc, and instead should generate documentation for the java file.

## notes

The error implies that javadoc does not like the -d option which specifies the output directory. However, running ``javadoc -d outdir Test.java`` with JDK 10 does generate the correct javadoc.

Note also that that javadoc exits with a non-zero exit code, but sbt still thinks it was successful. Potentially a separate issue?

sbt version: 1.2.1
java versoin: JDK10

**Comment by stevedlawrence** [comment]
I discovered that setting the ``javaHome`` key causes sbt to fork javadoc rather than instantiating javadoc via the class loader. This results in the correct generation of javadocs. So the issue appears to be related to javadoc being executed reflectively.

**Comment by xuwei-k** [comment]
> Note also that that javadoc exits with a non-zero exit code, but sbt still thinks it was successful. Potentially a separate issue?

https://github.com/sbt/zinc/issues/414

**Comment by xuwei-k** [comment]
- https://github.com/sbt/zinc/blob/v1.2.2/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/javac/LocalJava.scala#L42-L77
- https://github.com/xuwei-k/sbt-java10-javadoc

**Comment by xuwei-k** [comment]
workaround: set the `javaHome` key explicitly (e.g. ↓)

```
set javaHome := Some(file("/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home"))
```

**Comment by xuwei-k** [comment]
use `javax.tools.ToolProvider.getSystemDocumentationTool` ? 🤔 

- https://github.com/xuwei-k/sbt-java10-javadoc/commit/5b31c23eb26feb3742e9c33cd3d656e481146e50
- https://github.com/sbt/zinc/blob/932472b05ba294e4627ac3d3eb60194eae1df80f/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/javac/JavaCompiler.scala#L117-L118
- https://github.com/xuwei-k/zinc/commit/89ac9ee2e8a3a117454990c3f141a63dcbc1746b

**Comment by eed3si9n** [comment]
@xuwei-k Yes. That looks vaguely familiar to me.

**Comment by xuwei-k** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk10-integrate-community-build/268/

```
[twitter-util] [error] javadoc: error - invalid flag: -d
[akka-stream] [warn] Unexpected javac output: javadoc: error - invalid flag: -Xdoclint:none.
[sbt-util] [warn] Unexpected javac output: javadoc: error - invalid flag: -d.
[zinc] [warn] Unexpected javac output: javadoc: error - invalid flag: -d.
```

**Comment by SethTisue** [comment]
@eed3si9n (I can't judge importance versus other tasks on your plate, but it would be nice to have a fix for this for the Scala community build)

**Comment by eed3si9n** [comment]
## red

Here's a quick way to get a unit test to fail on Zinc.

```diff
--- a/build.sbt
+++ b/build.sbt
@@ -191,6 +191,7 @@ lazy val zincCompile = (project in file("zinc-compile"))
   .settings(
     name := "zinc Compile",
     mimaSettings,
+    Test / fork := true,
   )
```

Then from sbt shell:

```
java++ 11!
zincCompile/testOnly sbt.inc.DocSpec
```

This yields

```
[info] DocSpec:
[info] Doc.cachedJavadoc
[warn] Unexpected javac output: javadoc: error - invalid flag: -d.
[warn] javadoc exited with exit code 1
[info] - should generate Java Doc *** FAILED ***
[info]   new java.io.File(out, "index.html").exists() was false (DocSpec.scala:25)
[warn] Unexpected javac output: javadoc: error - invalid flag: -d.
[warn] javadoc exited with exit code 1
[info] - should generate cache input
[info] ScalaTest
[info] Run completed in 3 seconds, 312 milliseconds.
[info] Total number of tests run: 2
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
```

## green

Next, take Yoshida-san's https://github.com/xuwei-k/zinc/tree/issue-4350 branch, rebase to `develop`, and run the same test:

```
[info] All tests passed.
[info] Passed: Total 2, Failed 0, Errors 0, Passed 2
```

Here's the PR - https://github.com/sbt/zinc/pull/610
