### ISSUE TITLE
exclude dependency does not work with bundles

### ISSUE THREAD

**Issue by cpoile** [sbt/sbt#436]
As per the discussion on [sbt list](https://groups.google.com/d/topic/simple-build-tool/fq7bJnOd9SM/discussion) we found that sbt exclude is the equivalent of Ivy's `<exclude org="org.atmosphere" module="atmosphere-compat-jetty" type="jar"/>`. Unfortunately this means that when we try to exclude a transient dependency which is a bundle:

`"org.vaadin" % "dontpush-addon-ozonelayer" % "0.4.6" exclude("org.atmosphere", "atmosphere-compat-jetty")`

atomsphere-compat-jetty it is not excluded. The workaround is to use Ivy directly:

```
ivyXML :=
  <dependency org="org.vaadin" name="dontpush-addon-ozonelayer" rev="0.4.6">
      <exclude org="org.atmosphere" module="atmosphere-compat-jetty"/>
  </dependency>
```

Mark noted in the thread I linked to above that this is a bug and could be fixed for 0.12.  Hopefully that can be done.

Thanks!
Chris.

**Comment by kul** [comment]
haha :+1:  for the workaround...wouldnt have thought of that
