### ISSUE TITLE
Log is either too noisy or unhelpful

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4362]
## steps

1. compile a large build with plugins, macros, code generation, library dependencies etc.

## problem

The problem is that the log gets really noisy

```
[info] Updating {file:/…/scalajs-react/}root...
[info] Updating {file:/…/scalajs-react/}core...
[info] Updating {file:/…/scalajs-react/}gh-pages-macros...
[info] Done updating.
[info] Compiling 2 Scala sources to /…/scalajs-react/gh-pages-macros/…
[info] Done updating.
[info] Updating {file:/…/scalajs-react/}extra...
```

but when something is taking a long time it's hard to tell what's going on.

## expectation

Remove the "Updating..." .. "Done" with currently executing tasks with count up clock?

**Comment by SethTisue** [comment]
is there some other tool, not necessarily a Scala or JVM tool even but just anything, that does a good job with this, and we could copy their design?

**Comment by eatkins** [comment]
One thing that I think is nice in [mill](https://github.com/lihaoyi/mill) is that by default it generates performance reports for each task. I think it would be great if sbt could do something similar. The implementation in mill is here: [Evaluator](https://github.com/lihaoyi/mill/blob/master/main/core/src/mill/eval/Evaluator.scala)

**Comment by eed3si9n** [comment]
@SethTisue Gradle.

I wrote http://eed3si9n.com/console-games-in-scala as a preliminary research for implementing Gradle's progress bar. It takes over bottom _n_ rows of your terminal where _n_ is the number of concurrent tasks, and shows you what the overall command you're executing on:

![gradle-progress](https://user-images.githubusercontent.com/184683/45581987-143d1800-b876-11e8-8368-40f25be64e26.gif)
