### ISSUE TITLE
sbt logger does super weird stuff with string context without interpolation

### ISSUE THREAD

**Issue by mriehl** [sbt/sbt#4371]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps
```scala
scala> sbt.internal.util.ConsoleLogger().info(s"\t")
[info] \t

scala> sbt.internal.util.ConsoleLogger().info(s"\t${"wtf"}")
[info]  wtf

scala> sbt.internal.util.ConsoleLogger().info("\tfoo")
[info]  foo
```

## problem
`s""` should be simplified to `""` at runtime, but the sbt logger somehow escapes the contents additionally.

## expectation
`s""` should behave like a regular string w.r.t. escaping.
See
```scala
scala> s"\t"
res8: String = "        "
```

## notes

sbt version: 
1.0 works fine
1.2.1 has this issue
1.2.3 has this issue

**Comment by eed3si9n** [comment]
Thanks for the report.

**Comment by mrveera** [comment]
I am thinking of adding process/treat escapes before appending to log, @eed3si9n  does that make sense?

**Comment by eed3si9n** [comment]
@veera83372 See https://github.com/sbt/util/blob/develop/internal/util-logging/src/main/scala/sbt/internal/util/ConsoleAppender.scala. I think it's doing some of processing in there. Check it out and see if you can reproduce it or fix it.

**Comment by mrveera** [comment]
I don't know any processing happens there but I can fix it by calling processingEscapes from StringContext before logging

**Comment by eed3si9n** [comment]
I can reproduce this without sbt - scala/bug#11196

**Comment by eed3si9n** [comment]
Hopefully fixed by https://github.com/scala/scala/pull/7334.
