### ISSUE TITLE
[sbt-server] helper for completions

### ISSUE THREAD

**Issue by andreaTP** [sbt/sbt#4374]
Started building a thin client for Sbt (https://gitlab.com/andreaTP/sbtcli) and I wanted to implement some kind of completion for the interactive shell.

LSP define completion requests: https://microsoft.github.io/language-server-protocol/specification#textDocument_completion

it should be supported by the sbt-server to enable more user-friendly CLIs.

**Comment by eed3si9n** [comment]
`TextDocumentPositionParams` takes `TextDocumentIdentifier`, which contains an URI.
We can make an URI convention for the shell. We can make up a URI convention for our use.
For example we can say `"sbt://shell"` means sbt shell like `chrome://about/`.

The context could be:

```json
{
  "triggerKind": 1,
  "triggerCharacter": "comp"
}
```

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/4397
