### ISSUE TITLE
Send custom HTTP headers when publishing

### ISSUE THREAD

**Issue by mvdstam** [sbt/sbt#4382]
Hello,

When publishing to a private repository, it's necessary for us to send custom HTTP headers when doing this. These headers contain, for example, authentication tokens.

I know that Maven uses a `~/.m2/settings.xml` file for this where custom httpHeaders can be configured per server/repository. I haven't found an analogous functionality in SBT to do this aside from basic authentication.

Is it possible to do this at the moment with SBT? If not, please consider this a feature request. :+1:

**Comment by eed3si9n** [comment]
I don't think it's possible currently.

For potential contributors, see code that was changed in https://github.com/sbt/librarymanagement/pull/246 for the relevant code.

**Comment by mvdstam** [comment]
Hey @eed3si9n, thanks for your reply. :+1:

**Comment by gael-ft** [comment]
@mvdstam Did you find a workaround for this ?

SBT developers, please consider this feature 😃

**Comment by mvdstam** [comment]
@gael-ft No, unfortunately I did not find a workaround for this particular issue. 😞

I haven’t found the time either to dive into this myself, so putting this on the agenda for the SBT team would be great.

**Comment by gael-ft** [comment]
Ok thank you for your answer @mvdstam, I'll have to go through mvn deploy:deploy-file... 😢

**Comment by cemelo** [comment]
Workaround for this:

If you set up a custom `URLHandlerDispatcher`, sbt will respect that starting with 1.0.4 ([sbt/librarymanagement#183](https://github.com/sbt/librarymanagement/pull/183)), unless you're trying to use HTTP or HTTPS. To force these two protocols to go over a custom URLHandler, you'd need an instance whose `setDownloader` methods don't do anything, and set up your custom URLHandler on instantiation:

    onLoad in Global := (onLoad in Global).value andThen { state =>
      import org.apache.ivy.util.url._
    
      val urlHandlerDispatcher = new URLHandlerDispatcher {
        super.setDownloader("http", CustomURLHandler)
        super.setDownloader("https", CustomURLHandler)
    
        override def setDownloader(protocol: String, downloader: URLHandler): Unit = {}
      }
    
      URLHandlerRegistry.setDefault(urlHandlerDispatcher)
    
      state
    }

Then, you just implement a `CustomURLHandler` that extends `GigahorseUrlHandler` and overrides `upload`:

```scala
object CustomURLHandler extends GigahorseUrlHandler {

  private lazy val okHttpClient: OkHttpClient = {
    GigahorseUrlHandler.http
      .underlying[OkHttpClient]
      .newBuilder()
      .authenticator(new sbt.internal.librarymanagement.JavaNetAuthenticator)
      .followRedirects(true)
      .followSslRedirects(true)
      .build
  }

  private val EmptyBuffer: Array[Byte] = new Array[Byte](0)

  override def upload(source: File, dest0: URL, l: CopyProgressListener): Unit = {
    
    if (("http" != dest0.getProtocol) && ("https" != dest0.getProtocol)) {
      throw new UnsupportedOperationException("URL repository only support HTTP PUT at the moment")
    }

    IvyAuthenticator.install()
    ErrorMessageAuthenticator.install()

    val dest = normalizeToURL(dest0)

    val body = RequestBody.create(MediaType.parse("application/octet-stream"), source)

    val request = new Request.Builder()
          .url(dest)
          .addHeader("Custom-Header", "custom-header-value")
          .put(body)
          .build()

    if (l != null) {
      l.start(new CopyProgressEvent())
    }
    val response = okHttpClient.newCall(request).execute()
    try {
      if (l != null) {
        l.end(new CopyProgressEvent(EmptyBuffer, source.length()))
      }
      validatePutStatusCode(dest, response.code(), response.message())
    } finally {
      response.close()
    }
  }
}
```

**Comment by mvdstam** [comment]
@cemelo Thanks so much, your code works like a charm! :+1:

**Comment by eed3si9n** [comment]
I'm going to close this if https://github.com/sbt/sbt/issues/4382#issuecomment-469734888 works.

**Comment by ghost** [comment]
Hi @mvdstam and @cemelo , could you briefly comment where / how you add the CustomURLHandler exactly, I have the same issue and would like to get it to work, yet my sbt skills are novice. Thank you!

**Comment by alterationx10** [comment]
@christianri if it helps, here is what I threw together https://gitlab.com/SLUDG/gitlab-sbt

I've never written an SBT plugin before, so I'm sure it's far from perfect, but I got it to work!

Edit: I've moved the repo over to https://github.com/k8ty-app/sbt-publish

**Comment by mjuanes** [comment]
@alterationx10 @cemelo I'm using this same approach to add headers to the download request of artifacts. I'm overriding GigahorseUrlHandler's download but is not working, any idea?

**Comment by kevmo314** [comment]
@alterationx10 Can you publish your plugin on Maven Central? Publishing it locally to use is a bit cumbersome on CI/CD. :)

**Comment by alterationx10** [comment]
@kevmo314 I could try and get something set up in the next few days, if it'd be helpful! Ironically, I haven't published it's artifact to it's own GitLab repo 🤣

**Comment by kevmo314** [comment]
@alterationx10 Yeah that would be helpful, thanks!

**Comment by alterationx10** [comment]
@kevmo314 Better late than never? In the process of getting my account set up to publish to Maven Central. In the meantime, I've got it published to GitLab: https://gitlab.com/k8ty/gitlab-sbt/-/packages/294966 

Please note the group change + some name refactoring (and therefore some command changes). Not wanting to use this thread as a news letter 🤣 so I'll make a note there in the projects README once it's published with the MC info

**Comment by kevmo314** [comment]
Awesome! Definitely better late than never, this is an easy switch flip for us and saves us one step in the manual process :)

**Comment by ramabu** [comment]
@alterationx10 Your first plugin rocks!

I am new to gitlab; and want to offer some changes.
Not sure how to branch and/or MergeRequest.

Anyway we can discuss the changes I needed?

[slugd_patch.txt](https://github.com/sbt/sbt/files/4944047/slugd_patch.txt)

**Comment by alterationx10** [comment]
@ramabu Sure! It looks like you just want to add in some general options to pass in header - seems sensible to add in! I notice you did add it to the old repository that I hadn't cleaned up much - but there weren't a lot of changes, so should be easy to add in.

I seem to get a lot more interaction of GitHub, so I've moved the repository over here. Feel free to make a PR or an issue there if you're more comfortable with GitHub:  https://github.com/k8ty-app/sbt-publish

**Comment by ramabu** [comment]
Thanks @alterationx10!
One other thing I noticed is - Your plugin allows csrf-token-based upload.
What about "GET", used to resolve dependencies? This too may not succeed without a token

**Comment by gilandose** [comment]
also late to this but for dependency resolution as well as publish  this should be resolved for sbt v1.3.10 using @alterationx10 plugin + this below that got added to sbt-coursier which is the default for dependency resolution since v1.3
https://github.com/coursier/sbt-coursier/pull/220
```
resolvers +=
  "gitlab" at "https://gitlab.com/api/v4/projects/1234567/packages/maven"

csrConfiguration ~=
(_.withAuthenticationByRepositoryId(Vector(("gitlab",Authentication("","",false,None,Some(Seq(("Private-Token","xxxx"))))))))
updateClassifiers / csrConfiguration ~= (_.withAuthenticationByRepositoryId(Vector(("gitlab",Authentication("","",false,None,Some(Seq(("Private-Token","xxxx"))))))))
```
If you are on an older version and need both publishing and dependency resolution:
https://github.com/gilcloud/sbt-gitlab just add following to project/plugins.sbt
```
resolvers += Resolver.bintrayIvyRepo("gilcloud", "sbt-plugins")
addSbtPlugin("com.gilcloud" % "sbt-gitlab" % "0.0.3")
```

**Comment by ramabu** [comment]
Hi Richard

No older version.
So - let me see if I understood you correctly.

*For Token-based auth for resolve/download*
- *no need for a plugin*. It is built into coursier, which is the default
download for sbt1.3+ (we are with 1.3.13)

*For Token-based auth for publish/upload*:

   - @Alterationx10's plugin does it.
   - It, or a modified version of it, will probably be built into future sbt
   - Till then - we ca use our modified version in a private repo

So far so good?

If so - then we need the following changes in the upload plugin (see the previously
attached patch):

   - Instead of [env-var+special publish verb] per token-type (Job,Private)
      - use a couple of env vars - token-type + token value
   - Use a keys argument for gitlab host (as well as project id)
   - (The request/response printlns can be ignored, though were quite
   useful debugging this)

I'll recreate the patch for the newer
https://github.com/k8ty-app/sbt-publish
How soon do you think we can find these in master of
https://github.com/k8ty-app/sbt-publish?

Thanks,
rama

**Comment by gilandose** [comment]
@ramabu have a try with this version published last night, currently pending addition to sbt pluglin community releases so needs extra resolver, I've added a couple of things for your use case a new setting `gitlabDomain` which defaults to `gitlab.com`, but can be overridden to what ever suits for private.

it supports credentials file for local dev, and will now auto build credentials in ci pipeline, with publishTo also optionaly being auto generated from the $gitlabProjectId and gitlabDomain pull request above open if you want to review to check it meet self hosted requirements  
```scala
addSbtPlugin("com.gilcloud" % "sbt-gitlab" % "0.0.4")

```
if you have an sbt version > 1.3.10 then you can ignore this bit and use coursier for dependency resolution with the instructions above and this plugin will still work for publishing
you'll also need to set `ThisBuild / useCoursier := false`

**Comment by ramabu** [comment]
I didn't use coursier (yet)

Other than that - 

- Added the plugin in the correct version (project/plugin.sbt)
- Enabled the plugin (build.sbt)
- defined the plugin's settings:

```scala
GitlabPlugin.autoImport.gitlabProjectId :=  Option(1234)
GitlabPlugin.autoImport.gitlabDomain :=  "my.gitlab.net"
GitlabPlugin.autoImport.gitlabCredentials := Option(GitlabCredentials(s"$glTokenType", s"$glTokenValue"))

```

Worked like charm!

**Comment by gilandose** [comment]
Excellent glad to hear. 
FYI on credentials front it should support adding your credentials like this for local development:
~/.sbt/.credentials using the standard mechanisms
```
realm=gitlab
host=""
user=Private-Token
password=<api-token>
```
and in pipeline it will auto build credentials from the pipeline environment, so you can keep api keys well away from source control.

**Comment by ramabu** [comment]
Hi @gilandose 

Thank you so much for all the explanations.
To sum this up:

**To upload an artifact -** 

```scala
addSbtPlugin("com.gilcloud" % "sbt-gitlab" % "0.0.4")  // Add plugin; note version (project/plugin.sbt)
enablePlugin(GitlabPlugin)   // Enable the plugin (build.sbt)

// Define the plugin's settings(build.sbt):
GitlabPlugin.autoImport.gitlabProjectId :=  Option(1234)
GitlabPlugin.autoImport.gitlabDomain :=  "my.gitlab.net"
GitlabPlugin.autoImport.gitlabCredentials := Option(GitlabCredentials("Deploy-Token", "some-value"))
```

**To download an artifact (dependency)**

```scala
// in build.sbt
val glHost      = "my.gitlab.net"
val glGroup     = 4321
val glGrpRegistry=s"https://$glHost/api/v4/groups/$glGroup/-/packages/maven"

resolvers += s"gitlab at $glGrpRegistry"

val auth:Authentication = Authentication(Seq(("Private-Token","some-value")))
csrConfiguration ~= (_.addRepositoryAuthentication("gitlab",auth))
updateClassifiers / csrConfiguration ~= (_.addRepositoryAuthentication("gitlab",auth))

```

**Comment by robkler** [comment]
I just receive the error was refused by the server, the url is corret, I'm using my private token. what can be wrong?

**Comment by ramabu** [comment]
@robkler 
First check sbt version >= 1.3.10
Next, verify the groupid 
Also, on the same client machine I'd try to curl get from the repo, to shorten the cycle making sure I have the correct token, group etc.

**Comment by hamnis** [comment]
I have added custom header support to sbt-aether-deploy now, so that can also be used with this.

```scala
aether.AetherKeys.aetherCustomHttpHeaders := {
  if (sys.env.contains("CI")) {
    Map("Job-Token" -> sys.env("CI_JOB_TOKEN"))
  } else {
    sys.env.get("GITLAB_PRIVATE_TOKEN").map("Private-Token" -> _).toMap
  }
}
publishTo := Some("gitlab-deploy" at "https://gitlab.com/api/v4/projects<project-id>/packages/maven")
```

**Comment by robkler** [comment]
I plublished, but most often fails and return the error: was refused by the server. One time I try to publish 2 times and got the error

**Comment by listba** [comment]
@gilandose It appears that your plugin is currently failing if multiple sbt commands are chaitn together.

ie: 
`sbt clean test publish` -> Results in an Authorization Error
while
`sbt clean publish` -> Works as expected

I haven't had time to dive into your code to try and debug it. Also it appears as though your master branch is not current with what is deployed (master is still at `0.1.0`)

**Comment by eatkins** [comment]
I’m glad that @gilandose’s plugin is working for people. Nevertheless, I ask that all discussion of the plugin move to https://github.com/gilcloud/sbt-gitlab. Any issues with the plugin should be reported there so they can be tracked and fixed.

**Comment by ramabu** [comment]
Hi @gilandose

Regarding coursier fetch of dependencies - The authentication settings as they are don't apply to sub-projects.
The error distinctly indicates dependencies-resolve issue in the subproject. The root project depends on the same library, same version, and gets it.

[error] (subP / ssExtractDependencies) sbt.librarymanagement.ResolveException: Error downloading com.mine:common-deps:0.0.12-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /Users/ramabu/.ivy2/local/com.mine/common-deps/0.0.12-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/mine/common-deps/0.0.12-SNAPSHOT/common-deps-0.0.12-SNAPSHOT.pom
[error]   not found: https://my.gitlab.net/api/v4/groups/4321/-/packages/maven/com/mine/common-deps/0.0.12-SNAPSHOT/common-0deps.0.12-SNAPSHOT.pom

I tried putting in "in ThisBuild", no luck
I also tried modify the csrConfiguration of the subproject - no luck either
I am probably doing something wrong

```scala
resolvers in ThisBuild += s"gitlab at $glGrpRegistry" // 'in ThisBuild' mandatory

val auth:Authentication = Authentication(Seq(("Private-Token","some-value")))
csrConfiguration  ~= (_.addRepositoryAuthentication("gitlab",auth)) // 'in ThisBuild' makes no difference 
updateClassifiers / csrConfiguration ~= (_.addRepositoryAuthentication("gitlab",auth))
subP / csrConfiguration ~= (_.addRepositoryAuthentication("gitlab",auth)) // makes no difference either
```

**Comment by gilandose** [comment]
open an issue here, https://github.com/coursier/sbt-coursier as this is the lib that is used for that

**Comment by ramabu** [comment]
I don't see an option to create an Issue, nor to request access.
But - Is this supposed to work? Was this tested?

**Comment by neboduus** [comment]
> @robkler
> First check sbt version >= 1.3.10
> Next, verify the groupid
> Also, on the same client machine I'd try to curl get from the repo, to shorten the cycle making sure I have the correct token, group etc.

Sorry @ramabu, but I noticed that Groups are only available for Gilab Premium versio. What if I do not want to specify it? Does the plugin still work. For now I have the same error as @robkler:

> I just receive the error was refused by the server, the url is corret, 

But Im using a Deploy-Token instead, because I need to access an organization Package Repository. Do you have any suggestion about why I get REFUSED by the server? Thanks

**Comment by joschua-fink** [comment]
@neboduus Late to the party, but I think the problem lies with GitLab and not sbt in your case: https://gitlab.com/gitlab-org/gitlab/-/issues/273178 My current workaround is having a separate user account with access only to the project in question and using a Private-Token.

**Comment by pitchblack408** [comment]
How was this resolved?  I see that someone wrote a plugin, but seems that this should be a feature.  What company allows a personal user/password to authenticate over tokens anymore?

**Comment by todor-kolev** [comment]
@ramabu how did you get the `glGroup` id?

**Comment by ramabu** [comment]
That's just the groupid of the project i am publishing to.
