### ISSUE TITLE
IO.classLocationFile(cl: Class[_]): File does not work on JDK 11

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4386]
This was originally reported by @xuwei-k as https://github.com/sbt/io/issues/85 that on Travis CI `IO.classLocationFile` test fails.

```
[info] ! IO.IO.classLocationFile able to determine containing directories: Falsified after 1 passed tests.
```

I am opening this here since `IO.classLocationFile` is used in a few places, and it might require some creative solutions.

### Notes provided by Yoshida-san

`IO.classLocationFile(cl: Class[_]): File` does not work with Java 9.

https://github.com/sbt/io/blob/b5a4b6f56e95945274d4d67680a73f1ffcb28a07/io/src/main/scala/sbt/io/IO.scala#L66-L74

Java 8

```
Welcome to Scala 2.12.4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_151).
Type in expressions for evaluation. Or try :help.

scala> ClassLoader.getSystemClassLoader.getResource("java/lang/Integer.class")
res0: java.net.URL = jar:file:/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/lib/rt.jar!/java/lang/Integer.class
```

Java 9

```
Welcome to Scala 2.12.4 (Java HotSpot(TM) 64-Bit Server VM, Java 9.0.1).
Type in expressions for evaluation. Or try :help.

scala> ClassLoader.getSystemClassLoader.getResource("java/lang/Integer.class")
res0: java.net.URL = jrt:/java.base/java/lang/Integer.class

scala> java.nio.file.FileSystems.getFileSystem(java.net.URI.create("jrt:/"))
res1: java.nio.file.FileSystem = jrt:/

scala> res1.getPath("java.base", "java", "lang", "Integer.class")
res2: java.nio.file.Path = java.base/java/lang/Integer.class

scala> res2.toFile
java.lang.UnsupportedOperationException
  at java.base/jdk.internal.jrtfs.JrtPath.toFile(JrtPath.java:571)
  ... 28 elided
```

- http://openjdk.java.net/jeps/220
- https://github.com/scala/scala/commit/159480f2504cc08f9cc35660cc33090a49e0228e

Can't return `java.io.File` in Java 9 🤔 ?

**Comment by eed3si9n** [comment]
### sbt/main-actions/src/main/scala/sbt/ForkTests.scala

```
128:          IO.classLocationFile[ForkMain],
129:          IO.classLocationFile[Framework]
```

### sbt/run/src/test/scala/sbt/ForkTest.scala
```
34:    IO.classLocationFile[scala.Option[_]] ::
35:      IO.classLocationFile[sbt.exit.type] ::
```

### sbt/testing/src/main/scala/sbt/TestFramework.scala

```
253:    val interfaceJar = IO.classLocationFile(classOf[testing.Framework])
```

### sbt/main-actions/src/main/scala/sbt/compiler/Eval.scala

```
72:    this(Nil, IO.classLocationFile[Product] :: Nil, mkReporter, backing)
```

### sbt/main/src/main/scala/sbt/internal/parser/SbtParser.scala

```
45:    sbt.io.Path.makeString(sbt.io.IO.classLocationFile[Product] :: Nil)
```

### zinc/internal/zinc-classpath/src/main/scala/sbt/internal/inc/classpath/ClasspathUtilities.scala

```
100:    println(c.getName + " loader=" + c.getClassLoader + " location=" + IO.classLocationFile(c))
```

### io/io/src/test/scala/sbt/io/IOSpecification.scala

```
7:  property("IO.classLocationFile able to determine containing directories") = forAll(classes) {
9:      Try(IO.classLocationFile(c)).toOption.exists {
```

### io/io/src/test/scala/sbt/io/FileUtilitiesSpecification.scala

```
31:    unzipFile(IO.classLocationFile(mf.runtimeClass))
```

Looks like for the most part we are doing a hardcoded lookup from an sbt class to a JAR. This should work as long as we are using the File-based classpath.

```
scala> IO.classLocationFile[ForkMain]
res0: java.io.File = /Users/eed3si9n/.ivy2/local/org.scala-sbt/test-agent/1.3.0-SNAPSHOT/jars/test-agent.jar1s
```

**Comment by xuwei-k** [comment]
https://github.com/sbt/sbt/commit/6725b39a84c36cae707a354cf92a9ce4ffc7a109

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/4406 and https://github.com/sbt/io/pull/189
