### ISSUE TITLE
Task completion time is in UTC, not in system time zone

### ISSUE THREAD

**Issue by aaabramov** [sbt/sbt#4391]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps
Set system time zone to non-UTC (in my case it is `Europe/Kiev` (`EEST`)):

```
date +%Z
EEST
```

```
date
Fri Sep 28 13:22:51 EEST 2018
```

```
sbt compile
...
[success] Total time: 1 s, completed Sep 28, 2018 10:20:17 AM
```

## problem
Task completion time is shown in UTC not in local time.

## expectation
System time zone is being used.

## notes

sbt version: *1.2.3*

**Comment by eed3si9n** [comment]
It works for me:

```
sbt:IO Root> compile
[success] Total time: 2 s, completed Sep 28, 2018, 12:20:52 PM
```

**Comment by aaabramov** [comment]
@eed3si9n what is your time zone?
```
date +%Z
```

**Comment by eed3si9n** [comment]
I live in the US.

```
$ date +%Z
EDT
```

**Comment by aaabramov** [comment]
Closing this one.
In my global `SBT_OPTS` env I have the following config:

```
export SBT_OPTS="... -Duser.timezone=GMT"
```

So `user.timezone` overrides any local / machine timezone.
