### ISSUE TITLE
Classpath issue in sbt 1.1.5+

### ISSUE THREAD

**Issue by ahjohannessen** [sbt/sbt#4394]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps

Checkout https://github.com/ahjohannessen/sbt-classpath-issue and read the instructions listed in the readme.

## problem

Classpath available to `run` command is different in sbt `<= 1.1.4` and `>= 1.1.5`

## expectation

Identical classpaths in sbt `1.1.4` and `1.1.5+`

**Comment by eed3si9n** [comment]
If forking fixes the issue, I am guessing that 1.3.0 would provide a workaround via #4476:

```scala
Compile / classLoaderLayeringStrategy := ClassLoaderLayeringStrategy.Flat
```
