### ISSUE TITLE
--addPluginsSbtFile fails if .sbt/1.0/plugins directory does not exist

### ISSUE THREAD

**Issue by jastice** [sbt/sbt#4395]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps

1. fresh sbt install or `> rm -r ~/.sbt/1.0/plugins/`
2. create `extra.sbt` in a non-project path with contents:
```
addSbtPlugin("org.jetbrains" % "sbt-idea-shell" % "2017.2")
```
3. start sbt with `--addPluginsSbtFile /path/to/extra.sbt`

## problem

Plugins in `extra.sbt` are not loaded:
```
sbt:SCL-14415> plugins
In file:/Users/jast/playspace/SCL-14415/
	sbt.plugins.IvyPlugin: enabled in scl-14415
	sbt.plugins.JvmPlugin: enabled in scl-14415
	sbt.plugins.CorePlugin: enabled in scl-14415
	sbt.ScriptedPlugin
	sbt.plugins.SbtPlugin
	sbt.plugins.JUnitXmlReportPlugin: enabled in scl-14415
	sbt.plugins.Giter8TemplatePlugin: enabled in scl-14415
```

## expectation

after creating `plugins` directory and restarting, plugins are loaded as expected:
```
In file:/Users/jast/playspace/SCL-14415/
	sbt.plugins.IvyPlugin: enabled in scl-14415
	sbt.plugins.JvmPlugin: enabled in scl-14415
	sbt.plugins.CorePlugin: enabled in scl-14415
	sbt.ScriptedPlugin
	sbt.plugins.SbtPlugin
	sbt.plugins.JUnitXmlReportPlugin: enabled in scl-14415
	sbt.plugins.Giter8TemplatePlugin: enabled in scl-14415
	org.jetbrains.sbt.IdeaShellPlugin: enabled in scl-14415
```

## notes

sbt version: 1.2.0+

**Comment by eed3si9n** [comment]
Thanks for the report. That actually rings a bell because I piggy backed on the global plugin loading.

**Comment by NicolasRouquette** [comment]
Ah, this makes sense now. When I experienced this problem in #4375, I had wiped out `~/.sbt`.
So there was no `~/.sbt/1.0/plugins` folder either.

**Comment by jvican** [comment]
I just ran into this issue. It would be great if sbt can create this file if it doesn't exist at startup. It's quite confusing that the non-existence of this directory causes `-addPluginSbtFile` to fail with no information about the error.

**Comment by OlivierBlanvillain** [comment]
It looks like relative path given to `addPluginSbtFile` are resolved relatively to `~/.sbt/1.0/plugins`, which is probably related to this issue.
