### ISSUE TITLE
Failure in detection of recompilation targets

### ISSUE THREAD

**Issue by nuttycom** [sbt/sbt#44]
It appears that SBT does not detect that a package object needs to be recompiled when that package object extends a trait within that package. See the attached gist for files that demonstrate the problem.

This bug causes me to have to clean and recompile the project fully after each change that impacts such a trait. Here's a trace of a session demonstrating the error:

> clean
> [success] Total time: 0 s, completed Jun 7, 2011 1:40:54 PM
> compile
> [info] Updating...
> [info] Done updating.
> [info] Compiling 2 Scala sources to /Users/knuttycombe/tmp/sbt/target/scala-2.8.1.final/classes...
> [success] Total time: 6 s, completed Jun 7, 2011 1:41:01 PM

// at this point, add a line of whitespace to BarTrait.scala

> compile
> [info] Compiling 1 Scala source to /Users/knuttycombe/tmp/sbt/target/scala-2.8.1.final/classes...
> [error] error while loading bar, class file needed by package is missing.
> [error] reference type BarTrait of package foo.bar refers to nonexisting symbol.
> [error] one error found
> [error] Incomplete tasks (run 'last <task>' for the full log):
> [error]   {file:/Users/knuttycombe/tmp/sbt/}default/compile: Compilation failed
> [error] Total time: 1 s, completed Jun 7, 2011 1:41:21 PM

Sample files are here; no other build configuration is being used.

https://gist.github.com/1012980

**Comment by harrah** [comment]
Thanks, Kris.  I appreciate the minimized test case.

**Comment by harrah** [comment]
This is actually not a bug in incremental recompilation, but something odd with plain partial recompilation, but I can't yet reproduce it outside of sbt.

**Comment by harrah** [comment]
Reproducible outside of sbt by deleting the classes for BarTrait in between compilations.  Hopefully this won't end up meaning that package.scala has to be recompiled pretty much all of the time.

**Comment by retronym** [comment]
Possibly related issue in the IDEA builder. 

http://youtrack.jetbrains.net/issue/SCL-2990

https://bitbucket.org/dibblego/idea-package-object/src/tip/README

**Comment by harrah** [comment]
https://issues.scala-lang.org/browse/SI-4695

**Comment by ijuma** [comment]
Maybe worth adding a comment there that this affects SBT?

**Comment by harrah** [comment]
It is known that it affects sbt (Paul filed the bug).

Closing because it is a confirmed scalac bug.
