### ISSUE TITLE
Misleading error message `No Scala version specified or detected`

### ISSUE THREAD

**Issue by lgirault** [sbt/sbt#4412]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps
Start sbt with an empty ivy cache and no network 
(real use case scenario involve a sandboxed nix-build an a closed list of enabled urls)

## problem
sbt fails to start with the following error message : `Error during sbt execution: No Scala version specified or detected `

## expectation
An error message that explains better what is the problem such as :  `Error during sbt execution: Cannot retrieve artifact X`

## notes

sbt version: 1.2.1

**Comment by eed3si9n** [comment]
Thanks for the report. When you say "start sbt" how was it installed? Are you using the official sbt distribution or something else? I am asking this because the official distribution should contain all the JARs at least to launch `sbt` program.

**Comment by lgirault** [comment]
it was installed via the nix package manager : https://github.com/NixOS/nixpkgs/blob/288ce0cb845c03fafa1f3c673440e9922f22131a/pkgs/development/tools/build-managers/sbt/default.nix
do you need more details ?

**Comment by eed3si9n** [comment]
Thanks that looks like it's using the official distribution.

Could you post the full output of what you see when you start sbt as follows:

```
sbt -debug
```

**Comment by lgirault** [comment]
I'm sorry now that I fixed it, I have trouble reproducing the error. When I enable no url I stumble upon the following message
```unresolved dependency: org.scala-sbt#sbt;1.2.1: not found
Error during sbt execution: Error retrieving required libraries
```

and adding the missing library one by one lead to more `Error during sbt execution: Error retrieving required libraries` which is the message I was looking for.  

If you want you can close this issue

**Comment by eed3si9n** [comment]
ok. I'll close it for now, but feel free to add more info for future reference.
