### ISSUE TITLE
sbt ignores credentials defined in project/plugins.sbt but picks up resolvers while resolving plugins

### ISSUE THREAD

**Issue by pshirshov** [sbt/sbt#4434]
## steps

I have a project with a couple of resolvers defined in `project/plugins.sbt`, depending on local plugin:

```
resolvers in Global ++= Seq(
  "company-jfrog-releases" at artifactoryReleases,
  "company-jfrog-snapshots" at artifactorySnapshots
)

credentials in Global ++= Credentials(Path.userHome / s".sbt/credentials.company.properties")

lazy val selfPlugin = RootProject(file("../sbt/sbt-project-deps"))
lazy val root = project.in(file(".")).dependsOn(selfPlugin)
```

`../sbt/sbt-project-deps` depends on a plugin in private repo. `build.sbt` is:

```
sbtPlugin := true
libraryDependencies ++= Seq("org.scala-sbt" % "sbt" % sbtVersion.value)

addSbtPlugin("net.playq" % "sbt-base-deps" % "0.21.0-SNAPSHOT")
```

## problem

sbt tries to query the resolvers I use while resolving `sbt-base-deps` but doesn't send credentials and fails. It works with `coursier` installed globally though.

## notes

I feel like it's a regression, it definitely worked previously. Not sure when since we started using coursier globally several months ago.

sbt version: 1.2.6

May be relevant: #3844

**Comment by mickaelmagniez** [comment]
Same problem here, and with 1.3.0-rc1 too

**Comment by pshirshov** [comment]
I'm closing this. In our case the problem was an accidental change made by our devops which prevented `www-authentication` header from being sent. We didn't notice this because we've been using globally installed coursier for a while, and coursier has been optimizing traffic by avoiding `HEAD` requests in case only one credential set is defined in a project. Be very careful and check your http headers.

I'm sorry about being annoying with this problem.
