### ISSUE TITLE
update task performance and UpdateReport persistence

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4438]
## steps

1. sbt
2. `update`

## problem

`update` is slow due to its persistence of `UpdateReport` using JSON.
For a large graph, majority the information consists of "caller" information which is not needed unless you run eviction report.

## expectation

1. Try flattening the caller information like cached resolution.
2. Consider alternative persistence if JSON is the bottleneck.

**Comment by mdedetrich** [comment]
If JSON is the bottleneck (but you still want to try and persist JSON) you may want to consider having a look at http://www.lihaoyi.com/upickle/#uJson . uJson uses the visitor pattern to parse text into JSON and vice versa which means that no intermediate data structures are created, in other words its much faster than Circe/Argonaut/PlayJson (basically any other JSON library out there that uses an AST)

**Comment by rethab** [comment]
From the docs, I don't really get what the update report is used for. Could it be disabled if it is a bottleneck and not crucial?

**Comment by eed3si9n** [comment]
UpdateReport is the result of Ivy dependency resolution, which is upstream of things like external classpath. Using the caller information, we can display tree in the error message like:

```
[warn]  Note: Unresolved dependencies path:
[warn]    foundrylogic.vpp:vpp:2.2.1
[warn]      +- org.apache.cayenne:cayenne-tools:3.0.2
[warn]      +- org.apache.cayenne.plugins:maven-cayenne-plugin:3.0.2 (/foo/build.sbt#L25)
[warn]      +- root:root_2.10:0.1-SNAPSHOT
[trace] Stack trace suppressed: run last *:update for the full output.
[error] (*:update) sbt.ResolveException: unresolved 
```

However, all that rich information does not have to be persisted into a big JSON file (hundreds of MBs) if all we need typically is list of JARs.

### idea 1: updateSlim only
A potential idea might be to add a new data structure like `UpdateReportSlim`, and persist that instead, and NOT persist `UpdateReport` in `update` task.
The problem with that approach is that if there's a plugin out there that's calling or using `update` task (like [Play](https://github.com/playframework/playframework/blob/2.6.21/framework/src/play-docs-sbt-plugin/src/main/scala/com/typesafe/play/docs/sbtplugin/PlayDocsPlugin.scala#L177-L178)), it will trigger full update, and it will end up being even slower.

### idea 2: updateSlim and update
To workaround the issue with idea 1, we probably need to persist both `UpdateReport` and `UpdateReportSlim`.
That should make the reading side faster for projects without plugins that are using `update` tasks.
However, the writing will still be slow.

### idea 3: updateSlim, update, and updateFull
To workaround the issue with idea 2, one thing we could try is remove all caller information from `update` task when we persist `UpdateReport`, and provide another task `updateFull` if someone wants it.
