### ISSUE TITLE
https://dl.bintray.com/sbt/native-packages/sbt/ stops at v0.13.15

### ISSUE THREAD

**Issue by ctataryn** [sbt/sbt#4442]
## steps
Goto: https://dl.bintray.com/sbt/native-packages/sbt/

## problem
The latest 0.13.x version of sbt is 0.13.17 according to: https://www.scala-sbt.org/download.html

However only 0.13.15 has been released to https://dl.bintray.com/sbt/native-packages/sbt/

## expectation
The [Jenkins sbt plugin](https://github.com/jenkinsci/sbt-plugin) relies on dl.bintray.com to provide installers, however if 0.13.17 is not avaialbe there, then the jenkins plugin cannot use it for builds.

If there is an alternative release repo that contains >0.13.15, then I can update the sbt-plugin to use it, otherwise resolution of this issue would require uploading versions >0.13.15 to dl.bintray.com

Somewhat relates to: #4281

sbt version: *0.13.17*

**Comment by eed3si9n** [comment]
Yes, Bintray download started to go over monthly transfer allowance given to OSS projects, so we switched to hosting it ourselves. Since sbt 1.0.0 all installers should be available as https://piccolo.link/sbt-1.0.0.zip.

**Comment by ctataryn** [comment]
@eed3si9n is there a way to index the higher versions of 0.13.x? Pico is a URL shortener so its tough to index programmatically.

P.S. why can’t the 0.13.x jars be hosted on repo1.maven.org?

**Comment by ctataryn** [comment]
@eed3si9n I recently have been given commit on [jenkinsci/sbt-plugin](https://github.com/jenkinsci/sbt-plugin) and I'm looking to update the associated tool crawler such that it'll pickup all the 0.13.x versions missing from bintray (re: 0.13.16/17). Is my only option to parse the html of https://www.scala-sbt.org/download.html page then?  Or is there a way to query piccolo.link for all sbt-related shortened links? If not, would you consider switching to a shortener that does (i.e. bit.ly)?
