### ISSUE TITLE
Watch aborts if first task isn't successful

### ISSUE THREAD

**Issue by japgolly** [sbt/sbt#4446]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps

1. Create a build with two modules A and B such that B depends on A
1. Create a compilation error in A's main sources
2. Run `~B/test`

## problem

SBT reports the compilation error then goes back to the shell/prompt.

## expectation

It should be watching so that when I fix the compilation error, it gets automatically recompiled and then tests run. It used to work in earlier versions.

## notes

sbt version: 1.2.6

**Comment by eatkins** [comment]
I have seen this before, but I'm struggling to reproduce. I have a test project here: https://github.com/eatkins/sbt-coursier-multi-project where I'm unable to get `~` to exit early if I break Foo.scala in the parent directory. Would you be able to post a simple project that causes the issue for you?

I rewrote almost the entire file watch subsystem for sbt 1.3.x. Does the problem persist if you run sbt with `-Dsbt.version=1.3.0-bin-20181106T202042`? This is a nightly build so it will probably take a few minutes for sbt to start up with this property set.

**Comment by japgolly** [comment]
Sure, here is a repo with reproduction steps.

1. Check out https://github.com/japgolly/scala-graal
2. Change an `override def` to `xxx` in `core/src/main/scala/japgolly/scalagraal/Expr.scala`
3. SBT
4. Run `~extBoopickleJVM/test`

Output:

```
root> ~extBoopickleJVM/test
[info] Compiling 9 Scala sources to /home/golly/projects/public/scala-graal/core/target/scala-2.12/classes ...
[error] /home/golly/projects/public/scala-graal/core/src/main/scala/japgolly/scalagraal/Expr.scala:12:47: ';' expected but '=' found.
[error]   xxx apply(context: Context): Expr.Result[A] =
[error]                                               ^
[error] one error found
[error] (core / Compile / compileIncremental) Compilation failed
root>
```

**Comment by eatkins** [comment]
Great, thanks. I can reproduce on my machine now. I'll see about a fix.

**Comment by eatkins** [comment]
This should be fixed by #4447.

**Comment by japgolly** [comment]
Awesome and thanks for getting a fix in so fast!!

**Comment by eed3si9n** [comment]
Closing this as resolved.
