### ISSUE TITLE
Metabuild can't use scala compiler

### ISSUE THREAD

**Issue by eatkins** [sbt/sbt#4452]
## steps

I created a simple repo that reproduces the issue: https://github.com/eatkins/failed-plugin

## problem

If I build a local sbt version off of the head of the origin/develop branch, I am unable to access the scala.tools.nsc package:
```
[info] Loading project definition from /Users/ethanatkins/work/scratch/failed-plugin/project

[info] Compiling 1 Scala source to /Users/ethanatkins/work/scratch/failed-plugin/project/target/scala-2.12/sbt-1.0/classes ...
[error] /Users/ethanatkins/work/scratch/failed-plugin/project/com/swoval/Plugins.scala:3:14: object tools is not a member of package scala
[error] import scala.tools.nsc
[error]              ^
[error] /Users/ethanatkins/work/scratch/failed-plugin/project/com/swoval/Plugins.scala:6:22: not found: value nsc
[error]   val settings = new nsc.Settings()
[error]                      ^
[error] two errors found
```

## expectation

`scala.tools.nsc` is available.

**Comment by eatkins** [comment]
@eed3si9n if I revert https://github.com/sbt/sbt/commit/ab5e99c9c835985e3a003e1322d86895bce2af9b, the problem goes away.

**Comment by eed3si9n** [comment]
Interesting. Does that mean launcher-resolved sbt is different from the metabuild's dependency graph?

**Comment by eed3si9n** [comment]
It seems to work ok for sbt 1.3.2.

**Comment by eed3si9n** [comment]
In https://github.com/sbt/sbt/pull/6085 I resurrected https://github.com/sbt/sbt/pull/4443 with Coursier, and lo and behold this issue popped backed up according to https://github.com/scala/scala/pull/9202.
Ultimately though, I don't think excluding sbt modules from the dependency graph, and reusing the list of JARs from sbt-launcher (#4443 / #6085) is wrong. What I'm missing somehow is the way metabuild is compiled, and I wonder if it's more to do with setting up the right layered `ClassLoader` that has access to `scala-compiler`.

Another potential way of fixing this would be to simply append all the JARs from ScalaInstance into the classpath.

**Comment by eatkins** [comment]
> Another potential way of fixing this would be to simply append all the JARs from ScalaInstance into the classpath

I took this approach in #6146
