### ISSUE TITLE
Interaction between 'crossPaths := false' and '+publish'

### ISSUE THREAD

**Issue by erikerlandson** [sbt/sbt#4453]
- [x ] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps
Defined a `build.sbt` that has one sub-project that is java-only, and so I have set `crossPaths := false` for that project to publish artifacts without scala version (this part works).

If I publish with only a single `scalaVersion`, this works OK. However, if I have multiple versions in `crossScalaVersions`, I will get an error when it tries to invoke `publish` on this java sub-project a second time. Because it is now attempting to publish artifacts with the same names as previously, due to `crossPaths := false`.

Setting `publishConfiguration := publishConfiguration.value.withOverwrite(true)` works, but this is not great because it's re-generating artifacts multiple times, and over-write isn't safe.

So what I'm looking for is something that is logically similar to `skip in publish := false`, but is `true` for exactly one scala version, and only in the java sub-project.

## notes

sbt version: *insert sbt version*

**Comment by eed3si9n** [comment]
Please see https://www.scala-sbt.org/1.x/docs/Cross-Build.html#Cross+building+with+a+Java+project
