### ISSUE TITLE
Support multiple `test` files per scripted test to reuse code

### ISSUE THREAD

**Issue by ignasi35** [sbt/sbt#4458]
Often `test` files are bloated with many assertions to reuse the project built to run the tests on.

This makes it hard to fix issues when the error happens on the first assertion as the rest of the script is not run.

Discovering test files via a regexp (e.g. `test.*`) and considering each a separate test run would improve the testing UX.

**Comment by eed3si9n** [comment]
Interesting idea, but given the inactivity probably not going to happen.
