### ISSUE TITLE
Clean up task progress

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4461]
- Clean up some of the issues of it wiping out text
- Make it configurable via settings?

**Comment by eed3si9n** [comment]
@eatkins I can't reproduce the text wiping issue with hello world app:

[![asciicast](https://asciinema.org/a/RdVvxs7aTb9Vor1rJL2sD1e9T.svg)](https://asciinema.org/a/RdVvxs7aTb9Vor1rJL2sD1e9T)

I'm on macOS Mojave + iTerm2.

**Comment by eatkins** [comment]
Aah. I use the built in Terminal.app. I verified that if I use iterm2, then I don't see the issue that I showed you.

**Comment by eatkins** [comment]
That was a great clue. If I change the Terminal.app terminal emulation mode to vt100, I don't see the issue. Previously I had it set to xterm-256color.

**Comment by eatkins** [comment]
I switched back to xterm-256color and it still seems to be working, so I am not sure what my issue was.

**Comment by eatkins** [comment]
I do still see a bit of weirdness even with iterm:
![Output sample](https://media.giphy.com/media/5n7VbxEzxMW3GvINqf/giphy.gif)
This is in the sbt project itself where I'm running a local version of sbt off of the latest develop branch. In my ideal world, the previous task would not be deleted and the progress tasks would be fully cleared.

**Comment by eatkins** [comment]
In my ideal world, the progress tasks would be fully cleared, but my previous command would not be.

**Comment by eed3si9n** [comment]
> In my ideal world, the previous task would not be deleted and the progress tasks would be fully cleared.

Agreed on both points.

**Comment by eed3si9n** [comment]
Here's a recent SNAPSHOT. The progress status is cleared.

[![asciicast](https://asciinema.org/a/6xOQSpHucre4c8QHU342CFmhy.png?t=1:30)](https://asciinema.org/a/6xOQSpHucre4c8QHU342CFmhy?t=1:30)
