### ISSUE TITLE
Provide a means to report error without call stack

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [sbt/sbt#4469]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps

Make a task that has detected an error:

```
myCustomTask := {
  if (somethingNastyDetected())
      sys error "Something nasty"
  else
     workNormally()
}
```

## problem

A long noisy call stack is shown, that hides what has happened.

## expectation

I need a means of denoting failure in a stack for well known problems, and avoid a noisy call stack.

## notes

sbt version: 1.1.4

Long ago, I asked in [stackoverflow](https://stackoverflow.com/questions/30730249/how-to-avoid-stack-trace-with-sys-errormessage) how to make a task fail without call stack.

No good answers.

**Comment by eed3si9n** [comment]
I posted my answer to Stackoverflow that uses undocumented, internal exception class - https://stackoverflow.com/a/53525281/3827

We could potentially turn this into an official function like `sys.error(...)`, and define `messageOnlyError(...)` or something like that. The downside if you're trying to use it from a plugin is that it would bump the minimum sbt version to the next version of sbt, and would break on 1.2.6.

**Comment by DavidPerezIngeniero** [comment]
Thanks.  I'll try it right away.

**Comment by DavidPerezIngeniero** [comment]
Confirmed that it works. :-)

**Comment by DavidPerezIngeniero** [comment]
It would be interesting if this could be documented.
