### ISSUE TITLE
No scripted plugin for 0.11.3

### ISSUE THREAD

**Issue by aolshevskiy** [sbt/sbt#447]
`[error] {file:/home/siasia/work/xsbt-web-plugin/project/}plugins/*:update: sbt.ResolveException: unresolved dependency: org.scala-tools.sbt#scripted-plugin_2.9.1;0.11.3: not found`

Please advice.

**Comment by harrah** [comment]
https://github.com/harrah/xsbt/wiki/Changes

"The sbt group ID is changed to org.scala-sbt (from org.scala-tools.sbt)"

**Comment by aolshevskiy** [comment]
Thanks, Mark.

**Comment by JMacLulich** [comment]
Thanks, I'm having the same issue, what does this line mean "This means you must use a 0.11.3 launcher to launch 0.11.3."? I'm trying to install sbt following https://github.com/harrah/xsbt/wiki/Getting-Started-Setup. 

I don't understand what using a 0.11.3 launcher means? I'm install on Ubuntu 10.04 LTS.
