### ISSUE TITLE
Source JAR missing in Maven repo for 0.13.17

### ISSUE THREAD

**Issue by radumanolescu** [sbt/sbt#4478]
- [x ] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps
Compare the contents of these directories
https://maven.atlassian.com/maven-external/org.scala-sbt/compiler-interface/0.13.13/srcs/
https://maven.atlassian.com/maven-external/org.scala-sbt/compiler-interface/0.13.17/srcs/

## problem
The JAR compiler-interface-sources.jar  has not been published to the Maven repo for 0.13.17
As a consequence, my sbt build fails with this message:
```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::              FAILED DOWNLOADS            ::
[warn]  :: ^ see resolution messages for details  ^ ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scala-sbt#compiler-interface;0.13.17!compiler-interface.jar(src)
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
...
(my_proj_name/compile:compileIncremental) sbt.InvalidComponent: Couldn't retrieve source module: org.scala-sbt:compiler-interface:0.13.17:component
```

## expectation
The JAR compiler-interface-sources.jar  should be published to the Maven repo for 0.13.17

## notes
I have downloaded the source JAR for 0.13.13 and copied it to my local Ivy repo as 0.13.17. Build succeeds.
sbt version: *0.13.17*

**Comment by eed3si9n** [comment]
sbt 0.13.17 is published originally to https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.17/ in Ivy layout. srcs are available there.

**Comment by ericdotdata** [comment]
For other google searchers:

```
resolvers += Resolver.url("fix-sbt-plugin-releases", url("https://dl.bintray.com/sbt/sbt-plugin-releases"))(Resolver.ivyStylePatterns)
resolvers += Resolver.url("fix-sbt-releases", url("https://dl.bintray.com/typesafe/ivy-releases"))(Resolver.ivyStylePatterns)
```
