### ISSUE TITLE
Can't include JCenter in POM repositiories

### ISSUE THREAD

**Issue by Katrix** [sbt/sbt#4479]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps
1. Add jcenter resolver to build 
```scala
resolvers += Resolver.JCenterRepository
```
2. run `makePom`

## problem
JCenter is not included in the POM.

## expectation
```xml
<repositories>
    <repository>
        <id>jcenter</id>
        <name>jcenter</name>
        <url>https://jcenter.bintray.com/</url>
        <layout>default</layout>
    </repository>
</repositories>
```
in POM.

## notes
My guess is that this is the reason why it doesn't work.
https://github.com/sbt/librarymanagement/blob/87393a3f9f19867725060da7c425e27f53351e5c/ivy/src/main/scala/sbt/internal/librarymanagement/MakePom.scala#L454

Possible workaround
```scala
resolvers += MavenRepository(Resolver.JCenterRepositoryName, Resolver.JCenterRepositoryRoot + "net/..")
```
sbt version: *1.2.7*

**Comment by eed3si9n** [comment]
Thanks for the report!

**Comment by eed3si9n** [comment]
Most of the times people would use JCenter in place of Maven Central, so I am guessing that the current behavior is intentional.

**Comment by Katrix** [comment]
Can I have a setting for if I want JCenter in the pom then? I have a dependency for my library that's only found on JCenter, and I'd rather not have to tell people to explicitly add JCenter to the resolvers.

**Comment by eed3si9n** [comment]
Try:

```scala
ThisBuild / useJCenter := true
```

**Comment by Katrix** [comment]
Nope, doesn't work.

**Comment by SethTisue** [comment]
RIP JCenter (except as a read-only archive), so maybe we should just close this
