### ISSUE TITLE
sbt logging level doesn't affect test task

### ISSUE THREAD

**Issue by ikryvorotenko** [sbt/sbt#4480]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps
1. run `sbt new scala/scala-seed.g8` (or pick any sbt project)
2. run `sbt -warn`

## problem

sbt log output contains:
```
[info] HelloSpec:
[info] The Hello object
[info] - should say hello
```

## expectation
sbt log output produces only warn level logs, as it's provided in running parameter.

## notes
I've tried to provide logging level using `logLevel in Scope.Global := Level.Warn`, but it only affects main sbt execution flow, not test task.
I also checked the code and found `TestLogger#make` has the following code 
```
      LogExchange.bindLoggerAppenders(newLog.name, buffs map { x =>
        (x, Level.Debug)
      })
```
which looks like it's always produce an appender with debug level.

If this is expected behavior, there should be a way to override the logging level for test task.

This is becoming more critical, when i add `"com.novocode" % "junit-interface" % "0.11" % Test` and junit test. Junit runner produces debug log to each test case, so that completely spoils logs, like:
```
[debug] Test run started
[debug] Test sample.Test.testSample started
[debug] Test sample.Test.testSample finished, took 1.005 sec
[debug] Test run finished: 0 failed, 0 ignored, 1 total, 1.011s
```
See https://github.com/ikryvorotenko/sbt-junit-sample as example

sbt version: *1.2.6*

**Comment by eed3si9n** [comment]
@ikryvorotenko Thanks for the report.

**Comment by eed3si9n** [comment]
I agree with the expectation.
I think I chose debug level because of sbt server, but I probably should distinguish relay appender vs the rest.

**Comment by ikryvorotenko** [comment]
@eed3si9n are there any workarounds for this now?

**Comment by eed3si9n** [comment]
If you want to workaround without forking sbt, you'd have to copy-paste https://github.com/sbt/sbt/blob/v1.2.7/testing/src/main/scala/sbt/internal/testing/TestLogger.scala and re-implement it I guess.

**Comment by ikryvorotenko** [comment]
@eed3si9n thanks for suggestion. Though could you please clarify where the copied class is supposed to be placed, so that it overrides the native sbt's one.
I tried to put it under `{root}/project/sbt/internal/testing` but no luck.

**Comment by eed3si9n** [comment]
You'd have to put it under some other package name, put it under `project/`, and also rewire the appropriate key that uses `TestLogger#make` using AutoPlugin (testListener?) also defined in `project/`.

**Comment by ikryvorotenko** [comment]
@eed3si9n overriding `Test / test / testListeners` with custom `TestLogger` worked, thanks for pointing me on that. 
I could try to raise a PR with a new setting key, which would allow to configure logging level in tests. Does that make sense to you?

**Comment by ejayaraman** [comment]
We are upgrading our cucumber tests from SBT `0.13.x` to `1.x.x` and we can see our tests (running via Junit runner) are reporting debug logs as reported above. We are also migrating some ScalaTest from `0.13.x` to `1.x.x` and we don't see debug logs in ScalaTest. 

Another observation is, while I am able to reproduce the issue using https://github.com/ikryvorotenko/sbt-junit-sample (linked above) for SBT `1.2.6`, the issue does not occur when using SBT `1.3.12` in the same repo. However, when I introduced a cucumber test in the same repo, I can see debug logs for cucumber tests but not for ScalaTest. 

**The below test output uses these versions:**
Scala: 2.12.7
SBT : 1.3.12
junit: 4.12
cucumber-junit: 6.1.1
cucumber-scala: 6.1.1

You can notice in the below output the HelloSpec has no debug logs, but the cucumber test has debug logs. Is there a possibility this could be cucumber specific? Any insight or pointer to address this would be very helpful. Thank you. 

```
info] welcome to sbt 1.3.12 (Oracle Corporation Java 1.8.0_201)
[info] loading settings for project global-plugins from plugins.sbt ...
…
[info] loading settings for project root from build.sbt ...

[info] HelloSpec:
[info] The Hello object
[info] - should say hello

@Example
Scenario: The Hello Object should say hello # src/test/resources/features/example.feature:5
  Then The hello object should say hello    # StepDefinitions.scala:9
[debug] Test run started
[debug] Test Example Feature file using Cucumber.The Hello Object should say hello started
[debug] Test Example Feature file using Cucumber.The Hello Object should say hello finished, took 0.201 sec
[debug] Test run finished: 0 failed, 0 ignored, 1 total, 0.412s
[info] ScalaTest
[info] Run completed in 970 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Passed: Total 2, Failed 0, Errors 0, Passed 2
[success] Total time: 3 s, completed 06-Aug-2020 11:26:29
```
