### ISSUE TITLE
lsp does not inform about resolved compilation issues, so problem markers stay in vscode

### ISSUE THREAD

**Issue by ritschwumm** [sbt/sbt#4491]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps

* install the vscode extension in vscode
* open a scala file
* introduce a syntax error
* save
* remove the syntax error
* save again

## problem

the problems view still shows the now outdated syntax error

## expectation

the problem view does not show a problem marker where there is no problem

## notes

sbt version:1.2.7

my impression is that the LSP never sends textDocument/publishDiagnostics messages when compilation issues are fixed, so vscode cannot know they are.

**Comment by eed3si9n** [comment]
Thanks for the report!

**Comment by ritschwumm** [comment]
this seems to work in sbt 1.4.1, except for files being deleted, see #5937
