### ISSUE TITLE
exportedProductsNoTracking triggers compilation

### ISSUE THREAD

**Issue by fikovnik** [sbt/sbt#4492]
- [X ] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps

```
sbt clean
sbt 'show exportedProductsNoTracking'
```

## problem

I guess I miss something, but the above steps trigger compilation despite the description of `exportedProductsNoTracking`:
```scala
taskKey[Classpath]("Just the exported classpath without triggering the compilation.").withRank(CTask)
```

## expectation

Just the exported classpath without triggering the compilation.

## notes

sbt version: 1.1.4

**Comment by eed3si9n** [comment]
See https://www.scala-sbt.org/0.13/docs/sbt-0.13-Tech-Previews.html#Inter-project+dependency+tracking for the documentation on inter-project dependency tracking.
