### ISSUE TITLE
Delete key not behaving properly in Mac OSx / iterm2

### ISSUE THREAD

**Issue by weallcock** [sbt/sbt#4493]
- [ x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps
I am trying to take the coursera "functional programming principles in scala" course.  I have written some C and python, but have never used java or scala.  My apologies if I am simply not understanding something simple.

I am running iterm2, build 3.2.6 on Mac Sierra 10.12.6, TERM is set to xterm-256-color.

I upgraded sbt via homebrew:
```narya:UB3WhoImportedMe allcock$ brew upgrade sbt
==> Upgrading 1 outdated package:
sbt 1.0.3 -> 1.2.7
==> Upgrading sbt
==> Downloading https://github.com/sbt/sbt/releases/download/v1.2.7/sbt-1.2.7.tgz

<SNIP>

==> Summary
🍺  /usr/local/Cellar/sbt/1.2.7: 521 files, 50MB, built in 55 seconds
```

However, the coursera project has a build.sbt with a different version and it did indeed download and rebuild (the output was long, so I only provided the first few and last few lines, but can provide the rest if needed):
```
narya:example allcock$ sbt
Getting org.scala-sbt sbt 0.13.17  (this may take some time)...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.17/jars/sbt.jar ...
	[SUCCESSFUL ] org.scala-sbt#sbt;0.13.17!sbt.jar (1447ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.10.7/scala-library-2.10.7.jar ...
	[SUCCESSFUL ] org.scala-lang#scala-library;2.10.7!scala-library.jar (2589ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.17/jars/main.jar ...
	[SUCCESSFUL ] org.scala-sbt#main;0.13.17!main.jar (2321ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-interface/0.13.17/jars/compiler-interface.jar ...
	[SUCCESSFUL ] org.scala-sbt#compiler-interface;0.13.17!compiler-interface.jar (1660ms)

<SNIP>

[info] 	[SUCCESSFUL ] com.dwijnand#sbt-compat;1.2.5!sbt-compat.jar(src) (1067ms)
[info] Done updating.
[info] Compiling 8 Scala sources to /Users/allcock/Documents/Coursera/FunctionalProgrammingPrinciplesInScala/example/project/target/scala-2.10/sbt-0.13/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.10.7. Compiling...
[info]   Compilation completed in 7.858 s
[warn] /Users/allcock/Documents/Coursera/FunctionalProgrammingPrinciplesInScala/example/project/CommonBuild.scala:3: trait Build in package sbt is deprecated: Use .sbt format instead
[warn] trait CommonBuild extends Build {
[warn]                           ^
[warn] one warning found
[info] Set current project to progfun1-example (in build file:/Users/allcock/Documents/Coursera/FunctionalProgrammingPrinciplesInScala/example/)
```

And the contents of the course build.sbt file:

```
narya:example allcock$ cat build.sbt
name := course.value + "-" + assignment.value

scalaVersion := "2.11.12"

scalacOptions ++= Seq("-deprecation")

// grading libraries
libraryDependencies += "junit" % "junit" % "4.10" % Test

// for funsets
libraryDependencies += "org.scala-lang.modules" %% "scala-parser-combinators" % "1.0.4"

// include the common dir
commonSourcePackages += "common"

courseId := "<redacted>"
```

## problem
My problem is very similar to this StackOverflow post (which had no responses, so I had nothing to try from there):
https://stackoverflow.com/questions/48786843/running-sbt-command-makes-delete-key-behave-wierd
In both versions of sbt, both at the command prompt and in the console / interpreter, when you hit the backspace key, the screen shows the cursor moving forward and no characters are deleted on the screen, however, if you hit return, it did indeed delete the characters.  That is not how it was described in the post above, though I suspect he just didn't realize the characters were being deleted.  

```narya:example allcock$ sbt
[info] Loading project definition from /Users/allcock/Documents/Coursera/FunctionalProgrammingPrinciplesInScala/example/project
[info] Set current project to progfun1-example (in build file:/Users/allcock/Documents/Coursera/FunctionalProgrammingPrinciplesInScala/example/)
> foo   |
>
```
I added the vertical bar, so you can see where the cursor was and note that there was no error when I hit return even though foo is not a valid command.  Here is the same thing, only hitting delete twice:
```> foo
[error] Not a valid command: f
[error] Not a valid project ID: f
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: f
[error] f
[error]  ^
>
```
Also, as in the above post, the arrow keys behave as described.  An up and down arrow bring up  previous and next commands, but with no line feed, they are just spaced or tabbed over on the same line.  Left and right seem to have no impact at all.  While it is actually deleting the characters it is completely unusable except in the simplest of command lines.

## expectation
The console display should update so that you can tell what was deleted and what the contents of the line actually are.  Also, left and right arrows should move the cursor along the command line.

## notes

sbt version: 
Honestly, I am not sure.  As I pasted above, I saw 0.13.17 and brew said the other version was 1.2.7, but they both say 0.1-SNAPSHOT when I type version on the sbt command line.

**Comment by eed3si9n** [comment]
Thanks for the report.

sbt version is determined by `project/build.properties` file. If this is for some coursera course, it would be best to stick to the sbt version the lecturer has provided.

The delete key situation sounds like you're having some bad interaction with JLine2, which we use internally. For what it's worth, I personally use iTerm2 with macOS, and it works for me.

1. Do you have TERM set? I think it comes from Preferences > Profile > Terminal > Report terminal type. Mine is `xterm-256color`.
2. Do you have `~/.inputrc` configured? I don't have the file, but I think JLine2 does stuff with keybinding when it finds it.

As a workaround you can try the following:

```
$ sbt -Djline.terminal=unix
```

or

```
$ sbt -Djline.terminal=false
```

**Comment by weallcock** [comment]
```
sbt -Djline.terminal=false
```
Did the trick.  Thanks for your help.

**Comment by weallcock** [comment]
An update on this.  Setting terminal=false fixes the backspace problem, but not the arrow problem.  I opened an issue with jline2 and when I get this fully resolved, I will update this issue.

**Comment by eed3si9n** [comment]
Arrow key is handled by JLine2, so by passing in `terminal=false` you forfeit the JLine2-enable features like commandline history via arrow key.
