### ISSUE TITLE
Debian sbt repository not signed

### ISSUE THREAD

**Issue by sunshinekitty** [sbt/sbt#4507]
- [ x ] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps

Follow steps at https://www.scala-sbt.org/1.x/docs/Installing-sbt-on-Linux.html

- echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
- sudo apt-get update
- sudo apt-get install sbt

## problem

apt-get install sbt fails with

Ign:8 https://dl.bintray.com/sbt/debian  InRelease
Get:9 https://dl.bintray.com/sbt/debian  Release [815 B]
Ign:10 https://dl.bintray.com/sbt/debian  Release.gpg
Reading package lists...
E: The repository 'https://dl.bintray.com/sbt/debian  Release' is not signed.

## expectation

sbt package installs

## notes

seems similar to #3883
sbt version: all

**Comment by nhynes** [comment]
Yep. For reference (for people who are new to Debian), a workaround is

```
# replace 1.2.8 with the latest version at https://dl.bintray.com/sbt/debian/
wget https://dl.bintray.com/sbt/debian/sbt-1.2.8.deb
sudo dpkg -i sbt-1.2.8.deb
sbt
```

since the url is https and `wget` checks certs, you can rest relatively assured that you won't be installing malicious software :)

**Comment by eed3si9n** [comment]
Recalculated the metadata.

**Comment by RiteshBM** [comment]
Same issue
```
E: Failed to fetch http://dl.bintray.com/sbt/debian/InRelease  403  Forbidden [IP: 34.223.170.36 80]
E: The repository 'http://dl.bintray.com/sbt/debian  InRelease' is not signed.
```

Facing the same issue, workaround suggested by @nhynes results in 
```
user@Machine:~$ wget https://dl.bintray.com/sbt/debian/sbt-1.4.9.deb
--2021-04-12 16:29:35--  https://dl.bintray.com/sbt/debian/sbt-1.4.9.deb
Resolving dl.bintray.com (dl.bintray.com)... 52.40.89.93, 34.223.170.36, 52.40.49.72, ...
Connecting to dl.bintray.com (dl.bintray.com)|52.40.89.93|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-04-12 16:29:35 ERROR 403: Forbidden.

```

**Comment by RiteshBM** [comment]
Same issue
```
E: Failed to fetch http://dl.bintray.com/sbt/debian/InRelease  403  Forbidden [IP: 34.223.170.36 80]
E: The repository 'http://dl.bintray.com/sbt/debian  InRelease' is not signed.
```
Workaround suggested by @nhynes  results in
```
user@Machine:~$ wget https://dl.bintray.com/sbt/debian/sbt-1.4.9.deb
--2021-04-12 16:29:35--  https://dl.bintray.com/sbt/debian/sbt-1.4.9.deb
Resolving dl.bintray.com (dl.bintray.com)... 52.40.89.93, 34.223.170.36, 52.40.49.72, ...
Connecting to dl.bintray.com (dl.bintray.com)|52.40.89.93|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-04-12 16:29:35 ERROR 403: Forbidden.
```

**Comment by darshan-rathi** [comment]
Same issue as @RiteshBM 

```
Err:5 http://dl.bintray.com/sbt/debian  InRelease                                                                                                  
  403  Forbidden [IP: 52.42.38.157 80]
Hit:6 http://security.ubuntu.com/ubuntu bionic-security InRelease                                    
Reading package lists... Done                      
E: Failed to fetch http://dl.bintray.com/sbt/debian/InRelease  403  Forbidden [IP: 52.42.38.157 80]
E: The repository 'http://dl.bintray.com/sbt/debian  InRelease' is not signed.

```

**Comment by mattshine** [comment]
Same issue as the above listed.

```
Reading package lists...
--
110 | E: Failed to fetch https://dl.bintray.com/sbt/debian/InRelease  403  Forbidden
111 | E: The repository 'https://dl.bintray.com/sbt/debian  InRelease' is not signed.
```

**Comment by netronicus** [comment]
same here!

Reading package lists...
--
71 | E: Failed to fetch https://dl.bintray.com/sbt/debian/InRelease  403  Forbidden [IP: 34.214.135.19 443]
72 | E: The repository 'https://dl.bintray.com/sbt/debian  InRelease' is not signed.

**Comment by eed3si9n** [comment]
Bintray is conducting a brown out - https://github.com/sbt/sbt/issues/6445
