### ISSUE TITLE
scripted within scripted do not work with latest util version

### ISSUE THREAD

**Issue by eatkins** [sbt/sbt#4514]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps
publish "1.3.0-SNAPSHOT" in https://github.com/sbt/util
change utilVersion to "1.3.0-SNAPSHOT" in project/Dependencies.scala

## problem
scripted tests fail hard with java.lang.NoClassDefFoundError: Could not initialize class org.apache.logging.log4j.util.PropertiesUtil

## expectation
scripted works

## notes

sbt version: unreleased

**Comment by eatkins** [comment]
The problem seems to be that scripted is using the classpath for an older version of sbt that does not provide this newer class. I'm not sure how we can upgrade util and successfully test on travis without first releasing a new version of sbt that scripted tests can use instead of 1.1.5 or whatever they're using.

**Comment by eatkins** [comment]
This is also related to a more general problem that if you add to the public api of sbt, but run scripted tests against an older version, certain apis are not available during scripted startup. This leads to a chicken and the egg problem where we can't release sbt without running scripted, but we can't run scripted without upgrading sbt. I'm not sure how best to address this.

**Comment by eed3si9n** [comment]
I feel like I've seen something like this before. Can we work around this by forcing latest log4j in the metabuild of sbt/sbt?

**Comment by eed3si9n** [comment]
I have a failing PR due to this issue - https://github.com/sbt/sbt/pull/4524

```
[error] 	project/scripted-plugin
[error] 	project/scripted-skip-incompatible
```

**Comment by eed3si9n** [comment]
Suspicious parts are:

https://github.com/sbt/sbt/blob/08d5eed549a458db2ab0909695686ed0dd104f1d/project/Scripted.scala#L103-L105

where the metabuild of sbt/sbt is sneaking into the freshly baked code.

**Comment by eed3si9n** [comment]
Should this be reopened based on https://github.com/sbt/sbt/pull/4527#issuecomment-459198959?

**Comment by eatkins** [comment]
No. My issue was that _none_ of the scripted tests would work prior to #4527. Those two tests that you had to disable were not what I was having trouble with.
