### ISSUE TITLE
SBT interactive prompt for 'new' is broken in Windows using MSYS2 / Git Bash / Cygwin

### ISSUE THREAD

**Issue by bruno-medeiros** [sbt/sbt#4522]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps

Run `sbt new scala/scala-seed.g8` in MSYS2 / Git Bash / Cygwin
The `new` task will ask for the new project name

## problem
Typing characters into the prompt, but they will not be displayed. Also backspace gets interpreted as a character (`\177`), not as a deletion. Pressing either creates a project with weird name:

![image](https://user-images.githubusercontent.com/4324232/51919955-5ce80e80-23dc-11e9-81ba-a3b84f193bdd.png)

## expectation
Typed characters are displayed, and backspace/delete delete characters (and arrow keys move, etc)

## notes

sbt version: 12.8

Tried with Git-Bash: `Git-2.20.1-64-bit`
and MSYS2: `msys2-x86_64-20180531`

**Comment by eed3si9n** [comment]
sbt delegates `new` to a template resolver, and stuff ending with ".g8" goes to Giter8, so it should likely require Giter8 fix. Do you mind reporting it to https://github.com/foundweekends/giter8/issues instead?

**Comment by bruno-medeiros** [comment]
Sure, created: https://github.com/foundweekends/giter8/issues/414
