### ISSUE TITLE
java.lang.NoClassDefFoundError: scala/math/Ordering$$anon$9 in runtime after adding sbt plugin

### ISSUE THREAD

**Issue by zella** [sbt/sbt#4525]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps

1) Create hello world project from official template
2) Add code, that uses scala compiler, in my case https://github.com/scalate/scalate
3) Add plugin: `addSbtPlugin("com.lucidchart"  % "sbt-scalafmt" % "1.16")`
4) Run code, that uses scala compiler

or
1) git clone https://github.com/zella/sbt-issue
2) sbt run

## problem
```
[error] Caused by: java.lang.NoClassDefFoundError: scala/math/Ordering$$anon$9
[error]         at scala.tools.nsc.transform.LambdaLift$LambdaLifter.<init>(LambdaLift.scala:67)
[error]         at scala.tools.nsc.transform.LambdaLift.newTransformer(LambdaLift.scala:49)
[error]         at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
[error]         at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:426)
[error]         at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:419)
[error]         at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1(Global.scala:390)
[error]         at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1$adapted(Global.scala:390)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:941)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error]         at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:390)
[error]         at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1446)
[error]         at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1430)
[error]         at scala.tools.nsc.Global$Run.compileSources(Global.scala:1423)
[error]         at scala.tools.nsc.Global$Run.compile(Global.scala:1539)
[error]         at org.fusesource.scalate.support.ScalaCompiler.compile(ScalaCompiler.scala:89)
```
No failures without `addSbtPlugin("com.lucidchart"  % "sbt-scalafmt" % "1.16")`

## expectation

I expect no failures.

## notes

**upd** No failures with sbt 1.1.1. With 1.1.2+ failed

sbt version: *1.2.8*

**Comment by eed3si9n** [comment]
@zella Thanks for the report. The interaction with neo-sbt-scalafmt sounds interesting.
If this started in sbt 1.1.2, then it might be related to this change - https://github.com/sbt/zinc/pull/505

sbt 1.3.0 should give you finer tuning of the classloader (https://github.com/sbt/sbt/pull/4476 by @eatkins) so hopefully this can be solved there. In the meantime, you might have to work around this by using forked run.

**Comment by eed3si9n** [comment]
The key step here is "Run code, that uses scala compiler". Scalate 1.9.0 uses Scala 2.12.6.
https://github.com/scalate/scalate/blob/scalate-project-1.9.0/build.sbt#L13-L14

Unlike Scala library, Scala compiler does not have binary compatibility between the patch releases, so you can't mix and match Scala compiler 2.12.6 with Scala library 2.12.8. When I downgraded Scala version to 2.12.6, it got the following output:

```
Hello Chris
You have just won $10,000!
Well, $6,000, after taxes.
```

**Comment by eed3si9n** [comment]
And oh why does this happen only when neo-sbt-scalafmt is in the picture?
It's because by default sbt uses Ivy mediator to enforce scala-library and scala-compiler to line up (https://github.com/sbt/sbt/pull/2634), but neo-sbt-scalafmt turns that off.
https://github.com/lucidsoftware/neo-sbt-scalafmt/blob/1.16/sbt-scalafmt/src/main/scala-2.12/com/lucidchart/sbt/scalafmt/Platform.scala#L42
