### ISSUE TITLE
Building and publishing artifacts in a CI/CD environment

### ISSUE THREAD

**Issue by abelmokadem** [sbt/sbt#4541]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps
This is what I thought a simple CI/CD pipeline for an SBT library would look like:
1. `sbt clean update compile test package`
2. `sbt publish`

Between step 1 and 2 some artifacts should be cached in order to ensure that publishing can happen with those same artifacts. 

## problem
SBT fetches all the packages and recompiles the library during publishing.

## expectation
I would expect that copying the results of package and then running publish, would just grab those artifacts and publish them without rebuilding them again.

## notes

sbt version: 1.2.1

**Comment by eed3si9n** [comment]
@abelmokadem Thanks for the report. Is this something that you observe with any build, or some specific builds? It would be helpful if you have a reproducible project. In particular I am wondering if presence of Play or dynamic revision affect this.

**Comment by abelmokadem** [comment]
@eed3si9n because this is a private build I can't just share it with you as is. I will make something similar in either Travis or CircleCI so that you can see my issue. Thanks for your reply. 👍

**Comment by abelmokadem** [comment]
@eed3si9n haven't had the time yet, but maybe I can elaborate. 

When you build and package a project, then sbt creates a jar file right? 

If you remove everything (target, project/target) **except** for the generated jar files and you run `sbt publish`, then sbt will start the whole process of fetching packages, compiling your code, packaging your code and publishing. 

I don't expect this to happen. I just want to publish the jar files to nexus, with the generated artifacts that I have. Is there a lightweight command in sbt for only publishing certain jar files to a maven repo?

**Comment by eed3si9n** [comment]
sbt stores the internal state in the target directory so if you wipe that out, I expect no caching behavior.
