### ISSUE TITLE
Running sbt in docker 18.09.2-ce on arch linux leads to core dump due to lack of memory

### ISSUE THREAD

**Issue by pascalwhoop** [sbt/sbt#4557]
running

```
$ docker --version                                                                                                                                                                     Mo 11 Mär 2019 16:48:03 CET
Docker version 18.09.2-ce, build 62479626f2
$ uname -r                                                                                                                                                                             Mo 11 Mär 2019 16:48:04 CET
4.19.24-1-MANJARO
```

when trying to execute sbt after installing it with 
```
echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
apt-get update
apt-get install sbt 
```

as well as using 

```
docker run -it hseeberger/scala-sbt:latest
```

leads to 
```
root@04d9a62b8c63:~# sbt --version
library initialization failed - unable to allocate file descriptor table - out of memory/usr/share/sbt/bin/sbt-launch-lib.bash: line 59:  1786 Aborted                 (core dumped) "$@"
```

## expectation
Being able to run sbt

## notes

sbt version is latest available on debian with `apt-get install`, I can't really tell exactly though as even the version call won't work inside of the docker container. 
I am running arch linux which is a rolling release OS, hence it's hart to pinpoint a version there.

**Comment by pascalwhoop** [comment]
Alright I am seeing that `sbt --version` doesn't exist when looking into `sbt-launch-lib.bash` and `sbt -h` does work (but that's just bash scripting so duh)...

**Comment by eed3si9n** [comment]
It seems like you found your own answer that's unrelated to sbt? - https://superuser.com/a/1413390

**Comment by pascalwhoop** [comment]
I did yes. Sorry for the ticket here, it was the only java container I was running at the time. Maybe someone stumbles here through the magics of search engines though and then they find the answer you linked.
