### ISSUE TITLE
sbt clean reports Total time as 0s

### ISSUE THREAD

**Issue by anilkumarmyla** [sbt/sbt#4558]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps
```
$ time sbt clean
...
[success] Total time: 0 s, completed Mar 11, 2019, 6:33:57 PM

real	0m9.323s
user	0m26.512s
sys	0m1.669s
```

## problem
Total time is always 0s for sbt clean task

## expectation
Total time should show how much time has elapsed

## notes

sbt version: 1.2.8

**Comment by eed3si9n** [comment]
sbt is an interactive build tool, which assumes that you have it running in interactive mode.
The total time should then indicate the time it took to process `clean` as the command.
