### ISSUE TITLE
https://sbt.bintray.com now in 502.

### ISSUE THREAD

**Issue by minhoryang** [sbt/sbt#4565]
- [v] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps
Following https://www.scala-sbt.org/1.0/docs/Installing-sbt-on-Linux.html,
```
curl https://bintray.com/sbt/rpm/rpm | sudo tee /etc/yum.repos.d/bintray-sbt-rpm.repo
sudo yum install sbt
```
leads to `https://sbt.bintray.com/rpm`.

## problem
- `https://sbt.bintray.com/rpm` in 502.

## expectation
- well installed

## notes

sbt version: *

## Current Status:
Bintray knows: https://status.bintray.com/incidents/2wvx6d5f807c

**Comment by eed3si9n** [comment]
@minhoryang Thanks for the report.
As a workaround, you can try the universal package available from https://www.scala-sbt.org/download.html, which contains all the sbt JARs.

**Comment by eed3si9n** [comment]
Supposedly this issue has been resolved.
