### ISSUE TITLE
Clean is now implemented using globs.

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4572]
## steps

```scala
cleanFiles += (buildDirectory in ThisBuild).value / "osgi"
```

## problem

I get

```
/Users/eed3si9n/work/scala/build.sbt:738: warning: value cleanFiles in object Keys is deprecated (since 1.3.0): Clean is now implemented using globs.
    cleanFiles += (buildDirectory in ThisBuild).value / "osgi"
    ^
```

## expectation

"now" gets pretty old, so we should avoid it.
I think it would be better to say "use blabla key instead" (no period), and also point to a migration guide?

**Comment by eatkins** [comment]
Yep. I didn't put a ton of thought into the deprecation warning messages. I need to update most/all of them. Where would a migration guide live?  On the sbt website? In `.md` files in the repo?

**Comment by eed3si9n** [comment]
> Where would a migration guide live? On the sbt website? In .md files in the repo?

Initially on the release note / blob post, then on the website I guess.

**Comment by eatkins** [comment]
Yeah. I also should have written before I closed this that I consider the migration guide a part of https://github.com/sbt/sbt/issues/4460.
