### ISSUE TITLE
sbt install on docker : server error for for libraries  sbt 1.2.8 

### ISSUE THREAD

**Issue by deepikathimmegowda** [sbt/sbt#4581]
## steps
I have docker file  to build and run play app
```
FROM centos:7.5.1804 as builder
RUN curl https://bintray.com/sbt/rpm/rpm | tee /etc/yum.repos.d/bintray-sbt-rpm.repo
RUN yum update -y
RUN yum install wget -y
RUN yum install epel-release -y
RUN yum install java-11-openjdk.x86_64 -y 
RUN yum install java-11-openjdk-devel.x86_64 -y
RUN yum install unzip -y
RUN yum install sbt -y
RUN sbt sbtVersion
.. ... .. 

```
## problem
All these while I was able to to build docker image without issues, but today when im building my docker image I am facing 'SERVER ERROR' for few libraries  After timeout the build process continue
as usual. 

Cos of time out,  docker  image build time drastically increased. Kindly help

**Step  RUN sbt sbtVersion is giving server error for few plugins and my build is getting delayed**

[0m[[0m[31merror[0m] [0m[0mSERVER ERROR: Gateway Time-out url=https://repo.typesafe.com/typesafe/ivy-releases/com.lightbend.play/play-file-watch_2.12/1.1.7/ivys/ivy.xml[0m
[0m[[0m[31merror[0m] [0m[0mSERVER ERROR: Gateway Time-out url=https://repo.typesafe.com/typesafe/ivy-releases/io.methvin/directory-watcher/0.3.2/ivys/ivy.xml[0m
[0m[[0m[31merror[0m] [0m[0mSERVER ERROR: Gateway Time-out url=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.play/twirl-compiler_2.12/1.3.15/ivys/ivy.xml[0m
[0m[[0m[31merror[0m] [0m[0mSERVER ERROR: Gateway Time-out url=https://repo.typesafe.com/typesafe/ivy-releases/org.glassfish.hk2/hk2-bom/2.4.0-b34/ivys/ivy.xml[0m
[0m[[0m[31merror[0m] [0m[0mSERVER ERROR: Gateway Time-out url=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.glassfish.hk2/hk2-api/2.4.0-b34/jars/hk2-api.jar[0m
[0m[[0m[31merror[0m] [0m[0mSERVER ERROR: Gateway Time-out url=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.glassfish.hk2/hk2-utils/2.4.0-b34/ivys/ivy.xml[0m
[0m[[0m[31merror[0m] [0m[0mSERVER ERROR: Gateway Time-out url=https://repo.typesafe.com/typesafe/ivy-releases/org.glassfish.hk2.external/aopalliance-repackaged/2.4.0-b34/ivys/ivy.xml[0m
[0m[[0m[31merror[0m] [0m[0mSERVER ERROR: Gateway Time-out url=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.glassfish.jersey.media/jersey-media-json-jackson/2.22.2/jars/jersey-media-json-jackson.jar[0m
[0m[[0m[31merror[0m] [0m[0mSERVER ERROR: Gateway Time-out url=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.glassfish.jersey.ext/jersey-entity-filtering/2.22.2/ivys/ivy.xml[0m
[0m[[0m[31merror[0m] [0m[0mSERVER ERROR: Gateway Time-out url=https://repo.typesafe.com/typesafe/ivy-releases/org.vafer/jdeb/1.3/maven-plugins/jdeb.jar[0m
[0m[[0m[31merror[0m] [0m[0mSERVER ERROR: Gateway Time-out url=https://repo.typesafe.com/typesafe/ivy-releases/org.sonatype.spice/spice-parent/12/jars/spice-parent.jar[0m
[0m[[0m[31merror[0m] [0m[0mSERVER ERROR: Gateway Time-out url=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.reactivestreams/reactive-streams/1.0.1/ivys/ivy.xml[0m
[0m[[0m[31merror[0m] [0m[0mSERVER ERROR: Gateway Time-out url=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.webjars/npm/4.2.0/ivys/ivy.xml[0m

## expectation
As there is 

## notes

sbt version: sbt 1.2.8

**Comment by holzfelix** [comment]
I have the same issue! Is there a ways to use a specific sbt version? I have the following Install script in my docker yml. 

~~~
apt-get install -y apt-transport-https
echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823


apt-get update
apt-get install -y sbt
~~~

This installs sbt 0.13.17

Can I use the previous version? and when how can I set the version in my yml?

**Comment by holzfelix** [comment]
`apt-get install -y sbt=1.2.8`

**Comment by eed3si9n** [comment]
See also https://github.com/sbt/sbt/issues/4578 and https://status.bintray.com/.
Bintray download service was unstable, which probably caused the timeout.
