### ISSUE TITLE
[1.3.0-M2] Symbol 'type sbt.io.PathFinder.Combinator' is missing from the classpath

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4582]
## steps

https://jenkins.scala-sbt.org:8592/job/sbt-community/641/consoleFull

```
[22:43:20] [akka-stuff] Fetching https://github.com/akka/akka.git
```

## problem

```
[error] /xxxx/akka/project/AddLogTimestamps.scala:19:68: Symbol 'type sbt.io.PathFinder.Combinator' is missing from the classpath.
[error] This symbol is required by 'method sbt.io.BaseSyntax.singlePathPathFinderCombinator'.
[error] Make sure that type Combinator is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'BaseSyntax.class' was compiled against an incompatible version of sbt.io.PathFinder.
[error]   val enableTimestamps: Boolean = CliOption("akka.log.timestamps", false).get
[error]                                                                    ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

## expectation

works.

## notes

See also https://twitter.com/nafg613/status/1110328280643719168

**Comment by eed3si9n** [comment]
@eatkins I am not sure if the error position is correct, but somewhere along the line IO syntax broke the bincompat, I think.
https://github.com/sbt/io/commits/develop/io/src/main/scala/sbt/io/syntax.scala

**Comment by eatkins** [comment]
Yeah. I’ve seen some weirdness with that. I’ll look into it.

**Comment by eed3si9n** [comment]
I think I know what's going on.
As the error message suggests, I should've first tried `-Ylog-classpath`. https://gist.github.com/eed3si9n/664583b405d84666657544170b04715d is the output you get, showing:

```
/xxx/.ivy2/cache/org.scala-sbt/io_2.12/jars/io_2.12-1.2.2.jar
```

This is because sbt 1.3.0 reuses application classpath from the sbt launcher into metabuild. I've excluded sbt out of the metabuild graph, but I need to probably exclude all sbt modules and/or organization.
