### ISSUE TITLE
Distribute SBT in a Flatpak on Flathub

### ISSUE THREAD

**Issue by LeandroStanger** [sbt/sbt#4584]
http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by eed3si9n** [comment]
Are you saying that sbt should be able to generate Flatpak packages?
If so that would probably belong to a plugin like sbt Native Packager.

**Comment by eed3si9n** [comment]
I feel like there's already too many package managers I'm personally responsible for distributing sbt very time it comes out. I am certainly not going to jump in to endorse another package manager without popular demand.
