### ISSUE TITLE
Scala Object not compiling if only test dependency exists

### ISSUE THREAD

**Issue by evbo** [sbt/sbt#4598]
- [X] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps

- Create a new SBT project
- Create `./src/main/scala/emptyFile.scala`
- Create `./project/Dependencies.scala`, containing: `object Dependencies {val scalaTestVersion = "3.0.5"}`
- Create `./build.sbt` containing: `scalaVersion := "2.12.8"` & `libraryDependencies := Seq("org.scalatest" %% "scalatest" % Dependencies.scalaTestVersion % Test)`
- Run: `sbt compile`

## problem
Presence of `Test` scope in `scalatest` dependency leads to:
`scala.reflect.internal.MissingRequirementError: object scala in compiler mirror not found.`

If you change `./build.sbt` by removing `% Test` this problem does not happen. If you duplicate the dependency this problem does not happen, e.g.:
```
libraryDependencies := Seq(
  "org.scalatest" %% "scalatest" % Dependencies.scalaTestVersion,
  "org.scalatest" %% "scalatest" % Dependencies.scalaTestVersion % Test,
)
```

I repeated this issue using the same steps but with: `"org.scala-lang" % "scala-library" % Dependencies.scalaVersion % Test`

So it's not just `scalatest` related.

## expectation

Project should compile

## notes
reproduced this issue using sbt `1.1.1` and `1.2.8`
sbt version: 1.2.8

**Comment by eed3si9n** [comment]
@evbo Thanks for a detailed bug report.
Although I don't think this is a bug, I think I know what might be going on.

As an example, we can reduce `build.sbt` to just the following line:

```scala
ThisBuild / scalaVersion     := "2.12.8"
```

Now, if you start an sbt session, and type `libraryDependencies` into the shell. I get:

```
sbt:empty> libraryDependencies
[info] * org.scala-lang:scala-library:2.12.8
```

In other words, the automatic Scala library injection that sbt is doing is done via `libraryDependencies` key. So ScalaTest should be appended using `+=`.

**Comment by evbo** [comment]
@eed3si9n Are you saying that because I'm not appending the automatically injected scala library is being excluded? If that's the case then why does the following successfully compile?:
```
libraryDependencies := Seq(
  "org.scalatest" %% "scalatest" % Dependencies.scalaTestVersion,
  "org.scalatest" %% "scalatest" % Dependencies.scalaTestVersion % Test,
)
```

Edit: oh, maybe because scalatest includes the scala library transistively? Therefore without `Test` scope I'm once again ensuring scala libary is included?

also, [the docs](https://www.scala-sbt.org/0.13/docs/Library-Dependencies.html) only say: 
>In rare cases you might find reasons to use := with libraryDependencies as well.

So maybe it should say something close to: "... Like when you need to override automatically included dependencies, such as the scala libary..."
