### ISSUE TITLE
connectInput in run only echoes input when `run` is invoked from the SBT shell

### ISSUE THREAD

**Issue by retronym** [sbt/sbt#460]
... and not when `sbt run` is invoked from the command line.

Sample project:

https://gist.github.com/raw/2688462/bedb0e06bb448f4e0bd46214adb41067115e48d0/Archive.zip

No echo:

```
scala ~/code/wisp sbt run
Detected sbt version 0.11.3
Using /Users/jason/.sbt/0.11.3 as sbt dir, -sbt-dir to override.
[info] Loading project definition from /Users/jason/code/wisp/project
[info] Set current project to Wisp (in build file:/Users/jason/code/wisp/)
[info] Running wisp.Main 
[info] Welcome to Wisp!
[info] ~> 1
[info] <function2>
[info] 1
```

Stdin is echoed.

```
scala ~/code/wisp sbt
Detected sbt version 0.11.3
Starting sbt: invoke with -help for other options
Using /Users/jason/.sbt/0.11.3 as sbt dir, -sbt-dir to override.
[info] Loading project definition from /Users/jason/code/wisp/project
[info] Set current project to Wisp (in build file:/Users/jason/code/wisp/)
> run
[info] Running wisp.Main 
[info] Welcome to Wisp!
1 + 1
[info] ~> 1
```

**Comment by espringe** [comment]
The same bug occurs in an absolute minimal project too:

https://github.com/espringe/wisp/tree/297c617c00bb5823e8e218b8327c7229fbb1e83e/

Although, in the minimal case -- backspace is also broken, while with your fork/connect-input example, it does. [I'm not sure if that's a different issue, or intentional]

**Comment by vigdorchik** [comment]
I think this might be related:
https://issues.scala-lang.org/browse/SI-3442
In REPL the input from readLine() is not echoed.
In sbt shell, however, jline explicitly modifies terminal settings with stty, that leads to echoing.

**Comment by harrah** [comment]
@vigdorchik yes, we do `disableEcho(); try jline.readLine()  finally enableEcho()`, but that should only be when reading from the prompt.  I'm not sure why echo is being disabled when not using the interactive prompt.

**Comment by vigdorchik** [comment]
@harrah my point is that the input is not echoed, unless enableEcho() is explicitly called. After reading from the prompt, the echo is enabled, which leads to the above behaviour.

**Comment by harrah** [comment]
What I meant was that if you run the program using `java`, echo is enabled from the start.  So, sbt must be doing something to disable it, but I don't know where.
