### ISSUE TITLE
--addPluginSbtFile applies only to meta build if project/project/*.sbt is present

### ISSUE THREAD

**Issue by ches** [sbt/sbt#4600]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## problem

This is very similar to #4375, the additional element is the meta build.

It appears that the `--addPluginSbtFile` feature from #4211 applies the added plugin to the meta build instead of to the proper build if there are `.sbt` files in `project/project`—is that intentional?

Here's a practical use case where this arises and the interaction is not very desirable: I commonly install sbt-coursier in `project/project/plugins.sbt` so that Coursier resolves sbt plugin dependencies. When I do this, it's breaking the IntelliJ Scala plugin's sbt shell integration mechanism as in [SCL-12430](https://youtrack.jetbrains.com/issue/SCL-12430).

## steps

```
$ mkdir demo && cd demo
$ mkdir -p project/project
$ echo 'sbt.version = 1.2.8' > project/build.properties
$ echo 'addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.1.0-M13")' > project/project/plugins.sbt
$ echo addSbtCoursier > project/plugins.sbt
```

Assume the contents of `/tmp/idea.sbt` are what IntelliJ generates when running the IDE's sbt shell just as #4375:

```scala
scala.collection.Seq(
resolvers += Resolver.file("intellij-scala-plugin", file(raw"/Users/cmartin/Library/Application Support/IdeaIC2019.1/Scala/repo"))(Resolver.ivyStylePatterns),
addSbtPlugin("org.jetbrains" % "sbt-structure-extractor" % "2018.2.1+4-88400d3f"),
addSbtPlugin("org.jetbrains" % "sbt-idea-shell" % "2018.3")
)
```

```
$ sbt --addPluginSbtFile=/tmp/idea.sbt idea-shell
[info] Loading settings for project global-plugins from metals.sbt,plugins.sbt ...
[info] Loading settings for project global-plugins from idea.sbt ...
[info] Loading global plugins from /Users/cmartin/.sbt/1.0/plugins
[info] Updating ProjectRef(uri("file:/Users/cmartin/.sbt/1.0/plugins/"), "global-plugins")...
[info] Done updating.
[error] Not a valid command: idea-shell (similar: shell, oldshell)
[error] Not a valid project ID: idea-shell
[error] Expected ':'
[error] Not a valid key: idea-shell
[error] idea-shell
[error]           ^
```

_(Snipped some irrelevant output because `sbt -warn` does not output log levels **above** warn like error, it outputs **only** warn level messages, and `sbt -error` in the above case outputs nothing! Is that a bug?)_

Upon inspection, the `idea-shell` key isn't available because it's "caught" by the meta build:

```
$ sbt --addPluginSbtFile=/tmp/idea.sbt
sbt:demo> plugins
In file:/Users/cmartin/src/demo/
        sbt.plugins.IvyPlugin: enabled in demo
        sbt.plugins.JvmPlugin: enabled in demo
        sbt.plugins.CorePlugin: enabled in demo
        sbt.ScriptedPlugin
        sbt.plugins.SbtPlugin
        sbt.plugins.JUnitXmlReportPlugin: enabled in demo
        sbt.plugins.Giter8TemplatePlugin: enabled in demo
        coursier.sbtcoursiershared.SbtCoursierShared: enabled in demo
        coursier.sbtcoursier.CoursierPlugin: enabled in demo

sbt:demo> reload plugins

sbt:project> plugins
In file:/Users/cmartin/src/demo/project/
        sbt.plugins.IvyPlugin: enabled in project
        sbt.plugins.JvmPlugin: enabled in project
        sbt.plugins.CorePlugin: enabled in project
        sbt.ScriptedPlugin
        sbt.plugins.SbtPlugin
        sbt.plugins.JUnitXmlReportPlugin: enabled in project
        sbt.plugins.Giter8TemplatePlugin: enabled in project
        org.jetbrains.sbt.StructurePlugin: enabled in project
        org.jetbrains.sbt.IdeaShellPlugin: enabled in project
        coursier.sbtcoursier.CoursierPlugin: enabled in project
        coursier.sbtcoursiershared.SbtCoursierShared: enabled in project
```

## expectation

`--addPluginSbtFile` applies to the proper build, as more likely desired behavior than the meta build.

**Comment by ches** [comment]
/cc @jastice @sugakandrey @unkarjedy

This might also be a cause of [SCL-15160](https://youtrack.jetbrains.com/issue/SCL-15160) for users who are using meta build plugins.

**Comment by eed3si9n** [comment]
@ches Thanks for a detailed bug report. This sounds like a bug.
