### ISSUE TITLE
~compile ignore source file changes in certain conditions.

### ISSUE THREAD

**Issue by todesking** [sbt/sbt#4603]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps

1. Make 2 project `foo` and `foo-bar`
  * `foo/build.sbt`: Empty
  * `foo-bar/build.sbt`: `val foo = RootProject("../foo")` and `val main = (project in file(".")).dependsOn(foo)`.
2. Run `sbt ~compile` in project `foo-bar`.
3. Edit file in `foo-bar/src/main/scala/A.scala` and save it.

Complete project here: https://github.com/todesking/bugreport-sbt

## problem

sbt still waiting file changes.

## expectation

sbt re-run compile task.

## notes

sbt version: 1.2.8

I also tried `val foo = project in file("foo")`(where `foo` is symbolic link to `../foo`).
Even in this case , source file changes are ignored.

It depends on directory name. If I rename project directory `foo-bar` to `bar-foo`, source file changes are properly watched and re-run compile task.

**Comment by eatkins** [comment]
@todesking are you using osx? It looks like this might be a bug in the osx file events api.

**Comment by eatkins** [comment]
Wow. Yeah, I found a workaround, but it's a pretty bizarre bug.

**Comment by eatkins** [comment]
The problem seems to be that the file events api doesn't work when you have multiple directories in the same path with the same prefix, i.e. `foo` and `foo-bar`. The workaround is to just register the parent directory with the os but drop all events for the parent directory which we don't actually care about.

**Comment by todesking** [comment]
Thanks!
Yes, I use osx 10.14
