### ISSUE TITLE
"model contains x documentable templates"

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4607]
## steps

`publishLocal`, or anything that involves `doc`

## problem

doc task prints stuff without using the reporter.

```
model contains 5 documentable templatese
```

## expectation

Don't output it.

## notes

Scala is using `println`.

https://github.com/scala/scala/blob/v2.12.8/src/scaladoc/scala/tools/nsc/doc/DocFactory.scala#L90-L91

```scala
        if (!settings.scaladocQuietRun)
          println("model contains " + modelFactory.templatesCount + " documentable templates")
```

We can try to move the cursor position so we are more println resistant.
Then again, we should probably turn on `settings.scaladocQuietRun` too.

**Comment by eatkins** [comment]
Crazy idea but I wonder if we can change System.out to wrote println through the console logger using `System.setOut`. That might be a terrible idea.

**Comment by eed3si9n** [comment]
https://github.com/scala/scala/pull/8442 is merged, so I am going to close this one out.
