### ISSUE TITLE
[Feature Request] Configurable binary compatibility policy to make eviction warnings more meaningful

### ISSUE THREAD

**Issue by jatcwang** [sbt/sbt#4613]
Different types of dependencies have different policy when it comes to indicating a binary incompatibility.

Desire: To be warned (and only warned) of evictions which may cause binary compatibility errors

* Traditionally in Scala ecosystem, minor version bump indicates binary incompatibility (Scalaz, Scalacheck)
* Libraries like cats and many newer libraries uses major version to indicate binary incompat
* A major version bump in Java dependencies normally means both binary and source incompatibility

From what I can gather, currently SBT will warn about evictions when minor or major version is different. However these warnings are false positives for a lot of the Scala or Java libraries because of their versioning policy.

## Idea: 

Some way to add a dependency versioning policy for dependencies, either at the user side or in pom.xml.

This means that when I get an eviction warning it will be an actual problem I need to address (i.e. should fail CI). It is also safer than `dependencyOverrides`, which will happily hide binary compatibility issues when you upgrade/add libraries that now depend on a binary incompat transitive dependency.

This may be related/combined with the feature request to [specify abiVersion](https://github.com/sbt/sbt/issues/3562)

Happy to take a stab at this but would love to get some ideas on how to approach this first.

**Comment by eed3si9n** [comment]
I think it is a duplicate of #3562

**Comment by jatcwang** [comment]
Seems like it is. Closing!
