### ISSUE TITLE
Cannot set sbt version from command line

### ISSUE THREAD

**Issue by mwisnicki** [sbt/sbt#4619]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps

```
mkdir test
cd test

D:\Users\user\test>sbt sbtVersion
[warn] No sbt.version set in project/build.properties, base directory: D:\Users\User\test
[info] Loading settings from idea.sbt ...
[info] Loading global plugins from D:\Users\User\.sbt\1.0\plugins
[info] Set current project to test (in build file:/D:/Users/User/test/)
[info] 1.1.1

D:\Users\User\test>sbt -Dsbt.version=1.2.1 sbtVersion
```

## problem
```
Error during sbt execution: sbt version cannot be empty (omit declaration to use the default)
```

## expectation
```
1.2.1
```

## notes

sbt version: 1.1.1

**Comment by eed3si9n** [comment]
@mwisnicki Thanks for the report. It works for me on macOS, but I wonder if this is something specific to the batch script.

**Comment by eed3si9n** [comment]
Actually could you try double quoting? 

    > sbt "-Dsbt.version=1.2.1" sbtVersion

Windows treats `=` as whitespace iirc.

**Comment by mwisnicki** [comment]
@eed3si9n wow, thanks that was it!
