### ISSUE TITLE
externalHooks-related issues

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4624]
## steps

1.3.0-RC1.

## problem

<s>1. The key `externalHooks` is not an intuitive name for sbt. In the context of sbt, "external" typically refers to libraryDependencies as opposed to other subprojects.
2. It's a function that accepts CompileOptions.</s>
3. Composability issue pointed out by @smarter  in https://github.com/sbt/sbt/commit/25e97f99f588d1ddc9bbd114740bfb25c2a955c6#r32293747.

> zinc's ExternalHooks are extremely tricky to use, I'm not sure what the current semantics are (it's changed a few times and it's confusing as hell) but I think this might overwrite existing externalhooks set in a plugin or by the user, I'm thinking in particular of the scala-js sbt plugin (https://github.com/scala-js/scala-js/blob/0ff1fbe3f7a003482c3b785b6a374202f44f47c1/sbt-plugin/src/main/scala-sbt-1.0/org/scalajs/sbtplugin/SBTCompat.scala#L57) and the dotty sbt plugin (https://github.com/lampepfl/dotty/blob/58b8aaa59eae3c05807b318b60148f13bacbe610/sbt-dotty/src/dotty/tools/sbtplugin/DottyPlugin.scala#L130)

## expectation

<s>
Idea 1-A:
Rename to `compileHooks`, use `compileOptions.value`, and type to `Option[ExternalHooks]`?

Compose with existing hooks. ScalaJS for example does:

```scala
    val newExternalHooks =
      incOptions.externalHooks.withExternalClassFileManager(sjsirFileManager)
    incOptions.withExternalHooks(newExternalHooks)
```
</s>
Idea 1-B:
A better solution might be to have a global Boolean setting `reuseFileLookup` (name subject to change), and push the change to `incOptions` task.

## notes

1. `sbt.internal.ExternalHooks` is concerned about lookup.
2. Dotty and ScalaJS are concerned about fileManager.

**Comment by smarter** [comment]
> Dotty and ScalaJS are concerned about fileManager.

Also note that the filemanager stuff by itself is basically impossible to use correctly, see https://github.com/sbt/zinc/issues/579

**Comment by eed3si9n** [comment]
Added idea 1-B, which is to change the implementation of `incOptions` task.
That way we are not competing with the plugins.

**Comment by eed3si9n** [comment]
I'm guessing that the issue remains for RC-1

https://github.com/sbt/sbt/blob/v1.3.0-RC1/main/src/main/scala/sbt/Defaults.scala#L611-L616

```scala
    compileIncSetup := {
      val base = compileIncSetupTask.value
      val incOptions =
        base.incrementalCompilerOptions.withExternalHooks(ExternalHooks.default.value)
      base.withIncrementalCompilerOptions(incOptions)
    },
```

https://github.com/sbt/sbt/blob/v1.3.0-RC1/main/src/main/scala/sbt/Defaults.scala#L501

```scala
      incOptions := IncOptions.of(),
```

**Comment by eatkins** [comment]
Oh, I think that should be relatively straightforward to fix.
