### ISSUE TITLE
sbt main may not work for alternative launchers

### ISSUE THREAD

**Issue by eatkins** [sbt/sbt#4628]
- [ ] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

In https://github.com/sbt/sbt/pull/4601/commits/73cfd7c8bdd484b49ff6695ef006f5f7ba995c0b I modified the classloader passed in by the launcher to change the hierarchy so that the sbt testing interface jar is above the scala provider. I made some assumptions about the classloader that is passed in by the launcher that wouldn't necessarily be valid if an alternative launcher is used. It would make probably sense to fallback to using the input classloader to xMain if it does not match the exact classloader provided by the normal launcher.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/4668
