### ISSUE TITLE
SSLHandshakeException when using Gigahorse Http Client to download dependencies requiring SSL Cert

### ISSUE THREAD

**Issue by LukeDeighton** [sbt/sbt#4629]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps
Problem exists in all SBT 1.x but works in 0.13.x.

Add resolver / lib dependency to a private artifactory server which requires a custom SSL Certificate. 

Update SBT_OPTS to include your SSL settings to be used for SSL Handshake with private repo:
```
-Djavax.net.ssl.keyStore=/path/to/cert.p12
-Djavax.net.ssl.keyStorePassword=<password>
-Djavax.net.ssl.keyStoreType=PKCS12
-Djavax.net.ssl.trustStore=/path/to/truststore
-Djavax.net.ssl.trustStorePassword=<password>
```

## problem

SBT fails to resolve the dependency throwing an exception (I've used underscores ___ to hide the name of the private repo, but it should be possible to reproduce with any non standard SSL cert)

```
[error] sbt.librarymanagement.ResolveException: unresolved dependency: ___ Artifactory: unable to get resource for ___: res=___.pom: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:238)
[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
[error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
```

## expectation
Should be able to resolve and download the dependency.

## notes

Disabling Gigahorse via SBT setting fixes the issue:
```
updateOptions := updateOptions.value.withGigahorse(false)
```

Seems like Gigahorse doesn't honour SSL settings.

sbt version: 1.2.8 (although problem exists on all 1.x)

**Comment by eed3si9n** [comment]
@LukeDeighton Thanks for the report.
Potentially related https://github.com/square/okhttp/issues/1711#issuecomment-194092912.

**Comment by tilmanginzel** [comment]
Hi, I just want to confirm that we have faced the same issue when resolving dependencies from a repository requiring a client certificate and disabling Gigahorse resolves it for now. 👍

Are there any major drawbacks in disabling Gigahorse? I have not found a possibility to use the default SSL context in the underlying okhttp client or at least adhere to the jvm system properties.

**Comment by eed3si9n** [comment]
Closing this since sbt 1.3.x now uses Coursier.
Let me know if this is still relevant.
