### ISSUE TITLE
scripted requires publishAll as opposed to publishLocalBinAll

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4636]
## steps

Run `scripted` on sbt/sbt.

## problem

It starts publishing Scaladocs.

## expectation

 It would be good to reduce the `doc` call as much as possible.

## notes

In https://github.com/sbt/sbt/commit/0b33c195efa861d2ec83de284dbab4a56fda15e6, @dwijnand says "For some reason scripted requires src/doc jars of sbt, so switch back to using `publishAll` rather than `publishLocalBinAll`. :("

I was looking into this again, and the resolution actually does fail looking for docs. However, if I set `useCoursier` to `false` in Defaults.scala `scripted actions/all` did seem to pass.

**Comment by eatkins** [comment]
Fixed by https://github.com/sbt/sbt/pull/5367.
