### ISSUE TITLE
sbt/librarymanagement fails to resolve with coursier

### ISSUE THREAD

**Issue by eatkins** [sbt/sbt#4637]
I tried to open the library management project with a  local version of sbt that uses the coursier version of sbt and project resolution fails to resolve `org.boris:pecoff4j:0.0.2.1`. I have no idea where that dependency is coming from because it doesn't show up in the dependency graph when I load the project using an older version of sbt and run dependencyBrowseGraph using https://github.com/jrudolph/sbt-dependency-graph.

**Comment by eed3si9n** [comment]
This is an odd one. If I comment out `addSbtPlugin("com.lightbend"  % "sbt-whitesource" % "0.1.9")` and its settings, the error goes away. Given https://mvnrepository.com/artifact/org.whitesource/pecoff4j, it's likely a case of transitive dependency mixup of sbt-whitesource, specifically wss-agent-hash-calculator that is prior to 2.5.7 is attempted to be resolved. This [commit](https://github.com/whitesource/agents/commit/322de017f39abb86093c0564f6d2b0e65ad55984) changes from `org.boris` to `org.whitesource`.

Coursier CLI is able to resolve `org.whitesource:wss-agent-report:2.7.9`

```
$ coursier resolve -t org.whitesource:wss-agent-report:2.7.9
  Result:
└─ org.whitesource:wss-agent-report:2.7.9
   ├─ com.google.code.gson:gson:2.2.2
   ├─ commons-io:commons-io:2.4
   ├─ org.apache.velocity:velocity:1.7
   │  ├─ commons-collections:commons-collections:3.2.1
   │  └─ commons-lang:commons-lang:2.4 -> 2.6
   ├─ org.whitesource:wss-agent-api:2.7.9
   │  ├─ commons-lang:commons-lang:2.6
   │  └─ org.whitesource:wss-agent-via-api:2.7.9
   ├─ org.whitesource:wss-agent-hash-calculator:2.7.9
   │  ├─ commons-codec:commons-codec:1.10
   │  ├─ commons-io:commons-io:2.4
   │  ├─ commons-lang:commons-lang:2.6
   │  ├─ net.java.dev.jna:jna-platform:4.1.0
   │  │  └─ net.java.dev.jna:jna:4.1.0
   │  ├─ org.mozilla:rhino:1.7.7.2
   │  ├─ org.whitesource:pecoff4j:0.0.2.1
   │  └─ org.whitesource:wss-agent-api:2.7.9
   │     ├─ commons-lang:commons-lang:2.6
   │     └─ org.whitesource:wss-agent-via-api:2.7.9
   └─ org.whitesource:wss-agent-utils:2.7.9
      ├─ com.google.code.gson:gson:2.2.2
      ├─ commons-codec:commons-codec:1.10
      └─ org.whitesource:wss-agent-api:2.7.9
         ├─ commons-lang:commons-lang:2.6
         └─ org.whitesource:wss-agent-via-api:2.7.9
```

**Comment by eed3si9n** [comment]
FWIW I can reproduce this by putting `addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.1.0-M14-1")` in `project/project/plugins.sbt` using sbt 1.2.8 as well.

**Comment by eed3si9n** [comment]
Actually looking at it closer, sbt/librarymanagement seems to be using a really old version of sbt-whitesource compared to sbt/sbt, so the failure actually is legitimate I think.
