### ISSUE TITLE
val ** should be behind import

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4651]
## steps

https://github.com/sbt/sbt/issues/4648 pointed out that

```scala
base ** ("*" + org + "*") ** ("*" + name + "*")
```

is a legal PathFinder expression, so we'd need to support this in Glob API as well.

## problem

Glob API introduces `**` as value, so in the following expression `**` appears twice but with different meanings:

```scala
base ** ("*" + org + "*") / ** / ("*" + name + "*")
```

## expectation

`val **` should be an opt-in for build.sbt.
See also https://github.com/sbt/io/pull/212#discussion_r242022770

**Comment by eatkins** [comment]
I am planning to remove the PathFinder <-> Glob conversions entirely. It's too difficult to entirely preserve semantics. To use a glob it will be necessary to call `.toGlob` on the file or use the Glob.apply methods.

**Comment by eatkins** [comment]
Also opt-in makes `**` a second class citizen because it can't really be used to build a glob in an interactive session. No one wants to write `set watchTriggers += baseDirectory.toValue.toGlob / sbt.nio.file.** / "*.txt"`.

**Comment by eed3si9n** [comment]
You could write

```scala
sbt> set watchTriggers += baseDirectory.toValue.toGlob / "**" / "*.txt"
```
and not lose much IMO

**Comment by eed3si9n** [comment]
Closing this for now since #4664 removed automatic lifting of path into a Glob.
