### ISSUE TITLE
Coursier doesn't download sources by default

### ISSUE THREAD

**Issue by eatkins** [sbt/sbt#4660]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps
Clone the sbt repo and start up sbt

## problem
Coursier downloads the library dependency jars but not the source dependency jars

## expectation

Coursier downloads the source dependency jars

## notes
The lack of source jars breaks intellij go to source.

sbt version: 1.3.0-M3

**Comment by eed3si9n** [comment]
`update` task using Ivy doesn't download source either, I think, but `updateClassifier` might.
Maybe `updateClassifier` some other part the interface IntelliJ plugin was using changed?

/cc @jastice

**Comment by jastice** [comment]
Sbt will not download source jars by default, only with the updateClassifiers task. This is invoked by a sbt refresh from IntelliJ, but only if "download library sources" option is checked in IntelliJ sbt options (default). Is this broken with coursier?

**Comment by eatkins** [comment]
Whoops. I think the issue may have been that I started a new sbt project because of other issues I was having and I didn't check the download sbt sources box.
