### ISSUE TITLE
Provide a way for plugins to handle changes in underlying keys types (e.g. javacOptions)

### ISSUE THREAD

**Issue by pfn** [sbt/sbt#467]
In sbt 0.12 javacOptions is now a Task[Seq[String]] where in 0.11 it was a Setting[Seq[String]]

plugins and build scripts that used javacOptions before have no way of gracefully handling both versions.

something like this would be nice to be able to do, but won't pass the type checker:

``` scala
javacOptions <<= (sbtVersion, ...) {
  (version,...) => if (version startsWith("0.11")) normal stuff else
    (various-sbt-keys) map { ... }
}
```

**Comment by harrah** [comment]
A more likely solution in the 0.12 timeframe is a way to automatically select different .sbt files based on the Scala version.  Changing things at compilation time like in that example can't really happen without macros and probably untyped macros at that.

**Comment by pfn** [comment]
Can this be resolved with reflection?  (java reflection or otherwise?)
