### ISSUE TITLE
[1.3.0-RC1] java.lang.OutOfMemoryError: Metaspace

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4686]
_Originally posted by @limansky in https://github.com/sbt/sbt/issues/4681#issuecomment-493146377_

## steps

1. get beanpuree https://github.com/limansky/beanpuree
2. set sbt version to 1.3.0-RC1
3. sbt
4. +test

## problem

I'm not sure if I should submit another ticket, but when I tried to compile BeanPuree with sbt 1.3.0-RC1 I've got OutOfMemoryError:
```
java.lang.OutOfMemoryError: Metaspace
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
```

## expectation

Everything works fine with 1.2.8.

## workaround

Set `-XX:MaxMetaspaceSize=1024M` or whatever you're currently using for `-Xmx` in `JAVA_OPTS` environment variable.

**Comment by eed3si9n** [comment]
I wasn't able to reproduce this either locally or on Travis - https://travis-ci.org/limansky/beanpuree/builds/533456390

**Comment by eatkins** [comment]
I was able to reproduce on my machine.

**Comment by eed3si9n** [comment]
Travis uses 

```
java
-Xms2048M
-Xmx2048M
-Xss6M
-XX:MaxPermSize=512M
```

could you post your mem settings?

**Comment by eatkins** [comment]
```
ethanatkins@Ethans-MacBook-ProZ:~/work/oss/sbt/community/beanpuree$ sbt -Dsbt.version=1.3.0-RC1 -v
[process_args] java_version = '11'
[copyRt] java9_rt = '/Users/ethanatkins/.sbt/0.13/java9-rt-ext-oracle_corporation_11_0_2/rt.jar'
# Executing command line:
java
-Xms1024m
-Xmx1024m
-XX:ReservedCodeCacheSize=128m
-XX:MaxMetaspaceSize=256m
-XX:+UseParallelGC
-XX:+HeapDumpOnOutOfMemoryError
-Dscala.ext.dirs=/Users/ethanatkins/.sbt/0.13/java9-rt-ext-oracle_corporation_11_0_2
-jar
/usr/local/Cellar/sbt/1.2.8/libexec/bin/sbt-launch.jar
-Dsbt.version=1.3.0-RC1
```

**Comment by eatkins** [comment]
I usually have "-XX:MaxMetaspaceSize=512m" added to my SBT_OPTS, but I disabled that for testing.

**Comment by eed3si9n** [comment]
ok. I can reproduce this too when I unset my JAVA_OPTS and SBT_OPTS.

```
$ SBT_OPTS="-Xms1024M -Xmx1024M -Xss2M" sbt -v
```

also works, so in addition to sbt 1.3.0 using too much metaspace, maybe the fact that `-XX:MaxMetaspaceSize` is specified at all by the script is a problem?

**Comment by eatkins** [comment]
I did notice that if I ran java -jar sbt-launch.jar directly, I didn't have the issue.

**Comment by eatkins** [comment]
That being said, I looked at a heap dump and the eclipse memory analyzer did report a leak.

**Comment by mr-git** [comment]
I got this error locally too, but when I started SBT like `sbt -mem 4096` it didn't fail any more.
The cause of this issue is sensitive to SBT configuration.

**Comment by eed3si9n** [comment]
@eatkins and I discussed this at length in sbt meeting today.
There are various small workarounds we can try to reduce the pressure on Metaspace (a space in the native heap of Java Virtual Machine where class metadata is stored), but we agreed that we need to _remove_ the use of `-XX:MaxMetaspaceSize` from launchers and launch scripts since it aggravates the problem by putting an arbitrary limit.

The problem in the short term might be that build users will continue to run `sbt` script from sbt 1.2.8 etc. In those cases, a workaround might be to specify `-XX:MaxMetaspaceSize` equaling the total heap.

**Comment by limansky** [comment]
So, it is not a leak, but it just requires more memory than 1.2.8?

**Comment by eatkins** [comment]
Not necessarily. Metaspace is a native memory region in the jvm. We have very little insight into what is occupying memory in there or if that memory is even used. I have detected very little difference in process heap, virtual or resident memory utilization comparing 1.2.8 and 1.3.0. In spite of that, 1.3.0 will require a much higher value for MaxMetaspaceSize or it will crash. We do not fully understand why that is, but the jvm default for MaxMetaspaceSize is unlimited so we decided it made sense to revert to the default.

**Comment by eed3si9n** [comment]
One potential explanation is that sbt 1.3.0 loads more number of classes for whatever reasons, and require higher water mark. This could be because we introduced lm-coursier with shaded third-party libraries, different ClassLoader mechanisms, etc. But that pressure on Metaspace might be a temporary thing during task execution (this is consistent with it getting triggered by `+test`), and it may or may not matter in the grand scheme of things.

**Comment by eed3si9n** [comment]
Removed MaxMetaspaceSize in https://github.com/sbt/sbt-launcher-package/pull/268

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/4729
