### ISSUE TITLE
[1.3.0-RC1] sbt-header doesn't work

### ISSUE THREAD

**Issue by tpolecat** [sbt/sbt#4687]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps

Clone [this minimal project](https://github.com/tpolecat/sbt-header-bug). If you do `sbt headerCreate` nothing happens, but if you change `sbt.version` to `1.2.8` and try again it will create a header for `foo.scala`.

## problem

Something has changed in 1.3 that makes sbt-header stop working. This may be due to sbt-header making bad assumptions, or may be a bug in sbt.

## expectation

It should work as in sbt 1.2

## notes

sbt version: *1.3.0-RC1*

It wasn't entirely clear where to file this bug but I thought I would start here.

/cc @hseeberger

**Comment by eed3si9n** [comment]
@tpolecat Thanks for the report. There's been changes around how we list source files, so I suspect it's on sbt's end.

**Comment by regadas** [comment]
~@eed3si9n I think the culprit might be `sbt.Defaults.collectFiles`~ Sorry I missed the fact that there's already something in the works.
