### ISSUE TITLE
[1.3.0-RC1] sbt-dependency-graph doesn't work

### ISSUE THREAD

**Issue by anilkumarmyla** [sbt/sbt#4688]
With 1.3.0-RC1, sbt-dependency-graph plugin stops working, since this release claims that plugins are expected to work throughout the 1.x series, I'm not sure if I should file this issue here or in sbt-dependency-graph repo, let me know

```
$ sbt dependencyList
...
...
[error] java.lang.NoSuchMethodError: sbt.internal.LibraryManagement$.cachedUpdate(Lsbt/librarymanagement/DependencyResolution;Lsbt/librarymanagement/ModuleDescriptor;Lsbt/util/CacheStoreFactory;Ljava/lang/String;Lsbt/librarymanagement/UpdateConfiguration;Lscala/Function1;ZZZLsbt/librarymanagement/UnresolvedWarningConfiguration;Lsbt/librarymanagement/EvictionWarningOptions;ZLsbt/internal/librarymanagement/CompatibilityWarningOptions;Lsbt/util/Logger;)Lsbt/librarymanagement/UpdateReport;
[error] 	at sbt.dependencygraph.DependencyGraphSbtCompat$.$anonfun$updateTask$5(DependencyGraphSbtCompat.scala:61)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:270)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:279)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:270)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:835)
[error] (ivyReport / update) java.lang.NoSuchMethodError: sbt.internal.LibraryManagement$.cachedUpdate(Lsbt/librarymanagement/DependencyResolution;Lsbt/librarymanagement/ModuleDescriptor;Lsbt/util/CacheStoreFactory;Ljava/lang/String;Lsbt/librarymanagement/UpdateConfiguration;Lscala/Function1;ZZZLsbt/librarymanagement/UnresolvedWarningConfiguration;Lsbt/librarymanagement/EvictionWarningOptions;ZLsbt/internal/librarymanagement/CompatibilityWarningOptions;Lsbt/util/Logger;)Lsbt/librarymanagement/UpdateReport;
```

**Comment by eatkins** [comment]
Objects that are marked internal are not meant to be used by directly by plugins so the binary compatibility guarantee doesn't hold in this case. It should be a straightforward fix to the plugin however.

**Comment by eed3si9n** [comment]
This issue was reported as https://github.com/sbt/sbt/issues/4688. (About to transfer)
Nope. I can't it's at https://github.com/jrudolph/sbt-dependency-graph.

**Comment by eed3si9n** [comment]
Closing this as, sorry-it's-internal.

**Comment by anilkumarmyla** [comment]
thanks, filed an issue on the plugin github repo

**Comment by dwijnand** [comment]
While I agree with the sorry-it's-internal-API response, I think sbt-dependency-graph is a major plugin in the ecosystem (it's my longest living global plugin - and, as such, I'd also lobby for it to be folded into sbt, but that's for another issue).

But with coursier coming in sbt 1.3 is `coursierDependencyTree` available instead?

**Comment by anilkumarmyla** [comment]
`coursierDependencyTree` is available only if you include the sbt-coursier plugin. Our usage is mainly the flattened list, maybe implement `coursierDependencyList` as a replacement for dependencyList of sbt-dependency-graph

**Comment by eed3si9n** [comment]
See also https://github.com/sbt/sbt/issues/4706

**Comment by lilac** [comment]
Dependency tree is an essential part of any production level build tool. It's sad that the developers of sbt do not support this feature, and obstructing others from fixing this as a plugin. It's a shame to the community.

**Comment by eatkins** [comment]
@lilac I don't understand what you mean about sbt maintainers obstructing a fix. There are two open issues related to it #4706 and #4707. From what I can tell, sbt-dependency-graph works fine with coursier disabled in sbt 1.3.3 so this isn't even entirely an sbt bug. It is due to an impedance mismatch between two complicated pieces of software: sbt and coursier.

Before you claim that it's "sad that the developers of sbt do not support this feature," consider that sbt has very few core contributors, none of whom work on sbt full time. Clearly this feature is not of critical importance to the sbt contributors or it would have been fixed prior to the sbt 1.3.0 release. If, however, it is of critical importance to the sbt community, then it is likely that someone from the sbt community needs to step up and fix it. I hope that happens sooner than later but I'm reasonably confident that it will get fixed at some point.

**Comment by eed3si9n** [comment]
For what it's worth, we had Lightbend internal Code Retreat as part of meeting in Athens last week, and both Johannes (author of the plugin) and I were looking into the lm-coursier to figure out where the information is getting lost in translation. I think the reverse dependencies are there but for some reason subprojects, or Projects in Coursier term are getting skipped.

**Comment by dwijnand** [comment]
@eed3si9n could you lay out the steps/problem/expectation/notes for this?  It might help a contributor pick it up.

**Comment by eed3si9n** [comment]
@dwijnand https://github.com/sbt/sbt/issues/4706 captures the core issue I think.

**Comment by eed3si9n** [comment]
Here's my PR to sbt-coursier - https://github.com/coursier/sbt-coursier/pull/156
