### ISSUE TITLE
ClassLoaderLayeringStrategy IlegalArgumentException when extending test configuration

### ISSUE THREAD

**Issue by davidhoyt** [sbt/sbt#4693]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps
Derive a new configuration from an existing one. e.g.:

```scala
import sbt._

object SmokeTestPlugin extends AutoPlugin {
  object autoImport {
    lazy val SmokeTest = Configuration.of("SmokeTest", "smoke") extend (Runtime, Test)
  }

  import autoImport._

  override val trigger = allRequirements

  lazy val smokeSettings: Seq[Setting[_]] = inConfig(SmokeTest)(Defaults.testSettings)

  override def projectConfigurations: Seq[Configuration] = Seq(SmokeTest)

  override lazy val projectSettings: Seq[Setting[_]] = smokeSettings
}
```

And then use it:

```scala
lazy val foo = Project
```

## problem
The following is output:
```
java.lang.IllegalArgumentException: Layering strategy TestDependencies is not valid for the classloader in Scope(Select(ProjectRef(file:/path/to/project/,foo)), Select(ConfigKey(smoke)), Zero, Zero). Valid options are: ClassLoaderLayeringStrategy.{ Flat, ScalaInstance, RuntimeDependencies }
```

## expectation
A new configuration extending `Test` should just work. In this case `extend (Runtime, Test)` is important because any other variant and IntelliJ will not recognize the new configuration's source directories.

## notes

sbt version: 1.3.0-RC1

**Comment by eed3si9n** [comment]
@davidhoyt Thanks for the report!

**Comment by davidhoyt** [comment]
And thanks to you and all the contributors for all the hard work that's gone into this release!

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/4729
