### ISSUE TITLE
Prompt continually being cleared

### ISSUE THREAD

**Issue by japgolly** [sbt/sbt#4694]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps

In the SBT shell, run `test:compile` interleaved with ctrl-L (to clear console) a few times.

## problem

Eventually SBT gets into a state where it keep clearing the current line.
I'll see the `root> ` prompt appear and then disappear. If I type anything I briefly see the character appear and then disappear again.

## expectation

The SBT prompt, and chars I type should remain on the screen.

## notes

sbt version: 1.3.0-RC1

**Comment by eed3si9n** [comment]
@japgolly Thanks for the report. Could you share more on your environment to help reproduce it on our end plz? For instance which os and terminal program are you using?

**Comment by japgolly** [comment]
Ah yes, of course :)

I'm on a mac - osx 10.12.6, just using the built in Terminal app.
I'm also using zsh 5.7.1 (x86_64-apple-darwin16.7.0)
Java is:

```
> java -version                                                        
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
```

If there's anything else useful that I didn't think of, let me know.

**Comment by eed3si9n** [comment]
On Terminal, I tend to use `⌘K` (Clear to Start). It seems like there's `^⌘L` (Clear Screen), which might be close to what you're talking about. Either way, I wasn't able to get to the problem state.

**Comment by japgolly** [comment]
Not it's not a terminal command, ctrl-L is a readline or jline supported
command, isn't it? Are you saying you tried ctrl-L and it didn't work? If
so maybe it's shell settings.

Also I'm not exactly sure if the screen clearing is relevant cos I saw a
Reddit comment that somebody else is experiencing this same issue. We
should probably reach out and ask them for more info too. I'd be surprised
if they were also clearing the screen like I was :)

**Comment by japgolly** [comment]
Ah I just visited Reddit to ask the other user if they could add more info to this ticket but I see you've already been there :)

**Comment by eed3si9n** [comment]
The super shell implementation has been updated since 1.3.0-RC1. Does this problem with Ctrl-L still  happen with 1.3.2?

**Comment by japgolly** [comment]
I've been using 1.3.2 for about a week now and I haven't seen this issue pop up again. I guess it's fixed :) Thanks! I'll close now
