### ISSUE TITLE
[1.3.0-RC1] Ivy repository for 0.13.x releases not available by default when cross-compiling a plugin

### ISSUE THREAD

**Issue by bjaglin** [sbt/sbt#4698]
## KO with 1.3.0-RC1

```
$ sbt new sbt/sbt-autoplugin.g8
...
sbtVersion [maven(org.scala-sbt,sbt,stable)]: 1.3.0-RC1
...
```

```
sbt:sbt-foo-bar> set crossSbtVersions := Vector("0.13.16")
sbt:sbt-foo-bar> ^compile
...
[error] sbt.librarymanagement.ResolveException: Error downloading org.scala-sbt:sbt:0.13.16
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.16/sbt-0.13.16.pom
[error]   not found: /home/bjaglin/.ivy2/local/org.scala-sbt/sbt/0.13.16/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt/sbt/0.13.16/ivys/ivy.xml

```

## OK with 1.2.8
```
$ sbt new sbt/sbt-autoplugin.g8
...
sbtVersion [maven(org.scala-sbt,sbt,stable)]: 1.2.8
...
```

```
sbt:sbt-foo-bar> set crossSbtVersions := Vector("0.13.16")
sbt:sbt-foo-bar> ^compile
...
[info] downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/scripted-framework/0.13.16/jars/scripted-framework.jar ...
[info] downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/scripted-sbt/0.13.16/jars/scripted-sbt.jar ...
[info] downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.16/jars/sbt-launch.jar ...
[info] 	[SUCCESSFUL ] org.scala-sbt#scripted-framework;0.13.16!scripted-framework.jar (1590ms)
[info] 	[SUCCESSFUL ] org.scala-sbt#scripted-sbt;0.13.16!scripted-sbt.jar (2617ms)
[info] 	[SUCCESSFUL ] org.scala-sbt#sbt-launch;0.13.16!sbt-launch.jar (3998ms)
```

**Comment by bjaglin** [comment]
Not sure if I am looking in the right place, but https://github.com/sbt/sbt/blob/cf932c8a13b4dee047ffd75fe31539720800a404/main/src/main/scala/sbt/internal/librarymanagement/CoursierRepositoriesTasks.scala#L22 does reference the repository where 0.13.x releases are published, but since there is a 302 redirect, maybe the Coursier behavior is not the same as ivy?

**Comment by bjaglin** [comment]
Adding
```
typesafe-releases: https://repo.typesafe.com/typesafe/ivy-releases/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
```
to a [custom repository configuration](https://www.scala-sbt.org/1.x/docs/Proxy-Repositories.html#sbt+Configuration) fixes the regression.

**Comment by eed3si9n** [comment]
@bjaglin Thanks for the report!

I am guessing you could also add a resolver like this:

```scala
resolvers += Resolver.typesafeIvyRepo("releases")
```

If so I might just update the g8 template and docs.

**Comment by bjaglin** [comment]
Thanks for the very prompt reply!

Indeed, my bad. It does make sense to add it, I just never thought about explicitly adding it with previous versions.

Regarding the actions we could take - https://github.com/sbt/website/blob/5524bb3e66a67fd73555910519abff51115fe3cd/src/reference/02-DetailTopics/05-Plugins-and-Best-Practices/07-Cross-Build-Plugins.md would need a big overhaul anyway and the amount of project cross-building to 0.13.x is probably small, so maybe having this issue and its solution indexed by search engines is enough to close?
