### ISSUE TITLE
Transitive dependency resolution oddity: jerkson -> jackson-mapper-asl

### ISSUE THREAD

**Issue by leifwickland** [sbt/sbt#47]
(This could well be due to user error or some factor outside of sbt's control.  I'm new enough to this realm I'm unsure, so I figured I'd mention it just in case.)

I created a buid.sbt that looks like:

``` scala
organization := "Example"

name := "example"

scalaVersion := "2.9.0-1"

resolvers += Resolver.url("Jerkson (Jackson JSON for Scala)", url("http://repo.codahale.com"))

libraryDependencies ++= Seq(
  "com.codahale" % "jerkson_2.9.0-1" % "0.3.1"
)
```

and a jerkson.scala that looks like:

``` scala

import com.codahale.jerkson.Json._

object jerkson extends App {
  println(generate(List(1, 2, 3)))
}
```

When I "sbt compile" that project, I see error messages that seem to indicate that Jerkson can't find the Jackson dependencies it needs. The (Jerkson POM)[http://repo.codahale.com/com/codahale/jerkson_2.9.0-1/0.3.1/jerkson_2.9.0-1-0.3.1.pom] points at (jackson-mapper-asl)[http://repo1.maven.org/maven2/org/codehaus/jackson/jackson-mapper-asl/1.7.7/jackson-mapper-asl-1.7.7.pom].  If I explicitly add a dependency on jackson-mapper-asl, my code will compile.  

``` scala
  "org.codehaus.jackson" % "jackson-mapper-asl" % "1.7.7"
```

Is this indicative of a problem in the (Jerkson POM)[http://repo.codahale.com/com/codahale/jerkson_2.9.0-1/0.3.1/jerkson_2.9.0-1-0.3.1.pom]?  Am I don't something wrong?  Is sbt somehow not handling the Jerkson POM correctly?

Thanks for reading this far.  Sorry if I've wasted your time.

**Comment by harrah** [comment]
Use:
```resolvers += "Jerkson (Jackson JSON for Scala)" at "http://repo.codahale.com"

```

URL resolvers are really only needed for Ivy-style repositories.

(Questions are best asked on the mailing list because there is more visibility and it is more likely someone else can answer it quicker there.)
```
