### ISSUE TITLE
sbt 1.3 classloader layering: support more than one jar for the standard library

### ISSUE THREAD

**Issue by smarter** [sbt/sbt#4705]
Dotty's standard library is currently effectively represented by two jars: a scala-library jar compiled by Scala 2 and its own dotty-library jar. Reusing the scala-library jar from Scala 2 is what makes it possible for Dotty code to reuse Scala 2 libraries. However, sbt is not aware of this because `ScalaInstance` in zinc requires using a single File for the standard library. So far this hasn't been too much of a problem (see https://github.com/lampepfl/dotty/blob/fb6667b0fbdf1e2811f36d5dd2909905d55735ee/sbt-dotty/src/dotty/tools/sbtplugin/DottyPlugin.scala#L194-L228) but sbt 1.3 classloader layering logic relies on ScalaInstance, so that might end up impacting users in one way or another.

**Comment by eed3si9n** [comment]
@smarter Thanks for the report!

**Comment by eatkins** [comment]
Fixed in #4729
