### ISSUE TITLE
[1.3.0-RC1] Eviction behavior changed since 1.2.x

### ISSUE THREAD

**Issue by jrudolph** [sbt/sbt#4710]
Already noted in https://github.com/sbt/sbt/issues/4706 but since it's such a big behavior change, here is a dedicated ticket for it.

build.sbt:

```
version := "0.1.0-SNAPSHOT"

scalaVersion := "2.9.1"

resolvers += "typesafe maven" at "https://repo.typesafe.com/typesafe/maven-releases/"

libraryDependencies ++= Seq(
  "com.codahale" % "jerkson_2.9.1" % "0.5.0",
  "org.codehaus.jackson" % "jackson-mapper-asl" % "1.9.10" // as another version of asl
)
```

Output of `show externalDependencyClasspath` in sbt 1.2.8:

```
[info] * Attributed(/home/johannes/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.9.1.jar)
[info] * Attributed(/home/johannes/.ivy2/cache/com.codahale/jerkson_2.9.1/jars/jerkson_2.9.1-0.5.0.jar)
[info] * Attributed(/home/johannes/.ivy2/cache/org.codehaus.jackson/jackson-core-asl/jars/jackson-core-asl-1.9.11.jar)
[info] * Attributed(/home/johannes/.ivy2/cache/org.codehaus.jackson/jackson-mapper-asl/jars/jackson-mapper-asl-1.9.11.jar)
```

Output of `show externalDependencyClasspath` in sbt 1.3.0-RC1 (note that the wrong version 1.9.10 of jackson is chosen):

```
[info] * Attributed(/home/johannes/.coursier/cache/v1/https/repo.typesafe.com/typesafe/maven-releases/com/codahale/jerkson_2.9.1/0.5.0/jerkson_2.9.1-0.5.0.jar)
[info] * Attributed(/home/johannes/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.9.1/scala-library-2.9.1.jar)
[info] * Attributed(/home/johannes/.coursier/cache/v1/https/repo1.maven.org/maven2/org/codehaus/jackson/jackson-mapper-asl/1.9.10/jackson-mapper-asl-1.9.10.jar)
[info] * Attributed(/home/johannes/.coursier/cache/v1/https/repo1.maven.org/maven2/org/codehaus/jackson/jackson-core-asl/1.9.10/jackson-core-asl-1.9.10.jar)
```

**Comment by jrudolph** [comment]
Hmm after some investigation, the resolution in 1.3.0-RC1 seems more correct than the old one because `jerkson` defines a dependency on jackson with revision `[1.9.0,2.0.0)`. It's unclear to me how version 1.9.11 came into the picture at all (maybe ivy chose the latest one based on contents of `http://repo1.maven.org/maven2/org/codehaus/jackson/jackson-core-asl/` where timestamps seem to be missing for 1.9.12 and 1.9.13). Anyway it seems to be quite an edge case. Closing for now.

**Comment by eed3si9n** [comment]
Yes. Dynamic revision (version range, SNAPSHOT, etc) on Ivy is broken since it tries to go out to Internet to grab the information rather than solve the reasonable candidate from the dependency graph.
Ref https://github.com/sbt/sbt/issues/2954 / https://github.com/sbt/sbt/pull/2959
