### ISSUE TITLE
1.3.0-RC1 regression: NoClassDefFoundError in tests

### ISSUE THREAD

**Issue by Atry** [sbt/sbt#4711]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps
``` scala
git clone https://github.com/Atry/Dsl.scala.git --branch=pr3 && cd Dsl.scala && sbt test
```

## problem

```

[info] com.thoughtworks.dsl.keywords.ContinueExample *** ABORTED ***
[info]   java.lang.NoClassDefFoundError: com/thoughtworks/dsl/Dsl$Keyword
[info]   at java.lang.ClassLoader.defineClass1(Native Method)
[info]   at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[info]   at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[info]   at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
[info]   at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
[info]   at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
[info]   at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
[info]   at java.security.AccessController.doPrivileged(Native Method)
[info]   at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[info]   ...
[info]   Cause: java.lang.ClassNotFoundException: com.thoughtworks.dsl.Dsl$Keyword
[info]   at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[info]   at java.lang.ClassLoader.defineClass1(Native Method)
[info]   at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[info]   at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[info]   at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
[info]   at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
[info]   at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
[info]   at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
[info]   ...
```

## expectation

No error

## notes

Changeset: https://github.com/Atry/Dsl.scala/commit/f83d92839af69c32f3be5092e776439623cc93ef
Error log: https://travis-ci.org/Atry/Dsl.scala/jobs/535001019

sbt version: 1.3.0-RC1

**Comment by eed3si9n** [comment]
@Atry Thanks for the report. Could you try the following and see if the test would run?

```scala
Test / classLoaderLayeringStrategy := ClassLoaderLayeringStrategy.Flat
```

**Comment by Atry** [comment]
It is still a `NoClassDefFoundError` for Scala 2.11, and becomes an `OutOfMemoryError` for Scala 2.12 and 2.13 if I add the above setting

* commit: https://github.com/Atry/Dsl.scala/commit/039a3033f1e843cd3a5a4f14cec2726797b46a4b
* build log: https://travis-ci.org/Atry/Dsl.scala/builds/535112033

**Comment by Ophirr33** [comment]
@eed3si9n I had some issues where `logback-test.xml` wasn't getting picked up with the new 1.3.0-RC1 release, but setting the `classLoaderLayeringStrategy` to flat like you suggested above fixes it. I'm curious what's different in the default behavior that files in `src/test/resources` aren't getting put into the test classpath?

**Comment by eatkins** [comment]
@Ophirr33 the default layering strategy creates multiple layers of classloaders. The src/test/resources get put in the bottom layer which makes them inaccessible to the higher layers. Theoretically ClassLoaderLayeringStrategy.ScalaLibrary should have worked for you, though there is a bug in 1.3.0-RC1 that prevents it from working if your project uses scala reflect.

**Comment by eed3si9n** [comment]
@eatkins @Ophirr33 

> The src/test/resources get put in the bottom layer which makes them inaccessible to the higher layers.

Maybe this is serious enough to split out into a new issue. https://github.com/sbt/sbt/issues/4714

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/4729
