### ISSUE TITLE
Running sbt in background will be suspended

### ISSUE THREAD

**Issue by lxohi** [sbt/sbt#4718]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps
Run ```sbt &```(with or without command, e.g. ```sbt package &```) 

## environment
**system:** Mac OS or Cent OS
**shell:** bash or zsh

## problem
The background process will be stopped and ```[2]  + suspended (tty output)  sbt``` prints out.

## expectation
sbt should run in the background.

## notes
- Many people says that suspended message is caused by stty's ```tostop``` flag, but I've already make sure that flag sets to off(```-tostop```) on my machines.
- I've tried to redirect stdout to file using ```>/dev/null 2>/dev/null```, but it was still suspended.
- I've looking through sbt source code, it seems sbt using log4j to print messages to console, but I failed to find something related with the suspension.

sbt version: [1.2.8, 0.13.15]

**Comment by eed3si9n** [comment]
This seems to work for me:

```
sbt -Djline.terminal=none < /dev/null &
```

**Comment by lxohi** [comment]
Looks like ```jline.terminal``` does the magic. And I can now write scripts with background sbt tasks. 

Thank you for the reply😋

**Comment by charpov** [comment]
This still feels hacky.  There should be a clear option (e.g., `sbt.ci` or `--batch`) that guarantees nothing will be done with the terminal.  It gets in the way in other places (e.g., using `timeout`).

**Comment by shinealex33** [comment]
sbt -Djline.terminal=none "run 9008" < /dev/null &

This gives me "p.c.s.AkkaHttpServer - Stopping server...". Much appreciated your reply.
