### ISSUE TITLE
[1.3.0-RC1] `--supershell=false` doesn't work (but `-Dsbt.supershell=false` does)

### ISSUE THREAD

**Issue by SethTisue** [sbt/sbt#4724]
issue title says it all

both forms are mentioned in the 1.3.0-RC1 release notes, but only one of them works.

**Comment by eed3si9n** [comment]
`--supershell=false` will be available when we roll out `sbt` script for 1.3.0 final.

**Comment by SethTisue** [comment]
note that `-Dsbt.supershell=false` must precede `-error`

**Comment by hrj** [comment]
@eed3si9n This still doesn't work, and doesn't have a milestone assigned to it. (Just an observation).

BTW, how can we disable this setting globally via global.sbt? I tried `SettingKey[Boolean]("supershell", "") := false` and variations thereof, but no luck.

**Comment by eed3si9n** [comment]
@hrj How are you running `sbt` (sbt-the-Bash/batch-script)? I'm on macOS, and using `sbt` from the latest Home Brew `sbt --supershell=false` works for me.

**Comment by hrj** [comment]
@eed3si9n Yes, I was using some older version of bash script + launcher on Linux. I updated to the latest one and the option seems to work fine. Thanks.

About the other question: How to disable the super-shell globally? I could modify the bash script but wondering if there is a more "official" option.

**Comment by eed3si9n** [comment]
```scala
SettingKey[Boolean]("useSuperShell", "") := false
```

might work if you don't want to define an environmental variable `SBT_OPTS`.
