### ISSUE TITLE
Transitive dependencies missing in SBT compared to Maven

### ISSUE THREAD

**Issue by Woodz** [sbt/sbt#4726]
- [X] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps
Create SBT project with
```
libraryDependencies ++= Seq(
  "org.optaplanner" % "optaplanner-benchmark" % "7.20.0.Final"
)
```
and a Maven project with
```
    <dependencies>
        <dependency>
            <groupId>org.optaplanner</groupId>
            <artifactId>optaplanner-benchmark</artifactId>
            <version>7.20.0.Final</version>
        </dependency>
    </dependencies>
```

## problem
The Maven project correctly identifies the transitive dependency on `org.drools:drools-compiler:7.20.0-Final` via `org.optaplanner:optaplanner-core:7.20.0.Final`, whereas the SBT project does not identify this transitive dependency.

## expectation
Maven and SBT projects identify the same set of transitive dependencies.

## notes
This Maven configuration includes a number of parent POMs which may be causing the issue with SBT. The files involved are:
- http://central.maven.org/maven2/org/optaplanner/optaplanner-benchmark/7.20.0.Final/optaplanner-benchmark-7.20.0.Final.pom (direct dependency containing dependency on `org.optaplanner:optaplanner-core`)
- http://central.maven.org/maven2/org/optaplanner/optaplanner-core/7.20.0.Final/optaplanner-core-7.20.0.Final.pom (transitive dependency that has dependency on `org.drools:drools-compiler`
- http://central.maven.org/maven2/org/kie/kie-parent/7.20.0.Final/kie-parent-7.20.0.Final.pom (grandparent POM via http://central.maven.org/maven2/org/optaplanner/optaplanner/7.20.0.Final/optaplanner-7.20.0.Final.pom containing version for dependencies - specifically 7.20.0.Final)

sbt version: 1.2.8

**Comment by eed3si9n** [comment]
@Woodz Thanks for the report.

I tried it with sbt 1.3.0-RC1, which uses Coursier instead of Apache Ivy, and it seems to identify drools-core-7.20.0.Final.jar.
I also needed to add `"org.freemarker" % "freemarker" % "2.3.28"` because it failed on `org.freemarker:freemarker:2.3.26.jbossorg-1`.

**Comment by Woodz** [comment]
> @Woodz Thanks for the report.
> 
> I tried it with sbt 1.3.0-RC1, which uses Coursier instead of Apache Ivy, and it seems to identify drools-core-7.20.0.Final.jar.
> I also needed to add `"org.freemarker" % "freemarker" % "2.3.28"` because it failed on `org.freemarker:freemarker:2.3.26.jbossorg-1`.

@eed3si9n the issue is identifying `drools-compiler`, not `drools-core` - `drools-core` is picked up in both SBT and Maven.
