### ISSUE TITLE
SBT S3Resolver

### ISSUE THREAD

**Issue by andy-britz** [sbt/sbt#473]
Would be great if sbt could support S3 as a repository. This would reduce downloads on ec2 machines during builds and is a great way to share a lightweight repo between teams.

**Comment by vigdorchik** [comment]
Would having a true S3 support provide much benefit over S3 over http? Note that I'm not an expert in the field, and would be happy to be enlightened.

**Comment by andy-britz** [comment]
Was thinking something similar to https://github.com/jcaddel/maven-s3-wagon. This would literally let us replace the repo with an S3 bucket.

**Comment by harrah** [comment]
This is a good candidate for being developed and distributed outside of sbt and possibly integrated later.
