### ISSUE TITLE
Ensure coursier is ready for sbt 1.3.0

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#4738]
Tracking https://github.com/coursier/coursier/issues/1174 in the 1.3.0 milestone so it doesn't get forgotten about.

**Comment by eed3si9n** [comment]
Thanks. I've been meaning to open this issue.

**Comment by eed3si9n** [comment]
Blessed sbt-coursier is now building - 
https://travis-ci.org/coursier/sbt-coursier/builds/538858452
