### ISSUE TITLE
After removing managed dependency, files that import (but don't use) classes from that dependency are not incrementally recompiled

### ISSUE THREAD

**Issue by stephenjudkins** [sbt/sbt#474]
Steps to reproduce:
- Include managed dependency
- Write class that includes an "import" statement that imports a class from that dependency, but does not actually use any of those classes
- Compile the project
- Remove managed dependency
- Restart SBT or reload SBT config
- Compile the project

_Expected_:
We should see a compilation error 

_Actual_: 
There is no compilation error unless `sbt clean` is run or that Scala source file is changed

**Comment by vigdorchik** [comment]
This is a duplicate of 213.

**Comment by stephenjudkins** [comment]
Thanks
