### ISSUE TITLE
Sbt uses too much cpu on idle

### ISSUE THREAD

**Issue by eatkins** [sbt/sbt#4746]
In 1.3.0-RC1, sbt is using roughly 10% of a cpu when idling. In older versions, it was more like 2% of a cpu. This is because I reduced a number of timeouts that are causing sbt to frequently wake up to poll queues. These can be reworked to poll from a concurrent blocking queue which should both lower latency and restore the old cpu utilization characteristics.

**Comment by eed3si9n** [comment]
Ref https://github.com/sbt/sbt/pull/4544/commits/fcd24ba7cd7b26c04d750ec70b026e5d5d654356

So should we change it back to `Thread.sleep(50)`? 0.05s should be below human perception and easy enough for machines.

**Comment by eatkins** [comment]
Fixed in #4750
