### ISSUE TITLE
Tilde (~, aka watch) can't take a command?

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#4756]
## steps

`~about`

## problem

```
> ~about
[error] java.lang.IllegalStateException: Error attempting to extract scope from about: Not a valid project ID: about (similar: sbtRoot)
[error] Expected ':'
[error] Not a valid key: about
[error] about
[error]      ^.
[error] 	at sbt.internal.Continuous$.parseCommand(Continuous.scala:386)
[error] 	at sbt.internal.Continuous$.$anonfun$getAllConfigs$1(Continuous.scala:394)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
[error] 	at scala.collection.immutable.List.map(List.scala:298)
[error] 	at sbt.internal.Continuous$.getAllConfigs(Continuous.scala:394)
[error] 	at sbt.internal.Continuous$.$anonfun$runToTermination$7(Continuous.scala:339)
[error] 	at sbt.std.Streams.use(Streams.scala:104)
[error] 	at sbt.std.Streams.use$(Streams.scala:100)
[error] 	at sbt.std.Streams$$anon$1.use(Streams.scala:117)
[error] 	at sbt.internal.Continuous$.$anonfun$runToTermination$6(Continuous.scala:335)
[error] 	at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:374)
[error] 	at sbt.internal.Continuous$.$anonfun$runToTermination$5(Continuous.scala:335)
[error] 	at sbt.internal.Continuous$.setup(Continuous.scala:269)
[error] 	at sbt.internal.Continuous$.$anonfun$runToTermination$1(Continuous.scala:334)
[error] 	at sbt.internal.Continuous$.withCharBufferedStdIn(Continuous.scala:308)
[error] 	at sbt.internal.Continuous$.runToTermination(Continuous.scala:317)
[error] 	at sbt.internal.Continuous$.$anonfun$continuous$1(Continuous.scala:108)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:144)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:139)
[error] 	at sbt.Command$.process(Command.scala:183)
[error] 	at sbt.MainLoop$.$anonfun$processCommand$1(MainLoop.scala:150)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:162)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:150)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:138)
[error] 	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:269)
[error] 	at sbt.State$StateOpsImpl$.process$extension(State.scala:273)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:138)
```

## expectation

The command I choose (here `about`) runs on every file change.

## notes

sbt version: 1.3.0-RC1

**Comment by eatkins** [comment]
I am of the opinion that watch shouldn't work with commands because commands can modify state and they also have no file inputs associated with them.

**Comment by dwijnand** [comment]
It also can't handle aliases.  For example with a `alias cl = clean` in `.sbtrc`:

```
> cl
[success] Total time: 1 s, completed 31-May-2019 16:04:10
> ~cl
[error] java.lang.IllegalStateException: Error attempting to extract scope from cl: Not a valid project ID: cl
[error] Expected ':'
[error] Not a valid key: cl
[error] cl
[error]   ^.
```

What is it about modifying state that should make commands inelligible for usage with watch?  Can we reduce the banning to a specific, smaller set of conniving commands?

Also, in my eyes, commands using anything (e.g. tasks) that has file inputs associated to them, use those file inputs transitively.

**Comment by eatkins** [comment]
Yes, there was a different case about aliases that was already resolved: https://github.com/sbt/sbt/issues/4695.

**Comment by eatkins** [comment]
There is no introspection capability in a command that allows one to determine what tasks it may run. The watch system uses the state extensively to determine numerous properties of the watch. If the state changes, we need to update the watch, which means having to add special logic for partitioning the watch commands into commands and tasks and resetting everything between each run if there is a command present.

Since you mentioned aliases, I am guessing that a use case for watching a command is to define a command that aggregates a number of tasks. That use case can be handled by a custom task. Is there  a different use case you have in mind? I have given this a lot of thought in the past and concluded that the semantics of watching commands were not well defined and the maintenance cost / implementation complexity (it's already quite complex) was not worth it .

**Comment by eatkins** [comment]
As a side note, I think that InputTask makes Command somewhat redundant. In fact, in my imaginary sbt 2.0, I'd probably consolidate Task, InputTask and Command into a single Task abstraction.

**Comment by dwijnand** [comment]
If you can detail what's off-limits, then I think it's acceptable to say that using watch with commands that touch anything in that off-limits is undefined and unsupported.

Here's a few commands/aliases that I use with watch:
* `~ ;clean ;compile`, so the `;` command (multi-command, iirc?)
* `~ ;clear ;compile`, so the `clear` alias, which is globally defined as `alias clear = eval "\u001B[2J\u001B[0\u003B0H"`
* `~ +compile` so the `+`/cross command

**Comment by eatkins** [comment]
Hmm. Cross builds did escape me and do seem important. Just to be clear, I assume you mean `alias clear = eval println("\u001B[2J\u001B[0\u003B0H")`.

**Comment by eed3si9n** [comment]
Would it be possible to support `~ <non-act-command>` by falling back to sbt 1.2-like watch-everything mode?

**Comment by dwijnand** [comment]
> Just to be clear, I assume you mean `alias clear = eval println("\u001B[2J\u001B[0\u003B0H")`.

No, I wasn't using the println.  It works without.

**Comment by eatkins** [comment]
Ha, I guess that's because the evaluating compiler prints the result.
