### ISSUE TITLE
Globs.nameFilterToRelativeGlob is partial

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#4757]
## steps

* Add & setup https://github.com/sbt/sbt-boilerplate
* Compile

## problem

```
[error] scala.MatchError: spray.boilerplate.Compat$$anon$1@5f16c775 (of class spray.boilerplate.Compat$$anon$1)
[error] 	at sbt.internal.nio.Globs$.nameFilterToRelativeGlob(Globs.scala:74)
```

## expectation

No exception thrown.

## notes
sbt version: 1.3.0-RC1

This is the `NameFilter` that Globs is failing to handle:

https://github.com/sbt/sbt-boilerplate/blob/v0.6.1/src/main/scala-sbt-1.0/Compat.scala#L24-L26

**Comment by eatkins** [comment]
Thanks for the report. I'll fix.

**Comment by eatkins** [comment]
Fixed in https://github.com/sbt/io/pull/242.
