### ISSUE TITLE
Class.forName can't find classes in sbt-1.3.0-RC1 

### ISSUE THREAD

**Issue by xerial** [sbt/sbt#4760]
## steps

I'm still trying to find a reproduction, but basically, a problem happens when using ~Spark 2.4.x with~ Scala 2.11, sbt-1.3.0-RC1.

## problem

- Call a method in a dependent library that uses `Class.forName("(class name)")` -> causes java.lang.ClassNotFoundException
- Call `Class.forName("(class name)")` works without any problem.

I guess some method (e.g., `ClassLoader.getClassLoader(caller)`) used in Class.forName has an issue in sbt-1.3.0-RC1's layered class loader:
```java
   @CallerSensitive
    public static Class<?> forName(String className)
                throws ClassNotFoundException {
        Class<?> caller = Reflection.getCallerClass();
        return forName0(className, true, ClassLoader.getClassLoader(caller), caller);
    }
```
## expectation
- There has been no problem until sbt 1.2.8

## notes

- It seems a workaround is using `Class.forName(name, true, Thread.currentThread().getContextClassLoader())` instead of `Class.forName(name)`
- Spark is unrelated (fixed the description)

sbt version: *1.3.0-RC1*

**Comment by eed3si9n** [comment]
@xerial Thanks the report.

> It seems a workaround is using Class.forName(name, true, Thread.currentThread().getContextClassLoader()) instead of Class.forName(name)

I think @eatkins is working on a workaround along the same lines, but built-in to our layered ClassLoader so you won't have to do it.

**Comment by eatkins** [comment]
See #4769.
