### ISSUE TITLE
Rename the "develop" branch to "master"

### ISSUE THREAD

**Issue by smarter** [sbt/sbt#4763]
The branch named `master` is used in the same way that everyone else uses `master`, can it be renamed to the standard ? It would be one less hurdle when trying to contribute to sbt.

**Comment by eatkins** [comment]
I am not in favor of this change. For one, I think master, while standard, is vague and doesn't clearly express what the branch represents. Also, in the US there is some historical baggage around the word master that makes me prefer to avoid using it as a noun without context.

**Comment by eed3si9n** [comment]
sbt follows the GitFlow branch model - https://datasift.github.io/gitflow/IntroducingGitFlow.html

Many guides would say "master branch should be ready to release any time", but in reality most of them are not. Besides, when would the branch name come up? Like when you are sending a PR?

**Comment by smarter** [comment]
> Many guides would say "master branch should be ready to release any time", but in reality most of them are not. 

Yeah that's a bit extreme, I would limit things to "the CI should always be green on master".

> Besides, when would the branch name come up? 

Every time I do a git rebase of a branch in one of the sbt repo, I get confused for a bit until I remember that I need to rebase on origin/develop and not origin/master. I also have a bunch of aliases in my gitconfig that assume that there's a branch called master on origin (like `ckob = checkout origin/master -b`).

Anyway, feel free to close this issue if you like having develop more.

**Comment by dwijnand** [comment]
I'm like smarter, it's annoying to have to remember its develop in these parts (I hit it in sbt/zinc) rather than master.

But we'd probably not want to intentionally rename to "master" now.

**Comment by smarter** [comment]
I've actually recently realized that `origin/HEAD` points to the default branch, it's not updated if the defautl branch changes after you clone the repo but you can do `git remote set-head origin develop` to set `origin/HEAD` to point to `origin/develop` for example (it's a completely local change so you can set it to whatever you want), which is great since I just had to change my aliases to use `origin/HEAD` instead of `origin/master`
