### ISSUE TITLE
Running sbt with the '-java-home' option fails

### ISSUE THREAD

**Issue by dubaut** [sbt/sbt#4768]
## steps
sbt version: *1.2.8*

## problem
As suggested by @eed3si9n in the (closed) issue 4766 I tried to run sbt with the `-java-home` option but it failed with the following error:

```
[error] Expected symbol
[error] Not a valid command: -
[error] Expected end of input.
[error] Expected '--'
[error] Expected 'debug'
[error] Expected 'info'
[error] Expected 'warn'
[error] Expected 'error'
[error] Expected 'addPluginSbtFile'
[error] -java-home
[error]  ^
```

## expectation
sbt compiles against the specified JDK.

## notes

- Windows 10 Professional

**Comment by eed3si9n** [comment]
Thanks for the report. It looks like a missing feature in Windows batch file.
Would you consider sending us a PR to fix this?
https://github.com/sbt/sbt-launcher-package/blob/master/src/universal/bin/sbt.bat

**Comment by dubaut** [comment]
I'd love to but I am afraid I do not know CMD scripting.

**Comment by virpara** [comment]
@eed3si9n I'd like to send PR for this fix. I should submit PR against the repository sbt/sbt-launcher-package, right ?

**Comment by eed3si9n** [comment]
@virpara Yes, please.

**Comment by gladiac** [comment]
@dubaut I already implemented the missing functionality in my fix-sbt-bat branch. Could you please check it out at https://github.com/gladiac1337/sbt-launcher-package/tree/fix-sbt-bat and test it? I already created PR sbt/sbt-launcher-package#272 .
