### ISSUE TITLE
80+ Gigs occupied by sbt output

### ISSUE THREAD

**Issue by mihaisoloi** [sbt/sbt#4772]
## steps
sbt version: *1.2.8*

## problem

When running an `sbt` incremental compile on a project and forgetting it overnight, sometimes you end up with an output file of a couple of gigs in size. It mostly contains this line:
```
[debug] [com.swoval.watchservice] No source filter found for /home/msoloi/Workspace/generic-project-name/target/streams/$global/$global/$global/$global/streams/out
```

The project is using play-framework 2.7.2 and the silencer 1.3.3. lib with the following scalac flag:
`"-P:silencer:pathFilters=target/scala-2\\.\\d+/(?:routes|twirl)/.*" // silence all warnings on autogenerated files`

Right before the error started happening these are the log outputs:
```
[debug] PatternFilter(.*\Q.scala.\E.*) && !HiddenFileFilter
[debug] ExactPath("/home/msoloi/Workspace/generic-project-name/test/assets")
[debug] ExactPath("/home/msoloi/Workspace/generic-project-name/test/public")
```

## expectation

The size of the output should be capped to a couple of KB.

## notes

Due to the huge size of this file, I'm forced to delete it, as it's impeding my work.

**Comment by eed3si9n** [comment]
@mihaisoloi Thanks for the report. Could you provide a bit more details on how sbt team can reproduce the issue on our computers? Do you set it to `~compile` and wait 12h?

**Comment by mihaisoloi** [comment]
@eed3si9n when starting the sbt server I usually start it with `sbt -jvm-debug 5005` and yes after that I `~compile` and I leave it running, only checking it when I need to. When everything is compiled and my tests pass I can `run` the play app and debug it if necessary without restarting the `sbt` server. 

So, 12h is usually the length of time it takes to get to this size, but it happens very rarely anyway, so I'm not sure I can tell you how to reproduce it.

**Comment by eatkins** [comment]
That log message is coming from [CloseWatch](https://github.com/swoval/swoval/blob/master/plugin/README.md). You probably don't need the close watch plugin in sbt 1.2.8 and you definitely won't want it for sbt >= 1.3.0. That being said, feel free to open an issue in the swoval repository.

**Comment by mihaisoloi** [comment]
@eatkins your recommendation is good enough for me, i.e. that it can be dropped for 1.2.8 and planning to switch to 1.3.0 as soon as it becomes generally available. Thanks.
