### ISSUE TITLE
1.3.0-RC2 NoClassDefError at shutdown hooks

### ISSUE THREAD

**Issue by xerial** [sbt/sbt#4794]
## steps
sbt version: 1.3.0-RC2

- Some user libraries cannot be found while running JVM shutdown hooks: https://travis-ci.org/wvlet/airframe/jobs/543922170#L2706
- Corresponding code (in my case):
  - Creating a custom shutdown hook: https://github.com/wvlet/airframe/blob/ea3d023f9534e3a67b09947d0c844c11dc9381f6/airframe-log/jvm/src/main/scala/wvlet/log/AirframeLogManager.scala#L31
  - Registering it to a shutdown hook: https://github.com/wvlet/airframe/blob/a6460cda5b2ca660da0955527df62a356dd9c92f/airframe/.jvm/src/main/scala/wvlet/airframe/AddShutdownHook.scala#L29

How to reproduce:
- Checkout wvlet/airframe
```
$ ./sbt 
abt:airframe-root> airframeJVM/test
...
sbt:airframe-root> exit
[info] shutting down server
Exception in thread "shutdownHook35" java.lang.NoClassDefFoundError: wvlet/log/AirframeLogManager$
	at wvlet.airframe.AddShutdownHook$.$anonfun$beforeStart$1(AddShutdownHook.scala:34)
	at scala.sys.ShutdownHookThread$$anon$1.run(ShutdownHookThread.scala:37)
Caused by: java.lang.ClassNotFoundException: wvlet.log.AirframeLogManager$
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
```

This happens only when the shutdown hook starts running. 

## problem
It looks like some classes in libraryDependencies cannot be found while running scala.sys.ShutdownHookThread. 

- It seems the layered class loader was already detached when a shutdown hook registered inside the application started. I understand this behavior, and technically speaking this might not be a bug.
- In this case, the expected application lifecycle (= JVM lifecycle) and sbt's lifecycle (running many applications using different class loaders) don't match. 
- What should be a workaround? Stop registering shutdown hooks if the application is using sbt? 

## expectation
- The same behavior with 1.3.0-RC1

## notes
- I've tested all different class loader strategies in https://www.lightbend.com/blog/sbt-1.3.0-release, and the result was the same.

**Comment by eatkins** [comment]
This is expected: https://www.scala-sbt.org/1.x/docs/Running-Project-Code.html. Shutdown hooks are fundamentally at odds with running in an in process jvm. I’d recommend reworking the code to remove and invoke any shutdown hooks before exiting. To restore sbt < 1.3.0 behavior, however, try running with ‘-Dsbt.classloader.close=false’.

**Comment by xerial** [comment]
Thanks for the explanation. 

Using `fork in Test` option works in general if testing shutdown hooks is necessary.

**Comment by xerial** [comment]
ok. I've found another issue when using sbt-1.3.0-RC2 + openjdk11 + JMXRegistry. I'll report it in another ticket.
