### ISSUE TITLE
ThisBuild / useSuperShell doesn't work

### ISSUE THREAD

**Issue by clhodapp** [sbt/sbt#4800]
## steps
sbt version: 1.3.0-RC2
1) Define a minimal project (just `project/build.properties` with `sbt.version=1.3.0-RC2` & `build.sbt`)
2) Set `ThisBuild / useSuperShell := false` in `build.sbt`
3) Start sbt

## problem
Supershell is active

## expectation
Supershell is not active

**Comment by taig** [comment]
Ran into the same issue and want to add that it works fine with `-Dsbt.supershell=false` (didn't get to test `--supershell=false`)

**Comment by eed3si9n** [comment]
I've been meaning to take a look at this one.
