### ISSUE TITLE
clean return success when failing to delete locked file configured in cleanFiles setting

### ISSUE THREAD

**Issue by neontorrent** [sbt/sbt#4812]
## steps
sbt version: 1.4.3

## problem

When a file in cleanFiles is locked by other process, `clean` does not delete the file successfully, but returns `[success]` status.

## expectation

Task should return `[error] Failed` status and give proper error message.

## notes

```
sbt:project> show cleanFiles
[info] * C:\Data\dev\project\target\scala-2.12
[info] * C:\Data\dev\project\target\streams
[info] * C:\Data\dev\project\test.db

sbt:project> clean
[success] Total time: 1 s, completed 14-Jun-2019 1:18:12 PM

> ls -al
-rw-r--r-- 1 User 40960 Jun 14 12:04 test.db
```

After killing the locking process and doing another `clean`, the file is gone.

**Comment by eed3si9n** [comment]
```
> help cleanFiles
The files to recursively delete during a clean.
```

`cleanFile` lists the files to clean.

**Comment by neontorrent** [comment]
@eed3si9n I mixed up `clean` with `cleanFiles`. cleanFiles is just the setting. I updated the title and description. Please reopen as the issue is still existing.

**Comment by eed3si9n** [comment]
See https://github.com/sbt/io/pull/235/commits/fa0d0eed5dbaf9c188e6bf4762fd1ca61291b95e.

Windows locks the used files, so if we actually threw exceptions I think sbt basically doesn't function well on Windows with `run`, `test` etc.

**Comment by neontorrent** [comment]
@eed3si9n In the commit the exception is silently swallowed. sbt should print some debug or error message for those exceptions. Otherwise user will assume the cleanup was done and all files were deleted successfully. This can impact consequential tests if previous one was not cleaned properly. 

I can open a PR and fix that. Just a few logging statements.

**Comment by eed3si9n** [comment]
@texasbruce 

> I can open a PR and fix that. Just a few logging statements.

Sounds good. https://github.com/sbt/io/blob/develop/io/src/main/scala/sbt/io/IO.scala
