### ISSUE TITLE
[1.3.0-RC2] Missing assets with binaries for download

### ISSUE THREAD

**Issue by plokhotnyuk** [sbt/sbt#4815]
```
andriy@notebook:~$ curl https://github.com/sbt/sbt/releases/download/v1.3.0-RC2/sbt-1.3.0-RC2.zip
Not Found
```

**Comment by eatkins** [comment]
@eed3si9n this also is true for 1.3.0-RC3. It would be great to get these up.

**Comment by eed3si9n** [comment]
There's manual work involved to create the installers, so I don't always create them for RCs.
