### ISSUE TITLE
[1.3.0-RC2] updateClassifiers not working

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4816]
## steps

```scala
// ThisBuild / useCoursier := false
ThisBuild / scalaVersion := "2.12.8"

lazy val root = (project in file("."))
  .settings(
    libraryDependencies += "com.typesafe.akka" %% "akka-actor" % "2.5.22",
    TaskKey[Unit]("checkSources") := (updateClassifiers map checkSources).value,
    TaskKey[Unit]("checkBinaries") := (update map checkBinaries).value
  )

def getSources(report: UpdateReport)  = report.matching(artifactFilter(`classifier` = "sources") )
def checkSources(report: UpdateReport): Unit = {
  val srcs = getSources(report).map(_.getName)
  if(srcs.isEmpty)
    sys.error(s"No sources retrieved\n\n$report")
  else if (srcs.size != 8 || !srcs.exists(_ == "akka-actor_2.12-2.5.22-sources.jar")) {
    // scala-library-2.12.8-sources.jar
    // config-1.3.3-sources.jar
    // akka-actor_2.12-2.5.22-sources.jar
    // scala-java8-compat_2.12-0.8.0-sources.jar
    // scala-xml_2.12-1.0.6-sources.jar
    // scala-compiler-2.12.8-sources.jar
    // scala-reflect-2.12.8-sources.jar
    // jline-2.14.6-sources.jar 
    sys.error("Incorrect sources retrieved:\n\t" + srcs.mkString("\n\t"))
  } else ()
}

def checkBinaries(report: UpdateReport): Unit = {
  val srcs = getSources(report)
  if(srcs.nonEmpty) sys.error("Sources retrieved:\n\t" + srcs.mkString("\n\t"))
  else ()
}
```

## problem

It was reported that using RC-2 `updateClassifiers` doesn't resolve dependency sources.

## expectation

It resolves and downloads sources.

**Comment by mushtaq** [comment]
@eed3si9n yes, it is not working. 

Our current workaround is adding `addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.1.0-M13-4")` in `plugins.sbt` and `metaplugins.sbt`

**Comment by eed3si9n** [comment]
sbt-coursier seems to reimplement `updateClassifiers`:

- https://github.com/coursier/sbt-coursier/blob/9173406bb399879508aa481fed16efda72f55820/modules/sbt-coursier/src/main/scala/coursier/sbtcoursier/CoursierPlugin.scala#L156-L159
- https://github.com/coursier/sbt-coursier/blob/bed2d2dd28056558404e153247a37fa28809f15f/modules/sbt-coursier/src/main/scala/coursier/sbtcoursier/UpdateTasks.scala#L14

whereas LM API implements `updateClassifiers` based on `lmEngine.update` - 
https://github.com/sbt/librarymanagement/blob/39bd17f33933d4c6b93a018bee6cbec9343a7f2e/core/src/main/scala/sbt/librarymanagement/DependencyResolution.scala#L158-L163

If the output of the two are not matching up, that would likely suggest there's a discrepancy in the implementation of `update`. In the short term, I'll look into trying to make the behavior closer to sbt-coursier, but this might come up later on.

/cc @alexarchambault

**Comment by alexarchambault** [comment]
@eed3si9n You might want to look at sbt-lm-coursier, where the way it's implemented should be [somewhat clearer](https://github.com/coursier/sbt-coursier/blob/9173406bb399879508aa481fed16efda72f55820/modules/sbt-lm-coursier/src/main/scala/coursier/sbtlmcoursier/LmCoursierPlugin.scala#L46-L56) (it basically tweaks the configuration a little for `updateClassifiers`).

It does the same for `updateSbtClassifiers` right after it.

**Comment by eed3si9n** [comment]
@alexarchambault Thanks for the hint. Hopefully this works out - https://github.com/sbt/sbt/pull/4821
