### ISSUE TITLE
Nightlies are not working

### ISSUE THREAD

**Issue by eatkins** [sbt/sbt#4820]
Try running, `sbt -Dsbt.version=1.3.0-bin-20190617T192002` and it will fail to resolve util-interface. I think this is because this is a pure java library and deployment is skipped by the validator.

**Comment by dwijnand** [comment]
Perhaps it's one step more indirect: it's being skipped because of its `crossScalaVersions`.

**Comment by eed3si9n** [comment]
Should be fixed now.
