### ISSUE TITLE
Unable to Ctrl-C out of 'run' in a Play app

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#4822]
## steps
sbt version: 1.3.0-RC2

* Take https://github.com/playframework/play-samples/tree/f6519a15096fd7eb49f4f19ae444faade936b479/play-scala-compile-di-example
* Update to sbt 1.3.0-RC2
* Also update Play to 2.7.3
* Start `sbt`
* Execute `run`
* Visit http://localhost:9000/
* Hit `Ctrl-C`

## problem

```
[play-scala-compile-di-example] $ run

--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Enter to stop and go back to the console...)

[info] play.api.Play - Application started (Dev) (no global state)

[warn] Canceling execution...

[warn] Canceling execution...
```

## expectation

(sbt 1.2.8 behaviour)

```
[play-scala-compile-di-example] $ run
[info] Updating ...
[info] Done updating.

--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Enter to stop and go back to the console...)

[info] play.api.Play - Application started (Dev) (no global state)
[info] p.c.s.AkkaHttpServer - Stopping server...
```

## notes
It's quite possible changes are necessary in sbt-play.  But even if that's the case it would mean this would be the behaviour of _existing_ version of sbt-play using _newer_ sbt 1.3+, so we should look into this a bit.

**Comment by eed3si9n** [comment]
In https://github.com/sbt/sbt/pull/4630, I made `Global / cancelable` true by default, which I am guessing is related.

**Comment by dwijnand** [comment]
Absolutely!  Setting `Global / cancelable := true` in 1.2.8 reproduces the issue and setting `Global / cancelable := false` in 1.3.0-RC2 works around it.

But why does setting "cancelable" to `true` make it not cancel with Ctrl-C??

**Comment by eed3si9n** [comment]
I am guessing it's because with `Global / cancelable` sbt and Play are competing for Ctrl-C's attention? Play should probably turn its Ctrl-C handling off when it detects `Global / cancelable` to be true.

**Comment by dwijnand** [comment]
> I am guessing it's because with `Global / cancelable` sbt and Play are competing for Ctrl-C's attention?

We should confirm if that's true, and it's not that sbt under cancelable = true is failing to cancel Play's run.

**Comment by eed3si9n** [comment]
https://github.com/sbt/sbt/blob/v1.3.0-RC2/main/src/main/scala/sbt/EvaluateTask.scala#L458-L464

```scala
    object runningEngine extends RunningTaskEngine {
      def cancelAndShutdown(): Unit = {
        println("")
        log.warn("Canceling execution...")
        shutdown()
      }
    }
```

Because we see "Canceling execution...", likely `cancelAndShutdown()` was reached.
https://github.com/sbt/sbt/blob/v1.3.0-RC2/main/src/main/scala/sbt/EvaluateTask.scala#L427-L436

`shutdown` tries to kill the thread?

```scala
    def shutdown(): Unit = {
      // First ensure that all threads are stopped for task execution.
      shutdownThreads()
      config.progressReporter.stop()

      // Now we run the gc cleanup to force finalizers to clear out file handles (yay GC!)
      if (config.forceGarbageCollection) {
        GCUtil.forceGcWithInterval(config.minForcegcInterval, log)
      }
    }
```

Play's Ctrl-C handling is here? https://github.com/playframework/playframework/blob/2.7.3/dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayInteractionMode.scala#L62-L78. Maybe `consoleReader.readCharacter()` doesn't allow the thread to be killed? I had to let shell prompt timeout and ask on repeat so it becomes interruptible.

**Comment by eed3si9n** [comment]
- https://github.com/sbt/util/pull/48
- https://github.com/sbt/sbt/pull/4585/commits/447ab5011c01b04af063130ac91338b960bcd4b5

**Comment by eed3si9n** [comment]
I don't think there's much we can do on sbt side. Play should either turn off `Global / cancelable` or wrap the inputstream to make it interruptible.

**Comment by dwijnand** [comment]
To avoid the regression I'm thinking the `Global / cancelable` change should be reverted and postpone to some time after Play has rolled out the necessary changes.

I've been using `Global / cancelable := true` for a long time, so I'm a fan, but I don't think we should force this change in behaviour through given this regression.

**Comment by eed3si9n** [comment]
I just realized that Play documentation [Using the play commands directly](https://www.playframework.com/documentation/2.7.x/PlayConsole#Using-the-play-commands-directly) says:

> The application starts directly. When you quit the server using `Ctrl+D` or `Enter`, you will come back to your OS prompt.

If `Ctrl+C` is not even a documented behavior why are we sweating over this?

**Comment by dwijnand** [comment]
I believe it's the behaviour that users expect and rely on, even if it has not been documented.  I'll confirm this with @marcospereira.

**Comment by marcospereira** [comment]
`ctrl+d` or `enter` should stop the Play application without exiting sbt shell. `ctrl+c` should both stop the application and exit shell.

**Comment by eed3si9n** [comment]
> `ctrl+c` should both stop the application and exit shell.

I don't think that holds if `Global / cancelable` is set to true. I'd suggest some other letter for the purpose like `q`.

**Comment by marcospereira** [comment]
> I don't think that holds if `Global / cancelable` is set to true. I'd suggest some other letter for the purpose like `q`.

Hey @eed3si9n, I was describing the existing behavior for Play 2.6/2.7 in combination with sbt 1.2.x. As far as I understood, `ctrl+c` was handled by sbt instead of Play, but let's investigate further.

**Comment by eed3si9n** [comment]
You're right that sbt handles Ctrl-C both in sbt 1.2.x and sbt 1.3.0-RC2. It's just that the handling doesn't result to sbt shutting down the JVM if `Global / cancelable` is set to `true` including in sbt 1.2.x, which leaves Play's `run` hanging waiting for `consoleReader.readCharacter()` to return.

Similarly new `~` in sbt 1.3 provides a shortcut to double-quit, and I am switching from using `x` to `q` now - #4830 / #4512

**Comment by dwijnand** [comment]
So when `cancelable` is true, Ctrl-C should just cancel run.  Seeing as this doesn't work with Play, can we postpone the default change?  Once we have Play's Ctrl-C working with cancelable this change would be safer.

**Comment by henricook** [comment]
Just to chime in as a normal play user we absolutely rely on ctrl+c behaviour - the 'hard stop' is something I use frequently when enter/ctrl+d doesn't respond in time, or triggers a recompile i don't want, or doesn't properly kill off background threads like database pools (some of this last point is to do with my own applications stop/start actions)

**Comment by eed3si9n** [comment]
If we can't get a patched Play 2.7 out in time, then I'm fine with postponing this till sbt 1.4.

**Comment by eed3si9n** [comment]
Here's a PR to Play - https://github.com/playframework/playframework/pull/9420

**Comment by eed3si9n** [comment]
I'm going to close this issue.
