### ISSUE TITLE
SBT not picking up file changes on MacOS

### ISSUE THREAD

**Issue by wdanilo** [sbt/sbt#4828]
## steps
sbt version: 1.2.8

## problem
When running `~run` in sbt, after changing a file nothing happens. I was testing different editors (VS Code, Idea, Sublime) and the problem still appears.

## expectation
Sbt should watch the files for changes

**Comment by eed3si9n** [comment]
@wdanilo Thanks for the report. Could you try 1.3.0-RC2, and see if the problem still happens?
If so could you list out the reproduction steps in such a way that the team can recreate your problem on our computer?

**Comment by eatkins** [comment]
@wdanilo this issue isn't specific enough to debug. Watching files on mac does work for the majority of projects so we need more details to investigate. Closing for now, but I will re-open if you provide more information.
