### ISSUE TITLE
sbt 1.3 updateClassifiers does not resolve library sources

### ISSUE THREAD

**Issue by jastice** [sbt/sbt#4831]
## steps
sbt version: 1.3-RC2

Create any sbt projects with a library dependency. Run `updateClassifiers`

## problem

`updateClassifiers` does not resolve sources of `libraryDependencies` when using coursier.

## notes

IntelliJ expects sources to be resolved to allow source navigation by the user.

**Comment by eed3si9n** [comment]
@jastice Thanks for the report. I've already reported it https://github.com/sbt/sbt/issues/4816 and fixed it in https://github.com/sbt/sbt/pull/4821
