### ISSUE TITLE
understand --version and -v as command line options

### ISSUE THREAD

**Issue by bjornregnell** [sbt/sbt#4833]
I see many of my students just learning Linux writing again and again `sbt --version` and `sbt -v` in terminal. After experiencing some Linux regularity they get confused and somewhat disappointed that sbt does not answer to this. Only a fraction manage to google `sbtVersion` ... 

* Could sbt be made to understand --version and -v as command line option? Or does this break something else? 

Output could be same as `sbt sbtVersion` or nice to have: something less intimidating when run in a lib with no built.sbt and no project/build.properties ... Think beginner student running their first project and wanting to know if sbt is awake on their machine.

**Comment by eed3si9n** [comment]
@bjornregnell Thanks for the report.

I agree that we should improve the version reporting of `sbt` script and the mothership version.
