### ISSUE TITLE
runMain info logging strips argument quotes

### ISSUE THREAD

**Issue by er1c** [sbt/sbt#4834]
## steps
sbt version: 1.2.8

    $ sbt "project foo" 'test:runMain com.foo.App -i "foo bar"' 

Output:

    [info] Running (fork) com.foo.App -i foo bar

## problem

This is only a "logging" issue, that was leading me down a bad path when debugging some code :). The arguments are actually correct (e.g. "foo bar" is a single argument as it is passed into the application arguments.

## expectation

    [info] Running (fork) com.foo.App -i "foo bar"

**Comment by eed3si9n** [comment]
@er1c Thanks for the report!

**Comment by eed3si9n** [comment]
https://github.com/sbt/sbt/pull/4836
