### ISSUE TITLE
Publish Local SNAPSHOT Configuration Not Found

### ISSUE THREAD

**Issue by darkfrog26** [sbt/sbt#4835]
## steps
sbt version: *1.2.8*

## problem
When I publish YouI (https://github.com/outr/youi) locally and then try to use it from another project I've started getting this:
io.youi#youi-core_2.12;0.11.8-SNAPSHOT: configuration not found in io.youi#youi-core_2.12;0.11.8-SNAPSHOT: 'master'. It was required from io.youi#youi-stream_2.12;0.11.8-SNAPSHOT compile

**Comment by darkfrog26** [comment]
Actually, I just confirmed this is even happening when I `publishLocal` with non-snapshots

**Comment by eed3si9n** [comment]
Thanks for the report. This is a duplicate of #2874.
