### ISSUE TITLE
Wait for a release of Play 2.7.x and 2.6.x before releasing 1.3.0

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#4837]
See https://github.com/sbt/sbt/issues/4823 for more info.

**Comment by eed3si9n** [comment]
Given that #4823 seems to be Coursier issue that's now addressed, do we still need to block on Play?

**Comment by dwijnand** [comment]
Absolutely.  Sorry I hadn't connected the dots (and then I got behind on GH notifications.)
