### ISSUE TITLE
sbt emits warnings about typesafe-ivy-releases

### ISSUE THREAD

**Issue by eatkins** [sbt/sbt#4839]
If you build off the latest nightly and run sbt, you will see these warnings:
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-ivy-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
This seems to be fallout from https://github.com/sbt/sbt/pull/4829.

**Comment by marekzebrowski** [comment]
I experience that a lot in 1.3.0-RC2
