### ISSUE TITLE
Improving sbt 'run' final message

### ISSUE THREAD

**Issue by ssabat** [sbt/sbt#4843]
Please use https://discuss.lightbend.com/c/tooling including a specific user story instead of posting them to the issue tracker. This is done.

I am using sbt after long time. I tried hello-scala project. It took some setup  on my behalf.
In the end, I see following output:

sbt:hello-scala> run
[info] Updating ...
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.jar ...
[info] downloading https://repo1.maven.org/maven2/org/scalatest/scalatest_2.12/3.0.5/scalatest_2.12-3.0.5.jar ...
[info] downloading https://repo1.maven.org/maven2/org/scalactic/scalactic_2.12/3.0.5/scalactic_2.12-3.0.5.jar ...
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8.jar ...
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.8/scala-compiler-2.12.8.jar ...
[info]  [SUCCESSFUL ] org.scalactic#scalactic_2.12;3.0.5!scalactic_2.12.jar(bundle) (1468ms)
[info]  [SUCCESSFUL ] org.scala-lang#scala-reflect;2.12.8!scala-reflect.jar (3784ms)
[info]  [SUCCESSFUL ] org.scala-lang#scala-library;2.12.8!scala-library.jar (4420ms)
[info]  [SUCCESSFUL ] org.scalatest#scalatest_2.12;3.0.5!scalatest_2.12.jar(bundle) (4442ms)
[info]  [SUCCESSFUL ] org.scala-lang#scala-compiler;2.12.8!scala-compiler.jar (5220ms)
[info] Done updating.
[info] Compiling 1 Scala source to /mnt/chromeos/removable/SD Card/Android/data/hello-scala/target/scala-2.12/classes ...
[info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.8. Compiling...
[info]   Compilation completed in 96.157s.
[info] Done compiling.
[info] Packaging /mnt/chromeos/removable/SD Card/Android/data/hello-scala/target/scala-2.12/hello-scala_2.12-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[info] Running example.Hello 
hello
[success] Total time: 134 s, completed Jun 30, 2019 9:55:58 AM

 Please look at how hello is hidden above.
My ask is we should separate final output message from rest of output message.
sbt  run logs lot of messages which build up to final  run output.  Developers would greatly benefit if we keep them apart for clarity.

 Here is a spec

{

ALL RUN related messages

}

Here is output of your  program : 
{

Final RUN output from  code 

}

In Kubernetes world, this kind of message display  has been on the rise. This will  really help developers.

Thanks,

Sunil Sabat

**Comment by eed3si9n** [comment]
ok. Let's continue the conversation on Discuss thread then.
