### ISSUE TITLE
Unresolved dependency

### ISSUE THREAD

**Issue by lilac** [sbt/sbt#4844]
## steps
sbt version: *insert sbt version*
0.13

## problem
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: oauth.signpost#signpost-core;1.2.1.2: configuration not found in oauth.signpost#signpost-core;1.2.1.2: 'master(compile)'. Missing configuration: 'compile'. It was required from oauth.signpost#signpost-commonshttp4;1.2.1.2 compile
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::

## expectation
Should resolve successfully

## notes
I solved the problem by following advice from this [stackoverflow question ](https://stackoverflow.com/questions/33289594/sbt-does-not-resolve-all-dependencies-for-playframework-2-4-2). That is, deleting some directories under `~/.ivy2\cache`. But that is just a workaround. It must be a bug of sbt.

**Comment by eed3si9n** [comment]
sbt 0.13 is no longer supported. Please try sbt 1.3.0-RC2 that changes the dependency resolver to Coursier.
