### ISSUE TITLE
publish-local can't publish to local Maven repository

### ISSUE THREAD

**Issue by vetler** [sbt/sbt#485]
The command `publish-local` can only publish to local Ivy repository, not the Maven repository.

To publish to the local Maven repository, the user has to set `publishTo`, but this requires the user to run the command `publish`, which might be intended for publishing to a Maven repository. In some cases the user might want to only publish a version to the local (Maven) repository.

SBT should provide an option to publish locally to Maven repositories as well as Ivy repositories with the `publish-local` command.

**Comment by adriaanm** [comment]
+1
