### ISSUE TITLE
Build fails with SBT 1.3.0-RC2: "Not a valid command: assembly"

### ISSUE THREAD

**Issue by dejan2609** [sbt/sbt#4854]
**Configuration:**

- build.sbt:
```
scalaVersion := "2.13.0"
assemblyMergeStrategy in assembly := {
...
}
```
- plugins.sbt: `addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.10")`
- build.properties: 
  - sbt.version=1.2.8 -->> **_sbt assembly_** build  succeeds ✔️ 
  - sbt.version=1.3.0-RC2 -->> build fails :x: with error:
```
[error] Not a valid command: assembly
[error] Not a valid project ID: assembly
[error] Expected ':'
[error] Not a valid key: assembly
[error] assembly
[error]         ^
```
**Hint:** I can create skeleton POV project (if required).

**Note:** SBT 1.3.0-RC2 build opts out Coursier via `ThisBuild / useCoursier := false`; presumably this is irrelevant (in this context, that is).

**Comment by eatkins** [comment]
@dejan2609 I can't reproduce this. Would you post that skeleton please?

**Comment by dejan2609** [comment]
Now I'm also not able to reproduce it  :confused: 

**_Deus ex machina_** intervened, I guess 😃
