### ISSUE TITLE
[1.3.0-RC2] multi command ignored if followed by reload

### ISSUE THREAD

**Issue by OlegYch** [sbt/sbt#4860]
## steps
sbt version: 1.3.0-RC2
run `;compile;reload`

## problem
`compile` is not executed

## expectation
both compile and reload are executed

## notes
there are perhaps other commands like reload which swallow the previous one
works fine in 1.3.0-RC1

**Comment by eatkins** [comment]
Whoops: #4861.

**Comment by eatkins** [comment]
Also @OlegYch, the leading ';' is now optional (though it doesn't hurt to use it).

**Comment by OlegYch** [comment]
@eatkins cheers
