### ISSUE TITLE
skip in publish not working

### ISSUE THREAD

**Issue by daniel-shuy** [sbt/sbt#4863]
## steps
sbt version: *1.2.8*

## problem
`skip in publish` doesn't stop project from executing `publish` task

## expectation
`skip in publish` should prevent `publish` task from running

## notes
This behavior can be easily tested with this example `build.sbt`:
```scala
lazy val root = project
  .in(file("."))
  .settings(
    publish := {
      streams.value.log.info("PUBLISH ROOT")
    },
    skip in publish := true,
  )
  .aggregate(subProject)

lazy val subProject = project
  .in(file("subproject"))
  .settings(
    publish := {
      streams.value.log.info("PUBLISH SUBPROJECT")
    },
    skip in publish := true,
  )
```

Running `publish` in the `root` aggregator project will display:
```
PUBLISH SUBPROJECT
PUBLISH ROOT
```
in the SBT console

**Comment by eed3si9n** [comment]
https://github.com/sbt/sbt/blob/e2921e70d2bb1c3bfa9f8b0fef7b7d9e96279771/main/src/main/scala/sbt/Defaults.scala#L2702-L2709

The publish task that's shipped respects `publish / skip`. If you rewire publish task all bets are off.

**Comment by daniel-shuy** [comment]
Sorry, I tried to create a bare minimum project to reproduce the issue without realizing that the `publish / skip` behavior is implemented by the default `publish` task implementation itself.

**Comment by daniel-shuy** [comment]
The actual issue I faced was in a project that didn't rewire the `publish` task. The offending `build.sbt` can be found at https://github.com/daniel-shuy/sbt-release-mdoc/blob/release/0.2.0/build.sbt. Even though the `root` aggregator project had `skip in publish := true`, SBT still attempted to publish it, resulting in the error:
```
failed to release daniel-shuy/root@0.2.0: {"message":"Repo 'maven' was not found"}
```
(see https://travis-ci.org/daniel-shuy/sbt-release-mdoc/jobs/558278371 for the full build log).

**Comment by daniel-shuy** [comment]
Opened a new issue for this at #4881
