### ISSUE TITLE
[1.3.0-RC3] CI build output no longer in color

### ISSUE THREAD

**Issue by francisdb** [sbt/sbt#4879]
When running sbt locally both on `1.2.8` and `1.3.0-RC3` we have colored output.
When running on our CI servers (drone/jenkins) on `1.3.0-RC3` we no longer have colored output, this used to be the case on `1.2.8`.

**Comment by eed3si9n** [comment]
@francisdb Thanks for the report!

**Comment by torkelrogstad** [comment]
I'm seeing this as well on `1.3.0-RC4` and Travis CI

**Comment by eatkins** [comment]
This can be reproduced by piping the output, e.g. `sbt -Dsbt.version=1.3.0-RC4 | ts "%H:%M:%.s"`. The output will be colored with 1.2.8 but not 1.3.0-RC4.

**Comment by eed3si9n** [comment]
That was done intentionally per https://github.com/sbt/sbt/issues/4284

**Comment by eed3si9n** [comment]
You can regain the color as follows:

```bash
sbt -Dsbt.color=always -Dsbt.supershell=false
```

**Comment by francisdb** [comment]
That indeed brings back colors on CI, `sbt.color` is however not mentioned at https://www.scala-sbt.org/1.x/docs/Command-Line-Reference.html

**Comment by AndriusFromLTU** [comment]
`sbt -Dsbt.color=always -Dsbt.supershell=false` didn't work for me, but `-Dsbt.color=true` did

**Comment by anthonyemerson** [comment]
This is still an issue on 1.3.3 and @eed3si9n #4284 you very specifically said this was NOT supposed to be done because it would cause incompatibility with CI tools like Travis and Jenkins. Why was this done anyway?

**Comment by francisdb** [comment]
Everything has been documented at https://www.scala-sbt.org/1.x/docs/Command-Line-Reference.html

Looks like there now also is `-Dsbt.ci=true` but somehow this is not super clear:

> `-Dsbt.ci=true` For continuous integration environments. Suppress supershell and color.

From that description I would expect that option to suppress color but it **suppresses supershell** and **enables color** (will post a [PR to fix that](https://github.com/sbt/website/pull/859))

I guess this ticket can be closed.

**Comment by anthonyemerson** [comment]
@francisdb the documentation seems to indicate that the flipping of this flag to true is automatic if the BUILD_NUMBER env variable is set.

`sbt.ci | Boolean | false (unless then env var BUILD_NUMBER is set)`

Jenkins absolutely sets the BUILD_NUMBER variable so unless the documentation is wrong here too it seems this is still a bug

**Comment by francisdb** [comment]
@anthonyemerson I suggest you create a different ticket for that
