### ISSUE TITLE
skip in publish

### ISSUE THREAD

**Issue by daniel-shuy** [sbt/sbt#4881]
## steps
sbt version: *1.2.8*

## problem
`skip in publish` doesn't stop project from executing `publish` task

## expectation
`skip in publish` should prevent `publish` task from running

## notes
The offending `build.sbt` can be found at https://github.com/daniel-shuy/sbt-release-mdoc/blob/release/0.2.0/build.sbt. Even though the `root` aggregator project had `skip in publish := true`, SBT still attempted to publish it, resulting in the error:
```
failed to release daniel-shuy/root@0.2.0: {"message":"Repo 'maven' was not found"}
```
(see https://travis-ci.org/daniel-shuy/sbt-release-mdoc/jobs/558278371 for the full build log).

**Comment by eed3si9n** [comment]
If you issued `publish` _command_ to sbt shell, setting `skip in publish` will not prevent all aggregated from receiving work order for `publish` task. What it does, is skip the actual publishing work for a particular subproject. This allows build users to aggregate over subprojects without publishing root. So in general, I think it's working as designed.

**Comment by daniel-shuy** [comment]
Yes, that's what I expected it to do (I wanted to publish `sbtReleaseMdoc` without publishing the `docs` subproject and the `root` aggregate project), but somehow its still attempting to publish `root`, even though it has `skip in publish := true`. Am I configuring it wrongly?

**Comment by eed3si9n** [comment]
You have `releaseStepTask(bintrayRelease),` in your release steps.

**Comment by daniel-shuy** [comment]
Ah my bad, I found out what the issue was, my `sbt-bintray` settings should've been set in the `root` aggregate project instead of the subproject, thanks.
