### ISSUE TITLE
[1.3.0-RC3] dependencyOverrides doesn't resolve conflicts

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4895]
### steps

```scala
libraryDependencies += "com.github.gpgekko" % "sbt-autoprefixer" % "1.2.0"
dependencyOverrides += "org.webjars.npm" %% "kind-of" % "6.0.0"
```

### problem
dependencyOverrides doesn't take effect.

### expectations
dependencyOverrides resolves the conflict.

_Originally posted by @joan38 in https://github.com/sbt/sbt/issues/4720#issuecomment-512572863_

**Comment by eed3si9n** [comment]
This was fixed recently in https://github.com/coursier/sbt-coursier/pull/106.

**Comment by eed3si9n** [comment]
I should've added a test for this. Apparently this is not fixed for sbt.

**Comment by mickaelmagniez** [comment]
Can confirm still broken in 1.3.0-RC4

**Comment by rdesgroppes** [comment]
Not sure it helps, but `sbt evicted` shows `dependencyOverrides` aren't taken into account.

**Comment by eed3si9n** [comment]
Yes, I have to look into this before next RC / final.
