### ISSUE TITLE
Randomized test order task

### ISSUE THREAD

**Issue by ghost** [sbt/sbt#4896]
Looking at https://github.com/sbt/sbt/blob/0.13/main/actions/src/main/scala/sbt/Tests.scala#L153 , it appears as though tests run in order by name when running serially. Consider providing an option to run tests in an arbitrary order. Some possible target task names:
```
testShuffle
it:testShuffle
```

**Comment by eed3si9n** [comment]
Hi @kanishka-azimi
We use GitHub issue mostly to track bugs and tasks on sbt development.
This sounds like an interesting topic you can bring up to https://discuss.lightbend.com/c/tooling or explore in plugin space.

**Comment by ghost** [comment]
Makes sense, but I don't want to create another user account just to
communicate with sbt dev
