### ISSUE TITLE
Consistent location for source jars with retrieveManaged := true

### ISSUE THREAD

**Issue by ijuma** [sbt/sbt#49]
With retrieveManaged := true,  withSources causes the source jars to be downloaded to lib_managed/src while update-classifiers causes them to be downloaded to lib_managed/jar. It would be nice to make this consistent, if not too hard.

In relation to filing this issue, Mark said:

"Ok, go ahead.  It seems like it could be easy enough to implement, but if not, I'll just close it as wontfix for not worth the effort."

Original thread:

https://groups.google.com/d/topic/simple-build-tool/NJR7ZAMj93o/discussion

**Comment by ijuma** [comment]
I've tested this and it works, thanks.

I noticed that update-sbt-classifiers still users jars instead of srcs, but that is less of an issue because I am not aware of a way for those to be duplicated. If it's easy to fix, then it may be worth it for consistency purposes. :)

**Comment by ijuma** [comment]
To be clear, it's only for the artifacts with org.scala-tools.sbt for group id, e.g.:

./jars/org.scala-tools.sbt/tasks_2.8.1/tasks_2.8.1-0.10.1-SNAPSHOT-sources.jar

**Comment by harrah** [comment]
Yes, there is a fix for that in the artifacts/configurations clean up.  It will not affect sbt until 0.10.2 because 0.10.1 will be published with 0.10.0.

**Comment by ijuma** [comment]
Oh I see. Great.
