### ISSUE TITLE
Ordering of dependencies matters when using test classifiers

### ISSUE THREAD

**Issue by taylorleese** [sbt/sbt#490]
The ordering of dependencies matters when using test classifiers. For example, classes in test classifier dependencies aren't found when they are included after other test dependencies (with no classifier).

This works:

``` scala
libraryDependencies ++= {
  Seq(
    ...
    "com.foo" %% "bar" % 1.0 % "test" classifier "test" withSources(),
    "org.specs2" %% "specs2" % "1.9" % "test" withSources(),
    "org.mockito" % "mockito-all" % "1.9.0" % "test" withSources()
  )
}
```

This does not work:

``` scala
libraryDependencies ++= {
  Seq(
    ...
    "org.specs2" %% "specs2" % "1.9" % "test" withSources(),
    "org.mockito" % "mockito-all" % "1.9.0" % "test" withSources(),
    "com.foo" %% "bar" % 1.0 % "test" classifier "test" withSources()
  )
}
```

This results in class not found errors when attempting to use a class in the test classifier dependency from a spec.

**Comment by harrah** [comment]
Duplicate of #419, #285.
