### ISSUE TITLE
unresolved dependency: com.eed3si9n#sbt-assembly;0.14.9

### ISSUE THREAD

**Issue by anigos** [sbt/sbt#4902]
Tried all the contents over web and all my certificates are trusted. But no luck

**Plugins.sbt**

addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "2.5.0")
resolvers += "typesave" at "http://repo.typesafe.com/typesafe/releases"
addSbtPlugin("com.earldouglas" % "xsbt-web-plugin" % "0.4.2")
resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"

**assembly.sbt**

addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.9")

**build.properties**

sbt.version = 1.2.8

**build.sbt**
import sbtassembly.MergeStrategy

name := "Streaming"

version := "2.0"

scalaVersion := "2.12.7"
//scalaVersion in ThisBuild := "2.12.7"

val sparkVersion = "2.3.0"

dependencyOverrides ++= Seq(
  "com.fasterxml.jackson.core" % "jackson-core" % "2.8.7",
  "com.fasterxml.jackson.core" % "jackson-databind" % "2.8.7",
  "com.fasterxml.jackson.module" % "jackson-module-scala_2.11" % "2.8.7"
)
libraryDependencies ++= Seq(
  "org.apache.bahir" %% "spark-streaming-twitter" % sparkVersion,
  "org.apache.spark" %% "spark-core" % sparkVersion,
  "org.apache.spark" % "spark-sql_2.11" % sparkVersion,
  "org.apache.spark" %% "spark-streaming" % sparkVersion,
  "org.apache.kafka" % "kafka_2.11" % "1.1.1",
  "org.apache.kafka" % "kafka-streams" % "0.10.2.0",
  "org.apache.spark" % "spark-sql_2.11" % "2.3.0",
  "org.apache.spark" % "spark-sql-kafka-0-10_2.11" % "2.3.0",
  "org.apache.spark" % "spark-streaming-kafka-0-10_2.11" % "2.3.0",
  "org.apache.kafka" % "kafka-clients" % "0.11.0.1")

    assemblyMergeStrategy in assembly := {
    case PathList("META-INF", xs @ _*) => MergeStrategy.discard
    case x => MergeStrategy.first
  }

**sbtconfig.txt**

# Set the java args to high

-Xms1G
-Xmx2G
-XX:MaxPermSize=512m
-XX:ReservedCodeCacheSize=128m

# Set the extra SBT options

-Dhttp.proxySet=true 
-Dhttp.proxyHost=proxy_server
-Dhttp.proxyPort=proxy_port 
-Dhttp.nonProxyHosts="localhost|127.0.0.1" 
-Dhttp.proxyUser=username
-Dhttp.proxyPassword=password
-Dhttps.proxyHost=proxy_server
-Dhttps.proxyPort=proxy_port 
-Dhttps.nonProxyHosts="localhost|127.0.0.1" 
-Dhttps.proxyUser=username
-Dhttps.proxyPassword=password
-Dsbt.repository.secure=false

-Dsbt.gigahorse=false

**Comment by eed3si9n** [comment]
We use GitHub issue mostly to track bugs and tasks on sbt development. If you need help, please check this out - https://www.scala-sbt.org/support.html
