### ISSUE TITLE
Alias in .sbtrc makes SBT unable to initialise the project

### ISSUE THREAD

**Issue by melezov** [sbt/sbt#4903]
## steps
sbt version: 1.3.0-RCX
Seems to fail regardless of Java 8-11 on all 1.3.0 RCs

Place an alias in .sbtrc:
```alias scalacFoo = ; set scalacOptions ++= Seq("-foo")```

## problem
SBT crashes with [error] java.lang.RuntimeException: Session not initialized.

## expectation
alias should be "inert" and not affect SBT load until it's actually invoked.

## notes
Full reproducible here: https://github.com/melezov/sbt-reproducibles/tree/master/sbtrc-woes

**Comment by melezov** [comment]
Removing the semicolon will enable the project to initialise, so this seems to be a parser issue when having multiple commands in an alias line

**Comment by eatkins** [comment]
@melezov thanks for the report. This should be fixed by #4904.
