### ISSUE TITLE
Let's stop resolving dependencies over HTTP and require HTTPS

### ISSUE THREAD

**Issue by JLLeitschuh** [sbt/sbt#4905]
[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
[Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)

The details in the blog post above describe my research over the past 4 months into the use of HTTP to resolve dependencies across the JVM ecosystem.

This vulnerability impacted the open source build infrastructure for organizations like the Apache Foundation, Eclipse Foundation, Jenkins, JetBrains, RedHat, ect...

One of the cases where I discovered this vulnerability was in the build infrastructure for some of [Twitter's](https://twitter.com)'s open source projects. They were declaring jar dependencies using repositories over HTTP. Thus a MITM of their SBT build could have allowed for the malicious compromise of their artifacts. For this finding, I was awarded a bug bounty by their security team.

I believe that it's the responsibility of API authors, especially of build tools to help protect their users from careless security vulnerabilities like this.

As such, I've begun work on fixing this for all users of Gradle in this PR:
https://github.com/gradle/gradle/pull/9419

Additionally, I've opened an issue with the Apache Maven team about fixing this there as well:
https://issues.apache.org/jira/browse/MNG-6673

Similar work is being done by the Bazel team:
https://github.com/bazelbuild/bazel/issues/8607

## Deliverables

 - [ ] Next minor release: Begin warning users about their use of HTTP to download dependencies.
 - [ ] Next major release: Force users to explicitly opt-out of the security offered by using HTTPS.

**Comment by eed3si9n** [comment]
@JLLeitschuh Thanks for the report.

Since 2014 (https://github.com/sbt/sbt/pull/1507) sbt defaults to HTTPS for Maven Central downloads, but you're proposing that we force HTTPS for custom resolvers as well without an explicit opt-out?

**Comment by JLLeitschuh** [comment]
@eed3si9n I'm suggesting that you fail if the user specifies `http` instead of `https`. They are allowed to opt-in to being insecure if necessary for their use case, but this should be explicit.

I believe that a majority of the cases where I found uses of `http` instead of `https` were either copy/pasted code or were fat fingered typos.

**Comment by eed3si9n** [comment]
> I believe that a majority of the cases where I found uses of http instead of https were either copy/pasted code or were fat fingered typos.

Searching GitHub for [resolvers extension:sbt language:Scala, sorted recently indexed](https://github.com/search?o=desc&q=resolvers+extension%3Asbt+language%3AScala&s=indexed&type=Code) seems to back up your claim.

```scala
resolvers += Resolver.url("jetbrains-sbt", url(s"http://dl.bintray.com/jetbrains/sbt-plugins"))(Resolver.ivyStylePatterns)

resolvers += "Typesafe Releases" at "http://repo.typesafe.com/typesafe/releases/"

resolvers += "MimirDB" at "http://maven.mimirdb.info/"
```

**Comment by SethTisue** [comment]
in RC4, the new warning is appearing for my local Artifactory, which is what I always resolve everything from

perhaps I could/should configure my local Artifactory for https, but it looks like work. I'm also curious if I can suppress the warning

(or, idk, perhaps the warning ought not to appear at all when it's 127.0.0.1 or localhost?)

**Comment by SethTisue** [comment]
another thought about configurability: some users might want to go in the other direction and have the warning always be an error

**Comment by eed3si9n** [comment]
> another thought about configurability: some users might want to go in the other direction and have the warning always be an error

The plan is to remove HTTP support in sbt 1.4.0 by making it an error. At that point (or sooner) we would create `-Dsbt.insecureprotocol=true` or something like that.

**Comment by JLLeitschuh** [comment]
@eed3si9n Out of curiosity, why make it a flagg instead of per-repository?

There are certain cases where companies may have internal mirrors without certs and they don't consider MTIM a threat inside their network, however all other repos must use HTTPS.

The approach that I'm taking with Gradle is to do per-repository. We are also making the intentional decision not to offer a build flag to disable the check as it makes it too easy to make the whole build insecure.

One other thing we're thinking about is ensuring that we protect against servers that redirect to an HTTP based repository and failing in those cases as well.

**Comment by JLLeitschuh** [comment]
> perhaps the warning ought not to appear at all when it's 127.0.0.1 or localhost

For gradle we don't warn on 127.0.0.1 which allows us to test the HTTP/HTTPS logic in a controlled way across our codebase and gives our tests an easy opt-out so we don't have to install a truststore for every test.

**Comment by eed3si9n** [comment]
In sbt, the resolvers can come from machine-specific repository overrides, frequently used in behind-firewall environments - https://www.scala-sbt.org/1.0/docs/Proxy-Repositories.html

I will also think about per-repo opt-in.

> For gradle we don't warn on 127.0.0.1 which allows us to test the HTTP/HTTPS logic in a controlled way across our codebase and gives our tests an easy opt-out so we don't have to install a truststore for every test.

That's good to know. That would solve Seth's issue.

**Comment by swsnr** [comment]
I'm happy to see that SBT takes step to require HTTPS for public repositories, but I'd also appreciate a per-repo opt-in to HTTP.  

We resolve all artifacts, internal or otherwise, through an in-house artifactory inside a walled cable-network only accessible to employees in an access-controlled building.  In this scenario HTTPS isn't really necessary and I'd like to avoid the hassle of setting up certificates, etc.

**Comment by swsnr** [comment]
I see that SBT 1.3.0 now warns about HTTP requests, recommending to switch to HTTPS or opt-in with `.withAllowInsecureProtocol(true)`.  Thanks for this :+1: 

However, we typically configure our proxy repository in `~/.sbt/repositories`; as said [before](https://github.com/sbt/sbt/issues/4905#issuecomment-523896754) our proxy repository runs on HTTP because it's inside a isolated access-controlled network where MITM is no real-thread, so I'd like to opt-out from HTTPS.

But how can I do that in the `repositories` file?

**Comment by henricook** [comment]
+1 - we have the same situation as @lunaryorn and now see lots of warnings on a regular basis

**Comment by eed3si9n** [comment]
> But how can I do that in the `repositories` file?

I didn't want to rush a solution for repositories file change, and I haven't figured out what it should be done here. If I can figure out resolvers coming from `repositories` file, should they be exempted automatically, or should I somehow extend the syntax to allow opt-in?

**Comment by JLLeitschuh** [comment]
> Should they be exempted automatically

I would argue no. This puts us back at square one if you do this.

> Should I somehow extend the syntax to allow opt-in

This is probably the most appropriate thing to do. You want to keep the opt-out per repository declaration.

**Comment by swsnr** [comment]
I guess explicit‘s better than implicit in this case, so I tend to lean towards an explicit flag in the file. 🙂

**Comment by henricook** [comment]
I'd also settle for a global allow http flag, if that's not already been bandied around

**Comment by JLLeitschuh** [comment]
@henricook As I said before, we made the intentional decision not to do this for Gradle:

> We are also making the intentional decision not to offer a build flag to disable the check as it makes it too easy to make the whole build insecure.

**Comment by mrt181** [comment]
Would a whitelist be a sensible compromise?
Instead of a global build flag use a comma separated list of urls to disable it for those urls, e.g.:
```
// explicit
-Dsbt.allow.insecure.protocol=sonatype.mycompany.com,repository.mycompany.com
```

**Comment by felixbr** [comment]
I commend sbt pushing for secure defaults proactively. 👍
That said, the way this was implemented is very unfortunate. In our situation we have company-internal http-resolvers defined in internal sbt-plugins which are still used by lots of projects which aren't using sbt 1.3.x yet (40+ at this point).

This puts us in the following situation:
- Projects which are already using 1.3.x receive dozens of useless warnings for company-internal resolvers *on basically every command*.

- Projects which are not yet on 1.3.x don't receive the warning, but if we upgraded the sbt-plugins to 1.3.x and added the `.withInsecureProtocol(true)` flag they'd now crash with `NoSuchMethodError` as the flag doesn't exist in 1.2.x.

It's basically a lose-lose unless we drop everything, upgrade *every last one* of the 40+ projects to 1.3.x (which isn't always straightforward) and then upgrade the sbt-plugins to a new version with the flag only to have to upgrade all projects with the new plugin-version again afterwards.

We would highly appreciate a way to globally treat a company-internal resolver as secure even with http, so the constant warning-spam stops and we don't have to upgrade *all* our projects twice just to be able to silence these warnings.

Thanks for your time 🙂

**Comment by JLLeitschuh** [comment]
I think that you can compile your code so that it checks the SBT version before calling `withInsecureProtocol` and the JVM won't crash with a `NoSuchMethodError` since the `if` check won't attempt to call the method that doesn't exist.

**Comment by felixbr** [comment]
Thanks for the suggestion! I got it working for both 1.3.x and 1.2.x 👍

For other people who need a workaround in sbt-plugins:
```scala
  // in a sbt-plugin

  override def globalSettings: Seq[Def.Setting[_]] = Seq(
    // The resolver to get libraries from.
    companyResolver := {
      val sbtVersionValue = sbtVersion.value

      ("Company Release Repo Nexus" at "http://artifacts.company.com/content/groups/public")
        .allowInsecureConnection(sbtVersionValue)
    }
    // possibly do something similar for `publishTo`
  )

  /**
    * Needed to keep backwards compatibility with projects not on 1.3.x yet
    */
  implicit private final class MavenRepositoryOps(repo: MavenRepository) {
    def allowInsecureConnection(sbtVersion: String): MavenRepository =
      if (sbtVersion.startsWith("1.3."))
        repo.withAllowInsecureProtocol(true)
      else
        repo
  }
```

**Comment by Openpalm** [comment]
hmm, so i just tried to upgrade to 2.13 (from 2.12.8, sbt 1.2.8) .. and it failed on HTTPS. 

so here is my opinion, first, this is a work setting, so to save time i will simply not upgrade now until i read up on this and figure out what's going on.

the rest of my opinion is that a compiler should just compile. not worry if i use HTTP or HTTPS.

this should have been handled internally by the compiler's logic. much like HTTPSEverywhere (use https if available, and make sure repos actually HTTPS available.)

making this a configurable just increases SBT's obtuseness. worse still, a forced feature will simply make sure projects don't upgrade. (features bring in more money, i hate that kind of thinking, but this is what we mostly have.)

**Comment by SethTisue** [comment]
@Shokodemon if you think anybody is making any money by maintaining or supporting the maintenance and continued improvement of sbt, you are sorely mistaken. it's a labor of love for everyone involved

and if you actually read the discussion here, _literally nobody_ has suggested a “forced” feature without an easy opt-out

**Comment by eed3si9n** [comment]
@Shokodemon 

> hmm, so i just tried to upgrade to 2.13 (from 2.12.8, sbt 1.2.8) .. and it failed on HTTPS.

First, could you clarify what you mean by "it failed on HTTPS" by posting error messages etc? As far as I know, sbt 1.3.7 does not fail just because you have HTTP in the list of resolvers. What you might see is a warning like:

```
[warn] insecure HTTP request is deprecated 'http://repo1.maven.org/maven2/'; switch to HTTPS or opt-in as ("public" at "http://repo1.maven.org/maven2/").withAllowInsecureProtocol(true)
```

> the rest of my opinion is that a compiler should just compile. not worry if i use HTTP or HTTPS.

I disagree. Tooling should actually prevent unsafe behavior by default because many people don't pay attention to the URL they are copy-pasting from an old blog post or something even when there are HTTPS endpoint available. This is the direction the world is shifting in the recent years.

- [Decommissioning HTTP for Gradle Services](https://blog.gradle.org/decommissioning-http) October, 2019
- [The Central Repository is Moving to HTTPS](https://blog.sonatype.com/central-repository-moving-to-https) December, 2019
- [JCenter went full HTTPS! Starting Jan 13th, any non-HTTPS requests will be denied with 403 error.](https://jfrog.com/blog/secure-jcenter-with-https/) January, 2020

When we do remove the out-of-box use of HTTP, we will provide an opt-in to support the use of HTTP, but I think this is the responsible thing to do for the tooling ecosystem in JVM and elsewhere.

> this should have been handled internally by the compiler's logic.

It's a minor point, but the resolution of library dependencies has nothing to do with Scala compiler. I'll just interpret this this as "sbt should silently try using HTTPS during dependency resolution automatically." Sure, I think that is one way of doing it. It might make the transition phase easier. But that basically introduces magic into the build process. What if the hacker somehow is able to do Denial of Service attack on HTTPS endpoint of Maven Central or JCenter? If we silently fell back to HTTP, which then could be man-in-the-middled, you wouldn't notice something went wrong. Even though it might introduce some pain during the transition, doing this transparently I think is the safe and better way of doing this.

**Comment by JLLeitschuh** [comment]
@eed3si9n very eloquently stated.

SBT Team, is there any plan on the roadmap to drop support for HTTP for `http[s]://repo.typesafe.com`? (I'm assuming that you host that one).

I'm sorry for not including you in this decommission discussion earlier when I started having it with Maven Central, I should have. If you do want to move forward with the plan, I suggest a 3 month warning with a blog post at minimum.

**Comment by eed3si9n** [comment]
We (Lightbend) host https://repo.typesafe.com/ and https://repo.scala-sbt.org/ which currently redirect to Bintray repositories. I think it makes sense to drop the HTTP support on them following your lead. I'll forward this to internal discussion.

**Comment by JLLeitschuh** [comment]
@eed3si9n You can also ask JFrog to drop support from your bintray repo as well. I believe the Spring team did this for their decommission as well.

**Comment by eed3si9n** [comment]
We use `dl.bintray.com`, so I am not sure if we have any control over whether HTTP is served or not, but we can ask JFrog.

**Comment by zhengcan** [comment]
> > But how can I do that in the `repositories` file?
> 
> I didn't want to rush a solution for repositories file change, and I haven't figured out what it should be done here. If I can figure out resolvers coming from `repositories` file, should they be exempted automatically, or should I somehow extend the syntax to allow opt-in?

Any update for this?
We use nexus as repository proxy instead of use public repositories directly. So we need better support for internal HTTP-only repository.

**Comment by henricook** [comment]
I agree, I still can't take my SBT 1.2.8 CI setup with a repositories file that points everything to my internal mirror and upgrade it to SBT 1.3.8

I get a weird checksum issue first, but even after disabling checksums (safe, I know ;-) I still find that it tries to go out to the internet in situations where it wasn't before and claims it can't find dependencies. I've given up again

**Comment by eed3si9n** [comment]
> Any update for this?

I was thinking about adding some changes for sbt 1.4.0. In other words, it hasn't been urgent priority to fix this and patch 1.3.x series since people should still be able to use sbt behind the firewall. Is this not the case?

Looking at the implementation, I think it would be similar to this commit https://github.com/sbt/launcher/commit/00f681a7121d73c598f41358e1158fa0169d5a60 where it added support for:

```
  ivy-repo: http://repo.example.com, [pattern], descriptorOptional
```

This could be extended to something like

```
  ivy-repo: http://repo.example.com, [pattern], allowInsecureProtocol
  maven-repo: http://repo.example.com, allowInsecureProtocol
```

**Comment by henricook** [comment]
I'm sorry I think, at least for my comments, this ticket has diverged into "I can't use an internal dependencies proxy/mirror with sbt 1.3.x like i could with sbt 1.2.8"

I do agree that being able to turn off the HTTP warning would be useful if you know what you're doing, and that some use cases do see genuine http use cases in the real world

**Comment by yanns** [comment]
With a standard sbt project without any customized resolver, I still have the following warnings:
```
[warn] insecure HTTP request is deprecated 'http://repo.typesafe.com/typesafe/releases'; switch to HTTPS or opt-in as ("typesafe-releases" at "http://repo.typesafe.com/typesafe/releases").withAllowInsecureProtocol(true)
```
Is it configured like this per default in sbt?

**Comment by liebichw** [comment]
I am working within a company net, which is rigorously firewalled. Our Nexus repository proxies everything, including public repositories, and it would be a huge hassle for us to set that up with https.
As our repository is configured in the "repositories" file, I get these insecure warnings for every command on every project, which is quite a hassle.
Is there a solution in the pipeline to enable this? The "withAllowInsecureProtocol" method does not work in this time.

**Comment by SethTisue** [comment]
@eed3si9n is this fixed in 1.3.11? or is https://github.com/sbt/launcher/pull/75 only one piece of it?

**Comment by eed3si9n** [comment]
@SethTisue sbt 1.3.11 should address the `allowInsecureProtocol` part that corporate proxy users have been waiting for. 

1.4.x would pull out the HTTPS to close out this epic.

**Comment by eed3si9n** [comment]
https://github.com/sbt/sbt/pull/5593 scheduled for sbt 1.4.0 will drop HTTP support out of box.

**Comment by JLLeitschuh** [comment]
@eed3si9n Is there a public issue tracking the drop of HTTP support for `http://repo.typesafe.com`?

https://github.com/sbt/sbt/issues/4905#issuecomment-575803374

**Comment by henricook** [comment]
Oh wow, what isn't clear from #5593 to me is how I can keep HTTP resolvers (e.g. for private resolver), is there a flag? Or is it forced unsupported?

**Comment by SethTisue** [comment]
@JLLeitschuh not sure if there's an issue, but there was a blog post: https://www.lightbend.com/blog/lightbend-to-require-https-on-repos-starting-august-5-2020

@henricook use `.withAllowInsecureProtocol(true)`

@eed3si9n on Christmas 🎅, you [wrote](https://github.com/sbt/sbt/issues/5247#issuecomment-568971384):

> Currently there's no way to suppress the warning if you're using repository override

does that remain the case? because my local-Artifactory setup, which uses an `~/.sbt/repositories` file, is `http:` based, will I need to fix that?

**Comment by henricook** [comment]
Nice, i hadn't seen this which should let me do that via a repository override file as well, so very nice :+1: https://github.com/sbt/sbt/issues/4905#issuecomment-636261825

In our situation we HTTP to a caching internal proxy which HTTPS to repo.typesafe.com (for example) - so we simultaneously support the HTTPS move for these repos whilst wanting to be able to retain HTTP for repos override files. Seems like we're good.

**Comment by henricook** [comment]
Perhaps some repositories file documentation improvements may be necessary, is this valid in a repositories file or do i have to specify the optional patterns etc as well?

`maven-proxy: http://dep-proxy.cluster.local/repo1.maven.org/maven2/, allowInsecureProtocol` ?

Currently the above on sbt 1.3.12 results in:

```
[warn] insecure HTTP request is deprecated 'Patterns(ivyPatterns=Vector(http://dep-proxy.cluster.local/repo1.maven.org/maven2/allowInsecureProtocol), artifactPatterns=Vector(http://dep-proxy.cluster.local/repo1.maven.org/maven2/allowInsecureProtocol), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false)'; switch to HTTPS or opt-in as Resolver.url("maven-proxy", url(...)).withAllowInsecureProtocol(true)
```

**Comment by eed3si9n** [comment]
@SethTisue sbt 1.3.12 + launcher together add `allowInsecureProtocol` support to launcher configuration, including `repositories` file. This means that `sbt` launcher needs to be upgraded via SDKMAN etc for this feature to kick in.

@henricook Your definition should be ok. I'll try to update the docs.

**Comment by henricook** [comment]
> @SethTisue sbt 1.3.12 + launcher together add `allowInsecureProtocol` support to launcher configuration, including `repositories` file. This means that `sbt` launcher needs to be upgraded via SDKMAN etc for this feature to kick in.
> 
> @henricook Your definition should be ok. I'll try to update the docs.

Thanks, so the launcher isn't bundled with 1.3.12? For an average user like me does that mean waiting until 1.3.13?

**Comment by eed3si9n** [comment]
The sbt 1.3.12 installer uses the new launcher, but many people don't reinstall sbt every time there's a patch release of sbt, and just change `project/build.properties`.

**Comment by wildape** [comment]
> I see that SBT 1.3.0 now warns about HTTP requests, recommending to switch to HTTPS or opt-in with `.withAllowInsecureProtocol(true)`. Thanks for this 👍
> 
> However, we typically configure our proxy repository in `~/.sbt/repositories`; as said [before](https://github.com/sbt/sbt/issues/4905#issuecomment-523896754) our proxy repository runs on HTTP because it's inside a isolated access-controlled network where MITM is no real-thread, so I'd like to opt-out from HTTPS.
> 
> But how can I do that in the `repositories` file?

in `repositories` file，you can add config as `name: url,allowInsecureProtocol`
ref: https://www.scala-sbt.org/1.x/docs/Launcher-Configuration.html
eg.
```
[repositories]
local
nexus-private: http://private-example.com/,allowInsecureProtocol
```

**Comment by pmkyl** [comment]
> > I see that SBT 1.3.0 now warns about HTTP requests, recommending to switch to HTTPS or opt-in with `.withAllowInsecureProtocol(true)`. Thanks for this 👍
> > However, we typically configure our proxy repository in `~/.sbt/repositories`; as said [before](https://github.com/sbt/sbt/issues/4905#issuecomment-523896754) our proxy repository runs on HTTP because it's inside a isolated access-controlled network where MITM is no real-thread, so I'd like to opt-out from HTTPS.
> > But how can I do that in the `repositories` file?
> 
> in `repositories` file，you can add config as `name: url,allowInsecureProtocol`
> ref: https://www.scala-sbt.org/1.x/docs/Launcher-Configuration.html
> eg.
> 
> ```
> [repositories]
> local
> nexus-private: http://private-example.com/,allowInsecureProtocol
> ```

This doesnt work. At least when settings are stored in ./sbt/repositories and using sbt 1.4.3

**Comment by eed3si9n** [comment]
@pmkyl Could you open a new issue for this please?
