### ISSUE TITLE
Supershell produces redudant lines

### ISSUE THREAD

**Issue by eatkins** [sbt/sbt#4911]
On the latest develop branch, if I run test in io, I get something like this:
![demo2](https://user-images.githubusercontent.com/2658825/62339948-ab14c200-b492-11e9-80ba-630193737091.gif)

**Comment by eatkins** [comment]
It happens with both iterm2 and terminal.app.

**Comment by eed3si9n** [comment]
Yea. I've seen that. I wonder if there are multiple reports running simultaneously, or it's printing on top of the other so it looks that way.

**Comment by SethTisue** [comment]
I don't know if this is the same or different, but with both 1.3.0-RC4 and 1.3.0-RC5 I'm seeing supershell output get mixed up with regular output, so for example over at https://github.com/SethTisue/Project-Euler :

<img width="578" alt="Screen Shot 2019-08-29 at 9 28 53 PM" src="https://user-images.githubusercontent.com/161079/63988962-24103500-caa4-11e9-816a-24c7f83ca811.png">

I'm short on time at the moment but I could investigate / follow up more next week if you want

**Comment by eed3si9n** [comment]
@SethTisue might be https://github.com/scala/nanotest-strawman/issues/20

**Comment by SethTisue** [comment]
looking at @eatkins's animation above, it appears to me that a bunch of tests are running in parallel, that's a good thing, and there's no issue? am I mistaken?

**Comment by eed3si9n** [comment]
I'm not sure if it's multiple tests that's causing this, but I don't think there should be multiple lines of supershell countup clock displayed per task.

```
  | => io / Test / executeTest 4s
  | => io / Test / executeTest 3s
  | => io / Test / executeTest 3s
...
```

**Comment by eatkins** [comment]
Yeah. That is specifically what I created this issue for. I’d expect only one `io / Test / executeTest` line.

**Comment by eatkins** [comment]
@SethTisue is correct about the underlying cause though I think it's suboptimal from a ux perspective. Setting `Test / parallelExecution := false` makes the problem go away (and the tests take 3 times longer!). The `test` task delegates to a number of anonymous tasks and they all inherit the name of the calling task, `executeTest`. This is actually a general problem for the progress reports. As it currently stands, we actually report something more like utime rather than walltime in the reports:
```
Total time: 16714 ms
  io / Test / executeTests                                    : 48376 ms
  io / Compile / previousCompile                              :   159 ms
```
I think it would make sense to aggregate the tasks by name and calculate both the the wall time `max(end) - min(start)` as well as the total time `sum(end - start) for all tasks`. For the purpose of supershell, we'd just display a single time with a running counter based on the current `max(end) - min(start)`.

**Comment by eed3si9n** [comment]
that's interesting.

the impetus for super shell is to surface what's going on inside of sbt's task engine, so if it is in fact the case that there are multiple effect monads processing the test suites, that's great, and my stance then would be to visualize that fact more effectively. Maybe we should distinguish the tasks by some sequential number (test group id?), or JVM thread id.

**Comment by eatkins** [comment]
I think I have a nice solution here: https://github.com/sbt/sbt/pull/5023

**Comment by eatkins** [comment]
Closing since #5023 is merged.
