### ISSUE TITLE
deprecate insecure(non-ssl) maven central access?

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt#4917]
- https://central.sonatype.org/articles/2019/Apr/30/http-access-to-repo1mavenorg-and-repomavenapacheorg-is-being-deprecated/
- https://github.com/sbt/launcher/blob/1a138595f25192ae0c3a95a626cb17954afcd40c/launcher-implementation/src/main/scala/xsbt/boot/Update.scala#L367-L368

**Comment by theBlackDragon** [comment]
Just saw this warning after being away from Scala for a while. Is the intention to remove http access entirely? If so that's slightly worrying to me as having to deal with ssl certificates on local proxy repositories, or internal networks, seems rather unnecessary to me.

Will the option to just use plain http remain?

**Comment by eed3si9n** [comment]
@theBlackDragon This issue (4917) is about Maven Central HTTP access, which is not defunct.

For general HTTP access, please see the discussion in https://github.com/sbt/sbt/issues/4905. There will always be opt-in for HTTP but it will need explicit opt-in after sbt 1.4.x.

**Comment by theBlackDragon** [comment]
> 
> 
> @theBlackDragon This issue (4917) is about Maven Central HTTP access, which is not defunct.
> 
> For general HTTP access, please see the discussion in #4905. There will always be opt-in for HTTP but it will need explicit opt-in after sbt 1.4.x.

Thank you, for some reason that issue didn't come up when I searched, it's good to hear a well documented opt-in will remain.

**Comment by SethTisue** [comment]
stale ticket — Maven Central has required https (their change, not sbt's) for a long time now
