### ISSUE TITLE
Migration to Coursier

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4939]
This is an epic to track migration to [Coursier](https://get-coursier.io/) as the internal library management engine. #4614

## wins
- better cache management
- `${packaging.type}` variable - #3618
- URL follow redirect - #2609, #3670
- latest-wins on Maven Central origin artifacts - #3525
- multiple version ranges - #2647, #4271
- specific version over version range - #2291
- classifier handling - #3803
- offline? - #3778
- download progress - #2788

## eviction reports

- dependencyOverrides don't suppress eviction warnings #5008
- Eviction message missing when dependency has version range  #5312
- Incorrect evicted warnings for closed version ranges  #5261

## explicit URL using `from(...)`

There was a bug in earlier version of Coursier 2.0 beta, but since 2.0.0-RC2-1, there's been scripted test called `dependency-management/url` that tests for this feature. However there's been some report that it's not working.

- Explicit URL using `from` not working as expected https://github.com/sbt/sbt/issues/5418 / https://github.com/sbt/sbt/issues/6293

## proxy

<s>- proxy with basic authentication not working #5307 / https://github.com/coursier/coursier/issues/930</s>

## dependency graph regression

<s>- `Test` resolution leaks over to `Compile` configuration, evicting `Compile` dependencies - https://github.com/coursier/coursier/issues/1382</s>

## other regressions

- <s>classpath is no longer topologically sorted #5282 / https://github.com/coursier/coursier/issues/1466</s>
- unresolved resolution graph error #5168
- java.lang.NumberFormatException: For input string: "h7v0l43" #5218
- <s>`"org.nd4j" % "nd4j-native-platform" % "1.0.0-beta4"` resolves to an URL with `${project.packaging}` - #5046</s> 
- <s>Basic auth handling - #4852 (has PR https://github.com/coursier/coursier/pull/1350)</s>
- <s>Transitive dependencies with classifier are not downloaded https://github.com/coursier/coursier/issues/1455</s>
- <s>a transitive non-optional dependency that is optional in its parent POM is missing - #4968 (also https://github.com/coursier/coursier/issues/1336. it might be a "won't fix" because [MNG-5227](https://issues.apache.org/jira/browse/MNG-5227) says it's correct?)</s>
- <s>updateFull is missing caller for direct dependencies #4706</s>

**Comment by SethTisue** [comment]
@eed3si9n surely this can be closed now 😀

**Comment by eed3si9n** [comment]
Yea.
