### ISSUE TITLE
Compiler plugins not included in `show libraryDependenciesAsJson` 

### ISSUE THREAD

**Issue by exoego** [sbt/sbt#4957]
## steps
sbt version: *1.2.8*

build.sbt
```scala
lazy val project1 = project
  .in(file("project1"))
  .settings(
    addCompilerPlugin("org.spire-math" %% "kind-projector" % "0.9.10"),
  )
```

Run `show libraryDependenciesAsJson`

## problem

Compiler plugin `"org.spire-math" %% "kind-projector" % "0.9.10"` are not included.

Result of `show libraryDependenciesAsJson` is
```
[info] project1 / libraryDependenciesAsJson
[info]  [ { "groupId": "org.scala-lang", "artifactId": "scala-library", "artifactIdCross": "scala-library", "version": "2.12.7" } ]
```

## expectation

Compiler plugin should be included.
Since `show libraryDependencies` includes compiler plugins like
```
[info] project1 / libraryDependencies
[info]  List(org.scala-lang:scala-library:2.12.7, org.spire-math:kind-projector:0.9.10:plugin->default(compile))
```

**Comment by exoego** [comment]
It is weird that there is no `libraryDependenciesAsJson` string found in source code, as far as I grep-ed `libraryDependenciesAsJson` in
* https://github.com/sbt/io
* https://github.com/sbt/util
* https://github.com/sbt/librarymanagement
* https://github.com/sbt/zinc
* https://github.com/sbt/sbt

Is key `libraryDependenciesAsJson` generated somehow, like reflection or macro 🤔 ?

**Comment by eed3si9n** [comment]
Looks like it's not us - https://github.com/fthomas/scala-steward/blob/03b93e0fbe09a04af06dd59adaef74d22846a0d1/modules/core/src/main/resources/StewardPlugin.scala#L27

**Comment by exoego** [comment]
Ah, true.
I was not aware of that `StewardPlugin` is installed globally in `~/.sbt/1.0/plugins/ `.
Thanks !!
