### ISSUE TITLE
Futures suddenly stopped executing when running my program via SBT

### ISSUE THREAD

**Issue by Zahnentferner** [sbt/sbt#496]
Something quite strange has just happened to me.

I usually keep SBT running, and after making changes in my code, I simply type "run".  Suddenly, my code stopped working. It took me a while to figure out that all my futures were not being called anymore. I even tried trivial futures like: 

future {
  println("future does work")
}

but nothing was printed.

I tried doing "clean" before "run", but it didn't help.

Finally I restarted SBT, and then magically everything started working properly again.

**Comment by harrah** [comment]
Please use the mailing list for support: http://groups.google.com/group/simple-build-tool/topics.  A reproducible test case is the best way to get an answer there.
