### ISSUE TITLE
[1.3.0-RCx] a transitive non-optional dependency, but optional in parent POM, is missing

### ISSUE THREAD

**Issue by anilkumarmyla** [sbt/sbt#4968]
Ref: https://github.com/lukas-krecan/JsonUnit
- json-unit-parent declares hamcrest-core as optional dependency
- json-unit-core needs hamcrest-core
- json-unit inherits from json-unit-parent and needs json-unit-core

By this logic json-unit needs hamcrest-core in both compile/test scopes which is true with sbt-1.2.x series, but not in sbt-1.3.x series, reproducible sample below

## steps

`sbt dependencyList test:dependencyList`

Setup
```
$ cat build.sbt 
libraryDependencies ++= Seq(
  "net.javacrumbs.json-unit" % "json-unit" % "2.8.0"
)
$ cat project/sbt-dependency-graph.sbt 
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.10.0-RC1")
```

sbt-1.2.8
```
$ cat project/build.properties 
sbt.version=1.2.8
$ sbt dependencyList test:dependencyList
...
[info] default:optional_2.12:0.1.0-SNAPSHOT
[info] net.javacrumbs.json-unit:json-unit:2.8.0
[info] net.javacrumbs.json-unit:json-unit-core:2.8.0
[info] org.hamcrest:hamcrest-core:1.3
[info] org.opentest4j:opentest4j:1.1.1
...
[info] default:optional_2.12:0.1.0-SNAPSHOT
[info] net.javacrumbs.json-unit:json-unit:2.8.0
[info] net.javacrumbs.json-unit:json-unit-core:2.8.0
[info] org.hamcrest:hamcrest-core:1.3
[info] org.opentest4j:opentest4j:1.1.1
```

sbt-1.3.0-RC4
```
$ cat project/build.properties 
sbt.version=1.3.0-RC4
$ sbt dependencyList test:dependencyList
...
[info] default:optional_2.12:0.1.0-SNAPSHOT
[info] net.javacrumbs.json-unit:json-unit:2.8.0
[info] net.javacrumbs.json-unit:json-unit-core:2.8.0
[info] org.opentest4j:opentest4j:1.1.1
...
[info] default:optional_2.12:0.1.0-SNAPSHOT
[info] net.javacrumbs.json-unit:json-unit:2.8.0
[info] net.javacrumbs.json-unit:json-unit-core:2.8.0
[info] org.opentest4j:opentest4j:1.1.1
```

**Comment by anilkumarmyla** [comment]
If we declare json-unit in `Test` scope, we get similar results

`"net.javacrumbs.json-unit" % "json-unit" % "2.8.0" % Test`

sbt-1.2.8
```
[info] default:optional_2.12:0.1.0-SNAPSHOT
...
[info] default:optional_2.12:0.1.0-SNAPSHOT
[info] net.javacrumbs.json-unit:json-unit:2.8.0
[info] net.javacrumbs.json-unit:json-unit-core:2.8.0
[info] org.hamcrest:hamcrest-core:1.3
[info] org.opentest4j:opentest4j:1.1.1
```

sbt-1.3.0-RC4
```
[info] default:optional_2.12:0.1.0-SNAPSHOT
...
[info] default:optional_2.12:0.1.0-SNAPSHOT
[info] net.javacrumbs.json-unit:json-unit:2.8.0
[info] net.javacrumbs.json-unit:json-unit-core:2.8.0
[info] org.opentest4j:opentest4j:1.1.1
```

**Comment by eed3si9n** [comment]
@anilkumarmyla Thanks for the report.

> - json-unit-core needs hamcrest-core

More importantly, json-unit-core not only _needs_ it but it actually _declares dependency_ without optional hamcrest-core, correct?

https://repo1.maven.org/maven2/net/javacrumbs/json-unit/json-unit-core/2.8.0/json-unit-core-2.8.0.pom

```xml
<dependency>
  <groupId>org.hamcrest</groupId>
  <artifactId>hamcrest-core</artifactId>
</dependency>
```

So I agree with your expectation that final resolution should contain `org.hamcrest:hamcrest-core:1.3`.

For now please workaround this by using `ThisBuild / useCoursier := false`.

**Comment by anilkumarmyla** [comment]
> More importantly, json-unit-core not only needs it but it actually declares dependency without optional hamcrest-core, correct?

Yes. json-unit is mostly used in unit tests in `Test` scope, so it was rather weird to see tests failing to find hamcrest classes.

> For now please workaround this by using ThisBuild / useCoursier := false.

We can also explicitly add it `"org.hamcrest" %  "hamcrest" % "2.1" % Test` as well to make the tests pass

**Comment by eed3si9n** [comment]
Opened issue on Coursier - https://github.com/coursier/coursier/issues/1336

**Comment by eed3si9n** [comment]
Closing here as well following https://github.com/coursier/coursier/issues/1336 /  https://github.com/lukas-krecan/JsonUnit/issues/193.
