### ISSUE TITLE
Tests do not exit, if actors are still active

### ISSUE THREAD

**Issue by gerdriesselmann** [sbt/sbt#497]
Testcase: https://github.com/gerdriesselmann/sbt-actor-object-testcase

If there are started actors and sbt test is run, sbt will not terminate until every actor is terminated. sbt therefore runs forever.

This worked perfectly fine in sbt 0.7.

**Comment by harrah** [comment]
Please finish the discussion here first: https://groups.google.com/d/topic/simple-build-tool/eNtnN9wrY2A/discussion.

Eugene's concerns appear valid.  I don't see how this could have worked before or at least worked without leaking.

**Comment by gerdriesselmann** [comment]
I changed the code to demonstrate it is not the start() in the object constructor, which is causing this issue. 

As I already noted: It works in sbt 0.7.

What exactly do you mean with "finish the discussion"?

**Comment by gerdriesselmann** [comment]
I added a sbt 0.7 build so you may convince yourself that it worked with sbt 0.7.4.

1.) Comment in line sbt.version=0.7.4 in project/build.properties
2.) Run "sbt7 test" on the command line: Project is compiled, test are succesfully run, and the command prompt reappears
3.) Run sbt7 and then test on the sbt prompt. Test are executed, and the sbt prompt reappears

Now with sbt 0.12:

1.) Comment in line sbt.version=0.12.0-RC3 in project/build.properties
2.) Run "sbt12 test" on the command line: Project is compiled, test are succesfully run, but the command prompt does not reappear - program hangs
3.) Run sbt12 and then test on the sbt prompt. Test are executed, but the sbt prompt does not reappear - program hangs

It also hangs if there is a task - like assembly from the sbt-assembly plugin - that depends on test:Test. It will execute the tests, but hang after that (before creating assembly, that is).

For me this is a bug, since it used to work. Therefore I would like you to reopen this report. If you think is not a bug. but desired behavior, I'd be glad to hear some arguments.
