### ISSUE TITLE
[1.3.0-RC4] tab completion regression

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt#4989]
## steps

sbt version: 1.3.0-RC4

```
> set scalaVer[TAB KEY]
```

### sbt 1.3.0-RC4

![sbt-1.3](https://user-images.githubusercontent.com/389787/63772458-1166f600-c914-11e9-93c9-e603d48e430b.gif)

sbt suggest `scalaVersion` and `;`  😢 

### sbt 1.2.8

![sbt-1.2.8](https://user-images.githubusercontent.com/389787/63772575-55f29180-c914-11e9-90d5-96deaf6b5a10.gif)

## expectation

completion `scalaVersion`

## notes

@eatkins introduce some multi command improvements since 1.3.x.

- https://github.com/sbt/sbt/pull/4456
- https://github.com/sbt/sbt/pull/4811
- https://github.com/sbt/sbt/pull/4838

**Comment by eed3si9n** [comment]
@xuwei-k Thanks for the report. I think it makes sense to exclude `;` from the suggestion
