### ISSUE TITLE
SBT, Jetty and Servlet 3.0

### ISSUE THREAD

**Issue by hrj** [sbt/sbt#499]
The issue is well describe here:
http://stackoverflow.com/questions/9889674/sbt-jetty-and-servlet-3-0

To summarize:

Adding,

```
libraryDependencies += "org.eclipse.jetty" % "jetty-webapp" % "8.1.2.v20120308"
```

to a project causes this:

```
[warn]  [NOT FOUND  ] org.eclipse.jetty.orbit#javax.servlet;3.0.0.v201112011016!javax.servlet.orbit (603ms)
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/org/eclipse/jetty/orbit/javax.servlet/3.0.0.v201112011016/javax.servlet-3.0.0.v201112011016.orbit
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::              FAILED DOWNLOADS            ::
[warn]  :: ^ see resolution messages for details  ^ ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.eclipse.jetty.orbit#javax.servlet;3.0.0.v201112011016!javax.servlet.orbit
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[error] {file:/C:/dev/tueet/}default-d5e982/*:update: sbt.ResolveException: download     failed: org.eclipse.jetty.orbit#javax.servlet;3.0.0.v201112011016!javax.servlet.orbit
```

The root of the problem is desribed in this bug:
https://jira.codehaus.org/browse/JETTY-1493

The recommended fix:

``` scala
ivyXML := 
<dependency org="org.eclipse.jetty.orbit" name="javax.servlet" rev="3.0.0.v201112011016">
  <artifact name="javax.servlet" type="orbit" ext="jar"/>
</dependency>
```

has no effect for me. I even tried:

``` scala
ivyXML := 
<dependencies>
  <dependency org="org.eclipse.jetty.orbit" name="javax.servlet" rev="3.0.0.v201112011016">
    <artifact name="javax.servlet" type="orbit" ext="jar"/>
  </dependency>
</dependencies>
```

Still no luck. I have also tried

``` bash
rm -r ~/.ivy2/cache/org.eclipse.jetty*
rm ~/.ivy2/cache/*.properties
rm ~/.ivy2/cache/*.xml
```

Still, no luck.

**Comment by harrah** [comment]
Yes, the abuse of `<packaging>` is unfortunate.  For the workaround, in addition to the explicit artifact, you need to indicate that you want that type on the classpath:

``` scala
classpathTypes += "orbit"
```

Also, you don't need the XML if you don't want it.  The `artifacts` method on ModuleID can be used here.  See also #463, and this thread: https://groups.google.com/forum/#!topic/simple-build-tool/AYLw15EJcvg

**Comment by hrj** [comment]
Thanks Mark for the quick response.

Sorry for being a little dense, but can I use the workarounds with sbt 0.11.3 or do I have to use a version with your referenced commit?

I tried the following with sbt 0.11.3 to no avail:

```
"org.eclipse.jetty" % "jetty-webapp" % "8.1.4.v20120524" % "container" artifacts (Artifact("jetty-webapp", "jar", "jar"))
```

That may be because I was not able to successfully do this:

```
classpathTypes += "orbit"
```

The error was:

```
build.sbt:22: error: No implicit for Append.Value[Set[String], java.lang.String] found,
  so java.lang.String cannot be appended to Set[String]
classpathTypes += "orbit"
```

Is that supported in 0.11.3 ?

**Comment by harrah** [comment]
Sorry, that must have been added in 0.12.  In 0.11, make the addition explicit:

``` scala
classpathTypes <<= classpathTypes.apply {
  (ct: Set[String]) => ct + "orbit"
}
```

or the shorter version:

``` scala
classpathTypes ~= (_ + "orbit")
```

**Comment by hrj** [comment]
Thanks; that was accepted by sbt 0.11.3. But the result is still the same.

Can you please try this yourself? A very simple build file reproduces this error:
https://gist.github.com/3062255

**Comment by harrah** [comment]
The `artifacts` method overrides the artifacts defined in the metadata (pom.xml), so it goes on the dependency being modified.  Here, that dependency is 'javax.servlet' and not 'jetty-webapp'.

``` scala
libraryDependencies ++= Seq(
  "org.eclipse.jetty.orbit" % "javax.servlet" % "3.0.0.v201112011016" artifacts (
    Artifact("javax.servlet", "jar", "jar")
  )
)
```

**Comment by mheese** [comment]
Jesus, thanks a lot guys! Anyway, even though everything is written in the comments, it took me hours to solve it... if someone like me is searching for the exact lines, here you go:

``` scala
classpathTypes ~= (_ + "orbit")

libraryDependencies ++= Seq(
  "org.eclipse.jetty.orbit" % "javax.servlet" % "3.0.0.v201112011016" % "container" artifacts (Artifact("javax.servlet", "jar", "jar")
  )
)

libraryDependencies ++= Seq(
  "org.eclipse.jetty" % "jetty-webapp" % "8.1.4.v20120524" % "container" artifacts (Artifact("jetty-webapp", "jar", "jar"))
)
```

**Comment by harrah** [comment]
I expect you don't need the first setting.  It is only required if you declare the artifact to have type "orbit" like in the original post (only "jar" is used here).  The third setting probably doesn't need 'artifacts' because that should be the default artifact for jetty-webapp already.

**Comment by ritschwumm** [comment]
right, this seems to work

```
libraryDependencies ++= Seq(
    "org.eclipse.jetty.orbit"   % "javax.servlet"   % "3.0.0.v201112011016" % "provided"    artifacts Artifact("javax.servlet", "jar", "jar"),
    "org.eclipse.jetty"         % "jetty-webapp"    % "8.1.5.v20120716"     % "container"
)
```

the only problem i still have now is the classes form the javax.servlet package don't seem to be on the classpath, so i cannot compile code depending on these. i'd have expected the javax.servlet dependency to be in "provided" instead of "container" - but that just leads to a slightly different error message:

```
[info] downloading http://repo1.maven.org/maven2/org/eclipse/jetty/orbit/javax.servlet/3.0.0.v201112011016/javax.servlet-3.0.0.v201112011016.jar ...
[info]  [SUCCESSFUL ] org.eclipse.jetty.orbit#javax.servlet;3.0.0.v201112011016!javax.servlet.jar (660ms)
[warn]  [NOT FOUND  ] org.eclipse.jetty.orbit#javax.servlet;3.0.0.v201112011016!javax.servlet.orbit (0ms)
```

what am i doing wrong?

**Comment by arosien** [comment]
projects depending on a project with this workaround also need to do the workaround, it does not pass along the chain :(

**Comment by oolekk** [comment]
didn't work for me on sbt 0.12. any clue why?

```
[warn]  [NOT FOUND  ] org.eclipse.jetty.orbit#javax.servlet;3.0.0.v201112011016!javax.servlet.orbit (203ms)
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/org/eclipse/jetty/orbit/javax.servlet/3.0.0.v201112011016/javax.servlet-3.0.0.v201112011016.orbit
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::              FAILED DOWNLOADS            ::
[warn]  :: ^ see resolution messages for details  ^ ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.eclipse.jetty.orbit#javax.servlet;3.0.0.v201112011016!javax.servlet.orbit
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[trace] Stack trace suppressed: run last *:update for the full output.
[error](*:update) sbt.ResolveException: download failed: org.eclipse.jetty.orbit#javax.servlet;3.0.0.v201112011016!javax.servlet.orbit
```

**Comment by oolekk** [comment]
this worked for me:

```scala
"org.eclipse.jetty" % "jetty-webapp" % "8.1.7.v20120910" % "container,compile",
"org.eclipse.jetty.orbit" % "javax.servlet" % "3.0.0.v201112011016" % "container,compile" artifacts Artifact("javax.servlet", "jar", "jar"),
```

thx to Marko

**Comment by zvozin** [comment]
To confirm, this works in SBT 0.12.0:

``` scala
libraryDependencies ++= Seq(
    "org.eclipse.jetty" % "jetty-webapp" % "8.1.7.v20120910" % "container,compile",
    "org.eclipse.jetty.orbit" % "javax.servlet" % "3.0.0.v201112011016" % "container,compile" artifacts Artifact("javax.servlet", "jar", "jar"))
```

**Comment by laurilehmijoki** [comment]
For me, using the version `8.1.0.v20120127` solved this problem.

E.g.: `"org.eclipse.jetty" % "jetty-webapp" % "8.1.0.v20120127" % "test, container"`.

**Comment by harrah** [comment]
Note that this issue is fixed in sbt 0.12.2 and later.  The older jetty version probably works because it was before the metadata change.  Newer versions of jetty should be usable in sbt versions before 0.12.2 with the workaround in https://github.com/sbt/sbt/issues/499#issuecomment-8794028.

**Comment by ldeck** [comment]
@harrah it seems the work around is still necessary in sbt 0.12.4 

```scala
libraryDependencies += 
"org.eclipse.jetty"        % "jetty-webapp"   % "8.1.12.v20130726" % "container"
```

```
[warn]  [NOT FOUND  ] org.eclipse.jetty.orbit#javax.servlet;3.0.0.v201112011016!javax.servlet.orbit (78ms)
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/org/eclipse/jetty/orbit/javax.servlet/3.0.0.v201112011016/javax.servlet-3.0.0.v201112011016.orbit
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::              FAILED DOWNLOADS            ::
[warn]  :: ^ see resolution messages for details  ^ ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.eclipse.jetty.orbit#javax.servlet;3.0.0.v201112011016!javax.servlet.orbit
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by harrah** [comment]
@ldeck If sbt <0.12.2 was used to get this dependency, the bad metadata in the cache won't be invalidated.  Try removing `~/.ivy2/cache/org.eclipse.jetty.orbit` and reresolving.

**Comment by n8han** [comment]
I'm running into this problem when using the 0.13.0 launcher to resolve an app artifact that, transitively, depends on the dreaded "orbit" artifact from [this launchconfig](https://github.com/n8han/pamflet/blob/beta/src/main/conscript/pf/launchconfig). Doesn't seem like the fix to sbt applies to its launcher.

Any ideas?

**Comment by harrah** [comment]
You're right, it doesn't apply to the launcher.  The complicated workarounds required for issues like this don't get applied to the launcher for various reasons.  You can open a separate bug or a bug for unifying the sbt-side Ivy support with the launcher's.  Honestly, I'm not sure either of those will happen anytime soon.  If the issue is fixed by upgrading to the latest Ivy, it might be covered by #847.

If you can describe how to see the issue with the launchconfig (is it just a resolve error or is it a later linkage error or something?) I'll see if there is a workaround in your case.

**Comment by n8han** [comment]
I found a workaround: https://github.com/n8han/pamflet/commit/71f542c6ebb7dd77a29ae3fe42c57ee4905b7efc

:)

**Comment by harrah** [comment]
Ok, great.  Sorry for the trouble.

**Comment by behrad** [comment]
Can someone elaborate on this?
https://github.com/hawtio/hawtio/issues/122#issuecomment-58786410
