### ISSUE TITLE
sbt 0.13.x binaries aren't on maven central

### ISSUE THREAD

**Issue by eatkins** [sbt/sbt#4993]
## steps
Try to run a 0.13.x project, like https://github.com/sbt/launcher, without having any 0.13.x binaries in the .ivy or coursier caches.

## problem
sbt won't load because the typesafe repo isn't serving requests at the moment.

## expectation
sbt resolves the needed artifacts from maven and starts up.

**Comment by shadaj** [comment]
Seeing the same issue for 1.2.4, see https://travis-ci.com/shadaj/scalapy/builds/124800185

**Comment by eed3si9n** [comment]
I think there was a problem on our redirect proxy. It should be fixed now.
