### ISSUE TITLE
SBT not found

### ISSUE THREAD

**Issue by Sascha999** [sbt/sbt#50]
Hello,

I want to use SBT to compile a Maven project.

The Problem ist alwas that SBT don't find lift. If I add a project.scala the loading of the project fails. The SBT Console does not find "import sbt._" . I recreate projects many times but it does not work.

Sascha

**Comment by ijuma** [comment]
You haven't included enough detail for someone to be able to help you. I suggest sending an email to the mailing list (https://groups.google.com/forum/#!forum/simple-build-tool) with a detailed description of what you have tried, what your build file looks, what you expected and what actually happened.
