### ISSUE TITLE
xsbt does not automatically pick up *.jnilib (Mac OS X JNI lib files) from the unmanaged lib folder

### ISSUE THREAD

**Issue by mallman** [sbt/sbt#500]
I noticed from main/Defaults.scala that *.so and *.dll native libs are added to unmanagedJars by default. Can you add *.jnilib to this list? Mac OS X's Java requires jni libs to have that extension. See

http://developer.apple.com/library/mac/technotes/tn2147/_index.html#//apple_ref/doc/uid/DTS10003827-CH1-BUILDING

Hopefully this can make it into 0.12.

Cheers.

**Comment by indrajitr** [comment]
Makes sense, added on 0.13. Whether this can make it to 0.12 this late is for @harrah to decide.

**Comment by harrah** [comment]
It is not a regression so it is too late for 0.12.0.  It can go into 0.12.1.

**Comment by mallman** [comment]
Thanks guys!
