### ISSUE TITLE
Upgrade To Latest Version of Protobuf

### ISSUE THREAD

**Issue by mikail-khan** [sbt/sbt#5001]
See [this](https://github.com/protocolbuffers/protobuf/issues/6512) issue.

**Comment by eed3si9n** [comment]
@co-category This is a duplicate of https://github.com/sbt/zinc/issues/459, which has been fixed in 1.3.x. Please try 1.3.0-RC4.

**Comment by mikail-khan** [comment]
Can't upgrade to sbt version >= 1.0 where I work so it would be good to backport the fix if you can to pre-1.0 versions if possible.
