### ISSUE TITLE
Test results XML malformed in legacy file name format

### ISSUE THREAD

**Issue by mkljakubowski** [sbt/sbt#5003]
## Steps
sbt version: 1.2.8 (doesn't occur on 1.1.6)
scala: 2.13
play: 2.7.3
os: win, linux, osx
run tests in sbt

## Problem
Test results of file prefixed with "TEST-" are sometimes malformed. It looks like they are written 1.5x to the file, which makes the file unparsable. 

Example
```
<?xml version='1.0' encoding='UTF-8'?>
<testsuite tests="9"
           errors="0" failures="0" skipped="0" time="1">
    <properties>
    </properties>
    <testcase classname="xxx"
              name="yyy"
              time="1">
    </testcase>
    <system-out><![CDATA[]]></system-out>
    <system-err><![CDATA[]]></system-err>
</testsuite>m-out><![CDATA[]]></system-out>
<system-err><![CDATA[]]></system-err>
        </testsuite>
```
Note stuff `m-out>...`

## Expectation
All test results should be valid XML.

## Notes
I think it was introduced with #4343, which makes the test results run twice.
It occurs only on one project using sbt 1.2.8 Others have duplicated test results, as expected, and they are all valid XML.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/5017
