### ISSUE TITLE
Temporary files not deleted

### ISSUE THREAD

**Issue by bytbox** [sbt/sbt#502]
Temporary files (created in /tmp on my system) are not deleted after each run by sbt, eventually filling up the partition and breaking things.

**Comment by harrah** [comment]
I don't see temporarily files accumulate.  There is a temporary directory that doesn't get deleted, but it is empty (and I will fix it not getting deleted).  If sbt shuts down abnormally, it displays a message like:

```
sbt appears to be exiting abnormally.
  The log file for this session is at /tmp/sbt823985.log
```

and the log file will not be deleted.  Other than that, I don't see temporary files hanging around.
