### ISSUE TITLE
[1.3.0] Cannot download dependencies with absolute domain names (domain names ending in '.')

### ISSUE THREAD

**Issue by henricook** [sbt/sbt#5030]
## Steps
sbt version: 1.3.0

## Problem

We have an internal dependency mirror that uses an FQDN:

http://dep-proxy.cluster.local.:8000/jcenter.bintray.com/io/gatling/gatling-sbt_2.12_1.0/3.0.0/gatling-sbt-3.0.0.pom

On SBT 1.2.8 dependencies downloaded fine, on 1.3.0 you get this error:

```
[error]   download error: Caught java.lang.IllegalArgumentException: illegal IPv4 address (illegal IPv4 address) while downloading http://dep-proxy.cluster.local.:8000/jcenter.bintray.com/io/gatling/gatling-sbt_2.12_1.0/3.0.0/gatling-sbt-3.0.0.pom
```

## Expectation

Dependencies download fine from FQDN URLs

## Workarounds

- Disable coursier in 1.3.0 to restore 1.2.8 behaviour
- Stop using FQDNs

**Comment by SethTisue** [comment]
interesting — first I'm hearing that such domain names exist

presumably this would need to be fixed upstream, in Coursier

**Comment by henricook** [comment]
Indeed! When a hostname's defined in the hosts file on a machine I believe doing it this way can save any dns searches although tbh, I'm not the one who put it in place on our project.

I probably didn't understand the coursier SBT relationship as well as I do now when I created this so if you think it's worth creating over there instead I can do that

**Comment by SethTisue** [comment]
> if you think it's worth creating over there instead I can do that

well, I really cannot guess the likelihood of someone actually attempting a fix. but I believe such tickets are worthwhile regardless. note that the ticket, if you open one, should include a Coursier-only reproduction of the problem. (Coursier is both a library and a CLI tool; a CLI-based reproduction would be sufficient, and probably easier to construct than an API-based one)
