### ISSUE TITLE
SBT 1.3.0 in IntelliJ idea takes about 40 minutes to dump project

### ISSUE THREAD

**Issue by yinshurman** [sbt/sbt#5034]
## steps
sbt version: *1.3.0*

## problem
although I know that SBT is very slow and hard to use, but 
sbt 1.3.0 in IntelliJ idea takes about more than 40 minutes to dump project, is it an exception or just normal case for SBT ?

## notes

**Comment by plokhotnyuk** [comment]
@yinshurman AFAIK sbt 1.3.0 uses a new dependency resolver with own cache directory, but it provides an option to use the previous one, see the following article for details: https://www.lightbend.com/blog/sbt-1.3.0-release

**Comment by yinshurman** [comment]
@plokhotnyuk  thanks , follow the doc,I add the line `ThisBuild / useCoursier := false`, it completed the dump task in 2min !!!!

**Comment by plokhotnyuk** [comment]
@yinshurman please also check how much it takes to dump after renaming of cache directory for the old resolver from `~/.ivy2` to `~/.ivy2-backup`.

**Comment by yinshurman** [comment]
@plokhotnyuk   I just killed the task after waiting more than 20mins dumping  with ~/.ivy2 renamed to ~/.ivy2-backup, and I checked the directory size of ~/.ivy2-backup, it is more than 2.5G!
It seems that the 2mins completion  is due to the cache, but  i just write the follow spark dependencies,

```
    libraryDependencies += "org.apache.spark" %% "spark-core" % "2.3.0",

    libraryDependencies += "org.apache.spark" %% "spark-sql" % "2.3.0",

    libraryDependencies += "org.apache.spark" %% "spark-mllib" % "2.3.0",

    libraryDependencies += "com.microsoft.ml.spark" %% "mmlspark" % "0.18.1"```

**Comment by eed3si9n** [comment]
Yea. so sbt 1.3.0 changed to Coursier to you might need to re-resolve your dependencies. I don't know why that takes 40 minutes unless someone is throttling your network.
