### ISSUE TITLE
rsync errors when starting sbt-1.3.0

### ISSUE THREAD

**Issue by vn971** [sbt/sbt#5035]
## steps
* upgrade sbt to version: 1.3.0 (on version 1.2.8 everything is OK)
* start sbt in any project (tested on 2 different projects)

## problem
SBT prints this in console when starting:
```
rsync: chgrp "/home/vasya/.sbt/preloaded/." failed: Invalid argument (22)
rsync: chgrp "/home/vasya/.sbt/preloaded/com" failed: Invalid argument (22)
rsync: chgrp "/home/vasya/.sbt/preloaded/com/eed3si9n" failed: Invalid argument (22)
rsync: chgrp "/home/vasya/.sbt/preloaded/com/eed3si9n/gigahorse-core_2.12" failed: Invalid argument (22)
... about 100-200 lines like that ...
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1189) [sender=3.1.3]
[info] Loading settings for project global-plugins from plugins.sbt,idea.sbt ...
[info] Loading global plugins from /home/vasya/.sbt/1.0/plugins
[info] Loading settings for project ***** from plugins.sbt ...
```
Then it starts seemingly normally. `test:compile` works, for example. Maybe it wouldn't work if I wouldn't have `~/.sbt/preloaded` already present though.

## expectation
same behavior as on 1.2.8, e.g. no problems.

## notes
java version is `java-8-openjdk`, OS is ArchLinux.

`sbt` is used from the official Arch repos:
https://www.archlinux.org/packages/community/any/sbt/
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/sbt

**Comment by eed3si9n** [comment]
@vn971 Thanks for the report! I think it worked ok on Ubuntu, so is there something I did weird that's making Arch mad?

Side note. The layout of the preloaded changed to Maven in sbt 1.3.0 because of https://github.com/sbt/sbt/issues/4661.

**Comment by eed3si9n** [comment]
Google says https://serverfault.com/questions/213647/rsync-fails-to-backup-some-files-giving-error-22. Is there FAT32 or NTFS involved?

**Comment by vn971** [comment]
@eed3si9n nope, certainly no FAT32 or NTFS... Just the usual `ext4`.

**Comment by vn971** [comment]
The bug apparently happens because SBT is invoked in a user namespace (on my system). Having that in mind, maybe we can understand more on why the bug happens? Where does this `rsync` happen? Maybe I can help. I tried to search: https://github.com/sbt/sbt/search?q=rsync&type=Issues  but no results in code.

**Comment by vn971** [comment]
Before 1.3.0 it worked fine in a user namespace, so it certainly sounds like something fix-able to me. (And it still works fine if I just use the later version for now.)

**Comment by eed3si9n** [comment]
Forgot to reply on this. Currently bash scripts are in https://github.com/sbt/sbt-launcher-package.

See https://github.com/sbt/sbt-launcher-package/pull/315

**Comment by vn971** [comment]
@eed3si9n thanks! I possibly found the reason. SBT does this command internally:
```
rsync -a --ignore-existing "$source_preloaded" "$target_preloaded" || true
```
rsync expands the `-a` flag into `-rlptgoD`. The `-o` flag (meaning `--owner`) is what makes it break in a user namespace. Can we maybe remove the flag `-o` and thus write `rsync -rlptgD`? This would allow the tool to work inside a user namespace, if I understand things correctly.

Thoughts?

**Comment by eed3si9n** [comment]
Sounds good to me.

**Comment by eed3si9n** [comment]
Here's my PR for this - https://github.com/sbt/sbt-launcher-package/pull/316

**Comment by vn971** [comment]
Thanks! This should work I think. Especially dropping all unnecessary flags, keeping only the minimum required. Awesome.

**Comment by vn971** [comment]
Confirming that the fix works! :tada:
sbt-1.3.6 starts up and runs without any warnings.

**Comment by eed3si9n** [comment]
Awesome. Thanks for the confirmation.
