### ISSUE TITLE
java.lang.ClassNotFoundException is thrown when creating a new class instance after main thread has finished

### ISSUE THREAD

**Issue by marq** [sbt/sbt#5036]
## steps
sbt version: 1.3.0
scala version: 2.12.9

## problem
java.lang.ClassNotFoundException is thrown when creating a new class instance in non-main thread after main thread has finished.

```scala
package sbttest

object App {
	def main(args: Array[String]): Unit = {
		new Thread {
			override def run(): Unit = {
				Thread.sleep(1000)
				new A
			}
		}.start()
	}
}

class A
```

```
[info] running sbttest.App 
[error] (Thread-2) java.lang.NoClassDefFoundError: sbttest/A
[error] java.lang.NoClassDefFoundError: sbttest/A
[error]         at sbttest.App$$anon$1.run(App.scala:8)
[error] Caused by: java.lang.ClassNotFoundException: sbttest.A
[error]         at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
[error] bt-test at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
[error] 	at sbttest.App$$anon$1.run(App.scala:8)
```

## expectation
It should work.

## notes
The test case works correctly if I downgrade sbt to version 1.2.8 or change it so `main` waits for the created thread to end (`.join()`).

**Comment by eatkins** [comment]
@marq this is an intentional change. You can revert to the sbt 1.2.8 behavior by running sbt with `-Dsbt.classloader.close=false`.

**Comment by marq** [comment]
Well, I wish this was easier to find. I've spent hours to find out why my application is crashing after updating sbt. I'm closing this then.

**Comment by eatkins** [comment]
Apologies. This should have been in the release notes. @eed3si9n can we add this?

**Comment by eed3si9n** [comment]
@eatkins sure. if you could email me the wording, and I'll edit the blog.
