### ISSUE TITLE
Multi command hides parser error message and turns it into Expected ';' (semicolon)

### ISSUE THREAD

**Issue by jsoref** [sbt/sbt#5039]
## steps
sbt version: 1.3.0
(brew install sbt@1.3.0)

## problem
```
sbt -Dsbt.ci=true -Dsbt.banner=false
...
sbt:foo> coursierUseSbtCredentials := true;
[error] Expected ';'
[error] coursierUseSbtCredentials := true
[error]                                  ^
sbt:foo>
```

## expectation
Helpful error? Preferably something that doesn't tell me I should put in a `;` right where I put in a `;` ...

## notes
I'm trying to figure out how to use coursier w/ 1.3.0, but I don't really understand sbt or coursier, so I'm going to make lots of mistakes (and enter random text everywhere).

## notes by eed3si9n

Ref 
- #4989
- https://github.com/sbt/sbt/pull/4456
- https://github.com/sbt/sbt/pull/4811
- https://github.com/sbt/sbt/pull/4838

**Comment by eed3si9n** [comment]
@jsoref Thanks for the report.
This seems to be related to another semicolon bug - https://github.com/sbt/sbt/issues/4989

**Comment by eed3si9n** [comment]
The expectation should be the same error message as sbt 1.2.8:

```
sbt:Test> coursierUseSbtCredentials := true
[error] Expected ID character
[error] Not a valid command: coursierUseSbtCredentials
[error] Expected project ID
[error] Expected configuration
[error] Expected ':'
[error] Expected key
[error] Not a valid key: coursierUseSbtCredentials (similar: credentials)
[error] coursierUseSbtCredentials := true
[error]                          ^
```

**Comment by eed3si9n** [comment]
It's bit of a complicated situation. We do need a `multi` command that can process `compile;test;`, but at the same time, we need to keep it out of tab completion and parser errors when the input string does not include `;`.

This might mean that we can't just `|` together the parsers like we are doing now.

**Comment by jroper** [comment]
I guess the problem is that the multi parser isn't being `|`'ed in, since `|` should result in error messages being combined, instead maybe it's being applied after the main parser fails?
