### ISSUE TITLE
GC thrashing can cause silent hangs

### ISSUE THREAD

**Issue by eatkins** [sbt/sbt#5044]
This is more of a feature idea than an issue. Sometimes sbt will become unresponsive because it's stuck in a full GC loop. I've been thinking of adding a GC monitor that will print warnings to the console if sbt is spending a lot of time in GC. The JDK provides tools that should make this relatively straightforward.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/5812
