### ISSUE TITLE
sbt sets -XX:+UseParallelGC for jdk >= 9

### ISSUE THREAD

**Issue by eatkins** [sbt/sbt#5045]
The launcher script explicitly sets `-XX:+UseParallelGC` for jdk greater than 9. This isn't a great default because while the peak throughput is somewhat better than the default g1 collector, the worst case performance is better with g1 -- especially with large heaps. It makes sense to set the conservative default and lets users explicitly set parallel gc if they want maximum throughput. In my experiments, the upside of parallel gc is only 5-10% compared to g1 while in some projects compile will take minutes to run with parallel gc compared to seconds or tens of seconds using g1 because the parallel gc process gets stuck in gc thrashing cycles.

**Comment by plokhotnyuk** [comment]
It would be better to increase young gen part of the heap, metaspace and compiled code cache sizes then keep working hard to reduce allocations and use best technologies/algorithms instead of switching to GCs which trade offs better latency by reducing throughput.

**Comment by eatkins** [comment]
@plokhotnyuk I respectfully disagree completely.

**Comment by plokhotnyuk** [comment]
@eatkins could you peek a couple of projects, tune them for shorter build time by switching to G1 GC and share results with steps to reproduce?

**Comment by eed3si9n** [comment]
When JDK 9 came out, it was considered more conservative to stay with `-XX:+UseParallelGC` because Scala compilation slowed down significantly under G1GC as reported in https://github.com/sbt/sbt/issues/3559.

Under JDK 11 and later G1GC has supposedly improved (http://mail.openjdk.java.net/pipermail/hotspot-gc-use/2018-June/002759.html), so I think getting back to not imposing opinions sounds good to me since sbt sessions are meant to run for a long time, and also the long pause of GC has severely negative UX, and often people would blame sbt or the compiler for it.

Advanced users who are fans of `-XX:+UseParallelGC` or any other form of JVM tuning can always specify those flags on their own.

**Comment by eatkins** [comment]
I can induce issues with ParallelGC using jdk 13 in https://github.com/ThoughtWorksInc/dsl.scala. Running
`++2.11.12; clean; test` I got the following results:
g1gc:
```
java -Xmx1500m -XX:+UseG1GC -verbose:gc -jar  -Dsbt.version=1.4.0-SNAPSHOT   699.15s user 27.00s system 307% cpu 3:56.17 total
```
parallel:
```
java -Xmx1500m -XX:+UseParallelGC -verbose:gc -jar   "++2.11.12;clean;test"  1370.69s user 26.38s system 398% cpu 5:50.87 total
```
The parallel run actually gc thrashed for 2 minutes and then crashed with `java.lang.OutOfMemoryError: GC overhead limit exceeded`. While thrashing, this was all that you would see in the output:
```
[295.010s][info][gc] GC(270) Pause Full (Ergonomics) 1166M->1146M(1331M) 899.830ms
[296.047s][info][gc] GC(271) Pause Full (Ergonomics) 1166M->1150M(1333M) 921.144ms
[296.961s][info][gc] GC(272) Pause Full (Ergonomics) 1166M->1154M(1331M) 814.414ms
[297.847s][info][gc] GC(273) Pause Full (Ergonomics) 1166M->1156M(1333M) 825.885ms
[298.734s][info][gc] GC(274) Pause Full (Ergonomics) 1166M->1158M(1331M) 840.570ms
[299.603s][info][gc] GC(275) Pause Full (Ergonomics) 1166M->1160M(1333M) 845.544ms
[301.397s][info][gc] GC(276) Pause Full (Ergonomics) 1166M->1161M(1331M) 1768.094ms
[303.008s][info][gc] GC(277) Pause Full (Ergonomics) 1166M->1162M(1333M) 1591.822ms
```
If verbose:gc were off, this would have manifested as two minutes of sbt appearing to do nothing and then crashing.


With a 2GB heap, G1GC was about 10% faster running `;clean;+test` in 7 mins vs 7.5 mins for ParallelGC.
