### ISSUE TITLE
sys.exit and exit do not work in console mode

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#505]
## steps
1. `set scalaVersion := "2.9.1"` to work around #504.
2. go into `console` mode.
3. type in `sys.exit` or `exit`.
## problem

Neither of them exits me out of console mode.

```
scala> sys.exit
null

scala> exit
<console>:8: warning: method exit in object Predef is deprecated: Use sys.exit() instead
              exit
              ^
null
```
## expectation

console mode behaves like Scala REPL and exits.

```
$ scala
Welcome to Scala version 2.10.0-M5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.6.0_33).
Type in expressions to have them evaluated.
Type :help for more information.

scala> exit
warning: there were 1 deprecation warnings; re-run with -deprecation for details
$ 
```

**Comment by harrah** [comment]
Works in Scala 2.10, can't workaround on sbt side due to REPL trapping the exception.
