### ISSUE TITLE
[1.3.0 Coursier] unresolved dependencies

### ISSUE THREAD

**Issue by kamilkloch** [sbt/sbt#5050]
Sbt version: 1.3.0

### Problem:
```sbt
resolvers += Resolver.url("...", url("http://..."))
  (Patterns("[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]")).withAllowInsecureProtocol(true),
```
sbt 1.3.0 with Coursier enabled fails to resolve some dependencies:
```
[error]   not found: http://[...]/x-logback-access/0.1/x-logback-access-0.1.pom
``` 
(If this helps, `.pom` file is not present, as it is an ivy, not maven repository).

Disabling Coursier (`ThisBuild / useCoursier := false`) solves the problem.

**Comment by eed3si9n** [comment]
@kamilkloch Thanks for the report.
Do you mind reporting this also to the upstream plz? (Coursier)

**Comment by kamilkloch** [comment]
@eed3si9n Please check if the Coursier issue https://github.com/coursier/coursier/issues/1351 is correct. Thanks!

**Comment by kamilkloch** [comment]
Update: problem persists in sbt 1.3.4. It looks that for ivy repo coursier expects url of the form
```
ivy:http://
```
yet sbt rejects it as a malformed url. 
(Command-line coursier properly resolves the ivy repo with `ivy:http://`).

**Comment by eed3si9n** [comment]
That's interesting. So maybe we can work around this by translating Ivy URL resolver to `ivy:http://` style Coursier repository?

**Comment by kamilkloch** [comment]
If it works both for the 'old and 'new' (coursier) artifact fetching, it would be fantastic. 

FYI, quoting from the coursier web page (https://get-coursier.io/docs/cli-overview.html#usage):

Repositories starting with ivy: are assumed to be Ivy repositories, specified with an Ivy pattern, like ``ivy:https://repo.typesafe.com/typesafe/ivy-releases/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]``. Else, a Maven repository is assumed.

**Comment by kamilkloch** [comment]
I found a workaround here: https://github.com/sbt/librarymanagement/blob/50ca3902c379cf4056ec2a677dfe7fd30c3640cc/core/src/main/scala/sbt/librarymanagement/ResolverExtra.scala#L37

Custom Ivy repo in Coursier works by setting the `isMavenCompatible` flag to `false`:
```
resolvers += Resolver.url("...", url("http://..."))
  (Patterns(false, "...."))
```
