### ISSUE TITLE
How do you use clearOnTrigger?

### ISSUE THREAD

**Issue by lespea** [sbt/sbt#5051]
## steps
sbt version: 1.3.0

## problem
The deprecation warning for clearWehnTriggered says to use watchTriggeredMessage && clearOnTrigger but this doesn't appear to be documented anywhere?  In fact the only place I can find clearOnTrigger in the code base is in the deprecation message.

I tried looking through the sbt site to find the new way to do this but couldn't find it.

## expectation
The new settings are easy to find / documented

## notes

Exact deprecation messages I'm getting:

```
[warn] {file}:23:7: value triggeredMessage in object Keys is deprecated (since 1.3.0): Use watchTriggeredMessage instead
[warn]       triggeredMessage := Watched.clearWhenTriggered,
[warn]       ^
[warn] {file}:23:35: value clearWhenTriggered in object Watched is deprecated (since 1.3.0): Use clearOnTrigger in conjunction with the watchTriggeredMessage key
[warn]       triggeredMessage := Watched.clearWhenTriggered,
```

**Comment by eatkins** [comment]
Thanks for the report. This was an oversight. We'll fix the deprecation message and documentation for 1.3.1. In the mean time, what you want is `watchTriggeredMessage := Watch.clearScreenOnTrigger`.

**Comment by eatkins** [comment]
Thanks again for the report and apologies for the confusion. Closing with #5054 and https://github.com/sbt/website/pull/813.

**Comment by lespea** [comment]
Awesome thanks!
