### ISSUE TITLE
do not duplicate artifacts in `allJars` when creating `ScalaInstance`

### ISSUE THREAD

**Issue by unkarjedy** [sbt/sbt#5052]
sbt 1.3.0

## problem
(I guess after migrating to Coursier)
`sbt update` output can contain duplicate artifacts with different configurations (e.g. "optional" and "default") in
```"configuration": { "name": "scala-tool" }```
sbt does not remove duplicates when creating `ScalaInstance`

## notes
relates to:
https://github.com/sbt/sbt/pull/3561
https://youtrack.jetbrains.com/issue/SCL-16208
https://youtrack.jetbrains.com/issue/SCL-16231

**Comment by anilkumarmyla** [comment]
@eed3si9n any timeline on 1.3.1 release? This issue broke the naive way of running tests through intellij without using sbt shell. Workaround is to use sbt shell in intellij

**Comment by eed3si9n** [comment]
I'm guessing in a week or two.
