### ISSUE TITLE
[1.3.0] Regression, consoleQuick is hopelessly broken

### ISSUE THREAD

**Issue by blast-hardcheese** [sbt/sbt#5057]
## steps
sbt version: 1.3.0

- Launch `sbt` (as in the gif)
- Type `consoleQuick` (it does not matter if you type other things beforehand)

## problem

Unable to type in `consoleQuick`

## expectation

Ability to type in `consoleQuick`

## notes

This appears to be directly related to supershell, as `-Dsbt.supershell=false` makes consoleQuick work again.

![sbt-1 3 0](https://user-images.githubusercontent.com/278900/64460235-c0db5f80-d0ae-11e9-835b-d92eda2fc46b.gif)

**Comment by eed3si9n** [comment]
@blast-hardcheese Thanks for the report!

**Comment by SethTisue** [comment]
I'm not able to reproduce this in sbt 1.8.2.
