### ISSUE TITLE
Build source monitoring is does not track sub/build.sbt files

### ISSUE THREAD

**Issue by eatkins** [sbt/sbt#5061]
The new feature in sbt 1.3.0 that build sources are monitored and sbt can optionally reload the build when sources change doesn't work with nested projects.

**Comment by eed3si9n** [comment]
Because of [sbt is recursive](https://www.scala-sbt.org/1.x/docs/Organizing-Build.html#sbt+is+recursive), I thought you meant `project/project/*.scala`.

**Comment by eatkins** [comment]
Yeah, that was probably an abuse of nomenclature. I thought about adding project/project/*.scala, etc. but it raises the question of how deep to go. At the moment, sbt 1.3.0 is polling the build sources so I'd rather not add a bunch of directories that might not contain any files. If we were asynchronously monitoring the build sources, we could more easily support fully recursive monitoring without degrading performance.
