### ISSUE TITLE
sbt new: console input isn't echoed

### ISSUE THREAD

**Issue by sidnt** [sbt/sbt#5063]
## steps
sbt version: *1.3.0*
On terminal `sbt new sbt/scala-seed.g8` asks for project name. When the name is entered, it is not echoed in realtime. It's like entering a password. You can't see what you've entered, until you hit return.

## problem
Console inputs are not echoed. Even if the program is run via sbt run, and the main takes an StdIo.readline(), the same isn't echoed as well.

## expectation
In sbt 1.2.8, the same flow, resulted in the name of project being fed back live on the screen, so that we could see what is being typed.

**Comment by eed3si9n** [comment]
@sidnt Thanks for the report!

**Comment by lrytz** [comment]
Saw the same when using sbt-bintray's `bintrayChangeCredentials`

**Comment by eed3si9n** [comment]
Maybe we need to use https://github.com/sbt/sbt/blob/v1.3.0/main/src/main/scala/sbt/CommandLineUIService.scala and pause super shell during user input.

**Comment by eed3si9n** [comment]
Actually I am not 100% sure if the issue of super shell overwriting is the same as input not echoing during sbt new.

**Comment by agilesteel** [comment]
Just posting for someone who is looking for a workaround until this gets fixed.
```sbt --supershell=false new scala/scala-seed.g8```

**Comment by ennru** [comment]
The problem shows with `sbt run` when you need to select a main class, as well.

**Comment by eed3si9n** [comment]
On my machine using sbt 1.3.2 + (macOS, iTerm, zsh), `sbt new sbt/scala-seed.g8` seems to echo fine.

I wonder if there's a specific combination that causes this.

**Comment by counter2015** [comment]
My environment: sbt 1.3.2 (windows, wsl ubuntu 18.04 ,bash), console input isn't echoed.

**Comment by zetashift** [comment]
On Ubuntu 19.04 x64, using ZSH and Konsole terminal, I currently have the same issue.
I'm using the workaround of `--supershell=false`.
I have the issue also with other new templates like Slinky's `sbt new shadaj/create-react-scala-app.g8`

**Comment by raboof** [comment]
Hrm, I cannot reproduce this problem on NixOS unstable, using bash, tried with xterm, Konsole and terminology.

**Comment by raboof** [comment]
I can reproduce this, but when I add an `.sbt` file to the current directory with *any* `addSbtPlugin` statement in it the problem goes away. Perhaps some timing thing?

**Comment by eed3si9n** [comment]
@eatkins and I discussed this issue in the meeting yesterday.
It's likely related to the timing of terminal reset / initialization (character buffering + no echo).

**Comment by raboof** [comment]
Sounds likely, though I checked with `script` and it doesn't appear to use terminal escape codes to control `echo`, so I guess that's handled 'internally' somewhere? (unless I misinterpreted that output)

**Comment by eed3si9n** [comment]
Here's reproduction steps using Docker:

```
[Ga:/tmp/hello]$ docker run -it --mount src="$HOME/.ivy2",target=/root/.ivy2,type=bind   hseeberger/scala-sbt:8u222_1.3.4_2.13.1
root@9a38941d5d93:~# cd /root
root@9a38941d5d93:~# sbt new sbt/scala-seed.g8 -Dsbt.version=1.4.0-SNAPSHOT
[info] [launcher] getting org.scala-sbt sbt 1.4.0-SNAPSHOT  (this may take some time)...
:: loading settings :: url = jar:file:/usr/share/sbt/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/usr/share/sbt/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/usr/share/sbt/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/usr/share/sbt/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: retrieving :: org.scala-sbt#boot-app
	confs: [default]
	81 artifacts copied, 0 already retrieved
[info] Set current project to root (in build file:/root/)
[info] Set current project to root (in build file:/root/)
[info] resolving Giter8 0.12.0...

A minimal Scala project.

name [Scala Seed Project]:
Template applied in /root/./aaa
```

**Comment by eed3si9n** [comment]
Here's my PR to fix this - https://github.com/sbt/sbt/pull/5295

**Comment by eshu** [comment]
The same bug in 1.4 :)

**Comment by counter2015** [comment]
> The same bug in 1.4

environment: mac, sbt 1.4.0
It seems like
```bash
sbt new lampepfl/dotty.g8
[info] welcome to sbt 1.4.0 (AdoptOpenJDK Java 14.0.2)
[info] loading global plugins from /Users/counter/.sbt/1.0/plugins
[info] loading project definition from /Users/counter/test/project
[info] set current project to test (in build file:/Users/counter/test/)
[info] set current project to test (in build file:/Users/counter/test/)

A template to demonstrate a minimal Dotty application 

name [Dotty Project Template]: 
Template applied in /Users/counter/test/./1122
``` 
The project name isn't echoed.

**Comment by eatkins** [comment]
@counter2015 did you try 1.4.2?

**Comment by counter2015** [comment]
@eatkins thanks, it worked!

**Comment by eugeniyk** [comment]
~same here on mac + ITerm + zsh with sbt 1.4.9~
upd - sbt version is taken from your env path and may be different from the version in template
so just to be sure, use newest version:
```sbt -sbt-version 1.5.3 new ...```
