### ISSUE TITLE
Create a means to add a repository to the default list at the project global level

### ISSUE THREAD

**Issue by JustinPihony** [sbt/sbt#5070]
Right now there is a way to override repositories entirely, but not append to the list. The feature I’m requesting is an ability to set a resolver for both plugins and project, which could then be checked into the codebase and used by subsequent developers seamlessly.

**Comment by eed3si9n** [comment]
Thanks Justin. I think this is a good idea. See there are similar situation that's happening for SuperSafe (https://github.com/sbt/sbt/issues/4103, http://www.scalatest.org/supersafe#installation) where it needs to configure the resolver for both the metabuild and the proper build.

What do you think about adding a key like:

```scala
ThisBuild / includePluginResolvers := true
```

that would inject plugin level resolver to all subprojects?

**Comment by JustinPihony** [comment]
Sounds good to me
