### ISSUE TITLE
[1.3.0] Can't use system properties with spaces anymore

### ISSUE THREAD

**Issue by kingslef** [sbt/sbt#5076]
## steps
sbt version: 1.3.0

After updating to 1.3.0, I can't use a system property that has space in it. Very easy to reproduce: start sbt in any project giving e.g. `-Dfoobar="foo bar"` as an option.

## problem
```sh
$ sbt -Dfoobar="foo bar" run
Error: Could not find or load main class bar
```
## expectation
System property is provided to sbt and sbt starts.

Using 1.2.8 directly from GitHub:
```sh
$ ~/Downloads/sbt-1.2.8/bin/sbt -Dfoobar="foo bar" run
[warn] No sbt.version set in project/build.properties, base directory: /private/tmp/foobar
[info] Loading settings for project global-plugins from idea.sbt,credentials.sbt,plugins.sbt,metals.sbt ...
[info] Loading global plugins from ~/.sbt/1.0/plugins
[info] Set current project to foobar (in build file:/private/tmp/foobar/)
[info] Updating ...
[info] Done updating.
[info] Packaging /private/tmp/foobar/target/scala-2.12/foobar_2.12-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
....
```

Using 1.3.0:
```
$ ~/Downloads/sbt-1.3.0/bin/sbt -Dfoobar="foo bar" run
Error: Could not find or load main class bar
```

## notes

There is a very similar issue in https://github.com/sbt/sbt/issues/3943, but that still exists in 1.2.8 where as giving system properties with `-D` worked.

As a workaround, `JAVA_OPTS`, `-J-Dfoobar="foo bar"` or `.jvmopts` don't seem to work, but [https://stackoverflow.com/a/21433585](this) works.

**Comment by eed3si9n** [comment]
@er1c Could this be related to https://github.com/sbt/sbt-launcher-package/commit/2d21c0fd2a67641f63e8e4f4f4b68772ae41fad1?

**Comment by eed3si9n** [comment]
@kingslef Thanks for the detailed bug report!

**Comment by kingslef** [comment]
> @er1c Could this be related to [sbt/sbt-launcher-package@2d21c0f](https://github.com/sbt/sbt-launcher-package/commit/2d21c0fd2a67641f63e8e4f4f4b68772ae41fad1)?

thanks for the pointer! but I don't think it is that commit, but one later that removed the quotes from `${java_args[@]}`. Anyway, https://github.com/sbt/sbt-launcher-package/pull/280 should fix this issue.
