### ISSUE TITLE
`sbt new` partially takes g8 template's .gitignore into account

### ISSUE THREAD

**Issue by Esardes** [sbt/sbt#5084]
## steps
sbt version: 1.3.0
create a g8 template with a `secret` folder in `src/main/g8`, a file `src/main/g8/secret/encrypted.conf` and a `src/main/g8/.gitignore` file that contains  
```
secret/*
!secret/encrypted.conf
```
Create a new project using the template and `sbt new`

## problem
The generated project does not contain the `secret` folder/the file `secret/encrypted.conf`

## expectation
The file `secret/encrypted.conf` should be present in the generated folder.

**Comment by eed3si9n** [comment]
Please open the issue on https://github.com/foundweekends/giter8 instead.
