### ISSUE TITLE
Strange NoClassDefFoundError error with SBT 1.3.0

### ISSUE THREAD

**Issue by OndrejSpanel** [sbt/sbt#5088]
## steps
sbt version: 1.3.0
Clone repository https://github.com/aganm/NoClassDefFoundError and use `sbt run`

## problem

Very simple project using `java.awt` throws `NoClassDefFoundError` exception.

## expectation

No exception should be thrown when running this project.

## notes

- the issue does not show with sbt 1.2.8
- the issue does not show when using `fork := true`
- originally asked as https://stackoverflow.com/questions/57960185/java-awt-in-scala-awt-eventqueue-0-java-lang-noclassdeffounderror

**Comment by eed3si9n** [comment]
@OndrejSpanel Thanks for the report. This is likely fixed in https://github.com/sbt/sbt/pull/5081. I also posted more details on Stackoverflow.

**Comment by eed3si9n** [comment]
This was fixed in sbt 1.3.2.
