### ISSUE TITLE
High CPU usage after run

### ISSUE THREAD

**Issue by palutz** [sbt/sbt#5089]
## steps
sbt version: 1.3.0

## problem
Running a simple console program to test some libs, sbt takes the CPU to 100% despite the program is not doing anything. It keeps the CPUs at 100% also if I quit the program (but I stay inside the sbt). Only way to stop is to quit sbt.
the actual command keeping the CPU us is: 
/usr/bin/java -Dfile.encoding=UTF-8 -Xmx2G -jar /usr/local/Cellar/sbt/1.3.0/libexec/bin/sbt-launch.jar

## expectation
when the program stops or quit, sbt should stop using all the resources.

## notes
MBP 2019, 16GB RAM
MacOsX Mojave 10.14.5
Homebrew 2.1.11
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
sbt = 1.3.0

My build.sbt
> name := "tryDeltaLake"
> organization in ThisBuild := ""
> version in ThisBuild := "0.1-SNAPSHOT"
> 
> scalaVersion in ThisBuild := "2.12.8"
> 
> val deltalake  = "io.delta" %% "delta-core" % "0.3.0"
> val sparkLibs  = Seq(
>     "org.apache.spark" %% "spark-core" % "2.4.2",
>     "org.apache.spark" %% "spark-sql" % "2.4.2"
>   )
> 
> lazy val tryDeltaLake = (project in file("."))
>   .settings(
>     name := "tryDeltaLake",
>     libraryDependencies ++= sparkLibs,
>     libraryDependencies += deltalake
> )
> 
>

**Comment by eed3si9n** [comment]
@palutz Thanks for the report. Do you have a build somewhere public that we can use to reproduce your issue? In the meantime, could you add the following and see if the issue goes away?

```scala
Compile/ run / fork := true
```

**Comment by eed3si9n** [comment]
I am unifying the term to "High CPU usage" so we can search this later. See also https://github.com/sbt/sbt/issues/1697. Are you using `sys.exit`?

**Comment by palutz** [comment]
@eed3si9n Thanks for the answer.
I will try your parameters. I shared the build.sbt. You mean do you need the whole project (with also the code)? I think I can share it, despite it's quite crappy code to try a new integration.

PS: here it's the code:
https://gitlab.com/palutz/trydeltalake

**Comment by palutz** [comment]
@eed3si9n still the same problem also with the little trick suggested.
I figured out that, maybe, the problem is happening more often when the program raises an exception (!!!) and don't terminate properly. So it could be related to the spark/deltalake libraries. Hope this helps.

**Comment by eed3si9n** [comment]
If the problem persists even after forking, then it's likely not sbt's problem.

**Comment by eed3si9n** [comment]
Also could you try sbt 1.3.2?

**Comment by palutz** [comment]
@eed3si9n I thought the same and I just tried.
It looks like with 1.3.2 the problem disappears.

**Comment by eed3si9n** [comment]
ok. I'm closing this then. Let us know if it happens again.
