### ISSUE TITLE
semanticdbVersion ignored in sbt 1.3.2

### ISSUE THREAD

**Issue by ryanberckmans** [sbt/sbt#5110]
## steps
sbt version: 1.3.2

contents of build.sbt
```scala
scalaVersion := "2.13.1"
ThisBuild / semanticdbEnabled := true
ThisBuild / semanticdbVersion := "4.2.3"
ThisBuild / semanticdbIncludeInJar := false
```
## problem
`ThisBuild / semanticdbVersion := "4.2.3"` appears to be ignored and `sbt compile` fails with

```
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.scalameta:semanticdb-scalac_2.13.1:4.1.0
[error]   Not found
[error]   Not found
[error]   not found: ~/.ivy2/local/org.scalameta/semanticdb-scalac_2.13.1/4.1.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.13.1/4.1.0/semanticdb-scalac_2.13.1-4.1.0.pom
[error] Total time: 0 s, completed Sep 21, 2019 1:43:43 PM
```

Ie. org.scalameta:semanticdb-scalac_2.13.1:**4.1.0** looks like sbt is attempting to download semanticdb-scalac 4.1.0 which isn't built for Scala 2.13.1, ignoring the semanticdbVersion of 4.2.3 which is built for Scala 2.13.1.

## expectation
`semanticdbVersion` should be respected and the build should compile using semanticdb `4.2.3`.

**Comment by eed3si9n** [comment]
@ryanberckmans Thanks for the report. I think the workaround would be to scope as `Global / semanticdbVersion` for now.

I think it makes sense to support `ThisBuild` scoping as well.

The fix would be to move 

https://github.com/sbt/sbt/blob/3ca185fe30bbd0a752cdff7aa9bf67d28d413c4c/main/src/main/scala/sbt/plugins/SemanticdbPlugin.scala#L25-L28

into `projectSettings`.

**Comment by ryanberckmans** [comment]
@eed3si9n thanks for the quick response and workaround!
