### ISSUE TITLE
_to_be_replaced is not replaced

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#5119]
originally reported by @er1c

## steps

Install sbt 1.3.2

```
$ cat /usr/local/Cellar/sbt/1.3.2/libexec/bin/sbt | grep "to_be"
declare init_sbt_version=_to_be_replaced
```

## problem

`_to_be_replaced` is a placeholder that was not replaced.

## expectation

That should use 1.3.2.

## notes

This regressed likely when two bash scripts were merged. See https://github.com/sbt/sbt-launcher-package/blob/v1.2.8/build.sbt#L156-L160

**Comment by jsoref** [comment]
Fixed by sbt/sbt-launcher-package#289
