### ISSUE TITLE
test with fork enabled hangs in some cases

### ISSUE THREAD

**Issue by ijuma** [sbt/sbt#512]
Mark mentioned that Stefan provided an example project that shows this. I am filing this to track the issue.

In my case, I have experienced something similar in my multi-module project but the symptoms were slightly different. One thing to note is that in my project, the hang only happens when "test" is invoked. If I invoke <projectName>/test everything works fine.

**Comment by vigdorchik** [comment]
Can you please post a link to the project where I can reproduce the hang? What test framework do you use?

**Comment by ijuma** [comment]
I was hoping that @harrah would post the example he has. If that turned out not to be fix my problem, then I would spend the time trying to create a sample example too.

I used ScalaTest, but I don't know which framework is used for @harrah's case.

**Comment by vigdorchik** [comment]
The hang most probably means the forked JVM failed to exit, which happened for scalatest 1.7.1: https://groups.google.com/forum/?fromgroups#!topic/scalatest-users/KkdU_o-49yg
But if you happen to use a newer version of ScalaTest, then there might be another problem.

**Comment by ijuma** [comment]
I am using ScalaTest 1.8 so I don't think it's that.

**Comment by harrah** [comment]
@vigdorchik I don't think it is a test framework problem because the hang is before tests are run (if I remember correctly).  I think it is probably the concurrent restrictions feature.  If you want to look into it, ask Stefan for how to reproduce.

**Comment by szeiger** [comment]
That must be a different issue than the one I had. What looked like sbt hanging in my case was really a left-over System.out redirection so sbt was still running but the console was dead. The redirection was done by junit-interface and the cause of the problem is the inability of sbt to run in-JVM tests from multiple test configurations or sub-projects non-concurrently. I tried several configuration options that Mark suggested but without success.

**Comment by ijuma** [comment]
OK, I will create an isolated test case in the next few days and post it here.

**Comment by harrah** [comment]
@szeiger Thanks.  I thought there was a remaining issue when trying to restrict concurrent access and a message about no tasks to run was printed.

**Comment by ijuma** [comment]
I pushed a project that shows the issue:

https://github.com/ijuma/sbt-test-bug

If you run `test` it simply hangs before the test gets run. If we change the build to fork := false, then it runs fine. I tested it on Java 7.

**Comment by pk11** [comment]
FYI it's timing out on our CI server as well https://playframework2.ci.cloudbees.com/job/play2-integrationtest/651/console
although I can not replicate it locally (I also just got emails saying that other team members experienced this problem on their dev boxes, so it's not just our CI server).

**Comment by pk11** [comment]
By the way it seems like in our case if it hangs it always happens after all the tests are finished (just like in case of our CI server). I still can not replicate it though

**Comment by vigdorchik** [comment]
I can reproduce the hang in the project @ijuma published. Looks like an ObjectStream issue to me. I'll investigate it further.
