### ISSUE TITLE
[supershell] interactive tasks have a hard time with super shell

### ISSUE THREAD

**Issue by swaldman** [sbt/sbt#5122]
## steps
sbt version: 1.3.2

## problem
Here's a minimal `build.sbt`:

```
val interactiveTask = taskKey[Unit]("This is an interactive task.")

interactiveTask := {
  val is = interactionService.value
  val log = streams.value.log
  val name = is.readLine( "What is your name? ", mask = false ).get
  log.info( s"Hi, ${name}!" )
}
```
It's not usable with super shell enabled.

## expectation

In older version of sbt, or in 1.3.x with `ThisBuild / useSuperShell := false`, this does what you'd expect:

```
> interactiveTask
What is your name? Fluffy
[info] Hi, Fluffy!
[success] Total time: 10 s, completed Sep 24, 2019 2:09:41 AM
```
However, with super shell, the interactive prompt flashes instantaneously and then is overwritten:

```
> interactiveTask





  | => interactive-task / interactiveTask 5s
```

Even if you know the prompt, each character you type is quickly overwritten, so you never see the full word.
## notes

It seems like there must be some kind of way around this, as some interactive tasks seem okay. For example, in the `publishSigned` task, the prompt and echoing of characters (masked as `*`, as they should be) seems to work fine.

```
> publishSigned
[info] Wrote /Users/swaldman/tmp/interactive-task/target/scala-2.12/interactive-task_2.12-0.1.0-SNAPSHOT.pom
Please enter PGP passphrase (or ENTER to abort): ****************








  | => interactive-task / update 0s
```
Looking at the sbt-pgp source code, the trick seems to be embedding the interaction in blocks synchronized on `System.out`. Trying that...

```
val interactiveTask = taskKey[Unit]("This is an interactive task.")

interactiveTask := {
  val is = interactionService.value
  val log = streams.value.log
  val name = System.out.synchronized( is.readLine( "What is your name? ", mask = false ).get )
  log.info( s"Hi, ${name}!" )
}
```
...and the problem does seem to be resolved. The interaction is no longer overwritten.

So maybe there is no issue at all, that's the solution. But I am going to post this, as documentation in case anyone else encounters the same, um, issue.

**Comment by eed3si9n** [comment]
@swaldman Thanks for the report! Maybe we need a way to let build authors opt-out of super shell during some tasks.

**Comment by swaldman** [comment]
Task-scoped `useSuperShell := false` would be a nice feature, if it's not a huge pain to make happen, as for some interactive tasks you like to have the vertical space.

But as long as supershell respects synchronization on `System.out`, it's not a hugely urgent problem. An easy thing to do for now would be to document a convention of using `System.out`'s lock to protect interaction.

(`InteractionService` is not really present in sbt's documentation, like much of the magic of `sbt` it is a magic one discovers by trawling source. Maybe rather than quasidocumenting with an issue, i should try to contribute something about that to the docs.)

**Comment by eed3si9n** [comment]
The original `interactiveTask` seems to work ok on sbt 1.4.2:

<img width="375" alt="5122" src="https://user-images.githubusercontent.com/184683/99196792-8f532f00-275c-11eb-962f-2fefaf8ef270.png">
