### ISSUE TITLE
sbt download from piccolo.link returning 500

### ISSUE THREAD

**Issue by marcindulak** [sbt/sbt#5123]
```
curl -L --head https://piccolo.link/sbt-1.3.2.tgz
HTTP/1.1 500 Internal Server Error
Content-Type: text/html; charset=UTF-8
X-Powered-By: PHP/7.1.22
Cache-Control: no-cache, private
date: Tue, 24 Sep 2019 10:55:33 GMT
```

**Comment by eed3si9n** [comment]
@marcindulak Thanks for the report. We're currently investigating the situation. 
In the meantime please use the link from https://github.com/sbt/sbt/releases/tag/v1.3.2.

**Comment by eed3si9n** [comment]
I've contacted the CDN, and they've brought the service back up.
Internal investigation might continue, but I am closing this for now.
