### ISSUE TITLE
[1.3.x coursier] artifact type overriden in libraryDependencies ignored 

### ISSUE THREAD

**Issue by bjaglin** [sbt/sbt#5132]
## steps
sbt version: 1.3.0, 1.3.2

build.sbt
```
libraryDependencies += "io.grpc" % "protoc-gen-grpc-java" % "1.23.0" % "compile" artifacts(Artifact("protoc-gen-grpc-java", "protoc-plugin", "exe", "linux-x86_64"))
```

## problem

update report shows `exe` as artifact type
```
bjaglin@x1:/tmp/sbt$ sbt "show update" | grep -m1 protoc-gen-grpc-java
[info] 		io.grpc:protoc-gen-grpc-java:1.23.0:default: (Artifact(protoc-gen-grpc-java, exe, exe, Some(linux-x86_64), Vector(), Some(https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.23.0/protoc-gen-grpc-java-1.23.0-linux-x86_64.exe), Map(), None, false),/home/bjaglin/.cache/coursier/v1/https/repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.23.0/protoc-gen-grpc-java-1.23.0-linux-x86_64.exe)
```

## expectation

update report should show `protoc-plugin` as artifact type

https://github.com/sbt/librarymanagement/blob/3377168/core/src/main/scala/sbt/librarymanagement/ModuleIDExtra.scala#L120-L125
> If this ModuleID represents a dependency, these artifact definitions override the information in the dependency's published metadata.

## notes

disabling coursier brings back the 1.2.x / expected behavior

```
bjaglin@x1:/tmp/sbt$ sbt "show update" | grep -m1 protoc-gen-grpc-java
[info] 		io.grpc:protoc-gen-grpc-java:1.23.0: (Artifact(protoc-gen-grpc-java, protoc-plugin, exe, Some(linux-x86_64), Vector(), None, Map(), None, false),/home/bjaglin/.ivy2/cache/io.grpc/protoc-gen-grpc-java/protoc-plugins/protoc-gen-grpc-java-1.23.0-linux-x86_64.exe)
```

**Comment by bjaglin** [comment]
a real-world test case (plugin that relies on the expected behavior): https://github.com/thesamet/sbt-protoc/pull/105

**Comment by eed3si9n** [comment]
@bjaglin Thanks for the report. If this is likely a Coursier issue, could you report to coursier/coursier as well please?

**Comment by bjaglin** [comment]
https://github.com/coursier/coursier/issues/1391

**Comment by bjaglin** [comment]
Fixed upstream, release (still to be cut off) after the current one `v2.0.0-RC4`  should have the fix.

**Comment by eed3si9n** [comment]
nice. we'll bump Coursier when the next one comes out then.
