### ISSUE TITLE
Auth fail in private repo: sbt new git@bitbucket.org:miuler/private-repo.g8.git 

### ISSUE THREAD

**Issue by Miuler** [sbt/sbt#5134]
## steps
sbt version: 1.3.2

sbt -v new git@bitbucket.org:miuler/demo.g8.git
[process_args] java_version = '8'
[sbt_options] declare -a sbt_options=()
# Executing command line:
java
-Dfile.encoding=UTF-8
-Xms1024m
-Xmx1024m
-Xss4M
-XX:ReservedCodeCacheSize=128m
-jar
/home/miuler/.sdkman/candidates/sbt/1.3.2/bin/sbt-launch.jar
new
git@bitbucket.org:miuler/demo.g8.git

[info] Loading settings for project global-plugins from plugins.sbt ...
[info] Loading global plugins from /home/miuler/.sbt/1.0/plugins
[info] Set current project to root-321 (in build file:/home/miuler/Downloads/321/)
[info] Set current project to root-321 (in build file:/home/miuler/Downloads/321/)

git@bitbucket.org:miuler/demo.g8.git: Auth fail

## problem
I can not cloning the my private repository in bitbucket.

## notes
cat ~/.ssh/config
Host bitbucket.org - Work
    Hostname bitbucket.org
    IdentityFile ~/.ssh/id_rsa_my_1
    IdentitiesOnly yes
    User miuler

**Comment by eed3si9n** [comment]
@Miuler I am guessing this is more of a https://github.com/foundweekends/giter8 issue. Could you report it there please?
