### ISSUE TITLE
sbt overrides -XX:MaxRAMPercentage/-XX:MinRAMPercentage by adding -Xmx/-Xms

### ISSUE THREAD

**Issue by azolotko** [sbt/sbt#5135]
According to http://hg.openjdk.java.net/jdk/jdk11/file/1ddf9a99e4ad/src/hotspot/share/runtime/arguments.cpp#l1750, -Xmx/-Xms options have precedence over recently introduced -XX:MaxRAMPercentage/-XX:MinRAMPercentage. sbt doesn't recognise the laters and adds its default -Xmx/-Xms values, which causes problems for users who try to run sbt in cgroup-constrained environments, for example Docker.

**Comment by eed3si9n** [comment]
@azolotko Thanks for the report! 

The relevant part of the script is likely https://github.com/sbt/sbt-launcher-package/blob/23e0f6ebeecbcc685fc3d5bda36e0b2125f50c2c/src/universal/bin/sbt#L176-L188

```bash
addDefaultMemory() {
  # if we detect any of these settings in ${JAVA_OPTS} or ${JAVA_TOOL_OPTIONS} we need to NOT output our settings.
  # The reason is the Xms/Xmx, if they don't line up, cause errors.
  if [[ "${java_args[@]}" == *-Xmx* ]] || [[ "${java_args[@]}" == *-Xms* ]]; then
    :
  elif [[ "${JAVA_TOOL_OPTIONS}" == *-Xmx* ]] || [[ "${JAVA_TOOL_OPTIONS}" == *-Xms* ]]; then
    :
  elif [[ "${sbt_options[@]}" == *-Xmx* ]] || [[ "${sbt_options[@]}" == *-Xms* ]]; then
    :
  else
    addMemory $sbt_default_mem
  fi
}
```

I guess we need to add `-XX:MaxRAMPercentage/-XX:MinRAMPercentage` as one of the memory opt-out signal.

Would you like to send a PR for this?

**Comment by azolotko** [comment]
@eed3si9n Yes, I'll prepare a PR during the weekend.
