### ISSUE TITLE
update homebrew formula for 0.12

### ISSUE THREAD

**Issue by mergeconflict** [sbt/sbt#517]
https://github.com/mxcl/homebrew/blob/master/Library/Formula/sbt.rb still refers to 0.11.3-2 presently

**Comment by harrah** [comment]
Native packages, including the homebrew formula, are not provided by this project.  Please file a bug with the appropriate maintainer.

**Comment by mergeconflict** [comment]
Hmm, I arrived here via http://www.scala-sbt.org/community.html.  Should I have filed this issue in the launcher project (https://github.com/sbt/sbt-launcher-package) instead?

**Comment by mergeconflict** [comment]
Or I guess I should ask... who maintains all the stuff here: http://www.scala-sbt.org/download.html

**Comment by harrah** [comment]
Good point about the scala-sbt.org site.  The other packages provide a link to where to report issues, but the homebrew one does not.  Please file a bug for the website here: https://github.com/sbt/sbt.github.com/issues 

If you can find out who is responsible for the homebrew package, that would help.
