### ISSUE TITLE
Windows sbt.bat doesn't support --sbt-jar

### ISSUE THREAD

**Issue by er1c** [sbt/sbt#5178]
## steps
sbt version: 1.3.3

## problem

The `sbt.bat` currently doesn't support `--sbt-jar`

https://github.com/sbt/sbt-launcher-package/blob/master/src/universal/bin/sbt.bat#L745-L747

```bash
rem echo   --sbt-jar      ^<path^>      use the specified jar as the sbt launcher
```

## expectation

They would match the bash `sbt` functionality.

**Comment by eed3si9n** [comment]
I think that's a documentation error on Bash version. At least I've never used `--sbt-rc` or `--sbt-snapshot`.

**Comment by er1c** [comment]
Good catch, so missing the `--sbt-jar`, but `--sbt-rc` and `--sbt-snapshot` should be removed from the bash usage, since I see they aren't implemented.

**Comment by er1c** [comment]
Added in https://github.com/sbt/sbt-launcher-package/commit/9f9dd66336f97e0402fa3215aa93d932166ce595
