### ISSUE TITLE
Release sbt 1.3.3

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#5184]
https://github.com/sbt/sbt/compare/v1.3.2...1.3.x

**Comment by eed3si9n** [comment]
Draft release note.

- Fixes "Could not create directory ...classes.bak" https://github.com/sbt/sbt/pull/5146 by [@retronym][@retronym] and [@eed3si9n][@eed3si9n]
- Fixes internal ClassLoader causing dead locks https://github.com/sbt/sbt/pull/5131 by [@eatkins][@eatkins]
- Fixes race condition around `clean` task https://github.com/sbt/sbt/pull/5157 by [@eatkins][@eatkins]
- Fixes "Class sun.reflect.CallerSensitive not found" problem https://github.com/sbt/zinc/pull/701 by [@retronym][@retronym]
- Fixes error messages reported coming from Dotty https://github.com/sbt/zinc/pull/699 by [@smarter][@smarter] 
- Fixes super shell display https://github.com/sbt/util/pull/223 / https://github.com/sbt/util/pull/227 / https://github.com/sbt/sbt/pull/5125 / https://github.com/sbt/sbt/pull/5148 / https://github.com/sbt/sbt/pull/5156 by [@eatkins][@eatkins]
- Fixes check build sources for projects with meta-meta-build https://github.com/sbt/sbt/pull/5109 by [@eatkins][@eatkins]
- Fixes `fgRun` performance regression https://github.com/sbt/sbt/pull/5126 by [@eatkins][@eatkins]
- Fixes scripted parser https://github.com/sbt/sbt/pull/5158 by [@eatkins][@eatkins]
- Fixes `-v` getting on all the time https://github.com/sbt/sbt-launcher-package/pull/283 by [@eed3si9n][@eed3si9n]
- Fixes initial version number in `sbt` script https://github.com/sbt/sbt-launcher-package/pull/289 by [@jsoref][@jsoref]
- Adds `--numeric-version`, `--script-version`, and updates `--version` to print both versions https://github.com/sbt/sbt-launcher-package/pull/288 by [@er1c][@er1c]
- Adds `--verbose` option to `sbt.bat` https://github.com/sbt/sbt-launcher-package/pull/291 by [@eed3si9n][@eed3si9n]
- Adds `--help`, `--version` and many other feature to `sbt.bat` https://github.com/sbt/sbt-launcher-package/pull/285 by [@er1c][@er1c]
- Fixes equal sign handling in `-Dkey=value` for `sbt.bat` https://github.com/sbt/sbt-launcher-package/pull/290 by [@eed3si9n][@eed3si9n]
- Fixes `-XX:MaxRAMPercentage` option handling https://github.com/sbt/sbt-launcher-package/pull/295 by [@azolotko][@azolotko]

  [@eed3si9n]: https://github.com/eed3si9n 
  [@smarter]: https://github.com/smarter 
  [@retronym]: https://github.com/retronym 
  [@eatkins]: https://github.com/eatkins
  [@jsoref]: https://github.com/jsoref
  [@er1c]: https://github.com/er1c
  [@azolotko]: https://github.com/azolotko

**Comment by plokhotnyuk** [comment]
@eed3si9n thanks! it is 200-th release of sbt!

BTW, will you attach binaries to the release assets?

**Comment by eed3si9n** [comment]
The above is a draft release note. I will be released sometime today with installers.
