### ISSUE TITLE
Show more details if package upload fails

### ISSUE THREAD

**Issue by francisdb** [sbt/sbt#5185]
I'm trying to publish to the Github package repository. When `publish fails` all you get is 

> java.io.IOException: PUT operation to URL https://maven.pkg.github.com/company/foo/bar/utils/utils/0.0.1/utils-0.0.1.pom failed with status code 400: Bad Request

But the body actually contains more details on what went wrong. An example below for a 401 response

>  ...was refused by the server: Unauthorized response=Your token has not been granted the required scopes to execute this query. The 'id' field requires one of the following scopes: ['read:packages'], but your token has only been granted the: ['repo'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.

(I had to patch sbt-ivy to see this)

Related ticket on the publishing to Github here: 
https://github.com/djspiewak/sbt-github-packages/issues/1

**Comment by eed3si9n** [comment]
@francisdb Thanks for the report. There was a related PR on this https://github.com/sbt/librarymanagement/pull/309, but from sbt 1.3.x Gigahorse is not enabled by defaults, so likely we need similar patch for non-Gigahorse handler.

**Comment by francisdb** [comment]
Is Coursier also a possible player in this field?

**Comment by francisdb** [comment]
So you suggest to patch Ivy instead of fixing Gigahorse?

**Comment by eed3si9n** [comment]
Publishing is done by Ivy, so yea we might need a custom URL handler that is not Gigahorse based, but takes the idea from the PR that I linked.

**Comment by francisdb** [comment]
see https://github.com/sbt/ivy/pull/35

**Comment by eed3si9n** [comment]
Keeping this open as a reminder until the whole thing gets merged.

**Comment by eed3si9n** [comment]
Sorry I forgot to backport https://github.com/sbt/librarymanagement/pull/324 to 1.3.x, so this missed 1.3.4.
