### ISSUE TITLE
scala-libary jar not included in class path

### ISSUE THREAD

**Issue by aperez17** [sbt/sbt#5186]
## steps
sbt version: *1.3.2*

## problem
In previous versions of sbt, the scala-libary jar has been accessible through the class loader, however, now it is not.
```
getClass.getClassLoader match {
      case urlClassLoader: net.URLClassLoader => urlClassLoader.getURLs.map(u => new File(u.toURI).getCanonicalPath).toList
}
```
That specifically does not have the scala-libary jar in 1.3.2, works in 1.2.8 and was previously on 0.13 when it was working. I tried turning off coursier and adding the library manually to list of dependencies, but that did not work.

## expectation
class loader has the scala-libary jars

**Comment by eatkins** [comment]
It is not safe to assume much about the layout of the sbt classloaders. To access the scala library, you will need to traverse the parents of the classloader to find the loader that has the scala library jar in it.
