### ISSUE TITLE
sbt new doesn't work on Windows: '"!_JAVACMD!"' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#5188]
## steps

sbt 1.3.3

```
sbt new scala/scala-seed.g8
```

## problem

First problem is that it prompts me to continue or not. This should not show up for `new`.

```
c) continue
q) quit
?      if /I "" == "c" (
```

Second problem is that it doesn't work.

```
The Java Development Kit (JDK) installation you have is not up to date.
sbt requires at least version !required_version!+, you have
version "!JAVA_VERSION!"

Please go to http://www.oracle.com/technetwork/java/javase/downloads/ and download
a valid JDK and install before running sbt.

Missing operator.
Missing operator.
'"!_JAVACMD!"' is not recognized as an internal or external command,
operable program or batch file.
```

## expectation

It works.

**Comment by eed3si9n** [comment]
- https://github.com/sbt/sbt-launcher-package/blob/d43357144bce255fee5c8419f1a991bfacf0e8ef/src/universal/conf/sbtconfig.txt
- https://github.com/sbt/sbt-launcher-package/blob/d43357144bce255fee5c8419f1a991bfacf0e8ef/src/universal/conf/sbtopts

We should probably add `-sbt-create` first.

**Comment by er1c** [comment]
```
c:\Users\Eric Peters\IdeaProjects>sbt --script-version
1.3.3

c:\Users\Eric Peters\IdeaProjects>sbt new scala/scala-seed.g8

[info] Loading settings for project global-plugins from idea.sbt,metals.sbt ...
[info] Loading global plugins from C:\Users\Eric Peters\.sbt\1.0\plugins
[info] Set current project to ideaprojects (in build file:/C:/Users/Eric%20Peters/IdeaProjects/)
[info] Set current project to ideaprojects (in build file:/C:/Users/Eric%20Peters/IdeaProjects/)

A minimal Scala project.

name [Scala Seed Project]:
```

Ugh...the java version not being recognized in your output is suspect, do you have any other info on your windows setup?  I just installed the MSI on my windows desktop, and it seemed to work fine.

**Comment by eed3si9n** [comment]
```
which java
/c/Program Files/Java/jdk1.8.0_151/bin/java
```

To trigger `continue`/`quit`, you have to run it in an empty directory.

**Comment by er1c** [comment]
I was able to reproduce this on `Windows 7`

**Comment by daiguel** [comment]
how did you fixe this ?

**Comment by molotch** [comment]
I have the exact same problem with sbt 1.3.3 on both Adoptopenjdk 8u232b09 and Amazon Corretto 8.232.09.1. Strange thing is the first scaffold worked once on Corretto, next time I tried to seed a project it broke.

I'm  running on Windows 10 build 17134.

**Comment by Training-Predix** [comment]
The fix referenced in this issue has not been uploaded to the scala-lang.org website.  I just downloaded the sbt 1.3.3 .msi installer package from https://www.scala-sbt.org/download.html?_ga=2.33660135.732802283.1573849365-235766934.1573773842, and the issue persists.

**Comment by teachermanalex** [comment]
The fix referenced in this issue has not been uploaded to the scala-lang.org website. I just downloaded the sbt 1.3.3 .msi installer package from https://www.scala-sbt.org/download.html?_ga=2.33660135.732802283.1573849365-235766934.1573773842, and the issue persists.
