### ISSUE TITLE
`sbt new` should not create a target directory in the working directory

### ISSUE THREAD

**Issue by ghost** [sbt/sbt#5190]
## steps
sbt version: *1.3.1*
run sbt new scala/hello-world.g8

## problem
this creates ./target/... directories

## expectation
Current working directory should not get polluted. 

## notes
This issue was fixed in version 1.2.1. Refer. https://github.com/sbt/sbt/issues/2835. But the same issue is reproducible in version 1.3.1

**Comment by eed3si9n** [comment]
@dexter2305 Thanks for the report.

To potential contributor, first thing to look at would be https://github.com/sbt/sbt/pull/4033, and see if that still works.

**Comment by dhorkin** [comment]
I'm new to Scala as of today (using for gatling), but wanted to confirm this still appears to repro with sbt 1.3.10 and `sbt new gatling/gatling.g8`

**Comment by ivarasg** [comment]
Have the same issue, I am using version 1.3.4 of sbt as of July 2020.

**Comment by jneo8** [comment]
+1 same issue.

```bash
$ sbt -V    
sbt version in this project: 1.4.6
sbt script version: 1.4.6
```

**Comment by eed3si9n** [comment]
I reopened https://github.com/sbt/sbt/issues/2835
