### ISSUE TITLE
It should be possible to flexibly exclude projects and plugins from the build

### ISSUE THREAD

**Issue by pshirshov** [sbt/sbt#5191]
Please use https://discuss.lightbend.com/c/tooling including a specific user story instead of posting them to the issue tracker.

Right now SBT in very inconvenient for big monorepos.

For example, I may have ten software components but at some point I may wish to work with just couple of them. 

At this point there is no easy to exclude several subprojects from the project. In some cases projectmatrix/siracha can help. But things are getting worse in case we have a cross-build wish to build all the artifacts of a component for one of the platforms. One of the cases is when we use IntelliJ -- it has a lot of bugs in ScalaJS support, at this point it can't build any projects referencing `sbt-crossprojects`. And there are other similar cases.

It would be great if we can add tags to projects and then specify exclusion rules in commandline, for example

```bash
sbt --exclude "(platform:javascript && tagname) || platform:native"
```

[More details about my motivation](https://medium.com/playqtechblog/monorepo-or-multirepo-role-based-repositories-b2e52326c553)

**Comment by eed3si9n** [comment]
> Please use https://discuss.lightbend.com/c/tooling including a specific user story instead of posting them to the issue tracker.

umm. Let's discuss on Discuss.
