### ISSUE TITLE
Global .sbt files for settings

### ISSUE THREAD

**Issue by n8han** [sbt/sbt#52]
For global plugins it would be nice to have global, user-defined settings. For example, the [posterous-sbt plugin](https://github.com/n8han/posterous-sbt) has settings `posterousEmail` and `posterousPassword` that the user must define somewhere before sbt can boot with the plugin on the classpath.

Currently, the recommendation is for users to have a file `~/.sbt/plugins/user.scala` that defines the settings manually:

``` scala
import sbt._
import posterous.Publish._

object User extends Plugin {
  override def settings = Seq(
    posterousEmail := "you@example.com",
    posterousPassword := "yourpassword"
  )
}
```

Alternatively, you could define these in a `user.sbt` within every project:

``` scala
posterousEmail := "you@example.com",
posterousPassword := "yourpassword"
```

It would be great if we could place a file like this in `~/.sbt/` or some other location and have it be loaded for every project.

**Comment by timperrett** [comment]
+1 on this. The CloudBees deployment plugin also needs something similar in terms of having that global configuration values which you wouldn't want to commit to the main build.sbt

**Comment by harrah** [comment]
Note that the need for this is not to keep things out of <project>/build.sbt.  You can easily create a <project>/local.sbt that you don't check into version control.  It is so that you only have to define the settings once.

**Comment by timperrett** [comment]
Thanks for the clarification Mark, my wording was just poorly chosen there. The use case I have is identical to Nathans. Cheers

**Comment by MasseGuillaume** [comment]
@harrah what if you accidentally add and push local.sbt ?

**Comment by harrah** [comment]
@MasseGuillaume You can add it to .gitignore or use other version control hooks/techniques to avoid that.  Note that this feature got implemented and it can be used to specify credentials or other user-global information as requested.
