### ISSUE TITLE
sbt randomly forgets test failures

### ISSUE THREAD

**Issue by szeiger** [sbt/sbt#520]
While investigating https://github.com/szeiger/junit-interface/issues/9 I ran into an issue where sbt would sometimes report failed test runs (using "test" or "test-only") as successful. The test success/failure counts are printed correctly, first by junit-interface and then by sbt, but in Tests.showResults it does not find any failures to report.

To reproduce, clone https://github.com/szeiger/junit-interface and publish-local (to get junit-interface 0.9-SNAPSHOT), then clone https://github.com/szeiger/cucumberjvm-sbt/tree/inconsistent-reporting and run "test" or "test-only" in it (using sbt 0.12.0).

One test run might produce this:

```
...
[error] Test Then the result is 2        failed: expected:<2.0> but was:<1.0>
[error] Test Scenario: Subracting      failed: expected:<2.0> but was:<1.0>
[error] Failed: : Total 6, Failed 2, Errors 0, Passed 4, Skipped 0
[error] Failed tests:
[error]         cucumber.examples.scalacalculator.RunCukesTest
[trace] Stack trace suppressed: run last test:test for the full output.
[error] (test:test) Tests unsuccessful
[error] Total time: 1 s, completed Aug 16, 2012 3:45:36 PM
```

And the next one this:

```
...
[error] Test Then the result is 2        failed: expected:<2.0> but was:<1.0>
[error] Test Scenario: Subracting      failed: expected:<2.0> but was:<1.0>
[error] Failed: : Total 6, Failed 2, Errors 0, Passed 4, Skipped 0
[success] Total time: 1 s, completed Aug 16, 2012 3:46:17 PM
```

I was unable to reproduce this effect in any project but since the only way for a test-interface implementer to report failures to sbt is through the EventHandler and the counts reported by sbt are still correct, I expect the bug to be on sbt's side.

**Comment by vigdorchik** [comment]
Does junit-interface call the provided EventHandler from multiple threads? That could explain it, since the passed EventHandler is not thead-safe: https://github.com/harrah/xsbt/blob/0.13/testing/TestFramework.scala#L70

**Comment by szeiger** [comment]
No, all events are posted from the same thread. Synchronizing the EventHandler calls does not make a difference. I also added some debug logging to see which thread ID posts an event. As you can see it fails to retain the events even though they are all handled on the same thread:

```
> test
#### handling from 51
#### handling from 51
#### handling from 51
#### handling from 51
#### handling from 51
#### handling from 51
#### handling from 51
#### handling from 51
...
[error] Test Then the result is 2        failed: expected:<2.0> but was:<1.0>
[error] Test Scenario: Subracting      failed: expected:<2.0> but was:<1.0>
[error] Failed: : Total 6, Failed 2, Errors 0, Passed 4, Skipped 0
[success] Total time: 1 s, completed Aug 27, 2012 5:26:32 PM
```

**Comment by szeiger** [comment]
On a related note, I think it would be useful if the list of failed tests included the actual test names reported by the test framework. In sbt 0.12 you only get the test class names discovered by sbt. The names reported to sbt in the failure events are ignored. I guess this won't be an issue any more when sbt moves to the new test interface where test frameworks can print their own summary.

**Comment by harrah** [comment]
`junit-interface` defines both `RunWith` and `Test` annotations as fingerprints.  When a class has both, sbt calls junit-interface twice with the definitions `TestDefinition("RunCukesTest", AnnotationFingerprint("RunWith"))` and `TestDefinition("RunCukesTest", AnnotationFingerprint("Test"))`.  It seems that the `RunWith` variant passes and the `Test` variant fails.  Because the results are collected by test name, only one of the test results can be used.  Different execution orders probably cause the different results from run to run.

**Comment by harrah** [comment]
So, ideally sbt would pass all fingerprints for a test at once.  The test interface doesn't allow this.  Another possibility is to just select the first fingerprint according to the order returned by the test framework.

**Comment by szeiger** [comment]
If by "passes" you mean that it doesn't actually run the test (thus not "failing" it), yes, that is correct. Without improvements to the test-interface which allow junit-interface to see all tests and once and then decide what to run, I see no way of changing that in junit-interface. (For the current test interface, the changes you propose should allow me to work around the issue, too)
