### ISSUE TITLE
Stack trace being supressed

### ISSUE THREAD

**Issue by Fristi** [sbt/sbt#5209]
I recently upgraded sbt to 1.3. After this update when I get a error, I run in to this: `stack trace is suppressed; run last tests / IntegrationTest / test for the full output`

This is not such good UX in my opinion, as my test output is pretty big and lot's of scrolling is involved. So question is, should you put it on as default and is there a way to turn it off?

**Comment by eed3si9n** [comment]
Is this a bug report? If so, please follow the https://github.com/sbt/sbt/issues/new?assignees=&labels=Bug&template=---bug-report.md&title= format.

A normal test failure should not cause stack trace, suppressed or not.
