### ISSUE TITLE
Failure to Parse Batch Command in Windows

### ISSUE THREAD

**Issue by domainexpert** [sbt/sbt#5210]
## steps
sbt version: 1.3.3

## problem
The Sbt documentation [here](https://www.scala-sbt.org/1.x/docs/Running.html) says I could enter a command with its arguments in quotes, e.g.:
```
sbt clean compile "testOnly TestA TestB"
```
However, instead of executing the commands, on Windows 10 Sbt terminates with error:
```
TestA was unexpected at this time.
```

## expectation

The project compiles and the tests get executed if they were available, or some other error message is shown otherwise.

## notes
It seems this is due to the following line in `sbt.bat`:
```
 if x%g:^==% == x%g% (
```
It should instead be:
```
 if "%g:^==%" == "%g%" (
```

**Comment by eed3si9n** [comment]
@domainexpert Thanks for the report! It seems like you know how to fix this, so could you send a PR for this please?

Relevant files are:
- https://github.com/sbt/sbt-launcher-package/blob/master/src/universal/bin/sbt.bat
- https://github.com/sbt/sbt-launcher-package/blob/master/integration-test/src/test/scala/RunnerTest.scala
- https://github.com/sbt/sbt-launcher-package/blob/master/citest/build.sbt

**Comment by domainexpert** [comment]
@eed3si9n I replaced the sbt.bat of Sbt 1.3.3 with the sbt.bat of sbt/sbt-launcher-package@9f9dd66336f97e0402fa3215aa93d932166ce595 and the problem disappeared, so it seems no fixing is necessary. Looking forward to 1.3.4.

**Comment by enzeart** [comment]
I'm still seeing this issue in sbt 1.3.4 on Windows

**Comment by eed3si9n** [comment]
https://github.com/sbt/sbt-launcher-package/pull/317 failed on Windows, so this might be related.

**Comment by jkoberg** [comment]
FYI, still getting this with SBT 1.5.5 on Windows 10, with Java installed in e.g. `c:\Progam Files\Eclipse Foundation\...`

**Comment by eed3si9n** [comment]
@jkoberg Are you hitting the same issue with exact same reproduction steps?
