### ISSUE TITLE
-J flags not supported in .sbtopts on windows

### ISSUE THREAD

**Issue by OlegYch** [sbt/sbt#5214]
## steps
sbt version: 1.3.3 from https://piccolo.link/sbt-1.3.3.tgz
have .sbtopts file with -J options, eg like this 
https://github.com/scalacenter/scastie/blob/master/.sbtopts

## problem
sbt (using sbt.bat from official package) fails to startup:
`Unrecognized option: -J-Xmx2g`

## expectation
sbt starts up and passes options from .sbtopts to jvm

## notes
using the same distribution on linux requires using -J prefix, otherwise startup fails like this:
```
[error] Expected ';'
[error] -XX:+UseG1GC
```

**Comment by eed3si9n** [comment]
@OlegYch Thanks for the report!

**Comment by dimon222** [comment]
I confirm the same issue for all platforms.
Including OS X and Linux

The last release it was still working was 1.3.0, then some breaking change got introduced

Update after tests: **the -J flag is no longer needed, just pass args directly and it seems to work**

**Comment by eed3si9n** [comment]
This actually looks like a duplicate of https://github.com/sbt/sbt/issues/5179

I also wrote https://discuss.lightbend.com/t/environment-variables-java-opts-sbt-opts-and-how-to-pass-jvm-arguments/5385 to discuss the details around this area.
