### ISSUE TITLE
Scalatest test suites are not executed in parallel, even though it's set "fork in IntegrationTest := true"

### ISSUE THREAD

**Issue by nikkatalnikov** [sbt/sbt#5216]
I have a bunch of integration tests running by sbt, given test N suites with 1..M tests per each suite. 
I have set `fork in IntegrationTest := true`, but test suites are always executed sequentially. According to the docs, this must not be the case: test suites should be executed concurrently.

the test suites are a class as following:
```
class MyTestSuite1 extends FlatSpec with Matchers 
...
it should "do A" {}
it should "do B" {}
```

```
class MyTestSuite2 extends FlatSpec with Matchers 
...
it should "do C" {}
it should "do D" {}
```

## the problem
MyTestSuite1 and MyTestSuiteN are executed sequentially (by the alphabet order to be exact)

## expectation
MyTestSuite1 and MyTestSuiteM are executed concurrently

## env

.sbopts:
```
-J-Xms1G
-J-Xmx4G
-J-XX:MaxMetaspaceSize=512m
-J-Xss4M
```

## note
I noticed that all test are running using the same pool and thread, for example, `pool-1-thread-1` for all tests.

sbt version: 1.2.8
Scala: 2.12.8
os: MacOS 10.15, Ubuntu 19.04
Scalatest ver: 3.2.0-SNAP10

Tried sbt v. 1.3.2 - same result.
Adding 
```
testOptions in IntegrationTest += Tests.Argument(TestFrameworks.ScalaTest, "-P4"),
```
does not help.

============
## Update

`fork in(IntegrationTest, test) := true` works on a global level, but I have 2 projects and I want to make it work to preserve relative path to the proj.

e.g.

```
lazy val `p1` = Project(id = "p1", base = file("./p1"))
  .configs(IntegrationTest)
  .settings(Defaults.itSettings: _*)
  .settings(
    fork in(IntegrationTest, test) := true,
    ...)

lazy val `p2` = Project(id = "p2", base = file("./p2"))
  .configs(IntegrationTest)
  .settings(Defaults.itSettings: _*)
  .settings(
    fork in(IntegrationTest, test) := true,
    ...)

```

does not run tests in parallel

instead, this runs in parallel, but, obviously, the home dir is set to be "." rather than to be "./p1" or "./p2" respectively:

```
fork in(IntegrationTest, test) := true

lazy val `p1` = Project(id = "p1", base = file("./p1"))
  .configs(IntegrationTest)
  .settings(Defaults.itSettings: _*)
```

**Comment by eed3si9n** [comment]
Test suites are split up into sbt tasks when `IntegrationTest / parallelExecution` is set to `true` (default), and it uses sbt's task parallelism to execute suites in parallel. To run forked tests in parallel you might need:

```
IntegrationTest / testForkedParallel := true
```

See https://www.scala-sbt.org/1.x/docs/Testing.html
