### ISSUE TITLE
Overcompilation after whitespace change

### ISSUE THREAD

**Issue by OlegYch** [sbt/sbt#5217]
## steps
sbt version: 1.1.5-1.3.3
using https://github.com/scalacenter/scastie/tree/overcompilation
run `~client/compile`
add a new line at the end of eg `./client/src/main/scala/com.olegych.scastie.client/components/ScaladexSearch.scala`

## problem
unrelated files are recompiled, even though no code has actually changed
here is a sample debug log https://gist.github.com/OlegYch/775e657ad4edb41b77c88e0fa8be3c83

## expectation
only the modified file is recompiled

## notes
this is a scala.js project, but i've been assured that this is inconsequential 
minimizing the problem turned out to be very hard, because sometimes the problem goes away only to reappear after clean compile
sbt 1.0.0-1.1.4 works fine, so it appears that some change in 1.1.5 caused the regression

**Comment by eed3si9n** [comment]
@OlegYch Thanks for the report!

**Comment by eatkins** [comment]
This looks like a zinc bug. I created a new issue over there: https://github.com/sbt/zinc/issues/718 and am closing this one.
