### ISSUE TITLE
windows: 'sbt -jvm-debug 5005' not working with 1.3.3 launcher bat file

### ISSUE THREAD

**Issue by noisypants** [sbt/sbt#5223]
## steps
sbt version: *insert sbt version*
D:\test>sbt -version
sbt version in this project: 1.3.3
sbt script version: 1.3.3

## problem
When upgrading the sbt installation from 1.2.8 to 1.3.3 (using the msi), the '-jvm-debug' command line setting stopped working.
```
D:\test>sbt --jvm-debug
[info] Loading global plugins from C:\Users\user\.sbt\1.0\plugins
[info] Loading project definition from D:\test\project
[info] Loading settings for project test from build.sbt ...
[info] Set current project to test (in build file:/D:/test/)
[error] Expected ';'
[error] --jvm-debug
[error]

D:\test>
```
Same results with variations of the cmd: 
```
sbt --jvm-debug 5005
sbt -jvm-debug
sbt -jvm-debug 5005
```

## expectation
I would expect the jvm-debug command to be recognized and set up the jvm for remote debugging correctly.  

## notes
Other cmds like _--mem 2048_ work ok.
using sbt script 1.3.3 with a project version of 1.2.8 exhibits the same problem.

**Comment by eed3si9n** [comment]
@noisypants Thanks for the report!

**Comment by er1c** [comment]
@eed3si9n feel free to mention me in these windows launcher script when you triage them.

**Comment by er1c** [comment]
This is working for me (at least in `1.3.5`)

```
PS C:\Users\Eric Peters\IdeaProjects\ta-solr-healthcheck-plugin> sbt --script-version
1.3.5
PS C:\Users\Eric Peters\IdeaProjects\ta-solr-healthcheck-plugin> sbt -v -jvm-debug runMain
...
# Executing command line:
"C:\Program Files\AdoptOpenJDK\jdk-11.0.3.7-hotspot\\bin\java.exe"
-Dfile.encoding=UTF-8
-Dscala.ext.dirs="C:\Users\Eric Peters\.sbt\0.13\java9-rt-ext-adoptopenjdk_11_0_3"
-agentlib:jdwp
transport
dt_socket
server
y
suspend
n
address
5005
-Xms1024m
-Xmx1024m
-Xss4M
-XX:ReservedCodeCacheSize=128m
-cp
"C:\Program Files (x86)\sbt\\bin\sbt-launch.jar"
xsbt.boot.Boot
runMain

Listening for transport dt_socket at address: 5005
```

**Comment by noisypants** [comment]
Confirmed.  I tried on 1.3.5 and it works again.  thanks.

**Comment by noisypants** [comment]
Apparently i got a ahead of myself.  this issue still seems to exist with 1.3.5.
```
D:\dev\testapp>sbt --script-version
1.3.5

D:\dev\testapp>sbt -v -jvm-debug 5005
# Executing command line:
"java"
-Dfile.encoding=UTF-8
-agentlib:jdwp
transport
dt_socket
server
y
suspend
n
address
5005
-Xms1024m
-Xmx1024m
-Xss4M
-XX:ReservedCodeCacheSize=128m
-cp
"C:\Program Files (x86)\sbt\\bin\sbt-launch.jar"
xsbt.boot.Boot
-jvm-debug
5005

Listening for transport dt_socket at address: 5005
[info] Loading project definition from D:\dev\testapp\project
[info] Loading settings for project testapp from build.sbt ...
[info] Set current project to testapp (in build file:/D:/dev/testapp/)
[error] Expected ';'
[error] -jvm-debug
[error]           ^

D:\dev\testapp>
```

**Comment by dpinn** [comment]
A workaround: explicitly set the debug agent in the ```JAVA_OPTS``` environment variable, as follows:

`set JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9999`
... where 9999 is a port number. You could alternatively use 5005 or whatever.

You can then call sbt.bat without the `-jvm-debug` parameter, and it will start up in debug mode.

**Comment by lolgab** [comment]
`-jvm-debug` doesn't work anymore on sbt 1.4 .
Was it dropped or is it a bug @eed3si9n?

**Comment by eed3si9n** [comment]
@lolgab As far as I know, it's not dropped. Could you open a new issue with the output of

```
sbt --script-version
sbt -v -jvm-debug 5005
```
