### ISSUE TITLE
Status of vscode extension

### ISSUE THREAD

**Issue by dvirtz** [sbt/sbt#5228]
It seems the vscode extension stopped being developed. 
Are you still plan to work on it? Would you take PRs?

**Comment by eed3si9n** [comment]
We still plan to work on sbt server as a concept (see for example https://github.com/sbt/sbt/pull/5207) but practically speaking Metals is a full ledge language server for Scala, so the VS Code extension I would say is not really active. Instead it might be more interesting to drive sbt as a backend of LSP servers.
