### ISSUE TITLE
makeIvyXml ignores description and homepage settings

### ISSUE THREAD

**Issue by fthomas** [sbt/sbt#5234]
## steps
sbt version: 1.3.3

`buildt.sbt`:
```sbt
name := "sbt-ivy-test"
description := "This is just a test"
homepage := Some(url("http://example.com"))
```

`project/build.properties`:
```
sbt.version = 1.3.3
```

## problem

`sbt makeIvyXml` generates an `ivy.xml` file with an empty `<description>`:
```xml
<description/>
```

## expectation

Downgrading to sbt 1.2.8 and running `makeIvyXml` again produces a `<description>` that contains the values of the `description` and `homepage` settings:
```xml
<description homepage="http://example.com"> This is just a test </description>
```

**Comment by fthomas** [comment]
I just checked that sbt 1.3.0, 1.3.0-RC1, and 1.3.0-M3 also produce an empty description. 1.3.0-M2 seems to be the last version that is not affected.

**Comment by fthomas** [comment]
If [`IvyXml.content`](https://github.com/sbt/sbt/blob/08c7fd1b8f69d9f8d6704131811f10787eb016d0/main/src/main/scala/sbt/internal/librarymanagement/IvyXml.scala#L114) is used to generate the file written by `makeIvyXml`, then it is obvious why there is no `homepage` attribute. But it does not explain why `<description>` and therefore `project.info.description` is empty.

**Comment by fthomas** [comment]
Oh, if we set `useCoursier := false`, the description and homepage are in the `ivy.xml` file.

**Comment by eed3si9n** [comment]
@fthomas Thanks for the report! Would you be interesting sending a PR for this?

**Comment by fthomas** [comment]
I can certainly send a PR that sets the `homepage` attribute with the value of `project.info.homePage` if it is not empty but I haven't yet figured out why `project.info.description` is empty when Coursier is used.

**Update:** I found that [CoursierInputsTasks.coursierProject0](https://github.com/sbt/sbt/blob/08c7fd1b8f69d9f8d6704131811f10787eb016d0/main/src/main/scala/sbt/coursierint/CoursierInputsTasks.scala#L40) returns a `CProject` with an empty `CInfo`. I think that can easily be fixed.

**Comment by fthomas** [comment]
I should note that this bug can be observed in the wild in this `ivy.xml` for example: https://dl.bintray.com/sbt/sbt-plugin-releases/com.dwijnand/sbt-dynver/scala_2.12/sbt_1.0/4.0.0/ivys/ivy.xml
