### ISSUE TITLE
sbt 1.3.3 ${packaging.type}

### ISSUE THREAD

**Issue by kamilkloch** [sbt/sbt#5237]
Hi all, 

the issue has already been supposedly fixed (https://github.com/sbt/sbt/issues/4682), but I keep getting the following error with sbt 1.3.3:
```
[error] (update) java.net.URISyntaxException: Illegal character in path at index 104: https://repo1.maven.org/maven2/org/nd4j/nd4j-backend-impls/0.9.1/nd4j-backend-impls-0.9.1-linux-x86_64.${project.packaging}
```

Any ideas? Thanks!

**Comment by eed3si9n** [comment]
@kamilkloch Thanks for the report. Please follow the template on https://github.com/sbt/sbt/issues/new?assignees=&labels=Bug&template=---bug-report.md&title=  following the issue reporting guideline - https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md#what-to-report

**Comment by kamilkloch** [comment]
@eed3si9n I could not reproduce the error with sbt 1.3.4. Closing the issue. Thanks.
