### ISSUE TITLE
util and io should be in the main repository

### ISSUE THREAD

**Issue by eatkins** [sbt/sbt#5243]
I don't think the development overhead of having io and util in separate repositories is worth it. In the two years that I've been working on sbt, I can't recall any independent, non-milestone release of either. Those milestone releases were generally made just so that new code could be used in the sbt main repository.

**Comment by eatkins** [comment]
Even if they remain separate repositories, it might potentially be easier to develop features that cross boundaries if they were at least submodules of the main project.

**Comment by dwijnand** [comment]
100%.  It was a big mistake to split the sbt repo.  Even for Zinc I'm not sure it was worth it in the end.  Assuming we want to keep Zinc separate, the problem is some of the code in util and io are used by Zinc.  Everything else can come up, so you can start looking at that.  Also, you might want to consider merging the 2 repos and consider them "pre-zinc" sbt modules.

**Comment by eatkins** [comment]
Yeah. I left Zinc out because of the joint ownership with lightbend and the scala center. That being said, since Zinc is still a part of the sbt organization the repository separation doesn't achieve that much. My cursory git grepping suggests that it wouldn't be _that_ much work to replace the usages of `sbt.io.*`, `sbt.util.*` and `sbt.internal.util.*` from zinc and/or fork and shade them. Fully decoupling sbt and zinc might require making a zinc 2.0 to remove the sbt apis from zinc's public api but is definitely doable. I know that @jvican wanted to move over to java.nio apis from the java.io apis that are currently used anyway which would probably necessitate or at least encourage a 2.0 release.

I'm not personally excited about working on that myself, however. This is really about features like supershell and watch that cross the repository boundaries and are thus a pain to develop.

**Comment by smarter** [comment]
Yes please, I've wasted so much time coordinating PRs between these repos for simple changes I wanted to do.

**Comment by eed3si9n** [comment]
Ethan and I discuss this today in the meeting, and we agreed on moving util to sbt/sbt first as a try out. Zinc and IO would remain split for now.

This would create a situation where part 1 of sbt would be published before zinc, and then zinc, and then part 2 of sbt, when we do a full release like 1.3.0.

**Comment by dwijnand** [comment]
😱
