### ISSUE TITLE
"Multiple main classes detected" prompt uses println, leads to corrupt output with supershell

### ISSUE THREAD

**Issue by smarter** [sbt/sbt#5246]
See https://github.com/sbt/sbt/blob/964f7867b31c0765af0f59951541fcf1c130edf3/run/src/main/scala/sbt/SelectMainClass.scala#L23 (it seems like println should be banned in sbt to avoid this sort of things, or its output redirected somehow)

**Comment by eatkins** [comment]
Agreed. I experimented a bit with redirecting stdout recently. It’s not trivial but probably doable. Auditing printlns and changing them to log lines should be straightforward in many if not most cases.
