### ISSUE TITLE
Incorrect artifact resolution for maven artifacts

### ISSUE THREAD

**Issue by kstokoz** [sbt/sbt#526]
Commit 5903fb88a249b5d88fa2f0cd7c953cf44542f240 iin IvyInterfaces file changes the pattern for maven resolution of dependencies. 

If you append scala version and sbt version to groupId you should add same to file as well.
Like [organisation]/[module](_[scalaVersion])(_[sbtVersion])/[revision]/[artifact](_[scalaVersion])(_[sbtVersion])-[revision](-[classifier]).[ext]

Providing custom pattern like 
resolvers += Resolver.url("my-test-repo", url)(Patterns(Nil, List("[organisation]/[module]/[revision]/[artifact]-[revision](-[classifier]).[ext]"), true))
always uses ivy style.

**Comment by harrah** [comment]
What is the actual bug?  That commit does not affect normal dependencies, which do not have extra attributes.
