### ISSUE TITLE
Can not publish to Azure devops maven reporitory (Unauthorized)

### ISSUE THREAD

**Issue by jn73** [sbt/sbt#5264]
(masked out corporate specifics in logs/examaples)

## steps
- sbt version: 1.3.4
- build.sbt:
```
publishMavenStyle := true
publishTo := Some("maven repo" at "https://se01wstfs01.<masked>.com/SomeCollection/_packaging/corepi/maven/v1")
credentials += Credentials("https://se01wstfs01.<masked>.com/", "se01wstfs01.<masked>.com", "<user>", "<secret>")
```
- sbt publish

## problem
I run into an error when trying to `sbt publish` to a corporate internal maven repository that is hosted through an Azure DevOps server. To me it looks like a problem with the basic auth negotiation (the realm/Credential matching).

Logs (with company name masked):
```
[error] Unable to find credentials for [ @ se01wstfs01.<masked>.com].
[error]   Is one of these realms misspelled for host [se01wstfs01.<masked>.com]:
[error]   * https://se01wstfs01.<masked>.com/
[error] java.io.IOException: Access to URL https://se01wstfs01.<masked>.com/SomeCollection/_packaging/corepi/maven/v1/com/<masked>/queryservice_2.12/0.22-SNAPSHOT/queryservice_2.12-0.22-SNAPSHOT.pom was refused by the server: Unauthorized
[error] 	at org.apache.ivy.util.url.AbstractURLHandler.validatePutStatusCode(AbstractURLHandler.java:79)
[error] 	at org.apache.ivy.util.url.BasicURLHandler.upload(BasicURLHandler.java:264)
[error] 	at org.apache.ivy.util.url.URLHandlerDispatcher.upload(URLHandlerDispatcher.java:82)
[error] 	at org.apache.ivy.util.FileUtil.copy(FileUtil.java:150)
[error] 	at org.apache.ivy.plugins.repository.url.URLRepository.put(URLRepository.java:84)
``` 

It looks like the realm hasn't been parsed ok: `Unable to find credentials for [ @ se01wstfs01.<masked>.com]` 

I tried a PUT request on the same url and got the following www-authenticate headers back (code 401):

```
www-authenticate | Bearer
www-authenticate | Basic realm="https://se01wstfs01.<masked>.com/"
www-authenticate | Negotiate
www-authenticate | NTLM
```

Could ut be that the realm is being  parsed from the first www-authenticate header (Bearer) and therefore missed/empty? 

Is there any way to bypass this? Force some credential to being used?

**Comment by eed3si9n** [comment]
Could you add

```scala
credentials += Credentials("", "se01wstfs01.<masked>.com", "<user>", "<secret>")
```

and see if that works if Ivy thinks your realm is blank?

**Comment by jn73** [comment]
With the realm blank i still get Unauthorized (no question about spelling though):

```
[error] java.io.IOException: Access to URL https://se01wstfs01.<masked>.com/SomeCollection/_packaging/corepi/maven/v1/com/<masked>/queryservice_2.12/0.22-SNAPSHOT/queryservice_2.12-0.22-SNAPSHOT.pom was refused by the server: Unauthorized
[error] 	at org.apache.ivy.util.url.AbstractURLHandler.validatePutStatusCode(AbstractURLHandler.java:79)
[error] 	at org.apache.ivy.util.url.BasicURLHandler.upload(BasicURLHandler.java:264)
[error] 	at org.apache.ivy.util.url.URLHandlerDispatcher.upload(URLHandlerDispatcher.java:82)
[error] 	at org.apache.ivy.util.FileUtil.copy(FileUtil.java:150)
```

Setting it to `null` resulted in a NPR.

**Comment by rohit21agrawal** [comment]
@eed3si9n @jn73 did you find a way to make this work yet? i am trying to get this work for my team as well and keep hitting the same error.

Also, how is the host name mapped to a realm name?

**Comment by eed3si9n** [comment]
Actually let's close this and consolidate with https://github.com/sbt/sbt/issues/2366
