### ISSUE TITLE
mkl-platform-redist isn't showing up as a dependency

### ISSUE THREAD

**Issue by yukoba** [sbt/sbt#5268]
The original bug report is https://github.com/bytedeco/javacpp-presets/issues/823 .

## steps
sbt version: 1.3.4

My test code is https://github.com/yukoba/MklTest:

```scala
libraryDependencies += "org.bytedeco" % "mkl-platform" % "2019.5-1.5.2"
libraryDependencies += "org.bytedeco" % "mkl-platform-redist" % "2019.5-1.5.2"
```

## problem

I cannot use mkl-platform-redist on Sbt.

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnimkl_rt in java.library.path
```

## note

@saudet says sbt does not add it to the classpath and this looks like an issue with sbt.

I found that if I disable Coursier by ThisBuild / useCoursier := false this problem does not happen.

**Comment by yukoba** [comment]
I found that the problem comes from Coursier.
Either of these solves the problem.
1. Use sbt 1.2. Not 1.3.
2. Add ```ThisBuild / useCoursier := false``` and use sbt 1.3.

**Comment by eed3si9n** [comment]
@yukoba Thanks for the report.
