### ISSUE TITLE
cross builds commands not working anymore when triggered from commandline

### ISSUE THREAD

**Issue by FloWi** [sbt/sbt#5283]
## steps
sbt version: 1.3.0 (working) vs 1.3.4 (broken)

I created an example project [here](https://github.com/FloWi/sbt-crossbuild-broken). 

## problem
I wanted to trigger a cross build (e.g. the update command) via `sbt "+update"`
In version 1.3.0 it worked fine - in version 1.3.4 it is broken. sbt doesn't do anything and just outputs `Copying runtime jar.` and quits.

## expectation
sbt should resolve everything for all the given scala-versions.

## notes
Just follow the readme and see it fail for v1.3.4 and succeed for v1.3.0

**Comment by eed3si9n** [comment]
Thanks for the report. I wonder if this is related to https://github.com/sbt/sbt/issues/5270.

**Comment by SethTisue** [comment]
is it still reproducible with sbt 1.8.2?

why does the reproducer use Docker? shouldn't it be reproducible without involving Docker?

I tried `sbt +update` in some crossbuilt sbt 1.8.2 projects I have around, and it worked in every case.

**Comment by FloWi** [comment]
@SethTisue I'm closing this issue, since it's no longer relevant for me and I don't work in this project anymore. 

In my current job we don't have any issues with cross-building so I guess everything's fine :-)
