### ISSUE TITLE
Add IO.gunzipURL() method

### ISSUE THREAD

**Issue by alexanderdean** [sbt/sbt#529]
I believe the code needs to be something like this:

``` scala
def gunzipURL(from: URL, toDirectory: File, filter: NameFilter = AllPassFilter, preserveLastModified: Boolean = true): Set[File] =
  urlInputStream(from)(in => gunzipStream(in, toDirectory, filter, preserveLastModified))
def gunzipStream(from: InputStream, toDirectory: File, filter: NameFilter = AllPassFilter, preserveLastModified: Boolean = true): Set[File] =
{
  createDirectory(toDirectory)
  gzipInputStream(from) { gzipInput => extract(gzipInput, toDirectory, filter, preserveLastModified) }
}
```

**Comment by alexanderdean** [comment]
Note that it's currently not possible to hack this into a project's Build.scala because `IO.extract()` is private...

**Comment by harrah** [comment]
A gzip is not a zip, so extract wouldn't help even if it were public.  I assume you actually want a tar.gz, which the Java standard library doesn't implement support for.  A pull request for this is welcome.

**Comment by alexanderdean** [comment]
Thanks - me talking about `extract` was a bit of a red herring; it was just a plain `.gz` file I wanted to download and expand.

Anyway, code attached. I tried to follow your existing conventions exactly.

**Comment by alexanderdean** [comment]
Had a glitch in the first pull request. #56472bd is second time lucky...
