### ISSUE TITLE
Removing Coursier cache directory causes SBT to fail initialization

### ISSUE THREAD

**Issue by SvenssonWeb** [sbt/sbt#5292]
## steps
sbt version: `1.3.4`

Tested with all 1.3.x version up to 1.3.4

## problem
When removing the Coursier cache, all previously initialized SBT projects fail to load correctly.

The issue is mitigated by removing the `target/scala-2.12/sbt-1.0/update/update_cache_2.12/output` file.

Steps to reproduce:

1. Run `sbt version` in any project
2. Remove `~/.cache/coursier` catalogue
3. Re-run `sbt version` in the same project

## expectation
SBT should correctly trigger Coursier to refresh the now empty cache.

## notes
Since SBT init fail to load, no SBT command is possible to execute to fix the problem, requiring you to remove files manually inside the project catalogues.

**Comment by eed3si9n** [comment]
@SvenssonWeb Thanks for the report.

Others have run into this in a form of sbt not being able to launch in Docker where only the pwd is shared with Docker - https://github.com/sbt/sbt/issues/5142

**Comment by eed3si9n** [comment]
Here's a PR for this https://github.com/sbt/sbt/pull/5303
