### ISSUE TITLE
Include File Hashes for Downloads

### ISSUE THREAD

**Issue by james-crowley** [sbt/sbt#5294]
## Steps
N/A

## Problem
Most projects include file hashes with their downloads. Whether it is MD5, SHA1, SHA256 or SHA512, it would be nice to verify the download is correct.

## Expectation
You can take a look at [Ant's](http://archive.apache.org/dist/ant/binaries/) downloads. Each release they push they have the associated hashes. 

I expect to be able to download a universal package from the download [page](https://www.scala-sbt.org/download.html) and download the associated hash. 

## Notes
This is a security issue and I hope it gets fixed swiftly!

**Comment by eed3si9n** [comment]
We do publish PGP signature for each file if you add `.asc` at the end - <https://piccolo.link/sbt-1.3.4.tgz.asc>

**Comment by james-crowley** [comment]
@eed3si9n Thanks for the quick response! I glad to know you publish the signature for each file. Where would I get sbt's public key to verify the file?

Cause when I run this command, `gpg --verify sbt-1.3.4.tgz.asc sbt-1.3.4.tgz`, I get:

```
root@750b45235c2f:/# gpg --verify sbt-1.3.4.tgz.asc sbt-1.3.4.tgz
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: Signature made Sat Nov 23 19:38:07 2019 UTC
gpg:                using RSA key 2EE0EA64E40A89B84B2DF73499E82A75642AC823
gpg: Can't check signature: No public key
```

Additionally, would you guys be willing to add file hashes too?

**Comment by eed3si9n** [comment]
Here's the public key <https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823>

For the SHA hash, would it be ok if it's done for the downloads going forward and not back filled?

**Comment by james-crowley** [comment]
@eed3si9n Works for me! Thank so much for the information. 

Looking forward to seeing file hashes!

**Comment by eed3si9n** [comment]
Here's https://piccolo.link/sbt-1.3.5.tgz.sha256 for sbt 1.3.5.

**Comment by james-crowley** [comment]
@eed3si9n Thanks
