### ISSUE TITLE
Cached UpdateReport may become stale if cachedDescriptor was externally changed

### ISSUE THREAD

**Issue by jrudolph** [sbt/sbt#532]
One scenario where this happens is in jrudolph/sbt-cross-building#13. Here the last actually run `update` determines what the result of `deliver` will be. However, since the UpdateReport isn't considered stale even if the `cachedDescriptor` was changed (externally or by sbt), sbt will skip the `update` and `deliver` will happily deliver anything which is found at the `cachedDescriptor` location.

I could imagine that a fix for this issue would fix more of those scenarios where it is necessary to delete the `resolved*.xml` in the ivy cache to make something work.

The resolution could be to not only store the `cachedDescriptor` location but a hashsum over the contents as well in the UpdateReport and check if it is still current in the `uptodate` method in `Defaults.scala`.

**Comment by harrah** [comment]
This was a timely report as the cache is the subject of my current work.  I was aware of some of this (see c7f6ce4aec211b605b17e88ad37a9c9bb9c8068f from yesterday) but not the problem with plugin descriptors overwriting themselves.  Thanks for the detailed analysis.
