### ISSUE TITLE
Wrong classifier is silently ignored by coursier

### ISSUE THREAD

**Issue by pdalpra** [sbt/sbt#5324]
## steps
sbt version:1.3.5

* Clone https://github.com/pdalpra/coursier-test
* Go to the `netty-epoll-direct` folder, modify the netty dependency classifier to `woops` (any non existing classifier would do the trick too)
* Run `sbt update` => Dependency resolution is successful (fails with Ivy)
* Run `sbt 'show fullClasspath'` => Transitive dependencies are in the classpath, but not the dependency with the failed classifier (??)

## problem

Dependency with invalid classifiers are silently ignored, but there is still a partial dependency resolution done by coursier (I suspect based on the default classifiers) 

## expectation

sbt with coursier should fail dependency resolution if the classifier could not be found.

**Comment by eed3si9n** [comment]
@pdalpra Thanks for the report! Could you also report this to coursier/coursier please?

**Comment by pdalpra** [comment]
Done!
