### ISSUE TITLE
sbt occasionally outputs "Copying runtime jar." and completes successfully after 1 second

### ISSUE THREAD

**Issue by oharboe** [sbt/sbt#5326]
## steps
sbt version: 1.3.5

Run sbt as usual

## problem

Occasionally sbt outputs ```Copying runtime jar.``` and nothing else, no exit code(i.e. sbt completed succesfully). It completes in 1 second when this happens.

If I re-run sbt, it works fine.

## expectation

If there is a problem, sbt should not just output ```Copying runtime jar.``` and exit, but rather print out an error message.

**Comment by eed3si9n** [comment]
This might be a duplicate of https://github.com/sbt/sbt/issues/5270.

**Comment by oharboe** [comment]
@eed3si9n  Yes: I believe it is. Might as well close this bug. Sorry for the duplication.
