### ISSUE TITLE
sbt keeps a few empty lines after the prompt

### ISSUE THREAD

**Issue by Feuermurmel** [sbt/sbt#5331]
## steps
sbt version: 1.3.5

## problem
I just upgraded sbt and am using version 1.3.5 for the first time. I noticed that sbt somehow uses a few lines after the prompt to display some sort of progress (it's just a flickering mess on my machine, I'd rather have this information output on individual lines before the next prompt). I'm assuming that this prevents the last few lines of my terminal emulator from being used for input and permanent output:

<img width="490" alt="Screen Shot 2019-12-24 at 19 17 28" src="https://user-images.githubusercontent.com/50332/71422448-56145b00-2682-11ea-91b8-1f0727968551.png">

Even when just hitting return a few times, the prompt does not reach the last line of the terminal window:

<img width="490" alt="Screen Shot 2019-12-24 at 19 17 34" src="https://user-images.githubusercontent.com/50332/71422459-6af0ee80-2682-11ea-90be-1c21d51707c0.png">

Is this a problem with my setup or a bug in sbt?

## expectation

I would expect that after a task is done the input prompt _always_ sits on the last line of the terminal. This the behaviour I see in effectively every other shell-like console application I use.

**Comment by eatkins** [comment]
When using the task progress feature, aka supershell, there is a buffer zone for the progress line that will often prevent the cursor from reaching the last line in the terminal. In future versions of sbt, the buffer zone will be smaller so the prompt should appear closer to the bottom but will still probably sit one or two lines from the bottom.

You can disable supershell by adding `ThisBuild / useSuperShell := false`.

**Comment by Feuermurmel** [comment]
Thanks for the quick response and clarification! So this is expected behaviour? This sucks! :(

Is there a way to set `useSuperShell` in the context of my local user (i.e. a file under `~`) instead of a specific sbt project? I would like to disable this feature, but don't want to force this decision on anyone else working on the same projects.

**Comment by eatkins** [comment]
> This sucks! :(

Please keep your comments respectful.

> Is there a way to set useSuperShell in the context of my local user (i.e. a file under ~) instead of a specific sbt project?

You can set global configuration in `~/.sbt/1.0/global.sbt`.

**Comment by Feuermurmel** [comment]
> > This sucks! :(
> 
> Please keep your comments respectful.
> 

I'm sorry that my comment came across disrespectful. This was not my intention and I removed that part.

> > Is there a way to set useSuperShell in the context of my local user (i.e. a file under ~) instead of a specific sbt project?
> 
> You can set global configuration in `~/.sbt/1.0/global.sbt`.

Hmm. That's a great tip but I think, from what I'm observing, that the supershell is still active during startup and only disabled after the first prompt is shown. This is an improvement in my case but I would still be glad to be able to disable it completely.

Oh, and it does break all projects that do not yet know about that setting. :/

**Comment by eed3si9n** [comment]
You should also be able to define`SBT_OPTS=-Dsbt.supershell=never` to globally opt out of supershell across different sbt versions.
