### ISSUE TITLE
update to new Coursier when it comes out

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#5333]
I'm interested in 2.0.0-RC5-4 for https://github.com/coursier/coursier/pull/1457, but it seems to have introduced a bug that was caught in sbt-coursier PR - https://github.com/coursier/sbt-coursier/pull/170

**Comment by alexarchambault** [comment]
FYI, lm-coursier-shaded [`2.0.0-RC5-3`](https://github.com/coursier/sbt-coursier/releases/tag/v2.0.0-RC5-3) is [out](https://repo1.maven.org/maven2/io/get-coursier/lm-coursier-shaded_2.12/2.0.0-RC5-3/).

**Comment by eed3si9n** [comment]
Thanks!
