### ISSUE TITLE
SBT launcher script expanding asterisks as globs in task arguments

### ISSUE THREAD

**Issue by bpiper** [sbt/sbt#5343]
## steps
sbt version: 1.3.0+

Run SBT's testOnly task from bash with a wildcard test suite matcher and additional arguments, e.g.
```
sbt "testOnly * -- -l foo.ExcludedTag"
```

## problem

The asterisk is glob-expanded by the launcher script (`/usr/bin/sbt`), resulting in a command that doesn't actually run any tests, e.g.

`java -jar /usr/share/sbt/bin/sbt-launch.jar 'testOnly build.sbt someSubDir1 someSubDir2 -- -l foo.ExcludedTag'`

## expectation

Asterisks should not be expanded, and resulting java command should be something like this:

`java -jar /usr/share/sbt/bin/sbt-launch.jar 'testOnly * -- -l foo.ExcludedTag'`

## notes

Behaviour is correct in SBT 1.2.8, but broken as of 1.3.0 and later.  The glob expansion appears to occur around about this line in the launcher script:

```
miniscript=$(map_args "${sbt_options0[@]}") && eval ${miniscript/retarr/sbt_options}
```

If there are no additional args, e.g. just `testOnly *` then glob expansion doesn't occur.  Not really familiar enough with this script to offer an optimal solution.

**Comment by eed3si9n** [comment]
@bpiper Thanks for the detailed bug report!

**Comment by eed3si9n** [comment]
@bpiper I can't reproduce this on macOS or on Travis CI, except on Windows batch file (https://github.com/sbt/sbt-launcher-package/pull/317). How was `sbt` launcher script installed?

**Comment by bpiper** [comment]
@eed3si9n sorry I should have made it explicit - this was on Ubuntu 18.04 using the sbt Debian package.

**Comment by eed3si9n** [comment]
This was my mistake. I kept testing `sbt "testOnly *"` instead of the provided steps. Using `"testOnly * -- -l foo.ExcludedTag"` I can repro this on macOS.

```
$ sbt "testOnly * -- -l foo.ExcludedTag" -v
[process_args] java_version = '8'
[sbt_options] declare -a sbt_options='([0]="-Xms2048M" [1]="-Xmx2048M" [2]="-Xss2M")'
# Executing command line:
java
-Dfile.encoding=UTF-8
-Xms2048M
-Xmx2048M
-Xss2M
-jar
/usr/local/Cellar/sbt/1.3.6/libexec/bin/sbt-launch.jar
"testOnly build.sbt project src target -- -l foo.ExcludedTag"
```

**Comment by eed3si9n** [comment]
A shorter reproduction is `sbt "testOnly * " -v`.
