### ISSUE TITLE
ProjectRef no longer resolves correctly in 0.12.0

### ISSUE THREAD

**Issue by crimsoncor** [sbt/sbt#536]
As far as I can tell, the API for specifying ProjectRefs did not change between 0.11.3 and 0.12.0, but projects that use ProjectRef load fine in  0.11.3 and will not load at all in 0.12.0.  I've put together a minimal example here: https://github.com/crimsoncor/sbtBug that demonstrates the issue.

**Comment by harrah** [comment]
I was working on this today in order to answer your email, realized it was a duplicate of #511, and that it was fixable.  It took a bit longer than expected, so sorry I didn't respond earlier to save you the trouble of following up.

**Comment by crimsoncor** [comment]
No worries.  I looked in the bug DB and didn't see anything that looked similar.  When no one replied to the email, I figured no one else had run into the issue, so I made a simple test case.  Glad it got fixed.  
Thanks!
