### ISSUE TITLE
SBT Unable To Fetch Play 2.7.4

### ISSUE THREAD

**Issue by neilchaudhuri** [sbt/sbt#5366]
## steps
sbt version: 1.3.5

## problem

SBT does not fetch Play Framework's SBT plugin.

## expectation

SBT should fetch Play Framework's SBT plugin.

## notes

```
resolvers += Resolver.typesafeRepo("releases")
resolvers += Resolver.typesafeIvyRepo("releases")
resolvers += Resolver.typesafeRepo("snapshots")
resolvers += Resolver.jcenterRepo
resolvers += Resolver.sbtPluginRepo("releases")
resolvers += Resolver.url("heroku-sbt-plugin-releases", url("http://dl.bintray.com/heroku/sbt-plugins/"))(Resolver.ivyStylePatterns)
resolvers += Resolver.bintrayRepo("neomaclin", "maven")
resolvers += Resolver.bintrayRepo("playframework", "sbt-plugin-releases")

addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.7.4")
```

None of that finds Play 2.7.4, which is located here

https://dl.bintray.com/playframework/sbt-plugin-releases/com.typesafe.play/sbt-plugin/scala_2.12/sbt_1.0/2.7.4/ivys/ivy.xml

The closest SBT's dependency resolution comes is this:

`[error]   not found: https://dl.bintray.com/playframework/sbt-plugin-releases/com/typesafe/play/sbt-plugin_2.12_1.0/2.7.4/sbt-plugin-2.7.4.pom`

**Comment by neilchaudhuri** [comment]
Just wanted to point out that I reverted everything to sbt 0.13.8 and made no other changes but upgrade to 1.3.6 and found the same host of errors with the inability to fetch dependencies where 0.13.8 had no problem at all.

**Comment by eatkins** [comment]
Just for the record, sbt 1.3.6 has no problem resolving the play plugin using the default resolvers. I don't necessarily know why your 0.13.18 build doesn't work with 1.3.6 but I wonder if it would work if you ran sbt with `-Dsbt.coursier=false`. We switched the default dependency management implementation from ivy to coursier in the 1.3.x series. There may be some issues with certain resolvers behaving differently with coursier vs. ivy.

**Comment by neilchaudhuri** [comment]
Thanks for letting me know.

As it turned out, sbt was fine--except for all the warnings related to http/s. I figured this out by running at the command line. It turns out all those PKIX errors are a function of IntelliJ. The solution seems to be upgrading JDK there although it still isn't working as it should, but that's another issue.

**Comment by eatkins** [comment]
Sorry to hear about Intellij but glad that sbt has been exonerated!
