### ISSUE TITLE
Provide a simple way for a local project to depend on another local project with a different scalaBinaryVersion (important for dotty/scala2 interop)

### ISSUE THREAD

**Issue by smarter** [sbt/sbt#5369]
Dotty can read Scala 2 signatures (and soon the reverse will be true too), so a dotty project can depend on a scala 2 project, sbt-dotty makes this as convenient as possible by providing a `withDottyCompat` method to change the cross version:
```scala
libraryDependencies += ("a" %% "b" % "c").withDottyCompat(scalaVersion.value)
```
However, when using `dependsOn` to declare a local dependency between two projects, there is no way to specify the cross version, this prevents having a local dotty project that depends on a local scala2 project and vice-versa, even though this would be extremely useful for progressively porting a project to dotty.

As a workaround, one can fiddle with `projectDependencies`, but it's not very nice:
```scala
lazy val scala2Lib = project.in(file("scala2Lib"))
  .settings(
    scalaVersion := "2.13.1"
  )

lazy val dottyApp = project.in(file("dottyApp"))
  .dependsOn(scala2Lib)
  .settings(
    // Set withDottyCompat on the scala2Lib dependency if we had a mix of dotty
    // and scala2 dependencies, we would have to be more careful here.
    projectDependencies := {
      projectDependencies.value.map(_.withDottyCompat(scalaVersion.value))
    },
    scalaVersion := "0.21.0-RC1"
  )
```

**Comment by eed3si9n** [comment]
What would the expectation here? Should the following work out of the box?

```scala
val dottyVersion = "0.21.0-RC1"

lazy val scala2Lib = project.in(file("scala2Lib"))
  .settings(
    scalaVersion := "2.13.1"
  )

lazy val dottyApp = project.in(file("dottyApp"))
  .dependsOn(scala2Lib)
  .settings(
    scalaVersion := "0.21.0-RC1"
  )
```

**Comment by smarter** [comment]
Out of the box would be nice, failing that I would be OK with something like having to use `dottyCompatDependsOn(scala2Lib)` instead of `dependsOn(scala2Lib)`

**Comment by dwijnand** [comment]
> As a workaround, one can fiddle with `projectDependencies`, but it's not very nice:

TIL, that's useful to know, thank you.

**Comment by olofwalker** [comment]
@eed3si9n Was this issue addressed on the SBT side?

**Comment by eed3si9n** [comment]
No action has been taken yet.

**Comment by adpi2** [comment]
As an alternative one can set the `crossVersion` in the `scala2Lib` project:

```scala
lazy val scala2Lib = project.in(file("scala2Lib"))
  .settings(
    scalaVersion := "2.13.3",
    crossVersion := CrossVersion.constant("0.26.0-RC1")
  )

lazy val dottyApp = project.in(file("dottyApp"))
  .dependsOn(scala2Lib)
  .settings(
    scalaVersion := "0.26.0-RC1"
  )
```
But I am not sure if it is a good idea in general.

**Comment by eed3si9n** [comment]
Here's my PR for this - https://github.com/sbt/sbt/pull/5767

@adpi2 `CrossVersion.constant("0.26.0-RC1")` may use `_0.26.0-RC1` as opposed to the normal binary suffix?

**Comment by adpi2** [comment]
> CrossVersion.constant("0.26.0-RC1") may use _0.26.0-RC1 as opposed to the normal binary suffix?

Here the `scala2lib` is only compiled to the `scala2lib\target\scala-2.13` directory. My understanding is that the `CrossVersion.constant("0.26.0-RC1")` tells sbt that the project can be consumed by a `0.26.0-RC1` project. It does not change the binary version of neither the dependency nor the dependent project.

It works as well if I write `CrossVersion.constant("0.26")`.
