### ISSUE TITLE
[1.3.7] updateSbtClassifiers fails if some sources are not available

### ISSUE THREAD

**Issue by OlegYch** [sbt/sbt#5374]
## steps
sbt version: 1.3.7
add

```scala
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.0")
```

to project/plugins.sbt
run updateSbtClassifiers or try to import project in intellij

## problem

```
[error] (updateSbtClassifiers) lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] https://repo1.maven.org/maven2/org/webjars/npm/4.2.0/npm-4.2.0-sources.jar: not found: https://repo1.maven.org/maven2/org/webjars/npm/4.2.0/npm-4.2.0-sources.jar
```

## expectation
update(Sbt)classifiers should continue if any source/doc downloads are not available

**Comment by OlegYch** [comment]
sbt 1.3.6 works correctly

**Comment by OlegYch** [comment]
hm, now i can't reproduce this...

**Comment by eed3si9n** [comment]
There's a flag in UpdateConfiguration called `missingOk` - https://github.com/sbt/librarymanagement/blob/v1.3.1/core/src/main/contraband-scala/sbt/librarymanagement/UpdateConfiguration.scala
I wonder if that's not being respected.

**Comment by OlegYch** [comment]
yeah lmcoursier.CoursierDependencyResolution#update ignores updateConfiguration

**Comment by mikail-khan** [comment]
Still broken even with the release of 1.3.8

**Comment by eed3si9n** [comment]
@OlegYch Could you open an issue on coursier/coursier?

**Comment by OlegYch** [comment]
@eed3si9n opened https://github.com/coursier/coursier/issues/1541

**Comment by eed3si9n** [comment]
I am going to close this since I realized there's https://github.com/sbt/sbt/issues/4707

**Comment by He-Pin** [comment]
```
[error] (akka-multi-node-testkit / updateSbtClassifiers) lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] https://repo1.maven.org/maven2/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava-sources.jar: not found: https://repo1.maven.org/maven2/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava-sources.jar
[error] (updateSbtClassifiers) lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] https://repo1.maven.org/maven2/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava-sources.jar: not found: https://repo1.maven.org/maven2/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava-sources.jar
[error] Total time: 19 s, completed 2020年3月29日 上午6:14:38
```

**Comment by jeffrey-aguilera** [comment]
Returned in 1.3.12...

**Comment by zhaihao** [comment]
Returned in 1.3.13

**Comment by NicolasRouquette** [comment]
I downgraded to 1.3.11, which seems OK; 1.3.12 and 1.3.13 didn't work for me.

**Comment by JayZYan** [comment]
tried 1.3.13, 1.3.12, 1.3.11, all not working for me...Downgrade to 1.3.6, which worked for me...

**Comment by nmatkheev** [comment]
Had the same thing, found two equivalent tricks:  
* disabling local maven repo in ~/.sbt/repositories
* manual deletion of folder from .m2, where artifact mentioned in error message is stored
