### ISSUE TITLE
[1.3.7] Transitive dependency on aws-java-sdk-bom fails to update project

### ISSUE THREAD

**Issue by anilkumarmyla** [sbt/sbt#5379]
## steps
sbt version: 1.3.7

## problem
Any project including bom (bill of materials) pom of aws sdk transitively fails to update with the following error message

```
libraryDependencies +=  "com.yahoo.athenz" % "athenz-zts-java-client-core" % "1.8.43"
..
sbt update
..
[error]   not found: https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-sts/${awsjavasdk.version}/aws-java-sdk-sts-${awsjavasdk.version}.pom
```

## expectation
This does not happen in 1.3.6 or lower, most probably a coursier regression

**Comment by eed3si9n** [comment]
@anilkumarmyla Thanks for the report. Could you also report this to coursier/coursier please?

**Comment by anilkumarmyla** [comment]
@eed3si9n This issue is merged upstream and can be probably be closed after the necessary coursier upgrade. Any timeline of the upcoming sbt release?

**Comment by eed3si9n** [comment]
I don't have a set schedule, but patch releases have been coming out every 2~4 weeks.

**Comment by eed3si9n** [comment]
Oops. I forgot about this for 1.3.8.

**Comment by anilkumarmyla** [comment]
@eed3si9n when is the next expected sbt release?

**Comment by eed3si9n** [comment]
There hasn't been many fixes, but I guess we can get a release out this week or next.
