### ISSUE TITLE
Ivy settings scripted tests are failing

### ISSUE THREAD

**Issue by eatkins** [sbt/sbt#5382]
## steps
sbt version: develop

## problem
A number of ivy settings tests seem to specify insecure resolvers that are now failing. Here is a sample failing CI build: https://travis-ci.org/sbt/sbt/jobs/637599650

## expectation
The tests use secure (or local) resolvers.

## notes

I am not familiar with ivy-settings.xml and there were no urls (secure or otherwise) or ssl related toggles in the scripted tests so I quickly gave up on debugging this. A sample broken ivysettings.xml file can be found here: https://github.com/sbt/sbt/blob/develop/sbt/src/sbt-test/dependency-management/ivy-settings-a/changes/scala-tools-ivysettings.xml.

**Comment by eed3si9n** [comment]
I am kind of ok with removing any Ivy specific weird feature tests.

**Comment by eatkins** [comment]
Here is why the tests started failing: https://blog.sonatype.com/central-repository-moving-to-https

**Comment by eatkins** [comment]
Disabled in #5383.
