### ISSUE TITLE
When using multiple test configurations without testGrouping, the wrong tests are run

### ISSUE THREAD

**Issue by szeiger** [sbt/sbt#539]
I am using this sbt build with the highlighted workaround for setting a dummy test grouping for both, the standard Test configuration and my own DocTest configuration: https://github.com/typesafehub/doc-example/blob/02836ed9901c7ebf5880ac7eae98b933f51238b9/project/Build.scala#L15-L18

Without these explicit testGroupings, the doctest:test command runs the same tests as the standard test command, instead of its own doctest tests.

**Comment by vigdorchik** [comment]
I think when you just say `testGrouping <<= definedTests in Test map partitionTests`
you override testGrouping for all configurations to be a result of partitioning `definedTests in Tests`.  If you want the same function to apply to all configurations, just say `testGrouping <<= definedTests map partitionTests`. Otherwise you can detail the target on the left hand-side.

**Comment by szeiger** [comment]
But even without any testGrouping for any of the configurations, the wrong tests are run.

**Comment by vigdorchik** [comment]
Can you make a public repository that demonstrates the problem?

**Comment by szeiger** [comment]
Ah, sorry, the original repo is private. You should be able to access it now. But the problem can also be reproduced with https://github.com/slick/slick. Just run doctest:test -> runs the correct tests for "doctest", then comment out both testGrouping lines in Build.scala, reload and run again -> now it runs the tests for "test" instead of "doctest".

**Comment by vigdorchik** [comment]
Actually you only need the second setting `testGrouping in DocTest <<= definedTests in DocTest map partitionTests` but it's true, without it the code in sbt
https://github.com/harrah/xsbt/blob/0.13/main/Defaults.scala#L313
groups the wrong tests. I'm not sure about the fix though.
