### ISSUE TITLE
Custom configuration scope sources jar ends up in jars folder instead of srcs on publishing

### ISSUE THREAD

**Issue by rohit21agrawal** [sbt/sbt#5391]
https://stackoverflow.com/questions/59795760/custom-configuration-src-jar-ending-up-in-jars-folder-instead-of-srcs-when-using#

## steps
sbt version: *1.3.3*

```scala
ThisBuild / scalaVersion     := "2.12.10"
ThisBuild / version          := "0.1.0-SNAPSHOT"
ThisBuild / organization     := "com.example"
ThisBuild / organizationName := "example"

lazy val Dev = config("dev").extend(Compile)
  .describedAs("Dependencies required for development environments")

lazy val root = (project in file("."))
  .configs(Dev)
  .settings(
    name := "datapipeline-framework",
    inConfig(Dev)(Defaults.compileSettings),
    addArtifact(Dev / packageBin / artifact, Dev / packageBin),
    addArtifact(Dev / packageDoc / artifact, Dev / packageDoc),
    addArtifact(Dev / packageSrc / artifact, Dev / packageSrc),
    Dev / publishArtifact := true,
    Test / dependencyClasspath ++= Seq(Attributed.blank((Test / classDirectory).value))
  )
```

From sbt shell:

```
> publishLocal
```

## problem

I have a custom configuration called "Dev" defined in my sbt file, but when i am publishing the sources-jar it's ending up in the jars folder instead of srcs folder (for publishLocal) ...

## expectation
dev-sources.jar should end up in srcs folder.

**Comment by eed3si9n** [comment]
> anyone knows how to fix this so it ends up in the right place?

We use GitHub issue mostly to track bugs and discuss feature or bugs on sbt. If you need help, please check this out - https://www.scala-sbt.org/support.html#how-can-I-get-help

**Comment by rohit21agrawal** [comment]
@eed3si9n 

I have tried gitter and stackoverflow, but with no help available.

https://stackoverflow.com/questions/59795760/custom-configuration-src-jar-ending-up-in-jars-folder-instead-of-srcs-when-using#

It's only when i ran out of options, i figured it might even be a bug, which is why i decided to post here. How do you determine if it's a bug or not?

**Comment by eed3si9n** [comment]
> It's only when i ran out of options, i figured it might even be a bug, which is why i decided to post here. How do you determine if it's a bug or not?

I think it's case by case. If some build used to work in some version, but stopped working for whatever reason, that might be considered a bug immediately. I generally prefer undetermined cases to go Stackoverflow since otherwise GitHub issues will fill up with un-triaged questions. I can take a look at your Stackoverflow question later.

**Comment by rohit21agrawal** [comment]
@eed3si9n  any chance you got to take a look at it? not trying to rush you..but just looking for a resolution so we can decide whether we can ship this additional configuration/scope without issues.

**Comment by eed3si9n** [comment]
I've updated the description to simplify the problem, and posted my answer here - https://stackoverflow.com/a/59924791/3827

The workaround is to add

```scala
    Dev / packageDoc / artifact ~= { _.withType("doc") },
    Dev / packageSrc / artifact ~= { _.withType("src") },
```

It's not a big deal if you know what's going on, but sbt should probably create an `Artifact` based on `Dev / packageSrc / artifactClassifier`.
