### ISSUE TITLE
Unable to compile after Java downgrade from 13 to 8

### ISSUE THREAD

**Issue by gavinbaumanis** [sbt/sbt#5393]
## steps
sbt version: *1.3.7*

## background
I was previously using openJDK 13 - and have swapped back ot Oracle 8_202 so that I can successfully compile a PlayFramework fork.

## problem
In a completely separate application I used;
```
sbt clean cleanFiles clearCaches compile test
```

but it fails with;
```
[error] /Users/gavinbaumanis/workspace/ecpr/pas/conf/routes: cannot access router.RoutesPrefix
[error]   bad class file: /Users/gavinbaumanis/workspace/ecpr/pas/target/scala-2.13/classes/router/RoutesPrefix.class
[error]     class file has wrong version 56.0, should be 52.0
[error]     Please remove or make sure it appears in the correct subdirectory of the classpath.
[error] (Compile / compileIncremental) javac returned non-zero exit code
```

## expectation
Should clean and or cleanFiles ensure this doesn't happen?

**Comment by gavinbaumanis** [comment]
IO manually deleted;
target/
project/project/
project/target/

and retried - but still get the same error.

**Comment by eatkins** [comment]
That does seem weird. If you run `find . -name "RoutesPrefix.class"`, does it exist anywhere?

If not, is it possible that you may have inadvertently published play using some classes compiled with jdk13? I have personally seen somewhat similar errors when I have inadvertently published a local copy of a dependency using a newer version of the jdk.

**Comment by gavinbaumanis** [comment]
I have managed to work it out - and (possibly) as expected this is a user error.
I had TARGET:11 defined in scala.sbt

Which isn;t going to work when you have 8 installed!
TARGET:8 - corrected the issue.

Double checked by reinstalling 13, compiling successfully,
(target:12)
Downgrading to java 8
(target:12)

Failed again.

Ensuring the target matches (or lesser) than the installed JDK - ensures successful compilation.
