### ISSUE TITLE
Snapshot versions not updated properly between local and remote 

### ISSUE THREAD

**Issue by OndrejSpanel** [sbt/sbt#5397]
This is similar to #5377

I am convinced what I see is an issue, but convince me if I am wrong or missing some obvious setting.

## steps
sbt version: 1.3.7

I have a library for which sometimes I publish snapshots, sometimes local, sometimes remote. The library is referenced in the sbt as:

`libraryDependencies += "net.xxx" %% "yyyy" % "0.112.1-SNAPSHOT" changing()`

I have also tried just `libraryDependencies += "net.xxx" %% "yyyy" % "0.112.1-SNAPSHOT"`  with the same result.

## problem

No matter how I update and clean in the sbt, the project is using the version I have last published locally.

## expectation

I expect remote snapshots should be able to override local ones, at least once the local ones are sufficiently old.

## notes

What I see now is my local published version was last modified 21/1/2020 13:50 (both jars and pom), which means it is almost two days old, certainly more than 24h TTL. I have just published a new version on a private remote nexus, I have verified it exists there with following modification timestamps:

The jar file:  Blob updated | Thu Jan 23 2020 13:02:04 GMT+0100
The pom file:  Blob updated | Fri Jan 17 2020 17:10:16 GMT+0100

I am not sure if the fact the pom file timestamp is not updated is an issue or not, I use built-in SBT `publishMavenStyle` and `publishTo` for publishing.

**Comment by eed3si9n** [comment]
I personally think SNAPSHOT should never be used outside of local testing, and I don't really have high expectations on dependency resolvers being able to accurately compare publish dates. There's code in Apache Ivy that literally screen scrapes for the directory output of Apache HTTP for example, and Ivy (still used for publishing) also doesn't publish `maven-metadata.xml`. Does your Nexus generate one?

In any case, if you suspect there's an issue with TTL, please report to coursier/coursier as well.

**Comment by OndrejSpanel** [comment]
> also doesn't publish maven-metadata.xml. Does your Nexus generate one?

I really do not understand much about package publishing.

How would I know? Where and what should I look for?

**Comment by eed3si9n** [comment]
Looks something like this - https://repo1.maven.org/maven2/org/foundweekends/giter8/giter8_2.12/maven-metadata.xml

**Comment by OndrejSpanel** [comment]
If the metadata is required for this to work correctly, I can confirm it was somehow broken on our Nexus, for reasons unknown to me. Details follow. I will try if fixing them has resolved the issue later.

----

I see metadata relevant for the artifact I am interested about on our nexus. It seems not updated and not downloaded recently. The content is:

```
<metadata modelVersion="1.1.0">
<groupId>net.xxxx</groupId>
<artifactId>yyyy_2.12</artifactId>
<versioning>
<latest>0.88.5-SNAPSHOT</latest>
<versions>
<version>0.88.4-SNAPSHOT</version>
<version>0.88.5-SNAPSHOT</version>
</versions>
<lastUpdated>20191214010007</lastUpdated>
</versioning>
</metadata>
```
This somewhat corresponds to the info shown:

> Blob created | Sat Dec 14 2019 02:00:07 GMT+0100
> Blob updated | Sat Dec 14 2019 02:00:07 GMT+0100
> Last downloaded | Sat Dec 14 2019

I am not sure what has changed since the 0.88 was published. I use SBT 0.13.17 in the project used to publish this artifact since 2018, 0.13.16 was used before. Based on Git history version 0.88.5-SNAPSHOT was published 28.11.2017. Since then multiple snapshot versions were published, including 0.88.7-SNAPSHOT. No version seems to be published near 14.12.2019, I have no idea why this is the last update time for the metadata, I think most likely is some configuration change on the Nexus happened then. I have created and ran a "Rebuild metadata" task, now I can also the recent snapshots listed there.

**Comment by OndrejSpanel** [comment]
@eed3si9n I have just tried updating and I can see fixing the metadata did not help. This corresponds with the fact Nexus is reporting "Last downloaded | Thu Jan 23 2020", which is yesterday, not today - updating from SBT does not seem to read the metadata related to the corresponding snapshot artifact at all.

Metadata were read once I have changed `build.sbt` to request the snapshot which is not published locally (0.112.2-SNAPSHOT). The nexus info has immediately changed to "Last downloaded | Fri Jan 24 2020" in such situation.

I think SBT 1.3.x (Coursier) is strictly preferring local artifacts and once it finds them, it does not ask about remote ones at all.

**Comment by eed3si9n** [comment]
It seems like a Coursier issue or behavior then. Could you open an issue on coursier/coursier to discuss it please?

**Comment by dzagorovsky** [comment]
@eed3si9n could you please suggest any workaround?

**Comment by eed3si9n** [comment]
I don't think we should use SNAPSHOT outside of local testing, so I don't have any further suggestions on this.
Please use https://github.com/dwijnand/sbt-dynver.

**Comment by linehrr** [comment]
delete the folder under:
<projectRoot/project/target>
that's where sbt keeps lib cache. 
also to be sure, you also wipe .iv2/cache. 
that should fix it.
