### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by mahfooziiitian** [sbt/sbt#5398]
- Issue Type: `Bug`
- Extension Name: `vscode-sbt-scala`
- Extension Version: `0.2.4`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.41.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by eed3si9n** [comment]
Looks like it's missing the actual bug report.
