### ISSUE TITLE
Cyclic reference with 0.10.1-SNAPSHOT and Web plugin

### ISSUE THREAD

**Issue by ijuma** [sbt/sbt#54]
I am getting the following cycle reference with 0.10.1-SNAPSHOT and the web plugin (I replaced the project names):

Cyclic reference involving {file:/root-project-path/}subproject-name/_:prepare-webapp, {file:/root-project-path/}subproject-name/_:jetty-classpaths, {file:/root-project-path/}subproject-name/runtime:full-classpath, {file:/root-project-path/}subproject-name/runtime:exported-products, {file:/root-project-path/}subproject-name/package, {file:/root-project-path/}subproject-name/package-configuration(for package), {file:/root-project-path/}subproject-name/mappings(for package)

The exact same build file works fine with 0.10.0. Does this make it clear what the issue is or do you need an isolated test case?

**Comment by ijuma** [comment]
I can confirm that removing the settings from the web plugin fixes this.

**Comment by harrah** [comment]
I tried to reproduce by declaring a source plugin dependency on the web plugin.  I had to fix a bug that was causing a cyclic dependency in Projects (in the commit referenced above).  Once that was fixed, I didn't see this cyclic reference in settings.  Can you try the latest and let me know what exactly causes the problem?

**Comment by ijuma** [comment]
I tried with the latest and it works now. Thanks!
