### ISSUE TITLE
Upgrading Play Project to 1.3.7 triggers incorrect warnings

### ISSUE THREAD

**Issue by mikail-khan** [sbt/sbt#5400]
sbt version: *1.3.7*

## steps

https://github.com/hmrc/cgt-property-disposals-frontend

Clone it, open up an sbt session and run compile. You will see the warnings.

## problem
Upgrading a Play 2.6 project to use sbt 1.3.7 is triggering warnings on Twirl templates having unused imports:

```scala
 Unused import
[warn] @*
[warn] ^
[warn] one warning found
```
That is actually a Twirl comment.

and

```scala
[warn] app.routes: Unused import
```
This Play route is actually used.

## expectation
Should not trigger warnings in these cases.

**Comment by eed3si9n** [comment]
@co-category Thanks for the report. Could you follow https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md#what-to-report and describe the steps needed to reproduce the problems on our machines please?

**Comment by mikail-khan** [comment]
@eed3si9n you can access the repo that has this bug here:

https://github.com/hmrc/cgt-property-disposals-frontend

Clone it, open up an sbt session and run `compile`. You will see the warnings.

**Comment by eed3si9n** [comment]
@mikail-khan I think this is actually an unused import created by Twirl.
See https://github.com/playframework/twirl/issues/105.
