### ISSUE TITLE
Incorrect 404 error when accessing repo

### ISSUE THREAD

**Issue by pysa** [sbt/sbt#542]
Hi,

When accessing a repository, if the host name can't be resolved, the error indicated by SBT is 404, which is not correct and is very misleading. The error message should indicate a DNS resolution problem.

By the way, I could not found any indication about how to setup DNS for SBT. I supposed it would work out of the box, but is does not. I am specifying :

resolvers += "repo-name" at "http://hostname:8081/artifactory/repo"

and getting a 404 error although using wget in the same console to access the dependency works perfectly.

Replacing "hostname" with the IP address solves the problem.

Pierre-Yves

**Comment by harrah** [comment]
sbt doesn't need DNS set up for it specifically, although a proxy may need to be configured.  Please use the [mailing list](http://groups.google.com/group/simple-build-tool/topics) or stackoverflow.com for troubleshooting and show the full output that indicates the 404 and the wget command that is run.
