### ISSUE TITLE
sbt.bat launcher is not working from a "program files (x86)"subfolder

### ISSUE THREAD

**Issue by NirvanaNrv** [sbt/sbt#5420]
## steps

Have sbt.bat in your path. Clone any sbt project in c:\program file (x86), go there and try invoking sbt.bat from there.

## problem

The shell reports "\folder was unexpected"; the closing parenthesis in the path does bad with the echo instruction within a parenthesis bloc.

## expectation

Launches.

## notes
A simple quoting of %CD% works, and I would not mind the lesser alteration of the message from it. Anyway, it would not even display when we are in a correct sbt project folder.
My use case was trying to open the sbt prompt from a Jenkins' workspace, which by default goes in a such (x86) subfolder.

**Comment by eed3si9n** [comment]
@NirvanaNrv Thanks for the report. Could you tell us which version of the installation are you using?

**Comment by NirvanaNrv** [comment]
@eed3si9n, you are welcome. I had just reinstalled sbt, so that was 1.3.8 (msi). The server where I noticed it first was 1.3.4.

**Comment by l-konov** [comment]
Same issue. Sbt 1.3.10.
For me workaround is changing Jenkins workspace directory.

**Comment by l-konov** [comment]
Following warn in sbt with echo on: 
     echo [warn] Neither build.sbt nor a 'project' directory in the current directory: C:\Program Files (x86)\Jenkins\workspace\Jenkins-item-name
But build.sbt and project exists

**Comment by eed3si9n** [comment]
https://github.com/sbt/sbt-launcher-package/pull/324 hopefully fixes this.
