### ISSUE TITLE
Enable GPG signatures for the RPM repo

### ISSUE THREAD

**Issue by dskrvk** [sbt/sbt#5426]
The RPM repo [file](https://bintray.com/sbt/rpm/rpm) has `gpgcheck=0` since the releases there are currently not signed. This is a pretty serious security issue for anyone using SBT as part of their release process on an RHEL/CentOS machine. The corresponding Debian releases already include signatures. What would it take to enable them for RPM as well?

This is a follow-up to https://github.com/sbt/sbt/issues/2049. See also the [post](https://access.redhat.com/blogs/766093/posts/1976693) on secure RPM distribution originally linked in that issue.

**Comment by eed3si9n** [comment]
The repo file is generated by Bintray.

```
$ curl https://bintray.com/sbt/rpm/rpm
#bintray--sbt-rpm - packages by  from Bintray
[bintray--sbt-rpm]
name=bintray--sbt-rpm
baseurl=https://sbt.bintray.com/rpm
gpgcheck=0
repo_gpgcheck=0
enabled=1
```

<s>`*.asc` files are there - https://sbt.bintray.com/rpm/sbt-1.3.8.rpm.asc, so I am not sure what I can do.</s>

**Comment by eed3si9n** [comment]
ok, so the article says there's a tool to add signature into the `rpm` file:

> The `rpmsign` command to create the signature looks like this:
> 
> ```
> $ rpmsign -D '_gpg_name rpmsign@example.com' --addsign hello-2.10.1-1.el6.x86_64.rpm
> Enter pass phrase:
> Pass phrase is good.
> hello-2.10.1-1.el6.x86_64.rpm:
> ```

This looks useful if we can automate it.

We'd still have the generated repo file problem.

**Comment by dskrvk** [comment]
What process generates this file?

**Comment by eed3si9n** [comment]
The repo file is provided by Bintray.

**Comment by tomasherman** [comment]
👍 this is an issue for us aswell

**Comment by dskrvk** [comment]
So there’s no way to contact them or affect the way the repo file is
structured?

**Comment by eed3si9n** [comment]
I just pinged Bintray. Let's see what they would say.

**Comment by SethTisue** [comment]
with Bintray dead, is this still applicable?

**Comment by esamson** [comment]
Yes, I think it is still preferable to have GPG signed RPM. On Fedora, the sbt repo does not play well with the default tooling (Discovery on KDE) to get updates because it expects GPG signatures. That, plus the security issues pointed out earlier.

Checking the current repo:

```
$ curl -OL https://repo.scala-sbt.org/scalasbt/rpm/sbt-1.8.2.rpm
$ rpm -K sbt-1.8.2.rpm
sbt-1.8.2.rpm: digests OK
```

Package still has no signatures.

**Comment by tq-t** [comment]
what needs to be done to get this put in place?

**Comment by eed3si9n** [comment]
RPM packages are hosted by Artifactory, which signs the metadata, but not the packages.
We signed the tgz file here (https://github.com/sbt/sbt/releases/tag/v1.10.2), but unless something magical happens at Artifactory package signing will not happen.
