### ISSUE TITLE
Macros in Scala.js No Longer Access the JVM

### ISSUE THREAD

**Issue by darkfrog26** [sbt/sbt#5427]
**Steps**
1. Write a Macro that makes use of `java.io.File`
2. Use that Macro in a Scala.js enabled project

**Problems**
As of `1.3.4`, I get errors `Referring to non-existent class java.io.File`

**Expectations**
Previous to `1.3.4`, this would work just fine and any JVM operation could be dealt with inside the Macro.

**Comment by eed3si9n** [comment]
Could you follow the issue template and the bug report guideline please? https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md#what-to-report

**Comment by darkfrog26** [comment]
I started there, but the template doesn't really apply as this is a more abstract situation.

**Comment by darkfrog26** [comment]
Reproduction is as simple as enabling Scala.js and then writing a Macro that makes use of `java.io.File`.

**Comment by darkfrog26** [comment]
Updated the ticket to follow the guidelines

**Comment by eed3si9n** [comment]
It works on my machine - https://github.com/sbt/sbt/pull/5428. Maybe there's something else that's happening.

**Comment by darkfrog26** [comment]
Strange. Sorry about that, I'll do some more digging on my side and get back to you.

@eed3si9n, any thoughts on what might have changed in `1.3.4` that might have to do with this?

**Comment by eed3si9n** [comment]
Maybe https://github.com/sbt/sbt/issues/5262? Also could you try the latest sbt 1.3.8 plz?

**Comment by darkfrog26** [comment]
It was using `1.3.8` that I first discovered the issue and worked my way back until it went away.  I don't think it's because of #5262, but I'm having a little bit of trouble nailing down a simple test to reproduce it.  I'll get back to you when I have more.

**Comment by darkfrog26** [comment]
Going ahead and closing this as it's going to take more effort to understand what's going on here.  I'll open a new ticket when I have something definitive to explain the issue. Thanks @eed3si9n for taking the time to work with me on this.
