### ISSUE TITLE
definition  "parallel" is  misleading have to be "concurrent"

### ISSUE THREAD

**Issue by git2013vb** [sbt/sbt#5431]
#3206  notes
Most sites and here too people use the work "parallel" insted of "concurrent" causing people to believe that software are parallel. I saw same thing all around in internet. Likewise when people start to use the "atomic"  word in the past: https://i.pinimg.com/originals/d6/94/00/d69400fed536348839fcbe7fc528f378.jpg

Wikipedia (trustworthy and not biased)  clearly tell us what is parallel and what is concurrent:
https://en.wikipedia.org/wiki/Parallel_computing
https://en.wikipedia.org/wiki/Concurrent_computing

Personally I knew these concept even before internet.

Until we use Windows/Linux (that are at best concurrent) we can use concurrent approach. 
In windows and in Linux GPU + driver can give us a parallel product.

Parallel is something that can obtained using parallel hardware and parallel software together.

This do not reduces the value of sbt/scala that is great.

Thank you.

**Comment by eed3si9n** [comment]
Could you follow the guideline https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md#what-to-report for reporting bugs please? If there's a particular bug in documentation please point them out specifically.

If you have some time, I discussed a bit about concurrency in sbt core concept talk - https://www.youtube.com/watch?v=-shamsTC7rQ&t=756

**Comment by git2013vb** [comment]
I say your interesting video.
However, Concurrent tasks don't became "automatically" parallel for just saying it. :)  As long we work inside a concurrent environment they don't change their nature.  To change definition from "concurrent" to "parallel" casually will bring confusion to the new generation. I have seen many people say that sbt works in parallel while they have no idea at all what it mean - just because they say this definition in internet together with  the word "sbt". Even they make questions - in job interview - where is wrong tell  the truth. :)

Anyway sbt is great tool.
Have fun. :)

**Comment by eed3si9n** [comment]
Tasks graph is able to express concurrent tasks (tasks A and B that do not have causal relationship between them). sbt can automatically lift those tasks into JVM threads, which for the sake of this discussion can run in parallel (physically simultaneously). The degree of parallelism is even configurable from the setting
https://www.scala-sbt.org/1.x/docs/Parallel-Execution.html

**Comment by git2013vb** [comment]
Until hardware is not parallel how software can be? A and B can start at same CPU cycle? If not then is not parallel - this is one of constraints that define parallel processing..
Honestly I can't see any simplest way to tell you what is the difference between them. Is up to you to dig in hardware specifics and software too to understand it.
You can do what you want with this tread. Is not my concern. My effort is to share common knowledge. Try to read the 2 links I gave to you - if you have some time.
Thank you for your patience. I will not reply anymore.
Have fun.
 I found a nice youtube video made by  Rob Pike (GoLang) who explain better than me what is the difference between parallel and concurrent. I invite you if you have time to watch it. https://www.youtube.com/watch?v=cN_DpYBzKso
