### ISSUE TITLE
Published classpath doesn't match compile or test classpath

### ISSUE THREAD

**Issue by OlegYch** [sbt/sbt#5449]
## steps
sbt 1.3.8
with a project like

```scala
    libraryDependencies ++= List(
      "com.eed3si9n" %% "gigahorse-okhttp" % "0.5.0",
      "org.specs2" %% "specs2-junit" % "4.8.3" % Test
    )
```
## problem

`Compile/managedClasspath` and `Test/managedClasspath` contains scala-parser-combinators 1.1.2  
if you publish that project in ivy or maven style and include in another project managedClasspath will contain scala-parser-combinators 1.1.1

## expectation

either Compile or Test classpath (preferably both) should be equal to published classpath

## notes
before coursier `Compile/managedClasspath` would have scala-parser-combinators 1.1.1 and `Test/managedClasspath` scala-parser-combinators 1.1.2, published library would have 1.1.1
related to https://github.com/coursier/coursier/issues/1382

**Comment by eed3si9n** [comment]
> if you publish that project in ivy or maven style and include in another project managedClasspath will contain scala-parser-combinators 1.1.1

How does the published POM look like? I am guessing it would be similar to

```scala
    libraryDependencies ++= List(
      "com.eed3si9n" %% "gigahorse-okhttp" % "0.5.0",
      "org.specs2" %% "specs2-junit" % "4.8.3" % Test
    )
```

If so, maybe this is just a variant of https://github.com/coursier/coursier/issues/1382, and a reason why it's bad.

**Comment by OlegYch** [comment]
the published pom has
```
...  
<dependency>
            <groupId>org.specs2</groupId>
            <artifactId>specs2-junit_2.11</artifactId>
            <version>4.8.3</version>
            <scope>test</scope>
....
```
both ivy (on sbt 0.13) and coursier (on sbt 1.3) just ignore that (when dependency is using Compile config, haven't tried including it in Test)
we can't be fixing this on consumer side, because then we'd have to fix maven and every other tool too

**Comment by eed3si9n** [comment]
> if you publish that project in ivy or maven style and include in another project managedClasspath will contain scala-parser-combinators 1.1.1

Using sbt 1.3.8 or sbt 1.4.3, I see scala-parser-combinators_2.13-1.1.2.jar.

**Comment by OlegYch** [comment]
@eed3si9n sorry, i failed to minimize it properly
```
    libraryDependencies ++= List(
      "org.scala-lang.modules" %% "scala-parser-combinators" % "1.1.1",
      "org.scala-lang.modules" %% "scala-parser-combinators" % "1.1.2" % Test,
    )
```
on 1.3.x the project will have 1.1.2 in both compile and test classpath, but 1.1.1 on published classpath
1.4.x has it fixed, as it only has 1.1.2 on test classpath (which is not great since you end up testing and publishing different things, but oh well)

**Comment by eed3si9n** [comment]
ok. So it sounds like https://github.com/coursier/sbt-coursier/pull/235 fixed the problematic aspect of the behavior where `Test` could end up influencing `Compile` configuration?

**Comment by OlegYch** [comment]
@eed3si9n right
though i think it would be great if we could at least warn about deps in test upgrading those from compile
