### ISSUE TITLE
SBT 0.13 build with SBT 0.12 stalls after hidden import warning

### ISSUE THREAD

**Issue by docbrown** [sbt/sbt#545]
When building the latest snapshot of SBT 0.13 with `sbt build-all`, the process appears to stall completely and doesn't even respond to Ctrl+C after this warning is issued:

```
C:\Dev\Tools\SBT\xsbt\compile\inc\CompileSetup.scala:6: warning: imported `Output' is permanently hidden by definition of object Output in package sbt
        import xsbti.compile.{ CompileOrder, Output, SingleOutput, MultipleOutput }
               ^
```

**Comment by harrah** [comment]
The compiler probably needs more memory.  I don't know what the minimum settings are, but my standard sbt script has:

```
-XX:MaxPermSize=512M \
-Xss4M \
-Xmx2500M \
-XX:ReservedCodeCacheSize=256M
```
