### ISSUE TITLE
Stock sbt 1.3.8 distro tries to access jenkins.scala-sbt.org at startup

### ISSUE THREAD

**Issue by cunei** [sbt/sbt#5458]
## steps

```
$ docker run -t -i adoptopenjdk:11-jre-hotspot
# curl -L 'https://piccolo.link/sbt-1.3.8.tgz' | tar xfz -
# echo "127.0.0.1 jenkins.scala-sbt.org" >>/etc/hosts
# mkdir test
# cd test
# ../sbt/bin/sbt -Dsbt.log.noformat=true
```

## problem

sbt will complain that it cannot get certain files:
```
  Server access Error: Connection refused (Connection refused) url=https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/sonatype/oss/oss-parent/9/oss-parent-9.jar
```

## expectation

This shouldn't happen. Sites with particular firewall rules will encounter sbt errors.

## notes

What seems to happen is that the stock sbt distro refers to certain packages looking for them in a snapshot repo: `https://repo.scala-sbt.org/scalasbt/maven-snapshots`. In turn, that is redirected to `https://jenkins.scala-sbt.org/sbt-snapshots`. That leads to an attempt to access the test cluster in Lausanne, which is not a dependable system, and shouldn't happen to begin with. For example, with the `/etc/hosts` above:
```
# wget 'https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/fusesource/fusesource-pom/1.11/fusesource-pom-1.11.jar'
--2020-03-04 09:00:40--  https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/fusesource/fusesource-pom/1.11/fusesource-pom-1.11.jar
Resolving repo.scala-sbt.org (repo.scala-sbt.org)... 34.202.147.211, 54.85.165.101, 52.1.64.47
Connecting to repo.scala-sbt.org (repo.scala-sbt.org)|34.202.147.211|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://jenkins.scala-sbt.org/sbt-snapshots/org/fusesource/fusesource-pom/1.11/fusesource-pom-1.11.jar [following]
--2020-03-04 09:00:41--  https://jenkins.scala-sbt.org/sbt-snapshots/org/fusesource/fusesource-pom/1.11/fusesource-pom-1.11.jar
Resolving jenkins.scala-sbt.org (jenkins.scala-sbt.org)... 127.0.0.1
Connecting to jenkins.scala-sbt.org (jenkins.scala-sbt.org)|127.0.0.1|:443... failed: Connection refused.
```
I have not investigated further. This issue led to failures while trying to use sbt on one of the LAMP machines, recently; their system administrator got in touch with me pointing out the odd behavior.

**Comment by eed3si9n** [comment]
@cunei I've made the change so ppl can use our nightly builds.

**Comment by cunei** [comment]
Hm, I think it might have been enough to add instructions on customizing the resolvers, for the very few people that actually need the sbt nightlies. You mean it's now on the default resolvers list? The EPFL pipe is relatively large, but the humble old server in Lausanne is not exactly a CDN. I hope that doesn't impact the resolution performance, especially for people that are geographically distant.
All, in all, I would favor a revert of this change; it adds an extra resolution step for everyone, to little general advantage.
Traffic is metered at the Lausanne office. Thankfully the repo is not a proxy, so it will just say "no" all the time; our cost impact should be limited. However, I checked the logs and just today, in seventeen hours, the http server received 229715 requests for sbt snapshots, out of all but 6 were 404's, and the rest index requests (no actual snapshot files served.)
(edit: wrong log file). Yesterday the number of 404 was 362487 in 24 hours.

**Comment by eed3si9n** [comment]
I think there's a value in being able to try nightly build easily.
The tricky problem is that the resolver needs to be part of the sbt launcher JAR, so it's not as easy to customize compared to the current instruction of just putting the latest build number into `project/build.properties` file.

We could tweak the redirect rule from repo.scala-sbt.org so that it won't hit the Jenkins server unless it's for actual sbt artifacts.

**Comment by cunei** [comment]
That is a good idea. It's sufficient to redirect just the path corresponding to the sbt org, and return 404 right away otherwise. The remote clients will still hit repo.scala-sbt.org more than necessary, which is not ideal, but better than what happens now.

**Comment by fsalvi** [comment]
Thanks Toni for opening the ticket.
Now, it looks ok for our machines.

**Comment by cunei** [comment]
Why is this closed? The general redirection from `https://repo.scala-sbt.org/scalasbt/maven-snapshots` to `jenkins.scala-sbt.org` is still in place it seems. Yesterday, the poor machine replied 308'696 times "404-please stop asking" to random requests for non-existing jars.

**Comment by eed3si9n** [comment]
https://repo.scala-sbt.org/scalasbt/maven-snapshots/ now points to Bintray.
