### ISSUE TITLE
DependencyResolution.retrieve doesn't respect retrieveDirectory on coursier

### ISSUE THREAD

**Issue by dcsobral** [sbt/sbt#5465]
## steps

With sbt 1.38, try [this example](https://github.com/sbt/librarymanagement) using Coursier's (the default) `DependencyResolver`:

```scala
scala> import sbt.librarymanagement._, syntax._
import sbt.librarymanagement._
import syntax._

scala> val log = sbt.util.LogExchange.logger("test")
log: sbt.internal.util.ManagedLogger = sbt.internal.util.ManagedLogger@2012731b

scala> val lm = dependencyResolution.eval
lm: sbt.librarymanagement.DependencyResolution = sbt.librarymanagement.DependencyResolution@25740f57

scala> val module = "commons-io" % "commons-io" % "2.5"
module: sbt.librarymanagement.ModuleID = commons-io:commons-io:2.5

scala> lm.retrieve(module, scalaModuleInfo = None, new File("target"), log)
res0: Either[sbt.librarymanagement.UnresolvedWarning,Vector[java.io.File]] = Right(Vector(/Users/dcsobral/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/commons-io/commons-io/2.5/commons-io-2.5.jar, /Users/dcsobral/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/commons-io/commons-io/2.5/commons-io-2.5.jar, /Users/dcsobral/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/commons-io/commons-io/2.5/commons-io-2.5.jar))
```

## problem

The `retrieveDirectory` parameter is not respected.

## expectation

The retrieved files should have been placed on "target".

## notes

Though the example uses a relative path, I've tried using an absolute path. As far as I can tell, Coursier completely ignores `retrieveDirectory` on `RetrieveConfiguration` on `UpdateConfiguration`. In fact, it completely ignores `UpdateConfiguration`, which is hinted at by this line in it:

```scala
    // TODO Take stuff in configuration into account? uwconfig too?
```

**Comment by eed3si9n** [comment]
@dcsobral Thanks for the report.

This is probably related or duplicate of https://github.com/sbt/sbt/issues/5078. Somewhat unfortunate since Coursier CLI has similar feature.

**Comment by dcsobral** [comment]
@eed3si9n Looks like a dupe, though my PR identify the problem more closely. I'll add a pointer on that thread.
