### ISSUE TITLE
NoClassDefFoundError when generating test reports with ScalaTest

### ISSUE THREAD

**Issue by liebichw** [sbt/sbt#5467]
I have a multi module project having both Java and Scala sources.
After upgrading to scalatest 3.1.0, I can no longer run tests from the sbt console because of following error:
`java.lang.NoClassDefFoundError: com/vladsch/flexmark/ast/Node
         at org.scalatest.tools.ReporterFactory.createHtmlReporter(ReporterFactory.scala:194)
...
`
This error occurs with sbt 1.2.8, 1.3.4 and 1.3.8.
It is the same as bug #5308 - it was not fixed, it seems.

**Comment by eed3si9n** [comment]
@liebichw Thanks for the report. Could you follow the issue reporting guidelines https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md#what-to-report please? Specifically we are looking for a way to reproduce your problem on our machines.

**Comment by eed3si9n** [comment]
> It is the same as bug #5308 - it was not fixed, it seems.

I don't think this is the exact same bug since I am unable to reproduce the issue using the repro steps in #5308.

**Comment by liebichw** [comment]
OK, I try to describe first the project where this issue came up:

It is a somewhat bigger multimodule project, which started out as pure Java project, and which is now a mixed project, with some modules having a mixed Java/Scala sources, some only Java sources. The project contains 49 sub-projects.

The project still uses Java 8, and when the error occurred, it used Scala 2.12.10. It also occurs after switchting to Scala 2.13.1, though.
The sbt version I used has as launcher sbt 1.2.8. Initially I also used this as the build version. I experimentally switched to sbt 1.3.8 - the same error occurred here.
I did not yet try to update the launcher yet.

After I upgraded the scalatest library version from version 3.0.8 to 3.1.0, suddenly I could no longer run the "test" task from within sbt.
I only got the exception described above.

Later on I tried out also scalatest 3.1.1 - it showed the same behavior.

Further details:
- I ran this test on gentoo linux (64 bit).
- I tried to set up a minimal test project to reproduce the error. It immediately cropped up as soon as I tried to run "test" from sbt, even though the project contained no sources at all.

EDIT: I looked up the link from #5308 - and I saw that I did not explicitely include the line `"com.vladsch.flexmark" % "flexmark-all" % "0.35.10" % Test` in my build - this was not required by http://www.scalatest.org/install - but according to https://github.com/scalatest/scalatest/issues/1736 this seems to be a bug in scalatest (!) - I will investigate this further.

**Comment by liebichw** [comment]
Update: After explicitely adding `"com.vladsch.flexmark" % "flexmark-all" % "0.35.10" % Test` to my scalatest dependencies, my tests work again - this is a bug in scalatest, not in sbt (because the scalatest library does not indicate that it needs this dependency).

**Comment by liebichw** [comment]
I mistakenly took this as an sbt issue - in fact it is an issue with scalatest.
