### ISSUE TITLE
Unable to build with two identical artifact ids and different groupd ids

### ISSUE THREAD

**Issue by muuki88** [sbt/sbt#547]
I'm not able to build akka with sbt due to the following error:

``` bash

{file:/home/muki/Development/workspace_play/akka/}akka-osgi-tests/*:update: 
sbt.ResolveException: unresolved dependency: org.apache.commons#commons-io;1.3.2: java.text.ParseException: 
inconsistent module descriptor file found in 'http://repo1.maven.org/maven2/org/apache/commons/commons-io/1.3.2/commons-io-1.3.2.pom': 
bad organisation: expected='org.apache.commons' found='commons-io';
```

There are two dependencies:
1. **commons-io:commons-io**
1. **org.apache.commons:commons-io**

And it seems that sbt can't handle both in the same build.

[Akka Pull Request](https://github.com/akka/akka/pull/589)
[Akka Ticket](https://www.assembla.com/spaces/akka/tickets/2524)

**Comment by harrah** [comment]
This was asked as a question on the mailing list: https://groups.google.com/d/topic/simple-build-tool/4ovt3BFdptA/discussion.  There was no follow up, so closing.

**Comment by muuki88** [comment]
I try to provide a simple standalone example, but this issue still remains :(

**Comment by muuki88** [comment]
https://github.com/akka/akka/pull/589#issuecomment-9217590

> It seems like the ivy resolver does not like the child not to share the parents groupid (see: >http://repo1.maven.org/maven2/org/apache/commons/commons-io/1.3.2/commons-io-1.3.2.pom)
