### ISSUE TITLE
sbt-allsources fails with NoSuchMethodError

### ISSUE THREAD

**Issue by Recon419A** [sbt/sbt#5471]
Error found while following steps in `DEVELOPING.md`, after cloning all sources and attempting to load the project with `sbt/sbt-allsources`. Log output: https://pastebin.com/nF1DTTQN (project loading failed).

**Comment by eed3si9n** [comment]
@Recon419A Thanks for the report. I'm aware Zinc and sbt are currently off-sync.

**Comment by eed3si9n** [comment]
This should be fixed now.
