### ISSUE TITLE
Send custom HTTP headers when downloading artifacts

### ISSUE THREAD

**Issue by mjuanes** [sbt/sbt#5473]
Hi! Sorry in advance if this post causes any inconvenience.

I have the same issue stated here: https://stackoverflow.com/questions/55834674/sbt-add-http-headers-when-fetching-private-maven-repo-with-credentials

The solution I'm trying is based in this workaround: https://github.com/sbt/sbt/issues/4382#issuecomment-469734888

Instead of overriding upload, I'm overring download and then I modify the update task. 

```
onLoad in Global := (onLoad in Global).value andThen { state =>
  def info: String => Unit = state.log.info(_)

  def debug: String => Unit = state.log.debug(_)

  info(s"Updating urlHandlerDispatcher to use GitlabCIURLHandler")
  val factory = new URLStreamHandlerFactory {
        def createURLStreamHandler(protocol: String): URLStreamHandler = protocol match {
          case "https" => new Handler
          case _    => null
        }
  }

  URL.setURLStreamHandlerFactory(factory)
  val urlHandlerDispatcher = new URLHandlerDispatcher {
    super.setDownloader("http", GitlabTokenURLHandler)
    super.setDownloader("https", GitlabTokenURLHandler)

    override def setDownloader(protocol: String, downloader: URLHandler): Unit = {}
  }

  URLHandlerRegistry.setDefault(urlHandlerDispatcher)


  state
}

```

Is not working, any idea if this is possible?

**Comment by gilandose** [comment]
I've got a working solution for this, I've set it up specifically for gitlab, but could be used for others, it doesn't currently work with Coursier resolution though so you need to disable that. I'll push up a solution in a couple of days:
I think Ivy resolution can be done with a custom plugin, but for Coursier https://github.com/coursier/coursier/issues/1203 needs to be resolved. 
This will require a small update to sbt-coursier and sbt

**Comment by gilandose** [comment]
I think his can be closed now  due to 
https://github.com/coursier/sbt-coursier/pull/220 resolves this

**Comment by eed3si9n** [comment]
ok. Closing this.

**Comment by zperee** [comment]
@mjuanes Did you find a working solution? And what is your `GitlabTokenURLHandler`?

**Comment by mjuanes** [comment]
@zperee: nope, sorry. Did you check the messages above?

**Comment by todor-kolev** [comment]
This doesn't work for resolving privately published plugins though, does it? It will only resolve library dependencies but not plugin dependencies, right?
