### ISSUE TITLE
StateTransform doesn't work as documented

### ISSUE THREAD

**Issue by dcsobral** [sbt/sbt#5477]
## steps

Following [these steps](https://www.scala-sbt.org/1.x/docs/Build-State.html#Updating+State+in+a+task), the provided example does not work:

build.sbt:
```scala
import complete.DefaultParsers._
val counter = AttributeKey[Int]("counter")
val setCounter = inputKey[StateTransform]("Set the value of the counter attribute")
setCounter := {
  val count = (Space ~> IntBasic).parsed
  StateTransform(_.put(counter, count))
}
```

## problem

Trying to load that project:

```
[info] Updated file /Users/dcsobral/tmp/stateTransform/project/build.properties: set sbt.version to 1.3.7
[info] Loading global plugins from /Users/dcsobral/.sbt/1.0/plugins
[info] Loading project definition from /Users/dcsobral/tmp/stateTransform/project
/Users/dcsobral/tmp/stateTransform/build.sbt:6: error: missing parameter type for expanded function ((x$1: <error>) => x$1.put(counter, count))
  StateTransform(_.put(counter, count))
                 ^
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q
```

## expectation

The example should work, obviously. I've looked into the source code and the `apply` method of `object StateTransform` just returns its input, which is of type `State`, not `State => State`. 

## notes

All uses of `StateTransform` in sbt itself are either the type `StateTransform`, or returning `new StateTransform(newState)` instances.

I guess the intention was having that apply method inject something like

```scala
new StateTransform(func(state.value))
```

I don't know how easy it is to do that, but my feeling is "not very". A simpler alternative would be changing the documentation. I'll open a PR with the simpler alternative referencing this ticket, and leave it to more knowledgeable people to decide the best course of action.

**Comment by dcsobral** [comment]
Doc fix on PR sbt/website#882.

**Comment by eatkins** [comment]
The problem is that we changed the api for 1.4.0 and preemptively updated the docs. I would rather temporarily remove the documentation for StateTransform than document the flawed api exposed in 1.3.x.

**Comment by eed3si9n** [comment]
Yea. I agree with Ethan. Maybe we can add a note in the doc saying the API is in flux now?
