### ISSUE TITLE
test-only should compile only files needed to run the selected test

### ISSUE THREAD

**Issue by greenrd** [sbt/sbt#548]
Currently, `test-only` tries to compile all the tests, which is inconvenient if some of the other tests currently aren't compiling and you just want to try something out to see if it works.

**Comment by mepcotterell** [comment]
+1 I'd like a fix for this too. I often create mock tests that don't compile right away. A fix for this would be awesome.

**Comment by eed3si9n** [comment]
Hi Robin, I don't think we would ever do this.
