### ISSUE TITLE
sbt-coursier loses callers for dependencies that are both pulled transitively and directly from the module

### ISSUE THREAD

**Issue by slandelle** [sbt/sbt#5484]
## steps

Using sbt 1.3.8.
Write a plugin that fetches the UpdateReport and analyzes the callers tree.

## problem

On contrary to ivy, sbt-coursier loses transitive callers when a dependency is also pulled directly from the module. Problem doesn't happen when coursier is disabled.

It seems to me the issue is here: https://github.com/coursier/sbt-coursier/blob/master/modules/lm-coursier/src/main/scala/lmcoursier/internal/SbtUpdateReport.scala#L224

We have 2 `Map[Dependency, Seq[Dependency]]` and the `++` drops the values for the clashing keys in the left Map that contains the entries for the transitive dependencies. The 2 Maps should be merged instead so no values are lost.

## expectation

Behavior should be the same with and without Coursier enabled.
Update report should report the full dependency graph.

**Comment by slandelle** [comment]
PR: https://github.com/coursier/sbt-coursier/pull/209

**Comment by SethTisue** [comment]
sbt-coursier doesn't exist anymore, coursier is built in. maybe we should close this, and offer to reopen if someone presents evidence the problem exists in current sbt?

**Comment by slandelle** [comment]
@SethTisue This issue should have been closed when the PR against sbt-coursier was merged 3 years ago (GitHub couldn't do it because 2 different orgs).
