### ISSUE TITLE
Missing old versions in maven

### ISSUE THREAD

**Issue by darrenchiu** [sbt/sbt#5499]
I am trying to deploy an old piece of software which leverage sbt 0.13.6. It works fine until today and I found that the sbt 0.13.6 was removed from the maven repo and the oldest version available is 0.99. I would like to see if there are any repo that I can still use the old versions? Or would there be a chance to restore the old versions in maven?

Thanks a lot,
Darren

**Comment by eed3si9n** [comment]
sbt 0.13.x is under Typesafe Ivy Releases repo, not Maven Central -  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.6/
