### ISSUE TITLE
IllegalArgumentException in update-classifiers while adding pom artifact

### ISSUE THREAD

**Issue by ijuma** [sbt/sbt#55]
Seems like 0.10.1-SNAPSHOT doesn't like me! After disabling the web module, I get the following during update-classifiers:

[error] {file:/media/internal0/home/ijuma/src/root/}sub/*:update-classifiers: java.lang.IllegalArgumentException: Cannot add artifact 'sub.pom' to configuration 'pom' of module groupId#sub$sources;1.0 because this configuration doesn't exist!

**Comment by ijuma** [comment]
By the way, I get similar errors during update-sbt-classifiers. If you need a test case, let me know and I'll try to isolate it.

**Comment by harrah** [comment]
Are you explicitly setting ivyConfigurations?  In this commit:

https://github.com/harrah/xsbt/commit/540f7df9e1e96f2e6728da15739f2fc47d282fab

I added "sources", "docs", and "pom" configurations in order to better classify artifacts.  It should be automatic unless you override ivyConfigurations.

**Comment by ijuma** [comment]
No, I am not setting that. Weird.
