### ISSUE TITLE
Coursier is adding transitive dependencies of test configuration to runtime

### ISSUE THREAD

**Issue by srednal** [sbt/sbt#5500]
## steps

Transitive dependencies of libraries in a test configuration are being added to the runtime.

SBT version 1.3.9
Scala 2.13.1

See attached 
[coursier-deps.zip](https://github.com/sbt/sbt/files/4446823/coursier-deps.zip)

Running the Main app triggers a library version collision ("bad" library brought in via test configuration disabled logging):

    sbt:coursier-deps> run
    ...
    [info] running whatever.Main
    SLF4J: No SLF4J providers were found.
    SLF4J: Defaulting to no-operation (NOP) logger implementation
    SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
    SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions prior to 1.8.
    SLF4J: Ignoring binding found at [jar:file:/var/folders/q9/d3zz50q12zbd5hfcyt8y9hjh0000gp/T/sbt_c774719a/target/ffe5d269/97705cb7/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]

Without Coursier, the test library is excluded from the runtime (and logging happens):

    sbt:coursier-deps> set ThisBuild / useCoursier := false
    [info] Defining ThisBuild / useCoursier
    ...
    sbt:coursier-deps> run
    [info] Compiling 1 Scala source to /Users/dlanders/dev/bugreports/coursier-deps/target/scala-2.13/classes ...
    [info] running whatever.Main
    14:15:17.431 [run-main-1] INFO whatever.Main$ - Hello, World!
 

_The specific end result involving slf4j is not my issue, but it is the real problem I ran into and happens to illustrate the dependency problem easily._

## problem

The specific case I have involves a test library which, within its transitive dependencies, includes a beta version of slf4j logging that is incompatible with the runtime dependencies.
See comments in the attached `build.sbt` for the libraries involved in that dependency chain.

Running an app (i.e. `sbt run`) will have the `slf4j 1.8.0-beta2` jar included and effectively disable logging.

Disabling coursier (i.e. behavior prior to sbt 1.3) does not include transitive dependencies from the test configuration.

Running `evicted` is no help: it does show that `1.8.0-beta2` was selected, but not what dependency brought it in.

    sbt:coursier-deps> evicted
    [info] Here are other dependency conflicts that were resolved:
    [info] 	* org.slf4j:slf4j-api:1.8.0-beta2 is selected over {1.7.25, 1.7.26, 1.7.28, 1.7.28, 1.7.28, 1.7.28}
    [info] 	    +- org.apache.kafka:kafka-streams:2.4.0               (depends on 1.7.28)
    [info] 	    +- org.apache.kafka:kafka-clients:2.4.0               (depends on 1.7.28)
    [info] 	    +- org.apache.kafka:connect-json:2.4.0                (depends on 1.7.28)
    [info] 	    +- org.apache.kafka:connect-api:2.4.0                 (depends on 1.7.28)
    [info] 	    +- com.typesafe.scala-logging:scala-logging_2.13:3.9.2 (depends on 1.7.26)
    [info] 	    +- ch.qos.logback:logback-classic:1.2.3               (depends on 1.7.25)

## expectation

Test dependencies do not leak into compile or runtime configurations.

**Comment by eed3si9n** [comment]
@srednal Thanks for the report. This is a known issue with Coursier integration - https://github.com/coursier/coursier/issues/1382

**Comment by ches** [comment]
Thus this is at least related to #5449 I think.

Too bad lm-coursier 2.0.0-RC6-5 didn't make it in time for sbt 1.3.12.

**Comment by eed3si9n** [comment]
sbt 1.4.x series uses per-config resolved Coursier.

```
sbt:deps> run
[info] running whatever.Main
12:21:22.846 [run-main-1] INFO whatever.Main$ - Hello, World!
```
