### ISSUE TITLE
TestQuick not re-running tests on changed function in object

### ISSUE THREAD

**Issue by amumurst** [sbt/sbt#5504]
## steps
1. Start new sbt project and create

#### project/build.properties
```scala
sbt.version = 1.3.9
```

#### build.sbt
```scala
name := "sbt-testquick-trigger"
scalaVersion := "2.13.1"
libraryDependencies += "org.scalatest" %% "scalatest" % "3.1.1" % "test"
```
#### src/main/scala/MathFunction.scala
```scala 
object MathFunction {
  def times2(i: Int): Int = i * 2
}
```
#### src/test/scala/MathFunctionTest.scala
```scala
class MathFunctionTest extends org.scalatest.funsuite.AnyFunSuite {
  test("one") { assert(MathFunction.times2(2) == 4) }
  test("two") { assert(MathFunction.times2(8) == 16) }
}
``` 
2. Start sbt with `sbt`
3. Run command `testQuick`
4. Change function in `MathFunction`-object to something else, eg:
```scala
  def times2(i: Int): Int = 2 * 2
``` 
5. Run command `testQuick` again

## problem
The second time the `testQuick` command is ran, the test are not actually re-ran even though the function is now bad and they would fail.

## expectation
The tests are re-ran since the function is changed and I would like to see that it is now indeed broken.

## notes
Running `test` instead of `testQuick` the second time does indeed fail as expected.

Going through the same steps with MathFunction as a `case class` or `class` does pick up the changes and run the tests correctly when the function is changed.

**Comment by eed3si9n** [comment]
@amumurst Thanks for the detailed bug report!

**Comment by ScalaWilliam** [comment]
@eed3si9n any ideas where this issue could be coming from?

**Comment by eed3si9n** [comment]
It's likely to do with the detection of which classes are invalidated. 

https://github.com/sbt/sbt/blob/e0f309f4c6d68be824a92cfbfa4577a82056d23d/main/src/main/scala/sbt/Defaults.scala#L1376-L1418

It's using stamp information to find out which classes have been changed, but maybe the time-based logic is no longer accurate.
