### ISSUE TITLE
Verbose switch for `+` is broken

### ISSUE THREAD

**Issue by ches** [sbt/sbt#5506]
## steps

No project is needed at all to reproduce:

```
$ mkdir /tmp/demo && cd /tmp/demo
$ sbt --warn --sbt-version 1.3.10
sbt:demo> + -v compile
[error] Expected ';'
[error] ++ -v 2.12.10! demo/Compile/compile
[error]                                    ^
```

This looks like a regression from #3995.

## problem

`+ -v` does not work at all.

## expectation

Commands should work with verbose Scala version switching, as `help +` describes.

**Comment by eed3si9n** [comment]
@ches Thanks for the report!
