### ISSUE TITLE
'<' can be defined as alias, but cannot be used

### ISSUE THREAD

**Issue by rethab** [sbt/sbt#5523]
## steps
- SBT 1.3.8

Steps:
- Put `alias <=project root` into ~/.sbtrc
- Start SBT
- Navigate to a project
- Type `<`
- SBT shows error: 

```
sbt:subproject> <
[error] Expected ';'
[error] < usage:
[error] 
[error] 
[error] More command help available using 'help <command>' for:
[error]   <
[error] 
[error] <
[error]  ^

```

## problem
I could only guess..

## expectation
I would expect that the alias is just something that is replaced 1:1, but `<` seems to be treated specially.

If this is not a legal alias, it would be good if SBT warned about that, because it seems to actually accept it as an alias:
```
sbt:subproject> alias
coverage = ;set coverageEnabled in ThisBuild := true
coverageOn = ;set coverageEnabled in ThisBuild := true
coverageOff = ;set coverageEnabled in ThisBuild := false
q = exit
< = project root
to = test:compile
```

## notes
If you give me some hints, I'd be happy to try and fix it myself.

**Comment by eed3si9n** [comment]
> If you give me some hints, I'd be happy to try and fix it myself.

sbt gave you the hint:

```
[error] More command help available using 'help <command>' for:
[error]   <
```

```
sbt:demo> help <
< file1 file2 ...

	Reads the lines from the given files and inserts them as commands.
	All empty lines and lines that start with '#' are ignored.
	If a file does not exist or is not readable, this command fails.

	All the lines from all the files are read before any of the commands
	  are executed. Thus, if any file is not readable, none of commands
	  from any of the files (even the existing ones) will be run.

	You probably need to escape this command if entering it at your shell.
```

`<` is an existing command in sbt called "read" command. Due to the way it's implemented, you cannot start other commands starting with `<`.
