### ISSUE TITLE
I am not programmer and i need help with that :s

### ISSUE THREAD

**Issue by Mac2298** [sbt/sbt#5528]
05.05 12:11:05 [Server] INFO [init] error: error while loading Object, Missing dependency 'object scala in compiler mirror', required by /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar(java/lang/Object.class)
05.05 12:11:05 [Server] INFO Failed to initialize compiler: object scala in compiler mirror not found.
05.05 12:11:05 [Server] INFO ** Note that as of 2.8 scala does not assume use of the java classpath.
05.05 12:11:05 [Server] INFO ** For the old behavior pass -usejavacp to scala, or if using a Settings
05.05 12:11:05 [Server] INFO ** object programmatically, settings.usejavacp.value = true.
05.05 12:11:05 [Server] ERROR Encountered an unexpected exception

((I would like to explain that this error occurred after adding a script to an npc of the custom mod npc))

**Comment by eed3si9n** [comment]
Hi. Welcome to sbt/sbt. sbt is a build tool for Scala and other programming languages.

> ((I would like to explain that this error occurred after adding a script to an npc of the custom mod npc))

I'm not sure what this means, but I'm guessing that you are trying to add a mod to Minecraft.

First, you came to a wrong place. sbt/sbt issue is for discussing bugs in sbt. If you need help how to use sbt, please ask questions on Stackoverflow. For Minecraft etc, you have to find some other forum.

Second, wherever you go next, you should provide more details, like way more, details on how you got to the error message. The person on the other end of the Internet cannot just guess what wrong turns you took if you showed like a picture of a tree when you're lost. You need to provide exact steps that the other person can trace back to your error message on her computer. That would include version number of the game (server?), URL of where you got the mod from, and what script you changed etc.
