### ISSUE TITLE
Enhance .sbt format

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#554]
Known problems and a proposal described on https://github.com/harrah/xsbt/wiki/Definition-Format-Enhancement.md.

Original title was "Add setting project id in build.sbt file".  Original description follows:

It really irks me when I see that my project (a single module project) is named "default-eb7f88", the workaround is that each and every sbt project I have has this project/Build.scala file:

```
import sbt._
import Keys._

object Build extends sbt.Build {
  lazy val root = Project("myproject", file("."))
}
```

It would be nice if I could drop this boilerplate and set it in my build.sbt file.

Thank you.

**Comment by xuwei-k** [comment]
How about this ?

``` scala
name := "myproject"
```

in your `build.sbt`

**Comment by dwijnand** [comment]
That's the project's name, which is different to its id..

**Comment by pvorb** [comment]
What's the difference?

**Comment by dwijnand** [comment]
Two things (not the end of the world, mind you): The label in the sbt shell "Set current project to default-eb7f88" and the name of the module in IntelliJ.

**Comment by pvorb** [comment]
OK. So maybe the real bug is that the IntelliJ plugin and the sbt shell don't use the name from `build.sbt`. @harrah Is there any reason for that?

**Comment by harrah** [comment]
The IntelliJ plugin bug is here: https://github.com/mpeltonen/sbt-idea/issues/136.  It is really an issue in sbt and anything done in the plugin is a workaround.  This can't be solved without enhancing the .sbt format.  It is a big change to modify the .sbt format.  It is being considered, but certainly won't happen before 0.13.0.

**Comment by harrah** [comment]
I'll turn this bug into the general .sbt definition format enhancement bug.  The page describing one proposal is here: https://github.com/harrah/xsbt/wiki/Definition-Format-Enhancement.md.  It includes the various limitations of the .sbt format.  The proposal needs attention in the form of feedback, especially identifying problems, potential solutions, and expanding the specification.

**Comment by dwijnand** [comment]
If possible, could you explain to me why setting the id in build.sbt is different from setting anything else (eg. name). Thanks.

**Comment by harrah** [comment]
Yes, the ID is used when evaluating settings, so sbt needs to know it beforehand.  (Not sure if you want more details than that.)

**Comment by dwijnand** [comment]
That's what I assumed and just wanted to confirm that was the issue. Thanks

**Comment by harrah** [comment]
This is close to being resolved with the latest changes to the .sbt format, which are described at http://www.scala-sbt.org/snapshot/docs/Community/ChangeSummary_0.13.0.html#sbt-format-enhancements.

The main remaining problem is this.  sbt creates a default project when there are only .sbt files and it is this default project that has the random ID described in this bug.  If the user defines Projects in the .sbt file, this default project is probably undesirable and unnecessary.  However, the "loose" settings in .sbt files would normally get added to this default project.  The options that I see are:

  i) Don't allow loose settings when Projects are defined in a .sbt file
  ii) Put loose settings in ThisBuild scope, the first defined project, or require them to all be in a specific project's scope.  (Only one option would be used, not all three tried in sequence.)
  iii) Have the default project with the project directory as its name (possibly with "-root" appended) and aggregate all defined projects
  iv) Require a root project to be explicitly defined (its base directory is the directory containing the .sbt file) and put all loose settings in that project

Only option iii) still uses the default project.  Opinions are welcome.

**Comment by nafg** [comment]
How about (iii) but name it after the project directory (perhaps with -root appended)?

**Comment by harrah** [comment]
Thanks, I've added that suggestion.  One problem is that moving the directory changes the project name.  Perhaps that means it shouldn't be a normal project or something like that.

**Comment by nafg** [comment]
Anyone going with a random ID until now isn't relying on the ID that strongly. However it would be good if there was a way to specify the ID, maybe in project/build.properties?

**Comment by harrah** [comment]
You're right, it's just the ID.  The name can be set via a setting as usual.  I'd vote for not appending "-root" and maybe not worry about configuring the ID.  `project/build.properties` is supposed to go away at some point (small chance in 0.13, but more likely not), so I don't want to add ways it is used.

**Comment by nafg** [comment]
How will you control per-project sbt versions?

**Comment by harrah** [comment]
Certainly there will be a proper alternative.  One idea was to put it in `build.sbt` somehow, possibly as a comment at the top, like:

```
// sbt.version=0.13.0
```

**Comment by nafg** [comment]
Okay, so why not do that for the default project ID too?

**Comment by nafg** [comment]
FWIW I like the idea of adding -root (perhaps only if there are defined projects).
Anyway another approach simply to preserve the ID's stability is to cache it the first time it's calculated from the directory. Of course cleaning or rebooting the project would lose the stability.

**Comment by harrah** [comment]
The sbt.version configuration has to be treated specially because the launcher has to read it, which happens before the main sbt is loaded.  I'm not sure we'd want to have more special syntax than necessary.  It is a possibility, though.

I think one of the main goals is make the transition from a single project to multiple projects as easy as possible.  I'm not sure which of the options is best for this, but it seems to me that for iii), changing the ID to have -root is a potential surprise here.  Perhaps not, since users are unlikely to need to reference the ID, but perhaps so, since the original issue was filed because of the ID shown in an IDE.

I was mainly concerned with people on different machines having different directory names, which might make it harder to give consistent instructions.  I'm not sure how much the root project ID matters, though.

**Comment by hseeberger** [comment]
Assuming that .sbt files of subprojects are assigned to these, I vote for (iv), i.e. require a root project and assign the loose / top-level .sbt settings to that.

**Comment by harrah** [comment]
Yes, a subproject with base directory `sub/` would still load settings from `sub/*.sbt` by default.

**Comment by vnicolici** [comment]
I just created my first project not using a .scala build file (my previous projects had a .scala build file and didn't have this issue), and I spent a lot of time trying to determine why it ignores my project name (it didn't, but the message was confusing).

The message is:

```
[info] Set current project to default-0e2ae1 (in build file:/C:/Users/Vladimir/scalaworkspace/backup-tool/)
```

Until a solution is implemented for this issue, what I think would help in the interim is changing the message, making it more clear, for example:

```
[info] Set current project to 'backup-tool' (id 'default-0e2ae1') (in build file:/C:/Users/Vladimir/scalaworkspace/backup-tool/)
```

**Comment by harrah** [comment]
The solution I went with was a combination of iii) and iv) as described in the three linked commits.
