### ISSUE TITLE
Add  the used Java version to welcome information of sbt

### ISSUE THREAD

**Issue by He-Pin** [sbt/sbt#5544]
![image](https://user-images.githubusercontent.com/501740/81467855-118ef380-920e-11ea-8b0e-142d5f4dc5e8.png)

,Scala gives:
![image](https://user-images.githubusercontent.com/501740/81467871-2b303b00-920e-11ea-849c-4b29c4a87708.png)
sbt console gives
![image](https://user-images.githubusercontent.com/501740/81467900-57e45280-920e-11ea-9ddd-8b2db67ea60f.png)
amm gives
![image](https://user-images.githubusercontent.com/501740/81467906-66cb0500-920e-11ea-86f5-5ce06177b386.png)

**Comment by eed3si9n** [comment]
Here's my PR for this - https://github.com/sbt/sbt/pull/5579
