### ISSUE TITLE
aggregate false for project-config-task axis doesn't work as expected.

### ISSUE THREAD

**Issue by dmakhno** [sbt/sbt#555]
SBT 12.1-RC2

I tried to use following:
lazy val root = project(".")
    .aggregate(sub, sub2, sub3)
    .settings( aggregate in (sub, IntegrationTest, test) := false)

it:test
Actual: => executes it:test and for sub.
Expected: it:test executed only for sub2 and sub3, and sub is only compiled. 

I have a goal to prohibit some tasks from root project, due to specific nature of "it:test" for particular project.
But I still want that it:compile does all the work to keep code safe via jenkins.

**Comment by harrah** [comment]
`aggregate` set on a project `A` controls whether a task run on `A` is propagated to subprojects, not whether that project `A`

**Comment by harrah** [comment]
Sorry, GitHub keyboard shortcuts kicked in.   In your case, the `aggregate` setting controls whether running sub/it:test is propagated to aggregated projects.  `sub` doesn't aggregate anything, so it doesn't do anything.  I would suggest creating your own task that depends on the tasks you want to run.
