### ISSUE TITLE
Travis cant find sbt for 1.2.8 and neither do i

### ISSUE THREAD

**Issue by ghost** [sbt/sbt#5559]
## steps
try to use sbt in travis

This is just the out of the box behavior. is there a quick fix for this?
get the following error:

![image](https://user-images.githubusercontent.com/22631338/82132863-55977080-9799-11ea-9047-3b5a46a6ddcc.png)

**Comment by eed3si9n** [comment]
Make sure you have `language: scala`.

Otherwise you'd get an older version of sbt-extras. Otherwise see https://github.com/travis-ci/travis-cookbooks/pull/491 / https://github.com/travis-ci/travis-ci/issues/4527, and please open an issue with Travis CI with a link to your build.
