### ISSUE TITLE
sbt version in apt-reporitry is not updated

### ISSUE THREAD

**Issue by rssh** [sbt/sbt#556]
sbt version in apt-repository is not updated  (i.e. apt-get install sbt say-s. that 0.11.3 is the latest sbt version).

apt-cache show sbt
Package: sbt
Version: 0.11.3-build-0100
 .....
\
apt-get update
 ....

apt-get install sbt
Reading package lists... Done
Building dependency tree  
Reading state information... Done
sbt is already the newest version.

**Comment by harrah** [comment]
Please report issues with the native packages here: https://github.com/sbt/sbt-launcher-package/issues
