### ISSUE TITLE
WatchSource regression in a multi-projects build 

### ISSUE THREAD

**Issue by vmunier** [sbt/sbt#5561]
## steps

I have set up a minimal repository to reproduce the issue: https://github.com/vmunier/sbt-watch-issue

There's also another small branch, but not as minimal, to show what I was trying to do initially: https://github.com/vmunier/sbt-watch-issue/tree/re-start-scalajs

## problem

The problem is present with SBT 1.3.x, not with SBT 1.2.8.

Let's take a build with 2 projects. The first project contains a task, `compile` for example, which depends on a task defined in the second project:
```
lazy val firstProject = project.settings(
  compile in Compile := ((compile in Compile) dependsOn (secondProject / Compile / compile)).value
)

lazy val secondProject = project
```
The task being run in watch mode in the first project (`~compile`) watches the sources of the second project, whereas it should not. 

## expectation

Since the second project's Scala sources are _not_ part of the first project's `watchSources`, running `~compile` in the first project should not be triggered when updating the second project's Scala sources.

## notes

`compile` is being used in this example, but the same issue occurs with other tasks, like Scala.js' `fastOptJS` as shown in https://github.com/vmunier/sbt-watch-issue/tree/re-start-scalajs

Are there any workarounds for SBT 1.3.x users?

**Comment by eatkins** [comment]
I feel like I am missing something. Why do you not want the first project compile to be triggered by changes to the second project sources when the first project compile depends on the second project compile?

Watch is working exactly as designed in 1.3.x. Sbt 1.3.0 introduced a new way of managing and monitoring source files: [Howto-Track-File-Inputs-and-Outputs](https://www.scala-sbt.org/1.x/docs/Howto-Track-File-Inputs-and-Outputs.html). The compile task uses `fileInputs` to determine _both_ what sources to use during compilation _and_ what sources to watch in `~`. It also transitively watches all of the `fileInputs` of the dependencies of a task, which is the behavior that you are reporting in this issue.

The `watchSources` task wasn't deprecated in `1.3.x` but was left in for backwards compatibility for older builds in the 1.x series. It will likely be deprecated in `1.2.x`. There were a number of issues with `watchSources` in `1.2.x` including the fact that they were global at the project level so they more often watched completely irrelevant files to the watched task than the new implementation. The analogous key in `1.3.x` is `watchTriggers` which is similar but can be set at the task level, not just the project level. The documentation of the `1.3.x` settings is here: https://www.scala-sbt.org/1.x/docs/Triggered-Execution.html.

If you are writing a plugin and want to support < `1.3.x` and `1.3.x`, you probably need to define the `1.3.x` and `1.2.x` settings in separate classes and append the appropriate settings to the project settings at runtime after checking the sbt version.
