### ISSUE TITLE
Regression? An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by nalzok** [sbt/sbt#5565]
## steps

On macOS 10.14, run `sudo port install sbt`, and run `sbt` with

```bash
$ sbt --version
Getting org.scala-sbt sbt 0.13.18  (this may take some time)...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.ivy.util.url.IvyAuthenticator (file:/opt/local/share/sbt/sbt-launch.jar) to field java.net.Authenticator.theAuthenticator
WARNING: Please consider reporting this to the maintainers of org.apache.ivy.util.url.IvyAuthenticator
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

## problem

The warning doesn't seem to be right.

## expectation

No warnings.

## notes

Regression of #3676, #3748, #3968?

Since it mentioned Java, here is some version information

```bash
$ javac --version
javac 13.0.2
$ java --version
openjdk 13.0.2 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.2+8)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.2+8, mixed mode, sharing)
```

**Comment by nalzok** [comment]
Ah, it appears that the bug has been fixed in a newer version, but MacPorts still ships `0.13.x`. Could you upgrade the receipt on MacPorts?

**Comment by eed3si9n** [comment]
> Could you upgrade the receipt on MacPorts?

I don't deal with MacPorts, but you or someone could send them a PR. Looks like the distribution has its own `sbt` script from 2010, so that should be changed to use the official script from our tgz.

I do update SDKMAN though.
