### ISSUE TITLE
Errors at run lila

### ISSUE THREAD

**Issue by ghost** [sbt/sbt#5566]
[error] a.i.TcpListener - Bind failed for TCP channel on endpoint [/0.0.0.0:9663]
java.net.BindException: [/0.0.0.0:9663] Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:469)
	at java.base/sun.nio.ch.Net.bind(Net.java:458)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:220)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:88)
	at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:60)
	at akka.io.TcpListener.<init>(TcpListener.scala:57)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error] akka.stream.impl.io.ConnectionSourceStage$$anon$1$$anon$2: Bind failed because of java.net.BindException: [/0.0.0.0:9663] Address already in use
[error] Caused by: java.net.BindException: [/0.0.0.0:9663] Address already in use
[error] 	at java.base/sun.nio.ch.Net.bind0(Native Method)
[error] 	at java.base/sun.nio.ch.Net.bind(Net.java:469)
[error] 	at java.base/sun.nio.ch.Net.bind(Net.java:458)
[error] 	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:220)
[error] 	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:88)
[error] 	at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:60)
[error] 	at akka.io.TcpListener.<init>(TcpListener.scala:57)
[error] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error] 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[error] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[error] 	at akka.util.Reflect$.instantiate(Reflect.scala:70)
[error] 	at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:101)
[error] 	at akka.actor.Props.newActor(Props.scala:226)
[error] 	at akka.actor.ActorCell.newActor(ActorCell.scala:611)
[error] 	at akka.actor.ActorCell.create(ActorCell.scala:637)
[error] 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:511)
[error] 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:533)
[error] 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
[error] 	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
[error] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
[error] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[error] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[error] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[error] stack trace is suppressed; run last Compile / run for the full output
[error] (Compile / run) java.lang.reflect.InvocationTargetException

**Comment by eed3si9n** [comment]
@jasurbek01 Please follow the bug reporting guideline - https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md#what-to-report.

Looking at the stack trace, all I'm seeing is Akka Stream failing to open port for 9663. Likely the socket is still in TIME-WAIT state. See my server fault answer for the details https://serverfault.com/questions/329845/how-to-forcibly-close-a-socket-in-time-wait/329846#329846. I don't see how this is an sbt issue.
