### ISSUE TITLE
Sbt runs assembly twice 

### ISSUE THREAD

**Issue by limansky** [sbt/sbt#5567]
## steps

The demonstration project is available at: 
https://github.com/limansky/fatbug

Then run `sbt clean publishLocal docker` (you have to have docker running).

## problem

In this setup I use assembly artifact both for publishing and in docker image. We use same setup, and in our case assembly performs quite long. I've found that our CI server performs assembly twice: first time before publishing, and second time for building docker image, even thought it's a same artifact.

## expectation

Assembly task performs only once.

**Comment by eed3si9n** [comment]
sbt treats two command invocation as separately. It's up to each task to cache based on the input value. Please request on sbt/sbt-assembly to cache.

**Comment by limansky** [comment]
@eed3si9n thanks for explanation.
