### ISSUE TITLE
Add the installation instructions for Fedora DNF along with Yum

### ISSUE THREAD

**Issue by XVilka** [sbt/sbt#5573]
Currently at https://www.scala-sbt.org/download.html you can see the following snippet:

```
curl https://bintray.com/sbt/rpm/rpm > bintray-sbt-rpm.repo
sudo mv bintray-sbt-rpm.repo /etc/yum.repos.d/
sudo yum install sbt
```
But yum was deprecated since Fedora 22 in favor of DNF (latest Fedora version is 32). And soon it will be removed completely: https://fedoraproject.org/wiki/Changes/Retire_YUM_3

Please add support/instructions for DNF too.

**Comment by eed3si9n** [comment]
For installation, is `dnf` a drop-in replacement for `yum`?

**Comment by XVilka** [comment]
Yes .

**Comment by cbrunnkvist** [comment]
All of Bintray is in `403 Forbidden` mode now, so this instruction isn't correct anymore anyway.

Are we still publishing RPMs somewhere? I can't see any in e.g. [releases/tag/v1.5.5](https://github.com/sbt/sbt/releases/tag/v1.5.5)

**Update** Files seem to be retrievable through JFrog's Artifactory [Scala RPM repo](https://scala.jfrog.io/ui/native/rpm) but I can't see how they get there or their directly downloadable URLs.

**Comment by eed3si9n** [comment]
Please see https://www.scala-sbt.org/1.x/docs/Installing-sbt-on-Linux.html#Red+Hat+Enterprise+Linux+and+other+RPM-based+distributions
