### ISSUE TITLE
:cp in console breaks input when started from sbt (v 0.12.0)

### ISSUE THREAD

**Issue by kschwank** [sbt/sbt#558]
If I run "sbt" in an empty directory, then run "console" and at the console call ":cp" (with or without a path) the input is afterwards broken: It still seems to correctly understand "normal" character, although it won't echo them anymore, but special characters like BS don't work at all.

```
Welcome to Scala version 2.9.2 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_07).
Type in expressions to have them evaluated.
Type :help for more information.

scala> :cp 
Added '/space/sbt'.  Your new classpath is:
".:/space/sbt"

scala> <console>:8: error: value text is not a member of object $iw
          this text is not echoed
               ^

scala> <console>:1: error: illegal character
   BS show up as ???
```

This is reproduceable in GNOME Terminal, xterm and on the login console and happens only if called from SBT, but not if I run "scala" directly from the command-line.

Cheers, Karsten

**Comment by harrah** [comment]
This is a bug in Scala that is fixed in 2.10.0-M7.
