### ISSUE TITLE
1.4 nightlies stopped being published in February

### ISSUE THREAD

**Issue by bjaglin** [sbt/sbt#5581]
See
- https://jenkins.scala-sbt.org/sbt-snapshots/org/scala-sbt/sbt/
- https://jenkins.scala-sbt.org:8592/job/sbt-validator/buildTimeTrend

**Comment by bjaglin** [comment]
Here is how far I got in the investigation. Chronologically:

1. https://jenkins.scala-sbt.org:8592/job/sbt-validator/1949/ is the last successful nightly (February 8th), although it did not publish sbt-launch, which makes it impossible to use
1. https://jenkins.scala-sbt.org:8592/job/sbt-validator/1958/ failed because of dependency-management/snapshot-resolution
1. https://jenkins.scala-sbt.org:8592/job/sbt-validator/1959/ brought an earlier error [error] Not a valid key: safeUnitTests (similar: scriptedTests, executeTests) which sbt/sbt-validator@aa29250 addressed as visible in https://jenkins.scala-sbt.org:8592/job/sbt-validator/1966/console
1. https://jenkins.scala-sbt.org:8592/job/sbt-validator/2020 shows compilation warning (signature changes, usage of deprecated methods)
1. https://jenkins.scala-sbt.org:8592/job/sbt-validator/2020/ brought an even earlier failure `(compilerInterface210 / Compile / compileIncremental) java.lang.NullPointerException`
1. https://jenkins.scala-sbt.org:8592/job/sbt-validator/2038 fails even faster, this time because of what seems to be a Jenkins slave setup issue (*it's the first build on agent `a1` instead of `sbtbench`*). I suspected it was linked to https://gitter.im/sbt/sbt?at=5eba832bf8ac21780740bb49 but dates don't match.

**Comment by eed3si9n** [comment]
Closing this in favor of https://github.com/sbt/sbt/issues/6062
