### ISSUE TITLE
sbt 1.3.11 regression: `appResolvers` is always `None`, `~/.sbt/repositories` is ignored

### ISSUE THREAD

**Issue by SethTisue** [sbt/sbt#5582]
## steps

in an otherwise empty directory with nothing but a `project/build.properties` file specifying either 1.3.10 or 1.3.11, with 1.3.11 I get:

```
sbt:root-20200529> show appResolvers
[info] None
```

whereas with 1.3.10 I get:

```
sbt:root-20200529> show appResolvers
[info] Some(Vector(FileRepository(local, Patterns(ivyPatterns=Vector(${ivy.home}/local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactPatterns=Vector(${ivy.home}/local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false), FileConfiguration(true, None)), public: https://repo1.maven.org/maven2/, FileRepository(local-preloaded-ivy, Patterns(ivyPatterns=Vector(/Users/tisue/.sbt/preloaded/[organization]/[module]/[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactPatterns=Vector(/Users/tisue/.sbt/preloaded/[organization]/[module]/[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false), FileConfiguration(true, None)), local-preloaded: file:////Users/tisue/.sbt/preloaded/))
```

## problem

I don't know enough about resolvers in sbt to understand the implications of this, but it seems like an unintended change, and it's breaking the Scala community build at https://github.com/scala/community-build/pull/1157 because the `resolvers.conf` file we use there is being ignored

and also, outside of the community build, it's causing my local Artifactory to be ignored. I have a `~/.sbt/repositories` file:

```
[repositories]
  local
  cache-ivy: http://127.0.0.1:8081/artifactory/scala-ci-virtual/, [organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  cache: http://127.0.0.1:8081/artifactory/scala-ci-virtual/
```

this always worked before, but now with 1.3.11 when I run `update` I see it hitting Maven Central instead of going to my Artifactory

## expectation

no deep understanding, but I expected the 1.3.10 behaviors to continue

**Comment by eed3si9n** [comment]
Thanks for the repro!

**Comment by eed3si9n** [comment]
I couldn't originally reproduce this on my machine:

```
$ sbt
[warn] No sbt.version set in project/build.properties, base directory: /private/tmp/empty
[info] welcome to sbt 1.3.11 (AdoptOpenJDK Java 1.8.0_232)
[info] loading settings for project global-plugins from idea.sbt,vimquit.sbt,plugins.sbt,pgp.sbt ...
[info] loading global plugins from /Users/eed3si9n/.sbt/1.0/plugins
[info] set current project to empty (in build file:/private/tmp/empty/)
[info] sbt server started at local:///Users/eed3si9n/.sbt/1.0/server/c8780c37cc225ce40c1a/sock
sbt:empty> show appResolvers
[info] Some(Vector(FileRepository(local, Patterns(ivyPatterns=Vector(${ivy.home}/local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactPatterns=Vector(${ivy.home}/local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false), FileConfiguration(true, None)), public: https://repo1.maven.org/maven2/, FileRepository(local-preloaded-ivy, Patterns(ivyPatterns=Vector(/Users/eed3si9n/.sbt/preloaded/[organization]/[module]/[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactPatterns=Vector(/Users/eed3si9n/.sbt/preloaded/[organization]/[module]/[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false), FileConfiguration(true, None)), local-preloaded: file:////Users/eed3si9n/.sbt/preloaded/))
```

but I might know what's going on... In sbt 1.3.11 I introduced the test to check `m.allowInsecureProtocol`:

https://github.com/sbt/sbt/blob/0d90b7d67b215c1d0d56cdef1cbc5969f0edf4c6/main/src/main/scala/sbt/Defaults.scala#L3785-L3789

The method comes from the `launcher.jar`, which I have because I bumped my `sbt` setup using SDKMAN, but given that many people would NOT have the latest launcher, I wonder if they'd get `NoSuchMethodError`. There's a silent safety net to fallback to `None` when that happens:

https://github.com/sbt/sbt/blob/0d90b7d67b215c1d0d56cdef1cbc5969f0edf4c6/main/src/main/scala/sbt/Defaults.scala#L3755-L3760

### revised repro steps

1. `sdk use sbt 1.3.10`
2. create `project/build.properties`: `sbt.version=1.3.11`
3. `sbt show appResolvers`

### workaround

Install sbt 1.3.11 as `sdk upgrade sbt` or via other means.

### notes

I guess the fix would be to add a better fallback so `m.allowInsecureProtocol` part just goes to `false`.

**Comment by eed3si9n** [comment]
Here's my PR for this https://github.com/sbt/sbt/pull/5583

**Comment by SethTisue** [comment]
Nice, thanks Eugene!

`brew upgrade sbt` isn't getting me 1.3.11 yet, but I retried my experiment just now with sbt-extras which downloaded the 1.3.11 launcher jar, and indeed the problem didn't occur.

(Over in the community build, I'll have to poke around to see what launcher jar is being used and why.)

**Comment by dwijnand** [comment]
> sbt-extras which downloaded the 1.3.11 launcher jar

:+1:



> (Over in the community build, I'll have to poke around to see what launcher jar is being used and why.)

Dbuild has its own launcher, which is only a small change on sbt/launcher (just the descriptor file, maybe?).  So it would need to be rebuilt on the new version.

**Comment by SethTisue** [comment]
@dwijnand see my commentary at https://github.com/scala/community-build/pull/1157#issuecomment-636361296 and below (TL;DR dbuild embeds the sbt 1.0.0 launcher jar which it uses to launch sbt when building individual projects). It hadn't occurred to me to wonder about dbuild's own launcher, but I don't think there's a problem there
