### ISSUE TITLE
Vulnerability in log4j dependencies

### ISSUE THREAD

**Issue by jorgebaez212** [sbt/sbt#5588]
## steps
Create an executable file containing:

java -Dsbt.ivy.home=$HOME/.ivy2 -Dsbt.boot.directory=$HOME/.sbt/boot -Dsbt.repository.config=$SBT_HOME/repositories -Djline.terminal=jline.UnixTerminal -jar $SBT_HOME/bin/sbt-launch-1.3.12.jar "$@"

## problem
Several libraries are downloaded when running the command sbt console, and at least one of them seem to have vulnerabilities:
org.apache.logging.log4j:log4j-core:2.8.1

https://snyk.io/vuln/SNYK-JAVA-ORGAPACHELOGGINGLOG4J-31409
Even if the description says that the solution is to migrate to log4j 2.8.2 or higher, the dependencies affected by vulnerabilities change between versions of log4j, and the first version without reported vulnerabilities until now seems to be org.apache.logging.log4j:log4j-core:2.13.1

## expectation

Could it be possible to modify this dependency in order to use a version of log4j that is free of issues?

## notes
Thank you for your time!

**Comment by eed3si9n** [comment]
> Several libraries are downloaded when running the command sbt console

Are you doing this on an empty directory, or on some existing sbt build? If so what sbt version are you using (set in `project/build.properties`)? As far as I know, sbt 1.3.x uses log4j 2.11.2.

**Comment by jorgebaez212** [comment]
Ok, after some testing, it looks like the log4j requirement is the one you mention, but anyhow, these versions of log4j also have dependencies with reported vulnerabilities, for example, for log4j 2.11.2:
com.fasterxml.jackson.core:jackson-databind:2.9.7:jar has some problems: https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-455617

As far as I know, the first version without reported vulnerabilities until now seems to be org.apache.logging.log4j:log4j-core:2.13.1

**Comment by eed3si9n** [comment]
https://github.com/apache/logging-log4j2/blob/d484b898218897a813eba67fc0aee62839282fce/log4j-core/pom.xml#L74-L85
jackson-databind is an optional dependency, which we do not use.
