### ISSUE TITLE
Can't override the repositories config for the launcher itself

### ISSUE THREAD

**Issue by nigredo-tori** [sbt/sbt#5590]
I can't seem to figure out how to override the repositories that the launcher itself uses. From what I can see [in the doc](https://www.scala-sbt.org/1.x/docs/Launcher-Configuration.html#Example), setting the `sbt.repository.config` system property should work. But whatever I do, the launcher keeps looking to maven.org for the artifacts, while SBT itself uses the provided repositories.

To reproduce:
1. Start in an empty directory.
1. Create a `repositories` file like this:
    ```
    [repositories]
      my-ivy-proxy-releases: https://foo.bar/repository/ivy/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext], allowInsecureProtocol
      my-maven-proxy-releases: https://foo.bar/repository/public/, allowInsecureProtocol
    ```
1. Run SBT:
    ```sh
    $ COURSIER_CACHE=./coursier sbt \
      -sbt-boot ./boot -sbt-dir ./sbt -Dsbt.repository.config=./repositories \
      -no-share -no-global --verbose --debug \
      "show version"
    ```
1. See that the launcher downloads JARs from repo1.maven.org: [out.txt](https://github.com/sbt/launcher/files/4715567/out.txt)

Environment: Ubuntu 20.04, SBT 1.3.12 from bintray.

**Comment by eed3si9n** [comment]
Please try

```
$ COURSIER_CACHE=./coursier sbt \
  -sbt-boot ./boot -sbt-dir ./sbt -Dsbt.repository.config=./repositories \
  -Dsbt.ivy.home=./ivy  --verbose --debug \
  "show version"
```

Launcher still uses Ivy.
