### ISSUE TITLE
sbt 1.4.0 forgets incremental compilation after reboot

### ISSUE THREAD

**Issue by bishabosha** [sbt/sbt#5591]
## steps

- build locally sbt on commit b1192c9021970fdd4252498ca5fcf9d7cffa9b32
- make the hello world template with `sbt new scala/hello-world.g8`
- change `sbt.version` in the new project to `1.4.0-SNAPSHOT`
- in sbt shell: `sbt:hello-world> ;run;run;run`
  - incremental compilation is cached after the first run
- shut down and restart sbt
- again use the command `;run;run;run`
  - all the sources are compiled again, despite not changing

## problem

compilation is not cached from the last boot

## expectation

the run command on the second sbt session should have immediately executed and not need to compile the project

## notes

**Comment by ngbinh** [comment]
I tried `1.4.0-M1` on our big repo at work and got hit by this issue. Had to switch back to `1.3.12`

**Comment by eed3si9n** [comment]
Here's the debug output:

```
[debug] [zinc] IncrementalCompile -----------
[debug] IncrementalCompile.incrementalCompile
[debug] previous = Stamps for: 4 products, 1 sources, 2 libraries Map(${BASE}/src/main/scala/example/Hello.scala -> farm(ef1a5f692190c990))
[debug] current source = Set(${BASE}/src/main/scala/example/Hello.scala)
[debug] Invalidating '${JAVA_HOME}/lib/rt.jar' because could not find class java.lang.String on the classpath.
[debug] > initialChanges = InitialChanges(Changes(added = Set(), removed = Set(), changed = Set(), unmodified = ...),Set(),Set(${JAVA_HOME}/lib/rt.jar),API Changes: Set())
[debug]
[debug] Initial source changes:
[debug] 	removed:Set()
[debug] 	added: Set()
[debug] 	modified: Set()
[debug] Invalidated products: Set()
[debug] External API changes: API Changes: Set()
[debug] Modified binary dependencies: Set(${JAVA_HOME}/lib/rt.jar)
[debug] Initial directly invalidated classes: Set()
[debug]
[debug] Sources indirectly invalidated by:
[debug] 	product: Set()
[debug] 	binary dep: Set(${BASE}/src/main/scala/example/Hello.scala)
[debug] 	external source: Set()
[debug] all 1 sources are invalidated
[debug] Initial set of included nodes:
[debug] Recompiling all sources: number of invalidated sources > 50.0% of all sources
```

**Comment by eatkins** [comment]
I noticed this exact same error message a few hours ago when loading the zinc project with sbt 1.4.0-SNAPSHOT. It would recompile the scala sources for the metabuild every time I started sbt for this reason.

**Comment by eed3si9n** [comment]
Here's my PR for this - https://github.com/sbt/zinc/pull/807

**Comment by eed3si9n** [comment]
https://github.com/sbt/sbt/pull/5699 pulled in the latest Zinc.
