### ISSUE TITLE
Don't publish repositories information (at least for releases)

### ISSUE THREAD

**Issue by gslowikowski** [sbt/sbt#5597]
Remove all additional resolvers from `build.sbt`, at least for releases, because artifacts published to Maven central repository should not contain additional repositories, and in fact don't need them because all dependencies are already in Maven central repo.

**Comment by eed3si9n** [comment]
Adding this line should be the fix:

```scala
ThisBuild / pomIncludeRepository := { _ => false }
```

**Comment by eed3si9n** [comment]
Since we no longer use Bintray, we can probably close this.
