### ISSUE TITLE
Save one network request per artifact

### ISSUE THREAD

**Issue by jvican** [sbt/sbt#5599]
Maven Central provides `X-Checksum-SHA1`. Right now, ivy is always downloading the files instead of picking these checksums from the same request used to download artifacts. This leads to a new network connection for every file that is downloaded.
  
This is a big deal because we would save the download of checksums for all the things we download from the Internet (not only artifacts, but also xml files!).
  
This option would be enabled only for the requests that support `X-Checksum-SHA1` and `X-Checksum-MD5`.
  
This would bring juicy speedups. Is coursier already doing this? /cc @alexarchambault

**Comment by alexarchambault** [comment]
@eed3si9n This is fixed in coursier, since https://github.com/coursier/coursier/pull/1297 (included in [`2.0.0-RC3-1`](https://github.com/coursier/coursier/releases/tag/v2.0.0-RC3-1) from 2019/08)

**Comment by eed3si9n** [comment]
ok. I'll close this then.
