### ISSUE TITLE
sbt 0.10 does not create directory structure in new project.

### ISSUE THREAD

**Issue by meowsqueak** [sbt/sbt#56]
I am operating under the (perhaps erroneous) assumption that sbt should create the directory structure defined on the Setup Wiki page when first run in a new directory. I cannot find anything that says it _ought to_, but the documentation seems to imply that it should. However it does not seem to do this for me.

 $ mkdir new
 $ cd new
 $ sbt
[info] Set current project to default (in build file:/Users/foo/new/)

> exit
>  $ ls -F
> project/ target/
>  $ ls -F project
> target/
> $ ls -F target
>  streams/

Obviously I can create the structure manually so it's a minor bug, if a bug at all. If it is not supposed to create the directory structure automatically, then perhaps a single sentence in the Wiki would be sufficient to communicate this. I am happy to edit the wiki myself if someone can confirm that this is the case.

I am using Java version 1.6.0_24.

**Comment by harrah** [comment]
This was intentionally not reimplemented.  There are better tools for setting up a new project, like lifty and giter8.

https://github.com/n8han/giter8/
http://lifty.github.com/

(I don't know whether they have been ported to 0.10.)  If you aren't sure if something is a bug, it is better to discuss on the mailing list where it can get higher visibility.

**Comment by meowsqueak** [comment]
Ok, I found the bit in the **old** wiki that made me think sbt should be doing something more than it is:

http://code.google.com/p/simple-build-tool/wiki/Setup section "Create Project", which says:

> "When you run sbt and it does not find a project in the current directory, it asks if you want to create a new project. If you say yes, sbt will prompt for some basic information:
> ...
> With the above information, sbt creates the project properties file and **directory structure**." (emphasis mine).

This doesn't happen for me with 0.10 - I just get the output mentioned in my original report. No questions, no directory structure. I expected to be prompted for Project Name, Version, etc. but instead I simply get:

```
info] Set current project to default (in build file:/home/.../ )
```

I wonder if it would be useful for the **new** wiki to mention this difference, as I, like many other people I suspect, accidentally started with the code.google.com version before we discovered that it's been superceded. When I then upgraded to 0.10 it _feels like_ a bunch of functionality is missing.

**Comment by harrah** [comment]
Everything related to 0.10 is on this github site.  That page is on Google Code, which applies to 0.7 and earlier.  If something links there from the github site it needs to be fixed.  Please use the mailing list, where you can get help easier.
