### ISSUE TITLE
JLine: The content of the buffer appears empty after an interruption

### ISSUE THREAD

**Issue by Duhemm** [sbt/sbt#5604]
When using the interruptible JLine, the following scenario can happen:

If the user types something in, doesn't press return and then the sleep is interrupted, then we get a new prompt that appears empty, but with a non-empty buffer. If the human presses enter, the reader returns what was written before the interruption (and possibly what has been added after the interruption).

Ref sbt/util#48

**Comment by eed3si9n** [comment]
I am guessing this scenario is either handled or done in a different way so it shouldn't matter?
