### ISSUE TITLE
LogExchange.initStringCodecs shows up with about 10% in sbt startup time

### ISSUE THREAD

**Issue by jrudolph** [sbt/sbt#5605]
That's for the akka-http sbt 1.0 build (commit https://github.com/akka/akka-http/commit/da0060d3bbf46efdb9e7727db590484db5bb763f on akka-http)

The code in question uses TypeTags which initializes `scala.reflect.runtime.universe` which takes most of the time. If that universe is not used elsewhere some time could be saved by not using TypeTag, maybe `StringTypeTag` could be made a macro and calculated at compile time instead of when sbt is run?

**Comment by eed3si9n** [comment]
I'm guessing this has been addressed by https://github.com/sbt/util/pull/153.
