### ISSUE TITLE
TypeTag materialization, stringification appears to be a significant overhead in logging API

### ISSUE THREAD

**Issue by retronym** [sbt/sbt#5607]
```scala
  def logEvent[A: JsonFormat: TypeTag](level: Level.Value, event: => A): Unit = {
    val v: A = event
    val tag = StringTypeTag[A]
    LogExchange.getOrElseUpdateJsonCodec(tag.key, implicitly[JsonFormat[A]])
    // println("logEvent " + tag.key)
    val entry: ObjectEvent[A] = ObjectEvent(level, v, channelName, execId, tag.key)
    xlogger.log(
      ConsoleAppender.toXLevel(level),
      new ObjectMessage(entry)
    )
  }

```

I don't quite know whether to believe what I'm seeing here:

![image](https://user-images.githubusercontent.com/65551/36296438-01673266-1339-11e8-8ce9-29b279992b34.png)

but it suggests far too much time is spent logging (only 12k samples were spent in scalac and zinc)

`ManagedLogger.success` could be tunneled through to a version of `logEvent` that accepted a pre-stringified `tag`, rather than a `TypeTag`.

I'd really suggest use of `ClassTag` instead of `TypeTag` as the key here, although there might be a good reason that you want the generic types.

**Comment by eed3si9n** [comment]
This was fixed in https://github.com/sbt/util/pull/152, I think.
