### ISSUE TITLE
Add BSP support for Metals

### ISSUE THREAD

**Issue by adpi2** [sbt/sbt#5616]
For a full integration of Metals with sbt, as a BSP server, it is required to enable the semanticdb plugin and to set some compiler options (see [Metals documentation](https://scalameta.org/metals/docs/build-tools/new-build-tool.html))

Metals include some metadata in its intialization request that should be used to identify the semanticdb version:
```
{
  "rootUri": "file:///home/adpi2/hello-world/",
  "displayName": "Metals",
  "version": "0.9.0",
  "bspVersion": "2.0.0-M4+10-61e61e87",
  "capabilities": {
    "languageIds": [
      "scala"
    ]
  },
  "data": {
    "semanticdbVersion": "4.3.10",
    "supportedScalaVersions": [
      "2.13.2",
      "2.12.11",
      "2.12.10",
      "2.13.1",
      "2.11.12",
      "2.12.8",
      "2.12.9",
      "2.13.0"
    ]
  }
}
```

**Comment by adpi2** [comment]
The problem with enabling the semanticdb plugin is that it forces a full compilation. So it is not a good idea to enable it automatically at Metals connection. It would compile everything once, then if the user stop using Metals, it will recompile everything again.

A user of Metals can enable the semanticdb plugin in its global sbt settings so that it does not worry about it anymore. It would have then a good experience using Metals with sbt and a good experience with sbt incremental compilation.

This should be as simple as:
```
Global / semanticdbEnabled := true
Global / semanticdbVersion := "4.3.10"
```

I suggest to issue a warning when Metals connects if the semanticdb plugin is not enabled or the semanticdb version is not the right one.

**Comment by adpi2** [comment]
I am curious about the `-P:semanticdb:targetroot:...` options that sbt add when semanticdb is enabled. Apparently Metals can deal with it so we are fine. But I don't see the point of overriding the targetroot default value as documented [here](https://scalameta.org/docs/semanticdb/guide.html#scalac-compiler-plugin).

I think the `semanticdbTargetRoot` setting does more harm than good:
- it is duplicated in tests config:
```
sbt:scaladex> show server / Test / semanticdbOptions
[info] * -Yrangepos
[info] * -P:semanticdb:targetroot:/home/adpi2/helloworld/server/target/scala-2.12/meta
[info] * -P:semanticdb:targetroot:/home/adpi2/helloworld/server/target/scala-2.12/test-meta

```
- it is sometime overridden to the default value
https://github.com/sbt/sbt/blob/5ca27512ca2ab4651309e0495039e20fd095df19/main/src/main/scala/sbt/plugins/SemanticdbPlugin.scala#L49-L53

I think the `semanticdbTargetRoot` setting should be removed but maybe there is a reason for it that I dont know about.

**Comment by eed3si9n** [comment]
As of https://github.com/sbt/sbt/pull/5613/commits/8789d2072453387dadedfbd29cc93f105860ba3e, you can either define `-Dsbt.semanticdb=true` or env variable `SBT_SEMANTICDB=true` that would set `semanticdbEnabled` setting too.

**Comment by sjrd** [comment]
> As of [8789d20](https://github.com/sbt/sbt/commit/8789d2072453387dadedfbd29cc93f105860ba3e), you can either define `-Dsbt.semanticdb=true` or env variable `SBT_SEMANTICDB=true` that would set `semanticdbEnabled` setting too.

This is dangerous. It exposes the same issue with spurious full recompilations if you open sbt once with and once without the env var. Same problem if Metals launches sbt with the env var but the user doesn't.

Such volatile environment should not affect compile settings.

**Comment by olafurpg** [comment]
I agree with @sjrd the compile confirmation should not be affected by the presence of an environment variable or sbt flag. 

One solution could be to declare the configuration (semanticdb=true) in some file on disk that the user can optionally gitignore. For example, the default value for `semanticdbEnabled` and associated settings could be declared via `semanticdb.json` or `project/semanticdb.json` 🤔

**Comment by sjrd** [comment]
This looks like the kind of option I would like to enable or disable globally on my machine, irrespective of the project, and without impacting the project on other machines. That's because it depends on the IDE I am using, not on the particular project.

So I would recommend that this option be stored globally, perhaps in `~/.sbt/1.0/*`.

**Comment by adpi2** [comment]
Both solution are good.

@olafurpg solution is useful for occasional or first time users of Metals that don't want semanticdb on all their projects. Metals could suggest it in a pop-up.

@sjrd solution is useful for frequent users of Metals. You configure it once and forall and then you can work on any sbt project in Metals. This solution could be documented on the Metals website.

**Comment by jastice** [comment]
@sjrd if it depends on the IDE, shouldn't the respective IDE be passing it in?

**Comment by sjrd** [comment]
Not if it affects the compiled products, or incremental compilation in any way. Otherwise you suffer from spurious recompilations from scratch every time you switch from compiling while your IDE is running or not.

**Comment by jastice** [comment]
What if different IDEs require different settings? (I don't think it applies here though, IntelliJ should not really care if this setting is on or not)

**Comment by sjrd** [comment]
If they require conflicting settings, then yeah, you're out of luck of you want to use *both* IDEs for some reason. But it seems unlikely that enabling SemanticDB could enter into conflict with anything.

**Comment by adpi2** [comment]
#5618 adds suggestion about enabling semanticdb when connecting to Metals
