### ISSUE TITLE
sbt console fails to load terminal - Invalid terminal type: jline.UnixTerminal

### ISSUE THREAD

**Issue by bmjsmith** [sbt/sbt#562]
I'm running "sbt console" using 0.12.0 under cygwin on windows with scala 2.9.2, jdk 1.6.0_25.

I'm using the shell script supplied as part of the MSI, and TERM=xterm.

I get this output, and the terminal is fairly non functional (no local echo, ^D doesn't exit).

<code>$ sbt console
Getting net.java.dev.jna jna 3.2.3 ...
:: retrieving :: org.scala-sbt#boot-jna
        confs: [default]
        1 artifacts copied, 0 already retrieved (838kB/125ms)
Getting org.scala-sbt sbt 0.12.0 ...
:: retrieving :: org.scala-sbt#boot-app
        confs: [default]
        40 artifacts copied, 0 already retrieved (8158kB/5419ms)
Getting Scala 2.9.2 (for sbt)...
:: retrieving :: org.scala-sbt#boot-scala
        confs: [default]
        4 artifacts copied, 0 already retrieved (20090kB/3389ms)
[info] Loading project definition from D:\workspace\scalaz-example-sbt\project
[info] Set current project to scalaz-example-sbt (in build file:/D:/workspace/scalaz-example-sbt/)
[info] Starting scala interpreter...
[info]
[ERROR] Failed to construct terminal; falling back to unsupportedjava.lang.IllegalArgumentException: Invalid terminal type: jline.UnixTerminal
        at scala.tools.jline.TerminalFactory.create(TerminalFactory.java:83)
        at scala.tools.jline.TerminalFactory.get(TerminalFactory.java:154)
        at scala.tools.jline.console.ConsoleReader.<init>(ConsoleReader.java:87)
        at scala.tools.jline.console.ConsoleReader.<init>(ConsoleReader.java:134)
        at scala.tools.nsc.interpreter.JLineReader$JLineConsoleReader.<init>(JLineReader.scala:42)
        at scala.tools.nsc.interpreter.JLineReader.<init>(JLineReader.scala:21)
        at scala.tools.nsc.interpreter.ILoop.chooseReader(ILoop.scala:777)
        at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:796)
        at scala.tools.nsc.interpreter.ILoop.main(ILoop.scala:851)
        at xsbt.ConsoleInterface.run(ConsoleInterface.scala:57)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:73)
        at sbt.compiler.AnalyzingCompiler.console(AnalyzingCompiler.scala:64)
        at sbt.Console.console0$1(Console.scala:23)
        at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(Console.scala:24)
        at sbt.TrapExit$.executeMain$1(TrapExit.scala:33)
        at sbt.TrapExit$$anon$1.run(TrapExit.scala:42)
Caused by: java.lang.ClassCastException: jline.UnixTerminal cannot be cast to scala.tools.jline.Terminal
        at scala.tools.jline.TerminalFactory.create(TerminalFactory.java:80)
        ... 19 more
Welcome to Scala version 2.9.2 (Java HotSpot(TM) Client VM, Java 1.6.0_25).
Type in expressions to have them evaluated.
Type :help for more information.
scala>
</code>

This seems to be an incompatibility between a jline.jar containing scala.tools.jline at ~/.sbt/boot/scala-2.9.2/lib/jline.jar and one containing plain ole jline at ~/.sbt/boot/scala-2.9.2/org.scala-sbt/sbt/0.12.0/jline-1.0.jar.

If I delete the former, I get the same as issue #504.  If I wipe ~/.sbt/boot as mentioned in 504, sbt downloads it all again.

Any workaround gratefully received.

**Comment by bmjsmith** [comment]
Just to note, this is still a problem in 0.12.2.

**Comment by mbrambley** [comment]
im having this issue also... is there at least any workaround?

**Comment by bmjsmith** [comment]
I haven't found one I like I'm afraid.  You can run sbt under DOS.  I tried finding a way to pass -Djline.terminal=scala.tools.jline.UnixTerminal through to console but couldn't get that to work.

**Comment by mbrambley** [comment]
can we get anyone to look at this? surely it would make it nicer for everyone if sbt worked in cygwin

**Comment by jsuereth** [comment]
Sorry, I've been fighting this for a long time.   It's actually a pretty annoying problem with various versions of jline.   We're paying attention and trying to fix this, but having issues.

**Comment by jsuereth** [comment]
Ok, I think I have a fix for the MSI, but I'm having issues using cygwin/terminal with the BACKSPACE button getting destroyed in the REPL.   Still some kind of odd jline/jansi versioning madness.

**Comment by bmjsmith** [comment]
Thanks Josh - if you want someone to test this let me know which build is in and I'll give it a spin.

**Comment by jsuereth** [comment]
FYI - https://github.com/sbt/sbt-launcher-package/pull/47

That's the result of my morning's debugging.   Hopefully I can hammer some more in here.

**Comment by harrah** [comment]
Possibly fixed by 1a3ea6fb8b73d290aab73964c62ad3b14c30916b.  Verification pending.

**Comment by mbrambley** [comment]
gents im just an sbt user how can i try this fix/file as i cannot even find Launch.scala in my installation?
thanks

**Comment by harrah** [comment]
Launch.scala is an sbt source file.  You can either build sbt from source (see CONTRIBUTING) or wait for 0.13.0-RC1, which might be out later this week.

**Comment by jsuereth** [comment]
Ok, so here's a quick analysis of the issues.

_FIRST_ ->  
  JLine has issues detecting cygwin.  This means we have to manually pass in the jline.Terminal setting when in cygwin using a wrapper script (combined with stty hooks, thanks to cygwin's strange environment and lack of direct cygwin hooks in jline, for good reason).
  See https://github.com/jline/jline2/issues/62
  *_Note: this workaround is the common solution for most jline cygwin users.  I'll update the docs appropriately for cygwin users, and the native packages have already had this fix for a while. *_

_SECOND_ ->
  JLine 1.x -> 2.x adapted the `jline.Terminal` setting so that you can pass just "unix" or "windows" instead of a class name.   THis is only valid in Jline 2.x, and not in 1.x.   For sbt < 0.13, it uses jline 1.x, so must pass a fully qualified classname of which terminal to use.   Scala + sbt 0.13 both use JLine 2.x, so they can just pass "unix" as the parameter and be done.

_THIRD_ ->
  Scala shades the jline library (places it under a scala.jline package).   However it does not shade the `jline.terminal` option NOR does it provide a hook such that unshaded jline class references work within it.   I consider this a bug in the shading.

SO for 0.12.x we really have no solution to this problem.   Starting in 0.13, we'll have the scripts specify the terminal as =unix.  I just verified that this works beautifully. For 0.12.x I see one of a few options:
1. Disable jline when running in cygwin by default.
2. Use `-Djline.terminal=jline.UnixTerminal` and wait for scala to fix their shaded jline.
3. Leave the scala console broken under cygwin.

I'm going to report the issue against Scala's code-base, and elicit some feedback on how we want to proceed.

**Comment by jsuereth** [comment]
Note:   Scala JLine bug reported: https://issues.scala-lang.org/browse/SI-7604

**Comment by harrah** [comment]
Awesome, thanks Josh.  The main action items for 0.13.0-RC1 are to update the setup docs for manual setup, update the changes page to notify users of the potential for improvement by using `-Djline.terminal=unix, and make the native packages to do the right thing by default.

**Comment by jsuereth** [comment]
Yeah, already have the patches ready for native packages, I'll work on the docs after I figure out this JANSI issue.

**Comment by sourcedelica** [comment]
Hi guys - would one of you mind to add answer to http://stackoverflow.com/questions/17124689/i-really-would-like-sbt-and-its-console-to-work-under-cygwin-any-way-you-think-i giving the status?  I was wondering which version of sbt and Scala repl will have the fix and if there any workarounds for now.  Thanks!

**Comment by jsuereth** [comment]
sbt 0.13 will have the fix, and will work with any Scala version AFAIK.  The backspace will most likely still be broken.  We're not sure what that issue is, but there's a fix for Scala 2.11 that may fix this issue as well.

**Comment by sourcedelica** [comment]
Thanks - that's good to know.  The backspace is my primary source of pain.

**Comment by harrah** [comment]
It is probably clear in the context of this bug, but that is backspace in the Scala REPL on mintty/cygwin that will be broken.  Other windows terminals (that don't require UnixTerminal) should work ok, including backspace.

**Comment by sourcedelica** [comment]
Ok. Are there any other terminals for Cygwin that support cut and paste?  I realize this question is out of scope for this fix :) I'm coming from Mac and Cygwin is a necessary evil.

**Comment by sourcedelica** [comment]
I'm going to try rxvt when I get back to work.

**Comment by harrah** [comment]
I don't know much about windows options other than what I've done to help reproduce and fix this bug.  I believe other terminals are limited in some way on earlier sbt versions, perhaps lacking color and shortcut support.

**Comment by bmjsmith** [comment]
Just as an update.  Using 0.13 RC 5 on mintty/cygwin/win8 and everything works like a charm, cut'n'paste and backspace in the sbt shell and in the scala console included.  Thanks all for fixing this, much appreciated.

**Comment by mbrambley** [comment]
not for me... backspace woks in sbt now but still does nothing in the scala console
am i missing something? (just installed 13.5 tonight)

**Comment by bmjsmith** [comment]
If you're using mintty, try enabling "Backspace sends ^H" in the terminal options under Keys.  If that doesn't do the trick, check that ^H is recognised as the erase character by running stty from the bash prompt.

**Comment by mbrambley** [comment]
that did it thanks!!
"backspace sends ^H"

**Comment by jsuereth** [comment]
This backspace send ^H setting sounds like something that belongs in our FAQs or documentation.  Would either of you mind contributing to the place you would most likely have found the information besides the bug request :)

Thanks, and glad this works!

**Comment by bmjsmith** [comment]
Josh - I'm not massively github savvy so let me know if I've done that wrong.
