### ISSUE TITLE
Community Build failure on 1.4.x

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#5624]
## steps

- https://github.com/scala/community-build/pull/1163

## problem

31 projects out of 219 failed to load:

https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1543/console

```
[info] Project akka-management-------------: EXTRACTION FAILED (RuntimeException: )
[info] Project akka-persistence-cassandra--: EXTRACTION FAILED (RuntimeException: )
[info] Project boopickle-------------------: EXTRACTION FAILED (RuntimeException: )
[info] Project breeze----------------------: EXTRACTION FAILED (RuntimeException: )
[info] Project cats-mtl--------------------: EXTRACTION FAILED (RuntimeException: )
[info] Project cats-retry------------------: EXTRACTION FAILED (RuntimeException: )
[info] Project circe-----------------------: EXTRACTION FAILED (RuntimeException: )
[info] Project decline---------------------: EXTRACTION FAILED (RuntimeException: )
[info] Project droste----------------------: EXTRACTION FAILED (RuntimeException: )
[info] Project expecty---------------------: EXTRACTION FAILED (RuntimeException: )
[info] Project http4s-jwt-auth-------------: EXTRACTION FAILED (RuntimeException: )
[info] Project lagom-----------------------: EXTRACTION FAILED (RuntimeException: )
[info] Project lift-json-------------------: EXTRACTION FAILED (RuntimeException: )
[info] Project log4s-----------------------: EXTRACTION FAILED (RuntimeException: )
[info] Project minitest--------------------: EXTRACTION FAILED (RuntimeException: )
[info] Project nscala-time-----------------: EXTRACTION FAILED (RuntimeException: )
[info] Project playframework---------------: EXTRACTION FAILED (RuntimeException: )
[info] Project pureconfig------------------: EXTRACTION FAILED (RuntimeException: )
[info] Project pureconfig-more-------------: EXTRACTION FAILED (RuntimeException: )
[info] Project redis4cats------------------: EXTRACTION FAILED (RuntimeException: )
[info] Project scala-logging---------------: EXTRACTION FAILED (RuntimeException: )
[info] Project scala-stm-------------------: EXTRACTION FAILED (RuntimeException: )
[info] Project scalatags-------------------: EXTRACTION FAILED (RuntimeException: )
[info] Project scalatest-------------------: EXTRACTION FAILED (RuntimeException: )
[info] Project scalatest-tests-------------: EXTRACTION FAILED (RuntimeException: )
[info] Project sconfig---------------------: EXTRACTION FAILED (RuntimeException: )
[info] Project scoverage-------------------: EXTRACTION FAILED (RuntimeException: )
[info] Project spire-----------------------: EXTRACTION FAILED (RuntimeException: )
[info] Project sttp------------------------: EXTRACTION FAILED (RuntimeException: )
[info] Project sttp-model------------------: EXTRACTION FAILED (RuntimeException: )
[info] Project zinc------------------------: EXTRACTION FAILED (RuntimeException: )
```

## expectation

The builds load.

**Comment by eed3si9n** [comment]
## Akka Management

```scala
[akka-management] [info] These subprojects will be built: default-sbt-project
[akka-management] [warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[akka-management] [info] Compiling 4 Scala sources to /home/jenkins/workspace/scala-2.13.x-jdk11-integrate-community-build/target-0.9.16/extraction/bc9ccf1cafe031a075ca111205eb01795f2f8e87/projects/af664e37a6225be847d432daf158a994559006b1/project/target/scala-2.12/sbt-1.0/classes ...
[akka-management] [error] ${BASE}/project/Common.scala:50:19: type mismatch;
[akka-management] [error]  found   : Seq[String]
[akka-management] [error]  required: Seq[Nothing]
[akka-management] [error]           else Seq("--release", "8")
[akka-management] [error]                   ^
[akka-management] [error] ${BASE}/project/Common.scala:48:20: type mismatch;
[akka-management] [error]  found   : sbt.Def.Initialize[sbt.Task[Seq[Nothing]]]
[akka-management] [error]  required: sbt.Def.Initialize[sbt.Task[Seq[String]]]
[akka-management] [error]       javacOptions ++= (
[akka-management] [error]                    ^
[akka-management] [error] two errors found
[akka-management] [error] (Compile / compileIncremental) Compilation failed
[akka-management] [warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

The build code https://github.com/akka/akka-management/blob/8bca6479de815ee145f3816fee34474fe046706b/project/Common.scala#L48-L51

```scala
      javacOptions ++= (
          if (isJdk8) Seq.empty
          else Seq("--release", "8")
        ),
```

So this looks like a regression around conditional task.

**Comment by xuwei-k** [comment]
## Zinc

```
[zinc] [info] resolving key references (24119 settings) ...
[zinc] [error] java.lang.NoSuchMethodError: 'boolean scalapb.package$.gen$default$1()'
[zinc] [error] Use 'last' for the full log.
[zinc] [warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

https://github.com/scalapb/ScalaPB/issues/777#issuecomment-645392103

**Comment by eed3si9n** [comment]
## cats-mtl

```
[cats-mtl] [error] java.lang.NoSuchMethodError: 'void geny.Writable.$init$(geny.Writable)'
[cats-mtl] [error] Use 'last' for the full log.
```

Also decline, droste, http4s-jwt-auth

**Comment by SethTisue** [comment]
I remember seeing the geny error on multiple projects, informally it seemed to be the second-most-common failure mode, after the type inference thing

**Comment by eed3si9n** [comment]
I wonder if there's a transitive lihaoyi universe of library conflict happening (due to no fault of Haoyi). Zinc uses ScalaPB 0.10.2, which pulls in lihaoyi/fastparse 2.2.4 on runtime along with **lihaoyi/geny 0.5.1** (https://repo1.maven.org/maven2/com/lihaoyi/fastparse_2.12/2.2.4/fastparse_2.12-2.2.4.pom).

I'm speculating here, but maybe the failing builds are using sbt-microsites. sbt-microsites uses lihaoyi/scalatags 0.9.0, which uses **lihaoyi/geny 0.6.0** (https://repo1.maven.org/maven2/com/lihaoyi/scalatags_2.12/0.9.0/scalatags_2.12-0.9.0.pom).

**Comment by eed3si9n** [comment]
Manually loading some repos using local 1.4.0-SNAPSHOT:

- akka-management: ok
- zinc: ok
- cats-mtl: ok
- circe: ok

**Comment by eed3si9n** [comment]
Started sbt 1.4.0-M2 Community Build:

https://github.com/scala/community-build/pull/1201
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1781/console

**Comment by eed3si9n** [comment]
sbt 1.4.0-M2 couldn't get past the first loading error. I think it's a regression - https://github.com/sbt/sbt/issues/5790

**Comment by eed3si9n** [comment]
According to Ethan (https://github.com/sbt/sbt/issues/5808):

3 projects fail to extract: droste, Lagom, playframework
1 project fails to run: enumeratum

### enumeratum

Scala broke binary compatibility in 2.12.11 breaking https://github.com/tkawachi/sbt-doctest
Ethan made a PR to restore binary compatibility for scala: scala/scala#9191
Ethan also made a PR to enumeratum to upgrade sbt-doctest to a version that is unaffected by the broken binary compatibility: lloydmeta/enumeratum#292

### droste

The droste project was depending on undefined sbt behavior: https://github.com/higherkindness/droste/pull/180

### Lagom
```
lagom/build.sbt:245: error: value ** is not a member of Seq[xsbti.VirtualFileRef]             
    val products = (a.asInstanceOf[sbt.internal.inc.Analysis]).relations.allProducts.toSeq ** new SimpleFileFilter(                    
                                                                                           ^                                           
[error] sbt.compiler.EvalException: Type error in expression
```

Ethan made a PR to lagom to address this: https://github.com/lagom/lagom/pull/3031

### Play

This project is pinned to  and the following errors are reported:

If I use origin/master instead, we get the following errors:

```
[error] ${BASE}/project/Docs.scala:186:37: overloaded method value create with alternatives:
[error]   (x$1: xsbti.compile.ClassFileManager,x$2: Boolean)xsbti.compile.IncToolOptions <and>
[error]   (x$1: java.util.Optional[xsbti.compile.ClassFileManager],x$2: Boolean)xsbti.compile.IncToolOptions
[error]  cannot be applied to (java.util.Optional[Nothing], Boolean)
[error]     val incToolOpt = IncToolOptions.create(Optional.empty(), false)
[error]                                     ^
[error] ${BASE}/project/Docs.scala:190:16: not enough arguments for method run: (sources: List[xsbti.VirtualFile], classpath: List[xsbti.VirtualFile], converter: xsbti.FileConverter, outputDirectory: java.nio.file.Path, options: List[String], incToolOptions: xsbti.compile.IncToolOptions, log: sbt.util.Logger, reporter: xsbti.Reporter)Unit.
[error] Unspecified value parameter reporter.
[error]     javadoc.run(sources, classpath, outputDir, options, incToolOpt, log, reporter)
[error]                ^
[error] two errors found
```

Ethan made a PR to playframework to fix the type inference issue: https://github.com/playframework/playframework/pull/10442

**Comment by mkurz** [comment]
> Ethan made a PR to playframework to fix the type inference issue: playframework/playframework#10442

Merged.

**Comment by mkurz** [comment]
Play still failing: https://travis-ci.com/github/playframework/playframework/jobs/381896192#L651-L740

**Comment by eatkins** [comment]
I have no idea what is going on with that build but it looks like a zinc issue. Just for the record, it is only the documentation subproject of play, which is independent from the main build, that is broken. Not that it shouldn't work but I was expecting that all of play would be broken which isn't the case.

**Comment by eed3si9n** [comment]
(For record keeping) Play issue seems to be related to Coursier - https://github.com/sbt/sbt/issues/5915

**Comment by eed3si9n** [comment]
@SethTisue wrote https://github.com/scala/community-build/pull/1223#issuecomment-701060146:

> we ended up with the following still on 1.3:
> 
> * alpakka-kafka: uses sbt-dependency-graph
> * gigahorse: same error, idk why, not investigated
> * playframework: we're on 2.8.x, fixes are on master. it's fine, it can wait
> * scalatest-tests: ScalaTest core is fine on 1.4.0-RC2, the part that isn't is `scalatest-tests`, which is so big and fragile I doubt it's worth looking into
> * proj/zinc.conf: because we're pinned to an old version
> 
> overall, this seems very good to me.

I can fix Gigahorse by bumping up Contraband version.

```
[error] (core / Compile / generateContrabands) java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: scala.collection.immutable.List.$anonfun$flatMap$1$adapted(Lscala/runtime/BooleanRef;Lscala/runtime/ObjectRef;Lscala/runtime/ObjectRef;Ljava/lang/Object;)Ljava/lang/Object;
```

This is a JSON4S bug - https://github.com/json4s/json4s/issues/455
