### ISSUE TITLE
[1.4.0-M1] Runtime reference to undefined setting: bspInternalDependencyConfigurations 

### ISSUE THREAD

**Issue by jtjeferreira** [sbt/sbt#5626]
## steps

Trying 1.4.0-M1 in my project yields the following error when starting sbt:

```
[error] Runtime reference to undefined setting: 
[error] 
[error]   coreControllers / It,test / bspInternalDependencyConfigurations from plannerservices / IntegrationTest / bspInternalDependencyConfigurations ((sbt.internal.server.BuildServerProtocol.configSettings) BuildServerProtocol.scala:139)
[error]  
[error] Use 'last' for the full log.
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

## problem

I think the problem is because `plannerservices` `dependsOn(coreControllers % "compile->compile;test->test;it->it,test")`

## expectation

sbt should start without errors as in 1.3.x

## notes

If this error is not enough I might work and submit a smaller reproducer project

**Comment by adpi2** [comment]
Thank you @jtjeferreira for reporting this issue. I'll have a look at it.

**Comment by jtjeferreira** [comment]
Hi @adpi2! I checked out e323f1f713251968b3d4ecda8a7f0ed52593713a, published locally and set my project to use `1.4.0-SNAPSHOT`, and this error still happens... :thinking:

**Comment by adpi2** [comment]
Thank you for trying @jtjeferreira!

I tried to reproduce with this sbt project but it works fine...  :thinking: 
```
ThisBuild / scalaVersion     := "2.13.2"
ThisBuild / version          := "0.1.0-SNAPSHOT"
ThisBuild / organization     := "com.example"
ThisBuild / organizationName := "example"

lazy val core = (project in file("core"))
  .configs(IntegrationTest)
  .settings(
    Defaults.itSettings,
    name := "hello-core"
  )

lazy val root = (project in file("."))
  .configs(IntegrationTest)
  .settings(
    Defaults.itSettings,
    name := "hello"
  )
  .dependsOn(core % "compile->compile;test->test;it->it,test")
```

Maybe you have to remove the 1.4.0-SNAPSHOT that is cached by boot and then reboot your sbt shell to fetch the newer 1.4.0-SNAPSHOT from your local ivy:
```
rm -Rf ~/.sbt/boot/scala-2.12.11/org.scala-sbt/sbt/1.4.0-SNAPSHOT
```

If it does not solve the issue then can you provide a minimal sbt project that reproduce the error?

Thank you for your help!!

**Comment by jtjeferreira** [comment]
Hi @adpi2! I finally found the issue. The error that I was having after your fix was similar but a bit different:

```
inventoryNgCore / It  / bspInternalDependencyConfigurations from inventoryImporters / At / bspInternalDependencyConfigurations ((sbt.internal.server.BuildServerProtocol.configSettings) BuildServerProtocol.scala:123)
```

And it was happening because I have:

```
inventoryNgCore % "compile->compile;test->test;it->test,it ",
```
(notice the extra space before the closing quote)

As soon as I removed that space, it works. However since this was working with sbt 1.3.x I am not sure if it should be "fixed", WDYT?

**Comment by adpi2** [comment]
This should be fixed by a simple ".trim" at the right place. So yeah sure we should fix it.
