### ISSUE TITLE
watch-sources will trigger on hidden .swp files (vim swap files) by default

### ISSUE THREAD

**Issue by jeremyjh** [sbt/sbt#563]
Vim by default creates hidden swap files for temporary storage and recoverability. It creates these  by default in the file's directory with the name .{filename}.swp ; e.g. Foo.scala will have a .Foo.scala.swp . 

sbt's test watcher will trigger on these files by default, so for example everytime I switch buffers a compile/test is triggered - this may be several times in a second if I page through a couple buffers - after awhile bizarre things happen and SBT crashes with an OOM exception. We can work around telling vim to use another directory or just stuff the files, but It might be nice if sbt would ignore hidden files by default, or ignore files with extended name extensions. 

Thanks!

**Comment by harrah** [comment]
By default, the watched files are `unmanagedSources` and `unmanagedResources`, which are your manually created sources and resources.  The definitions of those tasks ignore hidden files.  Perhaps a plugin is adding files to `watchSources` and it isn't ignoring hidden files?

**Comment by jeremyjh** [comment]
Yes it looks something like that. This build file is created by Play; it looks like its including all files if I understand this inspect output correctly. I don't see this problem using other build files. I'll ask them about it then, thanks for your help!

FYI this is what my inspect looks like:

[playtut] $ inspect watch-sources
[info] Task: scala.collection.Seq[java.io.File]
[info] Description:
[info]  Defines the sources in this project for continuous execution to watch for changes.
[info] Provided by:
[info]  {file:/home/jeremy/test/playtut/}playtut/_:watch-sources
[info] Dependencies:
[info]  test:unmanaged-sources
[info]  *:base-directory
[info]  test:unmanaged-resources
[info]  compile:unmanaged-sources
[info]  compile:unmanaged-resources
[info]  *:play-conf
[info] Delegates:
[info]  *:watch-sources
[info]  {.}/_:watch-sources
[info]  _/_:watch-sources
[info] Related:
[info]  _/_:watch-sources
[playtut] $ inspect _:play-conf
[info] Setting: java.io.File = /home/jeremy/test/playtut/conf
[info] Description:
[info]  
[info] Provided by:
[info]  {file:/home/jeremy/test/playtut/}playtut/_:play-conf
[info] Dependencies:
[info]  _:base-directory
[info] Reverse dependencies:
[info]  *:watch-sources
[info]  compile:source-generators
[info] Delegates:
[info]  *:play-conf
[info]  {.}/_:play-conf
[info]  _/_:play-conf

**Comment by pfn** [comment]
I've been having this same issue forever. .swp files in the resources directory causes a recompile everytime they are created and removed. No plugins are adding anything to watchSources nor unmanagedResources.

My workaround:

```
watchSources ~= { _.filterNot(_.isDirectory) }
```

**Comment by udalrich** [comment]
@pfn 's solution fails in sbt 1.1.5 (and probably 1.x, based on the docs)

build.sbt:74: error: value isDirectory is not a member of sbt.Watched.WatchSource
watchSources ~= { _.filterNot(_.isDirectory) }
