### ISSUE TITLE
Allow customization of remote cache artifacts

### ISSUE THREAD

**Issue by iRevive** [sbt/sbt#5638]
## Motivation

There are several scenarios when `cached-compile` and `cached-test` artifacts are not enough:
1) Custom configurations: IntegrationTest, additional build folders, etc.
2) Generated twirl templates.

In the current implementation, a new artifact can be added to the publish configuration: 
```scala
pushRemoteCacheConfiguration / packagedArtifacts ++= Seq(
  // custom artifacts here
)
```

Unfortunately, SBT does not know how to extract custom artifacts during `pullRemoteCache`. There is a hardcoded logic for `cached-compile` and `cached-test`.

## Possible solution

Introduce a new configuration that keeps a link between artifact and an extraction directory. Choose extraction logic based on the configuration.

**Comment by iRevive** [comment]
@eed3si9n should we close this ticket?

**Comment by eed3si9n** [comment]
Sounds good to me.

**Comment by jtjeferreira** [comment]
> Custom configurations: IntegrationTest

Is there an easy way to add IntegrationTest artifacts to the remote cache? I had a quick look to the PR, but it was not obvious...

**Comment by iRevive** [comment]
@jtjeferreira hey, could you try these settings?

```scala
import sbt.internal.RemoteCache

lazy val example = project.in(file("./example"))
  ...
  .settings(
    inConfig(IntegrationTest)(
      RemoteCache.configCacheSettings(RemoteCache.testArtifact(IntegrationTest, "cached-integration-test"))
    )
  )

**Comment by jtjeferreira** [comment]
@iRevive I tried that but still dont see any "cached-integration-test" jars being pushed.

Also in the sbt shell if I do `show core/pushRemoteCacheConfiguration/remoteCacheArtifacts`
```
> show core/pushRemoteCacheConfiguration/remoteCacheArtifacts
[info] * CompileRemoteCacheArtifact(Artifact(core, jar, jar, Some(cached-compile), Vector(), None, Map(), None, false), TaskKey(This / Select(ConfigKey(compile)) / This / packageCache), /Users/joao/git/platform/modules/core/target/scala-2.13/classes, /Users/joao/git/platform/modules/core/target/scala-2.13/zinc/inc_compile_2.13.zip)
[info] * TestRemoteCacheArtifact(Artifact(core, jar, jar, Some(cached-test), Vector(), None, Map(), None, false), TaskKey(This / Select(ConfigKey(test)) / This / packageCache), /Users/joao/git/platform/modules/core/target/scala-2.13/test-classes, /Users/joao/git/platform/modules/core/target/scala-2.13/test-zinc/inc_compile_2.13.zip, /Users/joao/git/platform/modules/core/target/streams/test/test/_global/streams/succeeded_tests)
``` 

and no sign of `cached-integration-test`, however if I do

```
show core/IntegrationTest/pushRemoteCacheConfiguration/remoteCacheArtifacts
[info] * TestRemoteCacheArtifact(Artifact(core, jar, jar, Some(cached-integration-test), Vector(), None, Map(), None, false), TaskKey(This / Select(ConfigKey(it)) / This / packageCache), /Users/joao/git/platform/modules/core/target/scala-2.13/it-classes, /Users/joao/git/platform/modules/core/target/scala-2.13/it-zinc/inc_compile_2.13.zip, /Users/joao/git/platform/modules/core/target/streams/it/test/_global/streams/succeeded_tests)
```

do I have to explicitly call `IntegrationTest/pushRemoteCache`?

**Comment by jtjeferreira** [comment]
I think the problem is in 

```scala
    pushRemoteCacheConfiguration / remoteCacheArtifacts := {
      enabledOnly(remoteCacheArtifact.toSettingKey, defaultArtifactTasks).apply(_.join).value
    }
```
and 

```
  private def defaultArtifactTasks: Seq[TaskKey[File]] =
    Seq(Compile / packageCache, Test / packageCache)
```

@iRevive @eed3si9n any hints?
