### ISSUE TITLE
forked jline2

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#5646]
Ref https://github.com/sbt/jline2/pull/1
Publish jline2

**Comment by eed3si9n** [comment]
@eatkins What should we do about JAnsi?
The original I think bundles JAnsi into the jar - https://github.com/sbt/jline2/blob/dc5c5bbd5238bef2890b77b1dea7dac02da3b43e/pom.xml#L404-L438. Splitting it out would allow more normal behavior when there's another JAnsi on the dependency graph, but this could introduce subtle change in the behavior.

**Comment by eatkins** [comment]
Good question. I have exclusively been testing without a bundled jansi so sbt itself as well as sbt console work well without the bundled jansi. My intuition would be to publish without the bundled jansi and if we see issues, we can always publish a fat jar with both.

**Comment by eed3si9n** [comment]
ok. It's on its way to Maven Central.

**Comment by eed3si9n** [comment]
https://repo1.maven.org/maven2/org/scala-sbt/jline/jline/2.14.7-sbt-5e51b9d4f9631ebfa29753ce4accc57808e7fd6b/
