### ISSUE TITLE
Forked tests and System.exit

### ISSUE THREAD

**Issue by pk11** [sbt/sbt#565]
In order to make sbt's behavior consistent with regards to calling System.exit after executing tests, it would be useful if we could configure to call System.exit for the child process when executing tests in forked mode.

This mailing list thread provides some extra background:
https://groups.google.com/forum/?fromgroups=#!topic/simple-build-tool/z282ZDoMq14

**Comment by pk11** [comment]
Thank you!

**Comment by ijuma** [comment]
I have an issue where SBT hangs while executing tests in forked mode if an exception is thrown during construction of the test class (using ScalaTest). Is it expected that this fix would solve that?

**Comment by vigdorchik** [comment]
Yes, this change fixes the hang. Still it doesn't address the issue that the failure to construct one test framework should not influence running tests from the others. What exception do you get?

**Comment by ijuma** [comment]
The stacktrace follows:

https://gist.github.com/3972753

**Comment by ijuma** [comment]
Added a follow-up to the gist.
