### ISSUE TITLE
BSP: spawned sbt process is not closed on Boot process close

### ISSUE THREAD

**Issue by jastice** [sbt/sbt#5650]
## steps

1. start an sbt BSP server process via `xsbt.boot.Boot -bsp` while there is no running sbt instance for a project
2. the process will spawn an sbt server
3. close the `Boot` process

## problem

The spawned sbt server process is not closed and remains as zombie.

**Comment by eatkins** [comment]
This sounds more like a feature than a bug to me. It means that if my editor started up a server for bsp then it's available for shell commands even if I closed the editor. It also means that if I close my editor and then start it up again, I don't have to wait for an sbt server to start for bsp features to start working.

That being said, as part of #5620, I added a server idle timeout to deal with inactive sbt server instances: https://github.com/sbt/sbt/pull/5620/commits/ea823f105101fe8a1ae62c45cabdb6b0256e2262

**Comment by adpi2** [comment]
I agree with @eatkins and I am waiting forward to #5620 on this topic and many more.

**Comment by jastice** [comment]
Right, a timeout appears to be a reasonable solution to zombification.

**Comment by adpi2** [comment]
@eatkins Can you confirm this issue has been addressed by the proposed timeout?

**Comment by eatkins** [comment]
You can test with `serverIdleTimeout := Some(30.seconds)` or some other small value to see if the server exits.

**Comment by adpi2** [comment]
Thanks for the tip! It works like a charm.

Do you know why the default value is so long?
```
serverIdleTimeout := Some(new FiniteDuration(7, TimeUnit.DAYS)),
```

**Comment by eatkins** [comment]
Yeah, I made it a week so that people who are working 9-5 will have the server survive through a long weekend. The server uses very few resources in the background since it's just blocking on some queues and its memory should be swapped out by the os. But I figure if it's been idle for a week, it's a good idea to shut it down.

**Comment by adpi2** [comment]
I guess I can close this issue.
@jastice feel free to reopen it if you would like any improvement.
