### ISSUE TITLE
1.3.13 Release is Missing Artifacts

### ISSUE THREAD

**Issue by nebhale** [sbt/sbt#5657]
It appears that the [1.3.13 release](https://github.com/sbt/sbt/releases/tag/v1.3.13) does not have the complete collection of artifacts that [previous releases](https://github.com/sbt/sbt/releases/tag/v1.3.12) had.  The release notes didn’t mention any change to this behavior, so I’m guessing it was unintentional.

**Comment by eed3si9n** [comment]
> so I’m guessing it was unintentional.

Yes. It was totally unintentional error on my part. Thanks for the reminder!

**Comment by eed3si9n** [comment]
https://github.com/sbt/sbt/releases/tag/v1.3.13

**Comment by nebhale** [comment]
Thanks for the quick turn around!
