### ISSUE TITLE
Add a task to generate the BSP connection details

### ISSUE THREAD

**Issue by adpi2** [sbt/sbt#5676]
The BSP connection details are created just after the server has started. If the server has not been started manually the BSP client wont be able to connect, unless it starts the server by itself. An alternative solution would be for the client to run a unique command such as `sbt bspConnectionDetails` which creates the connection file. Then the client can connect to the server.

Also it would be in line with the [protocol definition](https://build-server-protocol.github.io/docs/server-discovery.html#the-bsp-connection-details):

>Every build tool supporting BSP must implement a build-tool-specific command to generate the BSP connection details in one of the standard BSP locations for BSP connection files.

**Comment by adpi2** [comment]
@jastice would like to have this feature implemented?

**Comment by jastice** [comment]
Yes that would be great!

**Comment by eed3si9n** [comment]
Would it also make sense to remove the file like we remove `project/active.json` on JVM shutdown? (similar to 
https://github.com/sbt/sbt/issues/4191)
I end up having multiple sbt servers because there might be multiple attempts at trying to connect, each waiting on sbt to load.

**Comment by jastice** [comment]
The idea with the `.bsp/sbt.json` is to have a persistent configuration that any client can reference. Do you mean you end up with multiple BSP server processes?

**Comment by adpi2** [comment]
`project/active.json` and `.bsp/sbt.json` are not comparable I think.

The first one is like a lock that prevents from multiple sbt servers to run simultaneously. The other one contains information for all BSP clients to connect to the server, which means that we can have multiple `sbt -bsp` processes running at the same time.

I think the problem you have, @eed3si9n, is that your one client creates multiple `sbt -bsp` processes which then try to start the sbt server. Only one process will eventually be the sbt server but then it is possible to have some zombie processes running in the background.

A solution to this problem would be for the sbt process to kill itself when it does not hold the lock on the `project/active.json` file, meaning it is not a server, and it knows it is not a shell either. I dont know how to get the information whether a sbt process is a shell or not but we can set an option for telling so: `sbt -server`. In other words the `sbt -server` process would either get the lock on the `project/active.json` and be the only server or exit. Any opinion on this?

**Comment by eed3si9n** [comment]
It depends on the use case and some preferences, but I personally do not want sbt running as a background process ever if I can help it. This is partly due to the fact that there's no visibility into how many of them are running etc.

When using Metals for example, I would like to open a terminal tab within the editor and control the timing of BSP server connection. Today, I have to manually delete `.bsp` directory before opening a project to avoid background sbt process.

**Comment by eatkins** [comment]
I added mechanism in #5620 to prevent multiple servers from starting in many situations:
https://github.com/sbt/sbt/commit/267918958dfab2b0f21ebd9638150c8526c60457
https://github.com/sbt/sbt/blob/30e4c02c9c74db093dec21b31b5f8ae30a2ef6ff/main-command/src/main/java/sbt/internal/BootServerSocket.java#L41-L73
If we merged the bsp client with network client, it could take advantage of that infrastructure.

**Comment by eatkins** [comment]
I also attempted to make zombie server processes kill themselves, but I'm not 100% sure how well this works: https://github.com/sbt/sbt/blob/30e4c02c9c74db093dec21b31b5f8ae30a2ef6ff/main/src/main/scala/sbt/Main.scala#L1024-L1031

**Comment by adpi2** [comment]
@eatkins it would be awesome if it works! I'll give it a try!

@jastice On second thought, I think it is rather useless to create this sbt task to create the BSP connection file. Because the connection command is just `sbt -bsp`. IntelliJ can run it even if the file does not exist, it will spawn the server (which will create the file) and connect to it.

**Comment by jastice** [comment]
@adpi2 I experimented with that and it doesn't seem to be robust. First of all to create the file it's necessary to start the server and exit it manually (eg by piping in an `exit`), instead of running a batch command. And once a server is running, it don't create the file when starting sbt, since it connects to the existing server. The file won't then be created unless the server is killed and restarted.

**Comment by adpi2** [comment]
@jastice 

> First of all to create the file it's necessary to start the server and exit it manually (eg by piping in an exit)

You are right about that but why do you want to exit the server instead of connecting to it? Once the server is running the file exist and you can connect.

> And once a server is running, it doesn't create the file when starting sbt, since it connects to the existing server.

If the server is running, how is it possible that the file does not exist? Someone may have deleted it by mistake. For more robustness I can make the `sbt -bsp` process create the file as well.

On my side I have tried this:
1. no sbt process is running
2. I remove the `.bsp/sbt` file manually
3. I run `sbt -bsp` in a shell
4. I can see:
  - the sbt server process is forked
  - the `.bsp/sbt.json` file is created
  - the `sbt -bsp` process connects to the server

And so I would expect IntelliJ to do something like:
```scala
if (bspFile.exists) {
  val argv = bspFile.read().argv
  connect(argv)
} else {
  connect("sbt -bsp")
}
```

**Comment by jastice** [comment]
> You are right about that but why do you want to exit the server instead of connecting to it? Once the server is running the file exist and you can connect.

Creating the config and running the server can/should be separate steps. At least it makes it easier to generalize the UI. With an existing config any BSP client can connect automatically. With the command to create a config, I can add a convenience setup step that creates the config file for sbt initially, if I detect an sbt project. I can work around this of course, but ideally I'd like a simple and robust way to do it.

> If the server is running, how is it possible that the file does not exist? Someone may have deleted it by mistake. For more robustness I can make the sbt -bsp process create the file as well.

Someone deleted it, wheter by mistake or on purpose ;) It may be not a big deal in general, but I think it's safer not to make assumptions about what the user will or will not do here, and have a mechanism that works in any case. For example, I might want to debug connection issues and setup the project afresh, and remove the file manually. Or I remove untracked files.

> On my side I have tried this:

Yes, in that constellation it works. But this will break:

1. start `sbt -bsp`
2. sbt.json created
3. BSP server closed, but sbt server process remains
4. delete .bsp directory
5. start `bsp -sbt` again
6. sbt.json is not created

> And so I would expect IntelliJ to do something like:

That's basically what happens, except it needs to work for all the other BSP servers too, so it's much simpler to deal with if they have a similar pattern to create a config file.
