### ISSUE TITLE
New sbt task: dry-run package report 

### ISSUE THREAD

**Issue by ignasi35** [sbt/sbt#5683]
There are multiple factors affecting what artifacts are produced given an sbt build. Settings like, `crossScalaVersion` or even `scalaVersion` combine interact between the root project and the sub-project. Other settings enabling/disabling the generation of a `-sourcer.jar` (or others) can cause all types of hard-to-detect issues from the common "incomplete release missing artifact `abc_2.13.jar`" to "Too many artifacts produced, build takes twice as long".

It'd be useful to have a task to list all the artifacts a build will produce without actually producing any artifact or paying the cost of compilation. With such a list, users would be able to write their own assertions so ensure their build produce the expected outputs.

**Comment by ignasi35** [comment]
Take for example, this [issue](https://github.com/playframework/playframework/issues/10333).

**Comment by eed3si9n** [comment]
What artifact each task would produce is opaque to sbt until it happens. Like how would I ever know what class files, html files, or css files a compiler or a plugin would produce without actually running them?

**Comment by ignasi35** [comment]
> Like how would I ever know what class files, html files, or css files a compiler or a plugin would produce without actually running them?

I didn't expect a dry-run a report to be so fine-grained. I think an initial infra to list the `jar` files produced when running, for example, `publish` or `package`. `sbt` can be used by an incredible variety of technologies but the most common use case is to compile and package some scala (and/or Java) sources into a `.jar`, a `-sources.jar` and a `-javadoc.jar`

Each plugin and each task is unique so I agree that sbt can't know the full list, instead, if sbt provided a setting where plugins can aggregate the data could be useful.

------

I think I jumped too quickly to a possible solution losing focus on the problem I'm trying to solve: often I missed tools to assert the output of a build would meet my needs. Is this artifact produced, is that artifact published on the proper repository and using the correct repository format? 

This issue focuses only on the first part: what will a `+publish` command produce? With such a collection, I could assert that a certain output is produced.

If there is a combination of commands/tasks to achieve such verifications, even some documentation with recommendations or best practices would suffice for my usual needs.

**Comment by eed3si9n** [comment]
This is why I call `scalaVersion` as axis of evil. It ends up acting like a fourth axis.
As powerful as `+` is, the whole wiring is really confusing, and I feel like https://github.com/sbt/sbt-projectmatrix or something like it would bring much clarify to what's going on.

**Comment by ignasi35** [comment]
> [sbt/sbt-projectmatrix](https://github.com/sbt/sbt-projectmatrix) or something like it would bring much clarify to what's going on.

TIL: `sbt-projectmatrix` looks very intersting!

**Comment by eed3si9n** [comment]
For the preview-ish of what happens with `+`, you can try:

```
+artifacts
+packageBin/artifactPath
```

Unless there's a concrete action you're planning to take with sbt/sbt, I would like to close this issue. Is that ok?

**Comment by ignasi35** [comment]
Hi @eed3si9n, I'm on vacation now.
I'll look at the proposed solution when back to work. 


Feel free to close this. Thanks.
