### ISSUE TITLE
repo.scala-sbt.org SSL certificate is invalid

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#5685]
## steps

Open https://repo.scala-sbt.org/

## problem

SSL certificate is invalid - it's showing https://repo.lightbend.com/

## expectation

It works.

**Comment by edwardcallahan** [comment]
Sorry, all. Corrected.

**Comment by eed3si9n** [comment]
Thanks for the quick fix!

**Comment by edwardcallahan** [comment]
We've added an uptime check for repo.sbt-scala.org now too.
