### ISSUE TITLE
versionScheme setting

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#5710]
Ref https://github.com/sbt/sbt/issues/3562

This is a proposal to consider a new `Option[String]` setting called `versionScheme`. Initially the supported values are:

| versionScheme  | description |
| ---------------- | ------------- |
| `Some("early-semver")` |  Early Semantic Versioning that would keep binary compatibility across patch updates within 0.Y.z (for instance 0.13.0 and 0.13.2). Once it goes 1.0.0, it follows the regular Semantic Versioning where 1.1.0 is bincompat with 1.0.0. |
| `Some("semver-spec")`  | [Semantic Versioning](https://semver.org/) where all 0.y.z are treated as initial development (no bincompat guarantees)  |
| `Some("pvp")`                  | [Haskell Package Versioning Policy](https://pvp.haskell.org/) where X.Y are treated as major version |
| `Some("strict")`                | Requires exact match of version |

This setting can serve 2 purposes:
- (Library authors) Drive compatibility check in https://github.com/scalacenter/sbt-compatibility
- (Library users) Parse from POM file to drive more accurate eviction report

**Comment by julienrf** [comment]
>     * `Some("semver-zero")`

It is stricter than `semver`, so what do you think about `semver+`? Otherwise, I keep thinking that `semver-scala` is fine (despite it’s not yet what is used by the standard library)

Also, what do you think of using an enumeration (case objects) rather than strings?

**Comment by eed3si9n** [comment]
As per the name I'd go with whatever that comes out from the discussion in https://github.com/coursier/versions/issues/7

> Also, what do you think of using an enumeration (case objects) rather than strings?

If this ends up in POM, then I think we should use String. Let's say 1.4.0 has three schemes and 1.5.0 adds another one. 1.4.0 still needs to be able to parse the scheme.

Another motivation would be to let plugins like sbt-compatibility define keys before sbt 1.4.0. Using a data structure introduces complication if we want to do that.

**Comment by eed3si9n** [comment]
Here's the PR for the automatic eviction report - https://github.com/sbt/librarymanagement/pull/339

This needs to be paired with including versionScheme into POM, and carrying the information along to sbt.

**Comment by eed3si9n** [comment]
Including versionScheme into POM is trivial, but somehow the information seems to get lost when it goes through Coursier and/or lm-coursier - https://github.com/sbt/sbt/pull/5724

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/5724

**Comment by Daenyth** [comment]
What do the different new values *mean* specifically? I haven't yet been able to find a description of the semantics at play

**Comment by eed3si9n** [comment]
@Daenyth I updated the description.

**Comment by Daenyth** [comment]
Thank you! That's very helpful
