### ISSUE TITLE
"Can't find bundle for base name" error during compile

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#5736]
## steps

I added the test file to all 10 projects, added Ethans helpful command, an alias for `;clean;test` and updated the library versions. I run it in this way: `time sbt "repeat 1000 testAndClean"`, and it takes about 5-10 minutes sometimes longer on my machine. 

https://github.com/kraigmckernan/sbt-5262

## problem

```scala
[error] /home/kmckernan/git/sbt-5262/p4/src/test/scala/closetest/ATest.scala:6:5: exception during macro expansion: 
[error] java.util.MissingResourceException: Can't find bundle for base name org.scalactic.ScalacticBundle, locale en_US
[error]         at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
[error]         at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
[error]         at java.util.ResourceBundle.getBundle(ResourceBundle.java:782)
[error]         at org.scalactic.Resources$.resourceBundle$lzycompute(Resources.scala:8)
[error]         at org.scalactic.Resources$.resourceBundle(Resources.scala:8)
[error]         at org.scalactic.Resources$.pleaseDefineScalacticFillFilePathnameEnvVar(Resources.scala:256)
[error]         at org.scalactic.source.PositionMacro$PositionMacroImpl.apply(PositionMacro.scala:65)
[error]         at org.scalactic.source.PositionMacro$.genPosition(PositionMacro.scala:85)
[error]     1 should be (1)
[error]     ^
```

## expectations

No errors.

## note

I don't think the change to set `sbt.classloader.close` to `false` by default is a complete fix for this.

Interestingly I was also able to reproduce the problem in sbt `1.3.5` even though there is some custom code for a scalatest classloader.

_Originally posted by @kraigmckernan in https://github.com/sbt/sbt/issues/5262#issuecomment-671418525_

**Comment by kiara-riley** [comment]
Verified this is still broken with the latest versions(`scalatest 3.2.2` and `sbt 1.4.1`).

We did switch to jdk 11 though, and now I am unable to reproduce using my own repository using the new jdk. Previously, I was on jdk 8.

**Comment by HyukjinKwon** [comment]
I am facing this intermittently. I use JDK 8 with SBT 1.4.1 as well

**Comment by eed3si9n** [comment]
Would using

```scala
Test / classLoaderLayeringStrategy := ClassLoaderLayeringStrategy.Flat
```

help?

**Comment by HyukjinKwon** [comment]
Let me try with the CI (linked ^).

**Comment by HyukjinKwon** [comment]
That looks working, so far. I am going to monitor the builds for a week, and get back to you.

**Comment by HyukjinKwon** [comment]
@eed3si9n I can confirm that I don't see the exception anymore.

**Comment by HyukjinKwon** [comment]
Okay, it still happens but I *think* it's less frequent.

**Comment by eed3si9n** [comment]
I'm going to close this issue for now then.

**Comment by erikvanoosten** [comment]
Did it come back with sbt 1.8.3? (Temurin 8 and scala 2.12.17):
https://github.com/erikvanoosten/metrics-scala/actions/runs/5099828796/jobs/9167763274?pr=466#step:8:44

The second build did not see the problem.

**Comment by eed3si9n** [comment]
If this is happening even with forking I wonder if the issue is with ScslaTest not sbt?

**Comment by erikvanoosten** [comment]
> If this is happening even with forking I wonder if the issue is with ScslaTest not sbt?

I have no idea, I don't even have the beginning of an idea. For sure it is something that doesn't happen often though.
