### ISSUE TITLE
[launcher-package] Overwrites ReservedCodeCache settings specified on the command line

### ISSUE THREAD

**Issue by henricook** [sbt/sbt#5741]
## steps

Version: Sbt + launcher version 1.3.13
Repro steps:
- Make an empty directory anywhere and `cd` into it
- Run `sbt -v`
- Observe output:
```
[process_args] java_version = '8'
[sbt_options] declare -a sbt_options=([0]="-Xss8m")
# Executing command line:
java
-Dfile.encoding=UTF-8
-Xms1024m
-Xmx1024m
-Xss4M
-XX:ReservedCodeCacheSize=128m
-Xss8m
-jar
/usr/share/sbt/bin/sbt-launch.jar
```
- Try to override -XX:ReservedCodeCacheSize with `sbt -v -J-XX:ReservedCodeCacheSize=256M`
- Observe output:
```
sbt -v -J-XX:ReservedCodeCacheSize=256M
[process_args] java_version = '8'
[sbt_options] declare -a sbt_options=([0]="-Xss8m")
# Executing command line:
java
-Dfile.encoding=UTF-8
-Xms1024m
-Xmx1024m
-Xss4M
-XX:ReservedCodeCacheSize=128m
-Xss8m
-jar
/usr/share/sbt/bin/sbt-launch.jar
```

**Actual:** ReservedCodeCacheSize parameter is ignored
**Expected:** ReservedCodeCacheSize parameter is passed to JVM

## problem

It looks like the packager intentionally ignores and overwrites this argument: https://github.com/sbt/sbt-launcher-package/blob/master/src/universal/bin/sbt#L177

## expectation

**Actual:** ReservedCodeCacheSize parameter is ignored
**Expected:** ReservedCodeCacheSize parameter is passed to JVM

## workaround

If you add `-Xmx1G -XX:ReservedCodeCacheSize=256M` to `.jvmopts` in this directory the issue is fixed. It seems that you *must* specify `-Xmx` (any value) for this to work.

To test:

`echo "-Xmx1G -XX:ReservedCodeCacheSize=256M" > .jvmopts && sbt -v -J-XX:+PrintCodeCache` (and ctrl+c out of the shell to get the code cache print)

Looks like:

![image](https://user-images.githubusercontent.com/82004/89902239-1d5bce80-dbde-11ea-80ce-d7875a6a1829.png)

## notes

It's also worth noting that this "just set Xmx workaround" doesn't appear to work on the command line - only via the .jvmopts route.

![image](https://user-images.githubusercontent.com/82004/89904067-64e35a00-dbe0-11ea-911e-9113e6f1229c.png)

The simplest quick-fix solution to me seems to be: "Don't set -XX:ReservedCodeCacheSize if it's already set" - ignoring any other weirdness about why things only happen if -Xmx is set in a jvmopts.

**Comment by eed3si9n** [comment]
@henricook Thanks for the details bug report!

I'm a bit torn on this one. The relevant logic I think is the function below - https://github.com/sbt/sbt-launcher-package/blob/7d75936b0248446297a0559e21e31fcefece7c25/src/universal/bin/sbt#L181-L211

```bash
addDefaultMemory() {
  # if we detect any of these settings in ${JAVA_OPTS} or ${JAVA_TOOL_OPTIONS} we need to NOT output our settings.
  # The reason is the Xms/Xmx, if they don't line up, cause errors.
  if [[ "${java_args[@]}" == *-Xmx* ]] || \
     [[ "${java_args[@]}" == *-Xms* ]] || \
     [[ "${java_args[@]}" == *-XX:+UseCGroupMemoryLimitForHeap* ]] || \
     [[ "${java_args[@]}" == *-XX:MaxRAM* ]] || \
     [[ "${java_args[@]}" == *-XX:InitialRAMPercentage* ]] || \
     [[ "${java_args[@]}" == *-XX:MaxRAMPercentage* ]] || \
     [[ "${java_args[@]}" == *-XX:MinRAMPercentage* ]]; then
    :
  elif [[ "${JAVA_TOOL_OPTIONS}" == *-Xmx* ]] || \
       [[ "${JAVA_TOOL_OPTIONS}" == *-Xms* ]] || \
       [[ "${JAVA_TOOL_OPTIONS}" == *-XX:+UseCGroupMemoryLimitForHeap* ]] || \
       [[ "${JAVA_TOOL_OPTIONS}" == *-XX:MaxRAM* ]] || \
       [[ "${JAVA_TOOL_OPTIONS}" == *-XX:InitialRAMPercentage* ]] || \
       [[ "${JAVA_TOOL_OPTIONS}" == *-XX:MaxRAMPercentage* ]] || \
       [[ "${JAVA_TOOL_OPTIONS}" == *-XX:MinRAMPercentage* ]] ; then
    :
  elif [[ "${sbt_options[@]}" == *-Xmx* ]] || \
       [[ "${sbt_options[@]}" == *-Xms* ]] || \
       [[ "${sbt_options[@]}" == *-XX:+UseCGroupMemoryLimitForHeap* ]] || \
       [[ "${sbt_options[@]}" == *-XX:MaxRAM* ]] || \
       [[ "${sbt_options[@]}" == *-XX:InitialRAMPercentage* ]] || \
       [[ "${sbt_options[@]}" == *-XX:MaxRAMPercentage* ]] || \
       [[ "${sbt_options[@]}" == *-XX:MinRAMPercentage* ]] ; then
    :
  else
    addMemory $sbt_default_mem
  fi
}
```

it says if you have memory-related setting in arguments or SBT_OPTS, it would not create the default memory setting. Currently, `-XX:ReservedCodeCacheSize` is not recognized as one of them. So what would happen if we add `-XX:ReservedCodeCacheSize` into this logic is that no `-Xmx` setting would be set but `-XX:ReservedCodeCacheSize` would be set. Maybe that's what you want, but it feels like an easy pitfall someone could fall into. The workaround would be to specify both `-Xmx` and `-XX:ReservedCodeCacheSize`.

```bash
$ SBT_OPTS= sbt -v -J-Xmx1G -J-XX:ReservedCodeCacheSize=256M
[process_args] java_version = '8'
[sbt_options] declare -a sbt_options='()'
# Executing command line:
java
-Dfile.encoding=UTF-8
-Xmx1G
-XX:ReservedCodeCacheSize=256M
-jar
/Users/eed3si9n/.sdkman/candidates/sbt/1.3.13/bin/sbt-launch.jar
```

**Comment by henricook** [comment]
Thanks for your response Eugene, I was feeling the same thing. I realise that setting `Xmx` often (always?) goes hand-in-hand with setting `ReservedCodeCacheSize` so I see your point.

I'd kept this open because I thought command line override wasn't working, but I see in my 'notes' section screenshot above I've missed of a `-` before the `J` for `Xmx` :man_facepalming: 

So I think we can close this, it's probably enough that this issue will be Googleable with this one piece of easy to follow advice

**If you want to set -XX:ReservedCodeCacheSize via sbt you must also set -Xmx or it will be ignored**
