### ISSUE TITLE
sbtn build process

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#5758]
AppVeyor is setup to build native image.

If you push a branch named `build-graal`, AppVeyor would start a build and with "artifact"

```bash
VER=1.4.0-M1-5cf8e9f65e
MAC_URL=https://ci.appveyor.com/api/buildjobs/a0hkavuv8t4qi46b/artifacts/client%2Ftarget%2Fbin%2Fsbtn
LINUX_URL=https://ci.appveyor.com/api/buildjobs/hhj31jkk05y4aby5/artifacts/client%2Ftarget%2Fbin%2Fsbtn
WINDOWS_URL=https://ci.appveyor.com/api/buildjobs/k879pa12wcys12cp/artifacts/client%2Ftarget%2Fbin%2Fsbtn.exe

cd /tmp
mkdir sbtn
cd sbtn
mkdir darwin-amd64
mkdir linux-amd64
mkdir windows-amd64

curl -L $MAC_URL > darwin-amd64/sbtn
curl -L $LINUX_URL > linux-amd64/sbtn
curl -L $WINDOWS_URL > windows-amd64/sbtn.exe

cd darwin-amd64
chmod +x sbtn
tar czvf sbtn-darwin-amd64-$VER.tar.gz sbtn
mv sbtn-darwin-amd64-$VER.tar.gz ../
cd ../
gpg -u 0x642ac823 --detach-sign --armor sbtn-darwin-amd64-$VER.tar.gz

cd linux-amd64
chmod +x sbtn
tar czvf sbtn-linux-amd64-$VER.tar.gz sbtn
mv sbtn-linux-amd64-$VER.tar.gz ../
cd ../
gpg -u 0x642ac823 --detach-sign --armor sbtn-linux-amd64-$VER.tar.gz

cd windows-amd64
zip sbtn-windows-amd64-$VER.zip sbtn.exe
mv sbtn-windows-amd64-$VER.zip ../
cd ../
gpg -u 0x642ac823 --detach-sign --armor sbtn-windows-amd64-$VER.zip
```

Created files were uploaded manually to https://github.com/sbt/sbtn-dist/releases/tag/v1.4.0-M1-5cf8e9f65e.

**Comment by eed3si9n** [comment]
We have a permanent URL this way, and we can re-upload this to Maven Central too.

**Comment by eed3si9n** [comment]
@eatkins If these will be eventually included into the universal download like https://www.scala-sbt.org/download.html, then maybe we don't have to worry about putting them on to Maven Central for now.

<s>
On the other hand, if we want to create a universal installer, then we would need a universal `sbtn` script to distinguish between the sbtn's. (I guess that topic should be discussed in existing https://github.com/sbt/sbt/issues/5665)
</s>

**Comment by eatkins** [comment]
Looks good to me.

**Comment by eed3si9n** [comment]
https://github.com/sbt/sbtn-dist/releases/tag/v1.4.0-M2

**Comment by eed3si9n** [comment]
This is captured in https://github.com/sbt/sbtn-dist/blob/develop/download.sh
