### ISSUE TITLE
doc building fails on Windows

### ISSUE THREAD

**Issue by almibe** [sbt/sbt#5764]
## steps

Hello when I run any command that includes (Compile / doc) I get the following error on Windows:
`[error] (Compile / doc) java.net.URISyntaxException: Illegal character in path at index 53: https://docs.oracle.com/en/java/javase/11/docs/api/C:\Program Files\AdoptOpenJDK\jdk-11.0.8.10-hotspot\jmods\java.base/java/lang/Class.html`
I've tried this with sbt 1.3.4, 1.3.10, and 1.3.13

## problem

It seems like Windows paths aren't be escaped properly to work with URIs.

## expectation

Windows paths get escaped properly to work with URIs.

## notes

Work around is just to add 
`publishArtifact in (Compile, packageDoc) := false`
to your build.sbt

**Comment by eed3si9n** [comment]
@almibe Thanks for the report.

I think this is actually a bug on Scaladoc itself known as https://github.com/scala/bug/issues/11839, and was fixed in https://github.com/scala/scala/pull/8663. Please try Scala 2.13.3.

**Comment by almibe** [comment]
Cool, thanks.

**Comment by almibe** [comment]
Yep updating from 2.13.2 to 2.13.3 fixed it.  Thanks again.
