### ISSUE TITLE
sbt 1.4.0-M2 fails to resolve transitive maven dependencies from a custom Ivy repo

### ISSUE THREAD

**Issue by kamilkloch** [sbt/sbt#5787]
`ThisBuild / useCoursier := false` solves the issue.

**Comment by eed3si9n** [comment]
Thanks for the report. Could you provide reproduction steps so we can reproduce your problem on _our computers_? Also if this related to Coursier could you report it to coursier/coursier as well please?

**Comment by kamilkloch** [comment]
> Thanks for the report. Could you provide reproduction steps so we can reproduce your problem on _our computers_? Also if this related to Coursier could you report it to coursier/coursier as well please?

Sadly, I cannot easily provide provide reproduction steps, as it is a private (legacy) ivy repo. All I can say is that dependency is not an easy one and looks like this:
```sbt
libraryDependencies += ("xxx" % "yyy" % dataServerVersion %
  "compile->client-library-compile, client-library-master; runtime->client-library-runtime").
  withBranchName(Some("dev")).
  artifacts(jarArtifact("xxx-dataserver-client")).
  exclude("xxx", "yyy-utilities")
```
Works with no problems with Coursier disabled. As for reporting to coursier/coursier, I have no idea how to assemble such a dependency for `cs resolve`. If, by any chance, someone knows how to feed this horrific dependency into CLI, I will gladly file a ticket.

**Comment by kamilkloch** [comment]
Closing in favor of https://github.com/sbt/sbt/issues/5795
