### ISSUE TITLE
Display a meaningful error message for build.sbt files that do not use empty lines

### ISSUE THREAD

**Issue by michaelklishin** [sbt/sbt#58]
I just kicked off a new app and wanted to use SBT 0.10. I did not notice empty lines requirement initially and wasted about 20 minutes figuring out why my build.sbt cannot be parsed:

```
/Users/antares/Development/supersecretapp/build.sbt:2: error: eof expected but ';' found.
name := "supersecretapp"
^
[error] Error parsing expression.
```

I am sorry but this error message just isn't helpful. I don't know why this empty lines requirement is there but it is very counter-intuitive. At least improve this error message.

**Comment by ClintCombs** [comment]
The empty lines requirement does seem strange.  Is this going to change?

**Comment by rslifka** [comment]
Big +1 here, very confusing error message (and interesting requirement)
