### ISSUE TITLE
Build fails if withSources() is omitted

### ISSUE THREAD

**Issue by taylorleese** [sbt/sbt#581]
I have a build that is failing to find classes in a snapshot artifact if `withSources()` is omitted from the definition. I would leave `withSources()` in the definition except that with 0.12.1 (see https://github.com/harrah/xsbt/issues/546) that means a published pom would have an actual dependency on the source jar. Perhaps the issue has something to do with the fact that I have a dependency on the same artifact that is also a test classifier?

For example, the project will build if I leave `withSources()` below, but if I omit it then it will not build.

``` scala
lazy val myArtifact = "com.myartifact" %% "foo" % 
  "0.0.1-SNAPSHOT" withSources() changing()

lazy val myArtifactTest = "com.myartifact" %% "foo" % 
  "0.0.1-SNAPSHOT" % "test" classifier "test" changing()
```

Definitely seems suspect that things are only working without `withSources()`. Any ideas? I am using sbt 0.12.1 and compiling to 2.9.1. However, I can also reproduce the issue with 0.11.3.

**Comment by taylorleese** [comment]
Alright, so if you run `sbt "show dependency-classpath"` you can see that without `withSources()` only the test dependency is included rather than both the standard dependency and the test dependency. That seems to be the issue.

**Comment by harrah** [comment]
I attempted to reproduce this using this build.sbt with sbt 0.12.1:

``` scala
libraryDependencies ++= Seq(
  "com.github.scala-incubator.io" %% "scala-io-core" % "0.4.1" withSources() changing(),
  "com.github.scala-incubator.io" %% "scala-io-core" % "0.4.1" % "test" classifier "test" changing()
)

resolvers += "TS releases" at "http://repo.typesafe.com/typesafe/releases/"
```

`show dependency-classpath` and `show test:dependency-classpath` both appear to include the correct dependencies with or without `withSources()` or `changing()`.  (I'm not sure why `changing()` is present in your example, as SNAPSHOTs are already configured with `changing()` enabled.)
