### ISSUE TITLE
1.4.0-RC1: Unable to load as a BSP project in IntelliJ with coursier managed Java

### ISSUE THREAD

**Issue by mushtaq** [sbt/sbt#5817]
## steps

I use `coursier` to manage the Java installations and versions. 
`JAVA_HOME` is correctly set by `eval "$(cs java --jvm 11 --env)"` in the shell's rc file.
I also see that sbt generated .bsp/sbt.json contains the complete and correct path to the `java` executable.

## problem

Importing a project in IntelliJ as BSP on such a machine fails with with message "No Java runtime present, requesting install."

## notes

This may not be an sbt issue, in that case please close the ticket and I will open another one in the IntelliJ tracker.

**Comment by eed3si9n** [comment]
Given the information it's not really clear to me what the actual problem is on sbt side is. Maybe you could open IntelliJ tracker, and they could potentially inform us what's wrong?

**Comment by mushtaq** [comment]
Done. cc: @jastice 
https://youtrack.jetbrains.com/issue/SCL-18131

**Comment by mushtaq** [comment]
As suggested by @jastice on the other ticket, I tried to test the bsp from command line:

- started the sbt shell
- from another terminal, ran `sbt -bsp`
- entered the JSON mentioned in the blog: 
```json
{ "jsonrpc": "2.0", "id": 1, "method": "build/initialize", "params": { "displayName": "foo", "version": "1.0.0", "bspVersion": "2.0.0-M5", "rootUri": "file:///tmp/hello", "capabilities": { "languageIds": ["scala"] } } }
```
- Got this in response:
```txt
Content-Length: 59
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc":"2.0","method":"shutdown","params":[false,null]}
```
- in the sbt shell, got this:
```txt
[info] new client connected: network-3
sbt:msocket-root> Exception in thread "sbt-networkchannel-0" java.lang.StringIndexOutOfBoundsException: offset 0, count 219, length 128
	at java.base/java.lang.String.checkBoundsOffCount(String.java:3304)
	at java.base/java.lang.String.<init>(String.java:465)
	at sbt.internal.util.ReadJsonFromInputStream$.getLine$1(ReadJsonFromInputStream.scala:35)
	at sbt.internal.util.ReadJsonFromInputStream$.apply(ReadJsonFromInputStream.scala:47)
	at sbt.internal.server.NetworkChannel$$anon$3.run(NetworkChannel.scala:182)
sbt:msocket-root>
```
- Here is my `.bsp/sbt.json`:
```json
{
  "name": "sbt",
  "version": "1.4.0-RC1",
  "bspVersion": "2.0.0-M5",
  "languages": [
    "scala"
  ],
  "argv": [
    "/Users/mushtaqahmed/Library/Caches/Coursier/jvm/adopt@1.11.0-7/Contents/Home/bin/java",
    "-Xms100m",
    "-Xmx100m",
    "-classpath",
    "/Users/mushtaqahmed/Library/Application Support/Coursier/bin/sbt:/Users/mushtaqahmed/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/io/get-coursier/sbt/sbt-runner/0.2.0/sbt-runner-0.2.0.jar:/Users/mushtaqahmed/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-sbt/sbt-launch/1.4.0-RC1/sbt-launch-1.4.0-RC1.jar",
    "xsbt.boot.Boot",
    "-bsp"
  ]
}
```

Not sure what is wrong with my installation.

**Comment by eatkins** [comment]
#5846 fixes the StringIndexOutOfBoundsException

**Comment by mushtaq** [comment]
@eatkins Thanks, I will test it again once the fix is in.

**Comment by eed3si9n** [comment]
I'm going to close this preemptively since #5846 is fixed.
