### ISSUE TITLE
1.4.0-RC1: Support coursier based installation for sbtn native binary

### ISSUE THREAD

**Issue by mushtaq** [sbt/sbt#5819]
## steps

`sbtn` native binaries are already available from https://github.com/sbt/sbtn-dist/releases/tag/v1.4.0-M2
But there is no way to install them via coursier.

## problem

It is currently not possible to add `sbtn.json` in the coursier's [app channel](https://github.com/coursier/apps/tree/master/apps/resources) because:

1. `sbtn` binary names for the `platform` value uses a different convention compared to the coursier's [prebuilt](https://get-coursier.io/docs/cli-install.html#prebuilt) app-descriptor. E.g., `darwin-amd64` instead of `x86_64-apple-darwin`
2. Binaries are zipped

## expectation

Follow the convention so that we can support `cs install sbtn`

**Comment by dwijnand** [comment]
The binary is 5.1 MB gzipped and 15 MB unzipped.  So makes sense for cs install to support unzipping, IMO.

**Comment by mushtaq** [comment]
> The binary is 5.1 MB gzipped and 15 MB unzipped. So makes sense for cs install to support unzipping, IMO.

Makes sense. cc @alexarchambault

**Comment by eed3si9n** [comment]
I changed the platform tag, and the zip support was added to Coursier -  https://github.com/coursier/coursier/releases/tag/v2.0.5, so I'm closing this issue as fixed.
