### ISSUE TITLE
AssertionError from MergeDescriptors

### ISSUE THREAD

**Issue by asflierl** [sbt/sbt#582]
Using sbt 0.12.1, the following produces an AssertionError during the "update" task:

``` scala
libraryDependencies ++= Seq(
  "org.easytesting" % "fest-assert"  % "1.4",
  "org.easytesting" % "fest-assert"  % "1.4" % "test" intransitive())
```

Removing the "intransitive" from the 3rd line makes the error go away. This used to work with sbt 0.12.0.

Looking at the source of MergeDescriptors, this probably happens for other attributes (such as "changing"), too.

Here's the full stack trace:

> last update
> [info] Updating {file:/home/aydjen/Desktop/bug/}default-4e3e62...
> [debug] post 1.3 ivy file: using exact as default matcher
> java.lang.AssertionError: assertion failed
>     at scala.Predef$.assert(Predef.scala:146)
>     at sbt.ivyint.MergeDescriptors$.apply(MergeDescriptors.scala:22)
>     at sbt.IvySbt$$anonfun$mergeDuplicateDefinitions$1.apply(Ivy.scala:467)
>     at sbt.IvySbt$$anonfun$mergeDuplicateDefinitions$1.apply(Ivy.scala:462)
>     at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
>     at scala.collection.immutable.List.foreach(List.scala:76)
>     at sbt.IvySbt$.mergeDuplicateDefinitions(Ivy.scala:462)
>     at sbt.IvySbt$.addDependencies(Ivy.scala:440)
>     at sbt.IvySbt$Module.configureInline(Ivy.scala:150)
>     at sbt.IvySbt$Module.x$6(Ivy.scala:130)
>     at sbt.IvySbt$Module.sbt$IvySbt$Module$$moduleDescriptor0(Ivy.scala:125)
>     at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:114)
>     at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:114)
>     at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:102)
>     at sbt.IvySbt.liftedTree1$1(Ivy.scala:49)
>     at sbt.IvySbt.action$1(Ivy.scala:49)
>     at sbt.IvySbt$$anon$3.call(Ivy.scala:58)
>     at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:75)
>     at xsbt.boot.Locks$GlobalLock.withChannelRetries$1(Locks.scala:58)
>     at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:79)
>     at xsbt.boot.Using$.withResource(Using.scala:11)
>     at xsbt.boot.Using$.apply(Using.scala:10)
>     at xsbt.boot.Locks$GlobalLock.liftedTree1$1(Locks.scala:51)
>     at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:51)
>     at xsbt.boot.Locks$.apply0(Locks.scala:30)
>     at xsbt.boot.Locks$.apply(Locks.scala:27)
>     at sbt.IvySbt.withDefaultLogger(Ivy.scala:58)
>     at sbt.IvySbt.withIvy(Ivy.scala:99)
>     at sbt.IvySbt.withIvy(Ivy.scala:95)
>     at sbt.IvySbt$Module.withModule(Ivy.scala:114)
>     at sbt.IvyActions$.update(IvyActions.scala:121)
>     at sbt.Classpaths$$anonfun$work$1$1.apply(Defaults.scala:951)
>     at sbt.Classpaths$$anonfun$work$1$1.apply(Defaults.scala:949)
>     at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$54.apply(Defaults.scala:972)
>     at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$54.apply(Defaults.scala:970)
>     at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
>     at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:974)
>     at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:969)
>     at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
>     at sbt.Classpaths$.cachedUpdate(Defaults.scala:977)
>     at sbt.Classpaths$$anonfun$45.apply(Defaults.scala:856)
>     at sbt.Classpaths$$anonfun$45.apply(Defaults.scala:853)
>     at sbt.Scoped$$anonfun$hf10$1.apply(Structure.scala:586)
>     at sbt.Scoped$$anonfun$hf10$1.apply(Structure.scala:586)
>     at scala.Function1$$anonfun$compose$1.apply(Function1.scala:49)
>     at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
>     at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
>     at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:41)
>     at sbt.std.Transform$$anon$5.work(System.scala:71)
>     at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
>     at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
>     at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
>     at sbt.Execute.work(Execute.scala:238)
>     at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
>     at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
>     at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
>     at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
>     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
>     at java.util.concurrent.FutureTask.run(FutureTask.java:138)
>     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
>     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
>     at java.util.concurrent.FutureTask.run(FutureTask.java:138)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
>     at java.lang.Thread.run(Thread.java:662)

**Comment by asflierl** [comment]
Thank you.

**Comment by harrah** [comment]
I forgot to repeat part of the commit message here: "This avoids the assertion, but note that Ivy is unlikely to work properly in this situation."  Unless I did something wrong while testing, it doesn't look like the test dependency was actually treated as intransitive in 0.12.0.

**Comment by asflierl** [comment]
Thanks for the warning, I'll see what effect it'll have.
