### ISSUE TITLE
1.4.0-RC1: Compilation task output continues after console mode starts

### ISSUE THREAD

**Issue by mcanlas** [sbt/sbt#5826]
## steps

1. Create a completely empty project, with the only file being `project/build.properties` to specify the version as RC1
2. Type `sbt console` from the shell
(problem does not manifest when using `console` from within an sbt session)

## problem

The compilation task for console keeps counting upwards and showing up on screen, even though the console session has started.

## expectation

SBT should be still/quiet after the console is ready.

**Comment by eatkins** [comment]
I can't reproduce on my computer. Would it be possible to create a small project that reproduces the issue? Are you using linux, mac or windows?

**Comment by mcanlas** [comment]
Looks fixed in 1.4.0-RC2
