### ISSUE TITLE
1.4.0-RC1: On Ubuntu 20.02 terminal doesn't show keystrokes after sbt exits

### ISSUE THREAD

**Issue by e-orz** [sbt/sbt#5827]
## steps

1. clone this repo: git@github.com:e-orz/CM-Well.git
2. checkout branch dc-sync-buffer-limit
3. inside the server directory type: sbt
4. exit sbt and be back in the normal terminal
5. press some keys on the keyboard - nothing is shown

## problem

No keystrokes are shown in the terminal. Although everything works. Typing `ls` and then pressing `Enter` will show all the files in the current directory, still the keystrokes are not shown.

## expectation

See the keystrokes echoes to the terminal.

## notes
The same project works with sbt 1.3.13

**Comment by melezov** [comment]
Can confirm identical behavior on CentOS Linux release 7.7.1908

**Comment by eatkins** [comment]
Interestingly I could only reproduce with bash but the error did not happen with fish shell. At any rate, fixed by #5834
