### ISSUE TITLE
1.4.0-RC1: Exiting when using Tcp produces a SocketException

### ISSUE THREAD

**Issue by melezov** [sbt/sbt#5829]
Reproduce steps (minimum I could conjure up):

`R:\test\build.sbt` with one line:

    ThisBuild / serverConnectionType := ConnectionType.Tcp

Now, when running the SBT shell, and exiting afterwards, SBT will say farewell with a Socket explosion every time:

    r:\test>java -Duser.home=R:/empty -jar sbt-launch-1.4.0-RC1.jar
    [info] welcome to sbt 1.4.0-RC1 (AdoptOpenJDK Java 11.0.7)
    [info] loading project definition from R:\test\project
    [info] loading settings for project test from build.sbt ...
    [info] set current project to test (in build file:/R:/test/)
    [warn] there's a key that's not used by any other settings/tasks:
    [warn]
    [warn] * ThisBuild / serverConnectionType
    [warn]   +- R:\test\build.sbt:1
    [warn]
    [warn] note: a setting might still be used by a command; to exclude a key from this `lintUnused` check
    [warn] either append it to `Global / excludeLintKeys` or call .withRank(KeyRanks.Invisible) on the key
    [info] sbt server started at tcp://127.0.0.1:5857
    sbt:test> show serverConnectionType
    [info] Tcp
    sbt:test> exit
    [info] shutting down sbt server
    Exception in thread "sbt-socket-server" java.net.SocketException: Socket operation on nonsocket: configureBlocking
            at java.base/java.net.PlainSocketImpl.configureBlocking(Native Method)
            at java.base/java.net.PlainSocketImpl.socketAccept(PlainSocketImpl.java:169)
            at java.base/java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:458)
            at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:565)
            at java.base/java.net.ServerSocket.accept(ServerSocket.java:533)
            at sbt.internal.server.Server$$anon$1$$anon$2.run(Server.scala:108)
    
This is reproducible on Windows 10 x64 / CentOS 7.7 / ...

P.S.: TBH, I cannot recall exactly why we needed to switch to Tcp over Local, but I recall that it seemed to resolve an issue

**Comment by melezov** [comment]
This could have been reproduced without the `build.sbt` by using `set ThisBuild / serverConnectionType := ConnectionType.Tcp` as an argument, but I wanted to show the warning that "there's a key that won't be used blah blah", while it certainly is being used... 

Unsure I understand this new linting mechanism ^^

**Comment by eatkins** [comment]
Yes, serverConnectionType should be whitelisted from linting because it is used internally outside of normal task evaluation.
