### ISSUE TITLE
1.4.0-RC1: Confusing GC/heap tip

### ISSUE THREAD

**Issue by melezov** [sbt/sbt#5830]
When compiling a rather large project, I frequently (like every time) get the following warning:

    [warn] xx seconds of the last 10 seconds were spent in garbage collection. You may want to increase the project heap size for better performance.

The weird part is that xx is usually >> 10, a'la: 

    [warn] 30.165 seconds of the last 10 seconds were spent in garbage collection. You may want to increase the project heap size for better performance.

This is either a buggy in the measurement, or the message is somewhat unclear.

**Comment by eatkins** [comment]
Thanks for reporting! That was indeed a confusing bug but it was previously reported in #5818 and fixed in #5824.
