### ISSUE TITLE
1.4.0-RC1: Confusing cache resolution messages

### ISSUE THREAD

**Issue by melezov** [sbt/sbt#5848]
When compiling a multi-project build, the remote cache messages leave something to be desired:

    [info] remote cache not found for 0.0.0-4de3154dfe2290e65174c1cc740636ffbfea757c
    [info] remote cache artifact extracted for Some(cached-compile)
    [info] remote cache artifact extracted for Some(cached-test)
    [info] remote cache artifact extracted for Some(cached-compile)
    [info] remote cache artifact extracted for Some(cached-test)
    [info] remote cache artifact extracted for Some(cached-compile)
    [info] remote cache artifact extracted for Some(cached-test)
    [info] remote cache artifact extracted for Some(cached-compile)
    [info] remote cache artifact extracted for Some(cached-test)
    [info] remote cache not found for 0.0.0-1d149c7cb425617484ffa7a7cb5c5de3845fac11

It would be very helpful to have the module / subproject name next to the "not found / extracted" messages to get an idea what SBT is talking about.

**Comment by eed3si9n** [comment]
This was address in https://github.com/sbt/sbt/pull/5996 by @xuwei-k
