### ISSUE TITLE
sbt warns about unused keys when shouldn't

### ISSUE THREAD

**Issue by limansky** [sbt/sbt#5849]
I've faced with this issue with sbt-release plugin, but possible there can be other false warnings.

## steps

1. Use sbt-release.
2. Set `releaseCrossBuild` and `releaseProcess` settings.
3. Upgrade to sbt 1.4.0-RC1

## problem

I've got following warning:
```
[warn] there are 2 keys that are not used by any other settings/tasks:
[warn]  
[warn] * beanPuree / releaseCrossBuild
[warn]   +- /home/limansky/projects/beanpuree/build.sbt:61
[warn] * beanPuree / releaseProcess
[warn]   +- /home/limansky/projects/beanpuree/build.sbt:63
```

## expectation

No warning should be produced, since this settings are used by the plugin (`release` task).

## notes

The `build.sbt` file is here: https://github.com/limansky/beanpuree/blob/master/build.sbt

**Comment by eed3si9n** [comment]
I am guessing that `release` is a command, so you're right that it shouldn't be warned, but it's also true that it's not being used by any other settings/tasks.

**Comment by limansky** [comment]
@eed3si9n you're right, it's a command https://github.com/sbt/sbt-release/blob/master/src/main/scala/ReleasePlugin.scala#L159 .

**Comment by l15k4** [comment]
:wave: There are more of these, like : 
```
run / configuration
semanticdbTargetRoot
sourceDirectories
```
Dunno how to shake it off, there are 30 warnings in a project with 10 subprojects

**Comment by eatkins** [comment]
@l15k4 `Global / lintUnusedKeysOnLoad := false` will turn off this feature.
