### ISSUE TITLE
[BSP] Add support for `debugSession/start`

### ISSUE THREAD

**Issue by adpi2** [sbt/sbt#5866]
The `debugSession/start` starts a [DAP](https://microsoft.github.io/debug-adapter-protocol/) server for running or debugging a Scala application or test class in Metals (VScode, Emacs et Vim).

An implementation of a Java DAP server is provided by the [*com.microsoft.java.debug.core*](https://github.com/microsoft/vscode-java-debug) library.

**Comment by er1c** [comment]
This would be amazing!  Looks like there is more information on how bloop implemented it here: https://scalacenter.github.io/bloop/docs/debugging-reference

**Comment by adpi2** [comment]
Thanks @er1c for your support.

So far we decided not to implement it in sbt because we don't want to add the dependency to [com.microsoft.java.debug.core](https://github.com/microsoft/vscode-java-debug) nor do we want to reimplement DAP from scratch in sbt.

As an alternative, which has already been discussed with Metals maintainers, we want to implement `debugSession/start` in the Metals sbt plugin: https://github.com/scalameta/metals-feature-requests/issues/168

**Comment by er1c** [comment]
@adpi2 should this issue be closed?

**Comment by adpi2** [comment]
Yes and sorry if this issue was misleading...
