### ISSUE TITLE
sbtn exits after "starting an instance" on Windows 10

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#5870]
## steps

Using sbt 1.4.0-RC1 build.

```
> sbtn.exe
```

## problem

```
> sbtn.exe
[info] entering *experimental* thin client - BEEP WHIRR
[info] server was not detected. starting an instance
```

Then the program quits.

## expectation

It enters into sbt shell or display some error message.

**Comment by eatkins** [comment]
I can't reproduce this with the latest code but I have seen this behavior before. It happens when System.console != null but the console input stream returns -1 to the jline reader https://github.com/sbt/sbt/blob/cc0445db4e9ad649ea2a55988bd0842e64fe8840/internal/util-complete/src/main/scala/sbt/internal/util/LineReader.scala#L84-L91 I'm not opposed to adding some logging before exiting but it would be a change from the original working behavior.

**Comment by eed3si9n** [comment]
I wonder if this should be `sbt.bat` instead of `sbt.cmd`?

https://github.com/sbt/sbt/blob/923ae57c1c6f906540f13d3896ba9966216929a6/main-command/src/main/scala/sbt/internal/client/NetworkClient.scala#L983

**Comment by eatkins** [comment]
I have a repro now where sbtn just hangs on startup on windows.

**Comment by eed3si9n** [comment]
I'll move this out to 1.4.1 until we can test more.

**Comment by eed3si9n** [comment]
I get another error using sbt 1.4.0:

```
C:\Users\xxx\work\hello>sbt --client
[info] entering *experimental* thin client - BEEP WHIRR
[info] server was not detected. starting an instance
 ava.io.IOException: Failed to get console mode: T h e   h a n d l e   i s   i n v a l i d .

        at org.jline.terminal.impl.jansi.win.JansiWinSysTerminal.createTerminal(JansiWinSysTerminal.java:47)
        at sbt.internal.util.JLine3$.windowsJansi(JLine3.scala:44)
        at sbt.internal.util.JLine3$.system(JLine3.scala:56)
        at sbt.internal.util.Terminal$.newConsoleTerminal(Terminal.scala:722)
        at sbt.internal.util.Terminal$.withStreams(Terminal.scala:333)
        at sbt.internal.client.NetworkClient$.main(NetworkClient.scala:1135)
        at sbt.internal.client.NetworkClient.main(NetworkClient.scala)
        at sbt.client.Client.main(Client.java:19)
```

**Comment by eatkins** [comment]
I can verify that this happens with `sbt --client` on my vm but not if you call sbtn directly. It seems that no console input exists in the forked client however `sbt --client` invokes it.

**Comment by SethTisue** [comment]
is this still reproducible?

**Comment by eed3si9n** [comment]
I didn't check, but hopefully no longer an issue.
