### ISSUE TITLE
`--ivy` option not supported in `SBT_OPTS` for launcher

### ISSUE THREAD

**Issue by avdv** [sbt/sbt#5885]
## steps

1. `export SBT_OPTS='--ivy /tmp/foo`
2. `sbt sbtVersion`

## problem

It seems like the option in SBT_OPTS is not properly removed from the arguments to the JVM.

Output:
```
Unrecognized option: --ivy
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
## expectation

I would expect that this had the same meaning as `sbt --ivy /tmp/foo`.

**Comment by avdv** [comment]
Um, there seems to be more problems regarding the `SBT_OPTS` variable.

Setting it to `--no-share`, and running `sbt sbtVersion` results in:
```console
$ ls -A1 project/
.sbtboot -Dsbt.boot.directory=project
build.properties
target
```
So it does not seem to properly split the arguments, but interprets the latter arguments as a single value...

**Comment by avdv** [comment]
OK, I see that `--ivy` / `-ivy` is not processed in `map_args` which handles `SBT_OPTS`. So that option is not seen as an SBT option at all, although it sets the `sbt.ivy.home` which is a sbt system property such as those set by `--no-global`, `--no-share` et cetera.

Is there a rationale why this option is not considered a sbt option?

edit: It also works as expected when added to the `.sbtopts` file.

**Comment by eed3si9n** [comment]
@avdv I think the meaning of `SBT_OPTS` used to be just another `JAVA_OPTS`? I support the shift towards anything-arg-would-support. The change may have been happening already but maybe it's been inconsistent.
