### ISSUE TITLE
https://piccolo.link is not responding

### ISSUE THREAD

**Issue by anthonylusardi-da** [sbt/sbt#5890]
## steps

Attempt to download sbt via: `https://piccolo.link/sbt-1.3.13.zip`

## problem

Request times out. In a web browser it looks like:

![image](https://user-images.githubusercontent.com/59614480/94067174-79a83580-fdbb-11ea-827e-8595b6d3499b.png)

## expectation

I get the sbt zip file.

## notes

Likely related to/the cause of https://github.com/sdkman/sdkman-cli/issues/805

**Comment by eed3si9n** [comment]
Sorry about this. It seems like something is going on there. There's an existing issue here - https://github.com/sbt/sbt/issues/5860
