### ISSUE TITLE
Compile analysis does not contain warnings since 1.4.0-RC2

### ISSUE THREAD

**Issue by rtimush** [sbt/sbt#5892]
## steps

build.sbt:
```
scalaVersion := "2.12.12"
scalacOptions := Seq("-Xlint:unused")
```

src/main/scala/A.scala:
```
object A {
  private val a: Int = 1
}
```

Steps:
- `sbt clean consoleProject`
- `(Compile / compile).eval.readSourceInfos.getAllSourceInfos.values`

## problem

With 1.4.0-RC2 the list of problems in the `SourceInfo` is empty:
```
[info] compiling 1 Scala source to .../classes ...
[warn] .../A.scala:2:15: private val a in object A is never used
[warn]   private val a: Int = 1
[warn]               ^
[warn] one warning found
res0: java.util.Collection[xsbti.compile.analysis.SourceInfo] = [SourceInfo(List(), List(), List())]
```

## expectation

With 1.4.0-RC1 and earlier the `SourceInfo` used to contain information about warnings:
```
scala> (Compile / compile).eval.readSourceInfos.getAllSourceInfos.values
[info] compiling 1 Scala source to .../classes ...
[warn] ${BASE}/src/main/scala/A.scala:2:15: private val a in object A is never used
[warn]   private val a: Int = 1
[warn]               ^
[warn] one warning found
res0: java.util.Collection[xsbti.compile.analysis.SourceInfo] = [SourceInfo(List([Warn] ${BASE}/src/main/scala/A.scala:2: private val a in object A is never used), List(), List())]
```

## notes

I'm not sure if this change was intentional, but it breaks my [sbt-rewarn](https://github.com/rtimush/sbt-rewarn) plugin, so I thought it's worth reporting.

**Comment by eed3si9n** [comment]
@rtimush Thanks for the report. Sounds like a regression to me.

**Comment by eed3si9n** [comment]
If we regressed from RC1 (9/7) to RC2 (9/23)

It has to be from one of Zinc changes - https://github.com/sbt/zinc/compare/v1.4.0-M12...v1.4.0-M13
or one of Defaults changes https://github.com/sbt/sbt/commits/develop/main/src/main/scala/sbt/Defaults.scala

but nothing really jumps at me.

**Comment by rtimush** [comment]
I ran git bisect, and the commit that broke the compile analysis warnings is https://github.com/sbt/sbt/commit/3c24e9d29d7090127d1be73e40665c002d8494a7. Also, setting `sourcePositionMappers := Nil` fixes the problem.

**Comment by rtimush** [comment]
So, apparently what happens is that sourcePositionMapper converts virtualizes path into the real one, then the real path is used to build a map of compile problems in [Incremental#problem](https://github.com/sbt/zinc/blob/b40423e350d6ed803850deeaf07fdc937decb1cd/internal/zinc-core/src/main/scala/sbt/internal/inc/Incremental.scala#L683) but the lookup uses the virtualized path in [Incremental#addProductsAndDeps](https://github.com/sbt/zinc/blob/b40423e350d6ed803850deeaf07fdc937decb1cd/internal/zinc-core/src/main/scala/sbt/internal/inc/Incremental.scala#L964).

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/zinc/pull/931 by @adpi2
