### ISSUE TITLE
1.4.0-RC2: cannot load a plugin that depends on sbt-dependency-graph transitively

### ISSUE THREAD

**Issue by raboof** [sbt/sbt#5894]
## steps

Depend on a plugin that depends on sbt-dependency-graph transitively (e.g. https://github.com/lightbend/sbt-paradox-dependencies)

## problem

```
[error] Some keys were defined with the same name but different types: 'moduleGraphStore' (sbt.Task[net.virtualvoid.sbt.graph.ModuleGraph], sbt.Task[sbt.internal.graph.ModuleGraph])
[error] Use 'last' for the full log.
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

From this error, it's not to clear what's going on, and even if you are aware of the issue, it's not so easy to see *which* sbt plugin has this transitive dependency.

## notes

This is a consequence of folding sbt-dependency-graph into sbt 1.4.0.

It might be fine (there are probably few plugins that have this transitive dependency, and for those it's probably not a problem to introduce a new version where the transitive dependency is dropped), but I wanted to create this issue to make sure we're aware of it and it can come up in a web search for someone who runs into this problem :)

**Comment by eed3si9n** [comment]
@raboof Thanks for the report! Maybe I can change the intermediate key names to avoid this?

**Comment by eatkins** [comment]
Looks like this came up with the community build too: https://github.com/scala/community-build/pull/1223#issuecomment-698060910. Renaming the intermediate keys sounds like a good approach.
