### ISSUE TITLE
Add scala major version source directories

### ISSUE THREAD

**Issue by mpilquist** [sbt/sbt#5895]
SBT currently adds various Scala version specific source directories -- e.g., src/{main,test}/scala-{major.minor}. With the Scala 3 release getting closer and libraries cross building for Scala 3 and Scala 2, it would be helpful if SBT added major version specific source directories as well -- e.g., src/{main,test}/scala-{major}.

I've been using this snippet in fs2 and a few other projects:

```scala
Compile / unmanagedSourceDirectories ++= {
  val major = if (isDotty.value) "-3" else "-2"
  List(CrossType.Pure, CrossType.Full).flatMap(
    _.sharedSrcDir(baseDirectory.value, "main").toList.map(f => file(f.getPath + major))
  )
}
```

**Comment by eed3si9n** [comment]
@jastice iirc each of these create an empty directory when using IntelliJ. Is that still the case?

**Comment by eed3si9n** [comment]
In principle it sounds like a good idea, but also it's hard to gauge what the overall % of builds would benefit from `src/main/scala-2/` as opposed to `src/main/scala-2.12/` and `src/main/scala-2.13/` that it currently supports. I'd encourage creating a plugin first and see how it catches on?

**Comment by mpilquist** [comment]
sbt-spiewak does this already, but you get all of Daniel's strongly formed opinions about builds as well. :) Daniel and I and some others on Gitter have discussed upstreaming this type of config to sbt-dotty, but if I understand the roadmap of sbt-dotty correctly, that's about to be incorporated in to sbt proper.

No strong opinions on whether SBT should do this or not, but would be nice to lower the barrier of entry for folks cross building scala 2 & 3 projects. I'm pretty sure most of the Typelevel projects that are cross-building have required at least one scala-3 directory -- definitely at least cats-effect, fs2, and scodec-bits (also ip4s, though that's non-Typelevel). This will be common for any library that has a macro or otherwise wants to include support for new Scala 3 language features.

**Comment by djspiewak** [comment]
> strongly formed opinions about builds

I believe the adjective you're looking for is "correct". 😉 

Just kidding. I do believe that sbt should do this, for the same reason it does the minor source dirs already. This would also be a similar pathway to how *that* feature arose, since it was extremely common practice for builds prior to when this functionality was upstreamed.

I've migrated several projects to Dotty at this point of varying complexity, and only the most absolutely basic ones were able to avoid this need.

**Comment by tpolecat** [comment]
I think this is going to be pretty universal for library maintainers but I'm fine with a plugin, if someone can figure out how to do that. While we're asking for ponies I'd also like to see `scala-<version>+` for that `<version>` or later, and the same with `-`. For doobie I ended up with 

```
src/
  main/
    scala/
    scala-2/
    scala-2.12/
    scala-2.13+/
    scala-3/
```

**Comment by jastice** [comment]
> @jastice iirc each of these create an empty directory when using IntelliJ. Is that still the case?

No, this doesn't happen anymore

**Comment by eed3si9n** [comment]
Here's my PR for this - https://github.com/sbt/sbt/pull/5919

**Comment by mpilquist** [comment]
@eed3si9n I noticed something with this fix -- in a cross project, the Scala major version directories are added for the jvm directory but not the shared directory.

E.g., from fs2:

```
sbt:fs2-core> show unmanagedSourceDirectories
[info] * /Users/mpilquist/Development/oss/fs2/core/jvm/src/main/scala
[info] * /Users/mpilquist/Development/oss/fs2/core/jvm/src/main/scala-3.0.0-M2
[info] * /Users/mpilquist/Development/oss/fs2/core/jvm/src/main/scala-3
[info] * /Users/mpilquist/Development/oss/fs2/core/jvm/src/main/java
[info] * /Users/mpilquist/Development/oss/fs2/core/shared/src/main/scala-3.0.0-M2
[info] * /Users/mpilquist/Development/oss/fs2/core/shared/src/main/scala
```

**Comment by eed3si9n** [comment]
@mpilquist Aren't those construct created by a plugin?

**Comment by mpilquist** [comment]
Hm, not sure, sbt-crossproject maybe?

**Comment by armanbilge** [comment]
The cross project issue is fixed in https://github.com/portable-scala/sbt-crossproject/pull/132.
