### ISSUE TITLE
[1.4.0-RC2] sbt-site's `previewSite` can't be stopped by pressing a key

### ISSUE THREAD

**Issue by ennru** [sbt/sbt#5899]
## steps

Many Akka projects use sbt-site to bring together documentation generated by unidoc and Paradox.

Eg. Alpakka Kafka https://github.com/akka/alpakka-kafka

1. updated sbt version in build propertiesd
1. comment out "sbt-paradox-dependencies" in plugins.sbt (see #5894)
1. sbt
1. sbt> docs/previewSite

## problem

sbt-site's `previewSite` task waits until the user presses any key. With sbt 1.4.0-RC2 the keypress is not detected. It can't be stopped by Ctrl-C either.

The current solution in sbt-site

https://github.com/sbt/sbt-site/blob/5aab1d9a2be6d270d9bee1637c503d8a831a88b4/src/main/scala/com/typesafe/sbt/site/SitePreviewPlugin.scala#L31-L37

**Comment by eed3si9n** [comment]
If pressing Enter is acceptable, then the following works on my machine:

```diff
diff --git a/src/main/scala/com/typesafe/sbt/site/SitePreviewPlugin.scala b/src/main/scala/com/typesafe/sbt/site/SitePreviewPlugin.scala
index efe043d..b6435ea 100644
--- a/src/main/scala/com/typesafe/sbt/site/SitePreviewPlugin.scala
+++ b/src/main/scala/com/typesafe/sbt/site/SitePreviewPlugin.scala
@@ -24,20 +24,14 @@ object SitePreviewPlugin extends AutoPlugin {
       val portOption = previewFixedPort.value
       val browser = previewLaunchBrowser.value
       val path = previewPath.value
+      val ui = interactionService.value

       val port = portOption getOrElse Port.any
       val server = createServer(file, port) start()
-      val sLog = streams.value.log
-      sLog.info("SitePreviewPlugin server started on port %d. Press any key to exit." format port)
-      // TODO: use something from sbt-web?
-      @annotation.tailrec def waitForKey(): Unit = {
-        try { Thread sleep 500 } catch { case _: InterruptedException => () }
-        if(System.in.available <= 0)
-          waitForKey()
-      }
       if(browser)
         Browser open ("http://localhost:%d/%s".format(port, path))
-      waitForKey()
+      ui.readLine(s"SitePreviewPlugin server started on port $port. Press enter to exit. ", false)
```

@eatkins Is there a way to get to a `Terminal` object or `UITask.Reader` (?) from the user land so a plugin can do "press any key" like watch?

**Comment by eed3si9n** [comment]
> It can't be stopped by Ctrl-C either.

That might be because of

```scala
try { Thread sleep 500 } catch { case _: InterruptedException => () }
```

**Comment by ennru** [comment]
Thank you @eed3si9n.
We go with "Enter" and use the `ui.readLine`. It works for me in the sbt 1.4.0-RC2 shell.
It does NOT work in `sbtn` -- and Ctrl-C doesn't work either there.

**Comment by eatkins** [comment]
The big problem was the use of `System.in.available` which isn't guaranteed to ever return a non-zero value. Since the task blocks until there is any input, I am not sure why they were polling `System.in.available` and not just calling `System.in.read` directly. Catching and ignoring the `InterruptedException` prevents ctrl+c from working because the only mechanism we have for cancelling a task is interrupting it. The log message is also misleading because any key did not work with 1.3.13, only enter did even with 1.3.13 because sbt always puts itself in canonical mode before running tasks which means that `System.in` is line buffered.

Here is what I think would be a better fix for sbt-site:
```patch
-      sLog.info("SitePreviewPlugin server started on port %d. Press any key to exit." format port)
-      // TODO: use something from sbt-web?
-      @annotation.tailrec def waitForKey(): Unit = {
-        try { Thread sleep 500 } catch { case _: InterruptedException => () }
-        if(System.in.available <= 0)
-          waitForKey()
-      }
+      sLog.info("SitePreviewPlugin server started on port %d. Press enter to exit." format port)
       if(browser)
         Browser open ("http://localhost:%d/%s".format(port, path))
-      waitForKey()
-      server stop()
-      server destroy()
+      try System.in.read
+      finally {
+        server stop()
+        server destroy()
+      }
     },
```

With this patch, enter and ctrl+c work both with sbt and sbtn.

**Comment by eatkins** [comment]
> @eatkins Is there a way to get to a Terminal object or UITask.Reader (?) from the user land so a plugin can do "press any key" like watch?

I don't think either of those are ideal to expose publicly. What I do think might make sense is to add an api for toggling canonical mode and echo in a task. I am imaging a macro that checks that it is only called in a task and toggles those terminal parameters.

**Comment by ennru** [comment]
Thank you @eatkins 

That solution is the least unexpected, so much better.

**Comment by ennru** [comment]
Interestingly enough, that solution doesn't work for normal keys nor Enter.
But Ctrl-C works nicely.
This applies both to the sbt shell and sbtn.

**Comment by eatkins** [comment]
That is strange. It worked fine for me. What os and jvm are you using?

**Comment by ennru** [comment]
OSX with AdoptOpenJDK 11.

**Comment by eatkins** [comment]
Hmm. That is pretty much my setup too.

**Comment by ennru** [comment]
I started over but get the same result.
So for now `ui.readLine` seems better if #5900 gets sorted out.

**Comment by eatkins** [comment]
As an sbt maintainer, I don't really care how previewSite is fixed but I would really like to understand why this isn't working on your terminal because it means that my assumptions of how sbt's input streams work is wrong which could cause problems elsewhere.

**Comment by ennru** [comment]
Sure, what more can I try out to ensure your assumptions are correct?

**Comment by eatkins** [comment]
I need to generate an sbt branch that adds some println debugging. Are you up for publishing a local sbt from that branch and testing with it?

**Comment by ennru** [comment]
Sure. I'm happy to help.

**Comment by eatkins** [comment]
I created a branch in my sbt fork called read-debug, https://github.com/eatkins/sbt/tree/read-debug, that adds some printlns. When I run docs/previewSite and hit enter when prompted, I see the following:
```
[info] SitePreviewPlugin server started on port 4000. Press enter to exit.
enter read scripted? false booting? false
reading from sbt.internal.util.Terminal$ConsoleTerminal@2fa631a3 sbt.internal.util.Terminal$WriteableInputStream@7e574cca
writeable input stream sbt.internal.util.Terminal$WriteableInputStream@7e574cca engering read
No bytes avaialable waiting for result from java.io.BufferedInputStream@5537ab1a on background thread
Reading from java.io.BufferedInputStream@5537ab1a on background thread

got 10 from java.io.BufferedInputStream@5537ab1a on background thread
writeable input stream sbt.internal.util.Terminal$WriteableInputStream@7e574cca returning 10 in read
[success] Total time: 46 s, completed Sep 26, 2020, 12:44:41 PM
sbt:akka-stream-kafka> No bytes avaialable waiting for result from java.io.BufferedInputStream@5537ab1a on background thread
Reading from java.io.BufferedInputStream@5537ab1a on background thread
```

As a warning, these debugging messages are very annoying when you are trying to input commands in the shell.

**Comment by eatkins** [comment]
It would also be interesting to see what is printed with the interaction service approach.

**Comment by eatkins** [comment]
Interestingly, I see that I get 10 when I press enter when using System.in.read vs 13 for the ui interaction service approach so there is something different going on with my computer as well even though it does work for me either way.

**Comment by ennru** [comment]
I've problems to get a local sbt build to work. (I haven't built sbt locally before.)

`./sbt-allsources.sh` results in `java.lang.NoSuchMethodError: sbtbuildinfo.package$BuildInfoKey$.taskValue(Lsbt/Task;Lscala/reflect/Manifest;)Lsbtbuildinfo/package$BuildInfoKey$Entry;`

Just `sbt` starts but `publishLocalAllModule` fails with `java.lang.NoSuchMethodError: lmcoursier.Inputs$.configExtendsSeq(Lscala/collection/Seq;)Lscala/collection/Seq;` for all projects.

**Comment by eatkins** [comment]
For this purpose, you don't actually need sbt-allsources.sh. All you need to do is `sbt publishLocal`. That will publish sbt with version `1.4.0-SNAPSHOT`. Once that's done, you should be able to run the project with `sbt -Dsbt.version=1.4.0-SNAPSHOT`.

**Comment by ennru** [comment]
Even `sbt publishLocal` fails with `java.lang.NoSuchMethodError: lmcoursier.Inputs$.configExtendsSeq(Lscala/collection/Seq;)Lscala/collection/Seq;` for me.
I'll try it harder tomorrow :-)

**Comment by eatkins** [comment]
That is all very interesting. Thanks for trying today. In the meantime, I will try and figure out why I get a newline in some cases and a carriage return in others.

**Comment by ennru** [comment]
The short answer is: it works for me with current develop but not with RC2

To make my local build of sbt work, I switched to sbt 1.3.13 to avoid the `NoSuchMethodError` above.

**Comment by eatkins** [comment]
Ok, great. It's still strange to me that it didn't work for you with RC2. With respect to publishing sbt, I'm wondering if you have any global plugins that possibly conflict with sbt.

**Comment by ennru** [comment]
> With respect to publishing sbt, I'm wondering if you have any global plugins that possibly conflict with sbt.

I commented out what I had there.

As this works with current `develop` I'm fine with closing this issue. Let me know if there is something more you'd like me to try out to understand what might have caused this.

**Comment by eatkins** [comment]
Ok. Thanks for the report and your help debugging!
