### ISSUE TITLE
Task progress listener

### ISSUE THREAD

**Issue by TheSultan** [sbt/sbt#592]
I'm trying to update the SBT TeamCity plugin to properly indicate compilation errors, which requires publishing teamcity events when compilation starts and completes, essentially wrap compilation with a pre and post event. I tried to wrap the compile task to do this with something like this

compile in Compile <<= (compile in Compile) mapR {
        case Inc(inc) => TeamCity.teamcityReport("compilationFinished", ("compiler", "sbt")); throw inc
        case Value(v) => TeamCity.teamcityReport("compilationFinished", ("compiler", "sbt")); v
      } dependsOn (teamcityCompilationStarted in Compile),
      teamcityCompilationStarted in Compile := TeamCity.teamcityReport("compilationStarted", ("compiler", "sbt")),

This works fine in some builds but for more complicated scenarios, the order doesn't seem to be guaranteed so compilationStarted is indicated long before compilation actually begins so a lot of unrelated messages are picked up as compilation errors.

I saw a feature you were working on mentioned here: http://stackoverflow.com/questions/12360974/sbt-before-after-hooks-for-a-task that seemed like it might expose these event hooks in a cleaner way, but that hasn't been merged back. Was wondering if you think this is the right approach and if so when you were planning on merging this back in, otherwise if you have any good suggestions on other approaches.

**Comment by harrah** [comment]
I have no immediate plans to work on it.  I will leave this open as an enhancement tracking that.

If your specific issue is getting the output just for compile, note that sbt has per-task logging and you can directly pull the logging for 'compile' after it has run.

**Comment by TheSultan** [comment]
Ok. The main issue is that I want to be able to have a pre and post task to publish events such as compile started, finished etc to teamcity (I'm extending the TeamCity plugin test reporting plugin, https://github.com/guardian/sbt-teamcity-test-reporting-plugin, to provide better support for things like compilation failures etc). I tried doing this with task dependencies but the pre-task runs before but not immediately before thereby confusing teamcity (we have a complicated build with many compile steps). Any other suggestions on that? I might be able to get away with something like extracting the compile output and publishing to TC but this feature of being able to have a task that is guaranteed to run immediately before another is very useful in a number of contexts.

**Comment by TheSultan** [comment]
Ping, any recommendation on how to achieve the above reliably?

**Comment by copumpkin** [comment]
I'd like to see this too (unsurprisingly)
