### ISSUE TITLE
sbt 1.4.0 'whatDependsOn' - java.lang.NoSuchMethodError: sbt.internal.LibraryManagement$.cachedUpdate

### ISSUE THREAD

**Issue by worace** [sbt/sbt#5933]
Hi, congrats on the sbt 1.4.0 release and thanks for all the effort that has gone into recent versions of this tool.

I am very excited to have the features from [sbt-dependency-graph](https://github.com/sbt/sbt-dependency-graph) built-in to sbt now since it's one of the plugins we rely on in many of our projects.

I ran into an error using the `whatDependsOn` command with the built-in version of that plugin. The error seems to have existed in some previous versions of sbt-dependency-graph, and I'm able to make it go away by re-enabling the external version of that plugin.

Here is an example project I set up to confirm the issue in an isolated environment: [worace/sbt-1.4-deps-graph-error](https://github.com/worace/sbt-1.4-deps-graph-error).

## steps

Made a new sbt project using sbt 1.4.0, and a single dependency, then tried to use the `whatDependsOn` command that used to be in sbt-dependency-graph but now is built in to sbt 1.4.0.

## problem

It crashes with

```
sbt:dep graph test> whatDependsOn io.circe circe-core 0.11.2
[error] stack trace is suppressed; run last ivyReport for the full output
[error] (ivyReport / update) java.lang.NoSuchMethodError: sbt.internal.LibraryManagement$.cachedUpdate(Lsbt/librarymanagement/DependencyResolution;Lsbt/librarymanagement/ModuleDescriptor;Lsbt/util/CacheStoreFactory;Ljava/lang/String;Lsbt/librarymanagement/UpdateConfiguration;Lscala/Function1;ZZZLsbt/librarymanagement/UnresolvedWarningConfiguration;Lsbt/librarymanagement/EvictionWarningOptions;ZLsbt/internal/librarymanagement/CompatibilityWarningOptions;Lsbt/util/Logger;)Lsbt/librarymanagement/UpdateReport;
``` 

## expectation

Should print something like

```
[info] com.example:dep-graph-test_2.11:0.1.0-SNAPSHOT [S]
[info]   +-io.circe:circe-core_2.11:0.11.2 [S]
```

## notes

[example project with reproduction](https://github.com/worace/sbt-1.4-deps-graph-error)

**Comment by conderls** [comment]
I also encountered exactly this issue with sbt1.3.13 and sbt1.4.1. failed to use `whatDependsOn`, `dependencyTree` and so on with same error described above.

**Comment by eed3si9n** [comment]
Full strength `DependencyTreePlugin` is enabled by putting the following to `project/plugins.sbt`:

```scala
addDependencyTreePlugin
```

`DependencyTreePlugin` bring in a significant amount of settings/tasks, which affects the load time, so this was a compromise we made. With the above, `whatDependsOn` works.

```scala
sbt:dep graph test> whatDependsOn io.circe circe-core_2.11 0.11.2
[info] io.circe:circe-core_2.11:0.11.2 [S]
[info]   +-com.example:dep-graph-test_2.11:0.1.0-SNAPSHOT [S]
[info]
[success] Total time: 0 s, completed Nov 15, 2020 3:14:11 PM
```

**Comment by worace** [comment]
@eed3si9n thanks for the explanation. I actually got a different error when trying that on the example project in the link above (https://github.com/worace/sbt-1.4-deps-graph-error/commit/f6dcd4cb0bb9585fd9de20c79ce639a8d66ac280):

```
[error] Some keys were defined with the same name but different types: 'whatDependsOn' (sbt.InputTask[java.lang.String], sbt.InputTask[Unit])
```

This is on a fresh clone of that repo after just making that change. Anything else I should look out for there?

**Comment by eed3si9n** [comment]
Looks like there's conflict on `whatDependsOn` key? sbt-dependency-graph can't be used together it seems.

**Comment by worace** [comment]
You mean if you have the external plugin enabled and also try to load the built-in one?

In that example I think that shouldn't be the case; it's just commented out in `plugins.sbt`:

```
 // addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.10.0-RC1")
```

**Comment by eed3si9n** [comment]
I can reopen and check again later using your repro project.

**Comment by eed3si9n** [comment]
Not sure if there was a bug here? I'm closing this for now.
