### ISSUE TITLE
"-Yrangepos" disappears from Test / scalacOptions when semanticdbEnabled is not `true` (was munit tests fail after upgrade to 1.4.0)

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#5934]
## steps

```scala
ThisBuild / scalaVersion := "2.12.13"

lazy val root = (project in file("."))
  .settings(
    name := "hello",
    Compile / scalacOptions += "-Yrangepos",
  )
```

Type the following in shell:

```
Test/scalacOptions
```

## problem

```
sbt:hello> show Test/scalacOptions
[info] *
```

## expectation

```
sbt:hello> show Test/scalacOptions
[info] * -Yrangepos
```

----

## steps

https://github.com/scalameta/munit/pull/213 upgrades to sbt 1.4.0.

## problem

https://github.com/scalameta/munit/runs/1207061695

```
==> X munit.AssertionsSuite.basic  0.018s munit.FailException: /home/runner/work/munit/munit/tests/shared/src/test/scala/munit/AssertionsSuite.scala:19
18:  val c: List[Int] = List(41)
19:  check(
20:    "basic",
diff assertion failed
=> Obtained
    """|Clues {
       |  : Int = 42
       |  : Long = 43
       |}
       |""".stripMargin
=> Diff (- obtained, + expected)
 Clues {
-  : Int = 42
-  : Long = 43
+  a: Int = 42
+  b: Long = 43
 }
    at munit.AssertionsSuite$$anonfun$check$1.apply$mcV$sp(AssertionsSuite.scala:13)
    at munit.AssertionsSuite$$anonfun$check$1.apply(AssertionsSuite.scala:11)
    at munit.AssertionsSuite$$anonfun$check$1.apply(AssertionsSuite.scala:11)
```

## expectation

It works as before.

**Comment by eed3si9n** [comment]
@SethTisue wrote:

> I'm seeing the same failures in the Scala community build, after moving from 1.4.0-RC2 to 1.4.0 final.

If it happened post RC2, then maybe something like https://github.com/sbt/sbt/pull/5898?

**Comment by gabro** [comment]
Updates from the discussion in scalameta/munit#313: the issue seems to be that `scalacOptions` are not propagated anymore from the `Compile` to the `Test` configuration.

The test failure was caused by the lack of `-Yrangepos` (it only failed on 2.12 and 2.11, because the flag is on by default in >= 2.13)

@eed3si9n any idea of what the root cause for this change might be?

**Comment by griggt** [comment]
Seems to be a result of this change in sbt/sbt#5887:

```diff
+  lazy val testSettings: Seq[Def.Setting[_]] = List(
+    // remove Compile targetRoot from Test config
+    semanticdbOptions --= targetRootOptions(
+      (Compile / scalaVersion).value,
+      (Compile / semanticdbTargetRoot).value
+    ),
+    // remove duplicated semanticdbOptions
+    scalacOptions --= (Compile / semanticdbOptions).value
+  )
+
```

**Comment by eed3si9n** [comment]
@griggt Thanks! 

I've updated the description of this issue with minimized repro of `"-Yrangepos"` disappearing.

**Comment by eed3si9n** [comment]
@gabro To unpack what Tom discovered, sbt does some special things to support the addition of SemanticDB by a built-in plugin called `SemanticdbPlugin` - https://github.com/sbt/sbt/blob/v1.4.7/main/src/main/scala/sbt/plugins/SemanticdbPlugin.scala, which is enabled by default as a plugin.

But SemanticDB itself is not enabled until `semanticdbEnabled` setting is set to `true`. When `semanticdbEnabled` is set to `true` it also sets `"-Yrangepos"` or other necessary flags on `Compile / scalacOptions`. In https://github.com/sbt/sbt/issues/5886 @adpi2 reported that `Test / scalacOptions` could have unwanted duplicated flags from `Compile / scalacOptions`. So #5887 added

```diff
+    // remove duplicated semanticdbOptions
+    scalacOptions --= (Compile / semanticdbOptions).value
```

Notice that it's subtracting `(Compile / semanticdbOptions).value` regardless of the `semanticdbEnabled` value. If `semanticdbEnabled` is set to `true` I am guessing that it would all work out, but when it's `false`, it's just subtracting `"-Yrangepos"`.

**Comment by eed3si9n** [comment]
Here's my PR for this - https://github.com/sbt/sbt/pull/6316
