### ISSUE TITLE
sbt 1.4.0: setting a custom xsbti.Reporter for compilerReporter leads to a MatchError

### ISSUE THREAD

**Issue by ritschwumm** [sbt/sbt#5935]
## steps

set `compilerReporter` to a custom implementation of `xsbti.Reporter`

## problem

because the custom Reporter is not an instance of BuildServerReporter,
https://github.com/sbt/sbt/blob/develop/main/src/main/scala/sbt/Defaults.scala#L2147 produces a MatchError.
https://github.com/sbt/sbt/blob/develop/main/src/main/scala/sbt/Defaults.scala#L2118 probably does, too

## expectation

using a custom reporter should work as before

## notes

i used this for a nasty hack where the custom reporter (after messaging my editor) forwarded all calls to the original reporter.
this cannot be made to work correctly any more, because `sendFinalReport` is not a part of the `Reporter` interface, and cannot even be overridden in a subclass of `BuildServerReporter` because it's `private[sbt]` there.

**Comment by eed3si9n** [comment]
@adpi2 Could you take a look at this plz? The reporter could potentially be changed by the build user or a plugin like https://github.com/Duhemm/sbt-errors-summary

**Comment by adpi2** [comment]
I don't really like the idea of making `BuildServerReporter` public because I know it is not stable yet and I don't want to expose too much of it.

But, at the same time, I would like to maintain the BSP support on custom reporter. So that the user can have its own reporter for the shell or file or whatever, without affecting the BSP diagnostics.

I will soon come up with an alternative solution.

**Comment by note** [comment]
For the context - it also makes https://github.com/Duhemm/sbt-errors-summary incompatible with sbt 1.4.0

**Comment by adpi2** [comment]
Thank you @note for pointing this out.

I have tested #5948 against https://github.com/Duhemm/sbt-errors-summary, it works like a charm.

**Comment by Duhemm** [comment]
@adpi2 Did you mean to link #5956?

**Comment by adpi2** [comment]
@Duhemm nope

The PR #5956 is a continuation of the PR #5948 that fixes the current issue. `sbt-errors-summary` should works on both of them.

**Comment by Duhemm** [comment]
> The PR #5956 is a continuation of the PR #5935 that fixes the current issue.

#5935 is not a PR, it's this very issue 😄 . Do you mean #5948 then?

Yeah I missed the link above. I'm pretty sure that's what you meant. Thanks!

**Comment by adpi2** [comment]
Oh right, my mistake! :smile: 
It is indeed #5948
