### ISSUE TITLE
sbt 1.4.0: prompt is missing in the jEdit console on ubuntu

### ISSUE THREAD

**Issue by ritschwumm** [sbt/sbt#5936]
## steps

run bin/sbt from inside the jEdit console

## problem

sbt  starts normally and runs until this log message
`[info] sbt server started at local`
but does not display a prompt at all

## expectation

sbt should display a prompt

## notes

typing commands does start them, command output is visible. just the prompt is missing.
jEdit reports `$TERM` to be `dumb`
this worked in sbt 1.3.3 and earlier.

**Comment by eed3si9n** [comment]
@ritschwumm Thanks for the report!

**Comment by ritschwumm** [comment]
that was quick. thanks a lot, @eatkins  and @eed3si9n !
