### ISSUE TITLE
sbt 1.4.0: "cancelable" is not working

### ISSUE THREAD

**Issue by unarist** [sbt/sbt#5940]
## steps

build.sbt

```
cancelable in Global := true
val foo = taskKey[Unit]("foo")
foo := {
  Thread.sleep(5000)
}
```

1. Run `sbt`
2. Enter `foo`
3. Hit Ctrl-C during task execution

## problem

sbt waits completion of the task execution (i.e. waits 5 seconds for this case), then exits sbt shell.

```
sbt:test> foo
   (hit Ctrl-C)
[success] Total time: 5 s, completed 2020/10/06 14:15:49
sbt:test>
   (then exits sbt shell)
```

(The last line is printed due to sbt.bat on Windows)

## expectation

sbt cancels task execution and returns to sbt prompt.

Example (sbt 1.3.13):

```
sbt:test> foo
   (hit Ctrl-C)
[warn] Canceling execution...
[error] Total time: 1 s, completed 2020/10/06 14:13:37
sbt:test>   
```

**Comment by eed3si9n** [comment]
@unarist Thanks for the report.

**Comment by eatkins** [comment]
The regression was introduced in bb8b9a1c997ef472cd8f321abc273aa7c128d115. Hopefully it won't be too difficult to fix.

**Comment by eatkins** [comment]
#5947
