### ISSUE TITLE
sbt-1.4.0 not available on homebrew

### ISSUE THREAD

**Issue by francisdb** [sbt/sbt#5941]
Since homebrew is promoted on the download page I expect the update of https://github.com/Homebrew/homebrew-core/blob/master/Formula/sbt.rb to be part of the release process?

**Comment by eed3si9n** [comment]
I keep Homebrew info on download page because many ppl use it, but I don't personally update it any more since they've added the weird JDK 13 thing. I do update SDKMAN myself.

**Comment by eed3si9n** [comment]
For the record, anyone can send a pull request to update Brew recipe by following https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md

```bash
$ shasum -a 256 ~/Downloads/sbt-1.3.8.tgz
27b2ed49758011fefc1bd05e1f4156544d60673e082277186fdd33b6f55d995d  

$ brew bump-formula-pr --url https://github.com/sbt/sbt/releases/download/v1.3.8/sbt-1.3.8.tgz --sha256 27b2ed49758011fefc1bd05e1f4156544d60673e082277186fdd33b6f55d995d sbt
```

**Comment by francisdb** [comment]
thanks for the clear info, switching to sdkman
