### ISSUE TITLE
exclude() not working on transitive dependency

### ISSUE THREAD

**Issue by daschl** [sbt/sbt#595]
Hi,

we ran into an issue when using a java dependency that uses netty 3.5.5 and play framework which uses 3.5.0. We tried to remedy this issue by excluding 3.5.5 from loading, but the setting is somehow ignored:

For example, when I do this:  

```
"couchbase" % "couchbase-client" % "1.1-dp4" exclude("io.netty", "netty")
```

then in the play dependency list netty still shows up with 3.5.5.

The fun thing is now, when I basically "invert" the whole thing like this (so to say include everything by hand except netty) - it works!:

```
    val appDependencies = Seq(
      ("couchbase" % "couchbase-client" % "1.1-dp4" notTransitive())
        .exclude("org.codehaus.jettison", "jettison")
        .exclude("commons-codec", "commons-codec")
        .exclude("spy", "spymemcached")
        .exclude("org.apache.httpcomponents", "httpcore")
        .exclude("org.apache.httpcomponents", "httpcore-nio")
    )
```

The dependency is now correctly bundled as 3.5.0.

Could this be a bug in sbt (or even in play, sorry I'm not able to distinguish it clearly) or am I missing something obvious in here?

Just to be complete if someone wants to reproduce it: the couchbase library is available from here: 

```
resolvers += "Couchbase Maven Repository" at "http://files.couchbase.com/maven2" 
```

Thank you very much!

**Comment by harrah** [comment]
Please provide a self contained example that does not depend on Play.
