### ISSUE TITLE
Writing SBT output to file ends up with terminal color stuff in file

### ISSUE THREAD

**Issue by soc** [sbt/sbt#5965]
(As requested by @eed3si9n in https://twitter.com/eed3si9n/status/1313125156559171591)

## steps

Run a application with `sbt run` and pipe it into a file: `sbt run > some_file`

## problem

In 1.4.0 the file contains terminal color stuff:

```
[info] welcome to sbt 1.4.0 (Ubuntu Java 11.0.8)
[0J[info] loading settings for project global-plugins from gpg.sbt ...
[0J[info] loading global plugins from /home/soc/.sbt/1.0/plugins
[0J[info] loading project definition from /home/soc/code/module-infos/project
[0J[info] loading settings for project root from build.sbt ...
[0J[info] set current project to module-infos (in build file:/home/soc/code/module-infos/)
[0J[info] running mods.Main
[0JBLA                                    DONE[0J
[0JBLI                         DONE[0J
[0JBLUBBB                      TODO[0J
```

## expectation

The file does not contain terminal color stuff, like in 1.3.x.

## notes

The problem can be worked around with `--no-colors`.

**Comment by eed3si9n** [comment]
Ethan fixed this in https://github.com/sbt/sbt/pull/5966

**Comment by soc** [comment]
Thanks!
