### ISSUE TITLE
Lombok can't load lombok.config because it can't handle sbt's VirtualFile

### ISSUE THREAD

**Issue by mkurz** [sbt/sbt#5968]
I am upgrading a Play Java project to sbt 1.4. That Java project uses [Lombok](https://projectlombok.org/).
Basically, Lombok works fine with sbt 1.4, however it's [optional configuration system](https://projectlombok.org/features/configuration) doesn't.

Until sbt 1.3.x it was possible to configure how various Lombok annotations should behave by putting a `lombok.config` into the root folder of a (sbt) project (or into a specific package folder for package specific behaviour). Starting with sbt 1.4 such a `lombok.config` can't be read by Lombok anymore, because Lombok does not support the new sbt VirtualFile concept.

I did some debugging and it turns out that until sbt 1.3 the files passed to Lombok where actual "real" files, like `file://home/mkurz/some_project/app/some_package/MyClass.java`. Therefore lombok was able to find the `lombok.config` which, based on my example, would be `file://home/mkurz/some_project/lombok.config`.

However with sbt 1.4, what Lombok sees are the virtual files like `vf://tmp/$%7BBASE%7D/app/some_package/MyClass.java`. The 
problem is, as said, that Lombok just can't handle virtual files (`vf://`), it only can operate with actual "real" files.
The relevant code in Lombok [can be found here](https://github.com/rzwitserloot/lombok/blob/v1.18.14/src/core/lombok/core/configuration/FileSystemSourceCache.java#L67-L87):
```java
URI uri = javaFile.normalize();
if (!uri.isAbsolute()) uri = URI.create("file:" + uri.toString());

try {
	File file = new File(uri);
	if (!file.exists()) throw new IllegalArgumentException("File does not exist: " + uri);
	File directory = file.isDirectory() ? file : file.getParentFile();
	if (directory != null) result = ConfigurationFile.forDirectory(directory);
	uriCache.put(javaFile, result);
} catch (IllegalArgumentException e) {
	// This means that the file as passed is not actually a file at all, and some exotic path system is involved.
	// examples: sourcecontrol://jazz stuff, or an actual relative path (uri.isAbsolute() is completely different, that checks presence of schema!),
	// or it's eclipse trying to parse a snippet, which has "/Foo.java" as uri.
	// At some point it might be worth investigating abstracting away the notion of "I can read lombok.config if present in
	// current context, and I can give you may parent context", using ResourcesPlugin.getWorkspace().getRoot().findFilesForLocationURI(javaFile) as basis.
	
	// For now, we just carry on as if there is no lombok.config. (intentional fallthrough)
} catch (Exception e) {
	// Especially for eclipse's sake, exceptions here make eclipse borderline unusable, so let's play nice.
	ProblemReporter.error("Can't find absolute path of file being compiled: " + javaFile, e);
}
```

The problem here is the `file.exists()` check, because Java of course does not have a clue how to handle `vf://...`, nor does the "real" file `/tmp/$%7BBASE%7D/lombok.config` even exist on the filesystem. But anyway, the lengthy comment in the above code snippet says it all: The `lombok.config` just won't be loaded.

Now my questions are:
- In sbt 1.4, is it possible to somehow make Lombok see "real" files (`file:...`) instead of virtual files (`vf:...`)?
  - Or would it be possible to somehow plug in sbt's virtual file implementation into Lombok, so it transparently can operate on such virtual files? I know in Java it's possible to create own File System Providers, so file operations (like `File.exists(...)`) operate transparently on different Java "file systems". How is sbt's virtual file implemented?
- Is it possible to somehow disable the Virtual file mechanism and just operate with normal files, like it was the case in sbt 1.3 and before?
- Is it possible to exclude specific files from the "virtual file/path system"?

Of course you could say, this is not a bug in sbt, but Lombok should either be able to
- handle other file/path systems (via some adapter code or plugin system or similar to clue things together)
- configure the location of a main `lombok.config` via e.g. a system property (e.g. `-Dlombokconfig=/some/path/lombog.config`) which currently is not possible. Also, Lombok allows to create multiple `lombok.config`s for package specific settings, however such a system property would only work for a single config file, that one-and-only config would then bubble down to all packages (which for most people probably would be enough).

Actually I'm thinking about to provide a patch to Lombok for the system property solution, because that would be enough for me, however if there is an easier way be tweaking sbt, this would also be nice.

What do you think?

**Comment by eed3si9n** [comment]
Could you try `ThisBuild / rootPaths := Nil` and see if that would work?

**Comment by mkurz** [comment]
Setting it to `Nil` does not work:
```
$ set ThisBuild / rootPaths := Nil
<set>:1: error: type mismatch;
 found   : scala.collection.immutable.Nil.type
 required: Map[String,java.nio.file.Path]
ThisBuild / rootPaths := Nil
                         ^
[error] Type error in expression
```

That's why I set it to `Map.empty`. However that did not solve the problem. `lombok.config` still can't be loaded.

I debugged and this is how the path look like now:
```
vf://tmp/home/mkurz/some_project/app/some_package/MyClass.java
```
So there is still the `vf:` prefix, followed by `/tmp`, followed by the absolute path of a file.
For me it looks strange that there is `/tmp` + absolute path... Is that intentional?

**Comment by eed3si9n** [comment]
Another direction to try might be setting `javaHome` setting or modifying `compilers` setting to nudge Zinc into using forked javac (https://github.com/sbt/zinc/blob/develop/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/javac/JavaCompiler.scala). That should use the traditional file (for now). I guess in the long-run, we should provide an opt-out for vf.

**Comment by eed3si9n** [comment]
> For me it looks strange that there is `/tmp` + absolute path... Is that intentional?

https://github.com/sbt/zinc/blob/5a1a9d2cd1119b8d9300fc489ec6bbaa31e4388f/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/javac/LocalJava.scala#L190

I think I added `/tmp` in the URI to denote that it is intentionally VirtualFile, and not get confused with real ones.

**Comment by mkurz** [comment]
> Another direction to try might be setting `javaHome` setting

This works! However I don't like the solution because I would need to introduce hardcoded paths to JDKs in `build.sbt`...

> or modifying `compilers` setting to nudge Zinc into using forked javac (https://github.com/sbt/zinc/blob/develop/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/javac/JavaCompiler.scala). 

How does that work? Is this just a one-liner setting like `compilers := ...`? I think I need your help here...

> I guess in the long-run, we should provide an opt-out for vf.

Yeah, that would be nice.

**Comment by domdorn** [comment]
@eed3si9n  could you please elaborate what the proposed workaround is (e.g. with a small sample)? 
This is currently blocking me from upgrading from sbt 1.3.12 to 1.4.5.

**Comment by eed3si9n** [comment]
I haven't tested it but something like this?

```scala
import sbt.internal.inc.javac

ThisBuild / scalaVersion     := "2.13.3"
ThisBuild / version          := "0.1.0-SNAPSHOT"
ThisBuild / organization     := "com.example"

lazy val root = (project in file("."))
  .settings(
    name := "forktest",
    compilers := compilers.value.withJavaTools(
      javac.JavaTools(javac.JavaCompiler.fork(), javac.Javadoc.fork())),
  )
```

**Comment by mkurz** [comment]
Servus @domdorn,

the only workaround that worked for me was to hardcode the path to the jdk. So in your `build.sbt`:
```scala
javaHome := Some(file("/path/to/your/jdk"))
```
Looks like disables sbt's virtual file system.
It's not nice and probably won't work because different environments have different paths... Therefore I am just waiting for the fix in lombok itself (AFAIK I read somewhere a new Lombok release should be around the corner this week?!? Not 100% sure)

**Comment by mkurz** [comment]
@eed3si9n I am closing this pull request, because Lombok fixed this issue by adding support for sbt's virtual file system, see https://github.com/rzwitserloot/lombok/commit/e1f82ac4d132769cfc272dccfc916aeba7181718 and also https://github.com/rzwitserloot/lombok/pull/2668
So we just have to wait for the next Lombok release (I can confirm the fixes are working)

@domdorn What you can do of course as well is to compile Lombok from its current master and put that file into the `lib` folder until there is a new release... The edge release (https://projectlombok.org/download-edge) unfortunately does not yet contain my sbt subproject fix (meaning if in your project Lombok is NOT used in a sub-project the edge release should already work for you)

**Comment by domdorn** [comment]
hmm.. unfortunatelly I have lombok in submodules AND I have a different environment on my local machine (mac) and on my CI server (jenkins@linux), so hardcoding a JDK is not an option.. guess I'll stick with sbt 1.3.12 for now.

**Comment by mkurz** [comment]
@domdorn If you trust me, here is the latest lombok jar I just compiled from current Lombok master (commit [f17dd036](https://github.com/rzwitserloot/lombok/tree/f17dd036384242971546bc443749ad527b8cd21c)) containing my subproject fix:
https://drive.google.com/file/d/1sXBzeIfv0x4XB_-BuSjaSF7czDagyg3I/view


Just put that in your sub-projects' `lib` folder and remove the lombok dependency from your `build.sbt`
Would also be good if someone else tests the fixes...

You can of course also compile lombok yourself by running `ant dist`
I am using 
```
Apache Ant(TM) version 1.10.8 compiled on May 10 2020
openjdk version "11.0.9.1" 2020-11-04
```
and that works for me.
