### ISSUE TITLE
sbt 1.4.0 Scala 2.13.{2,3} console exits on ctrl-d on nonempty line

### ISSUE THREAD

**Issue by klaeufer** [sbt/sbt#5974]
## steps

1. `$ sbt console`
2. enter one or more characters and type ctrl-d 

## problem

Scala REPL exits

## expectation

at EOL of nonempty input line: no effect
not at EOL of nonempty input line: delete character under cursor
on empty input line: exit REPL

## notes

sbt 1.4.0 launcher (via SDKMAN!)
project/build.properties: sbt.version=1.4.0
build.sbt: scalaVersion := "2.13.2" // or .3 BUT NOT .1 or earlier

[info] welcome to sbt 1.4.0 (AdoptOpenJDK Java 11.0.8)

This does not happen for earlier releases of sbt or Scala, or when invoking the Scala REPL directly.

**Comment by eatkins** [comment]
Thanks for the report! Fixed in #5975.

**Comment by klaeufer** [comment]
Thank you for the prompt action!
