### ISSUE TITLE
Invoking an alias should display the original command

### ISSUE THREAD

**Issue by OlegYch** [sbt/sbt#598]
E.g. if i have
alias gip= idea with-sources=yes sbt-classifiers

and invoke

> gip

it should display

> idea with-sources=yes sbt-classifiers

Otherwise it might be confusing if alias has an error
 $   gip
[error] Expected whitespace character
[error] Not a valid project ID: gip
[error] Not a valid configuration: gip
[error] Not a valid key: gip (similar: skip)
[error] gip
[error]    ^

**Comment by harrah** [comment]
This is reasonable, but requires some changes to the underlying parser combinator library.  The parser library automatically generates errors based on the real input and there would have to be special support for switching the input context or something.  I won't get to this soon, but can certainly help guide a pull request.
