### ISSUE TITLE
OOM due to SBT 1.4.+ upgrade in CI build 

### ISSUE THREAD

**Issue by Baccata** [sbt/sbt#5992]
## problem: SBT upgrade leads to CI build crashing 

* The [commit](https://github.com/disneystreaming/weaver-test/pull/111#partial-pull-merging)
* The [failed build](https://cloud.drone.io/disneystreaming/weaver-test/352)
* The SBT_OPTS [ci settings](https://github.com/disneystreaming/weaver-test/blob/master/.drone.yml#L14) 

NB : an OOM had already been witnessed in a previous version of this project, which had lead to the introduction of these SBT_OPTS, fixing the problem.

**Comment by eatkins** [comment]
Thanks for the report! I think I tracked down the memory leak in #6001.

**Comment by eatkins** [comment]
Fixed in #6001
