### ISSUE TITLE
BSP server logs to stdout

### ISSUE THREAD

**Issue by jastice** [sbt/sbt#5993]
The BSP server process started via `java -cp sbt-launch.jar xsbt.boot.Boot -bsp` writes logging output to stdout.
As per [server discovery protocol](https://build-server-protocol.github.io/docs/server-discovery.html#build-tool-commands-to-start-bsp-servers) only the json-rpc data should be written to stdout, any logging should go to stderr.

This behavior causes problems when clients start the server through the command generated in the connection file.

## steps

1. generate BSP connection file 
2. ensure sbt server process is closed
3. refresh the project from IntelliJ

## problem

IntelliJ runs the connection command, but BSP commands time out, because the log output can't be parsed as JSON-RPC message.

## notes

Workaround: start sbt server before attempting to connect. This will bypass the initial log messages. However, sending an erroneous request such as `{}` will also trigger log messages on stdout besides the json-rpc error response.

**Comment by jastice** [comment]
Update: The importing problem doesn't seem to appear with sbt 1.4.1 - so my hypothesis as to the reason might be wrong. However the output is still expected to go to stderr

**Comment by ckipp01** [comment]
I'm glad I actually stumbled on this. Reading this, I believe I hit on the same problem, which caused me to actual have to special case sbt here https://github.com/scalameta/metals/pull/2154/files#diff-229a555759af5a899d47a58df15699eacbf966bf5b976cf3cefd884670379503R77-R86 and start up sbt _before_ making the bsp connect since it wasn't connecting correctly due to header context exceptions, and then times out. I wonder if we were hitting on the same thing with this 🤔

**Comment by jastice** [comment]
@ckipp01 I assume it would be the same issue since we're both using bsp4j. Does sbt 1.4.1 also fix the problem for you?

**Comment by ckipp01** [comment]
> @ckipp01 I assume it would be the same issue since we're both using bsp4j. Does sbt 1.4.1 also fix the problem for you?

Yes, same as you mentioned. Just checked, and with 1.4.1, bsp discovery works as expected for me without having to start sbt or anything before hand.

**Comment by ckipp01** [comment]
Following up on this, we're seeing this pop up again with 1.4.3 where the first connection attempt via BSP discovery fails almost every time.

EDIT: _Read Chris, read_... I see that there is a pr open for this now 👍

**Comment by adpi2** [comment]
Thanks @ckipp01 for reporting this on `1.4.3`.

I really don't know what happened between `1.4.2` and `1.4.3`.

But there has ever been something wrong in the way the server was started by `bsp -sbt`. #6097 fixes it and it should prevent this issue to happen again. Also it fixes #6097.
