### ISSUE TITLE
scala-library.jar not copied to lib_managed (0.10.0)

### ISSUE THREAD

**Issue by robinst** [sbt/sbt#60]
I have an explicit dependency on scala-library.jar in my build.sbt and have set autoScalaLibrary to true. But the scala-library.jar is not copied to lib_managed. (It's a mixed JRuby/Scala project, scala-library.jar is needed for deployment.)

In sbt 0.7.5, I had this in my project definition: override def filterScalaJars = false

Is there an equivalent in 0.10? Or another way to accomplish the same?

**Comment by harrah** [comment]
Please use the mailing list for questions.  Thanks!

http://groups.google.com/group/simple-build-tool
