### ISSUE TITLE
Undefined Setting Key externalDepedencyClasspath if JVM Plugin is disabled and products is set to nil

### ISSUE THREAD

**Issue by albuch** [sbt/sbt#6009]
## steps

Given the following build.sbt with an implicit root project:

```scala
val foo = project
   .disablePlugins(sbt.plugins.JvmPlugin)
   .settings(
       Compile / products := Nil
   )

lazy val myTask = taskKey[Unit]("Should work")
myTask := (foo / Compile / externalDependencyClasspath).value foreach println
```
## problem

when trying to execute the task with `sbt myTask` I get an error that the setting externalDependencyClasspath is not defined:

```
[error] Reference to undefined setting:
[error]
[error]   foo / Compile / externalDependencyClasspath from myTask
```

Once I either remove `Compile / products := Nil` or enable the JvmPlugin the task works as expected. I can't seem to find the relationship between `products` and `externalDependencyClasspath` in the sbt source code that could explain this behavior.

## expectation

The task should not fail.

## notes

My use case comes from a plugin that tries to get all dependencies from aggregate projects when executed on the root project and it fails for this specifically configured sub-project.
I tested this with sbt 1.4.0 and 1.2.8.

**Comment by eed3si9n** [comment]
For the record, `externalDependencyClasspath` is introduced as part of `configSettings`, so I don't think it should work if you've disabled `JvmPlugin`.

https://github.com/sbt/sbt/blob/3536959c311d4922bc0803f51a5a0bca57440719/main/src/main/scala/sbt/Defaults.scala#L2464-L2478

> Once I either remove `Compile / products := Nil`  .... the task works as expected.

I can't reproduce this. With or without `Compile / products := Nil`, I correctly get 

```
[error] Reference to undefined setting:
[error]
[error]   foo / Compile / externalDependencyClasspath from myTask (/private/tmp/foo/build.sbt:8)
[error]
[error] Use 'last' for the full log.
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```
