### ISSUE TITLE
use eclipse update site resolvers...

### ISSUE THREAD

**Issue by justjoheinz** [sbt/sbt#601]
Ivy supports using eclipse (p2) update sites as repositories and it would be nice if you could add this feature to sbt.

**Comment by harrah** [comment]
I know little about p2 update sites and Ivy support for them, so the more information you can provide the better.  If it is just a matter of providing an sbt wrapper around a specific Ivy resolver, consider submitting a pull request.

**Comment by dwijnand** [comment]
I feel like the need for using eclipse (p2) update sites as repositories is quite niche. As such perhaps it would be best (if possible) to explore how to add this support in a plugin first.
