### ISSUE TITLE
sbt 1.4.1: watchBeforeCommand is no longer executed in ~compile

### ISSUE THREAD

**Issue by ritschwumm** [sbt/sbt#6015]
## steps

create a minimal project
```
// build.sbt
organization	:= "de.test"
version			:= "0.0.1"
name			:= "repro"
scalaVersion	:= "2.13.3"

watchBeforeCommand	:= { () =>
	println("WATCHBEFORE")
	watchBeforeCommand.value()
}
```
```
# project/build.properties
sbt.version=1.4.1
```
```
// src/main/Repro.scala
package repro

object Repro {
	def main(args:Array[String]):Unit	= {
		println("hallo")
	}
}
```

run `~sbt compile` and change the `print` statement in `object Repro`

## problem

`WATCHBEFORE` is not printed to the console before compilation starts

## expectation

`WATCHBEFORE` is printed to the console before compilation starts, this worked in sbt 1.3.13

**Comment by eatkins** [comment]
Thanks for the report! This was indeed a regression that should be fixed by #6018.
