### ISSUE TITLE
Migrate from travis-ci to GitHub Action

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#6031]
https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom?e=%5BUNIQID%5D

> In an effort to ensure that all of our users - whether you build open-source, public or private repositories - receive regular feature updates, security patches and UX/UI enhancements, we are announcing that travis-ci.org will be officially closed down completely on December 31st, 2020, allowing us to focus all our efforts on bringing new features and fixes to travis-ci.com and all of our awesome users like yourself on the travis-ci.com domain.

**Comment by eed3si9n** [comment]
https://twitter.com/headius/status/1320870340634005512

> Anyone seeing travisci take much longer to run jobs lately? In the past week or two, even if I have no other jobs running, even off peak, I'm seeing wait times of hours to queue even single jobs. It's like they massively cut back the number of available servers.

... 

https://twitter.com/ButlerPCnet/status/1320878768030928896

> Actually... I guess this is just the normal backlog now. Looking back to the week and month graph, it's clear they reduced capacity greatly, and are just depending on the job queue clearing "overnight" as devs go home Disappointed but relieved face

https://www.traviscistatus.com/#week

<img width="868" alt="Travis_CI_Status" src="https://user-images.githubusercontent.com/184683/97241886-c622ce80-17c8-11eb-9e75-207694645127.png">

https://www.traviscistatus.com/#month

<img width="863" alt="month" src="https://user-images.githubusercontent.com/184683/97242025-2ca7ec80-17c9-11eb-8fc6-2894b7baa65a.png">

**Comment by eed3si9n** [comment]
Looks like on October 22nd Travis CI halved the capacity to 593 jobs, which could explain hours of queuing.
Even at 9pm Eastern there are still like 3633 jobs on backlog.

**Comment by eed3si9n** [comment]
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

> We love our OSS teams who choose to build using TravisCI and we fully want to support that community. However, recently we have encountered significant abuse of the intention of this offering. Abusers have been tying up our build queues and causing performance reductions for everyone. In order to bring the rules back to fair playing grounds, we are implementing some changes for our public build repositories.
>
> - For those of you who have been building on public repositories (on travis-ci.com, with no paid subscription), we will upgrade you to our trial (free) plan with a 10K credit allotment (which allows around 1000 minutes in a Linux environment).

They've give open source accounts a free lifetime of 1000 Linux minutes (= 200 macOS minutes). We'd go through that in a matter of days since a single CI job takes about 100 minutes.

**Comment by eatkins** [comment]
I guess we shouldn't be surprised by this. Travis ci was acquired by a private equity firm about two years ago. I'm almost surprised it took this long for them to kill it for oss.
