### ISSUE TITLE
Continuous compilation seemingly caused by source generation during BSP connection

### ISSUE THREAD

**Issue by ckipp01** [sbt/sbt#6037]
## steps

This is really only happening in the Metals code base and I can't seem to get a minimal reproduction. So it could be potentially something we are doing wrong in our definition, but it does happen to both me and @tgodzik, and only when using sbt via BSP.

Using sbt 1.4.1, during a BSP connection, we have a module that enables `sbt-jmh`, and when the initial BSP connection is made and compilation is happening, it gets stuck and goes into a continuous loop. The logs look like this:

```
2020.10.30 21:38:23 INFO  running org.openjdk.jmh.generators.bytecode.JmhBytecodeGenerator /Users/ckipp/Documents/scala-workspace/scalameta-org/metals/metals-bench/target/scala-2.12/classes /Users/ckipp/Documents/scala-workspace/scalameta-org/metals/metals-bench/target/scala-2.12/src_managed/jmh /Users/ckipp/Documents/scala-workspace/scalameta-org/metals/metals-bench/target/scala-2.12/resource_managed/jmh default
2020.10.30 21:38:23 INFO  compiling bench-jmh
2020.10.30 21:38:23 INFO  time: compiled bench-jmh in 11ms
2020.10.30 21:38:23 INFO  Processing
2020.10.30 21:38:23 INFO  Processing
2020.10.30 21:38:24 INFO  compiling interfaces
2020.10.30 21:38:24 INFO  compiling input
2020.10.30 21:38:24 INFO  time: compiled interfaces in 6ms
2020.10.30 21:38:24 INFO  time: compiled input in 23ms
2020.10.30 21:38:24 INFO  compiling mtags
2020.10.30 21:38:24 INFO  compiling input-test
2020.10.30 21:38:24 INFO  time: compiled input-test in 589μs
2020.10.30 21:38:24 INFO  time: compiled mtags in 0.17s
2020.10.30 21:38:24 INFO  compiling mtest
2020.10.30 21:38:24 INFO  compiling metals
2020.10.30 21:38:24 INFO  time: compiled mtest in 4ms
2020.10.30 21:38:24 INFO  time: compiled metals in 0.19s
2020.10.30 21:38:24 INFO  compiling unit
2020.10.30 21:38:24 INFO  time: compiled unit in 69ms
2020.10.30 21:38:24 INFO  compiling bench
2020.10.30 21:38:24 INFO  time: compiled bench in 13ms
2020.10.30 21:38:24 INFO  running org.openjdk.jmh.generators.bytecode.JmhBytecodeGenerator /Users/ckipp/Documents/scala-workspace/scalameta-org/metals/metals-bench/target/scala-2.12/classes /Users/ckipp/Documents/scala-workspace/scalameta-org/metals/metals-bench/target/scala-2.12/src_managed/jmh /Users/ckipp/Documents/scala-workspace/scalameta-org/metals/metals-bench/target/scala-2.12/resource_managed/jmh default
```
In a small repo, the same run seems to happen, but it only happens 2-3 times and then stops. However, when in Metals it just continues to go crazy:

![2020-10-30 21 53 28](https://user-images.githubusercontent.com/13974112/97756292-ee793880-1afa-11eb-914f-5c2051b93bbf.gif)

We have the plugin enabled here:

https://github.com/scalameta/metals/blob/089ce4289266c206a868e14245fb851144057f81/build.sbt#L649-L665

Any idea as to what might be going on here causing this?

**Comment by eed3si9n** [comment]
I haven't checked but I wonder if the loops looks as follows:

1. Metals connects with sbt's BSP server
2. Metals queries for bench-jmh target's sources
3. sbt tries to enumerate sources, and it generates `BuildInfo.scala`
4. Metals issues compile task
5. sbt compiles bench-jmh, which also triggers `JmhBytecodeGenerator`
6. Metals detects this as new resource being added, and goes to step 2

/cc @adpi2

**Comment by adpi2** [comment]
As @eed3si9n puts it, I think the problem is that `sbt-jmh` generates new sources at each compilation.

What I see from the traces is:

1. Metals sends a `compileRequest` on `bench-jmh`
2. sbt replies that `bench-jmh` is compiled successfully
3. Metals sends a `scalaMainClasses` request on `bench-jmh`
4. sbt runs `discoveredMainClasses` that generates new sources
5. sbt replies that `bench-jmh` contains no Main classes
6. Metals detects the new generated sources and goes to step 1

I don't think there is much we can do on sbt side. One solution would be to make `sbt-jmh` truly incremental if possible: avoid generating new sources at each compilation. Another solution is to deactivate BSP on `bench-jmh`:
```
lazy val bench = project
  .settings(
     Jmh / bspEnabled := false
  )
```
By doing so, the `bench-jmh` target will not be discovered.

**Comment by adpi2** [comment]
`Jmh / bspEnabled := false` does not deactivate BSP on the `bench` project, but only on the `Jmh` configuration of the `bench` project. In other words, Metals will not trigger the `bench / Jmh / compile` task, but it will trigger `bench / Compile / compile` and `bench / Test / compile`.

**Comment by ckipp01** [comment]
> `Jmh / bspEnabled := false` does not deactivate BSP on the bench project, but only on the Jmh configuration of the bench project. 

Alright, that makese sense and does indeed seem to fix the problem. Thanks!

> I don't think there is much we can do on sbt side. One solution would be to make sbt-jmh truly incremental if possible: avoid generating new sources at each compilation. Another solution is to deactivate BSP on bench-jmh:

I know this is probably guesswork, but how widespread among different plugins do you think this may be? I can see this behavior being really difficult to troubleshoot for Metals + sbt BSP users that don't really get what's going on.

**Comment by tgodzik** [comment]
The alternative as we discussed with @adpi2 is that because:

`The buildTarget/sources response tells if a file is generated or not. `

we could try to not run compilation on changes to those files.

**Comment by ckipp01** [comment]
> The alternative as we discussed with @adpi2 is that because:

> The buildTarget/sources response tells if a file is generated or not. we could try to not run compilation on changes to those files.

🤔 yea that could work. However, would there be any potential cases where after that generation we _would_ want to run a compilation after those are generated?

**Comment by ckipp01** [comment]
I need to look closer at how the order of this happens, but basically my concern would be

1. Compile request sent
2. `BuildInfo` is being used, so the `BuildInfo.scala` comes back as a generated source
3. Since it was generated, we don't trigger another compilation on it, and then we potentially have broken code that is trying to access `BuildInfo`? Unless the compilation in step 2 took into account the generates sources.

**Comment by tgodzik** [comment]
> yea that could work. However, would there be any potential cases where after that generation we would want to run a compilation after those are generated?

Shouldn't sbt compile `BuildInfo.scala` when it first generates it? We never really explicitly call source generation, it's all compiled together, so there should be no need to recompile on changes to any generated files.

**Comment by ckipp01** [comment]
> Shouldn't sbt compile BuildInfo.scala when it first generates it? We never really explicitly call source generation, it's all compiled together, so there should be no need to recompile on changes to any generated files.

Alright, just checking. I'll create an issue in the Metals repo outlining this all, and then close this here.

Closing this and opened up https://github.com/scalameta/metals/issues/2183 Thanks for the help everyone!
