### ISSUE TITLE
No credentials used when publishing to HTTP Nexus repository with artifact added

### ISSUE THREAD

**Issue by amorfis** [sbt/sbt#6038]
## steps

1. Add artifact by `addArtifact` command
2. Add some repository (Nexus in my case) that needs credentials for publishing
3. Try to publish the project

## problem

Publishing fails, and from sniffing the packets with Wireshark I can see that credentials are not used when artifact is added. When `addArtifact` setting is removed, credentials are sent and publishing works.

## expectation

Default and added artifact should be published

## notes

There is repo on github with example showing the problem: https://github.com/amorfis/sbt-assembly-publish-error It's necessary to enter repo address and credentials in `project/Nexus.scala` file.

EDIT: 
Tested on Nexus repository not protected with SSL. When testing with HTTPS, publish with artifact works as expected

**Comment by eed3si9n** [comment]
Thanks for the report!

**Comment by eed3si9n** [comment]
Potentially related is https://github.com/sbt/sbt/pull/5593.

Looks like this checks for any explicit artifacts and rejects HTTP

```scala
  private[sbt] def errorInsecureProtocolInModules(mods: Seq[ModuleID], log: Logger): Unit = {
    val artifacts = mods.flatMap(_.explicitArtifacts.toSeq)
    val bad = !artifacts.forall(!_.validateProtocol(log))
    if (bad) {
      sys.error("insecure protocol is unsupported")
    }
  }
```

This should print out the error message `"insecure protocol is unsupported"`. Did you see that?

**Comment by amorfis** [comment]
No, I have no message like this

**Comment by cchepelov** [comment]
This might be related to #5200 . @amorfis, can you reproduce this with sbt 1.4.7?

**Comment by eed3si9n** [comment]
Closing this for now since #5200 might have fixed this. Let us know if this issue is still relevant.
