### ISSUE TITLE
add task to compile selected files with custom options

### ISSUE THREAD

**Issue by retronym** [sbt/sbt#604]
Along the lines of:

https://github.com/retronym/scratch/blob/master/20111022/project/CompileQuickPlugin.scala

**Comment by Blaisorblade** [comment]
Until this gets properly done, I'm trying to use your original task. Of course it didn't compile any more, but I managed to make it minimally work again [1]. Here's my result, for 0.12.0:

https://github.com/ps-mr/LinqOnSteroids/commit/1c9deb1059ae20a22629199244d6a41112df8d0d

I'm submitting this, hoping that it either helps, or that you save me from the horrible mistakes I made.

[1]

```
> compile
[info] Compiling 1 Scala source to /Users/pgiarrusso/Documents/Research/Sorgenti/linqonsteroids/target/scala-2.10/classes...
[success] Total time: 6 s, completed Nov 26, 2012 9:27:15 AM
> set scalacOptions in compileQuick += "-Xprint:typer" 
[info] Reapplying settings...
[info] Set current project to LinqOnSteroids (in build file:/Users/pgiarrusso/Documents/Research/Sorgenti/linqonsteroids/)
> compile-quick src/main/scala/ivm/tests/Debug.scala
[[syntax trees at end of                     typer]] // Debug.scala
package ivm.tests {
  object Debug extends scala.AnyRef {
    def <init>(): ivm.tests.Debug.type = {
      Debug.super.<init>();
      ()
    };
    private[this] val active: Boolean = true;
    <stable> <accessor> def active: Boolean = Debug.this.active
  }
}
```

**Comment by Blaisorblade** [comment]
Hm.  The code attached above doesn't work with test:compile-quick. The first bug is `compileInputs in Compile` instead of `compileInputs in conf`, but fixing that doesn't seem enough.

**Comment by dwijnand** [comment]
I think this would be an interesting feature that should be explored in an sbt plugin. If it proves successful, and after its API and expected behaviour has stabilised, we could definitely consider rolling this into sbt proper (as a niche, power feature).

**Comment by SethTisue** [comment]
for the record, the usual workaround is to put the files you want compiled with different compiler flags in their own subproject.
