### ISSUE TITLE
PRs seem to hang in a yellow dot state

### ISSUE THREAD

**Issue by eatkins** [sbt/sbt#6049]
I've noticed that regardless of whether or not CI passes, there is a fourth PR check that never completes with the tag `continuous-integration/travis-ci Expected — Waiting for status to be reported`
<img width="920" alt="Screen Shot 2020-11-02 at 2 06 18 PM" src="https://user-images.githubusercontent.com/2658825/97924533-ab92ad00-1d14-11eb-9311-c5254ee670a3.png">

**Comment by eed3si9n** [comment]
I had removed the webhooks setting, but there was also branch protection rules that needed an update.
