### ISSUE TITLE
Remove sbtn (Graal Native Client) from the default debian packaging

### ISSUE THREAD

**Issue by JustinPihony** [sbt/sbt#6053]
The addition of this has caused a 6x increase in sbt size, which results in a MUCH higher download cost in Bintray.

**Comment by eed3si9n** [comment]
This was an unintended consequence of sbtn being part of install.
This is timely since sbt 1.4.2 added `installSbtn` command.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt-launcher-package/pull/341
