### ISSUE TITLE
ClassLoaderCache for Scala 3

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt#6058]
## problem

https://github.com/sbt/sbt/blob/25f492d9195dd7b1c8365e137278e8ca7e088951/main-command/src/main/scala/sbt/internal/classpath/ClassLoaderCache.scala#L182

https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3.0.0-M1/

## expectation

```diff
-      case d :: s :: Nil if d.getName.startsWith("dotty-library") =>
+      case d :: s :: Nil if d.getName.startsWith("dotty-library") && d.getName.startsWith("scala3-library") =>
```

🤔

**Comment by eed3si9n** [comment]
Do you mean `||`? Would you like to send a PR for this?

**Comment by xuwei-k** [comment]
> Do you mean `||` ?

Ah, it's my mistake.
