### ISSUE TITLE
nightlies

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#6062]
Maybe it's best to start nightly process from scratch rather than trying to resurrect the on-again-off-again Jenkins approach.

GitHub packages, for example may be a good option - https://docs.github.com/en/free-pro-team@latest/packages/publishing-and-managing-packages/about-github-packages

**Comment by SethTisue** [comment]
I hope a path forward can be found here. This would definitely reduce friction for people (like myself!) wanting to help test fixes that have landed recently.

It would also make it possible to test fixes in the Scala community build — either individual repos that might benefit from a fix, or build-wide. This could help avoid regressions in sbt point releases.

In short, although I know setting this up is work for you now, in the long run I suspect the effort would be repaid, since it would help all of us help you.

**Comment by eed3si9n** [comment]
I earnestly tried to use GitHub Package Registry from GitHub Actions, and I was able to eventually semi-automatically publish sbt artifacts to https://github.com/sbt/sbt/packages/502680, but it is unsatisfying repository as it stands for many reasons:

1. The repository https://maven.pkg.github.com/sbt/sbt/ is behind the authentication wall. As far as I know, anyone with a GitHub account can get to it, but the users would need to go through the hassle of creating a personal GitHub token with the correct authorization.
2. The fact that the repo is behind the authentication wall is doubly annoying for sbt artifacts, because to pass the credentials to the sbt launcher requires a special property `-Dsbt.boot.credentials=$HOME/.sbt/github_credentials`.
3. Even after you convinced sbt launcher to resolve the artifacts using custom `repositories` file, Coursier doesn't seem to handle the credentials: `unauthorized: https://maven.pkg.github.com/sbt/sbt/org/scala-sbt/sbt/1.4.0-bin-20201115T022424/sbt-1.4.0-bin-20201115T022424.pom (GitHub Package Registry)`

So the incantation to get sbt shell to show up was:

```
$ sbt -Dsbt.repository.config=/tmp/hello/repositories -Dsbt.boot.credentials=$HOME/.sbt/github_credentials -Dsbt.coursier=false
```

In comparison to publishing to Jenkins box (https://jenkins.scala-sbt.org/sbt-snapshots/org/scala-sbt/sbt/) where the artifacts are publicly available and already built in to the sbt launcher as https://repo.scala-sbt.org/scalasbt/maven-snapshots/, this feels many steps inferior.

**Comment by eed3si9n** [comment]
I guess the alternative might be good old Bintray.

**Comment by eed3si9n** [comment]
I've setup GitHub cron job so 3am EST it will release sbt to Bintray. https://bintray.com/sbt/maven-snapshots/sbt/1.4.0-bin-20201115T081042 succeeded last night.

**Comment by SethTisue** [comment]
after adding `sbt-nightlies: https://dl.bintray.com/sbt/maven-snapshots/` to my `~/.sbt/repositories` I was able to run `1.4.0-bin-20201115T081042` :+1:

**Comment by eed3si9n** [comment]
Thanks to @sebastian-alfers https://repo.scala-sbt.org/scalasbt/maven-snapshots/ now points to Bintray, so people can just put `sbt.version=1.4.0-bin-20201117T081157` in `project/build.properties` to try the latest. I'm closing this issue as done.
