### ISSUE TITLE
New 1.4.2 breaks IntelliJ project import

### ISSUE THREAD

**Issue by ChibiTomo** [sbt/sbt#6065]
## steps

Just create a project, with `sbt.version=1.4.2` inside build.properties.
Then import it as a new sbt project.

## problem

IntelliJ (Windows) is stuck after the server creation:
```
[info] sbt server started at local:sbt-server-66a04c1bce0050b6f555
[project-name] $
```

## expectation

Expect IntelliJ to continue importing the project

## notes

I am not sure if sbt is the real culprit here. The import seems to work on IntelliJ Linux.

IntelliJ ticket: [#2953376](https://intellij-support.jetbrains.com/hc/en-us/requests/2953376)

**Comment by eatkins** [comment]
Thanks for the report! This was fixed in https://github.com/sbt/sbt/pull/6051.
