### ISSUE TITLE
Domain scala-sbt.org expired

### ISSUE THREAD

**Issue by iRevive** [sbt/sbt#6075]
Seems the domain has been expired:

```
nslookup scala-sbt.org
Server:		192.168.31.1
Address:	192.168.31.1#53

** server can't find scala-sbt.org: NXDOMAIN
```

**Comment by eed3si9n** [comment]
Thanks for the report. Lightbend was notified about this, and they are investigating the issue.

**Comment by larsrh** [comment]
Seems to be back online now.

**Comment by eed3si9n** [comment]
Registration was renewed by Lightbend.

**Comment by sebastian-alfers** [comment]
For the record: it was a glitch in our domain setting which got fixed yesterday together with another change that makes sure this will not happen again in the future. Thank you all for reporting on this!
