### ISSUE TITLE
`-client` is different from `--client`

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#6078]
## steps

```bash
sbt -client
```

## problem

`-client` is different from `--client`

## expectation

`-client` is same as `--client`

## note

Make a new argument that's like `--java-client` or something for the old behavior currently implemented by `-client`?

_Originally posted by @eatkins in https://github.com/sbt/website/pull/948#issuecomment-724312989_

**Comment by SethTisue** [comment]
haha oh no why didn't I see this one coming 🤦😄
