### ISSUE TITLE
Warning about excessive time in GC measures it wrong

### ISSUE THREAD

**Issue by nafg** [sbt/sbt#6081]
## steps

Build a large project a few times in sbt, especially with a few scala.js modules doing fastOpt, or other ways to churn GC

## problem

SBT prints warnings that defy logic like these:

```text
[warn] 246.322 seconds of the last 10 seconds were spent in garbage collection. You may want to increase the project heap size using `-Xmx` or try a different gc algorithm, e.g. `-XX:+UseG1GC`, for better performance.
```

## expectation

There aren't 246.322 seconds in 10 ;)

## notes

Would also be nice if the suggestions were smarter. I am already using a high -Xmx and G1GC

**Comment by eed3si9n** [comment]
I now remember that there was a previous report - https://github.com/sbt/sbt/issues/5818, which we thought was fixed.

To potential contributor: The relevant code is contained in https://github.com/sbt/sbt/pull/5812 / https://github.com/sbt/sbt/pull/5824.

**Comment by eed3si9n** [comment]
https://github.com/sbt/sbt/blob/d651c95c03f93d4467a2632e6bcd0acf0c79a118/main/src/main/scala/sbt/internal/GCMonitor.scala#L38-L40

I wonder if there's an issue on denominator being 10s especially for the initial report when the initial `lastWarned` is set to 0. 

Even on the subsequent reports, if the report came in every 30s, then it could go over the 50% ratio if 12s out of 30s is spent in GC.

**Comment by jm-g** [comment]
Couldn't it be that 10s was a wall clock time, where as the 246s are compute time. I.e. there roughly 24 threads on 24 cores busy for 10s.
