### ISSUE TITLE
allow customizing apiExtractor's phase

### ISSUE THREAD

**Issue by adriaanm** [sbt/sbt#609]
it seems more consistent to extract the api after picklers, since that way we'll see the same symbol information/structure whether we were typechecking from source / unpickling previously compiled classes

let's make the phase customizable in 0.12.2 and evaluate setting it to picklers by default in future versions of SBT

as soon as I figure out how to test my patch, I'll submit a PR for this issue

**Comment by adriaanm** [comment]
I was targeting the wrong release / environment. The requesters of this enhancement are using 0.13 from the IDE. Investigating whether system properties are a valid means of communication here.

**Comment by harrah** [comment]
It shouldn't be a problem.  I'll cherry-pick it where it needs to go.  I'm fine with pickler being the new default, in which case I don't think it wouldn't matter whether system properties are ok.  The system property just gives us a workaround if a problem is found after final.

**Comment by adriaanm** [comment]
awesome -- thanks! I'm happy to submit a PR to the 0.13 branch with that fix

**Comment by harrah** [comment]
Do you think it should be included in 0.12.2?  I thought so, since so far it fixes problems with no known issues yet, right?  PR on either branch is fine and I'll cherry-pick it wherever we decide it should go.

**Comment by harrah** [comment]
Also, do we have a test case that fails without this?

**Comment by adriaanm** [comment]
Unfortunately, I don't have a repro as we couldn't narrow it down from the huge codebase on which this was causing trouble.

**Comment by harrah** [comment]
Ok.

**Comment by adriaanm** [comment]
It was verified to solve the spurious recompiles they were seeing, though. The behavior was prompted by a custom phase that was adding symbols after typers but before pickler, which seems like a reasonable thing to do.

**Comment by harrah** [comment]
Ok, I won't merge it into 0.12.2 then.
