### ISSUE TITLE
sbt 1.4.0~1.4.3 - all the files in the packaged jar files created at epoch millisecond 0 (1970-01-01 00:00:00)

### ISSUE THREAD

**Issue by kevin-lee** [sbt/sbt#6092]
## steps

Simply
* `sbt package` or
* `sbt packagedArtifacts`

## problem
sbt version: 1.4.x (1.3.x versions don't have this problem)

All the files in the jar files created by sbt's package tasks (`package`, `packagedArtifacts`) have `1970-01-01 00:00:00` for their creation date and time. Please have a look at the following screenshot.
<img width="816" alt="Screen Shot 2020-11-16 at 6 27 25 pm" src="https://user-images.githubusercontent.com/2307335/99224529-9b152300-283a-11eb-8eec-1aeaddb64d14.png">

This might be a big deal for some cases where the application is using a particular version of Spring Boot with a problem like the following one.
https://github.com/spring-projects/spring-boot/issues/19518
Although it was already fixed in Spring Boot, there might be some case where upgrading Spring Boot might not be an option

## expectation

It's expected to have the time the files were actually compiled and created.

## notes
I've already fixed it and test it locally with `publishLocal`. I'll create a PR for this issue soon. 
Done (#6093).

**Comment by eed3si9n** [comment]
As commented https://github.com/sbt/sbt/pull/6093#discussion_r524343922, this was done intentionally to make the packaging more reproducible.

**Comment by kevin-lee** [comment]
@eed3si9n Thanks Eugene. I got that. I'm closing it now. 🙂
