### ISSUE TITLE
stable representation for typerefs to refinement classes

### ISSUE THREAD

**Issue by adriaanm** [sbt/sbt#610]
goal:

a representation of type references to refinement classes that's stable across compilation runs (and thus insensitive to typing from source or unpickling from bytecode)

problem:

the current representation, which corresponds to the owner chain of the refinement:
1. is affected by pickling, so typing from source or using unpickled symbols give different results (because the unpickler "localizes" owners -- this could be fixed in the compiler in the long term)
2. can't distinguish multiple refinements in the same owner (this is a limitation of SBT's internal representation and cannot be fixed in the compiler)

proposed solution:

expand the reference to the corresponding refinement type: doing that recursively may not terminate, but we can deal with that by approximating recursive references  (all we care about is being sound for recompilation: recompile iff a dependency changes, and this will happen as long as we have one unrolling of the reference to the refinement)

**Comment by harrah** [comment]
Can you give an example of the problematic source code?

**Comment by adriaanm** [comment]
More details here: https://issues.scala-lang.org/browse/SI-6596

**Comment by harrah** [comment]
Ok, proposed fix seems reasonable.

**Comment by adriaanm** [comment]
I'll submit a PR to 0.13 and let you cherry pick for 0.12.2 if so desired.
