### ISSUE TITLE
sbt wrongly prints "sbt server is already booting"

### ISSUE THREAD

**Issue by sideeffffect** [sbt/sbt#6101]
## steps

Start sbt in an "unusual" filesystem, fox example, in Eclipse Che, which is a containerized, cloud IDE, where the filesystem sbt works with is mounted over network.

## problem

The whole message is this:

```
sbt server is already booting. Create a new server? y/n (default y)
```

sbt prints it even at wrong times.

## expectation

It seems enough to just press Enter or y and Enter, and sbt then continues, but it shouldn't be displayed in the first place, because no sbt server has started yet.

## notes

Other instance is this StackOverflow question, where there were issues with Windows' wsl2:
https://stackoverflow.com/questions/64809111/sbt-server-is-already-booting-error-when-launching-sbt-from-wsl2-ubuntu

It may be causing issues for other tools depending on sbt: https://github.com/scalameta/metals/issues/2235

**Comment by tahakonuk** [comment]
I too agree that the error message is misleading. I searched for a zombie instance when I first got the error. Although sbt continues booting process after pressing Enter, some functionalities don't work. Such as file watching mechanism (commands starting with "~").

**Comment by eed3si9n** [comment]
@sideeffffect Hi I don't have a context to what's going on in this issue. Could you please follow the prescribed format and https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md#what-to-report guide please?

**Comment by eatkins** [comment]
There is a workaround. If you run sbt with `-Dsbt.server.forcestart=true` this behavior should be avoided (you can add this to .sbtopts in the project directory to always apply the property).

The problem is likely that sbt is unable to create a unix domain socket on this file system. I am not going to fix the underlying issue myself but I can provide guidance for a potential contributor. The offending code is here: https://github.com/sbt/sbt/blob/c52e9916e22e6b1340d83c74abd8e3a331c3229b/main-command/src/main/java/sbt/internal/BootServerSocket.java#L348. The trick is to figure out what kind of IOException is thrown on exotic file systems and how to handle it.

**Comment by sideeffffect** [comment]
We could log the caught exception. `Info` level seems to high, but `Debug` should be appropriate. I can open a PR for this.

**Comment by sideeffffect** [comment]
Btw, @eatkins is `-Dsbt.server.forcestart=true` something you would recommend tools like Metals (the Scala language server) to use for their purposes (like importing a project from sbt)?

**Comment by eatkins** [comment]
No. The point of this feature is to prevent multiple instances of sbt server from starting concurrently. Ideally, metals should be running `sbt --client $METALS_COMMAND` rather than `sbt $METALS_COMMAND`. The former command will only start a new server if one is not already running.

**Comment by sideeffffect** [comment]
This is the command Metals normally runs
```
/usr/lib/jvm/default-jvm/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar /tmp/metals14214498662893508356/sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall
```
Even if I add `--client`
```
/usr/lib/jvm/default-jvm/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar /tmp/metals14214498662893508356/sbt-launch.jar --client -Dbloop.export-jar-classifiers=sources bloopInstall
```
It still asks
```
sbt server is already booting. Create a new server? y/n (default y)
```
And if I then press Enter, I get
```
[info] entering *experimental* thin client - BEEP WHIRR
[info] server was not detected. starting an instance
```
and the program (java) terminates. This happens, even if I run `/usr/lib/jvm/default-jvm/bin/java ... --client ...` multiple times.

/cc @tgodzik

**Comment by eatkins** [comment]
The fact that your filesystem may not support unix domain sockets means that client features may not work out of the box. 
When sbt starts up, it creates a domain socket that clients can use to see the startup progress of the server. That is the feature that is causing you problems. Without it though, there is no feedback while the server starts up. This is particularly problematic if there is a problem with the build because the client is unable to see the issue loading the build.

Then, once sbt starts up, it creates a separate unix domain socket that clients can connect to in order to issue remote commands to sbt. Since this probably won't work on your file system, you might need to set
```
Global / serverConnectionType := ConnectionType.Tcp
```
for remote commands to work.

**Comment by mounaTay** [comment]
which sbt version are you using? I got the same error using sbt 1.4.3 but it got away when using sbt 1.2.8

**Comment by rosemorozenkova** [comment]
Hello! Any updates on this issue? Is there workaround? 

I tried using `sbt -Dsbt.server.forcestart=true compile`, but it still prints the `sbt server is already booting`-message. 

Environment: sbt 1.4.3 (Java 11.0.9.1) in WSL2.

**Comment by eed3si9n** [comment]
According to this [Stackoverflow answer](https://stackoverflow.com/a/64854348), the workaround for WSL 2 is to move the project into a directory within WSL 2.

**Comment by japgolly** [comment]
I'm having this same problem but I'm in Linux, not Windows, but trying to run sbt from within docker.

I haven't been able to find a workaround. It seems to me that we can't run sbt from within docker anymore. That's a pretty major bug.

**Comment by japgolly** [comment]
A bit more info: sbt is running in docker as part of CI, where the build env is provided by a docker image.

In my case, I'm even starting sbt with `-Dsbt.server.autostart=false` which I thought would've avoided this issue, no? Is it a separate bug that this still occurs with that flag?

**Comment by vvlevykin** [comment]
We have a problem similar to the one above with WSL. We use vagrant on virtualbox for the local environments and the source code is mapped via shared folders. sbt cannot create a unix socket in the shared folder and always asks about the sbt server which is breaking the automatic provisioning of the vagrant env.

Is there a workaround for this?

**Comment by ScalaWilliam** [comment]
This keeps on popping for me up as well, like for @japgolly and @vvlevykin.

@eatkins I tried the following, but it did not work:

```
$ sbt -Dsbt.server.forcestart=true update
sbt server is already booting. Create a new server? y/n (default y)
```

I also tried `echo |`, `< /dev/null`, and other various methods, to no avail.

I appreciate that server is very useful for many cases like Metals and performance but there are important less-common cases like CI/Docker/WSL2 where you rather things just _work without a hitch_ or having to Google for how to handle the error. I would not expect a build tool to start up a server - make, Gradle, Maven. It can lead to user attrition (I am very worried for [this guy](https://github.com/sbt/sbt/issues/6279)) if they cannot get it to work (and they don't know that downgrading to 1.3.13 would solve it).

If it doesn't run in Docker, or in my case on WSL, it seems a regression. Happy to be a guinea pig if needed to resolve this.

**Comment by eatkins** [comment]
Sorry, I don't work on sbt anymore.

**Comment by carmo-evan** [comment]
Running into the same issue on WSL2.

**Comment by sideeffffect** [comment]
Btw this happens because in `BootServerSocket.newSocket`, either `Files.deleteIfExists` or `new UnixDomainServerSocket` throws an `IOException`. We just don't know what exceptions it is and what it signifies.
https://github.com/sbt/sbt/blob/ab2875e83723b750c3fc0269e80a231442e99d4f/main-command/src/main/java/sbt/internal/BootServerSocket.java#L336-L350

**Comment by ScalaWilliam** [comment]
Another note- I had an sbt instance freeze up (not sure of the cause), then launched another one (not necessarily killing the frozen one), and got this.

[error] server failed to start on local:sbt-server-386a8f86ab975e22a6f0. java.io.IOException: Could not create lock for \\.\pipe\sbt-server-386a8f86ab975e22a6f0_lock, error 5

this is purely on native Windows CLI.

**Comment by ScalaWilliam** [comment]
Just got this in IntelliJ, native Windows SBT.
![image](https://user-images.githubusercontent.com/2464813/109724946-4f4b7700-7ba8-11eb-8a68-81b0c093255c.png)

**Comment by maffstephens** [comment]
For a bit of added context, I'm also seeing the same problem if I run sbt on Linux Mint in VirtualBox, on a Windows 10 host, using the win10 filesystem. The "force start" workaround doesn't make any difference.  From asking around, I'm getting the impression this is happening to a *lot* of people.

**Comment by sideeffffect** [comment]
@eed3si9n would you, as an sbt steward, reconsider this PR https://github.com/sbt/sbt/pull/6104 ? Or would you be open to a "less invasive" PR that would at least debug-log the caught `IOException`?

Now the situation for sbt users is difficult, because they cannot debug this issue nor report properly on this issue to sbt developers. They have no way to understand what is going on, what is causing this issue (what is the `IOException`).

**Comment by eed3si9n** [comment]
@sideeffffect Sure. Let's do it. I'm actually open to displaying the error message as part of "sbt server is already booting" without prompting the user to type `e`.

**Comment by sideeffffect** [comment]
PR opened https://github.com/sbt/sbt/pull/6353 :crossed_fingers:

**Comment by ScalaWilliam** [comment]
Tried 1.4.8, which has the exception debug. Thanks so much for including it.

I managed to get a bit more information on the issue:
In particular, IntelliJ was reloading the project, and I booted up an sbt shell at the same time. This is what I got:

```
sbt thinks that server is already booting because of this exception:
java.io.IOException: Could not create lock for \\.\pipe\sbt-load7131702087746856167_lock, error 5
Create a new server? y/n (default y)
```

What is \\.\pipe? Does it get removed somehow? Error 5 looks like an access error.

**Comment by ScalaWilliam** [comment]
Also got this in sbt shell after restarting it.

```
[info] compiling 1 Scala source to project\target\scala-2.12\sbt-1.0\classes ...
[info] done compiling
[info] loading settings for project root from build.sbt ...
[info] resolving key references (15014 settings) ...
...
[info] set current project to prj (in build file:/x)
java.lang.NoClassDefFoundError: org/fusesource/jansi/AnsiOutputStream
        at jline.internal.Ansi.stripAnsi(Ansi.java:29)
        at jline.console.ConsoleReader.setPrompt(ConsoleReader.java:528)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2454)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2407)
        at sbt.internal.util.Terminal$$anon$4.super$readLine(Terminal.scala:786)
...
Caused by: java.lang.ClassNotFoundException: org.fusesource.jansi.AnsiOutputStream
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
```

Only happens in IntelliJ's SBT Shell. Clearing project/target has no effect.

Outside of the SBT Shell, in the CLI, works just fine.
Removed ~/.sbt/boot, still get this error.

Reverting back to 1.4.7 works just fine on SBT shell.

**Comment by eed3si9n** [comment]
`\.\pipe...` is a named pipe.

For the second issue please see https://github.com/sbt/sbt/issues/6372.

**Comment by eed3si9n** [comment]
Could someone check if

```scala
Global / autoStartServer := false
```

would fix this? 

Another potential workaround is using TCP/IP instead:

```scala
Global / serverConnectionType := ConnectionType.Tcp
```

This might be ok for Docker, but it could be unsafe for any machines connected to untrusted network.

**Comment by japgolly** [comment]
Thanks @eed3si9n , I just tried both settings from within Docker with sbt 1.4.9 and unfortunately it still doesn't work. I should add a caveat though that it's likely that although everyone in this thread is experiencing the same failure, the underlying causes might be different.

In my case, I'm running sbt from within docker, where the main directory is mounted as read-only and the `targetDirectory` settings point to places in `/tmp`. It used to be fine but trying again with 1.4.9 I'm seeing a clearer error:

```
> sbt -Dsbt.server.autostart=false
sbt thinks that server is already booting because of this exception:
java.io.IOException: org.scalasbt.ipcsocket.NativeErrorException: [30] Read-only file system
Create a new server? y/n (default y)
```

Would it not be an easy solution to just add a flag to tell it not to start a server at all? I specify `-Dsbt.server.autostart=false` but it doesn't seem to workaround this.

**Comment by eed3si9n** [comment]
I was curious if I can run sbt on Windows Subsystem for Linux (WSL), so I just installed it on my Windows-debug machine with Linux build of AdoptOpenJDK 8, and sbt 1.4.9 ran fine for me:

![ExBprypWQAMYQPo](https://user-images.githubusercontent.com/184683/111917885-95ce1c00-8a58-11eb-8f1f-8706fed0573e.jpeg)

I'm not claiming the non-existence of the bug for other environments and platforms, but I'm glad to know sbt seems to work ok on WSL.

**Comment by sideeffffect** [comment]
@eed3si9n :+1: 

How about the "other" WSL? Does that also work for you out of the box?

**Comment by eed3si9n** [comment]
What's the other WSL? Docker? WSL 1? Cygwin?

**Comment by sideeffffect** [comment]
Oh, only now I see that you tested on WSL 2, silly me... Than the other would be WSL 1 :smile_cat: 
Is that something that some people still use? (I think so, I'm not 100 % sure.)

**Comment by ZeerDonker** [comment]
@sideeffffect @eed3si9n 
The issue happens if you are in a windows folder on wsl2. 

So with the same sbt folder, copied to a ~/folder or in a /mnt/c/folder.

In the linux folder, the issue doesn't happen. In the windows folder it does.

**Comment by sideeffffect** [comment]
@ZeerDonker What exception are you getting?

**Comment by ZeerDonker** [comment]
@sideeffffect  No exception. Just the following message. 

```sbt server is already booting. Create a new server? y/n (default y)```

**Comment by sideeffffect** [comment]
@ZeerDonker you're using an old version of sbt then. Please try upgrading to the newest one. (I also recommend using [Scala Steward](https://github.com/scala-steward-org/scala-steward/), it will help you keep your project up to date :wink: )

**Comment by ctoomey** [comment]
FYI with sbt 1.4.9 in a Docker image running ubuntu 16.04, the exception I get is

`java.io.IOException: org.scalasbt.ipcsocket.NativeErrorException: [22] Invalid argument`

I was able to successfully workaround the issue by adding the `--batch` argument too, i.e. `sbt -Dsbt.server.forcestart=true --batch ...`

**Comment by ZeerDonker** [comment]
> you're using an old version of sbt then. Please try upgrading to the newest one. (I also recommend using [Scala Steward](https://github.com/scala-steward-org/scala-steward/), it will help you keep your project up to date 😉 )

@sideeffffect  Thanks. 

Gives the following exception. (On a windows folder, wsl2 ) 

```
java.io.IOException: org.scalasbt.ipcsocket.NativeErrorException: [95] Operation not supported
Create a new server? y/n (default y)

[info] welcome to sbt 1.5.0  (Ubuntu Java 11.0.10)
```

**Comment by xkrt** [comment]
I got the same issue:
```
sbt thinks that server is already booting because of this exception:
java.io.IOException: org.scalasbt.ipcsocket.NativeErrorException: [1] Operation not permitted
```

I use Vagrant with VirtualBox shared directory between Windows 10 (host) and Linux (guest VM) for sbt project.

I've tried workarounds `-Dsbt.server.forcestart=true`, `Global / autoStartServer := false` and `Global / serverConnectionType := ConnectionType.Tcp` without success.

sbt ver: 1.5.2

**Comment by adrian-2414745** [comment]
> 
> 
> @sideeffffect @eed3si9n
> The issue happens if you are in a windows folder on wsl2.
> 
> So with the same sbt folder, copied to a ~/folder or in a /mnt/c/folder.
> 
> In the linux folder, the issue doesn't happen. In the windows folder it does.

Same for me. v1.5.5

**Comment by ScalaWilliam** [comment]
It's happening for me on plain Windows 10 (no WSL), SBT 1.5.5, even setting the aforementioned settings makes no difference.

**Comment by ScalaWilliam** [comment]
Further information:

At least in my specific case, doing `[System.IO.Directory]::GetFiles("\\.\\pipe\\")` in PowerShell gives me:
```
\\.\\pipe\\sbt-load-9219294593538022506_lock
\\.\\pipe\\sbt-load-9219294593538022506
```

In this case, it seems that once there's one instance of SBT, whether alive or ghosted, it would not release this lock, but the logic in booting the server does not seem to release this lock; perhaps in Windows the IPC behaviour is different from that on UNIX?

I also built my own local SBT to throw the full stack trace and it looks like this:
```
sbt thinks that server is already booting because of this exception:
java.io.IOException: Could not create lock for \\.\pipe\sbt-load-9219294593538022506_lock, error 5
Create a new server? y/n (default y)
sbt.internal.ServerAlreadyBootingException: java.io.IOException: Could not create lock for \\.\pipe\sbt-load-9219294593538022506_lock, error 5
        at sbt.internal.BootServerSocket.newSocket(BootServerSocket.java:348)
        at sbt.internal.BootServerSocket.<init>(BootServerSocket.java:294)
        at sbt.xMain$.getSocketOrExit(Main.scala:145)
        at sbt.xMain$.bootServerSocket$lzycompute$1(Main.scala:77)
        at sbt.xMain$.bootServerSocket$1(Main.scala:77)
        at sbt.xMain$.withStreams$1(Main.scala:85)
        at sbt.xMain$.run(Main.scala:121)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:56)
        at sbt.xMain.run(Main.scala:46)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:131)
        at xsbt.boot.Launch$.run(Launch.scala:111)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
        at xsbt.boot.Launch$.launch(Launch.scala:120)
        at xsbt.boot.Launch$.apply(Launch.scala:20)
        at xsbt.boot.Boot$.runImpl(Boot.scala:56)
        at xsbt.boot.Boot$.main(Boot.scala:18)
        at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.io.IOException: Could not create lock for \\.\pipe\sbt-load-9219294593538022506_lock, error 5
        at org.scalasbt.ipcsocket.Win32NamedPipeServerSocket.<init>(Win32NamedPipeServerSocket.java:129)
        at org.scalasbt.ipcsocket.Win32NamedPipeServerSocket.<init>(Win32NamedPipeServerSocket.java:48)
        at sbt.internal.BootServerSocket.newSocket(BootServerSocket.java:342)
        ... 21 more
```

Since a `_lock` pipe already exists, should it actually try to create another one? Because when it tries to create a new one, that is when it will try to create a file, and then cause this `error 5` which corresponds to Access Denied (I would imagine it would deny access to create a pipe on top of one that already exists).

The other server in this case is booted already, rather than booting, so the `ServerAlreadyBootingException` does not describe the situation correctly

**Comment by a1russell** [comment]
I also get this error on vanilla Windows 10, and I have been for a long time. It's especially apparent when there are multiple servers, e.g. a frontend and a backend, that need to run via SBT. Start one task, open a new shell, try to launch the second SBT task, and watch the error appear.

**Comment by MaggieLeber** [comment]
Me too, trying to work with Akka...on Windows 10 IDEA SBT Console

**Comment by ianknowles** [comment]
Happening for me when I open my project thats in the Win10 Documents folder from within WSL2 Ubuntu 20.04
`sbt thinks that server is already booting because of this exception:
java.io.IOException: org.scalasbt.ipcsocket.NativeErrorException: [95] Operation not supported`

**Comment by lbialy** [comment]
Same issue with a VirtualBox VM with a git repo as a shared from host directory. Linux VM, Mac OS X host.

**Comment by michael-etzkorn** [comment]
for WSL and Virtual machines experiencing this due to shared files between the systems seems like the only workaround at the moment is to move from a shared folder to something completely contained within the virtual environment. I hope this gets patched :/

**Comment by jdmuntacb** [comment]
I had the same issue (sbt server is already booting. Create a new server? y/n (default y)) with 1.4.7 version. This issue got resolved by adding "--batch -Dsbt.server.forcestart=true" to sbt command as below.

sbt --batch -Dsbt.server.forcestart=true run

**Comment by djx314** [comment]
```
sbt thinks that server is already booting because of this exception:
java.io.IOException: org.scalasbt.ipcsocket.NativeErrorException: [95] Operation not supported
Create a new server? y/n (default y)
```
in WSL2 will lead to vscode can not import project setting. The workaround is find the failed build log, copy the failed command and run it in terminal.

**Comment by ohuu** [comment]
I too have hit this problem. I'm developing on windows but have SBT running in a docker container. I'm sharing the filesystem between windows and docker so that when I make changes in windows they are reflected in the docker container. If I use the Hyper-V backend for docker (i.e. the windows native backend) I get this error. If I switch to using WSL2 as the backend then it goes away.

Although this is a workaround for me it would be nice to be able to develop without having WSL2 installed on my machine.

**Comment by eed3si9n** [comment]
I am guessing that the majority of the issue is caused by sbt server trying to use either Unix domain socket or Windows named pipe and some environments do not support those really well. While sbt server could be beneficial to those who can use the feature, but I recognize that it doesn't always work and hinder you from doing actual build work.

This is not a fix exactly, but I've added `--no-server` "mode" in https://github.com/sbt/sbt/pull/6728. It's a flag to pass system props `-Dsbt.io.virtual=false -Dsbt.server.autostart=false`. (You can try that today by running `sbt -Dsbt.io.virtual=false -Dsbt.server.autostart=false`)

**Comment by ScalaWilliam** [comment]
Hi @eed3si9n, seems this issue is still happening (also #6777). The reproduction seems to be quite simple now on Windows: open a project in IntelliJ, then try to open it in VSCode/Metals. Project fails to load in Metals because SBT won't start because it's waiting on a response to the server message. Not sure if there are any instructions how this can be worked around?

Many thanks

**Comment by eed3si9n** [comment]
If IntelliJ keeps the sbt session active, then it seems like the message is printed as intended?

**Comment by a1russell** [comment]
Why would that be intended, even if the flag is passed?

**Comment by kaizendev2015** [comment]
I am using **sbt** on Ubuntu 22.04. 
 By running sbt ";project api; run -Dhttp.port=9200", I got the above error.
I entered **y** and then got a permission error.
So I added **sudo** and then it works.
sudo  sbt ";project api; run -Dhttp.port=9200" works for me.

**Comment by SethTisue** [comment]
> then got a permission error

when asking for help on the Internet, never summarize or paraphrase an error message; always, always, always paste in the full error message

the exact details of the error might not have meant anything to you, but they're likely to mean something to someone who's trying to help you

**Comment by ScalaWilliam** [comment]
This issue is still happening. Even after closing an SBT process, opening a new one gives still gives this error.

I am constantly seeing people experience it.

**Comment by djx314** [comment]
I think `sbt` can provide a option that can "close existing sbt server anyway".



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 31, 2023 07:34 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [sbt/sbt] sbt wrongly prints "sbt server is already booting"(#6101)




 
This issue is still happening. Even after closing an SBT process, opening a new one gives still gives this error.
 
I am constantly seeing people experience it.

**Comment by ScalaWilliam** [comment]
@djx314 this is not obvious how to do for a user if SBT is launched by Metals in Vs Code

**Comment by djx314** [comment]
It seems that stop the sbt server and restart that the VSCode can auto reconnect. VSCode just need one sbt server on this directory and run with the lastest build.sbt. You can start the sbt yourself and close other sbt and the VSCode will works well if you already finished indexing by metals.



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 31, 2023 18:55 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [sbt/sbt] sbt wrongly prints "sbt server is already booting"(#6101)




 
@djx314 this is not obvious how to do for a user if SBT is launched by Metals in Vs Code

**Comment by djx314** [comment]
It seems that stop the sbt server and restart sbt by yourself that the VSCode can auto reconnect. VSCode just need one sbt server on this directory and run with the lastest build.sbt. You can start the sbt yourself and close other sbt and the VSCode will works well if you already finished indexing by metals use VSCode.




---Original---
From: ***@***.***&gt;
Date: Fri, Mar 31, 2023 18:55 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [sbt/sbt] sbt wrongly prints "sbt server is already booting"(#6101)




 
@djx314 this is not obvious how to do for a user if SBT is launched by Metals in Vs Code
