### ISSUE TITLE
[BSP] - Somehow signify a no-op compilation

### ISSUE THREAD

**Issue by ckipp01** [sbt/sbt#6103]
Following up on a quick conversation on [Gitter](https://gitter.im/sbt/sbt?at=5fb39b5574152347c23cc60d), in Metals one of the things we check when we get notified of a `build/taskStart` is to see whether or not it's a no-op compilation. You can see this here:

https://github.com/scalameta/metals/blob/8f1c5db0e76ddbb95db06a55afc395ca6a965d13/metals/src/main/scala/scala/meta/internal/metals/ForwardingMetalsBuildClient.scala#L117-L148

For better or worse, we just check in the message params to see if it starts with `Start no-op compilation`. This is Bloop specific at the moment, and you can see where this is being reported in Bloop here:

https://github.com/scalacenter/bloop/blob/4768184cc8842d5d6773646ccda93210a89f1b05/frontend/src/main/scala/bloop/reporter/BspProjectReporter.scala#L301-L331

Within Metals we do various check on this compilation to see if we need to do certain things that can in some situations offer some nice UX and speed improvements. Just to give an example we have a Tree View of all packages, and if it's a no-op compilation we know that we don't need to compute anything new for the tree view. As state, right now this is quite Bloop specific, but it'd be great to expand this somehow so that we could have a more generic approach to know if a compilation is a no-op or not from sbt. I'd love to know if this is possible and something you'd consider to forward somehow in the `build/taskStart`. Thanks!

**Comment by eed3si9n** [comment]
In the long-term, it might be better to create a specific compilation event in BSP instead of trying to copy-paste log messages across different build tools.

**Comment by ckipp01** [comment]
> In the long-term, it might be better to create a specific compilation event in BSP instead of trying to copy-paste log messages across different build tools.

Of course. I've gone ahead and created an issue in the BSP repo to discuss it to see if there is a way we can do just that, bake it into the spec.

https://github.com/build-server-protocol/build-server-protocol/issues/148
