### ISSUE TITLE
macOS 11.0 "NoMethodError: undefined method `path' for nil:NilClass" on Homebrew

### ISSUE THREAD

**Issue by cj506817364** [sbt/sbt#6109]
![image](https://user-images.githubusercontent.com/33059555/99521359-4951d180-29cf-11eb-9780-5cadb0c506a0.png)

**Comment by eed3si9n** [comment]
The latest points to 1.4.3 but it's downloading 1.3.13. In general though Homebrew recipe https://github.com/Homebrew/homebrew-core/blob/master/Formula/sbt.rb is maintained by volunteers in the community, and I'm not currently involved.

**Comment by eed3si9n** [comment]
This is likely more to do with your Homebrew setup. See https://discourse.brew.sh/t/homebrew-installation-fail/7439 for example.
