### ISSUE TITLE
Default sbt script does not support commands with quotes.

### ISSUE THREAD

**Issue by ebolinger** [sbt/sbt#614]
sbt-version is 0.12.0

The [documentation](http://www.scala-sbt.org/release/docs/Getting-Started/Running.html) says: 

> For sbt commands that take arguments, pass the command and
> arguments as one argument to sbt by enclosing them in quotes.

But running "sbt run-main MyWebApp" fails with this message:

> [error] Expected whitespace character
> [error] run-main
> [error]                  ^

If the '-d' debug option is used, it is clear that the quotes are ignored or stripped along the way.

**FIX**

The last line if the sbt script needs double-quotes around the $@ argument, like this:

run "$@"

The script in question came from the sbt.tgz file, from the [Setup](http://www.scala-sbt.org/release/docs/Getting-Started/Setup.html) page.  I'm submitting this bug report because I cannot find this script in the XSBT repository (and go the fork/clone/pull request route).  The scala-sbt.org FAQ led to this forum.

**Comment by jsuereth** [comment]
This has already been opened against the appropriate project:  https://github.com/sbt/sbt-launcher-package  and I believe a fix is in place, which will be included in the next release.

Thanks for the report!
