### ISSUE TITLE
SBT does not resolve property from pom

### ISSUE THREAD

**Issue by Zejnilovic** [sbt/sbt#6154]
## steps

1. Add `"za.co.absa" % "atum" % "3.1.0"` to your dependencies
2. Try to build

## problem

SBT does not resolve a property that is part of the pom `${awsjavasdk.version}`

pom.xml in question : https://github.com/AbsaOSS/atum/blob/master/pom.xml#L123

Part of stack trace
```
[error] stack trace is suppressed; run 'last update' for the full output
[error] stack trace is suppressed; run 'last ssExtractDependencies' for the full output
[error] (update) sbt.librarymanagement.ResolveException: Error downloading software.amazon.awssdk:s3:${awsjavasdk.version}
```

## expectation

I would expect it to resolve

## notes
scalaVersion := "2.11.12"
sbt.version=1.3.8

rest of dependencies
```
libraryDependencies ++=  List(
  "org.apache.spark" %% "spark-core" % "2.4.5" % "provided",
  "org.apache.spark" %% "spark-sql" % "2.4.5" % "provided",
  "org.scalatest"    %% "scalatest" % "3.0.5" % Test,
  "za.co.absa" % "atum" % "3.1.0"
)
```

**Comment by eed3si9n** [comment]
@Zejnilovic Thanks for the report. Could you test using the latest stable sbt 1.4.3 please?
This sounds like a duplicate of https://github.com/sbt/sbt/issues/5379

**Comment by Zejnilovic** [comment]
1.4.3 Works. Thank you
