### ISSUE TITLE
[1.4.3] `sbt new` should not create a target and a project directory in the working directory 

### ISSUE THREAD

**Issue by KaoCC** [sbt/sbt#6156]
## steps

sbt version 1.4.3 
run the following commands:
`sbt new akka/akka-quickstart-scala.g8`  or 
`sbt new scala/scala-seed.g8`

## problem

These will create `target` and `project` folders in the current directory.

## expectation

These directory should not be generated.

**Comment by eed3si9n** [comment]
Thanks for the report. I think this is a duplicate of https://github.com/sbt/sbt/issues/5190
