### ISSUE TITLE
Separate compilation broken with 1.4.4

### ISSUE THREAD

**Issue by jrudolph** [sbt/sbt#6197]
* Checkout https://github.com/akka/akka-http
 * run `akka-http-core/compile`
 * change a line in `headers.scala`
 * run `akka-http-core/compile`

shows this error:

```
[info] compiling 1 Scala source to /home/johannes/git/opensource/akka-http/akka-http-core/target/java-1.8.0_275_akka-2.5.32/scala-2.13/classes ...
[error] /home/johannes/git/opensource/akka-http/akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala:987:53: could not find implicit value for parameter ev: akka.http.impl.util.Renderer[Seq[akka.http.scaladsl.model.TransferEncoding]]
[error]   def renderValue[R <: Rendering](r: R): r.type = r ~~ acceptableEncodings
[error]                                                     ^
[error] one error found
```

It sometimes even happens without separate compilation as observed in the master build where we updated the sbt version:

https://travis-ci.com/github/akka/akka-http/jobs/456682975

**Comment by eed3si9n** [comment]
@jrudolph Thanks for the report!

**Comment by jrudolph** [comment]
I'm closing this. It seems this line has issues regardless of sbt or Scala version. It seems to be one of those issues where implicit resolution depends on definition order. I guess in our case sbt 1.4.4 might have supplied sources in a different order or git checked files out in a different order so that they were enumerated in a different order, etc.

We can fix the problem in question locally.
