### ISSUE TITLE
'update' should not be invoked unless there are build changes

### ISSUE THREAD

**Issue by ijuma** [sbt/sbt#62]
'update' should not be invoked unless there are build changes. A build file that shows the issue:

```
import sbt._
import Keys._

object FooBuild extends Build {

  lazy val root = Project("root", file("."), settings = Defaults.defaultSettings) aggregate(
    common)

  def projectSettings = Defaults.defaultSettings ++ Seq(
    libraryDependencies ++= deps.toSeq,
    scalaVersion := "2.9.0-1"
  )

  lazy val common = Project("common", file("likecube-common"),
    settings = projectSettings
  )

  lazy val deps = Set(
    "commons-io" % "commons-io" % "2.0.1",
    "joda-time" % "joda-time" % "1.6.2",
    "log4j" % "log4j" % "1.2.16",
    "com.google.guava" % "guava" % "r09",
    "net.sf.opencsv" % "opencsv" % "2.1"
  )
}
```

See what happens:

[ijuma@localhost]~/tmp/sbt-bug-4% sbt-dev  
[info] Compiling 1 Scala source to /media/internal0/home/ijuma/tmp/sbt-bug-4/project/target/scala_2.8.1/classes...
[info] Set current project to root (in build file:/media/internal0/home/ijuma/tmp/sbt-bug-4/)

> compile
> [info] Updating...
> [info] Done updating.
> [success] Total time: 1 s, completed 19-Jun-2011 20:04:14
> exit
> [ijuma@localhost]~/tmp/sbt-bug-4% sbt-dev  
> [info] Set current project to root (in build file:/media/internal0/home/ijuma/tmp/sbt-bug-4/)
> compile
> [info] Updating...
> [info] Done updating.
> [success] Total time: 1 s, completed 19-Jun-2011 20:04:22

Interestingly, this goes away if I change the deps Set to Seq.

**Comment by harrah** [comment]
I assume that the order of iteration of the Set is changing between JVM iterations because of the hash code of ModuleID class instance (used by the ModuleID hashCode method, since it is a case class).

So, this is intended because the order of dependencies can affect resolution.  I will see if there can be a warning if only the order has changed.

**Comment by ijuma** [comment]
The hash code for case classes doesn't vary between JVM invocations though. The change for this was committed before 2.8.0 if I remember correctly.

**Comment by harrah** [comment]
With your dependencies

```
$ sbt
> set TaskKey[Seq[Int]]("demo") <<= libraryDependencies map { _.map(_.hashCode) }
> show demo
```

In two separate runs, I get different values.  If I run `console-project` and enter:

```
ModuleID("a", "a", "1.0").hashCode
```

I get the same value in the same jvm invocation, but not in different ones.

**Comment by ijuma** [comment]
Interesting. I'll investigate tomorrow as I don't have access to a computer at the moment.

**Comment by ijuma** [comment]
So, the commit I was referring to is https://codereview.scala-lang.org/fisheye/changelog/scala-svn?cs=17161 . The issue is https://issues.scala-lang.org/browse/SI-1387 .

The bytecode for ModuleID.hashCode:

public int hashCode();
  Code:
   Stack=2, Locals=1, Args_size=1
   0:   getstatic   #356; //Field scala/runtime/ScalaRunTime$.MODULE$:Lscala/runtime/ScalaRunTime$;
   3:   aload_0
   4:   invokevirtual   #360; //Method scala/runtime/ScalaRunTime$._hashCode:(Lscala/Product;)I
   7:   ireturn
  LineNumberTable: 
   line 12: 0

The code for ScalaRuntime in 2.8.x (this changed again in 2.9.0):

  def _hashCode(x: Product): Int = {
    val arr =  x.productArity
    var code = arr
    var i = 0
    while (i < arr) {
      val elem = x.productElement(i)
      code = code \* 41 + (if (elem == null) 0 else elem.##)
      i += 1
    }
    code
  }

**Comment by ijuma** [comment]
OK, the issue are the Options. In this case, "configurations: Option[String] = None" since the hashCode for None changes on each invocation. Would you be opposed to adding an explicit hashCode to ModuleID that special-cases None?

**Comment by harrah** [comment]
It would have to be done for Artifact and some Resolvers as well.  I'm not convinced this is a good idea.

**Comment by ijuma** [comment]
What are your concerns? For the record, this is what I was thinking:

```
trait FixedHashCode { self: Product =>
  override def hashCode: Int = {
    val arr = productArity
    var code = arr
    var i = 0
    while (i < arr) {
      val elem = productElement(i)
      code = code * 41 + (if (elem == null || elem == None) 0 else elem.##)
      i += 1
    }
    code
  } 
}
```

Then:

```
case class ModuleID(...) extends FixedHashCode
```

**Comment by harrah** [comment]
It doesn't address the underlying problem, which is using an unordered collection when order matters.  There has been and still is a tension between order, uniqueness, and immutability because there is no `immutable.LinkedHashSet`.  sbt 0.10 generally drops uniqueness from the type and instead throws around lots of `.distinct` calls (unfortunately, but such is the tradeoff).  I understand that previous versions of sbt used a Set, which that is why I suggest a warning.

**Comment by ijuma** [comment]
For this (and many other cases, I guess), order of the Set doesn't really matter as long as it stays the same between invocations. And the suggested approach ensures that. It's an improvement as far as I can see without any real downsides.

**Comment by harrah** [comment]
https://issues.scala-lang.org/browse/SI-4752

**Comment by ijuma** [comment]
If you're not willing to workaround the issue in Scala, then I think it's a good idea to add an entry to the FAQ since it's not easy to diagnose this.
