### ISSUE TITLE
Unable to get source jars for sbt metabuild.

### ISSUE THREAD

**Issue by ckipp01** [sbt/sbt#6203]
## problem

In Metals users are able to get sbt file support by us creating a bsp connection with Bloop for the meta-build. Utilizing sbt-bloop we are able to get everything we need for navigation, hovers, etc since we are able to extract all the sources etc that are needed.

Starting with 1.4.3 we started seeing CI failures as you [can see here](https://github.com/scalameta/metals/pull/2279/checks?check_run_id=1477184052#step:5:3030) where the symbols needed were missing. After digging a bit, it seems that all of the source jars that are normally gathered into the meta-build bloop file are missing. I've included a diff of a minimal projects meta-build bloop files [here to illustrate](https://www.diffchecker.com/zNgiUqb0). On the left hand side is a 1.4.2 metabuild and the right side is a 1.4.5 metabuild. As you can see in the right, all of the source jars under the resolutions are missing.

I am _assuming_ that this has something to do with https://github.com/sbt/sbt/pull/6085 since that's the only change that seems close to being related between 1.4.2 and 1.4.3 that would cause this. Reading through the commit and the linked issues it's still a bit unclear to me how to fix this so that sbt-bloop correctly gets all of the desired source jars. I'm also unsure if this would just be a change we need to make in sbt-bloop or something else. So any pointers or confirmation about what we are seeing would be fantastic.

## Steps to reproduce

- With metals, using Bloop as a BSP server, make sure your project has sbt >= 1.4.3 and import your build. After the build is importing, attempt to go to a key by navigating to it like you normally would
- See error about no definition found (since the source can't be found by Metals)

## expectation

- I'd expect for sbt-bloop to still contain all of the source jars so that navigation in sbt file works while using Metals.

## notes

Again, please let me know if this is actually more of an sbt-bloop issue that we need to sort out. I have taken a look there, but it wasn't incredibly clear to me what would need to change to achieve this based on the changes I see in the pr I linked. Or, I may be completely missing the core issue of what is happening. Let me know if you need anything else or how I can help.

**Comment by tgodzik** [comment]
It seems that when using `updateSbtClassifiers` we no longer get sbt artifacts when invoked inside the plugin. I think it's due to the fact that they are indeed excluded. That change @ckipp01 pointed out seems to be the reason indeed.

I works when I add: 
```scala
Keys.reresolveSbtArtifacts := true
```

**Comment by adpi2** [comment]
@tgodzik I guess I can close this issue since it was fixed by https://github.com/scalacenter/bloop/pull/1433
