### ISSUE TITLE
SBT - publish 0.13.18 to bintray rpm

### ISSUE THREAD

**Issue by rarodriguez94** [sbt/sbt#6205]
## steps
Try to setup sbt launcher to 0.13.18
create file sbt.repo
```
baseurl=https://sbt.bintray.com/rpm
```
Centos install sbt
```
cp sbt.repo /etc/yum.repos.d/sbt.repo
yum update -y
yum install sbt-0.13.18
```
## problem

It seems you can't set the launcher to sbt 0.13.18 for centos 7
They don't exist, so It seems that version is missing:

https://sbt.bintray.com/rpm/
https://bintray.com/sbt/rpm/sbt/0.13.18

## expectation

I should be able to run a scala application using sbt 0.13 and https
https://repo.typesafe.com/typesafe/ivy-releases/

## notes
Currently http://repo.typesafe.com/ is not available anymore since It was disabled earlier this year

**Comment by eed3si9n** [comment]
Done https://bintray.com/sbt/rpm/sbt/0.13.18
