### ISSUE TITLE
Sbt with java 15 sources

### ISSUE THREAD

**Issue by larousso** [sbt/sbt#6208]
## steps

Compiling java sources with the use of multiline string: 

```java 
var aText = """ 
A text 
""";
```

## problem

The compilation fails with an `unclosed string literal`. It's like the sources are not compiled with the good options.

## expectation

It compiles

**Comment by eed3si9n** [comment]
@larousso Thanks for the report.

**Comment by SethTisue** [comment]
does it depend on the `compileOrder` setting (https://www.scala-sbt.org/1.x/docs/Java-Sources.html)? in mixed compilation mode, scalac processes Java sources too, so maybe it's actually a scalac problem rather than an sbt problem?

**Comment by larousso** [comment]
Hi, 
I will try but my app is a java only application.

**Comment by SethTisue** [comment]
the default compile order is "mixed" regardless of whether any Scala sources are present, so yeah I think it's worth a try

**Comment by larousso** [comment]
With 
`Compile / compileOrder := CompileOrder.ScalaThenJava` it works fine, I'am using sbt build info plugin so `Compile / compileOrder := CompileOrder.JavaThenScala` doesn't work.

**Comment by eed3si9n** [comment]
I'm closing this as an upstream Scala compiler issue - https://github.com/scala/bug/issues/12290
