### ISSUE TITLE
Homebrew installation of sbt doesn't work because Homebrew uses untested/unsupported JDK against the will of sbt project

### ISSUE THREAD

**Issue by juli1** [sbt/sbt#6223]
## steps

```
sbt new sbt/scala-seed.g8
```

And launch sbt on the new seed

## problem

sbt crashes.

```
sbt                                                                                                                                                                               08:30:08
[info] Loading global plugins from /Users/julien/.sbt/1.0/plugins
[info] Loading project definition from /Users/julien/git/antlr/project
error: error while loading String, class file '/modules/java.base/java/lang/String.class' is broken
(class java.lang.NullPointerException/Cannot invoke "scala.tools.nsc.Global$Run.typerPhase()" because the return value of "scala.tools.nsc.Global.currentRun()" is null)
[error] java.io.IOError: java.lang.RuntimeException: /packages cannot be represented as URI
[error] 	at java.base/jdk.internal.jrtfs.JrtPath.toUri(JrtPath.java:176)
[error] 	at scala.tools.nsc.classpath.JrtClassPath.asURLs(DirectoryClassPath.scala:204)
[error] 	at scala.tools.nsc.classpath.AggregateClassPath.$anonfun$asURLs$1(AggregateClassPath.scala:55)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:937)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:937)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:70)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:240)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:237)
[error] 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error] 	at scala.tools.nsc.classpath.AggregateClassPath.asURLs(AggregateClassPath.scala:55)
[error] 	at scala.tools.nsc.typechecker.Macros.findMacroClassLoader(Macros.scala:66)
[error] 	at scala.tools.nsc.typechecker.Macros.findMacroClassLoader$(Macros.scala:65)
[error] 	at scala.tools.nsc.Global$$anon$1.findMacroClassLoader(Global.scala:469)
```

## expectation

sbt should work

## notes

```
brew list --versions | grep sbt                                                                                                                                                                                               
sbt 1.4.5
```

It is using JDK15

**Comment by juli1** [comment]
A workaround is to use another JDK


```
export JAVA_HOME=/Library/Java/JavaVirtualMachines/<JDK>
```

**Comment by eed3si9n** [comment]
This why we put warnings against using Homebrew since they ship sbt with some random JDK that we did not test against our will - https://www.scala-sbt.org/download.html
This is their problem, not sbt's.

**Comment by Ryanrpei** [comment]
I reinstalled the one gotten from brew and get another by "sdk install sbt" . It is the same problem.

**Comment by eed3si9n** [comment]
@Ryanrpei We currently test using JDK 8 and 11. What JDK are you using?

**Comment by sabariU** [comment]
@Ryanrpei I have encountered the same issue above. Got the direction from @eed3si9n 's comments
1) Installed SBT 1.4.6 version through SDKMAN
2) Changed sbt.version=1.4.6 in build.properties
3) Reload the sbt changes (refresh icon appear in Intelij when you edit the file)
4) Above issue resolved

**Comment by ALexanderSpiridonov** [comment]
Had the sme issue.

> @Ryanrpei I have encountered the same issue above. Got the direction from @eed3si9n 's comments
> 
> 1. Installed SBT 1.4.6 version through SDKMAN
> 2. Changed sbt.version=1.4.6 in build.properties
> 3. Reload the sbt changes (refresh icon appear in Intelij when you edit the file)
> 4. Above issue resolved

That also did work for me.
Thanks

**Comment by alexkhachikyan** [comment]
thanks for the idea!

I have just simply re-installed the sbt with sdkman
https://www.scala-sbt.org/download.html

here is the sdkman:
https://sdkman.io/install

Best

**Comment by carlocab** [comment]
Hi there, Homebrew maintainer here. A bit late to this, but:

If someone provides a minimal piece of code that reproduces problems when `sbt` is used with Java 17, we can include this in the formula's `test do` block and make the formula depend on Java 11. The addition to the `test do` block will make sure CI blocks anyone from trying to switch `sbt` to an unsupported version.

**Comment by eed3si9n** [comment]
Hi Carlo. sbt is a _build tool_ used by the majority of Scala users, especially in the open source.
What's available under https://www.scala-sbt.org/download.html and Homebrew package is actually not sbt itself, but a shell script called `sbt` and the sbt launcher, which in turn resolves and downloads sbt based on `project/build.properties` (analogous to gradlew or Bazelisk).

In any case, traditionally `sbt` runner script has always used `java` program on the PATH. This is because what JDK the user should use for build is not an easy question to answer. The latest version of sbt 1.6.x would in fact work with JDK 17, but not all versions of Scala works with JDK 17, let alone libraries in JVM ecosystem.

I understand that these design choices might not be compatible with Homebrew's current policies, but that's how `sbt` runner + launcher works on all other distribution channel for the last 12 years. Breaking these compatibility behavior needs to be communicated and coordinated carefully with the Scala community so not to break someone else's build and/or products.

**Comment by carlocab** [comment]
Ok -- so what version of `java` should the `sbt` shell script and sbt launcher use? Or, at least, what is the most sensible default? The formula could be changed to use that instead (though it also allows for users to use whichever Java they want if they set `JAVA_HOME`). But we'd need to add something to run inside the `test` block to prevent someone from changing it to a newer version of Java that isn't a sensible default.
