### ISSUE TITLE
Emit a warning for a "misconfigured" scalaVersion

### ISSUE THREAD

**Issue by hmemcpy** [sbt/sbt#6224]
It turns out that specifying a top-level `scalaVersion` doesn't work as you'd expect in a multi-project build. According to the [sbt documentation](https://www.scala-sbt.org/release/docs/Multi-Project.html), specifying top-level settings without scoping them to `ThisBuild` will only apply it to the root project.

In my sample project,
```scala
name := "sbt-playground"
version := "0.1"
scalaVersion := "2.13.4"

lazy val root = project
  .in(file("."))
  .aggregate(
    shared,
    test
  ).settings(
  name := "myname",
)

lazy val shared =
  (project in file("shared"))
    .settings(
      libraryDependencies ++= Seq(
        ...
      )
    )

lazy val test =
  (project in file("another"))
    .settings(
      name := "another",
      libraryDependencies ++= Seq(
          ...
      )
    )
    .dependsOn(shared % "compile->compile;test->test")
```

Running `show scalaVersion` in sbt will output the following:
```
sbt:sbt-playground> show scalaVersion
[info] shared / scalaVersion
[info] 	2.12.10
[info] test / scalaVersion
[info] 	2.12.10
[info] scalaVersion
[info] 	2.13.4
```
To fix this, the top-level `scalaVersion` has to be specified as `ThisBuild / scalaVersion = "2.13.4"` (or any other variant of the syntax).

Given that this seems to be a common pitfall (see this [twitter thread](https://twitter.com/eed3si9n/status/1340375889780088832)) about it, I want to suggest emitting a warning about it to the user.

Saying that the project is misconfigured (multiple Scala versions detected), and offer a fix - scoping to `ThisBuild`.

I've opened a similar request on the IntelliJ youtrack - its "new sbt project" default template does not emit `ThisBuild`. I believe this is a common enough mistake that many people are making, and hopefully the tooling will provide enough hints to do the right thing.

**Comment by eed3si9n** [comment]
Isn't this a duplicate of https://github.com/sbt/sbt/issues/6217?

**Comment by hmemcpy** [comment]
Oh wow, I didn't see that one. Thank you for starting the discussion. I will close this and follow the other issue.
