### ISSUE TITLE
use 2.9.3 in inc-pickled-existential test

### ISSUE THREAD

**Issue by adriaanm** [sbt/sbt#623]
since 2.9.3 will have a fix for https://issues.scala-lang.org/browse/SI-6692,
https://github.com/harrah/xsbt/blob/0.13/sbt/src/sbt-test/compiler-project/inc-pickled-existential/pending

will start to pass with 2.9.3

(assign to @gkossakowski)

**Comment by harrah** [comment]
Isn't this covered by #616?

**Comment by adriaanm** [comment]
the test is currently using 2.9.2, but fails there -- it'll start passing in 2.9.3

**Comment by harrah** [comment]
#616 was opened to see if a workaround on the sbt side is possible, since sbt is stuck on 2.9.2 and won't get the fix in 2.9.3.

**Comment by adriaanm** [comment]
When working on the fix, I tried switching to 2.9.3 and it worked for me. I'm not talking about compiling sbt with 2.9.3, just using 2.9.3 to compile the test case, as it is essentially testing a bug in the compiler that's fixed in 2.9.3
