### ISSUE TITLE
Error in  `sbt` startup shell in cygwin environment

### ISSUE THREAD

**Issue by flomebul** [sbt/sbt#6260]
I use cygwin environment from years and scala in this environment as well. I just started to use sbt some month ago (with some difficulties I work arround).

After installation of version 1.4.5 I eventually found the first corrections I propose to allow (again) the use of sbt in cygwin.
The corrections is only for the startup shell script:
```
$ diff sbt sbt.edited
109c109,111
<   echo "${sbt_bin_dir}/java9-rt-export.jar"
---
>   #-> echo "${sbt_bin_dir}/java9-rt-export.jar"
>   #-> Must be a windows path on cygwin, as for 'jar_file'
>   echo "$(cygwinpath "${sbt_bin_dir}/java9-rt-export.jar")"
338a341,343
>     #-> java9_ext=$("$java_cmd" "${sbt_options[@]}" "${java_args[@]}" \
>     #->   -jar "$rtexport" --rt-ext-dir | grep java9-rt-ext-)
>     #-> The returned vamlue ends with '\r' on cygwin, so remove it
340c345
<       -jar "$rtexport" --rt-ext-dir | grep java9-rt-ext-)
---
>       -jar "$rtexport" --rt-ext-dir | grep java9-rt-ext- | tr -d '\r')
Luc@Mulan ~/bin
$
```
Hope this can help

**Comment by eed3si9n** [comment]
@flomebul Thanks. Could send a PR on this plz? The file is here - https://github.com/sbt/sbt-launcher-package/blob/master/src/universal/bin/sbt
