### ISSUE TITLE
Entries of Jar files built by sbt have zero timestamp

### ISSUE THREAD

**Issue by RomanIakovlev** [sbt/sbt#6270]
## steps
To reproduce: 
 * `sbt clean publishLocal` on any project, even an empty one, 
 * `unzip -l ~/.ivy2/local/<group_name>/<name>/<version>/<name>.jar`
 * examine the timestamps of entries, they all are `1970-01-01 00:00`

To my best knowledge, this was introduced in sbt version `1.4.0` and applies to all the subsequent versions as well. The version `1.3.13` is the last one to produce the correct timestamps.

## problem
Zero timestamps of JAR entries cause problems with certain popular OSS like Spring, see e.g. https://github.com/RomanIakovlev/timeshape/issues/79

## expectation
JAR entries have the actual timestamps, corresponding to when the artifact is created.

## notes
The `clean` part in `sbt clean publishLocal` is important. Without it, if one first builds the test project on sbt `1.3.13`, and then switches to any of `1.4.x`, the timestamps would stay correct. To actually see the problem, the project must be cleaned.

**Comment by eed3si9n** [comment]
Thanks for the report!

This was done so intentionally in https://github.com/sbt/sbt/pull/5344. There's a duplicate issue https://github.com/sbt/sbt/issues/6235 to allow opt-out. One of the solutions discussed in https://github.com/sbt/sbt/pull/6237 is using the commit date. I'm going to close this as a duplicate.
