### ISSUE TITLE
sbt server does not stay up when sbtn is called from emacs

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#6271]
## steps

run

```
sbtn compile
```

twice from within emacs.

## problem

When called from Emacs the first server dies and the second call starts a new one.

## expectation

I expect the first invocation to start the server, and the second one to use it. This works as expected if called from a terminal emulator such as urxvt-unicode.

## notes

https://github.com/hvesalai/emacs-scala-mode/pull/165

**Comment by eed3si9n** [comment]
@fommil Thanks for the report. I wonder if it's somehow failing to create a virtual terminal.

**Comment by fommil** [comment]
that might be the case, the TERM is usually set to `dumb` and there is the `INSIDE_EMACS` envvar that can be used to add special handling.

**Comment by fommil** [comment]
can you please point me at the code where it's trying to create the virtual terminal? From what I can tell, the server is started (I can see the socket in the .sbt folder), it just gets killed when the process ends. Is there maybe something funny going on where the daemon process is being attached? It's possible that emacs is spinning up a process to start the sbtn process and killing it when sbtn finishes.

**Comment by eed3si9n** [comment]
I am not actually super familiar with the underlying terminal IO stuff, but I think
- sbtn spawns sbt server as a background process
- sbtn sends a query to determine the terminal capability of the sbt server here - https://github.com/sbt/sbt/blob/c0e82677567ad7a6686ed8b60a93b556514d003b/main/src/main/scala/sbt/internal/server/NetworkChannel.scala#L741
- sbt server creates `sbt.internal.util.Terminal` object somewhere in here to determine its capability - https://github.com/sbt/sbt/blob/develop/internal/util-logging/src/main/scala/sbt/internal/util/Terminal.scala

See also https://github.com/sbt/sbt/issues/6186

**Comment by eed3si9n** [comment]
> It's possible that emacs is spinning up a process to start the sbtn process and killing it when sbtn finishes.

sbtn process is meant to end, but sbt server process should persist in the background. Could it be possible that emacs somehow doesn't like that behavior and tries to kill it?

**Comment by fommil** [comment]
it looks like a lot of the emacs jline customisations @hvesalai added have been lost in sbt's Terminal layer. I think we'll need to add them here. Specifically I think we want ansi colours to be enabled but for the supershell to be disabled when INSIDE_EMACS is set.

I can't see where the spawning of the background process is controlled by the Terminal capabilities, perhaps @eatkins can say more on that? If it's possible to add some more debugging, e.g. writing out to a log file on kill signals, that would be really useful.

Can you please direct me to where the spawning happens? I assume there is some external OS call since I can't imagine doing that from the JVM.

**Comment by eatkins** [comment]
The server is forked by `sbtn` (or `sbt -client`) here: https://github.com/sbt/sbt/blob/844deab78c833b8f59e53051636d218658daa1bf/main-command/src/main/scala/sbt/internal/client/NetworkClient.scala#L340-L347 All of the terminal logic should live in https://github.com/sbt/sbt/blob/develop/internal/util-logging/src/main/scala/sbt/internal/util/Terminal.scala

The server is supposed to disconnect the standard io streams when it launches and maybe it's possible that it isn't? That could potentially cause the server to crash if the spawning process exits. The disconnection happens here: https://github.com/sbt/sbt/blob/2bbbcfae77b53e89cea525e3f7b68da8ea142a96/main/src/main/scala/sbt/internal/CommandExchange.scala#L257-L259

**Comment by fommil** [comment]
@eatkins I'll try to do some experiments. I think the issue might be with the way that Emacs spawns processes. It spins up a new process in a buffer and then when that process completes it considers it finished. I think it might be analagous to typing `sbtn compile` in a terminal window and then closing the terminal; would you expect the sbt server to still be running? I'm trying to think about it in terms of parent processes.

**Comment by hvesalai** [comment]
https://www.emacswiki.org/emacs/PersistentProcesses

**Comment by fommil** [comment]
@hvesalai I think you've nailed it there. We need to use `nohup` on the Emacs side!

I'll send a PR to fix the ansi / colour / super issues.

**Comment by fommil** [comment]
or should sbt use `nohup` when spawning the server? :thinking:
