### ISSUE TITLE
Control characters randomly appear in sbt console

### ISSUE THREAD

**Issue by tdg5** [sbt/sbt#6273]
## steps

In my experience, all that is needed is to open a console, create a long line of text and use the keyboard arrows to move left and right. Eventually, some weird characters will start to get injected. All I'm doing is holding down left arrow or right arrow and `[C` and `[D` keep popping in out of nowhere.

![sbt-weird-chars](https://user-images.githubusercontent.com/2316989/105241535-d0d8cf80-5b3b-11eb-87e9-f507cacb0ff1.gif)

## problem

I don't want those characters :( In a string they're less of a problem, but if it's a line of code that's affected it breaks the code generally. Navigating to the stray character to remove it usually results in more stray characters. yuck.

## expectation

Weird characters will not be injected while maneuvering around.

## notes

Reproduced on ubuntu 18.04 and 20.04.

Does not happen with sbt version `1.2.8`.
Does happen with sbt version `1.3.13`
Does happen with sbt version `1.4.4`.
Does happen with sbt version `1.4.6`.

I have only tried w/ scala version `2.11.8`.

Please let me know if there are any other details I can provide.

**Comment by eed3si9n** [comment]
@tdg5 Thanks for the report.

**Comment by philliptaylorpro** [comment]
I get this, and have gotten it for years and it's very irritating. I'm on Debian stable with konsole and bash. It happens in all Scala versions, all sbt versions.

**Comment by SethTisue** [comment]
so weird. I've never seen this even once. (but I mainly use MacOS)

I wonder if there's anything about it at https://github.com/jline/jline3/issues

I almost wrote "it seems highly unlikely to have an sbt-specific cause", and perhaps that's right, but then I thought: maybe it has something to do with both sbt itself and the Scala REPL _both_ using JLine, and there is somehow resulting interference?

**Comment by Friendseeker** [comment]
I don't have an Ubuntu machine so tested on Windows machine.

Not reproducible on Windows 11, sbt 1.10.4 and Java 17. Although did notice a different issue. When sbtn is used instead of sbt, after spamming arrow keys the console freezes.
