### ISSUE TITLE
Run tasks named on command-line in parallel

### ISSUE THREAD

**Issue by LeifWarner** [sbt/sbt#628]
So I could say `sbt test doc downloadStuff` or whatever, and downloadStuff, which doesn't have a dep on the other tasks, could start running while the code is being compiled, tested, artifacts published, whatever.

We run groups of tasks like this from the command-line on our continuous integration server (Jenkins).

**Comment by vigdorchik** [comment]
I really like the suggestion. To generalize and make it more orthogonal, I think it should allow for the same functionality from interactive shell. 

There needs to be a way to group a sequence of commands into a single command allowing for a whole-sequence dependency resolution.
