### ISSUE TITLE
sbt's default repository is blocked in China

### ISSUE THREAD

**Issue by PinkyJie** [sbt/sbt#629]
Sbt's default repository http://repo.typesafe.com/typesafe/ivy-releases/ is blocked by GFW in China. When I try to execute the command 'sbt', it keeps downloading the jars needed for booting.

So, is there any other repositories that sbt can use?

**Comment by harrah** [comment]
There aren't alternative repositories, but there haven't been any problems so far.  What is a specific URL that is blocked and can you run a traceroute?  (You can send this directly to me if you prefer.)

**Comment by PinkyJie** [comment]
Finally I use a proxy, it works.
