### ISSUE TITLE
remote caching: run test incrementally

### ISSUE THREAD

**Issue by gontard** [sbt/sbt#6292]
As explained in #6286, i am integrating the new remote caching feature.

I would like to also take advantage of the remote caching to run test incrementally as explained in [this blog post](https://eed3si9n.com/cached-compilation-for-sbt):
> This idea could expand out to things like test results. sbt currently stores the list of succeeded tests and their timestamps. Using that testQuick run incremental tests. If we used the content hash, or something that does not depend on the timestamp, we might be able to run only the tests that's been affected by the last CI run.

If i understand correctly since #6026 the remote caching relies on content hashing. Is there something else missing?

Also in source code, there is already a commented out block to do that:
https://github.com/sbt/sbt/blob/0a6e5c311696ae2ae39e3da2ac80f9206a64179d/main/src/main/scala/sbt/internal/RemoteCache.scala#L411-L416

**Comment by eed3si9n** [comment]
Fixed in sbt 2.x - https://github.com/sbt/sbt/pull/7644
