### ISSUE TITLE
Machine-independent file stamping to embed caches in remote cache artifacts

### ISSUE THREAD

**Issue by bjaglin** [sbt/sbt#6298]
Both the historical `sbt.util.FileInfo` & the sbt 1.3 `sbt.nio.FileStamp` mechanisms stamp files with the absolute path. For caches to be machine-independant and thus to have a chance to generate a cache hit after being pulled from a remote cache, paths should be relativized when possible (at least when using hashes, as last-modified is not machine-independant anyway).

I assume it would be OK to do a breaking change from one sbt release to another as there is no guarantee the serialization is stable. However, I wonder how `sbt.util.FileInfo` helpers could get a hold of the base directory without changing signatures? Could we provide overloads with `VirtualFile` instead? From a plugin author perspective (using file stamping), I guess changes would be required anyway, to declare the artifact to be embedded in the remote cache somehow.

I am willing to work on this if we can come up with a rough design.

**Comment by bjaglin** [comment]
> I wonder how `sbt.util.FileInfo` helpers could get a hold of the base directory without changing signatures?

Maybe a new `MachineIndependantFileInfo` strategy could be introduced, which would require a base directory for the formatters to be available in implicit scope. It would only serialize paths relative to that base directory (and fail if anything outside is found?). I wonder how `ChangeReport` deals with non-absolute files though?

**Comment by eed3si9n** [comment]
I think this is now addressed in https://eed3si9n.com/sbt-remote-cache/?
