### ISSUE TITLE
Can't change the "test" filename of scripted-test

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt#630]
I want to use different filename. Because Play2.0 has **test** directory in top level by default.
But current sbt does not configurable **test** filename.

https://github.com/harrah/xsbt/blob/v0.12.1/scripted/sbt/ScriptedTests.scala#L19
https://github.com/harrah/xsbt/blob/v0.12.1/scripted/sbt/ScriptedTests.scala#L54
https://github.com/harrah/xsbt/blob/v0.12.1/scripted/plugin/ScriptedPlugin.scala#L15-L27

**Comment by harrah** [comment]
The scripted framework isn't that sophisticated and I'm not sure how to keep it that way and allow configuring the name.  Maybe it could also look for files with some extension.  A pull request would be accepted, but perhaps it is reasonable for you to make the Play project a subproject, which wouldn't need a top-level test/?  You might be able to override the name of that directory as well (possibly `scalaSource in Test`).

**Comment by harrah** [comment]
@xuwei-k what do you think?  Look for an extension as well, like something.test?

**Comment by christian-schlichtherle** [comment]
I've hit the same issue. Why does the code even put some auxiliary file in the same directory as the code under test? If you could change this, it would work no matter what's in the directory.

**Comment by eed3si9n** [comment]
Proposed solution:
1. Look for `test`.
2. If it's not found, look for `test.script`

To potential contributor: The relevant code locations are
- https://github.com/sbt/sbt/blob/0d3d6bab021ccef17dfce055b593df4d3d84e1d0/scripted/sbt/src/main/scala/sbt/scriptedtest/ScriptedTests.scala#L388-L392
- https://github.com/sbt/sbt/blob/0d3d6bab021ccef17dfce055b593df4d3d84e1d0/main/src/main/scala/sbt/ScriptedPlugin.scala#L123-L124
