### ISSUE TITLE
FetchError$DownloadingArtifacts when importing sbt project to IntelliJ with "Library sources" checked and no sources jar in the artifact repo

### ISSUE THREAD

**Issue by neontorrent** [sbt/sbt#6300]
Related issue: #5501 

## steps

1. Make sure Intellij SBT plugin has checked option "Download Library sources"
2. Import a project with any dependency that does not have source jar in the artifact repo and only binary jar
3. Import fails with 

```
[error] (updateClassifiers) lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] https://xxxxx/xxxx/xxxxx/xxxxxxx-sources.jar: download error: Caught java.io.IOException: Server returned HTTP response code: 403 for URL: https://xxxxx/xxxx/xxxxx/xxxxxxx-sources.jar (Server returned HTTP response code: 403 for URL: https://xxxxx/xxxx/xxxxx/xxxxxxx-sources.jar) while downloading https://xxxxx/xxxx/xxxxx/xxxxxxx-sources.jar
[error] Total time: 33 s, completed 8-Feb-2021 11:26:33 AM
```

## problem

One dependency without source shoulnd't make the whole project import fails. 

## expectation

Source of dependency without source jar should be skipped and project should be imported successfully in IntelliJ

## notes

It was working prior to 1.3.x

**Comment by eed3si9n** [comment]
@texasbruce Thanks for the report.

I tried to implement missingOk support on Couriser here https://github.com/sbt/sbt/pull/5634 /  https://github.com/coursier/sbt-coursier/pull/212. If that was somehow not complete, maybe the test case https://github.com/sbt/sbt/tree/develop/sbt/src/sbt-test/dependency-management/missingok needs to be expanded such that the binary artifact exists but the source is missing?

Either way, I am guessing it would require some fixes in coursier/coursier or coursier/sbt-coursier.

**Comment by eed3si9n** [comment]
<s>Could you also report this to coursier/coursier to get their attention please?</s>

https://github.com/coursier/coursier/issues/1961

**Comment by solarmosaic-kflorence** [comment]
FWIW, I ran into this when importing https://github.com/lagom/lagom which is now using SBT `1.3.13` (IntelliJ version 2020.3.2, Build #IU-203.7148.57). I had originally imported this project some time ago. Deleting the project cache (`.idea`) and re-importing resolved the issue for me.

**Comment by eed3si9n** [comment]
Here's my PR for this - https://github.com/coursier/coursier/pull/1966

**Comment by eed3si9n** [comment]
Coursier 2.0.12 was released with my patch. Here's a PR to bump to it - https://github.com/sbt/sbt/pull/6311

**Comment by neontorrent** [comment]
@eed3si9n I think we commented on the wrong issue. Yes it worked with 1.5.0-RC2
