### ISSUE TITLE
assumedVersionScheme / assumedVersionSchemeJava

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#6301]
## steps

As a user, I can set

```scala
ThisBuild / assumedVersionScheme := VersionScheme.PVP
ThisBuild / assumedVersionSchemeJava := VersionScheme.EarlySemVer
```

## expectations

This lets me decide about default `versionScheme` for libraries that don't define it during the eviction error/warning validation.

_Originally posted by @majk-p in https://github.com/sbt/sbt/issues/6221#issuecomment-776684244_

**Comment by mr-git** [comment]
in https://github.com/sbt/sbt/blob/83012a964476aa68d436b68103069242ac8a70fc/main/src/main/scala/sbt/Keys.scala#L539 all possible values for version scheme are defined as strings and here are used as `String`s too.

Would it be possible to make them typed, like `VersionScheme.PVP` and `VersionScheme.EarlySemVer`? Navigating to definition would have documentation in place, otherwise now have to find correct `key` to read about the meaning of each of them.

This way it would not allow typos in code and would be consistent with scoping, like in ` ... % Test`.

**Comment by eed3si9n** [comment]
@mr-git I avoided that because this feature was developed in conjunction with plugins like sbt-version-policy (https://github.com/scalacenter/sbt-version-policy) and using case classes / case objects normally means that it would bump the required minimum version of sbt.

Creating `VersionScheme` object with `PVP` is possible though.

**Comment by mr-git** [comment]
@eed3si9n, isn't bump to 1.5.0 enough for that?
I was reading your article https://www.scala-lang.org/blog/2021/02/16/preventing-version-conflicts-with-versionscheme.html and for me it seems that backwards compatibility [in this case] would not be broken as new settings are added.

And that would not break `sbt-version-policy` either, as it is still [technically] on 0.x branch (may be broken) and fact that it is in RC run, doesn't mean that breaking of it is not possible any more, as there were no 1.x version released, yet.

Switching to SBT 1.5.0 will be must for all projects, which will want to take advantage of new versioning hints and for library developers to be able to us Scala 3.

**Comment by eed3si9n** [comment]
Here's a PR for this issue - https://github.com/sbt/librarymanagement/pull/366

**Comment by mr-git** [comment]
I am sorry, maybe I got lost in translation, the only thing I wanted is to have typed case objects instead of `String`s like: `"early-semver"` or `"pvp"`, to have less strings in our SBT files. 

I am not sure, how this type-safe wish means:
> users are interested in keeping the eviction warning feature

**Comment by eed3si9n** [comment]
> users are interested in keeping the eviction warning feature

Sorry this wasn't about you. This particular issue #6301 originates from the discussion in https://github.com/sbt/sbt/pull/6221.
