### ISSUE TITLE
assumedEvictionErrorLevel

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#6302]
## steps

As a user, I can set

```scala
ThisBuild / assumedEvictionErrorLevel := Level.Warn
```

## expectations

This allows me to decide if I want to turn on warnings
In case some users didn't ignore the warnings and believe those were useful to them, I'd vote for allowing them to enable warnings instead of silently evicting with an sbt flag like `assumedEvictionErrorLevel := Level.Warn (fail|warn|info)`

Combined with https://github.com/sbt/sbt/issues/6301, I can revive eviction warnings as sbt 1.4.x.

_Originally posted by @majk-p in https://github.com/sbt/sbt/issues/6221#issuecomment-776684244_

**Comment by majk-p** [comment]
I'd be happy to help with that, if someone could provide some guidance on where to start.

**Comment by eed3si9n** [comment]
It should be contained mostly here

- https://github.com/sbt/librarymanagement/blob/develop/core/src/main/scala/sbt/librarymanagement/EvictionError.scala 
- https://github.com/sbt/librarymanagement/blob/develop/ivy/src/test/scala/sbt/internal/librarymanagement/EvictionErrorSpec.scala

**Comment by eed3si9n** [comment]
Here's a PR for this - https://github.com/sbt/librarymanagement/pull/366
