### ISSUE TITLE
Have a look at buildkit project 

### ISSUE THREAD

**Issue by valdo404** [sbt/sbt#6304]
Docker team have recently pushed a project named buildkit.

https://github.com/moby/buildkit

it is able to build anything, including docker image, and it is relying upon an intermediate representation named LLB (low level builder).

And it is also able to launch builds on systems like kubernetes.

 I think it could be funny to have a look to this project to see how it could talk with SBT.

**Comment by eed3si9n** [comment]
We use GitHub issue mostly to track bugs and tasks on sbt development. We do have more open-ended https://github.com/sbt/sbt/discussions for discussions.

If someone wants to investigate buildkit any other integration they could do it, but I don't think we have the bandwidth to do so. Maybe you could try setting it up and blog out it etc.
