### ISSUE TITLE
Package the sbt launcher in such a way that it can easily be installed by coursier

### ISSUE THREAD

**Issue by julienrf** [sbt/sbt#6314]
cf the discussion below.

---

> Would you be interested in making this change (cs setup installs the official sbt launcher) happen?

I just tried, and it turns out it's a little bit more complicated. The scripts in the sbt archive seems not to work in a standalone fashion. The `sbt` and `sbt.bat` scripts need `sbt-launch.jar` and `java9-rt-export.jar` alongside them. Which breaks what I had in mind and could have mostly worked right now, that is just picking `sbt` or `sbt.bat` from the archive, and put that in the `PATH`.

(I'm not sure what was the point of keeping `java9-rt-export.jar` separate. Its 3 classes could just have been folded in `sbt-launch.jar`… And `sbt-launch.jar` could actually be appended to `sbt` and `sbt.bat`, so that these scripts don't need to look for external files.)

To work around that, `cs` could maybe extract the full archive, instead of picking just one file, and have the script it generates itself (the one actually put in the `PATH`) call the right file from the extracted archive. But that needs a bit of work… Or maybe we could do some ad hoc post-processing just for sbt, so that we can merge `java9-rt-export.jar` and `sbt-launch.jar` ourselves, append the result to `sbt` or `sbt.bat`, and change a few strings in them so that they use themselves as JAR instead of looking for external files.

_Originally posted by @alexarchambault in https://github.com/scala/scala-lang/issues/1209#issuecomment-779761887_

**Comment by eed3si9n** [comment]
Sounds like a plan. If folding java9-rt-export.jar into the launcher helps that seems like a relatively small adjustment we should make.

**Comment by eed3si9n** [comment]
The relevant repos:
- https://github.com/sbt/java9-rt-export
- https://github.com/sbt/launcher

**Comment by eed3si9n** [comment]
I've updated Launcher to use Scala 2.12 (https://github.com/sbt/launcher/pull/82) as opposed to Scala 2.10, and brought in java9-rt-export https://github.com/sbt/launcher/pull/84

**Comment by SethTisue** [comment]
did this get resolved by changes on the Coursier side instead...?

**Comment by julienrf** [comment]
Good point, this is now solved! I am closing the issue.
