### ISSUE TITLE
Windows MSI installer: unrecognized app

### ISSUE THREAD

**Issue by unkarjedy** [sbt/sbt#6317]
Just try to run installer from https://www.scala-sbt.org/download.html
Looks like the installers should be somehow signed / verified by Microsoft

![image](https://user-images.githubusercontent.com/3989292/108187466-8f7a1680-711f-11eb-81a8-15063c9c1d74.png)

**Comment by eed3si9n** [comment]
I think this is a duplicate of https://github.com/sbt/sbt/issues/4309
