### ISSUE TITLE
Need for a new JAR file when "No changes" but file deleted

### ISSUE THREAD

**Issue by ppKrauss** [sbt/sbt#6319]
## steps

1. Delete JAR file from target folder
2. Using terminal SBT prompt, compile by commands `sbt`, `compile` and `package`.
3. check JAR file: **file not found**.

## problem

The JAR file was deleted but SBT not generated a new JAR file.

## expectation

SBT must generate a new JAR file, even when *"[debug] No changes"*.

## notes

It is not a "natural behaviour", more humans expected a new JAR file. See https://stackoverflow.com/q/66250328/287948

**Comment by eed3si9n** [comment]
I've just answered Stackoverflow. I think this is a duplicate of https://github.com/sbt/sbt/issues/4118.
