### ISSUE TITLE
Disabling IvyPlugin or JvmPlugin in the root project

### ISSUE THREAD

**Issue by adpi2** [sbt/sbt#6321]
## steps

```scala
// build.sbt
lazy val root = project.in(file(".")).disablePlugins(plugins.IvyPlugin)
```

## problem

```shell
[error] References to undefined settings: 
[error]   pluginCrossBuild / scalaBinaryVersion from pluginCrossBuild / sbtDependency ((sbt.Defaults.coreDefaultSettings) Defaults.scala:2500)
[error] 
[error]   pluginCrossBuild / scalaVersion from pluginCrossBuild / sbtDependency ((sbt.Defaults.coreDefaultSettings) Defaults.scala:2500)
```

## expectation

The project should load successfully

## notes

There is a circular dependency between `JvmPlugin` and `CorePlugin`:
`JvmPlugin` requires `IvyPlugin` which requires `CorePlugin` which consumes the `scalaBinaryVersion` and `scalaVersion` defined in the `JvmPlugin`

## solutions

There are at least 3 possible solutions:
1. `CorePlugin` should not consume `scalaBinaryVersion` nor `scalaVersion`
2. `CorePlugin` should have a fallback if `scalaBinaryVersion` or `ScalaVersion` are not defined
3. `scalaBinaryVersion` and `scalaVersion` should be defined globally in `CorePlugin`

**Comment by adpi2** [comment]
`scalaBinaryVersion` and `scalaVersion` are defined in `JvmPlugin.projetcSettings`. However there is something called `DefaultSetting` that pushes them to `Global`. And so, surprisingly, this project is valid:

```scala
// build.sbt
lazy val root = project.in(file(".")).disablePlugins(plugins.IvyPlugin)

lazy val foo = project.in(file("foo"))
```

That's why the scripted `project/auto-plugins` is not failing.

I don't totally understand the comment on `DefaultSetting`:
https://github.com/sbt/sbt/blob/6dc132785598a2da8550cc2994bea2dbaaa93ad5/internal/util-collection/src/main/scala/sbt/internal/util/Settings.scala#L768-L770

It's pretending that `Plugin.globalSettings` are not available internally. Is it still the case? If not I think we should move the "default" `projectSettings` to `globalSettings` . @eed3si9n, @dwijnand  do you have a take on this?

**Comment by eed3si9n** [comment]
@adpi2 Here's a discussion thread I created on the topic of configuration, derived, and default settings - https://github.com/sbt/sbt/discussions/6323.
