### ISSUE TITLE
Concurrent modification of stamps in testQuickFilter leads to infinite loop

### ISSUE THREAD

**Issue by RafalSumislawski** [sbt/sbt#6325]
## steps

SBT version: 1.3.13 

I've got a large multi module project, with build configured so that `testQuick` gets triggered twice on one of the modules. 

Think of it as the following two tasks running concurrently:
```
module1 \ Test \ testQuick class1
module1 \ Test \ testQuick class2
```

## problem

- [`testQuickFilter`](https://github.com/sbt/sbt/blob/dffa34c3ecda2d0e9599148e8774f647e3b26b29/main/src/main/scala/sbt/Defaults.scala#L1341) allocates a mutable map `stamps`
- the `stamps` get closed over by the lambda expression which becomes the `testQuickFilter` task
- the `testQuickFilter` mutates the `stamps` with no synchronisation
- if two`testQuickFilter` execute at the same time, they mutate the same `stamps` Map concurrently, potentially leading to inconsistent state of the Map
- with large enough project the "potentially" becomes "almost allways"
- the exact result in my case is that one of the `DefaultEntry` instances in the hash table, starts pointing to itself as `next` leading to a Hashmap with infinite number of entries. When the hashmap attempts to resize itself, the operation becomes an infinite loop and sbt is stuck burning 100% of two cores (one for each of the `testQuickFilter`).

## expectation

It should be possible to safely run two `testQuick` on one module in parallel. Or in other words the `stamps`should either not be shared or the sharing should be done with proper synchronisation.

**Comment by eed3si9n** [comment]
@RafalSumislawski Thanks for the thorough bug report!
