### ISSUE TITLE
Handle Annotation Processor in Mixed Compilation  Mode.

### ISSUE THREAD

**Issue by SchrodingerZhu** [sbt/sbt#6343]

**Comment by eed3si9n** [comment]
@SchrodingerZhu Could you follow the bug reporting format please? https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md#issues-and-pull-requests
If there's no reproduction steps, it would be an extra effort for the maintainers or contributor to reproduce it and more likely not gonna happen.
