### ISSUE TITLE
SBT install fails on CentOS7

### ISSUE THREAD

**Issue by brian-muse** [sbt/sbt#6344]
## steps

Follow the steps described here for RHEL and other RPM distrobutions: https://www.scala-sbt.org/1.x/docs/Installing-sbt-on-Linux.html

## problem

Yum can't create a secure connection to sbt.bintray.com/rpm so it fails on install:
![image](https://user-images.githubusercontent.com/66379035/109427790-03d77400-79c2-11eb-92dc-faa8b22645e8.png)

## expectation

SBT is installed 
## notes

I'm not sure if you are the right folks to reach out to, but the certs for sbt.bintray.com seem to be having issues. If you don't manage those and I need to reach out to Bintray, just let me know.

**Comment by cbcoutinho** [comment]
Same issue on openSUSE using the RPM package on bintray

```shell
$ cat /etc/zypp/repos.d/bintray--sbt-rpm.repo
[sbt-bintray]
name=bintray--sbt-rpm
enabled=1
autorefresh=1
baseurl=https://sbt.bintray.com/rpm
type=rpm-md
gpgcheck=1
keeppackages=0

$ sudo zypper up -r sbt-bintray
Problem retrieving files from 'bintray--sbt-rpm'.
Download (curl) error for 'https://sbt.bintray.com/rpm/repodata/repomd.xml':
Error code: Curl error 35
Error message: error:1408F10B:SSL routines:ssl3_get_record:wrong version number

Please see the above error message for a hint.
Warning: Skipping repository 'bintray--sbt-rpm' because of the above error.
Some of the repositories have not been refreshed because of an error.
Loading repository data...
Reading installed packages...
Nothing to do.
```

**Comment by brian-muse** [comment]
This issue is resolved for me now.
