### ISSUE TITLE
ZIP dependency SNAPSHOTs not being updated in 0.12.1

### ISSUE THREAD

**Issue by galderz** [sbt/sbt#637]
I'm using SBT 0.12.1 and I'm seeing ZIP artifact based SNAPSHOT dependencies not being updated, even after executing 'update'. Example:

Dependency:
    "io.escalante" % "escalante-dist" % "0.2.0-SNAPSHOT" artifacts(Artifact("escalante-dist", "zip", "zip")),

I first updated the dependency on 10th December and I've just updated it yesterday, 10th of January. Looking at my .ivy folder I see:

```
-rw-r--r--  1 g  staff  34084 Jan 10 23:53 ivy-0.2.0-SNAPSHOT.xml
-rw-r--r--  1 g  staff   6122 Jan 10 23:53 ivy-0.2.0-SNAPSHOT.xml.original
-rw-r--r--  1 g  staff   1114 Jan 11 17:16 ivydata-0.2.0-SNAPSHOT.properties
drwxr-xr-x  3 g  staff    102 Dec 18 18:41 zips
```

And zips contains the one from December :(

```
-rw-r--r--  1 g  staff  140518828 Dec 10 18:55 escalante-dist-0.2.0-SNAPSHOT.zip
```

So, the ZIP has not been updated?? :(

Metadata file info: 
- ivy-0.2.0-SNAPSHOT.xml: https://gist.github.com/4511969
- ivydata-0.2.0-SNAPSHOT.properties: https://gist.github.com/4511987
- maven-metadata.xml in https://repository.jboss.org/nexus/content/groups/public/io/escalante/escalante-dist/0.2.0-SNAPSHOT/maven-metadata.xml: https://gist.github.com/4511994

What is going on here?

**Comment by harrah** [comment]
Probably the same as #641.

**Comment by galderz** [comment]
Thx @harrah, very quick! :)
