### ISSUE TITLE
Travis CI Build Fails with Checksum After Upgrade to sbt 1.4.8

### ISSUE THREAD

**Issue by joesan** [sbt/sbt#6377]
## steps

For one of my project, I',m using Scala Steward and Mergify and I got a PR which was about upgrading to sbt 1.4.8

## problem

As soon as it ran through the Travis CI, it fails with the following message:

```
0.01s$ sh scripts/before_install_check.sh
1.56s$ sbt clean coverage test coverageReport
Detected sbt version 1.4.8
Downloading sbt launcher for 1.4.8:
  From  https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/sbt-launch/1.4.8/sbt-launch-1.4.8.jar
    To  /home/travis/.sbt/launchers/1.4.8/sbt-launch.jar
Downloading sbt launcher 1.4.8 md5 hash:
  From  https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/sbt-launch/1.4.8/sbt-launch-1.4.8.jar.md5
    To  /home/travis/.sbt/launchers/1.4.8/sbt-launch.jar.md5
cat: /home/travis/.sbt/launchers/1.4.8/sbt-launch.jar.md5: No such file or directory
md5sum: 'standard input': no properly formatted MD5 checksum lines found
Checksum does not match
Could not download and verify the launcher. Obtain the jar manually and place it at /home/travis/.sbt/launchers/1.4.8/sbt-launch.jar
The command "sbt clean coverage test coverageReport" exited with 1.
```

## notes

Here is the link to my project: https://github.com/joesan/plant-simulator

**Comment by eed3si9n** [comment]
That's because Travis CI doesn't use the official `sbt` script + launcher, but instead use an outdated version of an official script called sbt-extras. This problem has been addressed in https://github.com/paulp/sbt-extras/pull/305.

In the meantime, my recommendation is to migrate to the official `sbt` script. The release note includes the instruction for this - https://github.com/sbt/sbt/releases/tag/v1.4.8

**Comment by joesan** [comment]
I did setup my travis ci to reflect the official sbt script, but now I get the following error:

`Error: Could not find or load main class @.etc.sbt.sbtopts`

**Comment by note** [comment]
@joesan The fix from release notes worked for me. You can see a fix for my project here: https://github.com/note/dhallj-magnolia/pull/8

**Comment by eed3si9n** [comment]
@joesan Make sure to override `SBT_OPTS` environment variable:

```bash
    export SBT_OPTS="-Dfile.encoding=UTF-8"
```

or

```bash
    export SBT_OPTS=
```

**Comment by joesan** [comment]
I have it already, but still it fails! - https://github.com/joesan/plant-simulator/blob/master/scripts/travis_sbt_script.sh

**Comment by joesan** [comment]
Seems not to work if I have it as a script file. As soon as I added it as is to my .travis.yml, it kind of passed.
