### ISSUE TITLE
cleanFiles only cleans directories, not files

### ISSUE THREAD

**Issue by bobismijnnaam** [sbt/sbt#6395]
## steps

sbt version: 1.4.8 (set in `project/build.properties`)

build.sbt:

```scala
lazy val MyProject: Project = (project in file("."))
    .settings(
        // Line A:
        cleanFiles += baseDirectory.value / "testdir" / "testfile",
        // Line B:
        // cleanFiles += baseDirectory.value / "testdir",
    )
```

Project folder structure:

- testproject
  - build.sbt
  - testfolder
    - testfile

## problem

Calling the `clean` task does not delete `testfile` when only line A is in `build.sbt`.

## expectation

When line B is uncommented, testfile is properly deleted. However, line A _alone_ should be sufficient for including `testfile` for deletion in the `clean` task, in my opinion.

## notes

I think this is because of:

https://github.com/sbt/sbt/blob/699ffe57cd4953b5d1e19d4e3f0d4c66156386ff/main/src/main/scala/sbt/internal/Clean.scala#L43

By appending `AnyPath`, only children of the paths in `cleanFiles` are considered. This is inconsistent as the name implies file paths are also valid paths. Possible resolutions I'd find acceptable is this is indeed a bug:

- Change documentation to reflect only directory paths are allowed
  - (In this case, I'd also like to do a feature request for being able to add single files to the `clean` task...)
- Actually delete file paths as well if they occur in `cleanFiles`.
  - I think this can be achieved by checking for file paths in `deleteContents`.

**Comment by eed3si9n** [comment]
@bobismijnnaam Thanks for the bug report and the analysis.
I agree with your expectation that it should be deleted.

I guess the clean task can do a check if the entry is a directory or not here?
https://github.com/sbt/sbt/blob/699ffe57cd4953b5d1e19d4e3f0d4c66156386ff/main/src/main/scala/sbt/internal/Clean.scala#L95-L98

**Comment by bobismijnnaam** [comment]
Thank you for looking at my issue. That sounds like an appropriate solution.
