### ISSUE TITLE
BSP debug session should support Environment Variables

### ISSUE THREAD

**Issue by arixmkii** [sbt/sbt#6396]
## steps

1. Add environment variables in `launch.json` in VSCode with Metals.
2. Launch build configuration.

## problem

Environment variables are not available in the started application.

## expectation

Environment variables are available in the started application.

## notes
This works with latest Bloop. Seems it is very recent addition to the protocol and hasn't been implemented in SBT yet.

**Comment by adpi2** [comment]
Thanks @arixmkii for opening this issue. Unfortunately the `debugSession/start` is not implementeted natively in sbt. It is provided by a plugin in this repository: https://github.com/scalacenter/scala-debug-adapter

Would you like to contribute there as well?

**Comment by arixmkii** [comment]
@adpi2 thank you for the heads up! I will try to implement necessary changes there. Didn't manage to figure out the whole picture on my own in my first try.

**Comment by arixmkii** [comment]
@adpi2 I sketched the needed changes in this [commit](https://github.com/arixmkii/scala-debug-adapter/commit/ee4a173878fef7e15622c20f8df3aa1a21fbe174).

It seems that I will need to have sbt release in place first, because I need updated proto. Also, I decided to drop local versions of contraband definitions, as same models are part of sbt proto (current develop, not sure about 1.4.X).

Managed to published sbt with my changes and debug-adapter with this commit locally and can confirm that VSCode successfully set environment variables for new debug session.

**Comment by arixmkii** [comment]
And it seems after changes to `sbt-debug-adapter` are released we will need a new release of `sbt-metals` as well (bumping the `sbt-debug-adapter` dependency).

**Comment by adpi2** [comment]
Thanks @arixmkii !

> It seems that I will need to have sbt release in place first

If we do it that way, `sbt-debug-adapter` becomes incompatible with older sbt versions (1.4) which is unfortunate.

Alternatively, I suggest to copy-paste the `ScalaMainClass` contraband schema to the `sbt-debug-adapter` repo as we did for `DebugSessionAddress`. A few months after sbt 1.5 is released we can easily drop and replace those by the native ones.

> And it seems after changes to sbt-debug-adapter are released we will need a new release of sbt-metals as well (bumping the sbt-debug-adapter dependency).

Yes but you can also put the `sbt-debug-adpater` plugin explicitly in your `project/plugins.sbt` to force the version.

**Comment by arixmkii** [comment]
>  copy-paste the `ScalaMainClass` contraband schema to the `sbt-debug-adapter` repo as we did for `DebugSessionAddress`

That explains why the schema is there. Haven't thought about backward compatibility in this aspect.

> Yes but you can also put the `sbt-debug-adpater` plugin explicitly in your `project/plugins.sbt` to force the version.

This is what I ended up doing to run my end-to-end tests :)

Thank you for your input! It helps me better understand how the things are organized around this functionality. Will try to update PRs this week.
