### ISSUE TITLE
If update fails with checksum error, link to a FAQ entry on how to disable checksum checking

### ISSUE THREAD

**Issue by retronym** [sbt/sbt#64]
This thread might not be easy enough to discover.

https://groups.google.com/d/msg/simple-build-tool/1QzuzXPt5hw/4vsuFsM8GjkJ

**Comment by harrah** [comment]
I added a section to https://github.com/harrah/xsbt/wiki/FAQ.

I don't see a reasonable way to detect when a bad checksum is the cause of a failed resolution.  Unfortunately, Ivy does not propagate this information except through the logger.

**Comment by retronym** [comment]
Sounds fine, Google will do the rest.
