### ISSUE TITLE
[DOC] sbt update doesn't necessarily trigger updating to latest snapshots without COURSIER_TTL=0s environment variable

### ISSUE THREAD

**Issue by ozars** [sbt/sbt#6411]
## steps

N/A

## problem

It's stated in [Dependency Mangament Flow][1] in docs:

> Directly running the update task (as opposed to a task that depends on it) will force resolution to run, whether or not configuration changed. This should be done in order to refresh remote SNAPSHOT dependencies. 

However, that's not exactly the current behavior (see https://github.com/sbt/sbt/issues/5377#issuecomment-575748040) due to coursier's caching TTL. It is 24 hours [by default][2]. sbt defaults to coursier [since 1.3.0][3].

[1]: https://www.scala-sbt.org/1.x/docs/Dependency-Management-Flow.html
[2]: https://get-coursier.io/docs/ttl
[3]: https://www.scala-sbt.org/1.x/docs/sbt-1.3-Release-Notes.html

## expectation

Documentation reflects current behavior of `sbt update`. Perhaps coursier's TTL behavior can be noted among Troubleshooting steps (e.g. "Run it with `COURSIER_TTL=0s sbt update` if your sbt version >= 1.3.x").

## notes

Setting an environment variable isn't a great solution, but it works. Are there any better alternatives currently?

**Comment by eed3si9n** [comment]
@ozars Thanks for the report. The whole page probably should be rewritten for modern sbt.

**Comment by eed3si9n** [comment]
https://github.com/sbt/website/pull/1010

**Comment by ozars** [comment]
Thanks for very quick response. The rewrite looks even better.

I've just one question though. Are there any differences between appending `changing()` vs running update task? Or is there any official recommendation between these two?

**Comment by eed3si9n** [comment]
`changing()` doesn't add anything. If it's `-SNAPSHOT` it would be treated as a changing thing.

https://github.com/dwijnand/sbt-dynver might be of interest as something like SNAPSHOT.

**Comment by ozars** [comment]
I see. Thanks a lot.
