### ISSUE TITLE
[1.5.0-RC2] `for3Use2_13`  not working in the dotty repo

### ISSUE THREAD

**Issue by adpi2** [sbt/sbt#6420]
## steps

This bug is specific to https://github.com/lampepfl/dotty/pull/11568 where I bump to sbt 1.5.0-RC2 and stop using sbt-dotty.

It is caused by:
```scala
scalaVersion := "3.0.1-RC1"
libraryDependencies +=
        ("org.scala-js" %% "scalajs-library" % "1.5.0").cross(CrossVersion.for3Use2_13)
```

## problem

```scala
[error] stack trace is suppressed; run last scala3-library-bootstrappedJS / update for the full output
[error] (scala3-library-bootstrappedJS / update) sbt.librarymanagement.ResolveException: Error downloading org.scala-js:scalajs-library_3.0.1-RC1:1.5.0
[error]   Not found
[error]   Not found
[error]   not found: /home/piquerez/.ivy2/local/org.scala-js/scalajs-library_3.0.1-RC1/1.5.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scala-js/scalajs-library_3.0.1-RC1/1.5.0/scalajs-library_3.0.1-RC1-1.5.0.pom
[error] Total time: 73 s (01:13), completed Mar 30, 2021 3:22:20 PM
```

Currently the bootstrapped `scalaVersion` of the dotty repo  is `3.0.1-RC1` and its `scalaBinaryVersion` is `3.0.1-RC1`. But `for3Use2_13` is only triggered if `binaryVersion` is `3` or starts with `3.0.0`:

([source](https://github.com/sbt/librarymanagement/blob/23b7d923af2e93d5eebd67c93352758160462388/core/src/main/scala/sbt/librarymanagement/CrossVersionExtra.scala#L130-L134))
```scala
val compat =
   if (binaryVersion == "3" || binaryVersion.startsWith("3.0.0")) "2.13"
   else binaryVersion
```

## expectation

Theoretically, I think the binary version of `3.0.1-RC1` should be `3`? But that would be weird since `3.0.0` is not yet released.

Alternatively we can relax the rule in `for3Use2_13`.

```scala
val compat =
   if (binaryVersion == "3" || binaryVersion.startsWith("3.0")) "2.13"
   else binaryVersion
```

@smarter @sjrd

**Comment by adpi2** [comment]
Actually the current `scalaBinaryVersion` implementation in sbt  is very clear that for `3.0.1-RC1` it should be `3.0.1-RC1`:

([source](https://github.com/sbt/librarymanagement/blob/0672da475d88662c90af543528949fc35da40243/core/src/main/scala/sbt/internal/librarymanagement/cross/CrossVersionUtil.scala#L77-L83))
```scala
private[sbt] def binaryScala3Version(full: String): String = full match {
    case ReleaseV(maj, _, _, _)                       => maj
    case CandidateV(maj, min, _, _) if min.toLong > 0 => maj
    case MilestonV(maj, min, _, _) if min.toLong > 0  => maj
    case BinCompatV(maj, min, patch, stage, _)        => binaryScala3Version(s"$maj.$min.$patch$stage")
    case _                                            => full
  }
```

So we should definitely relax `for3Use2_13`

**Comment by smarter** [comment]
The binary version of 3.0.1-RC1 (and all 3.x versions) should be 3
