### ISSUE TITLE
sbt shell is practically unusable in the terminal Foot

### ISSUE THREAD

**Issue by zsolt-donca** [sbt/sbt#6421]
## steps

- use the terminal emulator [Foot](https://codeberg.org/dnkl/foot/), currently using version `1.7.1`
- start an SBT shell (tested with versions 1.4.3 and 1.4.6) on anywhere, on any project, even outside a project folder

## problem

The screen gets cleared on each command, I can't see the results of the commands that I type into the SBT shell.

The sbt shell is practically unusable because of this, since I cannot see the results of my commands.

I've made a recording of the issue:
https://user-images.githubusercontent.com/6824167/113099557-cd7c5700-9202-11eb-9255-e44ea5bc1221.mp4

## expectation

The screen buffer shouldn't constantly get cleared. I should be able to see the output of my previous commands, just as I can if I use another terminal emulator, such as [Alacritty](https://github.com/alacritty/alacritty).

## notes

I am on Arch Linux, using sbt version `1.4.6` and ncurses version `6.2` in case that's relevant. I am also running foot version `1.7.1`. Note that foot is a Wayland-only terminal emulator, which means that it runs only on Linux and some BSDs, assuming that they use a Wayland-based compositor instead of the more traditional Xorg.

**Comment by eed3si9n** [comment]
@zsolt-donca Thanks for the report. Would `sbt --supershell=false` help?

**Comment by zsolt-donca** [comment]
Thanks for the answer! Yes, passing `--supershell=false` does indeed somewhat help, the shell behaves mostly normally, but not entirely: some actions do clear the screen in a weird way, for example, me opening another sbt shell in another terminal.

**Comment by dnkl** [comment]
I stumbled upon this and it appears to be a bug in foot.

Foot, unlike most other terminals, implements the `auto_left_margin`/`bw`terminfo capability (i.e. reverse-wrapping). From `man terminfo`:

> auto_left_margin   |    bw   |     bw   |  **cub1 wraps from column 0 to last column**

`cub1` is typically `^H` (i.e. backspace).

Sbt issues lots of `CSI 1000 D` escapes (`cub`, **not** `cub1`). Foot incorrectly wraps this, causing the cursor to move back to (0,0), or at least close to that. Combine this with a mix of erase-line and erase-screen escapes, and you get the effect seen in the video.

URxvt is another terminal that implements `bw`, and sbt works correctly there.

Foot needs to be fixed to **only** reverse-wrap the cursor on `cub1`, nothing else. Upstream issue: https://codeberg.org/dnkl/foot/issues/441

**Comment by zsolt-donca** [comment]
I can confirm that this is indeed a bug in foot, and this pull request actually fixes it: https://codeberg.org/dnkl/foot/pulls/442 

Note the comment https://codeberg.org/dnkl/foot/issues/442#issuecomment-188773 that has some further info on exactly what was causing it, and also another way of moving the cursor that is apparently more used that sbt's current one that was causing this issue.

Either way, thanks @eed3si9n for looking into this and thank @dnkl for finding and fixing this issue this quickly!

**Comment by dnkl** [comment]
> and also another way of moving the cursor that is apparently more used that sbt's current one that was causing this issue.

Not sure if `hpa` is used **more**. But it probably fits the bill better than 1000 `cub`s. While I consider `hpa` to be a core escape, i.e. something a terminal _should_ implement, I don't actually know how well supported it is. The correct approach would be to look up `hpa` in terminfo, use it if available, and otherwise fallback to e.g. `cub`.
