### ISSUE TITLE
Provide compilation progress tracking in incremental compiler

### ISSUE THREAD

**Issue by gkossakowski** [sbt/sbt#643]
The following commit:

https://github.com/JetBrains/intellij-scala/commit/b8014c0

that uses `AnalysisCallback` to track progress of compilation suggests that we are lacking the necessary API in incremental compiler or it's not easy to discover one.

See also:

https://issues.scala-lang.org/browse/SI-6985

**Comment by vigdorchik** [comment]
It's not part of 0.12, but it's there:
https://github.com/sbt/sbt/blob/0.13/interface/src/main/java/xsbti/compile/CompileProgress.java

**Comment by harrah** [comment]
Thanks @vigdorchik.

**Comment by gkossakowski** [comment]
I accidentally reopened this issue but clicking the wrong button on issue list. I'm very sorry for that. Closing again.
