### ISSUE TITLE
`@nowarn annotation does not suppress any warnings` when compiling SBT plugins

### ISSUE THREAD

**Issue by dziemba** [sbt/sbt#6430]
## steps

Trying to build an SBT plugin with sbt 1.5.0, in our case [twinagle](https://github.com/soundcloud/twinagle/pull/224). 

## problem

We get `@nowarn annotation does not suppress any warnings` [errors](https://github.com/soundcloud/twinagle/pull/224/checks?check_run_id=2276625337#step:5:208) in the code that extends `AutoPlugin`.

## expectation

No warnings/errors are emitted.

## notes

Seems related to https://github.com/sbt/sbt/issues/6398

**Comment by adpi2** [comment]
Thanks for reporting!

This bug is indeed related to #6398

We will be able to fix it by adding `scalacOptions += "-Wconf:cat=unused-nowarn:s"` to the `SbtPlugin.projectSettings`

As a temporary fix you should do the same in your build.

**Comment by dziemba** [comment]
Thanks for the quick fix!

**Comment by dziemba** [comment]
Hey @adpi2 and @eed3si9n, it looks like the problem still happens with sbt 1.5.1, at least under certain circumstances. Here's a minimal example:

```
$ cat build.sbt
sbtPlugin := true
scalacOptions ++= Seq("-Xlint", "-Xfatal-warnings")

$ cat project/build.properties
sbt.version=1.5.1

$ cat src/main/scala/Test.scala
import sbt.Keys._
import sbt._

object Test extends AutoPlugin {
  override def projectSettings: Seq[Setting[_]] = Seq(organization := "foo")
}

$ sbt compile
[info] welcome to sbt 1.5.1 (AdoptOpenJDK Java 1.8.0_282)
[info] loading project definition from ~/tmp/project
[info] loading settings for project tmp from build.sbt ...
[info] set current project to tmp (in build file:~/tmp/)
[info] Executing in batch mode. For better performance use sbt's shell
[info] compiling 1 Scala source to ~/tmp/target/scala-2.12/sbt-1.0/classes ...
[error] ~/tmp/src/main/scala/Test.scala:5:68: @nowarn annotation does not suppress any warnings
[error]   override def projectSettings: Seq[Setting[_]] = Seq(organization := "foo")
[error]                                                                    ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

**Comment by dziemba** [comment]
Ah, I think I figured this out. Looking at the fix (https://github.com/sbt/sbt/pull/6431/files) it only works when using `enablePlugins(SbtPlugin)` instead of `sbtPlugin := true`.

I assume that using the plugin is (now) preferred over just setting the `sbtPlugin` key?

**Comment by eed3si9n** [comment]
@dziemba Thanks for the detective work. It's true that using `SbtPlugin` is generally preferred but I am not sure if it's ok to start displaying false warnings without it. A quick fix might be to move the fix into a regular `JvmPlugin` settings.
