### ISSUE TITLE
Fails to initialize on IBM i platform

### ISSUE THREAD

**Issue by ThePrez** [sbt/sbt#6435]
## steps
run `bin/sbt` on the IBM i platform
## problem
```
[info] [launcher] getting org.scala-sbt sbt 1.5.0  (this may take some time)...
[error] [launcher] java.lang.ExceptionInInitializerError
[error] [launcher] could not retrieve sbt 1.5.0
```
## expectation
sbt functions correctly

## notes
The root cause is over in the [directories-jvm](https://github.com/dirs-dev/directories-jvm) project, which I will cross-link shortly. Opening an issue here to help track the issue for IBM i users.

**Comment by eed3si9n** [comment]
Thanks for the report!
You might be able to work around directories-jvm problem by running sbt with COURSIER_CACHE environment variable?

**Comment by SethTisue** [comment]
the linked ticket was closed. can this one be closed as well now?
