### ISSUE TITLE
Installing sbt on debian

### ISSUE THREAD

**Issue by Andromelus** [sbt/sbt#6445]
I'm asking here becasue it seems I am going to be closed on [SO](https://stackoverflow.com/questions/67059575/installing-sbt-1-4-7-on-debian-20).

I want to install sbt 1.4.7 on debian 20.

According to this: https://www.scala-sbt.org/1.x/docs/Installing-sbt-on-Linux.html#Ubuntu+and+other+Debian-based+distributions, I should be able to find a package for sbt 1.4.7 (for now).

> DEB package is officially supported by sbt. (sbt 1.4.8 and onwards do
> not have DEB packaging yet due to Bintray going away)

However, I do have the `Unable to locate sbt` error.

According to the message on bintray web site, it goes down on first may, so I should find the package.

Here are the commands I use (taken from official sbt doc):

    RUN echo "deb https://dl.bintray.com/sbt/debian /" |  tee -a /etc/apt/sources.list.d/sbt.list 
    RUN curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add 
    RUN apt-get update 
    RUN apt-get -y install sbt=1.4.7

- Why do I get this error ?
- How to solve this ?
- How to get the package on debian if bintray does down next month ?

**Comment by eed3si9n** [comment]
Thanks for the report! I am not sure why Bintray is already shut down. We'll hopefully have some replacement before May 1st.
But in the meantime, I suggest you grab tgz and put sbt in PATH.

**Comment by eed3si9n** [comment]
I think there's a brown out going on - https://status.bintray.com/

**Comment by Andromelus** [comment]
Alright, thanks for the answer. I should have checked bintray status.
Will go for tgz. 

Good day sir !

**Comment by domizei385** [comment]
Something like this should work (untested):
```
wget https://github.com/sbt/sbt/releases/download/v1.5.0/sbt-1.5.0.tgz
sudo tar xzvf sbt-1.5.0.tgz -C /usr/share/
sudo update-alternatives --install /usr/bin/sbt sbt /usr/share/sbt/bin/sbt 9999
```

**Comment by hrj** [comment]
> I think there's a brown out going on - https://status.bintray.com/

Is this also affecting downloading of sbt plugins like `sbt-assembly`, etc?

Jobs in CI are failing as the dependencies are not being resolved.

**Comment by eed3si9n** [comment]
I'm going to reopen this until this entire thing is resolved.

**Comment by philipschwarz** [comment]
Hello, I am trying to install sbt as part of a Gitlab build and I get this:

`$ echo "deb http://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
deb http://dl.bintray.com/sbt/debian /

$ apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
Warning: apt-key output should not be parsed (stdout is not a terminal)
Executing: /tmp/apt-key-gpghome.lUx1fBVXq7/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
gpg: key 99E82A75642AC823: public key "sbt build tool <scalasbt@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1

$ apt-get update -yqq
E: Failed to fetch http://dl.bintray.com/sbt/debian/InRelease  403  Forbidden [IP: 34.223.179.172 80]
E: The repository 'http://dl.bintray.com/sbt/debian  InRelease' is not signed.`

Does anyone know what the workaround will be for the sunsetting of bintray? https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by kuberlog** [comment]
The workaround is lightbend getting their shit together.

**Comment by eed3si9n** [comment]
The migration plan is discussed at https://github.com/sbt/sbt/issues/6294. JFrog has granted us the use of Artifactory Online instance, so we need to migrate everything from Bintray to there.

**Comment by philipschwarz** [comment]
@eed3si9n thank you

**Comment by alana314** [comment]
+1, this broke our CI/CD on codebuild (apt-get update in ubuntu)

**Comment by thuan826** [comment]
> +1, this broke our CI/CD on codebuild (apt-get update in ubuntu)

same here, were you able to find a workaround?

**Comment by alana314** [comment]
We temporarily disabled apt-get update

**Comment by a1kemist** [comment]
FWIW this is what we swapped to in our CI images a few weeks ago in order to work around the bintray migration:

```shell
curl -fsL https://github.com/sbt/sbt/releases/download/v$SBT_VERSION/sbt-$SBT_VERSION.tgz | tar xfz - -C /usr/share
chown -R root:root /usr/share/sbt
chmod -R 755 /usr/share/sbt
ln -s /usr/share/sbt/conf /etc/sbt
ln -s /usr/share/sbt/bin/java9-rt-export.jar /usr/bin/java9-rt-export.jar
ln -s /usr/share/sbt/bin/sbt /usr/bin/sbt
# add sbt daemon user and group (to mimick the .deb behavior)
groupadd sbt --system
useradd --gid sbt --system --shell /bin/false -c "sbt daemon-user" sbt
```

**Comment by tmccombs** [comment]
Is there a plan to replace bintray with something else?

**Comment by eed3si9n** [comment]
The migration plan is discussed at #6294. I'm actually done migrating, and I'm just waiting for the redirect proxy change.

**Comment by SethTisue** [comment]
repo.scala-sbt.org now redirects to Cloudsmith instead of Bintray

is there still an issue here?

**Comment by eed3si9n** [comment]
> repo.scala-sbt.org now redirects to Cloudsmith instead of Bintray

You mean Scala Center Artifactory?

I've updated the installation instruction on the doc to use repo.scala-sbt.org here - https://github.com/sbt/website/pull/1016

**Comment by mkurz** [comment]
@eed3si9n Will you deploy sbt 1.5.0 to the debian repo as well anytime soon?

**Comment by eed3si9n** [comment]
Yea. I'm working on a lighter packaging that implements automatic download of `sbt-launch.jar` - https://github.com/sbt/sbt/blob/develop/sbt. Hopefully I'll complete it this weekend.

**Comment by mblonsky** [comment]
Hi there, I'm just wondering when May 1st comes and the bintray url is sunset, will "apt-get update" still work in codebuild, or do we need to make some changes to somehow avoid that url?

**Comment by eed3si9n** [comment]
@mblonsky See https://www.scala-sbt.org/1.x/docs/Installing-sbt-on-Linux.html

```
echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
sudo apt-get update
sudo apt-get install sbt
```

`https://dl.bintray.com/sbt/debian` is out; the new hotness is `https://repo.scala-sbt.org/scalasbt/debian`.

**Comment by mblonsky** [comment]
> @mblonsky See https://www.scala-sbt.org/1.x/docs/Installing-sbt-on-Linux.html
> 
> ```
> echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
> curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
> sudo apt-get update
> sudo apt-get install sbt
> ```
> 
> `https://dl.bintray.com/sbt/debian` is out; the new hotness is `https://repo.scala-sbt.org/scalasbt/debian`.

Thank you for this information eed3si9n. Much appreciated.

**Comment by matthewlein** [comment]
Did anyone get anything working on codebuild stardard 4.0 images? I need an `apt-get update` in my builds, so disabling is not an option.

I've been flailing around trying all the various things here without any luck.

**Comment by darkoverlordofdata** [comment]
I'm still getting the same 'repository is not signed' error when I use the new instructions "the new hotness is https://repo.scala-sbt.org/scalasbt/debian." But if I go to that web site, download and "sudo apt install ./sbt-1.5.1.deb", it works...
