### ISSUE TITLE
https://dl.bintray.com/sbt/debian/Release is not publicly accessible

### ISSUE THREAD

**Issue by nercisla** [sbt/sbt#6446]
## steps

run `sudo apt update` on Ubuntu 18.04
the command fails with

```
Err:6 https://dl.bintray.com/sbt/debian  InRelease
  403  Forbidden
```

## problem

[https://dl.bintray.com/sbt/debian/Release](https://dl.bintray.com/sbt/debian/Release) is not publicly accessible

## expectation

[https://dl.bintray.com/sbt/debian/Release](https://dl.bintray.com/sbt/debian/Release) should be publicly accessible

**Comment by JayCork** [comment]
```
[Container] 2021/04/12 16:09:27 Running command apt-get update
Err:11 https://dl.bintray.com/sbt/debian  InRelease
  403  Forbidden [IP: XX]
```

**Comment by obohrer** [comment]
We are encountering this issue as well

**Comment by ajaykumarmandapati** [comment]
This also happens for https://sbt.bintray.com/rpm/repodata/repomd.xml , we get `Forbidden!`

**Comment by teroxik** [comment]
There is a brownout in place. Nothing what can be done by the maintainers except publishing to some other repository.

https://github.com/sbt/sbt/issues/6445

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

@eed3si9n is there any plan to push the packages to some other repositories as ultimately it will go away. The other libraries artifacts have a similar problem.

**Comment by eed3si9n** [comment]
Closing this as duplicate of https://github.com/sbt/sbt/issues/6445

> is there any plan to push the packages to some other repositories as ultimately it will go away. The other libraries artifacts have a similar problem.

Yes. Please see https://github.com/sbt/sbt/issues/6294.
