### ISSUE TITLE
Generating a pom.xml with multiple dependencies with extra attributes is inconsistent with parsing it

### ISSUE THREAD

**Issue by gseitz** [sbt/sbt#645]
If there is more than 1 dependency with extra attributes, the attributes are rendered in the `<extraDependencyAttributes>` tag in the generated `pom.xml` (see [`makeProperties`](https://github.com/sbt/sbt/blob/0.13/ivy/src/main/scala/sbt/MakePom.scala#L101)).
The attributes for different dependencies are separated by `\n`.
However, the XML for the pom is processed by `scala.xml.PrettyPrinter` [here](https://github.com/sbt/sbt/blob/0.13/ivy/src/main/scala/sbt/MakePom.scala#L35), which removes the `\n` inside the `<extraDependencyAttributes>` tag.

At this point, reading/processing and generating the pom diverge from each other, as [`CustomPomParser`](https://github.com/sbt/sbt/blob/0.13/ivy/src/main/scala/sbt/CustomPomParser.scala#L121) splits the content of `<extraDependencyAttributes>` by EOL. The actual error (`+e:scalaVersion doesn't start with +`) is thrown within Ivy.

**Comment by bwmcadams** [comment]
Solved this one last week, and planning to send a patch in to SBT for a permanent fix. It turns out if you add an XML pragma of `xml:space="preserve"` to the XML, it won't strip the newlines.

You can patch an existing project w/o touching SBT internals using a pom-post-process hook which adds the pragma:

``` scala
import scala.xml._
import scala.xml.transform._

object FixExtra extends RewriteRule {
  override def transform(n: Node): Seq[Node] = n match {
    case <extraDependencyAttributes>{extra}</extraDependencyAttributes> => 
        <extraDependencyAttributes xml:space="preserve">{extra.text.replace(" ", "\n")}</extraDependencyAttributes>
    case _ => n
  }
}

pomPostProcess := { (node: Node) =>
    new RuleTransformer(FixExtra)(node)
}
```

**Comment by gseitz** [comment]
Thanks, Brendan. I'll give it a shot on Monday.

**Comment by gseitz** [comment]
Just to confirm what you already know, this works like a charm ;)
Thanks

**Comment by harrah** [comment]
@bwmcadams Marked this as for 0.12.3, which is scheduled for RC1 in early March.

**Comment by harrah** [comment]
@bwmcadams This is the only issue left for 0.12.3, which is supposed to have an RC1 next week.  Let me know if you will not have time to do it.

**Comment by bwmcadams** [comment]
Looking into this now.

**Comment by kahliburke** [comment]
Thank you! This was really annoying and I just found that it had been fixed. I was about to pull my hair out because of this issue. :)

**Comment by bwmcadams** [comment]
We aim to please. The credit for figuring out "how" to fix goes to Grzegorz
Kossawski.
