### ISSUE TITLE
`inputFiles` resolves to the wrong paths when a file specific glob is used

### ISSUE THREAD

**Issue by matomer** [sbt/sbt#6453]
## steps

1. Create an SBT project with the following task:
```
lazy val bla = taskKey[Unit]("")
bla / fileInputs += Glob(baseDirectory.value / "d" / "b.txt")
bla / fileInputs += Glob(baseDirectory.value / "d" / "a") / **

bla := {
  println((bla / fileInputs).value)
  println(bla.inputFiles)
}
```

2. Create the following files under the base directory:
```
- base
  |-d
    |-a
      |-a.txt
    |-b.txt
```

3. Run the `bla` sbt task in sbt version `1.5.0`

## problem

`bla.inputFiles` resolves to `Vector({{base}}/d/b.txt, {{base}}/d/b.txt)`

## expectation

`bla.inputFiles` resolves to `Vector({{base}}/d/b.txt, {{base}}/d/a/a.txt)`.

**Comment by eed3si9n** [comment]
@matomer Thanks for the report! This does look like a bug.

**Comment by eatkins** [comment]
Fixed by https://github.com/sbt/io/pull/319
