### ISSUE TITLE
www.scala-sbt.org/download.html directs users to use bintray

### ISSUE THREAD

**Issue by wiml** [sbt/sbt#6454]
The page at `https://www.scala-sbt.org/download.html` currently directs Linux users to a couple of repositories located on bintray.com.

However according to issues like #6294 users should be using `repo.scala-sbt.org` which will redirect to the appropriate repository.

My expectation is that `download.html` would send users to the recommended URL.

**Comment by kebeda** [comment]
`https://repo.scala-sbt.org/sbt/rpm/rpm` results in a 404.

Ref. https://www.scala-sbt.org/1.x/docs/Installing-sbt-on-Linux.html

**Comment by eed3si9n** [comment]
### Ubuntu

This works for me:

```
$ docker run -it --entrypoint=/bin/bash  adoptopenjdk/openjdk11:jdk-11.0.6_10-ubuntu
java -version
apt-get update > /dev/null && apt-get -y install sudo && apt-get -y install gnupg
echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
apt-get update > /dev/null
sudo apt-get install -y sbt
mkdir -p /tmp/foo && cd /tmp/foo/ && touch build.sbt
sbt
```

This produces

```
....
[info] Fetched artifacts of
[info] loading settings for project foo from build.sbt ...
[info] set current project to foo (in build file:/tmp/foo/)
[info] sbt server started at local:///root/.sbt/1.0/server/4c0c08c28ca021b53943/sock
[info] started sbt server
sbt:foo>
```

### CentOS

For RedHat, I think Bintray had a repo file you could download from their description page, not the dl.bintray, so I'll have to create something like that on sbt website. For now you can write one manually as follows:

```
$ docker run -it --entrypoint=/bin/bash adoptopenjdk/openjdk11:jdk-11.0.6_10-centos
java -version
yum install -y sudo
vi /etc/yum.repos.d/sbt-rpm.repo
cat /etc/yum.repos.d/sbt-rpm.repo
[sbt-rpm]
name=sbt-rpm
baseurl=https://repo.scala-sbt.org/scalasbt/rpm
gpgcheck=0
repo_gpgcheck=0
enabled=1

sudo yum install sbt
mkdir -p /tmp/foo && cd /tmp/foo/ && touch build.sbt
sbt
```

This produces

```
[info] welcome to sbt 1.4.9 (AdoptOpenJDK Java 11.0.6)
....
```

**Comment by eed3si9n** [comment]
Here's a PR for this - https://github.com/sbt/website/pull/1016
