### ISSUE TITLE
typesafeRepo	(https://repo.typesafe.com/typesafe/releases) is returning a 404 error

### ISSUE THREAD

**Issue by DanielBlanco** [sbt/sbt#6459]
## steps

Cannot access **typesafeRepo**!

## problem

https://repo.typesafe.com/typesafe/releases is redirecting to https://dl.cloudsmith.io/public/lightbend/maven-releases/maven and it is always returning a 404.

Are you working on the servers? 

## expectation

When accessing https://repo.typesafe.com/typesafe/releases I should see a list of artifacts.

## notes
I am aware of the JFrog announcement and how this impacted typesafe servers, I'm just wondering if typesafeRepo will be available any time soon? (we depend on it for some of our old services)

**Comment by eed3si9n** [comment]
Could you report this https://discuss.lightbend.com/ instead please?
I am not involved in the migration of typesafe releases repo, so there's not much I can do.
