### ISSUE TITLE
Jars on https://bintray.com/typesafe/ivy-releases/sbt/0.13.17 failed to download

### ISSUE THREAD

**Issue by Tonix517** [sbt/sbt#6472]
## steps

1. Visited https://bintray.com/typesafe/ivy-releases/sbt/0.13.17#files/org.scala-sbt%2Fsbt-launch%2F0.13.17
2. Clicked to https://bintray.com/typesafe/ivy-releases/sbt/0.13.17#files/org.scala-sbt%2Fsbt-launch%2F0.13.17 
3. Clicked sbt-launcher.jar to download the jar

## problem

the redirected URL https://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.17/sbt-launch.jar gave me "Forbidden!"

## expectation

sbt-launcher.jar was downloaded successfully.

## notes

It has been working until 2-3 hours ago (~7AM PST, Apr 26, 2021).

**Comment by felipefrancisco** [comment]
Same problem here +1
Happening when trying to download https://dl.bintray.com/sbt/debian/sbt-1.3.3.deb

**Comment by Tonix517** [comment]
Looks like it is a scheduled maintenance and after May 1st all users should use a different URL to download jars: https://status.bintray.com/

"We recommend that JFrog Cloud customers continue using jcenter.bintray.com, gocenter.io, and repo.chartcenter.io as Artifactory remote repositories going forward."

**Comment by eed3si9n** [comment]
We no longer use Bintray.

https://eed3si9n.com/bintray-to-jfrog-artifactory-migration-status-and-sbt-1.5.1
