### ISSUE TITLE
"Forbidden!" when attempting to download https://dl.bintray.com/sbt/debian/sbt-1.3.3.deb

### ISSUE THREAD

**Issue by felipefrancisco** [sbt/sbt#6473]
## steps

Downloading or accessing the following URL https://dl.bintray.com/sbt/debian/sbt-1.3.3.deb outputs **"Forbidden!"**

## problem

Considering the file cannot be downloaded, builds using this package fatally break.
![image](https://user-images.githubusercontent.com/2165248/116132631-aa3fad00-a6c5-11eb-93d0-de6f638a6abe.png)

## expectation

The file available should be downloadable.

**Comment by eed3si9n** [comment]
Please see https://eed3si9n.com/bintray-to-jfrog-artifactory-migration-status-and-sbt-1.5.1
