### ISSUE TITLE
Ability to configure jvm options for bsp server which is run over bsp/sbt.json

### ISSUE THREAD

**Issue by Alexey-NM** [sbt/sbt#6476]
Currently, a large project will not compile in IntelliJ IDEA if sbt server is not run manually from command line. 

https://discuss.lightbend.com/t/sbt-proposal-ability-to-configure-jvm-options-for-bsp-server-which-is-run-over-bsp-sbt-json/8115

**Comment by adpi2** [comment]
Thank you for reporting this! It seems indeed that the `SBT_OPTS`, `JVM_OPTS` env variables or even the `.jvmopts` file are not taken into account by the `.bsp/sbt.json` command.

**Comment by adpi2** [comment]
Fixed by #6593
