### ISSUE TITLE
getting 404 while downloading sbt plugins 

### ISSUE THREAD

**Issue by vishalpawar17** [sbt/sbt#6477]
## steps

I am getting 404 not found while downloading sbt jars for scala project when i did sbt build
Let me know when those libraries will be available at respective paths

https://repo.scala-sbt.org/scalasbt/maven-releases/com/typesafe/sbt/sbt-ghpages_2.12_1.0/0.6.3/sbt-ghpages-0.6.3.pom
https://repo.scala-sbt.org/scalasbt/maven-releases/com/typesafe/sbt/sbt-js-engine_2.12_1.0/1.2.3/sbt-js-engine-1.2.3.pom
https://repo.scala-sbt.org/scalasbt/maven-releases/com/typesafe/sbt/sbt-native-packager_2.12_1.0/1.5.2/sbt-native-packager-1.5.2.pom
https://repo.scala-sbt.org/scalasbt/maven-releases/com/eed3si9n/sbt-buildinfo_2.12_1.0/0.10.0/sbt-buildinfo-0.10.0.pom
https://repo.scala-sbt.org/scalasbt/maven-releases/com/lightbend/sbt/sbt-javaagent_2.12_1.0/0.1.5/sbt-javaagent-0.1.5.pom
https://repo.scala-sbt.org/scalasbt/maven-releases/com/github/cb372/sbt-explicit-dependencies_2.12_1.0/0.2.10/sbt-explicit-dependencies-0.2.10.pom
https://repo.scala-sbt.org/scalasbt/maven-releases/com/typesafe/sbt/sbt-site_2.12_1.0/1.4.0/sbt-site-1.4.0.pom
https://repo.scala-sbt.org/scalasbt/maven-releases/com/dwijnand/sbt-compat_2.12_1.0/1.2.6/sbt-compat-1.2.6.pom
https://repo.scala-sbt.org/scalasbt/maven-releases/com/typesafe/sbt/sbt-twirl_2.12_1.0/1.5.1/sbt-twirl-1.5.1.pom
https://repo.scala-sbt.org/scalasbt/maven-releases/io/gatling/gatling-sbt_2.12_1.0/3.1.0/gatling-sbt-3.1.0.pom
https://repo.scala-sbt.org/scalasbt/maven-releases/com/typesafe/sbt/sbt-web_2.12_1.0/1.4.4/sbt-web-1.4.4.pom
https://repo.scala-sbt.org/scalasbt/maven-releases/com/eed3si9n/sbt-unidoc_2.12_1.0/0.4.3/sbt-unidoc-0.4.3.pom

https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/typesafe/sbt/sbt-ghpages_2.12_1.0/0.6.3/sbt-ghpages-0.6.3.pom
https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/typesafe/sbt/sbt-js-engine_2.12_1.0/1.2.3/sbt-js-engine-1.2.3.pom
https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/typesafe/sbt/sbt-native-packager_2.12_1.0/1.5.2/sbt-native-packager-1.5.2.pom
https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/eed3si9n/sbt-buildinfo_2.12_1.0/0.10.0/sbt-buildinfo-0.10.0.pom
https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/lightbend/sbt/sbt-javaagent_2.12_1.0/0.1.5/sbt-javaagent-0.1.5.pom
https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/github/cb372/sbt-explicit-dependencies_2.12_1.0/0.2.10/sbt-explicit-dependencies-0.2.10.pom
https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/typesafe/sbt/sbt-site_2.12_1.0/1.4.0/sbt-site-1.4.0.pom
https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/dwijnand/sbt-compat_2.12_1.0/1.2.6/sbt-compat-1.2.6.pom
https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/typesafe/sbt/sbt-twirl_2.12_1.0/1.5.1/sbt-twirl-1.5.1.pom
https://repo.scala-sbt.org/scalasbt/maven-snapshots/io/gatling/gatling-sbt_2.12_1.0/3.1.0/gatling-sbt-3.1.0.pom
https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/typesafe/sbt/sbt-web_2.12_1.0/1.4.4/sbt-web-1.4.4.pom
https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/eed3si9n/sbt-unidoc_2.12_1.0/0.4.3/sbt-unidoc-0.4.3.pom

**Comment by eed3si9n** [comment]
https://repo.scala-sbt.org/scalasbt/maven-releases/ or https://repo.scala-sbt.org/scalasbt/maven-snapshots/ were never used for serving sbt plugins, so 404 is the correct response.

**Comment by wangyum** [comment]
@eed3si9n Why https://repo.scala-sbt.org/scalasbt/maven-releases/  auto redirect to https://repo1.maven.org/maven2/?
