### ISSUE TITLE
Unable to clean/compile projects using JDK 15

### ISSUE THREAD

**Issue by ghost** [sbt/sbt#6482]
## steps

Please try these commands(in terminal) with the below versions, 

**sbt** -> sbt script version: 1.5.1
**Java** -> openjdk version 15.0.1 
**OS** -> Ubuntu
**scalaVersion** -> 2.12.9

**Command**: sbt clean compile 

## problem

sbt clean compile
copying runtime jar...
[info] Loading global plugins from /home/santhosh/.sbt/1.0/plugins
[info] waiting for lock on /home/santhosh/.ivy2/.sbt.ivy.lock to be available...
[info] Loading settings for project XXXXXX-build from plugins.sbt ...
[info] Loading project definition from /home/santhosh/Desktop/XXXX/XXXXX/project
error: error while loading String, class file '/modules/java.base/java/lang/String.class' is broken
(class java.lang.NullPointerException/null)
[error] java.io.IOError: java.lang.RuntimeException: /packages cannot be represented as URI
[error] 	at java.base/jdk.internal.jrtfs.JrtPath.toUri(JrtPath.java:176)
[error] 	at scala.tools.nsc.classpath.JrtClassPath.asURLs(DirectoryClassPath.scala:204)
[error] 	at scala.tools.nsc.classpath.AggregateClassPath.$anonfun$asURLs$1(AggregateClassPath.scala:55)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:937)

## expectation

Should be able to compile and start the application without any issues. 

## Note: Application compiles and starts with Open JDK 12

**Comment by ghost** [comment]
Let me check with the latest scala version and update you. 

2.13.2, 2.12.11 | 2.13.5, 2.12.13

**Comment by SethTisue** [comment]
Yeah, that should fix it, as per https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html

**Comment by ghost** [comment]
It is not working with Scala version -> 2.12.13. The application compiles without issues. but it's not starting. Throwing the same error. 
java.io.IOError: java.lang.RuntimeException: /packages cannot be represented as URI

**Comment by SethTisue** [comment]
Lots of people are using sbt 1.5.1 + Scala 2.12.13 + JDK 15 (or 16); the combination has been well-tested in the Scala community build. The problem must involve some detail you haven't provided. Are you able to construct an MCVE demonstrating the problem?
