### ISSUE TITLE
Not able to install sbt on centos7

### ISSUE THREAD

**Issue by AnudeepKonaboina** [sbt/sbt#6486]
## steps
While executing the below command 
curl https://bintray.com/sbt/rpm/rpm |  tee /etc/yum.repos.d/bintray-sbt-rpm.repo && yum install -y sbt 

## problem
Below is the error:
failure: repodata/repomd.xml from bintray--sbt-rpm: [Errno 256] No more mirrors to try.
https://sbt.bintray.com/rpm/repodata/repomd.xml: [Errno 14] HTTPS Error 403 - Forbidden

## expectation
sbt should have been installed

**Comment by eed3si9n** [comment]
Please check out the updated Linux install instruction - https://www.scala-sbt.org/1.x/docs/Installing-sbt-on-Linux.html
