### ISSUE TITLE
Debian install returning 403 for older sbt version

### ISSUE THREAD

**Issue by vakhtang** [sbt/sbt#6495]
## steps

`apt-get install sbt=1.2.8` 

## problem

Running the command above fails with:

```
Err:1 https://scala.jfrog.io/artifactory/debian  sbt 1.2.8
  403  Forbidden
```

## expectation

Older versions of sbt should install for Debian systems.

## notes

I'm aware of the migration from bintray, and followed the Debian-specific instructions outlined in the [migration guide](https://eed3si9n.com/bintray-to-jfrog-artifactory-migration-status-and-sbt-1.5.1). As far as I can tell only `1.5.0` and `1.5.1` are available for Debian based on a https://scala.jfrog.io/ui/packages/deb:%2F%2Fsbt?name=sbt&type=packages. Was this intentional? Am I missing something?

**Comment by pedrovaleriojumia** [comment]
The 403 error, I believe I had a similar issue last week.

The full error was:

```
Err:1 https://scala.jfrog.io/artifactory/debian  sbt 1.3.5
  403  Forbidden
E: Failed to fetch https://d1v3mxuwh7c9ff.cloudfront.net/filestore/94/94edf8733053f65625d8d19368eb42287dfd4a67?response-content-type=application/x-debian-package&response-content-disposition=attachment;filename="sbt-1.3.5.deb"&x-jf-traceId=81be5909ff4e93f7&Expires=1619775170&Signature=PQWYfaVaI3wca2qif59Ydd4fIXTPd4nL0aKE~EHwnEM361tl1ydhvnwY~51Pu4GSqE-jmblhDxTxJ0WCTCucj46O3qob6JI1fquJBtAc2HbpGnYP3mcR7Cy0~o6bbi9eRImuEjELp5fT2ODteINXWG0yjtCbDPVGnlsCvV87XdHy25OKyYvqyAYBNHXLKQi1IQoXjCiNCbgDcuTwucVvOKDoVXDWLBtyCfMn0DdefTjZF3c9SndZjsoUfENYCUvGewQ0w0AjPrqb7CcbTvV9Fa3d2OYksRZJdC8Bv9GvADf3PVvqLflgqCerB57ADInI7ntO2mVP3ZdyHzEQUOYBKw__&Key-Pair-Id=APKAJ6NHFWMVU3M6DPBA  403  Forbidden
```

This appears to be an issue with apt, which decodes URLs when it is redirected, and in the case of cloudfront signed URL, that would cause this issue.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=806959

I couldn't find a straightforward way to fix this. I updated from debian:stretch to debian:buster and the issue was gone, however that had other impacts.

**Comment by eed3si9n** [comment]
In general, sbt runner installed by 1.5.1 should be capable of running all versions of sbt.

If you really want to you can grab the deb file using curl and install it too. I'm closing this since it seems to be a Debian issue.
