### ISSUE TITLE
Binary-compatible versions are suspected to be binary incompatible

### ISSUE THREAD

**Issue by seanrohead** [sbt/sbt#6496]
## steps

I am using sbt 1.5.1 (with Coursier disabled) and I'm importing multiple libraries, e.g. a and b

a has a transitive dependency to c, version 1.1-prerelease
b has a transitive dependency to c, version 1.0

I am using early-semver as the version scheme.

## problem

I'm getting an error when building that there are version conflicts that are suspected to be binary incompatible.

## expectation

1.0 and 1.1 are supposed to be binary compatible according to the semantic versioning spec. Therefore, my build should succeed without errors. I thought the whole point of setting the versionScheme was to avoid errors like this when the minor or patch number changes, and to only get them when the major version conflicts between multiple transitive dependencies, e.g. 1.1 to 2.0.

**Comment by eed3si9n** [comment]
@seanrohead Thanks for the report. I agree with your expectations.
I wonder if there's a bug in version parsing code when the version consists of two segments as opposed to `x.y.z`.

**Comment by seanrohead** [comment]
I simplified the version numbers in my example. The actual version numbers that caused the bug were:

1.1.0-DLP-7923-presigned-download-url.5
1.0.7
