### ISSUE TITLE
sbt-launcher.jar: command line arg to point to current Scala installation?

### ISSUE THREAD

**Issue by byrongibson** [sbt/sbt#65]
Scripting and running sbt-launcher.jar automatically downloads Scala 2.8.1.  I've already got 2.9.0.1 from the Typesafe distribution installed.  Is there any way to point sbt-launcher.jar at my current Scala installation so it doesn't re-download another one?

**Comment by ijuma** [comment]
SBT 0.10.x is compiled against Scala 2.8.1 and is meant to work with that.

**Comment by harrah** [comment]
Please use the mailing list for questions.  Thanks!
