### ISSUE TITLE
1.5.2 MSI does not work on my PC.

### ISSUE THREAD

**Issue by gavinbaumanis** [sbt/sbt#6506]
SBT 1.5.2's MSI does not work on my laptop.
There is no error message - the installer just seems to "stall" , the installer window does not appear, but windows gives me the "spinny" (busy) circle - and after 90 minutes, was still going... 
There is no apparent process / application for me to kill either.
It also stops the "Explorer" window (Downloads folder in this case) from being closed with the "X" icon, "CTRL-W" or "Alt/CRTL-F4"

**Comment by eed3si9n** [comment]
@gavinbaumanis Thanks for the report. Could you tell us which version of Windows you are on?

**Comment by SethTisue** [comment]
did 1.5.1 or earlier versions work?

**Comment by gavinbaumanis** [comment]
Here are the details for my machine / OS;

Processor	Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   2.59 GHz
Installed RAM	32.0 GB (31.7 GB usable)
System type	64-bit operating system, x64-based processor

Edition	Windows 10 Pro
Installed on	‎07/‎05/‎2021
OS build	21376.1
Experience	Windows 10 Feature Experience Pack 321.11803.0.3

**Comment by gavinbaumanis** [comment]
Hi,

I was on 1.4.9 before trying to upgrade to 1.5.2
I have installed (successfully) 1.5.1
I did not try 1.5.0

**Comment by eed3si9n** [comment]
Could you try uninstalling the existing one and try again please?

**Comment by gavinbaumanis** [comment]
Hi there - yes it does work, now.
But I have also upgraded windows since I posted the original issue.

Edition	Windows 10 Pro
Version	Dev
Installed on	‎28/‎05/‎2021
OS build	21390.1
Serial number	PF25NYFY
Experience	Windows 10 Feature Experience Pack 321.13302.10.3

**Comment by eed3si9n** [comment]
Not sure what concrete action we can take so I'm closing this.
