### ISSUE TITLE
sbt 1.4.0 'whatDependsOn' - java.util.NoSuchElementException: key not found

### ISSUE THREAD

**Issue by SJern** [sbt/sbt#6518]
## steps

Make a new sbt project using sbt 1.4.7, and add a dependency whose artifacts in a repository has been relocated from one groupId to a different groupId, then tried to use the whatDependsOn command

## problem

In my case, I got an error saying `java.util.NoSuchElementException: key not found: GraphModuleId(org.hibernate,hibernate-validator,7.0.1.Final)`

In fact, groupId `org.hibernate` has been relocated to groupId `org.hibernate.validator`
https://maven.apache.org/guides/mini/guide-relocation.html

## expectation

while `hibernate-validator-7.0.1.Final.jar` really does not exist under `org.hibernate`, but it does under `org.hibernate.validator`
The dependency plugin should be able to recognize that fact.

## notes
https://maven.apache.org/guides/mini/guide-relocation.html
https://mvnrepository.com/artifact/org.hibernate/hibernate-validator

**Comment by eed3si9n** [comment]
@SJern Thanks for the report. Could you provide reproduction steps so we can reproduce your problem on _our computers_? Also could you try with the current stable sbt 1.5.2 plz?

**Comment by SethTisue** [comment]
I suggest we close this as we don't have reproduction steps or confirmation that it's broken on current sbt.
