### ISSUE TITLE
scaladoc 2.0 diagram

### ISSUE THREAD

**Issue by MasseGuillaume** [sbt/sbt#652]
I know svg diagram was included in scaladoc 2.0 shipped with scala 2.10.

How can we use this feature from the doc task in sbt ?

**Comment by indrajitr** [comment]
`scalacOptions in doc += "-diagrams"` is what you are probably looking for.
As you would probably know, to see all the options that scaladoc supports `scaladoc -help` is you friend.

Feel encouraged to followup with further questions on the mailing list :)

**Comment by MasseGuillaume** [comment]
thanks !
