### ISSUE TITLE
sbt deploy/publish fails with java 12 enable preview feature | JavadocGenerationFailed

### ISSUE THREAD

**Issue by ghost** [sbt/sbt#6524]
Hi Team,

JDK: 12
SBT: 1.3.4
Scala: 2.12.9
Play : 2.7

sbt debian:deploy or debian:publish command also fails with the below error

```
[warn] Constructing Javadoc information...
[warn] error: classfile for XXXXXXX/Indexable.class uses preview features of Java SE 12.
[warn]   (use --enable-preview to allow loading of classfiles which contain preview features)
[warn] error: classfile for XXXXXXX/Client.class uses preview features of Java SE 12.
[warn]   (use --enable-preview to allow loading of classfiles which contain preview features)
[warn] error: classfile for XXXXXXX/ConfigOptional.class uses preview features of Java SE 12.
[warn] 15 errors.
[warn] javadoc exited with exit code 1
model contains 324 documentable templates
[info] Main Scala API documentation successful.
[error] sbt.inc.Doc$JavadocGenerationFailed
```

but we pass "--enable-preview" in **javacOptions & javaOptions** & setting **JAVA_OPTS**="--enable-preview". 

```
sbt.inc.Doc$JavadocGenerationFailed
[error] 	at sbt.inc.Doc$$anon$1.run(Doc.scala:72)
[error] 	at sbt.inc.Doc$$anon$2.run(Doc.scala:91)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5(Doc.scala:118)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5$adapted(Doc.scala:114)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.inc.Doc$$anon$3.run(Doc.scala:122)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1642)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:835)
[error] (search / Compile / doc) sbt.inc.Doc$JavadocGenerationFailed
```

Any suggestions?

_Originally posted by @Santhoshas in https://github.com/sbt/sbt/issues/5021#issuecomment-849574985_

**Comment by eed3si9n** [comment]
Thanks for the report. Could you provide reproduction steps so we can reproduce your problem on _our computers_?

**Comment by ghost** [comment]
Hi Team,

We are trying to upgrade our play modules to JDK 12 with the below versions

JDK: 12 
SBT: 1.3.4
Scala: 2.12.9
Play : 2.7

Below lines are added to **build.sbt** to avoid the below-mentioned issues. 

**Issue:** 
use --enable-preview to allow loading of classfiles which contain preview features

**Lines:**
+javacOptions ++= Seq("--enable-preview", "--release", "12")
+javaOptions ++= Seq("--enable-preview")

**sbt clean/compile** looks fine but when we execute **sbt debian:publish** on Jenkins/local, the build fails with the below-mentioned error. 

**Reason:** I think "javac --enable-preview" gets the parameter (compile step is fine) but the implicit javadoc (or scaladoc) in the deploy doesn't seem to get that argument.

**Comment by ghost** [comment]
> Thanks for the report. Could you provide reproduction steps so we can reproduce your problem on _our computers_?

Do you need any other details?

**Comment by eed3si9n** [comment]
I haven't tried to repro it, but hopefully it's enough info for someone to get started on it. 

The relevant area is likely https://github.com/sbt/zinc/blob/develop/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/javac/LocalJava.scala.

**Comment by ghost** [comment]
> I haven't tried to repro it, but hopefully it's enough info for someone to get started on it.
> 
> The relevant area is likely https://github.com/sbt/zinc/blob/develop/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/javac/LocalJava.scala.

Is it a bug from your end or something that needs to change on the application side? Can you please give some idea so that will proceed further?

**Comment by ghost** [comment]
Compile / doc / javacOptions ++= Seq("--enable-preview",  "--release", "12") solves the problem
