### ISSUE TITLE
[BSP] - `exit` notification not shutting down the server.

### ISSUE THREAD

**Issue by ckipp01** [sbt/sbt#6536]
## The problem

To be honest, I'm not 100% sure what the expected behavior should be in this scenario, but I'm trying to work an issue with Metals starting sbt as a BSP server and it still hanging around. My debugging led me to the the `exit` notification in sbt. To better outline the issue I'll explain below.

## Steps to reproduce

1. In a new minimal repo do a `sbt bspConfig` to ensure you have your `.bsp/sbt.json`.
2. Open metals in the repo, ignore the build import from Bloop, trigger a `Metals Switch Build Server` command, which differs a bit based on client. Select sbt
3.  At this point take a look at the processes that are running. You'll see something like this after Metals is connected to sbt.

```
❯ jps -l
79137 /Users/ckipp/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-sbt/sbt-launch/1.5.3/sbt-launch-1.5.3.jar
79136 xsbt.boot.Boot
79111 /Users/ckipp/.cache/nvim/nvim-metals/metals
79148 jdk.jcmd/sun.tools.jps.Jps
```

4. At this point, close Metals. You can tail the [lsp trace file](https://scalameta.org/metals/docs/contributors/getting-started.html#json-rpc-trace) to ensure that Metals correctly shuts down and sends the `exit` notification.
5. After the `exit` was sent and Metals is shut down, take another look at the processes.

```
❯ jps -l
79137 /Users/ckipp/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-sbt/sbt-launch/1.5.3/sbt-launch-1.5.3.jar
79157 jdk.jcmd/sun.tools.jps.Jps
```
This is where the main issue lies. You'll see the `sbt-launch.jar` still chilling there. If you also try to start `sbt` in this workspace you'll get a warning that there is already another server running there. In order to stop it, issue a `sbt --client shutdown`. You'll then see the warning will be gone if you try again and the `sbt-launch.jar` will be shutdown. At first I thought we weren't ending the process, but looking at the sbt code here:

https://github.com/sbt/sbt/blob/9e98b6daa1c5021b852661feb2a5b263bda9ce67/main/src/main/scala/sbt/internal/server/BuildServerProtocol.scala#L264-L265

It seems that upon receiving the `exit` notification that a `Shutdown` should be executed. Am I understanding that `Shutdown` correctly that it should be doing the same thing as the `sbt --client shutdown` that I do now to shut down the server? Or is that not expected and we should actually handle the full shutdown on the Metals side?

## expectation

I'd sort of expect that `Shutdown` to indeed shut down the server so it's not still hanging around

**Comment by adpi2** [comment]
Thank you @ckipp01 for reporting this with so much details!

It seems that there is something wrong in the sbt build server implementation because sbt expects a `build/exit` request whereas `build/exit` is a notification. So it never falls into the "shutdown" case.

However I don't think that Metals or any BSP client should be able to force sbt to shutdown. The current behavior is that sbt shuts down automatically if it has been idle for some time. The amount of time is defined in the `serverIdleTimeout` settings.

```text
sbt:root> show Global / serverIdleTimeout
[info] Some(7 days)
```

As you can see the default value is quite large and the reason for that is described in https://github.com/sbt/sbt/issues/6176#issuecomment-735046271. But it is possible to configure it globally in `~/.sbt/1.0`.

**Comment by ckipp01** [comment]
> It seems that there is something wrong in the sbt build server implementation because sbt expects a build/exit request whereas build/exit is a notification. So it never falls into the "shutdown" case.

ahhhh I totally missed that it was expected a request instead of a notification. Of course I miss the most obvious thing 😆 .

> serverIdleTimeout

I literally forget about this setting all the time. Actually I totally forgot about that entire conversation in https://github.com/sbt/sbt/issues/6176, so thanks for linking it,  that helps with the context and I remember now why there is a desire to keep it alive.

On a related note, it's a bit ironic that the two servers that Metals mainly works with don't want us to end the server process when the spec explicity says

> It is up to the client to decide when to start (process-wise) and when to shutdown a server.

Taken from [here](https://build-server-protocol.github.io/docs/specification.html#server-lifetime).
I'm wondering if we should adjust that to better reflect the reality that often the server may want to stick around even if the client is done with it. But that's probably a better convo to have in the BSP repo.

This is probably a better conversation in the BSP rep
https://build-server-protocol.github.io/docs/specification.html#server-lifetime
