### ISSUE TITLE
Ivy bug with specific dependencies

### ISSUE THREAD

**Issue by jdolson** [sbt/sbt#654]
Adding the following three dependencies

``` scala
libraryDependencies += "commons-io" % "commons-io" % "2.4"

libraryDependencies += "org.jbehave" % "jbehave-core" % "2.5.9" % "test"

libraryDependencies += "com.thoughtworks.xstream" % "xstream" % "1.3.1"
```

to an empty build.sbt file and running 'sbt update' causes a crash with the error message:

```
[error] impossible to get artifacts when data has not been loaded. IvyNode = commons-io#commons-io;1.4
java.lang.IllegalStateException: impossible to get artifacts when data has not been loaded. IvyNode = commons-io#commons-io;1.4
```

Remove any one of these dependencies or remove the "test" configuration on jbehave and update work fine. Also, Mark pointed out that one can add an exclude("commons-io", "commons-io") to the jbehave dependency to make things work.

Tested with both 0.12.1 and 0.12.2.

**Comment by hamnis** [comment]
https://issues.apache.org/jira/browse/IVY-1333

This still happens in sbt 0.13.5

**Comment by unoexperto** [comment]
Any progress on this ? Still happens on 0.13.6

**Comment by eed3si9n** [comment]
We are using Ivy 2.3.0, which should have IVY-1333 fixed. If it's still happening, I'd say this is something that needs to be dealt with using `dependencyOverrides`. See http://www.scala-sbt.org/0.13/docs/Library-Management.html#Overriding+a+version
