### ISSUE TITLE
println("Hello\r\nWorld") not working as expected

### ISSUE THREAD

**Issue by sebastian-alfers** [sbt/sbt#6540]
## steps

Starting from `1.4.4`, sbt swallows ([this](https://github.com/sbt/sbt/commit/f3120f8f159b87cee8d17f1462e4b72bda3dc2ad) change) the first part of the expression above.

Given the following executed via `sbt run`:

```
println("Hello\r\nWorld")
```

## problem

Wrong output in `>=1.4.4`

```
$ sbt run
[info] welcome to sbt 1.4.4 (AdoptOpenJDK Java 11.0.7)
...
[info] running Main

World
```

## expectation

Expected output in `<=1.4.3`
```
$ sbt run
[info] welcome to sbt 1.4.3 (AdoptOpenJDK Java 11.0.7)
...
[info] running Main
Hello
World
```

## notes

Happy to start fixing it once confirmed this is an actual bug.

**Comment by eed3si9n** [comment]
I confirm it's a 🐛, and agree with your expectation.

**Comment by sebastian-alfers** [comment]
@eed3si9n Was this fixed in [1.5.5](https://github.com/sbt/sbt/releases/tag/v1.5.5)?

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/6556?

**Comment by sebastian-alfers** [comment]
Jepp :)
