### ISSUE TITLE
Include/exclude of plugins sub-projects for SBT BSP

### ISSUE THREAD

**Issue by dkovalenko** [sbt/sbt#6546]
**STR:**
- I have sbt multiproject with scapegoat autoplugin added.
- I use SBT as a BSP server with metals in VSCode.
**AR**:
- When I edit source code project-scapegoat is recompiled every time
**ER**:
- When I edit source code scapegoat don't start compilation. I should trigger scapegoat manually when I need it. 

![image](https://user-images.githubusercontent.com/874918/122037515-5146e800-cddd-11eb-92c1-7c6e4eea4cbc.png)

Maybe we can add some kind of include/exclude list of plugins sub-projects to export to metals?

In projects with many modules and plugins I have this situation:

![telegram-cloud-photo-size-4-5843805723996305105-y_partial](https://user-images.githubusercontent.com/874918/122037719-881cfe00-cddd-11eb-84da-e975abe2bc91.jpg)
Using SBT BSP in this project is a nightmare because many plugins can kick in after source code change.

My biggest concern is with sbt-scapegoat because it kicks in before the main compilation and takes a lot of time.
![image](https://user-images.githubusercontent.com/874918/122038919-c830b080-cdde-11eb-9e13-2a449c85d21c.png)

If I switch to bloop as BSP, I don't see all these sub-projects from plugins and compilation is much faster.

**Comment by adpi2** [comment]
Thank you for opening this issue.

There is a setting `bspEnabled` to enable/disable BSP on a particular project or configuration.

Something like this should work:
```scala
val myProject = project.in(file(..))
  .settings(
    Scalafix / bspEnabled := false,
    Gatling / bspEnabled := false,
    Scapegoat / bspEnabled := false
  )
```

Ideally this setting should be set on the plugin itself so that users don't have to worry about it. But since it is not backward compatible with sbt 1.3.x, many plugin don't have it yet.

**Comment by dkovalenko** [comment]
Thanks!

**Comment by cquiroz** [comment]
I'm trying this fix but I'm getting this error which I cannot decipher
```
/Users/cquiroz/Projects/explore/build.sbt:59: error: value / is not a member of sbt.Tags.Tag
    Scalafix / bspEnabled := false,
```

**Comment by adpi2** [comment]
@cquiroz, actually the identifier of the Scalafix config is `ScalafixConfig`:

```scala
ScalafixConfig / bspEnabled := false,
```

**Comment by cquiroz** [comment]
Thanks, that works, otherwise I see a message that it tries to compiles a scalafix target forever

**Comment by adpi2** [comment]
I'll push a request to deactivate that by default in the sbt-scalafix plugin directly. It will be easier for everybody.
