### ISSUE TITLE
sbt thin client with batch mode gets stuck into an infinite loop when build can't be loaded

### ISSUE THREAD

**Issue by max-peroch** [sbt/sbt#6547]
## steps

With sbt version 1.5.4:
- Add `-batch` to `.sbtopts` or `/etc/sbt/sbtopts`
- Add a key that doesn't exist in a build.sbt, or a plugin that has a broken version.
- Run:
> sbt --client compile

or
> SBT_NATIVE_CLIENT=true sbt compile

## problem

The thin client starts, then fails to load the project and gets stuck into an infinite loop of:
```
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
Invalid response: 'ÿ'
```

## expectation

Shutdown the sbt client without expecting an user input.

## notes

We encountered this issue when a bot that automates our dependency updates bumped a version of a plugin with an invalid POM. The plugin couldn't be resolved, which is expected, but our CI job got stuck until timeout.
Here is a small project to easily reproduce the issue if needed https://github.com/max-peroch/sbtn-batch-bug

**Comment by adpi2** [comment]
Thank you @max-peroch for opening this issue!

I tried also with `sbtn` (installed with `cs install sbtn`) and it does not seem to work either because in this case the `-batch` option is not taken into account.

**Comment by simlei** [comment]
Also experiencing this; a fix would be appreciated

**Comment by simlei** [comment]
In the meanwhile, I'm running sbt client like this:
`sbt --client <cmd> < <(echo q)`

This passes the "q" to such an interactive prompt before any of these `ÿ` get read. Of course, this is not a very satisfactory solution but for me it bridges this over until the issue is resolved.

**Comment by max-peroch** [comment]
@adpi2 any idea where the issue would be located/what's going on? I'm happy to try and have a look if you want, but I have absolutely no prior experience or knowledge of the launcher

**Comment by max-peroch** [comment]
Thanks a lot! 😊
