### ISSUE TITLE
[BSP] - IntegrationTest configuration not tagged as test

### ISSUE THREAD

**Issue by github-samuel-clarenc** [sbt/sbt#6548]
## steps

A simple SBT (1.5.4) / Scala (2.13.6) project imported with [BSP](https://github.com/build-server-protocol/build-server-protocol) with an `IntegrationTest` config.

## problem

SBT does not tag the build target with as a "test" nor "integration-test" workspace. 

When calling BSP with the following command : 
```
{ "jsonrpc": "2.0", "id": 1, "method": "workspace/buildTargets" }
```

The attribute "tags" returns an empty array : 

```
{"id":{"uri":"file:bspSingleIntegrationTest/#module/IntegrationTest"},"displayName":"module-it","baseDirectory":"file:bspSingleIntegrationTest/module/","tags":[],"capabilities":{"canCompile":true,"canTest":true,"canRun":true},"languageIds":["scala"],...}
```

## expectation

The workspace should be tagged with "integration-test" (or at least with "test") to make Intellij Idea can mark it as a test folder. 

## notes

Linked to intellij-scala plugin PR : https://github.com/JetBrains/intellij-scala/pull/592

A simple solution would be to add a case in [BuildTargetTag](https://github.com/sbt/sbt/blob/eec3c32cc841365799eaa5460272e8287b975f10/protocol/src/main/scala/sbt/internal/bsp/BuildTargetTag.scala#L19) like this : 

```
    case "it"      => Vector(test, integrationTest)
```

The main question here would be : do we need the "test" tag, or "integration-test" ou both ? 

As a workaround, the configuration can be done manually in sbt this way : 

```
IntegrationTest/bspBuildTarget := (IntegrationTest/bspBuildTarget).value.withTags(Vector("integration-test"))
```

**Comment by adpi2** [comment]
@samuelClarencTeads thanks for opening this issue!

It seems you have a good idea of what the fix should be. So it would help us a lot if you could open a pull request?

Also I think the "integration-test" tag alone should be enough, since it is defined as a default BSP tag in the [specification](https://build-server-protocol.github.io/docs/specification.html#build-target).

**Comment by github-samuel-clarenc** [comment]
I opened a PR : https://github.com/sbt/sbt/pull/6551 but I signed the CLA after opening it : do I need to close this one and open a new one ?
