### ISSUE TITLE
[BSP] Implement buildTarget/resources

### ISSUE THREAD

**Issue by github-samuel-clarenc** [sbt/sbt#6550]
## steps

Import a project with resource files in `src/main/resources` on Intellij Idea using SBT via BSP. 

## problem

The BSP specification provides a [buildTarget/resources](https://github.com/build-server-protocol/build-server-protocol/blob/master/docs/specification.md#resources-request) that allows getting the resources for a build target. 

The [BspProjectResolver](https://github.com/JetBrains/intellij-scala/blob/idea212.x/bsp/src/org/jetbrains/bsp/project/importing/BspProjectResolver.scala#L280) on intellij side needs this query to complete its build target data with resources. 

The [BuildServerProtocol handler](https://github.com/sbt/sbt/blob/develop/main/src/main/scala/sbt/internal/server/BuildServerProtocol.scala#L225) on SBT side does not implement the `buildTarget/resources` query. 

## expectation

`buildTarget/resources` query should be implemented in [BuildServerProtocol handler](https://github.com/sbt/sbt/blob/develop/main/src/main/scala/sbt/internal/server/BuildServerProtocol.scala#L225)

## notes
_(I can open a pull request to fix this issue if needed)_

**Comment by github-samuel-clarenc** [comment]
It seems to work with [bloop](https://github.com/scalacenter/bloop) as BSP implementation : https://github.com/scalacenter/bloop/pull/946

**Comment by adpi2** [comment]
Again, thank you for opening this issue!

A PR would very much appreciated.

**Comment by github-samuel-clarenc** [comment]
The following [PR](https://github.com/sbt/sbt/pull/6552) is a proposal for the [buildTarget/resources](https://build-server-protocol.github.io/docs/specification#resources-request) implementation !
