### ISSUE TITLE
sbt uses setSecurityManager which is now deprecated on JDK 17

### ISSUE THREAD

**Issue by SethTisue** [sbt/sbt#6558]
```
% git grep setSecurity
run/src/main/scala/sbt/TrapExit.scala:      case m           => System.setSecurityManager(new TrapExit(m)); m
run/src/main/scala/sbt/TrapExit.scala:    System.setSecurityManager(previous)
```

I noticed this in the context of https://github.com/scala/community-build/issues/1432

**Comment by SethTisue** [comment]
note that this isn't merely an issue when compiling sbt itself; users see a warning printed at runtime:

```
~/akka % sbt
WARNING: java.lang.System::setSecurityManager is deprecated and will be removed in a future release.
[info] welcome to sbt 1.5.4 (Oracle Corporation Java 17-ea)
...
```

**Comment by eed3si9n** [comment]
Yea. This has been foretold by Yoshida-san - https://twitter.com/xuwei_k/status/1382935881418383361

**Comment by DieBauer** [comment]
Just a heads-up with the GA of Java 17, still present and potentially off-putting. 

```
sbt
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by sbt.TrapExit$ (file:/Users/DieBauer/.sbt/boot/scala-2.12.14/org.scala-sbt/sbt/1.5.5/run_2.12-1.5.5.jar)
WARNING: Please consider reporting this to the maintainers of sbt.TrapExit$
WARNING: System::setSecurityManager will be removed in a future release
[info] welcome to sbt 1.5.5 (Oracle Corporation Java 17)
```

**Comment by jtjeferreira** [comment]
AFAICT there is not way to disable that warning (otherwise we could change the sbt launcher with some option to disable it).

The eventual alternative will be https://bugs.openjdk.java.net/browse/JDK-8199704...

**Comment by numero-744** [comment]
Update: It seems that Java 18 finally removed SecurityManager. The warning turned into a hard error.

After an update yesterday, I get this:

```
% java --version
openjdk 18.0.1.1 2022-04-22
OpenJDK Runtime Environment (build 18.0.1.1+2)
OpenJDK 64-Bit Server VM (build 18.0.1.1+2, mixed mode)
% sbt --version 
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
        at java.base/java.lang.System.setSecurityManager(System.java:416)
        at sbt.TrapExit$.installManager(TrapExit.scala:54)
        at sbt.StandardMain$.runManaged(Main.scala:187)
        at sbt.xMain$.$anonfun$run$8(Main.scala:102)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withIn(Console.scala:230)
        at sbt.internal.util.Terminal$.withIn(Terminal.scala:560)
        at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:350)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withOut(Console.scala:167)
        at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:550)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withErr(Console.scala:196)
        at sbt.internal.util.Terminal$.withOut(Terminal.scala:550)
        at sbt.internal.util.Terminal$.withStreams(Terminal.scala:350)
        at sbt.xMain$.run(Main.scala:86)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:83)
        at sbt.xMain.run(Main.scala:46)
        at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
        at xsbt.boot.Launch$.run(Launch.scala:149)
        at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
        at xsbt.boot.Launch$.launch(Launch.scala:159)
        at xsbt.boot.Launch$.apply(Launch.scala:44)
        at xsbt.boot.Launch$.apply(Launch.scala:21)
        at xsbt.boot.Boot$.runImpl(Boot.scala:78)
        at xsbt.boot.Boot$.run(Boot.scala:73)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
[error] [launcher] error during sbt launcher: java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
sbt script version: 1.6.0
```

I cannot use `sbt` anymore :disappointed:

**Comment by SethTisue** [comment]
@numero-744 even in an empty directory? at https://github.com/lampepfl/dotty/issues/14814#issuecomment-1135267898 , someone reported the same thing, then withdrew it with "never mind, i was somehow still running an old version of sbt"

I'm not able to reproduce the problem locally (on "OpenJDK 64-Bit Server VM Temurin-18.0.1+10 (build 18.0.1+10, mixed mode")

**Comment by SethTisue** [comment]
@numero-744 I suspect you ran that in a directory containing a `project/build.properties` file specifying an old version of sbt

the `sbt` command is just a little wrapper script that retrieves and runs whatever sbt version that file specifies

**Comment by numero-744** [comment]
Thanks for the fast answers :)

I have updated `project/build.properties` and it is okay now. Also note that it did work from an empty folder.

**Comment by godenji** [comment]
**EDIT2**
Actually, even in a bare project with just `build.sbt`, `project/build.properties` and empty `src/main/scala` I get the Security Manager exception.

This is with scala 2.13.8 and sbt 1.7.0-M2.

How can I get Scala 2.13 projects working with sbt on Java 18??

**EDIT**
Found it, minimum Scala 2.13.7 required for Java 18+

**ORIGINAL**
uname -a
> Linux localhost.localdomain 5.15.11-200.fc35.x86_64 (Fedora 35)

java -version
> openjdk version "18.0.1" 2022-04-19

cat project/build.properties 
> 1.7.0-M2

sbt
> java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release

FWIW, I don't have this issue in Scala 3 projects, just this one using Scala 2.13.6

Is there a cache that needs to be cleared? Blew away `project/project` and `project/target` to no effect.

**Comment by eed3si9n** [comment]
The latest stable version of sbt is sbt 1.6.2 available from https://www.scala-sbt.org/download.html
sbt 1.6.2 works fine on my machine.

```
$ sbt --script-version
1.6.2
$ java -version
openjdk version "18.0.1" 2022-04-19
OpenJDK Runtime Environment Temurin-18.0.1+10 (build 18.0.1+10)
OpenJDK 64-Bit Server VM Temurin-18.0.1+10 (build 18.0.1+10, mixed mode, sharing)
$ sbt
copying runtime jar...
[info] welcome to sbt 1.6.2 (Eclipse Adoptium Java 18.0.1)
[info] loading settings for project global-plugins from idea.sbt,pgp.sbt,plugins.sbt,vimquit.sbt ...
[info] loading global plugins from /Users/eed3si9n/.sbt/1.0/plugins
[info] loading project definition from /private/tmp/hello/project
[info] compiling 1 Scala source to /private/tmp/hello/project/target/scala-2.12/sbt-1.0/classes ...
[info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.15. Compiling...
[info]   Compilation completed in 8.934s.
[info] loading settings for project root from build.sbt ...
[info] set current project to hello (in build file:/private/tmp/hello/)
[info] sbt server started at local:///Users/eed3si9n/.sbt/1.0/server/478e6db75688771ddcf1/sock
[info] started sbt server
sbt:hello> run
[info] compiling 1 Scala source to /private/tmp/hello/target/scala-2.13/classes ...
[info] Non-compiled module 'compiler-bridge_2.13' for Scala 2.13.8. Compiling...
[info]   Compilation completed in 8.984s.
[info] running example.Hello
hello
[success] Total time: 10 s, completed May 28, 2022, 12:31:09 PM
sbt:hello> exit
[info] shutting down sbt server
```

**Comment by godenji** [comment]
Thanks, same result with 1.6.2.

And now I see why: `/bin/sbt-launch.jar` is out of date.

Sorry for the noise, all set now...

**Comment by SelinGungor** [comment]
Upgrading the sbt version to `1.6.2` from `1.4.9` in the `build.properties` file fixed my problem.

**Comment by ProjectDimlight** [comment]
Sorry but I upgraded my sbt to 1.7.1 but the error remains.
I am considering downgrading my jdk right now..

**Comment by eed3si9n** [comment]
As Seth pointed out sbt launcher uses `project/build.properties` to determine the actual sbt version, so please make sure you update it to the latest.

**Comment by SethTisue** [comment]
workaround: pass `-Djava.security.manager=allow` when starting the JVM, e.g. with `sbt -Djava.security.manager=allow` or by adding it to `.jvmopts`

if you try the `.jvmopts` route and it doesn't work, check your launch script, maybe it's too old

**Comment by SethTisue** [comment]
I'm going to cautiously unlock this thread. But please, anyone, before commenting, please carefully read what's already written above and make sure that what you have to say hasn't already been covered.

**Comment by SethTisue** [comment]
workaround that I have found to work with sbt 0.13.18: as per https://openjdk.org/jeps/411 , pass `-Djava.security.manager=allow` when starting the JVM, e.g. with `sbt -Djava.security.manager=allow` or by adding it to `.jvmopts`

if you try the `.jvmopts` route and it doesn't work, check your launch script, maybe it's too old

note that `-Djava.security.manager=allow` isn't accepted on JDK 8 or 11, though; it is accepted on 17

**Comment by SethTisue** [comment]
Note that `-Djava.security.manager=allow` works on JDK 17, but does not work anymore on 21.

(I think it was disabled starting on 18? I mainly care about LTS versions.)

I do not know any workaround on 21.

**Comment by SethTisue** [comment]
`-Djava.security.manager=allow` still works on JDK 21.

Note that some old sbt launchers don't understand `-D` and require `-J-D` instead, so: `-J-Djava.security.manager=allow`

```scala
% cat S.scala
object O extends App { println("hi there") }
% usejava21
openjdk version "21.0.1" 2023-10-17 LTS
OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (build 21.0.1+12-LTS, mixed mode)
% ./sbt-0.13.18/bin/sbt -J-Djava.security.manager=allow run
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by sbt.TrapExit$ (file:/Users/tisue/.sbt/boot/scala-2.10.7/org.scala-sbt/sbt/0.13.18/run-0.13.18.jar)
WARNING: Please consider reporting this to the maintainers of sbt.TrapExit$
WARNING: System::setSecurityManager will be removed in a future release
[warn] No sbt.version set in project/build.properties, base directory: /Users/tisue/tmp/sbt-0.13.18
[info] Set current project to sbt-0-13-18 (in build file:/Users/tisue/tmp/sbt-0.13.18/)
[info] Running O 
hi there
[success] Total time: 0 s, completed Oct 29, 2023, 2:46:56 PM
```
