### ISSUE TITLE
Contradiction in the docs

### ISSUE THREAD

**Issue by markisus** [sbt/sbt#657]
http://www.scala-sbt.org/release/docs/Getting-Started/Basic-Def.html

"You can use either one exclusively, or use both. A good approach is to use .sbt files for most purposes, and use .scala files only to contain what can't be done in .sbt..."

The second sentence explains that .scala files can do some things that .sbt files can't. Therefore I can't exclusively use .sbt files like the first sentence said.

Can you just delete the first sentence?

**Comment by harrah** [comment]
This line is no longer in 0.13 docs, so closing.
