### ISSUE TITLE
BSP: support task progress

### ISSUE THREAD

**Issue by jastice** [sbt/sbt#6570]
BSP supports [task progress notifications](https://build-server-protocol.github.io/docs/specification.html#task-progress). Bloop already supports these for target compile progress. Would be nice if sbt would do this as well where possible / for long running tasks.

**Comment by hmemcpy** [comment]
I'd like to work on this, but at the moment struggling to find a good way to hook into progress. It seems that bloop is talking to zinc directly, and utilizing the `xsbti.CompileProgress` for reporting. Unless I misunderstand, sbt seems to launch scalac directly (via `compileIncrementalTaskImpl`), and it doesn't seem to provide a progress reporter.

Any advice?

**Comment by adpi2** [comment]
In `compileIncrementalTaskImpl`:
https://github.com/sbt/sbt/blob/a199875e1dcb16cd92a439b47379954daff1a995/main/src/main/scala/sbt/Defaults.scala#L2357

`incCompiler` is the Zinc compiler and `i` contains the Zinc setup which contains an optional `CompileProgress` instance. This `compileProgress` is configured by the `compileProgress` task declared here:
https://github.com/sbt/sbt/blob/a199875e1dcb16cd92a439b47379954daff1a995/main/src/main/scala/sbt/Keys.scala#L233
and defined here:
https://github.com/sbt/sbt/blob/a199875e1dcb16cd92a439b47379954daff1a995/main/src/main/scala/sbt/Defaults.scala#L907-L919

So probably this implementation needs to be adapted to redirect some compilation progress notification to the BSP clients.

**Comment by hmemcpy** [comment]
Oh, that's great! Thank you, I'll poke around!

**Comment by hmemcpy** [comment]
Me again, back from the poking around :)

The missing endpoint, `build/taskProgress` is part of the [task notifications](https://build-server-protocol.github.io/docs/specification.html#task-progress) API, and requires (at the very least) a unique `taskId`, so doing this work in the `compileProgress` task doesn't seem like a great idea... 

I was thinking of refactoring `BspCompileTask` to handle this, by doing the following:
1. Expose the actual task to the compilation step (pass as an argument to `compileIncrementalTaskImpl`, i.e. `compile: BspCompileTask => CompileResult`)
2. Move the `notify*` methods into the task instance, make them public (or at least `private[sbt]`)
3. Hook into `CompileProgress#advance` shortly before calling the incremental compiler, and report progress on a new `task.notifyProgress(progress, total)`

WDYT? Any better idea is appreciated!

**Comment by hmemcpy** [comment]
Success :)
![image](https://user-images.githubusercontent.com/601206/131221999-bfe7cb1e-4b0b-4189-85f7-d32dd6cbe88b.png)
