### ISSUE TITLE
.sbtopts doesn't get picked up when sbt server gets started by Metals

### ISSUE THREAD

**Issue by Jasper-M** [sbt/sbt#6575]
If I manually start sbt and then start vscode everything works fine. But if I start vscode first and Metals starts the sbt server, the JVM options from the `.sbtopts` file in my project folder don't seem be used.

This is the _.bsp/sbt.json_ file that sbt generates:
```
{"name":"sbt","version":"1.5.2","bspVersion":"2.0.0-M5","languages":["scala"],"argv":["/Users/jasper.moeys/.sdkman/candidates/java/11.0.11.hs-adpt/bin/java","-Xms100m","-Xmx100m","-classpath","/Users/jasper.moeys/.sdkman/candidates/sbt/1.5.1/bin/sbt-launch.jar","xsbt.boot.Boot","-bsp","--sbt-launch-jar=/Users/jasper.moeys/.sdkman/candidates/sbt/1.5.1/bin/sbt-launch.jar"]}
```

This is on OS X. I think this did work on Ubuntu a while ago, but then that was with different versions of sbt, vscode and metals.

@tgodzik

**Comment by adpi2** [comment]
That's related to #6476 and #6468.

I think we should fix this by giving the `NetworkClient` class the ability to read the `.sbtopts` and `.jvmopts` files (also the JVM_OPTS and SBT_OPTS env var) when the `--sbt-launch-jar` is given.

**Comment by eed3si9n** [comment]
When `sbt` shell script is not on IntelliJ PATH (https://github.com/sbt/sbt/issues/6176) it makes sense to downgrade to `java -jar sbt-launch.jar`, but when using from Metals, why not use `sbt` if it's on PATH?

**Comment by adpi2** [comment]
The idea of the `.bsp/sbt.json` discovery file is that it could be used by any build client. So when we generate it we don't know if it will be used by Metals, IntelliJ or both. Also, having it completely independent of the environment is a good way to start the server consistently every time: same java version, same launcher, same options.
