### ISSUE TITLE
The "Learn" section of the sbt site doesn't display properly because of the header

### ISSUE THREAD

**Issue by ColourGrey** [sbt/sbt#6579]
The "Learn" section of the sbt site doesn't display properly, the upper part of what is visible of the web page being obscured by the header. The content is displayed fine if the page is shrunk at 90%. The behaviour is identical in the latest versions of Firefox and Microsoft Edge, so it's not a web engine bug.

The attached file "bad.png" shows the problem (upper part of the image, right under the address bar).
<img width="960" alt="bad" src="https://user-images.githubusercontent.com/57685970/124353502-95285280-dc0f-11eb-90a5-6be0dee76601.png">
 The file "good.png" shows the page displayed properly if shrunk.
<img width="960" alt="good" src="https://user-images.githubusercontent.com/57685970/124353505-96f21600-dc0f-11eb-84ea-26da4cbe3a8e.png">

**Comment by eed3si9n** [comment]
@concastinator Thanks for the report!

**Comment by eed3si9n** [comment]
To put some numbers on this situation, once the screen width is below 800px width Pamflet would hide the nav bars, so it fixes itself. On Chrome using macOS, the nav bar folding happens exactly at 1295px. So any devices with screen resolution between 800px and 1295px are affected.
