### ISSUE TITLE
Where is the documentation to use Scala as build configuration language? I don't want to learn sbt-ish.

### ISSUE THREAD

**Issue by bledari** [sbt/sbt#6581]
[this](https://www.scala-sbt.org/1.x/docs/Scala-Files-Example.html) is not comprehensive at all

**Comment by eed3si9n** [comment]
You can't use sbt without build.sbt DSL.

**Comment by SethTisue** [comment]
The closest you can come is to declare your subprojects in `build.sbt` but put everything else in `project/*.scala`. An example of a build done this way is https://github.com/scalatest/scalatest/blob/3.2.x-new/build.sbt

**Comment by SethTisue** [comment]
> this is not comprehensive

is there something in particular you can't figure out how to do?

**Comment by bledari** [comment]
@SethTisue I would make sense to me to just be able to take a look at the API and extend the Project trait and implement the stuff needed etc etc. Maybe the API could have some examples and boom you can do anything, no fancy DSL needed if you don't have time to learn all that stuff. 

@eed3si9n and why is that? Everyone complains about the "magic" of sbt DSL. So I guess a discussion is needed here, instead of closing this issue just because you can

**Comment by bledari** [comment]
@SethTisue on a more practical level I just can't find a way to make sbt aspectj plugin to pick up some calls on a library I'm using, only on project source code. Also it works only through sbt console, IntelliJ doesn't know about anything sadly

**Comment by SethTisue** [comment]
> I just can't find a way to make sbt aspectj plugin to pick up some calls on a library I'm using

Seems like getting into details on that would take this ticket too far afield. But, have you asked the question elsewhere?

**Comment by bledari** [comment]
https://github.com/sbt/sbt-aspectj/issues/48 (yet another project without good docs). Some solutions might work for old versions of sbt, hence I think the problem is sbt syntax since one can not figure out in a simple way how to do whatever from just looking at the API and some docs. So I guess I'll figure it out in sbt or other build tools (looking around by taking this as a test case)
