### ISSUE TITLE
Installing from Bintray results in 403 Forbidden

### ISSUE THREAD

**Issue by badrinathpatchikolla** [sbt/sbt#6582]
Trying to download SBT : 

Command Used : 
```
curl https://bintray.com/sbt/rpm/rpm | sudo tee /etc/yum.repos.d/bintray-sbt-rpm.repo
```
Error :

```Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/home/badri/.wget-hsts'. HSTS will be disabled.
--2021-07-05 14:33:26--  https://dl.bintray.com/sbt/native-packages/sbt/0.13.15/sbt-0.13.15.tgz
Resolving dl.bintray.com (dl.bintray.com)... 52.88.131.165, 34.210.204.177
Connecting to dl.bintray.com (dl.bintray.com)|52.88.131.165|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-07-05 14:33:28 ERROR 403: Forbidden.
```

**Comment by Stofkat** [comment]
We're experiencing the same issue with
`https://dl.bintray.com/sbt/debian/InRelease`

`--2021-07-05 11:40:27--  https://dl.bintray.com/sbt/debian/InRelease
Resolving dl.bintray.com (dl.bintray.com)... 3.124.176.138, 35.157.24.53
Connecting to dl.bintray.com (dl.bintray.com)|3.124.176.138|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-07-05 11:40:27 ERROR 403: Forbidden.
`

**Comment by jeremlvt** [comment]
Same issue here on my runner, so I checked bintray status... It seems to have been shutdown yesterday.

https://status.bintray.com/

**Comment by IvanHarbr** [comment]
Same issue here:

```


Reading package lists...
--
84 | E: Failed to fetch https://dl.bintray.com/sbt/debian/InRelease  403  Forbidden [IP: 3.124.176.138 443]
85 | E: The repository 'https://dl.bintray.com/sbt/debian  InRelease' is no longer signed.
86 |  
87 | [Container] 2021/07/05 11:50:57 Command did not exit successfully apt-get update exit status 100
88 | [Container] 2021/07/05 11:50:57 Phase complete: INSTALL State: FAILED
89 | [Container] 2021/07/05 11:50:57 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: apt-get update. Reason: exit status 100


```

**Comment by jeremlvt** [comment]
I fixed it by using SDKMan as explained on this page : https://www.scala-sbt.org/1.x/docs/Installing-sbt-on-Linux.html

If, like me, you are using it inside a Gitlab runner, you can use these commands to install SDKMan : 

```yaml
   - apt-get update -qq && apt-get install -y -qq unzip zip curl
   - curl -sSL https://get.sdkman.io | bash
   - echo sdkman_auto_answer=true > /root/.sdkman/etc/config
   - source /root/.sdkman/bin/sdkman-init.sh
```

and then install SBT according to the documentation.

**Comment by eed3si9n** [comment]
https://eed3si9n.com/bintray-to-jfrog-artifactory-migration-status-and-sbt-1.5.1

We also have an Artifactory instance that distribute the DEB package.
