### ISSUE TITLE
Incorrectly calculated binary scala versions for scala 3

### ISSUE THREAD

**Issue by prolativ** [sbt/sbt#6585]
## problem

`binaryScalaVersion` in librarymanagement doesn't always calculate the version correctly for scala 3, e.g. (input -> output):
`3.0.1-bin-nonbootstrapped` -> `3.0.1null`
`3.0.1-SNAPSHOT` -> `3.0.1-SNAPSHOT`
The problem seems not to occur for milestones and release candidate versions.

## expectation

The binary version of all scala versions later that `3.0.0` should be `3`

## notes

This affects the release of scala 3.0.1

**Comment by adpi2** [comment]
Thanks @prolativ! I am taking a look.
