### ISSUE TITLE
missing version 1.0.0 of jse_2.10, webdriver_2.10 and npm_2.10 required by sbt-plugin:2.3.9 in sbt 0.13.18

### ISSUE THREAD

**Issue by philipschwarz** [sbt/sbt#6586]
Hello,

I tried asking the question on https://stackoverflow.com/questions/tagged/sbt, but submitting the question kept failing due to an alleged code formatting error accompanied by a less-than-useful error message that made diagnosing the problem near-impossible. So I am creating an issue here.

I have come across a stone-age Scala sbt build that uses sbt 0.13.18 and sbt Play plugin 2.3.9, but fails as follows:

[![enter image description here][1]][1]

The dependences are required by sbt-plugin 2.3.9, e.g.:

[![enter image description here][2]][2]

Questions:

 1. Does anyone know a repo where the dependencies can be found?  
 2. The dependencies are needed by a plugin (the Play sbt-plugin), rather
    than by application code, so once I find a repo that hosts the JARs
    how do I change the build so that the plugin in question has access
    to them?

It may be that the problem started with Bintray's sunsetting: https://eed3si9n.com/bintray-to-jfrog-artifactory-migration-status-and-sbt-1.5.1.

I see that https://cloudsmith.com/ says it makes the dependencies available:
 
https://cloudsmith.io/~lightbend/repos/maven-releases/packages/detail/maven/webdriver_2.10/1.0.0/a=noarch;xg=com.typesafe/#install
https://cloudsmith.io/~lightbend/repos/maven-releases/packages/detail/maven/jse_2.10/1.0.0/a=noarch;xg=com.typesafe/#package-install-sbt
https://cloudsmith.io/~lightbend/repos/maven-releases/packages/detail/maven/npm_2.10/1.0.0/a=noarch;xg=com.typesafe/#install

But https://dl.cloudsmith.io/public/lightbend/maven-releases/maven/ responds with a 404

https://status.cloudsmith.io/history says Cloudsmith had connectivity issues a few days ago (on Jul 5th 2021) but there is no mention of any problems today (8th Jul 2021).

Maven Central only hosts more recent versions of the dependencies:
https://repo.maven.apache.org/maven2/com/typesafe/jse_2.10/
https://repo.maven.apache.org/maven2/com/typesafe/npm_2.10/
https://repo.maven.apache.org/maven2/com/typesafe/webdriver_2.10/

While it appears that e.g. webdriver_2.10 1.0.0 should be available here https://mvnrepository.com/artifact/com.typesafe/webdriver_2.10/1.0.0 the associated url for that is https://repo.typesafe.com/ but visiting it results in the following, and the JARs cannot be found at any of the mentioned URLs:

[![enter image description here][3]][3]

Resolver.typesafeIvyRepo("releases") https://repo.typesafe.com/typesafe/ivy-releases/
Resolver.typesafeRepo("releases") https://repo.typesafe.com/typesafe/maven-releases/

  [1]: https://i.stack.imgur.com/ah9Ku.png
  [2]: https://i.stack.imgur.com/vkljp.png
  [3]: https://i.stack.imgur.com/GY5qk.png

**Comment by eed3si9n** [comment]
Thanks for the report.
Could you let Lightbend IT folks know about this on https://discuss.lightbend.com/t/typesaferepo-https-repo-typesafe-com-typesafe-releases-is-returning-a-404-error/8156/9 please?

**Comment by philipschwarz** [comment]
Yes, I will do that. 

Thank you for the suggestion @eed3si9n

**Comment by philipschwarz** [comment]
I am glad to report that I have rationalised the build so that it uses the following resolvers, and now there is no longer a problem: repo.lightbend.com , repo.scala-sbt.org

**Comment by eed3si9n** [comment]
I'm closing this for now then. Hopefully they'll reply to you on the other thread.

**Comment by philipschwarz** [comment]
@eed3si9n 👍 thanks
