### ISSUE TITLE
sbt 1.5.5 launcher defaults to sbt 1.5.4

### ISSUE THREAD

**Issue by francisdb** [sbt/sbt#6594]
## steps

see https://github.com/hseeberger/scala-sbt/runs/3048236449?check_suite_focus=true

once the image is built it runs `sbt about` in the home directory which seems to fetch 1.5.4

```
[info] [launcher] getting org.scala-sbt sbt 1.5.4  (this may take some time)...
[info] [launcher] getting Scala 2.12.14 (for sbt)...
[info] Updated file /home/runner/work/scala-sbt/scala-sbt/project/build.properties: set sbt.version to 1.5.4
[info] welcome to sbt 1.5.4 (AdoptOpenJDK Java 11.0.11)
```

## expectation

I would expect sbt `1.5.5` to be used as default as that was downloaded from `https://github.com/sbt/sbt/releases/download/v1.5.5/sbt-1.5.5.tgz`

## notes

```bash
➜  sbt cat ./bin/sbt | grep 1.5
declare builtin_sbt_version="1.5.4"
declare init_sbt_version=1.5.5
```

**Comment by eed3si9n** [comment]
@francisdb Thanks for the report.

I think I have a bug in my build automation that runs as GitHub Action:

```sh
buildLinux() {
  git clone https://github.com/sbt/sbt.git
  pushd sbt
  cd launcher-package
  sbt -Dsbt.build.version=$SBT_VER -Dsbt.build.offline=false clean universal:packageBin universal:packageZipTarball
  mv target/universal/sbt.zip target/universal/sbt-$SBT_VER.zip
  mv target/universal/sbt.tgz target/universal/sbt-$SBT_VER.tgz
  popd
}
```

The above assumes that the develop branch has the latest launcher-package, but in fact sometimes the latest is in a branch like 1.5.x.

**Comment by eed3si9n** [comment]
Confirmed by creating zip installer

```
declare builtin_sbt_version="1.5.5"
```
