### ISSUE TITLE
Connection timed out to repo.scala-sbt.org 

### ISSUE THREAD

**Issue by vitaliihonta** [sbt/sbt#6612]
Hi there! It seems that repo.scala-sbt.org is currently not working.

Our CI's are failing with connection timeouts while downloading sbt plugins.
For instance:
```
https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.7.6/jars/sbt-native-packager.jar: download error: Caught java.net.ConnectException: Connection timed out (Connection timed out) (Connection timed out (Connection timed out)) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.7.6/jars/sbt-native-packager.jar
```

Locally I'm unable to ping repo.scala-sbt.org because it hangs:
```
ping  repo.scala-sbt.org
PING resolver-nginx-redirect-lb-1267960602.us-east-1.elb.amazonaws.com (34.199.146.42) 56(84) bytes of data.
```

Has anybody had the same issues?

**Comment by SethTisue** [comment]
seems to be working now. transient problem?

**Comment by eed3si9n** [comment]
I'm not sure if this is the same outage since the following was posted 20 minutes ago, but they seem to be going through something:

https://status.jfrog.io/incidents/xfylzpkbw04l
> Scheduled maintenance is currently in progress. We will provide updates as necessary. Posted 18 minutes ago. Aug 05, 2021 - 22:45 UTC

**Comment by vitaliihonta** [comment]
Thank you for helping :) Yes, it seems that the problem was caused by JFrog maintenance.
Sorry for disturbing you! I just wasn't sure where repo.scala-sbt.org is hosted

**Comment by crazyjat** [comment]
I am currently experiencing this issue. 

```[centos@ip-10-7-54-45 ~]$ sudo yum install sbt
Loaded plugins: fastestmirror, s3iam
Determining fastest mirrors
https://repo.scala-sbt.org/scalasbt/rpm/repodata/repomd.xml: [Errno 12] Timeout on https://repo.scala-sbt.org/scalasbt/rpm/repodata/repomd.xml: (28, 'Operation timed out after 30001 milliseconds with 0 out of 0 bytes received')
Trying other mirror.
^Chttps://repo.scala-sbt.org/scalasbt/rpm/repodata/repomd.xml: [Errno 14] curl#56 - "Callback aborted"
Trying other mirror.```

**Comment by SethTisue** [comment]
@crazyjat I tried `curl -O -L 'https://repo.scala-sbt.org/scalasbt/rpm/repodata/repomd.xml'` just now and it succeeded fine, so unless you have further evidence to the contrary, it appears that whatever you're experiencing was either transient, or a connectivity problem at your end.
