### ISSUE TITLE
Java Source Code `Mybatis XML mapper files` is missing in the target 

### ISSUE THREAD

**Issue by partoneplay** [sbt/sbt#6617]
## steps
Structure
```
src
  - main
    - java
      - package-name
        - mapper
          A.xml
```

version `1.1.6`

`compile` or `package`

## problem

`A.xml` is not included in the `target` folder or `jar` file.

## Note

I prefer to think of `mapper.xml` as source code rather than a resource file and put is together with `mapperInterface.java`.

**Comment by eed3si9n** [comment]
You're free to customize the directory by changing the settings.
There are documentation regarding that here - https://www.scala-sbt.org/1.x/docs/Howto-Customizing-Paths.html

**Comment by partoneplay** [comment]
> You're free to customize the directory by changing the settings.
> There are documentation regarding that here - https://www.scala-sbt.org/1.x/docs/Howto-Customizing-Paths.html

```
When sbt traverses unmanagedSourceDirectories for sources, it only includes directories and files that match includeFilter and do not match excludeFilter. 
... ...
Note: By default, sbt includes .scala and .java sources, excluding hidden files.
```
For `unmanagedSources `, the default filter may be useful, but for `managedSources`, why ? Nobody will put non-source file in the `src/main/java` `src/main/scala` folder.

I tried: 
```scala
Compile / unmanagedSources / includeFilter := "*.xml"
```
then compile error:
```log
[error] expected class or object definition
```
I just want to add `mapper.xml` into the jar, what should i do?

I have read https://www.scala-sbt.org/1.x/docs/Howto-Package.html#Modify+the+contents+of+the+package, it should work. 
For maven project, there's no such extra work. Sbt should be more simple than maven.

**Comment by SethTisue** [comment]
> I have read scala-sbt.org/1.x/docs/Howto-Package.html#Modify+the+contents+of+the+package, it should work.

You say you're using sbt 1.1.6. That's ancient. Tons of stuff has changed since then; for example, the slash syntax which you're trying to use was added. Try 1.5.5, which at present is the current version.

**Comment by partoneplay** [comment]
> > I have read scala-sbt.org/1.x/docs/Howto-Package.html#Modify+the+contents+of+the+package, it should work.
> 
> You say you're using sbt 1.1.6. That's ancient. Tons of stuff has changed since then; for example, the slash syntax which you're trying to use was added. Try 1.5.5, which at present is the current version.

Currently, I must use scala `2.11.8`. Is there a compatibility list between scala and sbt ?

**Comment by SethTisue** [comment]
sbt 1.5.5 works with any Scala version, including 2.11.8.
