### ISSUE TITLE
Apple Silicon (M1 Chip arm64) support?

### ISSUE THREAD

**Issue by shi27feng** [sbt/sbt#6619]
Hi there,
Is here the right place to raise the issue? or should I ask homebrew to update their repo?
My installation of SBT returns the below complaint:
```shell
❯ brew install sbt
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 13 formulae.
==> Updated Casks
Updated 50 casks.

sbt: The x86_64 architecture is required for this software.
Error: An unsatisfied requirement failed this build.
```

and my system has been installed with OpenJDK 17, which is a native arm64 version:
```
❯ java --version
openjdk 17 2021-09-14
OpenJDK Runtime Environment Homebrew (build 17+0)
OpenJDK 64-Bit Server VM Homebrew (build 17+0, mixed mode)
```
Should I install SBT from the source?
Thanks in advance!

**Comment by eed3si9n** [comment]
You should try installing from our official installer like the tar gz or try SDKMAN. There's been multiple releases since we added Apple Silicon (M1) support although it may not work yet for some plugins until the next release.

**Comment by catap** [comment]
@shi27feng M1 support at brew is quite limited. I suggest to switch to macports :) It is much better support.

Anyway, to enjoy M1 native java you need to use Zulu build which is work very nice, and also works with old (not 17) JDK.

P.S. - I'm one of the first owners of M1 who biught it for fun and make a lot of fun with sbt. I guess @eed3si9n remember last October ;)

**Comment by shi27feng** [comment]
@catap @eed3si9n  Thanks, I'll try.

**Comment by catap** [comment]
@shi27feng I just bumped macport's sbt version to the last one: https://github.com/macports/macports-ports/pull/11869

**Comment by eed3si9n** [comment]
I'm closing this issue for now. Let us know if you there are other issues.

**Comment by viswanath7** [comment]
https://doesitarm.com/formula/sbt/

I've created an issue for homebrew team. 
Checkout https://github.com/Homebrew/brew/issues/12246

**Comment by catap** [comment]
@viswanath7 you always can switch to macports, it has much better support of M1 :)
