### ISSUE TITLE
Download link for 0.12.2 zip actually contains 1.2.0

### ISSUE THREAD

**Issue by gurgl** [sbt/sbt#662]
Namely this link: 
http://scalasbt.artifactoryonline.com/scalasbt/sbt-native-packages/org/scala-sbt/sbt//0.12.2/sbt.zip

**Comment by jsuereth** [comment]
Yeah, it appears the 0.12.2 release caught a stale 0.12.0 launcher.  I'll fix this ASAP.

**Comment by ritschwumm** [comment]
in the meantime, is at least the jarfile available somewhere?

**Comment by jsuereth** [comment]
Not fixed this yet, will do shortly

**Comment by ritschwumm** [comment]
shortly?

**Comment by jsuereth** [comment]
Ha, yeah, so 0.12.3 is fixed, 0.13.0-M1 is fixed too. I think I did 0.12.2, just forgot to reply

**Comment by jsuereth** [comment]
Ok, done.  Sorry it took so long, forgot to update 0.12.2 with 0.12.3.
