### ISSUE TITLE
Eviction errors don’t show the complete chain of transitive dependencies leading to the conflicting modules

### ISSUE THREAD

**Issue by julienrf** [sbt/sbt#6621]
> I think we can address your issue @adrian-salajan by showing a more complete dependency chain when sbt exhibits the conflicting dependencies. Currently, it only shows the conflicting modules, but sometimes these modules come from transitive dependencies, and it’s not easy to figure out where they come from. Instead, sbt could show the complete chain of dependencies that eventually pulled the conflicting modules.

_Originally posted by @julienrf in https://github.com/sbt/sbt/issues/6221#issuecomment-897445388_

**Comment by adrian-2414745** [comment]
this may duplicate the bug i opened for my issue: https://github.com/sbt/sbt/issues/6618

**Comment by julienrf** [comment]
Indeed, I’m sorry I didn’t see this issue!
