### ISSUE TITLE
Can't re-tag `Test / test`

### ISSUE THREAD

**Issue by japgolly** [sbt/sbt#6623]
## steps

```scala
val PhantomJsTag = Tags.Tag("PhantomJs")

Global / concurrentRestrictions += Tags.limit(PhantomJsTag, 4)

Test / test := Def.task{ (Test / test).value }.tag(Tags.Test, PhantomJsTag).value
```

## problem

When I run, I'm still seeing 10+ parallel instances of test running at the same time.

## expectation

I'm expecting a max of 4 test instances running in parallel.

**Comment by eed3si9n** [comment]
Here's obligatory `test` clarification (https://github.com/sbt/sbt/issues/2425)

> When discussing parallel or serial execution of tests, we need to clarify different layers (or ambiguousness) of the way the term "test" is used. Here are the layers:
> 1. subprojects A and B calling "test" task
> 2. test grouping (just one grouping by default)
> 3. test suites, or Specification in specs2 term
> 4. test examples, or individual "should" expressions

In addition, https://www.scala-sbt.org/1.x/docs/Parallel-Execution.html#Future+work is probably relevant here:

>[Tagging] is an experimental feature and there are several aspects that may change or require further work.
>
> .... Currently, a tag applies only to the immediate computation it is defined on. 

If I recall correctly, sbt performs parallel testing by breaking each test suites into test groups, which are then assigned to a task.

So with all these combined, we can reinterpret your problem statement as subproject-level `test` task was limited to run 4 subprojects at a time, and we're still seeing 10 test suites running in parallel.

To propagate the (subproject-level) `test` tags down to (test suite-level) micro-tasks, there's a special setting called `tags`:

```scala
sbt:foo> show Test/test/tags
[info] 	List((Tag(test),1))
```

So tagging as following might work better:

```scala
Test / test / tags := List(PhantomJsTag -> 1)
```

We can test this using something like

```scala
package example

import org.scalatest.funsuite.AnyFunSuite

class Spec1 extends AnyFunSuite {
  test("addition") {
    Thread.sleep(3000)
    assert(1 + 1 == 2)
  }
}
```

and see that there would be 4 suites running at the same time:

```scala
sbt:foo> test

  | => example.Spec2 2s
  | => example.Spec1 2s
  | => example.Spec4 2s
  | => example.Spec3 2s
```

so all in all, maybe we could improve the documentation but I don't think there's a bug.

**Comment by japgolly** [comment]
Modifying `Test/test/tags` works perfectly. Thank you so much @eed3si9n for the detailed response!

**Comment by eed3si9n** [comment]
> Modifying `Test/test/tags` works perfectly. 

Great. Thanks for the confirmation.
