### ISSUE TITLE
scala-library-2.13 on managedClasspath of Scala 3 project

### ISSUE THREAD

**Issue by azolotko** [sbt/sbt#6628]
## steps

```
$ docker run -it --rm hseeberger/scala-sbt:11.0.12_1.5.5_3.0.1 sbt ++3.0.1! 'show managedClasspath'
...
[info] * Attributed(/root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.0.1/scala3-library_3-3.0.1.jar)
[info] * Attributed(/root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.6/scala-library-2.13.6.jar)
```

## problem

`scala-library-2.13.6.jar` is being added to the `managedClasspath` of Scala 3 project.

## expectation

Only `scala3-library_3-3.0.1.jar` should be present in `managedClasspath`.

## notes

Disabling Coursier doesn't seem to affect the behaviour (must be something in sbt itself then?):

```
$ docker run -it --rm hseeberger/scala-sbt:11.0.12_1.5.5_3.0.1 sbt ++3.0.1! 'set useCoursier := false; show managedClasspath' 
...
[info] * Attributed(/root/.ivy2/cache/org.scala-lang/scala3-library_3/jars/scala3-library_3-3.0.1.jar)
[info] * Attributed(/root/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.13.6.jar)
```

**Comment by eed3si9n** [comment]
> Only `scala3-library_3-3.0.1.jar` should be present in `managedClasspath`.

Is this true? Scala 3 as far as I know is built on top of Scala 2.13's standard library (5.5MB). `scala3-library` contains the runtime for Scala 3 features, but I don't think it contains collection library etc.

**Comment by azolotko** [comment]
@eed3si9n Indeed, thanks for pointing this out! Closing as invalid.
