### ISSUE TITLE
RPM repo causes "yum makecache" to fail with "requested datatype filelists not available"

### ISSUE THREAD

**Issue by LeifW** [sbt/sbt#6635]
Installing the RPM repo described at https://www.scala-sbt.org/1.x/docs/Installing-sbt-on-Linux.html#Red+Hat+Enterprise+Linux+and+other+RPM-based+distributions
causes the command `yum makecache` to fail with `Error: requested datatype filelists not available` on Amazon Linux 2 (RHEL 7-based). Running `yum makecache` is requred by AWS CloudFormation Init - e.g. used to install this stuff when spinning up an EC2 box.

Googling for that error says the repo is missing the metadata filelists.xml.gz. And there's apparently a checkbox on Artifactory that can populate that for you: https://unix.stackexchange.com/a/448256

This issue also seems to have been described here: https://stackoverflow.com/questions/68496376/linux-patch-failing-due-to-sbt-rpm-repo

**Comment by LeifW** [comment]
An example of what that filelists.xml.gz file looks like: here's an rpm repo with that metadata, in the repodata/ dir:
https://downloads.apache.org/cassandra/redhat/311x/

**Comment by eed3si9n** [comment]
Thanks for the report. I just enabled filelist generation on JFrog Artifactory. Let us know if this worked.
