### ISSUE TITLE
Coursier unable to pull dependencies from Github Packages

### ISSUE THREAD

**Issue by guizmaii** [sbt/sbt#6636]
## steps

```scala
ThisBuild / resolvers += "Github Packages Registry" at "https://maven.pkg.github.com/<GITHUB_ACCOUNT>/<GITHUB_REPO>"
ThisBuild / credentials += 
  Credentials(
    "Github Packages Registry",
    "maven.pkg.github.com",
    "<GITHUB_LOGIN>",
    "<GITHUB_TOKEN>"
  )
```

## problem

```scala
[error]   unauthorized: https://maven.pkg.github.com/<GITHUB_ACCOUNT>/<GITHUB_REPO>/com/example/lib_2.13/0.2.0/lib_2.13-0.2.0.pom (GitHub Package Registry)
```

but when I set `ThisBuild / useCoursier := false`, then sbt is able to download the packages from Github Packages

## expectation

Should work with Coursier, which is the default resolver today.

## notes

I don't know if it's related but, I tried to debug a bit to understand what was wrong. I more or less randomly put a breakpoint here:

<img width="781" alt="Screen Shot 2021-08-26 at 8 00 47 pm" src="https://user-images.githubusercontent.com/1193670/130959160-9806af38-eb22-428c-9772-eb0b728095c6.png">

When this function was called with the `"https://maven.pkg.github.com/<GITHUB_ACCOUNT>/<GITHUB_REPO>"` I was talking about previously, the `authentication` parameter of the function was equal to `None` 🤔

**Comment by SethTisue** [comment]
is the problem reproducible using coursier only, outside of sbt?

(I'm wondering if a ticket needs to be filed over at https://github.com/coursier/coursier/issues , or whether it's conceivable that coursier itself is working fine and sbt is just invoking it wrong)

**Comment by guizmaii** [comment]
Ok. I don't know how but we've found a way to make it work. 

Here's how to declare your resolver in your `build.sbt` file:
```scala
val GITHUB_OWNER = "guizmaii"

ThisBuild / resolvers += s"GitHub $GITHUB_OWNER Apache Maven Packages" at s"https://maven.pkg.github.com/$GITHUB_OWNER/_/"
ThisBuild / credentials += Credentials(
  "GitHub Package Registry",
  "maven.pkg.github.com",
  GITHUB_OWNER,
  sys.env.get("MY_GITHUB_TOKEN").getOrElse(throw new RuntimeException("Missing env variable: `MY_GITHUB_TOKEN`))
)
```
