### ISSUE TITLE
sbt-launcher 0.13.x fails to download

### ISSUE THREAD

**Issue by baffles** [sbt/sbt#6640]
## steps

Using sbt-launcher 1.5.5, `sbt --sbt-version 0.13.18 sbtVersion` will fail.

Exact repro:

1. Get on Ubuntu Focal (e.g., `docker run --rm -it ubuntu:focal`)
2. Install SBT from official repo, e.g.:
```shell
apt-get update
apt-get install -y curl gnupg openjdk-8-jdk
echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | tee /etc/apt/sources.list.d/sbt.list
echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | tee /etc/apt/sources.list.d/sbt_old.list
curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add
apt-get update
apt-get install -y sbt
```
3. Observe the failure:
```shell
mkdir /tmp/test
cd /tmp/test
sbt sbtVersion # downloads sbt-launcher 1.5.5 and prints 1.5.5
sbt --sbt-version 0.13.18 sbtVersion # fails
```

## problem

```
downloading sbt launcher 0.13.18
shasum: standard input: no properly formatted SHA checksum lines found
failed to download launcher jar: https://repo1.maven.org/maven2/org/scala-sbt/sbt-launch/0.13.18/sbt-launch-0.13.18.jar (shasum mismatch)
```

## expectation

sbt 0.13.18 runs and prints 0.13.18 to the console

## notes

This worked previously. Not sure if this is due to the whole bintray fiasco or something else?

**Comment by eed3si9n** [comment]
My guess is that

```
sbt -Dsbt.version=0.13.18 sbtVersion
```

would work, or just typing `sbt` in a directory with `project/build.properties` file in it that points to `0.13.18`.

Currently `--sbt-version` option is tied to the sbt launcher version, so what you're seeing is failure for the runner script (`sbt` the Bash script) to download `sbt-launch-0.13.18.jar` since it never existed on Maven Central.

**Comment by baffles** [comment]
Ah perfect, that works. I didn't realize the difference between those two options. In this case, I'm just trying to pre-cache the proper version of SBT within a Docker image, so I don't have a build.properties file handy unless I created one on the fly. But defining it as a property works great. Thanks!

**Comment by eed3si9n** [comment]
I've opened https://github.com/sbt/sbt/issues/6645 to change `--sbt-version`.
