### ISSUE TITLE
Remove calls to deprecated SecurityManager APIs

### ISSUE THREAD

**Issue by keynmol** [sbt/sbt#6660]
When running JDK 17, it's angrily load about the SecurityManager API slated for removal:

```
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by sbt.TrapExit$ (file:$HOME/.sbt/boot/scala-2.12.14/org.scala-sbt/sbt/1.5.5/run_2.12-1.5.5.jar)
WARNING: Please consider reporting this to the maintainers of sbt.TrapExit$
WARNING: System::setSecurityManager will be removed in a future release
```

I'm not familiar with the SecurityManager and what it's used for in SBT, but opening this for future tracking

**Comment by griggt** [comment]
Duplicate of #6558

**Comment by keynmol** [comment]
Of course @SethTisue got there first, do'h. Sorry :)

**Comment by SethTisue** [comment]
I only got silver, Yoshida-san took the gold :-)  https://twitter.com/xuwei_k/status/1382935881418383361
