### ISSUE TITLE
dependency-graph/ignoreScalaLibrary marked pending

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#6666]
## steps

```
scripted dependency-graph/ignoreScalaLibrary
```

## problem

`dependency-graph/ignoreScalaLibrary` and `dependency-graph/toFileSubTask`  were marked pending in https://github.com/sbt/sbt/pull/6662, so this is potentially a regression related to JDK 17.

## expectation

Works, or investigate what's happening.

**Comment by xuwei-k** [comment]
- https://github.com/scala/bug/issues/12471
- https://github.com/sbt/sbt/blob/adc217000b80097b6ba71933b46936c80bcbedfd/main/src/main/scala/sbt/internal/graph/rendering/AsciiTree.scala#L39

😭


```diff
  [info] +-ch.qos.logback:logback-classic:1.0.7
  [info] | +-ch.qos.logback:logback-core:1.0.7
- [info] | +-org.slf4j:slf4j-api:1.6.6 (evicted by: 1.7.2)
+ [info] | +-org.slf4j:slf4j-api:1.6.61.7.2
  [info] | +-org.slf4j:slf4j-api:1.7.2
  [info] |
  [info] +-org.slf4j:slf4j-api:1.7.2
```

**Comment by xuwei-k** [comment]
Note: another `Predef.StringFormat.formatted` call in sbt

https://github.com/sbt/sbt/blob/adc217000b80097b6ba71933b46936c80bcbedfd/main/src/main/scala/sbt/internal/graph/rendering/LicenseInfo.scala#L23
