### ISSUE TITLE
Error downloading org.typelevel:macro-compat_2.13 (sbt 1.5.4)

### ISSUE THREAD

**Issue by SarpongAbasimi** [sbt/sbt#6669]
## problem

I keep seeing this error

`Error downloading org.typelevel:macro-compat_2.13`

 when I add this library as a `dependency`

`libraryDependencies += "com.outworkers" %% "phantom-dsl" % "2.59.0"`

But for some reason, after downgrading `sbt` to `sbt.version=1.4.9` the problem got solved.

I do not know what the issue is that is why I am here. Can someone help me understand what the issue is please?

thanks

**Comment by SethTisue** [comment]
see https://www.scala-sbt.org/support.html for advice on where to seek help with sbt

(it is certainly possible you've discovered a bug in sbt, but it's far likelier that there is some problem with your environment/setup)

**Comment by giannoug** [comment]
I've been facing the same problem with a project. This looks like an sbt issue. With `sbt.version = 1.4.9` and running from cli everything works fine. Importing from IntelliJ doesn't work. After upgrading to 1.5.5, both cli and IntelliJ fail with the same error:

```
[info] Updating
[info] Resolved  dependencies
[warn]
[warn] 	Note: Unresolved dependencies path:
[error] stack trace is suppressed; run last my-awesome-project / update for the full output
[error] (my-awesome-project / update) sbt.librarymanagement.ResolveException: Error downloading org.typelevel:macro-compat_2.13.6:1.1.1
[error]   Not found
[error]   Not found
[error]   not found: /Users/user/.ivy2/local/org.typelevel/macro-compat_2.13.6/1.1.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/typelevel/macro-compat_2.13.6/1.1.1/macro-compat_2.13.6-1.1.1.pom
[error]   not found: /Users/user/.m2/repository/org/typelevel/macro-compat_2.13.6/1.1.1/macro-compat_2.13.6-1.1.1.pom
[error]   not found: http://[REDACTED]/artifactory/libs-mirror/org/typelevel/macro-compat_2.13.6/1.1.1/macro-compat_2.13.6-1.1.1.pom
[error]   not found: https://oss.sonatype.org/content/repositories/releases/org/typelevel/macro-compat_2.13.6/1.1.1/macro-compat_2.13.6-1.1.1.pom
[error]   not found: https://repo.typesafe.com/typesafe/releases/org/typelevel/macro-compat_2.13.6/1.1.1/macro-compat_2.13.6-1.1.1.pom
[error] Total time: 10 s, completed Sep 30, 2021, 2:14:13 P
```

**Comment by eed3si9n** [comment]
This sounds like https://github.com/sbt/sbt/issues/6439 / https://github.com/coursier/coursier/issues/2054 . I've fixed it in Coursier but there hasn't been a release of Coursier since March.
