### ISSUE TITLE
https://www.scala-sbt.org/1.x/docs/Testing-sbt-plugins.html deadlink

### ISSUE THREAD

**Issue by er1c** [sbt/sbt#6674]
## problem

https://www.scala-sbt.org/1.x/docs/Testing-sbt-plugins.html

[100+ scripted tests](https://github.com/sbt/sbt/tree/develop/sbt/src/sbt-test) is a dead link

**Comment by eed3si9n** [comment]
It moved to https://github.com/sbt/sbt/tree/develop/sbt-app/src/sbt-test

**Comment by er1c** [comment]
@eed3si9n sorry PR already out :) was just documenting
