### ISSUE TITLE
Migrate scala.util.parsing.json usage to Contraband

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#6676]
## problem

While looking at https://github.com/sbt/sbt/pull/6675 I realized that there's `scala.util.parsing.json`.

## expectation

Migrate that to use Contraband, if not Jawn and ScalaJSON.

**Comment by SethTisue** [comment]
what will you give me not to publicly shame you for this on Twitter? ;-)

**Comment by eed3si9n** [comment]
I think the sadness is that Scala still doesn't have the standard way parsing and representing JSON.

**Comment by SethTisue** [comment]
😭
