### ISSUE TITLE
sbt 1.6.0-M1 does not contain the zip asset

### ISSUE THREAD

**Issue by github-samuel-clarenc** [sbt/sbt#6677]
## steps

The `sbt-1.6.0-M1.zip` asset is not present in the [sbt 1.6.0-M1 release](https://github.com/sbt/sbt/releases/tag/v1.6.0-M1), which forbids for example the sbtn installation : 

```
sbt installSbtn
[error] (Global / installSbtn) java.io.FileNotFoundException: https://github.com/sbt/sbt/releases/download/v1.6.0-M1/sbt-1.6.0-M1.zip

```

## expectation

The zip should be present in the assets list. 

## notes

Thanks for updating the assets list !

**Comment by eed3si9n** [comment]
There are some manual work involved in making the installers, and I didn't make them for M1. I probably will for RC1.

**Comment by github-samuel-clarenc** [comment]
OK thanks @eed3si9n for your response, we'll wait for the RC1 then !
