### ISSUE TITLE
Conflicting cross-version failures for a Java library

### ISSUE THREAD

**Issue by ncreep** [sbt/sbt#6681]
Hi,

I've stumbled upon an issue when using a Java library in the build.

## Steps
In SBT `1.5.5`, given the following `build.sbt` file:
```scala
scalaVersion := "2.13.6"

libraryDependencies += "info.archinnov" % "integration-test-3_0" % "6.1.0"
```
Running the `sbt update` would yield:
```
[error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("..."), "..."):
[error]    info.archinnov:integration-test-2 _2, _1
[error] stack trace is suppressed; run last update for the full output
[error] (update) Conflicting cross-version suffixes in: info.archinnov:integration-test-2
```
The same build works fine in SBT `<= 1.5.4`.

## Problem

The `integration-test-3_0`  (Java) library depends on `integration-test-2_2` and `integration-test-2_1` (see [here](https://mvnrepository.com/artifact/info.archinnov/integration-test-3_0/6.1.0)).
It looks like the fix in sbt/librarymanagement#383 changed the regex in such a way that it catches the `integration-test` libraries and considers them to be cross-compiled and conflicted. This is obviously not the case as all these are Java libraries.

Is there anything that can be done to avoid this false-positive cross-version failure?

Thanks

**Comment by eed3si9n** [comment]
Could you try adding the following to your subproject setting?

```scala
import sbt.librarymanagement.ConflictWarning

conflictWarning := ConflictWarning.disable
```

**Comment by ncreep** [comment]
Yes, forgot to mention that adding `ConflictWarning.disable` indeed fixes the issue. But ideally I would like to avoid turning off this warning for the whole project.

Thanks

**Comment by eed3si9n** [comment]
Given that Scala 3 has adopted `_3` as suffix, and assuming not many other libraries have suffix like `_0` or `_1`, it's a won't fix for me. If you have some idea to resolve this, let us know.

**Comment by ncreep** [comment]
How complicated would it be to make it possible to disable this warning per artifact?
If you think that it's something that wouldn't require deep changes in the codebase, I'll try to tackle it myself.

**Comment by eed3si9n** [comment]
It's all in one file https://github.com/sbt/librarymanagement/blob/develop/core/src/main/scala/sbt/librarymanagement/ConflictWarning.scala, but in my opinion it's not worth complicating it, esp if it's for integration testing. Not detecting cross-version conflict could result in a runtime issue, but the runtime of a test is still a test.

**Comment by ncreep** [comment]
Right, I guess I can scope that setting to the `test` part of the project, and that wouldn't be particularly dangerous.

Great, thanks for the support.

**Comment by ncreep** [comment]
I thought that scoping this setting to `Test` would be easy, but it seems that my knowledge here is lacking.
Trying to do something like  this:
```scala
Test / conflictWarning := ConflictWarning.disable
// or
Test / update / conflictWarning := ConflictWarning.disable
```
doesn't seem to have any effect.

Am I missing something obvious, or it's impossible to override since the `update` task is orthogonal to `Test`?

Thanks

**Comment by eed3si9n** [comment]
There's only one `update` per subproject for both `Compile` and `Test`, so you'd need to split up to multiple subprojects if you want different setting.

**Comment by ncreep** [comment]
I see, thanks
