### ISSUE TITLE
Negative download speeds for tensorflow-scala

### ISSUE THREAD

**Issue by Sciss** [sbt/sbt#6683]
## steps

the binary is 300 MB in size:

```scala
libraryDependencies += "org.platanios" %% "tensorflow" % "0.6.4" classifier "linux"
```

https://repo1.maven.org/maven2/org/platanios/tensorflow_2.13/0.6.4/

## problem

sbt reports negative download times, probably due to integer overflow:

https://repo1.maven.org/maven2/org/platanios/tensorflow_2.13/0.6.4/\

progress is stuck at 0,0%

see attached screenshot
![Screenshot from 2021-10-01 23-56-00](https://user-images.githubusercontent.com/131300/135690667-d2d56ee2-0eb6-460f-a810-54dd64d810bd.png)

**Comment by eed3si9n** [comment]
Thanks for the report.
Assuming the progress bar is coming from Coursier, could you please report to coursier/coursier as well?

**Comment by SethTisue** [comment]
I think that since there's a coursier ticket there's no need to keep this one open.
