### ISSUE TITLE
AWS CodeArtifact rejects requests with current Accept header

### ISSUE THREAD

**Issue by maxwell-carbon** [sbt/sbt#6695]
Hello! 👋 

As you're probably aware, when you specify a Maven coordinate depedency in sbt that's not a specific version (like say, `latest.integration`), sbt/Ivy will go out and query for the `maven-metadata.xml` file in the repository. However, because of the Accept header currently being set (by the JDK, I think), CodeArtifact will 4xx these requests.

# Problem

When the repository is CodeArtifact, the request looks something like this (in cURL-equivalent form):

```
curl -H 'User-Agent: Apache Ivy/2.3.0-sbt-fbc4f586aeeb1591710b14eb4f41b94880dcd745' -H 'Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2' -H 'Authorization: *redacted*' -X HEAD https://{redacted}.d.codeartifact.us-east-1.amazonaws.com/maven/{redacted}/maven-metadata.xml
```

However, this causes CodeArtifact to respond with a **404**.

(in the following examples, `$URL` is equal to `https://{redacted}.d.codeartifact.us-east-1.amazonaws.com/maven/{redacted}`, for brevity)

If I change the Accept header to lead with `text/xml`, it works:

```
# sad, current headers
$ curl -v --header "Accept: text/html, *; q=.2, */*; q=.2" --user "aws:$CODEARTIFACT_AUTH_TOKEN" $URL/maven-metadata.xml 2>&1 | grep "< HTTP/2"
< HTTP/2 404

# sad, removing */*
$ curl -v --header "Accept: text/html, *; q=.2" --user "aws:$CODEARTIFACT_AUTH_TOKEN" $URL/maven-metadata.xml 2>&1 | grep "< HTTP/2" 
< HTTP/2 404

# happy, removing everything after first ;
$ curl -v --header "Accept: text/html, *" --user "aws:$CODEARTIFACT_AUTH_TOKEN" $URL/maven-metadata.xml 2>&1 | grep "< HTTP/2"
< HTTP/2 200

# happy, replacing text/html with text/xml
$ curl -v --header "Accept: text/xml, *; q=.2, */*; q=.2" --user "aws:$CODEARTIFACT_AUTH_TOKEN" $URL/maven-metadata.xml 2>&1 | grep "< HTTP/2"
< HTTP/2 200
```

Similar results for snapshot metadata, but it returns 400s instead of 404s:

```
# sad, current headers
$ curl -v --header "Accept: text/html, *; q=.2, */*; q=.2" --user "aws:$CODEARTIFACT_AUTH_TOKEN" $URL/0.0.1-SNAPSHOT/maven-metadata.xml 2>&1 | grep "< HTTP"
< HTTP/2 400

# sad, removing */*
$ curl -v --header "Accept: text/html, *; q=.2" --user "aws:$CODEARTIFACT_AUTH_TOKEN" $URL/0.0.1-SNAPSHOT/maven-metadata.xml 2>&1 | grep "< HTTP" 
< HTTP/2 400 

# happy, replacing text/html with text/xml
$ curl -v --header "Accept: text/xml, *; q=.2, */*; q=.2" --user "aws:$CODEARTIFACT_AUTH_TOKEN" $URL/0.0.1-SNAPSHOT/maven-metadata.xml 2>&1 | grep "< HTTP"
< HTTP/2 200

# happy, removing everything after first ;
$ curl -v --header "Accept: text/html, *" --user "aws:$CODEARTIFACT_AUTH_TOKEN" $URL/0.0.1-SNAPSHOT/maven-metadata.xml 2>&1 | grep "< HTTP" 
< HTTP/2 200
```

I don't know why this behavior is the way it is...kinda just looks like CodeArtifact is exceptionally bad at parsing Accept headers.

# Setup

I don't think our setup is anything special, just an authenticated Maven repository.

We've added a resolver that looks like this:

```scala
"company/repository" at s"https://{redacted}.d.codeartifact.us-east-1.amazonaws.com/maven/{repository}/"
```

with credentials that look like

```scala
Credentials(
  "company/repository",
  "{redacted}.d.codeartifact.us-east-1.amazonaws.com",
  codeArtifactAuthUser,
  codeArtifactAuthToken,
)
```

# Versions Affected

We're using sbt 1.4.9, but I've also repro'd this on 1.5.5. I haven't tried any other version.

**Comment by maxwell-carbon** [comment]
Also this sounds similar to https://github.com/sbt/sbt/issues/5483 but as this is on the dependency resolution side and not the publish side, it seems to be executing a different code path.

**Comment by eed3si9n** [comment]
Thanks for the report. Could you provide reproduction steps so we can reproduce your problem on _our computers_? Unless we can reproduce some portion of it, I don't think this would move forward. In particular, are you using `useCoursier := false`?

As far as I know, Ivy should be out of the picture at least during resolution.

**Comment by maxwell-carbon** [comment]
I can confirm it repros with Coursier.

I have a test project almost ready to go, but since AWS resources are involved I'm waiting to get company sign-off before sharing. I'll need to share an AWS secret key with you -- is email fine for that? The one in your GitHub profile?

**Comment by maxwell-carbon** [comment]
In the interest of time...I'll assume yes.

The repository, which I'll add you to, is here: https://github.com/maxwell-carbon/SbtCodeArtifact . There are repro instructions in the README. I'll also email you the secret key in a moment.

**Comment by maxwell-carbon** [comment]
Hey, this is causing a lot of anguish for us internally, would appreciate it if you could take a look at it soon, thanks 😄

**Comment by eed3si9n** [comment]
> Hey, this is causing a lot of anguish for us internally, would appreciate it if you could take a look at it soon, thanks 😄

I (no longer) work for Lightbend, so sbt is a side project I do on my free time. I found a workaround by using Apache Ivy as follows:

```scala
useCoursier := false

ivyConfiguration := {
  val config0 = Classpaths.mkIvyConfiguration.value
  config0
    .withUpdateOptions(UpdateOptions().withGigahorse(true))
}
```

For the solution with Coursier, you might want to report to upstream coursier/coursier about this issue, maybe consider contracting VirtusLab to work on the fix.

**Comment by maxwell-carbon** [comment]
Alright, thanks @eed3si9n.
