### ISSUE TITLE
Add a `shutdownall sbt`

### ISSUE THREAD

**Issue by adpi2** [sbt/sbt#6696]
With sbt server, we can have many idle processes running in the background. For one reason or another (low cpu, low ram, unresponding server) the user may want to kill all these sbt processes.

One of the possible solution is to run this bash command manually: `jps -v | grep sbt-launch | cut -f1 -d ' ' | xargs kill -9`.

For convenience, sbt could provide a similar command. It could be part of the existing script (`sbt -shutdownall`) or a standalone script `shutdownall-sbt`.

**Comment by er1c** [comment]
Nice, I didn't know about `jps` - looks like this is from java7+ looks like the above command should be fairly portable for *nx variants.

**Comment by eed3si9n** [comment]
I gentrified the name to shutdownall in the title, as I left similar comment to the PR.
