### ISSUE TITLE
sbt as a language server for vim

### ISSUE THREAD

**Issue by hnbon** [sbt/sbt#6705]
## steps

The steps are described here:
https://github.com/neovim/nvim-lspconfig/issues/1386
or here:
https://github.com/neoclide/coc.nvim/issues/3460

## problem

I'm trying to use `sbt` as a TCP language server for `vim`, but I failed with two extensions. Since the failure looks similar for both extensions, I'm reporting the issue here as it is possible the problem comes from `sbt` itself.

## expectation

Errors should be highlighted in the editor.

**Comment by hnbon** [comment]
https://github.com/neoclide/coc.nvim/issues/3460 was closed, the dev said:

> The language server didn't publish diagnosis to client.

**Comment by eed3si9n** [comment]
Please use Metals instead for LSP.

**Comment by hnbon** [comment]
Is sbt as a language server deprecated? There are unrelated issues in metals (which are already reported on github) that prevent me from using it on my projects, so I wanted to try `sbt` language server directly.

The `nvim-lspconfig` issue was closed too.

**Comment by eed3si9n** [comment]
Yes. Now that sbt server implements Build Server Procotol (BSP) as a backend of Metals, I think it's most beneficial to the Scala ecosystem that we consolidate the effort on that. All I wanted really is for an sbt session to be the backend of IDE experience and Metals + BSP + sbt server achieves that.

Maybe I should clarify this position better on https://www.scala-sbt.org/1.x/docs/sbt-server.html?

**Comment by hnbon** [comment]
Yes maybe, thank you for clarifying, I got inspired by this page and several of your (old) tutorials on sbt + Neovim/VS Code/Sublime.
