### ISSUE TITLE
Can't download deb file (https://dl.bintray.com/sbt/debian/sbt-0.13.17.deb). Forbidden 403

### ISSUE THREAD

**Issue by dk8996** [sbt/sbt#6712]
## steps

1) Try downloading the file via this url (https://dl.bintray.com/sbt/debian/sbt-0.13.17.deb)

## problem

Can't download deb file (https://dl.bintray.com/sbt/debian/sbt-0.13.17.deb). Forbidden, 403 error.

**Comment by eed3si9n** [comment]
duplicate of #6582
