### ISSUE TITLE
Unwanted Windows line endings in ./sbt script 

### ISSUE THREAD

**Issue by bab9e9** [sbt/sbt#6717]
## steps

A fresh install of sbt-1.5.5.msi.

## problem

This resulted in /cygdrive/c/Program Files (x86)/sbt/bin/sbt containing Windows style line endings, namely \r\n.

This seems wrong.

## expectation

**it should have Unix line endings**.

## notes

Nevertheless, this seems to work with MINGW64 bash (gitbash) or MSYS2 bash, which have special adaptations for windows.

```
$ sbt
[info] welcome to sbt 1.5.5 (Oracle Corporation Java 11.0.1)
[info] loading project definition from C:\Users\XXXX\project
[info] set current project to bab9e (in build file:/C:/Users/XXXX/)
[info] sbt server started at local:sbt-server-1b3dd0729952391dda2a
[info] started sbt server
>....
```

But **FAILS** when run from WSL (ubuntu),

```
$ which sbt
/mnt/c/Program Files (x86)/sbt/bin/sbt
bab@OrX1W:/mnt/c/WINDOWS/system32$ sbt
/usr/bin/env: ‘bash\r’: No such file or directory
```

Also **FAILS** on Cygwin64 (bash, or mksh):

```
$ sbt
/cygdrive/c/Program Files (x86)/sbt/bin/sbt: line 2: $'\r': command not found
: invalid optionram Files (x86)/sbt/bin/sbt: line 3: set: +
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
': not a valid identifier (x86)/sbt/bin/sbt: line 5: declare: `residual_args
': not a valid identifier (x86)/sbt/bin/sbt: line 6: declare: `java_args
': not a valid identifier (x86)/sbt/bin/sbt: line 7: declare: `scalac_args
': not a valid identifier (x86)/sbt/bin/sbt: line 8: declare: `sbt_commands
': not a valid identifier (x86)/sbt/bin/sbt: line 9: declare: `sbt_options
': not a valid identifier (x86)/sbt/bin/sbt: line 10: declare: `print_version
/cygdrive/c/Program Files (x86)/sbt/bin/sbt: line 11: declare: `print_sbt_versio': not a valid identifier
/cygdrive/c/Program Files (x86)/sbt/bin/sbt: line 12: declare: `print_sbt_script': not a valid identifier
': not a valid identifier (x86)/sbt/bin/sbt: line 13: declare: `original_args
': not a valid identifier (x86)/sbt/bin/sbt: line 15: declare: `java_version
/cygdrive/c/Program Files (x86)/sbt/bin/sbt: line 26: $'\r': command not found
/cygdrive/c/Program Files (x86)/sbt/bin/sbt: line 30: $'\r': command not found
/cygdrive/c/Program Files (x86)/sbt/bin/sbt: line 32: syntax error near unexpected token `$'{\r''
'cygdrive/c/Program Files (x86)/sbt/bin/sbt: line 32: `realpathish () {
```

**Comment by bab9e9** [comment]
vi "$(which sbt)"
Using Vim with  :e ++ff=unix
Some text from ./sbt

#!/usr/bin/env bash^M
^M
set +e^M
declare builtin_sbt_version="1.5.4"^M
declare -a residual_args^M
declare -a java_args^M
declare -a scalac_args^M

**Comment by bab9e9** [comment]
What I want is for the .MSI to install properly with correct line endings. I don't want work-arounds like "use gitbash" or use dos2unix.  It should work first time out of the box.

**Comment by eed3si9n** [comment]
Thanks for the report. I automate the creation of msi installer using GitHub Actions, so this behavior of files changing line ending was not intentional, although kind of understandable since I can image the exact opposite could happen for `sbt.bat` files where it _not_ having Windows line ending could break it.

**Comment by eed3si9n** [comment]
Assuming it's git clone that's changing the line ending hopefully https://github.com/sbt/sbt/pull/6719 would fix this issue.
