### ISSUE TITLE
when ~/.sbt/1.0/plugins exists, sbt fails to boot if configured to use private repository

### ISSUE THREAD

**Issue by daddykotex** [sbt/sbt#6718]
## steps

1. configure sbt to use a private repository (credentials, repositories file, SBT_OPTS=`-Dsbt.override.build.repos=true -Dsbt.boot.credentials=/root/.sbt/.credentials`
2. launch sbt when `~/.sbt/1.0/plugins` does not exists (success)
3. launch sbt when `~/.sbt/1.0/plugins` does exists (**fail**)

## problem

it seems like credentials are discarded for some reason and thus we get unauthorized http response from the repository

## expectation

the sbt / boot process should use the same credentials to fetch sbt and any other jars it needs.

## notes

I've documented a way to reproduce here: https://github.com/daddykotex/sbt-issue-creds without messing up your own system.

I'd be happy to fix it. I've already checked out the source of both `sbt/sbt` and `sbt/librarymanagement` but so far, I can't crack it.

**Comment by eed3si9n** [comment]
Thanks for the report. Please note that `sbt.boot.credentials` only affects the sbt launcher (that's whoever added it meant by "boot" here) to resolve the core artifacts of the sbt itself.

The metabuild (plugin world) normally depends on the sbt artifacts as well, so my guess is that resolver is failing because you'd need to configure the credential for Coursier used to resolve the metabuild.

**Comment by eed3si9n** [comment]
Also here from the documentation - https://www.scala-sbt.org/1.x/docs/Proxy-Repositories.html#Using+credentials+for+the+proxy+repository

**Comment by daddykotex** [comment]
I'm 95% sure there is a bug.

At this point, I've hit all the corner cases of credentials handling in this setup:

- ivy properties files along with the sbt setting file
- coursier properties file along with the env var
- repositories file along with the sbt opt

The key takeaway of this reproduction is that `sbt` will fail to start when there is **only** `1.0/plugins`. No plugin file (.scala) to compile, no `addSbtPlugin` (.sbt) either.

In the repro, when there is no `1.0/plugins` folder, everything works:

- the launcher fetches sbt 1.5.5 and scala
- sbt then fetches all it needs to run the project, from the private repository (including dependencies (like typesafe hocon config as defined in the dummy build))

When you add the folder, it breaks:

- the launcher fetches sbt 1.5.5 and scala
- sbt fails when resolving plugin `[info] loading global plugins from /root/.sbt/1.0/plugins` (even though no plugins are defined)

Anyway, you can keep it close for now, but I will get to the bottom of this, and if there is no bug, I'll at least improve the doc.

**Comment by daddykotex** [comment]
So it is maybe not a bug, I'll let you decide. Either way, bug or not, I think the documentation can be improved.

When you configure sbt in the following fashion:

1. ask sbt to use only an internal repository (**authenticated only**) - https://www.scala-sbt.org/1.x/docs/Proxy-Repositories.html#sbt+Configuration
2. configure it with credentials - https://www.scala-sbt.org/1.x/docs/Proxy-Repositories.html#Using+credentials+for+the+proxy+repository

(See below for the actual configuration)

Then you cannot use global plugins.

When resolving the meta build, sbt *will use the repositories overrides* but **will not grab the credentials** from your global settings.

Possible solutions:

1. copy the credentials settings from `/root/.sbt/1.0/credentials.sbt` to `/root/.sbt/1.0/plugins/project/credentials.sbt`, both contains the same thing and reference the actual credentials file: `/root/.sbt/.credentials`
2. load the global settings before loading the `GlobalPlugin` so that settings defined in `/root/.sbt/1.0/credentials.sbt` can be used to load global plugins

------

## Details of the configuration

On the file system:

```bash
> tree -a ~/.sbt
/root/.sbt
├── 1.0
│   └── credentials.sbt
├── .credentials
├── .credentials-coursier
└── repositories

1 directory, 4 files

>cat /root/.sbt/.credentials
host=nexus
user=admin
password=admin

> cat /root/.sbt/.credentials-coursier
simple.host=nexus
simple.username=admin
simple.password=admin
simple.auto=true

> cat /root/.sbt/1.0/credentials.sbt
credentials += Credentials(file("/root/.sbt/.credentials"))
```

With env vars:

```bash
> env | grep -E "SBT|COURSIER"
SBT_CREDENTIALS=/root/.sbt/.credentials
COURSIER_CREDENTIALS=/root/.sbt/.credentials-coursier
SBT_OPTS=-Dsbt.override.build.repos=true -Dsbt.boot.credentials=/root/.sbt/.credentials
```

**Comment by eed3si9n** [comment]
Thanks for the investigation.

As an alternative solution, maybe sbt mothership should also take `SBT_CREDENTIALS` environment variable into account (not just sbt launcher).

In the meantime copying `/root/.sbt/1.0/credentials.sbt` to `~/.sbt/1.0/plugins` sounds like a workaround that would work?

**Comment by daddykotex** [comment]
To be clear, the workaround that I've used is copying `/root/.sbt/1.0/credentials.sbt` to `~/.sbt/1.0/plugins/project`. But yes, it works and I have already implemented it.

I'd be happy to look at a fix to load the file defined in `SBT_CREDENTIALS` and to use it to load the global plugins.
If that's fine with you, let me know, and I'll work on PR.

Thanks, @eed3si9n

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/6724

**Comment by fernanluyano** [comment]
Having the same issue here and the workaround does not work for me. Was it resolved? I have seen many people complaining about unauthorized issues when pulling a custom plugin, for years.
