### ISSUE TITLE
API: Replacement for deprecated LogExchange methods aren't public

### ISSUE THREAD

**Issue by lefou** [sbt/sbt#6734]
Ref https://github.com/sbt/sbt/issues/6722

### Issue

Some methods in `sbt.util.LogExchange` are deprecated since 1.4.0, with the suggestion to use `sbt.util.LoggerContext` instead.

These methods include:
* `LogExchange.logger`
* `LogExchange.unbindLoggerAppenders`
* `LogExchange.bindLoggerAppenders`

It seems that all essential methods of `LoggerContext` which could be used instead are more or less private to `sbt`, `sbt.util` or even `sbt.util.LoggerContext`.

### Context

We use Zinc in Mill as Java/Scala compiler, and in order to get proper compiler messages, e.g. to forward it to BSP clients, we need to be able to create `ManagedLoggedReporter` and as a precondition also `ManagedLogger`. This is what the deprecated API did.

https://github.com/com-lihaoyi/mill/blob/538ffe26f209cff93255f812e0501db4488335aa/scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala#L416-L443

What is the recommended solution?

**Comment by eed3si9n** [comment]
Thank for the report. I moved the issue here since util is under this repo.

**Comment by Nirvikalpa108** [comment]
Thank you so much @lefou for raising this pertinent issue 👍🏽

It's perfect timing as @eed3si9n and I just started working on removing the deprecated `sbt.util.LogExchange` methods. Your issue has been fixed in this draft PR: https://github.com/sbt/sbt/pull/6726. 

I've linked your issue to that PR, so that it will be closed automatically once the PR is merged.

Thanks!🙏🏾

**Comment by lefou** [comment]
Can you a bit more specific in what way this issue is solved? From a quick look at the linked PR #6726, it looks like all of these API methods (deprecated and new) are gone.

**Comment by Nirvikalpa108** [comment]
Sure! 👍🏽

I've just added a comment on the PR here: https://github.com/sbt/sbt/pull/6726/files?authenticity_token=6IfrQwVGvFbqhY73DpFsPlMqJmdjgn4dkMmlFFKHltLMT2jTmYDrqSvYRr6gDLMHZnZNA1yAC%2F1GFF3Rlgti9g%3D%3D&file-filters%5B%5D=.scala&w=1#r762409111

**Comment by lefou** [comment]
Ah, great, thanks! I must have misread it the first time and thought, you removed them entirely.
