### ISSUE TITLE
Pass JVM options with whitespace?

### ISSUE THREAD

**Issue by nvollmar** [sbt/sbt#6759]
I need to launch sbt with the JVM option "--add-opens java.base/java.util=ALL-UNNAMED".
Since SBT_OPTS/JAVA_OPTS are set to arrays it ends up on two lines...

Is there a way to pass this?

**Comment by eed3si9n** [comment]
We use GitHub issue mostly to track bugs and tasks on sbt development. If you need help, please check this out - https://www.scala-sbt.org/support.html

**Comment by bunnycodego** [comment]
> I need to launch sbt with the JVM option "--add-opens java.base/java.util=ALL-UNNAMED". Since SBT_OPTS/JAVA_OPTS are set to arrays it ends up on two lines...
> 
> Is there a way to pass this?

Hello there, have you figured out how to do this? I'm having the same issue :(

**Comment by SethTisue** [comment]
for the record, you need to pass them as separate strings, like `javacOptions ++= Seq("-add-opens", ...)`
