### ISSUE TITLE
The `-print-lines` option in `scalacOptions` disables tab completion in `sbt console`

### ISSUE THREAD

**Issue by jhnaldo** [sbt/sbt#6780]
I'm an OSX user with `sbt` and `scala3`. I found the following bug.

## steps

- `build.sbt`:
```
ThisBuild / scalaVersion := "3.1.0"
ThisBuild / scalacOptions := Seq("-print-lines")
```

- `project/build.properties`
```
sbt.version=1.6.1
```

## problem

In `sbt console`, tab completion is not working in this setting:
```
scala> val hello = 42
     |val hello: Int = 42

scala> hel<TAB> /* nothing happens */
```

## expectation

Please support tab completion in `sbt console` when the `-print-lines` option is turned on.

**Comment by eed3si9n** [comment]
@jhnaldo Thanks for the report! If you install scala 3 CLI does this also happen?
I am trying to figure it this is an sbt issue or Scala 3 issue.

**Comment by adpi2** [comment]
I tried with `scala3-repl -print-lines` and tab completion did not work. So I reported the bug in https://github.com/lampepfl/dotty/issues/14227.

**Comment by jhnaldo** [comment]
Oh, it was actually the problem related to `scala3-repl`. Thank you for letting me know that!
