### ISSUE TITLE
What's wrong with this Dockerfile ?

### ISSUE THREAD

**Issue by abhinavralhan** [sbt/sbt#6781]
> Please use https://stackoverflow.com/questions/tagged/sbt for questions instead of posting them to the issue tracker.
FROM openjdk:8 as build
ENV SBT_VERSION "1.5.8"
ENV APP_HOME /identity-service
RUN \
  apt-get update && \
  apt-get install apt-transport-https curl gnupg -yqq && \
  echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | tee /etc/apt/sources.list.d/sbt.list && \
  echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | tee /etc/apt/sources.list.d/sbt_old.list && \
  curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/scalasbt-release.gpg --import && \
  chmod 644 /etc/apt/trusted.gpg.d/scalasbt-release.gpg && \
  apt-get update && \
  apt-get install sbt=$SBT_VERSION && \
  sbt sbtVersion
  
  
  I'm getting an error saying E: Version '1.5.8' for 'sbt' was not found

**Comment by SethTisue** [comment]
> Please use stackoverflow.com/questions/tagged/sbt for questions instead of posting them to the issue tracker
