### ISSUE TITLE
JLine.readLine should not catch InterruptedException

### ISSUE THREAD

**Issue by tpetillot** [sbt/sbt#6784]
## steps

Read a line using `JLine.readLine`, for example through `interactionService.readLine` default implementation being `CommandLineUIService` using a `SimpleReader` to read lines.

## problem

Read line catch InterruptedException, prevent `ctrl+c`  signal from user input, but warning is still being dispatch.

> [warn] Canceling execution...

https://github.com/sbt/sbt/blob/develop/internal/util-complete/src/main/scala/sbt/internal/util/LineReader.scala#L180
```scala
  override def readLine(prompt: String, mask: Option[Char] = None): Option[String] =
    try {
      unsynchronizedReadLine(prompt, mask)
    } catch {
      case _: InterruptedException =>
        // println("readLine: InterruptedException")
        Option("")
    }
```

## expectation

`InterruptedException` should not be dismissed.

## note

Odd behavior: `ctrl+x+c` seems to work, but keys must be press simultaneously.

**Comment by eed3si9n** [comment]
Looks like I added this in https://github.com/sbt/sbt/pull/3358 supposedly to fix https://github.com/sbt/sbt/issues/3282, but I am not sure if catching the InterruptedException is needed there tbh. I'd be happy look into this later, or someone else could send a PR to remove try-catch.
