### ISSUE TITLE
Add `s01.oss.sonatype.org` to `Resolver`

### ISSUE THREAD

**Issue by armanbilge** [sbt/sbt#6787]
I assume it would go here: https://github.com/sbt/librarymanagement/blob/a52e34a2b0cb9677fafc0b0d09f17f5fbd1042e5/core/src/main/scala/sbt/librarymanagement/ResolverExtra.scala#L97

Happy to PR, but any thoughts on naming? Thanks!

**Comment by eed3si9n** [comment]
@armanbilge Thanks for the report.

As far as I know, this repo is just for publishing purpose only and the resolver remains to be Maven Central?
Thus far we've not really added `oss.sonatype.org` etc into the `Resolver` and described the instruction in text as https://www.scala-sbt.org/1.x/docs/Using-Sonatype.html.
I am not opposed to adding this, but is the domain `s01.oss.sonatype.org` a semi-permanent thing, or it is just a transitory domain until everyone migrates into it and then it would become `oss.sonatype.org`? Is there a document you could link to? Thanks!

**Comment by armanbilge** [comment]
Thanks for getting back to me.

> As far as I know, this repo is just for publishing purpose only and the resolver remains to be Maven Central?

Well, yes and no. For example, s01 has its own snapshots repo, so if I want to resolve snapshots for a project published via s01, the usual `resolvers += Resolver.sonatypeRepo("snapshots")` wouldn't work.

> but is the domain s01.oss.sonatype.org a semi-permanent thing, or it is just a transitory domain until everyone migrates into it and then it would become oss.sonatype.org?

It's permanent, and seems that they will be keeping `oss.sonatype.org`.

> Even after we've updated our documentation on https://central.sonatype.org to reflect the new host, https://oss.sonatype.org is NOT going away.

https://central.sonatype.org/news/20210223_new-users-on-s01/

**Comment by eed3si9n** [comment]
> Well, yes and no. For example, s01 has its own snapshots repo, so if I want to resolve snapshots for a project published via s01, the usual `resolvers += Resolver.sonatypeRepo("snapshots")` wouldn't work.

Fair. Feel free to send a PR to support `Resolver.sonatypeOssS01Repo("snapshots")` or the name you think makes sense.
