### ISSUE TITLE
Cached code not invalidated in Scala 3

### ISSUE THREAD

**Issue by DGolubets** [sbt/sbt#6797]
I have a project using Scala 3 + Circe JSON derivation.
I also use two laptops to develop and can deploy and git push on one, then later git pull and deploy from another.

So today I pulled my code, did some changes, deployed and got JSON deserialization errors. I didn't change the deserialization code. Turned out I had to run `sbt clean`.

Essentially I compiled and deployed the code, that should not compile. This create a very subtle problem, breaking type safety guarantees of Scala.

I think SBT should be able to correctly deduce what code needs to be recompiled. In fact I didn't have this problem with Scala 2 for the last couple of ears, so this might be SBT+Scala 3 issue.

**Comment by eed3si9n** [comment]
@DGolubets Thanks for the report. Could you provide reproduction steps so we can reproduce your problem on _our computers_?

**Comment by SethTisue** [comment]
closing, since not actionable without details
