### ISSUE TITLE
Logging bug

### ISSUE THREAD

**Issue by sorenmat** [sbt/sbt#68]
Hi,
When trying to compile java source code, i get the following error. Should be a warning/info/note.

[error] Note: Some input files use or override a deprecated API.
[error] Note: Recompile with -Xlint:deprecation for details.
[error] Note: Some input files use unchecked or unsafe operations.
[error] Note: Recompile with -Xlint:unchecked for details.

**Comment by harrah** [comment]
Not a bug.  See http://groups.google.com/group/simple-build-tool/browse_thread/thread/8ab51cf394a30b4/.

We'll use this issue to track that suggestion.
