### ISSUE TITLE
Add support for Scala version specific sources in compiler interface

### ISSUE THREAD

**Issue by gkossakowski** [sbt/sbt#681]
Sbt managed to maintain one code base for the compiler interface project that was shared across all version of Scala compiler. The compiler interface is responsible for interacting with Scala compiler internals that perform dependency tracking and API extraction. It managed to maintain source compatibility by applying various trick that can be seen here:
https://github.com/sbt/sbt/blob/0.13/compile/interface/src/main/scala/xsbt/Analyzer.scala#L126

However, with the work I'm doing to track dependencies in a more fine-grained way we'll hit the wall of not being able to for example support dependency tracking for macros and supporting 2.9 compiler at the same time. See [this](https://groups.google.com/forum/?fromgroups=#!topic/scala-internals/b95Y-GbXVGA) thread on scala-internals for initial discussion about how to achieve that.

We can still share most of the code of compiler interface but we'll definitively need some custom code per Scala major version. It's worth noting that sbt already ships precompiled versions of the compiler interface so that part wouldn't be affected (apart from the fact that compilation of precompiled interface would need to chose the right version of certain sources). The more tricky problem is with artifact that stores compiler interface sources and is being used in case precompiled interface is missing for particular version of Scala compiler. We have two choices:
- Support only latest major release when it comes to `compiler-interface-src` artifact so we ship only one version like right now and it only works with latest major version of Scala at the time sbt was released;
- Include version number of major version Scala compiler in name of `compiler-interface-src` artifact as it's done with any other cross-versioned artifact

One way or another this seems like fairly involved refactoring so I'm filing a ticket for that.

**Comment by gkossakowski** [comment]
@harrah: I'd love to hear your input on that. I consider this to be critical for sbt 0.13 release. Not blocker in a sense that we can ship sbt 0.13 without this feature but it will mean there's little chance we can properly support incremental compilation in case macros are involved.

Since it's fairly difficult refactoring of parts of sbt I don't understand I think I'll need you to work on this if you consider it to be important.

**Comment by harrah** [comment]
Why isn't the dependency tracking code in the compiler?

**Comment by gkossakowski** [comment]
@harrah: because it's hard to design an API for that won't be specific just to sbt. IDE wants to perform some analysis of dependencies but they might want to preserve information about exact location in a tree that sbt doesn't care and it would be very inefficient to store all the time. At the moment I care only about whether dependency is coming by member reference or inheritance but I might need more fine grained tracking in the future for which compiler API (the stable one we are in process of establishing) would have to change again.

The idea is that since we expose trees, symbols and types as a stable api of the compiler (this is part of reflection refactoring that was done) both IDE and sbt and any other tool can extract whatever they specifically need without any need to change a compiler.

**Comment by harrah** [comment]
For this new dependency analysis, what Scala version(s) is it targeting?

For the first choice in the original post, would that major version be 2.11 or 2.10?

**Comment by gkossakowski** [comment]
I believe I can support all three Scala versions: 2.9, 2.10 and 2.11 if I have a chance to insert some version specific code. The idea is that new dependency tracking algorithm will walk trees and extract the dependencies. However, in case of macro application we need to extract dependencies from both original arguments passed to macro and from macro expansion. Therefore, in shared code (between all Scala versions) responsible for dependency extraction I'd have match like that:

``` scala
case MacroApply(fun, args, expansion) =>
  traverse(fun)
  traverse(args)
  traverse(expansion)
```

The `MacroApply` extractor would be defined per Scala major version so for 2.9 it would be simply:

``` scala
object MacroApply {
  def unapply(x: Tree): Option[(Tree, List[Tree], Tree)] = None
}
```

because there are no macros in Scala 2.9. For 2.10/2.11 we would be able to define appropriate implementations of that extractor. That would be general strategy for tackling the issue of supporting multiple versions of Scala that evolve their apis and add new features that affect incremental compilation.

We haven't decided yet if any of solutions proposed in the first post will be implemented. I think everybody agrees on basic idea that dependency extraction should run after typer and should be concerned with just walking trees. The details will be determined soon I hope.

How all of that sounds to you?

**Comment by harrah** [comment]
How will macros be supported in 2.10 in this approach?  MacroApply could only be added in 2.11, right?  At least, it won't be in 2.10.0/1.

**Comment by gkossakowski** [comment]
@harrah: `MacroApply` extractor would be added on sbt side with different definitions for Scala 2.9 (the one I presented), Scala 2.10 (extracting `expansion` through internal only tree attachments) and Scala 2.11 (proper, official API for that).

**Comment by jvican** [comment]
IMO this can be closed, we don't have this problem anymore and it's three years old.

**Comment by eed3si9n** [comment]
Yea. The bridge splitting work that @Duhemm worked on (https://github.com/sbt/sbt/pull/2197, https://github.com/sbt/sbt/pull/2106) is basically based on Grzegorz's idea.
Every time I see Scala team physically we talk about moving the maintenance of the bridge to a third library maintained by them, but we can close this issue for now.
