### ISSUE TITLE
Cannot escape the semicolon character in the run command

### ISSUE THREAD

**Issue by oripwk** [sbt/sbt#6821]
## steps

```bash
sbt "runMain example.Main --myArg=one;two"
```

## problem

sbt thinks that the semicolon (;) is a command delimiter, but it's actually a delimiter of the value of the "myArg" argument. What happens is that it thinks it's got two  commands: `runMain example.Main --myArg=one` and `two`, where `two` doesn't make sense

## expectation

sbt should provide a way to escape the semicolon character

**Comment by eed3si9n** [comment]
It works if you execute it from the interactive shell with double quotes:

```scala
sbt:hello> runMain example.Main "--myArg=one;two"
[info] running example.Main --myArg=one;two
hello
[success] Total time: 0 s, completed Feb 28, 2022 10:17:10 PM
```

To run that from terminal shell, you'd need to single quote the entire thing:

```bash
$ sbt 'runMain example.Main "--myArg=one;two"'

[info] set current project to hello (in build file:/private/tmp/hello/)
[info] running example.Main --myArg=one;two
hello
[success] Total time: 1 s, completed Feb 28, 2022 10:18:31 PM
```
