### ISSUE TITLE
Error when using -Yexplicit-nulls together with import scala.language.unsafeNulls

### ISSUE THREAD

**Issue by PiotrBorowianDeltek** [sbt/sbt#6837]
## steps

1.  Define a simple scala 3 project with the `-Yexplicit-nulls` scala option enabled:

```scala
scalacOptions ++= Seq(
    "-Yexplicit-nulls",
)
```

2. Create the following file and try to compile it with sbt
```scala
object Main extends App:
    import scala.language.unsafeNulls
    val str = "Hello world".substring(5) + "hello"
``` 

## problem
sbt reports the following error:
`undefined: "Hello world".substring(5).+ # -1: TermRef(OrType(TypeRef(ThisType(TypeRef(NoPrefix,module class lang)),class String),TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Null)),+) at sbt-api`

## notes
scala version = 3.1.0
sbt version = 1.6.2
os = Windows 10

**Comment by martingd** [comment]
@PiotrBorowianDeltek It does give the same error in the REPL:

```
% scala3 -Yexplicit-nulls
Welcome to Scala 3.1.1 (1.8.0_312, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
                                                                                
scala> object Main extends App:
     |     import scala.language.unsafeNulls
     |     val str = "Hello world".substring(5) + "hello"
     | 
-- Error: ----------------------------------------------------------------------
3 |    val str = "Hello world".substring(5) + "hello"
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |undefined: "Hello world".substring(5).+ # -1: TermRef(OrType(TypeRef(ThisType(TypeRef(NoPrefix,module class lang)),class String),TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Null)),+) at pickler
1 error found                                                                           
```

This is a Scala 3 compiler bug and is reported here:
https://github.com/lampepfl/dotty/issues/14592

**Comment by PiotrBorowianDeltek** [comment]
I just verified that this is indeed an already closed scala compiler bug as @martingd suggested.
https://github.com/lampepfl/dotty/issues/14592
Closing the bug.
