### ISSUE TITLE
`bgRun` does not forward logs to the client

### ISSUE THREAD

**Issue by adpi2** [sbt/sbt#6842]
## steps

1. Create a minimal sbt build with a program that prints some output

```scala
// build.sbt
scalaVersion := "2.13.7"
```
```scala
// src/main/scala/example
package example

object HelloWorld extends App {
  for (_ <- 1 to 10) {
    println(s"Hello world!")
    Thread.sleep(1000)
  }
}
```
2. Start sbtn shell: `$ sbtn`
3. Run `bgRun`

The program starts in the background of sbt server.

## problem

The logs are not forwarded to the client that run the `bgRun` task.

```
sbt:example> bgRun
[info] running HelloWorld 
Hello world!
[success] Total time: 0 s, completed Mar 16, 2022 10:26:30 AM
sbt:sbt-client-input> 
```

## expectation

The logs should continue being forwarded to the client:
![bgRun](https://user-images.githubusercontent.com/13123162/158559190-09a2dc4d-3023-485d-bd13-5bc72484d8b3.gif)

**Comment by nartamonov** [comment]
I have the same issue. It makes `bgRun` almost useless in cases where you're debugging client-server app: you run server in background and client in foreground. In those cases you want to read all console output from server app.

**Comment by adpi2** [comment]
I started to investigate this and found out that logging in bgJobService stopped working after https://github.com/sbt/sbt/pull/5731
