### ISSUE TITLE
[BSP] Do not fire `build/publishDiagnostics` if problems are the same

### ISSUE THREAD

**Issue by tanishiking** [sbt/sbt#6844]
### Context
For example, when we have the following sbt project and use metals + sbt BSP.
https://github.com/tanishiking/sbt-multi-project/tree/20a3d476dc874db295fb3af3450873f8f211f1ea

```
// project/build.properties
sbt.version=1.6.2
```

```scala
// build.sbt
lazy val proj1 = (project in file("proj1"))
lazy val proj2 = (project in file("proj2")).dependsOn(proj1)
```

```scala
// proj1/src/main/scala/A.scala
package proj1

object A {
  val a = "aaa"
}
```

```scala
// proj2/src/main/scala/B.scala

package proj2

import proj1.A

object B {
  def b = println(A.a)
}
```

When I edit `proj2/src/main/scala/B.scala` to something like (which doesn't have any compile error).

```scala
object B {
  def b = println(A.a)
  val c = 1
}
```

- `metals` publish `buildTarget/compile` against `proj2`.
- sbt compiles both projects (`proj1` and `proj2`) (actually compilation against `proj1` is no-op, FYI https://github.com/sbt/sbt/issues/6103)
- sbt fires `build/publishDiagnostics` **even though there's no change from the previous `buildTarget/publishDiagnostics`**
  - If there are only a few files, it's not a big deal.
  - However, if there're a lot of files in a project, publishing and receiving `buildTarget/publishDiagnositcs` every time users save files or open a new file(metals fires `buildTarget/compile` every time user open a new file), could be huge load for both (BSP) client and server.

## Proposal
Do not fire `build/publishDiagnostics` if problems (diagnostics) are the same as the previous compilation (Zinc Analysis).

Actually, `bloop` does the thing [here](https://github.com/tanishiking/bloop/blob/a9b3ea59631ca300c06394effbdf4b2a8e88dbf1/frontend/src/main/scala/bloop/reporter/BspProjectReporter.scala#L241-L246)

**Comment by tanishiking** [comment]
As a consequence of this issue, for example, every time I open/edit one file in `metals`, sbt sends around **200 - 500 of `build/publishDiagnostics` notification with no diagnostics** (depends on the file/projects)  to metals (because sbt sends the `publishDiagnostics` to `metals` for each file in the compiled project).

**Comment by adpi2** [comment]
Thanks @tanishiking for opening this issue! This is something that would be great to improve. It would probably require some effort though and I would be glad to help if you want to try.

**Comment by tanishiking** [comment]
Thanks! I just started working on this https://github.com/tanishiking/sbt/pull/2 (still WIP!), I'll ask your help when it's more ready to show you!

**Comment by tanishiking** [comment]
Closing for https://github.com/sbt/sbt/pull/6929 and https://github.com/sbt/sbt/pull/6847 :rocket:
