### ISSUE TITLE
Explore time stamps vs hashing for change detection in incremental compiler

### ISSUE THREAD

**Issue by gkossakowski** [sbt/sbt#685]
Inspired by discussion that happened here: https://github.com/gkossakowski/xsbt/commit/1e17ab89ab9348a8a5e52337f081babf4b4ef581#commitcomment-2707574

According to @harrah last modified timestamp is not accurate enough that's why content hashing is used for detecting changes in source files. However, for binary files (class files) time stamps are still used. We should explore following questions:
- Why time stamps are not accurate enough even if Java's [`File.lastModified`](http://docs.oracle.com/javase/6/docs/api/java/io/File.html#lastModified(\)) claims milisecond accuracy
- Can we make checking for timestamps configurable for binary files?
- What are the right defaults?

**Comment by fommil** [comment]
We encountered the same problem in ensime. The timestamp is only accurate to 1 second on most operating systems, which is not enough to capture a user interaction.

However, if the file is older than, say, 10 seconds, then timestamps are a perfectly reasonable way to shortcut the (re-)calculation of a hash. This goes for both jars and source files.

**Comment by dwijnand** [comment]
Fixed by implementing per-platform native code for millisecond precision: https://github.com/sbt/io/pull/92.
