### ISSUE TITLE
duplicate - `sbt run` quit condition changed with newer sbt versions

### ISSUE THREAD

**Issue by tg44** [sbt/sbt#6851]
## steps

```scala
//build.sbt
ThisBuild / version := "0.1.0-SNAPSHOT"

ThisBuild / scalaVersion := "2.13.8"

lazy val libs = {
  Seq(
    "com.typesafe.akka"  %% "akka-stream"    % "2.6.18",
  )
}

lazy val root = (project in file("."))
  .settings(
    name := "sbt-run-issue-repro",
    parallelExecution := false,
    libraryDependencies ++= libs
  )
```

```scala
//Main.scala
import akka.actor.ActorSystem
import scala.concurrent.ExecutionContext

object Main extends App {

  implicit val system: ActorSystem                = ActorSystem()
  implicit val executionContext: ExecutionContext = concurrent.ExecutionContext.global

  println("started")
}
```
`sbt run` with `sbt 1.4.7` and with `sbt 1.6.2`

With 1.4.7 the console prints "started" and hangs until the actor system stops (never).

With 1.6.2 the console prints "started" and `[success] Total time: 2 s, completed 25 Mar 2022, 22:40:02` and terminates.

## problem

With 1.4.7 the console prints "started" and hangs until the actor system stops (never).

With 1.6.2 the console prints "started" and `[success] Total time: 2 s, completed 25 Mar 2022, 22:40:02` and terminates.

## expectation

`sbt run` works as before

**Comment by tg44** [comment]
It is not this trivial :( I can't reproduce with minimal example (or in another project yet).

The error I get is;
```
t="2022-03-25 22:10:52" level=WARN source=o.f.c.i.s.c.JarFileClassPathLocationScanner#41 | Unable to determine jar from url (jar:file:/Users/X/dev/X/target/bg-jobs/sbt_15a33c37/job-1/target/abe6d8d1/b5eb8afa/X_2.13-0.2.0-e0b957f0ea1a3b3dad00ca06aa7e088c6c6dc004-SNAPSHOT.jar!/db/migration): /Users/X/dev/X/target/bg-jobs/sbt_15a33c37/job-1/target/abe6d8d1/b5eb8afa/X_2.13-0.2.0-e0b957f0ea1a3b3dad00ca06aa7e088c6c6dc004-SNAPSHOT.jar (No such file or directory)
```
At first, it seems like the process tried to access the file after another process deleted it. But this would be really strange... Any idea is appreciated!

**Comment by tg44** [comment]
I found it, and edited the original report.

**Comment by jtjeferreira** [comment]
Hi @tg44 see #6767

**Comment by tg44** [comment]
Thx @jtjeferreira , this is a total duplicate, I come from a seemingly totally different angle, and as I started to minimalize the problem I found out that indeed the `run` is it. I close this in favor of #6767.
