### ISSUE TITLE
Tracking source dependencies doesn't work in case of implicits and higher-kinded types

### ISSUE THREAD

**Issue by gkossakowski** [sbt/sbt#686]
Let's consider the following:

``` scala
import scala.languageFeature.higherKinds

// M.scala
class M[A](a: A);
object M {
  implicit def m[MM[_], A]: MM[A] = ???
}

// A.scala
trait A
object A {
  //implicit def m[MM[_], A]: MM[A] = ???
}

// B.scala
trait B extends A

// Test.scala
object Test { implicitly[M[B]] }
```

compile it and then uncomment `A.m` and try to compile again. This time compilation should fail due to ambiguous implicits. Unfortunately, current mechanism for tracking source dependencies is not capable of detecting such subtle dependencies introduced by type inference and implicit scope rules.

The example proposed by @retronym.

**Comment by dwijnand** [comment]
Moved to https://github.com/sbt/zinc/issues/339.
