### ISSUE TITLE
Incremental recompilation results in type error

### ISSUE THREAD

**Issue by FlorianCassayre** [sbt/sbt#6863]
## steps

[Minimal reproducible example repository with Actions](https://github.com/FlorianCassayre/sbt-incremental-compilation-bug)

Namely, an empty Scala 3 project (3.0.0 and upwards) with sbt 1.6.2 and the following source files:

```Scala
// A.scala

import p.*

type NAME2 = C[?]
```

```Scala
// p/p.scala

package p

object M {
  class C[N]()
}

export M.*
```

Then the following commands are executed in sequence:
```
sbt compile
sed -i 's/NAME/NAME2/g' src/main/scala/A.scala
sbt compile
```

In other words the code is compiled a first time, then in the file `A.scala` the type `NAME` is renamed to `NAME2`, and finally the code is recompiled.

## problem

The third command fails because of a compilation error:

```
[error] -- [E043] Type Error: /home/runner/work/sbt-incremental-compilation-bug/sbt-incremental-compilation-bug/src/main/scala/A.scala:3:13 
[error] 3 |type NAME2 = C[?]
[error]   |             ^^^^
[error]   |   unreducible application of higher-kinded type p.C to wildcard arguments
[error]   |
[error]   | longer explanation available when compiling with `-explain`
```

## expectation

The updated code should compile normally, and in fact does compile normally when the cache is initially empty (or cleaned before recompilation).

Thus all the commands should succeed.

This leads me to believe that there is an issue with incremental compilation.

**Comment by smarter** [comment]
The incremental compilation logic for Scala 3 is part of the https://github.com/lampepfl/dotty/ repository, could you open an issue there instead?

**Comment by FlorianCassayre** [comment]
Oh, I see, my bad.

**Comment by FlorianCassayre** [comment]
Moved to lampepfl/dotty#14858.
