### ISSUE TITLE
calling any sbt command through build.sbt returns exit code 1

### ISSUE THREAD

**Issue by prosasankad** [sbt/sbt#6884]
## steps
call any sbt command in build sbt

example 
==========

```scala
TestTask := {
	val s: TaskStreams = streams.value
        val shell: Seq[String] = if (sys.props("os.name").contains("Windows")) Seq("cmd", "/c") else Seq("bash", "-c")
	val exampleTest: Seq[String] = shell :+ "sbt \"-Dsbt.log.noformat=true\" dependencyTree"

	s.log.info("building test task...")

	if((exampleTest !) == 0) {
       s.log.success("build successful!")
      } else {
         s.log.error("frontend build failed")
      }
}
```

## problem

when the sbt version is 1.3.13 or less this works without any issues. But from v1.4.0 it returns with exit code 1

## expectation

above example should output the dependencies

**Comment by eed3si9n** [comment]
Are you calling sbt within sbt? I don't think that use case was ever supported.

**Comment by prosasankad** [comment]
Use case is slightly different. We use snyk to scan vulnerabilities and under the hood, it calls sbt dependencyTree, But in essence it's calling sbt in build.sbt. This worked until sbt v1.3.13

**Comment by eed3si9n** [comment]
The information you need should be obtained programmatically via `updateFull.value`, not by calling sbt.
