### ISSUE TITLE
Compiler plugins break remote caching

### ISSUE THREAD

**Issue by duxet** [sbt/sbt#6898]
## steps

1. Add any compiler plugin to build.sbt, eg. `addCompilerPlugin("com.olegpy"   %% "better-monadic-for" % "0.3.1")`
2. Compile project and push remote cache
3. Pull remote cache on another machine, where Coursier cache is located in a different directory
4. Entire project will be recompiled from scratch, even though JDK version and input source code is the same

## problem

When you use Scala compiler plugin added with `addCompilerPlugin` function, then Scala compiler `-Xplugin` parameter will include absolute path to its JAR file and thus it will enforce recompilation of entire project when pulled on machine with different Coursier cache location.

```
[debug] Found differing options:
[debug] a: scala=-Xmaxerrs,1000,-feature,-deprecation,-explaintypes,-unchecked,-encoding,UTF-8,-language:higherKinds,-language:existentials,-Xfatal-warnings,-Xlint:-infer-any,_,-Ywarn-value-discard,-Ywarn-numeric-widen,-Ywarn-extra-implicit,-Ywarn-unused:_,-explicits,-locals,-implicits,-imports,-privates,-patvars,-Ymacro-annotations,-Xlint:_,-byname-implicit,-Xplugin:/root/.cache/coursier/v1/https/repo1.maven.org/maven2/com/olegpy/better-monadic-for_2.13/0.3.1/better-monadic-for_2.13-0.3.1.jar,-Xplugin:/root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/typelevel/kind-projector_2.13.8/0.13.2/kind-projector_2.13.8-0.13.2.jar java=
[debug] b: scala=-Xmaxerrs,1000,-feature,-deprecation,-explaintypes,-unchecked,-encoding,UTF-8,-language:higherKinds,-language:existentials,-Xfatal-warnings,-Xlint:-infer-any,_,-Ywarn-value-discard,-Ywarn-numeric-widen,-Ywarn-extra-implicit,-Ywarn-unused:_,-explicits,-locals,-implicits,-imports,-privates,-patvars,-Ymacro-annotations,-Xlint:_,-byname-implicit,-Xplugin:/Users/wojciech/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/olegpy/better-monadic-for_2.13/0.3.1/better-monadic-for_2.13-0.3.1.jar,-Xplugin:/Users/wojciech/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/typelevel/kind-projector_2.13.8/0.13.2/kind-projector_2.13.8-0.13.2.jar java=
```

## expectation

Path to Coursier cache directory in compiler options should be replaced with some variable like ${CSR_CACHE}, just like it's done in `inc_compile.bin`.

## notes

The quickest workaround is to just ignore -Xplugin parameter when comparing scalac options, eg. by adding this piece of code to your `build.sbt`:

```scala
incOptions := incOptions.value.withIgnoredScalacOptions(
  incOptions.value.ignoredScalacOptions() :+ "-Xplugin:.*"
)
```

**Comment by xuwei-k** [comment]
- https://github.com/sbt/sbt/issues/6027
