### ISSUE TITLE
Looking for a place to host scala-sbt docker images

### ISSUE THREAD

**Issue by francisdb** [sbt/sbt#6904]
Hi,

I'm the maintainer of [scala-sbt](https://hub.docker.com/r/hseeberger/scala-sbt) docker images and since @hseeberger no longer can host the project I am looking for a place to move it to. Preferably not my personal github so next time a new maintainer is needed ppl don't have to switch image again.

Would https://github.com/sbt be interested in taking over https://github.com/hseeberger/scala-sbt ?
I would keep on maintaining it.

**Comment by eed3si9n** [comment]
> I would keep on maintaining it.

👼🙏

If you want to maintain a Docker container, we'd be happy to host the GitHub repository.

**Comment by francisdb** [comment]
Would it be best to fork or just bring over the repo?

**Comment by eed3si9n** [comment]
I'd suggest bringing it over to keep the existing issues etc. GitHub will add redirect to the old name. If you transfer it to me, I can transfer it to sbt org.

Also could we change the name of the repo to something like docker-sbt?

**Comment by hseeberger** [comment]
Thanks, guys.

>  Repository transfer to eed3si9n requested

**Comment by eed3si9n** [comment]
it's now transferred - https://github.com/sbt/docker-sbt
