### ISSUE TITLE
Don't put stuff in ~/.sbt

### ISSUE THREAD

**Issue by bjourne** [sbt/sbt#6914]
Please follow the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)  and put configuration files in ~/.config/sbt and cache files in ~/.cache/sbt, not in ~/.sbt.

**Comment by eed3si9n** [comment]
I kind of agree. Here's the issue I created in 2017 - https://github.com/sbt/sbt/issues/3681
Likely we can't do much in sbt 1.x, but we can hope for sbt 2.x?
