### ISSUE TITLE
sbt 1.6.2 on OpenJDK 18 is broken

### ISSUE THREAD

**Issue by tribbloid** [sbt/sbt#6925]
## steps

- checkout any sbt project
- run `sbt compile`

## problem

```
java.lang.ClassCastException: class java.lang.UnsupportedOperationException cannot be cast to class xsbti.FullReload (java.lang.UnsupportedOperationException is in module java.base of loader 'bootstrap'; xsbti.FullReload is in unnamed module of loader 'app')
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:59)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
	at xsbt.boot.Launch$.run(Launch.scala:149)
	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
	at xsbt.boot.Launch$.launch(Launch.scala:159)
	at xsbt.boot.Launch$.apply(Launch.scala:44)
	at xsbt.boot.Launch$.apply(Launch.scala:21)
	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
	at xsbt.boot.Boot$.run(Boot.scala:73)
	at xsbt.boot.Boot$.main(Boot.scala:21)
	at xsbt.boot.Boot.main(Boot.scala)
[error] [launcher] error during sbt launcher: java.lang.ClassCastException: class java.lang.UnsupportedOperationException cannot be cast to class xsbti.FullReload (java.lang.UnsupportedOperationException is in module java.base of loader 'bootstrap'; xsbti.FullReload is in unnamed module of loader 'app')

```

## expectation

should compile project without error

## notes

observed on Pop_OS 22.04.

Java version:

```
$ java --version
openjdk 18-ea 2022-03-22
OpenJDK Runtime Environment (build 18-ea+36-Ubuntu-1)
OpenJDK 64-Bit Server VM (build 18-ea+36-Ubuntu-1, mixed mode, sharing)

```

**Comment by SethTisue** [comment]
You're using an early-access build of JDK 18. Does the same thing occur in a final-release build?

fwiw, I'm on JDK 18 final (Eclipse Adoptium Java 18.0.1) on MacOS and sbt 1.6.2 works fine for me.

**Comment by eed3si9n** [comment]
Yea it worked last time I checked on macOS  
https://twitter.com/eed3si9n/status/1530594366401794051?s=21&t=hg6TWFbxHePiBzMLaNJPzg

**Comment by ghost** [comment]
I have the same problem 😔
How did you manage to solve the problem?

**Comment by eed3si9n** [comment]
@zmerr I am not sure what the repro steps are here. It worked with the latest Eclipse Temurin on Mac. What operating system and JDK are you using?

**Comment by ghost** [comment]
@eed3si9n I have MacOS
And I was using
openjdk 18.0.1 2022-04-19

I had the same problem with 
openjdk version "18.0.1.1" 2022-04-22

installed through `brew`

But it was workin on all the projects, except one which had 
`dockerBaseImage := "adoptopenjdk:15-jre-hotspot”,`
in the build file. 

So as a silly temporary fix, I just removed java 18 and installed adoptopenjdk15, instead.
And it started working. 

But this is not a real solution, because effectively this broke everything else that was supposed to work on java 18.

**Comment by ghost** [comment]
> You're using an early-access build of JDK 18. Does the same thing occur in a final-release build?
> 
> fwiw, I'm on JDK 18 final (Eclipse Adoptium Java 18.0.1) on MacOS and sbt 1.6.2 works fine for me.


mine was not working with openjdk 18.0.1 2022-04-19
what could possibly be wrong with it?
Any help would be appreciated.

**Comment by rainx00** [comment]
I met the same problem with jdk18.0.1.1.
Jdk17.0.1 works well with sbt.

**Comment by eed3si9n** [comment]
I am guessing that this is coming from the following code in the launcher https://github.com/sbt/launcher/blob/605b67814f4f1a2ed6ddd46213ffec8e8e58ec2e/launcher-implementation/src/main/scala/xsbt/boot/Launch.scala#L148-L150:

```scala
      try {
        withContextLoader(appProvider.loader)(main.run(appConfig))
      } catch { case e: xsbti.FullReload => if (e.clean) delete(launcher.bootDirectory); throw e }
```

Did something change in JDK 18 that's preventing a pattern match written in Scala?
Someone who is more interested in figuring this out could dig deeper.

**Comment by valentin-panalyt** [comment]
Seeing the same error on `sbt.version=1.5.8` and
```
openjdk version "18.0.1.1" 2022-04-22
OpenJDK Runtime Environment Homebrew (build 18.0.1.1+0)
OpenJDK 64-Bit Server VM Homebrew (build 18.0.1.1+0, mixed mode, sharing)
```

Can confirm that it doesn't appear with jdk 17.

**Comment by SethTisue** [comment]
It would help if we had the stack trace for the underlying `java.lang.UnsupportedOperationException`

**Comment by SethTisue** [comment]
I put out a call for assistance at https://twitter.com/SethTisue/status/1541822426203291648

what we need is a way to reproduce the problem. for example, is anyone able to make it happen in a GitHub Actions run in a public GitHub repo?

are any of you able to make it happen in a brand new, empty user account on a MacOS machine? (or any other OS?) if so, can you share steps?

**Comment by ghost** [comment]
Mine is reproducible when this is in the build file:
```
    dockerBaseImage := "adoptopenjdk:15-jre-hotspot”,
```

**Comment by eed3si9n** [comment]
What happens if you change JRE to JDK?

**Comment by Zamirk** [comment]
```

java.lang.ClassCastException: class java.lang.UnsupportedOperationException cannot be cast to class xsbti.FullReload (java.lang.UnsupportedOperationException is in module java.base of loader 'bootstrap'; xsbti.FullReload is in unnamed module of loader 'app')
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:59)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
	at xsbt.boot.Launch$.run(Launch.scala:149)
	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
	at xsbt.boot.Launch$.launch(Launch.scala:159)
	at xsbt.boot.Launch$.apply(Launch.scala:44)
	at xsbt.boot.Launch$.apply(Launch.scala:21)
	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
	at xsbt.boot.Boot$.run(Boot.scala:73)
	at xsbt.boot.Boot$.main(Boot.scala:21)
	at xsbt.boot.Boot.main(Boot.scala)
[error] [launcher] error during sbt launcher: java.lang.ClassCastException: class java.lang.UnsupportedOperationException cannot be cast to class xsbti.FullReload (java.lang.UnsupportedOperationException is in module java.base of loader 'bootstrap'; xsbti.FullReload is in unnamed module of loader 'app')


```

Mac intel chip.
Seems to have occurred for a colleague after installing the latest openjdk through brew.

**Comment by adpi2** [comment]
I managed to reproduce this issue on sbt 1.5.8, on Window, Mac, Ubuntu and many different Java 18 implementations.

But as soon as I bump to sbt 1.6.0, the problem disappears. Same if I use Java 17, no crash. The result of this investigation can be found [here](https://github.com/adpi2/sbt-6925/runs/7215510741?check_suite_focus=true). I tested it also on Mac M1 and I have the exact same behavior.

Still, I am a bit surprised by the title of this issue `sbt 1.6.2 on OpenJDK 18` because all my attempt to run sbt 1.6.2 on OpenJDK 18 succeeded. In addition the cast in `class java.lang.UnsupportedOperationException cannot be cast to class xsbti.FullReload` has been removed in sbt 1.6.0: https://github.com/sbt/sbt/commit/39bcfee937bbbe6d99529b5d28052bfc5a66a037

So I am quite sure now that this bug only happens on sbt 1.5.8 and there is a fix in sbt 1.6.0 that we can backport.

**Comment by adpi2** [comment]
Here is the fix: https://github.com/adpi2/sbt/tree/fix-JDK-18

But there is no branch `1.5.x` anymore in sbt so I guess that means 1.5 is EOL.

The solution is to upgrade your build to 1.6.2.

**Comment by adpi2** [comment]
Please reopen this issue if I am wrong and the same error appears on sbt 1.6.x.

**Comment by eed3si9n** [comment]
Thanks for the investigation @adpi2!

**Comment by jab701** [comment]
I am having this problem with SBT 1.7.1 & openJDK 18. I am running MacOS (Apple M1) and installed SBT via brew.

I am trying to run chisel...

**Comment by adpi2** [comment]
In [chipsalliance/chisel3](https://github.com/chipsalliance/chisel3), the version of sbt is still 1.5.8, that's why it does not work.

https://github.com/chipsalliance/chisel3/blob/master/project/build.properties

**Comment by JulianBailey** [comment]
Ah okay, the MacOS instructions I was following just said to "brew install sbt" it never specified a particluar version. Thanks for your help, I will try this out.

**Comment by som-snytt** [comment]
I just hit this because https://github.com/coursier/interface is on 1.5.8. Maybe there is a way to advertise the limitation.

Or hold a spree just for upgrading the entire ecosystem to 1.7.1. Or one day in which Scala Steward gets merge rights on every repository.

**Comment by SethTisue** [comment]
For those visiting this ticket who may be relatively new to sbt: it's important to understand that when you run `sbt`, the version that runs is determined by the `project/build.properties` file in your current directory, if it exists, rather than by the sbt version you have installed.

Thus: **Even if you've installed sbt 1.6 or 1.7 on your system, you may still need to update `project/build.properties`, too.**

**Comment by tianday66** [comment]
@adpi2 Thanks a lot for your help! I have tried to fix this problem for about an hour and finally solved it in a minute with your help!

**Comment by manojnpalat** [comment]
> here

Thanks @SethTisue and @adpi2  -  being a newbie to scala, these were great timesavers for me - worked like a charm.
