### ISSUE TITLE
Broken dependency on `sbt-dynver` plugin

### ISSUE THREAD

**Issue by kpodsiad** [sbt/sbt#6928]
## steps

1. clone sbt repository
1. run `sbt`

## problem

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.dwijnand#sbt-dynver;4.0.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.dwijnand:sbt-dynver:4.0.0 (scalaVersion=2.12, sbtVersion=1.0)
```

## expectation

One can start sbt shell and hack with sbt codebase.

## notes

As far I can see `sbt-dynver` isn't published to maven, it is published to bintray and bintray is dead.
I don't know this plugin, but after removing dependency on it I was able to run `sbt` and work with project (`compile`, `publishLocal`, basically all I needed), maybe this dependency is not needed?

**Comment by SethTisue** [comment]
in general, the old plugins that were published to bintray (the sbt org's shared bintray, not individuals’ private bintrays) remain available via repo.scala-sbt.org , which is one of the default resolvers that sbt looks for plugins on. is it possible that in your environment, access to that resolver is blocked? (such as by a corporate firewall?)

you might also try changing the dependency from 4.0.0 to 4.1.1 and see if that makes any difference

**Comment by kpodsiad** [comment]
I can open https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.dwijnand/sbt-dynver/scala_2.12/sbt_1.0/4.0.0/ivys/ivy.xml in my browser, but I cannot reach it from shell. Anyway, because it's my problem I'll close that issue and try to investigate why it isn't working on my machine. 

Thanks for response!
