### ISSUE TITLE
SBT >= 1.4.5 removes its parent's temporary directories on MacOS

### ISSUE THREAD

**Issue by note** [sbt/sbt#6931]
## steps

First create the minimal SBT project with:

```bash
mkdir -p minimal-sbt-project/project && echo "sbt.version=1.6.2" > minimal-sbt-project/project/build.properties
```

Then, run the following script:

```bash
#!/bin/bash

# Exit on any failure
set -e

COUNT=10

for i in $(seq $COUNT); do
        FILE=`mktemp -d`
        stat "$FILE"
        sbt -version
        stat "$FILE"
done
```

## problem

On my machine it consistently fails with:

```
> ./now.sh
16777232 21034573 drwx------ 2 michal staff 0 64 "Jun 23 16:01:42 2022" "Jun 23 16:01:42 2022" "Jun 23 16:01:42 2022" "Jun 23 16:01:42 2022" 4096 0 0 /var/folders/kv/xdkw5txn6kv5b58gvztphzdm0000gn/T/tmp.gNNuDyDk
sbt version in this project: 1.6.2
sbt script version: 1.6.2
stat: /var/folders/kv/xdkw5txn6kv5b58gvztphzdm0000gn/T/tmp.gNNuDyDk: stat: No such file or directory
```

Sometimes it fails after a few iterations, but `COUNT=10` is enough to make it fail consistently on my machine.

## expectation

I would expect SBT not to delete the directory created with `mktemp -d`

## notes

I know it may look ridiculous to even suspect SBT here which wasn't passed the file in the first place, but I have a number of reasons to believe that's the case:

* if I change `sbt.version` to e.g. `1.3.13` (or anything prior `1.3.13`) the problem goes away. The problem persists for any sbt version greater or equal to `1.4.5`. I am not sure about `<1.4.0, 1.4.4>` version range as those versions don't work on my machine because of the architecture (I have M1)
* if you think that there's something about the script - I am able to reproduce it consistently just by executing commands sequentially

## another observations

My MacOS version: 12.4. I had this problem before updating from 12.1 as well
Chip: Apple M1 Pro

Happens for all JDKs I tried:

```
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)

openjdk version "1.8.0_322"
OpenJDK Runtime Environment (build 1.8.0_322-b06)
OpenJDK 64-Bit Server VM (build 25.322-b06, mixed mode)

openjdk version "11.0.13" 2021-10-19 LTS
OpenJDK Runtime Environment (build 11.0.13+8-LTS)
OpenJDK 64-Bit Server VM (build 11.0.13+8-LTS, mixed mode)
```

It happens only for temporary directories. Namely, if you change `mktemp -d` to `mktemp` script works just fine.

It doesn't seem to be related to anything that sbt does on its exit, I see the file gone already after opening interactive sbt.

While it's easy to reproduce on my laptop, none of 2 people I asked for running it on MacOS had this issue.

**Comment by eed3si9n** [comment]
@note Thanks for the report. I was not able to reproduce this issue on my old Intel macOS laptop.
I searched for "No such file or directory", and interestingly https://github.com/sbt/sbt/issues/6173 came up which reports that on Arch Linux sbt 1.4.3 `sbtn` removes empty directories in `/tmp`, which sounds similar to your report. I can't think of a reason why this happens.

One potential possibility is that something that sbt is doing (perhaps something in the area I listed in https://github.com/sbt/sbt/discussions/6202) triggers the operating system to clean up temp directories?

**Comment by note** [comment]
@eed3si9n #6173 might be related indeed as modifying a script so it creates a file in tmp dir is enough for the issue to disappear:

```bash
#!/bin/bash

# Exit on any failure
set -e

COUNT=10

for i in $(seq $COUNT); do
        FILE=`mktemp -d`
        touch "$FILE/some.txt"
        stat "$FILE"
        sbt -version
        stat "$FILE"
done
```

^ With the above change the script works just fine

Also, now I noticed that similarly to #6173 the issue affects empty tmp dirs as opposed to tmp dirs created by parent's process

**Comment by eed3si9n** [comment]
@eatkins figured this out:

> The issue is in the native loader https://github.com/sbt/ipcsocket/blob/5a3b61d1be4d64077375413df6d4067d60ee7a73/src/main/java/org/scalasbt/ipcsocket/NativeLoader.java#L168 for the sbtipcsocket jni implementation (which is used only on apple silicon by the server but also probably affects all sbtn platforms). The problem is that in order to load the native library, we have to extract the shared library into a temporary location and then load it. To prevent an accumulation of these, there is code that garbage collects the extracted shared libraries from previous sbt instances. The problem was that I was assuming that we would control the location of this temp directory in sbt. It is controlled by the sbt.ipcsocket.tmpdir system property https://github.com/sbt/ipcsocket/blob/5a3b61d1be4d64077375413df6d4067d60ee7a73/src/main/java/org/scalasbt/ipcsocket/NativeLoader.java#L37-L39

I am glad there's somewhat rational explanation to seemingly out-there behavior. The fix looks pretty straightforward.

**Comment by eed3si9n** [comment]
Here's first of the PRs related to this - https://github.com/sbt/sbt/pull/6935
