### ISSUE TITLE
error in static import of inherited (?) inner classes

### ISSUE THREAD

**Issue by appamatto** [sbt/sbt#696]
Compiling ActionBarSherlock 4.2.0 as an apklib library dependency fails in android-plugin:

[error] /home/appamatto/src/maxd/player/target/scala-2.10/src_managed/main/java/com/actionbarsherlock/app/SherlockFragment.java:11: value OnCreateOptionsMenuListener is not a member of object com.actionbarsherlock.app.SherlockFragmentActivity
[error] import static com.actionbarsherlock.app.SherlockFragmentActivity.OnCreateOptionsMenuListener;

SherlockFragmentActivity inherits OnCreateOptionsMenuListener from Watson. When I replace SherlockFragmentActivity with Watson, OnCreateOptionsMenuListener is found.

Using maven to compile ActionBarSherlock works as expected.

Is this a known pitfall?

**Comment by harrah** [comment]
Please use the mailing list for questions and provide enough details to reproduce.  If it is specific to the android plugin, please use that issue tracker.
