### ISSUE TITLE
.scala defined builds: auto "root" Project

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#697]
It feels boilerplate-esque to have to type this sort of thing

``` scala
    lazy val root = Project(id = "root", base = file(".")) aggregate (
        domain, soap, test, dsl, core, api, main
    )
```

since all the Projects are auto loaded with reflection anyway, it would be really nice if this definition for a root project were automatic.

**Comment by harrah** [comment]
Implemented as part of #554.  If you do not declare any projects with base directory ".", sbt will automatically generate one for you that aggregates all projects.  This is mainly targeted as users of .sbt files, but will work for .scala files as well.
