### ISSUE TITLE
Ability to kill an app run in the background

### ISSUE THREAD

**Issue by nartamonov** [sbt/sbt#6971]
There are `bgRun` and `bgRunMain` tasks to run apps in the background. Also there are `ps` task to list background tasks. Nevertheless currently we haven't any means to kill background app from the SBT console. We have to use OS system tools to find proper java-process and forcedly kill it. That's not as convenient as it could be, especially on Windows platform.

I propose adding `kill` task or something similar.

**Comment by eed3si9n** [comment]
bgStop should work.

**Comment by nartamonov** [comment]
@eed3si9n yes, it works fine, thanks :-) Sadly, there are no documentation for that feature, so it is hard to discover.
