### ISSUE TITLE
Publish releases to Windows Package Manager (WinGet)

### ISSUE THREAD

**Issue by vedantmgoyal9** [sbt/sbt#6980]
With every new release of SBT, use a GitHub workflow to update manifests at https://github.com/microsoft/winget-pkgs repository.

I can create a pull request if you would like. It would help in keeping manifests up-to-date at WinGet with every new release automatically.

**Comment by eed3si9n** [comment]
I keep release workflows here - https://github.com/sbt/sbt-dist/tree/master/.github/workflows
If you're up for it, send us a PR there.

Also sbt is released under Apache v2 - https://github.com/sbt/sbt/blob/1.7.x/LICENSE

**Comment by vedantmgoyal9** [comment]
I think MSIs from this repo (sbt/sbt) are published to WinGet. Hence, the workflow should be present under this repository.

**Comment by vedantmgoyal9** [comment]
@eed3si9n  I have created a pull request. Please review.

**Comment by SethTisue** [comment]
https://github.com/sbt/sbt/pull/6981 was merged; should this be closed?

**Comment by eed3si9n** [comment]
I don't quite remember if I was eventually successful in creating a GitHub token that's not associated with my account, but I guess we can close it for now.
