### ISSUE TITLE
Documents need example for 1.7.0 added sonatypeOssRepos

### ISSUE THREAD

**Issue by ekrich** [sbt/sbt#6987]
## steps

Ran sbt and got warning
```scala
/Users/<user>/workspace/sconfig/build.sbt:56: warning: method sonatypeRepo in class ResolverFunctions is deprecated (since 1.7.0): Use sonatypeOssRepos instead
ThisBuild / resolvers += Resolver.sonatypeRepo("snapshots")
```
Tried to replace `sonatypeRepo` with `sonatypeOssRepos` and got error.
```scala
/Users/<user>/workspace/sconfig/project/plugins.sbt:2: error: No Append.Value[Seq[sbt.librarymanagement.Resolver], scala.collection.immutable.Vector[sbt.librarymanagement.MavenRepository]] found, so scala.collection.immutable.Vector[sbt.librarymanagement.MavenRepository] cannot be appended to Seq[sbt.librarymanagement.Resolver]
resolvers += Resolver.sonatypeOssRepos("snapshots")
```
Looked at documentation and didn't find anything. Looked at error again and thought `++=` would work and fixed the error.

## problem

I think the documentation need updating for 1.7.x.

## expectation

Expect to see and example in the docs.
```scala
// To test snapshots
resolvers ++= Resolver.sonatypeOssRepos("snapshots")
```

## notes
Thanks.

**Comment by eed3si9n** [comment]
@ekrich Thanks for the report. By documentation do you mean the warning message or markdown documentation? I guess both would be nice, but I think we should first get the warning message improved:

https://github.com/sbt/librarymanagement/blob/c992a314a13eda98ba3aa8ef48909a4885dc1c4a/core/src/main/scala/sbt/librarymanagement/ResolverExtra.scala#L158

https://github.com/sbt/sbt/blob/290925fd99f257dc3c7b3122e2d4640720e345d7/main/src/main/scala/sbt/Opts.scala#L44-L48

I guess these text should contain code example like:

```
resolvers ++= Resolver.sonatypeOssRepos("snapshots")
```

/cc @armanbilge

**Comment by ekrich** [comment]
I think that is great idea - I had the `resolvers` in both the plugin and the main build so that made things a little more confusing.

**Comment by carlos-verdes** [comment]
I think the main confusion is before the change you got 1 repo instance and had to wrap it inside a Seq but now `Resolver.sonatypeOssRepos` retrieves a Seq already

**Comment by hartmut27** [comment]
I'm just repeating this to have an summarizing overview, even though it's already been said. I replace

    resolvers += Resolver.sonatypeRepo("snapshots")

by

    resolvers ++= Resolver.sonatypeOssRepos("snapshots")

the interesting point is ```++=``` since the new  ...Oss... function _yet returns a collection_
