### ISSUE TITLE
Make exclude_classifiers and exclude_classifiers.lock less visible to users

### ISSUE THREAD

**Issue by ijuma** [sbt/sbt#70]
Using SBT 0.10.1-SNAPSHOT, after running gen-idea with-sbt-classifiers, I end up with two files in the root of my project:
- exclude_classifiers
- exclude_classifiers.lock

It would be nice if these files were either hidden, in /tmp or somewhere that's already in the typical .gitignore for SBT projects. Also, I don't know if they are meant to be deleted on exit or not, but they weren't when I exited SBT.

**Comment by harrah** [comment]
Thanks for pointing it out.  I meant to change that before committing the first time.
