### ISSUE TITLE
'run' task is executed with changed current directory

### ISSUE THREAD

**Issue by kriomant** [sbt/sbt#700]
I have project with several subprojects: _core_ (library) and several command-line tools: _foo_ and _bar_. There is also _data_ directory with test input.

I would like to use `sbt 'foo/run data'` command from project directory to compile and run _foo_ tool, but it is started with current directory set to _foo_ so it can't find _data_ directory. I have to run it using `sbt 'foo/run ../data'` which non-intuitive and ugly.

**Comment by harrah** [comment]
Either the current default or the build base directory are reasonable defaults, but there can only be one default.  If you would like to override the default, you can do so.  Please use the mailing list for further discussion.
