### ISSUE TITLE
Provide easy way to debug and fix plugins version confict.

### ISSUE THREAD

**Issue by counter2015** [sbt/sbt#7007]
It's not easy to debug problem around sbt-plugins.

This week, Scala Steward help me update some plugins to latest version which lead to runtime exception of sbt.

The error message like this

```
[error] java.lang.RuntimeException: found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* org.scala-lang.modules:scala-xml_2.12:2.1.0 (early-semver) is selected over 1.2.0
[error] 	    +- com.github.sbt:sbt-native-packager:1.9.11 (sbtVersion=1.0, scalaVersion=2.12) (depends on 2.1.0)
[error] 	    +- com.typesafe.play:twirl-api_2.12:1.5.1             (depends on 1.2.0)
[error]
[error]
[error] this can be overridden using libraryDependencySchemes or evictionErrorLevel
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:89)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3688)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (update) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* org.scala-lang.modules:scala-xml_2.12:2.1.0 (early-semver) is selected over 1.2.0
[error] 	    +- com.github.sbt:sbt-native-packager:1.9.11 (sbtVersion=1.0, scalaVersion=2.12) (depends on 2.1.0)
[error] 	    +- com.typesafe.play:twirl-api_2.12:1.5.1             (depends on 1.2.0)
[error]
[error]
[error] this can be overridden using libraryDependencySchemes or evictionErrorLevel
```

It seems that `dependencyTree` does not show anything like "scala-xml".

Fortunately, I cound *guess* which cause this error since the modified part is small enough.

```
// akka-grpc https://doc.akka.io/docs/akka-grpc/current/server/walkthrough.html
addSbtPlugin("com.lightbend.akka.grpc" % "sbt-akka-grpc" % "2.1.5")

// sbt-native-packager https://sbt-native-packager.readthedocs.io/
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.9.11")
```

It seem `sbt-native-package` [update](https://github.com/sbt/sbt-native-packager/issues/1513) `scala-xml` to 2.0

And the `sbt-akka-grpc` depend on `sbt-twril` which depends on `scala-xml`

https://github.com/playframework/twirl/blob/c7f5ee2acabce649939f4cc970134a9828ea6c18/build.sbt#L233-L234

My querstion is:
Is there any easy way to debug plugins dependency? In this sence, it's hard to find out which libary cause the version confict.

Could the sbt provide a more readable error message(e.g. show the confict depency stacktrace) ?

For example
```
[error] java.lang.RuntimeException: found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* org.scala-lang.modules:scala-xml_2.12:2.1.0 (early-semver) is selected over 1.2.0
[error] 	    +- com.github.sbt:sbt-native-packager:1.9.11 (sbtVersion=1.0, scalaVersion=2.12) (depends on 2.1.0)
[error] 	    +- com.typesafe.play:twirl-api_2.12:1.5.1             (depends on 1.2.0)
[error]       in plugins.sbt
[error]        "com.lightbend.akka.grpc:sbt-akka-grpc_2.12:2.1.5"
                     +- "com.typesafe.play:twirl-api_2.12:1.5.1"
                           +- "org.scala-lang.modules:scala-xml_2.12:1.2.0"
                           
[error]        and
[error]        "com.github.sbt:sbt-native-packager:1.9.11"
[error]           +- "org.scala-lang.modules:scala-xml_2.12:1.5.1"
```

In this case, **I can not even get into the sbt console**, is sbt load plugins when init? could it be lazy ?

https://github.com/scala/scala/pull/9743#issuecomment-908413601

**Comment by eed3si9n** [comment]
See https://github.com/scala/bug/issues/12632

> in your project/plugins.sbt

```scala
ThisBuild / libraryDependencySchemes ++= Seq(
  "org.scala-lang.modules" %% "scala-xml" % VersionScheme.Always
)
```

**Comment by counter2015** [comment]
> See [scala/bug#12632](https://github.com/scala/bug/issues/12632)
> 
> > in your plugins.sbt
> 
> ```scala
> ThisBuild / libraryDependencySchemes ++= Seq(
>   "org.scala-lang.modules" %% "scala-xml" % VersionScheme.Always
> )
> ```

Thanks you reply, I had read the workaroud.

**Comment by eed3si9n** [comment]
There are continuing discussions specifically related to scala-xml in https://github.com/scala/bug/issues/12632 and https://github.com/sbt/sbt/issues/6997.

Regarding:

> Could the sbt provide a more readable error message(e.g. show the confict depency stacktrace) ?

I think the current error message is readable, since most people seem to understand what it means.
I don't know if displaying more information is actually helpful since build users can only control the plugins they pick, not the transitive dependencies.

**Comment by crakjie** [comment]
@eed3si9n Why set the Schemes in the plugin.sbt and not in build.sbt?

**Comment by SethTisue** [comment]
> Why set the Schemes in the plugin.sbt and not in build.sbt?

Depends on where the version conflict in question is. If it the conflict is in plugins, you'd need to resolve it in `plugins.sbt`. If the conflict is in your project, you'd resolve it in `build.sbt`. https://www.scala-sbt.org/1.x/docs/Organizing-Build.html#sbt+is+recursive

**Comment by christhomas** [comment]
I understand this is a workaround, but does anybody understand what the solution finally will be?

**Comment by SethTisue** [comment]
@christhomas the solution to what?

**Comment by christhomas** [comment]
Well I read the workaround here for this problem, but I'm wondering what I need to do that will solve this without a workaround

**Comment by SethTisue** [comment]
If you're referring to scala-xml specifically, this will only be over once whatever sbt plugins are still using scala-xml 1.x have upgraded to scala-xml 2.x. Many have done so already, some haven't. If you find one that hasn't, it's good to open an issue (or, even better, pull request!) in their tracker.

**Comment by rubiesonthesky** [comment]
> > Why set the Schemes in the plugin.sbt and not in build.sbt?
> 
> Depends on where the version conflict in question is. If it the conflict is in plugins, you'd need to resolve it in `plugins.sbt`. If the conflict is in your project, you'd resolve it in `build.sbt`. https://www.scala-sbt.org/1.x/docs/Organizing-Build.html#sbt+is+recursive

I'm sorry that this is old thread, but commenting for more visibility for those who are still having this problem.

It may be, that you need to set the schemes in both `build.sbt` and `plugins.sbt` because there are conflicts all around.
