### ISSUE TITLE
sbt refuses to compile in bash's background mode

### ISSUE THREAD

**Issue by kim0** [sbt/sbt#701]
Trying to run "sbt compile &" from a bash shell prompt, once I hit enter, the process immediately jump to stopped state. It refuses to compile until it is made to work in "fg" mode again. Since I'm attempting to run this in background shell scripts, it's preventing normal operation. The tool seems to use STTY mode, even in batch mode. Please at least provide an option to turn that off

**Comment by charles-dyfis-net** [comment]
To provide a clearer spec -- the `stty` tool should not be used when operating with `-batch` passed on the command line.

**Comment by harrah** [comment]
This behavior comes from JLine.  JLine was upgraded by #684 from 1.0 to version 2.10, which fixes this problem.

**Comment by cmaeder** [comment]
Currently. I'm observing the same behaviour for `"sbt compile &"` and `"sbt -batch compile &"` using sbt-version 0.13.11 and I've no clue how to keep it running in the background. (In the foreground I get the message `"Resolving jline#jline;2.12.1"`). I'm on Ubuntu wily using `java version "1.7.0_95"`

**Comment by darabos** [comment]
It's the same here, Ubuntu 16.04, SBT 0.13.12. Can we reopen this?

```
$ sbt about &
[1]+  Stopped                 sbt about
```

It never completes. (Unless I run `fg`.)

There's a workaround:

```
sbt -Djline.terminal=jline.UnsupportedTerminal about &
```

Some more info from myself: https://github.com/ninja-build/ninja/issues/1190

Basically the same issue on Hive's Beeline: https://issues.apache.org/jira/browse/HIVE-6758

Basically the same issue on STS: https://issuetracker.springsource.com/browse/STS-2552

It sounds really like a JLine issue, but I haven't seen a ticket for that. Feel free to kick the bucket to them :).
