### ISSUE TITLE
/tmp for Un*x domain socket

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#7013]
One possible issue with defaulting to `/tmp` here is that it's shared between all users, and if one user creates `/tmp/.sbt/sbt-socketXXXXXX` then another might not have appropriate permissions on `/tmp/.sbt` or `/tmp/.sbt/sbt-socketXXXXXX`. And that's without considering concurrent users.

_Originally posted by @Jasper-M in https://github.com/sbt/sbt/issues/6887#issuecomment-1235300919_

**Comment by eed3si9n** [comment]
@Jasper-M  Interesting. That had not occurred to us, dude. I just kind of wanted to avoid littering `/tmp` so creating `/tmp/.sbt/` would be helpful, but I guess it has some side effects. Maybe we can generate a hash from `sys.props("user.name")` and append that to `/tmp/.sbt-(here)/`.

**Comment by Jasper-M** [comment]
That should probably avoid most potential issues.

Apologies for not opening an issue myself.
