### ISSUE TITLE
Reload during ~ quits sbt

### ISSUE THREAD

**Issue by nafg** [sbt/sbt#7017]
### Method 1
1. Go into an sbt 1.7.1 project directory
2. Set `Global / onChangedBuildSource := ReloadOnSourceChanges`
3. run `sbt ~compile`
4. Edit build.sbt

### Method 2 (simpler)
1. Run `sbt ~compile` in an sbt 1.7.1 project directory
2. When you see `Press <enter> to interrupt or '?' for more options.`, hit the `L` key

## problem

SBT dutifully restarts, but it doesn't go back into ~compile. Instead it quits to the system shell.

## expectation

In sbt 1.6.x it would run ~compile again

Note: it's not specific to `compile`, the same thing seems to happen with any command.

**Comment by nafg** [comment]
Anyone?

**Comment by nafg** [comment]
The same issue seems to happen with pressing L instead of the ReloadOnSourceChanges behavior

**Comment by nafg** [comment]
This is still on issue on the latest version. It's actually much easier to reproduce than above:

```
❯ sbt '~ eval 1'
[info] welcome to sbt 1.9.8 (GraalVM Community Java 17.0.7)
...
[info] ans: Int = 1
[info] 1. Monitoring source files for root/eval 1...
[info]    Press <enter> to interrupt or '?' for more options.
[info] Received input event: Reload.
[info] welcome to sbt 1.9.8 (GraalVM Community Java 17.0.7)
[...]
❯ 
```

So even triggering reload during a `~` command by hitting <kbd>L</kbd> causes sbt to exit (after dutifully reloading first).

**Comment by nafg** [comment]
Anyone have any ideas about this?

**Comment by Friendseeker** [comment]
Probably caused by https://github.com/sbt/sbt/pull/6870?

**Comment by Friendseeker** [comment]
This line from #6870 is the probably the culprit.

https://github.com/sbt/sbt/blob/2259598e5f60bba10740ee5ca52d67cac13878b2/main/src/main/scala/sbt/internal/Continuous.scala#L1397-L1398

Looks like it is cancelling the watch even if we are reloading.

**Comment by Friendseeker** [comment]
<img width="561" alt="image" src="https://github.com/user-attachments/assets/67d535bc-9d42-449c-becb-e166ed4540fe">

<img width="544" alt="image" src="https://github.com/user-attachments/assets/906275a3-88fd-41f1-8bfd-d29899fdf7e5">

Indeed `cs.callbacks.onTermination` somehow ejected `~ eval 1` from list of remaining commands, causing the issue.

The filtering is likely done here

https://github.com/sbt/sbt/blob/2259598e5f60bba10740ee5ca52d67cac13878b2/main/src/main/scala/sbt/nio/Watch.scala#L554-L575

I think the fix is probably passing the right action (`Action.Reload`) somehow to `cs.callbacks.onTermination`. Not immediate obvious how to do it though.

**Comment by Friendseeker** [comment]
Made a PR fixing the issue. Tested locally that reload now no longer quits sbt.

```
❯ sbt '~ eval 1'
[info] [launcher] getting org.scala-sbt sbt 1.10.4-SNAPSHOT  (this may take some time)...
[info] welcome to sbt 1.10.4-SNAPSHOT (Oracle Corporation Java 21.0.1)
[info] loading project definition from /Users/jiahuitan/test2/project
[info] set current project to test2 (in build file:/Users/jiahuitan/test2/)
[info] sbt server started at local:///Users/jiahuitan/.sbt/1.0/server/72cee1ed582024a639a3/sock
[info] started sbt server
[info] ans: Int = 1
[info] 1. Monitoring source files for test2/eval 1...
[info]    Press <enter> to interrupt or '?' for more options.
[info] Received input event: Reload.
[info] welcome to sbt 1.10.4-SNAPSHOT (Oracle Corporation Java 21.0.1)
[info] loading project definition from /Users/jiahuitan/test2/project
[info] set current project to test2 (in build file:/Users/jiahuitan/test2/)
[info] ans: Int = 1
[info] 2. Monitoring source files for test2/eval 1...
[info]    Press <enter> to interrupt or '?' for more options.
```
