### ISSUE TITLE
No instructions for installing with out dnf

### ISSUE THREAD

**Issue by theosib-amazon** [sbt/sbt#7022]
On more recent variants of RPM-based distributions, "dnf" is no longer a supported package. Linux installation instructions for Fedora and RHEL should be replaced with a method that can install sbt using a different installer.

Alternatively I could install from source, but there are no instructions for this either.

**Comment by eed3si9n** [comment]
Could you follow the steps, problem, expectations template please so we don't have to go back and forth on how can you reproduce this conversation?

There's https://www.scala-sbt.org/1.x/docs/Installing-sbt-on-Linux.html and it lists out a bunch of ways to install on Linux.
