### ISSUE TITLE
SBT 0.12 .2 - Play 2.1.0 / Windows Vista / Substitute drive

### ISSUE THREAD

**Issue by PhBastiani** [sbt/sbt#703]
I"ve a Play! framework environnement  installed on a substitute drive. 
I use this subst drive because my real Windows path contains several space characters...

From time to time, sbt seems use the real path for its cache.

Note: 
- it creates a new file tree with the space characters replaced by "%20" !
- it does not put any jar in these folders; and, it uses the subst drive for its cache,
- the build ends properly.

**Comment by jsuereth** [comment]
Can you tell us what the value of the `sys.props("user.home")` in sbt?

**Comment by harrah** [comment]
Also, what specifically do you mean by "its cache"?

**Comment by PhBastiani** [comment]
Thanks for your replies.. Today, I re-started my Play! environment from scratch, and  I cannot reproduce this strange situation !

How can I check `sys.props("user.home")` in sbt ? 
The play directory contains a file named '..\play-2.1.0\framework\sbt\boot\update.log' ! And, this one only  contains a variable 'user.dir' referencing my project...

I am a total newbie... I do not know how sbt is integrated into Play! sbt seems to maintain a cache directory named 'repository' ! This directory contains 2 folders : one of them is named 'cache'... It was this folder that was partially duplicated.

**Comment by harrah** [comment]
Run `eval sys.props("user.home")`.  `user.dir` is the current working directory, which might be useful as well.  There is no `repository` directory in sbt, so it must be defined by play.  What is the other directory in it? "local"?

**Comment by PhBastiani** [comment]
Yes, the 'local' folder contains jars; and, the 'cache' forder contains ivy scripts... these 2 folders are in the 'repository' directory of the Play! environment. My home .sbt folder is empty !

From the play console, i cannot start directly sbt command ! The Play! environment has a sbt starter (sbt-launch.jar) with an embedded release of xsbt.

So, to resume, if I understand: this issue concerns only Play! and its integration of SBT !
