### ISSUE TITLE
SBT crashes on startup with JDK 19

### ISSUE THREAD

**Issue by justinhj** [sbt/sbt#7045]
## steps

Install Java JDK version 19. In my example I use Amazon Corretto 19-amzn  
Install sbt version 1.7.1
Run any sbt command. e.g., `sbt --version`

## problem

In all cases the error is a stack trace with no useful information. Although i suspect that JDK 19 is not supported (yet?), I couldn't see anything in the documentation that says this is the case.

```
> sbt --version    
java.lang.ClassCastException: class java.lang.UnsupportedOperationException cannot be cast to class xsbti.FullReload (java.lang.UnsupportedOperationException is in module java.base of loader 'bootstrap'; xsbti.FullReload is in unnamed module of loader 'app')
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:59)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
	at xsbt.boot.Launch$.run(Launch.scala:149)
	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
	at xsbt.boot.Launch$.launch(Launch.scala:159)
	at xsbt.boot.Launch$.apply(Launch.scala:44)
	at xsbt.boot.Launch$.apply(Launch.scala:21)
	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
	at xsbt.boot.Boot$.run(Boot.scala:73)
	at xsbt.boot.Boot$.main(Boot.scala:21)
	at xsbt.boot.Boot.main(Boot.scala)
[error] [launcher] error during sbt launcher: java.lang.ClassCastException: class java.lang.UnsupportedOperationException cannot be cast to class xsbti.FullReload (java.lang.UnsupportedOperationException is in module java.base of loader 'bootstrap'; xsbti.FullReload is in unnamed module of loader 'app')
sbt script version: 1.7.1
```

## expectation

sbt should be able to exit with a useful error message if a JDK is not supported

**Comment by eed3si9n** [comment]
@justinhj Thanks for the report!

**Comment by adpi2** [comment]
This looks like a duplicate of https://github.com/sbt/sbt/issues/6925 because the `cast to xsbti.FullReload` has been removed since sbt 1.6.0.

@justinhj can you check the `sbt.version` in your `project/build.properties` file? Can you update it to `1.7.1` and try again?

**Comment by justinhj** [comment]
Hi @adpi2 
I did some more investigation. When I enter a project that has 
```
sbt.version=1.7.1
```
in the build.properties everything works fine. 

But when I am in a folder with no project and I want to execute, for example, `sbt new`, or even `sbt --version` then I get the stack trace above. Note that the last line of the of the stack trace is `sbt script version: 1.7.1`

I installed sbt with brew and have the latest version which I can see as follows:

```
> ls -la `which sbt`
lrwxr-xr-x  1 justinhj  admin  27 Aug 19 12:54 /usr/local/bin/sbt -> ../Cellar/sbt/1.7.1/bin/sbt
```
So I suspect you're right, it is somehow accessing older sbt but I'm not sure how.

**Comment by justinhj** [comment]
My mistake, I was doing `sbt new` in my projects folder thinking there was nothing in there that sbt could use to get the version. However, I forgot that running sbt in a folder without a project will create one, so I have a `project/build.properties` with the old version (1.5.5) and therefore ran into the problem.
Closing since this is certainly the same as #6925 thanks for the assistance.
