### ISSUE TITLE
sbt 1.7.3 warns about no-op slf4j implementation on startup

### ISSUE THREAD

**Issue by bpholt** [sbt/sbt#7062]
## steps
Launch sbt 1.7.3 with a plugin enabled that uses slf4j 1.x.

## problem
sbt prints this on startup:
```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
```

## expectation
I expected the log4j implementation included with sbt to be used, instead of the no-op implementation.

## notes
I think this is because of the coursier update, which ([according to its release notes](https://github.com/coursier/sbt-coursier/releases/tag/v2.0.12)) pulls in slf4j 2.0.3—but log4j 2.17.1, which [sbt depends on directly](https://github.com/sbt/sbt/blob/4841e85af0676ee0a659765dcc4dbb4076607d35/project/Dependencies.scala#L130), [depends on slf4j 1.7.25](https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-slf4j-impl/2.17.1).

**Comment by SethTisue** [comment]
Clarification: "Launch sbt 1.7.3" isn't sufficient to reproduce the problem.

https://github.com/scalacenter/scalafix/issues/1700 seems to imply that it's necessary certain plugins to be involved (sbt-scalafix is one such plugin, perhaps there are others?).

**Comment by bjaglin** [comment]
> https://github.com/scalacenter/scalafix/issues/1700 seems to imply that it's necessary certain plugins to be involved (sbt-scalafix is one such plugin, perhaps there are others?).

I assume (but haven't verified) that sbt itself does not use SLF4J, but any sbt plugin that does triggers the warning (and won't have Java logs).

**Comment by bpholt** [comment]
>Clarification: "Launch sbt 1.7.3" isn't sufficient to reproduce the problem.

Yep, you're right—we have a default set of plugins enabled, and it seems that `addSbtPlugin("com.github.sbt" % "sbt-git" % "2.0.0")` triggers the warnings as well.

**Comment by wsargent** [comment]
I've run into this as well.

**Comment by pk044** [comment]
Same here - I get this warning on >= 1.7.3. No warning on 1.7.2.

**Comment by eed3si9n** [comment]
> I think this is because of the coursier update, which ([according to its release notes](https://github.com/coursier/sbt-coursier/releases/tag/v2.0.12)) pulls in slf4j 2.0.3—but log4j 2.17.1, which [sbt depends on directly](https://github.com/sbt/sbt/blob/4841e85af0676ee0a659765dcc4dbb4076607d35/project/Dependencies.scala#L130), [depends on slf4j 1.7.25](https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-slf4j-impl/2.17.1).

So sbt's forced into bumping up slf4j-api and log4j binding?

**Comment by kevin-lee** [comment]
Is there any workaround? I think because of this, `sbt-dependency-check` doesn't show CVE info even with `Dlog4j2.level=debug`.

**Comment by ennru** [comment]
This shows in the same way with sbt 1.8.0 when plugins pull in slf4j.
(To make it even more fun: slf4j 2.x is not compatible with slf4j 1.7, but that's just another chamber in dependency hell.)

**Comment by eed3si9n** [comment]
I have a PR for this - https://github.com/coursier/sbt-coursier/pull/441

**Comment by bpholt** [comment]
Thanks @eed3si9n!
