### ISSUE TITLE
Sbt ignores scalaVersion when source dependency added

### ISSUE THREAD

**Issue by espringe** [sbt/sbt#708]
Checkout: https://github.com/espringe/scoobi

and sbt will happily uses the correct (2.10) version of scala. However, add a source dependency (e.g. uncomment this line):

https://github.com/espringe/scoobi/blob/9d0f0e5696/project/build.scala#L53

and sbt ignores the scalaVersion and uses scala 2.9.2 for everything

(And even the source project is a 2.10 project)

I'm using sbt 0.12.2

**Comment by harrah** [comment]
I assume by "uses 2.9.2 for everything", you mainly mean dependencies and cross-versioning.  This is indeed a fundamental problem to be fixed for 0.13.  You can work around it by explicitly setting `scalaBinaryVersion := "2.10"` for the scoobi and ascii-graphs projects.  (If you didn't control `ascii-graphs`, you could do it from the scoobi project with the appropriate scope.)
