### ISSUE TITLE
Potentially incompatible versions of dependencies between 2.10.1 and 2.10.0

### ISSUE THREAD

**Issue by jdolson** [sbt/sbt#709]
To reproduce create an empty project with the following build.sbt

```
scalaVersion := "2.10.1"

libraryDependencies += "org.scala-lang" % "scala-reflect" % "2.10.1"

libraryDependencies += "org.scalatest" %% "scalatest" % "1.9.1" % "test"
```

Running update or compile generates a warning

```
[warn] Potentially incompatible versions of dependencies of {file:/Users/jdolson/src/test/sbt-warn/}default-b92950:
[warn]    org.scala-lang: 2.10.1, 2.10.0
```

Given the assumed binary compatibility between 2.10.0 and 2.10.1 this warning is unnecessary (not to mention massively annoying if you have a lot of subprojects).

**Comment by harrah** [comment]
Sorry for not mentioning this earlier, but you can disable the warning entirely with:

``` scala
conflictWarning in ThisBuild := ConflictWarning.disable
```

You can alternatively keep the warning, but put it at the debug level:

``` scala
conflictWarning in ThisBuild ~= { _.copy(level = Level.Debug) }
```
