### ISSUE TITLE
-batch option doesn't work with OpenJDK-22/23

### ISSUE THREAD

**Issue by plokhotnyuk** [sbt/sbt#7091]
## steps

Run any multi-module project with `-batch` option

## problem

Sbt prints control symbols to the console

## expectation

No control symbols

**Comment by Friendseeker** [comment]
![image](https://github.com/user-attachments/assets/1dd61b94-01fd-441c-a029-ad474bf51ed3)

![image](https://github.com/user-attachments/assets/bf2b0227-ee8e-4303-a27e-85ceb9ccb1a6)

Not reproducible on Windows 11, JDK 23 and sbt 1.10.3

Feel free to reopen the issue if the issue is still reproducible on your end

**Comment by plokhotnyuk** [comment]
@Friendseeker Have you tried to store an output in a file yet?

I have a lot of `*.txt` files from historical runs of jsoniter-scala benchmarks that have control symbols in output.

Please see them in [this branch](https://github.com/plokhotnyuk/jsoniter-scala/tree/gh-pages).

All is fine with runs on JDK-17/21, but output from JDK-24 (and later JDK-22/23) contains a lot of them:

![image](https://github.com/user-attachments/assets/f550a0f1-5d33-4f7b-86a9-f9745b988a42)

**Comment by Friendseeker** [comment]
> @Friendseeker Have you tried to store an output in a file yet?
> 
> I have a lot of `*.txt` files from historical runs of jsoniter-scala benchmarks that have control symbols in output.
> 
> Please see them in [this branch](https://github.com/plokhotnyuk/jsoniter-scala/tree/gh-pages).
> 
> All is fine with runs on JDK-17/21, but output from JDK-24 (and later JDK-22/23) contains a lot of them:

Thanks for the info

Reproducible on sbt 1.10.4 & JDK 23 & Windows 11 (running `sbt -batch update` on a test project)

> [0m[[0m[0minfo[0m] [0m[0mwelcome to sbt 1.10.4 (Oracle Corporation Java 23.0.1)[0m[0J
> [0J[0m[[0m[0minfo[0m] [0m[0mloading project definition from D:\Repos\christ\project[0m[0J
> [0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[1000D
> [2K[2K  | => christ-build / Compile / compileIncremental 0s
> [2K[2A[1000D[0J[0m[[0m[0minfo[0m] [0m[0mloading settings for project root from build.sbt ...[0m[0J
> [0J[0m[[0m[0minfo[0m] [0m[0mset current project to christ (in build file:/D:/Repos/christ/)[0m[0J
> [0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[0J[1000D
> [2K[2K  | => root / update 0s
> [2K[2A[1000D[0J[0m[[0m[32msuccess[0m] [0m[0mTotal time: 1 s, completed Oct 30, 2024, 11:06:42ΓÇ»a.m.[0m[0J
> [0J[0J

Not reproducible on latest sbt snapshot build (https://github.com/sbt/sbt/commit/4835812e1c00fc0e74769e991fe3bb213032ef96) & JDK 23 & Windows 11

> [info] welcome to sbt 1.10.5-SNAPSHOT (Eclipse Adoptium Java 23.0.1)
> [info] loading project definition from D:\Repos\christ\project
> [info] loading settings for project root from build.sbt ...
> [info] set current project to christ (in build file:/D:/Repos/christ/)
> [success] Total time: 1 s, completed Oct 30, 2024, 11:17:31ΓÇ»a.m.

(Ignore the ΓÇ», it is a different but related issue that also a [pending PR fix](https://github.com/sbt/sbt/pull/7846)).

I think https://github.com/sbt/sbt/pull/7843 specifically fixed the issue. #7843 fixed sbt's detection of physical terminal on JDK22+. Basically JDK22+ started to create `System.console` even when a physical terminal do not exist (in this case, we are redirecting output so indeed no physical terminal), and I guess as a result sbt mistakenly thought a physical terminal is present and therefore printed all the control symbols.
