### ISSUE TITLE
Any way to generate JSON of dependency Tree?

### ISSUE THREAD

**Issue by rohitcoder** [sbt/sbt#7098]
I was trying https://github.com/sbt/sbt-dependency-graph and i found a way to generate a JSON dependency tree using ``sbt dependencyBrowseTree`` it generates a ``tree.json`` file in the target folder which has all the required details, but it also launches a viewer in a web browser, is there any way to stop this launch of a web browser?

And I wasn't able to find any library which generates a dependency list in JSON format, with all chid deps attached to it. Why we don't have something like that anywhere? Am i the only user, who is looking for this? This should be a important feature request?

**Comment by eed3si9n** [comment]
You can use Github's search feature to look for the implementation of built-in tasks - https://github.com/sbt/sbt/search?q=dependencyBrowseTree

```scala
      dependencyBrowseTree := openBrowser(dependencyBrowseTreeHTML).value,
```

Looks like you can type in `dependencyBrowseTreeHTML`, just get the files?
