### ISSUE TITLE
A `NoClassDefFoundError` exception is raised in sbt 1.8.1 on M1

### ISSUE THREAD

**Issue by jcazevedo** [sbt/sbt#7117]
## steps

Start `sbt` in version 1.8.1 on an M1 Mac via:

```
$ sbt
```

## problem

The following exception is raised on startup:

```
Exception in thread "sbt-socket-server" java.lang.NoClassDefFoundError: Could not initialize class org.scalasbt.ipcsocket.JNIUnixDomainSocketLibraryProvider
	at org.scalasbt.ipcsocket.UnixDomainSocketLibraryProvider.get(UnixDomainSocketLibraryProvider.java:26)
	at org.scalasbt.ipcsocket.UnixDomainSocketLibraryProvider.maxSocketLength(UnixDomainSocketLibraryProvider.java:31)
	at sbt.internal.server.Server$$anon$1$$anon$2.$anonfun$run$1(Server.scala:75)
	at scala.util.Try$.apply(Try.scala:213)
	at sbt.internal.server.Server$$anon$1$$anon$2.run(Server.scala:63)
```

## expectation

No exception is raised and the sbt server is able to start successfully.

## notes

I was able to dismiss the exception and get sbt server started successfully if I set `serverConnectionType := ConnectionType.Tcp` in my build.

**Comment by mkurz** [comment]
That sucks. Probably something went wrong from ipcsocket 1.5 to 1.6.1: https://github.com/sbt/ipcsocket/compare/v1.5.0...v1.6.1
Unfortuntaly I don't have time to look into that, maybe @eed3si9n knows the answer faster anyway...

**Comment by eed3si9n** [comment]
I am guessing that it's https://github.com/sbt/ipcsocket/commit/e9b01e175a50629c961071f65a924c906673ce6d?

I don't have M1 machine at hand. What does:

```scala
System.getProperty("os.arch", "").toLowerCase()
```

return on a REPL or sbt eval command?

**Comment by mzuehlke** [comment]
Mac M1
```Scala
scala> System.getProperty("os.arch", "")
res0: String = aarch64
```

**Comment by jcazevedo** [comment]
Do we also need a dylib built for darwin in `aarch64` under https://github.com/sbt/ipcsocket/tree/develop/src/main/resources?

**Comment by mkurz** [comment]
Fix is probably something like changing the condition in https://github.com/sbt/ipcsocket/commit/e9b01e175a50629c961071f65a924c906673ce6d to 
```java
      if (arch.equals("amd64") || isMac) {
        arch = "x86_64";
      }
```

**Comment by jcazevedo** [comment]
> Fix is probably something like changing the condition in [sbt/ipcsocket@e9b01e1](https://github.com/sbt/ipcsocket/commit/e9b01e175a50629c961071f65a924c906673ce6d) to
> 
> ```java
>       if (arch.equals("amd64") || isMac) {
>         arch = "x86_64";
>       }
> ```

Maybe also adding Windows to the mix? I suspect this might also be an issue in Windows machines running on ARM.

**Comment by mkurz** [comment]
> Maybe also adding Windows to the mix? I suspect this might also be an issue in Windows machines running on ARM.

The question is can Windows ARM handle libraries build by/for `x86_64`? I guess on M1 macOS this isn't a problem because of this Rosetta thing taking care of stuff like that?

**Comment by jcazevedo** [comment]
> The question is can Windows ARM handle libraries build by/for `x86_64`? I guess on M1 macOS this isn't a problem because of this Rosetta thing taking care of stuff like that?

Right! I have no idea if/how x86 emulation works on Windows ARM.

**Comment by eed3si9n** [comment]
> Fix is probably something like changing the condition in [sbt/ipcsocket@e9b01e1](https://github.com/sbt/ipcsocket/commit/e9b01e175a50629c961071f65a924c906673ce6d) to
> 
> ```java
>       if (arch.equals("amd64") || isMac) {
>         arch = "x86_64";
>       }
> ```

gaa. I'd forgotten that we use "universal binary" for macOS, which supports both x86_64 and aarch64, but it's in the x86_64 directory.

I don't think we do that for Windows, but I guess it's better to fallback on x86_64 and see if there's some emulation layer.

**Comment by eed3si9n** [comment]
Here's my PR for this - https://github.com/sbt/ipcsocket/pull/37

**Comment by will-sargent-eero** [comment]
I'm running into this on Apple M1

**Comment by eed3si9n** [comment]
sbt 1.8.2 is out - https://eed3si9n.com/sbt-1.8.2
