### ISSUE TITLE
SBT installer for Windows disregards custom path

### ISSUE THREAD

**Issue by dcsobral** [sbt/sbt#712]
While clicking on the button to select install path seems to work, when finished it keep displaying "Program Files (x86)" in the install path (as opposed to "Program Files" which I had selected), and installing it there as well.

Env: Windows Vista 64.

**Comment by jsuereth** [comment]
Thanks for the report, could you open on the sbt-launcher-package project, where the MSI is defined?

**Comment by dcsobral** [comment]
Turns out I had done it already.
