### ISSUE TITLE
`local arch="x86_64"`

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#7128]
this doesn't work on mac, it should be `local arch="x86_64"`:

> /opt/homebrew/Cellar/sbt/1.8.2/libexec/bin/sbt: line 174: local: `=': not a valid identifier

_Originally posted by @fredfp in https://github.com/sbt/sbt/pull/7111#discussion_r1065780262_

**Comment by mzuehlke** [comment]
Maybe an idea would be to integrate https://github.com/marketplace/actions/shellcheck into `ci.yml` ?

**Comment by mkurz** [comment]
Ups, sorry that was my fault :roll_eyes:

**Comment by julienrf** [comment]
Fixed by #7134 and #7144
