### ISSUE TITLE
Option to maintain execute permissions in IO.copy

### ISSUE THREAD

**Issue by jroper** [sbt/sbt#713]
It would be great if there was an option to maintain execute permissions in IO.copy, using File.canExecute/File.setExecutable.

**Comment by pvlugter** [comment]
I've implemented this in builds before and have also been meaning to suggest adding it to sbt. For example:

https://github.com/typesafehub/zinc/blob/master/project/Util.scala#L9-L34

**Comment by jroper** [comment]
Yeah I've used something similar in my build.

**Comment by harrah** [comment]
(Closing as a duplicate of the newer issue that had a contributed fix.)

**Comment by cos** [comment]
What is the id of the new issue? Thanks!
