### ISSUE TITLE
sbt: 1.8+, `set javaOptions += "@file"` will cause error: `Could not find or load main class @file`

### ISSUE THREAD

**Issue by spagreeks** [sbt/sbt#7132]
## steps

```sbt
set javaOptions += "@file"
runMain any.main.Method
```

**Comment by SethTisue** [comment]
Can you expand on why you believe this is a bug in sbt?

**Comment by gfZeng** [comment]
> expand

It's working on 1.7+

**Comment by spagreeks** [comment]
> Can you expand on why you believe this is a bug in sbt?
@SethTisue 
It works on 1.7+

**Comment by SethTisue** [comment]
I'm not able to reproduce the problem with the details you've provided.

project/build.properties

```
sbt.version=1.8.2
```

S.scala

```scala
object S extends App
```

build.sbt

```
scalaVersion := "2.13.10"
run / fork := true
```

**Comment by SethTisue** [comment]
I'm not able to reproduce the problem with the details you've provided.

project/build.properties

```
sbt.version=1.8.2
```

S.scala

```scala
object S extends App
```

build.sbt

```
scalaVersion := "2.13.10"
run / fork := true
```

file

```
-Xmx2G
```

and then:

```
sbt:tmp> runMain S
[info] running (fork) S 
[success] Total time: 0 s, completed Jan 15, 2023, 6:39:09 AM
```

don't know if matters, but this is on Eclipse Adoptium Java 17.0.5 on MacOS

**Comment by spagreeks** [comment]
all dash arguments(-any-options) works on javaOptions, only arguments file(@someFile) not working on javaOptions.

You can get detail on `java --help`

**Comment by SethTisue** [comment]
This is a bug tracker. It's not enough to say "not working", we need detailed instructions for how to reproduce the problem. You need to make a case that there is actually a bug in sbt.

we can reopen this if that information is brought forward

**Comment by SethTisue** [comment]
sorry, I see that my reproduction steps above were missing the `@file` part. but when I add that in, I still don't get the error you reported:

```
sbt:sbt-7132> set javaOptions += "@file"
...
sbt:sbt-7132> runMain S
[info] running (fork) S 
[success] Total time: 0 s, completed Jan 19, 2023, 10:38:20 AM
```

**Comment by spagreeks** [comment]
> sorry, I see that my reproduction steps above were missing the `@file` part. but when I add that in, I still don't get the error you reported:
> 
> ```
> sbt:sbt-7132> set javaOptions += "@file"
> ...
> sbt:sbt-7132> runMain S
> [info] running (fork) S 
> [success] Total time: 0 s, completed Jan 19, 2023, 10:38:20 AM
> ```
:-(, you should fork = true
```sbt
set run/fork := true
```

@SethTisue

**Comment by SethTisue** [comment]
@gfZeng I already have `run/fork := true` in my `build.sbt`, as shown in my comment above. additionally issuing `set run/fork := true` interactively doesn't affect the outcome

**Comment by spagreeks** [comment]
@SethTisue 
I have tried in my other projects, it's works well. this project really trouble me.
to be precise, this error only throws on `Test/runMain`. here is my sbt file:
```sbt

//cancelable in Global := true
run / fork := true
scalacOptions ++= Seq("-language:implicitConversions")
Test / logBuffered := false

Compile / unmanagedSourceDirectories += baseDirectory.value / "src" / "main" / "python"
Test / unmanagedSourceDirectories += baseDirectory.value / "src" / "test" / "python"

lazy val Q = project
  .in(file("."))
  .settings(
    name         := "Q",
    version      := "0.1.0",
    scalaVersion := "3.1.2"
  )

/** depends
  */
libraryDependencies += "org.log4s" %% "log4s" % "1.10.0"

libraryDependencies += "com.fasterxml.jackson.module" %% "jackson-module-scala" % "2.13.2"

libraryDependencies += "com.github.pjfanning" % "jackson-module-scala3-enum_3" % "2.13.1"

libraryDependencies += "com.fasterxml.jackson.dataformat" % "jackson-dataformat-csv" % "2.13.2"

libraryDependencies += "com.squareup.okhttp3" % "okhttp" % "4.9.3"

libraryDependencies += "ch.qos.logback" % "logback-classic" % "1.2.11"

libraryDependencies += "org.apache.commons" % "commons-lang3" % "3.12.0"

libraryDependencies += "com.typesafe" % "config" % "1.4.2"

libraryDependencies += "com.auth0" % "java-jwt" % "3.18.1"

libraryDependencies += "commons-codec" % "commons-codec" % "1.15"

libraryDependencies += "org.redisson" % "redisson" % "3.17.1"

libraryDependencies += "org.scalatest" %% "scalatest"       % "3.2.15" % Test 

```

```shell 
sbt --version
sbt version in this project: 1.8.2
sbt script version: 1.8.2
```

**Comment by SethTisue** [comment]
even with that `build.sbt` file, I'm still not able to reproduce the problem:

```
sbt:Q> set javaOptions += "@file"
...
sbt:Q> Test/runMain S
[info] running (fork) S 
[error] Error: Could not find or load main class S
[error] Caused by: java.lang.ClassNotFoundException: S
```

**Comment by SethTisue** [comment]
Great, I'm now able to reproduce the problem with the provided `build.sbt`, and you're right that it only happens with `Test/runMain`, not regular `runMain`.

My next question to you is: what is the _absolutely minimal_ `build.sbt` that still reproduces the problem? How much of what you provided is inessential and can be removed?

**Comment by spagreeks** [comment]
It's unclear what causes this problem. I have now found that removing scalatest can solve the problem. It seems that scalatest is causing the problem, but there is no problem if I just keep scalatest.

@SethTisue

**Comment by SethTisue** [comment]
weird! I don't know what to think. I had hoped enabling `debug` would cause the full Java command line to be shown, to help troubleshoot, but it isn't

**Comment by spagreeks** [comment]
Is that in processing?

**Comment by SethTisue** [comment]
Not sure what you mean — can you rephrase?
