### ISSUE TITLE
Pasting into Scala shell provided by sbt console is slow

### ISSUE THREAD

**Issue by tomonacci** [sbt/sbt#7155]
## steps

1. In Mac OS Terminal, go to an empty directory and run `sbt console`
2. Paste in a long string and observe that there is a delay before each character appears on the screen

- macOS Ventura 13.2
- sbt version 1.8.2
- Java 17.0.6

## problem

It seems to share the root cause with #6644, i.e., per-character invocation of `isEchoEnabled` which leads to forking `stty`. I opened a new issue only because it is not about sbt's own shell (`sbt shell`), which by the way works fine for me with regard to pasting in long strings.

## expectation

Pasting is instantaneous. It should take only roughly as long as it would if you pasted the same string into a Scala shell you get by invoking `scala`.

## notes

**Comment by eed3si9n** [comment]
@tomonacci Thanks for the report.
