### ISSUE TITLE
Binary-compatible versions are suspected to be binary incompatible

### ISSUE THREAD

**Issue by seanrohead** [sbt/sbt#7163]
## steps

I am using sbt 1.8.2 (with Coursier disabled) and I'm importing multiple libraries using early-semver as the version scheme. I'm seeing an error message that transitive dependencies are suspected to be binary incompatible, even though the version numbers have the same major, minor, and patch version, and differ only in the qualifier

```
(update) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:

* com.proofpoint:commons-http_2.13:8.0.0-DLP-12867-remove-commons-logging.4 (early-semver) is selected over 8.0.0-DLP-12867-remove-commons-logging.2
+- com.proofpoint:commons-authenticator-oit_2.13:7.0.0-DLP-12867-remove-commons-logging.5 () (depends on 8.0.0-DLP-12867-remove-commons-logging.4)
+- com.proofpoint:unified-edm-ingestion_2.13:0.0.0-SNAPSHOT () (depends on 8.0.0-DLP-12867-remove-commons-logging.2)
```

The two versions that are suspected to be incompatible are:

- 8.0.0-DLP-12867-remove-commons-logging.4
- 8.0.0-DLP-12867-remove-commons-logging.2

## problem

I'm getting an error when building that there are version conflicts that are suspected to be binary incompatible.

## expectation

The build should succeed as the two versions that are suspected to be incompatible have the same major, minor, and patch version

**Comment by seanrohead** [comment]
This bug is very similar to [#6496], which was fixed, so this is either a regression or the version numbers are failing for a slightly different reason.

**Comment by eed3si9n** [comment]
According to [the Semantic Versioning spec](https://semver.org/#spec-item-9):
> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version.

"8.0.0-DLP-12867-remove-commons-logging.4" is a pre-release version like `-M1`.

> A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version.

So because this is a pre-release of `major.0.0`, in this case sbt is correct to assume that they are binary incompatible.
