### ISSUE TITLE
How to compile and bootstrap from source

### ISSUE THREAD

**Issue by bastien-roucaries** [sbt/sbt#7167]
Hi,

I want to compile sbt from source for debian

I could not find documentation for compiling from source sbt

Could you please:
- explain how to compile from source
- the bootstrap process

rouca

**Comment by SethTisue** [comment]
To build the current version of sbt, you need to use a previous version of sbt. There is no way around this.

> explain how to compile from source

there are full instructions in DEVELOPING.md

**Comment by SethTisue** [comment]
There is some pretty extensive previous discussion at https://contributors.scala-lang.org/t/compiling-scala-and-sbt-for-debian-distro/3620
