### ISSUE TITLE
Non-compliant parsing of maven's settings.xml file

### ISSUE THREAD

**Issue by nrinaudo** [sbt/sbt#7195]
## steps

Have a non-default maven [`settings.xml`](https://maven.apache.org/settings.html) file on your system, in which you customized the `localRepository` element to point to an environment variable.

This is perfectly legal and is, in fact, the first example in the [Simple values](https://maven.apache.org/settings.html#simple-values) section:
```xml
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
  <localRepository>${user.home}/.m2/repository</localRepository>
...
```

Then attempt to run `sbt publishM2` in some valid project.

## problem

The variable, instead of being expanded, will be used as is in the path, resulting in artifacts being published to, say, `./${env.FOO_BAR}/path/to/artifacts`.

## expectation

Variables should be expended, as documented in the `settings.xml` documentation.

## notes

Here's the [source of the problem](https://github.com/sbt/librarymanagement/blob/develop/core/src/main/scala/sbt/librarymanagement/ResolverExtra.scala#L400-L402):
```scala
          ((XML.loadFile(file) \ "localRepository").text match {
            case ""    => None
            case e @ _ => Some(new File(e))
```

Notice how no expansion is being performed in the content of the node.

**Comment by eed3si9n** [comment]
Thanks for the report!

**Comment by eed3si9n** [comment]
@nrinaudo Would you consider sending a PR for this?

**Comment by nrinaudo** [comment]
I initially thought this was an interpreted language - maybe groovy or something- and was about to answer “ha ha no”, but it’s apparently strictly limited to environment variables and system properties, which seem a lot more manageable. It’s also very local to that file, so, sure, that should be manageable!
