### ISSUE TITLE
Add standard command for ;compile;copy-resources

### ISSUE THREAD

**Issue by retronym** [sbt/sbt#72]
This is the most common command that users of the IDEA SBT plugin want to use as a replacement for the built in Make from IntelliJ. It's would be convenient to have a built in command for this; otherwise all users need to modify there global SBT settings.

I tried to find an existing command; exported-products was sufficient, but does too much.

We would need this available in the Test scope, too.

Note that in the Maven world, compile depends on copy-resources. If you're open to the idea of copying that approach, it would avoid the problem of naming this new command. (I call it 'prepare' and 'test-prepare' in my SBT 0.7.x builds, but that's a wishy-washy name)

**Comment by ijuma** [comment]
Agreed. This is what I have in my build file:

```
lazy val prepareRunSetting = TaskKey[Unit]("prepare-run").in(Test) <<= Seq(compile.in(Test), copyResources.in(Test)).dependOn
```

I had something similar for SBT 0.7.x.

**Comment by ijuma** [comment]
Btw, I just added it to the Test scope because I wanted the Test one to be the default in Global scope and when I had it in both compile and test, the former was the default in Global scope. This is applicable for our usage, but it probably would not be what you want for sbt itself.

**Comment by harrah** [comment]
Use 'products' and 'test:products'. The definition of products is:

```
products <<= (compile, compileInputs, copyResources) map { (_, i, _) =>
   ...trivial work...
}
```

(exported-products by default is basically products, so I'm not sure what is too much about it?)

**Comment by ijuma** [comment]
I thought exported-products was:

```
def exportProductsTask: Initialize[Task[Classpath]] =
  (products.task, packageBin.task, exportJars, compile) flatMap { (psTask, pkgTask, useJars, analysis) =>
    (if(useJars) Seq(pkgTask).join else psTask) map { _ map { f => analyzed(f, analysis) } }
}
```

**Comment by retronym** [comment]
Thanks, sorry for the noise.

**Comment by harrah** [comment]
@ijuma: It is.

When you call .task on a `ScopedTask[T]`, it converts it into a `ScopedSetting[Task[T]]` so that you get an reference to the actual underlying Task and not the resulting value of the task.  So, it doesn't force the task to run.  The definition then uses the value of exportJars to decide whether products or packageBin should be run.  flatMap allows this dynamic decision making for tasks.

**Comment by ijuma** [comment]
I see. Thanks for the explanation.
