### ISSUE TITLE
Error fetching artifacts when init sbt cause by forbidden 

### ISSUE THREAD

**Issue by nuaadupuliu** [sbt/sbt#7207]
## steps
EVN: 
```
System: Linux  5.4.226-129.415.amzn2.x86_64 #1 SMP x86_64 GNU/Linux
JDK: openjdk version "11.0.16" 2022-07-19
        OpenJDK Runtime Environment 18.9 (build 11.0.16+8)
        OpenJDK 64-Bit Server VM 18.9 (build 11.0.16+8, mixed mode, sharing)
SBT: sbt 1.8.2  
```
In project run **sbt clean compile**  command.

## problem
The dependency can't be download with forbidden.

11:31:02  downloading sbt launcher 1.8.2
11:31:02  copying runtime jar...
11:31:04  [info] [launcher] getting org.scala-sbt sbt 1.8.2  (this may take some time)...
11:31:07  [info] [launcher] getting Scala 2.12.17 (for sbt)...
11:31:07  [info] welcome to sbt 1.8.2 ()
11:31:10  [info] loading settings for project src_repo-build from plugins.sbt ...
11:31:10  [info] loading project definition from /home/eis/src_repo/project
11:31:17  [error] lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
11:31:17  [error] https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.5.2/jars/sbt-native-packager.jar: forbidden: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.5.2/jars/sbt-native-packager.jar
11:31:17  [error] https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.dwijnand/sbt-compat/scala_2.12/sbt_1.0/1.2.6/docs/sbt-compat-javadoc.jar: forbidden: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.dwijnand/sbt-compat/scala_2.12/sbt_1.0/1.2.6/docs/sbt-compat-javadoc.jar
11:31:17  [error] https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-js-engine/scala_2.12/sbt_1.0/1.2.3/docs/sbt-js-engine-javadoc.jar: forbidden: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-js-engine/scala_2.12/sbt_1.0/1.2.3/docs/sbt-js-engine-javadoc.jar
11:31:17  [error] https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.5.2/docs/sbt-native-packager-javadoc.jar: forbidden: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.5.2/docs/sbt-native-packager-javadoc.jar
11:31:17  [error] https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-web/scala_2.12/sbt_1.0/1.4.4/docs/sbt-web-javadoc.jar: forbidden: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-web/scala_2.12/sbt_1.0/1.4.4/docs/sbt-web-javadoc.jar
11:31:17  [error] 
11:31:17  [error] 	at lmcoursier.internal.shaded.coursier.Artifacts$.$anonfun$fetchArtifacts$9(Artifacts.scala:365)
11:31:17  [error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
11:31:17  [error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
11:31:17  [error] 	at lmcoursier.internal.shaded.coursier.util.Task$.wrap(Task.scala:82)
11:31:17  [error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
11:31:17  [error] 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
11:31:17  [error] 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
11:31:17  [error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
11:31:17  [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
11:31:17  [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
11:31:17  [error] 	at java.base/java.lang.Thread.run(Thread.java:829)

When download it manually, it changed to https://scala.jfrog.io/ui/native/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.5.2/jars/sbt-native-packager.jar

## expectation
Dependencies should be download successfully.

**Comment by SethTisue** [comment]
at my location, `curl -L -O 'https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.5.2/jars/sbt-native-packager.jar'` succeeds fine

perhaps you're experiencing some lingering after-effect of #7202?

**Comment by SethTisue** [comment]
I also tried, in an otherwise empty directory:

```
% cat project/plugins.sbt 
addSbtPlugin("com.typesafe.sbt" %% "sbt-native-packager" % "1.5.2")
% sbt
[info] Updated file /Users/tisue/tmp/sbt-7207/project/build.properties: set sbt.version to 1.8.2
[info] welcome to sbt 1.8.2 (Eclipse Adoptium Java 17.0.6)
[info] loading settings for project sbt-7207-build from plugins.sbt ...
[info] loading project definition from /Users/tisue/tmp/sbt-7207/project
[info] Updating 
https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_…
  100.0% [##########] 3.6 KiB (1.5 KiB / s)
[info] Resolved  dependencies
[info] Fetching artifacts of 
https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.1.1/scala-xml_2.12-1.1.1.jar
  100.0% [##########] 540.4 KiB (1.4 MiB / s)
https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_…
  100.0% [##########] 138.8 KiB (80.2 KiB / s)
https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_…
  100.0% [##########] 1.9 MiB (758.1 KiB / s)
https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_…
  100.0% [##########] 835.2 KiB (129.0 KiB / s)
...
```

so whatever you're experiencing is local and/or transient, I think

**Comment by nuaadupuliu** [comment]
Yes, the issue was resolved, I try it on my local machine, works well now, @SethTisue thank you.
