### ISSUE TITLE
[1.9.x] POM consistent publishing breaks on sbt 0.13 cross building

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#7210]
## steps

See https://repo1.maven.org/maven2/com/github/sbt/sbt-license-report_2.10_0.13/1.3.0/.

## problem
[sbt-license-report_2.10_1.0-1.3.0.pom](https://repo1.maven.org/maven2/com/github/sbt/sbt-license-report_2.10_0.13/1.3.0/sbt-license-report_2.10_1.0-1.3.0.pom)             2023-04-08 21:57      2129      
[sbt-license-report_2.10_1.0-1.3.0.pom.asc](https://repo1.maven.org/maven2/com/github/sbt/sbt-license-report_2.10_0.13/1.3.0/sbt-license-report_2.10_1.0-1.3.0.pom.asc)         2023-04-08 21:57       659      
[sbt-license-report_2.10_1.0-1.3.0.pom.asc.md5](https://repo1.maven.org/maven2/com/github/sbt/sbt-license-report_2.10_0.13/1.3.0/sbt-license-report_2.10_1.0-1.3.0.pom.asc.md5)     2023-04-08 21:57        32      
[sbt-license-report_2.10_1.0-1.3.0.pom.asc.sha...](https://repo1.maven.org/maven2/com/github/sbt/sbt-license-report_2.10_0.13/1.3.0/sbt-license-report_2.10_1.0-1.3.0.pom.asc.sha1)  2023-04-08 21:57        40      
[sbt-license-report_2.10_1.0-1.3.0.pom.md5](https://repo1.maven.org/maven2/com/github/sbt/sbt-license-report_2.10_0.13/1.3.0/sbt-license-report_2.10_1.0-1.3.0.pom.md5)         2023-04-08 21:57        32      
[sbt-license-report_2.10_1.0-1.3.0.pom.sha1](https://repo1.maven.org/maven2/com/github/sbt/sbt-license-report_2.10_0.13/1.3.0/sbt-license-report_2.10_1.0-1.3.0.pom.sha1)        2023-04-08 21:57        40

## expectation

It should produce `sbt-license-report_2.10_0.13-1.3.0.pom` with **0.13**.

**Comment by SethTisue** [comment]
I have a feeling you won't go for this, but I would be happy to see support for publishing 0.13 plugins dropped.

**Comment by eed3si9n** [comment]
If a semi-abandoned plugin can (with some upkeep) be republished to Maven Central, using the latest sbt 1.x, why not?

**Comment by SethTisue** [comment]
> why not?

because it doesn't currently work and fixing it would take effort that could be spent elsewhere. and might consume further such effort down the road, too

**Comment by SethTisue** [comment]
well I guess it's good my pessimism didn't discourage y'all from doing the one line fix :-)
