### ISSUE TITLE
Error fetching sbt-giter8-scaffold

### ISSUE THREAD

**Issue by joelonsw** [sbt/sbt#7211]
## steps

ENV: 
```
System: Darwin MacBookPro.local 21.4.0 Darwin Kernel Version 21.4.0; 
root:xnu-8020.101.4~2/RELEASE_ARM64_T6000 arm64

JDK: OpenJDK 11.0.18

SBT: sbt 1.5.2
```

## problem

The dependency download fails. Status 404 is returned from the repository. 
```
[info] welcome to sbt 1.5.2 (Eclipse Adoptium Java 11.0.18)
[info] loading settings for project bzm-lounge-build from plugins.sbt ...
[info] loading project definition from {project}
[warn]
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		org.foundweekends.giter8:sbt-giter8-scaffold:0.11.0 (sbtVersion=1.0, scalaVersion=2.12)
[warn]
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading org.foundweekends.giter8:sbt-giter8-scaffold;sbtVersion=1.0;scalaVersion=2.12:0.11.0
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/foundweekends/giter8/sbt-giter8-scaffold_2.12_1.0/0.11.0/sbt-giter8-scaffold-0.11.0.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/org.foundweekends.giter8/sbt-giter8-scaffold/scala_2.12/sbt_1.0/0.11.0/ivys/ivy.xml

[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.foundweekends.giter8:sbt-giter8-scaffold;sbtVersion=1.0;scalaVersion=2.12:0.11.0
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/foundweekends/giter8/sbt-giter8-scaffold_2.12_1.0/0.11.0/sbt-giter8-scaffold-0.11.0.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/org.foundweekends.giter8/sbt-giter8-scaffold/scala_2.12/sbt_1.0/0.11.0/ivys/ivy.xml
```

Accessing the following link(https://scala.jfrog.io/ui/native/ivy-releases/org.foundweekends.giter8/sbt-giter8-scaffold/scala_2.12/sbt_1.0/0.11.0/ivys/ivy.xml) returns the 404 page as follows. 
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/61370901/230823645-c64a99ea-35e7-4429-88c9-2ef3912efe08.png">

## expectation
Dependencies should be download successfully.

**Comment by SethTisue** [comment]
is the problem reproducible with sbt 1.8.2? 1.5.2 is very old.

the plugin fetches fine for me with 1.8.2:

```
% cat project/plugins.sbt 
addSbtPlugin("org.foundweekends.giter8" % "sbt-giter8-scaffold" % "0.11.0")
% sbt
[info] welcome to sbt 1.8.2 (Eclipse Adoptium Java 17.0.6)
[info] loading settings for project sbt-7211-build from plugins.sbt ...
[info] loading project definition from /Users/tisue/tmp/sbt-7211/project
[warn] sbt-giter8-scaffold.jar no longer exists at /Users/tisue/Library/Caches/Coursier/v1/https/repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.foundweekends.giter8/sbt-giter8-scaffold/scala_2.12/sbt_1.0/0.11.0/jars/sbt-giter8-scaffold.jar
[info] Updating 
https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.foundweekends.giter8/sbt-giter8-scaffold/scala_2.12/sbt_1.0/0.11.0/ivys/ivy.xml
  100.0% [##########] 1.7 KiB (1.3 KiB / s)
[info] Resolved  dependencies
[info] Fetching artifacts of 
[info] Fetched artifacts of 
[info] set current project to sbt-7211 (in build file:/Users/tisue/tmp/sbt-7211/)
...
```

perhaps you are experiencing some transient and/or local aftereffect of #7202

**Comment by adpi2** [comment]
@joelonsw I see that you :+1: Seth's response so I am closing this issue. Feel free to reopen it if you think there is still a bug.

**Comment by joelonsw** [comment]
@adpi2 Hi. Still same issue happens after two days have passed :( 
Should I reopen the same issue? It seems like the following repositories doesn't support hosting sbt-giter8-scaffold any more. 

https://repo1.maven.org/maven2/org/foundweekends/giter8/sbt-giter8-scaffold_2.12_1.0/0.11.0/sbt-giter8-scaffold-0.11.0.pom

https://repo.typesafe.com/typesafe/ivy-releases/org.foundweekends.giter8/sbt-giter8-scaffold/scala_2.12/sbt_1.0/0.11.0/ivys/ivy.xml

**Comment by SethTisue** [comment]
@joelonsw You are mistaken. Those artifacts never existed on repo1.maven.org or repo.typesafe.com. #7205 addresses this common misunderstanding.

The artifacts do exist on repo.scala-sbt.org — please re-read my comment above. There is no further problem on that server. `curl -f -O -L https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.foundweekends.giter8/sbt-giter8-scaffold/scala_2.12/sbt_1.0/0.11.0/ivys/ivy.xml` succeeds.

Perhaps your machine is behind some proxy or firewall that is causing difficulty?

**Comment by joelonsw** [comment]
@SethTisue 
Sorry for the confusion. I missed the point of getting the artifact from repo.scala-sbt.org

By removing the `org.foundweekends.giter8` cache from my local machine, the problem has been solved. 
```
rm -rf ~/Library/Caches/Coursier/v1/https/repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.foundweekends.giter8
```

I guess sbt checked my local machine's cache to check if there was a history of downloading giter8 from repo.scala-sbt.org. 

However, the cached giter8 artifact was invalid so it move on to repo1.maven.org / repo.typesafe.com to check whether the alternative is available (which was not available since it never existed).

Thank you for your help!

**Comment by SethTisue** [comment]
glad to hear it’s sorted! when I get a moment I’ll add your caching advice to the other tickets
