### ISSUE TITLE
sbt 1.9.0-RC1 failing with checksum files must be unique

### ISSUE THREAD

**Issue by mdedetrich** [sbt/sbt#7233]
## steps

I created a PR https://github.com/apache/incubator-pekko-grpc/pull/64 against pekko-grpc upgrading from SBT 1.8.2 to 1.9.0-RC1 specifically to bring in a new feature https://github.com/sbt/sbt/pull/7165.

When upgrading to this newer SBT version I noticed that `publishLocal` started failing in CI

## problem

When trying to publish a project locally, sbt 1.9.0-RC1 now fails with 

```
[error] java.lang.IllegalArgumentException: requirement failed: Checksum filenames should be unique
[error] 	at scala.Predef$.require(Predef.scala:281)
[error] 	at net.bzzt.reproduciblebuilds.Certification.<init>(Certification.scala:42)
[error] 	at net.bzzt.reproduciblebuilds.Certification$.apply(Certification.scala:118)
[error] 	at net.bzzt.reproduciblebuilds.ReproducibleBuildsPlugin$.$anonfun$ourCertification$1(ReproducibleBuildsPlugin.scala:61)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:750)
```

## expectation

For `publishLocal` to work with latest SBT 1.9.0-RC1

## notes

I created another PR which **only** bumps the SBT version and its also failing, see https://github.com/apache/incubator-pekko-grpc/pull/65. This makes me assume that the issue has nothing to do with https://github.com/sbt/sbt/pull/7165 but some feature which was merged into SBT from 1.8.2 to 1.9.0-RC1, possibly https://github.com/sbt/sbt/pull/7096 ?

**Comment by adpi2** [comment]
Thanks @mdedetrich for opening this issue, I am looking into it.

**Comment by mdedetrich** [comment]
I am currently trying to debug the issue as well, I think that setting `sbtPluginPublishLegacyMavenStyle` to false for every sbt plugin that pekko-grpc defines may solve the issue

**Comment by adpi2** [comment]
If you run `show myPlugin / packagedArtifacts` you should see that some artifacts points to the same file:

```
Map(
  Artifact(myPlugin_2.12_1.0, doc, jar, Some(javadoc), Vector(compile), None, Map(), None, false) ->
    myPlugin/target/scala-2.12/sbt-1.0/myPlugin-0.1.0-SNAPSHOT-javadoc.jar,
 ...
  Artifact(myPlugin, doc, jar, Some(javadoc), Vector(compile), None, Map(), None, false) ->
    myPlugin/target/scala-2.12/sbt-1.0/myPlugin-0.1.0-SNAPSHOT-javadoc.jar,
```

That is intended because those two artifacts must be identical. But the `sbt-reproducible-build` plugin does not like it.

To fix this we can either (1) copy the files, so that each artifact points to a different file, or (2) make `sbt-reproducible-build` more lenient.

I can push a PR with (1).

**Comment by mdedetrich** [comment]
Thanks for investigating, I am actually wondering whether (2) is the more principled solution?

**Comment by adpi2** [comment]
> Thanks for investigating, I am actually wondering whether (2) is the more principled solution?

Maybe but it is hard to know how many other plugins or builds rely on the assertion that two artifacts should points to different files. (1) seems reasonable enough and it can prevent all the users of sbt-reproducible-build to bump into this bug.

**Comment by mdedetrich** [comment]
> Maybe but it is hard to know how many other plugins or builds rely on the assertion that two artifacts should points to different files. (1) seems reasonable enough and it can prevent all the users of sbt-reproducible-build to bump into this bug.

Fair point, thanks for looking into this!
