### ISSUE TITLE
SBT fails to start on the latest JDK-21 builds since build 21 (2023/5/4)

### ISSUE THREAD

**Issue by plokhotnyuk** [sbt/sbt#7235]
## steps

1. Download and extract [jdk-21-ea](https://jdk.java.net/21/) to `/usr/lib/jvm/jdk-21`
2. Run `sbt -java-home /usr/lib/jvm/jdk-21`

## problem

The sbt fails to start with the following error:
```
[info] [launcher] getting org.scala-sbt sbt 1.9.0-RC1  (this may take some time)...
[info] welcome to sbt 1.9.0-RC1 (Oracle Corporation Java 21-ea)
error:
  bad constant pool index: 0 at pos: 47919
     while compiling: <no file>
        during phase: globalPhase=<no phase>, enteringPhase=<some phase>
     library version: version 2.12.17
    compiler version: version 2.12.17
  reconstructed args: -classpath /home/andriy/.sbt/boot/scala-2.12.17/lib/scala-library.jar -Yrangepos

  last tree to typer: EmptyTree
       tree position: <unknown>
            tree tpe: <notype>
              symbol: null
           call site: <none> in <none>
...
```

## expectation

Normal start

## notes

- Reproducible on both sbt versions `1.8.2` and `1.9.0-RC1`
- Works fine with older jdk-21 builds (build 20 or older)

**Comment by eed3si9n** [comment]
@plokhotnyuk Thanks for the report! I wonder if Scala 2.12.17 in general works on JDK 21-ea.

**Comment by mkurz** [comment]
I would guess this fails because Scala 2.12.17 comes with an asm version that does not yet support Java 21.
Upcoming Scala 2.12.18 / 2.13.11 should fix that. See the draft release notes for 2.12.18 for example, mentions Java 20/21 support via asm upgrade: https://github.com/scala/scala-dev/blob/scala-2.12.18/releases/2.12.18.md

**Comment by mkurz** [comment]
Actually I think it would be good idea to wait for Scala 2.12.18/2.13.11 for the 1.9.0 final release and use that within sbt then...

**Comment by cushon** [comment]
I'm seeing the same `bad constant pool index: 0` error with JDK 21 EA builds, with a stack trace like:

```
	at scala.reflect.internal.Reporting.abort(Reporting.scala:69)
	at scala.reflect.internal.Reporting.abort$(Reporting.scala:65)
	at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:28)
	at scala.tools.nsc.symtab.classfile.ClassfileParser$ConstantPool.errorBadIndex(ClassfileParser.scala:385)
	at scala.tools.nsc.symtab.classfile.ClassfileParser$ConstantPool.getExternalName(ClassfileParser.scala:249)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.readParamNames$1(ClassfileParser.scala:828)
```

edit: since the underlying issue is a scala problem, not an sbt problem, I reported it here: https://github.com/scala/bug/issues/12783

**Comment by eed3si9n** [comment]
@mkurz

> Actually I think it would be good idea to wait for Scala 2.12.18/2.13.11 for the 1.9.0 final release and use that within sbt then...

As far as I know there's no set release date for [Scala 2.12.18](https://contributors.scala-lang.org/t/scala-2-12-18-release-planning/6089/4?u=eed3si9n) since it's waiting on Scala 3.3.0 final, which just released its RC-6 and [release thread](https://contributors.scala-lang.org/t/3-3-0-release-thread/6079/6) doesn't mention it, so even with the best case scenario we are like 3 weeks out?
I've discussed this with @adpi2, and we think waiting on this makes things slower than it should be given that we could potentially bump Scala version in a patch release.

**Comment by mkurz** [comment]
I didn't expect a RC6, but yes, no need to wait. I thought it should be released already... but who knows.

**Comment by SethTisue** [comment]
We've published Scala 2.12.18-M2 and Scala 2.13.11-M2 to Maven Central with a fix for scala/bug#12783. You can start sbt on JDK 21 with `sbt -Dsbt.scala.version=2.12.18-M2` and it should start up. (Though you might be stymied if you are using plugins such as scoverage that haven't been published for 2.12.18-M2; if so, you'll need to wait for 2.12.18.)

I'll submit the same fix to Scala 3, though it won't make 3.3.0.

(2.12.18 and 2.13.11 will come along not long after Scala 3.3.0 is released.)

**Comment by mkurz** [comment]
@SethTisue Seems like the M2 git-tags didn't make it upstream? https://github.com/scala/scala/tags

**Comment by SethTisue** [comment]
@mkurz oh good call, I didn't think to tag either release. they are tagged now

**Comment by SethTisue** [comment]
Scala 2.12.18 is on Maven Central (to be announced next week, as per https://contributors.scala-lang.org/t/scala-2-12-18-release-planning/6089/)

**Comment by eed3si9n** [comment]
Here's my PR for this - https://github.com/sbt/sbt/pull/7271
