### ISSUE TITLE
Spurious incremental recompilation due to invalid value for OVERRIDE flag

### ISSUE THREAD

**Issue by gkossakowski** [sbt/sbt#726]
The incremental spuriously (on whitespace change) recompiles dependencies of a file that refers to type alias of certain kind. The example code explains it the best:

``` scala
// Foo.scala
object Foo {
  class Inner { type Xyz }
  type TypeInner = Inner { type Xyz = Int }
}

// Bar.scala
object Bar { 
  def bar: Foo.TypeInner = null
}

// Impl.scala
class Impl {
  def bleep = Bar.bar
}
```

Now, if you compile those 3 files and make a whitespace change to `Bar.scala` it'll trigger recompilation of `Impl.scala`.

If you run this test with api-diff branch merged you can easily see what's going on:

```
[info] [debug] Detected a change in a public API:
[info] [debug] --- /private/var/folders/0k/31jh6c293n31_tjkxmk90jjh0000gn/T/sbt_14084e7/inc-abstract-type-override/src/main/scala/Bar.scala
[info] [debug] +++ /private/var/folders/0k/31jh6c293n31_tjkxmk90jjh0000gn/T/sbt_14084e7/inc-abstract-type-override/src/main/scala/Bar.scala
[info] [debug] @@ -25,8 +25,8 @@
[info] [debug]  ^inherited^ final def $isInstanceOf[ java.lang.Object.T0 >: scala.this#Nothing <: scala.this#Any](): scala.this#Boolean
[info] [debug]  ^inherited^ final def $asInstanceOf[ java.lang.Object.T0 >: scala.this#Nothing <: scala.this#Any](): <java.lang.Object.T0>
[info] [debug]  def bar: this#Outer#Inner with java.lang.this#Object with scala.this#Any
[info] [debug]  {
[info] [debug]  
[info] [debug] -type Xyz = scala.this#Int
[info] [debug] +override type Xyz = scala.this#Int
[info] [debug]  }
[info] [debug]  }
```

This modifier appears and disappears depending on whether you recompile all files together or separately. Ultimately, this is a bug in the compiler related to separate compilation. The underlaying issue is tracker here: https://issues.scala-lang.org/browse/SI-7361

**Comment by retronym** [comment]
Iulian made a good point: override need not be part of the API has, as it only affects the current file. That is, subclasses and clients need not be recompiled if the override modifier is added/removed from a member.

This is not to say that we should tolerate flag instability in the compiler; we'll fix that too.

**Comment by harrah** [comment]
I don't remember the implementation details of flags off hand, but at least conceptually, override does affect other files via `abstract override`.

**Comment by retronym** [comment]
`abstract override` is actually a separate flag, `ABSOVERRIDE`.

**Comment by harrah** [comment]
Nice catch, thanks.  The second commit shows a test case where just the override changing (in B.scala) requires recompilation of another file (D.scala).

**Comment by dragos** [comment]
So, given that `OVERRIDE` and `ABSOVERRIDE` are different, wouldn't it be good to drop `OVERRIDE` from the API? It would fix this particularly annoying bug for existing Scala versions, too.

**Comment by harrah** [comment]
"The second commit shows a test case where just the override changing (in B.scala) requires recompilation of another file (D.scala)."

**Comment by dragos** [comment]
"Sorry I missed that"

**Comment by gkossakowski** [comment]
I accidentally reopened this issue but clicking the wrong button on issue list. I'm very sorry for that. Closing again.
