### ISSUE TITLE
Deprecate/remove vscode plugin?

### ISSUE THREAD

**Issue by kubukoz** [sbt/sbt#7262]
Is there any reason to keep the vscode extension alive? Its functionality seems to have been improved upon in Metals (with completions and navigation in sbt build files, and all the BSP goodies), and it hasn't seen code changes in years so I'm not even sure it works these days.

**Comment by eed3si9n** [comment]
Yea. It's essentially subsumed by BSP server, so I don't think there's any reason to keep the VS Code plugin around.

**Comment by eed3si9n** [comment]
It should be off the marketplace now - https://marketplace.visualstudio.com/vscode

**Comment by kubukoz** [comment]
oh, great! I was thinking if we should have a final release mentioning the deprecation. This makes the removal much easier for me :P I'll drop a PR later.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/7307
