### ISSUE TITLE
Easily reproducible bug in sbt's incremental compilation

### ISSUE THREAD

**Issue by markehammons** [sbt/sbt#727]
I'm in the course of porting my project to sbt, and one of the sbt build configuration files is now showing this error. When I change it in any way, such as adding a semicolon to the end of a line, the recompilation of the sbt project fails with the error:

```
[error] /home/luft/Documents/Work/openmole/project/src/main/scala/root/gui/GuiDefaults.scala:1: class file needed by package is missing.
[error] reference type GuiDefaults of package root.gui refers to nonexisting symbol.
[error] package root.gui
```

This can be fixed by deleting the target folder in the project folder.

My project is hosted at git://git.openmole.org/openmole, the affected revision is cafbd666238857e5064b20ce9529e0ff24eb38a6 on branch sbt-port of my project. The affected file is project/src/main/scala/root/gui/GuiDefaults.scala.

This issue effects at least 0.12.2 and greater.

**Comment by gkossakowski** [comment]
As discussed here: https://groups.google.com/d/msg/simple-build-tool/ra2LHQLuask/oq8-VkUhASEJ the reported problem is not related to sbt's incremental compilation.

I recommend closing this issue.

@markehammons: if you manage to reproduce this problem with minimal set of source files please check Scala bug database. If you don't find any ticket describing your problem please report there.
