### ISSUE TITLE
withSources() expecting a .src file instead of a .jar file?

### ISSUE THREAD

**Issue by ximyu** [sbt/sbt#728]
The `twitter/finagle` project has the following sbt config, which depends on com.twitter.common%metrics%0.0.6 withSources().

``` scala
lazy val finagleStats = Project(
  id = "finagle-stats",
  base = file("finagle-stats"),
  settings = Project.defaultSettings ++
    sharedSettings
).settings(
  name := "finagle-stats",
  libraryDependencies ++= Seq(
    "com.twitter.common" % "metrics" % "0.0.6" withSources(),
    jacksonLib)
).dependsOn(finagleCore, finagleHttp)
```

And I looked in to my `~/ivy2/cache/com.twitter/finagle-stats_2.9.2/ivy-6.3.0.xml` file and see the following generated XML:

``` xml
<dependency org="com.twitter.common" name="metrics" rev="0.0.6" force="true" conf="compile->compile(*),master(*);runtime->runtime(*)">
  <artifact name="metrics" type="src" ext="src" conf="compile,runtime" m:classifier="sources"/>
  <artifact name="metrics" type="jar" ext="jar" conf="compile,runtime"/>
</dependency>
```

Then SBT is trying to find something at `http://maven.twttr.com/com/twitter/common/metrics/0.0.6/metrics-0.0.6-sources.src` while the correct URL should be `http://maven.twttr.com/com/twitter/common/metrics/0.0.6/metrics-0.0.6-sources.jar`.

Is this an Ivy bug or SBT bug?  Thanks.

**Comment by harrah** [comment]
Can you provide steps to reproduce, please?

**Comment by ximyu** [comment]
Creating any project with dependency "com.twitter" %% "finagle-stats" % 6.3.0 would repro this bug.  I'm also finding this bug for specs.

Here is the SBT project file for finagle https://github.com/twitter/finagle/blob/master/project/Build.scala

All the uses of withSources() in this project def seems to lead to this bug.  I tried SBT 0.12.1 to 0.12.3

**Comment by MansurAshraf** [comment]
I am running into the same issue with sbt 0.12.4

**Comment by mtomko** [comment]
We're seeing this, too. The project that declares withSources is using 0.13.0. It builds fine, but a downstream project, which uses Play (2.1.2), can't find the source jar and fails.

**Comment by harrah** [comment]
Note that `withSources` is generally not recommended in 0.10+.  The IDE plugins use `updateClassifiers`, for example, and this can be used by other tasks/plugins that do similar things.  (This bug will still be fixed if possible.)

**Comment by mtomko** [comment]
Thanks. It probably makes sense for our build to not directly call withSources then.

**Comment by harrah** [comment]
This fix is on the generation side.  The pom.xml was generated with an incorrect `<type>` element.  This fixes `makePom` to not do that.  As noted above, however, builds should generally not use `withSources` or `withJavadoc`.
