### ISSUE TITLE
`java.lang.NoClassDefFoundError: scala/runtime/LazyVals$NullValue$` on new 3.3.0 projects with typelevel cats 2.9.0

### ISSUE THREAD

**Issue by dhinojosa** [sbt/sbt#7283]
## steps

Clone the simple project to demonstrate the bug from https://github.com/dhinojosa/mystery-bug. In SBT run, `sbt` and once in the shell, run `run`. The example is just demonstrating the `Show[T]` typeclass.

## problem

Running the application results in the following trace:
```
[info] running (fork) com.xyzcorp.showexample.somethingWrong
[error] Exception in thread "main" java.lang.NoClassDefFoundError: scala/runtime/LazyVals$NullValue$
[error] 	at com.xyzcorp.showexample.Employee$.showLastThenFirstAndMaskedSalary(Runner.scala:37)
[error] 	at com.xyzcorp.showexample.Runner$package$.somethingWrong(Runner.scala:14)
[error] 	at com.xyzcorp.showexample.somethingWrong.main(Runner.scala:6)
[error] Caused by: java.lang.ClassNotFoundException: scala.runtime.LazyVals$NullValue$
[error] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[error] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[error] 	... 3 more
```

## expectation

It should run: 
```
DeNiro, Robert : $XX,XXX.XX
Downey Jr, Robert : $XX,XXX.XX
DeNiro, Robert : $30,000.00
Downey Jr, Robert : $17,000.00
```

## notes
* If you remove `fork := true`, it will work.
* If you downgrade scala from version `3.3.0` it will work regardless if `fork` is enabled or not
* It works in Scastie: https://scastie.scala-lang.org/OBWoT9yrSQyARtbpo7ERjQ
* `show Compile/fullClasspath` has `scala3-library_3-3.2.1.jar` rather than the 3.3.0 JAR one would expect
* The class in question, `scala/runtime/LazyVals$NullValue$`, is missing from Scala 3.2.1
* @SethTisue helped me and recommended that I file this issue on SBT's repository
* Works fine with `scala-cli run --dep org.typelevel::cats-core:2.9.0 .`

**Comment by SethTisue** [comment]
@eed3si9n seems alarming to me that the class path would have the wrong standard library version

**Comment by eed3si9n** [comment]
@dhinojosa @SethTisue Thanks for the report!

I think this is actually working as intended because sbt by default appends `scala3-library_3-3.3.0.jar` to the same setting key the build user has access to, which is `libraryDependencies`, and you've used `:=` to overwrite it. If you switch to using

```scala
libraryDependencies += "org.typelevel" %% "cats-core" % "2.9.0"
```

then it should work as you expected.

**Comment by SethTisue** [comment]
ha, nice, I did not spot that!

**Comment by dhinojosa** [comment]
Neither did I. Thank you
