### ISSUE TITLE
Publish with SBT 1.9.0 always requires publishTo defined even with skip/publish set to true

### ISSUE THREAD

**Issue by KarelCemus** [sbt/sbt#7288]
## steps

- this bug first appeared with SBT 1.9.0, worked fine in older versions
- to reproduce the bug run `publish` on the following project

```
val root = (project in file(".")).aggregate(api,service)
lazy val api = project.settings(publishTo := Some(Resolver.mavenLocal))
lazy val service = project.settings(skip/publish := true)
```

## problem

I am getting

```
[error] stack trace is suppressed; run last service / publishConfiguration for the full output
[error] stack trace is suppressed; run last publishConfiguration for the full output
[error] (service / publishConfiguration) Repository for publishing is not specified.
[error] (publishConfiguration) Repository for publishing is not specified.
[error] Total time: 0 s, completed Jun 5, 2023, 11:01:56 PM
```

SBT forces me to set `publishTo` to `Some` even for modules which are never supposed to be published

## expectation

`publishTo` set to `None` (which is a default value) should be fine in modules with `skip/publish := true`

**Comment by eed3si9n** [comment]
@KarelCemus Sounds like a regression. Thanks for the report! /cc @adpi2

**Comment by adpi2** [comment]
This bug has likely been introduced by https://github.com/sbt/sbt/pull/7165

**Comment by domdorn** [comment]
just stumbled upon this issue as well.. could you please release a 1.9.1?

**Comment by domdorn** [comment]
additionally, it now wants to have a `versionScheme` set:

```
[warn] versionScheme setting is empty; set `ThisBuild / versionScheme := Some("early-semver")`, `Some("semver-spec")` or `Some("pvp")`
[warn] so tooling can use it for eviction errors etc - https://www.scala-sbt.org/1.x/docs/Publishing.html
```


this seems to work for me as a workaround:
```
  publish / skip         := true,
  versionScheme          := Some("early-semver"),
  publishTo              := None,
  publishConfiguration := PublishConfiguration(),
  ```

**Comment by thesamet** [comment]
I noticed that in SBT 1.9.0, projects with `publish / skip := true` get compiled when running `publishLocal`. Would the fix above take care of that too?

**Comment by adpi2** [comment]
> I noticed that in SBT 1.9.0, projects with publish / skip := true get compiled when running publishLocal. Would the fix above take care of that too?

Yes, it fixes that too.
