### ISSUE TITLE
[1.9.x] Missing range in BSP diagnostic

### ISSUE THREAD

**Issue by adpi2** [sbt/sbt#7297]
Since sbt 1.9.0

## steps

1. In an sbt project
```scala
package example 

class A {
  def foo: String = ""
}

class AA extends A {
  val foo: String = ""
}
```

2. Import the project in Metals using sbt as the build server

## problem

The missing `override` error is reported at the very top of the file (range 0, 0).

```scala
package example
// ^^^^
// overriding method foo in class A of type => String;
//   value foo needs `override' modifier
```

## expectation

The error should be reported on `def foo`:

```scala
class AA extends A {
  def foo: String = ""
// ^^^^^^^^^^^^^^^^^
// overriding method foo in class A of type => String;
//  method foo needs `override' modifiersbt
}
```

## notes

The bug was introduced in sbt 1.9.0, it works as expected in sbt 1.8.2

**Comment by iusildra** [comment]
This bug may also occurs when other kinds of error are present
* when function's input types cannot be inferred e.g. `elem.flatMap(a.b(_))`
* or when using `\000` (octal escape literals) instead of `\u0000` somewhere in the code
