### ISSUE TITLE
`java.lang.StackOverflowError` with `sbt dependencyBrowseTree`

### ISSUE THREAD

**Issue by Renkai** [sbt/sbt#7311]
## steps

Execute `sbt dependencyBrowseTree` on some project.

## problem
```
[info] Resolved  dependencies
[error] java.lang.StackOverflowError
[error] 	at java.base/java.util.TimSort.sort(TimSort.java:220)
[error] 	at java.base/java.util.Arrays.sort(Arrays.java:1441)
[error] 	at scala.collection.SeqLike.sorted(SeqLike.scala:659)
[error] 	at scala.collection.SeqLike.sorted$(SeqLike.scala:647)
[error] 	at scala.collection.AbstractSeq.sorted(Seq.scala:45)
[error] 	at scala.collection.SeqLike.sortBy(SeqLike.scala:634)
[error] 	at scala.collection.SeqLike.sortBy$(SeqLike.scala:634)
[error] 	at scala.collection.AbstractSeq.sortBy(Seq.scala:45)
[error] 	at net.virtualvoid.sbt.graph.ModuleGraph.$anonfun$createMap$2(model.scala:65)
[error] 	at scala.collection.MapLike$MappedValues.get(MapLike.scala:261)
[error] 	at scala.collection.Map$WithDefault.get(Map.scala:57)
[error] 	at scala.collection.MapLike.getOrElse(MapLike.scala:129)
[error] 	at scala.collection.MapLike.getOrElse$(MapLike.scala:129)
[error] 	at scala.collection.AbstractMap.getOrElse(Map.scala:65)
[error] 	at net.virtualvoid.sbt.graph.rendering.TreeView$.processSubtree(TreeView.scala:30)
[error] 	at net.virtualvoid.sbt.graph.rendering.TreeView$.$anonfun$processSubtree$2(TreeView.scala:31)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
//many similar lines
.......
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at net.virtualvoid.sbt.graph.rendering.TreeView$.processSubtree(TreeView.scala:31)
[error] 	at net.virtualvoid.sbt.graph.rendering.TreeView$.$anonfun$processSubtree$2(TreeView.scala:31)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
[error] 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[error] 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[error] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at net.virtualvoid.sbt.graph.rendering.TreeView$.processSubtree(TreeView.scala:31)
[error] 	at net.virtualvoid.sbt.graph.rendering.TreeView$.$anonfun$processSubtree$2(TreeView.scala:31)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
[error] 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[error] 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[error] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at net.virtualvoid.sbt.graph.rendering.TreeView$.processSubtree(TreeView.scala:31)
[error] 	at net.virtualvoid.sbt.graph.rendering.TreeView$.$anonfun$processSubtree$2(TreeView.scala:31)
[error] (Compile / dependencyBrowseTreeHtml) java.lang.StackOverflowError
```

## expectation
Show a tree in the preferred browser.

## notes
This happens in version 1.9.0, and also many earlier versions.

**Comment by eed3si9n** [comment]
Thanks for the report. Could you provide reproduction steps so we can reproduce your problem on _our computers_?

**Comment by Renkai** [comment]
I'm sorry, but it's from a private project, and I don't know how to properly reduce it to a public version. I will post an example as soon as I can make one.

**Comment by Renkai** [comment]
I solved this by removing the plugin `"net.virtual-void"  % "sbt-dependency-graph" % "0.10.0-RC1" `, and then adding`"org.scala-sbt"     % "sbt-dependency-tree" % "1.9.0" `. 
Without the plugin `sbt-dependency-tree` sbt has the command `dependencyTree` but not `dependencyBrowseTree`.

I find out the plugin axes by browsing the local ivy cache after executing `sbt publishLocal` of the sbt project. The [archived repository](https://github.com/sbt/sbt-dependency-graph) hasn't mentioned we should use the new axes instead. Is there a better place to introduce the migrated plugin to users?

**Comment by eed3si9n** [comment]
I am not sure if this one is listed but https://github.com/scala-steward-org/scala-steward/blob/main/modules/core/src/main/resources/artifact-migrations.v2.conf has some of these migrations listed.

**Comment by Renkai** [comment]
Thanks for digging out the history! But if A new sbt user wants to learn about the sbt dependency plugin, where is the best starting point for them?

**Comment by eed3si9n** [comment]
> But if A new sbt user wants to learn about the sbt dependency plugin, where is the best starting point for them?

I am not sure. I am only maintaining sbt on my own in my free time, and I can't always get around to all the details. To some extent the idea of the plugin to create a stable core and optional things are enabled optionally. From sbt 1.4.x [sbt-dependency-graph got in-sourced](https://www.scala-sbt.org/1.x/docs/sbt-1.4-Release-Notes.html#sbt-dependency-graph+is+in-sourced) to sbt, and `dependencyTree` task is available without plugin, but the other tasks are considered advanced tasks that can be enabled optionally. You're welcome to contribute any docs in sbt/website.
