### ISSUE TITLE
`; reload; compile` makes sbt 0.12.0/0.12.3 exit if compilation fails

### ISSUE THREAD

**Issue by Blaisorblade** [sbt/sbt#732]
When `compile` fails and is part of the composite command `; reload; compile`, SBT exits with error code 1, while it should present me a new prompt; in comparison, `; compile` does not make SBT exit.

To reproduce:
- introduce a compile error in an SBT-built software. A `build.sbt` containing just `scalaVersion := "2.10.0"` is enough.
- if you invoke `compile`, sbt will report a compile error and bring back to the SBT prompt.
- if you invoke `; reload; compile`, sbt will report the same compile error and exit SBT, whether `build.sbt` changed or not. It doesn't matter whether you run `compile` before.

The error seems robust with all variations of the instructions I could try. In particular, I can take a software which compiles, change `build.sbt` so that it stops compiling (by changing Scala compiler version, in my case), and type `; reload; compile`: I'll get the compilation error and SBT will exit automatically.

**Comment by harrah** [comment]
Thanks for the report.  The first command did have to be `reload`, but it could be any failing command afterwards.  This should be fixed for 0.13.0.
