### ISSUE TITLE
[Fatal Error] :1:3: The markup in the document preceding the root element must be well-formed. in scala compile

### ISSUE THREAD

**Issue by LizzyMiao** [sbt/sbt#7324]
I have a scala project which used to work just fine, but suddenly out of work yesterday... 
I have tried with invalidate Intellij cache, delete the project and reclone again, restart my laptop, reinstall the sbt plugin, none of them worked...
Weird thing is my other scala sbt project worked just fine...

I use Intellij: IntelliJ IDEA 2021.3.2 (Community Edition) Build #IC-213.6777.52
my local sbt is 1.3.2
In my project the build.properties is：`sbt.version=1.5.0`
scala version is `2.12.15`
java version is Zulu version 11.0.13
scala plugin for Intellij: 2021.3.22

It seems generating sbt-structure.xml failed... Not sure about the exact error...

/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -Xms8G -Xmx8G -Xss20M -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=500M -XX:+TieredCompilation -Dhttp.nonProxyHosts=127.0.0.1|localhost -Xmx8192M -Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled -Didea.managed=true -Dfile.encoding=UTF-8 -Didea.installation.dir=/Users/username/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/213.6777.52/IntelliJ IDEA CE.app/Contents -jar /Users/username/.sbt/sbt/bin/sbt-launch.jar
[info] welcome to sbt 1.5.0 (Azul Systems, Inc. Java 11.0.13)
[info] loading settings for project global-plugins from credentials.sbt,plugins.sbt ...
[info] loading global plugins from /Users/username/.sbt/1.0/plugins
[info] loading settings for project index-builder-build from plugins.sbt ...
[info] loading project definition from /Users/username/IdeaProjects/index-builder/project
[info] loading settings for project root from build.sbt,release.sbt ...
[info] resolving key references (10450 settings) ...
[info] set current project to index-builder (in build file:/Users/username/IdeaProjects/index-builder/)
[info] sbt server started at local:///Users/username/.sbt/1.0/server/abaf94f632f9aa72be1a/sock
[info] started sbt server
sbt:index-builder>
;set _root_.scala.collection.Seq(historyPath := None,shellPrompt := { _ => "" },SettingKey[_root_.scala.Option[_root_.sbt.File]]
("sbtStructureOutputFile")
in _root_.sbt.Global := _root_.scala.Some(_root_.sbt.file("/private/var/folders/v9/vbxmj8w54bn_9s_258z0z34c0000gq/T/sbt-structure.xml")),SettingKey[_root_.java.lang.String]("sbtStructureOptions")
in _root_.sbt.Global := "download, resolveClassifiers")
[info] Defining Global / sbtStructureOptions, Global / sbtStructureOutputFile and 1 others.
[info] The new values will be used by cleanKeepGlobs
[info] 	Run `last` for details.
[info] Reapplying settings...
[info] set current project to index-builder (in build file:/Users/username/IdeaProjects/index-builder/)
[info] Applying State transformations org.jetbrains.sbt.CreateTasks from /Users/username/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/213.6777.52/IntelliJ IDEA CE.app.plugins/Scala/repo/org/jetbrains/scala/sbt-structure-extractor_2.12_1.0/2021.3.0/sbt-structure-extractor-2021.3.0.jar
[info] Reapplying settings...
[info] set current project to index-builder (in build file:/Users/username/IdeaProjects/index-builder/)
[warn] sbt 0.13 shell syntax is deprecated; use slash syntax instead: Global / dumpStructure
[Fatal Error] :1:3: The markup in the document preceding the root element must be well-formed.
[Fatal Error] :1:3: The markup in the document preceding the root element must be well-formed.
[error] stack trace is suppressed; run 'last standaloneIndexer / update' for the full output
[error] stack trace is suppressed; run 'last bulkIndexer / update' for the full output
[error] stack trace is suppressed; run 'last standaloneIndexer / ssExtractDependencies' for the full output
[error] stack trace is suppressed; run 'last docs / ssExtractDependencies' for the full output
[error] stack trace is suppressed; run 'last bulkIndexer / ssExtractDependencies' for the full output
[error] stack trace is suppressed; run 'last standaloneIntegrationTest / ssExtractDependencies' for the full output
[error] (standaloneIndexer / update) org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 3; The markup in the document preceding the root element must be well-formed.
[error] (bulkIndexer / update) org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 3; The markup in the document preceding the root element must be well-formed.
[error] (standaloneIndexer / ssExtractDependencies) org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 3; The markup in the document preceding the root element must be well-formed.
[error] (docs / ssExtractDependencies) org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 3; The markup in the document preceding the root element must be well-formed.
[error] (bulkIndexer / ssExtractDependencies) org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 3; The markup in the document preceding the root element must be well-formed.
[error] (standaloneIntegrationTest / ssExtractDependencies) org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 3; The markup in the document preceding the root element must be well-formed.
[error] Total time: 2 s, completed Jul 6, 2023, 12:24:30 PM
[info] shutting down sbt server

**Comment by adpi2** [comment]
```
[error] (standaloneIndexer / update) org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 3; The markup in the document preceding the root element must be well-formed.
```

This error indicates that sbt failed at parsing an ill-formed XML or POM file while resolving the dependencies. Unfortunately it does not indicate which file. You can try to use a clean Coursier cache to see if it re-downloads correct dependencies. Or you can try to bisect your dependencies to identify which one fails.

**Comment by LizzyMiao** [comment]
I sort the file by timestamp and find one corrupted xml file...by removing this folder the issue was gone!!! thank you so much!!!
