### ISSUE TITLE
cross-build no longer works when `CrossVersion.full` projects depend on `CrossVersion.binary` ones

### ISSUE THREAD

**Issue by kitbellew** [sbt/sbt#7327]
## steps

Check out scalameta/scalameta#3212 and build locally.

## problem

In sbt 1.6.2, having a `CrossVersion.full` project with several `crossScalaVersions` (say, 2.13.1 to 2.13.11) depend on a `CrossVersion.binary` project with only 2.13.11 used to work, and in more recent versions (possibly after #6946) the build fails.

Local build for me failed with `Modules were resolved with conflicting cross-version suffixes`, while CI build failed with `Error downloading org.scalameta:scalameta_2.12:4.8.2+9-291843d8-SNAPSHOT` (by trying to download the dependency project rather than building it locally).

## expectation

- If cross-build dependencies between `full` and `binary` projects are not allowed
  - the error message should stipulate that explicitly
  - https://www.scala-sbt.org/1.x/docs/Cross-Build.html should mention this as well, possibly with suggestions on how to deal with this issue
- if such a dependency is to be allowed again
  - either #6946 should be reverted
  - or `project.dependsOn` could be augmented with some new parameters to specify explicit fallback versions of dependency
  - also, ideally, when multiple `full` projects depend on a single `binary` project, the `binary` project wouldn't be built multiple times

## notes

Also see comment https://github.com/sbt/sbt/pull/6946#issuecomment-1627716934.

**Comment by eed3si9n** [comment]
I think `++ <sv>` behavior works as expected. It switches the subprojects that lists argument in `crossScalaVersions`. 
You can: 
1. use `!` to force the same Scala version across the subprojects - https://github.com/scalameta/scalameta/pull/3243
2. use `++` twice: `"++ 2.13.11" "++ 2.13.1"`, which should switch the core to latest, and semanticdb to 2.13.1.
3. use sbt-projectmatrix

**Comment by kitbellew** [comment]
> I think `++ <sv>` behavior works as expected. It switches the subprojects that lists argument in `crossScalaVersions`. You can:
> 
> 1. use `!` to force the same Scala version across the subprojects - [sbt: Update sbt to 1.9.1 scalameta/scalameta#3243](https://github.com/scalameta/scalameta/pull/3243)

Thank you for this suggestion!

> 2. use `++` twice: `"++ 2.13.11" "++ 2.13.1"`, which should switch the core to latest, and semanticdb to 2.13.1.

Not sure I understand how this works :)

> 3. use sbt-projectmatrix

I have been reading this project's documentation, and examples of usage, over the past few days. Still don't understand how to:
- set up semanticdb-2.13.1 to depend on core-2.13.11
- make sure semanticdb-2.13.1 and 2.13.2 can be built in parallel (since they seem to write to the same target)
- build one specific version (that is, we use CI to test each scala version separately)

**Comment by eed3si9n** [comment]
> > 2. use `++` twice: `"++ 2.13.11" "++ 2.13.1"`, which should switch the core to latest, and semanticdb to 2.13.1.
> 
> Not sure I understand how this works :)

sbt 1.9.1 only switches the `scalaVersion` of the subprojects whose `crossScalaVersion` matches exactly the passed in argument.

First `++ 2.13.11` will switch the Scala Version of both core and semanticdb subprojects.
Second `++ 2.13.1` will switch _only_ the Scala version of semanticdb subproject.
All while, the dependency relationship will be maintained. The end result should be what you want: core using 2.13.11, but semanticdb using 2.13.1.

**Comment by kitbellew** [comment]
> I think `++ <sv>` behavior works as expected. It switches the subprojects that lists argument in `crossScalaVersions`. You can:
> 
> 1. use `!` to force the same Scala version across the subprojects - [sbt: Update sbt to 1.9.1 scalameta/scalameta#3243](https://github.com/scalameta/scalameta/pull/3243)
> 2. use `++` twice: `"++ 2.13.11" "++ 2.13.1"`, which should switch the core to latest, and semanticdb to 2.13.1.

Turns out any `+command` (such as `sbt +publish`) doesn't work, since it doesn't apply either of these. Would you say that cross-build is not operational, then?

**Comment by eed3si9n** [comment]
> Would you say that cross-build is not operational, then?

Yeah. If we prioritize exact match, but let it fall back to bincompat Scala version like sbt 1.6.x we can still rescue this feature.

**Comment by eed3si9n** [comment]
Here's a PR for this - https://github.com/sbt/sbt/pull/7328
