### ISSUE TITLE
Provide a way in TestReportListener to get the test duration

### ISSUE THREAD

**Issue by copumpkin** [sbt/sbt#734]
I can't seem to find any way to find out how long an individual test took to run when my testEvent callback gets called. If we got an event for when a test is started and when one is ended, I could compute the duration by hand, but it seems like regardless of separating start/stop events for tests, sbt could include a duration in the test result event, whether the test failed or succeeded. Am I just missing something or is there no way to get this information right now?

**Comment by harrah** [comment]
@cheeseng Do you have an opinion on this?  Should the test execution time be added to TestEvent somehow?

**Comment by cheeseng** [comment]
Hi Mark,

Er, perhaps add to SuiteResult instead?  if it needs to be stored up and
used later?

Cheers,
Chee Seng

**Comment by harrah** [comment]
The request is for the information to be consumed by a TestReportListener.  I'm not sure whether fine-grained information is required (at the level of test methods) or if suite-level is ok, so I don't know whether SuiteResult is ok.

**Comment by copumpkin** [comment]
Ideally it'd be per-test, since TeamCity supports displaying statistics about test speeds and it can be helpful. It wouldn't be a precise benchmark, but over a bunch of runs it might reveal patterns about slowdowns and such.

**Comment by cheeseng** [comment]
Hi Mark,

I think in the case of TestReportListener TestEvent makes more sense, since
it is discarded after the 'suite' is completed, while SuiteResult is saved
in the memory until the run is completed.

Cheers,
Chee Seng

**Comment by harrah** [comment]
The memory consumption from adding a long to SuiteResult is probably negligible if that is what you are concerned about.

**Comment by cheeseng** [comment]
Hi Mark,

> > The memory consumption from adding a long to SuiteResult is probably
> > negligible if that is what you are concerned about.

Agree that it is probably negligible, since it is just long and not string.

Perhaps the deciding factor is level of fine-grained it should be, if it is
'test' level then it has to be TestEvent, right?

Cheers,
Chee Seng

**Comment by harrah** [comment]
Yes, although it wouldn't hurt to sum the total time since that is probably a common requirement.

**Comment by cheeseng** [comment]
Yes, probably no harm adding that, though imho it is easy for
TestReporterListener implementation to just perform the sum itself when
needed.

**Comment by copumpkin** [comment]
I see there appears to be support for this in the new test-interface (and scalatest's framework seems to report something). Unfortunately, I'm getting questionable results from it so I'm not sure if it isn't ready yet or if I'm doing something wrong. If it's expected to work at this point, I'll take some time to make a reduction of the timing issues I'm seeing.

**Comment by harrah** [comment]
The test framework is reponsible for reporting it.  What ScalaTest version are you using?

**Comment by harrah** [comment]
(Also, I'm closing this because it is supposed to be implemented in test-interface 1.0 + sbt 0.13.0.  We can continue to discuss here and reopen if necessary.)

**Comment by copumpkin** [comment]
Oh nevermind, I just saw that it's actually reporting a duration of -1 every time. I can't tell which framework I'm even using. It's either scalatest or the junit runner, but I can't find them in the dependencies being fetched, and don't really understand how this is loaded (is it reflective?)

**Comment by copumpkin** [comment]
Aha! https://github.com/sbt/sbt/blob/8c7a1a4f8a5451dc96e6096794a83d854e3b25ea/testing/agent/src/main/java/sbt/FrameworkWrapper.java#L148

**Comment by copumpkin** [comment]
Okay, so it all happens because of this line:

``` scala
case oldFramework: OldFramework => new FrameworkWrapper(oldFramework)
```

in https://github.com/sbt/sbt/blob/8c7a1a4f8a5451dc96e6096794a83d854e3b25ea/testing/src/main/scala/sbt/TestFramework.scala#L37. Which just means I need to update my runner (probably the JUnit one, since the scalatest one seems to implement it) to implement the new interface.

**Comment by harrah** [comment]
Note that only a recent, snapshot version of ScalaTest implements the test-interface.  I believe junit-interface is being updated, but you probably have to build that from source to get this feature.
