### ISSUE TITLE
Sbt fails to detect change of structure when type aliases dealias to the same type

### ISSUE THREAD

**Issue by gkossakowski** [sbt/sbt#736]
Consider the following code:

``` scala
// Foo.scala
object Foo {
  type S1 = String
  type S2 = String
  def foo: S1 = null
}

// Bar.scala
class Bar {
  // inferred return type is Foo.S1; this type is pickled in the bytecode of Bar
  def bar = Foo.foo
}
```

Now if you change return type of `Foo.foo` to `Foo.S2` sbt won't detect this as a change to the structure of `Foo` and won't recompile `Bar`. Therefore incorrect (stale) type will be stored in pickled information for `Bar`. This violates the invariant that incremental compilation always leads to the same end result (in terms of bytecode in this case) as full, clean compile.

The reason is that sbt eagerly normalizes (which involves dealiasing) types when it indexes structure of compilation units, see:
https://github.com/sbt/sbt/blob/bef8ce05b900e393f2437bf0a18a7e0c1a622343/compile/interface/src/main/scala/xsbt/API.scala#L317

Note: the method is wrongly called `dealias` since it performs normalization.

**Comment by jsuereth** [comment]
Greg -

Quick question,  how often is this an actual issue in practice?  I'm running through scenarios in my head, to better understand the "no longer normalize" change.   I can understand the pickled information would be wrong, but it seems the runtime behavior should be fine.

In any case, a little help understanding the issue would be nice.  Thanks!

**Comment by harrah** [comment]
Ok, you're right that it would be useful to have a test case that fails at runtime instead of just a check that recompilation happened.  That is how similar existing test cases work.

**Comment by harrah** [comment]
Well, not necessarily runtime- it could be a compile time failure, but one that is an actual problem.

**Comment by gkossakowski** [comment]
I accidentally reopened this issue but clicking the wrong button on issue list. I'm very sorry for that. Closing again.
