### ISSUE TITLE
Plugin: DependencyGraph: Valid DOT syntax fails to parse in common DOT parser

### ISSUE THREAD

**Issue by philipwhiuk** [sbt/sbt#7363]
Hi folks,

This is sort of a hail-mary approach to fixing an issue I'm having.

https://github.com/sbt/sbt/blob/bc00cee4df8bda48908699efa852c8c4aa13fb8e/main/src/main/scala/sbt/plugins/DependencyTreeSettings.scala#L119

produces 

`graph[rankdir="LR"; splines=polyline]`

Unfortunately, a common, but archived, dotGraph parser only accepts `,`:

https://github.com/paypal/digraph-parser/blob/3a947dd99e521c23da657bd56cb85f46bca56fa6/src/main/java/com/paypal/digraph/parser/antlr/DOT.g4#L44

Note, per: https://graphviz.org/doc/info/lang.html both are acceptable here (`a_list`)

Is it possible to change SBT to use `,` to maintain compatibility with this parser? Would this be an accepted PR?

**Comment by eed3si9n** [comment]
If that's the only occurrence, could you pipe it through sed or something to locally fix this issue?

**Comment by SethTisue** [comment]
I feel like we should just close this as “not planned".

**Comment by nycnewman** [comment]
This actually breaks Synopsys Blackduck SBT scanner as they depend on the paypal parser which does handle the extra attibute for splines. "Sed" solution does work as this is handle fully within their SCA product.

**Comment by philipwhiuk** [comment]
Yep @nycnewman that's my use case too. Maybe we have to push Synopsys to fix it by forking PayPal's parser..

**Comment by nycnewman** [comment]
I have a support ticket in with Synopsys referencing exactly this. Didn't ask why they aren't using a proper SCA tool to check for Operational Risks in their code base ....   troll ... ;-)

**Comment by losonczylaci** [comment]
hey @nycnewman, any update on that support ticket? in case it is public, could you share the link with us?

**Comment by nycnewman** [comment]
Synopsys have official registered issue and it is on backlog. No timeline for resolution. Their proposed workaround is to use earlier SBT version. The fix is a single line change in the parser configuration for the library. This was provided to Synopsys as part of the ticket.
