### ISSUE TITLE
Console broken (to varying degrees) for TERM=dumb

### ISSUE THREAD

**Issue by hvesalai** [sbt/sbt#7371]
I am using sbt through the emacs `sbt-mode` (of which I'm the maintainer), which reports it self as a TERM=dumb. 

I was using sbt version 1.6.2 and noticed that the console is echoing erroneously and came to write a bug report on that. While doing so, I decided to upgrade to latest sbt (1.9.4) so as not to report a bug against an old version. To do so, I created a new clean project and there 1.6.2 as well as 1.9.4 are even more broken, so much so that at the moment the console is unusable in term=DUMP in 1.9.4.

I will thus report both behaviors (partially broken 1.6.2 and completely broken 1.9.4) here.

The partial echo problem was also reproduced on 1.8.3 by @rossabaker (in the `Cats` project)

## steps

1. Create an empty new project folder and move  to it
2. run `env TERM=dumb sbt consoleQuick`
3. type: `"foo"`
4. you will see the following:

```
scala> "foo"
foo"
<console>:1: error: unclosed string literal
       foo"
```
5. type `vval x = 1` [sic!]

```
scala> vval x = 1
val x = 1
x: Int = 1
```

If at step 2. you run  `env TERM=dumb sbt` and then in sbt-shell type `consoleQuick` it works differently. In this case, there is full echo, but the first character of the input is not skipped. The scala version in the clean project is the default `2.12.15`

For 1.6.2 in my project (with scala version `2.13.8`), I get the following

1. run `env TERM=dumb sbt consoleQuick`
2. type `"foo"` and there is no echo
```
scala> "foo"
val res1: String = foo
```
3. type `"foo)bar"` and there is echo until `)`
```
scala> "foo)bar"
"foo)val res2: String = foo()
```

4. type `"foo)bar(}zot{"`
```
scala> "foo)bar(}zot{"
"foo)bar(}val res11: String = foo)bar(}zot{
```

In the latter case, the results do not depend on whether the console was started from the command line or from sbt shell.

## problem

When in the DUMB terminal mode, there should be no echo.  However...

1.9.4 in clean and empty project folder: there is full echo (the line right after the input was given) and the console is skipping the first character of the input.

1.6.2 in my project: there is no echo on most input, but if the input contains any closing parenthesis or brackets (`)}]`), the terminal echoes the part of the expression until the last closing bracket. Note that the closing parenthesis can be even inside a string

## expectation

There should be no echo in any case and the terminal should not skip the first character of input.

**Comment by SethTisue** [comment]
The problem goes away if I `++2.13.11! consoleQuick` or `++3.3.1! consoleQuick`. The Scala version defaults to 2.12 otherwise. This makes me suspect it's fundamentally a problem with JLine 2. (The newer Scala versions use JLine 3.)

**Comment by SethTisue** [comment]
The problem also goes away if I `env TERM=dumb sbt 'set scalacOptions += "-Xnojline"'  shell`, then once sbt has started, run `consoleQuick`. (But it doesn't go away if I cram that all into one command.)

To make things even more complicated, if I don't attempt to manipulate `scalacOptions`, but if I follow the two-step process of starting with `env TERM=dumb sbt` and then issuing `consoleQuick`, then I got the following third behavior:

```
scala> "foo"
"foo"
res1: String = foo
```

where it doesn't fail, but it's weird that the extra `"foo"` got printed

**Comment by hvesalai** [comment]
Ah, that's a good catch that the behavior might not be sbt-version dependent, but scala-version dependent.

in

```
scala> "foo"
"foo"
res1: String = foo
```

The middle line is called echo and is what I would not like to have, but if there is echo, it should be the full line, not partial as what I'm seeing now.

**Comment by SethTisue** [comment]
You originally observed the problem in the context of your emacs sbt-mode; do you recall if the project(s) you were working on when you saw it were 2.12 projects, or some newer version?

**Comment by hvesalai** [comment]
Indeed in my project (using sbt 1.6.2 and scala 2.13.8), if I do `set scalacOptions += "-Xjline:off"`, the problem goes away (there is no echo at all).

So the problem seems to be related to JLine.

With JLine disabled I have:

```
scala> "foo"
val res0: String = foo

scala> "foo()"
val res1: String = foo()
```

Which is perfect. However, it should be noted that disabling JLine is the worst fix as code completions are implemented by JLine.

**Comment by eed3si9n** [comment]
Given that none (or small %?) of the sbt contributors are using this mode regularly, it's somewhat bound to regress without extensive testing, so I'd suggest that we stop expecting TERM=dumb to be functional. Not that I am promising future support, investing energy into sbtn (sbt shell against sbt server) might be more a more useful exercise, although you might run into similar issues there as well.

**Comment by hvesalai** [comment]
sbt has supported emacs from the very beginning not least because of my contributions along the years to both sbt and Jline. 

Killing support for TERM=dump in the context of emacs would mean death to the `sbt-mode` for emacs, so I hope that decision is not made lightly.

**Comment by eed3si9n** [comment]
The _sbt part_ of sbt (not Zinc) is mostly maintained by some engineering time by Scala Center and some community effort (like me). Both from the my own personal perspective (I don't use emacs), and from objective chess game of "allocating resources for the good of Scala" point-of-view, any engineering time we have should be towards making VS Code and IntelliJ the best it can be, unless the sub-community is willing to put in work time or free time.

For instance, a few NeoVim/Helix users were dissatisfied with the tree-sitter support of Scala syntax, especially Scala 3, so they/we rolled up our sleeves and started contributing parser code to tree-sitter-scala. It's still not perfect, but it has improved significantly, and I believe this has side benefits potentially for modern emacs or VS Code web mode.

**Comment by hvesalai** [comment]
That's all right. The emacs support for scala and sbt has been maintained by my self since 2017 and I've made several PRs to `sbt` to fix stuff and also add features such as querying command completions, etc.

I'm not asking anybody else to fix the current issue either, but I wanted to open the issue so others can help me by pointing me to the correct direction to fix this. So please don't 

- remove support for dumb terminal; or
- close this issue before the described issue has been resolved

**Comment by hvesalai** [comment]
To continue with the debugging: the same problem appears also in sbt-shell, so it is actually not limited to console.

**Comment by hvesalai** [comment]
I don't actually think this is traditional terminal input echo (which would be per character or per line) at all. It looks to be more like some code that detects blocks of code and then echoes them.

If you enter a multi-line code block (example below), it will not echo each line separately, but all of them in the end. Furthermore, the lines have been formatted differently than the original input, which a terminal would never do.

@eed3si9n @SethTisue  would you have any idea what in the code could be producing this:

```
scala> {
"foo"
}
{
     | "foo"
     | }val res2: String = foo
```

Notice the indentation and the vertical bar `|` at the beginning of the "echo" of the two last lines.

**Comment by hvesalai** [comment]
The culpit might be JLine3 parenthesis matching.

**Comment by hvesalai** [comment]
https://github.com/jline/jline3/issues/864

**Comment by hvesalai** [comment]
The issue was in JLine3 and a fix has been merged to their master.

Let's keep this issue open until there is a new release and we have included that in sbt.

**Comment by hvesalai** [comment]
@eed3si9n do you know if the JLine used by `console` is from scala or sbt?

**Comment by eed3si9n** [comment]
My guess is that it's sbt.

**Comment by hvesalai** [comment]
@eed3si9n a new version of JLine3 has been released with my fix in it. I would now like to make a PR to sbt, but I don't fully understand the JLine2 fork thing (with respect to updating JAnsi). Can you shed some light on why it exists? Why (and where) is JLine2 used?

**Comment by hvesalai** [comment]
@eed3si9n also the tag for the current release of sbt/jline2 (2.14.7) is missing from the repo.

**Comment by hvesalai** [comment]
I propose a permanent and a temporary solution. The temporary solution is super simple, just disables the offending keymapping when inside emacs. The permanent solution is to upgrade JLine3 to 3.24.0, but that requires also updating JAnsi to 2.4.0, which then requires updating the JLine2 fork for sbt.

**Comment by eed3si9n** [comment]
Here's our fork of JLine2 - https://github.com/sbt/jline2

> Can you shed some light on why it exists? Why (and where) is JLine2 used?

If I recall correctly, you can only have one version of JAnsi because it's using something native library stuff on Windows etc, and we also wanted to keep JLine2 around because certain functions expose it as a form of readLine (vaguely recall called by plugin to enter password for pgp etc).
