### ISSUE TITLE
`error: not found: object xsbti` when compiling 2.13.12 bridge

### ISSUE THREAD

**Issue by mariussoutier** [sbt/sbt#7382]
sbt 1.9.5 generates Zinc compiler errors when running ScalablyTyped. Version 1.9.6 also seems to exhibit the same problem:

```
info] ZincCompiler.scala:234 msg.get() Non-compiled module 'scala2-sbt-bridge' for Scala 2.13.12. Compiling... [project => <project-name>, ms => 25084]
/var/folders/0c/mqgg_cgs2fddcd981gkpvbfc0000gn/T/sbt_8c978be6/scala/tools/xsbt/API.scala:20: error: not found: object xsbti
import xsbti.api._
       ^
/var/folders/0c/mqgg_cgs2fddcd981gkpvbfc0000gn/T/sbt_8c978be6/scala/tools/xsbt/API.scala:21: error: not found: object xsbti
import xsbti.VirtualFile
```

sbt 1.9.4 works fine.

**Comment by eed3si9n** [comment]
Thanks for the report. Could you provide reproduction steps so we can reproduce your problem on _our computers_ or on GitHub Actions?

**Comment by mariussoutier** [comment]
I was hoping the error messages would be the same you referred to in the 1.9.6 release notes.

I have a project using Scala 2.13.12, Scala.JS, Vite, and ScalablyTyped.
`package.json` should have JS dependencies that are transformed by ScalablyTyped, which then fails with the above message.

If you don't have something similar lying around, I can try to set up a minimal project over the next few days.

**Comment by SethTisue** [comment]
> Non-compiled module 'scala2-sbt-bridge' for Scala 2.13.12. Compiling...

Is it actually compiling the bridge? Seems like it ought to be using a retrieved binary bridge

**Comment by SethTisue** [comment]
>  I can try to set up a minimal project over the next few days.

yes please, that's what we need in order to diagnose this

**Comment by lrytz** [comment]
It doesn't need to be a minimal project necessarily, is your project open source?

It seems very likely that this needs to be addressed in the ScalablyTyped sbt plugin. @eed3si9n maybe it's easy for you to spot? https://github.com/ScalablyTyped/Converter/blob/f593f499941944e5a373e3c7c42c88ca95b60875/sbt-converter/src/main/scala/org/scalablytyped/converter/internal/ZincCompiler.scala#L128-L151

cc @oyvindberg; the corresponding change in sbt: https://github.com/sbt/sbt/pull/7374/files. For Scala 2.12.13 and newer we publish compiler bridge as a binary jar with every Scala release.

**Comment by oyvindberg** [comment]
Thanks for the ping. Tracked in https://github.com/ScalablyTyped/Converter/issues/565

**Comment by eed3si9n** [comment]
Seems like a fairly straightforward plugin issue, so I'll close this out. Thanks for the pointers @lrytz

**Comment by mariussoutier** [comment]
Thanks guys!
