### ISSUE TITLE
`.sbtopts` memory options not working on Windows

### ISSUE THREAD

**Issue by ptrdom** [sbt/sbt#7387]
## steps
Tested on Windows 11 and sbt `1.9.6` by:
- Running sbt from terminal on a project.
- Running IntelliJ project with BSP support using sbt as build server.

Run sbt with following `.sbtopts` file present in working directory:
```
-J-XX:MaxMetaspaceSize=4G
-J-XX:MaxInlineLevel=20
-J-Xss2m
-J-Xms512M
-J-Xmx6G
-J-XX:ReservedCodeCacheSize=256M
```
These options were taken from https://github.com/disneystreaming/smithy4s/blob/series/0.18/.sbtopts.

## problem

Memory options do not get assigned to the spawned sbt process. Default options get assigned instead.

## expectation

Memory options should get assigned to the spawned sbt process.

## notes

I think the issue is looping of `_SBT_OPTS` done in this function - https://github.com/sbt/sbt/blob/1.10.x/launcher-package/src/universal/bin/sbt.bat#L825-L855. The for loop of `_SBT_OPTS` set to `-XX:MaxMetaspaceSize=4G -XX:MaxInlineLevel=20 -Xss2m -Xms512M -Xmx6G -XX:ReservedCodeCacheSize=256M` only enters loop with `-XX:MaxMetaspaceSize=4G` and then exits. Placing a memory argument as a first argument in `.sbtopts` instead can be used as a workaround.

**Comment by ptrdom** [comment]
Changing loop in https://github.com/sbt/sbt/blob/1.10.x/launcher-package/src/universal/bin/sbt.bat#L845 from `if defined _SBT_OPTS for /F %%g in ("!_SBT_OPTS!") do` to `if defined _SBT_OPTS for %%g in (%_SBT_OPTS%) do` seems to fix this bug.

**Comment by eed3si9n** [comment]
Thanks for the report. Would you like to send a PR for this?

**Comment by ptrdom** [comment]
Sure, will do.
