### ISSUE TITLE
Conflicting cross-version suffixes detected between Java & Scala libraries with same name

### ISSUE THREAD

**Issue by andrew-selvia** [sbt/sbt#7391]
## steps

The issue can be reproduced consistently with the following configuration:

`project/build.properties`:
```properties
sbt.version = 1.9.6
```

`build.sbt`:
```sbt
ThisBuild / scalaVersion := "3.3.1"
lazy val root = project.aggregate(a, aJava, b).in(file("."))
lazy val aJava = project.settings(autoScalaLibrary := false, crossPaths := false, name := "a")
lazy val a = project.dependsOn(aJava).settings(name := "a")
lazy val b = project.dependsOn(a)
```

```shell
sbtn update
```

## problem

This is the error message sbt reports:
```
sbt:root> update
[error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/private/tmp/foo/"), "b"):
[error]    a:a <none>, _3
[error] stack trace is suppressed; run last b / update for the full output
[error] (b / update) Conflicting cross-version suffixes in: a:a
```

## expectation

sbt should not detect conflicting cross-version suffixes when a Java & Scala library share the same name. It makes sense to detect cross-version conflicts for different Scala binary versions, but on the surface it's less clear that this should be the behavior between Java & Scala libraries. Please forgive any ignorance I carry into the conversation.

## notes

I noted [this first on Discord](https://discord.com/channels/632150470000902164/922600050989875282/1159055446502555678). @armanbilge & I are under the impression that [this should actually work](https://discord.com/channels/632150470000902164/922600050989875282/1159126148605804664). There seems to be no workaround.

**Comment by eed3si9n** [comment]
I think this is somewhat borderline situation. Internally `"com.example" % "foo" % "1.0.0"` and `"com.example" %% "foo" % "1.0.0"` are represented using `ModuleID("com.example", "foo", "1.0.0")` with different values on cross attributes. The validation logic is merely asserting the assumption that we make that the triple is considered an identity, and we expect to have unique values in a classpath.

In practice, like you mentioned mixing Java and Scala coordinate might be ok. In any case, you can turn off the warning at your own risk using the following:

```scala
conflictWarning := ConflictWarning.disable,
```

**Comment by eed3si9n** [comment]
Also thanks for reporting with steps, problem, and expectations.

**Comment by andrew-selvia** [comment]
I appreciate the explanation. 🙏🏻 The default behavior is sensible.

My build leverages scalapb to generate both Java & Scala sources so that `javaConversions` can be generated. I'll link @thesamet in case it may help to mention this possibility in the scalapb documentation.

I'm confident enough in sbt to use `disable`, but I'll leave a link to our discussion adjacent to the setting in my build. Thanks for the suggestion @eed3si9n! 👏🏻
