### ISSUE TITLE
JAR creation captures current time?

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#7401]
## problem

https://github.com/sbt/io/blob/2656359e9ce42dc7e901277775bd66e3e9ccd4f3/io/src/main/scala/sbt/io/IO.scala#L756
```scala
            e setTime time.getOrElse(System.currentTimeMillis)
```

## expectation

This should be stable (hardcode to 2010 by default)

**Comment by ghost** [comment]
Hi @eed3si9n , do you mean `System.currentTimeMillis` be set to 2010 ? Does anything else need to be done ?
I would like to take up this issue.

**Comment by eed3si9n** [comment]
Never mind. It is doing `time.getOrElse(System.currentTimeMillis)` so it should be stable when time is Some.
