### ISSUE TITLE
Running two simultaneous instances of sbt fails

### ISSUE THREAD

**Issue by samstarling** [sbt/sbt#741]
Regardless of where I run `sbt` from (ie. regardless of the project), I get the following error when I try and run two instances of `sbt`:

```
$ sbt
Error: Exception thrown by the agent : java.rmi.server.ExportException: Port already in use: 8089; nested exception is:
    java.net.BindException: Address already in use
```

Running `lsof` to see what's holding on to that port seems to show that it's `sbt`:

```
java      1259 starls01   31u    IPv6 0x1fc4419f875e80af       0t0     TCP *:8089 (LISTEN)
```

That line disappears when I quit the running `sbt`. I'm unsure if this is a bug, but I re-installed my entire machine recently and it still occurs. Has anyone seen this happen before? I'm using `0.12`.

**Comment by jsuereth** [comment]
Are you using any global or non-standard plugins?

**Comment by samstarling** [comment]
My `~/.sbt/global.sbt` only adds a couple of additional resolvers. How do I check whether I have any plugins? I'm pretty sure I don't have any.

**Comment by jsuereth** [comment]
`~/.sbt/plugins` or `<your local project>/project/*.sbt`   Also do you have any _agents_ installed on the JVM itself?

**Comment by samstarling** [comment]
I have nothing in `~/.sbt/plugins`, and I'm running this from a project with no plugins. I don't think I have any agents installed, but (again!) I'm not sure how to check that I'm afraid – it's just the vanilla JVM that comes with OS X.

**Comment by harrah** [comment]
This appears to be related to jmx and is very unlikely to be related to sbt.  Check your sbt startup script or anywhere a jvm agent might be added.  Please feel free to see if anyone has ideas on the mailing list.
