### ISSUE TITLE
sbt run issue

### ISSUE THREAD

**Issue by gopakumarkeerthiveettil** [sbt/sbt#7415]
I have an Scala sbt application. Using the sbt to compile and generate jar file from the Scala application. I installed sbt in my local machine and setup the environment variable. While running sbt its getting the below error. Can any one please support to fix the issue.

C:\tesseract-OA-testbranch>sbt
[info] [launcher] getting org.scala-sbt sbt 1.8.0  (this may take some time)...
[error] [launcher] xsbt.boot.internal.shaded.coursier.error.ResolutionError$CantDownloadModule: Error downloading org.scala-sbt:sbt:1.8.0
  not found: C:\Users\UX506188\.ivy2\local\org.scala-sbt\sbt\1.8.0\ivys\ivy.xml
  download error: Caught javax.net.ssl.SSLHandshakeException (PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.8.0/sbt-1.8.0.pom
  download error: Caught javax.net.ssl.SSLHandshakeException (PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/sbt/1.8.0/sbt-1.8.0.pom
  download error: Caught javax.net.ssl.SSLHandshakeException (PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/scala-sbt/sbt/1.8.0/sbt-1.8.0.pom
  download error: Caught javax.net.ssl.SSLHandshakeException (PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/1.8.0/ivys/ivy.xml
  download error: Caught javax.net.ssl.SSLHandshakeException (PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/1.8.0/ivys/ivy.xml
[error] [launcher] could not retrieve sbt 1.8.0

**Comment by eed3si9n** [comment]
1. Could you please use the latest stable version, sbt 1.9.7?
2. SSLHandshakeException might be an indication of JDK or network error. Could you update your JDK to the latest patch version of JDK 8, 11, 17 etc of a reputable JDK? I recommend Eclipse Adoptium - https://adoptium.net/

In general, however, this doesn't appear to be a bug of sbt itself. See https://www.scala-sbt.org/community.html on where you can get further assistance.

**Comment by gopakumarkeerthiveettil** [comment]
I have installed jdk 17.0.3.1 already but not working

**Comment by SethTisue** [comment]
There is abundant information online about these PKIX errors. It's nothing specific to sbt.
