### ISSUE TITLE
Sbt going into sbtn by default on WSL2 Ubuntu, Ignoring scalaVersion in build.sbt

### ISSUE THREAD

**Issue by nsubordin81** [sbt/sbt#7422]
## steps

1. install windows subsystem for linux 2 on a PC running Windows 11
2. use Ubuntu 22.04.2 LTS, jammy as the ubuntu version
3. follow the linux instructions to install coursier from this page https://get-coursier.io/docs/cli-installation
4. sbt verison I'm using through coursier is the latest available I believe right now after performing an update with coursier, which is 1.9.6
5. create some scala 3 project with a build.sbt that specifies scalaVersion to v3.3.1 with scalaVersion := "3.3.1"

## problem

when I start the sbt console in wsl2 ubuntu with the sbt setup as above, it is always launching with the experimental thin client (sbtn?)
looks like this: 
![image](https://github.com/sbt/sbt/assets/4014893/653ec96c-73d8-4b51-813a-ae501f406279)

Additionally, when using this thin client, sbtn seems to always build my project against scala 2.12.18, which isn't anywhere in my project's configuration. I've read that sbt uses an internally set default version of scala when none is provided, but I have provided a scalaVersion in my build.sbt as described above. Since I want to use scala3 features, the compiler breaks.

I have attempted to force sbt to run in the non thin client mode by using the --server flag, but as this appears to be yet another non-standard mode that uses sockets for communication, it is preventing my application from communicating with its filesystem database.

## expectation

I would have expected sbt to launch in WSL2 Ubuntu the same way it does on my Windows installation, not in the sbtn thin client. failing that, I would have expected there to be some way that I can specify that I don't want to use --client or --server mode and just want sbt to launch in a standard way. Lastly, if I had to use the thin client because it was the only way sbt would work within the WSL2 platform, I'd have expected it to pick up the scalaVersion setting in my build.sbt.

## notes

I'm fairly new to using sbt as a build tool and don't have an understanding or appreciation of the nuances of these different flavors of sbt (sbtn, --server mode, ...). I am mostly just trying to get scala compilation to work within windows subsystem for linux. I'm open to alternative strategies if wsl2 isn't supported in the way I'm expecting it to be. I'm a happy camper if I can compile my project with a dotty compiler and have the running program use slick to talk to an h2db instance, its just that so far none of the configurations I've tried have allowed for all of these things to be true. Thank you and thanks for making such great software I'll keep working on learning it!

**Comment by nsubordin81** [comment]
ok, I feel silly, somewhere along the line I must have set $SBT_NATIVE_CLIENT to 'true'. 

egg on my face. 

I am thinking of closing this out, however, I wonder if ignoring the project's scala version in the build is expected behavior for the client? If so then there is probably no reason to keep this one up.

**Comment by nsubordin81** [comment]
hmm, couldn't find that setting in any of my dotfiles. well that's odd, maybe the shell gets that env var set that way through coursier or something? not really sure, didn't track it down, just added the export to the setting I wanted to my zshrc file. 

I don't know what I'd suggest here. The docs for the thin client do mention this environment variable, so it was an easy find for debugging. If this setting really is automatically made by one of the tools I used for setting up my scala environment I'd suggest not have it default to the thin client unless that will behave pretty much like standard sbt.  But this 'bug' is like 90% pebkac I'm thinking now.

**Comment by SethTisue** [comment]
was there any indication of what was going on if you ran under `-debug`? because if not, surely we'd accept a PR that added a debug-level logging line about it
