### ISSUE TITLE
Universal sbtn binary for mac

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#7427]
## steps

https://github.com/sbt/sbtn-dist/releases/tag/v1.9.2

## problem

Currently installSbtn logic assumes a universal macOS binary (a binary that works on both aarch64/M1 and Intel mac), but our CI/CD is set up to create aarch64-specific binary.

_Originally posted by @keynmol in https://github.com/sbt/sbt/pull/7426#discussion_r1381706728_

**Comment by eed3si9n** [comment]
https://github.com/sbt/sbtn-dist/releases/tag/v1.9.7 has universal macOS binary.

https://github.com/sbt/sbtn-dist/blob/7ab26769978f6d54381024734e950d3c03acfbb3/.github/workflows/native.yml#L90-L97

1. Create a release on sbtn/sbtn-dist
2. Manually upload `sbtn-aarch64-apple-darwin` from https://cirrus-ci.com/github/sbt/sbtn-dist (in theory this process should be automated)
3. Rerun action that combines the Apple binaries, if needed
4. Run script to compress and sign

**Comment by keynmol** [comment]
@eed3si9n I think this can be reopened, given that Github finally released free Apple Silicon workers - I think it's best to modify the Github workflow to build all binaries automatically: https://github.com/sbt/sbtn-dist/pull/11

**Comment by eed3si9n** [comment]
Fixed in 1.10.0 - https://github.com/sbt/sbt/pull/7551 / https://github.com/sbt/sbtn-dist/pull/11
