### ISSUE TITLE
No download progress shown when running as part of "podman build" or "docker build"

### ISSUE THREAD

**Issue by gaeljw** [sbt/sbt#7438]
## steps

Given the following `Dockerfile` which runs a `sbt update` command as part of the image construction:

```Dockerfile
FROM eclipse-temurin:11-jre-jammy

# Install git
RUN apt-get update && \
  apt-get install -y git && \
  rm -rf /var/lib/apt/lists/* && \
  git --version

# Mandatory as sbt cannot run from /root anyway
WORKDIR /build

# Install sbt
ARG SBT_VERSION=1.9.7
RUN \
  curl -k -L -o sbt-$SBT_VERSION.deb https://repo.scala-sbt.org/scalasbt/debian/sbt-$SBT_VERSION.deb && \
  dpkg -i sbt-$SBT_VERSION.deb && \
  rm sbt-$SBT_VERSION.deb && \
  apt-get update && \
  apt-get install sbt && \
  rm -rf /var/lib/apt/lists/* && \
  sbt sbtVersion

# Download some sbt project
RUN git clone https://github.com/leanovate/play-mockws.git

# Run a sbt command that should give plenty of output
RUN cd play-mockws && sbt update
```

Copy the file in a folder and run `podman build --no-cache .` to build the image from the Dockerfile.

## problem

When building the image with `podman build --no-cache .`, the sbt command doesn't give as much output as it does when running outside of a Dockerfile.

Here's the output:
```
...
STEP 6/7: RUN git clone https://github.com/leanovate/play-mockws.git
Cloning into 'play-mockws'...
--> 1ae889e2fe5b
STEP 7/7: RUN cd play-mockws && sbt update
[info] welcome to sbt 1.9.7 (Eclipse Adoptium Java 11.0.21)
[info] loading settings for project play-mockws-build from plugins.sbt ...
[info] loading project definition from /build/play-mockws/project
[info] loading settings for project play-mockws from build.sbt ...
[info] set current project to play-mockws (in build file:/build/play-mockws/)
[success] Total time: 14 s, completed Nov 23, 2023, 4:12:50 PM
COMMIT
--> fc9820272ac3
```

## expectation

Doing the same commands outside of the build context/scenario gives plenty of output (like all the stuff that sbt downloads).

For instance, comment the last line (the `sbt update` command) of the Dockerfile above:
```diff
- RUN cd play-mockws && sbt update
+ # RUN cd play-mockws && sbt update
```

Build the image again and give it a name to then exec into it:
```shell
podman build . -t testsbt

podman run -it testsbt bash

> cd play-mockws
> sbt update
```

Now the output is something like the following:
```
[info] welcome to sbt 1.9.7 (Eclipse Adoptium Java 11.0.21)
[info] loading settings for project play-mockws-build from plugins.sbt ...
[info] loading project definition from /build/play-mockws/project
https://repo1.maven.org/maven2/com/github/sbt/sbt-github-actions_2.12_1.0/0.19.0/sbt-github-actions_2.12_1.0-0.19.0.pom
  100.0% [##########] 3.0 KiB (4.5 KiB / s)
https://repo1.maven.org/maven2/org/scalameta/sbt-scalafmt_2.12_1.0/2.5.2/sbt-scalafmt_2.12_1.0-2.5.2.pom
  100.0% [##########] 2.9 KiB (4.4 KiB / s)
https://repo1.maven.org/maven2/org/scoverage/sbt-coveralls_2.12_1.0/1.3.11/sbt-coveralls_2.12_1.0-1.3.11.pom
  100.0% [##########] 3.8 KiB (5.7 KiB / s)
https://repo1.maven.org/maven2/org/scoverage/sbt-scoverage_2.12_1.0/1.8.2/sbt-scoverage-1.8.2.pom
  100.0% [##########] 2.3 KiB (47.4 KiB / s)
...
```

I would expect to have this same output when running `sbt update` as part of `podman build`.

## notes

I guess this issue is somewhere between sbt and podman, I open it here as I believe I didn't see the same behaviour with Maven for instance but obviously, I may transfer it to podman/docker if you tell me this has nothing to do with sbt.

In comparison with another unrelated tool, the `apt-get` commands do give some outputs as I would expect.

To be noted that the same happens with Docker, it's not specific to podman.

**Comment by SethTisue** [comment]
i don't know anything about podman or docker, but maybe sbt is (probably by design) behaving differently depending on whether it's connected to a terminal or not. is it possible it's as simple as that?

**Comment by gaeljw** [comment]
I guess so indeed. Then the question would be: how to get the full output when not connected to a terminal?

**Comment by SethTisue** [comment]
https://www.scala-sbt.org/community.html has advice on where to ask questions. (This was really more of a question than a bug report from the beginning.)

**Comment by gaeljw** [comment]
Right, here's the question on StackOverflow for anyone coming here: https://stackoverflow.com/questions/77541385/no-download-progress-shown-when-running-as-part-of-podman-build-or-docker-bui
