### ISSUE TITLE
Use of `MainGenericRunner` with `fork in run := true`

### ISSUE THREAD

**Issue by jrudolph** [sbt/sbt#744]
Why are forked Scala processes run through `MainGenericRunner`? 

Users of sbt-revolver are reporting that the use of `MainGenericRunner` seems to implicate a certain class loader setup which may lead to issues sometimes. See spray/sbt-revolver#18

**Comment by jsuereth** [comment]
IIRC - this was done due to the windows console argument bug, where you can't pass arugment lists greater than a certain size, so you wrap the main method with something that reads arguments from a file, and then runs the main method.

**Comment by harrah** [comment]
See #702.

@jsuereth I don't see how that relates here.  There are no argument files involved.

**Comment by jrudolph** [comment]
Sorry, I missed the follow-up. Thanks for fixing it.
