### ISSUE TITLE
sbt 1.9.8 not yet available with sdkman

### ISSUE THREAD

**Issue by mkurz** [sbt/sbt#7461]
```
$ sdk list sbt
```
:cry:

**Comment by eed3si9n** [comment]
oops sorry. I just released it on sdkman.

**Comment by mkurz** [comment]
Would it make sense to make publishing to sdkman part of a GitHub workflow that runs when pushing the tag or when the release notes get published?

**Comment by eed3si9n** [comment]
Yea, maybe we can try it upon release.
