### ISSUE TITLE
Enable overriding of plugin default settings

### ISSUE THREAD

**Issue by sirthias** [sbt/sbt#749]
Currently it appears to be impossible to override the settings provided by a plugin via its `settings` member. It'd be great if these settings had lower priority than the ones I explicitly provide myself.

Motivation: I use the sbt-pgp plugin for a project with 5 sub-projects, of which only 3 need publishing of signed artifacts. For the other 2 sub-projects I'd like to be able to "disable" the `publish-signed` task via an explicit `publishSigned := ()` setting.
Up until sbt-pgp version 0.7 the plugin relied on the default `publish` task which overriding via `publish := ()` works nicely for. However, since with version 0.8 the plugin now provides its own task `publish-signed` with its default settings overriding is not possible anymore.

See also this issue from sbt-pgp: https://github.com/sbt/sbt-pgp/issues/36

**Comment by harrah** [comment]
Settings have the following precedence, higher first: 1) settings from .sbt files 2) auto-settings from plugins 3) Build.scala settings.

In any case, control over automatically added settings was already implemented for 0.13:  http://www.scala-sbt.org/0.13.0/docs/Community/ChangeSummary_0.13.0.html#control-over-automatically-added-settings

**Comment by sirthias** [comment]
Thanks, Mark, for this clarification and the pointer!
