### ISSUE TITLE
JLine version (3.19.0) is outdated

### ISSUE THREAD

**Issue by SethTisue** [sbt/sbt#7498]
sbt is still on JLine 3.19.0, which is quite old — it's from 2021. The JLine folks have fixed a ton of bugs since then. Current version is 3.24.1.

At minimum, it would be good for sbt 2.x to upgrade. We could also look at whether a backport to 1.x would be feasible.

**Comment by SethTisue** [comment]
I fooled with this for an about an hour locally, but to get on 3.24.1, a bunch of changes to `sbt.internal.util.JLine3` will be needed, and then I'm not sure how much more rabbit hole lies beyond that

**Comment by eed3si9n** [comment]
Are they supposed to be backward compatible? In other words, if we injected the latest JLine 3.24.1 to classpath, would Scala 2.x REPL and Scala 3.x REPL continue to work?

**Comment by hamzaremmal** [comment]
> Are they supposed to be backward compatible? In other words, if we injected the latest JLine 3.24.1 to classpath, would Scala 2.x REPL and Scala 3.x REPL continue to work?

It doesn't look like this is the case for earlier versions of JLine3 (jline/jline3#189). Also, Scala 3 might be moving to JLine 3.25.1 (See lampepfl/dotty#19744)

**Comment by eed3si9n** [comment]
I also realized that we've already bumped JLine for sbt 1.10.x, and 1.10.0-M1 has been out for a while - https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.10.0-M1/ and REPL seem to work fine for both Scala 2.13 and 3.

**Comment by SethTisue** [comment]
> I also realized that we've already bumped JLine for sbt 1.10.x, and 1.10.0-M1 has been out for a while

Oh, right you are. I mistakenly looked at the 1.x branch but did not look at the 1.10.x branch.
