### ISSUE TITLE
Error when compiling with Scala 2.9.0*

### ISSUE THREAD

**Issue by john76** [sbt/sbt#75]
C:\Local\john\brambly\src\sandbox\xsbt\compile\Eval.scala:117: error: overloaded method value Super with alternatives:
  (sym: Eval.this.global.Symbol,mix: Eval.this.global.TypeName)Eval.this.global.Tree <and>
  object Eval.this.global.Super
 cannot be applied to (Eval.this.global.TypeName, Eval.this.global.TypeName)
                        Block(List(Apply(Select(Super(emptyTypeName, emptyTypeName), nme.CONSTRUCTOR), Nil)), Literal(Constant(())))

Happens with both 2.9.0.final and 2.9.0-1

**Comment by harrah** [comment]
I don't know what the issue is here.  sbt is built against 2.8 (obviously).  If you have a question, please use the mailing list and not the bug tracker.

**Comment by john76** [comment]
Hi Mark,

Thank you for your reply.

Does the word "obviously" mean it's better to stick with 2.8.1 for now (including Scala IDE)?

I'm quite new to Scala, and I want to set up a stable environment, with Eclipse as an IDE and OSGi support, which would allow me to concentrate on my project rather than fight with dependencies.

bnd4sbt is a very desirable tool to be used, but it still supports only sbt 0.7. Is it better to stick to 0.7 till the majority of useful plugins gets ported to 0.10?

Thank you,
Roman

**Comment by harrah** [comment]
The version of Scala that sbt is compiled against is different from the version of Scala used to build a project.  Please use the mailing list for questions.
