### ISSUE TITLE
Tracking.jar : Repo is down

### ISSUE THREAD

**Issue by Gingonic** [sbt/sbt#751]
The : http://repo.typesafe.com/typesafe/maven-ivy-releases/org.scala-sbt/tracking/0.12.3/jars/tracking.jar is down.
The download can't proceed and it blocks the complet process (even manualy you can't download).
The complete 0.12.\* reacts in the same way.

**Comment by harrah** [comment]
Please use the mailing list for transient problems.  It is up from here now.

**Comment by jsuereth** [comment]
Just a quick note:  Our artifactory went through an upgrade cycle yesterday.   It should be complete now, and everythign back online.  Sorry for any inconvenience.

**Comment by Gingonic** [comment]
Doesn't seem to be up, at least not reachable from germany, I just tested
again.
I really don't see what could be wrong on my side on such an automatised
process :

<< Begin Console Log>>

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\xxx\swagger-codegen>sbt assembly
Getting org.scala-sbt sbt 0.12.2 ...
downloading
http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/trackin
g/0.12.2/jars/tracking.jar ...

<< End Console Log>>

2013/5/6 Josh Suereth notifications@github.com

**Comment by jsuereth** [comment]
Hmm, I'm able to see: http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/tracking/0.12.3/jars/tracking.jar

and
http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/tracking/0.12.2/jars/tracking.jar

right now.  Maybe bump your build.properties to 0.12.3 and see what happens?

**Comment by Gingonic** [comment]
I just switched back to the 0.12.3 to be sure, but as expected, same result.

What's really strange is that I can't even downloaded by "hand" directly
from the Browser or so, while I can download all the other, for example the
Task.jar.

This actually leeds me to think that it can't be on my end, except if I'm
facing some very new crazy windows .jar security policy stuff. But why just
that one?

(I joined a small png of what Chrome says after 10 minutes or so when I try
by Browser : "Fehler - Netzwerkfehler" => "Error - Network error")

2013/5/6 Josh Suereth notifications@github.com

**Comment by jsuereth** [comment]
It could also be a stale DNS cache.

If you go to repo.typesafe.com, what do you see?

**Comment by Gingonic** [comment]
Sorry, wrong picture

2013/5/6 Christophe Nick christophe.nick@gmail.com

**Comment by Gingonic** [comment]
Seems to be all good

2013/5/6 Josh Suereth notifications@github.com
