### ISSUE TITLE
Error downloading org.scalameta:semanticdb-scalac_2.12.19:4.8.3

### ISSUE THREAD

**Issue by godenji** [sbt/sbt#7529]
## steps

set `build.properties` sbt version to `1.10.0-RC1`

## problem

Start `sbt` from project directory; error in issue title happens.

## expectation

Latest version of `semanticdb-scalac` (4.9.3) is downloaded. 

## notes

I blew away all top level bloop, bsp, metals directories, as well as releated config files in `project` directory. Additonally I cleaned out applicable files to in `~/.sbt/1.0/` to rule out global config pulling in the apparently non-existent `4.8.3` version of `semanticdb-scalac`.

1.10.0-M1 didn't have this issue. Perhaps I jumped the gun and related deps to 1.10.0-RC1 need to catch up??

**Comment by godenji** [comment]
After clearing out `project/project` and `project/target` for each subproject in the application, sbt session started successfully.

That's a *lot* of house cleaning to workaround the issue, someone new to Scala wouldn't even know where to begin :)

**Comment by eed3si9n** [comment]
For what it's worth Scala 2.12.19 seems to have semanticdb support for a bunch of versions - https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac-core_2.12.19/. It's possible that sbt's invalidation logic is somehow buggy, or it could even be one of the plugins (I don't think hand-rolled cache logic would remember to put Scala version into the input key)? We will keep an eye out for similar reports.
