### ISSUE TITLE
Add a javaSourceManaged

### ISSUE THREAD

**Issue by paddymahoney** [sbt/sbt#753]
From
http://www.scala-sbt.org/0.12.3/docs/Howto/generatefiles.html: "A source generation task should generate sources in a subdirectory of sourceManaged and return a sequence of files generated."

An issue arises with sourceGenerator that produces a sequence of java files. 

When these files are generated in a subdirectory of javaSource, they are seen and compiled as java code. But then continuous compile using ~ compile goes into a loop, as the javaSource directory is watched for changes and when the sourceGenerator runs it creates java files in this location. In addition, the build then doesn't manually cleanup after these files. 

If the java sources are generated in a subdirectory of sourceManaged, they are subsequently under the scala-2.10 /target/scala-2.10/src_managed/... directory, and are treated as scala code, and they fail to compile. 

This is a request for a javaSourceManaged output dir which isn't watched by an sbt "~ compile", is within target/java perhaps. Java source generated to this location using a sourceGenerator task would be compiled as javaSource.

**Comment by paddymahoney** [comment]
Per @jsuereth 's advice, I added the following SettingKey to the Build.scala file: 

val javaSourceManaged = SettingKey[File]("java-source-managed", "Output location for managed or generated java sources.")

This was a multi-project build file, and so within the project Settings, I added the following to the setting sequence: 
...
javaSourceManaged <<= target(t => t / "java"), 
managedSourceDirectories in Compile <+= javaSourceManaged,
...

Then, I adjusted our java sourceGenerator to output to the javaSourceManaged directory, which looks like:  
...
sourceGenerators in Compile <+= (myGen in Compile),
myGen in Compile <<= (name, javaSourceManaged, dependencyClasspath in Runtime in mainProj, baseDirectory) map { (name, outputDir, cp, base) =>
      generateJavaSources(name, outputDir, cp.files, base)
    },
...

One thing to watch out for if like me you were generating sources to some other source directory that isn't managed by sbt(we were putting to javaSources), is to ensure that when the output directory for the java source generator is changed to javaSourceManaged, that the original files are removed. Else, you may encounter errors like; 
[error] /home/dir/to/java/src/managed/S_SomeJavaClassName.java:7: error: duplicate class: com.your.pkg.name.SomeJavaPkgName.S_SomeJavaClassName
[error] public class S_SomeJavaClassName extends SomeJavaClass {
[error]        ^

**Comment by harrah** [comment]
Well, I wouldn't be opposed to a `javaSourceManaged`, but it would be strictly organizational as far as I know.  This comment is not the behavior I would expect:

```
If the java sources are generated in a subdirectory of sourceManaged,
they are subsequently under the scala-2.10 /target/scala-2.10/src_managed/... 
directory, and are treated as scala code, and they fail to compile. 
```

Internally, Scala and Java sources are mixed and are re-separated by extension.  A test case showing the problem would be apprecated.  A pull request adding `javaSourceManaged` would be welcome.

**Comment by paddymahoney** [comment]
So my initial report is just plain incorrect. I made the mistake of failing to clear javaSources after changing the output directory of the source generator. Upon changing the output directory for the sourceGenerator, I ran into duplicate class definition errors, as the generated source still existed in the unmanaged javaSources directory. I then jumped the gun and attributed it to the java source being compiled as scala, and failing. This was incorrect. Is it worthwhile to correct the original report, perhaps with corrections inline? i worry about my mistake confusing future sbt'ers. 

Pull request forthcoming.

**Comment by harrah** [comment]
I wouldn't worry about it.  Users have to know that an initial bug report is not always accurate and you have to read the full conversation.  If you really want to, you could add a short note to the top of the original report.  It is probably best to keep the original text, though.

**Comment by harrah** [comment]
Closing per discussion in #766.

**Comment by jroper** [comment]
Somewhat related to this (this would be a possible solution).  The sbt documentation is currently wrong - it says that generated sources should be in a sub directory under `sourceManaged`.  But it treats `sourceManaged` as the root directory for compilation.  This is irrelevant for scala files, since the directory structure of scala files does not need to match the package structure.  But for Java files, it does, so the Java sources must be in a directory structure that matches their package structure under `sourceManaged`, not a sub directory of `sourceManaged`.  One way to solve this would be to have a separate `javaSourceManaged` key.

Issues related to this:

https://github.com/mpeltonen/sbt-idea/pull/257
https://github.com/playframework/playframework/issues/2941
