### ISSUE TITLE
Command alias doesn't work with the project prefix

### ISSUE THREAD

**Issue by danicheg** [sbt/sbt#7535]
## steps
0. I have sbt `1.9.9`.
1. Define a `sbt.Project` via API. Let it be called `foo`.
2. Define a command alias via API. Let it be `addCommandAlias("fmtCheck", ";scalafmtCheckAll ;scalafmtSbtCheck")`.
3. Run the `sbt foo/fmtCheck`.

## problem
```
sbt:example> foo/fmtCheck
[error] Expected ':'
[error] Not a valid key: fmtCheck (similar: scalafmtCheck, scalafmtSbtCheck, scalafmtCheckAll)
[error] foo/fmtCheck
[error]
```

## expectation
It should work analogously to 
```
sbt:example> project foo
[info] set current project to foo (in build file:/Users/user/projects/example/)
sbt:foo> fmtCheck
[success] Total time: 1 s, completed Apr 15, 2024, 1:54:49 PM
[success] Total time: 0 s, completed Apr 15, 2024, 1:54:49 PM
sbt:foo> project /
[info] set current project to example (in build file:/Users/user/projects/example/)
sbt:example>
```

## notes
I didn't manage to find any similar issues (however, there are other open issues with command aliases), so I created this one.

**Comment by eed3si9n** [comment]
The subproject syntax is handled by the act command, so you probably have to make it a task that calls both.
