### ISSUE TITLE
Print a warning if sbt.version is not defined in the project/build.properties

### ISSUE THREAD

**Issue by OlegYch** [sbt/sbt#754]
This would help creating more reproducible builds.

**Comment by SethTisue** [comment]
this'd be great. I often run into people who aren't aware this is recommended practice. there are also people who are aware, but never quite get around to adding the version, and a nudge from a warning would help.

**Comment by eed3si9n** [comment]
We should just create one automatically if it's not there at startup.

**Comment by dwijnand** [comment]
@eed3si9n Sure, but only after being prompted. Otherwise we run the risk of creating `build.properties` files in random locations when the user is in the wrong directory (eg. in `src/`).

**Comment by dwijnand** [comment]
`sbt new` is the exception to the rule.

**Comment by dwijnand** [comment]
Ok, so to mitigate accidental file creation we can use sbt-extras' algorithm: the presence of a .sbt file at the root or a 'project' directory at the root.

**Comment by dwijnand** [comment]
Silently create the file.

**Comment by dwijnand** [comment]
If there's no sbt.version, no *.sbt file and no project directory, e.g you accidentally started sbt in /tmp, warn and continue, in both 0.13 and 1.0.
