### ISSUE TITLE
Work around platform limits when forking tests 

### ISSUE THREAD

**Issue by harrah** [sbt/sbt#755]
Windows in particular has limits that are hit when forking tests with larger classpaths.

[Eclipse bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=327193) and [first](http://git.eclipse.org/c/jdt/eclipse.jdt.debug.git/commit/?id=a24b7af73c4e08e7b05935d30be10b1afd046dcc) and [second](http://git.eclipse.org/c/jdt/eclipse.jdt.debug.git/diff/org.eclipse.jdt.launching/launching/org/eclipse/jdt/internal/launching/StandardVMRunner.java?id=d175f8d9ea16b28a0f2a79d2e972a887ec333db8) commits implementing it.

[IntelliJ behavior](http://stackoverflow.com/questions/4853540/what-does-the-dynamic-classpath-flag-do-intellij-project-settings)

**Comment by harrah** [comment]
There is currently no specific timeline for implementing this.

**Comment by vigdorchik** [comment]
How is forking tests different from e.g. forking javac for compilation?

**Comment by harrah** [comment]
javac has the convenient `@argfile` option, which sbt takes advantage of.  If the java command did too, it would be an easier fix.

**Comment by harrah** [comment]
Will try to implement the CLASSPATH solution for 0.13.1.

**Comment by harrah** [comment]
Full testing on Windows is pending.  Windows users are invited to verify `run/test` succeeds.

**Comment by harrah** [comment]
Also, Linux has limits on the total space allocated to a forked process that includes the environment.  This limits the upper size of the classpath to somewhere between 100k and 200k characters.  This can't be fixed without the more invasive ClassLoader fix used by IntelliJ or without `java` providing the argfile option like `javac`.

**Comment by vigdorchik** [comment]
Running run / daemon
Running run / daemon-exit
Running run / error
Running run / fork
Running run / fork-loader
Running run / spawn
Running run / spawn-exit
[success] Total time: 252 s, completed 13-Sep-2013 16:32:52

Running tests / arguments
Running tests / arguments-new
Running tests / do-not-discover
Running tests / done
Running tests / empty
Running tests / fork
Running tests / fork-uncaught
Running tests / fork2
Running tests / it
Running tests / junit
Running tests / nested-inproc-par
Running tests / nested-inproc-seq
Running tests / nested-subproc
Running tests / one-class-multi-framework
Running tests / order
Running tests / resources
Running tests / serial
Running tests / setup-cleanup
Running tests / single-runner
Running tests / specs-run
Running tests / t543
Running tests / task
Running tests / test-quick
[success] Total time: 964 s, completed 13-Sep-2013 16:49:26

It's painfully slow though.

**Comment by harrah** [comment]
Hey @vigdorchik, thanks for testing.  What I meant was the `test` task for the `run` project.  With the configuration explicit: `run/test:test`.

**Comment by vigdorchik** [comment]
@harrah ah, that's faster:

> run/test:test
> run/test:test
> [info] + Fork.Arbitrary length classpath successfully passed.: OK, passed 100 tests.
> [info] Passed: Total 1, Failed 0, Errors 0, Passed 1
> [success] Total time: 24 s, completed 13-Sep-2013 17:37:25

**Comment by harrah** [comment]
Great, thanks @vigdorchik!
