### ISSUE TITLE
Ivy revision latest version Semver syntax is buggy.

### ISSUE THREAD

**Issue by altrack** [sbt/sbt#7552]
## steps

I'm running SBT version 1.9.9 (also happens in 1.9.8) on Mac M1 OS 14.4.1.
A dependency version defined with Ivy syntax to fetch latest minor version as following `1.+`.  
The resolver is an Artifactory server.  
This definition works time to time. 

## problem

Issue: When I update the version of the dependency, it doesn't fetch the newest version.  

Checking in the Artifcatory server and it has the new version folder and updated `maven-metadata.xml`.

I tried to kill + start SBT, `reload` the SBT, as well as run `update`, but nothing fixes the issue.

Checking the local cache at:  
`~/Library/Caches/Coursier/v1/https/artifactory.myserver.com/artifactory/sbt-main/com/company/mypackage_2.13`  
I see that `maven-metadata.xml` is not being updated to the latest version, 
also the folder of the latest version doesn't exist.

This issue has been reproduced on multiple Mac computers.

Another check I did is setting the specific version of the latest dependency - works as expected.  
After that changing back to `1.+` doesn't seem to fix the issue.  

## expectation

`1.+` Ivy syntax in SBT fetches the latest version of the dependency.
This feature works time to time.

## notes

Work-around delete the local cache folder of the package.

**Comment by eed3si9n** [comment]
This is because Coursier implements TTL. See https://get-coursier.io/docs/ttl please.
