### ISSUE TITLE
Sbt server displays weird characters around dates on Windows

### ISSUE THREAD

**Issue by segundovolante** [sbt/sbt#7558]
## steps

Run sbt, for example
* sbt compile

## problem

Output display weird characters on the timestamps.

```
Total time: 1 s, completed May 12, 2024, 2:35:31ΓÇ»PM
```
![image](https://github.com/sbt/sbt/assets/792325/1fa8bd27-b833-45de-9cbc-5908e7f0b69a)

This does not happen on WSL (ubuntu), same terminal same font. 

![image](https://github.com/sbt/sbt/assets/792325/ef7b0971-adc6-4fd7-9812-2c83bbac4c4f)

## expectation

Display date times without the extra characters: 

```
Total time: 1 s, completed May 12, 2024, 2:35:31 PM
```

**Comment by eed3si9n** [comment]
Thanks for the report. Could you tell us what the environment that you are seeing this issue, for example the shell and the console program? Also could you check if this is specific to sbt 1.10.0 or it happens with previous versions?

**Comment by segundovolante** [comment]
Both images are using Windows terminal. (Version: 1.20.11271.0)
* Black background:  Powershell 7.4.2 (Windows 11) . I can also reproduce this on regular CMD from windows.
* Blue background: WSL - Ubuntu on windows terminal

Yes, I also see this happening on 1.9.9

**Comment by eed3si9n** [comment]
So I'm guessing that "ΓÇ»" is either an ASCII control sequence or some string in encoding A, misinterpreted by your shell as another encoding B, also known as mojibakeh. If you have some override of JVM parameters, could you try adding `-Dfile.encoding=UTF-8`?

**Comment by segundovolante** [comment]
I ran it in verbose mode, I can see the encoding being UTF-8.  I still see the issue. 

```
❯ sbt -v
# Executing command line:
"C:\Program Files\Amazon Corretto\jdk21.0.3_9\bin\java.exe"
-Dfile.encoding=UTF-8
-Dscala.ext.dirs="C:\Users\username\.sbt\1.0\java9-rt-ext-amazon_com_inc__21_0_3"
-Xms1024m
-Xmx1024m
-Xss4M
-XX:ReservedCodeCacheSize=128m
-cp
"C:\Users\username\AppData\Local\Coursier\cache\arc\https\github.com\sbt\sbt\releases\download\v1.10.0\sbt-1.10.0.zip\sbt\bin\sbt-launch.jar"
xsbt.boot.Boot
```

**Comment by segundovolante** [comment]
unrelated, but I noticed that this does not work on powershell (it works on regular cmd) 

```
sbt -Dfile.encoding=UTF-8
```

It throws this error:
```
[error] Not a valid command: UTF-8
[error] Not a valid project ID: UTF-8
[error] Expected ':'
[error] Not a valid key: UTF-8
[error] UTF-8
[error]  
```

It seems that on windows/powershell I am not able to override properties that contain a period.

This works:
```
sbt  -Dkey=value

```

**Comment by segundovolante** [comment]
Hey I think i found the issue. 

It uses this character NNBS, this can also be reproduced in scala-cli, or other java tool I think. This might be an issue on how java handles this in windows,.
```
val c: Char = 8239
```
I don't think it is specific to SBT, so you can probably close it, unless you want to display different format in windows compared to linux.

**Comment by Friendseeker** [comment]
Still reproducible on sbt 1.10.4. The JLine updates did not sort the issue out... (Screenshot is on cmd, but also issue with Powershell with Windows Terminal).

![image](https://github.com/user-attachments/assets/bb72af09-c65f-4177-b391-9dcdf64fa26a)

**Comment by Friendseeker** [comment]
```
@main
def main(): Unit = {
  val c: Char = 8239
  println(c + "Hello world!" + c)
}
```

Outputs

![image](https://github.com/user-attachments/assets/ebfaac3a-d3c9-422e-a3c1-60ac09fe958f)

on Windows...

This is probably a JLine issue.

**Comment by Friendseeker** [comment]
This issue is cursed. It is actually not JLine issue but rather windows terminal / cmd.exe does not support display it. [My last test](https://github.com/sbt/sbt/issues/7558#issuecomment-2445503465) succeeded as I was checking result in Intellij's own shell. Printing to windows terminal surfaces the issue.

```java
public class Main {
    public static void main(String[] args) {
        char c = 8239;
        System.out.println(c + "Hello World" + c);
    }
}
```

Output (Windows Terminal)
```
PS D:\Repos\untitled12223\out\production\untitled12223> java Main
?Hello World?
```

It is not even a java exclusive issue. Node.js actually does a [string replacement hack](https://github.com/nodejs/node/commit/492fc95bdf#diff-4a2fe69385dc3e1d4b11272846d7270ccd77643ad7eb2edbb33a02a3d13ca609R758) to replace 8239 to regular space... Unlike node.js Java just [went ahead with their change](https://inside.java/2024/03/29/quality-heads-up/).

----

It is not actually windows terminal... I guess indeed it is JDK then.

```
PS D:\Repos\untitled12223\out\production\untitled12223> $text = "NNBSP Test:" + ([char]0x202F) + "Example Text"
PS D:\Repos\untitled12223\out\production\untitled12223> Write-Output $text
NNBSP Test: Example Text
```

I gave up investigating the issue and made #7846 to workaround it.
