### ISSUE TITLE
Scala no longer likes being told things twice (-Xplugin specified twice in test:compile::scalacOptions)

### ISSUE THREAD

**Issue by jsuereth** [sbt/sbt#757]
As of Scala 2.11, specifying -Xplugin twice causes wonky behaviors, particularly build failures.

However, the issue is about specifying the plugin twice, which can be reproduced very simply:

build.sbt

``` scala
autoCompilerPlugins := true

libraryDependencies <<= (scalaVersion, libraryDependencies) apply { (v, d) =>
    d :+ compilerPlugin("org.scala-lang.plugins" % "continuations" % v)
}
```

Demonstrates the issue:

```
 ➜ sbt
[info] Loading global plugins from /home/jsuereth/.sbt/plugins
[info] Loading project definition from /home/jsuereth/projects/tmp/continuations/project
[info] Updating {file:/home/jsuereth/projects/tmp/continuations/project/}default-170815...
[info] Resolving org.scala-sbt#precompiled-2_10_1;0.12.3 ...
[info] Done updating.
[info] Set current project to default-7e1ed8 (in build file:/home/jsuereth/projects/tmp/continuations/)
> show test:compile::scalac-options
[info] Updating {file:/home/jsuereth/projects/tmp/continuations/}default-7e1ed8...
[info] Resolving org.scala-lang#scala-compiler;2.9.2 ...
[info] Done updating.
[info] List(-Xplugin:/home/jsuereth/.ivy2/cache/org.scala-lang.plugins/continuations/jars/continuations-2.9.2.jar, -Xplugin:/home/jsuereth/.ivy2/cache/org.scala-lang.plugins/continuations/jars/continuations-2.9.2.jar)
[success] Total time: 0 s, completed May 17, 2013 9:49:28 AM
> show compile:compile::scalac-options
[info] List(-Xplugin:/home/jsuereth/.ivy2/cache/org.scala-lang.plugins/continuations/jars/continuations-2.9.2.jar)
[success] Total time: 0 s, completed May 17, 2013 9:49:35 AM
> 
```

**Comment by som-snytt** [comment]
Sorry to be dense, but do you mean you expect two instances of the plugin?  Or one? I know, isn't that a dumb question?

Just clarifying before I jump in.

The legacy code to prune seems to work at first glance:

About to pick List(scala.tools.selectivecps.SelectiveCPSPlugin@3cbcef07, t6446.Ploogin@17f0d3b8, scala.tools.selectivecps.SelectiveCPSPlugin@43dbe14f, t6446.Ploogin@18a52c57, scala.tools.selectivecps.SelectiveCPSPlugin@4021065)
[loaded plugin continuations]
[disabling plugin: ploogin]
[skipping a repeated plugin: continuations]
[disabling plugin: ploogin]
[skipping a repeated plugin: continuations]
Picked List(scala.tools.selectivecps.SelectiveCPSPlugin@3cbcef07)

The bracketed output is enabled on -verbose (which is too verbose).

I haven't used sbt in years (though I would have been using the scala build...), so I'll have to refresh those dormant brain cells.  ATM, the sbt output above is actually not very meaningful to me, modulo guessing.

Maybe I'll just buy the book.

**Comment by som-snytt** [comment]
https://issues.scala-lang.org/browse/SI-7494
