### ISSUE TITLE
Fail to boot with match error with `scala-tools-releases` in `repositories`

### ISSUE THREAD

**Issue by jilen** [sbt/sbt#7572]
## steps

+ Set sbt version that not used before (esnure boot related jars not cached locally).
+ Put `scala-tools-releases` into `repositories`
+ Run sbt

## problem
[error] [launcher] scala.MatchError: scala-tools-releases (of class xsbti.Predefined)
[error] [launcher] could not retrieve sbt 1.x.x
## expectation
Boot successfully

## notes
`scala-tools-releases`  not matched [here](https://github.com/sbt/launcher/blob/ab729372bcba4febfdd290b6fbc303240a9265f0/launcher-implementation/src/main/scala/xsbt/boot/CoursierUpdate.scala#L323).
This is quite hard to point out if someone have `scala-tools-releases` in the repositories

**Comment by eed3si9n** [comment]
Scala Tools Releases (http://scala-tools.org/repo-releases) repo I don't think is operational, so if you listed it in the repositories override and the resolution fails, I think it's still within the realm of expected behavior. Maybe a more graceful degradation might be to display warning message like http vs https.

**Comment by jilen** [comment]
**Removing `scala-tools-releases` should be just fine.**

Sbt will report invalid predefined resolver alias  instead of a confusing match error
```
[error] [launcher] error during sbt launcher: java.lang.RuntimeException: Expected one of local, maven-local, maven-central, scala-tools-releases, scala-tools-snapshots, sonatype-oss-releases, sonatype-oss-snapshots, jcenter, got 'scala-tools-re'.
```

**Comment by eed3si9n** [comment]
Here's a PR for this - https://github.com/sbt/launcher/pull/104
