### ISSUE TITLE
Scala program does not receive EOF when using `sbt run`

### ISSUE THREAD

**Issue by lzm0** [sbt/sbt#7576]
When running a Scala project that uses [scala.io.StdIn](https://www.scala-lang.org/api/2.13.12/scala/io/StdIn$.html)  with `sbt run`, the program does not receive EOF and exit when `Ctrl-D` is pressed.

SBT version: 1.10.0
Scala version: 2.13.12
Shell: zsh 5.9 (x86_64-apple-darwin23.0)

## steps
1. Clone and run the demo repo.
    ```bash
    git clone https://github.com/lzm0/sbt-eof-bug.git
    cd sbt-eof-bug
    sbt run
    ```
2. The program should read characters from stdin. Press `Ctrl-D` when prompted to send an EOF.

## problem

The program should read EOF and exit.

## expectation

The program does not treat `Ctrl-D` as EOF and exit.
```zsh
% sbt -error run
Press Ctrl-D to exit:^D
```

## notes
A workaround is to use `sbt --client run`, which allows EOF to be sent correctly.
```zsh
% sbt -error --client run
[info] entering *experimental* thin client - BEEP WHIRR
[info] terminate the server with `shutdown`
> run
[info] running example.Main # Ctrl-D is pressed here
[success] Total time: 4 s, completed Jun 4, 2024, 1:29:00 PM
```

**Comment by Friendseeker** [comment]
On latest sbt head commit (Apple M1 MacBook) with zsh, the issue is not reproducible.

```
❯ sbt
[info] welcome to sbt 1.10.4-SNAPSHOT (Oracle Corporation Java 21.0.1)
[info] loading project definition from /Users/jiahuitan/sbt-eof-bug/project
[info] loading settings for project root from build.sbt ...
[info] set current project to sbt-eof-bug (in build file:/Users/jiahuitan/sbt-eof-bug/)
[info] sbt server started at local:///Users/jiahuitan/.sbt/1.0/server/ad788a8df695d7460e45/sock
[info] started sbt server
sbt:sbt-eof-bug> run
[info] running example.Main 
Press Ctrl+D to exit:[success] Total time: 2 s, completed Oct 26, 2024, 8:37:55 p.m.
```

Feel free to reopen the issue once sbt 1.10.4 is released and the issue remains reproducible on your end.
