### ISSUE TITLE
sbt whatDependsOn does not work anymore

### ISSUE THREAD

**Issue by misja-alma** [sbt/sbt#7583]
## steps

sbt --version output:
sbt version in this project:    1.6.2
sbt script version: 1.9.4

Run e.g.  `sbt "whatDependsOn org.slf4j slf4j-api 1.6.1"` in your project.
It doesn't work:

[error] Expected ID character
[error] Not a valid command: whatDependsOn
[error] Expected project ID
[error] Expected configuration
[error] Expected ':'
[error] Expected key
[error] Not a valid key: whatDependsOn (similar: sbtDependency)
[error] whatDependsOn org.slf4j slf4j-api 1.6.1
[error]

## problem

The sbt whatDependsOn task is not recognized anymore.

## expectation

I expect sbt whatDependsOn to be recognized and work according to sbt documentation, e.g. https://www.scala-sbt.org/sbt-dependency-graph/tasks/whatDependsOn.html

## notes

sbt dependencyTree still works.

**Comment by mzuehlke** [comment]
Did you add the required plugin ?
See: https://github.com/sbt/sbt-dependency-graph#usage-instructions

**Comment by misja-alma** [comment]
I haven't, because it's deprecated for sbt >= 1.4 and I'm using sbt 1.9.2: 
`DEPRECATED: This plugin has been replaced by built-in sbt plugin in sbt 1.4+, please replace your dependency on this plugin with the following statement addDependencyTreePlugin`

**Comment by misja-alma** [comment]
ah you're right, I needed to add addDependencyTreePlugin
