### ISSUE TITLE
StackOverflowError when using dependencyBrowseTree 

### ISSUE THREAD

**Issue by Krishnapro** [sbt/sbt#7599]
## steps

Using: 
sbt - 1.10.0
Java - 17.0.9
plugin - `addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.10.0-RC1")`

When I ran the command `sbt dependencyBrowseTree` then got stackOverflowError.

## problem

![image](https://github.com/user-attachments/assets/fad80f42-66d6-406f-9825-c0db2ac348df)

**Comment by mzuehlke** [comment]
For newer version sbt you just need to add:
```

addDependencyTreePlugin
```
to your `plugins.sbt` file

**Comment by eed3si9n** [comment]
Yea, hopefully that fixes it.

@Krishnapro 
Also, in the future, could you provide reproduction steps so we can reproduce your problem on _our computers_ or on GitHub Actions, like steps 1 checkout this repo, plz?

**Comment by Krishnapro** [comment]
Yey, but I already added this plugin `addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.10.0-RC1")` in `plugins.sbt`. After that when I was running the command `sbt dependencyBrowseTree`, I got the above error.
