### ISSUE TITLE
ScalaDoc errors with import renames

### ISSUE THREAD

**Issue by darkfrog26** [sbt/sbt#76]
Upgrading from 0.7.7 to 0.10.0 and everything is compiling fine, but generating the ScalaDocs for my math library is causing the build to fail.  I'm getting the output as follows:

http://paste.pocoo.org/show/420649/

It would appear this is specifically related to import renames that I'm doing to utilize org.sgine.math.Matrix4 within org.sgine.math.immutable.Matrix4 and org.sgine.math.mutable.Matrix4.  The exact same code compiles and generates fine with 0.7.7.  I've tried this with Scala 2.9.0 and 2.9.0.1 with the same result.

**Comment by darkfrog26** [comment]
After refactoring the code to utilize unique names this problem is still occurring.  At this point it would appear unrelated to the import rename, but something specifically wrong with doc generation.

**Comment by harrah** [comment]
Could be an sbt bug, but I need a reproducible test case.

**Comment by darkfrog26** [comment]
Here's a minimal project that reproduces the problem:

http://captiveimagination.com/download/sgine-math.zip

**Comment by indrajitr** [comment]
Hey Mark, I am having this problem as well :( The title is bit deceptive, it is just a scaladoc issue and doesn't have anything to do with import renames.

Looks like things work for 2.8.x but fail for 2.9.x. Little strange unless something changed in scaladoc interface in between that we are not aware of.

I would take a look when I have some time, would request re-opening it meanwhile.

**Comment by indrajitr** [comment]
This happens because of dangling `-cp` option when there are no user classpath files.

For example, in a standalone project with `libraryDependencies := Nil` there is nothing to append to `-cp`. Not sure how it works for 2.8.x series, but removing `-cp` altogether would make things tidy :)

Would submit a patch in a while.

**Comment by harrah** [comment]
Details are in #85.  This is a bug in scalac with no automatic workaround that sbt could use.  Not appending "" causes the current directory to be added to the classpath.  The problem is fixed in 2.9.1.RC2.

**Comment by indrajitr** [comment]
Aha, cool.
