### ISSUE TITLE
New resolvers are ignored after attempting to download artifacts without them

### ISSUE THREAD

**Issue by vnicolici** [sbt/sbt#760]
If you don't add the resolvers required for downloading some artifacts from the beginning, the fact that the artifacts could not be resolved seems to be cached in the ivy cache.

Then, if you add the required resolver, sbt ignores it and still complains that the artifacts cannot be resolved.

Steps to reproduce:
1. create a build file referencing an artifact that doesn't exist in the default repositories
2. run sbt update
3. add the required resolvers for that artifact
4. run sbt clean and sbt update

I would expect the artifact to be resolved at this point, but it isn't.

To fix the issue you have to delete the directories related to that artifact in the .ivy2 cache

If this is by design, I think there should be a force-update option that bypasses this limitation.

I will attach a sample project and the logs. The project uses the Play framework, I didn't try to reproduce it on a simple project.

**Comment by vnicolici** [comment]
Gist containing the project files and the logs: https://gist.github.com/vnicolici/5608248

And I forgot to mention the environment:

Windows 8
sbt 0.12.3
scala 2.10.0
play 2.1.1

**Comment by vnicolici** [comment]
Oh, and another thing, every time it reports a missing artifact, it shows that it searched only on http://repo1.maven.org/ , but in fact there were four other resolvers in my project.

This is only a cosmetic bug, but I lost a few hours thinking I defined the resolvers incorrectly and trying to fix it, when in fact they were fine. 

Finally, after running show resolvers and determining that resolvers are defined OK, I found the cache issue.

I can't tell you how many funny replacements I invented for the "Simple" from the SBT acronym while I investigated the issue.

**Comment by harrah** [comment]
The problem is that Maven Central has the metadata but not the artifacts:
http://repo1.maven.org/maven2/com/sun/jdmk/jmxtools/1.2.1/

Ivy remembers where it got the metadata and expects the artifacts to be there as well.

**Comment by harrah** [comment]
Thank you for the test case.  The issue can be reduced to just a dependency on jmx.  Another fix in 0.13 already fixed this, but this specific manifestation wasn't known.  The test case in the linked commit should keep it fixed.  Finally, this will be evaluated for a backport to 0.12.4 at the time of that release.  Thanks again for the report.
