### ISSUE TITLE
`META-INF/MANIFEST.MF` has no parent zip entry `META-INF/` when packaging to a jar.

### ISSUE THREAD

**Issue by Eyre-S** [sbt/sbt#7602]
## steps

1. Create a new project or open any project with sbt
2. Run `package` sbt task
3. Open the generated `.jar` file with `ZipFile` in java (or any zip reader that can list zip entries)
4. List the ZipFile's entries name.
## problem

You will find that this ZipFile contains a `META-INF/MANIFEST.MF` entry but no `META-INF/` entry.

This may cause some programs cannot read the `META-INF/MANIFEST.MF` or just throw errors.

## expectation

There should exists the `META-INF/` entry as the parent directory of `META-INF/MANITEST.MF` entry.

**Comment by eed3si9n** [comment]
> This may cause some programs cannot read the `META-INF/MANIFEST.MF` or just throw errors.

Could we close this issue until we find an actual evidence that this is actively causing harm, please?
