### ISSUE TITLE
The "update" or "evicted" commands are resolving to a different set of dependencies from just calling "compile" when not using coursier.

### ISSUE THREAD

**Issue by niander** [sbt/sbt#7609]
## steps

SBT version 1.10.1
Create a minimal SBT project targeting scala 2.12, Java 8.
Set `useCoursier` to false and make the only dependency be:

```scala
libraryDependencies += "com.twitter" %% "finagle-http" % "24.2.0"
```

Make sure your local ivy2 cache is empty.

## problem

Run commands `compile; show fullClasspath`. The output will show that `scala-collection-compat_2.12-2.4.4.jar` is the included artifact for this dependency.

Now, if you run `show evicted` or `show update`, a different version of `scala-collection-compat_2.12` is downloaded (if needed) and when running `show fullClasspath` again, the output will show that `scala-collection-compat_2.12-2.1.2.jar` is the used version for this dependency.

From now on, even after cleaning output with `clean`, the classpath will always include the versions `2.1.2` of `scala-collection-compat_2.12`. Only way to achieve the old behavior would be to delete the `~/.iv2` local cache.

## expectation

So, a couple of issues here:
* Just running `complie` or even just `run` will resolve to a different subset of dependencies than if you run `update` or `evicted`.
* When running `show evicted`, it says that `2.1.2` version is replacing `2.4.4`. Which seems wrong since the default conflict resolution would be the latest revision.
* It seems wrong that just because the `2.1.2` version of `scala-collection-compat_2.12` is cached in the local `~/.ivy2`, that `2.1.2` is the version included in the full classpath even after cleaning the compiled files, differently from what first happened in a clean environment where all dependencies are resolved from external resolvers.
* If `useCoursier := true`, the version `2.4.4` will always win. Even if `update` and/or `evicted` commands are never called.

**Comment by SlowBrainDude** [comment]
I think it would be helpful to publish your minimal repro project to make investigating this problem further easier.

**Comment by niander** [comment]
@SlowBrainDude here it is: https://github.com/niander/TestUpdateBug

**Comment by eed3si9n** [comment]
> ## expectation
>
> - When running show evicted, it says that 2.1.2 version is replacing 2.4.4. Which seems wrong since the default conflict resolution would be the latest revision.

I'm not too sure about this expectation. Given a conflict (having more than one version of the same module), different resolvers take different strategy, and by default Apache Ivy will try to emulate Maven, which uses nearest-wins semantics. In other words, if `C 2.4.4 -> B -> A` and `C 2.1.2 -> A`, C will resolve to C 2.1.2 on Maven.

Also in general, the notion of dependency resolution is like a black box from the point of view of sbt, and it's outsourced to either Coursier or (our fork of old) Apache Ivy, and for the most part we don't make changes to Ivy. So even though the behavior is weird that it flip-flops after hydrating the cache, I don't know how much we (sbt project) can do in here, especially given most users are on Coursier. If you want to send a PR to https://github.com/sbt/ivy I'd be happy to review it, but I'd close this as won't fix.

**Comment by niander** [comment]
@eed3si9n, thanks for the explanation. I am, however, confused by what you said: "Apache Ivy will try to emulate Maven." Because, according to their documentation, [the default resolution is latest revision](https://ant.apache.org/ivy/history/2.3.0/ivyfile/conflict.html#:~:text=If%20no%20specific%20conflict%20manager,latest%2Drevision%22%20conflict%20manager.). I can move this to https//github.com/sbt/ivy then and we can discuss there.

Now, about sbt weird flip-flop behavior. Why would that not be a bug? If I am not using Coursier, why is the compile task not generating the same full set of dependencies like when update task is invoked? One would think compile tasks depends on the update task?

**Comment by eed3si9n** [comment]
iirc Ivy creates a corresponding `ivy.xml` in the local Ivy cache so as not to re-retrieve POM each time over the network, and it uses `force=true` to _its_ dependencies, which might potentially explain the cache vs non-cache behavior?, but I think the force is meant to have some nearest-wins like effect.

**Comment by eed3si9n** [comment]
See `force="true"` in the dependencies seciton:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ivy-module version="2.0" xmlns:m="http://ant.apache.org/ivy/maven" xmlns:e="http://ant.apache.org/ivy/extra">
	<info organisation="com.github.scopt"
		module="scopt_2.12"
		revision="4.1.0"
		status="release"
		publication="20220702155951"
	>
		<license name="MIT" url="http://www.opensource.org/licenses/mit-license.php" />
		<description homepage="https://github.com/scopt/scopt">
		a command line options parsing library
		</description>
		<e:sbtTransformHash>8afde00157c3791d054e826ee4a70e1af39b3368</e:sbtTransformHash>
	</info>
	....
	<dependencies>
		<dependency org="org.scala-lang" name="scala-library" rev="2.12.16" force="true" conf="compile->compile(*),master(compile);runtime->runtime(*)"/>
		<dependency org="com.eed3si9n.verify" name="verify_2.12" rev="1.0.0" force="true" conf="test->runtime(*),master(compile)"/>
	</dependencies>
</ivy-module>
```
