### ISSUE TITLE
automatically reparse build.sbt

### ISSUE THREAD

**Issue by cbielow** [sbt/sbt#7628]
## steps

>sbt --version
sbt version in this project: 1.10.1
sbt script version: 1.10.1

***build.sbt***:
```
name := "TestProject"

version := "0.1"

scalaVersion := "3.3.1" // Change this to the desired Scala version

libraryDependencies +=
  "org.scala-lang.modules" %% "scala-parallel-collections" % "3.3.1"
```

The above config fails when trying `sbt> compile` with
```
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.scala-lang.modules:scala-parallel-collections_3:3.3.1
[error]   Not found
[error]   Not found
[error]   not found: C:\Users\bielow\.ivy2\localorg.scala-lang.modules\scala-parallel-collections_3\3.3.1\ivys\ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parallel-collections_3/3.3.1/scala-parallel-collections_3-3.3.1.pom
```

So far, so "good", since I used a non-existant package version of `scala-parallel-collections`.

## problem

However, when I edit the `build.sbt` to use another version of `scala-parallel-collections`, e.g.
```
libraryDependencies +=
  "org.scala-lang.modules" %% "scala-parallel-collections" % "1.0.4"
```
then save the build.sbt and run `compile` again in the sbt prompt, it does not use the updated build.sbt.
This is highly confusing for new users.

In the meantime I learned about `sbt reload`, but why would sbt not do this automatically?

## expectation

Check the modify date on the build.sbt file and reparse it if necessary when a `compile` command or similar is issued.

**Comment by adpi2** [comment]
Automatic reloading is not enabled by default because:
- it can be slow: it needs to recompile and reload all settings
- it can fail
- it does not work well with sbt server

However you can enable it with:
```
Global / onChangedBuildSource := ReloadOnSourceChanges
```

See the related documentation [here](https://www.scala-sbt.org/1.x/docs/Triggered-Execution.html#Build+sources).

**Comment by cbielow** [comment]
> Automatic reloading is not enabled by default because:
> 
>     * it can be slow: it needs to recompile and reload all settings
> 
>     * it can fail
> 
>     * it does not work well with sbt server
> 
> 
> However you can enable it with:
> 
> ```
> Global / onChangedBuildSource := ReloadOnSourceChanges
> ```
> 
> See the related documentation [here](https://www.scala-sbt.org/1.x/docs/Triggered-Execution.html#Build+sources).

Ok, thanks for the explanation.
This is just highly unusual for people coming from other languages and build systems, such as CMake, which would trigger automatically re-building when it detects changes to the build system.
I would argue that if someone changes the build.sbt, then they usually want a reload (why would you NOT want one?).
So the default should be reload IMHO. This is only expensive if people actually modify build.sbt; it does not cost anything to check a timestamp on the file.
Just my 50 cents...
