### ISSUE TITLE
Wrong ordering of platforms on Scala Native 0.5

### ISSUE THREAD

**Issue by adpi2** [sbt/sbt#7632]
## steps

https://index.scala-lang.org/scalameta/munit-scalacheck/artifacts/munit-scalacheck?stable-only=true

## problem

![image](https://github.com/user-attachments/assets/11974f30-5bd5-42dd-82a7-19c1b3ff4738)

## expectation

`Scala Native 0.5` should be on top of `Scala Native 0.4`

**Comment by eed3si9n** [comment]
Was this meant for Scaladex?

**Comment by adpi2** [comment]
Oh yeah sorry
