### ISSUE TITLE
Discord link is borked

### ISSUE THREAD

**Issue by grepwood** [sbt/sbt#7635]
On the bottom of https://www.scala-sbt.org/ it says there's a Discord link. "Yay", I thought. I could ask questions and receive answers in real-time, just like on good ol based IRC. However, the link https://discord.com/channels/632150470000902164/922600050989875282 is not working:
![image](https://github.com/user-attachments/assets/be9ce84d-8f01-45d4-abe5-b92d81725e22)

If the SBT Discord chat is still a thing please update the link.

**Comment by adpi2** [comment]
It's a link to the `sbt` channel in the [scala](https://discord.com/invite/scala) Discord. I tried it in a private window of my browser and it worked. Could it be that you are behind a firewall or proxy that is blocking the access?

**Comment by grepwood** [comment]
I'm not in the Scala Discord. That's the root cause. Some kind of info that this is a channel within another server would go a long way :)
