### ISSUE TITLE
Did I break CI?

### ISSUE THREAD

**Issue by SlowBrainDude** [sbt/sbt#7637]
I've just noticed:

https://github.com/sbt/sbt/actions/runs/10668225976/job/29567461450

I'm wondering as CI was green at the point this was merged. And I've checked whether my fork is up to date right before pushing the change requested in review, which was just shortly before this was merged.

Also, when you click the other tests, which are green, they contain red messages with "error".

I hope this is not related to my test implementation.

But in case it is drop me a line and I'll look more into what exactly happened in CI!

**Comment by eed3si9n** [comment]
Let me rerun the test.

**Comment by SlowBrainDude** [comment]
Thanks for taking care, @adpi2 and @eed3si9n! :+1:
