### ISSUE TITLE
Add jfxrt.jar to class path automatically for Java 7

### ISSUE THREAD

**Issue by hrj** [sbt/sbt#765]
I started playing with Java FX and found that I had to add this to my `.sbt` file:

```
unmanagedJars in Compile += Attributed.blank(file(System.getenv("JAVA_HOME") + "/jre/lib/jfxrt.jar"))
```

The catch here is that `JAVA_HOME` has to be set in the environment which is tedious.

Could this be automated? Java 6 and Java 8 don't/won't have this jar file, but Java 7 on all platforms has it.

sbt could automatically check for the presence of this file in the path it uses to find the java runtime and add it to the `unmanagedJars` list.

**Comment by ezh** [comment]
You may create your own plugin in 5 minutes. You may look at my jafafx toy at https://github.com/sbt-android-mill/sbt-application/blob/master/src/main/scala/sbt/application/javafx/JavaFX.scala. I published it under apache license :) Copy n paste if you wish and do what you want.

IMHO SBT is too fat enough already. More code contains more bugs. Better to extend it via plugin API if possible.

**Comment by hrj** [comment]
Since Java 8 is not too far away, I guess it doesn't make sense to add a Java 7 specific workaround to SBT.

Closing.
