### ISSUE TITLE
[2.x] Publish sbt plugins using platform prefix

### ISSUE THREAD

**Issue by adpi2** [sbt/sbt#7655]
In https://github.com/sbt/sbt/pull/7096 we started a transition to valid Maven patterns of sbt plugins. The code for handling backward and forward compatible resolution is quite hacky. We should clean that code in sbt 2.x and publish sbt plugins using a cross version prefix (`_sbt2` or `_sbt1.0`) as we do for other platforms, such as Scala.js or Scala Native.

As consequences:
- sbt 2.x won't be able to resolve plugins published with sbt 1.8-
- sbt 1.8- won't be able to resolve plugins published with sbt 2.x

**Comment by eed3si9n** [comment]
I think I agree with the overall spirit of this ticket, but with a minor nitpick on "`_sbt1.0`". Even with sbt 1.9.x and above, the artifact name is https://repo1.maven.org/maven2/com/github/sbt/sbt-ci-release_2.12_1.0/1.6.1/. IMO, we need to forever keep the `m.extra(...)` for sbt 1.x plugin:

| -          |                   Publish sbt 1.x plugin |                                 Publish sbt 2.x plugin |
|------------|-----------------------------------------:|-------------------------------------------------------:|
| On sbt 1.x |   `m.extra(...)`, encoded as `_2.12_1.0` |  `m.cross(binaryWith("sbt2_"))`, encoded as `_sbt2_3`  |
| On sbt 2.x | `m.extra(...)` , encoded as  `_2.12_1.0`* | `m.cross(binaryWith("sbt2_"))` , encoded as  `_sbt2_3` |

*) We can stop publishing the POM inconsistent `sbt-ci-release-1.6.1.jar` and only publish `sbt-ci-release_2.12_1.0-1.6.1.jar`, which will require sbt 1.9.x+ as you mentioned.

**Comment by eed3si9n** [comment]
https://github.com/sbt/librarymanagement/pull/437, which has landed addresses `1.0` vs `2`.

**Comment by eed3si9n** [comment]
Here's PR on sbt 1.x side - https://github.com/sbt/sbt/pull/7671

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/7679

**Comment by adpi2** [comment]
> IMO, we need to forever keep the m.extra(...) for sbt 1.x plugin

Yes that makes total sense. I went a bit too far when I wrote the issue, not remembering all the details.
