### ISSUE TITLE
Documented syntax for configuring additional Scala dependencies no longer works

### ISSUE THREAD

**Issue by bchallenor** [sbt/sbt#767]
The [documentation](http://www.scala-sbt.org/snapshot/docs/Detailed-Topics/Configuring-Scala.html) suggests you can do this:

```
libraryDependencies += "org.scala-lang" % "scala-compiler" % scalaVersion.value
```

but with 0.12.3 I get:

```
build.sbt:6: error: value value is not a member of sbt.SettingKey[String]
libraryDependencies += "org.scala-lang" % "scala-compiler" % scalaVersion.value
```

**Comment by bchallenor** [comment]
I've just noticed that this page is from the snapshot docs. Is it a new feature in 0.13?

**Comment by jsuereth** [comment]
No, that's a feature just for 0.13.0-SNAPSHOT.  Use the dropdown to migrate
your documentation page back to 0.12.3 for appropriate documentation.

**Comment by bchallenor** [comment]
Thanks. Is there a 0.12.3 equivalent to bring the value of scalaVersion into scope?

**Comment by jsuereth** [comment]
the 0.12.x equivalent is:

``` scala
libraryDependencies <+= scalaVersion apply { sv => "org.scala-lang" % "scala-compiler" % sv }
```

**Comment by bchallenor** [comment]
Thanks.
