### ISSUE TITLE
[2.x] Remove sbt 0.13 build.sbt `in` methods

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#7702]
See https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#Migrating+to+slash+syntax

We should remove `scalacOptions in (Compile, console)` notation. This was deprecated in https://eed3si9n.com/sbt-1.5.0.

See also https://eed3si9n.com/syntactic-scalafix-rule-for-unified-slash-syntax/ for semi-automated migration using Scalafix.

**Comment by adpi2** [comment]
@eed3si9n I think we can close this, since we merged https://github.com/sbt/sbt/pull/7703
