### ISSUE TITLE
Convenient way to set offline mode for SBT

### ISSUE THREAD

**Issue by jroper** [sbt/sbt#771]
Offline is typically not a project specific setting, nor is it a system specific setting that you might put in global settings, rather it's a per invocation setting.  This means it deserves a way to conveniently set it, per invocation.

Currently you can start the SBT console and say set offline := true, but it's not always possible to get to the SBT console to set that, a real example being in Play, the Play sbt-plugin has some transitive dependencies that use version ranges, which are only cached for a limited amount of time, which means when you have no internet connection, if the version range cache expires, you can't get to the SBT console unless you modify the plugins.sbt file to set offline := true, which is an undesirable workaround.

A convenient solution to this would be to have SBT define

```
offline := "true".equalsIgnoreCase(sys.props("sbt.offline"))
```

**Comment by cvogt** [comment]
+1
