### ISSUE TITLE
[2.x] Loading settings is slow

### ISSUE THREAD

**Issue by adpi2** [sbt/sbt#7711]
Loading softwaremill/sttp is 2x slower with sbt 2.x than 1.10.x. Also it consumes a lot more heap memory and use too much GC. At first glance it seems the problem is `TupleMapExtension`, which creates too many short-lived arrays.

**Comment by eed3si9n** [comment]
Maybe we need to resurrect the AList hierarchy like sbt 1.x.

**Comment by adpi2** [comment]
I have a re-implementation of `TupleMapExtension` that works like the old `AList`

**Comment by adpi2** [comment]
This was actually not the biggest issue. I've just found out that sbt 2.x creates a lot more instances of `Task`, `Info` and `Action` and it persists them in the heap. Like 5x more. I am still trying to figure out why.
