### ISSUE TITLE
[2.x] different coursier cache dir sbt 1.x and 2.x

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt#7721]
## steps

`build.sbt`

```scala
scalaVersion := "3.5.1"
```

`project/build.properties`

```
sbt.version=2.0.0-M2
```

sbt console

```
Welcome to Scala 3.5.1 (21.0.4, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
                                                                                                                                           
scala> classOf[scala.deriving.Mirror].getProtectionDomain.getCodeSource.getLocation
val res0: java.net.URL = file:/Users/kenji/.ivy2/coursier-cache/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.5.1/scala3-library_3-3.5.1.jar
```

## problem

sbt 1.x default coursier cache dir is `${HOME}/Library/Caches/Coursier/v1` in Mac OS.

but sbt 2.0.0-M2 does not use `${HOME}/Library/Caches/Coursier/v1`.

every jar files re-download by sbt 2.0.0-M2 if there are cache files in `${HOME}/Library/Caches/Coursier/v1`.

## expectation

use same coursier cache dir by default.

## notes

🤔 
https://github.com/sbt/sbt/blob/ea031a7fa0e039274f4eadb64c57a20727a1e5d7/main/src/main/scala/sbt/Defaults.scala#L3371-L3384

## workaround?

```scala
csrCacheDirectory := sbt.coursierint.LMCoursier.defaultCacheLocation
```

**Comment by eed3si9n** [comment]
This looks like a regression. The behavior should be same as sbt 1.x around here.
