### ISSUE TITLE
[2.x] `import sbt.given` and source compatibility with sbt 1.x

### ISSUE THREAD

**Issue by adpi2** [sbt/sbt#7737]
In sbt 2.0.0-M2 we translated a few `implicit def` to `given` or `Conversion`. Those new context abstractions in Scala 3 requires the explicit `import sbt.given`.

This makes it hard to cross-compile some plugins, because the `import sbt.given` is rejected by the Scala 2 compiler:
```
error] /home/piquerez/github/sbt/sbt-buildinfo/src/main/scala/sbtbuildinfo/BuildInfoPlugin.scala:5:8: object given is not a member of package sbt
[error] import sbt.given
[error]        ^
[error] one error found
```

I suggest we revert back to using `implicit def` in sbt 2.x, to fix this issue.

**Comment by adpi2** [comment]
For instance, in `sbt-buildinfo`: https://github.com/sbt/sbt-buildinfo/pull/207#discussion_r1791715267

**Comment by jtjeferreira** [comment]
Also in https://github.com/playframework/twirl/pull/840/files#diff-a2e196749d6ef985b6b6726915ccae8d35957839730761750e748a54bffeaef8R10

**Comment by adpi2** [comment]
> Also in https://github.com/playframework/twirl/pull/840/files#diff-a2e196749d6ef985b6b6726915ccae8d35957839730761750e748a54bffeaef8R10

Interesting! So it seems Scala 2.12 is lenient on `import sbt.{given, _}` but not on `sbt.given`.

That's enough to fix the issue. But it should be mentioned in the sbt 2.x migration guide.

**Comment by jtjeferreira** [comment]
> > Also in [playframework/twirl#840 (files)](https://github.com/playframework/twirl/pull/840/files#diff-a2e196749d6ef985b6b6726915ccae8d35957839730761750e748a54bffeaef8R10)
> 
> Interesting! So it seems Scala 2.12 is lenient on `import sbt.{given, _}` but not on `sbt.given`.
> 
> That's enough to fix the issue. But it should be mentioned in the sbt 2.x migration guide.

I misunderstood you then. I though you wanted to facilitate the migration/cross compilation, so we don't have to change `import sbt._` to `import sbt.{given,_}`. It was a facing this problem in some slash syntax that was failing to compile...

**Comment by adpi2** [comment]
> I misunderstood you then. I though you wanted to facilitate the migration/cross compilation, so we don't have to change import sbt._ to import sbt.{given,_}. It was a facing this problem in some slash syntax that was failing to compile...

I thought it was almost impossible to cross-compile.. But since the `given` import is the new convention in Scala 3, I think it's fine to require it when cross-compiling.

**Comment by jtjeferreira** [comment]
> > I misunderstood you then. I though you wanted to facilitate the migration/cross compilation, so we don't have to change import sbt._ to import sbt.{given,_}. It was a facing this problem in some slash syntax that was failing to compile...
> 
> I thought it was almost impossible to cross-compile.. But since the `given` import is the new convention in Scala 3, I think it's fine to require it when cross-compiling.

I am mostly still programming with scala2, so excuse me in advance if I am missing something obvious, but if we do what you suggested ("revert back to using implicit def in sbt 2.x"), wouldn't `import sbt._` be enough?

**Comment by adpi2** [comment]
> Generally, a normal wildcard selector * brings all definitions other than givens or extensions into scope whereas a given selector brings all givens (including those resulting from extensions) into scope.

> There are two main benefits arising from these rules:

> - It is made clearer where givens in scope are coming from. In particular, it is not possible to hide imported givens in a long list of regular wildcard imports.
> - It enables importing all givens without importing anything else. This is particularly important since givens can be anonymous, so the usual recourse of using named imports is not practical.

https://docs.scala-lang.org/scala3/reference/contextual/given-imports.html

**Comment by jtjeferreira** [comment]
> [docs.scala-lang.org/scala3/reference/contextual/given-imports.html](https://docs.scala-lang.org/scala3/reference/contextual/given-imports.html)

Thanks. 

> In some version after 3.1, old-style implicits accessed through a * wildcard import will give a compiler error.

In which version this happened? 3.3?

Inspired by that migration section, what do you think about sbt 2.0.x using old style implicits, and sbt 2.1.x using given?

**Comment by xuwei-k** [comment]
FYI

- https://github.com/scalameta/scalameta/issues/3981
- https://github.com/scala/scala/pull/9736
