### ISSUE TITLE
Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information) on sbt >=1.9.9

### ISSUE THREAD

**Issue by adrianlyjak** [sbt/sbt#7779]
## steps

if I just run `sbt` in a new directory if the sbt installation is 1.9.9 or greater (including 1.10.x), I get this error during startup:

```
$ sbt
Oct 18, 2024 1:29:24 PM org.jline.utils.Log logr
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
[warn] No sbt.version set in project/build.properties, base directory: /home/adrianlyjak/foo
[info] welcome to sbt 1.9.9 (Eclipse Adoptium Java 17.0.10)
[info] set current project to foo (in build file:/home/adrianlyjak/foo/)
[info] sbt server started at local:///home/adrianlyjak/.sbt/1.0/server/c5b8cd43921aa0890561/sock
[info] started sbt server
>....
```
## problem

The cli is "dumb", and does not do things for tab, arrows, etc. From what I can tell, this is some sort of bug in the newer version of jlines introduced in https://github.com/sbt/sbt/pull/7503. There's a comment that mentions it happens if you have a `test` dir on your path. https://github.com/sbt/sbt/pull/7503#issuecomment-1976921338

I don't have a `test` dir on my path. I tested on 2 separate machines (macos with zsh and ubuntu with bash). macos has a builtin `test`, and ubuntu has a `test` executable in /usr/local/bin.

## expectation

terminal should have fancy features

## notes

I thought that it might be something to do with my machine, but since its reproducible on 2 pretty different machines, seemed worth mentioning. Perhaps another upgrade of jlines might fix? The issue was closed https://github.com/jline/jline3/issues/946 and added to the 3.26.0 milestone

**Comment by Friendseeker** [comment]
> The issue was closed https://github.com/jline/jline3/issues/946 and added to the 3.26.0 milestone

JLine version is bumped into 3.27.0 in https://github.com/sbt/sbt/pull/7695

sbt is planning to release a patch version containing the above change within the next few days, which hopefully fixes the issue.

**Comment by Friendseeker** [comment]
Feel free to reopen it if in the next few days, the issue is encountered again on newest sbt release.

**Comment by adrianlyjak** [comment]
@Friendseeker aha, thanks

**Comment by adrianlyjak** [comment]
@Friendseeker I confirmed that 1.10.3 is now working 👍
