### ISSUE TITLE
sbt console HISTCONTROL=erasedups

### ISSUE THREAD

**Issue by jpswain** [sbt/sbt#778]
Would it be possible to add the similar functionality that one can enable in bash by adding this to bashrc:

```
export HISTCONTROL=erasedups
```

This means that if I execute these actions:

```
> compile
> container:start
> container:stop
> reload
> container:start
> container:stop
```

My up-arrow history, from most recent to oldest would be:

```
container:stop
container:start
reload
compile
```

the current behavior gets you (recent to oldest):

```
container:stop
container:start
reload
container:stop
container:start
compile
```

This makes it a lot more convenient to jump back to previous commands if you are starting and stopping the container a lot.

**Comment by harrah** [comment]
The request seems reasonable, but JLine 2.x is what provides the history support.  See https://github.com/jline/jline2.
