### ISSUE TITLE
sbtn "/home/runner/.cache/sbt/boot/sbtn/1.10.3/sbtn: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found"

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#7785]
## steps

Use sbt --client on ubuntu-20.04.

## problem

https://github.com/sbt/sbt/actions/runs/11422882199/job/31781389516

```bash
/home/runner/.cache/sbt/boot/sbtn/1.10.3/sbtn: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found
```

## expectation

We should probably use musl so we don't break sbt --client based on the building environment.

**Comment by Friendseeker** [comment]
Hopefully the official documentation from `GraalVM` is up to date

https://www.graalvm.org/latest/reference-manual/native-image/guides/build-static-executables/
