### ISSUE TITLE
version ranges do not works with repository override

### ISSUE THREAD

**Issue by hsn10** [sbt/sbt#779]
compiling play framework:

[info] Resolving org.avaje.ebeanorm#avaje-ebeanorm-api;3.1.1 ...

[info] Resolving org.avaje#avaje-javaparent;1.1 ...
[info] Resolving org.avaje.ebeanorm#avaje-ebeanorm-agent;[3.1,4) ...
[warn]  module not found: org.avaje.ebeanorm#avaje-ebeanorm-agent;[3.1,4)
[warn] ==== local: tried
[warn]   https://ponto.amerinoc.com:8081/content/repositories/snapshots/org/avaje/ebeanorm/avaje-ebeanorm-agent/[revision]/avaje-ebeanorm-agent-[revision].pom
[warn] ==== ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/org.avaje.ebeanorm/avaje-ebeanorm-agent/[revision]/ivys/ivy.xml
[warn] ==== sbt-plugins: tried
[warn]   http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.avaje.ebeanorm/avaje-ebeanorm-agent/[revision]/ivys/ivy.xml
[warn] ==== nexus: tried
[warn]   https://ponto.amerinoc.com:8081/content/groups/public/org/avaje/ebeanorm/avaje-ebeanorm-agent/[revision]/avaje-ebeanorm-agent-[revision].pom

.sbt/repositories
[repositories]
 local: https://ponto.amerinoc.com:8081/content/repositories/snapshots/
ivy-releases: http://repo.typesafe.com/typesafe/ivy-releases/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
 sbt-plugins: http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
 nexus: https://ponto.amerinoc.com:8081/content/groups/public/

**Comment by hsn10** [comment]
same as #752

**Comment by jsuereth** [comment]
Closing as duplicate.
