### ISSUE TITLE
Provide a non-reproducible version of `ConsistentAnalysisFormat` by default?

### ISSUE THREAD

**Issue by Friendseeker** [sbt/sbt#7790]
Currently some of Zinc's internal logic still relies on timestamp provided by `ConsistentAnalysisFormat`, which is wiped during serialization. This causes issue with invalidation of trait private API change and macros, as evidenced by some of Zinc's internal scripted tests failing when default format is switched to `ConsistentAnalysisFormat`.

While users are not mass reporting issues, should we proactively offer non-reproducible version of `ConsistentAnalysisFormat` by default and tell users to opt in when necessary? Another option is to test more and back port https://github.com/sbt/zinc/pull/1430.

**Comment by eed3si9n** [comment]
I guess we can use the non-consistent version by default in sbt 1.x series, and use the consistent version in sbt 2.x series?

**Comment by eed3si9n** [comment]
Sorry I wasn't clear. I meant making the older Protobuf binary the default for sbt 1.x if it requires timestamp etc.

**Comment by Friendseeker** [comment]
> Sorry I wasn't clear. I meant making the older Protobuf binary the default for sbt 1.x if it requires timestamp etc.
> 
> 

I see. Shall close the PR at Zinc end then.
