### ISSUE TITLE
[1.10.3] [Windows] Jansi deprecation notice emitted when opening sbt

### ISSUE THREAD

**Issue by Friendseeker** [sbt/sbt#7793]
Version: 1.10.3

```
[info] [launcher] getting org.scala-sbt sbt 1.10.3  (this may take some time)...
[info] [launcher] getting Scala 2.12.20 (for sbt)...
Oct. 21, 2024 10:48:00 A.M. org.jline.utils.Log logr
WARNING: The terminal provider jansi has been deprecated, check your configuration. This warning can be disabled by setting the system property org.jline.terminal.disableDeprecatedProviderWarning to true.
```

Here's quote from [JLine repo](https://github.com/jline/jline3)

> The [Jansi](https://github.com/fusesource/jansi) library is a library specialized in supporting ANSI sequences in terminals. Historically, the JNI methods used by JLine were provided by Jansi. In order to minimize the maintenance cost, Jansi has been merged into JLine 3.25.
> 
> This provider has been deprecated in 3.26 in favor of the JNI provider.

**Comment by eed3si9n** [comment]
This doesn't happen on my machine (macOS) using JDK 8 or JDK 21:

```scala
$ sbt
[info] welcome to sbt 1.10.3 (Azul Systems, Inc. Java 21)
...
[info] started sbt server
sbt:quux> exit
```

**Comment by Friendseeker** [comment]
> This doesn't happen on my machine (macOS) using JDK 8 or JDK 21:
> 
> ```scala
> $ sbt
> [info] welcome to sbt 1.10.3 (Azul Systems, Inc. Java 21)
> ...
> [info] started sbt server
> sbt:quux> exit
> ```

It is just Windows only then. I shall add that to issue description.

**Comment by Friendseeker** [comment]
Actually JNA is also deprecated...

> JNA
> The [JNA](https://github.com/java-native-access/jna) library aims to provide an alternative way to access native methods without requiring writing a full JNI native library. If JNA is in JLine's class loader, the provider may be used. JNA is not supported on Apple M2 architectures.
> 
> This provider has been deprecated in 3.26 in favor of the FFM provider.

So guess need to remove both and instead rely on `jline-terminal-jni`. FFM is only available for Java > 21 hence can't use it.
