### ISSUE TITLE
Problem using scala.tools.nsc.Interpreter

### ISSUE THREAD

**Issue by solowd** [sbt/sbt#78]
I'm unsure if this is an issue with SBT, or just a problem with my methods.

I'm trying to evaluate code in a full configuration. As a simple example, when I execute: 

```
        val writer = new StringWriter
        val settings = new Settings
        settings.usejavacp.value = true
        val interpreter = new Interpreter(settings, new PrintWriter(writer))
        val c = interpreter.interpret("println(4)")
        println(c+writer.toString)
```

The result printed to stdout is invariably:

```
        Error
        Failed to initialize compiler: class scala.runtime.VolatileBooleanRef not found.
        ** Note that as of 2.8 scala does not assume use of the java classpath.
        ** For the old behavior pass -usejavacp to scala, or if using a Settings
        ** object programatically, settings.usejavacp.value = true.
```

Any help would be appreciated.

**Comment by harrah** [comment]
In general, the mailing list is the best way to get help and issues should only be opened for confirmed or obvious bugs/enhancements.  In this case, the documentation needs to be improved to describe this common use case better, so it is ok.

This only helps when everything is run with one classpath and ends up in the same application class loader, like when running directly with 'java'.
```settings.usejavacp.value = true

``````

Try this instead:
```settings.embeddedDefaults[MyType]
``````

where MyType is some representative type you want on the classpath (like the current class).

**Comment by harrah** [comment]
More information in the original proposal that led to embeddedDefaults: https://gist.github.com/404272

**Comment by harrah** [comment]
Added section in https://github.com/harrah/xsbt/wiki/FAQ.
