### ISSUE TITLE
Incremental compilation is too eager

### ISSUE THREAD

**Issue by OlegYch** [sbt/sbt#782]
I have a project were an API change in one file causes recompilation of whole project.
I have no idea why this happens. All I can see is that there is only one other file in the project which can possibly be affected by this change and it does not change its API after compilation.
here is what 'last compile' tells me:

> last compile
> [debug] 
> [debug] Initial source changes: 
> [debug]     removed:Set()
> [debug]     added: Set()
> [debug]     modified: Set(InventoryProperty.scala)
> [debug] Removed products: Set()
> [debug] Modified external sources: Set()
> [debug] Modified binary dependencies: Set()
> [debug] Initial directly invalidated sources: Set(InventoryProperty.scala)
> [debug] 
> [debug] Sources indirectly invalidated by:
> [debug]     product: Set()
> [debug]     binary dep: Set()
> [debug]     external source: Set()
> [debug] All initially invalidated sources: Set(InventoryProperty.scala)
> [info] Compiling 1 Scala source to target\scala-2.10\classes...
> [debug] Running cached compiler 6a873175, interfacing (CompilerInterface) with Scala compiler version 2.10.2
> [debug] Calling Scala compiler with arguments  (CompilerInterface):
> [debug]     -encoding
> [debug]     UTF-8
> [debug]     -Yrangepos
> [debug]     -d
> [debug]     target\scala-2.10\classes
> [debug]     -bootclasspath
> [debug] Scala compilation took 0.977265111 s
> [debug] Step 2 changed sources and immdediate dependencies:
> [debug]     Set(InventoryProperty.scala, DefaultProduct.scala)
> [debug] Non-trivial strongly connected components: 
> [debug]     Set(...10 files...)
> [debug]     Set(... 3 files ...)
> [debug]     Set(...hundreds of files...)
> [debug] Recompiling all 376 sources: invalidated sources (202) exceeded 50.0% of all sources
> [info] Compiling 376 Scala sources to target\scala-2.10\classes...
> [debug] Running cached compiler 4f294ac8, interfacing (CompilerInterface) with Scala compiler version 2.10.2
> [debug] Calling Scala compiler with arguments  (CompilerInterface):
> [debug]     -encoding
> [debug]     UTF-8
> [debug]     -Yrangepos
> [debug]     -d
> [debug]     target\scala-2.10\classes
> [debug]     -bootclasspath
> [debug]     -classpath
> [debug] Scala compilation took 259.567269595 s
> [debug] Step 3 transitive dependencies:
> [debug]     Set()
> [debug] Step 3 sources from new step 2 source dependencies:
> [debug]     Set()

Using sbt 0.12.3, tried sbt 0.13-Beta2 but that issue persists.

This kills workflow and there I see no way to resolve this. I tried tracking down circular dependencies to no avail.
Please help, there is no way I can continue like this...

**Comment by OlegYch** [comment]
Hey actually in 0.13.0-Beta2 recompilation is much better. 
Tried adding a testcase to sbt but for some reason couldn't run scripted tests (they where failing to compile build definitions, although snapshot sbt was successfully resolved).
Then remembered that i already had a testcase (at https://github.com/OlegYch/sbt-test ) I guess i was trying with M1 previously..

Thanks for your work!

**Comment by harrah** [comment]
The launcher in that repository appears to be from April.  Make sure you use a recent launcher and a recent 0.13 version.  Issues with failing to find sbt classes should be fixed.  If you can at least minimize the repository to just the source files and some instructions on what steps were taken and what used to happen and what is improved, I can pull a test case out.

**Comment by jvican** [comment]
Let's close this, seems really outdated, there's no reproduction and it seems that the reported issue is fixed.
