### ISSUE TITLE
[1.x] [Windows] `dependencyBrowseTree` & `dependencyBrowseGraph` crashes

### ISSUE THREAD

**Issue by Friendseeker** [sbt/sbt#7828]
Checkout contraband repo, add `addDependencyTreePlugin` to `plugin.sbt`, open sbt shell, then type `dependencyBrowseTree`

```
sbt:contraband root> dependencyBrowseTree
[info] HTML tree written to file:/D:/Repos/contraband/library/target/tree.html
[info] HTML tree written to file:/D:/Repos/contraband/plugin/target/tree.html
[info] HTML tree written to file:/D:/Repos/contraband/target/tree.html
[info] Opening file:/D:/Repos/contraband/library/target/tree.html in browser...
[info] Opening file:/D:/Repos/contraband/target/tree.html in browser...
[info] Opening file:/D:/Repos/contraband/plugin/target/tree.html in browser...

sbt server connection closed.dencyBrowseTree 2s
  | => plugin / Compile / dependencyBrowseTree 2s
  | => library / Compile / dependencyBrowseTree 2s

```
If we manually copy the link to browser (e.g. D:/Repos/contraband/library/target/tree.html), the link works though. So it is `[info] Opening file` that failed.

**Comment by eed3si9n** [comment]
A while back I wrote a blog post on how file should be represented as URI - https://eed3si9n.com/encoding-file-path-as-URI-reference/

> Absolute paths from Windows filesystem (`C:\Documents and Settings\`): Use u3 notation `file:///C:/Documents%20and%20Settings/`
