### ISSUE TITLE
[2.x] `sbt.internal.IvyConsole` would not compile using 3.4.1+

### ISSUE THREAD

**Issue by WojciechMazur** [sbt/sbt#7831]
The issues was found when adding sbt 2.0.0-M2 to Scala 3 Open Community Build. 

The snippet would fail to compile after upgrading to 3.4.1 or later. Initially I wanted to report it as a bug in the compiler, but I believe it works as expected and uncovers possible bug in sbt implementation.

https://github.com/sbt/sbt/blob/ea031a7fa0e039274f4eadb64c57a20727a1e5d7/main/src/main/scala/sbt/internal/IvyConsole.scala#L55-L59

I've prepared a full minimization of the problem: 
```scala

type Classpath = Seq[Attributed[HashedVirtualFileRef]]

object Append:
  trait Values[A1, -A2]
  trait Sequence[A1, -A2] extends Values[A1, A2]

  given appendSeq[T, V <: T]: Sequence[Seq[T], Seq[V]] = ???
  given appendSeqImplicit[A1, V](using ev: Conversion[V, A1]): Sequence[Seq[A1], Seq[V]] = ???
  given Sequence[Classpath, Seq[HashedVirtualFileRef]] = ???

trait Attributed[A1]
object Attributed:
  def blankSeq[T](v: Seq[T]): Seq[Attributed[T]] = ???
trait HashedVirtualFileRef
trait VirtualFile extends HashedVirtualFileRef
trait Setting[A1]:
  final def append[A2](vs: A2)(using Append.Values[A1, A2]): Setting[A1] = ???

object Test {
  val classpath: Setting[Seq[Attributed[HashedVirtualFileRef]]] = ???
  val works = classpath.append(Seq.empty[Attributed[HashedVirtualFileRef]])
  val `fails since 3.4.1` = classpath.append{
    Attributed.blankSeq(Seq.empty[VirtualFile])
  }
  // val failsAlways = classpath.append(Seq.empty[Attributed[VirtualFile]])
}
```

Before [scala/scala3/#19096](https://github.com/scala/scala3/pull/19096) both cases would use `Append.appendSeq` however it was an incorrect behaviour - `Attributed[T]` is invariant, thus `Attributed[VirtualFile]` is not a subtype of `Attributed[HashedVirtualFileRef]`. The mentioned PR was fixed checking for this condition, thus this implicit can no longer be used. 

`given Sequence[Classpath, Seq[HashedVirtualFileRef]]` is not chosen because it's not using `Attributed` wraper type. Finally the `appendSeqImplicit` cannot be used because there is no defined `Conversion[Seq[Attributed[VirtualFile]], Seq[Attributed[HashedVirtualFileRef]]]`

Possible workarounds: 
1. Replace `Attributed[T]` with covariant `Attributed[+T]` however it might affect other code I'm not aware of yet 
2. Skip `Attributed.blankSeq(u)` conversion, pass `u` directly - the most straightforward solution 
3. Define a dedicated `Append.Values` to handle `Attributed[Classpath, Seq[Attributed[VirtualFile]]`

**Comment by eed3si9n** [comment]
@WojciechMazur Thanks a lot for the detailed explanation! Highly appreciated.

**Comment by eed3si9n** [comment]
Here's a PR to address this - https://github.com/sbt/sbt/pull/7834

**Comment by Friendseeker** [comment]
Fixed by https://github.com/sbt/sbt/pull/7837
