### ISSUE TITLE
Java annotation processors not working with `usePipelining := true`

### ISSUE THREAD

**Issue by guersam** [sbt/sbt#7847]
## steps

1. Clone [reproducer](https://github.com/guersam/sbt-pipeline-java-annotations-reproducer)
2. Run `sbt clean compile app/run`

Reproducer has:
- Scala 3.5.2
- Multi-project setup (lib, app)
- lib: Lombok with `@Data` annotation
- app: Uses generated getters/setters
- `usePipelining := true` in both projects

## problem

Java annotation processors (Lombok) appear to be ignored when `usePipelining := true` in a multi-project setup. The generated accessors are not available in the dependent project.

## expectation

Lombok should generate accessor methods (get/set) in the `lib` project, which should be available to use in the `app` project, even with pipelining enabled.

## notes

I've completely separated my Java and Scala subprojects following the explanation in #7546, but the build still fails due to this issue. I'm not sure if it's just a problem about annotation processors or something broader like passing `javacOptions` yet.

**Comment by Friendseeker** [comment]
The way pipelining works (correct me if I am wrong) is that Scala compiler generates a jar containing the public signature of Scala & Java source files (which is then used for downstream compilation). Since Scala compiler does not know the meaning behind lombok annotations, the generated jar won't contain the signatures of lombok generated setter/getters.

Since this is a fundamental limitation of pipelining, I think the only option is to turn off pipelining for the java subproject (I don't know whether sbt supports conditionally turning off pipelining for some submodules, hopefully it does, if not I think we can add it).

**Comment by guersam** [comment]
@Friendseeker Thanks for the explanation. Setting `usePipelining := false` for Java subproject doesn't make it work yet.

**Comment by Friendseeker** [comment]
> @Friendseeker Thanks for the explanation. Setting `usePipelining := false` for Java subproject doesn't make it work yet.

Emm... Probably a regression. This use case should be supported. Shall look into it more.

> sbt 1.4.0 adds experimental incremental build pipelining. To enable build pipelining for the build:
> 
> ThisBuild / usePipelining := true
> To opt-out of creating an early output for some of the subprojects:
> 
> exportPipelining := false

(c.c. https://www.scala-sbt.org/1.x/docs/sbt-1.4-Release-Notes.html)

Mixed Scala & Java project are very common, and for Java annotation processing is very common, hence I do feel this is a must fix issue for pipelining.

**Comment by guersam** [comment]
Didn't know there's `exportPipelining := false`. I'll try this. Thanks!

BTW, it was difficult to find it to me because the most other sbt settings can be opted-out using the same key.

**EDIT**: It works, thanks again! I just noticed it's a pair of `{use,export}Pipelining` instead of just `pipelining` because it's about different relationships with upstream and downstream. Zinc doesn't distinguish between them, but sbt [does](https://github.com/sbt/sbt/blob/94f239f4ae590dbae185a5950eee90e88de79048/main/src/main/scala/sbt/internal/ClasspathImpl.scala#L36).
