### ISSUE TITLE
compilation error on re-compilation (possibly bug in presentation compiler or incremental compilation)

### ISSUE THREAD

**Issue by cvogt** [sbt/sbt#786]
I run into this problem in our Slick example project.

The condensed code sample at https://github.com/cvogt/sbt-bug compiles fine at first. The problem occurs when dao.scala is re-compiled (e.g. because it has changed) and tables.scala is not recompiled.

May be a bug in incremental compilation or in the presentation compiler.
@harrah @dotta @dragos @skyluc

Reproduce steps

first compile

<pre>
> compile
[info] Updating {file:/Users/chris/stuff/playground/sbt-bug/}sbt-bug...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 2 Scala sources to /Users/chris/stuff/playground/sbt-bug/target/scala-2.10/classes...
[success] Total time: 4 s, completed Jun 19, 2013 1:20:58 AM
</pre>

add empty newline to dao.scala

<pre>
> compile
[info] Compiling 1 Scala source to /Users/chris/stuff/playground/sbt-bug/target/scala-2.10/classes...
[error] /Users/chris/stuff/playground/sbt-bug/src/main/scala/dao.scala:9: overriding type TableType in class DAOBase with bounds &lt;: models.Config.driver.simple.Table[models.Site];
[error]  type TableType has incompatible type
[error]     type TableType = tables.Sites
[error]          ^
[error] one error found
[error] (compile:compile) Compilation failed
[error] Total time: 1 s, completed Jun 19, 2013 1:21:03 AM
</pre>

add empty newline to tables.scala

<pre>
> compile
[info] Compiling 2 Scala sources to /Users/chris/stuff/playground/sbt-bug/target/scala-2.10/classes...
[success] Total time: 1 s, completed Jun 19, 2013 1:21:15 AM
</pre>

**Comment by cvogt** [comment]
the referenced repository uses sbt-1.3.0-Beta2, scala 2.10.2 and slick 1.0.1. The problem also exists with sbt-1.2.x, Scala 2.10.x and slick 1.0.0.

**Comment by dotta** [comment]
@cvogt This bug is fun :) This is not a presentation compiler bug. I guess @harrah or @gkossakowski will tell us more about it, but a weird interaction between incremental compiler and scalac seem plausible.

**Comment by harrah** [comment]
Thanks for the test case.  This is a bug in scalac's separate compilation, which can be verified by running scalac directly, first on both sources and then just on dao.scala.  To help with this, you can see the approximate command line used by sbt with `export compile`.  (The -bootclasspath can usually be dropped from that output.)

**Comment by cvogt** [comment]
I created a Scala ticket https://issues.scala-lang.org/browse/SI-7596.

Workaround for SBT and Play! users: use `clean` before re-compiling.
