### ISSUE TITLE
Consider adding the javac call to the sbt output when debug logging is set

### ISSUE THREAD

**Issue by felher** [sbt/sbt#7883]
Currently, when you enable debug logging via something like
```
set logLevel := Level.Debug
```

you get some nice output on how the _scala compiler_ is invoked. Something like this:
```
[debug] [zinc] The Scala compiler is invoked with:
[debug] 	-deprecation
[debug] 	-encoding
[debug] 	UTF-8
[debug] 	-feature
[debug] 	-language:existentials
[debug] 	-language:higherKinds
[debug] 	-language:implicitConversions
[debug] 	-unchecked
[debug] 	-Xfatal-warnings
[debug] 	-Yno-adapted-args
[debug] 	-Ywarn-dead-code
[debug] 	-Ywarn-numeric-widen
[debug] 	-Ywarn-value-discard
[debug] 	-Ypartial-unification
```

What you don't get is some output on how the _java compiler_ was invoked for projects that also have java files. Adding this might be useful to debug problems in mixed projects.

**Comment by SethTisue** [comment]
I’ve wanted this myself several times, and also wanted it several times when helping someone else troubleshoot their build
