### ISSUE TITLE
Chrome trace format broken

### ISSUE THREAD

**Issue by JulienBenoitSonos** [sbt/sbt#7884]
## steps

```
sbt --traces version
```

## problem

Output Chrome format trace is missing double quotes around thread name.
This regression was introduced recently in this commit: https://github.com/sbt/sbt/commit/0b34b6b4065e92e3d556703ec2960070406e20fa

## expectation

Thread name should be wrapped in double quotes, since this is a string and not a number anymore

**Comment by eed3si9n** [comment]
CC @Friendseeker

**Comment by xuwei-k** [comment]
- FYI https://github.com/scala/scala3/pull/21872
