### ISSUE TITLE
When project dependency includes package in 'Test' scope it is visible in main application code.

### ISSUE THREAD

**Issue by kpbochenek** [sbt/sbt#7885]
## steps

call `sbt new scala/hello-world.g8`
in Main.scala add line `new groovy.util.Node(null, null)`
compilation will fail because groovy is not in dependencies

in build.sbt add line: `libraryDependencies += "cz.jirutka.rsql" % "rsql-parser" % "2.1.0"`

compilation succeeds. `sbt dependencyTree` shows groovy on dependency list.

but according to package definition: https://mvnrepository.com/artifact/cz.jirutka.rsql/rsql-parser/2.1.0
groovy is available only as `Test` dependency.

Doing the same experiment with `maven` after adding `rsql-parser` as dependency compilation still fails.

This is not expected behaviour correct?
If it is expected, is there a way to not have `Test` dependencies in main scope?

**Comment by jtjeferreira** [comment]
The pom of `rsql-parser` has:

```xml
<parent>
  <groupId>cz.jirutka.maven</groupId>
  <artifactId>groovy-parent</artifactId>
  <version>1.2.0</version>
</parent>
```

And looking at https://mvnrepository.com/artifact/cz.jirutka.maven/groovy-parent/1.2.0 we can see a dependency on `org.codehaus.groovy:groovy`...

> If it is expected, is there a way to not have Test dependencies in main scope?

As a workaround you can use [exclude](https://www.scala-sbt.org/1.x/docs/Library-Management.html#Exclude+Transitive+Dependencies)

**Comment by kpbochenek** [comment]
Thanks for explanation don't know maven that well but it makes sense it comes from parent.pom 👍 

On one side it makes perfect sense that this dependency should be then visible in my scope because it must be on classpath for `rsql-parser` to work anyway.
If it was for maven, I would say they just have bug in their build tool, but also checked gradle and similarly `groovy` not visible.

Will try ask on their community why they have this behaviour.

**Comment by eed3si9n** [comment]
https://repo1.maven.org/maven2/cz/jirutka/maven/groovy-parent/1.2.0/groovy-parent-1.2.0.pom

```xml
<dependencies>
  <dependency>
    <groupId>org.codehaus.groovy</groupId>
    <artifactId>groovy</artifactId>
  </dependency>
</dependencies>
<dependencyManagement>
  <dependencies>
   ....
  </dependencies>
</dependencyManagement>
```

Wow. Normally a parent POM would contain `dependencyManagement > dependencies` section to centralize the version number management across multiple modules (aka bill of materials or BOM), but this one seems to contain an actual dependency.
