### ISSUE TITLE
Provide Option for Colorized Output w/o Cursor Movement Sequences

### ISSUE THREAD

**Issue by RSchulz** [sbt/sbt#789]
The refinement to SBT's output while updating that appeared in 0.12.1 and caused output lines for dependencies not requiring update to be overwritten was very welcome. Unfortunately, the Jenkins ANSI Color plug-in [1] does not handle the cursor movement and screen editing sequences SBT uses to produce this effect. The result is messy console pages in Jenkins. SBT currently allows only one option: both color sequences and cursor movement sequences or neither.

It would be very nice to be able to get the color without the cursor movement sequences.

[1] https://wiki.jenkins-ci.org/display/JENKINS/AnsiColor+Plugin

**Comment by harrah** [comment]
Yes, good point.  The ANSI color plugin should probably be patched to filter unsupported escape codes.  It is straightforward: escape codes start with ESC and end at the first character in the range of `@` to `~`.

**Comment by eed3si9n** [comment]
Hopefully this was already fixed in https://github.com/sbt/sbt/pull/3672
