### ISSUE TITLE
[1.x] [Linux] Enter key is not recognized by `sbt new`

### ISSUE THREAD

**Issue by Friendseeker** [sbt/sbt#7898]
## steps

Run `sbt new`, press enter.

## problem

Enter key is not recognized, ^M is added to the console.

## expectation

Enter key should be processed correctly.

## notes

Quote from Scala Discord

> oh, sbt new also doesn't work. It gets stuck in the name part because it can't process my enter key (when pressing enter, it adds ^M in the console) - RandomName

> Can confirm. I use WSL with Ubuntu 24 for new work. Enter is broken but ^J is ok. Maybe we've been too spoiled by a dedicated physical key. Think of all the amazing features that could be unleashed by freeing up Enter and Caps Lock. The latter could have special function in Caprese mode. - som-snytt

(c.c. https://discord.com/channels/632150470000902164/922600050989875282/1307120671272337420)

I failed to reproduce this issue on Mac OS & Windows. It seems to be Linux only issue.

Workaround, as mentioned by som-snytt, is to use ^J instead of enter

**Comment by mkurz** [comment]
Works for me, I am using Arch Linux.

**Comment by Friendseeker** [comment]
> Works for me, I am using Arch Linux.

Thanks for the information.

Maybe this issue is also fixed by recent sbt releases?

I shall try to see if I can reproduce the issue on WSL Ubuntu 24. If not I suppose we can safely close the issue.

**Comment by mkurz** [comment]
I just tested with Java 8, 11, 17, 21 with latest sbt 1.0.5 installed. Everything works.
I tried just running `sbt new` in bash.
And also `sbt` and then `new` in interactive mode.
All good for me.

**Comment by Friendseeker** [comment]
> I just tested with Java 8, 11, 17, 21 with latest sbt 1.0.5 installed. Everything works. I tried just running `sbt new` in bash. And also `sbt` and then `new` in interactive mode. All good for me.

Matthias, thanks for your hard work testing all the combinations!

I also cannot reproduce the issue with WSL Ubuntu 24. We can safely close the issue then.

![image](https://github.com/user-attachments/assets/d077b679-5fa2-49c0-9bb4-fc7955e679a6)

**Comment by Friendseeker** [comment]
FYI https://askubuntu.com/questions/441744/pressing-enter-produces-m-instead-of-a-newline

Crossposted from https://discord.com/channels/632150470000902164/922600050989875282/1308579117502955542
