### ISSUE TITLE
Tests fail because of mkdirs()

### ISSUE THREAD

**Issue by scroyston** [sbt/sbt#79]
java's java.io.File mkdirs()  has a race condition see:
http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=4742723

or

http://stackoverflow.com/questions/5189534/how-to-use-mkdirs-in-a-thread-safe-manner-in-java

When running parallel tests, after a clean, I occasionally get:
Could not run test org.Foo: java.lang.RuntimeException: Could not create directory /foo/bar/myproject/target/streams/test/test/is-module=true name=org.Foo: file exists and is not a directory.

IO.scala should probably have a synchronized mkdirs or something similar.

**Comment by harrah** [comment]
Reading that bug report, it doesn't seem like this error message corresponds to that problem.  Doesn't it seem more like sbt is trying to create a file and directory with the same name?  Anyway, do you want to try the naive lock to see if it goes away?

**Comment by scroyston** [comment]
I did the following, and it went away:

```
diff --git a/util/io/IO.scala b/util/io/IO.scala
index d8dc895..15ba866 100644
--- a/util/io/IO.scala
+++ b/util/io/IO.scala
@@ -86,10 +86,13 @@ object IO
        def createDirectory(dir: File): Unit =
        {
                def failBase = "Could not create directory " + dir
-               if(dir.isDirectory || dir.mkdirs())
+         var tryCount = 0
+         while (!dir.exists && !dir.mkdirs() && tryCount < 100) { tryCount += 1 }
+               if(dir.isDirectory)
                        ()
-               else if(dir.exists)
+               else if(dir.exists) {
                        error(failBase + ": file exists and is not a directory.")
+               }
                else
                        error(failBase)
        }
```

**Comment by harrah** [comment]
Sounds like a candidate for a pull request to me.

**Comment by harrah** [comment]
Thanks!

**Comment by lambdaknight** [comment]
This bug was still happening for me.  I upped the upper limit for tryCount to 10000 and it worked.  Though, it seems like a bad solution to just continue upping that number.

EDIT: This was using sbt launcher version 0.11.1-20111026-052021.
