### ISSUE TITLE
Override dependency of ProjectRef

### ISSUE THREAD

**Issue by mwisnicki** [sbt/sbt#7902]
I would like ability to override dependencies of `ProjectRef`, ideally even by replacing libraryDependency with another project/ProjectRef.

This is essentially https://github.com/sbt/sbt/discussions/7578. I looked at ProjectRef class and it only has few methods so it looks like it's not possible.

Use case:

```scala
lazy val root = (project in file("."))
  .aggregate(libFork, app)

// cannot use project() because both directories contain standalone projects with their own /project dirs.

lazy val libFork = ProjectRef("lib")

lazy val app = ProjectRef(file("app"), "root")
	.overrideDependency(("com.foo" % "lib") -> libFork)


```

**Comment by eed3si9n** [comment]
This sounds like what you want is https://lightbend-labs.github.io/dbuild/0.9.20/index.html. I think is out of scope for sbt.
