### ISSUE TITLE
Enhanced repository override

### ISSUE THREAD

**Issue by hsn10** [sbt/sbt#791]
I propose aditions to ~/.sbt/repositories. Adding repository type by appending  # to url.

[repositories]
 local: https://ponto.com:8081/content/repositories/snapshots/#maven
 ivy-releases: https://ponto.com:8081/content/groups/sbt/#sbt
 nexus: https://ponto.com:8081/content/groups/public/#maven
 ivy: https://ponto.com:8081/content/groups/public/#ivy

tags: #maven - maven repository. No ivy specific files will be published
        #sbt - ivy repo with #sbt layout
        #ivy - maven repo with additional ivy files

**Comment by jsuereth** [comment]
Just a note:

Right now if you don't specify a "layout" in the [repositories] file, then sbt treats it as a maven repository.   Perhaps we use the "#sbt" and "#ivy" style syntax to denote a default layout for ivy repositories?

**Comment by harrah** [comment]
It is unnecessary to make it a hack on the URL syntax here.  A pull request with a properly extended syntax is welcome, though.

**Comment by hsn10** [comment]
if you do not specify layout them maven layout is used, but ivy files are uploaded making our repository manager to complain.

**Comment by harrah** [comment]
Repository overrides do not control publishing.  The repository to publish to is defined by the `publishTo` setting.

**Comment by hsn10** [comment]
of course they do, try override local

**Comment by harrah** [comment]
That relies on undocumented internal implementation details that are subject to change.  Repository overrides are for the repositories to retrieve from, not to publish to.  The issue that should be fixed is then to disallow overriding the local repository by coincidence.

**Comment by hsn10** [comment]
repository override for deployment is basic requirement for running build tool from CI server. Best if you can do it from command line.

**Comment by jsuereth** [comment]
Not sure I understand how that works.  e.g. in our builds we configure publishTo for the CI, not ourselves.

**Comment by hsn10** [comment]
3rd party projects comes with their own publishTo settings. Usually to their own repo or sonatype. Its needed for CI integration to override destination without need to modify original source. Maven can do it from commandline which is best for CI server.

**Comment by hsn10** [comment]
currently i am using override local in ~/.sbt/repositories and running publish-local task

**Comment by eed3si9n** [comment]
Closing this since we won't likely implement it.
