### ISSUE TITLE
dependencyBrowseTree is locking up browser on typing into search input

### ISSUE THREAD

**Issue by mwisnicki** [sbt/sbt#7935]
## steps

Run `dependencyBrowseTree` on moderately complex project:
```
% sbt -version
sbt version in this project:    1.10.1
sbt script version: 1.6.2

% sbt svc/Test/dependencyTree |wc -l                                   
  325662

sbt svc/Test/dependencyBrowseTree
```

## problem

Typing letter into search box freezes Chrome browser for few minutes on latest M3 MacBook Pro

## expectation

Not freezing

**Comment by eed3si9n** [comment]
I don't think we can control if Chrome is going to freeze or not. dependecyGraph or dependencyBrowseTree is a utility to debug dependency, but it's not a magic wand to solve all the large scale issue. I suggest looking at the full output of `updateFull` or something if you need to analyze a large project.
