### ISSUE TITLE
sbt --script-version asks to continue (on alpine)

### ISSUE THREAD

**Issue by francisdb** [sbt/sbt#7942]
Found this issue while working on https://github.com/sbt/docker-sbt/pull/313

## steps

```
sbt  --script-version
```

or

```
sbt  --version
```

## problem

```
[warn] Neither build.sbt nor a 'project' directory in the current directory: /root
c) continue
q) quit
```

## expectation

I would expect this to not request input, or at least have a flag to continue

## notes

The bash version does not ignore the --script-version command
https://github.com/sbt/sbt/blob/f61100fe877c03861e3e01814c30da8e2f8fe0e8/sbt#L624-L625

The bat version does ignore the version
https://github.com/sbt/sbt/blob/f61100fe877c03861e3e01814c30da8e2f8fe0e8/launcher-package/src/universal/bin/sbt.bat#L529-L532

Strangely I can't reproduce this on macOS without calling bash directly?

```
➜  test bash /Users/me/.sdkman/candidates/sbt/current/bin/sbt --script-version
1.10.1
➜  test bash sbt --script-version
[warn] Neither build.sbt nor a 'project' directory in the current directory: /Users/me/test
c) continue
q) quit
```

**Comment by eed3si9n** [comment]
@francisdb Thanks for the report!

**Comment by Friendseeker** [comment]
```
jerrytan@DESKTOP-6SUJJE2:~$ sbt --version
sbt version in this project: 1.10.4
sbt script version: 1.10.4
jerrytan@DESKTOP-6SUJJE2:~$ sbt --script-version
1.10.4
jerrytan@DESKTOP-6SUJJE2:~$ echo $0
-bash
```

Not reproducible on Ubuntu 24.04.1 LTS. I wonder if this is shell related, Google Search suggests that alpine uses `ash` instead of bash as default shell?

**Comment by francisdb** [comment]
Recently came across this page below. Applying that might be a good idea?

https://clig.dev/#arguments-and-flags

> Never require a prompt. Always provide a way of passing input with flags or arguments. If stdin is not an interactive terminal, skip prompting and just require those flags/args.

**Comment by eed3si9n** [comment]
Somewhat related to this is https://github.com/sbt/sbt/issues/7955 / https://github.com/sbt/sbt/issues/2123, where we are asked to detect if we're in a non-sbt directory. `--script-version` is somewhat unique but normally `sbt` without any command invokes the sbt shell, so if we want to prevent user from entering into a session without first having `build.sbt`, we probably should exit rather than prompt and potentially block.

**Comment by francisdb** [comment]
This popped up because I just wanted to do a sanity check and log the sbt version during the docker build.

**Comment by eed3si9n** [comment]
Here's a PR for this - https://github.com/sbt/sbt/pull/7966

**Comment by francisdb** [comment]
Confirming that the original issue is fixed 👍
