### ISSUE TITLE
Should we move giter8 to sbt organization?

### ISSUE THREAD

**Issue by tgodzik** [sbt/sbt#7943]
Not sure if it's been raised before or what is the status, but it looks like https://github.com/foundweekends/giter8/issues has been left on the sidelines and it's actually an integral part of sbt.

I was prompted by https://github.com/coursier/coursier/issues/3045#issuecomment-2536205162

It looks like there was an update to slf4j in https://github.com/foundweekends/giter8/pull/899 and I think that would at least get rid of that warning, but no one was really available to merge that.

I could at least help with some smaller maintenance, but maybe it would also be good to move it to sbt org and have more people being able to merge things?

**Comment by eed3si9n** [comment]
I'm responsible for the current state of Giter8 showing some seams, but I don't know if moving to sbt org changes the situation much.

1. `sbt new` is a template resolver (https://www.scala-sbt.org/1.x/docs/sbt-new-and-Templates.html), so technically it's not limited to Giter8 templates.
2. running `sbt new` without parameter now shows `.local` templates built into sbt, which sbt project can keep it up to date.
3. foundweekends organization is managed by me and @xuwei-k, so I don't know if moving the project to sbt organization alone changes the situation significantly, just like many sbt plugins don't get maintained if people maintain them. in general, sbt project already has a wide range of projects including Zinc, so Giter8 just hasn't been on my radar.
4. I'd be happy to add more maintainers to Giter8 repo, but I've been careful not to add totally random person and end up introducing a "supply-chain" vulnerability intentionally or inadvertently. If you'd like to join the project to occasionally maintain it that would be awesome.
5. https://github.com/foundweekends/giter8/pull/899 changes the slf4j-simple version used for testing, so I don't know if bumping that is going to fix the unwanted slf4j warnings.

**Comment by tgodzik** [comment]
> I'd be happy to add more maintainers to Giter8 repo, but I've been careful not to add totally random person and end up introducing a "supply-chain" vulnerability intentionally or inadvertently. If you'd like to join the project to occasionally maintain it that would be awesome.

I would be happy to help whenever needed. We use it in Metals so it might make sense to make sure it works well. We haven't had any big issues though.

> https://github.com/foundweekends/giter8/pull/899 changes the slf4j-simple version used for testing, so I don't know if bumping that is going to fix the unwanted slf4j warnings.

Ach, I didn't look properly, but I see you looked into that already. Thanks!

**Comment by eed3si9n** [comment]
@tgodzik @adpi2 Added you both to https://github.com/orgs/foundweekends/teams/committers team.
