### ISSUE TITLE
Make link to source file position on warnings in sbt

### ISSUE THREAD

**Issue by goshacodes** [sbt/sbt#7944]
Hi, not sure if this is sbt issue and not compiler issue, but still trying here first

## build.sbt

```scala
lazy val root = (project in file("."))
  .settings(
    name := "sbt-test2",
    scalaVersion := "3.4.2",
    scalacOptions += "-Wunused:imports",
  )
```

## code

```scala
import scala.math.BigDecimal

object Foo {

}
```

## actual result

<img width="843" alt="image" src="https://github.com/user-attachments/assets/fec6a711-63ce-44f4-84ce-440caed72d75" />

## expected
I can click on **Foo** in warning and get to source file where import is deprecated like I can click on BigDecimal

**Comment by eed3si9n** [comment]
> I can click on Foo in warning and get to source file where import is deprecated like I can click on BigDecimal

Assuming you're using IntelliJ, the ability to link to the file path is a functionality of the terminal program.

In general, when you integrate with an IDE like IntelliJ or Metals, compiler and sbt can send the editor the location of warnings in a structural data, and editors should have the UI to display them, at least in theory. [IDE Integration](https://www.scala-sbt.org/1.x/docs/IDE.html) page used to document the setup, but I'm not sure if they still work with the latest versions.

Using Metals, for example, I can type `compile`, it sent the compiler warning to PROBLEMS tab, where I can click open the file.
<img width="615" alt="metals2024" src="https://github.com/user-attachments/assets/f22807b4-1f56-4d0d-9be6-e7f3545dedb0" />

**Comment by goshacodes** [comment]
Ok, thank you for answer!
