### ISSUE TITLE
sbt 1.10.6: Performance regression of update tasks

### ISSUE THREAD

**Issue by xerial** [sbt/sbt#7945]
## steps

In sbt 1.10.5:
```bash
$ gh repo clone wvlet/wvlet
$ cd wvlet
# Edit project/build.properties to use sbt 1.10.5
$ ./sbt 
sbt:wvlet> runner/update
[success] Total time: 1 s, completed Dec 13, 2024, 11:08:53 AM
```
In sbt 1.10.6:
```
# Edit project/build.properties to use sbt 1.10.6
sbt:wvlet> runner/update
[success] Total time: 59 s, completed Dec 13, 2024, 11:12:14 AM
-- The second run still takes longer time than sbt 1.10.5
sbt:wvlet> runner/update
[success] Total time: 6 s, completed Dec 13, 2024, 11:13:36 AM
```

## problem

Resolving some of the Java dependencies (Trino -> Apache Hadoop related dependencies?) in this build.sbt takes quite a long time. It was 1 second in sbt 1.10.5, but sbt 1.10.6 requires almost 1 minute:
https://github.com/wvlet/wvlet/blob/2987497fbc906149bb77c2a77d600b7f6270e2e9/build.sbt#L338-L355

Even after the first update run, there is still significant overhead. 

## expectation

As sbt update tasks always happen before recompilation, this step needs to be faster, at least after the first cold run.

**Comment by xerial** [comment]
I think it's related to recent changes around coursier cc: @alexarchambault

**Comment by eed3si9n** [comment]
Thanks for the report. Could you open an issue on coursier/coursier as well please, since as you pointed out, likely the change is in the upstream. Thanks!

**Comment by xerial** [comment]
Reported this problem to Coursier as well https://github.com/coursier/coursier/issues/3190

**Comment by Friendseeker** [comment]
In sbt, should we add an issue label for very serious issue (but not as serious as `priority/blocker`)? Maybe something like `P1`, `P2` etc?

**Comment by eed3si9n** [comment]
@Friendseeker Prioritization (what to work on next) isn't necessarily the same as severity (how serious/impactful the bug is). Unless it's a security issue, I don't always prioritize serious bugs.

1. If we want to flag something to be important maybe we can use "help wanted"?
2. For general mix of what-to-work-on, I prefer using GitHub milestones like https://github.com/sbt/sbt/milestone/101 if someone wants to take it on

**Comment by SethTisue** [comment]
> If we want to flag something to be important maybe we can use "help wanted"?

That's basically what we do in scala/bug (the Scala 2 bug tracker), fwiw. Either it's milestoned for an upcoming release or it's not (and the vast majority of open tickets aren't), and if it's not milestoned, then "help wanted" is an indicator that maintainers would be especially pleased if a volunteer appeared.

Scala 3 has a more elaborate system, but they also have an actual project manager tending to that system.

**Comment by Friendseeker** [comment]
On track to be fixed by https://github.com/coursier/coursier/pull/3193?

Shall close the issue once https://github.com/coursier/coursier/pull/3193 is merged

**Comment by mkurz** [comment]
> Shall close the issue once [coursier/coursier@7b0f09d](https://github.com/coursier/coursier/commit/7b0f09d6db85b619418d3bccccdbd6fceb91a0e1) is merged

- https://github.com/coursier/coursier/pull/3193

**Comment by eed3si9n** [comment]
FYI - I am considering to **turn off** the BOM-respecting resolution by default, and allow user to opt-in for now - https://github.com/coursier/sbt-coursier/pull/545. i.e. pass in `Some(false)` at the sbt/sbt level.

**Comment by SethTisue** [comment]
That sounds like a good stability-focused change for now, with the opportunity to make it the default again later.

**Comment by alexarchambault** [comment]
> FYI - I am considering to **turn off** the BOM-respecting resolution by default, and allow user to opt-in for now - [coursier/sbt-coursier#545](https://github.com/coursier/sbt-coursier/pull/545). i.e. pass in `Some(false)` at the sbt/sbt level.

I'm not sure it's a good idea. The results with that option are actually more correct than those without. The perf regression should go away in the next coursier release, thanks to https://github.com/coursier/coursier/pull/3193.

A diff between results obtained with (`cs resolve io.trino:trino-hive:467`) and without the option (`cs resolve io.trino:trino-hive:467 --enable-dependency-overrides=false --reconciliation '*:*:relaxed'`) shows that jackson / grpc / netty / kotlin -related dependencies have more consistent versions with each other when the option is enabled.
