### ISSUE TITLE
https://www.scala-sbt.org/ Origin DNS error

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#7946]
## Steps
https://www.scala-sbt.org/

## Problem
<img width="1045" alt="dns-issue" src="https://github.com/user-attachments/assets/8154964e-0655-4df4-8ad4-4a0dbb2bb9f9" />

**Comment by eed3si9n** [comment]
@SethTisue @JustinPihony Do you know what could be up, or is this internet weather?

**Comment by SethTisue** [comment]
was the website not included in the big handoff of sbt from Lightbend/Akka to the Center...? wondering if this is actually Fabien's wheelhouse

**Comment by eed3si9n** [comment]
Not sure cc @adpi2, @sjrd?

**Comment by SethTisue** [comment]
"we don't own it... that was given to scala center iirc" says Justin

**Comment by SethTisue** [comment]
@fsalvi assuming Justin is right, can you check on it?

**Comment by JustinPihony** [comment]
Yes, I double checked in my emails. This was turned on in early August 2023 and we turned it off from our end at the end of September 2023 after verification from Fabien.

**Comment by eed3si9n** [comment]
https://www.scala-sbt.org/ healed itself after your comment. Friday the 13th spookiness.
