### ISSUE TITLE
`Graph.toAscii` fails with `StringIndexOutOfBoundsException` if there's no terminal

### ISSUE THREAD

**Issue by jrudolph** [sbt/sbt#795]
See https://groups.google.com/forum/?fromgroups#!topic/simple-build-tool/csu0G50_zDQ and jrudolph/sbt-dependency-graph#32 

From the linked mailing list post:

> Just did a little bit of debugging on this and the problem is that in SettingGraph.scala for dump terminals (TERM=dump, e.g. the Emacs shell) JLine.usingTerminal(_.getTerminalWidth) returns 0, which creates the stack trace below. Use a different terminal (e.g. Emacs terminal) and you should be fine.

The solution is to check what `getTerminalWidth` returns and set some default value in case it returns 0 (or another low value which would make no sense).

I will add a fix like this to sbt-dependency-graph but it would make sense to fix that in sbt as well.

**Comment by harrah** [comment]
@eed3si9n can you review this?

**Comment by eed3si9n** [comment]
What @jrudolph is saying makes sense. If the width is 0, we need some default value.
I actually had it hardcoded in the original implementation to 72 because I remember paulp making [fun of it](https://groups.google.com/d/msg/simple-build-tool/Ac0_uheHaJg/y8-Spt2wEYoJ):

> Having a hardcoded 72-column width makes me feel like jimmy carter is
> president and the looming threat of disco is the problem on all of our
> minds.  However rather than do something sensible like take five
> minutes to make it configurable, I somehow ended up going down the
> rabbit hole of trying to get the window auto-adjusting.

**Comment by harrah** [comment]
Ok, so, add `... min 20` or something?  Do you want to submit a patch?

**Comment by eed3si9n** [comment]
Sure

**Comment by jrudolph** [comment]
Thanks, @eed3si9n and @harrah for the speedy resolution.
