### ISSUE TITLE
The links in the docs are broken missing a parent.

### ISSUE THREAD

**Issue by bjornbak** [sbt/sbt#7965]
Being on https://www.scala-sbt.org/2.x/docs/en/concepts/command.html all the links to the other chapters have a `concepts/` too much in the TOC to the left.

So chapter 5.2 have link https://www.scala-sbt.org/2.x/docs/en/concepts/concepts/cross-building.html and 6.2 https://www.scala-sbt.org/2.x/docs/en/concepts/reference/sbt-update.html.

Seems to happen on all the pages.

**Comment by Friendseeker** [comment]
Is this a regression? I might be just hallucinating but I vaguely remember the links used to be correct...

**Comment by bjornbak** [comment]
> Is this a regression? I might be just hallucinating but I vaguely remember the links used to be correct...

I don't know. I just found the sbt-update.html via Google and wanted to let you know.

**Comment by eed3si9n** [comment]
https://www.scala-sbt.org/2.x/docs/en/
> This is a draft documentation of sbt 2.x that is yet to be released. While the general concept translates to sbt 1.x, details of both 2.x and this doc are subject to change.

I do welcome bug reports like this tho.

**Comment by eed3si9n** [comment]
I'm hitting https://github.com/rust-lang/mdBook/issues/2488. Hopefully updating the template should fix this.
