### ISSUE TITLE
jars in provided scope don't get passed to javac

### ISSUE THREAD

**Issue by jesseeichar** [sbt/sbt#8]
In my build.sbt file included the line:

libraryDependencies += "javax.servlet" % "servlet-api" % "2.5" % "provided"

When I compiled the servlet api jar was not on the classpath.  I removed the % "provided" and the project compiled correctly.  I don't know if this is a general problem IE if scala has the problem or if it is only a problem with javac.  Or perhaps the way to define scopes has changed in 0.9.1.  I assumed it was the same since there are so many similarities between 0.91 and 0.7.x.

**Comment by harrah** [comment]
You are right to expect this would work correctly.  provided is a bit problematic to get right and isn't implemented yet in 0.9.x.

-Mark
