### ISSUE TITLE
Binary incompatibility between plugin and updated SBT should be reported

### ISSUE THREAD

**Issue by retronym** [sbt/sbt#80]
See: https://groups.google.com/d/msg/simple-build-tool/fpOlXTbq-XM/wYqBikTfBaMJ

I had a reference to a binary distribution of a the idea-sbt-plugin in my global `build.sbt`.

```
resolvers += "sbt-idea-repo" at "http://mpeltonen.github.com/maven/"

libraryDependencies += "com.github.mpeltonen" %% "sbt-idea" % "0.10.0-SNAPSHOT"
```

**Comment by harrah** [comment]
Part I (commit 9fb6f20).  Dependency on sbt is declared as provided, so it will not be pulled into the classpath by plugins.  This will only work for newly published plugins.  It fixes the immediate problem of multiple versions of sbt on the classpath.

Part II (pending).  Warn or error on mismatch and possibly a workaround for previous plugin versions.
