### ISSUE TITLE
Aggregated task loses state updates from `updateState` when just one sub-task fails

### ISSUE THREAD

**Issue by jrudolph** [sbt/sbt#804]
In `sbt-revolver` we use `update-state` on the `re-start` and `re-stop` tasks to register globally which processes are running when the task has successfully started a project.

See https://github.com/spray/sbt-revolver/blob/master/src/main/scala/spray/revolver/RevolverPlugin.scala#L35

This usually works well. However, if `re-start` is used from an aggregate project to start many processes in parallel the problem is that if only one of the project-specific re-starts fail (e.g. because of a compilation error) _all_ of the state updates seem to be discarded so that we effectively lose track of started processes.

https://github.com/spray/sbt-revolver/issues/21

Is this expected? I expected that if a task was successfully executed the state update would be applied regardless of what happens on other concurrently running tasks.

(It could also be that using tasks to trigger state changes is the wrong way to do it but it's so convenient...)

See https://groups.google.com/d/topic/simple-build-tool/62wORv6RRDI/discussion

**Comment by harrah** [comment]
Can you provide a test case?  Here is my attempt to reproduce:

``` scala
lazy val a = project.settings(sett("a"))

lazy val b = project.settings(sett("b"))

def demo[S](id: String)(st: State, s: S): State = {
  println("Updating '" + id + "'")
  st
}

def sett(id: String): Setting[_] = {
  val key = compile in (LocalProject(id), Compile)
  key <<= key.updateState(demo(id))
}
```

If all sources compile ok, I see:

```
Updating 'a'
Updating 'b'
```

If I add a source `a/A.scala` with an error, I see:

```
Updating 'b'
```

**Comment by jrudolph** [comment]
Interesting, what I missed to say before was that I only tested with sbt 0.12.4. Is it likely that it was fixed somehow afterwards?

**Comment by harrah** [comment]
Here is the sample converted for 0.12.4, which also works:

``` scala
import sbt._
import Keys._

object B extends Build {
  lazy val root = Project("root", file(".")).aggregate(a,b)
  lazy val a = Project("a", file("a")).settings(sett("a"))
  lazy val b = Project("b", file("b")).settings(sett("b"))

  def demo[S](id: String)(st: State, s: S): State = {
    println("Updating '" + id + "'")
    st
  }

  def sett(id: String): Setting[_] = {
    val key = compile in (LocalProject(id), Compile)
    key <<= key.updateState(demo(id))
  }
}
```

**Comment by jrudolph** [comment]
Ah, interesting. I think the problem is that the updater function is indeed called but the state is never updated with the new value.

I published a test project here: https://github.com/jrudolph/sbt-state-updater-test

**Comment by harrah** [comment]
Thanks for the test case.  If there is an RC2, this will go in- it is important, but not a regression.

**Comment by jrudolph** [comment]
Thanks Mark for fixing this. Any idea about a workaround for earlier versions? E.g. I can use `Seq(p1/a, p2/a, ...).dependOn` but that is quite cumbersome for the users.

**Comment by harrah** [comment]
This was a bug in the task evaluating command where if the overall result was failure, it would discard the new state.  The only solutions I see would be to either not fail or to override this command and neither of these are practical, sorry.

**Comment by jrudolph** [comment]
Ok, that's what I suspected as well. Thanks, anyway.

**Comment by harrah** [comment]
I forgot that there is the option of a synchronized var in your Plugin object.  Not normally recommended of course, but in this case I don't think there is another option until this is fixed.

**Comment by jrudolph** [comment]
You mean, relying on the side-effects of `updateState`? Either that or a singleton with mutable state that is directly changed by the task.

**Comment by harrah** [comment]
I meant the the singleton+var option.
