### ISSUE TITLE
Provide a way for commands to get adjustable log levels

### ISSUE THREAD

**Issue by copumpkin** [sbt/sbt#806]
Currently a command is passed the `State` of the world, and if it wants to log it will typically ask for the `.log` of that `State`. That `.log` is not attached to any configuration or scope that is settable in user projects, so plugins can be unconditionally noisy even in otherwise quiet builds. Mark says there's no endorsed mechanism for setting plugin log levels, so here is a juicy feature request!

**Comment by harrah** [comment]
Additionally, settings should have access to this logger.

**Comment by harrah** [comment]
... and the level should be configurable on startup before any logging occurs

**Comment by SethTisue** [comment]
`--warn` working great for me in 0.13.1-RC3. thank you
