### ISSUE TITLE
class file needed by Defaults is missing error in sbt-launch-0.10.1-20110629-052055

### ISSUE THREAD

**Issue by kahliburke** [sbt/sbt#81]
Trying this nightly:

sbt-launch-0.10.1-20110629-052055

I have  a project that demonstrates this on github:

git://github.com/kahliburke/sbtBug.git

Just run the sbt script and you should see it.

**Comment by harrah** [comment]
Please try the latest nightly.

http://repo.typesafe.com/typesafe/ivy-snapshots/org.scala-tools.sbt/sbt-launch/0.10.1-20110630-140903/

**Comment by harrah** [comment]
It doesn't appear to fix it for me, so incremental recompilation doesn't appear to be the problem.

**Comment by kahliburke** [comment]
This does work for me, I had the old version in the build.properties file which may have caused some confusion. Try it again with the version I just pushed to github.

**Comment by harrah** [comment]
Yes, you're right.  Leaving open until I minimize it.

**Comment by harrah** [comment]
https://issues.scala-lang.org/browse/SI-4757
