### ISSUE TITLE
Could not retrieve sbt 0.7.5RC0

### ISSUE THREAD

**Issue by greenrd** [sbt/sbt#816]
```
Getting org.scala-sbt sbt 0.7.5.RC0 ...

:: problems summary ::
:::: WARNINGS
                module not found: org.scala-sbt#sbt;0.7.5.RC0

        ==== local: tried

          /home/robin/.ivy2/local/org.scala-sbt/sbt/0.7.5.RC0/ivys/ivy.xml

        ==== typesafe-ivy-releases: tried

          http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.7.5.RC0/ivys/ivy.xml

        ==== Maven Central: tried

          http://repo1.maven.org/maven2/org/scala-sbt/sbt/0.7.5.RC0/sbt-0.7.5.RC0.pom

        ==== sonatype-snapshots: tried

          https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/sbt/0.7.5.RC0/sbt-0.7.5.RC0.pom

                ::::::::::::::::::::::::::::::::::::::::::::::

                ::          UNRESOLVED DEPENDENCIES         ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: org.scala-sbt#sbt;0.7.5.RC0: not found

                ::::::::::::::::::::::::::::::::::::::::::::::



:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
unresolved dependency: org.scala-sbt#sbt;0.7.5.RC0: not found
Error during sbt execution: Error retrieving required libraries
  (see /home/robin/.sbt/boot/update.log for complete log)
Error: Could not retrieve sbt 0.7.5.RC0
```

A workaround that worked for me, but might not work for others, is downloading the sbt 0.7.5RC0 launcher and running that instead.

**Comment by harrah** [comment]
The launcher only supports final releases of 0.7-0.11.  Some background:

https://groups.google.com/d/topic/simple-build-tool/T2_Jk5kLdRM/discussion
https://groups.google.com/d/topic/simple-build-tool/3sE6DxS9t6E/discussion

The scala-tools repository went away and sbt had to change its group ID, requiring a new launcher feature to work around the situation.  This feature switches the launcher configuration file based on the sbt version.  At the time of 0.7, non-final releases were published to a snapshot repository.  The configuration-selection feature doesn't distinguish final v. other versions, so the snapshot repository is not available to retrieve 0.7.5.RC0.  Or, it might just be that the feature expects the form 0.7.5-RC0 (with a dash) and can't parse it.
