### ISSUE TITLE
ivy.xml is missing all dependencies when downloaded from local filesystem

### ISSUE THREAD

**Issue by greenrd** [sbt/sbt#817]
I have the following entry in `~/.ivy2/ivysettings.xml`, which is loaded by `externalIvySettings`:

```
     <filesystem name="libraries">
        <ivy pattern="${ivy.settings.dir}/local/[organisation]/[artifact]/[revision]/ivys/ivy.xml"/>
        <artifact pattern="${ivy.settings.dir}/local/[organisation]/[artifact]/[revision]/[ext]s/[artifact].[ext]" />
      </filesystem>
```

The cached `ivy.xml` files in `~/.ivy2/cache`, such as this one:

```
<?xml version="1.0" encoding="UTF-8"?>
<ivy-module version="2.0">
        <info organisation="org.bowlerframework"
                module="core_2.9.1"
                revision="0.7-SNAPSHOT"
                status="release"
                publication="20130716133247"
                default="true"
        />
        <configurations>
                <conf name="default" visibility="public"/>
        </configurations>
        <publications>
                <artifact name="core_2.9.1" type="jar" ext="jar" conf="default"/>
        </publications>
</ivy-module>
```

are incorrect for files "downloaded" from this filesystem source. Unlike ivy files downloaded or produced from other sources, they do not include dependencies, so sbt doesn't add the dependencies of those artifacts to the classpath.

My workaround is to manually overwrite the file(s) in `~/.ivy2/cache` with the `ivy.xml` files from `${ivy.settings.dir}/local/[organisation]/[artifact]/[revision]/ivys/ivy.xml`, then do

`clean`
and `update`.

This is with sbt 0.11.3. I have reproduced the bug multiple times.

This does not occur for HTTP repositories.

**Comment by jsuereth** [comment]
Just curious, have you tried this against sbt 0.12/Play 2.1?

**Comment by harrah** [comment]
Please reopen if this still exists in 0.12.4 or 0.13.
