### ISSUE TITLE
ScalaDoc fails to resolve local classes

### ISSUE THREAD

**Issue by darkfrog26** [sbt/sbt#82]
Upgrading from 0.7.7 to 0.10.0 and everything is compiling fine, but generating the ScalaDocs for my math library is causing the build to fail. I'm getting the output as follows:

http://paste.pocoo.org/show/420649/

This is a repeat of this ticket: https://github.com/harrah/xsbt/issues/76 that was prematurely closed.  I have included a very simple project reproducing the error:

http://captiveimagination.com/download/sgine-math.zip

**Comment by harrah** [comment]
Thanks for the small test case.  This is fixed in the 0.10 branch and in the latest nightly:

http://repo.typesafe.com/typesafe/ivy-snapshots/org.scala-tools.sbt/sbt-launch/0.10.1-20110630-140903/
