### ISSUE TITLE
Private def with existential type causes spurious recompilation due to name instability

### ISSUE THREAD

**Issue by gkossakowski** [sbt/sbt#823]
Consider the following code structure:

``` scala
// Box.scala
class Box[T]

// Foo.scala
class Foo {
    def foo: Box[_] = null
}

// Bar.scala
class Bar {
    def f: Foo = null //we introduce dependency on Foo
}
```

Let's assume it's been compiled.

Now, let's introduce a _private_ method to `Foo` so it looks like this:

``` scala
class Foo {
    private def abc: Box[_] = null
    def foo: Box[_] = null
}
```

If we recompile we would expect one iteration of compilation (just to recompile `Foo.scala`) because the newly introduced method is private. At the moment, incremental compiler will decide to recompile `Bar.scala` as well because it sees changed signature of `foo` method. The reason its seen as changed is name instability for existential types introduced with widlcard syntax. What happens is that Scala compiler has a global counter for ids per compilation unit and uses that counter for naming existential types. Therefore even private definition can affect a signature a public definition thus causing spurious recompilation.

**Comment by harrah** [comment]
Probably due to 864580aae1c32041beccfcf61cb2b545b80c9579.  The correct approach was removed because it relied on Symbol.id, which is apparently an unreliable implementation detail.  The id didn't need to be stable across runs, but was just used to identify equal type parameters.  I don't remember the details, but should it be desirable to restore the indexed approach, perhaps a Symbol map would work instead.

**Comment by gkossakowski** [comment]
Thanks for the pointer! Yes, using Symbol.id would solve that particular problem but would introduce a lot more other problems.

I was thinking about introducing some kind of a map on Sbt side. I'm not sure if `Map[Symbol, Symbol]` is the best idea because it means we need to allocate new symbols. Allocating symbols is a side-effecting operation (e.g. it mutates the owner) so it's dangerous to do.

I was thinking about introducing a much more specialized map `Map[Symbol, String]` which would just deal with remapping names of symbols corresponding to existential type variables. However, synthesizing strings that are both stable and guarantee no collisions is rather difficult.

**Comment by paulp** [comment]
Not that everything isn't a side effecting operation, but in general owners know nothing of their children. It doesn't mutate the owner unless you mutate the owner (perhaps entering it into the owner's scope.)

**Comment by peter-fu** [comment]
+1

I got to this pull request from https://gist.github.com/jroper/6374383. I think this is the pull request of the "Scala incremental compiler improvements"? The result of the fix looks amazing!

Thanks!

**Comment by gkossakowski** [comment]
I accidentally reopened this issue but clicking the wrong button on issue list. I'm very sorry for that. Closing again.
