### ISSUE TITLE
Support for Ivy signers

### ISSUE THREAD

**Issue by rossabaker** [sbt/sbt#83]
Would like support for [Ivy signers](http://ant.apache.org/ivy/history/2.2.0/settings/signers.html) without resorting to [crude launcher hacks](http://github.com/rossabaker/sbt-signer-plugin).

The basic problem is that Ivy's pgp signer requires that

> This generator uses the BouncyCastle OpenPGP library. Before this generator can be used, these libraries must be available on Ivy's classpath.

In sbt, the Ivy classpath is determined by the launcher.  Library dependencies added via plugin are not seen by Ivy, so it can't load the necessary Bouncy Castle classes.  Users of the plugin must manually download these dependencies and add them as resources in a custom sbt.boot.properties, which is a lot of work to use such a trifling plugin.

Possible solutions:
1. Make sbt depend on Bouncy Castle. _Why not:_ Adds bulk for something most users don't need.
2. Make Ivy classpath managable by sbt plugins. _Why not:_ Possible chicken and egg problems.
3. Command line flags to support a known set of "boot profiles". _Why not_: Must wait for new sbt to use such features each time a new profile is added.
4. ???

**Comment by harrah** [comment]
I assume the chicken and egg problem you mean is that sbt is loaded with its classpath (including Ivy) and then plugins are loaded, so how can a plugin add to that classpath?  sbt can reload itself through the launcher and give its reloaded self additional classpath components.  So, you could probably implement this now with an 'onLoad' hook.  I'll take a look at this.

**Comment by harrah** [comment]
I will provide more details later, including an example.

**Comment by rossabaker** [comment]
Excellent.  I'm glad a general approach is possible rather than a BC-specific hack.  Thank you!

**Comment by harrah** [comment]
Documented here:

 https://github.com/harrah/xsbt/wiki/Specialized

It will be in 0.10.1 (and in the next nightly) and will require an updated launcher.
