### ISSUE TITLE
API extraction logic doesn't cover all simple types

### ISSUE THREAD

**Issue by gkossakowski** [sbt/sbt#830]
Here's a minimal reproduction:

``` scala
class Test {
  def foo: ({ type F })#F = ???
}
```

when compiled with sbt it gives:

```
[info] Compiling 1 Scala source to /Users/grek/tmp/sbt-not-simple-type/target/scala-2.10/classes...
[warn] Not a simple type:
[warn]  Type: AnyRef{type F} (class scala.reflect.internal.Types$RefinedType0)
[warn]  Transformed: class xsbti.api.Structure
[warn] one warning found
```

The problem is that sbt seems to have different notion of "simple type" than Scala spec defines. In Scala spec a SimpleType is defined as:

> SimpleType ::= SimpleType TypeArgs
> | SimpleType ‘#’ id
> | StableId
> | Path ‘.’ ‘type’
> | ‘(’ Types ’)’

I believe that sbt doesn't cover the last case.

**Comment by gkossakowski** [comment]
@harrah: your thoughts on this?

**Comment by harrah** [comment]
`'(' Types ')'` is for tuple types, described in 3.2.5, where it says that n must be >= 2.  So, I don't think the spec allows it.

However, I assume scalac doesn't enforce that, perhaps by mistake, but this could be how the type lambda syntax hack gets through.  I think that case gets handled by normalize/dealias though?  I'm not sure, maybe we have to support any type there?

**Comment by paulp** [comment]
The Types production is one or more types. Tuple types are n >= 2, but a single parenthesized type is valid because parentheses in types are used for grouping. Certainly 3.2.5 is misleading at least, but I do not think it excludes, nor do I think it is intended to exclude, a single parenthesized type.

**Comment by gkossakowski** [comment]
I interpret spec the same way @paulp does. Also, there's this one sentence mentioning grouping (beginning of chapter 3):

> Parentheses in types can be used for grouping

Yes, the type lambda hack is normalized early on by dealiasing. I think we have to support any type as a prefix when converting a type ref.

**Comment by retronym** [comment]
Related discussion: https://groups.google.com/d/msg/scala-internals/ANcaI6dVYPw/2Gt5z_S3Gc0J

**Comment by harrah** [comment]
From that discussion, SimpleType is only syntactic, like you guys said.  So, it should not be represented in the data structure separately.

**Comment by gkossakowski** [comment]
Yep. Now, if I wanted to fix it I'd need to get rid of SimpleType data structure in sbt. Is it considered to be a part of public API?

**Comment by harrah** [comment]
yes

**Comment by gkossakowski** [comment]
@harrah: so what can we do in that case? Deprecate? Those classes are generated and I don't think we have support for deprecation in code generation logic.

**Comment by harrah** [comment]
Oh, you can get rid of them without deprecating, it just can't happen in 0.13.x.

**Comment by gkossakowski** [comment]
I see. Thanks. I scheduled this for 0.14 then.

**Comment by gkossakowski** [comment]
There's unfortunate interaction with `-Xfatal-warnings` reported in #1475. We probably could demote the earning to debug log entry in 0.13 series as more principled fix is possible in next major version only.

**Comment by eed3si9n** [comment]
Closing this in favor of sbt/zinc#101
