### ISSUE TITLE
sbt clean "~run" takes 100% of processor activity after a call to elasticsearch

### ISSUE THREAD

**Issue by vallettea** [sbt/sbt#834]
hello,

this a reference to thinkaurelius/titan#336 : 
when using 

   sbt clean "~run"

with a program calling elastic search, the execution runs perfectly but it seems that sbt wants to control the underlying elastic search status and fails constantly which causes a sort of infinite loop.
I could provide materials.

It is the same on ubuntu 12 and 13 and on macos X

**Comment by harrah** [comment]
Please minimize the problem and provide enough information to reproduce: https://github.com/sbt/sbt/blob/0.13/CONTRIBUTING.md#new-issues.  sbt knows nothing about elastic search status.  What fails and what is the error message?  When you say constantly, what does that mean?  What sbt version?  Does running sbt in interactive mode and manually doing `run` multiple times also have problems?

**Comment by vallettea** [comment]
yes sorry about that:
I think the application i'm running is not closing correctly a connection to elastic search and that causes the mess.
I'll try to get further from the other side (titan).
