### ISSUE TITLE
network still used when -offline flag present

### ISSUE THREAD

**Issue by tomyan** [sbt/sbt#841]
If I remove a dependency of my project and run sbt with the -offline flag, I would expect it to fail. Instead it downloads the dependency from the network:

```
[developer@sandbox testsbtproject]$ rm -rf vendor/cache/junit/
[developer@sandbox testsbtproject]$ sbt -Dsbt.ivy.home=vendor -offline run
[info] Loading project definition from /mnt/hgfs/workspace/testsbtproject/project
[info] Set current project to my-project (in build file:/mnt/hgfs/workspace/testsbtproject/)
[info] Reapplying settings...
[info] Set current project to my-project (in build file:/mnt/hgfs/workspace/testsbtproject/)
[info] Updating {file:/mnt/hgfs/workspace/testsbtproject/}default-93651c...
[info] Resolving org.scala-lang#scala-library;2.9.1 ...
[info] Resolving junit#junit;4.8 ...
[info] downloading http://repo1.maven.org/maven2/junit/junit/4.8/junit-4.8.jar ...
[info]  [SUCCESSFUL ] junit#junit;4.8!junit.jar (79ms)
[info] Done updating.
[info] Running Hi
Hi!
[success] Total time: 12 s, completed 05-Aug-2013 12:48:14
```

This might be by design, but would be much more useful to me if there was an option where I could be sure that the build is repeatable without having to go to the network.

Thanks

Tom

**Comment by jsuereth** [comment]
the -offline mode in the script is still a little buggy.   COuld you reopen the issue against the script itself?

https://github.com/sbt/sbt-launcher-package

I beleive it's the difference between a `set every` and `set` call.

However, to make sure sbt is no the culprit can you try the following?
1. run `sbt`
2.  In the console, type `set every offline := true`
3. type `run`

IF you see the same download happening, then offline mode in sbt is also an issue.

Thanks!
- Josh

**Comment by tomyan** [comment]
Hi Josh

Thanks for getting back to me. Have tried suggestion - will include details in new ticket.

Regards

Tom

**Comment by tomyan** [comment]
See https://github.com/sbt/sbt-launcher-package/issues/56

Thanks

Tom
