### ISSUE TITLE
Consider modularization in Scala binary version detection

### ISSUE THREAD

**Issue by adriaanm** [sbt/sbt#846]
As of 2.11.0-M5, scala-xml will be published as scala-xml_2.11.0-M5%1.0-RC1.
I.e., modules are cross-versioned against the Scala version they target,
and get their own versions (and their own release schedule).

SBT 0.13 currently warns/errors about this. I think it's still useful to have some kind of
detection mechanism of the Scala binary version, but maybe it should be done via a properties file in the jar?

**Comment by adriaanm** [comment]
I see the milestone was set to 0.13.1, which is fine. Note that SBT 0.13 won't build using 2.11 after scala-xml and scala-parser-combinators are modularized, which is scheduled to happen in M5. I think we're happy to integrate against 0.13.1, but which branch (of sbt) should PR validation use. In other words, where should I submit PRs targetting 0.13.1?

BTW, this is the affected line: https://github.com/sbt/sbt/blob/0.13/project/Util.scala#L175.

/cc @dragos

**Comment by harrah** [comment]
Pull requests for 0.13.1 can target the 0.13 branch.  The modularization changes for building sbt are separate, though, since it uses 0.12.  Changes specific to building against 2.11 can go on the 0.13-2.11 branch.

**Comment by huitseeker** [comment]
As mentioned in email, Adriaan has a proposed fix here : https://github.com/adriaanm/sbt/commit/ec07ee46fa5a19e8fde47fed084fe47aeda5c487

**Comment by harrah** [comment]
@adriaanm Is this still an issue?  If so, what needs to be changed?

**Comment by adriaanm** [comment]
I think this particular issue can be closed. The main remaining work item is the scaladoc module.

**Comment by harrah** [comment]
Ok, thanks Adriaan.
