### ISSUE TITLE
Can't compile tests when using an external Ivy file

### ISSUE THREAD

**Issue by gtopper** [sbt/sbt#849]
It appears that SBT tries to compile the tests against a classpath that does not include other compiled classes (those compiled from src).

Here is a simple example https://github.com/gtopper/sbt-external-ivy-example

**Comment by gtopper** [comment]
Adding the following two lines to build.sbt makes it possible to compile the test sources, but still not run the tests.

test <<= (test in Test) dependsOn (compile in Compile)

managedClasspath in Test <+= baseDirectory(_ / "target/scala-2.9.2/classes") map identity

**Comment by harrah** [comment]
See http://www.scala-sbt.org/release/docs/Detailed-Topics/Library-Management.html#ivy-file-dependency-configuration.  If you think there is a documentation issue here, a pull request or comment would be welcome.

**Comment by harrah** [comment]
Also, thank you for the reproducible example.
