### ISSUE TITLE
Problem with ScalaDoc generation with package objects

### ISSUE THREAD

**Issue by darkfrog26** [sbt/sbt#85]
After creating a package.scala file in my project to represent a package object, the ScalaDoc begins failing with the following:

[error] error while loading package, Missing dependency 'class org.sgine.math.package', required by ./target/scala-2.9.0.1/classes/org/sgine/math/package.class

You can test with this simple test case: http://captiveimagination.com/download/sgine-math-scaladoc-package.bug.zip

This is using this build: http://repo.typesafe.com/typesafe/ivy-snapshots/org.scala-tools.sbt/sbt-launch/0.10.1-20110630-140903/

**Comment by harrah** [comment]
This is unlikely to be a bug in sbt, but regardless, the link provided doesn't work for me.

**Comment by darkfrog26** [comment]
Sorry, here's the link: http://captiveimagination.com/download/sgine-math-scaladoc-package-bug.zip

I didn't expect that to be the case with the last bug I ran into, but unless it's a bug in Scala 2.9.0.1 then I can't imagine any other scenario that would cause this problem as it's just a standard package.scala file.

**Comment by harrah** [comment]
This works for me.  I ran 'doc' using the referenced nightly and it completes ok.

**Comment by darkfrog26** [comment]
It's strange, the test I created failed for me the first time I ran it, but after running it again it passed.  I've created a new example showing the bug:

http://captiveimagination.com/download/sgine-core.zip

It would seem this is caused by multi-projects.  To reproduce you simply need to set the project to "core" and then run "doc" and it will throw the following:

[error] error while loading package, Missing dependency 'class org.sgine.transaction.package', required by ./core/target/scala-2.9.0.1/classes/org/sgine/transaction/package.class
model contains 26 documentable templates
[error] one error found
[error] {file:/storage/programming/projects/math/}core/doc: Scaladoc generation failed
[error] Total time: 3 s, completed Jul 4, 2011 1:48:05 PM

Please let me know if there is any additional information I can provide.  I'm holding out checking my code in until I have a fix for this so I don't break Jenkins. :)

**Comment by harrah** [comment]
Ok, it required running 'compile' first to see the error.  The cause was a bad fix for #82.  An empty classpath should be declared with -cp "" because omitting it puts the current directory on the classpath.  scalac then traverses all of the directories in the current directory looking for class files (even though target/scala-2.9.0.1/classes/... isn't a valid package name).

**Comment by darkfrog26** [comment]
It's very strange, and I presume not a bug with SBT, but this is still happening on my Jenkins server after changing to the latest build of SBT.  However, on my local machine it's working properly now:

http://build.sgine.org/job/sgine/299/console

You can see that it's pulling in the newest build of SBT and I've even logged into the box and completely re-checked out the project and I can't seem to avoid that exception.  The build server is running CentOS Linux and Java 1.6.0_26 64-bit.  My machine is Windows 7 64-bit and it works fine.  It would seem either the update doesn't fix all environments, or something's not clearing out of the cache for me.  Any suggestions would be appreciated.

**Comment by harrah** [comment]
I only recently committed the fix, so it isn't in a nightly build yet.  It will be in the next one.

**Comment by darkfrog26** [comment]
Ah, that explains that, but doesn't explain why on my local machine it builds now...

Oh well, not a big deal. Thanks again!

**Comment by harrah** [comment]
Because you re-checked out the project, you may not have run 'compile' before 'doc', which is required to trigger the problem.

**Comment by darkfrog26** [comment]
I'm sure you're getting sick of me by now, but the latest nightly fixed this problem, but re-introduced bug #82.

**Comment by harrah** [comment]
Ah, I see.  I misdiagnosed it the first time and the fix for this reverted the fix for #82.  It is actually a bug in scalac 2.9.0 where it ignores an empty string argument to -cp.  

https://issues.scala-lang.org/browse/SI-4782

**Comment by darkfrog26** [comment]
So does this mean that this will not be resolved until a new version of Scala is released?

**Comment by harrah** [comment]
Correct.  Unfortunately, sbt can't generally work around this as far as I can tell.

However, I think there is an easy workaround and that is to have a non-empty classpath.  For example, you could define a "provided" dependency on some small module.  Or, you could add an empty directory (or maybe even a non-existing directory) to the unmanagedClasspath in Compile.

**Comment by darkfrog26** [comment]
Can you give an example of how to do this?  Searching through the wiki and code I'm having a hard time determining how to add it to my Build.scala file.

**Comment by darkfrog26** [comment]
Additionally, wouldn't it be a good idea to create a work-around for this in SBT until this bug in resolved to not use empty classpath references?

**Comment by darkfrog26** [comment]
Ah, nevermind, just adding a dependsOn resolved the problem.  Thanks for the help.

**Comment by fhars** [comment]
I have very similar problems when trying to build the doc task in the trunk of http://www.assembla.com/code/scala-graph/subversion/nodes revision 70 with sbt 0.10.1, and the magic incantation for the workaround that I found after quite some searching is:

```
unmanagedClasspath in Compile += Attributed.blank(new java.io.File("doesnotexist"))
```

**Comment by aloiscochard** [comment]
Still facing same issue with SBT 11.2

**Comment by harrah** [comment]
That's strange.  Can you try 0.12.0-M1?

**Comment by filosganga** [comment]
I Have the same issue on sbt 0.11.2

**Comment by aloiscochard** [comment]
Still same issue with 0.11.3, only on jenkins not locally... unfortunately I still haven't found the time to test with 0.12 ... shame on me Mark :-/ ... I'll do it asap
