### ISSUE TITLE
"Invalid or corrupt jarfile" when packaging more than 66k files

### ISSUE THREAD

**Issue by Rogach** [sbt/sbt#850]
I stumbled upon following problem: when packaging a project with lots of files, resulting jar file is perceived as corrupt by java runtime. 

Steps to reproduce (on java 7, sbt 0.12.3):

```
$ # in fresh dir
$ echo "object App{}" > Main.scala
$ mkdir -p src/main/resources/
$ # the following is going to take a while :)
$ for i in {1..70000}; do touch src/main/resources/$i; done
$ sbt package
$ java -jar target/scala-2.9.2/default_*.jar
Error: Invalid or corrupt jarfile target/scala-2.9.2/default-92d531_2.9.2-0.1-SNAPSHOT.jar
```

The probable cause of this problem could be the 65k file limit of the old ZIP format - but java 7 already uses ZIP64 by default, and 7z reports that the resulting jar file is indeed in 64-bit format. ([relevant discussion](http://stackoverflow.com/questions/13021423/invalid-or-corrupt-jar-file-built-by-maven-shade-plugin))

The same problem happens with sbt-assembly, by the way (it also uses sbt.Package).

**Comment by Rogach** [comment]
Seems that it's a problem in a way Java reads jar files on launch - and the fix will only come to us in Java 8.

Meanwhile, there is a simple workaround:

```
java -jar app.jar
# becomes
java -cp app.jar app.Main
```
- [Bug in Oracle's bug db](http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=7191282)
- [Discussion at SO](http://stackoverflow.com/questions/18441076/why-java-complains-about-jar-files-with-lots-of-entries)

**Comment by harrah** [comment]
Thanks for following up on this.

**Comment by ijuma** [comment]
The bug referenced says that the "Fix version" is Java 7 update 40 (out in mid September) so looks like we'll get it sooner than Java 8.

**Comment by Rogach** [comment]
@ijuma - the resolution on that bug is "Duplicate", the [actual entry](http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=2230132) about backport says "Won't Fix" (and something about that it's "too risky").

**Comment by ijuma** [comment]
You are right. My bad.
