### ISSUE TITLE
Tests.setup not called when fork in Test is true

### ISSUE THREAD

**Issue by sauravshah** [sbt/sbt#860]
I would assume that this is not the expected behavior and tripped me up for a day. 

// Tests pass
testOptions in Test += Tests.Setup(() => System.setProperty("config.file", "path/to/conf/file")),
Keys.fork in Test := false

// Tests fails
testOptions in Test += Tests.Setup(() => System.setProperty("config.file", "path/to/conf/file")),
Keys.fork in Test := true

Can someone explain as to why the above behavior would be correct?

**Comment by harrah** [comment]
This was an implementation restriction in 0.12.x that was documented on the Testing page.  The restriction was lifted for 0.13.
