### ISSUE TITLE
Getting-Started/Basic-Def.html incomplete

### ISSUE THREAD

**Issue by ghost** [sbt/sbt#862]
In Getting-Started/Basic-Def.html there is section where you say 

> Using :=, you can assign a computation to a task, and that computation will be re-run each time:

 and then 

> ```
> hello := { println("Hello!") }
> ```

but taskKey hello is not yet created so reload doesn't work. I found out that I can create taskKey like

> ```
> lazy val hello = taskKey[Unit]("Hello'")
> ```

I think that info about creation hello task should also be on Basic-Def site.

**Comment by NightRa** [comment]
Agree.
