### ISSUE TITLE
Deploying to sonatype doco incorrect.

### ISSUE THREAD

**Issue by Synesso** [sbt/sbt#865]
At http://www.scala-sbt.org/release/docs/Community/Using-Sonatype.html the sample setting for `publishTo` does not compile. See https://github.com/Synesso/eshq-client/commit/e9d89a65f7f94c1ebbd6622f27018598280df6a7 for the change I needed to make to get it to work for my project.

**Comment by harrah** [comment]
Note that the current release is 0.13.0 and from your changes, it looks like you are on 0.12.x.  Instead of `.../release/...`, you can use `.../0.12.4/...` to look at 0.12 documentation.  (There is a drop down box with the version number on the left near the top.)
