### ISSUE TITLE
Odd classloader issue in tests with org.apache.xalan code.

### ISSUE THREAD

**Issue by kklipsch** [sbt/sbt#869]
In sbt 0.13.0 when using the built in java xslt transformer (javax.xml.transform.TransformerFactory) in a unit test (in this case using scalatest) you will get the following print to output "Warning:  The encoding 'UTF-8' is not supported by the Java runtime.".  Tracking this down, it appears that internally (in com.sun.org.apache.xml.internal.serializer.Encodings) the java transformer is looking for a properties file as a resource "com/sun/org/apache/xml/internal/serializer/Encodings.properties".

It finds this file correctly if run through a main in sbt but not in a unit test.  This problem does not exist in 0.12.0. 

java version "1.7.0_21"
Java(TM) SE Runtime Environment (build 1.7.0_21-b11)
Java HotSpot(TM) 64-Bit Server VM (build 23.21-b01, mixed mode)

``` scala
import javax.xml.transform.TransformerFactory
import javax.xml.transform.stream.{StreamResult, StreamSource}
import java.io.{OutputStream, ByteArrayInputStream}
import java.nio.charset.StandardCharsets
import org.scalatest.Suite

class Xalan extends Suite {

  def testResource() {
    val factory = TransformerFactory.newInstance()
    val transformer = factory.newTransformer(xsltSource)

    transformer.transform(xmlSource, new StreamResult(nullOutputStream))
  }

  def xsltSource = stringToSource(xsltString)
  def xmlSource = stringToSource(xmlString)

  def nullOutputStream = new OutputStream {
    def write(b: Int) {}
  }

  private def stringToSource(string: String) =
    new StreamSource(new ByteArrayInputStream(string.getBytes(StandardCharsets.UTF_8)))

  private val xmlString  = "<test>boo</test>"
  private val xsltString = "<xsl:stylesheet version=\"1.0\" xmlns:xsl=\"http://www.w3.org/1999/XSL/Transform\" />"

}
```

**Comment by harrah** [comment]
On both Java 7 and Java 8, this gives me the error "Premature end of file.", which presumably is due to `xsltString` being empty.  Please use StackOverflow for questions and if a bug is identified, this issue can be reopened.  Thanks!
