### ISSUE TITLE
update-classifiers does not download the sources of all dependencies

### ISSUE THREAD

**Issue by sblask** [sbt/sbt#872]
I've got a project with several dependencies, a few of them have been developed in house. Building them works fine, but update-classifiers does only ever download sources and javadoc for one of these dependencies. The others are downloaded if I specify withSources() and withJavadoc() in build.sbt for them. However, they are still no included when using sbteclipse. As it does not work without withSources() and withJavadoc(), I assume this to be an sbt and not sbteclipse issue. There is no error in the sbt console and setting logging to debug doesn't yield anything useful, sources are simply not downloaded. All inhouse libraries are hosted along with their sources and javadoc on a local install of Artifactory. I am not aware of any differences between the different libraries that could explain why it works for one, but not the other.

Can I do anything else to investigate this further?

**Comment by harrah** [comment]
`withSources` and `withJavadoc` are not recommended and they aren't used by the IDE plugins.  Please use StackOverflow to ask questions though.  If there is an underlying bug identified, this issue can be reopened.  Thanks!

**Comment by sblask** [comment]
I still have problems with this issue, but I do have a workaround, after having used withSources() and withJavadoc() once and then removed them from build.sbt, subsequent calls to update-classifiers do download sources and docs in case they have been updated. But only for dependencies with already downloaded sources/docs. So when new dependencies are added, withSources() and withJavadoc() have to be added once again to make it work.

**Comment by harrah** [comment]
If you can reproduce the problem with 0.13.0, that would be great.

**Comment by sblask** [comment]
We still rely on incompatible plugins, but as soon as we do the switch, I can give an update.

**Comment by harrah** [comment]
Great, thanks.  If these are public plugins, perhaps we can help update them.

**Comment by sblask** [comment]
Seems to work with 0.13, so all good :-)
