### ISSUE TITLE
Documentation error in FAQ for disabling ANSI codes (sbt.log.format=false)

### ISSUE THREAD

**Issue by emrecelikten** [sbt/sbt#873]
Hello,

Hopefully this is the right place. In sbt FAQ, it has been said that to disable ANSI codes in the output, we need to supply -Dsbt.log.format=false. 

The correct setting seems to be -Dsbt.log.noformat=true instead of the one above.

**Comment by harrah** [comment]
The FAQ is correct.  Please provide enough information to reproduce your problem, including the sbt version, expected output, actual output, etc...  See https://github.com/sbt/sbt/blob/0.13/CONTRIBUTING.md#new-issues.  Also, please use StackOverflow for questions.
