### ISSUE TITLE
Issue with multiple projects using a macro

### ISSUE THREAD

**Issue by mdedetrich** [sbt/sbt#874]
The stackoverflow question is here http://stackoverflow.com/questions/18732362/issue-with-using-macros-in-sbt

For quick reference, these are the 2 projects with the issue (just clone them)

https://github.com/mdedetrich/projectacontainingmacro
https://github.com/mdedetrich/projectb

Compile and run a `publish-local` on `projectacontainingmacro`

Load `projectb`, and `run` it, you will notice a runtime error like the following

`java.lang.IllegalAccessError: tried to access method projectbexample.Tuna$.<init>()V from class projectbexample.Fish$`

Uses scala 2.10.2 and SBT 0.13.0

**Comment by harrah** [comment]
Please do not both post a StackOverflow question and open a bug simultaneously.
