### ISSUE TITLE
javac warnings are treated as errors if errors exist

### ISSUE THREAD

**Issue by jroper** [sbt/sbt#875]
In SBT 0.13.0, enable java warnings:

```
javacOptions in (Compile, compile) += "-Xlint"
```

And add the following source file:

``` java
import java.net.URLEncoder;

public class Foo {
    public static void main(String... args) {
        URLEncoder.encode("foo");
        URLEncoder.foo("blah");
    }
}
```

It does of course, fail to compile, but the deprecation warning is reported as an error.  If you remove the compile error, it is correctly reported as a warning.

**Comment by jroper** [comment]
This probably isn't technically limited to javac, but I can't work out a way to get scalac to emit warnings when a compile error exists, I suspect it doesn't.

**Comment by jroper** [comment]
Ok, so looking at the source code, and looking at 0.12.x, I can see that it is specific to javac, and that this is the way it's always been in SBT, this is not a regression.

**Comment by jroper** [comment]
Looking into this, it appears the only way we could provide this support is to do filtering on the javac output, applying hereustics to try and work out which messages should be logged at error and which at warn.  If everything's in English, it's not too bad, match ": error: " or ": warning: ", and if the current line starts with an indent, then log it at the same level as the previous line.  But of course, javac is localised, so we'd need to know a) what language javac was running in, and b) what words javac used for "error" and "warning" in that language.

So it's probably not feasible to implement this.

**Comment by benmccann** [comment]
Hmm, this is a pretty frustrating bug. It means essentially that we can't turn on compilation warnings. Our code base has quite a few of them at the moment, so they completely overwhelm any errors. I'd like to turn on warnings, so that they get somewhat cleaned up over time. It would be nice if we at least supported English. If folks want to provide the translations for their own languages, it wouldn't hurt to accept them. It could be hard to proactively support every language, but there's no reason we couldn't support a handful and please the majority of users.

**Comment by harrah** [comment]
To confirm, @jroper's analysis is correct.  javac only sends errors/warnings to stderr, so there isn't a way to distinguish them without parsing the output.  Everything used to be logged as `[error]` until #74, which sends the output to `[warn]` if there are no errors.

**Comment by ebuchanan** [comment]
+1 this is making it nearly impossible to find errors in compilation output.  I end up having to redirect stderr to a file and manually grep it for "error", so if you could do that (at least for English) it would save me a lot of hassle.

**Comment by benmccann** [comment]
Woohoo! This is awesome! Thanks!!
