### ISSUE TITLE
`autoAPIMappings` doesn't work for libraries downloaded with 0.12

### ISSUE THREAD

**Issue by Blaisorblade** [sbt/sbt#876]
From http://stackoverflow.com/questions/18747265/sbt-scaladoc-configuration-for-the-standard-library#comment27662147_18747265:

`autoAPIMappings` works because, during resolution, SBT 0.13 knows that "info.apiURL property is important and should be made into an extra attribute" (quoting @harrah). Older SBTs (and possibly other tools?) will store that property, but not make into an extra attribute. Hence, if a library is first downloaded by SBT 0.12, the generated Ivy file will be incorrect, and `autoAPIMappings` will not pick up the documentation for that library.

This affects for instance scala-library.

All data is available at http://github.com/Blaisorblade/sbt-test-case-apiUrl, instructions to reproduce are in the last commit. And clean+update on 0.13 is no fix.

Minimal workaround: document the problem when documenting `autoAPIMappings`.

Now, Ivy files generated by older SBTs still contain m:properties__info.apiURL with the right content. Could SBT read that information without hacks (say, bypassing Ivy and passing the XML itself)?

**Comment by Blaisorblade** [comment]
To complete the summary, here's @harrah's first assessment:

> That's disappointing and will be a common problem. Only 0.13 knows that the info.apiURL property is important and should be made into an extra attribute. Clean ~/.ivy2/cache/org.scala-lang/scala-library/ivy-2.10.2.xml. Please open a bug. I'm not sure it can be worked around, but we'll see.

**Comment by harrah** [comment]
Yes, the best hope is to interpret "m:properties__info.apiURL".  Fortunately, sbt doesn't actually need to use the information during dependency resolution, so the extra attribute part is not critical.
