### ISSUE TITLE
No explanation for .scala builds.

### ISSUE THREAD

**Issue by NightRa** [sbt/sbt#878]
In the Starting Guide, in the last section, ".scala Build Definition", http://www.scala-sbt.org/0.13.0/docs/Getting-Started/Full-Def.html,
It's says just to copy the code and inspect what heppens.
It would be much more helpful to explain at least a little bit, what happens over there.
For example, what does the 'settings' value does, what's the 'root' parameter, ect.

**Comment by dwijnand** [comment]
That page no longer exists in the sbt 1.x docs. The pages in the current docs: [Build definition](https://www.scala-sbt.org/1.x/docs/Basic-Def.html), [Multi-project builds](https://www.scala-sbt.org/1.x/docs/Multi-Project.html), and [Organizing the build](https://www.scala-sbt.org/1.x/docs/Organizing-Build.html) have some more detail about various aspects of how to define a build. So I feel like this issue can be closed now.

Please let us know if you spots more gaps in explanation in docs, though!
