### ISSUE TITLE
update-sbt-classifiers should use the typesafe repo used by the launcher.

### ISSUE THREAD

**Issue by retronym** [sbt/sbt#88]
I'm (still) trying to get `gen-idea with-classifiers with-sbt-classfiers` to work.

With a nightly of SBT it's close; the last problem is that `update-classifiers` uses the resolvers from my project; rather than the resolvers from the launcher.

Can I workaround this with a scoped setting of the resolvers that would only apply for this task?

**Comment by harrah** [comment]
Yes, I know this is a problem.  No, sorry, update-sbt-classifiers doesn't scope its inputs more specifically.

**Comment by retronym** [comment]
For the interested reader, the workaround is to add the repo temporarily. For the SBT nightlies:

```
> set resolvers += Resolver.url("typesafe-snapshots") artifacts "http://repo.typesafe.com/typesafe/ivy-snapshots/[organisation]/[module]/[revision]/jars/[artifact](-[classifier]).[ext]"
[info] Reapplying settings...
[info] Set current project to default (in build file:/Users/jason/code/scratch/20110704/)
> set transitiveClassifiers := Seq("sources")
[info] Reapplying settings...
[info] Set current project to default (in build file:/Users/jason/code/scratch/20110704/)
> gen-idea with-sbt-classifiers with-classifiers  
```

This requires a fresh copy of `sbt-idea`:  https://github.com/mpeltonen/sbt-idea/pull/66

**Comment by retronym** [comment]
Closely related: `update-sbt-classifiers` is run with:

```moduleSettings = InlineConfiguration(default:default$sbt_2.9.0-1:0.1,List(org.scala-tools.sbt:sbt_2.8.1:0.10.1-20110703-052058),,List(),None,Some(IvyScala(2.9.0-1,List(),true,true,true)),false)

```

where `2.9.0-1` is the project scala version. 

This results in the wrong scala version in the update report.
```

**Comment by ijuma** [comment]
Mark, if you want to download the Scala sources for the _project_, is update-classifiers enough? I was under the impression that update-sbt-classifiers was necessary because of http://code.google.com/p/simple-build-tool/issues/detail?id=112#c6 but it seems like it isn't according to retronym.

**Comment by harrah** [comment]
Yes, update-classifiers is enough because scala-library and scala-compiler are declared as normal dependencies now.

**Comment by retronym** [comment]
You said on the list that the difficulty here is passing the resolver from the launcher to the build. Does this only apply for the snapshots repo? The type safe releases repo is already hard-coded in Defaults, for use when `isSbtPlugin` is true.

**Comment by harrah** [comment]
Well, now that I think about it, the bigger issue is that you can't have multiple dependency management configurations (including different resolver sets) per subproject.
