### ISSUE TITLE
Arrow keys do not work in windows

### ISSUE THREAD

**Issue by hsn10** [sbt/sbt#880]
sbt 0.13

if you run sbt in cmd.exe console window in win xp, then using up/down arrow key to list through history in interactive sbt prompt do not works. It prints 2 characters on keypress.

**Comment by xuwei-k** [comment]
please try to `-Dinput.encoding=Cp1252` #871

**Comment by hsn10** [comment]
yes. adding this to sbt/conf/sbtconfig.txt solved issue.

**Comment by harrah** [comment]
@hsn10 Sorry for the trouble.  I spent a lot of time before the release trying to figure this out.  The workaround that @xuwei-k references is the best that can be done right now.  I believe it is ultimately a bug in JLine 2.x (previous sbt versions used 1.x), but have not come up with a patch for it yet.  If you are able to use cygwin and a non-cmd.exe terminal, that environment should work fine.
