### ISSUE TITLE
Broken documentation links in 0.13.0 docs.

### ISSUE THREAD

**Issue by metasim** [sbt/sbt#881]
1. Line 213 of http://www.scala-sbt.org/release/docs/Detailed-Topics/Scripts
   
   `http://www.scala-sbt.org/release/sxr/IvyConsole.scala.html`
2. Line 106 of http://www.scala-sbt.org/release/docs/Detailed-Topics/Testing.html
   
   `http://scalatest.org/`
3. Line 200 of http://www.scala-sbt.org/release/docs/Detailed-Topics/Forking.html
   
   `http://www.scala-sbt.org/release/api/sbt/Fork$.ForkJava.html`
4. Line 222 of http://www.scala-sbt.org/release/docs/Detailed-Topics/Forking.html
   
   `http://www.scala-sbt.org/release/api/sbt/Fork$.ForkScala.html`

**Comment by xuwei-k** [comment]
duplicate? #863

**Comment by harrah** [comment]
@metasim thanks for reporting.  The sxr link (the first link) is a duplicate of #863 as @xuwei-k indicates.  The ScalaTest link works for me.  The other two I fixed in the linked commit.
