### ISSUE TITLE
Sbt adds colour codes even when output is redirected

### ISSUE THREAD

**Issue by squid-lee** [sbt/sbt#888]
If you run something like 'sbt test', but pipe it into a file, the colour tags used for colouring text in the shell are not removed.

**Comment by xuwei-k** [comment]
`-Dsbt.log.noformat=true`
http://www.scala-sbt.org/0.13.0/docs/Detailed-Topics/Command-Line-Reference.html#command-line-options

**Comment by squid-lee** [comment]
I don't want to disable colour, I want sbt to be sensible enough to disable it when I'm piping its output somewhere, as for example grep does.

**Comment by harrah** [comment]
The expected behavior is reasonable, but please specify enough information to reproduce.  See https://github.com/sbt/sbt/blob/0.13/CONTRIBUTING.md.

**Comment by squid-lee** [comment]
Apologies for a crappy bug report. To reproduce, run some sbt command like 'test' which produces coloured output. 
Do not use the repl, and redirect the output in to a text file e.g 'sbt test > /tmp/testOutput'. 
/tmp/testOutput will now contain the escape codes normaly used for colouring text in the shell as well as the expected output of 'sbt test'.

**Comment by harrah** [comment]
Thanks for the update.  I kind of expected you to say you were on windows, but I've reproduced on linux.  sbt gets its information from JLine and JLine shows the same behavior in its example application.

**Comment by SethTisue** [comment]
+1 on an eventual fix — remembering the noformat syntax sends me running to Google every time.

this relates to #840, in a "play nice in the Unix world" kind of way

**Comment by eed3si9n** [comment]
Recently closed similar issue https://github.com/sbt/sbt/issues/4284. Here's what I wrote:

> It sounds like a good idea, but sbt also runs on CI environments like Travis and Jenkins. I don't know exactly how the implementation looks like, but it might look something like `sbt compile | tee compile.log`. It would be sad if CI logs then became no colors, because they seem to support colors.

**Comment by cchandurkar** [comment]
Is there any solution for this? Maybe add a flag to not include colors? How do you pipe it and remove those color codes ?

**Comment by Blaisorblade** [comment]
@cchandurkar Here's the flag:
https://github.com/sbt/sbt/issues/888#issuecomment-25168402
