### ISSUE TITLE
scripted tests should not need to reference the plugin version

### ISSUE THREAD

**Issue by randomstatistic** [sbt/sbt#894]
sbt developers don't feel any pain here, because the sbt version _is_ the "plugin" version in question.
Other plugin authors have to resort to jumping through hoops though. Manually revving the version reference in each scripted test every time they rev their plugin version is the most common, but that's error prone and laborious. At least one project I've seen programmatically creates files that include their plugin in their test directories as part of the build.sbt, which is much better, but not something every plugin author should have to hand-roll.

All scripted-based tests should automatically include the current, just-published version of the plugin. Perhaps drop a file as part of the temp-dir setup.

**Comment by jozic** [comment]
+1
as a workaround you can use `"latest.integration"` as plugin revision

**Comment by harrah** [comment]
Please do not ask questions or start discussions in the issue tracker as described in [CONTRIBUTING](https://github.com/sbt/sbt/blob/0.13/CONTRIBUTING.md).  Use the mailing list [sbt-dev] for proposals/discussions or StackOverflow for questions.  This particular problem is covered in @eed3si9n's answer to this question: http://stackoverflow.com/questions/19102208/how-to-test-sbt-plugins.
