### ISSUE TITLE
clean-all

### ISSUE THREAD

**Issue by greenrd** [sbt/sbt#896]
From the old Google Code issue tracker:

We need a way to clean all generated, downloaded, compiled, or otherwise derived artifacts.

http://stackoverflow.com/questions/4483230/an-easy-way-to-get-rid-of-anything-generated-by-sbt

**Comment by evantill** [comment]
:+1: for example in maven a clean will clean all target directories

**Comment by harrah** [comment]
This has been discussed on the mailing list before with the same conclusion as the linked StackOverflow question.  If you really want a clean cache, boot directory, and workspace, you don't need to rely on the build tool's clean.  You probably are already using build slaves that are based on an image: start them up from a fresh image instead.  Particular obstacles to the request functionality are that deleting jars from under a running jvm will crash the jvm.  Please feel free to rediscuss on [sbt-dev], however, and we can reopen if that is the outcome.

@evantill not sure what you mean- `clean` on a project cleans that project's `target/` directory.  If you want to clean multiple projects, use aggregation, like for any other task.

**Comment by evantill** [comment]
@harrah on a simple sbt build of "my-project" the directories are

my-project/
  -- build.sbt
  -- src/
  -- target/
  -- project/
        --  build.properties
        --  SomeOtherCoolStuff.scala
        -- target/

How to clean with one command my-project/target and my-project/project/target ?
Is aggregation a solution ?

**Comment by jsuereth** [comment]
Try  `reboot full` on the comamnd line to reload even the build files.   The reason why is that the clean task is _defined_ in the classes in project/target, which is defined using classes in project/project/target.   The only way to truly clean house is to reboot full, which can break other running sbt instances, since jar files will disappear from the filesystem.

I'd recommend trying out `reboot full`.  It can work quite well for me, although it's not needed quite as often these days.

**Comment by harrah** [comment]
`reboot full` doesn't clean `project/target/`.  It clears the boot directory only, although that can trigger some selective cleaning of `project/target`.  As @jsuereth and I said, `clean` cannot delete the jars that define the classes with the code that is running `clean`, so it cannot delete `target/`.  In general, this is not needed anyway  If you need a fresh CI checkout, just do a fresh clone on a new workspace.  If there is a new use case, please describe it.

A bug tracker is a poor discussion forum.  Please use [sbt-dev] for further discussion.

**Comment by delitescere** [comment]
Sorry, despite all the interesting things sbt does, I can't reconcile what happens with the `clean` command. If the "build tool" _generates stuff_, then its "clean" needs to _clean that stuff_.

`sbt` is a not-insubstantial series of scripts that happen, at the end of hundreds of lines of shell code, to execute a Java program. There is nothing odd about it handling a `clean` command by also issuing shell commands to remove those directories when the Java app can't / shouldn't.

Given we probably shouldn't just delete any directory named `target` and it should only be the directories created by `sbt`, a protocol can be established between the Java app and its shell script to do this properly. That protocol need only be the presence of a marker file (created and populated by the Java app when `clean` is the command) of paths to be removed after the Java app has completed (you are no longer doing an `exec java`, so post-Java actions are possible, and in fact done in the case of cygwin). The paths present in that marker file, along with the marker file itself, can be removed by the script. For example:

``` bash
test -r ./project/target/.sbtclean && for p in $(cat ./project/target/.sbtclean); do rm -rf $p; done
```

Whatever the solution, this current situation of a "clean" command potentially __generating_ hundreds more files in an actually clean directory_ is not useful (starting before any sbt command has been run, in a project with a few components in sub-directories):

``` bash
$ find . | wc -l
     169
$ sbt clean
[info] Loading project definition from /x/project
[info] Updating {file:/x/project/}x-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 2 Scala sources to /x/project/target/scala-2.10/sbt-0.13/classes...
[warn] there were 1 deprecation warning(s); re-run with -deprecation for details
[warn] one warning found
[info] Set current project to x (in build file:/x/playing-microservices/)
[success] Total time: 0 s, completed 14/01/2016 9:45:34 PM
$ find . | wc -l
     600
$ find . -name target | wc -l
      11
$ sbt clean
[info] Loading project definition from /x/project
[info] Set current project to x (in build file:/x/)
[success] Total time: 0 s, completed 14/01/2016 9:46:04 PM
$ find . -name '*' | wc -l
     600
$ find . -name target | xargs rm -rf
$ find . | wc -l
     169
$
```

**Comment by SethTisue** [comment]
`git clean` ftw

**Comment by delitescere** [comment]
No, `git clean` is not appropriate. I don't need git to make sbt work.

**Comment by NicolasRouquette** [comment]
How about this?

```
clean
reload plugins
clean
exit
```

**Comment by singhalkanika198** [comment]
Resolving jline#jline;2.11 ...
I am getting this error and it is being paused here for about an hour...

**Comment by nhooey** [comment]
@harrah Where is the discussion in [`sbt-dev`](https://groups.google.com/forum/#!forum/sbt-dev) that you're referring to?

**Comment by dwijnand** [comment]
He wasn't referring to a specific discussion in sbt-dev. Just that it should be discussed there rather than here.

**Comment by nhooey** [comment]
@dwijnand: It looks like @harrah was referring to a specific discussion in `sbt-dev`, based on what he said:

> This has been discussed on the mailing list before with the same conclusion as the linked StackOverflow question.

**Comment by dwijnand** [comment]
Ah sorry. No idea, couldn't find anything.

**Comment by lssilva** [comment]
It seems SBT has side effect :)

**Comment by shea-hawkins** [comment]
@harrah what a narrow-minded and frankly misunderstood view of this problem. We're asking for a clean that cleans "all generated, downloaded, compiled, or otherwise derived artifacts". I'm not sure what images have to do with anything.

**Comment by eed3si9n** [comment]
@shea-hawkins 

> what a narrow-minded and frankly misunderstood view of this problem. We're asking for a clean that cleans "all generated, downloaded, compiled, or otherwise derived artifacts". I'm not sure what images have to do with anything.

This is a reminder that all communication under GitHub sbt/sbt is covered under Scala Code of Conduct - https://www.scala-lang.org/conduct/

At-mentioning a comment from 2013 with this comment is simultaneously abusive and misses the point of the original comment. `sbt`-the-script invokes a launcher, which automatically resolves sbt artifacts under boot. The build would trigger resolution of plugins and libraries via Couriser. If we take the "all generated, downloaded, compiled, or otherwise derived artifacts" at face value, this will involve wiping out various cache directories not directly maintained by sbt.

If anyone else wants to discuss more into deeper cleaning, feel free to start a thread under https://github.com/sbt/sbt/discussions
