### ISSUE TITLE
ansiCodeSupported not propagated through logger wrappers

### ISSUE THREAD

**Issue by retronym** [sbt/sbt#90]
Hard coded to true, should come from the delegate:

https://github.com/harrah/xsbt/blob/v0.10.0/testing/TestReportListener.scala#L73

Inherited false, should come from the delegate:

https://github.com/harrah/xsbt/blob/v0.10.0/util/log/BufferedLogger.scala#L16

**Comment by ijuma** [comment]
Probably best to use links to the the 0.10 branch instead of 0.10.0 tag:

https://github.com/harrah/xsbt/blob/0.10/testing/TestReportListener.scala#L73
https://github.com/harrah/xsbt/blob/0.10/util/log/BufferedLogger.scala#L16

**Comment by retronym** [comment]
Doesn't BufferedLogger also need to be changed?
