### ISSUE TITLE
Allow running of single junit test

### ISSUE THREAD

**Issue by benmccann** [sbt/sbt#911]
I'm often frustrated that I cannot run a single unit test method. sbt's test-only will let you run a single junit class, but not a single junit method.

It's possible to run a single junit method in the other JVM build systems that I've used. E.g.
[mvn -Dtest=TestCircle#xyz test](http://stackoverflow.com/questions/1873995/run-a-single-test-method-with-maven)
[grails test-app -unit YourController.testSomething](http://stackoverflow.com/questions/3680272/can-i-run-a-single-unit-test-from-the-command-line-for-a-grails-project)
## related
- [ScalaTest in sbt: is there a way to run a single test without tags?](http://stackoverflow.com/questions/11159953)
- [Run just a specific scalatest test from sbt](http://stackoverflow.com/questions/22205484)

**Comment by SamJoan** [comment]
:+1:

**Comment by wsargent** [comment]
This can be done, but it is implementation specific to the test framework, i.e. from http://etorreborre.github.io/specs2/guide/org.specs2.guide.Runners.html

```
test-only *SomeClass* -- -ex my shiny spec
```

**Comment by SamJoan** [comment]
Don't really understand :P maybe we should include like a default spec that runs only the test that is specified on the parameters?

sorry, should've added a noob warning :P

**Comment by harrah** [comment]
Everything following the `--` is passed to the test framework (in this case, specs2) as arguments.  These are interpreted by the test framework.  The link in @wsargent's comment describes how specs2 interprets them.  In this case, it provides a way to specify a specific test.

The general enhancement of running a single test "natively" via sbt syntax was one reason for the new test interface that went into 0.13.0.  ScalaTest 2.0 will support this new interface (not sure about specs2, ScalaCheck, or junit), but the actual syntax and support in `testOnly` for running a single test was deferred to 0.13.1.

I think there was a more recent discussion than this, but this is one thread discussing it:
https://groups.google.com/d/msg/simple-build-tool/816bxcVfRuU/rCMnpuSLMUYJ

**Comment by benmccann** [comment]
@harrah you mentioned a few months ago that an enhancement of running a single test "natively" via sbt syntax was deferred to 0.13.1. was that released in 0.13.1 and can this bug be closed? or has it since been deferred to a later release?

**Comment by harrah** [comment]
Deferred.  (You can see the target milestone at the top.)

**Comment by samuelgruetter** [comment]
:+1:

**Comment by dwijnand** [comment]
This is already possible:
- See https://github.com/sbt/junit-interface/issues/36#issuecomment-31817126
- and see `--tests` in https://github.com/sbt/junit-interface/blob/0.11/README.md

**Comment by DanielGGordon** [comment]
What about running testOnly when **not** in the sbt shell? I haven't been able to get this to work - even for a class.

**Comment by DanielGGordon** [comment]
I believe I just had my quotes wrong, but this works for me: `sbt testOnly com.my.class..`
