### ISSUE TITLE
"not found: value InputWrapper" when using the value of a setting

### ISSUE THREAD

**Issue by etorreborre** [sbt/sbt#914]
In a `build.scala` file, I have:

``` scala
lazy val scalazVersion = 
  SettingKey[String]("scalazVersion", 
                     "defines the current scalaz version")

lazy val core = Project(id = "core",
    base = file("core"),
    settings = Defaults.defaultSettings).dependsOn(
       "org.scalaz" %% "scalaz-core"       % scalazVersion.value,
       "org.scalaz" %% "scalaz-concurrent" % scalazVersion.value)
```

This fails to compile with `not found: value InputWrapper` which I guess comes from a macro implementation.

**Comment by harrah** [comment]
Thanks for the test case.  This should of course provide a better error message, but note that `dependsOn` is just for depending on other internal Projects and not external binary dependencies.  Those use `libraryDependencies += ...`.   I'm not sure why scalac gives this error message yet (InputWrapper is on the classpath), but the expected error message is something like "'value' can only be used in `:=`, `+=`, `++=`, or `Def.setting`".

**Comment by etorreborre** [comment]
> but note that dependsOn is just for depending on other internal Projects and not external binary dependencies

Yes, I realized that very shortly after I tried to use `dependsOn` this way. I was [driven by](https://groups.google.com/forum/#!topic/scala-melb/AvFg2uvDevI):

``` scala
lazy val XylemCore = project.in(file("."))
    .dependsOn(util % "test->test;compile->compile")
    .aggregate(util)
```

I just reported this because I thought that the compiler message was not very helpful. The one you propose would be much better!

**Comment by harrah** [comment]
Yes, I definitely appreciate the report.  You can see the expected, existing error message by using `.value` pretty much anywhere else it isn't allowed.  For example, `def x = scalazVersion.value`.  For some reason (perhaps an implicit search, the repeated parameters, or something else I haven't isolated yet), scalac fails internally with the reported message in this specific case.

**Comment by harrah** [comment]
This is a Scala bug, covered by https://issues.scala-lang.org/browse/SI-7519.  At least, @retronym's fix also fixes this.
