### ISSUE TITLE
Search on 'scala-sbt.org' produces inconsistent results

### ISSUE THREAD

**Issue by cdow** [sbt/sbt#916]
I believe that the `scala-sbt.org` is not fully indexed by google.  As a result, searches on this site frequently are missing results.  For example, if I do a search for `input tasks` from the home page go to a google search page for `input tasks site:http://www.scala-sbt.org/0.13.0/docs/`. I would expect to get a link to `http://www.scala-sbt.org/0.13.0/docs/Extending/Input-Tasks.html` but I only get 4 results and it doesn't include that page. However, if I change the google search to `input tasks site:http://www.scala-sbt.org`, I get `http://www.scala-sbt.org/release/docs/Extending/Input-Tasks.html` as the top result.

This might be solved by adding a site map to the site.  Or maybe it is just as simple as asking Google to re-index the site.  Someone with access to Google Webmaster Tools might be able to get a clearer picture.  As a stop-gap measure, it might be better to put the search site to `http://www.scala-sbt.org` on all pages rather than a version specific site.

**Comment by harrah** [comment]
Main part of interest is the sitemap entry configuration: https://github.com/sbt/sbt/commit/d6ca66d406489f26b30b63f4fd2340a5f27815a4#diff-170be026a5135129106da5a2647fb963R113

**Comment by cdow** [comment]
Thanks!
