### ISSUE TITLE
Provide standard task to list transient dependencies

### ISSUE THREAD

**Issue by justjoheinz** [sbt/sbt#920]
When using play, there is a standard task to list all transient dependencies for a project together with the information of the which dependency pulled the other one.

This is extremely useful when trying to debug "errors" which sbt 0.13.0 introduced since it better checks the versioning of scala jars.

Please make the play task available to sbt by default.

**Comment by eed3si9n** [comment]
I like this idea. Along with eviction warning, we should consider this as standard feature.

**Comment by SethTisue** [comment]
assuming “transitive” was meant (not “transient”), this has been done for a while now, yes?

**Comment by eed3si9n** [comment]
Yea closed it as done
