### ISSUE TITLE
Modules were resolved with conflicting cross-version suffixes (databinder dispatch)

### ISSUE THREAD

**Issue by Sciss** [sbt/sbt#929]
I have done a fresh clone of the repository. Trying to build, I get the following error:

```
[error] Modules were resolved with conflicting cross-version suffixes in {file:/Users/hhrutz/Documents/devel/sbt/project/}sbt-build:
[error]    net.databinder:dispatch-core _2.9.1, _2.10
[error]    net.databinder:dispatch-http _2.9.1, _2.10
[error]    net.databinder:dispatch-futures _2.9.1, _2.10
java.lang.RuntimeException: Conflicting cross-version suffixes in: net.databinder:dispatch-core, net.databinder:dispatch-http, net.databinder:dispatch-futures
```

**Comment by harrah** [comment]
No one else has reported this and there is CI run on every commit and nightly.  It is likely something specific with your setup.  Please use StackOverflow for questions: https://github.com/sbt/sbt/blob/0.13/CONTRIBUTING.md.  If there is an actual issue, this can be reopened.

**Comment by Sciss** [comment]
Well, I don't have a specific setup. I did a fresh clone and ran `sbt compile` where sbt = standard sbt 0.13.0 install. Whatever.
