### ISSUE TITLE
Documentation for Adding Local Maven Repo Incorrect

### ISSUE THREAD

**Issue by ghost** [sbt/sbt#93]
The documentation in Library-Management on the wiki states that this is the way to add the local Maven repository:

resolvers += "Local Maven Repository" at "file://"+Path.userHome+"/.m2/repository"

However, this produces the following kinds of paths:

file://sbt.RichFile@6469adc7/.m2/repository/com/

Apparently Path.userHome needs to be stringified differently.

Related question: Is there a way to interactively explore what's in the scope of build.sbt in a Scala console?

**Comment by harrah** [comment]
Library-Management says to use Path.userHome.absolutePath as far as I can see.

For questions, please use the mailing list:
http://groups.google.com/group/simple-build-tool/topics
