### ISSUE TITLE
Merge AnalysisFormats into InternedAnalysisFormats

### ISSUE THREAD

**Issue by benjyw** [sbt/sbt#934]
AnalysisFormats is deprecated, and going away entirely in 0.14. Its replacement, InternedAnalysisFormats, uses some definitions from AnalysisFormat. Those definitions must be copied over to InternedAnalysisFormats prior to deleting AnalysisFormats.

**Comment by dwijnand** [comment]
Done in https://github.com/sbt/zinc/pull/6
