### ISSUE TITLE
Failed compilation in case of dependsOn/RootProject w/ crossScalaVersions if scalaVersion is marked for a different version

### ISSUE THREAD

**Issue by sandys** [sbt/sbt#938]
I'm trying to pull Casbah (https://github.com/mongodb/casbah/blob/master/project/CasbahBuild.scala) in my project as a dependency. My build.scala is here https://gist.github.com/sandys/7169065

When I try to build my project, it fails with "[warn]   ::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: unresolved dependency: org.mongodb#casbah_2.9.2;2.7.0-SNAPSHOT: not found"

When I change the compiler version in MY build.scala to 2.10.3 (matching that of Casbah), it builds successfully. 

Is this intended ? As far as I can see, Casbah is marked with crossScalaVersions to support 2.9.2 .

**Comment by harrah** [comment]
Please use StackOverflow for questions.  See https://github.com/sbt/sbt/blob/0.13/CONTRIBUTING.md.
