### ISSUE TITLE
scripted task hangs if the configuration of a test project has errors

### ISSUE THREAD

**Issue by cdietze** [sbt/sbt#94]
Original post to group: https://groups.google.com/forum/#!topic/simple-build-tool/QoMH-hYDZzk

Steps to reproduce:

```
git clone git://github.com/thunderklaus/sbt-gwt-plugin.git
cd sbt-gwt-plugin
```

The following works (takes a while though):

```
sbt scripted 
```

Now, if we make the scripted project fail, the scripted task hangs endlessly after the line "Running plugintest / hello"

```
echo "nonsense" >> .\src\sbt-test\plugintest\hello\project\plugins\build.sbt
sbt scripted 
```

A guess is that this makes the forked process wait for user input. Running the test project directly from .\src\sbt-test\plugintest\hello results in:

```
"nonsense"
^
[error] Error parsing expression.
Project loading failed: (r)etry, (q)uit, or (i)gnore?
```

**Comment by harrah** [comment]
Just running `sbt scripted` the first time, I get:

```
[info] [info] Compiling 5 Java sources to /private/var/folders/np/npLyZ2bhEbOIXGMWBc6zPU+++TM/-Tmp-/sbt_6316221d/hello/target/scala-2.8.1.final/classes...
[info] [info] Compiling 1 GWT module: net/thunderklaus/hello_gwt_sbt/Hello_gwt_sbt
[error] Exception in thread "main" java.lang.NoClassDefFoundError: com/google/gwt/dev/Compiler
[error] Caused by: java.lang.ClassNotFoundException: com.google.gwt.dev.Compiler
```

**Comment by cdietze** [comment]
Alright, I installed Linux and found out that I had some Windows specific stuff in my code. That's fixed now. Thanks for pointing that out.

I tried to reproduce this bug with Linux and found that it works. So it looks like a windows specific issue.

The guess mentioned above might not be correct, since under Linux I get the question as well when I run the test directly: `Project loading failed: (r)etry, (q)uit, or (i)gnore?`.

**Comment by cdietze** [comment]
I accidentally closed the issue earlier... :)

I just made an interesting observation:

```
Running plugintest / hello
```

This is where the process hangs. Then I killed just the forked java process and got the following output:

```
[info] [info] Set current project to default (in build file:/C:/Users/christoph/.sbt/plugins/)
[error] C:\Users\christoph\AppData\Local\Temp\sbt_a0e7c5f\hello\project\plugins\build.sbt:8: error: eof expected but ';' found.
[error] "nonsense"
[error] ^
[info] [error] Error parsing expression.
[info] Project loading failed: (r)etry, (q)uit, or (i)gnore?
[error] x plugintest / hello
[error] Incomplete tasks (run 'last <task>' for the full log):
[error]   {file:/C:/workspace3/git/sbt-gwt-plugin/}default/*:scripted: Remote sbt initialization failed
[error] Total time: 21 s, completed 13.07.2011 00:00:10
C:\workspace3\git\sbt-gwt-plugin>
```

So maybe waiting for user input has to do with it after all.

**Comment by harrah** [comment]
```
module not found: com.github.siasia#xsbt-web-plugin_2.8.1;0.1.0-0.10.2-SNAPSHOT
```

Can you either change it to be a git repository dependency or otherwise make it work from scratch?

**Comment by cdietze** [comment]
I ran into some trouble making it into a git dependency, at first sight that might be windows related as well. I will investigate that later. For this issue I created a isolated much simpler example:

```
git clone git://github.com/thunderklaus/sbt-test.git
cd sbt-test\test1-scripted-hangs
sbt scripted
```

The above stuff works, the stuff below hangs.

```
echo "nonsense" > src\sbt-test\testgroup\test1\build.sbt
sbt scripted
```

**Comment by harrah** [comment]
Ok, it ran, but didn't hang on unix.  I'll have to find a windows machine.

**Comment by vigdorchik** [comment]
For me on a Windows machine the last sample doesn't hang, but displays
nonsense
^
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

Subsequent input is correctly processed, so I don't see the problem with sbt here.

**Comment by vigdorchik** [comment]
I should also mention that I added build.prperties files with
sbt.version=0.11.2
