### ISSUE TITLE
reasonable argument parsing missing

### ISSUE THREAD

**Issue by tvw** [sbt/sbt#942]
I installed sbt manually as explained in the docs.

What I at least expect from a command line tool I don't know, is:

that it responds to

  $ sbt -help

and 

  $ sbt -version

and that it evaluates the arguments it gets and dies with an error message, when they are not reasonable.

What I do not expect: that it downloads and creates files no matter what the input was and that it does not inform me about the files it created and where it puts them and that is swallows arguments just like that without some further messages.

Disclaimer: I am a scala beginner and sbt newbe ;-)

**Comment by eed3si9n** [comment]
I don't know if the situation has improved much, but we do print out -help and -version now.
