### ISSUE TITLE
Add option preserveExecutable to IO.copyFile and IO.copyDirectory

### ISSUE THREAD

**Issue by ngocdaothanh** [sbt/sbt#944]
As I understand correctly, they have option `preserveLastModified`, but no `preserveExecutable`.

I can modify and send a pull request if you want. Please let me know.

Use case:

I am creating this SBT plugin:
https://github.com/ngocdaothanh/xitrum-package

For example, it allows users to copy `bin/start.sh` to `target/xitrum/bin/start.sh`. But because there's no `preserveExecutable` option, the copied `start.sh` will not be execute.

**Comment by harrah** [comment]
Yes, that would be great, thanks.  I thought there was already an issue open for this, but I couldn't find it.  Please make sure it is source compatible.  To get into 0.13.x, it would also have to be binary compatible, but that is up to you.

**Comment by ngocdaothanh** [comment]
Please review my pull request.
preserveExecutable is true by default.
I guess it's not binary compatible?

**Comment by harrah** [comment]
Merged in 1e61b9acf34b7d89a54a5adc021cc37cd3ecd0ef.  Thanks!
