### ISSUE TITLE
generated pom contains platform specific linefeed, resulting in SHA1 mismatches

### ISSUE THREAD

**Issue by cdietze** [sbt/sbt#95]
I stumbled across this problem when a sbt project was pulling some dependency from my remote maven repository and produced an error like this: "somepom.xml invalid sha1: expected=123 computed=456". However, I just published that library...

The problem seems to be with platform specific linefeeds:
- sbt publish-local creates a pom.xml that contains CR LF after the first line (<?xml ...) (all other linefeeds in the file are plain LF)
- When downloading that file via http (in my case from thunderklaus.github.com/maven/...), all linefeeds are LF, thus the SHA1 numbers do not match
## A quick workaround

is to call the following in the sbt console before producing the pom.xml. This sets the separator to be used by BufferedWriter.newLine().

```
eval System.setProperty("line.separator", "\n")
```
## To reproduce:

```
git clone git://github.com/thunderklaus/sbt-gwt-plugin.git
cd sbt-gwt-plugin
sbt publish-local
```

Will produce .ivy2\local\net.thunderklaus\sbt-gwt-plugin_2.8.1\1.0-SNAPSHOT\poms\sbt-gwt-plugin_2.8.1.pom .
That pom file will contain a CR LF after the first line when using windows and (supposingly - haven't tried it) just a LF when using linux or mac. Also, the accompanying file sbt-gwt-plugin_2.8.1.pom.sha1 will contain different values.
## Possible Patch

 I tried this locally and it produces the desired LF.

```
diff --git a/ivy/MakePom.scala b/ivy/MakePom.scala
index 9a20e11..45d4b04 100644
--- a/ivy/MakePom.scala
+++ b/ivy/MakePom.scala
@@ -29,8 +29,7 @@ class MakePom
                val out = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(output), encoding))
                try
                {
-                       out.write("<?xml version='1.0' encoding='" + encoding + "'?>")
-                       out.newLine()
+                       out.write("<?xml version='1.0' encoding='" + encoding + "'?>\n")
                        out.write(xmlString)
                }
                finally { out.close() }
```

**Comment by harrah** [comment]
That looks like a good assessment to me.  The root problem is probably that PrettyPrinter hard codes \n instead of the platform separator.  I expect that something is normalizing the line endings somewhere.  Out of curiosity, are you using a repository manager or anything?

**Comment by cdietze** [comment]
I am not using a repository manager. I publish to my local maven repo which is a git repo, from which I push to my github page (thunderklaus.github.com).
I justed cloned that repository and the linefeeds in that pom is CR LF. When I download it with wget, they are LF.
Maybe it's actually git that is normalizing the new lines.

**Comment by harrah** [comment]
Yes, it is probably git.
