### ISSUE TITLE
SBT hangs when running tests

### ISSUE THREAD

**Issue by saeta** [sbt/sbt#964]
If there are enough projects in a multi-project build, running `sbt test` will hang forever. Please see the following sample project: http://betacs.pro/testcase.tgz

SBT Version: 0.13.0
System: Mac OS X (10.8.5) 16GB memory.

``` bash
saeta@betacspro ~% cat ~/.sbtconfig
SBT_OPTS="-XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=1G -Xmx2g"
```

**Comment by harrah** [comment]
It is likely that you are running into #937, which is mitigated in 0.13.1-RC2.  If that doesn't fix the issue, this can be reopened.
