### ISSUE TITLE
Formatting problem in docs

### ISSUE THREAD

**Issue by Blaisorblade** [sbt/sbt#970]
`|release|` should be 0.13.0 in the text below from the [docs](http://www.scala-sbt.org/release/docs/Getting-Started/Hello.html#setting-the-sbt-version), but for some reason it isn't:

> You can force a particular version of sbt by creating a file hello/project/build.properties. In this file, write:
> 
> ```
> sbt.version=|release|
> ```
> 
> to force the use of sbt 0.13.0. sbt is 99% source compatible from release to release. Still, setting the sbt version in project/build.properties avoids any potential confusion.

What's strange is that in the [sources](https://raw.github.com/sbt/sbt/0.13.0/src/sphinx/Getting-Started/Hello.rst), `|release|` appears twice and is substituted only once (in the text, but not in the code block); but above, `|scalaRelease|` is correctly formatted, even though it appears in a code block.

The offending source was introduced by
https://github.com/sbt/sbt/commit/c14179c358ad1177a5f89eecd629922bdb4b2f3e#diff-3e84e04dc4c79f9b2d9e85bc4c0d4d6eR84, but I cannot see anything obviously wrong with the code.

**Comment by harrah** [comment]
Thanks a lot for pointing it out.  The problem was due to a quirk in the substitution syntax that requires the previous character to be alphanumeric or a space.
