### ISSUE TITLE
The "Generating files" HOWTO is broken for 0.13.0

### ISSUE THREAD

**Issue by Blaisorblade** [sbt/sbt#971]
According to http://www.scala-sbt.org/0.13.0/docs/Howto/generatefiles.html:

> ``` scala
> sourceGenerators in Compile += <your Task[Seq[File]] here>
> ```

But this simply doesn't work. It's obvious why when comparing with [the 0.12.4 version](http://www.scala-sbt.org/0.12.4/docs/Howto/generatefiles.html), which gives:

> ``` scala
> sourceGenerators in Compile <+= <your Task[Seq[File]] here>
> ```

Now, that's just _not_ the kind of change which happened between 0.12 and 0.13. _Edit_: I spoke a bit too soon; you can replace <+= with += if the type on the right changes, and loses the `Initialize` part, but it's not the case here, probably because it's a setting containing a task.

This is visible in the example. Example given for 0.12.4:

> ``` scala
> sourceGenerators in Compile <+= sourceManaged in Compile map { dir =>
>   val file = dir / "demo" / "Test.scala"
>   IO.write(file, """object Test extends App { println("Hi") }""")
>   Seq(file)
> }
> ```

Example given for 0.13.0, but non-working:

> ``` scala
> sourceGenerators in Compile += Def.task {
>   val file = (sourceManaged in Compile).value / "demo" / "Test.scala"
>   IO.write(file, """object Test extends App { println("Hi") }""")
>   Seq(file)
> }
> ```

After replacing `+=` with `<+=`, we get a example that works:

``` scala
sourceGenerators in Compile <+= Def.task {
  val file = (sourceManaged in Compile).value / "demo" / "Test.scala"
  IO.write(file, """object Test extends App { println("Hi") }""")
  Seq(file)
}
```

Error from the given 0.13.0 code (not very self-explanatory, I'd say):

```
> reload
[info] Loading project definition from /Users/pgiarrusso/Documents/Research/PhD/Teaching/SLE2013/public-material-repo/lectures/sbt-sample/project
/Users/pgiarrusso/Documents/Research/PhD/Teaching/SLE2013/public-material-repo/lectures/sbt-sample/build.sbt:8: error: No implicit for Append.Value[Seq[sbt.Task[Seq[java.io.File]]], sbt.std.FullInstance.M[Seq[java.io.File]]] found,
  so sbt.std.FullInstance.M[Seq[java.io.File]] cannot be appended to Seq[sbt.Task[Seq[java.io.File]]]
sourceGenerators in Compile += Def.task {
                            ^
[error] Type error in expression
```

I'd open a further bug saying "example code in documentation is not tested", but I don't know if you'd care and/or if the technology for fixing it exists.

**Comment by Blaisorblade** [comment]
This was introduced in:
https://github.com/sbt/sbt/commit/132e29415ba9a47771720c74eae772b2952d810c#diff-1600cb100cbc40b8d0237585c4cd625d

**Comment by Blaisorblade** [comment]
The above fix uses <+= which is not currently explained by the docs.

I also tried using value; however, the problem is that while I need to convert an `Initialize[Task[T]]` to a `Task[T]`, .value will go all the way down to `T`, thanks to overloading resolution (see from `Def.scala`):

``` scala
  implicit def macroValueI[T](in: Initialize[T]): MacroValue[T] = ???
  implicit def macroValueIT[T](in: Initialize[Task[T]]): MacroValue[T] = ???
```

I guess I could disambiguate the call by invoking the implicit explicitly, but the implicit name is not part of the documented API, so it does not sound like a good idea. However, an ascription on the return value does not work:

``` scala
sourceGenerators in Compile <+= Def.task {
  val file = (sourceManaged in Compile).value / "demo" / "Test.scala"
  IO.write(file, """object Test extends App { println("Hi") }""")
  Seq(file)
}

//Works
sourceGenerators in Compile += (Def.macroValueI(Def.task {
  val file = (sourceManaged in Compile).value / "demo" / "Test.scala"
  IO.write(file, """object Test extends App { println("Hi") }""")
  Seq(file)
}).value: Task[Seq[File]])

//Also works
sourceGenerators in Compile += (Def.macroValueI(Def.task {
  val file = (sourceManaged in Compile).value / "demo" / "Test.scala"
  IO.write(file, """object Test extends App { println("Hi") }""")
  Seq(file)
}).value)
//Doesn't work.
/*sourceGenerators in Compile += ((Def.task {
  val file = (sourceManaged in Compile).value / "demo" / "Test.scala"
  IO.write(file, """object Test extends App { println("Hi") }""")
  Seq(file)
}).value: Task[Seq[File]])
 */
```

**Comment by harrah** [comment]
Your analysis is correct and sorry for the trouble.  The underlying bug is #866.

**Comment by Blaisorblade** [comment]
Thanks for the prompt fix!

**Comment by harrah** [comment]
No problem.  It will be a bit delayed getting pushed to the site due to being in an RC cycle.
