### ISSUE TITLE
RFE: sbt should not try to parse every file that ends with .sbt

### ISSUE THREAD

**Issue by josephks** [sbt/sbt#98]
```
java.io.FileNotFoundException: /<snip>/.#props.sbt (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:120)
```

The problem here is that .#props.sbt is a symlink created by emacs (for locking purposes I think) and does not point to a real file.

RFE: sbt should ignore files that end in .sbt if they begin with a dot.

I think what needs to be changed is  configurationSources() in Build.scala.  I tried to fix it myself with variations of

```
    def configurationSources(base: File): Seq[File] = (base *   (GlobFilter("*.sbt") - GlobFilter("^\\.*"))) get
```

 but couldn't get it to work.

Side note: having to wait 7.5 minutes for "sbt build-all" whenever you make a minor change to the sbt source makes it really hard to test your changes.

**Comment by harrah** [comment]
I use hidden .sbt files for permissions.  I think that lock file goes away when you save the main file.

**Comment by harrah** [comment]
GlobFilter is a simple glob pattern where `*` is interpreted as a wildcard.  It is not supposed to be a full regex.  So, ".*" should be the pattern you want.  If that doesn't work, it is probably a bug.

**Comment by harrah** [comment]
There is no need to run build-all, which builds documentation as well.

'publish-all' is sufficient if you have not modified the launcher.
