### ISSUE TITLE
scripted test and sbt-launch.jar version

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt#986]
here example
https://github.com/xuwei-k/sbt-scripted-test-and-launcher-version
https://travis-ci.org/xuwei-k/sbt-scripted-test-and-launcher-version/builds/14061652

`0.12.3 sbt-launch.jar` and `sbt.version=0.12.3` in `build.properties` is success

but `0.13.0 sbt-launch.jar` and `sbt.version=0.12.3` in `build.properties` is failure `java.lang.ClassNotFoundException: jline.Terminal`

**Comment by dwijnand** [comment]
rip sbt 0.12
