### ISSUE TITLE
.parsed and pattern matching assignment - fails to compile

### ISSUE THREAD

**Issue by mighdoll** [sbt/sbt#994]
this fails to compile:
 // `parsed` can only be used within an input task macro, such as := or Def.inputTask.  

```
 = Def.inputTask {
     val HostsAndArgs(hostsSeq, args) = hostsAndArgs.parsed
```

this compiles:

```
 = Def.inputTask {
     val parseResult = hostsAndArgs.parsed
     val HostsAndArgs(hostsSeq, args) = parseResult
```

(on 0.13.1-RC2)

Not a big issue, but it'd be nice to tweak the error messaging if not actually fix.

**Comment by harrah** [comment]
Related to #952.
